{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dinersClub"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardbrand\/dinersclub"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardbrand\/dinersclub"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/dinersClub","interfaceLanguage":"swift"},"abstract":[{"text":"Diners Club card","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPCardBrandDinersClub"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPCardBrand@STPCardBrandDinersClub","modules":[{"name":"StripePayments"}],"title":"STPCardBrand.dinersClub","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dinersClub","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"title":"STPCardBrand","url":"\/documentation\/stripepayments\/stpcardbrand","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardBrand","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/dinersClub":{"type":"topic","abstract":[{"type":"text","text":"Diners Club card"}],"navigatorTitle":[{"text":"STPCardBrandDinersClub","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/dinersClub","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand\/dinersclub","title":"STPCardBrand.dinersClub","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"dinersClub","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPCardBrandDinersClub"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardBrandDinersClub"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPCardBrandDinersClub"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","value":"STPCardBrand","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"kind":"identifier","text":"STPCardBrand"}]},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1dinersClub\/title","value":"STPCardBrandDinersClub","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardBrandDinersClub"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1dinersClub\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}