{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/JCB","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"]]},"kind":"symbol","abstract":[{"text":"JCB card","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JCB"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardbrand\/jcb"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardbrand\/jcb"]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"title":"STPCardBrand.JCB","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JCB"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPCardBrand@STPCardBrandJCB","navigatorTitle":[{"kind":"identifier","text":"STPCardBrandJCB"}],"roleHeading":"Case"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/JCB":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"JCB","kind":"identifier"}],"abstract":[{"type":"text","text":"JCB card"}],"kind":"symbol","navigatorTitle":[{"text":"STPCardBrandJCB","kind":"identifier"}],"title":"STPCardBrand.JCB","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/JCB","url":"\/documentation\/stripepayments\/stpcardbrand\/jcb","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardBrand"}],"navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand","title":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPCardBrandJCB"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPCardBrandJCB","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPCardBrandJCB"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1JCB\/title","value":"STPCardBrandJCB","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1JCB\/fragments","value":[{"text":"STPCardBrandJCB","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","value":"STPCardBrand","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"text":"STPCardBrand","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}