{"abstract":[{"text":"Mastercard card","type":"text"}],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mastercard"}],"externalID":"c:@M@StripePayments@E@STPCardBrand@STPCardBrandMastercard","navigatorTitle":[{"kind":"identifier","text":"STPCardBrandMastercard"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"case","title":"STPCardBrand.mastercard"},"variants":[{"paths":["\/documentation\/stripepayments\/stpcardbrand\/mastercard"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardbrand\/mastercard"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mastercard"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/mastercard","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/mastercard":{"title":"STPCardBrand.mastercard","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mastercard","kind":"identifier"}],"abstract":[{"text":"Mastercard card","type":"text"}],"url":"\/documentation\/stripepayments\/stpcardbrand\/mastercard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/mastercard","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardBrandMastercard"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"title":"STPCardBrand","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCardBrand","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","url":"\/documentation\/stripepayments\/stpcardbrand","navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPCardBrandMastercard","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPCardBrandMastercard"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPCardBrandMastercard"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1mastercard\/title","value":"STPCardBrandMastercard"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1mastercard\/fragments","value":[{"kind":"identifier","text":"STPCardBrandMastercard"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","op":"replace","value":"STPCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"text":"STPCardBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","value":[{"text":"STPCardBrand","kind":"identifier"}]}]}]}