{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"]]},"abstract":[{"type":"text","text":"UnionPay card"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"STPCardBrandUnionPay","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"roleHeading":"Case","title":"STPCardBrand.unionPay","externalID":"c:@M@StripePayments@E@STPCardBrand@STPCardBrandUnionPay","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unionPay"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unionPay","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardbrand\/unionpay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardbrand\/unionpay"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/unionPay","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"type":"topic","kind":"symbol","title":"STPCardBrand","role":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardBrand"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/unionPay":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unionPay","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardBrandUnionPay","kind":"identifier"}],"title":"STPCardBrand.unionPay","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/unionPay","url":"\/documentation\/stripepayments\/stpcardbrand\/unionpay","abstract":[{"text":"UnionPay card","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPCardBrandUnionPay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPCardBrandUnionPay"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPCardBrandUnionPay","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","value":"STPCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"text":"STPCardBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardBrand"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1unionPay\/title","value":"STPCardBrandUnionPay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1unionPay\/fragments","value":[{"kind":"identifier","text":"STPCardBrandUnionPay"}]}]}]}