{"metadata":{"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPCardBrand@STPCardBrandVisa","modules":[{"name":"StripePayments"}],"title":"STPCardBrand.visa","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"visa","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardBrandVisa","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardbrand\/visa"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardbrand\/visa"]}],"abstract":[{"type":"text","text":"Visa card"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/visa"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"visa"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/visa":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/visa","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"visa","kind":"identifier"}],"type":"topic","title":"STPCardBrand.visa","url":"\/documentation\/stripepayments\/stpcardbrand\/visa","kind":"symbol","abstract":[{"type":"text","text":"Visa card"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardBrandVisa"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardBrand"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"type":"topic","title":"STPCardBrand","url":"\/documentation\/stripepayments\/stpcardbrand","role":"symbol","abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"STPCardBrandVisa","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPCardBrandVisa","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPCardBrandVisa","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1visa\/title","value":"STPCardBrandVisa"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1visa\/fragments","value":[{"text":"STPCardBrandVisa","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","value":"STPCardBrand","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"text":"STPCardBrand","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle"}]}]}