{"metadata":{"modules":[{"name":"StripePayments"}],"title":"description","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL(py)description","roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionredirecttourl\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionredirecttourl\/description"]}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/description","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionRedirectToURL"}],"title":"STPIntentActionRedirectToURL","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to another page or application."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentActionRedirectToURL"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL","url":"\/documentation\/stripepayments\/stpintentactionredirecttourl","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionRedirectToURL"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/description","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","title":"description","url":"\/documentation\/stripepayments\/stpintentactionredirecttourl\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/title","op":"replace","value":"STPIntentActionRedirectToURL"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionRedirectToURL"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/navigatorTitle","op":"replace","value":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}]}]}