{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/autocompletecountries"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/autocompleteCountries","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Property","externalID":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV21autocompleteCountriesSaySSGvp","title":"autocompleteCountries","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocompleteCountries"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"modules":[{"name":"StripePaymentSheet"}],"symbolKind":"property"},"abstract":[{"text":"A list of two-letter country codes that support autocomplete","type":"text"},{"type":"text","text":" "},{"text":"Defaults to a list of countries that Stripe has audited to ensure a good autocomplete experience.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autocompleteCountries"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]}]}],"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/autocompleteCountries":{"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/autocompletecountries","kind":"symbol","abstract":[{"type":"text","text":"A list of two-letter country codes that support autocomplete"},{"text":" ","type":"text"},{"text":"Defaults to a list of countries that Stripe has audited to ensure a good autocomplete experience.","type":"text"}],"type":"topic","title":"autocompleteCountries","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"autocompleteCountries"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/autocompleteCountries","role":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct","title":"AddressViewController.Configuration","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct","abstract":[{"text":"Configuration for an ","type":"text"},{"type":"codeVoice","code":"AddressViewController"},{"text":" instance.","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","title":"StripePaymentSheet","abstract":[{"type":"text","text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app."}],"url":"\/documentation\/stripepaymentsheet","type":"topic","role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"abstract":[{"text":"A view controller that collects a name and an address, with full localization and autocomplete.","type":"text"}],"kind":"symbol","title":"AddressViewController","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AddressViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","op":"replace","value":"STPAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","value":[{"text":"STPAddressViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle","value":[{"text":"STPAddressViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}