{"abstract":[{"text":"Initializes a Configuration","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"defaultValues"},{"kind":"text","text":": "},{"text":"DefaultAddressDetails","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/DefaultAddressDetails","kind":"typeIdentifier","preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV07DefaultD7DetailsV"},{"text":" = .init(), ","kind":"text"},{"text":"additionalFields","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AddressViewController","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentSheet@objc(cs)STPAddressViewController"},{"text":".","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV16AdditionalFieldsV","kind":"typeIdentifier","text":"AdditionalFields","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/AdditionalFields-swift.struct"},{"text":" = .init(), ","kind":"text"},{"text":"allowedCountries","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"] = [], "},{"text":"appearance","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PaymentSheet","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet","preciseIdentifier":"s:18StripePaymentSheet0bC0C","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:18StripePaymentSheet0bC0C10AppearanceV","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet\/Appearance","text":"Appearance","kind":"typeIdentifier"},{"kind":"text","text":" = PaymentSheet.Appearance.default, "},{"kind":"externalParam","text":"buttonTitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/init(defaultvalues:additionalfields:allowedcountries:appearance:buttontitle:title:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"StripePaymentSheet"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"defaultValues","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DefaultAddressDetails","preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV07DefaultD7DetailsV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"additionalFields"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePaymentSheet@objc(cs)STPAddressViewController","text":"AddressViewController","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":"."},{"text":"AdditionalFields","kind":"typeIdentifier","preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV16AdditionalFieldsV"},{"kind":"text","text":", "},{"text":"allowedCountries","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"appearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:18StripePaymentSheet0bC0C","text":"PaymentSheet"},{"text":".","kind":"text"},{"text":"Appearance","kind":"typeIdentifier","preciseIdentifier":"s:18StripePaymentSheet0bC0C10AppearanceV"},{"kind":"text","text":", "},{"text":"buttonTitle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"title":"init(defaultValues:additionalFields:allowedCountries:appearance:buttonTitle:title:)","externalID":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV13defaultValues16additionalFields16allowedCountries10appearance11buttonTitle5titleA2E07DefaultD7DetailsV_AE010AdditionalK0VSaySSGAA0bC0C10AppearanceVSSSgAUtcfc","roleHeading":"Initializer","symbolKind":"init","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/init(defaultValues:additionalFields:allowedCountries:appearance:buttonTitle:title:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/PaymentSheet":{"navigatorTitle":[{"kind":"identifier","text":"PaymentSheet"}],"title":"PaymentSheet","role":"symbol","abstract":[{"text":"A drop-in class that presents a sheet for a customer to complete their payment","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSheet"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet","kind":"symbol","url":"\/documentation\/stripepaymentsheet\/paymentsheet"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"abstract":[{"type":"text","text":"A view controller that collects a name and an address, with full localization and autocomplete."}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","role":"symbol","navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddressViewController","kind":"identifier"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","kind":"symbol","title":"AddressViewController","type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/init(defaultValues:additionalFields:allowedCountries:appearance:buttonTitle:title:)":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/init(defaultValues:additionalFields:allowedCountries:appearance:buttonTitle:title:)","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Initializes a Configuration"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/init(defaultvalues:additionalfields:allowedcountries:appearance:buttontitle:title:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"defaultValues"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV07DefaultD7DetailsV","kind":"typeIdentifier","text":"DefaultAddressDetails"},{"text":", ","kind":"text"},{"text":"additionalFields","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentSheet@objc(cs)STPAddressViewController","text":"AddressViewController","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV16AdditionalFieldsV","text":"AdditionalFields"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"allowedCountries"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"appearance","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:18StripePaymentSheet0bC0C","text":"PaymentSheet","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:18StripePaymentSheet0bC0C10AppearanceV","text":"Appearance","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"buttonTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"title":"init(defaultValues:additionalFields:allowedCountries:appearance:buttonTitle:title:)"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/PaymentSheet/Appearance":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet\/Appearance","kind":"symbol","url":"\/documentation\/stripepaymentsheet\/paymentsheet\/appearance","type":"topic","abstract":[{"type":"text","text":"Describes the appearance of PaymentSheet"}],"role":"symbol","title":"PaymentSheet.Appearance","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"navigatorTitle":[{"text":"Appearance","kind":"identifier"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/DefaultAddressDetails":{"abstract":[{"text":"Default values for the fields collected by ","type":"text"},{"type":"codeVoice","code":"AddressViewController"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DefaultAddressDetails","kind":"identifier"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/defaultaddressdetails","title":"AddressViewController.Configuration.DefaultAddressDetails","navigatorTitle":[{"kind":"identifier","text":"DefaultAddressDetails"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/DefaultAddressDetails","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"abstract":[{"text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app.","type":"text"}],"title":"StripePaymentSheet","role":"collection","url":"\/documentation\/stripepaymentsheet","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/AdditionalFields-swift.struct":{"navigatorTitle":[{"text":"AdditionalFields","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/AdditionalFields-swift.struct","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Configuration related to the collection of additional fields beyond the physical address.","type":"text"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/additionalfields-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdditionalFields"}],"title":"AddressViewController.Configuration.AdditionalFields"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct":{"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct","type":"topic","abstract":[{"type":"text","text":"Configuration for an "},{"code":"AddressViewController","type":"codeVoice"},{"text":" instance.","type":"text"}],"title":"AddressViewController.Configuration","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","value":"STPAddressViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAddressViewController"}]},{"op":"replace","value":[{"text":"STPAddressViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}