{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSunbitParams\/init","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodsunbitparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSunbitParams"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"method","roleHeading":"Instance Method","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodSunbitParams(im)init"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSunbitParams":{"type":"topic","title":"STPPaymentMethodSunbitParams","url":"\/documentation\/stripepayments\/stppaymentmethodsunbitparams","abstract":[{"text":"An object representing parameters used to create a Sunbit Payment Method","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSunbitParams","navigatorTitle":[{"text":"STPPaymentMethodSunbitParams","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodSunbitParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSunbitParams/init":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSunbitParams\/init","role":"symbol","kind":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodsunbitparams\/init","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSunbitParams\/title","value":"STPPaymentMethodSunbitParams"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodSunbitParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSunbitParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSunbitParams\/navigatorTitle","value":[{"text":"STPPaymentMethodSunbitParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}