{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/created"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/created"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"title":"created","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:14StripePayments20STPConfirmationTokenC7created10Foundation4DateVvp","modules":[{"name":"StripePayments"}]},"abstract":[{"text":"Time at which the object was created. Measured in seconds since the Unix epoch.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":" { get }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","url":"\/documentation\/stripepayments\/stpconfirmationtoken","abstract":[{"text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments.","type":"text"}],"title":"STPConfirmationToken","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/created":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/created","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/created","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"title":"created","abstract":[{"type":"text","text":"Time at which the object was created. Measured in seconds since the Unix epoch."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title","value":"STPConfirmationToken","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments","value":[{"text":"STPConfirmationToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle","value":[{"kind":"identifier","text":"STPConfirmationToken"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}