{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"STPAPIResponseDecodable.decodedObject(fromAPIResponse:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPConfirmationToken(cm)decodedObjectFromAPIResponse:","title":"decodedObject(fromAPIResponse:)","modules":[{"name":"StripePayments"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"abstract":[{"type":"text","text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","type":"topic","title":"STPConfirmationToken","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtoken","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/decodedObject(fromAPIResponse:)":{"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"title":"decodedObject(fromAPIResponse:)","abstract":[],"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/decodedobject(fromapiresponse:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/decodedObject(fromAPIResponse:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title","value":"STPConfirmationToken"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments","value":[{"text":"STPConfirmationToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle","value":[{"text":"STPConfirmationToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}