{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/expiresAt","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/expiresat"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:14StripePayments20STPConfirmationTokenC9expiresAt10Foundation4DateVSgvp","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"title":"expiresAt"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken"]]},"abstract":[{"text":"Time at which this ConfirmationToken expires and can no longer be used to confirm a PaymentIntent or SetupIntent.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"? { get }","kind":"text"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtoken","abstract":[{"type":"text","text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","role":"symbol","title":"STPConfirmationToken","navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/expiresAt":{"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/expiresat","type":"topic","kind":"symbol","abstract":[{"text":"Time at which this ConfirmationToken expires and can no longer be used to confirm a PaymentIntent or SetupIntent.","type":"text"}],"role":"symbol","title":"expiresAt","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/expiresAt"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPConfirmationToken","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPConfirmationToken"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConfirmationToken"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}