{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/liveMode"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/livemode"]}],"metadata":{"symbolKind":"property","externalID":"s:14StripePayments20STPConfirmationTokenC8liveModeSbvp","title":"liveMode","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"StripePayments"}],"role":"symbol"},"abstract":[{"code":"true","type":"codeVoice"},{"text":" if the object exists in live mode or the value ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if the object exists in test mode.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"liveMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { get }"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/liveMode":{"role":"symbol","abstract":[{"code":"true","type":"codeVoice"},{"text":" if the object exists in live mode or the value ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if the object exists in test mode.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/livemode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/liveMode","type":"topic","title":"liveMode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}],"kind":"symbol","title":"STPConfirmationToken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","role":"symbol","navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmationtoken","abstract":[{"text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPConfirmationToken","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title"},{"value":[{"kind":"identifier","text":"STPConfirmationToken"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments"},{"value":[{"kind":"identifier","text":"STPConfirmationToken"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle"}]}]}