{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodPreview","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPreview","text":"STPPaymentMethodPreview","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/paymentMethodPreview"},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/paymentmethodpreview"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Non-PII preview of payment details captured by the Payment Element.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken"]]},"metadata":{"externalID":"s:14StripePayments20STPConfirmationTokenC20paymentMethodPreviewAA010STPPaymentfG0CSgvp","title":"paymentMethodPreview","role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodPreview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodPreview","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPreview"},{"kind":"text","text":"?"}],"symbolKind":"property"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"title":"STPConfirmationToken","abstract":[{"text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtoken"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview":{"navigatorTitle":[{"text":"STPPaymentMethodPreview","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Preview of payment method details captured by the ConfirmationToken."}],"role":"symbol","title":"STPPaymentMethodPreview","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview","url":"\/documentation\/stripepayments\/stppaymentmethodpreview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPreview","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/paymentMethodPreview":{"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/paymentmethodpreview","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Non-PII preview of payment details captured by the Payment Element."}],"title":"paymentMethodPreview","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodPreview"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPreview","kind":"typeIdentifier","text":"STPPaymentMethodPreview"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/paymentMethodPreview","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title","value":"STPConfirmationToken","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments","value":[{"text":"STPConfirmationToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle","value":[{"kind":"identifier","text":"STPConfirmationToken"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/title","value":"STPPaymentMethodPreview","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/fragments","value":[{"text":"STPPaymentMethodPreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/navigatorTitle","value":[{"text":"STPPaymentMethodPreview","kind":"identifier"}],"op":"replace"}]}]}