{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/setupFutureUsage","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","externalID":"s:14StripePayments20STPConfirmationTokenC16setupFutureUsageAA021STPPaymentIntentSetupfG0OSgvp","title":"setupFutureUsage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupFutureUsage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentSetupFutureUsage","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/setupfutureusage"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Indicates intent to reuse the payment method."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"abstract":[{"type":"text","text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments."}],"kind":"symbol","navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"title":"STPConfirmationToken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtoken"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","abstract":[{"text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes.","type":"text"},{"text":" ","type":"text"},{"text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"title":"STPPaymentIntentSetupFutureUsage","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/setupFutureUsage":{"abstract":[{"text":"Indicates intent to reuse the payment method.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/setupFutureUsage","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage"},{"text":"?","kind":"text"}],"title":"setupFutureUsage","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/setupfutureusage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPConfirmationToken","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPConfirmationToken"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPConfirmationToken"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle","op":"replace"},{"value":"STPPaymentIntentSetupFutureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","op":"replace"}]}]}