{"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/shipping"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails","text":"STPPaymentIntentShippingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"title":"shipping","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentShippingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"s:14StripePayments20STPConfirmationTokenC8shippingAA31STPPaymentIntentShippingDetailsCSgvp","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"text":"Shipping information collected on this token.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/shipping"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/shipping":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/shipping","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/shipping","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentShippingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails"},{"kind":"text","text":"?"}],"title":"shipping","abstract":[{"text":"Shipping information collected on this token.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"url":"\/documentation\/stripepayments\/stpconfirmationtoken","kind":"symbol","abstract":[{"type":"text","text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPConfirmationToken"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmationToken"}],"type":"topic","title":"STPConfirmationToken"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetails":{"url":"\/documentation\/stripepayments\/stppaymentintentshippingdetails","type":"topic","title":"STPPaymentIntentShippingDetails","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetails","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentShippingDetails"}],"abstract":[{"text":"Shipping information for a PaymentIntent","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPPaymentIntentShippingDetails","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You should only use one that is part of an existing ","type":"text"},{"code":"STPPaymentMethod","type":"codeVoice"},{"text":" object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPConfirmationToken","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title"},{"op":"replace","value":[{"text":"STPConfirmationToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConfirmationToken"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle"},{"op":"replace","value":"STPPaymentIntentShippingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/title"},{"op":"replace","value":[{"text":"STPPaymentIntentShippingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/fragments"},{"op":"replace","value":[{"text":"STPPaymentIntentShippingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/navigatorTitle"}]}]}