{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/stripeId"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripeId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { get }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"StripePayments"}],"externalID":"s:14StripePayments20STPConfirmationTokenC8stripeIdSSvp","title":"stripeId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripeId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Unique identifier for the object (e.g. "},{"code":"ctoken_...","type":"codeVoice"},{"type":"text","text":")."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtoken\/stripeid"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}],"abstract":[{"text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments.","type":"text"}],"title":"STPConfirmationToken","url":"\/documentation\/stripepayments\/stpconfirmationtoken"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/stripeId":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/stripeId","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/stripeid","kind":"symbol","title":"stripeId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripeId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Unique identifier for the object (e.g. "},{"code":"ctoken_...","type":"codeVoice"},{"type":"text","text":")."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title","value":"STPConfirmationToken"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments","value":[{"text":"STPConfirmationToken","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle","value":[{"text":"STPConfirmationToken","kind":"identifier"}]}]}]}