{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"weChatAppURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpsourcewechatpaydetails\/wechatappurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcewechatpaydetails\/wechatappurl"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/weChatAppURL","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A URL to the WeChat App."},{"type":"text","text":" "},{"type":"text","text":"Use "},{"code":"STPRedirectContext","type":"codeVoice"},{"type":"text","text":" instead of redirecting users yourself."}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatAppURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"weChatAppURL","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"weChatAppURL"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceWeChatPayDetails(py)weChatAppURL","role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceWeChatPayDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSourceWeChatPayDetails","kind":"identifier"}],"title":"STPSourceWeChatPayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails","url":"\/documentation\/stripepayments\/stpsourcewechatpaydetails","type":"topic","abstract":[{"type":"text","text":"Details of a WeChat Pay Source."}],"navigatorTitle":[{"text":"STPSourceWeChatPayDetails","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceWeChatPayDetails/weChatAppURL":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/weChatAppURL","url":"\/documentation\/stripepayments\/stpsourcewechatpaydetails\/wechatappurl","title":"weChatAppURL","navigatorTitle":[{"kind":"identifier","text":"weChatAppURL"}],"type":"topic","role":"symbol","abstract":[{"text":"A URL to the WeChat App.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Use "},{"type":"codeVoice","code":"STPRedirectContext"},{"type":"text","text":" instead of redirecting users yourself."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatAppURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"weChatAppURL","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"weChatAppURL","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"weChatAppURL"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"STPSourceWeChatPayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/fragments","value":[{"text":"STPSourceWeChatPayDetails","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPSourceWeChatPayDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/navigatorTitle"},{"value":"weChatAppURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1weChatAppURL\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1weChatAppURL\/fragments","value":[{"text":"weChatAppURL","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}