#!/bin/bash

git stash
git checkout gh-pages

rm -rf docs

./jazzy/bin/jazzy \
  --config .jazzy.yaml \
  --output "docs"

git add docs
git commit -m 'autogenerated documentation'
git push
git checkout -
git stash pop
