#!/bin/bash

# setup_simulator_xcode_26.sh
# Automatically finds or creates an iPhone 12 mini with iOS 16.4 for testing
# Caches the result to .stripe-ios-config for reuse

set -e

CONFIG_FILE=".stripe-ios-config"
DEVICE_TYPE_IDENTIFIER="com.apple.CoreSimulator.SimDeviceType.iPhone-12-mini"
RUNTIME_IDENTIFIER="com.apple.CoreSimulator.SimRuntime.iOS-16-4"
SIMULATOR_NAME="iPhone 12 mini (Stripe)"

# Function to clear cache
clear_cache() {
    if [ -f "$CONFIG_FILE" ]; then
        rm "$CONFIG_FILE"
    fi
}

# Function to find existing simulator
find_existing_simulator() {
    xcrun simctl list devices --json | ruby -rjson -e '
        document = JSON.parse(STDIN.read)
        devices = document.dig("devices", ARGV[0]) || []
        device = devices.find do |candidate|
          candidate["isAvailable"] && candidate["deviceTypeIdentifier"] == ARGV[1]
        end
        puts device["udid"] if device
    ' "$RUNTIME_IDENTIFIER" "$DEVICE_TYPE_IDENTIFIER"
}

# Function to validate UUID format
validate_uuid() {
    local uuid="$1"
    [[ "$uuid" =~ ^[A-F0-9]{8}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{12}$ ]]
}

# Function to create new simulator
create_simulator() {
    xcrun simctl create "$SIMULATOR_NAME" "$DEVICE_TYPE_IDENTIFIER" "$RUNTIME_IDENTIFIER"
}

# Function to validate simulator exists
validate_simulator() {
    local device_id="$1"

    xcrun simctl list devices --json | ruby -rjson -e '
        document = JSON.parse(STDIN.read)
        devices = document.dig("devices", ARGV[0]) || []
        valid = devices.any? do |device|
          device["udid"] == ARGV[1] &&
            device["isAvailable"] &&
            device["deviceTypeIdentifier"] == ARGV[2]
        end
        exit(valid ? 0 : 1)
    ' "$RUNTIME_IDENTIFIER" "$device_id" "$DEVICE_TYPE_IDENTIFIER"
}

# Main logic
main() {
    local device_id

    # Handle --clear-cache flag
    if [ "$1" = "--clear-cache" ]; then
        clear_cache
        return 0
    fi

    # Check if cached config exists and is valid
    if [ -f "$CONFIG_FILE" ]; then
        # shellcheck source=/dev/null
        source "$CONFIG_FILE"

        # Validate cached ID has correct format and simulator still exists
        if [ -n "$DEVICE_ID_FROM_USER_SETTINGS" ] && validate_uuid "$DEVICE_ID_FROM_USER_SETTINGS" && validate_simulator "$DEVICE_ID_FROM_USER_SETTINGS"; then
            # Config is valid, export it
            export DEVICE_ID_FROM_USER_SETTINGS
            return 0
        else
            # Invalid or stale cache, clear it
            clear_cache
        fi
    fi

    # Look for existing simulator
    device_id="$(find_existing_simulator)"

    if [ -z "$device_id" ]; then
        device_id="$(create_simulator)"
        if [ -z "$device_id" ]; then
            echo "Error: Failed to create simulator" >&2
            return 1
        fi
    fi

    # Validate the device ID before caching
    if ! validate_uuid "$device_id"; then
        echo "Error: Extracted device ID '$device_id' is not a valid UUID" >&2
        return 1
    fi

    # Save to config file as a proper shell script
    cat > "$CONFIG_FILE" << EOF
# Auto-generated by setup_simulator.sh
# This file is sourced to set up the simulator device ID
export DEVICE_ID_FROM_USER_SETTINGS="$device_id"
EOF

    # Export for current session
    export DEVICE_ID_FROM_USER_SETTINGS="$device_id"
}

# Show usage if requested
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "Usage: source ci_scripts/setup_simulator.sh [--clear-cache] [--help]"
    echo ""
    echo "For Xcode 26 and earlier, finds or creates an iPhone 12 mini with iOS 16.4."
    echo "Caches the result to .stripe-ios-config for reuse."
    echo ""
    echo "Options:"
    echo "  --clear-cache    Clear the cached simulator ID"
    echo "  --help, -h       Show this help message"
    echo ""
    echo "Usage:"
    echo "  source ci_scripts/setup_simulator.sh"
    echo "  xcodebuild [...] -destination \"id=\$DEVICE_ID_FROM_USER_SETTINGS,arch=arm64\" [...]"
    echo ""
    echo "The script exports DEVICE_ID_FROM_USER_SETTINGS to your environment."
else
    main "$@"
fi
