{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"internalParam","text":"lhs"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/!=(_:_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/Equatable-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/!=(_:_:)","interfaceLanguage":"swift"},"metadata":{"title":"!=(_:_:)","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"StripePayments"}],"roleHeading":"Operator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType","symbolKind":"op"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/!=(_:_:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/!=(_:_:)","title":"!=(_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/!=(_:_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/equatable-implementations","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/Equatable-Implementations","kind":"article","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","role":"symbol","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPPaymentIntentLastPaymentError","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"title":"STPPaymentIntentLastPaymentErrorType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","value":"STPPaymentIntentLastPaymentErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}