{"abstract":[{"text":"An error with the Stripe API.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPPaymentIntentLastPaymentErrorTypeAPI) ","kind":"text"},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"api","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"kind":"symbol","metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType@STPPaymentIntentLastPaymentErrorTypeAPI","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeAPI","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"STPPaymentIntentLastPaymentErrorType.api","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"api"}],"symbolKind":"case","role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/api","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/api"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/api"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","title":"STPPaymentIntentLastPaymentErrorType","abstract":[{"type":"text","text":"The type of the error represented by "},{"code":"STPPaymentIntentLastPaymentError","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/api":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/api","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAPI"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"api"}],"title":"STPPaymentIntentLastPaymentErrorType.api","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/api","abstract":[{"type":"text","text":"An error with the Stripe API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentLastPaymentErrorTypeAPI"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeAPI","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAPI"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","value":"STPPaymentIntentLastPaymentErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1api\/title","value":"STPPaymentIntentLastPaymentErrorTypeAPI"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1api\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAPI"}]}]}]}