{"abstract":[{"type":"text","text":"An error connecting to Stripe’s API."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(STPPaymentIntentLastPaymentErrorTypeAPIConnection) "},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiConnection"}]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAPIConnection"}],"title":"STPPaymentIntentLastPaymentErrorType.apiConnection","roleHeading":"Case","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType@STPPaymentIntentLastPaymentErrorTypeAPIConnection","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiConnection","kind":"identifier"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/apiConnection","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/apiconnection"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/apiconnection"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/apiConnection":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/apiConnection","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/apiconnection","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"apiConnection","kind":"identifier"}],"abstract":[{"type":"text","text":"An error connecting to Stripe’s API."}],"title":"STPPaymentIntentLastPaymentErrorType.apiConnection","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAPIConnection"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"title":"STPPaymentIntentLastPaymentErrorType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","abstract":[{"text":"The type of the error represented by ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentLastPaymentError"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentIntentLastPaymentErrorTypeAPIConnection","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeAPIConnection","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAPIConnection"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentIntentLastPaymentErrorTypeAPIConnection","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1apiConnection\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1apiConnection\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAPIConnection"}]},{"value":"STPPaymentIntentLastPaymentErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","op":"replace"}]}]}
