{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"abstract":[{"text":"A failure to authenticate your customer.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/authentication"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/authentication"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/authentication","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authentication","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeAuthentication","kind":"identifier"}],"title":"STPPaymentIntentLastPaymentErrorType.authentication","externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType@STPPaymentIntentLastPaymentErrorTypeAuthentication","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authentication"}],"symbolKind":"case"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/authentication":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authentication"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/authentication","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/authentication","kind":"symbol","role":"symbol","title":"STPPaymentIntentLastPaymentErrorType.authentication","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAuthentication"}],"abstract":[{"text":"A failure to authenticate your customer.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","type":"topic","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPPaymentIntentLastPaymentError","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types.","type":"text"}],"title":"STPPaymentIntentLastPaymentErrorType","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentIntentLastPaymentErrorTypeAuthentication"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeAuthentication","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAuthentication"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1authentication\/title","op":"replace","value":"STPPaymentIntentLastPaymentErrorTypeAuthentication"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1authentication\/fragments","op":"replace","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeAuthentication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","op":"replace","value":"STPPaymentIntentLastPaymentErrorType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}