{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeCard"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType@STPPaymentIntentLastPaymentErrorTypeCard","symbolKind":"case","title":"STPPaymentIntentLastPaymentErrorType.card"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"abstract":[{"type":"text","text":"Card errors are the most common type of error you should expect to handle."},{"type":"text","text":" "},{"type":"text","text":"They result when the user enters a card that can’t be charged for some reason."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"type":"codeVoice","code":"declineCode"},{"type":"text","text":" property for the decline code.  The "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property contains a message you can show to your users."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/card"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/card"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/card"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","title":"STPPaymentIntentLastPaymentErrorType","role":"symbol","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPPaymentIntentLastPaymentError","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/card":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/card","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/card","abstract":[{"type":"text","text":"Card errors are the most common type of error you should expect to handle."},{"type":"text","text":" "},{"type":"text","text":"They result when the user enters a card that can’t be charged for some reason."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"type":"codeVoice","code":"declineCode"},{"type":"text","text":" property for the decline code.  The "},{"type":"codeVoice","code":"message"},{"type":"text","text":" property contains a message you can show to your users."}],"title":"STPPaymentIntentLastPaymentErrorType.card","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeCard"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPPaymentIntentLastPaymentErrorTypeCard","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeCard"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPPaymentIntentLastPaymentErrorTypeCard","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentIntentLastPaymentErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle","op":"replace"},{"value":"STPPaymentIntentLastPaymentErrorTypeCard","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1card\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentLastPaymentErrorTypeCard","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1card\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}