{"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/Equatable-Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"topicSections":[{"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/!=(_:_:)"],"generated":true}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/!=(_:_:)":{"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/!=(_:_:)","title":"!=(_:_:)","abstract":[],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","abstract":[{"text":"The type of the error represented by ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentLastPaymentError"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"title":"STPPaymentIntentLastPaymentErrorType"}},"variantOverrides":[{"patch":[{"value":"STPPaymentIntentLastPaymentErrorType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title"},{"value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments"},{"value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}