{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"abstract":[{"type":"text","text":"Keys for idempotent requests can only be used with the same parameters they were first used with."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/idempotency"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/idempotency"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"idempotency","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/idempotency"},"metadata":{"title":"STPPaymentIntentLastPaymentErrorType.idempotency","externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType@STPPaymentIntentLastPaymentErrorTypeIdempotency","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"idempotency"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeIdempotency"}],"roleHeading":"Case"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"type":"topic","kind":"symbol","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPPaymentIntentLastPaymentError","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"title":"STPPaymentIntentLastPaymentErrorType"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/idempotency":{"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/idempotency","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"idempotency","kind":"identifier"}],"title":"STPPaymentIntentLastPaymentErrorType.idempotency","abstract":[{"text":"Keys for idempotent requests can only be used with the same parameters they were first used with.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/idempotency","kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeIdempotency","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPPaymentIntentLastPaymentErrorTypeIdempotency","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeIdempotency"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPPaymentIntentLastPaymentErrorTypeIdempotency","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"STPPaymentIntentLastPaymentErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1idempotency\/title","value":"STPPaymentIntentLastPaymentErrorTypeIdempotency","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1idempotency\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeIdempotency"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}