{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/invalidrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/invalidrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/invalidRequest","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"STPPaymentIntentLastPaymentErrorType.invalidRequest","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType@STPPaymentIntentLastPaymentErrorTypeInvalidRequest","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidRequest","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePayments"}]},"abstract":[{"type":"text","text":"Invalid request errors.  Typically, this is because your request has invalid parameters."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"abstract":[{"text":"The type of the error represented by ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentLastPaymentError"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types."}],"title":"STPPaymentIntentLastPaymentErrorType","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/invalidRequest":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/invalidRequest","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidRequest","kind":"identifier"}],"abstract":[{"text":"Invalid request errors.  Typically, this is because your request has invalid parameters.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest","kind":"identifier"}],"title":"STPPaymentIntentLastPaymentErrorType.invalidRequest","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/invalidrequest"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"STPPaymentIntentLastPaymentErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1invalidRequest\/title","value":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1invalidRequest\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}