{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/rateLimit"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"abstract":[{"text":"Too many requests hit the API too quickly.","type":"text"}],"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType@STPPaymentIntentLastPaymentErrorTypeRateLimit","symbolKind":"case","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeRateLimit"}],"role":"symbol","title":"STPPaymentIntentLastPaymentErrorType.rateLimit","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateLimit"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateLimit"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/ratelimit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/ratelimit"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/rateLimit":{"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/ratelimit","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rateLimit","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/rateLimit","abstract":[{"text":"Too many requests hit the API too quickly.","type":"text"}],"kind":"symbol","title":"STPPaymentIntentLastPaymentErrorType.rateLimit","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeRateLimit","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","title":"STPPaymentIntentLastPaymentErrorType","role":"symbol","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPPaymentIntentLastPaymentError","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPPaymentIntentLastPaymentErrorTypeRateLimit","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeRateLimit"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeRateLimit"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentIntentLastPaymentErrorTypeRateLimit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1rateLimit\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentLastPaymentErrorTypeRateLimit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1rateLimit\/fragments","op":"replace"},{"value":"STPPaymentIntentLastPaymentErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","op":"replace"},{"value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}