{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/unknown","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeUnknown","kind":"identifier"}],"role":"symbol","title":"STPPaymentIntentLastPaymentErrorType.unknown","externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType@STPPaymentIntentLastPaymentErrorTypeUnknown","symbolKind":"case","modules":[{"name":"StripePayments"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/unknown"]}],"abstract":[{"type":"text","text":"An unknown error type."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","title":"STPPaymentIntentLastPaymentErrorType","abstract":[{"type":"text","text":"The type of the error represented by "},{"code":"STPPaymentIntentLastPaymentError","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/unknown":{"title":"STPPaymentIntentLastPaymentErrorType.unknown","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/unknown","kind":"symbol","abstract":[{"text":"An unknown error type.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/unknown","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeUnknown","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentIntentLastPaymentErrorTypeUnknown","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeUnknown"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","value":"STPPaymentIntentLastPaymentErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1unknown\/title","value":"STPPaymentIntentLastPaymentErrorTypeUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1unknown\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeUnknown"}],"op":"replace"}]}]}