{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"borderWidth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The border width of the text field. Defaults to 2."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/borderWidth","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/borderwidth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/borderwidth"]}],"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization(py)borderWidth","title":"borderWidth","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"borderWidth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"borderWidth","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/borderWidth":{"type":"topic","kind":"symbol","title":"borderWidth","abstract":[{"text":"The border width of the text field. Defaults to 2.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/borderwidth","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"borderWidth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/borderWidth","role":"symbol","navigatorTitle":[{"text":"borderWidth","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization","abstract":[{"text":"A customization object to use to configure the UI of a text field.","type":"text"}],"navigatorTitle":[{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}],"title":"STPThreeDSTextFieldCustomization","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"borderWidth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"borderWidth"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderWidth"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1borderWidth\/title","value":"borderWidth"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1borderWidth\/fragments","value":[{"text":"borderWidth","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/title","value":"STPThreeDSTextFieldCustomization"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/fragments","value":[{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}