{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/font","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/font"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/font"]}],"kind":"symbol","abstract":[{"text":"The font to use for text.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"font","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","role":"symbol","title":"font","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization(py)font","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"font","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"font"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/font":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/font","title":"font","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"font","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"font","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/font","abstract":[{"text":"The font to use for text.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization","kind":"symbol","title":"STPThreeDSTextFieldCustomization","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization","abstract":[{"text":"A customization object to use to configure the UI of a text field.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"font"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"font","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":" * "},{"kind":"identifier","text":"font"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1font\/title","op":"replace","value":"font"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1font\/fragments","op":"replace","value":[{"text":"font","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/title","op":"replace","value":"STPThreeDSTextFieldCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/fragments","op":"replace","value":[{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/navigatorTitle","op":"replace","value":[{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}]}]}]}