{"abstract":[{"text":"The appearance of the keyboard. Defaults to UIKeyboardAppearanceDefault.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/keyboardAppearance","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"keyboardAppearance"}],"modules":[{"name":"StripePayments"}],"title":"keyboardAppearance","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization(py)keyboardAppearance","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyboardAppearance"},{"text":": ","kind":"text"},{"text":"UIKeyboardAppearance","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"keyboardAppearance"},{"text":": ","kind":"text"},{"text":"UIKeyboardAppearance","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/keyboardappearance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/keyboardappearance"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization":{"abstract":[{"type":"text","text":"A customization object to use to configure the UI of a text field."}],"navigatorTitle":[{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}],"title":"STPThreeDSTextFieldCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/keyboardAppearance":{"kind":"symbol","navigatorTitle":[{"text":"keyboardAppearance","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/keyboardAppearance","type":"topic","title":"keyboardAppearance","abstract":[{"type":"text","text":"The appearance of the keyboard. Defaults to UIKeyboardAppearanceDefault."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"keyboardAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIKeyboardAppearance","preciseIdentifier":"c:@E@UIKeyboardAppearance","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/keyboardappearance","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"keyboardAppearance","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"keyboardAppearance"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance"},{"kind":"text","text":" "},{"text":"keyboardAppearance","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/title","value":"STPThreeDSTextFieldCustomization","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}]},{"op":"replace","value":[{"text":"STPThreeDSTextFieldCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1keyboardAppearance\/title","value":"keyboardAppearance","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"keyboardAppearance"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1keyboardAppearance\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}