{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/alipayhandleredirect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/alipayhandleredirect"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/alipayHandleRedirect"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipayHandleRedirect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionAlipayHandleRedirect","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionAlipayHandleRedirect","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)alipayHandleRedirect","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipayHandleRedirect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionAlipayHandleRedirect","text":"STPIntentActionAlipayHandleRedirect","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"alipayHandleRedirect","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"title":"alipayHandleRedirect"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/alipayHandleRedirect":{"url":"\/documentation\/stripepayments\/stpintentaction\/alipayhandleredirect","type":"topic","abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website.","type":"text"}],"title":"alipayHandleRedirect","navigatorTitle":[{"kind":"identifier","text":"alipayHandleRedirect"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/alipayHandleRedirect","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"alipayHandleRedirect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionAlipayHandleRedirect","kind":"typeIdentifier","text":"STPIntentActionAlipayHandleRedirect"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"kind":"symbol","abstract":[{"text":"Next action details for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" to see which one it is, and then use the related","type":"text"},{"text":" ","type":"text"},{"text":"property for the details necessary to handle it.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentAction","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentAction","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","title":"STPIntentAction","url":"\/documentation\/stripepayments\/stpintentaction"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionAlipayHandleRedirect":{"title":"STPIntentActionAlipayHandleRedirect","url":"\/documentation\/stripepayments\/stpintentactionalipayhandleredirect","role":"symbol","navigatorTitle":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}],"abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPPaymentIntentActionAlipayHandleRedirect","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"alipayHandleRedirect","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"alipayHandleRedirect"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionAlipayHandleRedirect","kind":"typeIdentifier","text":"STPIntentActionAlipayHandleRedirect","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionAlipayHandleRedirect"},{"kind":"text","text":" * "},{"kind":"identifier","text":"alipayHandleRedirect"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1alipayHandleRedirect\/title","value":"alipayHandleRedirect","op":"replace"},{"value":[{"kind":"identifier","text":"alipayHandleRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1alipayHandleRedirect\/fragments","op":"replace"},{"value":"STPIntentAction","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","op":"replace"},{"value":[{"text":"STPIntentAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","op":"replace"},{"value":[{"text":"STPIntentAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","op":"replace"},{"value":"STPIntentActionAlipayHandleRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/title","op":"replace"},{"value":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/fragments","op":"replace"},{"value":[{"text":"STPIntentActionAlipayHandleRedirect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionAlipayHandleRedirect\/navigatorTitle","op":"replace"}]}]}