{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/allResponseFields","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentaction\/allresponsefields"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/allresponsefields"]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Property","title":"allResponseFields","modules":[{"name":"StripePayments"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)allResponseFields"},"abstract":[{"type":"text","text":":nodoc:"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"abstract":[{"text":"Next action details for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is a container for the various types that are available."},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentAction","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentaction","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","navigatorTitle":[{"kind":"identifier","text":"STPIntentAction"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"kind":"symbol","role":"symbol","title":"STPIntentAction"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/allResponseFields":{"title":"allResponseFields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"url":"\/documentation\/stripepayments\/stpintentaction\/allresponsefields","kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"allResponseFields"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"text":"allResponseFields","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"STPIntentAction","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPIntentAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","op":"replace"},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1allResponseFields\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}