{"metadata":{"extendedModule":"StripePayments","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizeWithURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL","text":"STPIntentActionRedirectToURL"},{"kind":"text","text":"?"}],"externalID":"c:@CM@StripePayments@objc(cs)STPIntentAction(py)authorizeWithURL","symbolKind":"property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"authorizeWithURL"}],"title":"authorizeWithURL","platforms":[{"unavailable":false,"message":"Use `redirectToURL` instead.","beta":false,"renamed":"redirectToURL","deprecated":true}]},"kind":"symbol","abstract":[{"type":"text","text":"The details for authorizing via URL, when "},{"code":"type == STPIntentActionTypeRedirectToURL","type":"codeVoice"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use `redirectToURL` instead.","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/authorizewithurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/authorizewithurl"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authorizeWithURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL","text":"STPIntentActionRedirectToURL","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/authorizeWithURL"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"title":"STPIntentAction","url":"\/documentation\/stripepayments\/stpintentaction","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Next action details for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is a container for the various types that are available."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentAction","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/authorizeWithURL":{"abstract":[{"text":"The details for authorizing via URL, when ","type":"text"},{"code":"type == STPIntentActionTypeRedirectToURL","type":"codeVoice"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/authorizeWithURL","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizeWithURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL","text":"STPIntentActionRedirectToURL"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpintentaction\/authorizewithurl","navigatorTitle":[{"kind":"identifier","text":"authorizeWithURL"}],"title":"authorizeWithURL","role":"symbol","kind":"symbol","deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionredirecttourl","title":"STPIntentActionRedirectToURL","type":"topic","abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to another page or application.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentActionRedirectToURL","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"unavailable":false,"deprecated":true,"beta":false}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"authorizeWithURL","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"authorizeWithURL"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPIntentActionRedirectToURL","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL"},{"text":" * ","kind":"text"},{"text":"authorizeWithURL","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":[{"inlineContent":[{"text":"Use `redirectToURL` instead.","type":"text"}],"type":"paragraph"}],"path":"\/deprecationSummary"},{"op":"replace","value":"STPIntentAction","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentAction"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentAction"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle"},{"op":"replace","value":"authorizeWithURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1authorizeWithURL\/title"},{"op":"replace","value":[{"text":"authorizeWithURL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1authorizeWithURL\/fragments"},{"op":"replace","value":"STPIntentActionRedirectToURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionRedirectToURL"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/fragments"},{"op":"replace","value":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}