{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"metadata":{"title":"boletoDisplayDetails","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"boletoDisplayDetails","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPIntentActionBoletoDisplayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionBoletoDisplayDetails"},{"kind":"text","text":"?"}],"externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)boletoDisplayDetails","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"boletoDisplayDetails"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentaction\/boletodisplaydetails"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/boletodisplaydetails"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/boletoDisplayDetails","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The details for displaying Boleto voucher via URL, when ","type":"text"},{"code":"type == .boleto","type":"codeVoice"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"boletoDisplayDetails"},{"kind":"text","text":": "},{"text":"STPIntentActionBoletoDisplayDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionBoletoDisplayDetails"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/boletoDisplayDetails":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"boletoDisplayDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionBoletoDisplayDetails","kind":"typeIdentifier","text":"STPIntentActionBoletoDisplayDetails"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpintentaction\/boletodisplaydetails","type":"topic","kind":"symbol","abstract":[{"text":"The details for displaying Boleto voucher via URL, when ","type":"text"},{"code":"type == .boleto","type":"codeVoice"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/boletoDisplayDetails","navigatorTitle":[{"text":"boletoDisplayDetails","kind":"identifier"}],"title":"boletoDisplayDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails":{"kind":"symbol","abstract":[{"text":"Contains Boleto details necessary for the customer to complete the payment.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPIntentActionBoletoDisplayDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails","title":"STPIntentActionBoletoDisplayDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"abstract":[{"text":"Next action details for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is a container for the various types that are available."},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" to see which one it is, and then use the related","type":"text"},{"type":"text","text":" "},{"text":"property for the details necessary to handle it.","type":"text"},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentAction","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","title":"STPIntentAction","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentaction","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPIntentAction","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"boletoDisplayDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"boletoDisplayDetails"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"STPIntentActionBoletoDisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionBoletoDisplayDetails"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"boletoDisplayDetails"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"boletoDisplayDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1boletoDisplayDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1boletoDisplayDetails\/fragments","value":[{"text":"boletoDisplayDetails","kind":"identifier"}]},{"value":"STPIntentActionBoletoDisplayDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/fragments","value":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}]},{"op":"replace","value":[{"text":"STPIntentActionBoletoDisplayDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/navigatorTitle"},{"value":"STPIntentAction","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPIntentAction"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle"}]}]}