{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/cashAppRedirectToApp","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cashAppRedirectToApp"},{"kind":"text","text":": "},{"text":"STPIntentActionCashAppRedirectToApp","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionCashAppRedirectToApp"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"cashAppRedirectToApp","navigatorTitle":[{"text":"cashAppRedirectToApp","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cashAppRedirectToApp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionCashAppRedirectToApp","kind":"typeIdentifier","text":"STPIntentActionCashAppRedirectToApp"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)cashAppRedirectToApp"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"kind":"symbol","abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentaction\/cashappredirecttoapp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentaction\/cashappredirecttoapp"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionCashAppRedirectToApp":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionCashAppRedirectToApp"}],"title":"STPIntentActionCashAppRedirectToApp","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPIntentActionCashAppRedirectToApp","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp","kind":"symbol","abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentActionCashAppRedirectToApp","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"role":"symbol","title":"STPIntentAction","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentaction","abstract":[{"text":"Next action details for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"type":"text","text":" and "},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"This is a container for the various types that are available.","type":"text"},{"type":"text","text":" "},{"text":"Check the ","type":"text"},{"code":"type","type":"codeVoice"},{"type":"text","text":" to see which one it is, and then use the related"},{"text":" ","type":"text"},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/cashAppRedirectToApp":{"title":"cashAppRedirectToApp","abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App.","type":"text"}],"navigatorTitle":[{"text":"cashAppRedirectToApp","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cashAppRedirectToApp"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionCashAppRedirectToApp","kind":"typeIdentifier","text":"STPIntentActionCashAppRedirectToApp"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/cashAppRedirectToApp","url":"\/documentation\/stripepayments\/stpintentaction\/cashappredirecttoapp"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"cashAppRedirectToApp"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"cashAppRedirectToApp","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionCashAppRedirectToApp","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp","kind":"typeIdentifier","text":"STPIntentActionCashAppRedirectToApp"},{"text":" * ","kind":"text"},{"text":"cashAppRedirectToApp","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/title","op":"replace","value":"STPIntentActionCashAppRedirectToApp"},{"value":[{"text":"STPIntentActionCashAppRedirectToApp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/navigatorTitle","op":"replace","value":[{"text":"STPIntentActionCashAppRedirectToApp","kind":"identifier"}]},{"op":"replace","value":"STPIntentAction","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentAction"}],"op":"replace"},{"value":"cashAppRedirectToApp","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1cashAppRedirectToApp\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"cashAppRedirectToApp"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1cashAppRedirectToApp\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}