{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/konbiniDisplayDetails","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentaction\/konbinidisplaydetails"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/konbinidisplaydetails"]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)konbiniDisplayDetails","modules":[{"name":"StripePayments"}],"symbolKind":"property","navigatorTitle":[{"text":"konbiniDisplayDetails","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"konbiniDisplayDetails","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionKonbiniDisplayDetails","text":"STPIntentActionKonbiniDisplayDetails"},{"kind":"text","text":"?"}],"title":"konbiniDisplayDetails"},"abstract":[{"text":"Contains instructions for authenticating a Konbini payment.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"konbiniDisplayDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionKonbiniDisplayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionKonbiniDisplayDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionKonbiniDisplayDetails"},{"kind":"text","text":"?"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionKonbiniDisplayDetails":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPIntentActionKonbiniDisplayDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionKonbiniDisplayDetails","role":"symbol","url":"\/documentation\/stripepayments\/stpintentactionkonbinidisplaydetails","abstract":[{"type":"text","text":"Contains Konbini details necessary for the customer to complete the payment."}],"type":"topic","title":"STPIntentActionKonbiniDisplayDetails","kind":"symbol","navigatorTitle":[{"text":"STPIntentActionKonbiniDisplayDetails","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentAction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Next action details for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Check the "},{"code":"type","type":"codeVoice"},{"type":"text","text":" to see which one it is, and then use the related"},{"text":" ","type":"text"},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"title":"STPIntentAction","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","url":"\/documentation\/stripepayments\/stpintentaction","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/konbiniDisplayDetails":{"type":"topic","title":"konbiniDisplayDetails","url":"\/documentation\/stripepayments\/stpintentaction\/konbinidisplaydetails","abstract":[{"type":"text","text":"Contains instructions for authenticating a Konbini payment."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"konbiniDisplayDetails"},{"text":": ","kind":"text"},{"text":"STPIntentActionKonbiniDisplayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionKonbiniDisplayDetails"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/konbiniDisplayDetails","navigatorTitle":[{"kind":"identifier","text":"konbiniDisplayDetails"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"konbiniDisplayDetails"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"konbiniDisplayDetails"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionKonbiniDisplayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionKonbiniDisplayDetails","text":"STPIntentActionKonbiniDisplayDetails","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"konbiniDisplayDetails"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionKonbiniDisplayDetails\/title","value":"STPIntentActionKonbiniDisplayDetails","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionKonbiniDisplayDetails\/fragments","value":[{"text":"STPIntentActionKonbiniDisplayDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionKonbiniDisplayDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionKonbiniDisplayDetails"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","op":"replace","value":"STPIntentAction"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"kind":"identifier","text":"STPIntentAction"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","op":"replace","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1konbiniDisplayDetails\/title","value":"konbiniDisplayDetails","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1konbiniDisplayDetails\/fragments","value":[{"text":"konbiniDisplayDetails","kind":"identifier"}]}]}]}