{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)multibancoDisplayDetails","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"multibancoDisplayDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentActionMultibancoDisplayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"multibancoDisplayDetails"}],"title":"multibancoDisplayDetails","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/multibancoDisplayDetails"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/multibancodisplaydetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/multibancodisplaydetails"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multibancoDisplayDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionMultibancoDisplayDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"The details for displaying Multibanco voucher via URL, when "},{"type":"codeVoice","code":"type == .multibanco"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"kind":"symbol","abstract":[{"text":"Next action details for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" to see which one it is, and then use the related","type":"text"},{"text":" ","type":"text"},{"text":"property for the details necessary to handle it.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentAction","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentAction","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","title":"STPIntentAction","url":"\/documentation\/stripepayments\/stpintentaction"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails","navigatorTitle":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails","abstract":[{"text":"Contains Multibanco details necessary for the customer to complete the payment.","type":"text"}],"role":"symbol","title":"STPIntentActionMultibancoDisplayDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/multibancoDisplayDetails":{"abstract":[{"type":"text","text":"The details for displaying Multibanco voucher via URL, when "},{"code":"type == .multibanco","type":"codeVoice"}],"navigatorTitle":[{"kind":"identifier","text":"multibancoDisplayDetails"}],"title":"multibancoDisplayDetails","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpintentaction\/multibancodisplaydetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/multibancoDisplayDetails","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"multibancoDisplayDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails","kind":"typeIdentifier","text":"STPIntentActionMultibancoDisplayDetails"},{"kind":"text","text":"?"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"multibancoDisplayDetails","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"multibancoDisplayDetails"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPIntentActionMultibancoDisplayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails"},{"text":" * ","kind":"text"},{"text":"multibancoDisplayDetails","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","value":"STPIntentAction","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/title","value":"STPIntentActionMultibancoDisplayDetails","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionMultibancoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/fragments","op":"replace"},{"value":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/navigatorTitle","op":"replace"},{"value":"multibancoDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1multibancoDisplayDetails\/title","op":"replace"},{"value":[{"kind":"identifier","text":"multibancoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1multibancoDisplayDetails\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}