{"metadata":{"role":"symbol","navigatorTitle":[{"text":"oxxoDisplayDetails","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"oxxoDisplayDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionOXXODisplayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionOXXODisplayDetails"},{"text":"?","kind":"text"}],"title":"oxxoDisplayDetails","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)oxxoDisplayDetails"},"sections":[],"abstract":[{"text":"The details for displaying OXXO voucher via URL, when ","type":"text"},{"code":"type == .OXXODisplayDetails","type":"codeVoice"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/oxxoDisplayDetails"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"oxxoDisplayDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionOXXODisplayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionOXXODisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentaction\/oxxodisplaydetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentaction\/oxxodisplaydetails"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"title":"STPIntentAction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentAction"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","abstract":[{"type":"text","text":"Next action details for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is a container for the various types that are available."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentaction"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/oxxoDisplayDetails":{"url":"\/documentation\/stripepayments\/stpintentaction\/oxxodisplaydetails","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"oxxoDisplayDetails"}],"type":"topic","abstract":[{"type":"text","text":"The details for displaying OXXO voucher via URL, when "},{"type":"codeVoice","code":"type == .OXXODisplayDetails"}],"role":"symbol","title":"oxxoDisplayDetails","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"oxxoDisplayDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentActionOXXODisplayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionOXXODisplayDetails"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/oxxoDisplayDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails":{"url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails","abstract":[{"text":"Contains OXXO details necessary for the customer to complete the payment.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}],"title":"STPIntentActionOXXODisplayDetails","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails","kind":"symbol","navigatorTitle":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"oxxoDisplayDetails","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"oxxoDisplayDetails","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPIntentActionOXXODisplayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionOXXODisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails"},{"text":" * ","kind":"text"},{"text":"oxxoDisplayDetails","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPIntentAction","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentAction"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentAction"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","op":"replace"},{"value":"oxxoDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1oxxoDisplayDetails\/title","op":"replace"},{"value":[{"kind":"identifier","text":"oxxoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1oxxoDisplayDetails\/fragments","op":"replace"},{"value":"STPIntentActionOXXODisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/title","op":"replace"},{"value":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/fragments","op":"replace"},{"value":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/navigatorTitle","op":"replace"}]}]}