{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/payNowDisplayQrCode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PayNow."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"title":"payNowDisplayQrCode","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)payNowDisplayQrCode","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"payNowDisplayQrCode"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payNowDisplayQrCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionPayNowDisplayQrCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPayNowDisplayQrCode"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payNowDisplayQrCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionPayNowDisplayQrCode","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPayNowDisplayQrCode"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/paynowdisplayqrcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/paynowdisplayqrcode"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"abstract":[{"type":"text","text":"Next action details for "},{"code":"STPPaymentIntent","type":"codeVoice"},{"type":"text","text":" and "},{"code":"STPSetupIntent","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is a container for the various types that are available."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"code":"type","type":"codeVoice"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"code":"STPIntentAction","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpintentaction","title":"STPIntentAction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentAction","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/payNowDisplayQrCode":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"payNowDisplayQrCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPayNowDisplayQrCode","text":"STPIntentActionPayNowDisplayQrCode"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/payNowDisplayQrCode","navigatorTitle":[{"kind":"identifier","text":"payNowDisplayQrCode"}],"title":"payNowDisplayQrCode","url":"\/documentation\/stripepayments\/stpintentaction\/paynowdisplayqrcode","abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PayNow."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode":{"abstract":[{"type":"text","text":"Contains instructions for presenting the QR code required to complete a PayNow payment."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentActionPayNowDisplayQrCode"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"type":"topic","title":"STPIntentActionPayNowDisplayQrCode","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"payNowDisplayQrCode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"payNowDisplayQrCode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPIntentActionPayNowDisplayQrCode","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPayNowDisplayQrCode"},{"text":" * ","kind":"text"},{"text":"payNowDisplayQrCode","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPIntentAction","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title"},{"value":[{"kind":"identifier","text":"STPIntentAction"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments"},{"value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle"},{"value":"payNowDisplayQrCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1payNowDisplayQrCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1payNowDisplayQrCode\/fragments","value":[{"text":"payNowDisplayQrCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/title","value":"STPIntentActionPayNowDisplayQrCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/fragments","value":[{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/navigatorTitle","value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}]}]}]}