{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptPayDisplayQrCode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPromptPayDisplayQrCode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode","kind":"typeIdentifier","text":"STPIntentActionPromptPayDisplayQrCode"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PromptPay."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/promptpaydisplayqrcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/promptpaydisplayqrcode"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/promptPayDisplayQrCode"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)promptPayDisplayQrCode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptPayDisplayQrCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentActionPromptPayDisplayQrCode","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPromptPayDisplayQrCode"},{"kind":"text","text":"?"}],"title":"promptPayDisplayQrCode","navigatorTitle":[{"kind":"identifier","text":"promptPayDisplayQrCode"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode":{"url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode","navigatorTitle":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode","type":"topic","title":"STPIntentActionPromptPayDisplayQrCode","abstract":[{"type":"text","text":"Contains instructions for presenting the QR code required to complete a PromptPay payment."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentActionPromptPayDisplayQrCode"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/promptPayDisplayQrCode":{"abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PromptPay."}],"url":"\/documentation\/stripepayments\/stpintentaction\/promptpaydisplayqrcode","navigatorTitle":[{"kind":"identifier","text":"promptPayDisplayQrCode"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptPayDisplayQrCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPromptPayDisplayQrCode","text":"STPIntentActionPromptPayDisplayQrCode"},{"kind":"text","text":"?"}],"title":"promptPayDisplayQrCode","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/promptPayDisplayQrCode","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"title":"STPIntentAction","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentAction"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","abstract":[{"type":"text","text":"Next action details for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is a container for the various types that are available."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentaction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"promptPayDisplayQrCode","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"promptPayDisplayQrCode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPromptPayDisplayQrCode"},{"text":" * ","kind":"text"},{"text":"promptPayDisplayQrCode","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPIntentActionPromptPayDisplayQrCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/fragments","value":[{"kind":"identifier","text":"STPIntentActionPromptPayDisplayQrCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/navigatorTitle","value":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1promptPayDisplayQrCode\/title","value":"promptPayDisplayQrCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1promptPayDisplayQrCode\/fragments","value":[{"text":"promptPayDisplayQrCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","value":"STPIntentAction"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"kind":"identifier","text":"STPIntentAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentAction"}]}]}]}