{"abstract":[{"type":"text","text":"The details for authorizing via URL, when "},{"type":"codeVoice","code":"type == .redirectToURL"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/redirectToURL","interfaceLanguage":"swift"},"metadata":{"title":"redirectToURL","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)redirectToURL","modules":[{"name":"StripePayments"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"redirectToURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL","text":"STPIntentActionRedirectToURL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"redirectToURL"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"redirectToURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL","kind":"typeIdentifier","text":"STPIntentActionRedirectToURL","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentaction\/redirecttourl"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/redirecttourl"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/redirectToURL":{"title":"redirectToURL","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"redirectToURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionRedirectToURL","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpintentaction\/redirecttourl","navigatorTitle":[{"text":"redirectToURL","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/redirectToURL","role":"symbol","abstract":[{"text":"The details for authorizing via URL, when ","type":"text"},{"type":"codeVoice","code":"type == .redirectToURL"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","type":"topic","kind":"symbol","title":"STPIntentAction","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentaction","abstract":[{"text":"Next action details for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is a container for the various types that are available."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"code":"type","type":"codeVoice"},{"text":" to see which one it is, and then use the related","type":"text"},{"text":" ","type":"text"},{"text":"property for the details necessary to handle it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL":{"abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to another page or application.","type":"text"},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentActionRedirectToURL"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionredirecttourl","type":"topic","title":"STPIntentActionRedirectToURL","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL","role":"symbol","navigatorTitle":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"redirectToURL","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"redirectToURL","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL","text":"STPIntentActionRedirectToURL"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"redirectToURL"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"redirectToURL","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1redirectToURL\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1redirectToURL\/fragments","value":[{"kind":"identifier","text":"redirectToURL"}],"op":"replace"},{"value":"STPIntentAction","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","op":"replace"},{"value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/title","value":"STPIntentActionRedirectToURL","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/fragments","value":[{"kind":"identifier","text":"STPIntentActionRedirectToURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionRedirectToURL"}]}]}]}