{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swishHandleRedirect","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionSwishHandleRedirect","text":"STPIntentActionSwishHandleRedirect","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)swishHandleRedirect","title":"swishHandleRedirect","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"swishHandleRedirect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentActionSwishHandleRedirect","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionSwishHandleRedirect"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"swishHandleRedirect"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/swishhandleredirect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/swishhandleredirect"]}],"abstract":[{"type":"text","text":"Contains details for redirecting to the Swish app."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/swishHandleRedirect","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"abstract":[{"text":"Next action details for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" to see which one it is, and then use the related","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"title":"STPIntentAction","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","url":"\/documentation\/stripepayments\/stpintentaction","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPIntentAction"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/swishHandleRedirect":{"navigatorTitle":[{"kind":"identifier","text":"swishHandleRedirect"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"swishHandleRedirect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentActionSwishHandleRedirect","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionSwishHandleRedirect"},{"kind":"text","text":"?"}],"abstract":[{"text":"Contains details for redirecting to the Swish app.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/swishHandleRedirect","url":"\/documentation\/stripepayments\/stpintentaction\/swishhandleredirect","title":"swishHandleRedirect","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionSwishHandleRedirect":{"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionSwishHandleRedirect"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect","url":"\/documentation\/stripepayments\/stpintentactionswishhandleredirect","kind":"symbol","abstract":[{"type":"text","text":"Contains instructions for redirecting to the Swish app."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"code":"STPIntentActionSwishHandle","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","role":"symbol","title":"STPIntentActionSwishHandleRedirect","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionSwishHandleRedirect"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"swishHandleRedirect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"swishHandleRedirect","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionSwishHandleRedirect","text":"STPIntentActionSwishHandleRedirect","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionSwishHandleRedirect","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"swishHandleRedirect","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","value":"STPIntentAction"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"kind":"identifier","text":"STPIntentAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1swishHandleRedirect\/title","value":"swishHandleRedirect"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1swishHandleRedirect\/fragments","value":[{"text":"swishHandleRedirect","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect\/title","value":"STPIntentActionSwishHandleRedirect"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect\/fragments","value":[{"text":"STPIntentActionSwishHandleRedirect","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionSwishHandleRedirect\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionSwishHandleRedirect"}]}]}]}