{"variants":[{"paths":["\/documentation\/stripepayments\/stpintentaction\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentaction\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionType","preciseIdentifier":"c:@M@StripePayments@E@STPIntentActionType","kind":"typeIdentifier"}],"symbolKind":"property","title":"type","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)type"},"abstract":[{"text":"The type of action needed. The value of this field determines which","type":"text"},{"text":" ","type":"text"},{"text":"property of this object contains further details about the action.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPIntentActionType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","kind":"typeIdentifier","text":"STPIntentActionType"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/type"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/type":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionType","preciseIdentifier":"c:@M@StripePayments@E@STPIntentActionType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentaction\/type","title":"type","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/type","abstract":[{"text":"The type of action needed. The value of this field determines which","type":"text"},{"text":" ","type":"text"},{"text":"property of this object contains further details about the action.","type":"text"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"type":"topic","abstract":[{"text":"Types of next actions for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype","title":"STPIntentActionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpintentaction","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentAction","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Next action details for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is a container for the various types that are available."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"title":"STPIntentAction"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripePayments@E@STPIntentActionType","kind":"typeIdentifier","text":"STPIntentActionType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1type\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","value":"STPIntentAction","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"kind":"identifier","text":"STPIntentAction"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}