{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/verifywithmicrodeposits"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/verifywithmicrodeposits"]}],"abstract":[{"type":"text","text":"Contains details describing microdeposits verification flow for US bank accounts"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyWithMicrodeposits","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionVerifyWithMicrodeposits"},{"text":"?","kind":"text"}]}]}],"metadata":{"roleHeading":"Instance Property","title":"verifyWithMicrodeposits","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)verifyWithMicrodeposits","navigatorTitle":[{"kind":"identifier","text":"verifyWithMicrodeposits"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyWithMicrodeposits","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionVerifyWithMicrodeposits"},{"text":"?","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/verifyWithMicrodeposits"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","abstract":[{"type":"text","text":"Next action details for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is a container for the various types that are available."},{"type":"text","text":" "},{"type":"text","text":"Check the "},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"role":"symbol","title":"STPIntentAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"url":"\/documentation\/stripepayments\/stpintentaction","navigatorTitle":[{"kind":"identifier","text":"STPIntentAction"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/verifyWithMicrodeposits":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyWithMicrodeposits"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionVerifyWithMicrodeposits","text":"STPIntentActionVerifyWithMicrodeposits"},{"kind":"text","text":"?"}],"title":"verifyWithMicrodeposits","abstract":[{"type":"text","text":"Contains details describing microdeposits verification flow for US bank accounts"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"verifyWithMicrodeposits"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/verifyWithMicrodeposits","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentaction\/verifywithmicrodeposits"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}],"title":"STPIntentActionVerifyWithMicrodeposits","abstract":[{"text":"Contains details describing microdeposits verification flow for US Bank Accounts.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"verifyWithMicrodeposits"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"verifyWithMicrodeposits","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionVerifyWithMicrodeposits","text":"STPIntentActionVerifyWithMicrodeposits","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits"},{"text":" * ","kind":"text"},{"text":"verifyWithMicrodeposits","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","value":"STPIntentAction"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1verifyWithMicrodeposits\/title","value":"verifyWithMicrodeposits"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1verifyWithMicrodeposits\/fragments","value":[{"text":"verifyWithMicrodeposits","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/title","value":"STPIntentActionVerifyWithMicrodeposits"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/fragments","value":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/navigatorTitle","value":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}]}]}]}