{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/weChatPayRedirectToApp"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"weChatPayRedirectToApp"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp","kind":"typeIdentifier","text":"STPIntentActionWechatPayRedirectToApp","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionWechatPayRedirectToApp"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/wechatpayredirecttoapp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction\/wechatpayredirecttoapp"]}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"weChatPayRedirectToApp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionWechatPayRedirectToApp","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionWechatPayRedirectToApp"},{"text":"?","kind":"text"}],"title":"weChatPayRedirectToApp","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"weChatPayRedirectToApp","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPIntentAction(py)weChatPayRedirectToApp"},"abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to the WeChat Pay app."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/weChatPayRedirectToApp":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPayRedirectToApp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionWechatPayRedirectToApp","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionWechatPayRedirectToApp","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpintentaction\/wechatpayredirecttoapp","title":"weChatPayRedirectToApp","type":"topic","navigatorTitle":[{"kind":"identifier","text":"weChatPayRedirectToApp"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/weChatPayRedirectToApp","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to the WeChat Pay app."}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"abstract":[{"text":"Next action details for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is a container for the various types that are available."},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentAction","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentaction","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","navigatorTitle":[{"kind":"identifier","text":"STPIntentAction"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"kind":"symbol","role":"symbol","title":"STPIntentAction"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionWechatPayRedirectToApp":{"role":"symbol","navigatorTitle":[{"text":"STPIntentActionWechatPayRedirectToApp","kind":"identifier"}],"title":"STPIntentActionWechatPayRedirectToApp","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to WeChat Pay app."},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentActionWechatPayRedirectToApp"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionWechatPayRedirectToApp"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"weChatPayRedirectToApp","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"weChatPayRedirectToApp","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp","kind":"typeIdentifier","text":"STPIntentActionWechatPayRedirectToApp","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionWechatPayRedirectToApp"},{"kind":"text","text":" * "},{"text":"weChatPayRedirectToApp","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"weChatPayRedirectToApp","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1weChatPayRedirectToApp\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1weChatPayRedirectToApp\/fragments","value":[{"text":"weChatPayRedirectToApp","kind":"identifier"}]},{"value":"STPIntentAction","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentAction"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/title","op":"replace","value":"STPIntentActionWechatPayRedirectToApp"},{"value":[{"text":"STPIntentActionWechatPayRedirectToApp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionWechatPayRedirectToApp"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}