{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams\/rootObjectName()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"STPFormEncodable.rootObjectName()","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"symbolKind":"method","modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","role":"symbol","title":"rootObjectName()","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams(cm)rootObjectName","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodoxxoparams\/rootobjectname()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodoxxoparams\/rootobjectname()"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodOXXOParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodoxxoparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create an OXXO Payment Method"}],"navigatorTitle":[{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}],"title":"STPPaymentMethodOXXOParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodOXXOParams/rootObjectName()":{"type":"topic","title":"rootObjectName()","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams\/rootObjectName()","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}],"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodoxxoparams\/rootobjectname()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"rootObjectName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/title","op":"replace","value":"STPPaymentMethodOXXOParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams~1rootObjectName()\/title","op":"replace","value":"rootObjectName"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams~1rootObjectName()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}]}]}]}