{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"This PaymentIntent was canceled and cannot be changed."}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/canceled","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusCanceled","title":"STPPaymentIntentStatus.canceled","role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentStatusCanceled","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/canceled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/canceled"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus","navigatorTitle":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentStatus","kind":"identifier"}],"title":"STPPaymentIntentStatus","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/canceled":{"navigatorTitle":[{"text":"STPPaymentIntentStatusCanceled","kind":"identifier"}],"title":"STPPaymentIntentStatus.canceled","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canceled"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This PaymentIntent was canceled and cannot be changed."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/canceled","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/canceled","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentIntentStatusCanceled","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"STPPaymentIntentStatusCanceled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentIntentStatusCanceled"}]}]}},{"op":"replace","value":"STPPaymentIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments"},{"value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle"},{"value":"STPPaymentIntentStatusCanceled","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1canceled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatusCanceled"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1canceled\/fragments","op":"replace"}]}]}