{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/equatable-implementations"]}],"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/!=(_:_:)"],"anchor":"Operators","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"kind":"article","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/!=(_:_:)":{"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/!=(_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/!=(_:_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"url":"\/documentation\/stripepayments\/stppaymentintentstatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentIntentStatus","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","role":"symbol","abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"type":"topic","title":"STPPaymentIntentStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title","op":"replace","value":"STPPaymentIntentStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}]},{"value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle"}]}]}