{"abstract":[{"type":"text","text":"Stripe is processing this PaymentIntent"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"processing"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusProcessing","symbolKind":"case","roleHeading":"Case","title":"STPPaymentIntentStatus.processing","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusProcessing"}],"modules":[{"name":"StripePayments"}],"role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/processing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/processing"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/processing","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"processing"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"title":"STPPaymentIntentStatus","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentstatus","navigatorTitle":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","abstract":[{"text":"Status types for an STPPaymentIntent","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/processing":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/processing","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/processing","role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentStatusProcessing","kind":"identifier"}],"abstract":[{"text":"Stripe is processing this PaymentIntent","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processing","kind":"identifier"}],"title":"STPPaymentIntentStatus.processing"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentIntentStatusProcessing","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatusProcessing"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPPaymentIntentStatusProcessing","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentIntentStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title"},{"value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle"},{"value":"STPPaymentIntentStatusProcessing","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1processing\/title"},{"value":[{"text":"STPPaymentIntentStatusProcessing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1processing\/fragments"}]}]}