{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresConfirmation","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"abstract":[{"text":"This PaymentIntent needs to be confirmed","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requiresconfirmation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requiresconfirmation"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresConfirmation"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","title":"STPPaymentIntentStatus.requiresConfirmation","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusRequiresConfirmation","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresConfirmation"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresConfirmation"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"navigatorTitle":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus","title":"STPPaymentIntentStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresConfirmation":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresConfirmation","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requiresconfirmation","kind":"symbol","type":"topic","abstract":[{"text":"This PaymentIntent needs to be confirmed","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresConfirmation","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentStatusRequiresConfirmation","kind":"identifier"}],"title":"STPPaymentIntentStatus.requiresConfirmation","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentIntentStatusRequiresConfirmation","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresConfirmation"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPPaymentIntentStatusRequiresConfirmation","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title","value":"STPPaymentIntentStatus"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments","value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle","value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresConfirmation\/title","value":"STPPaymentIntentStatusRequiresConfirmation","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresConfirmation\/fragments","value":[{"text":"STPPaymentIntentStatusRequiresConfirmation","kind":"identifier"}],"op":"replace"}]}]}