{"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusRequiresPaymentMethod","symbolKind":"case","title":"STPPaymentIntentStatus.requiresPaymentMethod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresPaymentMethod"}],"navigatorTitle":[{"text":"STPPaymentIntentStatusRequiresPaymentMethod","kind":"identifier"}],"role":"symbol","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresPaymentMethod"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresPaymentMethod"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requirespaymentmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requirespaymentmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"This PaymentIntent requires a PaymentMethod or Source","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","role":"symbol","title":"STPPaymentIntentStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentStatus"}],"kind":"symbol","abstract":[{"text":"Status types for an STPPaymentIntent","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresPaymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresPaymentMethod","kind":"symbol","type":"topic","title":"STPPaymentIntentStatus.requiresPaymentMethod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresPaymentMethod"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresPaymentMethod"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requirespaymentmethod","abstract":[{"type":"text","text":"This PaymentIntent requires a PaymentMethod or Source"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentIntentStatusRequiresPaymentMethod","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresPaymentMethod"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresPaymentMethod"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentIntentStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle"},{"value":"STPPaymentIntentStatusRequiresPaymentMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresPaymentMethod\/title"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresPaymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresPaymentMethod\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}