{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresCapture","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusRequiresCapture","symbolKind":"case","title":"STPPaymentIntentStatus.requiresCapture","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresCapture"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCapture"}],"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Case"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresCapture","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Indicates the payment must be captured, for STPPaymentIntentCaptureMethodManual","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requirescapture"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requirescapture"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresCapture":{"title":"STPPaymentIntentStatus.requiresCapture","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresCapture","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresCapture"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requirescapture","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCapture"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Indicates the payment must be captured, for STPPaymentIntentCaptureMethodManual"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"navigatorTitle":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus","title":"STPPaymentIntentStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPPaymentIntentStatusRequiresCapture","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPPaymentIntentStatusRequiresCapture","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresCapture"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentIntentStatusRequiresCapture","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresCapture\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentStatusRequiresCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresCapture\/fragments","op":"replace"},{"value":"STPPaymentIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}