{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresAction"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requiresaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requiresaction"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusRequiresAction","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresAction","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPaymentIntentStatusRequiresAction","kind":"identifier"}],"title":"STPPaymentIntentStatus.requiresAction"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresAction","interfaceLanguage":"swift"},"abstract":[{"text":"The selected PaymentMethod or Source requires additional authentication steps.","type":"text"},{"text":" ","type":"text"},{"text":"Additional actions found via ","type":"text"},{"code":"next_action","type":"codeVoice"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresAction":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresAction","abstract":[{"text":"The selected PaymentMethod or Source requires additional authentication steps.","type":"text"},{"text":" ","type":"text"},{"text":"Additional actions found via ","type":"text"},{"code":"next_action","type":"codeVoice"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresAction"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requiresaction","title":"STPPaymentIntentStatus.requiresAction","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresAction"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"title":"STPPaymentIntentStatus","url":"\/documentation\/stripepayments\/stppaymentintentstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentStatus","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","navigatorTitle":[{"text":"STPPaymentIntentStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentStatusRequiresAction"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentStatusRequiresAction","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPPaymentIntentStatusRequiresAction","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresAction\/title","value":"STPPaymentIntentStatusRequiresAction"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresAction\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title","value":"STPPaymentIntentStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}