{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use STPPaymentIntentStatus.requiresAction instead","type":"text"}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresSourceAction"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusRequiresSourceAction","platforms":[],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSourceAction"}],"title":"STPPaymentIntentStatus.requiresSourceAction"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSourceAction","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The selected Source requires additional authentication steps."},{"type":"text","text":" "},{"type":"text","text":"Additional actions found via "},{"type":"codeVoice","code":"next_source_action"},{"type":"text","text":" "},{"text":"Deprecated: Use STPPaymentIntentStatusRequiresAction instead.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresSourceAction"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requiressourceaction"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requiressourceaction"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"url":"\/documentation\/stripepayments\/stppaymentintentstatus","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","kind":"symbol","abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"title":"STPPaymentIntentStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentStatus"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresSourceAction":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSourceAction"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresSourceAction","kind":"identifier"}],"type":"topic","deprecated":true,"abstract":[{"text":"The selected Source requires additional authentication steps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Additional actions found via "},{"code":"next_source_action","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"Deprecated: Use STPPaymentIntentStatusRequiresAction instead."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSourceAction","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requiressourceaction","title":"STPPaymentIntentStatus.requiresSourceAction"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"STPPaymentIntentStatusRequiresSourceAction","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPPaymentIntentStatusRequiresSourceAction","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPPaymentIntentStatusRequiresSourceAction","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle","value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresSourceAction\/title","value":"STPPaymentIntentStatusRequiresSourceAction","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresSourceAction\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSourceAction"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}