{"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use STPPaymentIntentStatus.requiresPaymentMethod instead","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requiressource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/requiressource"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"kind":"symbol","abstract":[{"text":"This PaymentIntent requires a Source","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Deprecated: Use STPPaymentIntentStatusRequiresPaymentMethod instead."}],"metadata":{"role":"symbol","platforms":[],"modules":[{"name":"StripePayments"}],"title":"STPPaymentIntentStatus.requiresSource","navigatorTitle":[{"text":"STPPaymentIntentStatusRequiresSource","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresSource"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusRequiresSource"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresSource"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSource","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentStatus"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"title":"STPPaymentIntentStatus","url":"\/documentation\/stripepayments\/stppaymentintentstatus","abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresSource":{"title":"STPPaymentIntentStatus.requiresSource","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresSource"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSource"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"This PaymentIntent requires a Source"},{"type":"text","text":" "},{"type":"text","text":"Deprecated: Use STPPaymentIntentStatusRequiresPaymentMethod instead."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSource","deprecated":true,"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requiressource"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentStatusRequiresSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSource"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPPaymentIntentStatusRequiresSource","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"STPPaymentIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments","op":"replace"},{"value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresSource\/title","value":"STPPaymentIntentStatusRequiresSource"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresSource\/fragments","value":[{"text":"STPPaymentIntentStatusRequiresSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}