{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/succeeded","interfaceLanguage":"swift"},"abstract":[{"text":"The payment has succeeded","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/succeeded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/succeeded"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"succeeded"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusSucceeded","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"StripePayments"}],"title":"STPPaymentIntentStatus.succeeded","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusSucceeded"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/succeeded":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusSucceeded"}],"title":"STPPaymentIntentStatus.succeeded","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/succeeded","abstract":[{"type":"text","text":"The payment has succeeded"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/succeeded"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"abstract":[{"text":"Status types for an STPPaymentIntent","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus","title":"STPPaymentIntentStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"STPPaymentIntentStatusSucceeded","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentStatusSucceeded","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPPaymentIntentStatusSucceeded","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"STPPaymentIntentStatusSucceeded","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1succeeded\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1succeeded\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentStatusSucceeded"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title","value":"STPPaymentIntentStatus","op":"replace"},{"value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments"},{"op":"replace","value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle"}]}]}