{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"STPPaymentIntentStatusUnknown","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus@STPPaymentIntentStatusUnknown","roleHeading":"Case","symbolKind":"case","title":"STPPaymentIntentStatus.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentstatus\/unknown"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/unknown"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"]]},"abstract":[{"text":"Unknown status","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"title":"STPPaymentIntentStatus","url":"\/documentation\/stripepayments\/stppaymentintentstatus","role":"symbol","abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentStatus"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/unknown":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusUnknown"}],"abstract":[{"text":"Unknown status","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/unknown","title":"STPPaymentIntentStatus.unknown","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentIntentStatusUnknown","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPPaymentIntentStatusUnknown","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentIntentStatusUnknown"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments","op":"replace"},{"value":[{"text":"STPPaymentIntentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/navigatorTitle","op":"replace"},{"value":"STPPaymentIntentStatusUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1unknown\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentStatusUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1unknown\/fragments","op":"replace"}]}]}