{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceflow\/codeverification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceflow\/codeverification"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow"]]},"abstract":[{"text":"Your customer must verify ownership of their account by providing a code that you post to the Stripe API for authentication.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceFlowCodeVerification"}],"title":"STPSourceFlow.codeVerification","roleHeading":"Case","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeVerification"}],"externalID":"c:@M@StripePayments@E@STPSourceFlow@STPSourceFlowCodeVerification"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"codeVerification","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/codeVerification","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/codeVerification":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceFlowCodeVerification"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/codeVerification","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"codeVerification","kind":"identifier"}],"type":"topic","title":"STPSourceFlow.codeVerification","url":"\/documentation\/stripepayments\/stpsourceflow\/codeverification","role":"symbol","kind":"symbol","abstract":[{"text":"Your customer must verify ownership of their account by providing a code that you post to the Stripe API for authentication.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"type":"topic","abstract":[{"text":"Authentication flows for a Source","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"STPSourceFlow","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceFlow","kind":"identifier"}],"title":"STPSourceFlow","url":"\/documentation\/stripepayments\/stpsourceflow","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceFlowCodeVerification"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceFlowCodeVerification","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSourceFlowCodeVerification","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1codeVerification\/title","op":"replace","value":"STPSourceFlowCodeVerification"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1codeVerification\/fragments","op":"replace","value":[{"text":"STPSourceFlowCodeVerification","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title","op":"replace","value":"STPSourceFlow"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments","value":[{"kind":"identifier","text":"STPSourceFlow"}]},{"value":[{"text":"STPSourceFlow","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/navigatorTitle","op":"replace"}]}]}