{"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/description"],"generated":true}],"metadata":{"modules":[{"name":"StripePayments"}],"role":"collectionGroup","roleHeading":"API Collection","title":"CustomStringConvertible Implementations"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/CustomStringConvertible-Implementations"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceflow\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/description":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/description","kind":"symbol","abstract":[],"title":"description","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceflow\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"type":"topic","url":"\/documentation\/stripepayments\/stpsourceflow","title":"STPSourceFlow","kind":"symbol","navigatorTitle":[{"text":"STPSourceFlow","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceFlow","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","abstract":[{"type":"text","text":"Authentication flows for a Source"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title","value":"STPSourceFlow"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceFlow"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/navigatorTitle","op":"replace","value":[{"text":"STPSourceFlow","kind":"identifier"}]}]}]}