{"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceflow\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow"]]},"metadata":{"roleHeading":"API Collection","modules":[{"name":"StripePayments"}],"title":"RawRepresentable Implementations","role":"collectionGroup"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/hashValue"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/hash(into:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/RawRepresentable-Implementations"},"kind":"article","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/hashValue":{"abstract":[],"url":"\/documentation\/stripepayments\/stpsourceflow\/hashvalue","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/hashValue","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hashValue"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","abstract":[{"type":"text","text":"Authentication flows for a Source"}],"url":"\/documentation\/stripepayments\/stpsourceflow","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceFlow"}],"title":"STPSourceFlow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceFlow"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/hash(into:)":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/hash(into:)","title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"abstract":[],"url":"\/documentation\/stripepayments\/stpsourceflow\/hash(into:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title","op":"replace","value":"STPSourceFlow"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments","value":[{"kind":"identifier","text":"STPSourceFlow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceFlow"}]}]}]}