{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Your customer must push funds to the account information provided.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"receiver"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","roleHeading":"Case","symbolKind":"case","title":"STPSourceFlow.receiver","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"receiver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceFlowReceiver"}],"externalID":"c:@M@StripePayments@E@STPSourceFlow@STPSourceFlowReceiver"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceflow\/receiver"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceflow\/receiver"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/receiver","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/receiver":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/receiver","navigatorTitle":[{"text":"STPSourceFlowReceiver","kind":"identifier"}],"title":"STPSourceFlow.receiver","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourceflow\/receiver","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiver"}],"abstract":[{"text":"Your customer must push funds to the account information provided.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","url":"\/documentation\/stripepayments\/stpsourceflow","kind":"symbol","title":"STPSourceFlow","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPSourceFlow","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceFlow"}],"abstract":[{"type":"text","text":"Authentication flows for a Source"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceFlowReceiver"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"STPSourceFlowReceiver","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPSourceFlowReceiver","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1receiver\/title","value":"STPSourceFlowReceiver"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1receiver\/fragments","value":[{"text":"STPSourceFlowReceiver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title","value":"STPSourceFlow","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments","op":"replace","value":[{"text":"STPSourceFlow","kind":"identifier"}]},{"value":[{"text":"STPSourceFlow","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}