{"abstract":[{"text":"Your customer must be redirected to their online banking service (either a website or mobile banking app) to approve the payment.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"redirect","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/redirect"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceflow\/redirect"]},{"paths":["\/documentation\/stripepayments\/stpsourceflow\/redirect"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"StripePayments"}],"title":"STPSourceFlow.redirect","externalID":"c:@M@StripePayments@E@STPSourceFlow@STPSourceFlowRedirect","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"redirect","kind":"identifier"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"STPSourceFlowRedirect","kind":"identifier"}],"roleHeading":"Case"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/redirect":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/redirect","title":"STPSourceFlow.redirect","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourceflow\/redirect","abstract":[{"text":"Your customer must be redirected to their online banking service (either a website or mobile banking app) to approve the payment.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceFlowRedirect"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"redirect"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"kind":"symbol","title":"STPSourceFlow","abstract":[{"type":"text","text":"Authentication flows for a Source"}],"url":"\/documentation\/stripepayments\/stpsourceflow","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceFlow","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceFlow","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"STPSourceFlowRedirect","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPSourceFlowRedirect","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPSourceFlowRedirect","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1redirect\/title","op":"replace","value":"STPSourceFlowRedirect"},{"value":[{"kind":"identifier","text":"STPSourceFlowRedirect"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1redirect\/fragments"},{"value":"STPSourceFlow","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments","value":[{"kind":"identifier","text":"STPSourceFlow"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/navigatorTitle","op":"replace","value":[{"text":"STPSourceFlow","kind":"identifier"}]}]}]}