{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"sections":[],"abstract":[{"type":"text","text":"Notification that the user pressed the "},{"code":"return","type":"codeVoice"},{"type":"text","text":" key after completely filling"},{"text":" ","type":"text"},{"text":"out the STPPaymentCardTextField with data that passes validation.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The Stripe SDK is going to "},{"code":"resignFirstResponder","type":"codeVoice"},{"text":" on the ","type":"text"},{"type":"codeVoice","code":"STPPaymentCardTextField"},{"type":"text","text":" "},{"type":"text","text":"to dismiss the keyboard after this delegate method returns, however if your app wants"},{"type":"text","text":" "},{"text":"to do something more (ex: move first responder to another field), this is a good","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"opportunity to do that."},{"type":"text","text":" "},{"type":"text","text":"This is delivered "},{"type":"emphasis","inlineContent":[{"text":"before","type":"text"}]},{"text":" the corresponding ","type":"text"},{"code":"paymentCardTextFieldDidEndEditing:","type":"codeVoice"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forReturn"},{"text":" ","kind":"text"},{"text":"textField","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","kind":"typeIdentifier","text":"STPPaymentCardTextField"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The STPPaymentCardTextField that was being edited when the user pressed return","type":"text"}],"type":"paragraph"}],"name":"textField"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfieldwillendediting(forreturn:)"]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfieldwillendediting(forreturn:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldWillEndEditing(forReturn:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"Stripe"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentCardTextFieldWillEndEditing","kind":"identifier"},{"kind":"text","text":"("},{"text":"forReturn","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"kind":"text","text":")"}],"role":"symbol","title":"paymentCardTextFieldWillEndEditing(forReturn:)","externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(im)paymentCardTextFieldWillEndEditingForReturn:","navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldWillEndEditingForReturn:"}],"symbolKind":"method"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentCardTextField":{"type":"topic","url":"\/documentation\/stripe\/stppaymentcardtextfield","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"text":" ","type":"text"},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"text":" ","type":"text"},{"text":"designed to fit on a single line, and from a design perspective can be used","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField","title":"STPPaymentCardTextField","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/paymentCardTextFieldWillEndEditing(forReturn:)":{"kind":"symbol","abstract":[{"text":"Notification that the user pressed the ","type":"text"},{"type":"codeVoice","code":"return"},{"type":"text","text":" key after completely filling"},{"type":"text","text":" "},{"type":"text","text":"out the STPPaymentCardTextField with data that passes validation."},{"text":" ","type":"text"},{"type":"text","text":"The Stripe SDK is going to "},{"code":"resignFirstResponder","type":"codeVoice"},{"type":"text","text":" on the "},{"code":"STPPaymentCardTextField","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"to dismiss the keyboard after this delegate method returns, however if your app wants"},{"type":"text","text":" "},{"type":"text","text":"to do something more (ex: move first responder to another field), this is a good"},{"type":"text","text":" "},{"type":"text","text":"opportunity to do that."},{"type":"text","text":" "},{"text":"This is delivered ","type":"text"},{"inlineContent":[{"type":"text","text":"before"}],"type":"emphasis"},{"type":"text","text":" the corresponding "},{"code":"paymentCardTextFieldDidEndEditing:","type":"codeVoice"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldWillEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forReturn"},{"text":": ","kind":"text"},{"text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldWillEndEditing(forReturn:)","url":"\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfieldwillendediting(forreturn:)","role":"symbol","title":"paymentCardTextFieldWillEndEditing(forReturn:)","type":"topic","navigatorTitle":[{"text":"paymentCardTextFieldWillEndEditingForReturn:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"paymentCardTextFieldWillEndEditingForReturn:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"paymentCardTextFieldWillEndEditingForReturn:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"paymentCardTextFieldWillEndEditingForReturn:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","kind":"typeIdentifier","text":"STPPaymentCardTextField"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textField"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController"},{"value":[{"kind":"identifier","text":"STPAddCardViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldWillEndEditing(forReturn:)\/title","value":"paymentCardTextFieldWillEndEditingForReturn:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldWillEndEditing(forReturn:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditingForReturn:"}]}]}]}
