{"sections":[],"metadata":{"symbolKind":"method","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(im)paymentCardTextFieldDidBeginEditingCVC:","navigatorTitle":[{"text":"paymentCardTextFieldDidBeginEditingCVC:","kind":"identifier"}],"modules":[{"name":"Stripe"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingCVC"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"paymentCardTextFieldDidBeginEditingCVC(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidbegineditingcvc(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidbegineditingcvc(_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidBeginEditingCVC(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingCVC","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"textField","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"Called when editing begins in the payment card field’s CVC field.","type":"text"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"title":"STPAddCardViewController","abstract":[{"type":"text","text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"}],"navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/paymentCardTextFieldDidBeginEditingCVC(_:)":{"type":"topic","abstract":[{"type":"text","text":"Called when editing begins in the payment card field’s CVC field."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingCVC","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingCVC:"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidBeginEditingCVC(_:)","url":"\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidbegineditingcvc(_:)","title":"paymentCardTextFieldDidBeginEditingCVC(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextField"}],"abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"text":" ","type":"text"},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"text":"anywhere a UITextField would be appropriate.","type":"text"}],"title":"STPPaymentCardTextField","url":"\/documentation\/stripe\/stppaymentcardtextfield","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"paymentCardTextFieldDidBeginEditingCVC:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingCVC:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingCVC:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField"},{"kind":"text","text":" *) "},{"text":"textField","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","op":"replace","value":"STPAddCardViewController"},{"value":[{"kind":"identifier","text":"STPAddCardViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments"},{"value":"paymentCardTextFieldDidBeginEditingCVC:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidBeginEditingCVC(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidBeginEditingCVC(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingCVC:","kind":"identifier"}],"op":"replace"}]}]}
