{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidChange"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"the text field that has changed","type":"text"}]}],"name":"textField"}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(void)paymentCardTextFieldDidChange:(STPPaymentCardTextField *)textField {"},{"type":"text","text":" "},{"type":"text","text":"self.paymentButton.enabled = textField.isValid;"},{"type":"text","text":" "},{"type":"text","text":"}"}]}]}]}],"kind":"content"}],"metadata":{"modules":[{"name":"Stripe"}],"title":"paymentCardTextFieldDidChange(_:)","symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(im)paymentCardTextFieldDidChange:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidChange"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"paymentCardTextFieldDidChange:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidChange(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidchange(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidchange(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Called when either the card number, expiration, or CVC changes. At this point,"},{"type":"text","text":" "},{"text":"one can call ","type":"text"},{"code":"isValid","type":"codeVoice"},{"text":" on the text field to determine, for example,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"whether or not to enable a button to submit the form. Example:"}],"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/paymentCardTextFieldDidChange(_:)":{"kind":"symbol","abstract":[{"type":"text","text":"Called when either the card number, expiration, or CVC changes. At this point,"},{"type":"text","text":" "},{"type":"text","text":"one can call "},{"code":"isValid","type":"codeVoice"},{"type":"text","text":" on the text field to determine, for example,"},{"text":" ","type":"text"},{"type":"text","text":"whether or not to enable a button to submit the form. Example:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"kind":"text","text":")"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidchange(_:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidChange(_:)","role":"symbol","title":"paymentCardTextFieldDidChange(_:)","type":"topic","navigatorTitle":[{"text":"paymentCardTextFieldDidChange:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentCardTextField":{"type":"topic","url":"\/documentation\/stripe\/stppaymentcardtextfield","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"text":" ","type":"text"},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"text":" ","type":"text"},{"text":"designed to fit on a single line, and from a design perspective can be used","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField","title":"STPPaymentCardTextField","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"paymentCardTextFieldDidChange:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidChange:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"paymentCardTextFieldDidChange:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextField"},{"kind":"text","text":" *) "},{"text":"textField","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"paymentCardTextFieldDidChange:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidChange(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidChange:"}],"op":"replace"},{"value":"STPAddCardViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title"},{"value":[{"kind":"identifier","text":"STPAddCardViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
