{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/prefilledinformation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/prefilledinformation"]}],"metadata":{"title":"prefilledInformation","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"prefilledInformation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation","text":"STPUserInformation"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"prefilledInformation"}],"externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(py)prefilledInformation","role":"symbol","symbolKind":"property","modules":[{"name":"Stripe"}]},"kind":"symbol","abstract":[{"text":"You can set this property to pre-fill any information you’ve already collected from your user. - seealso: STPUserInformation.h","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefilledInformation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","text":"STPUserInformation","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/prefilledInformation","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/prefilledInformation":{"kind":"symbol","abstract":[{"type":"text","text":"You can set this property to pre-fill any information you’ve already collected from your user. - seealso: STPUserInformation.h"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prefilledInformation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation","text":"STPUserInformation","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/prefilledinformation","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/prefilledInformation","role":"symbol","title":"prefilledInformation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prefilledInformation"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation":{"title":"STPUserInformation","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPUserInformation"}],"abstract":[{"type":"text","text":"You can use this class to specify information that you’ve already collected"},{"text":" ","type":"text"},{"type":"text","text":"from your user. You can then set the "},{"code":"prefilledInformation","type":"codeVoice"},{"type":"text","text":" property on"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPAddCardViewController"},{"text":", etc and it will pre-fill","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"this information whenever possible."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPUserInformation","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripe\/stpuserinformation"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"prefilledInformation"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"prefilledInformation"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","text":"STPUserInformation"},{"kind":"text","text":" * "},{"text":"prefilledInformation","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"STPAddCardViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPAddCardViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments"},{"op":"replace","value":"prefilledInformation","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1prefilledInformation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1prefilledInformation\/fragments","value":[{"kind":"identifier","text":"prefilledInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/title","value":"STPUserInformation"},{"value":[{"kind":"identifier","text":"STPUserInformation"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
