{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForHeaderInSection"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(im)tableView:heightForHeaderInSection:","modules":[{"name":"Stripe"}],"symbolKind":"method","navigatorTitle":[{"text":"tableView:heightForHeaderInSection:","kind":"identifier"}],"title":"tableView(_:heightForHeaderInSection:)","role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"heightForHeaderInSection"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"section"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:heightforheaderinsection:)"]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:heightforheaderinsection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:heightForHeaderInSection:)"},"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:heightForHeaderInSection:)":{"navigatorTitle":[{"text":"tableView:heightForHeaderInSection:","kind":"identifier"}],"title":"tableView(_:heightForHeaderInSection:)","url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:heightforheaderinsection:)","kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForHeaderInSection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:heightForHeaderInSection:)","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"title":"STPAddCardViewController","abstract":[{"type":"text","text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"}],"navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"tableView:heightForHeaderInSection:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"tableView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"heightForHeaderInSection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"section","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:heightForHeaderInSection:)\/title","value":"tableView:heightForHeaderInSection:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:heightForHeaderInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController"},{"value":[{"kind":"identifier","text":"STPAddCardViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments"}]}]}
