{"variants":[{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:cellforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:cellforrowat:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"title":"tableView(_:cellForRowAt:)","modules":[{"name":"Stripe"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(im)tableView:cellForRowAtIndexPath:"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:cellForRowAt:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tableView","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":":nodoc:"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:cellForRowAt:)":{"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForRowAt"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:cellforrowat:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:cellForRowAt:)","role":"symbol","title":"tableView(_:cellForRowAt:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"tableView:cellForRowAtIndexPath:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cellForRowAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController","op":"replace"},{"value":[{"kind":"identifier","text":"STPAddCardViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:cellForRowAt:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
