{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:estimatedheightforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:estimatedheightforrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"abstract":[{"text":":nodoc:","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"estimatedHeightForRowAt"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"metadata":{"title":"tableView(_:estimatedHeightForRowAt:)","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(im)tableView:estimatedHeightForRowAtIndexPath:","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"text":"estimatedHeightForRowAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"navigatorTitle":[{"text":"tableView:estimatedHeightForRowAtIndexPath:","kind":"identifier"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:estimatedHeightForRowAt:)"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:estimatedHeightForRowAt:)":{"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"estimatedHeightForRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:estimatedheightforrowat:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:estimatedHeightForRowAt:)","role":"symbol","title":"tableView(_:estimatedHeightForRowAt:)","type":"topic","navigatorTitle":[{"text":"tableView:estimatedHeightForRowAtIndexPath:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"tableView:estimatedHeightForRowAtIndexPath:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:estimatedHeightForRowAtIndexPath:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"estimatedHeightForRowAtIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPAddCardViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","value":[{"text":"STPAddCardViewController","kind":"identifier"}]},{"value":"tableView:estimatedHeightForRowAtIndexPath:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:estimatedHeightForRowAt:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:estimatedHeightForRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:estimatedHeightForRowAtIndexPath:","kind":"identifier"}]}]}]}
