{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/updateAppearance()"},"abstract":[{"type":"text","text":":nodoc:"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(im)updateAppearance","navigatorTitle":[{"kind":"identifier","text":"updateAppearance"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateAppearance","kind":"identifier"},{"kind":"text","text":"()"}],"title":"updateAppearance()","roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"role":"symbol","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateAppearance","kind":"identifier"},{"kind":"text","text":"()"}]}]}],"variants":[{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/updateappearance()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/updateappearance()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/updateAppearance()":{"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateAppearance","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/updateAppearance()","url":"\/documentation\/stripe\/stpaddcardviewcontroller\/updateappearance()","role":"symbol","title":"updateAppearance()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateAppearance"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"updateAppearance"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updateAppearance","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateAppearance"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPAddCardViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewController"}]},{"value":"updateAppearance","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1updateAppearance()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1updateAppearance()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateAppearance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
