{"abstract":[{"text":":nodoc:","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewWillTransition(to:with:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"text":"size","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"coordinator"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/viewwilltransition(to:with:)"]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller\/viewwilltransition(to:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"viewWillTransition(to:with:)","externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController(im)viewWillTransitionToSize:withTransitionCoordinator:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillTransition"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewControllerTransitionCoordinator","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/viewWillTransition(to:with:)":{"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/viewwilltransition(to:with:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewWillTransition(to:with:)","role":"symbol","title":"viewWillTransition(to:with:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewWillTransitionToSize:"},{"text":"(","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"size"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withTransitionCoordinator:"},{"text":"(","kind":"text"},{"text":"id<UIViewControllerTransitionCoordinator>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"coordinator","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAddCardViewController"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1viewWillTransition(to:with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
