{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPIntentActionBoletoDisplayDetails(py)expiresAt","title":"expiresAt","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"expiresAt","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/expiresAt"},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/expiresat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/expiresat"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The expiry date of the boleto voucher."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"title":"STPIntentActionBoletoDisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails","url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails","type":"topic","abstract":[{"text":"Contains Boleto details necessary for the customer to complete the payment.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails/expiresAt":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/expiresAt","abstract":[{"text":"The expiry date of the boleto voucher.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"expiresAt"}],"title":"expiresAt","type":"topic","url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/expiresat","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"expiresAt","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"expiresAt","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"expiresAt"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPIntentActionBoletoDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/navigatorTitle","op":"replace"},{"value":"expiresAt","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1expiresAt\/title","op":"replace"},{"value":[{"text":"expiresAt","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1expiresAt\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}