{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/amounts"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amounts","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmicrodeposittype\/amounts"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmicrodeposittype\/amounts"]}],"sections":[],"abstract":[{"text":"Two non-unique micro-deposits to the customer’s bank account","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"amounts"}],"externalID":"c:@M@StripePayments@E@STPMicrodepositType@STPMicrodepositTypeAmounts","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"STPMicrodepositTypeAmounts","kind":"identifier"}],"title":"STPMicrodepositType.amounts"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType":{"url":"\/documentation\/stripepayments\/stpmicrodeposittype","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPMicrodepositType","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType","abstract":[],"navigatorTitle":[{"text":"STPMicrodepositType","kind":"identifier"}],"title":"STPMicrodepositType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/amounts":{"navigatorTitle":[{"text":"STPMicrodepositTypeAmounts","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"amounts"}],"type":"topic","kind":"symbol","abstract":[{"text":"Two non-unique micro-deposits to the customer’s bank account","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/amounts","url":"\/documentation\/stripepayments\/stpmicrodeposittype\/amounts","title":"STPMicrodepositType.amounts"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPMicrodepositTypeAmounts","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPMicrodepositTypeAmounts","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPMicrodepositTypeAmounts","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"STPMicrodepositType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/title"},{"value":[{"text":"STPMicrodepositType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/navigatorTitle","value":[{"kind":"identifier","text":"STPMicrodepositType"}]},{"op":"replace","value":"STPMicrodepositTypeAmounts","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1amounts\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1amounts\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPMicrodepositTypeAmounts"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}