{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpmicrodeposittype\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/CustomStringConvertible-Implementations"},"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"title":"CustomStringConvertible Implementations","role":"collectionGroup","roleHeading":"API Collection"},"kind":"article","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/description":{"title":"description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/description","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpmicrodeposittype\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType":{"title":"STPMicrodepositType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMicrodepositType","kind":"identifier"}],"navigatorTitle":[{"text":"STPMicrodepositType","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType","type":"topic","url":"\/documentation\/stripepayments\/stpmicrodeposittype","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"STPMicrodepositType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/title","op":"replace"},{"value":[{"text":"STPMicrodepositType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPMicrodepositType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}