{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/descriptorCode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmicrodeposittype\/descriptorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmicrodeposittype\/descriptorcode"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPMicrodepositTypeDescriptorCode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptorCode"}],"symbolKind":"case","title":"STPMicrodepositType.descriptorCode","externalID":"c:@M@StripePayments@E@STPMicrodepositType@STPMicrodepositTypeDescriptorCode","roleHeading":"Case"},"abstract":[{"type":"text","text":"A single micro-deposit sent to the customer’s bank account with a unique descriptor code"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"descriptorCode"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/descriptorCode":{"url":"\/documentation\/stripepayments\/stpmicrodeposittype\/descriptorcode","type":"topic","kind":"symbol","role":"symbol","title":"STPMicrodepositType.descriptorCode","abstract":[{"type":"text","text":"A single micro-deposit sent to the customer’s bank account with a unique descriptor code"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"descriptorCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPMicrodepositTypeDescriptorCode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/descriptorCode"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType":{"title":"STPMicrodepositType","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMicrodepositType"}],"type":"topic","url":"\/documentation\/stripepayments\/stpmicrodeposittype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPMicrodepositType"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPMicrodepositTypeDescriptorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPMicrodepositTypeDescriptorCode","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPMicrodepositTypeDescriptorCode","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1descriptorCode\/title","op":"replace","value":"STPMicrodepositTypeDescriptorCode"},{"value":[{"kind":"identifier","text":"STPMicrodepositTypeDescriptorCode"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1descriptorCode\/fragments","op":"replace"},{"op":"replace","value":"STPMicrodepositType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/fragments","value":[{"text":"STPMicrodepositType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/navigatorTitle","value":[{"text":"STPMicrodepositType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}