{"abstract":[{"text":"This is an unknown type that’s been added since the SDK","type":"text"},{"text":" ","type":"text"},{"text":"was last updated.","type":"text"},{"text":" ","type":"text"},{"text":"Update your SDK, or use the ","type":"text"},{"type":"codeVoice","code":"allResponseFields"},{"text":" ","type":"text"},{"text":"for custom handling.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmicrodeposittype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmicrodeposittype\/unknown"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/unknown"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","modules":[{"name":"StripePayments"}],"title":"STPMicrodepositType.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"STPMicrodepositTypeUnknown","kind":"identifier"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPMicrodepositType@STPMicrodepositTypeUnknown"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType":{"kind":"symbol","abstract":[],"role":"symbol","title":"STPMicrodepositType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMicrodepositType"}],"url":"\/documentation\/stripepayments\/stpmicrodeposittype","navigatorTitle":[{"kind":"identifier","text":"STPMicrodepositType"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/unknown":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/unknown","abstract":[{"type":"text","text":"This is an unknown type that’s been added since the SDK"},{"type":"text","text":" "},{"type":"text","text":"was last updated."},{"type":"text","text":" "},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"allResponseFields"},{"type":"text","text":" "},{"type":"text","text":"for custom handling."}],"role":"symbol","title":"STPMicrodepositType.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"url":"\/documentation\/stripepayments\/stpmicrodeposittype\/unknown","navigatorTitle":[{"kind":"identifier","text":"STPMicrodepositTypeUnknown"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPMicrodepositTypeUnknown","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPMicrodepositTypeUnknown","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPMicrodepositTypeUnknown"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPMicrodepositType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/title"},{"op":"replace","value":[{"text":"STPMicrodepositType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/fragments"},{"op":"replace","value":[{"text":"STPMicrodepositType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/navigatorTitle"},{"op":"replace","value":"STPMicrodepositTypeUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1unknown\/title"},{"op":"replace","value":[{"text":"STPMicrodepositTypeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1unknown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}