{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"StripePayments"}],"title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirmParams(im)init","symbolKind":"method"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodaffirmparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirmParams\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirmParams"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAffirmParams/init":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirmParams\/init","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodaffirmparams\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAffirmParams":{"navigatorTitle":[{"text":"STPPaymentMethodAffirmParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create an Affirm Payment Method","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirmParams","kind":"symbol","title":"STPPaymentMethodAffirmParams","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAffirmParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodaffirmparams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirmParams\/title","value":"STPPaymentMethodAffirmParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirmParams\/fragments","value":[{"text":"STPPaymentMethodAffirmParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirmParams\/navigatorTitle","value":[{"text":"STPPaymentMethodAffirmParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}