{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","text":"STPApplePayContext"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus","text":"STPPaymentStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"role":"symbol","required":true,"modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(pl)STPApplePayContextDelegate(im)applePayContext:didCompleteWithStatus:error:","navigatorTitle":[{"text":"applePayContext:didCompleteWithStatus:error:","kind":"identifier"}],"roleHeading":"Instance Method","title":"applePayContext(_:didCompleteWith:error:)","symbolKind":"method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(applePayContext:didCompleteWithStatus:error:) "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"attribute","text":"@preconcurrency"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"context","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","text":"STPApplePayContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentStatus","text":"STPPaymentStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}]}]},{"kind":"parameters","parameters":[{"name":"status","content":[{"inlineContent":[{"text":"The status of the payment","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The error that occurred, if any.","type":"text"}]}],"name":"error"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpapplepaycontextdelegate\/applepaycontext(_:didcompletewith:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpapplepaycontextdelegate\/applepaycontext(_:didcompletewith:error:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCompleteWith:error:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Called after the Apple Pay sheet is dismissed with the result of the payment.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Your implementation could stop a spinner and display a receipt view or error to the customer, for example."}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContext":{"url":"\/documentation\/stripe\/stpapplepaycontext","role":"symbol","abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"text":" ","type":"text"},{"text":"Usage looks like this:","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContext","kind":"identifier"}],"type":"topic","kind":"symbol","title":"STPApplePayContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContext","navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContextDelegate":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripe\/stpapplepaycontextdelegate","navigatorTitle":[{"text":"STPApplePayContextDelegate","kind":"identifier"}],"title":"STPApplePayContextDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPApplePayContextDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate","abstract":[{"type":"text","text":"Implement the required methods of this delegate to supply a PaymentIntent to STPApplePayContext and be notified of the completion of the Apple Pay payment."},{"type":"text","text":" "},{"type":"text","text":"You may also implement the optional delegate methods to handle shipping methods and shipping address changes e.g. to verify you can ship to the address, or update the payment amount."}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","abstract":[],"type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContextDelegate/applePayContext(_:didCompleteWith:error:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripe\/stpapplepaycontextdelegate\/applepaycontext(_:didcompletewith:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"applePayContext","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","text":"STPApplePayContext"},{"kind":"text","text":", "},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"title":"applePayContext(_:didCompleteWith:error:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCompleteWith:error:)","abstract":[{"text":"Called after the Apple Pay sheet is dismissed with the result of the payment.","type":"text"},{"type":"text","text":" "},{"text":"Your implementation could stop a spinner and display a receipt view or error to the customer, for example.","type":"text"}],"required":true,"navigatorTitle":[{"text":"applePayContext:didCompleteWithStatus:error:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentStatus":{"kind":"symbol","title":"STPPaymentStatus","abstract":[{"type":"text","text":"An enum representing the status of a payment requested from the user."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentStatus","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentStatus","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentStatus","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"applePayContext:didCompleteWithStatus:error:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"applePayContext:didCompleteWithStatus:error:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"applePayContext:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","text":"STPApplePayContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContext","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"context"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCompleteWithStatus:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus","text":"STPPaymentStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"status","content":[{"inlineContent":[{"text":"The status of the payment","type":"text"}],"type":"paragraph"}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"The error that occurred, if any.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/title","value":"STPApplePayContextDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/fragments","value":[{"text":"STPApplePayContextDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPApplePayContextDelegate"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate~1applePayContext(_:didCompleteWith:error:)\/title","value":"applePayContext:didCompleteWithStatus:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate~1applePayContext(_:didCompleteWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"applePayContext:didCompleteWithStatus:error:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}