{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"Called after the customer has authorized Apple Pay.  Implement this method to call the completion block with the client secret of a PaymentIntent or SetupIntent.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(applePayContext:didCreatePaymentMethod:paymentInformation:completion:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"context"},{"kind":"text","text":": "},{"text":"STPApplePayContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContext"},{"text":", ","kind":"text"},{"text":"didCreatePaymentMethod","kind":"externalParam"},{"kind":"text","text":" "},{"text":"paymentMethod","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"text":", ","kind":"text"},{"text":"paymentInformation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PKPayment","kind":"typeIdentifier","text":"PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIntentClientSecretCompletionBlock","preciseIdentifier":"s:14StripeApplePay36STPIntentClientSecretCompletionBlocka","kind":"typeIdentifier","text":"STPIntentClientSecretCompletionBlock"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The PaymentMethod that represents the customer’s Apple Pay payment method.","type":"text"},{"text":" ","type":"text"},{"text":"If you create the PaymentIntent with confirmation_method=manual, pass ","type":"text"},{"type":"codeVoice","code":"paymentMethod.stripeId"},{"text":" as the payment_method and confirm=true. Otherwise, you can ignore this parameter.","type":"text"}]}],"name":"paymentMethod"},{"content":[{"inlineContent":[{"text":"The underlying PKPayment created by Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If you create the PaymentIntent with confirmation_method=manual, you can collect shipping information using its "},{"code":"shippingContact","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"shippingMethod"},{"text":" properties.","type":"text"}],"type":"paragraph"}],"name":"paymentInformation"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Call this with the PaymentIntent or SetupIntent client secret, or the error that occurred creating the PaymentIntent or SetupIntent.","type":"text"}]}],"name":"completion"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate"]]},"variants":[{"paths":["\/documentation\/stripe\/stpapplepaycontextdelegate\/applepaycontext(_:didcreatepaymentmethod:paymentinformation:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpapplepaycontextdelegate\/applepaycontext(_:didcreatepaymentmethod:paymentinformation:completion:)"]}],"kind":"symbol","metadata":{"required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","text":"STPApplePayContext"},{"text":", ","kind":"text"},{"text":"didCreatePaymentMethod","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKPayment","kind":"typeIdentifier","text":"PKPayment"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentClientSecretCompletionBlock","preciseIdentifier":"s:14StripeApplePay36STPIntentClientSecretCompletionBlocka"},{"kind":"text","text":")"}],"title":"applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(pl)STPApplePayContextDelegate(im)applePayContext:didCreatePaymentMethod:paymentInformation:completion:","navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}],"role":"symbol","roleHeading":"Instance Method"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContextDelegate":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate","navigatorTitle":[{"text":"STPApplePayContextDelegate","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPApplePayContextDelegate","kind":"identifier"}],"title":"STPApplePayContextDelegate","role":"symbol","url":"\/documentation\/stripe\/stpapplepaycontextdelegate","abstract":[{"type":"text","text":"Implement the required methods of this delegate to supply a PaymentIntent to STPApplePayContext and be notified of the completion of the Apple Pay payment."},{"text":" ","type":"text"},{"text":"You may also implement the optional delegate methods to handle shipping methods and shipping address changes e.g. to verify you can ship to the address, or update the payment amount.","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContext":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContext","url":"\/documentation\/stripe\/stpapplepaycontext","type":"topic","title":"STPApplePayContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPApplePayContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"text":" ","type":"text"},{"type":"text","text":"Usage looks like this:"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethod":{"abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"url":"\/documentation\/stripe\/stppaymentmethod","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethod","kind":"identifier"}],"type":"topic","title":"STPPaymentMethod","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","type":"topic","role":"collection","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPIntentClientSecretCompletionBlock":{"title":"STPIntentClientSecretCompletionBlock","abstract":[{"text":"A block to be run with the client secret of a PaymentIntent or SetupIntent.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIntentClientSecretCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPIntentClientSecretCompletionBlock","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripe\/stpintentclientsecretcompletionblock","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentClientSecretCompletionBlock"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContextDelegate/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"applePayContext","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext"},{"text":", ","kind":"text"},{"text":"didCreatePaymentMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"paymentInformation"},{"text":": ","kind":"text"},{"text":"PKPayment","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPayment"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPIntentClientSecretCompletionBlock","preciseIdentifier":"s:14StripeApplePay36STPIntentClientSecretCompletionBlocka"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Called after the customer has authorized Apple Pay.  Implement this method to call the completion block with the client secret of a PaymentIntent or SetupIntent."}],"title":"applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","url":"\/documentation\/stripe\/stpapplepaycontextdelegate\/applepaycontext(_:didcreatepaymentmethod:paymentinformation:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"applePayContext:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","kind":"typeIdentifier","text":"STPApplePayContext"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didCreatePaymentMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod"},{"text":" *) ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentInformation:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPayment","text":"PKPayment"},{"text":" *) ","kind":"text"},{"text":"paymentInformation","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"paymentMethod","content":[{"inlineContent":[{"text":"The PaymentMethod that represents the customer’s Apple Pay payment method.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If you create the PaymentIntent with confirmation_method=manual, pass "},{"type":"codeVoice","code":"paymentMethod.stripeId"},{"type":"text","text":" as the payment_method and confirm=true. Otherwise, you can ignore this parameter."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The underlying PKPayment created by Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If you create the PaymentIntent with confirmation_method=manual, you can collect shipping information using its "},{"code":"shippingContact","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"shippingMethod"},{"type":"text","text":" properties."}]}],"name":"paymentInformation"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Call this with the PaymentIntent or SetupIntent client secret, or the error that occurred creating the PaymentIntent or SetupIntent."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/title","value":"STPApplePayContextDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/fragments","value":[{"kind":"identifier","text":"STPApplePayContextDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"STPApplePayContextDelegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate~1applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)\/title","op":"replace","value":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate~1applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:","kind":"identifier"}]}]}]}