{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams"]]},"sections":[],"kind":"symbol","metadata":{"title":"init","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibancoParams(im)init","modules":[{"name":"StripePayments"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/init","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodmultibancoparams\/init"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibancoParams/init":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/init","url":"\/documentation\/stripepayments\/stppaymentmethodmultibancoparams\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibancoParams":{"type":"topic","title":"STPPaymentMethodMultibancoParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodMultibancoParams"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams","abstract":[{"text":"An object representing parameters used to create a Multibanco Payment Method","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodMultibancoParams"}],"url":"\/documentation\/stripepayments\/stppaymentmethodmultibancoparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentMethodMultibancoParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/title"},{"value":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/fragments"},{"value":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/navigatorTitle"}]}]}