{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBank\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBank(cm)decodedObjectFromAPIResponse:","symbolKind":"method","role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"title":"decodedObject(fromAPIResponse:)","modules":[{"name":"StripePayments"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodpaybybank\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodpaybybank\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBank"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayByBank":{"role":"symbol","title":"STPPaymentMethodPayByBank","url":"\/documentation\/stripepayments\/stppaymentmethodpaybybank","abstract":[{"type":"text","text":"The Pay by Bank Payment Method."}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPayByBank","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodPayByBank","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBank"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayByBank/decodedObject(fromAPIResponse:)":{"role":"symbol","title":"decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stppaymentmethodpaybybank\/decodedobject(fromapiresponse:)","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBank\/decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBank\/title","op":"replace","value":"STPPaymentMethodPayByBank"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBank\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodPayByBank"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBank\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodPayByBank"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBank~1decodedObject(fromAPIResponse:)\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBank~1decodedObject(fromAPIResponse:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}