{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(dismissWithCompletion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCompletion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPVoidBlock-2384d","preciseIdentifier":"s:14StripePayments12STPVoidBlocka","text":"STPVoidBlock"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback to run after the view controller is dismissed. You may specify nil for this parameter."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/dismiss(withcompletion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/dismiss(withcompletion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/dismiss(withCompletion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If you’re pushing "},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" onto an existing "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"‘s stack, you should use this method to dismiss it, since it may have pushed an additional shipping method view controller onto the navigation controller’s stack."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCompletion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"kind":"text","text":"?)"}],"title":"dismiss(withCompletion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPShippingAddressViewController(im)dismissWithCompletion:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/dismiss(withCompletion:)":{"role":"symbol","title":"dismiss(withCompletion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCompletion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"If you’re pushing "},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" onto an existing "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"‘s stack, you should use this method to dismiss it, since it may have pushed an additional shipping method view controller onto the navigation controller’s stack."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/dismiss(withCompletion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/dismiss(withcompletion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPVoidBlock-2384d":{"role":"symbol","title":"STPVoidBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPVoidBlock"}],"abstract":[{"type":"text","text":"An empty block, called with no arguments, returning nothing."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPVoidBlock-2384d","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPVoidBlock"}],"url":"\/documentation\/stripe\/stpvoidblock-2384d"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"role":"symbol","title":"STPShippingAddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewController"}],"abstract":[{"type":"text","text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dismissWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissWithCompletion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dismissWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1dismiss(withCompletion:)\/title","value":"dismissWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1dismiss(withCompletion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","value":"STPShippingAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
