{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:) "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","text":"STPTheme"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selectedShippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"prefilledInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation","text":"STPUserInformation"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration to use (this determines the required shipping address fields and shipping type). - seealso: STPPaymentConfiguration"}]}]},{"name":"theme","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The theme to use to inform the view controller’s visual appearance. - seealso: STPTheme"}]}]},{"name":"currency","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The currency to use when displaying amounts for shipping methods. The default is USD."}]}]},{"name":"shippingAddress","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set, the shipping address view controller will be pre-filled with this address. - seealso: STPAddress"}]}]},{"name":"selectedShippingMethod","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set, the shipping methods view controller will use this method as the selected shipping method. If "},{"type":"codeVoice","code":"selectedShippingMethod"},{"type":"text","text":" is nil, the first shipping method in the array of methods returned by your delegate will be selected."}]}]},{"name":"prefilledInformation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If set, the shipping address view controller will be pre-filled with this information. - seealso: STPUserInformation"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/init(configuration:theme:currency:shippingaddress:selectedshippingmethod:prefilledinformation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/init(configuration:theme:currency:shippingaddress:selectedshippingmethod:prefilledinformation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPShippingAddressCardViewController"},{"type":"text","text":" with the provided parameters."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selectedShippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"prefilledInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPUserInformation","preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation"},{"kind":"text","text":"?)"}],"title":"init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@Stripe@objc(cs)STPShippingAddressViewController(im)initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"role":"symbol","title":"STPPaymentConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentConfiguration"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"type":"text","text":"You provide an "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" object to your "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" "},{"type":"text","text":"when making a charge. The configuration generally has settings that"},{"type":"text","text":" "},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"url":"\/documentation\/stripe\/stppaymentconfiguration"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"role":"symbol","title":"STPAddress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}],"url":"\/documentation\/stripe\/stpaddress"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation":{"role":"symbol","title":"STPUserInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPUserInformation"}],"abstract":[{"type":"text","text":"You can use this class to specify information that you’ve already collected"},{"type":"text","text":" "},{"type":"text","text":"from your user. You can then set the "},{"type":"codeVoice","code":"prefilledInformation"},{"type":"text","text":" property on"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":", etc and it will pre-fill"},{"type":"text","text":" "},{"type":"text","text":"this information whenever possible."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPUserInformation"}],"url":"\/documentation\/stripe\/stpuserinformation"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"role":"symbol","title":"STPTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTheme"}],"abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}],"url":"\/documentation\/stripe\/stptheme"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)":{"role":"symbol","title":"init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selectedShippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"prefilledInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPUserInformation","preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPShippingAddressCardViewController"},{"type":"text","text":" with the provided parameters."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/init(configuration:theme:currency:shippingaddress:selectedshippingmethod:prefilledinformation:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"role":"symbol","title":"STPShippingAddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewController"}],"abstract":[{"type":"text","text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","text":"STPTheme"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"theme"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"currency"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"shippingAddress"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedShippingMethod:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"selectedShippingMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefilledInformation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation","text":"STPUserInformation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"prefilledInformation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"kind":"identifier","text":"STPPaymentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/title","value":"STPUserInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/fragments","value":[{"kind":"identifier","text":"STPUserInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","value":"STPTheme"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","value":[{"kind":"identifier","text":"STPTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)\/title","value":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","value":"STPShippingAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
