{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithPaymentContext:) "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","text":"STPPaymentContext"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"paymentContext","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The payment context to use."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/init(paymentcontext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/init(paymentcontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(paymentContext:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" with the given payment context and sets the payment context as its delegate."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"kind":"text","text":")"}],"title":"init(paymentContext:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@Stripe@objc(cs)STPShippingAddressViewController(im)initWithPaymentContext:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPaymentContext:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContext"}],"url":"\/documentation\/stripe\/stppaymentcontext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/init(paymentContext:)":{"role":"symbol","title":"init(paymentContext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" with the given payment context and sets the payment context as its delegate."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(paymentContext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPaymentContext:"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/init(paymentcontext:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"role":"symbol","title":"STPShippingAddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewController"}],"abstract":[{"type":"text","text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPaymentContext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentContext:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPaymentContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","text":"STPPaymentContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"paymentContext"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init(paymentContext:)\/title","value":"initWithPaymentContext:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init(paymentContext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","value":"STPShippingAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}