{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"UITableViewDataSource Implementations","role":"collectionGroup","modules":[{"name":"Stripe"}]},"kind":"article","variants":[{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/uitableviewdatasource-implementations"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/UITableViewDataSource-Implementations"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/numberOfSections(in:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:numberOfRowsInSection:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller","title":"STPShippingAddressViewController","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPShippingAddressViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"navigatorTitle":[{"text":"STPShippingAddressViewController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/tableView(_:numberOfRowsInSection:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:numberOfRowsInSection:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"text":", ","kind":"text"},{"text":"numberOfRowsInSection","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/tableview(_:numberofrowsinsection:)","abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"title":"tableView(_:numberOfRowsInSection:)","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/tableView(_:cellForRowAt:)":{"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/tableview(_:cellforrowat:)","title":"tableView(_:cellForRowAt:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:cellForRowAt:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/numberOfSections(in:)":{"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/numberofsections(in:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"numberOfSectionsInTableView:"}],"title":"numberOfSections(in:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/numberOfSections(in:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSections"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/numberOfSections(in:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:numberOfRowsInSection:)"]}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","op":"replace","value":"STPShippingAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"text":"STPShippingAddressViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1tableView(_:numberOfRowsInSection:)\/fragments"},{"value":"tableView:cellForRowAtIndexPath:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1tableView(_:cellForRowAt:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1tableView(_:cellForRowAt:)\/fragments"},{"value":"numberOfSectionsInTableView:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1numberOfSections(in:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1numberOfSections(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInTableView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
