{"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"c:@M@Stripe@objc(cs)STPShippingAddressViewController(im)viewDidAppear:","role":"symbol","modules":[{"name":"Stripe"}],"title":"viewDidAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"]]},"abstract":[{"type":"text","text":":nodoc:"}],"variants":[{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/viewdidappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller\/viewdidappear(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidAppear"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"animated","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/viewDidAppear(_:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/viewDidAppear(_:)":{"role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"title":"viewDidAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/viewDidAppear(_:)","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/viewdidappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"type":"topic","abstract":[{"text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"title":"STPShippingAddressViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPShippingAddressViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"viewDidAppear:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidAppear:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1viewDidAppear(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","value":"STPShippingAddressViewController","op":"replace"},{"value":[{"text":"STPShippingAddressViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","op":"replace"}]}]}
