{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/Coordinator","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/SQ","doc:\/\/com.stripe.stripe-payments-ui\/SH","doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/Coordinator\/paymentCardTextFieldDidChange(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable\/coordinator"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"modules":[{"name":"StripePaymentsUI"}],"title":"STPPaymentCardTextField.Representable.Coordinator","externalID":"s:16StripePaymentsUI23STPPaymentCardTextFieldC13RepresentableV11CoordinatorC","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"symbolKind":"class"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIViewRepresentable.Coordinator"},{"text":".","type":"text"}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextField"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"text":" ","type":"text"},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"text":" ","type":"text"},{"text":"multiple UITextFields under the hood to collect this information. It’s","type":"text"},{"text":" ","type":"text"},{"text":"designed to fit on a single line, and from a design perspective can be used","type":"text"},{"text":" ","type":"text"},{"text":"anywhere a UITextField would be appropriate.","type":"text"}],"title":"STPPaymentCardTextField","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","role":"symbol","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","type":"topic","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments-ui/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/Representable/Coordinator":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/Coordinator","abstract":[],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable\/coordinator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinator"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"title":"STPPaymentCardTextField.Representable.Coordinator"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/Representable/Coordinator/paymentCardTextFieldDidChange(_:)":{"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable\/coordinator\/paymentcardtextfielddidchange(_:)","kind":"symbol","type":"topic","title":"paymentCardTextFieldDidChange(_:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/Coordinator\/paymentCardTextFieldDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when either the card number, expiration, or CVC changes. At this point,"},{"type":"text","text":" "},{"type":"text","text":"one can call "},{"type":"codeVoice","code":"isValid"},{"type":"text","text":" on the text field to determine, for example,"},{"type":"text","text":" "},{"type":"text","text":"whether or not to enable a button to submit the form. Example:"}]},"doc://com.stripe.stripe-payments-ui/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments-ui/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/Representable":{"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Representable"}],"title":"STPPaymentCardTextField.Representable","abstract":[{"text":"A SwiftUI representation of an STPPaymentCardTextField.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Representable"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","navigatorTitle":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"abstract":[{"text":"This protocol allows a delegate to be notified when a payment text field’s","type":"text"},{"text":" ","type":"text"},{"text":"contents change, which can in turn be used to take further actions depending","type":"text"},{"text":" ","type":"text"},{"text":"on the validity of its contents.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","title":"STPPaymentCardTextFieldDelegate"},"doc://com.stripe.stripe-payments-ui/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","title":"Swift.Sendable"}},"variantOverrides":[{"patch":[{"value":"STPPaymentCardTextField","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title"},{"value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"},{"value":"STPPaymentCardTextFieldDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}