{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.fileExporterFilenameLabel(_:)"},{"type":"text","text":"."}],"metadata":{"title":"fileExporterFilenameLabel(_:)","roleHeading":"Instance Method","role":"symbol","extendedModule":"SwiftUICore","platforms":[{"unavailable":false,"introducedAt":"17.0","beta":false,"deprecated":false,"name":"iOS"},{"unavailable":false,"introducedAt":"17.0","beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"17.0","beta":false,"deprecated":false,"name":"Mac Catalyst"},{"unavailable":false,"introducedAt":"14.0","beta":false,"deprecated":false,"name":"macOS"}],"externalID":"s:7SwiftUI4ViewPAAE25fileExporterFilenameLabelyQr10Foundation23LocalizedStringResourceVF::SYNTHESIZED::s:16StripePaymentsUI23STPPaymentCardTextFieldC13RepresentableV","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileExporterFilenameLabel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation23LocalizedStringResourceV","text":"LocalizedStringResource"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"modules":[{"relatedModules":["SwiftUICore"],"name":"StripePaymentsUI"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/fileExporterFilenameLabel(_:)-6tziq"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable\/fileexporterfilenamelabel(_:)-6tziq"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileExporterFilenameLabel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"label","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"LocalizedStringResource","preciseIdentifier":"s:10Foundation23LocalizedStringResourceV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":"\n"}]}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/Representable":{"abstract":[{"text":"A SwiftUI representation of an STPPaymentCardTextField.","type":"text"}],"role":"symbol","title":"STPPaymentCardTextField.Representable","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Representable"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable","navigatorTitle":[{"text":"Representable","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"text":" ","type":"text"},{"text":"multiple UITextFields under the hood to collect this information. It’s","type":"text"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"text":"anywhere a UITextField would be appropriate.","type":"text"}],"title":"STPPaymentCardTextField","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentCardTextField","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/Representable/fileExporterFilenameLabel(_:)-6tziq":{"title":"fileExporterFilenameLabel(_:)","abstract":[],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/fileExporterFilenameLabel(_:)-6tziq","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable\/fileexporterfilenamelabel(_:)-6tziq","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileExporterFilenameLabel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LocalizedStringResource","preciseIdentifier":"s:10Foundation23LocalizedStringResourceV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]}]}]}