{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"View.scrollInputBehavior(_:for:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable\/scrollinputbehavior(_:for:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","modules":[{"relatedModules":["SwiftUICore"],"name":"StripePaymentsUI"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollInputBehavior","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ScrollInputBehavior","preciseIdentifier":"s:7SwiftUI19ScrollInputBehaviorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ScrollInputKind","preciseIdentifier":"s:7SwiftUI15ScrollInputKindV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"extendedModule":"SwiftUICore","title":"scrollInputBehavior(_:for:)","role":"symbol","symbolKind":"method","platforms":[{"deprecated":false,"unavailable":false,"beta":false,"name":"iOS","introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"Mac Catalyst","introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"macOS","introducedAt":"15.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"tvOS","introducedAt":"18.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"visionOS","introducedAt":"2.0"},{"deprecated":false,"unavailable":false,"beta":false,"name":"watchOS","introducedAt":"11.0"}],"externalID":"s:7SwiftUI4ViewPAAE19scrollInputBehavior_3forQrAA06ScrolleF0V_AA0hE4KindVtF::SYNTHESIZED::s:16StripePaymentsUI23STPPaymentCardTextFieldC13RepresentableV"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"attribute","text":"@preconcurrency"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollInputBehavior"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"behavior"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI19ScrollInputBehaviorV","kind":"typeIdentifier","text":"ScrollInputBehavior"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"input"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI15ScrollInputKindV","kind":"typeIdentifier","text":"ScrollInputKind"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"},{"kind":"text","text":"\n"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/scrollInputBehavior(_:for:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"type":"topic","role":"collection","kind":"symbol","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","role":"symbol","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"title":"STPPaymentCardTextField","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/Representable/scrollInputBehavior(_:for:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollInputBehavior","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ScrollInputBehavior","preciseIdentifier":"s:7SwiftUI19ScrollInputBehaviorV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ScrollInputKind","preciseIdentifier":"s:7SwiftUI15ScrollInputKindV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"title":"scrollInputBehavior(_:for:)","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable\/scrollinputbehavior(_:for:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/scrollInputBehavior(_:for:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/Representable":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Representable"}],"abstract":[{"type":"text","text":"A SwiftUI representation of an STPPaymentCardTextField."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Representable"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable","title":"STPPaymentCardTextField.Representable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPPaymentCardTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title"},{"op":"replace","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"op":"replace","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}