{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/cancel"},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Case","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType@STPThreeDSCustomizationButtonTypeCancel","title":"STPThreeDSCustomizationButtonType.cancel","symbolKind":"case","navigatorTitle":[{"text":"STPThreeDSCustomizationButtonTypeCancel","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/cancel"]},{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/cancel"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The cancel button type."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","abstract":[{"text":"An enum that defines the different types of buttons that are able to be customized.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"title":"STPThreeDSCustomizationButtonType","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/cancel":{"title":"STPThreeDSCustomizationButtonType.cancel","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/cancel","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/cancel","abstract":[{"text":"The cancel button type.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"}],"navigatorTitle":[{"text":"STPThreeDSCustomizationButtonTypeCancel","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"STPThreeDSCustomizationButtonTypeCancel","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeCancel"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPThreeDSCustomizationButtonTypeCancel","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"STPThreeDSCustomizationButtonType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments","value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1cancel\/title","value":"STPThreeDSCustomizationButtonTypeCancel","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1cancel\/fragments","op":"replace","value":[{"text":"STPThreeDSCustomizationButtonTypeCancel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}