{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"StripePayments"}],"title":"STPThreeDSCustomizationButtonType.continue","role":"symbol","externalID":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType@STPThreeDSCustomizationButtonTypeContinue","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`continue`","kind":"identifier"}],"navigatorTitle":[{"text":"STPThreeDSCustomizationButtonTypeContinue","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/continue","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"]]},"abstract":[{"type":"text","text":"The continue button type."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`continue`"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/continue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/continue"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/continue":{"abstract":[{"type":"text","text":"The continue button type."}],"title":"STPThreeDSCustomizationButtonType.continue","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/continue","kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/continue","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"`continue`","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeContinue"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","abstract":[{"text":"An enum that defines the different types of buttons that are able to be customized.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"title":"STPThreeDSCustomizationButtonType","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPThreeDSCustomizationButtonTypeContinue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeContinue"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPThreeDSCustomizationButtonTypeContinue","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1continue\/title","value":"STPThreeDSCustomizationButtonTypeContinue"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1continue\/fragments","value":[{"text":"STPThreeDSCustomizationButtonTypeContinue","kind":"identifier"}],"op":"replace"},{"value":"STPThreeDSCustomizationButtonType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments","value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}]}]}]}