{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/CustomStringConvertible-Implementations"},"metadata":{"title":"CustomStringConvertible Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"sections":[],"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/description"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/customstringconvertible-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"abstract":[{"text":"An enum that defines the different types of buttons that are able to be customized.","type":"text"}],"navigatorTitle":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"title":"STPThreeDSCustomizationButtonType","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/description":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/description","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/description","title":"description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPThreeDSCustomizationButtonType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments","value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}]},{"value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}