{"abstract":[{"text":"The next button type.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"next","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/next"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/next"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/next"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"]]},"kind":"symbol","sections":[],"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"next","kind":"identifier"}],"roleHeading":"Case","title":"STPThreeDSCustomizationButtonType.next","modules":[{"name":"StripePayments"}],"symbolKind":"case","navigatorTitle":[{"text":"STPThreeDSCustomizationButtonTypeNext","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType@STPThreeDSCustomizationButtonTypeNext"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/next":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/next","kind":"symbol","title":"STPThreeDSCustomizationButtonType.next","abstract":[{"type":"text","text":"The next button type."}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeNext"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/next","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"next"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"abstract":[{"type":"text","text":"An enum that defines the different types of buttons that are able to be customized."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","title":"STPThreeDSCustomizationButtonType","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPThreeDSCustomizationButtonTypeNext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeNext"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPThreeDSCustomizationButtonTypeNext","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1next\/title","value":"STPThreeDSCustomizationButtonTypeNext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1next\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeNext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title","value":"STPThreeDSCustomizationButtonType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle","value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}]}]}]}