{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The resend button type."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resend","kind":"identifier"}]}]}],"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resend"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeResend"}],"roleHeading":"Case","title":"STPThreeDSCustomizationButtonType.resend","externalID":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType@STPThreeDSCustomizationButtonTypeResend"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/resend"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/resend"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/resend"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"title":"STPThreeDSCustomizationButtonType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","abstract":[{"type":"text","text":"An enum that defines the different types of buttons that are able to be customized."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/resend":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/resend","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/resend","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeResend"}],"title":"STPThreeDSCustomizationButtonType.resend","type":"topic","abstract":[{"text":"The resend button type.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"resend"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPThreeDSCustomizationButtonTypeResend","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPThreeDSCustomizationButtonTypeResend","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"STPThreeDSCustomizationButtonTypeResend","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPThreeDSCustomizationButtonType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title"},{"value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle","op":"replace"},{"value":"STPThreeDSCustomizationButtonTypeResend","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1resend\/title","op":"replace"},{"value":[{"text":"STPThreeDSCustomizationButtonTypeResend","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1resend\/fragments","op":"replace"}]}]}