{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"]]},"abstract":[{"text":"The submit button type.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/submit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/submit"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType@STPThreeDSCustomizationButtonTypeSubmit","title":"STPThreeDSCustomizationButtonType.submit","roleHeading":"Case","modules":[{"name":"StripePayments"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPThreeDSCustomizationButtonTypeSubmit","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/submit"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"submit","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/submit":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/submit","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/submit","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeSubmit"}],"abstract":[{"type":"text","text":"The submit button type."}],"title":"STPThreeDSCustomizationButtonType.submit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"submit"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"abstract":[{"text":"An enum that defines the different types of buttons that are able to be customized.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","title":"STPThreeDSCustomizationButtonType","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPThreeDSCustomizationButtonTypeSubmit","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPThreeDSCustomizationButtonTypeSubmit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeSubmit"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPThreeDSCustomizationButtonTypeSubmit","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1submit\/title"},{"value":[{"text":"STPThreeDSCustomizationButtonTypeSubmit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1submit\/fragments"},{"value":"STPThreeDSCustomizationButtonType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title"},{"value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments"},{"value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle"}]}]}