{"abstract":[{"text":"Delegate method that is called when all of the form view’s required inputs","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"are complete or transition away from all being complete. These transitions"},{"type":"text","text":" "},{"type":"text","text":"correspond to "},{"type":"codeVoice","code":"cardForView.cardParams"},{"text":" returning a nil value or not.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate"]]},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformviewdelegate\/cardformview(_:didchangetostatecomplete:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformviewdelegate\/cardformview(_:didchangetostatecomplete:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","modules":[{"name":"StripePaymentsUI"}],"title":"cardFormView(_:didChangeToStateComplete:)","role":"symbol","navigatorTitle":[{"text":"cardFormView:didChangeToStateComplete:","kind":"identifier"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cardFormView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPCardFormView","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView"},{"kind":"text","text":", "},{"text":"didChangeToStateComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"externalID":"c:@M@StripePaymentsUI@objc(pl)STPCardFormViewDelegate(im)cardFormView:didChangeToStateComplete:","roleHeading":"Instance Method"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate\/cardFormView(_:didChangeToStateComplete:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cardFormView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"form","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","text":"STPCardFormView"},{"text":", ","kind":"text"},{"text":"didChangeToStateComplete","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"complete","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewDelegate/cardFormView(_:didChangeToStateComplete:)":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformviewdelegate\/cardformview(_:didchangetostatecomplete:)","abstract":[{"text":"Delegate method that is called when all of the form view’s required inputs","type":"text"},{"type":"text","text":" "},{"type":"text","text":"are complete or transition away from all being complete. These transitions"},{"text":" ","type":"text"},{"text":"correspond to ","type":"text"},{"code":"cardForView.cardParams","type":"codeVoice"},{"type":"text","text":" returning a nil value or not."}],"title":"cardFormView(_:didChangeToStateComplete:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cardFormView:didChangeToStateComplete:"}],"required":true,"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate\/cardFormView(_:didChangeToStateComplete:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardFormView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPCardFormView","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didChangeToStateComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewDelegate":{"abstract":[{"code":"STPCardFormViewDelegate","type":"codeVoice"},{"text":" defines the interface that should be adopted to receive","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"updates from "},{"code":"STPCardFormView","type":"codeVoice"},{"text":" instances.","type":"text"}],"title":"STPCardFormViewDelegate","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormViewDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformviewdelegate","navigatorTitle":[{"text":"STPCardFormViewDelegate","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"type":"topic","navigatorTitle":[{"text":"STPCardFormView","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" provides a multiline interface for users to input their"},{"text":" ","type":"text"},{"type":"text","text":"credit card details as well as billing postal code and provides an interface to access"},{"type":"text","text":" "},{"type":"text","text":"the created "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"text":" ","type":"text"},{"type":"text","text":"is displayed when invalid input is detected."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCardFormView","kind":"identifier"}],"title":"STPCardFormView","url":"\/documentation\/stripepaymentsui\/stpcardformview","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"cardFormView:didChangeToStateComplete:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cardFormView:didChangeToStateComplete:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"cardFormView:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView","text":"STPCardFormView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"form"},{"kind":"text","text":" "},{"text":"didChangeToStateComplete:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"complete"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"cardFormView:didChangeToStateComplete:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate~1cardFormView(_:didChangeToStateComplete:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cardFormView:didChangeToStateComplete:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate~1cardFormView(_:didChangeToStateComplete:)\/fragments"},{"value":"STPCardFormViewDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/fragments","value":[{"text":"STPCardFormViewDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView"},{"value":[{"text":"STPCardFormView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments"}]}]}
