{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressLine1Check"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult","text":"STPPaymentMethodCardCheckResult"},{"kind":"text","text":" { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"If a address line1 was provided, results of the check.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"inlineContent":[{"text":"Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using your secret key instead.","type":"text"}],"type":"paragraph"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardchecks\/addressline1check"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardchecks\/addressline1check"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks\/addressLine1Check","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addressLine1Check"}],"title":"addressLine1Check","platforms":[{"unavailable":false,"beta":false,"message":"Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using your secret key instead.","deprecated":true}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardChecks(py)addressLine1Check","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressLine1Check"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardCheckResult","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"role":"symbol","abstract":[{"text":"The result of a check on a Card address or CVC.","type":"text"}],"title":"STPPaymentMethodCardCheckResult"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardChecks","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks","navigatorTitle":[{"text":"STPPaymentMethodCardChecks","kind":"identifier"}],"title":"STPPaymentMethodCardChecks","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Checks on Card address and CVC."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks/addressLine1Check":{"deprecated":true,"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks\/addressline1check","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressLine1Check","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"addressLine1Check","kind":"identifier"}],"type":"topic","title":"addressLine1Check","abstract":[{"type":"text","text":"If a address line1 was provided, results of the check."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks\/addressLine1Check"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"deprecated":true,"unavailable":false}],"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"addressLine1Check"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"addressLine1Check","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult","text":"STPPaymentMethodCardCheckResult","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"addressLine1Check","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using your secret key instead.","type":"text"}]}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title","value":"STPPaymentMethodCardCheckResult"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments","value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/navigatorTitle","value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/title","value":"STPPaymentMethodCardChecks"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardChecks"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/navigatorTitle","value":[{"text":"STPPaymentMethodCardChecks","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks~1addressLine1Check\/title","value":"addressLine1Check"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks~1addressLine1Check\/fragments","value":[{"kind":"identifier","text":"addressLine1Check"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}