{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"addressPostalCodeCheck","navigatorTitle":[{"kind":"identifier","text":"addressPostalCodeCheck"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"addressPostalCodeCheck","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardChecks(py)addressPostalCodeCheck","platforms":[],"role":"symbol"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardchecks\/addresspostalcodecheck"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardchecks\/addresspostalcodecheck"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using your secret key instead."}],"type":"paragraph"}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"addressPostalCodeCheck","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult","text":"STPPaymentMethodCardCheckResult","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"If a address postal code was provided, results of the check."},{"type":"text","text":" "},{"text":"deprecated Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using yoursecret key instead.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks\/addressPostalCodeCheck"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks/addressPostalCodeCheck":{"navigatorTitle":[{"text":"addressPostalCodeCheck","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks\/addresspostalcodecheck","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addressPostalCodeCheck"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult"}],"kind":"symbol","role":"symbol","deprecated":false,"title":"addressPostalCodeCheck","abstract":[{"text":"If a address postal code was provided, results of the check.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"deprecated Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using yoursecret key instead."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks\/addressPostalCodeCheck"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCardChecks","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardChecks"}],"abstract":[{"text":"Checks on Card address and CVC.","type":"text"}],"type":"topic","title":"STPPaymentMethodCardChecks"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"abstract":[{"text":"The result of a check on a Card address or CVC.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"title":"STPPaymentMethodCardCheckResult","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"addressPostalCodeCheck"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"addressPostalCodeCheck"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodCardCheckResult","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult"},{"text":" ","kind":"text"},{"text":"addressPostalCodeCheck","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks~1addressPostalCodeCheck\/title","value":"addressPostalCodeCheck"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks~1addressPostalCodeCheck\/fragments","value":[{"kind":"identifier","text":"addressPostalCodeCheck"}],"op":"replace"},{"value":"STPPaymentMethodCardChecks","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/fragments","op":"replace","value":[{"text":"STPPaymentMethodCardChecks","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title","op":"replace","value":"STPPaymentMethodCardCheckResult"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments","op":"replace","value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}]}]}]}
