{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvcCheck"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardCheckResult","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult"},{"kind":"text","text":" { get }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardchecks\/cvccheck"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardchecks\/cvccheck"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks\/cvcCheck","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks"]]},"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"cvcCheck","modules":[{"name":"StripePayments"}],"symbolKind":"property","navigatorTitle":[{"text":"cvcCheck","kind":"identifier"}],"platforms":[{"unavailable":false,"message":"Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using your secret key instead.","beta":false,"deprecated":true}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cvcCheck","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardChecks(py)cvcCheck"},"abstract":[{"text":"If a CVC was provided, results of the check.","type":"text"},{"text":" ","type":"text"},{"text":"deprecated Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using yoursecret key instead.","type":"text"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using your secret key instead."}],"type":"paragraph"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardChecks"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardChecks"}],"abstract":[{"text":"Checks on Card address and CVC.","type":"text"}],"title":"STPPaymentMethodCardChecks","url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks","kind":"symbol","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"role":"symbol","title":"STPPaymentMethodCardCheckResult","url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of a check on a Card address or CVC."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks/cvcCheck":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvcCheck"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardCheckResult","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult"}],"abstract":[{"text":"If a CVC was provided, results of the check.","type":"text"},{"text":" ","type":"text"},{"text":"deprecated Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using yoursecret key instead.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks\/cvccheck","title":"cvcCheck","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks\/cvcCheck","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cvcCheck"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"beta":false,"deprecated":true,"unavailable":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"cvcCheck","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"cvcCheck","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult","text":"STPPaymentMethodCardCheckResult"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvcCheck"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Card check values are no longer returned to clients using publishable keys. Retrieve them on your server using your secret key instead.","type":"text"}]}],"op":"replace"},{"op":"replace","value":"STPPaymentMethodCardChecks","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardChecks"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodCardChecks","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodCardCheckResult","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/navigatorTitle"},{"op":"replace","value":"cvcCheck","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks~1cvcCheck\/title"},{"op":"replace","value":[{"kind":"identifier","text":"cvcCheck"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks~1cvcCheck\/fragments"}]}]}