{"abstract":[{"type":"text","text":":nodoc:"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodbacsdebit\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodbacsdebit\/description"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"description","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebit(py)description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebit"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebit\/description"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebit/description":{"url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebit\/description","abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","title":"description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebit\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebit":{"kind":"symbol","type":"topic","abstract":[{"text":"A Bacs Debit Payment Method.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebit","role":"symbol","title":"STPPaymentMethodBacsDebit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBacsDebit","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodBacsDebit","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebit~1description\/title","op":"replace","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebit~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebit\/title","value":"STPPaymentMethodBacsDebit","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebit\/fragments","value":[{"text":"STPPaymentMethodBacsDebit","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebit\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBacsDebit"}]}]}]}
