{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/cardId"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/cardid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/cardid"]}],"abstract":[{"type":"text","text":"The Stripe ID of the Issuing card object to retrieve details for."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams"]]},"metadata":{"modules":[{"name":"Stripe"}],"title":"cardId","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"cardId","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningDetailsParams(py)cardId"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","abstract":[],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams":{"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams","type":"topic","abstract":[{"text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API.","type":"text"},{"text":" ","type":"text"},{"text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"title":"STPPushProvisioningDetailsParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/cardId":{"kind":"symbol","role":"symbol","title":"cardId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/cardId","abstract":[{"text":"The Stripe ID of the Issuing card object to retrieve details for.","type":"text"}],"type":"topic","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/cardid","navigatorTitle":[{"text":"cardId","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"cardId","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"cardId","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"cardId","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPushProvisioningDetailsParams","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/fragments","op":"replace","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/navigatorTitle","op":"replace","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1cardId\/title","op":"replace","value":"cardId"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1cardId\/fragments","op":"replace","value":[{"text":"cardId","kind":"identifier"}]}]}]}