{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"certificatesBase64"}],"externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningDetailsParams(py)certificatesBase64","title":"certificatesBase64","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"certificatesBase64","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"Stripe"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Implemented for convenience - the Stripe API expects the certificate chain as an array of base64-encoded strings."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"certificatesBase64","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/certificatesbase64"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/certificatesbase64"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificatesBase64"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/certificatesBase64":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificatesBase64","navigatorTitle":[{"text":"certificatesBase64","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"certificatesBase64","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"type":"topic","title":"certificatesBase64","kind":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/certificatesbase64","role":"symbol","abstract":[{"type":"text","text":"Implemented for convenience - the Stripe API expects the certificate chain as an array of base64-encoded strings."}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","type":"topic","role":"collection","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams","navigatorTitle":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"type":"topic","title":"STPPushProvisioningDetailsParams","kind":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams","role":"symbol","abstract":[{"type":"text","text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"certificatesBase64"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"certificatesBase64"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"certificatesBase64","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1certificatesBase64\/title","op":"replace","value":"certificatesBase64"},{"value":[{"text":"certificatesBase64","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1certificatesBase64\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/title","value":"STPPushProvisioningDetailsParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/navigatorTitle","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}