{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificates","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"certificates"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"] { get }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","modules":[{"name":"Stripe"}],"roleHeading":"Instance Property","title":"certificates","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"certificates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"]","kind":"text"}],"externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningDetailsParams(py)certificates","navigatorTitle":[{"text":"certificates","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams"]]},"sections":[],"abstract":[{"type":"text","text":"An array of certificates that should be used to encrypt the card details."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/certificates"]},{"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/certificates"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams":{"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams","kind":"symbol","title":"STPPushProvisioningDetailsParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}],"abstract":[{"type":"text","text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class."}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"title":"Stripe","role":"collection","abstract":[],"url":"\/documentation\/stripe","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/certificates":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificates","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/certificates","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"certificates"},{"kind":"text","text":": ["},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"]"}],"title":"certificates","navigatorTitle":[{"text":"certificates","kind":"identifier"}],"abstract":[{"type":"text","text":"An array of certificates that should be used to encrypt the card details."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"certificates","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"certificates","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSData *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"certificates"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/title","op":"replace","value":"STPPushProvisioningDetailsParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/fragments","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1certificates\/title","value":"certificates"},{"value":[{"text":"certificates","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1certificates\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
