{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/init(cardid:certificates:nonce:noncesignature:)"]},{"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/init(cardid:certificates:nonce:noncesignature:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningDetailsParams(im)initWithCardId:certificates:nonce:nonceSignature:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cardId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"certificates"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nonceSignature","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":")"}],"modules":[{"name":"Stripe"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithCardId:certificates:nonce:nonceSignature:"}],"title":"init(cardId:certificates:nonce:nonceSignature:)"},"abstract":[{"text":"Instantiates a new params object with the provided attributes.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"cardId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"certificates"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"], ","kind":"text"},{"text":"nonce","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"nonceSignature","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/init(cardId:certificates:nonce:nonceSignature:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"title":"Stripe","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","abstract":[],"role":"collection","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/init(cardId:certificates:nonce:nonceSignature:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/init(cardId:certificates:nonce:nonceSignature:)","abstract":[{"type":"text","text":"Instantiates a new params object with the provided attributes."}],"navigatorTitle":[{"kind":"identifier","text":"initWithCardId:certificates:nonce:nonceSignature:"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/init(cardid:certificates:nonce:noncesignature:)","title":"init(cardId:certificates:nonce:nonceSignature:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cardId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"certificates"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nonceSignature"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams":{"abstract":[{"type":"text","text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API."},{"text":" ","type":"text"},{"type":"text","text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class."}],"navigatorTitle":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}],"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"title":"STPPushProvisioningDetailsParams","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithCardId:certificates:nonce:nonceSignature:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCardId:certificates:nonce:nonceSignature:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCardId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"cardId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"certificates:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSData *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"certificates","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nonce:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"nonce","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nonceSignature:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"nonceSignature","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithCardId:certificates:nonce:nonceSignature:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1init(cardId:certificates:nonce:nonceSignature:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCardId:certificates:nonce:nonceSignature:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1init(cardId:certificates:nonce:nonceSignature:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/title","value":"STPPushProvisioningDetailsParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/fragments","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/navigatorTitle"}]}]}