{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncesignaturehex"]},{"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncesignaturehex"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams"]]},"abstract":[{"text":"Implemented for convenience - the Stripe API expects the nonce signature as a hex-encoded string.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignatureHex","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonceSignatureHex"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonceSignatureHex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"nonceSignatureHex","modules":[{"name":"Stripe"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nonceSignatureHex"}],"roleHeading":"Instance Property","externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningDetailsParams(py)nonceSignatureHex"},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams","title":"STPPushProvisioningDetailsParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams","abstract":[{"type":"text","text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API."},{"text":" ","type":"text"},{"type":"text","text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","abstract":[],"url":"\/documentation\/stripe","title":"Stripe","kind":"symbol","role":"collection","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/nonceSignatureHex":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonceSignatureHex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"nonceSignatureHex"}],"abstract":[{"type":"text","text":"Implemented for convenience - the Stripe API expects the nonce signature as a hex-encoded string."}],"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncesignaturehex","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignatureHex","role":"symbol","title":"nonceSignatureHex","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"nonceSignatureHex","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"nonceSignatureHex","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"nonceSignatureHex"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPushProvisioningDetailsParams","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/fragments","value":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}]},{"value":"nonceSignatureHex","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceSignatureHex\/title","op":"replace"},{"value":[{"kind":"identifier","text":"nonceSignatureHex"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceSignatureHex\/fragments"}]}]}