{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncesignature"]},{"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncesignature"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"A nonce signature that should be used during the encryption of the card details.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignature","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonceSignature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"title":"nonceSignature","navigatorTitle":[{"text":"nonceSignature","kind":"identifier"}],"modules":[{"name":"Stripe"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningDetailsParams(py)nonceSignature"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonceSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":" { get }","kind":"text"}]}]}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams":{"role":"symbol","abstract":[{"text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class."}],"title":"STPPushProvisioningDetailsParams","navigatorTitle":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}],"type":"topic","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/nonceSignature":{"role":"symbol","title":"nonceSignature","kind":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncesignature","abstract":[{"text":"A nonce signature that should be used during the encryption of the card details.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"nonceSignature","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"nonceSignature","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignature"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","url":"\/documentation\/stripe","title":"Stripe","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"nonceSignature","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"nonceSignature"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" * ","kind":"text"},{"text":"nonceSignature","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/title","value":"STPPushProvisioningDetailsParams"},{"value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}]},{"value":"nonceSignature","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceSignature\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceSignature\/fragments","op":"replace","value":[{"kind":"identifier","text":"nonceSignature"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}