{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nonceHex"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nonceHex","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"Stripe"}],"title":"nonceHex","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"nonceHex","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningDetailsParams(py)nonceHex","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceHex","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Implemented for convenience - the Stripe API expects the nonce as a hex-encoded string."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncehex"]},{"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncehex"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/nonceHex":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nonceHex","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceHex","title":"nonceHex","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncehex","navigatorTitle":[{"kind":"identifier","text":"nonceHex"}],"role":"symbol","abstract":[{"type":"text","text":"Implemented for convenience - the Stripe API expects the nonce as a hex-encoded string."}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","role":"collection","title":"Stripe","kind":"symbol","type":"topic","abstract":[]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams":{"role":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams","abstract":[{"type":"text","text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API."},{"text":" ","type":"text"},{"type":"text","text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class."}],"title":"STPPushProvisioningDetailsParams","type":"topic","navigatorTitle":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"nonceHex","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"nonceHex"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"nonceHex"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"nonceHex","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceHex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceHex\/fragments","value":[{"kind":"identifier","text":"nonceHex"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/title","value":"STPPushProvisioningDetailsParams"},{"op":"replace","value":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/navigatorTitle","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"op":"replace"}]}]}