{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/apiadapter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/apiadapter"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"metadata":{"title":"apiAdapter","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(py)apiAdapter","role":"symbol","modules":[{"name":"Stripe"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiAdapter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","text":"STPBackendAPIAdapter"}],"navigatorTitle":[{"text":"apiAdapter","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/apiAdapter"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"apiAdapter","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","text":"STPBackendAPIAdapter","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","kind":"typeIdentifier"},{"kind":"text","text":" { get }"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"STPBackendAPIAdapter.h"}],"type":"paragraph"}],"name":"See Also","style":"note","type":"aside"}]}],"abstract":[{"text":"Note: Instead of providing your own backend API adapter, we recommend using","type":"text"},{"type":"text","text":" "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":", which will manage retrieving and updating a","type":"text"},{"text":" ","type":"text"},{"text":"Stripe customer for you. - seealso: STPCustomerContext.h","type":"text"},{"type":"text","text":" "},{"text":"The API adapter the payment context will use to fetch and modify its contents.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You need to make a class conforming to this protocol that talks to your server."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPBackendAPIAdapter","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripe\/stpbackendapiadapter","title":"STPBackendAPIAdapter","abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":", which implements "},{"text":" ","type":"text"},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/apiAdapter":{"navigatorTitle":[{"text":"apiAdapter","kind":"identifier"}],"title":"apiAdapter","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiAdapter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","text":"STPBackendAPIAdapter","kind":"typeIdentifier"}],"url":"\/documentation\/stripe\/stppaymentcontext\/apiadapter","abstract":[{"text":"Note: Instead of providing your own backend API adapter, we recommend using","type":"text"},{"type":"text","text":" "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":", which will manage retrieving and updating a"},{"type":"text","text":" "},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"type":"text","text":" "},{"type":"text","text":"The API adapter the payment context will use to fetch and modify its contents."},{"type":"text","text":" "},{"text":"You need to make a class conforming to this protocol that talks to your server.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/apiAdapter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"apiAdapter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"apiAdapter","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPBackendAPIAdapter","text":"id<STPBackendAPIAdapter>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"apiAdapter","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","op":"replace","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]},{"op":"replace","value":"STPBackendAPIAdapter","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","value":[{"text":"STPBackendAPIAdapter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1apiAdapter\/title","value":"apiAdapter"},{"value":[{"kind":"identifier","text":"apiAdapter"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1apiAdapter\/fragments","op":"replace"}]}]}
