{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/authenticationPresentingViewController()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/authenticationpresentingviewcontroller()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/authenticationpresentingviewcontroller()"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)authenticationPresentingViewController","modules":[{"name":"Stripe"}],"symbolKind":"method","title":"authenticationPresentingViewController()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticationPresentingViewController","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticationPresentingViewController","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"The Stripe SDK will modally present additional view controllers on top","type":"text"},{"type":"text","text":" "},{"text":"of the ","type":"text"},{"type":"codeVoice","code":"authenticationPresentingViewController"},{"type":"text","text":" when required for user"},{"text":" ","type":"text"},{"type":"text","text":"authentication, like in the Challenge Flow for 3DS2 transactions."}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/authenticationPresentingViewController()":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/authenticationPresentingViewController()","role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext\/authenticationpresentingviewcontroller()","title":"authenticationPresentingViewController()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"type":"topic","abstract":[{"type":"text","text":"The Stripe SDK will modally present additional view controllers on top"},{"text":" ","type":"text"},{"type":"text","text":"of the "},{"type":"codeVoice","code":"authenticationPresentingViewController"},{"text":" when required for user","type":"text"},{"type":"text","text":" "},{"text":"authentication, like in the Challenge Flow for 3DS2 transactions.","type":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"type":"topic","title":"STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and modifying the customer.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authenticationPresentingViewController"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"authenticationPresentingViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":" *) ","kind":"text"},{"text":"authenticationPresentingViewController","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"authenticationPresentingViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1authenticationPresentingViewController()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationPresentingViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1authenticationPresentingViewController()\/fragments"},{"value":"STPPaymentContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","op":"replace"},{"value":[{"text":"STPPaymentContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
