{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"apiAdapter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPBackendAPIAdapter","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/init(apiadapter:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/init(apiadapter:)"]}],"metadata":{"symbolKind":"init","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)initWithApiAdapter:","navigatorTitle":[{"kind":"identifier","text":"initWithApiAdapter:"}],"roleHeading":"Initializer","title":"init(apiAdapter:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"apiAdapter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPBackendAPIAdapter","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"Stripe"}]},"abstract":[{"text":"Note: Instead of providing your own backend API adapter, we recommend using","type":"text"},{"type":"text","text":" "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":", which will manage retrieving and updating a"},{"type":"text","text":" "},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"type":"text","text":" "},{"type":"text","text":"This is a convenience initializer; it is equivalent to calling"},{"text":" ","type":"text"},{"type":"codeVoice","code":"init(apiAdapter:apiAdapter configuration:STPPaymentConfiguration.shared theme:STPTheme.defaultTheme)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPBackendAPIAdapter","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripe\/stpbackendapiadapter","title":"STPBackendAPIAdapter","abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":", which implements "},{"text":" ","type":"text"},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/init(apiAdapter:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithApiAdapter:"}],"title":"init(apiAdapter:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"apiAdapter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPBackendAPIAdapter","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentcontext\/init(apiadapter:)","abstract":[{"type":"text","text":"Note: Instead of providing your own backend API adapter, we recommend using"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which will manage retrieving and updating a"},{"type":"text","text":" "},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"text":" ","type":"text"},{"type":"text","text":"This is a convenience initializer; it is equivalent to calling"},{"type":"text","text":" "},{"type":"codeVoice","code":"init(apiAdapter:apiAdapter configuration:STPPaymentConfiguration.shared theme:STPTheme.defaultTheme)"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithApiAdapter:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithApiAdapter:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithApiAdapter:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<STPBackendAPIAdapter>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPBackendAPIAdapter"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"apiAdapter"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title","value":"STPBackendAPIAdapter","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments"},{"value":"initWithApiAdapter:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(apiAdapter:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithApiAdapter:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(apiAdapter:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentContext"}]}]}]}
