{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:configuration:theme:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"abstract":[{"text":"Note: Instead of providing your own backend API adapter, we recommend using","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which will manage retrieving and updating a"},{"type":"text","text":" "},{"text":"Stripe customer for you. - seealso: STPCustomerContext.h","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Initializes a new Payment Context with the provided API adapter and configuration."},{"type":"text","text":" "},{"type":"text","text":"After this class is initialized, you should also make sure to set its "},{"type":"codeVoice","code":"delegate"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"code":"hostViewController","type":"codeVoice"},{"type":"text","text":" properties."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"Stripe"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"apiAdapter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","text":"STPBackendAPIAdapter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"text":"STPTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":")"}],"role":"symbol","title":"init(apiAdapter:configuration:theme:)","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)initWithApiAdapter:configuration:theme:","navigatorTitle":[{"kind":"identifier","text":"initWithApiAdapter:configuration:theme:"}],"symbolKind":"init"},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/init(apiadapter:configuration:theme:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/init(apiadapter:configuration:theme:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"apiAdapter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","kind":"typeIdentifier","text":"STPBackendAPIAdapter","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","kind":"typeIdentifier","text":"STPPaymentConfiguration"},{"text":", ","kind":"text"},{"text":"theme","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"apiAdapter","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The API adapter the payment context will use to fetch and"},{"text":" ","type":"text"},{"type":"text","text":"modify its contents. You need to make a class conforming to this protocol that"},{"type":"text","text":" "},{"text":"talks to your server. - seealso: STPBackendAPIAdapter.h","type":"text"}]}]},{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration for the payment context to use. This lets","type":"text"},{"type":"text","text":" "},{"type":"text","text":"you set your Stripe publishable API key, required billing address fields, etc."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"the newly-instantiated payment context"}]}]},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"STPPaymentConfiguration.h"}]}],"name":"See Also","type":"aside"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"type":"topic","title":"STPPaymentConfiguration","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"text":" ","type":"text"},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"text":"will not change from payment to payment and thus is reusable, while the context","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentconfiguration","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPBackendAPIAdapter","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripe\/stpbackendapiadapter","title":"STPBackendAPIAdapter","abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":", which implements "},{"text":" ","type":"text"},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/init(apiAdapter:configuration:theme:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"apiAdapter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","text":"STPBackendAPIAdapter","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier","text":"STPTheme"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentcontext\/init(apiadapter:configuration:theme:)","role":"symbol","title":"init(apiAdapter:configuration:theme:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:configuration:theme:)","navigatorTitle":[{"text":"initWithApiAdapter:configuration:theme:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Note: Instead of providing your own backend API adapter, we recommend using"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which will manage retrieving and updating a"},{"text":" ","type":"text"},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"type":"text","text":" "},{"type":"text","text":"Initializes a new Payment Context with the provided API adapter and configuration."},{"type":"text","text":" "},{"text":"After this class is initialized, you should also make sure to set its ","type":"text"},{"code":"delegate","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"type":"codeVoice","code":"hostViewController"},{"text":" properties.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","type":"topic","abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"title":"STPTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTheme","kind":"identifier"}],"url":"\/documentation\/stripe\/stptheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithApiAdapter:configuration:theme:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithApiAdapter:configuration:theme:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithApiAdapter:"},{"text":"(","kind":"text"},{"text":"id<STPBackendAPIAdapter>","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPBackendAPIAdapter","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"apiAdapter"},{"kind":"text","text":" "},{"text":"configuration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"theme:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier","text":"STPTheme"},{"text":" *) ","kind":"text"},{"text":"theme","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"STPPaymentContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace","value":[{"text":"STPPaymentContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","op":"replace","value":[{"text":"STPPaymentConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title","op":"replace","value":"STPBackendAPIAdapter"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","value":[{"text":"STPBackendAPIAdapter","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithApiAdapter:configuration:theme:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(apiAdapter:configuration:theme:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithApiAdapter:configuration:theme:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(apiAdapter:configuration:theme:)\/fragments","op":"replace"},{"value":"STPTheme","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","op":"replace","value":[{"text":"STPTheme","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
