{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customerContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext","text":"STPCustomerContext"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"the newly-instantiated payment context"}]}]},{"kind":"parameters","parameters":[{"name":"customerContext","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The customer context the payment context will use to fetch"},{"type":"text","text":" "},{"type":"text","text":"and modify its Stripe customer. - seealso: STPCustomerContext.h"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/init(customercontext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/init(customercontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is a convenience initializer; it is equivalent to calling"},{"type":"text","text":" "},{"type":"codeVoice","code":"init(customerContext:customerContext configuration:STPPaymentConfiguration.shared theme:STPTheme.defaultTheme"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customerContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"kind":"text","text":")"}],"title":"init(customerContext:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)initWithCustomerContext:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCustomerContext:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/init(customerContext:)":{"role":"symbol","title":"init(customerContext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customerContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is a convenience initializer; it is equivalent to calling"},{"type":"text","text":" "},{"type":"codeVoice","code":"init(customerContext:customerContext configuration:STPPaymentConfiguration.shared theme:STPTheme.defaultTheme"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCustomerContext:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/init(customercontext:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"role":"symbol","title":"STPCustomerContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" retrieves and updates a Stripe customer and their attached"},{"type":"text","text":" "},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"type":"text","text":" "},{"type":"text","text":"instance’s cache. On your backend, be sure to create and return a"},{"type":"text","text":" "},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomerContext"}],"url":"\/documentation\/stripe\/stpcustomercontext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContext"}],"url":"\/documentation\/stripe\/stppaymentcontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCustomerContext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCustomerContext:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCustomerContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext","text":"STPCustomerContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"customerContext"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(customerContext:)\/title","value":"initWithCustomerContext:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(customerContext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCustomerContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}