{"metadata":{"modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCustomerContext:configuration:theme:"}],"title":"init(customerContext:configuration:theme:)","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)initWithCustomerContext:configuration:theme:","roleHeading":"Initializer","symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customerContext"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext","kind":"typeIdentifier","text":"STPCustomerContext"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"theme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":")"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:configuration:theme:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customerContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext","text":"STPCustomerContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"customerContext","content":[{"inlineContent":[{"type":"text","text":"The customer context the payment context will use to fetch"},{"type":"text","text":" "},{"text":"and modify its Stripe customer. - seealso: STPCustomerContext.h","type":"text"}],"type":"paragraph"}]},{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"The configuration for the payment context to use. This"},{"type":"text","text":" "},{"type":"text","text":"lets you set your Stripe publishable API key, required billing address fields, etc."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"the newly-instantiated payment context"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"content":[{"inlineContent":[{"text":"STPPaymentConfiguration.h","type":"text"}],"type":"paragraph"}],"style":"note","type":"aside","name":"See Also"}]}],"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/init(customercontext:configuration:theme:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/init(customercontext:configuration:theme:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"kind":"symbol","abstract":[{"text":"Initializes a new Payment Context with the provided customer context, configuration,","type":"text"},{"text":" ","type":"text"},{"text":"and theme. After this class is initialized, you should also make sure to set its","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":" properties."}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"kind":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"type":"text","text":" "},{"text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCustomerContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","url":"\/documentation\/stripe\/stpcustomercontext","role":"symbol","title":"STPCustomerContext","type":"topic","navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","type":"topic","abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"title":"STPTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTheme","kind":"identifier"}],"url":"\/documentation\/stripe\/stptheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/init(customerContext:configuration:theme:)":{"kind":"symbol","abstract":[{"text":"Initializes a new Payment Context with the provided customer context, configuration,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and theme. After this class is initialized, you should also make sure to set its"},{"type":"text","text":" "},{"type":"codeVoice","code":"delegate"},{"text":" and ","type":"text"},{"code":"hostViewController","type":"codeVoice"},{"text":" properties.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customerContext"},{"kind":"text","text":": "},{"text":"STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"theme","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","text":"STPTheme"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentcontext\/init(customercontext:configuration:theme:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:configuration:theme:)","role":"symbol","title":"init(customerContext:configuration:theme:)","type":"topic","navigatorTitle":[{"text":"initWithCustomerContext:configuration:theme:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"type":"topic","title":"STPPaymentConfiguration","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"text":" ","type":"text"},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"text":"will not change from payment to payment and thus is reusable, while the context","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentconfiguration","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithCustomerContext:configuration:theme:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCustomerContext:configuration:theme:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCustomerContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","text":"STPCustomerContext","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"customerContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration:"},{"kind":"text","text":"("},{"text":"STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"theme:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","text":"STPTheme"},{"kind":"text","text":" *) "},{"text":"theme","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext","op":"replace"},{"value":[{"kind":"identifier","text":"STPCustomerContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","op":"replace"},{"value":"STPTheme","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPTheme"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","op":"replace"},{"op":"replace","value":"initWithCustomerContext:configuration:theme:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(customerContext:configuration:theme:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCustomerContext:configuration:theme:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(customerContext:configuration:theme:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","op":"replace","value":"STPPaymentContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"value":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","op":"replace"}]}]}
