{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/largeTitleDisplayMode"},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/largetitledisplaymode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/largetitledisplaymode"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"largeTitleDisplayMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"UINavigationItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UINavigationItemLargeTitleDisplayMode","kind":"typeIdentifier","text":"LargeTitleDisplayMode"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The mode to use when displaying the title of the navigation bar in all view"},{"type":"text","text":" "},{"type":"text","text":"controllers presented by the context. The default value is "},{"code":"automatic","type":"codeVoice"},{"text":",","type":"text"},{"type":"text","text":" "},{"text":"which causes the title to use the same styling as the previously displayed","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"navigation item (if the view controller is pushed onto the "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"If the ","type":"text"},{"code":"prefersLargeTitles","type":"codeVoice"},{"text":" property of the ","type":"text"},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":"‘s navigation bar"},{"text":" ","type":"text"},{"type":"text","text":"is false, this property has no effect and the navigation item’s title is always"},{"text":" ","type":"text"},{"type":"text","text":"displayed as a small title."},{"text":" ","type":"text"},{"text":"If the view controller is presented modally, ","type":"text"},{"code":"automatic","type":"codeVoice"},{"text":" and","type":"text"},{"text":" ","type":"text"},{"code":"never","type":"codeVoice"},{"type":"text","text":" always result in a navigation bar with a small title."}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"Stripe"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"largeTitleDisplayMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UINavigationItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":"."},{"text":"LargeTitleDisplayMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@UINavigationItemLargeTitleDisplayMode"}],"symbolKind":"property","role":"symbol","title":"largeTitleDisplayMode","navigatorTitle":[{"kind":"identifier","text":"largeTitleDisplayMode"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(py)largeTitleDisplayMode"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/largeTitleDisplayMode":{"navigatorTitle":[{"text":"largeTitleDisplayMode","kind":"identifier"}],"title":"largeTitleDisplayMode","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"largeTitleDisplayMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationItem","text":"UINavigationItem"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UINavigationItemLargeTitleDisplayMode","kind":"typeIdentifier","text":"LargeTitleDisplayMode"}],"url":"\/documentation\/stripe\/stppaymentcontext\/largetitledisplaymode","abstract":[{"type":"text","text":"The mode to use when displaying the title of the navigation bar in all view"},{"type":"text","text":" "},{"type":"text","text":"controllers presented by the context. The default value is "},{"type":"codeVoice","code":"automatic"},{"type":"text","text":","},{"text":" ","type":"text"},{"type":"text","text":"which causes the title to use the same styling as the previously displayed"},{"type":"text","text":" "},{"type":"text","text":"navigation item (if the view controller is pushed onto the "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":")."},{"text":" ","type":"text"},{"type":"text","text":"If the "},{"type":"codeVoice","code":"prefersLargeTitles"},{"type":"text","text":" property of the "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":"‘s navigation bar"},{"type":"text","text":" "},{"type":"text","text":"is false, this property has no effect and the navigation item’s title is always"},{"text":" ","type":"text"},{"type":"text","text":"displayed as a small title."},{"text":" ","type":"text"},{"type":"text","text":"If the view controller is presented modally, "},{"code":"automatic","type":"codeVoice"},{"text":" and","type":"text"},{"text":" ","type":"text"},{"code":"never","type":"codeVoice"},{"type":"text","text":" always result in a navigation bar with a small title."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/largeTitleDisplayMode"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"largeTitleDisplayMode","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"largeTitleDisplayMode"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@E@UINavigationItemLargeTitleDisplayMode","kind":"typeIdentifier","text":"UINavigationItemLargeTitleDisplayMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"largeTitleDisplayMode"}]}]}},{"op":"replace","value":"largeTitleDisplayMode","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1largeTitleDisplayMode\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1largeTitleDisplayMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"largeTitleDisplayMode"}]},{"value":"STPPaymentContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","op":"replace"},{"value":[{"text":"STPPaymentContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments"}]}]}
