{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/modalpresentationstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/modalpresentationstyle"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"abstract":[{"text":"The presentation style used for all view controllers presented modally by the context.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Since custom transition styles are not supported, you should set this to either"},{"type":"text","text":" "},{"type":"codeVoice","code":"UIModalPresentationFullScreen"},{"text":", ","type":"text"},{"type":"codeVoice","code":"UIModalPresentationPageSheet"},{"type":"text","text":", or "},{"code":"UIModalPresentationFormSheet","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"UIModalPresentationFullScreen"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(py)modalPresentationStyle","title":"modalPresentationStyle","navigatorTitle":[{"kind":"identifier","text":"modalPresentationStyle"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"modalPresentationStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","kind":"typeIdentifier","text":"UIModalPresentationStyle"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"modalPresentationStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/modalPresentationStyle","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/modalPresentationStyle":{"navigatorTitle":[{"text":"modalPresentationStyle","kind":"identifier"}],"title":"modalPresentationStyle","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"modalPresentationStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle","kind":"typeIdentifier"}],"url":"\/documentation\/stripe\/stppaymentcontext\/modalpresentationstyle","abstract":[{"type":"text","text":"The presentation style used for all view controllers presented modally by the context."},{"type":"text","text":" "},{"text":"Since custom transition styles are not supported, you should set this to either","type":"text"},{"text":" ","type":"text"},{"code":"UIModalPresentationFullScreen","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"UIModalPresentationPageSheet"},{"text":", or ","type":"text"},{"type":"codeVoice","code":"UIModalPresentationFormSheet"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"The default value is ","type":"text"},{"code":"UIModalPresentationFullScreen","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/modalPresentationStyle"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"modalPresentationStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"modalPresentationStyle","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@UIModalPresentationStyle","text":"UIModalPresentationStyle","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"modalPresentationStyle","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1modalPresentationStyle\/title","value":"modalPresentationStyle"},{"value":[{"kind":"identifier","text":"modalPresentationStyle"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1modalPresentationStyle\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace","value":[{"text":"STPPaymentContext","kind":"identifier"}]}]}]}
