{"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"text":"STPPaymentOptionsViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"text":"didFailToLoadWithError","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":")","kind":"text"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)paymentOptionsViewController:didFailToLoadWithError:","role":"symbol","modules":[{"name":"Stripe"}],"title":"paymentOptionsViewController(_:didFailToLoadWithError:)","navigatorTitle":[{"text":"paymentOptionsViewController:didFailToLoadWithError:","kind":"identifier"}],"roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"This is called when the view controller encounters an error fetching the user’s","type":"text"},{"type":"text","text":" "},{"text":"payment options from its API adapter. You should dismiss the view controller","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"when this is called."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"paymentOptionsViewController"},{"text":": ","kind":"text"},{"text":"STPPaymentOptionsViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToLoadWithError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the view controller in question"}]}],"name":"paymentOptionsViewController"},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"the error that occurred"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontroller(_:didfailtoloadwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontroller(_:didfailtoloadwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didFailToLoadWithError:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptionsViewController(_:didFailToLoadWithError:)":{"navigatorTitle":[{"text":"paymentOptionsViewController:didFailToLoadWithError:","kind":"identifier"}],"title":"paymentOptionsViewController(_:didFailToLoadWithError:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didFailToLoadWithError","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontroller(_:didfailtoloadwitherror:)","abstract":[{"type":"text","text":"This is called when the view controller encounters an error fetching the user’s"},{"type":"text","text":" "},{"type":"text","text":"payment options from its API adapter. You should dismiss the view controller"},{"type":"text","text":" "},{"text":"when this is called.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didFailToLoadWithError:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"title":"STPPaymentOptionsViewController","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller","navigatorTitle":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","role":"symbol","abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"text":" ","type":"text"},{"text":"which they can select between. They can also add credit cards to the list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":", so you can either","type":"text"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"as the ","type":"text"},{"type":"codeVoice","code":"rootViewController"},{"text":" and then present the ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"text":"or push a new ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"paymentOptionsViewController:didFailToLoadWithError:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didFailToLoadWithError:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentOptionsViewController:"},{"text":"(","kind":"text"},{"text":"STPPaymentOptionsViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"paymentOptionsViewController"},{"text":" ","kind":"text"},{"text":"didFailToLoadWithError:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"paymentOptionsViewController:didFailToLoadWithError:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewController(_:didFailToLoadWithError:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"paymentOptionsViewController:didFailToLoadWithError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewController(_:didFailToLoadWithError:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"value":[{"kind":"identifier","text":"STPPaymentContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace"},{"value":"STPPaymentOptionsViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
