{"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontrollerfooterview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontrollerfooterview"]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"A view that will be placed as the footer of the payment options selection"},{"text":" ","type":"text"},{"text":"view controller.","type":"text"},{"type":"text","text":" "},{"text":"When the footer view needs to be resized, it will be sent a","type":"text"},{"text":" ","type":"text"},{"code":"sizeThatFits:","type":"codeVoice"},{"text":" call. The view should respond correctly to this method in order","type":"text"},{"type":"text","text":" "},{"text":"to be sized and positioned properly.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerFooterView","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","modules":[{"name":"Stripe"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"}],"title":"paymentOptionsViewControllerFooterView","roleHeading":"Instance Property","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(py)paymentOptionsViewControllerFooterView","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptionsViewControllerFooterView":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontrollerfooterview","abstract":[{"text":"A view that will be placed as the footer of the payment options selection","type":"text"},{"text":" ","type":"text"},{"text":"view controller.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When the footer view needs to be resized, it will be sent a"},{"text":" ","type":"text"},{"type":"codeVoice","code":"sizeThatFits:"},{"type":"text","text":" call. The view should respond correctly to this method in order"},{"type":"text","text":" "},{"type":"text","text":"to be sized and positioned properly."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"}],"title":"paymentOptionsViewControllerFooterView","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerFooterView","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paymentOptionsViewControllerFooterView","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"}]}]},"op":"replace"},{"value":"paymentOptionsViewControllerFooterView","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewControllerFooterView\/title","op":"replace"},{"value":[{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewControllerFooterView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace","value":[{"text":"STPPaymentContext","kind":"identifier"}]}]}]}
