{"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontroller(_:didselect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontroller(_:didselect:)"]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)paymentOptionsViewController:didSelectPaymentOption:","role":"symbol","title":"paymentOptionsViewController(_:didSelect:)","navigatorTitle":[{"text":"paymentOptionsViewController:didSelectPaymentOption:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentOptionsViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentOptionsViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","text":"STPPaymentOption"},{"text":")","kind":"text"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentOptionsViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"text":"didSelect","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentOption","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","text":"STPPaymentOption","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"parameters":[{"name":"paymentOptionsViewController","content":[{"inlineContent":[{"text":"the view controller in question","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"the selected payment method"}],"type":"paragraph"}],"name":"paymentOption"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didSelect:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"This is called when the user either makes a selection, or adds a new card.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This will be triggered after the view controller loads with the user’s current"},{"type":"text","text":" "},{"type":"text","text":"selection (if they have one) and then subsequently when they change their"},{"text":" ","type":"text"},{"type":"text","text":"choice. You should use this callback to update any necessary UI in your app"},{"type":"text","text":" "},{"text":"that displays the user’s currently selected payment method. You should ","type":"text"},{"inlineContent":[{"text":"not","type":"text"}],"type":"emphasis"},{"text":" ","type":"text"},{"type":"text","text":"dismiss the view controller at this point, instead do this in"},{"type":"text","text":" "},{"type":"codeVoice","code":"paymentOptionsViewControllerDidFinish:"},{"type":"text","text":". "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"will also call the necessary methods on your API adapter, so you don’t need to"},{"type":"text","text":" "},{"text":"call them directly during this method.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"type":"topic","title":"STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and modifying the customer.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptionsViewController(_:didSelect:)":{"abstract":[{"type":"text","text":"This is called when the user either makes a selection, or adds a new card."},{"type":"text","text":" "},{"text":"This will be triggered after the view controller loads with the user’s current","type":"text"},{"type":"text","text":" "},{"text":"selection (if they have one) and then subsequently when they change their","type":"text"},{"text":" ","type":"text"},{"text":"choice. You should use this callback to update any necessary UI in your app","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that displays the user’s currently selected payment method. You should "},{"inlineContent":[{"type":"text","text":"not"}],"type":"emphasis"},{"type":"text","text":" "},{"type":"text","text":"dismiss the view controller at this point, instead do this in"},{"type":"text","text":" "},{"code":"paymentOptionsViewControllerDidFinish:","type":"codeVoice"},{"type":"text","text":". "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"will also call the necessary methods on your API adapter, so you don’t need to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"call them directly during this method."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didSelect:)","role":"symbol","title":"paymentOptionsViewController(_:didSelect:)","url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontroller(_:didselect:)","navigatorTitle":[{"text":"paymentOptionsViewController:didSelectPaymentOption:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentOptionsViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"text":"didSelect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","kind":"typeIdentifier","text":"STPPaymentOption"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"title":"STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","abstract":[{"text":"This view controller presents a list of payment method options to the user,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"text":" ","type":"text"},{"text":"It must be displayed inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"text":", so you can either","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"as the ","type":"text"},{"code":"rootViewController","type":"codeVoice"},{"type":"text","text":" and then present the "},{"code":"UINavigationController","type":"codeVoice"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"text":"’s stack. You can also have ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"code":"pushPaymentOptionsViewController","type":"codeVoice"},{"text":" on it.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption":{"abstract":[{"type":"text","text":"This protocol represents a payment method that a user can select and use to"},{"type":"text","text":" "},{"type":"text","text":"pay."},{"text":" ","type":"text"},{"text":"The classes that conform to it and are supported by the UI:","type":"text"}],"url":"\/documentation\/stripe\/stppaymentoption","role":"symbol","kind":"symbol","type":"topic","title":"STPPaymentOption","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOption"}],"navigatorTitle":[{"text":"STPPaymentOption","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"paymentOptionsViewController:didSelectPaymentOption:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"paymentOptionsViewController:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","kind":"typeIdentifier","text":"STPPaymentOptionsViewController"},{"text":" *) ","kind":"text"},{"text":"paymentOptionsViewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didSelectPaymentOption:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<STPPaymentOption>","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPPaymentOption"},{"text":" *) ","kind":"text"},{"text":"paymentOption","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace","value":[{"text":"STPPaymentContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewController(_:didSelect:)\/title","value":"paymentOptionsViewController:didSelectPaymentOption:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewController(_:didSelect:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"paymentOptionsViewController:didSelectPaymentOption:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","op":"replace","value":"STPPaymentOptionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/title","op":"replace","value":"STPPaymentOption"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/fragments","value":[{"text":"STPPaymentOption","kind":"identifier"}]}]}]}
