{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentSummaryItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PKPaymentSummaryItem","preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The other will be automatically calculated on demand using your "},{"type":"codeVoice","code":"paymentCurrency."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/paymentsummaryitems"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/paymentsummaryitems"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentSummaryItems","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If you support Apple Pay, you can optionally set the PKPaymentSummaryItems"},{"type":"text","text":" "},{"type":"text","text":"you want to display here instead of using "},{"type":"codeVoice","code":"paymentAmount"},{"type":"text","text":". Note that the"},{"type":"text","text":" "},{"type":"text","text":"grand total (the amount of the last summary item) must be greater than zero."},{"type":"text","text":" "},{"type":"text","text":"If not set, a single summary item will be automatically generated using"},{"type":"text","text":" "},{"type":"codeVoice","code":"paymentAmount"},{"type":"text","text":" and your configuration’s "},{"type":"codeVoice","code":"companyName"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentSummaryItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PKPaymentSummaryItem","preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem"},{"kind":"text","text":"]"}],"title":"paymentSummaryItems","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(py)paymentSummaryItems","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"paymentSummaryItems"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentSummaryItems":{"role":"symbol","title":"paymentSummaryItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentSummaryItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PKPaymentSummaryItem","preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"If you support Apple Pay, you can optionally set the PKPaymentSummaryItems"},{"type":"text","text":" "},{"type":"text","text":"you want to display here instead of using "},{"type":"codeVoice","code":"paymentAmount"},{"type":"text","text":". Note that the"},{"type":"text","text":" "},{"type":"text","text":"grand total (the amount of the last summary item) must be greater than zero."},{"type":"text","text":" "},{"type":"text","text":"If not set, a single summary item will be automatically generated using"},{"type":"text","text":" "},{"type":"codeVoice","code":"paymentAmount"},{"type":"text","text":" and your configuration’s "},{"type":"codeVoice","code":"companyName"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentSummaryItems","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentSummaryItems"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentsummaryitems"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContext"}],"url":"\/documentation\/stripe\/stppaymentcontext"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"paymentSummaryItems"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"paymentSummaryItems"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<PKPaymentSummaryItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentSummaryItems"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentSummaryItems\/title","value":"paymentSummaryItems"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentSummaryItems\/fragments","value":[{"kind":"identifier","text":"paymentSummaryItems"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}