{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"This method is called before presenting a UIViewController for authentication."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/prepare(forPresentation:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)prepareAuthenticationContextForPresentation:","modules":[{"name":"Stripe"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prepare","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPresentation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments12STPVoidBlocka","text":"STPVoidBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"prepare(forPresentation:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prepare","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPresentation"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPVoidBlock-2384d","preciseIdentifier":"s:14StripePayments12STPVoidBlocka","kind":"typeIdentifier","text":"STPVoidBlock"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/prepare(forpresentation:)"]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/prepare(forpresentation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/prepare(forPresentation:)":{"navigatorTitle":[{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"}],"title":"prepare(forPresentation:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepare","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPresentation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments12STPVoidBlocka","text":"STPVoidBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentcontext\/prepare(forpresentation:)","abstract":[{"type":"text","text":"This method is called before presenting a UIViewController for authentication."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/prepare(forPresentation:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPVoidBlock-2384d":{"abstract":[{"type":"text","text":"An empty block, called with no arguments, returning nothing."}],"role":"symbol","url":"\/documentation\/stripe\/stpvoidblock-2384d","kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPVoidBlock"}],"navigatorTitle":[{"kind":"identifier","text":"STPVoidBlock"}],"title":"STPVoidBlock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPVoidBlock-2384d"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"prepareAuthenticationContextForPresentation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv()","text":"void (^)(void)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1prepare(forPresentation:)\/title","value":"prepareAuthenticationContextForPresentation:"},{"value":[{"text":"- ","kind":"text"},{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1prepare(forPresentation:)\/fragments","op":"replace"},{"value":"STPPaymentContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","op":"replace"},{"value":[{"text":"STPPaymentContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace"}]}]}
