{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/presentpaymentoptionsviewcontroller()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/presentpaymentoptionsviewcontroller()"]}],"kind":"symbol","abstract":[{"type":"text","text":"This creates, configures, and appropriately presents an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"on top of the payment context’s "},{"code":"hostViewController","type":"codeVoice"},{"type":"text","text":". It’ll be dismissed automatically"},{"text":" ","type":"text"},{"text":"when the user is done selecting their payment method.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentPaymentOptionsViewController"},{"kind":"text","text":"()"}]}]},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"already showing a view controller or in the middle of requesting a payment."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentPaymentOptionsViewController()"},"metadata":{"role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)presentPaymentOptionsViewController","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentPaymentOptionsViewController","kind":"identifier"},{"kind":"text","text":"()"}],"title":"presentPaymentOptionsViewController()","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"presentPaymentOptionsViewController"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/presentPaymentOptionsViewController()":{"navigatorTitle":[{"kind":"identifier","text":"presentPaymentOptionsViewController"}],"title":"presentPaymentOptionsViewController()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentPaymentOptionsViewController","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/stripe\/stppaymentcontext\/presentpaymentoptionsviewcontroller()","abstract":[{"text":"This creates, configures, and appropriately presents an ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"on top of the payment context’s "},{"type":"codeVoice","code":"hostViewController"},{"text":". It’ll be dismissed automatically","type":"text"},{"type":"text","text":" "},{"text":"when the user is done selecting their payment method.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentPaymentOptionsViewController()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"presentPaymentOptionsViewController","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentPaymentOptionsViewController"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"presentPaymentOptionsViewController"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"presentPaymentOptionsViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1presentPaymentOptionsViewController()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentPaymentOptionsViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1presentPaymentOptionsViewController()\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"text":"STPPaymentContext","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
