{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentShippingViewController()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/presentshippingviewcontroller()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/presentshippingviewcontroller()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentShippingViewController","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"already showing a view controller or in the middle of requesting a payment."}]}],"kind":"content"}],"metadata":{"navigatorTitle":[{"text":"presentShippingViewController","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)presentShippingViewController","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"title":"presentShippingViewController()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentShippingViewController"},{"text":"()","kind":"text"}]},"abstract":[{"text":"This creates, configures, and appropriately presents a view controller for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"collecting shipping address and shipping method on top of the payment context’s"},{"type":"text","text":" "},{"type":"codeVoice","code":"hostViewController"},{"text":". It’ll be dismissed automatically when the user is done","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"entering their shipping info."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/presentShippingViewController()":{"navigatorTitle":[{"text":"presentShippingViewController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentShippingViewController()","abstract":[{"type":"text","text":"This creates, configures, and appropriately presents a view controller for"},{"type":"text","text":" "},{"text":"collecting shipping address and shipping method on top of the payment context’s","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":". It’ll be dismissed automatically when the user is done"},{"type":"text","text":" "},{"type":"text","text":"entering their shipping info."}],"kind":"symbol","role":"symbol","title":"presentShippingViewController()","url":"\/documentation\/stripe\/stppaymentcontext\/presentshippingviewcontroller()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentShippingViewController"},{"text":"()","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"type":"topic","title":"STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and modifying the customer.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presentShippingViewController"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"presentShippingViewController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"presentShippingViewController","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1presentShippingViewController()\/title","op":"replace","value":"presentShippingViewController"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1presentShippingViewController()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentShippingViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"text":"STPPaymentContext","kind":"identifier"}]}]}]}
