{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/pushPaymentOptionsViewController()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/pushpaymentoptionsviewcontroller()"]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/pushpaymentoptionsviewcontroller()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pushPaymentOptionsViewController","kind":"identifier"},{"text":"()","kind":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"already showing a view controller or in the middle of requesting a payment."}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"This creates, configures, and appropriately pushes an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"onto the navigation stack of the context’s ","type":"text"},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":". It’ll be popped"},{"type":"text","text":" "},{"text":"automatically when the user is done selecting their payment method.","type":"text"}],"metadata":{"symbolKind":"method","title":"pushPaymentOptionsViewController()","navigatorTitle":[{"kind":"identifier","text":"pushPaymentOptionsViewController"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)pushPaymentOptionsViewController","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushPaymentOptionsViewController"},{"text":"()","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/pushPaymentOptionsViewController()":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/pushPaymentOptionsViewController()","navigatorTitle":[{"text":"pushPaymentOptionsViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This creates, configures, and appropriately pushes an ","type":"text"},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"onto the navigation stack of the context’s "},{"type":"codeVoice","code":"hostViewController"},{"text":". It’ll be popped","type":"text"},{"type":"text","text":" "},{"text":"automatically when the user is done selecting their payment method.","type":"text"}],"title":"pushPaymentOptionsViewController()","role":"symbol","type":"topic","url":"\/documentation\/stripe\/stppaymentcontext\/pushpaymentoptionsviewcontroller()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pushPaymentOptionsViewController","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"pushPaymentOptionsViewController","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"pushPaymentOptionsViewController","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"pushPaymentOptionsViewController","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"pushPaymentOptionsViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1pushPaymentOptionsViewController()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1pushPaymentOptionsViewController()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pushPaymentOptionsViewController","kind":"identifier"}]},{"value":"STPPaymentContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments"}]}]}
