{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestPayment","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"requestPayment","kind":"identifier"}],"modules":[{"name":"Stripe"}],"symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)requestPayment","roleHeading":"Instance Method","title":"requestPayment()","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"abstract":[{"text":"Requests payment from the user. This may need to present some supplemental UI","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to the user, in which case it will be presented on the payment context’s"},{"type":"text","text":" "},{"type":"codeVoice","code":"hostViewController"},{"text":". For instance, if they’ve selected Apple Pay as their","type":"text"},{"type":"text","text":" "},{"type":"text","text":"payment method, calling this method will show the payment sheet. If the user"},{"type":"text","text":" "},{"text":"has a card on file, this will use that without presenting any additional UI.","type":"text"},{"text":" ","type":"text"},{"text":"After this is called, the ","type":"text"},{"code":"paymentContext:didCreatePaymentResult:completion:","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"and "},{"code":"paymentContext:didFinishWithStatus:error:","type":"codeVoice"},{"type":"text","text":" methods will be called on the"},{"type":"text","text":" "},{"type":"text","text":"context’s "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/requestpayment()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/requestpayment()"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestPayment","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"already showing a view controller, or in the middle of requesting a payment."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/requestPayment()"},"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/requestPayment()":{"navigatorTitle":[{"text":"requestPayment","kind":"identifier"}],"title":"requestPayment()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestPayment"},{"text":"()","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentcontext\/requestpayment()","abstract":[{"text":"Requests payment from the user. This may need to present some supplemental UI","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to the user, in which case it will be presented on the payment context’s"},{"type":"text","text":" "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":". For instance, if they’ve selected Apple Pay as their"},{"type":"text","text":" "},{"text":"payment method, calling this method will show the payment sheet. If the user","type":"text"},{"type":"text","text":" "},{"text":"has a card on file, this will use that without presenting any additional UI.","type":"text"},{"type":"text","text":" "},{"text":"After this is called, the ","type":"text"},{"type":"codeVoice","code":"paymentContext:didCreatePaymentResult:completion:"},{"type":"text","text":" "},{"text":"and ","type":"text"},{"type":"codeVoice","code":"paymentContext:didFinishWithStatus:error:"},{"text":" methods will be called on the","type":"text"},{"type":"text","text":" "},{"text":"context’s ","type":"text"},{"code":"delegate","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/requestPayment()"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"requestPayment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestPayment"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"requestPayment","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"requestPayment","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1requestPayment()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1requestPayment()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"requestPayment","kind":"identifier"}]},{"value":"STPPaymentContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","op":"replace"},{"value":[{"text":"STPPaymentContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
