{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"retryLoading","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"If ","type":"text"},{"code":"paymentContext:didFailToLoadWithError:","type":"codeVoice"},{"type":"text","text":" is called on your delegate, you"},{"type":"text","text":" "},{"text":"can in turn call this method to try loading again (if that hasn’t been called,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"calling this will do nothing). If retrying in turn fails, "},{"type":"codeVoice","code":"paymentContext:didFailToLoadWithError:"},{"type":"text","text":" "},{"text":"will be called again (and you can again call this to keep retrying, etc).","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/retryloading()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/retryloading()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"Stripe"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"retryLoading","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","title":"retryLoading()","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)retryLoading","navigatorTitle":[{"text":"retryLoading","kind":"identifier"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/retryLoading()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/retryLoading()":{"navigatorTitle":[{"text":"retryLoading","kind":"identifier"}],"title":"retryLoading()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"retryLoading","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentcontext\/retryloading()","abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"paymentContext:didFailToLoadWithError:"},{"type":"text","text":" is called on your delegate, you"},{"text":" ","type":"text"},{"text":"can in turn call this method to try loading again (if that hasn’t been called,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"calling this will do nothing). If retrying in turn fails, "},{"type":"codeVoice","code":"paymentContext:didFailToLoadWithError:"},{"text":" ","type":"text"},{"type":"text","text":"will be called again (and you can again call this to keep retrying, etc)."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/retryLoading()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"retryLoading"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"retryLoading"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"retryLoading","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"retryLoading","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1retryLoading()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"retryLoading","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1retryLoading()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"text":"STPPaymentContext","kind":"identifier"}]}]}]}
