{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/selectedShippingMethod"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectedShippingMethod"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKShippingMethod","kind":"typeIdentifier","text":"PKShippingMethod"},{"text":"? { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/selectedshippingmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/selectedshippingmethod"]}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"selectedShippingMethod"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectedShippingMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(py)selectedShippingMethod","modules":[{"name":"Stripe"}],"title":"selectedShippingMethod"},"kind":"symbol","sections":[],"abstract":[{"text":"The user’s currently selected shipping method. May be nil.","type":"text"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/selectedShippingMethod":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"selectedShippingMethod","kind":"identifier"}],"abstract":[{"text":"The user’s currently selected shipping method. May be nil.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"selectedShippingMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PKShippingMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/selectedShippingMethod","title":"selectedShippingMethod","url":"\/documentation\/stripe\/stppaymentcontext\/selectedshippingmethod"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"type":"topic","title":"STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and modifying the customer.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"selectedShippingMethod","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"selectedShippingMethod","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod","text":"PKShippingMethod"},{"text":" * ","kind":"text"},{"text":"selectedShippingMethod","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1selectedShippingMethod\/title","op":"replace","value":"selectedShippingMethod"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1selectedShippingMethod\/fragments","value":[{"text":"selectedShippingMethod","kind":"identifier"}],"op":"replace"},{"value":"STPPaymentContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]}]}]}
