{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddress"},"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(py)shippingAddress","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shippingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","text":"STPAddress"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"Stripe"}],"title":"shippingAddress","navigatorTitle":[{"text":"shippingAddress","kind":"identifier"}]},"abstract":[{"type":"text","text":"The user’s shipping address. May be nil."},{"type":"text","text":" "},{"text":"If you’ve already collected a shipping address from your user, you may","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"prefill it by setting a shippingAddress in PaymentContext’s prefilledInformation."},{"text":" ","type":"text"},{"type":"text","text":"When your user enters a new shipping address, PaymentContext will save it to"},{"text":" ","type":"text"},{"type":"text","text":"the current customer object. When PaymentContext loads, if you haven’t"},{"text":" ","type":"text"},{"type":"text","text":"manually set a prefilled value, any shipping information saved on the customer"},{"text":" ","type":"text"},{"text":"will be used to prefill the shipping address form. Note that because your","type":"text"},{"type":"text","text":" "},{"text":"customer’s email may not be the same as the email provided with their shipping","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"info, PaymentContext will not prefill the shipping form’s email using your"},{"type":"text","text":" "},{"type":"text","text":"customer’s email."},{"text":" ","type":"text"},{"type":"text","text":"You should not rely on the shipping information stored on the Stripe customer"},{"text":" ","type":"text"},{"type":"text","text":"for order fulfillment, as your user may change this information if they make"},{"text":" ","type":"text"},{"text":"multiple purchases. We recommend adding shipping information when you create","type":"text"},{"type":"text","text":" "},{"type":"text","text":"a charge (which can also help prevent fraud), or saving it to your own"},{"text":" ","type":"text"},{"type":"text","text":"database. https:\/\/stripe.com\/docs\/api\/payment_intents\/create#create_payment_intent-shipping"},{"type":"text","text":" "},{"type":"text","text":"Note: by default, your user will still be prompted to verify a prefilled"},{"text":" ","type":"text"},{"text":"shipping address. To change this behavior, you can set","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"verifyPrefilledShippingAddress"},{"type":"text","text":" to NO in your "},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontext\/shippingaddress"]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/shippingaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shippingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","text":"STPAddress"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"kind":"symbol","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"type":"topic","title":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","url":"\/documentation\/stripe\/stpaddress","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAddress","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/shippingAddress":{"abstract":[{"type":"text","text":"The user’s shipping address. May be nil."},{"type":"text","text":" "},{"type":"text","text":"If you’ve already collected a shipping address from your user, you may"},{"text":" ","type":"text"},{"text":"prefill it by setting a shippingAddress in PaymentContext’s prefilledInformation.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"When your user enters a new shipping address, PaymentContext will save it to"},{"type":"text","text":" "},{"type":"text","text":"the current customer object. When PaymentContext loads, if you haven’t"},{"type":"text","text":" "},{"type":"text","text":"manually set a prefilled value, any shipping information saved on the customer"},{"text":" ","type":"text"},{"type":"text","text":"will be used to prefill the shipping address form. Note that because your"},{"type":"text","text":" "},{"type":"text","text":"customer’s email may not be the same as the email provided with their shipping"},{"type":"text","text":" "},{"type":"text","text":"info, PaymentContext will not prefill the shipping form’s email using your"},{"text":" ","type":"text"},{"text":"customer’s email.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You should not rely on the shipping information stored on the Stripe customer"},{"type":"text","text":" "},{"type":"text","text":"for order fulfillment, as your user may change this information if they make"},{"text":" ","type":"text"},{"type":"text","text":"multiple purchases. We recommend adding shipping information when you create"},{"type":"text","text":" "},{"text":"a charge (which can also help prevent fraud), or saving it to your own","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"database. https:\/\/stripe.com\/docs\/api\/payment_intents\/create#create_payment_intent-shipping"},{"text":" ","type":"text"},{"type":"text","text":"Note: by default, your user will still be prompted to verify a prefilled"},{"text":" ","type":"text"},{"type":"text","text":"shipping address. To change this behavior, you can set"},{"type":"text","text":" "},{"type":"codeVoice","code":"verifyPrefilledShippingAddress"},{"text":" to NO in your ","type":"text"},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/stripe\/stppaymentcontext\/shippingaddress","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shippingAddress"},{"kind":"text","text":": "},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"shippingAddress"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddress","title":"shippingAddress","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"shippingAddress"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"shippingAddress","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"shippingAddress","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddress\/title","value":"shippingAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddress\/fragments","value":[{"kind":"identifier","text":"shippingAddress"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext","op":"replace"},{"value":[{"text":"STPPaymentContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
