{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"addressViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"address","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":" "},{"kind":"internalParam","text":"method"},{"text":": ","kind":"text"},{"text":"PKShippingMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"addressViewController","content":[{"inlineContent":[{"text":"the view controller where the address was entered","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the address that was entered. - seealso: STPAddress"}]}],"name":"address"},{"content":[{"type":"paragraph","inlineContent":[{"text":"the shipping method that was selected.","type":"text"}]}],"name":"method"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shippingMethod","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?)"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)shippingAddressViewController:didFinishWithAddress:shippingMethod:","role":"symbol","symbolKind":"method","title":"shippingAddressViewController(_:didFinishWith:shippingMethod:)","navigatorTitle":[{"text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:","kind":"identifier"}],"modules":[{"name":"Stripe"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontroller(_:didfinishwith:shippingmethod:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontroller(_:didfinishwith:shippingmethod:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"This is called when the user selects a shipping method. If no shipping methods are given, or if the shipping type doesn’t require a shipping method, this will be called after the user has a shipping address and your validation has succeeded. After updating your app with the user’s shipping info, you should dismiss (or pop) the view controller. Note that if ","type":"text"},{"code":"shippingMethod","type":"codeVoice"},{"text":" is non-nil, there will be an additional shipping methods view controller on the navigation controller’s stack.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"type":"topic","abstract":[{"text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"title":"STPShippingAddressViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPShippingAddressViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"kind":"symbol","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"type":"topic","title":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","url":"\/documentation\/stripe\/stpaddress","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAddress","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code.","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/shippingAddressViewController(_:didFinishWith:shippingMethod:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","title":"shippingAddressViewController(_:didFinishWith:shippingMethod:)","abstract":[{"type":"text","text":"This is called when the user selects a shipping method. If no shipping methods are given, or if the shipping type doesn’t require a shipping method, this will be called after the user has a shipping address and your validation has succeeded. After updating your app with the user’s shipping info, you should dismiss (or pop) the view controller. Note that if "},{"type":"codeVoice","code":"shippingMethod"},{"type":"text","text":" is non-nil, there will be an additional shipping methods view controller on the navigation controller’s stack."}],"navigatorTitle":[{"text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontroller(_:didfinishwith:shippingmethod:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shippingAddressViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","kind":"typeIdentifier","text":"STPShippingAddressViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":", "},{"text":"shippingMethod","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"shippingAddressViewController:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"addressViewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didFinishWithAddress:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"address"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shippingMethod:"},{"text":"(","kind":"text"},{"text":"PKShippingMethod","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"method"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"STPShippingAddressViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","op":"replace"},{"op":"replace","value":"STPPaymentContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title"},{"value":[{"text":"STPPaymentContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace"},{"value":"shippingAddressViewController:didFinishWithAddress:shippingMethod:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewController(_:didFinishWith:shippingMethod:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewController(_:didFinishWith:shippingMethod:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"}],"op":"replace"}]}]}
