{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"addressViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":" "},{"kind":"internalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka","text":"STPShippingMethodsCompletionBlock"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"addressViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the view controller where the address was entered"}]}]},{"name":"address","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the address that was entered. - seealso: STPAddress"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call this callback when you’re done validating the address and determining available shipping methods."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontroller(_:didenter:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontroller(_:didenter:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didEnter:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is called when the user enters a shipping address and taps next. You"},{"type":"text","text":" "},{"type":"text","text":"should validate the address and determine what shipping methods are available,"},{"type":"text","text":" "},{"type":"text","text":"and call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when finished. If an error occurrs, call"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block with the error. Otherwise, call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" "},{"type":"text","text":"block with a nil error and an array of available shipping methods. If you don’t"},{"type":"text","text":" "},{"type":"text","text":"need to collect a shipping method, you may pass an empty array or nil."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"kind":"text","text":")"}],"title":"shippingAddressViewController(_:didEnter:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext(im)shippingAddressViewController:didEnterAddress:completion:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/shippingAddressViewController(_:didEnter:completion:)":{"role":"symbol","title":"shippingAddressViewController(_:didEnter:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user enters a shipping address and taps next. You"},{"type":"text","text":" "},{"type":"text","text":"should validate the address and determine what shipping methods are available,"},{"type":"text","text":" "},{"type":"text","text":"and call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when finished. If an error occurrs, call"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block with the error. Otherwise, call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" "},{"type":"text","text":"block with a nil error and an array of available shipping methods. If you don’t"},{"type":"text","text":" "},{"type":"text","text":"need to collect a shipping method, you may pass an empty array or nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didEnter:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontroller(_:didenter:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"role":"symbol","title":"STPAddress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}],"url":"\/documentation\/stripe\/stpaddress"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"role":"symbol","title":"STPShippingAddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewController"}],"abstract":[{"type":"text","text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingMethodsCompletionBlock":{"role":"symbol","title":"STPShippingMethodsCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingMethodsCompletionBlock"}],"abstract":[{"type":"text","text":"A callback to be run with a validation result and shipping methods for a"},{"type":"text","text":" "},{"type":"text","text":"shipping address."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingMethodsCompletionBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingMethodsCompletionBlock"}],"url":"\/documentation\/stripe\/stpshippingmethodscompletionblock"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContext"}],"url":"\/documentation\/stripe\/stppaymentcontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"shippingAddressViewController:didEnterAddress:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"shippingAddressViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","text":"STPShippingAddressViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"addressViewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didEnterAddress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"address"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum STPShippingStatus, NSError *, NSArray<PKShippingMethod *> *, PKShippingMethod *)","preciseIdentifier":"c:BFv(#$@M@Stripe@E@STPShippingStatus#*$objc(cs)NSError#*Q$objc(cs)NSArray#*$objc(cs)PKShippingMethod)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewController(_:didEnter:completion:)\/title","value":"shippingAddressViewController:didEnterAddress:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewController(_:didEnter:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","value":"STPShippingAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
