{"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceVerification(py)allResponseFields","title":"allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceverification\/allresponsefields"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceverification\/allresponsefields"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification\/allResponseFields"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] { get }"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerification/allResponseFields":{"type":"topic","url":"\/documentation\/stripepayments\/stpsourceverification\/allresponsefields","role":"symbol","title":"allResponseFields","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification\/allResponseFields","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerification":{"title":"STPSourceVerification","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification","type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSourceVerification","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceverification","abstract":[{"type":"text","text":"Information related to a source’s verification flow."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceVerification","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"allResponseFields","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"allResponseFields","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification~1allResponseFields\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification~1allResponseFields\/fragments","op":"replace","value":[{"kind":"identifier","text":"allResponseFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification\/title","value":"STPSourceVerification"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification\/fragments","value":[{"kind":"identifier","text":"STPSourceVerification"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSourceVerification"}]}]}]}