{"metadata":{"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"status","kind":"identifier"}],"roleHeading":"Instance Property","title":"status","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceVerificationStatus","text":"STPSourceVerificationStatus"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceVerification(py)status"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification\/status"},"abstract":[{"text":"The status of the verification.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","preciseIdentifier":"c:@M@StripePayments@E@STPSourceVerificationStatus","kind":"typeIdentifier","text":"STPSourceVerificationStatus"},{"text":" { get }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceverification\/status"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceverification\/status"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceVerificationStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourceverificationstatus","title":"STPSourceVerificationStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","navigatorTitle":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Verification status types for a Source."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerification":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceVerification"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceVerification","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceverification","abstract":[{"type":"text","text":"Information related to a source’s verification flow."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification","kind":"symbol","title":"STPSourceVerification","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerification/status":{"navigatorTitle":[{"kind":"identifier","text":"status"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceVerificationStatus","kind":"typeIdentifier","text":"STPSourceVerificationStatus"}],"abstract":[{"type":"text","text":"The status of the verification."}],"title":"status","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerification\/status","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceverification\/status","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"status","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"status"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","preciseIdentifier":"c:@M@StripePayments@E@STPSourceVerificationStatus","kind":"typeIdentifier","text":"STPSourceVerificationStatus"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/title","op":"replace","value":"STPSourceVerificationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceVerificationStatus"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceVerificationStatus"}],"op":"replace"},{"op":"replace","value":"STPSourceVerification","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification\/fragments","value":[{"kind":"identifier","text":"STPSourceVerification"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceVerification"}],"op":"replace"},{"value":"status","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification~1status\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerification~1status\/fragments","op":"replace","value":[{"text":"status","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}