{"abstract":[{"type":"text","text":"The action was cancelled by the cardholder\/user."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus\/canceled"},"metadata":{"roleHeading":"Case","title":"STPPaymentHandlerActionStatus.canceled","modules":[{"name":"StripePayments"}],"symbolKind":"case","navigatorTitle":[{"text":"STPPaymentHandlerActionStatusCanceled","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus@STPPaymentHandlerActionStatusCanceled"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandleractionstatus\/canceled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymenthandleractionstatus\/canceled"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"type":"topic","title":"STPPaymentHandlerActionStatus","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"type":"text","text":" represents the possible outcomes of requesting an action by "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":". An action could be confirming and\/or handling the next action for a PaymentIntent."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus/canceled":{"title":"STPPaymentHandlerActionStatus.canceled","type":"topic","abstract":[{"text":"The action was cancelled by the cardholder\/user.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus\/canceled","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus\/canceled","role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatusCanceled","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPPaymentHandlerActionStatusCanceled","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"STPPaymentHandlerActionStatusCanceled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPPaymentHandlerActionStatusCanceled","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","value":"STPPaymentHandlerActionStatus","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus~1canceled\/title","value":"STPPaymentHandlerActionStatusCanceled"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus~1canceled\/fragments","op":"replace","value":[{"text":"STPPaymentHandlerActionStatusCanceled","kind":"identifier"}]}]}]}
