{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus\/failed","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"]]},"metadata":{"title":"STPPaymentHandlerActionStatus.failed","modules":[{"name":"StripePayments"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus@STPPaymentHandlerActionStatusFailed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatusFailed","kind":"identifier"}]},"abstract":[{"type":"text","text":"The action failed. See the error code for more details."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandleractionstatus\/failed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandleractionstatus\/failed"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"title":"STPPaymentHandlerActionStatus","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"type":"topic","abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"type":"text","text":" represents the possible outcomes of requesting an action by "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":". An action could be confirming and\/or handling the next action for a PaymentIntent."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus/failed":{"url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus\/failed","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatusFailed","kind":"identifier"}],"abstract":[{"type":"text","text":"The action failed. See the error code for more details."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus\/failed","kind":"symbol","type":"topic","title":"STPPaymentHandlerActionStatus.failed"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentHandlerActionStatusFailed","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentHandlerActionStatusFailed","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPPaymentHandlerActionStatusFailed","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","value":"STPPaymentHandlerActionStatus"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}]},{"op":"replace","value":"STPPaymentHandlerActionStatusFailed","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus~1failed\/title"},{"value":[{"text":"STPPaymentHandlerActionStatusFailed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus~1failed\/fragments"}]}]}