{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"type":"text","text":"The action succeeded."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionStatusSucceeded"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","title":"STPPaymentHandlerActionStatus.succeeded","role":"symbol","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus@STPPaymentHandlerActionStatusSucceeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"succeeded","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus\/succeeded","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandleractionstatus\/succeeded"]},{"paths":["\/documentation\/stripepayments\/stppaymenthandleractionstatus\/succeeded"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus/succeeded":{"role":"symbol","abstract":[{"type":"text","text":"The action succeeded."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"succeeded","kind":"identifier"}],"kind":"symbol","title":"STPPaymentHandlerActionStatus.succeeded","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus\/succeeded","type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus\/succeeded","navigatorTitle":[{"text":"STPPaymentHandlerActionStatusSucceeded","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"type":"text","text":" represents the possible outcomes of requesting an action by "},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":". An action could be confirming and\/or handling the next action for a PaymentIntent.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"title":"STPPaymentHandlerActionStatus","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"STPPaymentHandlerActionStatusSucceeded","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatusSucceeded"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentHandlerActionStatusSucceeded"}]}]}},{"value":"STPPaymentHandlerActionStatusSucceeded","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus~1succeeded\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus~1succeeded\/fragments","value":[{"text":"STPPaymentHandlerActionStatusSucceeded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","value":"STPPaymentHandlerActionStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle","op":"replace"}]}]}