{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/accountHolderType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccount\/accountholdertype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccount\/accountholdertype"]}],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountHolderType"},{"kind":"text","text":": "},{"text":"STPBankAccountHolderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"accountHolderType"}],"externalID":"c:@M@StripePayments@objc(cs)STPBankAccount(py)accountHolderType","roleHeading":"Instance Property","title":"accountHolderType"},"sections":[],"abstract":[{"type":"text","text":"The type of entity that holds the account."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountHolderType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","text":"STPBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType","kind":"typeIdentifier"},{"kind":"text","text":" { get }"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/accountHolderType":{"type":"topic","navigatorTitle":[{"text":"accountHolderType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/accountHolderType","abstract":[{"type":"text","text":"The type of entity that holds the account."}],"kind":"symbol","title":"accountHolderType","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"accountHolderType","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/accountholdertype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType":{"abstract":[{"text":"The type of entity that holds a bank account.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountHolderType"}],"url":"\/documentation\/stripepayments\/stpbankaccountholdertype","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountHolderType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","kind":"symbol","type":"topic","title":"STPBankAccountHolderType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount":{"type":"topic","navigatorTitle":[{"text":"STPBankAccount","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","abstract":[{"type":"text","text":"Representation of a user’s bank account details that have been tokenized with"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API."}],"kind":"symbol","title":"STPBankAccount","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPBankAccount","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccount"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"accountHolderType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountHolderType"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","text":"STPBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountHolderType"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1accountHolderType\/title","value":"accountHolderType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1accountHolderType\/fragments","op":"replace","value":[{"text":"accountHolderType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/title","value":"STPBankAccountHolderType"},{"value":[{"kind":"identifier","text":"STPBankAccountHolderType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/navigatorTitle","value":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPBankAccount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/fragments","value":[{"text":"STPBankAccount","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/navigatorTitle","value":[{"text":"STPBankAccount","kind":"identifier"}]}]}]}