{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccount\/bankaccountid"]},{"paths":["\/documentation\/stripepayments\/stpbankaccount\/bankaccountid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bankAccountId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/bankAccountId","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPBankAccount(py)bankAccountId","modules":[{"name":"StripePayments"}],"platforms":[],"roleHeading":"Instance Property","title":"bankAccountId","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"bankAccountId","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankAccountId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"abstract":[{"type":"text","text":"The Stripe ID for the bank account."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use stripeID (defined in STPSourceProtocol)"}],"type":"paragraph"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPBankAccount","kind":"identifier"}],"title":"STPBankAccount","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","abstract":[{"type":"text","text":"Representation of a user’s bank account details that have been tokenized with"},{"text":" ","type":"text"},{"text":"the Stripe API.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPBankAccount","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccount"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/bankAccountId":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankAccountId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/bankAccountId","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bankAccountId"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/bankaccountid","type":"topic","abstract":[{"type":"text","text":"The Stripe ID for the bank account."}],"title":"bankAccountId","deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"bankAccountId","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"bankAccountId","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"bankAccountId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/title","value":"STPBankAccount"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBankAccount"}]},{"value":[{"text":"STPBankAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/navigatorTitle","op":"replace"},{"value":"bankAccountId","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1bankAccountId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1bankAccountId\/fragments","value":[{"text":"bankAccountId","kind":"identifier"}]}]}]}