{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/currency"},"kind":"symbol","abstract":[{"text":"The default currency for the bank account.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"title":"currency","externalID":"c:@M@StripePayments@objc(cs)STPBankAccount(py)currency","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccount\/currency"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccount\/currency"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount":{"title":"STPBankAccount","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccount","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccount","kind":"symbol","abstract":[{"type":"text","text":"Representation of a user’s bank account details that have been tokenized with"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API."}],"navigatorTitle":[{"text":"STPBankAccount","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/currency":{"title":"currency","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/currency","abstract":[{"text":"The default currency for the bank account.","type":"text"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/currency"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"currency"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"currency","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/title","op":"replace","value":"STPBankAccount"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBankAccount"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1currency\/title","op":"replace","value":"currency"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1currency\/fragments","op":"replace","value":[{"text":"currency","kind":"identifier"}]}]}]}