{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fingerprint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/fingerprint","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccount\/fingerprint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccount\/fingerprint"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"fingerprint","navigatorTitle":[{"kind":"identifier","text":"fingerprint"}],"externalID":"c:@M@StripePayments@objc(cs)STPBankAccount(py)fingerprint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fingerprint","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount"]]},"sections":[],"abstract":[{"type":"text","text":"A proxy for the account number, this uniquely identifies the account and can be"},{"text":" ","type":"text"},{"type":"text","text":"used to compare equality of different bank accounts."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","abstract":[{"text":"Representation of a user’s bank account details that have been tokenized with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API."}],"navigatorTitle":[{"text":"STPBankAccount","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccount","title":"STPBankAccount","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPBankAccount","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/fingerprint":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccount\/fingerprint","abstract":[{"text":"A proxy for the account number, this uniquely identifies the account and can be","type":"text"},{"type":"text","text":" "},{"type":"text","text":"used to compare equality of different bank accounts."}],"title":"fingerprint","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/fingerprint","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fingerprint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fingerprint"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"fingerprint","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"fingerprint","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"fingerprint","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/title","value":"STPBankAccount"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/fragments","value":[{"text":"STPBankAccount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1fingerprint\/title","value":"fingerprint"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1fingerprint\/fragments","value":[{"kind":"identifier","text":"fingerprint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}