{"metadata":{"title":"apiClient","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAPIClient","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"modules":[{"name":"StripePayments"}],"externalID":"s:14StripePayments23STPBankAccountCollectorC9apiClient0A4Core12STPAPIClientCvp","role":"symbol"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"kind":"symbol","abstract":[{"text":"By default ","type":"text"},{"code":"sharedHandler","type":"codeVoice"},{"text":" initializes with STPAPIClient.shared.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/apiClient"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/apiclient"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/apiClient":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/apiclient","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiClient"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"typeIdentifier","text":"STPAPIClient"}],"abstract":[{"type":"text","text":"By default "},{"code":"sharedHandler","type":"codeVoice"},{"type":"text","text":" initializes with STPAPIClient.shared."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/apiClient","kind":"symbol","title":"apiClient"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}],"navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}],"title":"STPBankAccountCollector","url":"\/documentation\/stripepayments\/stpbankaccountcollector","abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPBankAccountCollector","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments"},{"op":"replace","value":[{"text":"STPBankAccountCollector","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}