{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onEvent"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"FinancialConnectionsEvent","preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Client secret of the payment intent","type":"text"}]}],"name":"clientSecret"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A URL that redirects back to your app to be used to return after completing authentication in another app (such as bank app or Safari).","type":"text"}]}],"name":"returnURL"},{"content":[{"inlineContent":[{"type":"text","text":"Parameters for this call"}],"type":"paragraph"}],"name":"params"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Presenting view controller that will present the modal","type":"text"}]}],"name":"viewController"},{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"onEvent"},{"type":"text","text":" closure is triggered upon the occurrence of specific events during the process of a user connecting their financial accounts."}],"type":"paragraph"}],"name":"onEvent"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" instance with an expanded "},{"type":"codeVoice","code":"paymentMethod"},{"type":"text","text":" containing detailed payment method information"}]}]}],"metadata":{"roleHeading":"Instance Method","title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)","modules":[{"name":"StripePayments"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onEvent","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"FinancialConnectionsEvent","preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier"}],"externalID":"s:14StripePayments23STPBankAccountCollectorC011collectBankD10ForPayment12clientSecret9returnURL6params4from7onEventAA16STPPaymentIntentCSS_SSSgAA010STPCollectgD6ParamsCSo16UIViewControllerCy0A4Core020FinancialConnectionsQ0VcSgtYaKF","role":"symbol"},"abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a PaymentIntent"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:onevent:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","abstract":[{"type":"text","text":"Parameters to use with "},{"type":"codeVoice","code":"STPBankAccountCollector"},{"type":"text","text":" to collect bank account details for payments."}],"role":"symbol","title":"STPCollectBankAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","title":"STPBankAccountCollector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector","abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onEvent","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"FinancialConnectionsEvent","preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier"}],"title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a PaymentIntent"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:onevent:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"title":"STPPaymentIntent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","url":"\/documentation\/stripepayments\/stppaymentintent","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title","op":"replace","value":"STPCollectBankAccountParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments","op":"replace","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle","op":"replace","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","op":"replace","value":"STPBankAccountCollector"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","op":"replace","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollector"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","op":"replace","value":"STPPaymentIntent"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}