{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForSetup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock","text":"STPCollectBankAccountForSetupCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"clientSecret","content":[{"type":"paragraph","inlineContent":[{"text":"Client secret of the setup intent","type":"text"}]}]},{"name":"returnURL","content":[{"inlineContent":[{"text":"A URL that redirects back to your app to be used to return after completing authentication in another app (such as bank app or Safari).","type":"text"}],"type":"paragraph"}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"text":"Parameters for this call","type":"text"}]}]},{"name":"viewController","content":[{"inlineContent":[{"text":"Presenting view controller that will present the modal","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"Completion block to be called on completion of the operation.","type":"text"},{"text":" ","type":"text"},{"text":"Upon success, the ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"text":" instance will have an","type":"text"},{"text":" ","type":"text"},{"text":"expanded ","type":"text"},{"type":"codeVoice","code":"paymentMethod"},{"text":" containing detailed payment method information","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:returnurl:params:from:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:returnurl:params:from:completion:)"]}],"abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"text":"and if completed successfully, link your bank account to a SetupIntent","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPBankAccountCollector(im)collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:","navigatorTitle":[{"text":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForSetup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka","text":"STPCollectBankAccountForSetupCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"StripePayments"}],"title":"collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForSetupCompletionBlock":{"title":"STPBankAccountCollector.STPCollectBankAccountForSetupCompletionBlock","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforsetupcompletionblock","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountForSetupCompletionBlock"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountForSetupCompletionBlock"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","role":"symbol","abstract":[{"text":"Parameters to use with ","type":"text"},{"type":"codeVoice","code":"STPBankAccountCollector"},{"text":" to collect bank account details for payments.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","navigatorTitle":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"identifier"}],"title":"STPCollectBankAccountParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A class responsible for collecting bank account information"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","url":"\/documentation\/stripepayments\/stpbankaccountcollector","title":"STPBankAccountCollector","role":"symbol","navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)","abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a SetupIntent"}],"role":"symbol","title":"collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForSetup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:returnurl:params:from:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"type":"topic","url":"\/documentation\/stripepayments\/stpsetupintent","kind":"symbol","title":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"}],"abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"collectBankAccountForSetupWithClientSecret:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"clientSecret","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"returnURL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"params:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams"},{"text":" *) ","kind":"text"},{"text":"params","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"from:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Client secret of the setup intent","type":"text"}]}],"name":"clientSecret"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A URL that redirects back to your app to be used to return after completing authentication in another app (such as bank app or Safari)."}]}],"name":"returnURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameters for this call","type":"text"}]}],"name":"params"},{"content":[{"inlineContent":[{"text":"Presenting view controller that will present the modal","type":"text"}],"type":"paragraph"}],"name":"viewController"},{"content":[{"inlineContent":[{"type":"text","text":"Completion block to be called on completion of the operation."},{"type":"text","text":" "},{"type":"text","text":"Upon success, the "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":" instance will have an"},{"type":"text","text":" "},{"type":"text","text":"expanded "},{"type":"codeVoice","code":"paymentMethod"},{"type":"text","text":" containing detailed payment method information"}],"type":"paragraph"}],"name":"completion"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"STPCollectBankAccountParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments"},{"op":"replace","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle"},{"op":"replace","value":"STPBankAccountCollector","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle"},{"op":"replace","value":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)\/fragments"},{"op":"replace","value":"STPSetupIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title"},{"op":"replace","value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments"},{"op":"replace","value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle"}]}]}