{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)"},"metadata":{"roleHeading":"Instance Method","title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPBankAccountCollector(im)collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:","role":"symbol"},"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"text":"and if completed successfully, link your bank account to a PaymentIntent","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountForPaymentCompletionBlock","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Client secret of the payment intent"}],"type":"paragraph"}],"name":"clientSecret"},{"content":[{"inlineContent":[{"text":"A URL that redirects back to your app to be used to return after completing authentication in another app (such as bank app or Safari).","type":"text"}],"type":"paragraph"}],"name":"returnURL"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameters for this call","type":"text"}]}],"name":"params"},{"content":[{"inlineContent":[{"type":"text","text":"Presenting view controller that will present the modal"}],"type":"paragraph"}],"name":"viewController"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion block to be called on completion of the operation."},{"type":"text","text":" "},{"type":"text","text":"Upon success, the "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" instance will have an"},{"type":"text","text":" "},{"type":"text","text":"expanded "},{"type":"codeVoice","code":"paymentMethod"},{"type":"text","text":" containing detailed payment method information"}]}],"name":"completion"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)":{"title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a PaymentIntent"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountForPaymentCompletionBlock","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","abstract":[{"type":"text","text":"Parameters to use with "},{"type":"codeVoice","code":"STPBankAccountCollector"},{"type":"text","text":" to collect bank account details for payments."}],"role":"symbol","title":"STPCollectBankAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","title":"STPBankAccountCollector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector","abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForPaymentCompletionBlock":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountForPaymentCompletionBlock"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountForPaymentCompletionBlock"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","title":"STPBankAccountCollector.STPCollectBankAccountForPaymentCompletionBlock","role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforpaymentcompletionblock"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"title":"STPPaymentIntent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","url":"\/documentation\/stripepayments\/stppaymentintent","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"collectBankAccountForPaymentWithClientSecret:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"clientSecret"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"returnURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"params"},{"text":" ","kind":"text"},{"text":"from:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","text":"STPPaymentIntent","kind":"typeIdentifier"},{"text":" *","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" *","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Client secret of the payment intent"}]}],"name":"clientSecret"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A URL that redirects back to your app to be used to return after completing authentication in another app (such as bank app or Safari)."}]}],"name":"returnURL"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameters for this call"}]}],"name":"params"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Presenting view controller that will present the modal","type":"text"}]}],"name":"viewController"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion block to be called on completion of the operation."},{"type":"text","text":" "},{"type":"text","text":"Upon success, the "},{"code":"STPPaymentIntent","type":"codeVoice"},{"type":"text","text":" instance will have an"},{"type":"text","text":" "},{"type":"text","text":"expanded "},{"code":"paymentMethod","type":"codeVoice"},{"type":"text","text":" containing detailed payment method information"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)\/title","value":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title","value":"STPCollectBankAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","value":"STPBankAccountCollector"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"text":"STPPaymentIntent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","value":[{"text":"STPPaymentIntent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}