{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPBankAccountCollector(im)collectBankAccountForSetupWithClientSecret:params:from:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForSetup","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier","text":"STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka","text":"STPCollectBankAccountForSetupCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"collectBankAccountForSetupWithClientSecret:params:from:completion:","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Method","title":"collectBankAccountForSetup(clientSecret:params:from:completion:)","symbolKind":"method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(collectBankAccountForSetupWithClientSecret:params:from:completion:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectBankAccountForSetup","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka","text":"STPCollectBankAccountForSetupCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"text":"Client secret of the setup intent","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameters for this call"}]}],"name":"params"},{"name":"viewController","content":[{"inlineContent":[{"text":"Presenting view controller that will present the modal","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Completion block to be called on completion of the operation.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Upon success, the "},{"type":"codeVoice","code":"STPSetupIntent"},{"text":" instance will have an","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"expanded "},{"code":"paymentMethod","type":"codeVoice"},{"text":" containing detailed payment method information","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:params:from:completion:)"]},{"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:params:from:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:params:from:completion:)"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and if completed successfully, link your bank account to a SetupIntent"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForSetup(clientSecret:params:from:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:params:from:completion:)","title":"collectBankAccountForSetup(clientSecret:params:from:completion:)","type":"topic","abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and if completed successfully, link your bank account to a SetupIntent"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:params:from:completion:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectBankAccountForSetupWithClientSecret:params:from:completion:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectBankAccountForSetup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPCollectBankAccountForSetupCompletionBlock","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountCollector"}],"abstract":[{"type":"text","text":"A class responsible for collecting bank account information"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","role":"symbol","navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}],"kind":"symbol","title":"STPBankAccountCollector","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","abstract":[{"type":"text","text":"Parameters to use with "},{"type":"codeVoice","code":"STPBankAccountCollector"},{"type":"text","text":" to collect bank account details for payments."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"identifier"}],"title":"STPCollectBankAccountParams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSetupIntent","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"abstract":[{"text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintent","title":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForSetupCompletionBlock":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforsetupcompletionblock","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}],"title":"STPBankAccountCollector.STPCollectBankAccountForSetupCompletionBlock","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountForSetupCompletionBlock"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"collectBankAccountForSetupWithClientSecret:params:from:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"collectBankAccountForSetupWithClientSecret:params:from:completion:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"collectBankAccountForSetupWithClientSecret:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"clientSecret"},{"kind":"text","text":" "},{"kind":"identifier","text":"params:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"params"},{"text":" ","kind":"text"},{"text":"from:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"type":"text","text":"Client secret of the setup intent"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Parameters for this call","type":"text"}],"type":"paragraph"}],"name":"params"},{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"text":"Presenting view controller that will present the modal","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Completion block to be called on completion of the operation.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Upon success, the "},{"code":"STPSetupIntent","type":"codeVoice"},{"type":"text","text":" instance will have an"},{"text":" ","type":"text"},{"type":"text","text":"expanded "},{"code":"paymentMethod","type":"codeVoice"},{"type":"text","text":" containing detailed payment method information"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"collectBankAccountForSetupWithClientSecret:params:from:completion:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForSetup(clientSecret:params:from:completion:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForSetup(clientSecret:params:from:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectBankAccountForSetupWithClientSecret:params:from:completion:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","value":"STPBankAccountCollector"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title","op":"replace","value":"STPCollectBankAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","value":[{"text":"STPSetupIntent","kind":"identifier"}]},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}