{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(collectBankAccountForPaymentWithClientSecret:params:from:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectBankAccountForPayment"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","text":"STPCollectBankAccountForPaymentCompletionBlock"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Client secret of the payment intent"}],"type":"paragraph"}],"name":"clientSecret"},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameters for this call"}]}]},{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Presenting view controller that will present the modal"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Completion block to be called on completion of the operation.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Upon success, the "},{"type":"codeVoice","code":"STPPaymentIntent"},{"text":" instance will have an","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"expanded "},{"type":"codeVoice","code":"paymentMethod"},{"text":" containing detailed payment method information","type":"text"}]}],"name":"completion"}],"kind":"parameters"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:params:from:completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a PaymentIntent"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"collectBankAccountForPaymentWithClientSecret:params:from:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectBankAccountForPayment"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","kind":"typeIdentifier","text":"STPCollectBankAccountForPaymentCompletionBlock"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","title":"collectBankAccountForPayment(clientSecret:params:from:completion:)","modules":[{"name":"StripePayments"}],"symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPBankAccountCollector(im)collectBankAccountForPaymentWithClientSecret:params:from:completion:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:params:from:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:params:from:completion:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForPaymentCompletionBlock":{"abstract":[],"navigatorTitle":[{"text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforpaymentcompletionblock","kind":"symbol","title":"STPBankAccountCollector.STPCollectBankAccountForPaymentCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"role":"symbol","abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"url":"\/documentation\/stripepayments\/stppaymentintent","navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"title":"STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","title":"STPCollectBankAccountParams","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountParams"}],"abstract":[{"text":"Parameters to use with ","type":"text"},{"type":"codeVoice","code":"STPBankAccountCollector"},{"type":"text","text":" to collect bank account details for payments."}],"navigatorTitle":[{"text":"STPCollectBankAccountParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"title":"STPBankAccountCollector","role":"symbol","navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountCollector"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector","abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForPayment(clientSecret:params:from:completion:)":{"abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"text":"and if completed successfully, link your bank account to a PaymentIntent","type":"text"}],"navigatorTitle":[{"text":"collectBankAccountForPaymentWithClientSecret:params:from:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForPayment"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:params:from:completion:)","kind":"symbol","title":"collectBankAccountForPayment(clientSecret:params:from:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:params:from:completion:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"collectBankAccountForPaymentWithClientSecret:params:from:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"collectBankAccountForPaymentWithClientSecret:params:from:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"collectBankAccountForPaymentWithClientSecret:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"clientSecret"},{"text":" ","kind":"text"},{"text":"params:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"params","kind":"internalParam"},{"kind":"text","text":" "},{"text":"from:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"text":"Client secret of the payment intent","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameters for this call","type":"text"}]}],"name":"params"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Presenting view controller that will present the modal"}]}],"name":"viewController"},{"content":[{"inlineContent":[{"text":"Completion block to be called on completion of the operation.","type":"text"},{"text":" ","type":"text"},{"text":"Upon success, the ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" instance will have an"},{"type":"text","text":" "},{"text":"expanded ","type":"text"},{"code":"paymentMethod","type":"codeVoice"},{"type":"text","text":" containing detailed payment method information"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"text":"STPPaymentIntent","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPPaymentIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title","value":"STPCollectBankAccountParams"},{"value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","value":"STPBankAccountCollector"},{"value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","value":[{"text":"STPBankAccountCollector","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"collectBankAccountForPaymentWithClientSecret:params:from:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForPayment(clientSecret:params:from:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectBankAccountForPaymentWithClientSecret:params:from:completion:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForPayment(clientSecret:params:from:completion:)\/fragments","op":"replace"}]}]}