{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForSetup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier","text":"STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onEvent"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","kind":"typeIdentifier","text":"FinancialConnectionsEvent"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka","kind":"typeIdentifier","text":"STPCollectBankAccountForSetupCompletionBlock"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"clientSecret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Client secret of the setup intent"}]}]},{"name":"returnURL","content":[{"inlineContent":[{"type":"text","text":"A URL that redirects back to your app to be used to return after completing authentication in another app (such as bank app or Safari)."}],"type":"paragraph"}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"text":"Parameters for this call","type":"text"}]}]},{"name":"viewController","content":[{"inlineContent":[{"text":"Presenting view controller that will present the modal","type":"text"}],"type":"paragraph"}]},{"name":"onEvent","content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"onEvent","type":"codeVoice"},{"text":" closure is triggered upon the occurrence of specific events during the process of a user connecting their financial accounts.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"text":"Completion block to be called on completion of the operation.","type":"text"},{"text":" ","type":"text"},{"text":"Upon success, the ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"text":" instance will have an","type":"text"},{"text":" ","type":"text"},{"text":"expanded ","type":"text"},{"type":"codeVoice","code":"paymentMethod"},{"text":" containing detailed payment method information","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForSetup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onEvent"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"FinancialConnectionsEvent","preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCollectBankAccountForSetupCompletionBlock","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka"},{"kind":"text","text":")"}],"modules":[{"name":"StripePayments"}],"symbolKind":"method","externalID":"s:14StripePayments23STPBankAccountCollectorC011collectBankD8ForSetup12clientSecret9returnURL6params4from7onEvent10completionySS_SSSgAA010STPCollectgD6ParamsCSo16UIViewControllerCy0A4Core020FinancialConnectionsQ0VcSgyAA14STPSetupIntentCSg_So7NSErrorCSgtctF","title":"collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)","roleHeading":"Instance Method"},"abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"text":"and if completed successfully, link your bank account to a SetupIntent","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:returnurl:params:from:onevent:completion:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:returnurl:params:from:onevent:completion:)","title":"collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForSetup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onEvent","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","text":"FinancialConnectionsEvent","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka","text":"STPCollectBankAccountForSetupCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)","type":"topic","abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a SetupIntent"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForSetupCompletionBlock":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforsetupcompletionblock","title":"STPBankAccountCollector.STPCollectBankAccountForSetupCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"kind":"symbol","navigatorTitle":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"type":"topic","title":"STPCollectBankAccountParams","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Parameters to use with "},{"type":"codeVoice","code":"STPBankAccountCollector"},{"type":"text","text":" to collect bank account details for payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}],"abstract":[{"type":"text","text":"A class responsible for collecting bank account information"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}],"role":"symbol","title":"STPBankAccountCollector","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title","value":"STPCollectBankAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","value":"STPBankAccountCollector"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}