{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onEvent","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","text":"FinancialConnectionsEvent","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"s:14StripePayments23STPBankAccountCollectorC011collectBankD10ForPayment12clientSecret9returnURL6params4from7onEvent10completionySS_SSSgAA010STPCollectgD6ParamsCSo16UIViewControllerCy0A4Core020FinancialConnectionsQ0VcSgyAA16STPPaymentIntentCSg_So7NSErrorCSgtctF","modules":[{"name":"StripePayments"}],"title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)","symbolKind":"method","role":"symbol"},"abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"text":"and if completed successfully, link your bank account to a PaymentIntent","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:onevent:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onEvent","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","text":"FinancialConnectionsEvent","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","text":"STPCollectBankAccountForPaymentCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"clientSecret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Client secret of the payment intent"}]}]},{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A URL that redirects back to your app to be used to return after completing authentication in another app (such as bank app or Safari)."}]}]},{"name":"params","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameters for this call"}]}]},{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Presenting view controller that will present the modal"}]}]},{"name":"onEvent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"onEvent","type":"codeVoice"},{"type":"text","text":" closure is triggered upon the occurrence of specific events during the process of a user connecting their financial accounts."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion block to be called on completion of the operation."},{"type":"text","text":" "},{"type":"text","text":"Upon success, the "},{"code":"STPPaymentIntent","type":"codeVoice"},{"type":"text","text":" instance will have an"},{"type":"text","text":" "},{"type":"text","text":"expanded "},{"code":"paymentMethod","type":"codeVoice"},{"type":"text","text":" containing detailed payment method information"}]}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"abstract":[{"text":"Parameters to use with ","type":"text"},{"code":"STPBankAccountCollector","type":"codeVoice"},{"text":" to collect bank account details for payments.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","kind":"symbol","type":"topic","title":"STPCollectBankAccountParams","role":"symbol","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollector"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","title":"STPBankAccountCollector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollector"}],"abstract":[{"type":"text","text":"A class responsible for collecting bank account information"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a PaymentIntent"}],"title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onEvent"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"FinancialConnectionsEvent","preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCollectBankAccountForPaymentCompletionBlock","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:onevent:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForPaymentCompletionBlock":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountForPaymentCompletionBlock"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","title":"STPBankAccountCollector.STPCollectBankAccountForPaymentCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountForPaymentCompletionBlock"}],"abstract":[],"kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforpaymentcompletionblock"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title","op":"replace","value":"STPCollectBankAccountParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments","op":"replace","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle","op":"replace","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","op":"replace","value":"STPBankAccountCollector"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","op":"replace","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]}]}]}