{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(apiClient:style:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/init(apiclient:style:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"apiClient","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier"},{"text":" = .shared, ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","text":"STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier"},{"text":" = .automatic)","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"init","role":"symbol","title":"init(apiClient:style:)","roleHeading":"Initializer","externalID":"s:14StripePayments23STPBankAccountCollectorC9apiClient5styleAC0A4Core12STPAPIClientC_AA0cdE18UserInterfaceStyleOtcfc","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiClient"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"typeIdentifier","text":"STPAPIClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier","text":"STPBankAccountCollectorUserInterfaceStyle"},{"kind":"text","text":")"}],"modules":[{"name":"StripePayments"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/init(apiClient:style:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(apiClient:style:)","kind":"symbol","type":"topic","title":"init(apiClient:style:)","abstract":[],"role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/init(apiclient:style:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiClient"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"typeIdentifier","text":"STPAPIClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier","text":"STPBankAccountCollectorUserInterfaceStyle"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector","title":"STPBankAccountCollector","abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollector"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollector"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","kind":"symbol","title":"STPBankAccountCollectorUserInterfaceStyle","type":"topic","abstract":[{"type":"text","text":"Style options for colors in the bank account collector."}],"role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle","navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPBankAccountCollector","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title"},{"value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments"},{"value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle"},{"value":"STPBankAccountCollectorUserInterfaceStyle","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/title"},{"value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/fragments"},{"value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/navigatorTitle"}]}]}