{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(style:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithStyle:) ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","text":"STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","text":"STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithStyle:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init","platforms":[],"modules":[{"name":"StripePayments"}],"role":"symbol","title":"init(style:)","externalID":"c:@M@StripePayments@objc(cs)STPBankAccountCollector(im)initWithStyle:"},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/init(style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/init(style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/init(style:)":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/init(style:)","title":"init(style:)","kind":"symbol","deprecated":true,"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(style:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","text":"STPBankAccountCollectorUserInterfaceStyle"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle":{"kind":"symbol","title":"STPBankAccountCollectorUserInterfaceStyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","abstract":[{"type":"text","text":"Style options for colors in the bank account collector."}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","abstract":[{"type":"text","text":"A class responsible for collecting bank account information"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollector"}],"role":"symbol","title":"STPBankAccountCollector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollector"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithStyle:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStyle:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStyle:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier","text":"STPBankAccountCollectorUserInterfaceStyle"},{"kind":"text","text":") "},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/deprecationSummary","op":"add","value":[]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1init(style:)\/title","op":"replace","value":"initWithStyle:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1init(style:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/title","op":"replace","value":"STPBankAccountCollectorUserInterfaceStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","op":"replace","value":"STPBankAccountCollector"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollector"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}