{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","externalID":"s:14StripePayments23STPBankAccountCollectorC9apiClientAC0A4Core12STPAPIClientC_tcfc","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"apiClient","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(apiClient:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(apiClient:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiClient"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient"},{"text":" = .shared)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/init(apiclient:)"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"role":"symbol","title":"STPAPIClient","type":"topic","url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/init(apiClient:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(apiClient:)","abstract":[],"kind":"symbol","title":"init(apiClient:)","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/init(apiclient:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"apiClient","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"type":"topic","abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}],"role":"symbol","kind":"symbol","title":"STPBankAccountCollector","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","url":"\/documentation\/stripepayments\/stpbankaccountcollector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountCollector"}],"navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPBankAccountCollector","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"op":"replace"}]}]}
