{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforpaymentcompletionblock"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountForPaymentCompletionBlock"}],"roleHeading":"Type Alias","externalID":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","navigatorTitle":[{"text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"identifier"}],"symbolKind":"typealias","modules":[{"name":"StripePayments"}],"title":"STPBankAccountCollector.STPCollectBankAccountForPaymentCompletionBlock","role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollector"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","title":"STPBankAccountCollector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollector"}],"abstract":[{"type":"text","text":"A class responsible for collecting bank account information"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForPaymentCompletionBlock":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountForPaymentCompletionBlock"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","title":"STPBankAccountCollector.STPCollectBankAccountForPaymentCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountForPaymentCompletionBlock"}],"abstract":[],"kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforpaymentcompletionblock"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"kind":"symbol","type":"topic","title":"STPPaymentIntent","abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","url":"\/documentation\/stripepayments\/stppaymentintent"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","value":"STPBankAccountCollector","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntent"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntent"}],"op":"replace"}]}]}