{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforsetupcompletionblock"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"STPBankAccountCollector.STPCollectBankAccountForSetupCompletionBlock","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Type Alias","externalID":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka","navigatorTitle":[{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountForSetupCompletionBlock"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"STPSetupIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForSetupCompletionBlock":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock","abstract":[],"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforsetupcompletionblock","kind":"symbol","title":"STPBankAccountCollector.STPCollectBankAccountForSetupCompletionBlock","navigatorTitle":[{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollector"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollector"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollector","type":"topic","abstract":[{"type":"text","text":"A class responsible for collecting bank account information"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","title":"STPBankAccountCollector","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsetupintent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"kind":"symbol","role":"symbol","title":"STPSetupIntent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","op":"replace","value":"STPBankAccountCollector"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","op":"replace","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPBankAccountCollector","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle"},{"op":"replace","value":"STPSetupIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle"}]}]}