{"sections":[],"metadata":{"symbolKind":"property","externalID":"s:14StripePayments23STPBankAccountCollectorC5styleAA0cdE18UserInterfaceStyleOvp","modules":[{"name":"StripePayments"}],"role":"symbol","title":"style","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPBankAccountCollectorUserInterfaceStyle","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector\/style"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"text":"STPBankAccountCollectorUserInterfaceStyle","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/style"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Style options for the bank account collector."},{"type":"text","text":" "},{"type":"text","text":"By default, the bank account collector will automatically switch between light and dark mode compatible colors based on device settings."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle","navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"abstract":[{"text":"Style options for colors in the bank account collector.","type":"text"}],"title":"STPBankAccountCollectorUserInterfaceStyle"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","title":"STPBankAccountCollector","role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector","navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/style":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/style","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/style","abstract":[{"type":"text","text":"Style options for the bank account collector."},{"text":" ","type":"text"},{"type":"text","text":"By default, the bank account collector will automatically switch between light and dark mode compatible colors based on device settings."}],"type":"topic","kind":"symbol","role":"symbol","title":"style","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier","text":"STPBankAccountCollectorUserInterfaceStyle"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/title","op":"replace","value":"STPBankAccountCollectorUserInterfaceStyle"},{"value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","value":"STPBankAccountCollector"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","value":[{"text":"STPBankAccountCollector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccountCollector","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}