{"abstract":[{"text":"This field indicates whether this payment method can be shown again to its customer in a checkout flow","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview\/allowRedisplay"},"metadata":{"roleHeading":"Instance Property","title":"allowRedisplay","symbolKind":"property","modules":[{"name":"StripePayments"}],"externalID":"s:14StripePayments23STPPaymentMethodPreviewC14allowRedisplayAA0cd5AllowG0Ovp","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowRedisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay","text":"STPPaymentMethodAllowRedisplay"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowRedisplay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAllowRedisplay","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay"},{"text":" { get }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodpreview\/allowredisplay"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview":{"title":"STPPaymentMethodPreview","type":"topic","navigatorTitle":[{"text":"STPPaymentMethodPreview","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPreview","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodpreview","role":"symbol","abstract":[{"text":"Preview of payment method details captured by the ConfirmationToken.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview/allowRedisplay":{"url":"\/documentation\/stripepayments\/stppaymentmethodpreview\/allowredisplay","abstract":[{"type":"text","text":"This field indicates whether this payment method can be shown again to its customer in a checkout flow"}],"type":"topic","title":"allowRedisplay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview\/allowRedisplay","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowRedisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodAllowRedisplay","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Values for STPPaymentMethodAllowRedisplay"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay","title":"STPPaymentMethodAllowRedisplay","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"STPPaymentMethodPreview","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodPreview"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/fragments"},{"value":[{"text":"STPPaymentMethodPreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/navigatorTitle"},{"value":"STPPaymentMethodAllowRedisplay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/fragments"},{"value":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}