{"abstract":[{"type":"text","text":"If this is a card PaymentMethod, this contains the user’s card details."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","text":"STPPaymentMethodCard","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodpreview\/card"]}],"metadata":{"externalID":"s:14StripePayments23STPPaymentMethodPreviewC4cardAA0cD4CardCSgvp","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"role":"symbol","title":"card","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCard","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard"},{"text":"?","kind":"text"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview\/card","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview":{"kind":"symbol","abstract":[{"type":"text","text":"Preview of payment method details captured by the ConfirmationToken."}],"title":"STPPaymentMethodPreview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPreview","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodPreview","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodpreview","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview/card":{"title":"card","abstract":[{"type":"text","text":"If this is a card PaymentMethod, this contains the user’s card details."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview\/card","url":"\/documentation\/stripepayments\/stppaymentmethodpreview\/card","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard","text":"STPPaymentMethodCard","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"kind":"symbol","type":"topic","title":"STPPaymentMethodCard","abstract":[{"type":"text","text":"Contains details about a user’s credit card."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCard","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","navigatorTitle":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcard","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"STPPaymentMethodPreview","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodPreview"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodPreview"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/navigatorTitle"},{"value":"STPPaymentMethodCard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title"},{"value":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodCard"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}