{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview\/decodedObject(fromAPIResponse:)"},"sections":[],"metadata":{"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodPreview(cm)decodedObjectFromAPIResponse:","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"roleHeading":"Type Method","modules":[{"name":"StripePayments"}],"title":"decodedObject(fromAPIResponse:)","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodpreview\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodpreview\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The JSON dictionary that represents an object of this type"}]}],"name":"response"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The object represented by the JSON dictionary, or nil if the object"},{"type":"text","text":" "},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview":{"title":"STPPaymentMethodPreview","abstract":[{"type":"text","text":"Preview of payment method details captured by the ConfirmationToken."}],"url":"\/documentation\/stripepayments\/stppaymentmethodpreview","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPreview","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodPreview","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview/decodedObject(fromAPIResponse:)":{"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic","title":"decodedObject(fromAPIResponse:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview\/decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stppaymentmethodpreview\/decodedobject(fromapiresponse:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"decodedObjectFromAPIResponse:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The JSON dictionary that represents an object of this type"}],"type":"paragraph"}],"name":"response"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The object represented by the JSON dictionary, or nil if the object"},{"type":"text","text":" "},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/title","op":"replace","value":"STPPaymentMethodPreview"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodPreview"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodPreview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview~1decodedObject(fromAPIResponse:)\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview~1decodedObject(fromAPIResponse:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]}]}]}