{"abstract":[{"text":"Type of the payment method.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview\/type"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","text":"STPPaymentMethodType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"},{"kind":"text","text":" { get }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodpreview\/type"]}],"metadata":{"role":"symbol","externalID":"s:14StripePayments23STPPaymentMethodPreviewC4typeAA0cD4TypeOvp","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"symbolKind":"property","title":"type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodType"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodType"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","title":"STPPaymentMethodType","url":"\/documentation\/stripepayments\/stppaymentmethodtype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview":{"title":"STPPaymentMethodPreview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodPreview"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview","type":"topic","abstract":[{"text":"Preview of payment method details captured by the ConfirmationToken.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodpreview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodPreview"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPreview/type":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodpreview\/type","title":"type","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPreview\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType"}],"abstract":[{"text":"Type of the payment method.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","value":"STPPaymentMethodType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/title","value":"STPPaymentMethodPreview"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodPreview"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPreview\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodPreview"}]}]}]}