{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSwishParams"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodswishparams\/init"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSwishParams\/init"},"sections":[],"metadata":{"roleHeading":"Instance Method","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodSwishParams(im)init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSwishParams/init":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSwishParams\/init","abstract":[],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodswishparams\/init","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSwishParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a Swish Payment Method"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSwishParams","url":"\/documentation\/stripepayments\/stppaymentmethodswishparams","role":"symbol","title":"STPPaymentMethodSwishParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodSwishParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodSwishParams","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSwishParams\/title","op":"replace","value":"STPPaymentMethodSwishParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSwishParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodSwishParams"}],"op":"replace"},{"op":"replace","value":[{"text":"STPPaymentMethodSwishParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSwishParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}