{"abstract":[{"text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:","type":"text"},{"text":" ","type":"text"},{"text":"var cardParams = STPCardParams()","type":"text"},{"text":" ","type":"text"},{"text":"\/\/ add card values","type":"text"},{"text":" ","type":"text"},{"text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]","type":"text"},{"text":" ","type":"text"},{"text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable\/additionalAPIParameters","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"additionalAPIParameters","symbolKind":"property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"required":true,"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"externalID":"c:@M@StripePayments@objc(pl)STPFormEncodable(py)additionalAPIParameters"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpformencodable\/additionalapiparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpformencodable\/additionalapiparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable/additionalAPIParameters":{"url":"\/documentation\/stripepayments\/stpformencodable\/additionalapiparameters","required":true,"role":"symbol","kind":"symbol","abstract":[{"text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:","type":"text"},{"text":" ","type":"text"},{"text":"var cardParams = STPCardParams()","type":"text"},{"text":" ","type":"text"},{"text":"\/\/ add card values","type":"text"},{"text":" ","type":"text"},{"text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]","type":"text"},{"text":" ","type":"text"},{"text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);","type":"text"}],"navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"title":"additionalAPIParameters","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable\/additionalAPIParameters","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpformencodable","abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}],"title":"STPFormEncodable","navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"additionalAPIParameters","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"additionalAPIParameters","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"additionalAPIParameters","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable~1additionalAPIParameters\/title"},{"value":[{"kind":"identifier","text":"additionalAPIParameters"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable~1additionalAPIParameters\/fragments"},{"value":"STPFormEncodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"value":[{"kind":"identifier","text":"STPFormEncodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"value":[{"kind":"identifier","text":"STPFormEncodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}