{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(py)cardParams","symbolKind":"property","role":"symbol","title":"cardParams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardParams"},{"kind":"text","text":": "},{"text":"STPPaymentMethodCardParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"}],"navigatorTitle":[{"kind":"identifier","text":"cardParams"}],"platforms":[],"modules":[{"name":"StripePaymentsUI"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/cardparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/cardparams"]}],"abstract":[{"text":"Convenience property for creating an ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodCardParams"},{"text":" from the currently entered information","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or programmatically setting the field’s contents. For example, if you’re using another library"},{"text":" ","type":"text"},{"type":"text","text":"to scan your user’s credit card with a camera, you can assemble that data into an "},{"code":"STPPaymentMethodCardParams","type":"codeVoice"},{"text":" ","type":"text"},{"text":"object and set this property to that object to prefill the fields you’ve collected.","type":"text"},{"type":"text","text":" "},{"text":"Accessing this property returns a ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"copied"}]},{"type":"text","text":" "},{"type":"codeVoice","code":"cardParams"},{"text":". The only way to change properties in this","type":"text"},{"type":"text","text":" "},{"text":"object is to make changes to a ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodCardParams"},{"type":"text","text":" you own (retrieved from this text field if desired),"},{"type":"text","text":" "},{"type":"text","text":"and then set this property to the new value."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/cardParams","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cardParams","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","text":"STPPaymentMethodCardParams"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Deprecated. Use "},{"code":".paymentMethodParams","type":"codeVoice"},{"type":"text","text":" instead. If you must access the STPPaymentMethodCardParams, use "},{"type":"codeVoice","code":".paymentMethodParams.card"},{"text":".","type":"text"}]}],"type":"aside","style":"warning","name":"Warning"}],"kind":"content"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use .paymentMethodParams instead. If you must access the STPPaymentMethodCardParams, use .paymentMethodParams.card."}]}],"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextField"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","title":"STPPaymentCardTextField","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentMethodCardParams":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodCardParams","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentmethodcardparams","kind":"symbol","role":"symbol","title":"STPPaymentMethodCardParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"abstract":[{"type":"text","text":"The user’s card details."}],"navigatorTitle":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/cardParams":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/cardParams","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/cardparams","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cardParams","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"}],"navigatorTitle":[{"kind":"identifier","text":"cardParams"}],"role":"symbol","abstract":[{"text":"Convenience property for creating an ","type":"text"},{"code":"STPPaymentMethodCardParams","type":"codeVoice"},{"type":"text","text":" from the currently entered information"},{"type":"text","text":" "},{"type":"text","text":"or programmatically setting the field’s contents. For example, if you’re using another library"},{"text":" ","type":"text"},{"type":"text","text":"to scan your user’s credit card with a camera, you can assemble that data into an "},{"code":"STPPaymentMethodCardParams","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"object and set this property to that object to prefill the fields you’ve collected."},{"type":"text","text":" "},{"type":"text","text":"Accessing this property returns a "},{"inlineContent":[{"type":"text","text":"copied"}],"type":"emphasis"},{"type":"text","text":" "},{"type":"codeVoice","code":"cardParams"},{"text":". The only way to change properties in this","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"object is to make changes to a "},{"type":"codeVoice","code":"STPPaymentMethodCardParams"},{"type":"text","text":" you own (retrieved from this text field if desired),"},{"type":"text","text":" "},{"text":"and then set this property to the new value.","type":"text"}],"kind":"symbol","deprecated":false,"title":"cardParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"cardParams","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cardParams","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodCardParams","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"},{"kind":"text","text":" * "},{"text":"cardParams","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"STPPaymentCardTextField","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"op":"replace","value":"cardParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1cardParams\/title"},{"value":[{"text":"cardParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1cardParams\/fragments","op":"replace"}]}]}
