{"sections":[],"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)contextMenuInteraction:configurationForMenuAtLocation:","navigatorTitle":[{"text":"contextMenuInteraction:configurationForMenuAtLocation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contextMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIContextMenuInteraction","text":"UIContextMenuInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configurationForMenuAtLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIContextMenuConfiguration","text":"UIContextMenuConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePaymentsUI"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"contextMenuInteraction(_:configurationForMenuAtLocation:)"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/contextmenuinteraction(_:configurationformenuatlocation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/contextmenuinteraction(_:configurationformenuatlocation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contextMenuInteraction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"interaction","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIContextMenuInteraction","preciseIdentifier":"c:objc(cs)UIContextMenuInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configurationForMenuAtLocation","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"location","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIContextMenuConfiguration","preciseIdentifier":"c:objc(cs)UIContextMenuConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/contextMenuInteraction(_:configurationForMenuAtLocation:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/contextMenuInteraction(_:configurationForMenuAtLocation:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contextMenuInteraction","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIContextMenuInteraction","text":"UIContextMenuInteraction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"configurationForMenuAtLocation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIContextMenuConfiguration","text":"UIContextMenuConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/contextmenuinteraction(_:configurationformenuatlocation:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"contextMenuInteraction:configurationForMenuAtLocation:","kind":"identifier"}],"title":"contextMenuInteraction(_:configurationForMenuAtLocation:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/contextMenuInteraction(_:configurationForMenuAtLocation:)","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextField"}],"title":"STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui","title":"StripePaymentsUI","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"contextMenuInteraction:configurationForMenuAtLocation:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contextMenuInteraction:configurationForMenuAtLocation:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"UIContextMenuConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIContextMenuConfiguration"},{"text":" *) ","kind":"text"},{"text":"contextMenuInteraction:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIContextMenuInteraction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIContextMenuInteraction"},{"text":" *) ","kind":"text"},{"text":"interaction","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"configurationForMenuAtLocation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") ","kind":"text"},{"text":"location","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1contextMenuInteraction(_:configurationForMenuAtLocation:)\/title","value":"contextMenuInteraction:configurationForMenuAtLocation:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"contextMenuInteraction:configurationForMenuAtLocation:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1contextMenuInteraction(_:configurationForMenuAtLocation:)\/fragments","op":"replace"},{"value":"STPPaymentCardTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace"},{"value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}