{"sections":[],"metadata":{"navigatorTitle":[{"text":"cornerRadius","kind":"identifier"}],"modules":[{"name":"StripePaymentsUI"}],"title":"cornerRadius","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(py)cornerRadius"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/cornerRadius","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/cornerradius"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/cornerradius"]}],"abstract":[{"text":"The corner radius for the field’s border.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is 5.0."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"text":"multiple UITextFields under the hood to collect this information. It’s","type":"text"},{"type":"text","text":" "},{"text":"designed to fit on a single line, and from a design perspective can be used","type":"text"},{"type":"text","text":" "},{"text":"anywhere a UITextField would be appropriate.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"kind":"symbol","title":"STPPaymentCardTextField"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/cornerRadius":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cornerRadius","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","type":"topic","abstract":[{"text":"The corner radius for the field’s border.","type":"text"},{"type":"text","text":" "},{"text":"Default is 5.0.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/cornerradius","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/cornerRadius","title":"cornerRadius","navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"cornerRadius"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"cornerRadius","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":" "},{"text":"cornerRadius","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1cornerRadius\/title","value":"cornerRadius","op":"replace"},{"value":[{"kind":"identifier","text":"cornerRadius"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1cornerRadius\/fragments"}]}]}