{"kind":"symbol","metadata":{"modules":[{"name":"StripePaymentsUI"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(py)countryCode","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"countryCode","kind":"identifier"}],"title":"countryCode"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"The two-letter ISO country code that corresponds to the user’s billing address."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"postalCodeEntryEnabled"},{"type":"text","text":" is YES, this controls which type of entry is allowed."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"postalCodeEntryEnabled"},{"type":"text","text":" is NO, this property currently has no effect."},{"type":"text","text":" "},{"type":"text","text":"If set to nil and postal code entry is enabled, the country from the user’s current"},{"type":"text","text":" "},{"type":"text","text":"locale will be filled in. Otherwise the specific country code set will be used."},{"type":"text","text":" "},{"type":"text","text":"By default this will fetch the user’s current country code from NSLocale."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/countryCode","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/countrycode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/countrycode"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/countryCode":{"title":"countryCode","abstract":[{"text":"The two-letter ISO country code that corresponds to the user’s billing address.","type":"text"},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"type":"codeVoice","code":"postalCodeEntryEnabled"},{"text":" is YES, this controls which type of entry is allowed.","type":"text"},{"text":" ","type":"text"},{"text":"If ","type":"text"},{"type":"codeVoice","code":"postalCodeEntryEnabled"},{"text":" is NO, this property currently has no effect.","type":"text"},{"text":" ","type":"text"},{"text":"If set to nil and postal code entry is enabled, the country from the user’s current","type":"text"},{"text":" ","type":"text"},{"text":"locale will be filled in. Otherwise the specific country code set will be used.","type":"text"},{"text":" ","type":"text"},{"text":"By default this will fetch the user’s current country code from NSLocale.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"countryCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"countryCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/countryCode","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/countrycode"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","type":"topic","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"title":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"countryCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"countryCode","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"countryCode"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1countryCode\/title","op":"replace","value":"countryCode"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1countryCode\/fragments","op":"replace","value":[{"text":"countryCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace","value":"STPPaymentCardTextField"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","op":"replace","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}