{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteBackward","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)deleteBackward","modules":[{"name":"StripePaymentsUI"}],"symbolKind":"method","title":"deleteBackward()","roleHeading":"Instance Method","navigatorTitle":[{"text":"deleteBackward","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteBackward"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/deleteBackward()"},"abstract":[{"type":"text","text":":nodoc:"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/deletebackward()"]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/deletebackward()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentCardTextField","kind":"identifier"}],"title":"STPPaymentCardTextField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"text":" ","type":"text"},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"url":"\/documentation\/stripepaymentsui","kind":"symbol","role":"collection","title":"StripePaymentsUI","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/deleteBackward()":{"abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deleteBackward"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/deleteBackward()","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/deletebackward()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteBackward","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","title":"deleteBackward()","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"deleteBackward","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deleteBackward","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"deleteBackward","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"STPPaymentCardTextField","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace"},{"value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1deleteBackward()\/title","value":"deleteBackward","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1deleteBackward()\/fragments","value":[{"kind":"text","text":"- "},{"text":"deleteBackward","kind":"identifier"}]}]}]}