{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(errorImageForCardBrand:) "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorImage"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cardBrand","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"cardBrand","content":[{"inlineContent":[{"text":"The brand of card entered.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The error image used for a card brand."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/errorimage(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/errorimage(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Returns the error image used for a card brand."},{"type":"text","text":" "},{"type":"text","text":"Override this method in a subclass if you would like to provide custom images."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/errorImage(for:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"errorImage(for:)","modules":[{"name":"StripePaymentsUI"}],"symbolKind":"method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(cm)errorImageForCardBrand:","navigatorTitle":[{"kind":"identifier","text":"errorImageForCardBrand:"}],"roleHeading":"Type Method","role":"symbol"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/errorImage(for:)":{"abstract":[{"text":"Returns the error image used for a card brand.","type":"text"},{"text":" ","type":"text"},{"text":"Override this method in a subclass if you would like to provide custom images.","type":"text"}],"title":"errorImage(for:)","navigatorTitle":[{"text":"errorImageForCardBrand:","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/errorimage(for:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/errorImage(for:)","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui","role":"collection","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"role":"symbol","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"symbol","title":"STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextField"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"errorImageForCardBrand:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"errorImageForCardBrand:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"errorImageForCardBrand:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cardBrand"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The brand of card entered.","type":"text"}],"type":"paragraph"}],"name":"cardBrand"}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The error image used for a card brand.","type":"text"}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1errorImage(for:)\/title","value":"errorImageForCardBrand:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1errorImage(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"errorImageForCardBrand:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]}]}]}