{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formattedExpirationYear","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"formattedExpirationYear"}],"modules":[{"name":"StripePaymentsUI"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formattedExpirationYear","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","title":"formattedExpirationYear","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(py)formattedExpirationYear"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The current expiration year displayed by the field, as a string."},{"type":"text","text":" "},{"type":"text","text":"This is a 2-digit year (i.e. “15”), and may or may not be a valid entry"},{"type":"text","text":" "},{"type":"text","text":"unless "},{"type":"codeVoice","code":"isValid"},{"type":"text","text":" is true."}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/formattedexpirationyear"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/formattedexpirationyear"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/formattedExpirationYear"},"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/formattedExpirationYear":{"kind":"symbol","navigatorTitle":[{"text":"formattedExpirationYear","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formattedExpirationYear","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The current expiration year displayed by the field, as a string."},{"type":"text","text":" "},{"type":"text","text":"This is a 2-digit year (i.e. “15”), and may or may not be a valid entry"},{"type":"text","text":" "},{"type":"text","text":"unless "},{"type":"codeVoice","code":"isValid"},{"type":"text","text":" is true."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/formattedExpirationYear","title":"formattedExpirationYear","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/formattedexpirationyear"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"kind":"symbol","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","title":"STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui","kind":"symbol","role":"collection","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"formattedExpirationYear","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"formattedExpirationYear","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"formattedExpirationYear","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"formattedExpirationYear","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1formattedExpirationYear\/title"},{"value":[{"text":"formattedExpirationYear","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1formattedExpirationYear\/fragments"},{"value":"STPPaymentCardTextField","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}