{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/inserttext(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/inserttext(_:)"]}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/insertText(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]}]}],"metadata":{"modules":[{"name":"StripePaymentsUI"}],"title":"insertText(_:)","role":"symbol","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)insertText:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insertText","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"insertText:","kind":"identifier"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"title":"STPPaymentCardTextField","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/insertText(_:)":{"title":"insertText(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/insertText(_:)","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"insertText:"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/inserttext(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"insertText"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"type":"topic","kind":"symbol","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","role":"collection","url":"\/documentation\/stripepaymentsui"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"insertText:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"insertText:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"insertText:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"text","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentCardTextField","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"},{"value":"insertText:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1insertText(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"insertText:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1insertText(_:)\/fragments"}]}]}