{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/intrinsicContentSize","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"intrinsicContentSize","kind":"identifier"}],"role":"symbol","symbolKind":"property","modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(py)intrinsicContentSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"title":"intrinsicContentSize"},"sections":[],"abstract":[{"type":"text","text":":nodoc:"}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/intrinsiccontentsize"]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/intrinsicContentSize":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/intrinsicContentSize","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/intrinsiccontentsize","title":"intrinsicContentSize","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextField"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","title":"STPPaymentCardTextField","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"intrinsicContentSize","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"intrinsicContentSize","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1intrinsicContentSize\/title","op":"replace","value":"intrinsicContentSize"},{"value":[{"kind":"identifier","text":"intrinsicContentSize"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1intrinsicContentSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]}]}]}
