{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/keyboardAppearance","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/keyboardappearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/keyboardappearance"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The keyboard appearance for the field.","type":"text"},{"type":"text","text":" "},{"text":"Default is UIKeyboardAppearanceDefault.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardAppearance","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(py)keyboardAppearance","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"keyboardAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance"}],"title":"keyboardAppearance","navigatorTitle":[{"text":"keyboardAppearance","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePaymentsUI"}],"symbolKind":"property"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextField"}],"abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"type":"text","text":" "},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"text":" ","type":"text"},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"text":"anywhere a UITextField would be appropriate.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","role":"symbol","type":"topic","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"title":"STPPaymentCardTextField","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/keyboardAppearance":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/keyboardAppearance","abstract":[{"type":"text","text":"The keyboard appearance for the field."},{"text":" ","type":"text"},{"text":"Default is UIKeyboardAppearanceDefault.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"keyboardAppearance"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/keyboardappearance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"keyboardAppearance","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance","kind":"typeIdentifier"}],"title":"keyboardAppearance"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"kind":"symbol","role":"collection","title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"keyboardAppearance","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"keyboardAppearance"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardAppearance"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1keyboardAppearance\/title","value":"keyboardAppearance"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1keyboardAppearance\/fragments","op":"replace","value":[{"text":"keyboardAppearance","kind":"identifier"}]}]}]}