{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)layoutSubviews","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"title":"layoutSubviews()","modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"abstract":[{"type":"text","text":":nodoc:"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/layoutSubviews()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/layoutsubviews()"]}],"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/layoutSubviews()":{"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"title":"layoutSubviews()","role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/layoutsubviews()","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/layoutSubviews()","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","role":"collection","url":"\/documentation\/stripepaymentsui","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"title":"STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","type":"topic","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"text":"multiple UITextFields under the hood to collect this information. It’s","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentCardTextField","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"layoutSubviews"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"op":"replace","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}