{"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(py)paymentMethodParams","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"StripePaymentsUI"}],"title":"paymentMethodParams","navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentMethodParams"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier","text":"STPPaymentMethodParams"}]},"abstract":[{"type":"text","text":"Convenience property for creating an "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":" from the currently entered information","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or programmatically setting the field’s contents. For example, if you’re using another library"},{"text":" ","type":"text"},{"type":"text","text":"to scan your user’s credit card with a camera, you can assemble that data into an "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":" "},{"type":"text","text":"object and set this property to that object to prefill the fields you’ve collected."},{"text":" ","type":"text"},{"text":"Accessing this property returns a ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"copied"}]},{"type":"text","text":" "},{"code":"paymentMethodParams","type":"codeVoice"},{"type":"text","text":". The only way to change properties in this"},{"type":"text","text":" "},{"type":"text","text":"object is to make changes to a "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":" you own (retrieved from this text field if desired),"},{"type":"text","text":" "},{"text":"and then set this property to the new value.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/paymentMethodParams"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodParams"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodParams","kind":"typeIdentifier","text":"STPPaymentMethodParams"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/paymentmethodparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/paymentmethodparams"]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","url":"\/documentation\/stripepaymentsui","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextField"}],"title":"STPPaymentCardTextField","role":"symbol","type":"topic","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"text":" ","type":"text"},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"text":"designed to fit on a single line, and from a design perspective can be used","type":"text"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentMethodParams":{"title":"STPPaymentMethodParams","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodParams","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"url":"\/documentation\/stripepaymentsui\/stppaymentmethodparams","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/paymentMethodParams":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"paymentMethodParams","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/paymentmethodparams","role":"symbol","title":"paymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/paymentMethodParams","navigatorTitle":[{"kind":"identifier","text":"paymentMethodParams"}],"abstract":[{"type":"text","text":"Convenience property for creating an "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":" from the currently entered information"},{"type":"text","text":" "},{"type":"text","text":"or programmatically setting the field’s contents. For example, if you’re using another library"},{"type":"text","text":" "},{"text":"to scan your user’s credit card with a camera, you can assemble that data into an ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":" "},{"type":"text","text":"object and set this property to that object to prefill the fields you’ve collected."},{"type":"text","text":" "},{"text":"Accessing this property returns a ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"copied","type":"text"}]},{"type":"text","text":" "},{"code":"paymentMethodParams","type":"codeVoice"},{"text":". The only way to change properties in this","type":"text"},{"text":" ","type":"text"},{"text":"object is to make changes to a ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":" you own (retrieved from this text field if desired),"},{"type":"text","text":" "},{"type":"text","text":"and then set this property to the new value."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"paymentMethodParams","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"paymentMethodParams"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodParams"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"paymentMethodParams"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace","value":"STPPaymentCardTextField"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1paymentMethodParams\/title","op":"replace","value":"paymentMethodParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1paymentMethodParams\/fragments","value":[{"text":"paymentMethodParams","kind":"identifier"}],"op":"replace"}]}]}