{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"StripePaymentsUI"}],"platforms":[],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)preferredNetworks","title":"preferredNetworks_objc()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"preferredNetworks_objc","kind":"identifier"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]?","kind":"text"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"preferredNetworks","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(preferredNetworks) "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredNetworks_objc"},{"text":"() -> [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"The first preferred network that matches any available network will","type":"text"},{"type":"text","text":" "},{"text":"be offered to the customer. If no preferred network is applicable, the","type":"text"},{"text":" ","type":"text"},{"text":"customer will select the network.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Objective-C, this is an array of NSNumbers representing STPCardBrands."},{"type":"text","text":" "},{"type":"text","text":"For example:"},{"text":" ","type":"text"},{"type":"text","text":"[textField setPreferredNetworks:@[[NSNumber numberWithInt:STPCardBrandVisa]]];"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/preferredNetworks_objc()","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The list of preferred networks that should be used to process"},{"type":"text","text":" "},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"type":"text","text":" "},{"text":"network themselves.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/preferrednetworks_objc()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/preferrednetworks_objc()"]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/preferredNetworks_objc()":{"abstract":[{"type":"text","text":"The list of preferred networks that should be used to process"},{"type":"text","text":" "},{"text":"payments made with a co-branded card if your user hasn’t selected a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"network themselves."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"preferredNetworks_objc","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"preferredNetworks"}],"title":"preferredNetworks_objc()","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/preferrednetworks_objc()","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/preferredNetworks_objc()","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","title":"StripePaymentsUI","type":"topic","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"kind":"symbol","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"text":" ","type":"text"},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"text":" ","type":"text"},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","title":"STPPaymentCardTextField","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"preferredNetworks"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preferredNetworks"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"text":"preferredNetworks","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1preferredNetworks_objc()\/title","op":"replace","value":"preferredNetworks"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1preferredNetworks_objc()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preferredNetworks"}]},{"op":"replace","value":"STPPaymentCardTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title"},{"value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}