{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(setPreferredNetworks:) ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPreferredNetworks_objc","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preferredNetworks","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"]?)"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"The first preferred network that matches any available network will","type":"text"},{"type":"text","text":" "},{"type":"text","text":"be offered to the customer. If no preferred network is applicable, the"},{"type":"text","text":" "},{"text":"customer will select the network.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"In Objective-C, this is an array of NSNumbers representing STPCardBrands.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For example:"},{"text":" ","type":"text"},{"type":"text","text":"[textField setPreferredNetworks:@[[NSNumber numberWithInt:STPCardBrandVisa]]];"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/setpreferrednetworks_objc(preferrednetworks:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/setpreferrednetworks_objc(preferrednetworks:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The list of preferred networks that should be used to process","type":"text"},{"type":"text","text":" "},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"text":" ","type":"text"},{"type":"text","text":"network themselves."}],"metadata":{"role":"symbol","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)setPreferredNetworks:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPreferredNetworks_objc"},{"kind":"text","text":"("},{"text":"preferredNetworks","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"]?)","kind":"text"}],"platforms":[],"title":"setPreferredNetworks_objc(preferredNetworks:)","modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setPreferredNetworks:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/setPreferredNetworks_objc(preferredNetworks:)"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"url":"\/documentation\/stripepaymentsui","kind":"symbol","role":"collection","title":"StripePaymentsUI","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentCardTextField","kind":"identifier"}],"title":"STPPaymentCardTextField","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"text":" ","type":"text"},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/setPreferredNetworks_objc(preferredNetworks:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setPreferredNetworks_objc","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preferredNetworks","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"setPreferredNetworks:"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/setpreferrednetworks_objc(preferrednetworks:)","kind":"symbol","title":"setPreferredNetworks_objc(preferredNetworks:)","abstract":[{"type":"text","text":"The list of preferred networks that should be used to process"},{"text":" ","type":"text"},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"text":" ","type":"text"},{"type":"text","text":"network themselves."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/setPreferredNetworks_objc(preferredNetworks:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setPreferredNetworks:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setPreferredNetworks:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setPreferredNetworks:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preferredNetworks"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"STPPaymentCardTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1setPreferredNetworks_objc(preferredNetworks:)\/title","op":"replace","value":"setPreferredNetworks:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1setPreferredNetworks_objc(preferredNetworks:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setPreferredNetworks:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}