{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfieldshouldreturn(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfieldshouldreturn(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/textFieldShouldReturn(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"textFieldShouldReturn(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)textFieldShouldReturn:","modules":[{"name":"StripePaymentsUI"}],"navigatorTitle":[{"kind":"identifier","text":"textFieldShouldReturn:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"role":"symbol","title":"STPPaymentCardTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextField"}],"abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/textFieldShouldReturn(_:)":{"role":"symbol","title":"textFieldShouldReturn(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldReturn"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/textFieldShouldReturn(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldReturn:"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfieldshouldreturn(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textFieldShouldReturn:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldReturn:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"textFieldShouldReturn:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"textField"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1textFieldShouldReturn(_:)\/title","value":"textFieldShouldReturn:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1textFieldShouldReturn(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldShouldReturn:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}