{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/textFieldDidEndEditing(_:)"},"abstract":[{"type":"text","text":":nodoc:"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfielddidendediting(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfielddidendediting(_:)"]}],"metadata":{"role":"symbol","modules":[{"name":"StripePaymentsUI"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)textFieldDidEndEditing:","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"textFieldDidEndEditing:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"textFieldDidEndEditing(_:)","symbolKind":"method","roleHeading":"Instance Method"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/textFieldDidEndEditing(_:)":{"title":"textFieldDidEndEditing(_:)","type":"topic","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldDidEndEditing:"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/textFieldDidEndEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDidEndEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField"},{"kind":"text","text":")"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfielddidendediting(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","type":"topic","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"title":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"textFieldDidEndEditing:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldDidEndEditing:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textFieldDidEndEditing:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"textField","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1textFieldDidEndEditing(_:)\/title","value":"textFieldDidEndEditing:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1textFieldDidEndEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldDidEndEditing:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace"}]}]}