{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldShouldEndEditing"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/textFieldShouldEndEditing(_:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldShouldEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method","navigatorTitle":[{"text":"textFieldShouldEndEditing:","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePaymentsUI"}],"title":"textFieldShouldEndEditing(_:)","roleHeading":"Instance Method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)textFieldShouldEndEditing:"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfieldshouldendediting(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfieldshouldendediting(_:)"]}],"abstract":[{"type":"text","text":":nodoc:"}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/textFieldShouldEndEditing(_:)":{"title":"textFieldShouldEndEditing(_:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/textFieldShouldEndEditing(_:)","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfieldshouldendediting(_:)","kind":"symbol","navigatorTitle":[{"text":"textFieldShouldEndEditing:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldShouldEndEditing"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextField","kind":"typeIdentifier","text":"UITextField"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":":nodoc:","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","title":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","role":"symbol","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"text":" ","type":"text"},{"text":"multiple UITextFields under the hood to collect this information. It’s","type":"text"},{"type":"text","text":" "},{"text":"designed to fit on a single line, and from a design perspective can be used","type":"text"},{"type":"text","text":" "},{"text":"anywhere a UITextField would be appropriate.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"textFieldShouldEndEditing:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"textFieldShouldEndEditing:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"textFieldShouldEndEditing:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textField"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1textFieldShouldEndEditing(_:)\/title","op":"replace","value":"textFieldShouldEndEditing:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1textFieldShouldEndEditing(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"textFieldShouldEndEditing:","kind":"identifier"}]},{"value":"STPPaymentCardTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}