{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/textField(_:shouldChangeCharactersIn:replacementString:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"]]},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfield(_:shouldchangecharactersin:replacementstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfield(_:shouldchangecharactersin:replacementstring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldChangeCharactersIn","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"range","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRange","text":"NSRange","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"replacementString","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextField","kind":"typeIdentifier","text":"UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier","text":"NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"StripePaymentsUI"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField(im)textField:shouldChangeCharactersInRange:replacementString:","title":"textField(_:shouldChangeCharactersIn:replacementString:)","navigatorTitle":[{"text":"textField:shouldChangeCharactersInRange:replacementString:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"url":"\/documentation\/stripepaymentsui","kind":"symbol","title":"StripePaymentsUI","role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"role":"symbol","title":"STPPaymentCardTextField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextField"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/textField(_:shouldChangeCharactersIn:replacementString:)":{"title":"textField(_:shouldChangeCharactersIn:replacementString:)","navigatorTitle":[{"text":"textField:shouldChangeCharactersInRange:replacementString:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/textfield(_:shouldchangecharactersin:replacementstring:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/textField(_:shouldChangeCharactersIn:replacementString:)","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"textField:shouldChangeCharactersInRange:replacementString:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textField:shouldChangeCharactersInRange:replacementString:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textField:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"textField","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldChangeCharactersInRange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSRange"},{"text":") ","kind":"text"},{"text":"range","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"replacementString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1textField(_:shouldChangeCharactersIn:replacementString:)\/title","value":"textField:shouldChangeCharactersInRange:replacementString:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField~1textField(_:shouldChangeCharactersIn:replacementString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"op":"replace"}]}]}