{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams"]]},"abstract":[{"type":"text","text":":nodoc:"}],"metadata":{"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams(py)description","symbolKind":"property","navigatorTitle":[{"text":"description","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardparams\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardparams\/description"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"abstract":[{"type":"text","text":"The user’s card details."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","navigatorTitle":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"title":"STPPaymentMethodCardParams","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardparams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams/description":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams\/description","title":"description","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardparams\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodCardParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/fragments","value":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCardParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams~1description\/fragments","value":[{"kind":"identifier","text":"description"}]}]}]}