{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCardSourceParams:"}],"roleHeading":"Initializer","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams(im)initWithCardSourceParams:","modules":[{"name":"StripePayments"}],"title":"init(cardSourceParams:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardSourceParams"},{"text":": ","kind":"text"},{"text":"STPCardParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams"},{"kind":"text","text":")"}],"symbolKind":"init"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"cardSourceParams","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams\/init(cardSourceParams:)"},"sections":[],"abstract":[{"type":"text","text":"A convenience initializer for creating a payment method from a card source."},{"type":"text","text":" "},{"text":"This should be used to help with migrations to Payment Methods from Sources.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardparams\/init(cardsourceparams:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardparams\/init(cardsourceparams:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams/init(cardSourceParams:)":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardparams\/init(cardsourceparams:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cardSourceParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithCardSourceParams:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams\/init(cardSourceParams:)","title":"init(cardSourceParams:)","abstract":[{"type":"text","text":"A convenience initializer for creating a payment method from a card source."},{"text":" ","type":"text"},{"type":"text","text":"This should be used to help with migrations to Payment Methods from Sources."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"title":"STPCardParams","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","role":"symbol","url":"\/documentation\/stripepayments\/stpcardparams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardParams","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPCardParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of a user’s credit card details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"text":"an STPAPIClient.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardparams","title":"STPPaymentMethodCardParams","abstract":[{"text":"The user’s card details.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithCardSourceParams:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCardSourceParams:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithCardSourceParams:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams"},{"kind":"text","text":" *) "},{"text":"cardSourceParams","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams~1init(cardSourceParams:)\/title","value":"initWithCardSourceParams:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCardSourceParams:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams~1init(cardSourceParams:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title","value":"STPCardParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments","value":[{"kind":"identifier","text":"STPCardParams"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/title","value":"STPPaymentMethodCardParams"},{"value":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/navigatorTitle","value":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}