{"sections":[],"abstract":[{"type":"text","text":"Information about the networks to use with this payment method."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams"]]},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networks","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardNetworksParams","text":"STPPaymentMethodCardNetworksParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"networks","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams(py)networks","role":"symbol","modules":[{"name":"StripePayments"}],"title":"networks","roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams\/networks"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardNetworksParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardNetworksParams","text":"STPPaymentMethodCardNetworksParams"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardparams\/networks"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardparams\/networks"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams/networks":{"navigatorTitle":[{"text":"networks","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams\/networks","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networks","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardNetworksParams","text":"STPPaymentMethodCardNetworksParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"networks","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardparams\/networks","abstract":[{"type":"text","text":"Information about the networks to use with this payment method."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardparams","type":"topic","navigatorTitle":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"kind":"symbol","title":"STPPaymentMethodCardParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","abstract":[{"text":"The user’s card details.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardNetworksParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardNetworksParams","url":"\/documentation\/stripepayments\/stppaymentmethodcardnetworksparams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardNetworksParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardNetworksParams"}],"type":"topic","role":"symbol","title":"STPPaymentMethodCardNetworksParams","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"networks","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"networks"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardNetworksParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardNetworksParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardNetworksParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"networks"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"networks","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams~1networks\/title"},{"value":[{"text":"networks","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams~1networks\/fragments"},{"value":"STPPaymentMethodCardParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/title"},{"value":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/navigatorTitle"},{"value":"STPPaymentMethodCardNetworksParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardNetworksParams\/title"},{"value":[{"text":"STPPaymentMethodCardNetworksParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardNetworksParams\/fragments"},{"value":[{"text":"STPPaymentMethodCardNetworksParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardNetworksParams\/navigatorTitle"}]}]}