//
// LinkAccountSessionManifest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore

struct LinkAccountSessionManifest: StripeDecodable {
    let hostedAuthUrl: String
    let successUrl: String
    let cancelUrl: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
