//
// LinkAccountSessionsGenerateHostedUrlBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore

struct LinkAccountSessionsGenerateHostedUrlBody: StripeEncodable {
    var clientSecret: String
    var _additionalParametersStorage: NonEncodableParameters?
}
