{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingerprint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/fingerprint","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.","type":"text"}],"metadata":{"symbolKind":"property","modules":[{"name":"StripePayments"}],"title":"fingerprint","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"fingerprint","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAUBECSDebit(py)fingerprint","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingerprint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/fingerprint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/fingerprint"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit/fingerprint":{"type":"topic","title":"fingerprint","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/fingerprint","navigatorTitle":[{"kind":"identifier","text":"fingerprint"}],"abstract":[{"text":"Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/fingerprint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingerprint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit":{"type":"topic","abstract":[{"text":"An AU BECS Debit Payment Method.","type":"text"}],"title":"STPPaymentMethodAUBECSDebit","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit","url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fingerprint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fingerprint","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"fingerprint","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1fingerprint\/title","value":"fingerprint"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1fingerprint\/fragments","value":[{"text":"fingerprint","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/title","value":"STPPaymentMethodAUBECSDebit"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/fragments","value":[{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/navigatorTitle","value":[{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}]}]}]}