# Ordered by output of `jazzy --help config`

output: docs/docs
clean: true
objc: true
umbrella_header: Stripe/PublicHeaders/Stripe/Stripe.h
framework_root: .
sdk: iphonesimulator
author: Stripe
author_url: https://stripe.com
module: Stripe
github_url: https://github.com/stripe/stripe-ios
github_file_prefix: https://github.com/stripe/stripe-ios/tree/master
skip_undocumented: true
hide_documentation_coverage: true
theme: fullwidth
exclude: 
  - Stripe/PublicHeaders/Stripe/STD*
  - Stripe/PublicHeaders/Stripe/Stripe3DS2.h
