# Ordered by output of `jazzy --help config`

clean: true
sdk: iphonesimulator
author: Stripe
author_url: https://stripe.com
github_url: https://github.com/stripe/stripe-ios
github_file_prefix: https://github.com/stripe/stripe-ios/tree/master
skip_undocumented: true
hide_documentation_coverage: true
theme: .jazzy/theme
