# Detects dead code
# Usage periphery scan --config .periphery.yml 2>&1 | sed 's#.*/##' | grep 'is unused' | sort > periphery_report_feature_formatted_sorted.txt
# Install/info https://github.com/peripheryapp/periphery
# Why are so many targets/schemes commented out? This script takes a long time to run in CI, so we skip some schemes to speed it up. Note: AllStripeFrameworks covers a lot of the commented out schemes, e.g. AllStripeFrameworks contains StripeApplePay.

project: Stripe.xcworkspace

schemes:
- AllStripeFrameworks

retain_public: true
retain_objc_accessible: false
retain_objc_annotated: false
exclude_tests: true
verbose: true
no_retain_spi: ["STP"]

build_arguments:
  - -destination
  - 'generic/platform=iOS Simulator'