# Detects dead code
# Usage periphery scan --config .periphery.yml 2>&1 | sed 's#.*/##' | grep 'is unused' | sort > periphery_report_feature_formatted_sorted.txt
# Install/info https://github.com/peripheryapp/periphery
# Why are so many targets/schemes commented out? This script takes a long time to run in CI, so we skip some schemes to speed it up. Note: AllStripeFrameworks covers a lot of the commented out schemes, e.g. AllStripeFrameworks contains StripeApplePay.

workspace: Stripe.xcworkspace

schemes:
  - AllStripeFrameworks
  # - IntegrationTester
  # - Stripe3DS2
  # - Stripe3DS2DemoUI
  # - StripeApplePay
  # - StripeCameraCore
  # - StripeCardScan
  - StripeConnect
  # - StripeCore
  # - StripeFinancialConnections
  # - StripeIdentity
  # - StripePaymentSheet
  # - StripePayments
  # - StripePaymentsUI
  # - StripeUICore
  # - StripeiOS
  # - PaymentSheet Example
  # - AppClipExample
  # - CardImageVerification Example
  # - FinancialConnections Example
  # - IdentityVerification Example
  # - StripeConnect Example
  # - Non-Card Payment Examples
  # - UI Examples

targets:
  # - AppClipExample
  # - AppClipExampleClip
  # - AppClipExampleClipTests
  # - AppClipExampleClipUITests
  # - AppClipExampleTests iOS
  # - CardImageVerification Example
  # - CardImageVerification ExampleUITests
  # - Common
  # - FinancialConnections Example
  # - FinancialConnectionsUITests
  # - IdentityVerification Example
  # - IntegrationTester
  # - IntegrationTesterUITests
  # - Non-Card Payment Examples
  # - PaymentSheet Example
  # - PaymentSheetLocalizationScreenshotGenerator
  # - PaymentSheetUITest
  - Stripe3DS2
  - Stripe3DS2Tests
  - StripeApplePay
  - StripeApplePayTests
  - StripeCameraCore
  - StripeCameraCoreTestUtils
  - StripeCameraCoreTests
  - StripeCardScan
  - StripeCardScanTests
  - StripeConnect
  # - StripeConnect Example
  # - StripeConnect ExampleUITests
  - StripeConnectTests
  - StripeCore
  - StripeCoreTestUtils
  - StripeCoreTests
  - StripeFinancialConnections
  - StripeFinancialConnectionsTests
  - StripeIdentity
  - StripeIdentityTests
  - StripePaymentSheet
  - StripePaymentSheetTestHostApp
  - StripePaymentSheetTests
  - StripePayments
  - StripePaymentsObjcTestUtils
  - StripePaymentsTestHostApp
  - StripePaymentsTestUtils
  - StripePaymentsTests
  - StripePaymentsUI
  - StripePaymentsUITests
  - StripeUICore
  - StripeUICoreTests
  - StripeiOS
  - StripeiOSAppHostedTests
  - StripeiOSTestHostApp
  - StripeiOSTests
  # - UI Examples

retain_public: true
retain_objc_accessible: false
retain_objc_annotated: true
retain_objc_protocols: true

retain_ibaction: true
retain_iboutlet: true
retain_ibinspectable: true
verbose: true

build_arguments:
  - -destination
  - 'generic/platform=iOS Simulator'
  