source "https://rubygems.org"

gem "cocoapods"
gem "colorize"
gem "dotstrings"
gem "fastlane"
gem "mail"
gem "rubyzip"
gem "octokit", "~> 4.25.1"
gem "mime-types"
gem "CFPropertyList"
gem "terminal-table"
gem "httparty"

gem "xcode-install", "~> 2.6"
gem "plist"
gem "net-ssh"
gem "abbrev"
