import ProjectDescription

let workspace = Workspace(
    name: "Stripe",
    projects: [
        "Stripe",
        "Stripe3DS2",
        "StripeApplePay",
        "StripeCameraCore",
        "StripeCardScan",
        "StripeCore",
        "StripeFinancialConnections",
        "StripeIdentity",
        "StripePayments",
        "StripePaymentsUI",
        "StripePaymentSheet",
        "StripeUICore",
        "Testers/IntegrationTester",
        "Testers/LocalizationTester",
        "Example/UI Examples",
        "Example/FinancialConnections Example",
        "Example/CardImageVerification Example",
        "Example/IdentityVerification Example",
        "Example/Non-Card Payment Examples",
        "Example/Basic Integration",
        "Example/PaymentSheet Example",
        "Example/AppClipExample",
    ],
    additionalFiles: [
        "Package.swift",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
