{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Amex Express Checkout"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"amexExpressCheckout"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/amexexpresscheckout"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/amexexpresscheckout"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/amexExpressCheckout"},"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"case","title":"STPPaymentMethodCardWalletType.amexExpressCheckout","roleHeading":"Case","navigatorTitle":[{"text":"STPPaymentMethodCardWalletTypeAmexExpressCheckout","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amexExpressCheckout","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType@STPPaymentMethodCardWalletTypeAmexExpressCheckout"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/amexExpressCheckout":{"abstract":[{"text":"Amex Express Checkout","type":"text"}],"kind":"symbol","title":"STPPaymentMethodCardWalletType.amexExpressCheckout","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/amexexpresscheckout","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeAmexExpressCheckout"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/amexExpressCheckout","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amexExpressCheckout","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"abstract":[{"text":"The type of Card Wallet.","type":"text"}],"title":"STPPaymentMethodCardWalletType","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPPaymentMethodCardWalletTypeAmexExpressCheckout","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeAmexExpressCheckout"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeAmexExpressCheckout"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"STPPaymentMethodCardWalletTypeAmexExpressCheckout","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1amexExpressCheckout\/title"},{"value":[{"text":"STPPaymentMethodCardWalletTypeAmexExpressCheckout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1amexExpressCheckout\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/title","op":"replace","value":"STPPaymentMethodCardWalletType"},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/navigatorTitle","value":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}