{"sections":[],"metadata":{"symbolKind":"case","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePay","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodCardWalletTypeApplePay","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType@STPPaymentMethodCardWalletTypeApplePay","role":"symbol","roleHeading":"Case","title":"STPPaymentMethodCardWalletType.applePay"},"abstract":[{"text":"Apple Pay","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePay"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/applepay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/applepay"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/applePay","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType":{"kind":"symbol","abstract":[{"type":"text","text":"The type of Card Wallet."}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","role":"symbol","title":"STPPaymentMethodCardWalletType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/applePay":{"abstract":[{"type":"text","text":"Apple Pay"}],"title":"STPPaymentMethodCardWalletType.applePay","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/applePay","navigatorTitle":[{"text":"STPPaymentMethodCardWalletTypeApplePay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/applepay","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodCardWalletTypeApplePay","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPPaymentMethodCardWalletTypeApplePay","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPPaymentMethodCardWalletTypeApplePay","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodCardWalletType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodCardWalletTypeApplePay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1applePay\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodCardWalletTypeApplePay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1applePay\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}