{"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"StripePayments"}],"role":"collectionGroup"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/Equatable-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/!=(_:_:)":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/!=(_:_:)","title":"!=(_:_:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","title":"STPPaymentMethodCardWalletType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype","navigatorTitle":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The type of Card Wallet.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPPaymentMethodCardWalletType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}