{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/link"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/link"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Link"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"link","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/link","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeLink"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"link","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"STPPaymentMethodCardWalletType.link","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType@STPPaymentMethodCardWalletTypeLink"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType":{"kind":"symbol","abstract":[{"type":"text","text":"The type of Card Wallet."}],"title":"STPPaymentMethodCardWalletType","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","navigatorTitle":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/link":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"link","kind":"identifier"}],"title":"STPPaymentMethodCardWalletType.link","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/link","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCardWalletTypeLink","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Link","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/link"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentMethodCardWalletTypeLink","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodCardWalletTypeLink","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"STPPaymentMethodCardWalletTypeLink","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/title","value":"STPPaymentMethodCardWalletType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/fragments","value":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/navigatorTitle","value":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1link\/title","value":"STPPaymentMethodCardWalletTypeLink","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1link\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeLink"}],"op":"replace"}]}]}