{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType"]]},"abstract":[{"type":"text","text":"Masterpass"}],"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType@STPPaymentMethodCardWalletTypeMasterpass","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeMasterpass"}],"title":"STPPaymentMethodCardWalletType.masterpass","role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"masterpass"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/masterpass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/masterpass"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/masterpass"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"masterpass","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/masterpass":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeMasterpass"}],"title":"STPPaymentMethodCardWalletType.masterpass","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/masterpass","abstract":[{"type":"text","text":"Masterpass"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/masterpass","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"masterpass"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType":{"title":"STPPaymentMethodCardWalletType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"abstract":[{"text":"The type of Card Wallet.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodCardWalletTypeMasterpass"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeMasterpass"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPPaymentMethodCardWalletTypeMasterpass","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1masterpass\/title","op":"replace","value":"STPPaymentMethodCardWalletTypeMasterpass"},{"value":[{"text":"STPPaymentMethodCardWalletTypeMasterpass","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1masterpass\/fragments","op":"replace"},{"value":"STPPaymentMethodCardWalletType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/fragments","value":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}