{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Samsung Pay"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/samsungPay"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"samsungPay","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/samsungpay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/samsungpay"]}],"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType@STPPaymentMethodCardWalletTypeSamsungPay","navigatorTitle":[{"text":"STPPaymentMethodCardWalletTypeSamsungPay","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"samsungPay","kind":"identifier"}],"title":"STPPaymentMethodCardWalletType.samsungPay","role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/samsungPay":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/samsungPay","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/samsungpay","kind":"symbol","abstract":[{"type":"text","text":"Samsung Pay"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"samsungPay","kind":"identifier"}],"title":"STPPaymentMethodCardWalletType.samsungPay","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCardWalletTypeSamsungPay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType":{"title":"STPPaymentMethodCardWalletType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype","role":"symbol","abstract":[{"text":"The type of Card Wallet.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodCardWalletTypeSamsungPay"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPPaymentMethodCardWalletTypeSamsungPay","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"STPPaymentMethodCardWalletTypeSamsungPay","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentMethodCardWalletTypeSamsungPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1samsungPay\/title","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentMethodCardWalletTypeSamsungPay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1samsungPay\/fragments"},{"op":"replace","value":"STPPaymentMethodCardWalletType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}