{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddressParams(py)city","role":"symbol","symbolKind":"property","title":"city","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"city","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"city","kind":"identifier"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddressParams"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddressParams\/city","interfaceLanguage":"swift"},"abstract":[{"text":"City\/District\/Suburb\/Town\/Village.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"city","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetailsaddressparams\/city"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetailsaddressparams\/city"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsAddressParams":{"url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsaddressparams","abstract":[{"text":"Shipping address for a PaymentIntent’s shipping details.","type":"text"}],"type":"topic","kind":"symbol","title":"STPPaymentIntentShippingDetailsAddressParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddressParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsAddressParams","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsAddressParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsAddressParams/city":{"navigatorTitle":[{"text":"city","kind":"identifier"}],"type":"topic","kind":"symbol","title":"city","url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsaddressparams\/city","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"city","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddressParams\/city","abstract":[{"text":"City\/District\/Suburb\/Town\/Village.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"city"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"city","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"city","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddressParams\/title","value":"STPPaymentIntentShippingDetailsAddressParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddressParams\/fragments","value":[{"text":"STPPaymentIntentShippingDetailsAddressParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddressParams\/navigatorTitle","value":[{"text":"STPPaymentIntentShippingDetailsAddressParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddressParams~1city\/title","value":"city"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddressParams~1city\/fragments","value":[{"text":"city","kind":"identifier"}]}]}]}