{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/additionalAPIParameters","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Instance Property","title":"additionalAPIParameters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPDateOfBirth(py)additionalAPIParameters"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"STPFormEncodable.additionalAPIParameters","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpdateofbirth\/additionalapiparameters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpdateofbirth\/additionalapiparameters"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth/additionalAPIParameters":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/additionalAPIParameters","kind":"symbol","type":"topic","title":"additionalAPIParameters","role":"symbol","url":"\/documentation\/stripepayments\/stpdateofbirth\/additionalapiparameters"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth":{"navigatorTitle":[{"kind":"identifier","text":"STPDateOfBirth"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpdateofbirth","kind":"symbol","abstract":[{"text":"An individual’s date of birth.","type":"text"},{"text":" ","type":"text"},{"text":"See https:\/\/stripe.com\/docs\/api\/tokens\/create_account#create_account_token-account-individual-dob","type":"text"}],"title":"STPDateOfBirth","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPDateOfBirth"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"additionalAPIParameters","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"additionalAPIParameters"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth~1additionalAPIParameters\/title","value":"additionalAPIParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth~1additionalAPIParameters\/fragments","value":[{"kind":"identifier","text":"additionalAPIParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/title","value":"STPDateOfBirth","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/fragments","value":[{"kind":"identifier","text":"STPDateOfBirth"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/navigatorTitle","value":[{"kind":"identifier","text":"STPDateOfBirth"}],"op":"replace"}]}]}