{"variants":[{"paths":["\/documentation\/stripepayments\/stpdateofbirth\/day"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpdateofbirth\/day"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"The day of birth, between 1 and 31.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/day"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"day","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPDateOfBirth(py)day","symbolKind":"property","navigatorTitle":[{"text":"day","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth":{"role":"symbol","type":"topic","title":"STPDateOfBirth","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPDateOfBirth","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPDateOfBirth","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpdateofbirth","abstract":[{"type":"text","text":"An individual’s date of birth."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/stripe.com\/docs\/api\/tokens\/create_account#create_account_token-account-individual-dob"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth/day":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"day","kind":"identifier"}],"abstract":[{"text":"The day of birth, between 1 and 31.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/day","title":"day","url":"\/documentation\/stripepayments\/stpdateofbirth\/day"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"day","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"day"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPDateOfBirth","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/fragments","value":[{"text":"STPDateOfBirth","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/navigatorTitle","value":[{"kind":"identifier","text":"STPDateOfBirth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth~1day\/title","value":"day"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth~1day\/fragments","value":[{"text":"day","kind":"identifier"}]}]}]}