{"variants":[{"paths":["\/documentation\/stripepayments\/stpdateofbirth\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpdateofbirth\/stpformencodable-implementations"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/rootObjectName()"],"title":"Type Methods","anchor":"Type-Methods"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/STPFormEncodable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth"]]},"kind":"article","metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"StripePayments"}],"title":"STPFormEncodable Implementations"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPDateOfBirth"}],"abstract":[{"type":"text","text":"An individual’s date of birth."},{"type":"text","text":" "},{"text":"See https:\/\/stripe.com\/docs\/api\/tokens\/create_account#create_account_token-account-individual-dob","type":"text"}],"url":"\/documentation\/stripepayments\/stpdateofbirth","title":"STPDateOfBirth","type":"topic","role":"symbol","navigatorTitle":[{"text":"STPDateOfBirth","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth/propertyNamesToFormFieldNamesMapping()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"type":"codeVoice","code":"expMonth"},{"text":", but the Stripe API expects a field called ","type":"text"},{"type":"codeVoice","code":"exp_month"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpdateofbirth\/propertynamestoformfieldnamesmapping()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/propertyNamesToFormFieldNamesMapping()","type":"topic","role":"symbol","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"title":"propertyNamesToFormFieldNamesMapping()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth/rootObjectName()":{"navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"type":"text","text":" below."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/rootObjectName()","url":"\/documentation\/stripepayments\/stpdateofbirth\/rootobjectname()","title":"rootObjectName()","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth\/rootObjectName()"],"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/title","value":"STPDateOfBirth"},{"value":[{"kind":"identifier","text":"STPDateOfBirth"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/navigatorTitle","value":[{"text":"STPDateOfBirth","kind":"identifier"}],"op":"replace"},{"value":"propertyNamesToFormFieldNamesMapping","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth~1propertyNamesToFormFieldNamesMapping()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth~1rootObjectName()\/title","op":"replace","value":"rootObjectName"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth~1rootObjectName()\/fragments"}]}]}