{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"always"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/always"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/always"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Use always to indicate that this payment method can always be shown to a customer in a checkout flow."}],"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"always","kind":"identifier"}],"title":"STPPaymentMethodAllowRedisplay.always","symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay@STPPaymentMethodAllowRedisplayAlways","navigatorTitle":[{"text":"STPPaymentMethodAllowRedisplayAlways","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay\/always","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay","kind":"symbol","abstract":[{"text":"Values for STPPaymentMethodAllowRedisplay","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"title":"STPPaymentMethodAllowRedisplay"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay/always":{"navigatorTitle":[{"text":"STPPaymentMethodAllowRedisplayAlways","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay\/always","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"always","kind":"identifier"}],"title":"STPPaymentMethodAllowRedisplay.always","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Use always to indicate that this payment method can always be shown to a customer in a checkout flow."}],"url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/always","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodAllowRedisplayAlways"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPPaymentMethodAllowRedisplayAlways","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPPaymentMethodAllowRedisplayAlways","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"STPPaymentMethodAllowRedisplay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}]},{"op":"replace","value":"STPPaymentMethodAllowRedisplayAlways","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay~1always\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay~1always\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplayAlways"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}