{"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Case","title":"STPPaymentMethodAllowRedisplay.limited","navigatorTitle":[{"text":"STPPaymentMethodAllowRedisplayLimited","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay@STPPaymentMethodAllowRedisplayLimited","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"limited","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay\/limited"},"sections":[],"abstract":[{"text":"Use limited to indicate that this payment method can’t always be shown to a customer in a checkout flow. For example, it can only be shown in the context of a specific subscription.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/limited"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/limited"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"limited","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay/limited":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay\/limited","kind":"symbol","title":"STPPaymentMethodAllowRedisplay.limited","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"limited"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplayLimited"}],"url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/limited","abstract":[{"text":"Use limited to indicate that this payment method can’t always be shown to a customer in a checkout flow. For example, it can only be shown in the context of a specific subscription.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","kind":"symbol","title":"STPPaymentMethodAllowRedisplay","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay","abstract":[{"text":"Values for STPPaymentMethodAllowRedisplay","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentMethodAllowRedisplayLimited","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodAllowRedisplayLimited","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplayLimited"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay~1limited\/title","value":"STPPaymentMethodAllowRedisplayLimited","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay~1limited\/fragments","value":[{"text":"STPPaymentMethodAllowRedisplayLimited","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/title","value":"STPPaymentMethodAllowRedisplay","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/fragments","value":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/navigatorTitle","value":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"op":"replace"}]}]}