{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay"]]},"abstract":[{"text":"This is the default value for payment methods where allow_redisplay wasn’t set.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unspecified"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay\/unspecified"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay@STPPaymentMethodAllowRedisplayUnspecified","symbolKind":"case","modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodAllowRedisplay.unspecified","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unspecified"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplayUnspecified"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/unspecified"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/unspecified"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay":{"navigatorTitle":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay","title":"STPPaymentMethodAllowRedisplay","kind":"symbol","abstract":[{"text":"Values for STPPaymentMethodAllowRedisplay","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay/unspecified":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodAllowRedisplayUnspecified","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay\/unspecified","kind":"symbol","title":"STPPaymentMethodAllowRedisplay.unspecified","abstract":[{"type":"text","text":"This is the default value for payment methods where allow_redisplay wasn’t set."}],"url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay\/unspecified"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodAllowRedisplayUnspecified","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPPaymentMethodAllowRedisplayUnspecified","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPPaymentMethodAllowRedisplayUnspecified","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodAllowRedisplay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/navigatorTitle","value":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay~1unspecified\/title","value":"STPPaymentMethodAllowRedisplayUnspecified","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay~1unspecified\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplayUnspecified"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}