{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXO\/allResponseFields"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] { get }"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"title":"allResponseFields","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXO(py)allResponseFields","symbolKind":"property","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"STPAPIResponseDecodable.allResponseFields","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXO"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodoxxo\/allresponsefields"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodoxxo\/allresponsefields"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodOXXO":{"navigatorTitle":[{"text":"STPPaymentMethodOXXO","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXO","title":"STPPaymentMethodOXXO","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodOXXO","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodoxxo","abstract":[{"text":"An OXXO Payment Method.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodOXXO/allResponseFields":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"abstract":[],"title":"allResponseFields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXO\/allResponseFields","url":"\/documentation\/stripepayments\/stppaymentmethodoxxo\/allresponsefields","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"allResponseFields","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"STPPaymentMethodOXXO","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXO\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodOXXO"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXO\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodOXXO","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXO\/navigatorTitle"},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXO~1allResponseFields\/title"},{"op":"replace","value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXO~1allResponseFields\/fragments"}]}]}