{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toCustomer","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","kind":"typeIdentifier","text":"STPErrorBlock"},{"kind":"text","text":"?)"}]}]},{"parameters":[{"name":"paymentMethod","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A valid Payment Method"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this callback when you’re done adding the payment method"},{"type":"text","text":" "},{"type":"text","text":"to the customer on your backend. For example, "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":" (if your call succeeds)"},{"text":" ","type":"text"},{"text":"or ","type":"text"},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" if an error is returned."}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)attachPaymentMethodToCustomer:completion:","title":"attachPaymentMethod(toCustomer:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"attachPaymentMethodToCustomer:completion:"}],"roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachPaymentMethod"},{"kind":"text","text":"("},{"text":"toCustomer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"STPErrorBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}]},"variants":[{"paths":["\/documentation\/stripe\/stpcustomercontext\/attachpaymentmethod(tocustomer:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpcustomercontext\/attachpaymentmethod(tocustomer:completion:)"]}],"sections":[],"abstract":[{"text":"Adds a Payment Method to a customer.","type":"text"},{"type":"text","text":" "},{"text":"If you are implementing your own ","type":"text"},{"text":":","type":"text"},{"text":" ","type":"text"},{"text":"On your backend, retrieve the Stripe customer associated with your logged-in user.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Then, call the Attach method on the Payment Method with that customer’s ID"},{"type":"text","text":" "},{"type":"text","text":"( https:\/\/stripe.com\/docs\/api\/payment_methods\/attach ). If this API call succeeds,"},{"type":"text","text":" "},{"text":"call ","type":"text"},{"code":"completion(nil)","type":"codeVoice"},{"type":"text","text":". Otherwise, call "},{"code":"completion(error)","type":"codeVoice"},{"text":" with the error that","type":"text"},{"type":"text","text":" "},{"text":"occurred.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/attachPaymentMethod(toCustomer:completion:)"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"type":"topic","title":"STPCustomerContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"text":" ","type":"text"},{"text":"be sure to either create a new instance of ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" or clear the current","type":"text"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"text":"new ephemeral key for the Customer object associated with the new user.","type":"text"}],"navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcustomercontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"type":"topic","title":"STPErrorBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"navigatorTitle":[{"text":"STPErrorBlock","kind":"identifier"}],"url":"\/documentation\/stripe\/stperrorblock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/attachPaymentMethod(toCustomer:completion:)":{"title":"attachPaymentMethod(toCustomer:completion:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/attachPaymentMethod(toCustomer:completion:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"attachPaymentMethodToCustomer:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"attachPaymentMethod","kind":"identifier"},{"kind":"text","text":"("},{"text":"toCustomer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"kind":"symbol","abstract":[{"text":"Adds a Payment Method to a customer.","type":"text"},{"type":"text","text":" "},{"text":"If you are implementing your own ","type":"text"},{"text":":","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"text":" ","type":"text"},{"text":"Then, call the Attach method on the Payment Method with that customer’s ID","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"( https:\/\/stripe.com\/docs\/api\/payment_methods\/attach ). If this API call succeeds,"},{"type":"text","text":" "},{"type":"text","text":"call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"code":"completion(error)","type":"codeVoice"},{"text":" with the error that","type":"text"},{"type":"text","text":" "},{"text":"occurred.","type":"text"}],"url":"\/documentation\/stripe\/stpcustomercontext\/attachpaymentmethod(tocustomer:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethod":{"abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","role":"symbol","title":"STPPaymentMethod","url":"\/documentation\/stripe\/stppaymentmethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"attachPaymentMethodToCustomer:completion:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"attachPaymentMethodToCustomer:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"attachPaymentMethodToCustomer:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":" *) ","kind":"text"},{"text":"paymentMethod","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]},{"value":"attachPaymentMethodToCustomer:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1attachPaymentMethod(toCustomer:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1attachPaymentMethod(toCustomer:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"attachPaymentMethodToCustomer:completion:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
