{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearCache","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"sections":[],"kind":"symbol","metadata":{"title":"clearCache()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearCache"}],"externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)clearCache","modules":[{"name":"Stripe"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/clearCache()","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" will cache its customer object and associated payment methods"},{"type":"text","text":" "},{"type":"text","text":"for up to 60 seconds. If your current user logs out of your app and a new user logs"},{"text":" ","type":"text"},{"type":"text","text":"in, be sure to either call this method or create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"On your backend, be sure to create and return a new ephemeral key for the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"customer object associated with the new user."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcustomercontext\/clearcache()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpcustomercontext\/clearcache()"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/clearCache()":{"title":"clearCache()","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/clearCache()","role":"symbol","abstract":[{"code":"STPCustomerContext","type":"codeVoice"},{"text":" will cache its customer object and associated payment methods","type":"text"},{"type":"text","text":" "},{"text":"for up to 60 seconds. If your current user logs out of your app and a new user logs","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in, be sure to either call this method or create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"On your backend, be sure to create and return a new ephemeral key for the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customer object associated with the new user."}],"navigatorTitle":[{"kind":"identifier","text":"clearCache"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/stripe\/stpcustomercontext\/clearcache()","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"type":"topic","title":"STPCustomerContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"text":" ","type":"text"},{"text":"be sure to either create a new instance of ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" or clear the current","type":"text"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"text":"new ephemeral key for the Customer object associated with the new user.","type":"text"}],"navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcustomercontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"clearCache","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearCache"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"clearCache","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"clearCache","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1clearCache()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1clearCache()\/fragments","value":[{"kind":"text","text":"- "},{"text":"clearCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","op":"replace","value":"STPCustomerContext"},{"op":"replace","value":[{"text":"STPCustomerContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments"}]}]}
