{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromCustomer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"paymentMethod","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Payment Method to delete from the customer"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this callback when you’re done deleting the Payment Method"},{"type":"text","text":" "},{"type":"text","text":"from the customer on your backend. For example, "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":" (if your call"},{"type":"text","text":" "},{"type":"text","text":"succeeds) or "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" if an error is returned."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcustomercontext\/detachpaymentmethod(fromcustomer:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpcustomercontext\/detachpaymentmethod(fromcustomer:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethod(fromCustomer:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Deletes the given Payment Method from the customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"Call the Detach method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/detach )"},{"type":"text","text":" "},{"type":"text","text":"on the Payment Method. If this API call succeeds, call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromCustomer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"title":"detachPaymentMethod(fromCustomer:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)detachPaymentMethodFromCustomer:completion:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"detachPaymentMethodFromCustomer:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/detachPaymentMethod(fromCustomer:completion:)":{"role":"symbol","title":"detachPaymentMethod(fromCustomer:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromCustomer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deletes the given Payment Method from the customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"Call the Detach method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/detach )"},{"type":"text","text":" "},{"type":"text","text":"on the Payment Method. If this API call succeeds, call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethod(fromCustomer:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detachPaymentMethodFromCustomer:completion:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/detachpaymentmethod(fromcustomer:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"role":"symbol","title":"STPCustomerContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" retrieves and updates a Stripe customer and their attached"},{"type":"text","text":" "},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"type":"text","text":" "},{"type":"text","text":"instance’s cache. On your backend, be sure to create and return a"},{"type":"text","text":" "},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomerContext"}],"url":"\/documentation\/stripe\/stpcustomercontext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethod":{"role":"symbol","title":"STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"url":"\/documentation\/stripe\/stppaymentmethod"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"role":"symbol","title":"STPErrorBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPErrorBlock"}],"url":"\/documentation\/stripe\/stperrorblock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"detachPaymentMethodFromCustomer:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detachPaymentMethodFromCustomer:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"detachPaymentMethodFromCustomer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1detachPaymentMethod(fromCustomer:completion:)\/title","value":"detachPaymentMethodFromCustomer:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1detachPaymentMethod(fromCustomer:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detachPaymentMethodFromCustomer:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
