{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detachPaymentMethodFromCustomer"},{"text":"(","kind":"text"},{"text":"paymentMethodId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPErrorBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"text":"?)","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:","kind":"identifier"}],"role":"symbol","title":"detachPaymentMethodFromCustomer(paymentMethodId:completion:)","roleHeading":"Instance Method","externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)detachPaymentMethodFromCustomerWithPaymentMethodId:completion:","modules":[{"name":"Stripe"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"detachPaymentMethodFromCustomer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethodId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcustomercontext\/detachpaymentmethodfromcustomer(paymentmethodid:completion:)"]},{"paths":["\/documentation\/stripe\/stpcustomercontext\/detachpaymentmethodfromcustomer(paymentmethodid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethodFromCustomer(paymentMethodId:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"A convenience method for detaching the PaymentMethod to the current Customer"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/detachPaymentMethodFromCustomer(paymentMethodId:completion:)":{"type":"topic","title":"detachPaymentMethodFromCustomer(paymentMethodId:completion:)","navigatorTitle":[{"kind":"identifier","text":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethodFromCustomer(paymentMethodId:completion:)","url":"\/documentation\/stripe\/stpcustomercontext\/detachpaymentmethodfromcustomer(paymentmethodid:completion:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detachPaymentMethodFromCustomer","kind":"identifier"},{"kind":"text","text":"("},{"text":"paymentMethodId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"text":"?)","kind":"text"}],"abstract":[{"text":"A convenience method for detaching the PaymentMethod to the current Customer","type":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"type":"topic","title":"STPErrorBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"navigatorTitle":[{"text":"STPErrorBlock","kind":"identifier"}],"url":"\/documentation\/stripe\/stperrorblock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"type":"topic","title":"STPCustomerContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"text":" ","type":"text"},{"text":"be sure to either create a new instance of ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" or clear the current","type":"text"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"text":"new ephemeral key for the Customer object associated with the new user.","type":"text"}],"navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcustomercontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"detachPaymentMethodFromCustomerWithPaymentMethodId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"paymentMethodId"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1detachPaymentMethodFromCustomer(paymentMethodId:completion:)\/title","value":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1detachPaymentMethodFromCustomer(paymentMethodId:completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext"},{"op":"replace","value":[{"text":"STPCustomerContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments"}]}]}
