{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/includeApplePayPaymentMethods","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"Stripe"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(py)includeApplePayPaymentMethods","navigatorTitle":[{"text":"includeApplePayPaymentMethods","kind":"identifier"}],"title":"includeApplePayPaymentMethods","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"includeApplePayPaymentMethods"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeApplePayPaymentMethods"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"abstract":[{"type":"text","text":"By default, "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" will filter Apple Pay when it retrieves","type":"text"},{"type":"text","text":" "},{"text":"Payment Methods. Apple Pay payment methods should generally not be re-used and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"shouldn’t be offered to customers as a new payment method (Apple Pay payment"},{"type":"text","text":" "},{"type":"text","text":"methods may only be re-used for subscriptions)."},{"text":" ","type":"text"},{"text":"If you are using ","type":"text"},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":" to back your own UI and would like to"},{"type":"text","text":" "},{"type":"text","text":"disable Apple Pay filtering, set this property to YES."},{"type":"text","text":" "},{"text":"Note: If you are using ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", you should not change this property."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"variants":[{"paths":["\/documentation\/stripe\/stpcustomercontext\/includeapplepaypaymentmethods"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpcustomercontext\/includeapplepaypaymentmethods"]}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"type":"topic","title":"STPCustomerContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"text":" ","type":"text"},{"text":"be sure to either create a new instance of ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" or clear the current","type":"text"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"text":"new ephemeral key for the Customer object associated with the new user.","type":"text"}],"navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcustomercontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/includeApplePayPaymentMethods":{"type":"topic","abstract":[{"type":"text","text":"By default, "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":" will filter Apple Pay when it retrieves"},{"type":"text","text":" "},{"text":"Payment Methods. Apple Pay payment methods should generally not be re-used and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"shouldn’t be offered to customers as a new payment method (Apple Pay payment"},{"type":"text","text":" "},{"text":"methods may only be re-used for subscriptions).","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you are using "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to back your own UI and would like to"},{"type":"text","text":" "},{"type":"text","text":"disable Apple Pay filtering, set this property to YES."},{"text":" ","type":"text"},{"type":"text","text":"Note: If you are using "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":", you should not change this property.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"includeApplePayPaymentMethods","kind":"identifier"}],"title":"includeApplePayPaymentMethods","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"includeApplePayPaymentMethods","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/includeApplePayPaymentMethods","kind":"symbol","url":"\/documentation\/stripe\/stpcustomercontext\/includeapplepaypaymentmethods"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"includeApplePayPaymentMethods"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"includeApplePayPaymentMethods","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"includeApplePayPaymentMethods","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","op":"replace","value":"STPCustomerContext"},{"op":"replace","value":[{"text":"STPCustomerContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1includeApplePayPaymentMethods\/title","op":"replace","value":"includeApplePayPaymentMethods"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1includeApplePayPaymentMethods\/fragments","op":"replace","value":[{"kind":"identifier","text":"includeApplePayPaymentMethods"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
