{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithKeyProvider:apiClient:) ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","text":"STPCustomerEphemeralKeyProvider"},{"text":"?, ","kind":"text"},{"text":"apiClient","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAPIClient"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"keyProvider","content":[{"inlineContent":[{"text":"The key provider the customer context will use.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The API Client to use to make requests.","type":"text"}]}],"name":"apiClient"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"the newly-instantiated customer context."}]}]}],"abstract":[{"type":"text","text":"Initializes a new "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" with the specified key provider.","type":"text"},{"type":"text","text":" "},{"text":"Upon initialization, a CustomerContext will fetch a new ephemeral key from","type":"text"},{"type":"text","text":" "},{"text":"your backend and use it to prefetch the customer object specified in the key.","type":"text"},{"type":"text","text":" "},{"text":"Subsequent customer and payment method retrievals (e.g. by ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":")"},{"text":" ","type":"text"},{"type":"text","text":"will return the prefetched customer \/ attached payment methods immediately if"},{"text":" ","type":"text"},{"type":"text","text":"its age does not exceed 60 seconds."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcustomercontext\/init(keyprovider:apiclient:)"]},{"paths":["\/documentation\/stripe\/stpcustomercontext\/init(keyprovider:apiclient:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:apiClient:)"},"metadata":{"symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPCustomerEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"apiClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient"},{"kind":"text","text":")"}],"modules":[{"name":"Stripe"}],"title":"init(keyProvider:apiClient:)","roleHeading":"Initializer","externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)initWithKeyProvider:apiClient:","navigatorTitle":[{"text":"initWithKeyProvider:apiClient:","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/init(keyProvider:apiClient:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider","text":"STPCustomerEphemeralKeyProvider"},{"kind":"text","text":"?, "},{"text":"apiClient","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" with the specified key provider."},{"type":"text","text":" "},{"type":"text","text":"Upon initialization, a CustomerContext will fetch a new ephemeral key from"},{"text":" ","type":"text"},{"type":"text","text":"your backend and use it to prefetch the customer object specified in the key."},{"type":"text","text":" "},{"text":"Subsequent customer and payment method retrievals (e.g. by ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":")","type":"text"},{"type":"text","text":" "},{"type":"text","text":"will return the prefetched customer \/ attached payment methods immediately if"},{"type":"text","text":" "},{"type":"text","text":"its age does not exceed 60 seconds."}],"title":"init(keyProvider:apiClient:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:apiClient:)","url":"\/documentation\/stripe\/stpcustomercontext\/init(keyprovider:apiclient:)","navigatorTitle":[{"text":"initWithKeyProvider:apiClient:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAPIClient":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"url":"\/documentation\/stripe\/stpapiclient","title":"STPAPIClient","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAPIClient","kind":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerEphemeralKeyProvider":{"navigatorTitle":[{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"text":"It provides a way for Stripe utility classes to request a new ephemeral key from","type":"text"},{"type":"text","text":" "},{"text":"your backend, which it will use to retrieve and update Stripe API objects.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","url":"\/documentation\/stripe\/stpcustomerephemeralkeyprovider","title":"STPCustomerEphemeralKeyProvider"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"type":"topic","title":"STPCustomerContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"text":" ","type":"text"},{"text":"be sure to either create a new instance of ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" or clear the current","type":"text"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"text":"new ephemeral key for the Customer object associated with the new user.","type":"text"}],"navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcustomercontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithKeyProvider:apiClient:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithKeyProvider:apiClient:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithKeyProvider:"},{"text":"(","kind":"text"},{"text":"id<STPCustomerEphemeralKeyProvider>","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"keyProvider","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiClient:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"apiClient","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithKeyProvider:apiClient:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1init(keyProvider:apiClient:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithKeyProvider:apiClient:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1init(keyProvider:apiClient:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/title","value":"STPCustomerEphemeralKeyProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/fragments","op":"replace","value":[{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}]},{"value":"STPCustomerContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
