{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithKeyProvider:) "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider","text":"STPCustomerEphemeralKeyProvider"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"keyProvider","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key provider the customer context will use."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"the newly-instantiated customer context."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcustomercontext\/init(keyprovider:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpcustomercontext\/init(keyprovider:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" with the specified key provider."},{"type":"text","text":" "},{"type":"text","text":"Upon initialization, a CustomerContext will fetch a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend and use it to prefetch the customer object specified in the key."},{"type":"text","text":" "},{"type":"text","text":"Subsequent customer and payment method retrievals (e.g. by "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"will return the prefetched customer \/ attached payment methods immediately if"},{"type":"text","text":" "},{"type":"text","text":"its age does not exceed 60 seconds."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider"},{"kind":"text","text":")"}],"title":"init(keyProvider:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)initWithKeyProvider:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"initWithKeyProvider:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"role":"symbol","title":"STPCustomerContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" retrieves and updates a Stripe customer and their attached"},{"type":"text","text":" "},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"type":"text","text":" "},{"type":"text","text":"instance’s cache. On your backend, be sure to create and return a"},{"type":"text","text":" "},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomerContext"}],"url":"\/documentation\/stripe\/stpcustomercontext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/init(keyProvider:)":{"role":"symbol","title":"init(keyProvider:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" with the specified key provider."},{"type":"text","text":" "},{"type":"text","text":"Upon initialization, a CustomerContext will fetch a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend and use it to prefetch the customer object specified in the key."},{"type":"text","text":" "},{"type":"text","text":"Subsequent customer and payment method retrievals (e.g. by "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"will return the prefetched customer \/ attached payment methods immediately if"},{"type":"text","text":" "},{"type":"text","text":"its age does not exceed 60 seconds."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithKeyProvider:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/init(keyprovider:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerEphemeralKeyProvider":{"role":"symbol","title":"STPCustomerEphemeralKeyProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"url":"\/documentation\/stripe\/stpcustomerephemeralkeyprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithKeyProvider:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyProvider:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithKeyProvider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<STPCustomerEphemeralKeyProvider>","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"keyProvider"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1init(keyProvider:)\/title","value":"initWithKeyProvider:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1init(keyProvider:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyProvider:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/title","value":"STPCustomerEphemeralKeyProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/fragments","value":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
