{"kind":"symbol","abstract":[{"type":"text","text":"Retrieves a list of Payment Methods attached to a customer."},{"text":" ","type":"text"},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"Call the list method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/list )"},{"text":" ","type":"text"},{"text":"with the Stripe customer. If this API call succeeds, call ","type":"text"},{"type":"codeVoice","code":"completion(paymentMethods)"},{"text":" ","type":"text"},{"text":"with the list of PaymentMethods. Otherwise, call ","type":"text"},{"type":"codeVoice","code":"completion(error)"},{"text":" with the error","type":"text"},{"type":"text","text":" "},{"text":"that occurred.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/listPaymentMethodsForCustomer(completion:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcustomercontext\/listpaymentmethodsforcustomer(completion:)"]},{"paths":["\/documentation\/stripe\/stpcustomercontext\/listpaymentmethodsforcustomer(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listPaymentMethodsForCustomer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments32STPPaymentMethodsCompletionBlocka","kind":"typeIdentifier","text":"STPPaymentMethodsCompletionBlock"},{"text":"?)","kind":"text"}],"externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)listPaymentMethodsForCustomerWithCompletion:","modules":[{"name":"Stripe"}],"role":"symbol","title":"listPaymentMethodsForCustomer(completion:)","navigatorTitle":[{"text":"listPaymentMethodsForCustomerWithCompletion:","kind":"identifier"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listPaymentMethodsForCustomer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodsCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodsCompletionBlock","preciseIdentifier":"s:14StripePayments32STPPaymentMethodsCompletionBlocka","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Call this callback with the list of Payment Methods attached to the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"customer.  For example, "},{"code":"completion(paymentMethods)","type":"codeVoice"},{"text":" (if your call succeeds) or","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" if an error is returned."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"kind":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"type":"text","text":" "},{"text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCustomerContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","url":"\/documentation\/stripe\/stpcustomercontext","role":"symbol","title":"STPCustomerContext","type":"topic","navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethodsCompletionBlock":{"kind":"symbol","abstract":[{"type":"text","text":"A callback to be run with an array of PaymentMethods response from the Stripe API."}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodsCompletionBlock"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodsCompletionBlock","url":"\/documentation\/stripe\/stppaymentmethodscompletionblock","role":"symbol","title":"STPPaymentMethodsCompletionBlock","type":"topic","navigatorTitle":[{"text":"STPPaymentMethodsCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/listPaymentMethodsForCustomer(completion:)":{"kind":"symbol","abstract":[{"text":"Retrieves a list of Payment Methods attached to a customer.","type":"text"},{"type":"text","text":" "},{"text":"If you are implementing your own ","type":"text"},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"Call the list method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/list )"},{"text":" ","type":"text"},{"text":"with the Stripe customer. If this API call succeeds, call ","type":"text"},{"type":"codeVoice","code":"completion(paymentMethods)"},{"type":"text","text":" "},{"text":"with the list of PaymentMethods. Otherwise, call ","type":"text"},{"code":"completion(error)","type":"codeVoice"},{"type":"text","text":" with the error"},{"text":" ","type":"text"},{"type":"text","text":"that occurred."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"listPaymentMethodsForCustomer"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodsCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments32STPPaymentMethodsCompletionBlocka"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/listPaymentMethodsForCustomer(completion:)","url":"\/documentation\/stripe\/stpcustomercontext\/listpaymentmethodsforcustomer(completion:)","role":"symbol","title":"listPaymentMethodsForCustomer(completion:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"listPaymentMethodsForCustomerWithCompletion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"listPaymentMethodsForCustomerWithCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(NSArray<STPPaymentMethod *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPCustomerContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCustomerContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1listPaymentMethodsForCustomer(completion:)\/title","op":"replace","value":"listPaymentMethodsForCustomerWithCompletion:"},{"value":[{"text":"- ","kind":"text"},{"text":"listPaymentMethodsForCustomerWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1listPaymentMethodsForCustomer(completion:)\/fragments"}]}]}
