{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcustomercontext\/retrievecustomer(_:)"]},{"paths":["\/documentation\/stripe\/stpcustomercontext\/retrievecustomer(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/retrieveCustomer(_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPCustomerCompletionBlock","preciseIdentifier":"s:14StripePayments26STPCustomerCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerCompletionBlock","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call this callback when you’re done fetching and parsing the above information from your backend. For example, "},{"type":"codeVoice","code":"completion(customer, nil)"},{"type":"text","text":" (if your call succeeds) or "},{"code":"completion(nil, error)","type":"codeVoice"},{"text":" if an error is returned.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"name":"See Also","content":[{"inlineContent":[{"type":"text","text":"STPCard"}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"title":"retrieveCustomer(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"retrieveCustomer:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"retrieveCustomer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14StripePayments26STPCustomerCompletionBlocka","text":"STPCustomerCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)retrieveCustomer:"},"abstract":[{"text":"Retrieve the customer to be displayed inside a payment context.","type":"text"},{"type":"text","text":" "},{"text":"If you are not using STPCustomerContext:","type":"text"},{"type":"text","text":" "},{"text":"On your backend, retrieve the Stripe customer associated with your currently","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"logged-in user ( https:\/\/stripe.com\/docs\/api#retrieve_customer ), and return"},{"type":"text","text":" "},{"type":"text","text":"the raw JSON response from the Stripe API. Back in your iOS app, after you’ve"},{"type":"text","text":" "},{"type":"text","text":"called this API, deserialize your API response into an "},{"code":"STPCustomer","type":"codeVoice"},{"text":" object","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(you can use the "},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"type":"text","text":" class to do this)."}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/retrieveCustomer(_:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/retrieveCustomer(_:)","title":"retrieveCustomer(_:)","abstract":[{"type":"text","text":"Retrieve the customer to be displayed inside a payment context."},{"type":"text","text":" "},{"type":"text","text":"If you are not using STPCustomerContext:"},{"type":"text","text":" "},{"text":"On your backend, retrieve the Stripe customer associated with your currently","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"logged-in user ( https:\/\/stripe.com\/docs\/api#retrieve_customer ), and return"},{"type":"text","text":" "},{"type":"text","text":"the raw JSON response from the Stripe API. Back in your iOS app, after you’ve"},{"type":"text","text":" "},{"type":"text","text":"called this API, deserialize your API response into an "},{"type":"codeVoice","code":"STPCustomer"},{"text":" object","type":"text"},{"type":"text","text":" "},{"text":"(you can use the ","type":"text"},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"text":" class to do this).","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"retrieveCustomer:"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveCustomer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPCustomerCompletionBlock","preciseIdentifier":"s:14StripePayments26STPCustomerCompletionBlocka"},{"kind":"text","text":"?)"}],"url":"\/documentation\/stripe\/stpcustomercontext\/retrievecustomer(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"kind":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"type":"text","text":" "},{"text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCustomerContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","url":"\/documentation\/stripe\/stpcustomercontext","role":"symbol","title":"STPCustomerContext","type":"topic","navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerCompletionBlock":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerCompletionBlock","title":"STPCustomerCompletionBlock","abstract":[{"type":"text","text":"A callback to be run with a customer response from the Stripe API."}],"role":"symbol","navigatorTitle":[{"text":"STPCustomerCompletionBlock","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"STPCustomerCompletionBlock","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcustomercompletionblock"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"retrieveCustomer:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"retrieveCustomer:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"retrieveCustomer:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$@M@StripePayments@objc(cs)STPCustomer#*$objc(cs)NSError)","text":"void (^)(STPCustomer *, NSError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1retrieveCustomer(_:)\/title","value":"retrieveCustomer:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1retrieveCustomer(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"retrieveCustomer:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","op":"replace","value":"STPCustomerContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
