{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withShippingAddress"},{"kind":"text","text":" "},{"kind":"internalParam","text":"shipping"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"shipping","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The shipping address to set on the customer"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call this callback when you’re done updating the customer on"},{"type":"text","text":" "},{"type":"text","text":"your backend. For example, "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":" (if your call succeeds) or"},{"type":"text","text":" "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" if an error is returned."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"https:\/\/stripe.com\/docs\/api#update_customer"}]}],"type":"aside","name":"See Also"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcustomercontext\/updatecustomer(withshippingaddress:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpcustomercontext\/updatecustomer(withshippingaddress:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/updateCustomer(withShippingAddress:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the given shipping address on the customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"type":"text","text":" "},{"type":"text","text":"Then, call the Customer Update method ( https:\/\/stripe.com\/docs\/api#update_customer )"},{"type":"text","text":" "},{"type":"text","text":"specifying shipping to be the given shipping address. If this API call succeeds,"},{"type":"text","text":" "},{"type":"text","text":"call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withShippingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"title":"updateCustomer(withShippingAddress:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPCustomerContext(im)updateCustomerWithShippingAddress:completion:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"updateCustomerWithShippingAddress:completion:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/updateCustomer(withShippingAddress:completion:)":{"role":"symbol","title":"updateCustomer(withShippingAddress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withShippingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Sets the given shipping address on the customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"type":"text","text":" "},{"type":"text","text":"Then, call the Customer Update method ( https:\/\/stripe.com\/docs\/api#update_customer )"},{"type":"text","text":" "},{"type":"text","text":"specifying shipping to be the given shipping address. If this API call succeeds,"},{"type":"text","text":" "},{"type":"text","text":"call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/updateCustomer(withShippingAddress:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateCustomerWithShippingAddress:completion:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/updatecustomer(withshippingaddress:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"role":"symbol","title":"STPAddress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}],"url":"\/documentation\/stripe\/stpaddress"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"role":"symbol","title":"STPErrorBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPErrorBlock"}],"url":"\/documentation\/stripe\/stperrorblock"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"role":"symbol","title":"STPCustomerContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" retrieves and updates a Stripe customer and their attached"},{"type":"text","text":" "},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"type":"text","text":" "},{"type":"text","text":"instance’s cache. On your backend, be sure to create and return a"},{"type":"text","text":" "},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomerContext"}],"url":"\/documentation\/stripe\/stpcustomercontext"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateCustomerWithShippingAddress:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCustomerWithShippingAddress:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateCustomerWithShippingAddress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"shipping"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1updateCustomer(withShippingAddress:completion:)\/title","value":"updateCustomerWithShippingAddress:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1updateCustomer(withShippingAddress:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCustomerWithShippingAddress:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
