{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Initializes a new view controller with the specified theme","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"theme","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"theme","content":[{"inlineContent":[{"text":"The theme to use to inform the view controller’s visual appearance. - seealso: STPTheme","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(theme:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcoreviewcontroller\/init(theme:)"]},{"paths":["\/documentation\/stripe\/stpcoreviewcontroller\/init(theme:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"init(theme:)","roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"text":"STPTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithTheme:","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPCoreViewController(im)initWithTheme:","modules":[{"name":"Stripe"}],"symbolKind":"init"},"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/init(theme:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes a new view controller with the specified theme"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTheme:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(theme:)","url":"\/documentation\/stripe\/stpcoreviewcontroller\/init(theme:)","type":"topic","title":"init(theme:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCoreViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe view controllers. It is intended for use"},{"text":" ","type":"text"},{"text":"only by Stripe classes, you should not subclass it yourself in your app.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It theming, back\/cancel button management, and other shared logic for"},{"type":"text","text":" "},{"type":"text","text":"Stripe view controllers."}],"title":"STPCoreViewController","navigatorTitle":[{"text":"STPCoreViewController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController","kind":"symbol","url":"\/documentation\/stripe\/stpcoreviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","type":"topic","abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"title":"STPTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTheme","kind":"identifier"}],"url":"\/documentation\/stripe\/stptheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithTheme:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTheme:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithTheme:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"theme"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"initWithTheme:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init(theme:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithTheme:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init(theme:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/title","value":"STPCoreViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/fragments","value":[{"text":"STPCoreViewController","kind":"identifier"}]},{"value":"STPTheme","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","value":[{"text":"STPTheme","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
