{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcoreviewcontroller\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpcoreviewcontroller\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A convenience initializer; equivalent to calling "},{"type":"codeVoice","code":"init(theme: STPTheme.defaultTheme)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@Stripe@objc(cs)STPCoreViewController(im)init","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"A convenience initializer; equivalent to calling "},{"type":"codeVoice","code":"init(theme: STPTheme.defaultTheme)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/stripe\/stpcoreviewcontroller\/init()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController":{"role":"symbol","title":"STPCoreViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe view controllers. It is intended for use"},{"type":"text","text":" "},{"type":"text","text":"only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It theming, back\/cancel button management, and other shared logic for"},{"type":"text","text":" "},{"type":"text","text":"Stripe view controllers."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreViewController"}],"url":"\/documentation\/stripe\/stpcoreviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/title","value":"STPCoreViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}