{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"Stripe"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preferredStatusBarStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"}],"role":"symbol","title":"preferredStatusBarStyle","externalID":"c:@M@Stripe@objc(cs)STPCoreViewController(py)preferredStatusBarStyle","navigatorTitle":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcoreviewcontroller\/preferredstatusbarstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpcoreviewcontroller\/preferredstatusbarstyle"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredStatusBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":":nodoc:"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/preferredStatusBarStyle"},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/preferredStatusBarStyle":{"url":"\/documentation\/stripe\/stpcoreviewcontroller\/preferredstatusbarstyle","navigatorTitle":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"abstract":[{"type":"text","text":":nodoc:"}],"title":"preferredStatusBarStyle","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/preferredStatusBarStyle","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preferredStatusBarStyle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle","text":"UIStatusBarStyle"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCoreViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe view controllers. It is intended for use"},{"text":" ","type":"text"},{"text":"only by Stripe classes, you should not subclass it yourself in your app.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It theming, back\/cancel button management, and other shared logic for"},{"type":"text","text":" "},{"type":"text","text":"Stripe view controllers."}],"title":"STPCoreViewController","navigatorTitle":[{"text":"STPCoreViewController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController","kind":"symbol","url":"\/documentation\/stripe\/stpcoreviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"preferredStatusBarStyle"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"preferredStatusBarStyle"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"UIStatusBarStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIStatusBarStyle"},{"text":" ","kind":"text"},{"text":"preferredStatusBarStyle","kind":"identifier"}]}]}},{"value":"preferredStatusBarStyle","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1preferredStatusBarStyle\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1preferredStatusBarStyle\/fragments","op":"replace","value":[{"text":"preferredStatusBarStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/title","value":"STPCoreViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCoreViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
