{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewControllerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpaddcardviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPAddCardViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":" "},{"type":"text","text":"successfully creates a card token or is cancelled. It has internal error-handling"},{"type":"text","text":" "},{"type":"text","text":"logic, so there’s no error case to deal with."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"title":"STPAddCardViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@Stripe@objc(pl)STPAddCardViewControllerDelegate","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreatePaymentMethod:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateSource:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateToken:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewControllerDidCancel(_:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate/addCardViewController(_:didCreateSource:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"addCardViewController:didCreateSource:completion:"}],"deprecated":false,"role":"symbol","title":"addCardViewController(_:didCreateSource:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreateSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method is deprecated as of v16.0.0 (https:\/\/github.com\/stripe\/stripe-ios\/blob\/master\/MIGRATING.md#migrating-from-versions–1600)."},{"type":"text","text":" "},{"type":"text","text":"To use this class, migrate your integration from Charges to PaymentIntents. See https:\/\/stripe.com\/docs\/payments\/payment-intents\/migration\/charges#read"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateSource:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatesource:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"role":"symbol","title":"STPPaymentOptionsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"type":"text","text":" "},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":", so you can either"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"as the "},{"type":"codeVoice","code":"rootViewController"},{"type":"text","text":" and then present the "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" onto an existing"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"type":"codeVoice","code":"presentPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate/addCardViewControllerDidCancel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"addCardViewControllerDidCancel:"}],"role":"symbol","title":"addCardViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the user cancels adding a card. You should dismiss (or pop) the"},{"type":"text","text":" "},{"type":"text","text":"view controller at this point."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewControllerDidCancel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontrollerdidcancel(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate/addCardViewController(_:didCreatePaymentMethod:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"addCardViewController:didCreatePaymentMethod:completion:"}],"role":"symbol","title":"addCardViewController(_:didCreatePaymentMethod:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user successfully adds a card and Stripe returns a"},{"type":"text","text":" "},{"type":"text","text":"Payment Method."},{"type":"text","text":" "},{"type":"text","text":"You should send the PaymentMethod to your backend to store it on a customer, and then"},{"type":"text","text":" "},{"type":"text","text":"call the provided "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when that call is finished. If an error"},{"type":"text","text":" "},{"type":"text","text":"occurs while talking to your backend, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":", otherwise,"},{"type":"text","text":" "},{"type":"text","text":"dismiss (or pop) the view controller."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreatePaymentMethod:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatepaymentmethod:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate/addCardViewController(_:didCreateToken:completion:)":{"deprecated":false,"role":"symbol","title":"addCardViewController(_:didCreateToken:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreateToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method is deprecated as of v16.0.0 (https:\/\/github.com\/stripe\/stripe-ios\/blob\/master\/MIGRATING.md#migrating-from-versions–1600)."},{"type":"text","text":" "},{"type":"text","text":"To use this class, migrate your integration from Charges to PaymentIntents. See https:\/\/stripe.com\/docs\/payments\/payment-intents\/migration\/charges#read"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateToken:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCardViewController:didCreateToken:completion:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatetoken:completion:)"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate":{"role":"symbol","title":"STPAddCardViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPAddCardViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":" "},{"type":"text","text":"successfully creates a card token or is cancelled. It has internal error-handling"},{"type":"text","text":" "},{"type":"text","text":"logic, so there’s no error case to deal with."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"STPAddCardViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreatePaymentMethod:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateSource:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateToken:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewControllerDidCancel(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewControllerDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreateSource:completion:)\/title","value":"addCardViewController:didCreateSource:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreateSource:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreateSource:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","value":"STPPaymentOptionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewControllerDidCancel(_:)\/title","value":"addCardViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewControllerDidCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreatePaymentMethod:completion:)\/title","value":"addCardViewController:didCreatePaymentMethod:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreatePaymentMethod:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreatePaymentMethod:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreateToken:completion:)\/title","value":"addCardViewController:didCreateToken:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreateToken:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreateToken:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/title","value":"STPAddCardViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
