{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextFieldDelegate","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIScrollViewDelegate","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDataSource","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDelegate","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Stripe@objc(cs)STPAddCardViewController","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/init()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/init(configuration:theme:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/apiClient","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/customFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/delegate","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/prefilledInformation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/handleCancelTapped(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/numberOfSections(in:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidBeginEditing(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidBeginEditingCVC(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidChange(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidEndEditingCVC(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldWillEndEditing(forReturn:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:estimatedHeightForRowAt:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:heightForFooterInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:heightForHeaderInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:numberOfRowsInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:viewForFooterInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:viewForHeaderInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:willDisplay:forRowAt:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/updateAppearance()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewDidAppear(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewDidLayoutSubviews()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewWillTransition(to:with:)"]}],"references":{"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"A convenience initializer; equivalent to calling "},{"type":"codeVoice","code":"init(configuration: STPPaymentConfiguration.shared, theme: STPTheme.defaultTheme)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/init()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:viewForFooterInSection:)":{"role":"symbol","title":"tableView(_:viewForFooterInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForFooterInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:viewForFooterInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:viewForFooterInSection:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:viewforfooterinsection:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddCardViewControllerDelegate","preciseIdentifier":"c:@M@Stripe@objc(pl)STPAddCardViewControllerDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The view controller’s delegate. This must be set before showing the view controller in order for it to work properly. - seealso: STPAddCardViewControllerDelegate"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/delegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentCardTextFieldDelegate":{"role":"symbol","title":"STPPaymentCardTextFieldDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"abstract":[{"type":"text","text":"This protocol allows a delegate to be notified when a payment text field’s"},{"type":"text","text":" "},{"type":"text","text":"contents change, which can in turn be used to take further actions depending"},{"type":"text","text":" "},{"type":"text","text":"on the validity of its contents."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentCardTextFieldDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"url":"\/documentation\/stripe\/stppaymentcardtextfielddelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:estimatedHeightForRowAt:)":{"role":"symbol","title":"tableView(_:estimatedHeightForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"estimatedHeightForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:estimatedHeightForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:estimatedHeightForRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:estimatedheightforrowat:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/paymentCardTextFieldDidBeginEditing(_:)":{"role":"symbol","title":"paymentCardTextFieldDidBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when editing begins in the text field as a whole."},{"type":"text","text":" "},{"type":"text","text":"After receiving this callback, you will always also receive a callback for which"},{"type":"text","text":" "},{"type":"text","text":"specific subfield of the view began editing."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidBeginEditing(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditing:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidbeginediting(_:)"},"doc://com.stripe.stripe-ios/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/numberOfSections(in:)":{"role":"symbol","title":"numberOfSections(in:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfSections"},{"kind":"text","text":"("},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/numberOfSections(in:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfSectionsInTableView:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/numberofsections(in:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/prefilledInformation":{"role":"symbol","title":"prefilledInformation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefilledInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPUserInformation","preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"You can set this property to pre-fill any information you’ve already collected from your user. - seealso: STPUserInformation.h"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/prefilledInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prefilledInformation"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/prefilledinformation"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:viewForHeaderInSection:)":{"role":"symbol","title":"tableView(_:viewForHeaderInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewForHeaderInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:viewForHeaderInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:viewForHeaderInSection:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:viewforheaderinsection:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/paymentCardTextFieldDidBeginEditingCVC(_:)":{"role":"symbol","title":"paymentCardTextFieldDidBeginEditingCVC(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingCVC"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when editing begins in the payment card field’s CVC field."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidBeginEditingCVC(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingCVC:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidbegineditingcvc(_:)"},"doc://com.stripe.stripe-ios/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/viewWillTransition(to:with:)":{"role":"symbol","title":"viewWillTransition(to:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewWillTransition(to:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/viewwilltransition(to:with:)"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/viewdidlayoutsubviews()"},"doc://com.stripe.stripe-ios/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIScrollViewDelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/customFooterView":{"role":"symbol","title":"customFooterView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"customFooterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Provide this view controller with a footer view."},{"type":"text","text":" "},{"type":"text","text":"When the footer view needs to be resized, it will be sent a"},{"type":"text","text":" "},{"type":"codeVoice","code":"sizeThatFits:"},{"type":"text","text":" call. The view should respond correctly to this method in order"},{"type":"text","text":" "},{"type":"text","text":"to be sized and positioned properly."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/customFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customFooterView"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/customfooterview"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/updateAppearance()":{"role":"symbol","title":"updateAppearance()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateAppearance"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/updateAppearance()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateAppearance"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/updateappearance()"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/objc(pl)UITableViewDelegate":{"type":"unresolvable","title":"UITableViewDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDelegate"},"doc://com.stripe.stripe-ios/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling"},"doc://com.stripe.stripe-ios/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/objc(pl)UITableViewDataSource":{"type":"unresolvable","title":"UITableViewDataSource","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDataSource"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:cellForRowAt:)":{"role":"symbol","title":"tableView(_:cellForRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:cellForRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:cellforrowat:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:willDisplay:forRowAt:)":{"role":"symbol","title":"tableView(_:willDisplay:forRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willDisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:willDisplay:forRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:willdisplay:forrowat:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/handleCancelTapped(_:)":{"role":"symbol","title":"handleCancelTapped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleCancelTapped"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/handleCancelTapped(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"handleCancelTapped:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/handlecanceltapped(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:heightForHeaderInSection:)":{"role":"symbol","title":"tableView(_:heightForHeaderInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForHeaderInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:heightForHeaderInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:heightforheaderinsection:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/paymentCardTextFieldDidChange(_:)":{"role":"symbol","title":"paymentCardTextFieldDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when either the card number, expiration, or CVC changes. At this point,"},{"type":"text","text":" "},{"type":"text","text":"one can call "},{"type":"codeVoice","code":"isValid"},{"type":"text","text":" on the text field to determine, for example,"},{"type":"text","text":" "},{"type":"text","text":"whether or not to enable a button to submit the form. Example:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidChange:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidchange(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/init(configuration:theme:)":{"role":"symbol","title":"init(configuration:theme:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":" with the provided configuration and theme. Don’t forget to set the "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" property after initialization."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/init(configuration:theme:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:theme:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/init(configuration:theme:)"},"doc://com.stripe.stripe-ios/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController":{"role":"symbol","title":"STPCoreTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It inherits from STPCoreScrollViewController and changes the type of the"},{"type":"text","text":" "},{"type":"text","text":"created scroll view to UITableView, as well as other shared table view logic."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreTableViewController"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"role":"symbol","title":"STPAddCardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"}],"abstract":[{"type":"text","text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewController"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/paymentCardTextFieldDidEndEditingCVC(_:)":{"role":"symbol","title":"paymentCardTextFieldDidEndEditingCVC(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingCVC"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when editing ends in the payment card field’s CVC field."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidEndEditingCVC(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingCVC:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfielddidendeditingcvc(_:)"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:numberOfRowsInSection:)":{"role":"symbol","title":"tableView(_:numberOfRowsInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:numberOfRowsInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:numberofrowsinsection:)"},"doc://com.stripe.stripe-ios/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/apiClient":{"role":"symbol","title":"apiClient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"abstract":[{"type":"text","text":"The API Client to use to make requests."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"STPAPIClient.shared"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/apiClient","kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stpaddcardviewcontroller\/apiclient"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/paymentCardTextFieldWillEndEditing(forReturn:)":{"role":"symbol","title":"paymentCardTextFieldWillEndEditing(forReturn:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forReturn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Notification that the user pressed the "},{"type":"codeVoice","code":"return"},{"type":"text","text":" key after completely filling"},{"type":"text","text":" "},{"type":"text","text":"out the STPPaymentCardTextField with data that passes validation."},{"type":"text","text":" "},{"type":"text","text":"The Stripe SDK is going to "},{"type":"codeVoice","code":"resignFirstResponder"},{"type":"text","text":" on the "},{"type":"codeVoice","code":"STPPaymentCardTextField"},{"type":"text","text":" "},{"type":"text","text":"to dismiss the keyboard after this delegate method returns, however if your app wants"},{"type":"text","text":" "},{"type":"text","text":"to do something more (ex: move first responder to another field), this is a good"},{"type":"text","text":" "},{"type":"text","text":"opportunity to do that."},{"type":"text","text":" "},{"type":"text","text":"This is delivered "},{"type":"emphasis","inlineContent":[{"type":"text","text":"before"}]},{"type":"text","text":" the corresponding "},{"type":"codeVoice","code":"paymentCardTextFieldDidEndEditing:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldWillEndEditing(forReturn:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldWillEndEditingForReturn:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/paymentcardtextfieldwillendediting(forreturn:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/viewdidappear(_:)"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController/tableView(_:heightForFooterInSection:)":{"role":"symbol","title":"tableView(_:heightForFooterInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForFooterInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:heightForFooterInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForFooterInSection:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller\/tableview(_:heightforfooterinsection:)"},"doc://com.stripe.stripe-ios/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-ios/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPAddCardViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPAddCardViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/customFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/delegate","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/prefilledInformation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/handleCancelTapped(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/init()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/init(configuration:theme:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/numberOfSections(in:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidBeginEditing(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidBeginEditingCVC(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidChange(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldDidEndEditingCVC(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/paymentCardTextFieldWillEndEditing(forReturn:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:cellForRowAt:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:estimatedHeightForRowAt:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:heightForFooterInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:heightForHeaderInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:numberOfRowsInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:viewForFooterInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:viewForHeaderInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/tableView(_:willDisplay:forRowAt:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/updateAppearance()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewDidAppear(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewDidLayoutSubviews()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController\/viewWillTransition(to:with:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDataSource","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCoreTableViewController","text":"STPCoreTableViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:viewForFooterInSection:)\/title","value":"tableView:viewForFooterInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:viewForFooterInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:viewForFooterInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:estimatedHeightForRowAt:)\/title","value":"tableView:estimatedHeightForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:estimatedHeightForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:estimatedHeightForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidBeginEditing(_:)\/title","value":"paymentCardTextFieldDidBeginEditing:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidBeginEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditing:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1numberOfSections(in:)\/title","value":"numberOfSectionsInTableView:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1numberOfSections(in:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"numberOfSectionsInTableView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1prefilledInformation\/title","value":"prefilledInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1prefilledInformation\/fragments","value":[{"kind":"identifier","text":"prefilledInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:viewForHeaderInSection:)\/title","value":"tableView:viewForHeaderInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:viewForHeaderInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:viewForHeaderInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidBeginEditingCVC(_:)\/title","value":"paymentCardTextFieldDidBeginEditingCVC:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidBeginEditingCVC(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingCVC:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1viewWillTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1customFooterView\/title","value":"customFooterView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1customFooterView\/fragments","value":[{"kind":"identifier","text":"customFooterView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1updateAppearance()\/title","value":"updateAppearance"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1updateAppearance()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateAppearance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:cellForRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:willDisplay:forRowAt:)\/title","value":"tableView:willDisplayCell:forRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:willDisplay:forRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:willDisplayCell:forRowAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1handleCancelTapped(_:)\/title","value":"handleCancelTapped:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1handleCancelTapped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleCancelTapped:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:heightForHeaderInSection:)\/title","value":"tableView:heightForHeaderInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:heightForHeaderInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidChange(_:)\/title","value":"paymentCardTextFieldDidChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1init(configuration:theme:)\/title","value":"initWithConfiguration:theme:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1init(configuration:theme:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:theme:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/title","value":"STPCoreTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidEndEditingCVC(_:)\/title","value":"paymentCardTextFieldDidEndEditingCVC:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldDidEndEditingCVC(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingCVC:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldWillEndEditing(forReturn:)\/title","value":"paymentCardTextFieldWillEndEditingForReturn:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1paymentCardTextFieldWillEndEditing(forReturn:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditingForReturn:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:heightForFooterInSection:)\/title","value":"tableView:heightForFooterInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController~1tableView(_:heightForFooterInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForFooterInSection:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
