{"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/stripe\/stpapplepaypaymentoption"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpapplepaypaymentoption"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayPaymentOption"}],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"syntax":null,"type":"codeListing","code":["if paymentContext.selectedPaymentOption is STPApplePayPaymentOption {","\/\/ Don't ask the user for their card number; they want to pay with apple pay.","}"]}],"kind":"content"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"},"metadata":{"modules":[{"name":"Stripe"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPApplePayPaymentOption","kind":"identifier"}],"title":"STPApplePayPaymentOption","symbolKind":"class","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"STPApplePayPaymentOption","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPApplePayPaymentOption"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"An empty class representing that the user wishes to pay via Apple Pay. This can","type":"text"},{"type":"text","text":" "},{"text":"be checked on an ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":", e.g:","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/hash","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/image","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isReusable","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/label","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/templateImage"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isEqual(_:)"]}],"references":{"doc://com.stripe.stripe-ios/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/templateImage":{"kind":"symbol","navigatorTitle":[{"text":"templateImage","kind":"identifier"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption\/templateimage","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/templateImage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[{"text":"A small (32 x 20 points) logo image representing the payment method that can be","type":"text"},{"text":" ","type":"text"},{"text":"used as template for tinted icons.","type":"text"}],"title":"templateImage"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/hash":{"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/hash","url":"\/documentation\/stripe\/stpapplepaypaymentoption\/hash","role":"symbol","title":"hash","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/isEqual(_:)":{"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isEqual(_:)","url":"\/documentation\/stripe\/stpapplepaypaymentoption\/isequal(_:)","role":"symbol","title":"isEqual(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption":{"kind":"symbol","abstract":[{"type":"text","text":"This protocol represents a payment method that a user can select and use to"},{"type":"text","text":" "},{"type":"text","text":"pay."},{"type":"text","text":" "},{"type":"text","text":"The classes that conform to it and are supported by the UI:"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOption","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","url":"\/documentation\/stripe\/stppaymentoption","role":"symbol","title":"STPPaymentOption","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOption"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption\/init","type":"topic","title":"init","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/init"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/isReusable":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Describes whether this payment option may be used multiple times. If it is not reusable,"},{"type":"text","text":" "},{"type":"text","text":"the payment method must be discarded after use."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isReusable","role":"symbol","title":"isReusable","url":"\/documentation\/stripe\/stpapplepaypaymentoption\/isreusable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isReusable","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isReusable"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/image":{"kind":"symbol","navigatorTitle":[{"text":"image","kind":"identifier"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption\/image","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/image","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"abstract":[{"text":"A small (32 x 20 points) logo image representing the payment method. For","type":"text"},{"text":" ","type":"text"},{"text":"example, the Visa logo for a Visa card, or the Apple Pay logo.","type":"text"}],"title":"image"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption/label":{"kind":"symbol","navigatorTitle":[{"text":"label","kind":"identifier"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption\/label","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/label","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"label"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"text":"A string describing the payment method, such as “Apple Pay” or “Visa 4242”.","type":"text"}],"title":"label"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayPaymentOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPApplePayPaymentOption"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption","type":"topic","title":"STPApplePayPaymentOption","kind":"symbol","role":"symbol","abstract":[{"text":"An empty class representing that the user wishes to pay via Apple Pay. This can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"be checked on an "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":", e.g:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"STPApplePayPaymentOption","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPApplePayPaymentOption","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPApplePayPaymentOption"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/hash","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/image","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isReusable","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/label","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/templateImage"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/init","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption\/isEqual(_:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption"],"title":"Conforms To"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"STPApplePayPaymentOption","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1templateImage\/title","op":"replace","value":"templateImage"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1templateImage\/fragments","value":[{"text":"templateImage","kind":"identifier"}],"op":"replace"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1hash\/fragments","op":"replace"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/title","value":"STPPaymentOption"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentOption"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1isReusable\/title","value":"isReusable"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1isReusable\/fragments","value":[{"text":"isReusable","kind":"identifier"}],"op":"replace"},{"value":"image","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1image\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1image\/fragments","op":"replace","value":[{"kind":"identifier","text":"image"}]},{"op":"replace","value":"label","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1label\/title"},{"op":"replace","value":[{"text":"label","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption~1label\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/title","value":"STPApplePayPaymentOption"},{"value":[{"text":"STPApplePayPaymentOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/fragments"}]}]}
