{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate"},"variants":[{"paths":["\/documentation\/stripe\/stpapplepaycontextdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpapplepaycontextdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCompleteWith:error:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContextDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"_stpinternal_STPApplePayContextDelegateBase","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"STPApplePayContextDelegate","kind":"identifier"}],"title":"STPApplePayContextDelegate","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(pl)STPApplePayContextDelegate","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContextDelegate","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol"},"abstract":[{"type":"text","text":"Implement the required methods of this delegate to supply a PaymentIntent to STPApplePayContext and be notified of the completion of the Apple Pay payment."},{"type":"text","text":" "},{"type":"text","text":"You may also implement the optional delegate methods to handle shipping methods and shipping address changes e.g. to verify you can ship to the address, or update the payment amount."}],"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-ios/@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase":{"title":"_stpinternal_STPApplePayContextDelegateBase","identifier":"doc:\/\/com.stripe.stripe-ios\/@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContextDelegate/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)":{"title":"applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","navigatorTitle":[{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","text":"STPApplePayContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKPayment","text":"PKPayment"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay36STPIntentClientSecretCompletionBlocka","text":"STPIntentClientSecretCompletionBlock"},{"kind":"text","text":")"}],"url":"\/documentation\/stripe\/stpapplepaycontextdelegate\/applepaycontext(_:didcreatepaymentmethod:paymentinformation:completion:)","required":true,"abstract":[{"type":"text","text":"Called after the customer has authorized Apple Pay.  Implement this method to call the completion block with the client secret of a PaymentIntent or SetupIntent."}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","abstract":[],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContextDelegate/applePayContext(_:didCompleteWith:error:)":{"title":"applePayContext(_:didCompleteWith:error:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCompleteWith:error:)","required":true,"role":"symbol","abstract":[{"text":"Called after the Apple Pay sheet is dismissed with the result of the payment.","type":"text"},{"text":" ","type":"text"},{"text":"Your implementation could stop a spinner and display a receipt view or error to the customer, for example.","type":"text"}],"type":"topic","url":"\/documentation\/stripe\/stpapplepaycontextdelegate\/applepaycontext(_:didcompletewith:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPApplePayContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"applePayContext:didCompleteWithStatus:error:","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayContextDelegate":{"navigatorTitle":[{"kind":"identifier","text":"STPApplePayContextDelegate"}],"abstract":[{"type":"text","text":"Implement the required methods of this delegate to supply a PaymentIntent to STPApplePayContext and be notified of the completion of the Apple Pay payment."},{"type":"text","text":" "},{"type":"text","text":"You may also implement the optional delegate methods to handle shipping methods and shipping address changes e.g. to verify you can ship to the address, or update the payment amount."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate","title":"STPApplePayContextDelegate","type":"topic","url":"\/documentation\/stripe\/stpapplepaycontextdelegate","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayContextDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"STPApplePayContextDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPApplePayContextDelegate"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPApplePayContextDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCompleteWith:error:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayContextDelegate\/applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-ios\/@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContextDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"_stpinternal_STPApplePayContextDelegateBase","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(pl)_stpinternal_STPApplePayContextDelegateBase"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"value":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate~1applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applePayContext:didCreatePaymentMethod:paymentInformation:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate~1applePayContext(_:didCreatePaymentMethod:paymentInformation:completion:)\/fragments"},{"value":"applePayContext:didCompleteWithStatus:error:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate~1applePayContext(_:didCompleteWith:error:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"applePayContext:didCompleteWithStatus:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate~1applePayContext(_:didCompleteWith:error:)\/fragments"},{"value":"STPApplePayContextDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/title"},{"value":[{"kind":"identifier","text":"STPApplePayContextDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/fragments"},{"value":[{"text":"STPApplePayContextDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayContextDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}