{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"title":"Inherits From"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate"]},{"paths":["\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"An ","type":"text"},{"code":"STPBankSelectionViewControllerDelegate","type":"codeVoice"},{"type":"text","text":" is notified when a user selects a bank."}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate\/bankSelectionViewController(_:didCreatePaymentMethodParams:)"]}],"metadata":{"role":"symbol","symbolKind":"protocol","externalID":"c:@M@Stripe@objc(pl)STPBankSelectionViewControllerDelegate","roleHeading":"Protocol","title":"STPBankSelectionViewControllerDelegate","modules":[{"name":"Stripe"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPBankSelectionViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewControllerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPBankSelectionViewControllerDelegate","kind":"identifier"}],"title":"STPBankSelectionViewControllerDelegate","type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"STPBankSelectionViewControllerDelegate","type":"codeVoice"},{"text":" is notified when a user selects a bank.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewControllerDelegate/bankSelectionViewController(_:didCreatePaymentMethodParams:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate\/bankSelectionViewController(_:didCreatePaymentMethodParams:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bankSelectionViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPBankSelectionViewController","text":"STPBankSelectionViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCreatePaymentMethodParams"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier","text":"STPPaymentMethodParams"},{"text":")","kind":"text"}],"title":"bankSelectionViewController(_:didCreatePaymentMethodParams:)","type":"topic","abstract":[{"text":"This is called when the user selects a bank.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You can use the returned PaymentMethodParams to confirm a PaymentIntent, or inspect"},{"type":"text","text":" "},{"type":"text","text":"it to obtain details about the selected bank."},{"text":" ","type":"text"},{"text":"Once you’re done, you’ll want to dismiss (or pop) the view controller.","type":"text"}],"kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate\/bankselectionviewcontroller(_:didcreatepaymentmethodparams:)","navigatorTitle":[{"text":"bankSelectionViewController:didCreatePaymentMethodParams:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPBankSelectionViewControllerDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"STPBankSelectionViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate\/bankSelectionViewController(_:didCreatePaymentMethodParams:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"STPBankSelectionViewControllerDelegate","kind":"identifier"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]},"op":"replace"},{"value":"STPBankSelectionViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate\/title"},{"value":[{"text":"STPBankSelectionViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate\/fragments","op":"replace"},{"value":"bankSelectionViewController:didCreatePaymentMethodParams:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate~1bankSelectionViewController(_:didCreatePaymentMethodParams:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate~1bankSelectionViewController(_:didCreatePaymentMethodParams:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bankSelectionViewController:didCreatePaymentMethodParams:"}]}]}]}
