{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBackendAPIAdapter"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"STPCustomerContext.h"},{"text":" ","type":"text"},{"type":"text","text":"If you would prefer retrieving and updating your Stripe customer object via"},{"type":"text","text":" "},{"type":"text","text":"your own backend instead of using "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":", you should make your","type":"text"},{"type":"text","text":" "},{"type":"text","text":"application’s API client conform to this interface."}]}]}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"code":"STPPaymentContext","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"text":")","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"text":" ","type":"text"},{"text":"Typically, you will not need to implement this protocol yourself. You","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"should instead use "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which implements "},{"text":" ","type":"text"},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpbackendapiadapter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbackendapiadapter"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter"},"metadata":{"title":"STPBackendAPIAdapter","role":"symbol","symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBackendAPIAdapter"}],"externalID":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/attachPaymentMethod(toCustomer:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/detachPaymentMethod(fromCustomer:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/listPaymentMethodsForCustomer(completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/retrieveCustomer(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/updateCustomer(withShippingAddress:completion:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/retrieveCustomer(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveCustomer"},{"kind":"text","text":"("},{"text":"STPCustomerCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments26STPCustomerCompletionBlocka"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Retrieve the customer to be displayed inside a payment context.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you are not using STPCustomerContext:"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your currently"},{"type":"text","text":" "},{"type":"text","text":"logged-in user ( https:\/\/stripe.com\/docs\/api#retrieve_customer ), and return"},{"text":" ","type":"text"},{"text":"the raw JSON response from the Stripe API. Back in your iOS app, after you’ve","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"called this API, deserialize your API response into an "},{"type":"codeVoice","code":"STPCustomer"},{"text":" object","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(you can use the "},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"text":" class to do this).","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"retrieveCustomer:","kind":"identifier"}],"title":"retrieveCustomer(_:)","required":true,"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/retrieveCustomer(_:)","kind":"symbol","url":"\/documentation\/stripe\/stpbackendapiadapter\/retrievecustomer(_:)"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"abstract":[{"text":"A “bridge” from our pre-built UI (","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"text":" ","type":"text"},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"text":" ","type":"text"},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":", which implements ","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"title":"STPBackendAPIAdapter","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPBackendAPIAdapter","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol","url":"\/documentation\/stripe\/stpbackendapiadapter"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/attachPaymentMethod(toCustomer:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"attachPaymentMethod","kind":"identifier"},{"kind":"text","text":"("},{"text":"toCustomer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock"},{"text":"?)","kind":"text"}],"type":"topic","abstract":[{"text":"Adds a Payment Method to a customer.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If you are implementing your own "},{"text":":","type":"text"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"text":" ","type":"text"},{"type":"text","text":"Then, call the Attach method on the Payment Method with that customer’s ID"},{"type":"text","text":" "},{"type":"text","text":"( https:\/\/stripe.com\/docs\/api\/payment_methods\/attach ). If this API call succeeds,"},{"type":"text","text":" "},{"text":"call ","type":"text"},{"type":"codeVoice","code":"completion(nil)"},{"text":". Otherwise, call ","type":"text"},{"code":"completion(error)","type":"codeVoice"},{"type":"text","text":" with the error that"},{"type":"text","text":" "},{"text":"occurred.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"attachPaymentMethodToCustomer:completion:"}],"title":"attachPaymentMethod(toCustomer:completion:)","required":true,"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/attachPaymentMethod(toCustomer:completion:)","kind":"symbol","url":"\/documentation\/stripe\/stpbackendapiadapter\/attachpaymentmethod(tocustomer:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/detachPaymentMethod(fromCustomer:completion:)":{"kind":"symbol","url":"\/documentation\/stripe\/stpbackendapiadapter\/detachpaymentmethod(fromcustomer:completion:)","abstract":[{"type":"text","text":"Deletes the given Payment Method from the customer."},{"text":" ","type":"text"},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"text":"Call the Detach method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/detach )","type":"text"},{"type":"text","text":" "},{"text":"on the Payment Method. If this API call succeeds, call ","type":"text"},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"type":"topic","title":"detachPaymentMethod(fromCustomer:completion:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/detachPaymentMethod(fromCustomer:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachPaymentMethod"},{"text":"(","kind":"text"},{"text":"fromCustomer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"detachPaymentMethodFromCustomer:completion:","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"type":"topic","title":"STPCustomerContext","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerContext","kind":"identifier"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"text":" ","type":"text"},{"text":"be sure to either create a new instance of ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"text":" or clear the current","type":"text"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"text":"new ephemeral key for the Customer object associated with the new user.","type":"text"}],"navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcustomercontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/updateCustomer(withShippingAddress:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/updateCustomer(withShippingAddress:completion:)","title":"updateCustomer(withShippingAddress:completion:)","url":"\/documentation\/stripe\/stpbackendapiadapter\/updatecustomer(withshippingaddress:completion:)","abstract":[{"type":"text","text":"Sets the given shipping address on the customer."},{"text":" ","type":"text"},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"text":" ","type":"text"},{"type":"text","text":"Then, call the Customer Update method ( https:\/\/stripe.com\/docs\/api#update_customer )"},{"text":" ","type":"text"},{"text":"specifying shipping to be the given shipping address. If this API call succeeds,","type":"text"},{"type":"text","text":" "},{"text":"call ","type":"text"},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withShippingAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"updateCustomerWithShippingAddress:completion:","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/listPaymentMethodsForCustomer(completion:)":{"title":"listPaymentMethodsForCustomer(completion:)","kind":"symbol","abstract":[{"text":"Retrieves a list of Payment Methods attached to a customer.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"text":":","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Call the list method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/list )"},{"type":"text","text":" "},{"text":"with the Stripe customer. If this API call succeeds, call ","type":"text"},{"type":"codeVoice","code":"completion(paymentMethods)"},{"text":" ","type":"text"},{"type":"text","text":"with the list of PaymentMethods. Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error"},{"type":"text","text":" "},{"text":"that occurred.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/listPaymentMethodsForCustomer(completion:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPaymentMethodsForCustomer"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments32STPPaymentMethodsCompletionBlocka","text":"STPPaymentMethodsCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/stripe\/stpbackendapiadapter\/listpaymentmethodsforcustomer(completion:)","navigatorTitle":[{"text":"listPaymentMethodsForCustomerWithCompletion:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"STPBackendAPIAdapter","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/attachPaymentMethod(toCustomer:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/detachPaymentMethod(fromCustomer:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/listPaymentMethodsForCustomer(completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/retrieveCustomer(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/updateCustomer(withShippingAddress:completion:)"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext"],"type":"conformingTypes","title":"Conforming Types"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBackendAPIAdapter"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"retrieveCustomer:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1retrieveCustomer(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1retrieveCustomer(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"retrieveCustomer:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title","op":"replace","value":"STPBackendAPIAdapter"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1attachPaymentMethod(toCustomer:completion:)\/title","value":"attachPaymentMethodToCustomer:completion:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1attachPaymentMethod(toCustomer:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"attachPaymentMethodToCustomer:completion:","kind":"identifier"}]},{"value":"detachPaymentMethodFromCustomer:completion:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1detachPaymentMethod(fromCustomer:completion:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1detachPaymentMethod(fromCustomer:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"detachPaymentMethodFromCustomer:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"text":"STPCustomerContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1updateCustomer(withShippingAddress:completion:)\/title","op":"replace","value":"updateCustomerWithShippingAddress:completion:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1updateCustomer(withShippingAddress:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"updateCustomerWithShippingAddress:completion:","kind":"identifier"}]},{"op":"replace","value":"listPaymentMethodsForCustomerWithCompletion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1listPaymentMethodsForCustomer(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1listPaymentMethodsForCustomer(completion:)\/fragments"}]}]}
