{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPBillingAddressFields","kind":"identifier"}]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"the user may not be asked for one regardless of this setting."}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/SY"],"kind":"relationships","type":"conformsTo"}],"abstract":[{"type":"text","text":"What set of billing address information you need to collect from your user."}],"variants":[{"paths":["\/documentation\/stripe\/stpbillingaddressfields"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbillingaddressfields"]}],"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@Stripe@E@STPBillingAddressFields","navigatorTitle":[{"text":"STPBillingAddressFields","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"Stripe"}],"title":"STPBillingAddressFields","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBillingAddressFields"}],"role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/full","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/name","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/none","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/postalCode","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/zip"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/Equatable-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/CustomStringConvertible-Implementations","url":"\/documentation\/stripe\/stpbillingaddressfields\/customstringconvertible-implementations","abstract":[],"type":"topic","title":"CustomStringConvertible Implementations","kind":"article","role":"collectionGroup"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/name":{"url":"\/documentation\/stripe\/stpbillingaddressfields\/name","role":"symbol","navigatorTitle":[{"text":"STPBillingAddressFieldsName","kind":"identifier"}],"title":"STPBillingAddressFields.name","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/name","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Just request the user’s billing name"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/SQ":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/Equatable-Implementations","url":"\/documentation\/stripe\/stpbillingaddressfields\/equatable-implementations","abstract":[],"type":"topic","title":"Equatable Implementations","kind":"article","role":"collectionGroup"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/full":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"full"}],"navigatorTitle":[{"text":"STPBillingAddressFieldsFull","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/full","url":"\/documentation\/stripe\/stpbillingaddressfields\/full","abstract":[{"type":"text","text":"Request the user’s full billing address"}],"type":"topic","title":"STPBillingAddressFields.full","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/postalCode":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalCode"}],"navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsPostalCode"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/postalCode","url":"\/documentation\/stripe\/stpbillingaddressfields\/postalcode","abstract":[{"type":"text","text":"Just request the user’s billing postal code"}],"type":"topic","title":"STPBillingAddressFields.postalCode","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-ios/SY":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/RawRepresentable-Implementations","url":"\/documentation\/stripe\/stpbillingaddressfields\/rawrepresentable-implementations","abstract":[],"type":"topic","title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","type":"topic","kind":"symbol","url":"\/documentation\/stripe\/stpbillingaddressfields\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/init(rawValue:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/zip":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"zip"}],"navigatorTitle":[{"text":"STPBillingAddressFieldsZip","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/zip","url":"\/documentation\/stripe\/stpbillingaddressfields\/zip","abstract":[{"type":"text","text":"Just request the user’s billing ZIP (synonym for STPBillingAddressFieldsZip)"}],"type":"topic","deprecated":false,"title":"STPBillingAddressFields.zip","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields/none":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"STPBillingAddressFieldsNone"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/none","url":"\/documentation\/stripe\/stpbillingaddressfields\/none","abstract":[{"type":"text","text":"No billing address information"}],"type":"topic","title":"STPBillingAddressFields.none","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields":{"url":"\/documentation\/stripe\/stpbillingaddressfields","role":"symbol","navigatorTitle":[{"text":"STPBillingAddressFields","kind":"identifier"}],"title":"STPBillingAddressFields","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBillingAddressFields","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"What set of billing address information you need to collect from your user."}],"kind":"symbol"},"doc://com.stripe.stripe-ios/SH":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPBillingAddressFields"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPBillingAddressFields","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"STPBillingAddressFields","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/full","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/name","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/none","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/postalCode","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields\/zip"],"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPBillingAddressFields","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"STPBillingAddressFieldsName","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1name\/title"},{"value":[{"kind":"identifier","text":"STPBillingAddressFieldsName"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1name\/fragments","op":"replace"},{"value":"STPBillingAddressFieldsFull","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1full\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1full\/fragments","value":[{"text":"STPBillingAddressFieldsFull","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPBillingAddressFieldsPostalCode","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1postalCode\/title"},{"op":"replace","value":[{"text":"STPBillingAddressFieldsPostalCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1postalCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1zip\/title","value":"STPBillingAddressFieldsZip"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1zip\/fragments","value":[{"text":"STPBillingAddressFieldsZip","kind":"identifier"}]},{"value":"STPBillingAddressFieldsNone","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1none\/title","op":"replace"},{"op":"replace","value":[{"text":"STPBillingAddressFieldsNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields~1none\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/title","value":"STPBillingAddressFields","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/fragments","value":[{"kind":"identifier","text":"STPBillingAddressFields"}],"op":"replace"}]}]}
