{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankSelectionMethod"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpbankselectionmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpbankselectionmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The payment methods supported by STPBankSelectionViewController."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankSelectionMethod"}],"title":"STPBankSelectionMethod","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@Stripe@E@STPBankSelectionMethod","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionMethod"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/FPX","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/Equatable-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod":{"role":"symbol","title":"STPBankSelectionMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankSelectionMethod"}],"abstract":[{"type":"text","text":"The payment methods supported by STPBankSelectionViewController."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionMethod"}],"url":"\/documentation\/stripe\/stpbankselectionmethod"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpbankselectionmethod\/customstringconvertible-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-ios\/SY"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod/unknown":{"role":"symbol","title":"STPBankSelectionMethod.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"An unknown payment method"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionMethodUnknown"}],"url":"\/documentation\/stripe\/stpbankselectionmethod\/unknown"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpbankselectionmethod\/rawrepresentable-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod/FPX":{"role":"symbol","title":"STPBankSelectionMethod.FPX","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FPX"}],"abstract":[{"type":"text","text":"FPX (Malaysia)"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/FPX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionMethodFPX"}],"url":"\/documentation\/stripe\/stpbankselectionmethod\/fpx"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpbankselectionmethod\/equatable-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stpbankselectionmethod\/init(rawvalue:)"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPBankSelectionMethod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionMethod"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPBankSelectionMethod"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/FPX","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankSelectionMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/title","value":"STPBankSelectionMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod~1unknown\/title","value":"STPBankSelectionMethodUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod~1unknown\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionMethodUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod~1FPX\/title","value":"STPBankSelectionMethodFPX"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod~1FPX\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionMethodFPX"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
