{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerContext"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcustomercontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpcustomercontext"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" retrieves and updates a Stripe customer and their attached"},{"type":"text","text":" "},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"type":"text","text":" "},{"type":"text","text":"instance’s cache. On your backend, be sure to create and return a"},{"type":"text","text":" "},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerContext"}],"title":"STPCustomerContext","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Stripe@objc(cs)STPCustomerContext","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPCustomerContext"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:apiClient:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/includeApplePayPaymentMethods"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/attachPaymentMethod(toCustomer:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/attachPaymentMethodToCustomer(paymentMethodId:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/clearCache()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethod(fromCustomer:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethodFromCustomer(paymentMethodId:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/listPaymentMethodsForCustomer(completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/retrieveCustomer(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/updateCustomer(withShippingAddress:completion:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"role":"symbol","title":"STPBackendAPIAdapter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBackendAPIAdapter"}],"abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which implements "},{"type":"text","text":" "},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"url":"\/documentation\/stripe\/stpbackendapiadapter"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/clearCache()":{"role":"symbol","title":"clearCache()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearCache"},{"kind":"text","text":"()"}],"abstract":[{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" will cache its customer object and associated payment methods"},{"type":"text","text":" "},{"type":"text","text":"for up to 60 seconds. If your current user logs out of your app and a new user logs"},{"type":"text","text":" "},{"type":"text","text":"in, be sure to either call this method or create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"On your backend, be sure to create and return a new ephemeral key for the"},{"type":"text","text":" "},{"type":"text","text":"customer object associated with the new user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/clearCache()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearCache"}],"url":"\/documentation\/stripe\/stpcustomercontext\/clearcache()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/init(keyProvider:)":{"role":"symbol","title":"init(keyProvider:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" with the specified key provider."},{"type":"text","text":" "},{"type":"text","text":"Upon initialization, a CustomerContext will fetch a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend and use it to prefetch the customer object specified in the key."},{"type":"text","text":" "},{"type":"text","text":"Subsequent customer and payment method retrievals (e.g. by "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"will return the prefetched customer \/ attached payment methods immediately if"},{"type":"text","text":" "},{"type":"text","text":"its age does not exceed 60 seconds."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithKeyProvider:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/init(keyprovider:)"},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/attachPaymentMethodToCustomer(paymentMethodId:completion:)":{"role":"symbol","title":"attachPaymentMethodToCustomer(paymentMethodId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachPaymentMethodToCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethodId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"A convenience method for attaching the PaymentMethod to the current Customer"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/attachPaymentMethodToCustomer(paymentMethodId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"attachPaymentMethodToCustomerWithPaymentMethodId:completion:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/attachpaymentmethodtocustomer(paymentmethodid:completion:)"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/detachPaymentMethod(fromCustomer:completion:)":{"role":"symbol","title":"detachPaymentMethod(fromCustomer:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromCustomer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Deletes the given Payment Method from the customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"Call the Detach method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/detach )"},{"type":"text","text":" "},{"type":"text","text":"on the Payment Method. If this API call succeeds, call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethod(fromCustomer:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detachPaymentMethodFromCustomer:completion:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/detachpaymentmethod(fromcustomer:completion:)"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/init(keyProvider:apiClient:)":{"role":"symbol","title":"init(keyProvider:apiClient:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"apiClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" with the specified key provider."},{"type":"text","text":" "},{"type":"text","text":"Upon initialization, a CustomerContext will fetch a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend and use it to prefetch the customer object specified in the key."},{"type":"text","text":" "},{"type":"text","text":"Subsequent customer and payment method retrievals (e.g. by "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"will return the prefetched customer \/ attached payment methods immediately if"},{"type":"text","text":" "},{"type":"text","text":"its age does not exceed 60 seconds."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:apiClient:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithKeyProvider:apiClient:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/init(keyprovider:apiclient:)"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/includeApplePayPaymentMethods":{"role":"symbol","title":"includeApplePayPaymentMethods","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"includeApplePayPaymentMethods"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"By default, "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" will filter Apple Pay when it retrieves"},{"type":"text","text":" "},{"type":"text","text":"Payment Methods. Apple Pay payment methods should generally not be re-used and"},{"type":"text","text":" "},{"type":"text","text":"shouldn’t be offered to customers as a new payment method (Apple Pay payment"},{"type":"text","text":" "},{"type":"text","text":"methods may only be re-used for subscriptions)."},{"type":"text","text":" "},{"type":"text","text":"If you are using "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to back your own UI and would like to"},{"type":"text","text":" "},{"type":"text","text":"disable Apple Pay filtering, set this property to YES."},{"type":"text","text":" "},{"type":"text","text":"Note: If you are using "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", you should not change this property."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/includeApplePayPaymentMethods","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"includeApplePayPaymentMethods"}],"url":"\/documentation\/stripe\/stpcustomercontext\/includeapplepaypaymentmethods"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"role":"symbol","title":"STPCustomerContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" retrieves and updates a Stripe customer and their attached"},{"type":"text","text":" "},{"type":"text","text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific"},{"type":"text","text":" "},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"type":"text","text":" "},{"type":"text","text":"instance’s cache. On your backend, be sure to create and return a"},{"type":"text","text":" "},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomerContext"}],"url":"\/documentation\/stripe\/stpcustomercontext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/detachPaymentMethodFromCustomer(paymentMethodId:completion:)":{"role":"symbol","title":"detachPaymentMethodFromCustomer(paymentMethodId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachPaymentMethodFromCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentMethodId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"A convenience method for detaching the PaymentMethod to the current Customer"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethodFromCustomer(paymentMethodId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/detachpaymentmethodfromcustomer(paymentmethodid:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/listPaymentMethodsForCustomer(completion:)":{"role":"symbol","title":"listPaymentMethodsForCustomer(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPaymentMethodsForCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodsCompletionBlock","preciseIdentifier":"s:14StripePayments32STPPaymentMethodsCompletionBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Retrieves a list of Payment Methods attached to a customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"Call the list method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/list )"},{"type":"text","text":" "},{"type":"text","text":"with the Stripe customer. If this API call succeeds, call "},{"type":"codeVoice","code":"completion(paymentMethods)"},{"type":"text","text":" "},{"type":"text","text":"with the list of PaymentMethods. Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error"},{"type":"text","text":" "},{"type":"text","text":"that occurred."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/listPaymentMethodsForCustomer(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/listpaymentmethodsforcustomer(completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/retrieveCustomer(_:)":{"role":"symbol","title":"retrieveCustomer(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveCustomer"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPCustomerCompletionBlock","preciseIdentifier":"s:14StripePayments26STPCustomerCompletionBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Retrieve the customer to be displayed inside a payment context."},{"type":"text","text":" "},{"type":"text","text":"If you are not using STPCustomerContext:"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your currently"},{"type":"text","text":" "},{"type":"text","text":"logged-in user ( https:\/\/stripe.com\/docs\/api#retrieve_customer ), and return"},{"type":"text","text":" "},{"type":"text","text":"the raw JSON response from the Stripe API. Back in your iOS app, after you’ve"},{"type":"text","text":" "},{"type":"text","text":"called this API, deserialize your API response into an "},{"type":"codeVoice","code":"STPCustomer"},{"type":"text","text":" object"},{"type":"text","text":" "},{"type":"text","text":"(you can use the "},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"type":"text","text":" class to do this)."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/retrieveCustomer(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"retrieveCustomer:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/retrievecustomer(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/attachPaymentMethod(toCustomer:completion:)":{"role":"symbol","title":"attachPaymentMethod(toCustomer:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toCustomer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Adds a Payment Method to a customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"type":"text","text":" "},{"type":"text","text":"Then, call the Attach method on the Payment Method with that customer’s ID"},{"type":"text","text":" "},{"type":"text","text":"( https:\/\/stripe.com\/docs\/api\/payment_methods\/attach ). If this API call succeeds,"},{"type":"text","text":" "},{"type":"text","text":"call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that"},{"type":"text","text":" "},{"type":"text","text":"occurred."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/attachPaymentMethod(toCustomer:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"attachPaymentMethodToCustomer:completion:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/attachpaymentmethod(tocustomer:completion:)"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext/updateCustomer(withShippingAddress:completion:)":{"role":"symbol","title":"updateCustomer(withShippingAddress:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withShippingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Sets the given shipping address on the customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"type":"text","text":" "},{"type":"text","text":"Then, call the Customer Update method ( https:\/\/stripe.com\/docs\/api#update_customer )"},{"type":"text","text":" "},{"type":"text","text":"specifying shipping to be the given shipping address. If this API call succeeds,"},{"type":"text","text":" "},{"type":"text","text":"call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/updateCustomer(withShippingAddress:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateCustomerWithShippingAddress:completion:"}],"url":"\/documentation\/stripe\/stpcustomercontext\/updatecustomer(withshippingaddress:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPCustomerContext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPCustomerContext"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/includeApplePayPaymentMethods"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/attachPaymentMethod(toCustomer:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/attachPaymentMethodToCustomer(paymentMethodId:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/clearCache()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethod(fromCustomer:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/detachPaymentMethodFromCustomer(paymentMethodId:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/init(keyProvider:apiClient:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/listPaymentMethodsForCustomer(completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/retrieveCustomer(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext\/updateCustomer(withShippingAddress:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerContext"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title","value":"STPBackendAPIAdapter"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1clearCache()\/title","value":"clearCache"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1clearCache()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1init(keyProvider:)\/title","value":"initWithKeyProvider:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1init(keyProvider:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyProvider:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1attachPaymentMethodToCustomer(paymentMethodId:completion:)\/title","value":"attachPaymentMethodToCustomerWithPaymentMethodId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1attachPaymentMethodToCustomer(paymentMethodId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"attachPaymentMethodToCustomerWithPaymentMethodId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1detachPaymentMethod(fromCustomer:completion:)\/title","value":"detachPaymentMethodFromCustomer:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1detachPaymentMethod(fromCustomer:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detachPaymentMethodFromCustomer:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1init(keyProvider:apiClient:)\/title","value":"initWithKeyProvider:apiClient:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1init(keyProvider:apiClient:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyProvider:apiClient:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1includeApplePayPaymentMethods\/title","value":"includeApplePayPaymentMethods"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1includeApplePayPaymentMethods\/fragments","value":[{"kind":"identifier","text":"includeApplePayPaymentMethods"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title","value":"STPCustomerContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"kind":"identifier","text":"STPCustomerContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1detachPaymentMethodFromCustomer(paymentMethodId:completion:)\/title","value":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1detachPaymentMethodFromCustomer(paymentMethodId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detachPaymentMethodFromCustomerWithPaymentMethodId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1listPaymentMethodsForCustomer(completion:)\/title","value":"listPaymentMethodsForCustomerWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1listPaymentMethodsForCustomer(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1retrieveCustomer(_:)\/title","value":"retrieveCustomer:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1retrieveCustomer(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveCustomer:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1attachPaymentMethod(toCustomer:completion:)\/title","value":"attachPaymentMethodToCustomer:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1attachPaymentMethod(toCustomer:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"attachPaymentMethodToCustomer:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1updateCustomer(withShippingAddress:completion:)\/title","value":"updateCustomerWithShippingAddress:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext~1updateCustomer(withShippingAddress:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCustomerWithShippingAddress:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
