{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(coder:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(nibName:bundle:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(theme:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/preferredStatusBarStyle"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewDidLoad()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewWillAppear(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewWillDisappear(_:)"],"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCoreViewController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcoreviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpcoreviewcontroller"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"abstract":[{"text":"This is the base class for all Stripe view controllers. It is intended for use","type":"text"},{"type":"text","text":" "},{"type":"text","text":"only by Stripe classes, you should not subclass it yourself in your app."},{"text":" ","type":"text"},{"text":"It theming, back\/cancel button management, and other shared logic for","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Stripe view controllers."}],"metadata":{"title":"STPCoreViewController","navigatorTitle":[{"text":"STPCoreViewController","kind":"identifier"}],"modules":[{"name":"Stripe"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCoreViewController"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@Stripe@objc(cs)STPCoreViewController"},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","role":"symbol","abstract":[{"text":"This is the base class for all Stripe scroll view controllers. It is intended","type":"text"},{"text":" ","type":"text"},{"text":"for use only by Stripe classes, you should not subclass it yourself in your app.","type":"text"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCoreScrollViewController","kind":"identifier"}],"navigatorTitle":[{"text":"STPCoreScrollViewController","kind":"identifier"}],"kind":"symbol","title":"STPCoreScrollViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/viewWillDisappear(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcoreviewcontroller\/viewwilldisappear(_:)","role":"symbol","title":"viewWillDisappear(_:)","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewWillDisappear(_:)"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-ios/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://com.stripe.stripe-ios/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-ios/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"title":"STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","abstract":[{"text":"This view controller presents a list of payment method options to the user,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"text":" ","type":"text"},{"text":"It must be displayed inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"text":", so you can either","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"as the ","type":"text"},{"code":"rootViewController","type":"codeVoice"},{"type":"text","text":" and then present the "},{"code":"UINavigationController","type":"codeVoice"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"text":"’s stack. You can also have ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"code":"pushPaymentOptionsViewController","type":"codeVoice"},{"text":" on it.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"},"doc://com.stripe.stripe-ios/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/init()":{"title":"init()","url":"\/documentation\/stripe\/stpcoreviewcontroller\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"text":"A convenience initializer; equivalent to calling ","type":"text"},{"type":"codeVoice","code":"init(theme: STPTheme.defaultTheme)"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init()"},"doc://com.stripe.stripe-ios/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/preferredStatusBarStyle":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preferredStatusBarStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIStatusBarStyle","preciseIdentifier":"c:@E@UIStatusBarStyle","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/preferredStatusBarStyle","title":"preferredStatusBarStyle","kind":"symbol","url":"\/documentation\/stripe\/stpcoreviewcontroller\/preferredstatusbarstyle","navigatorTitle":[{"text":"preferredStatusBarStyle","kind":"identifier"}],"abstract":[{"text":":nodoc:","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-ios/objc(cs)UIViewController":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://com.stripe.stripe-ios/SQ":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/viewWillAppear(_:)":{"title":"viewWillAppear(_:)","url":"\/documentation\/stripe\/stpcoreviewcontroller\/viewwillappear(_:)","abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewWillAppear(_:)","kind":"symbol"},"doc://com.stripe.stripe-ios/SH":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-ios/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-ios/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.stripe.stripe-ios/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/init(coder:)":{"url":"\/documentation\/stripe\/stpcoreviewcontroller\/init(coder:)","abstract":[{"text":"Passes through to the default UIViewController behavior for this initializer,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and then also sets the default theme as in "},{"type":"codeVoice","code":"init"}],"kind":"symbol","type":"topic","title":"init(coder:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/init(theme:)":{"url":"\/documentation\/stripe\/stpcoreviewcontroller\/init(theme:)","role":"symbol","navigatorTitle":[{"text":"initWithTheme:","kind":"identifier"}],"title":"init(theme:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(theme:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":"?)"}],"type":"topic","abstract":[{"type":"text","text":"Initializes a new view controller with the specified theme"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/init(nibName:bundle:)":{"role":"symbol","abstract":[{"text":"Passes through to the default UIViewController behavior for this initializer,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and then also sets the default theme as in "},{"code":"init","type":"codeVoice"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"nibName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"bundle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle"},{"text":"?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(nibName:bundle:)","url":"\/documentation\/stripe\/stpcoreviewcontroller\/init(nibname:bundle:)","title":"init(nibName:bundle:)"},"doc://com.stripe.stripe-ios/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController":{"url":"\/documentation\/stripe\/stpcoreviewcontroller","abstract":[{"type":"text","text":"This is the base class for all Stripe view controllers. It is intended for use"},{"type":"text","text":" "},{"text":"only by Stripe classes, you should not subclass it yourself in your app.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It theming, back\/cancel button management, and other shared logic for"},{"text":" ","type":"text"},{"type":"text","text":"Stripe view controllers."}],"kind":"symbol","type":"topic","title":"STPCoreViewController","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreViewController"}],"navigatorTitle":[{"text":"STPCoreViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController/viewDidLoad()":{"abstract":[{"text":":nodoc:","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewDidLoad()","role":"symbol","title":"viewDidLoad()","url":"\/documentation\/stripe\/stpcoreviewcontroller\/viewdidload()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPCoreViewController","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPCoreViewController"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPCoreViewController"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/preferredStatusBarStyle"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(coder:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(nibName:bundle:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/init(theme:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewDidLoad()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewWillAppear(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController\/viewWillDisappear(_:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"],"type":"inheritedBy","kind":"relationships","title":"Inherited By"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCoreViewController","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/title","op":"replace","value":"STPCoreScrollViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreScrollViewController"}]},{"value":"viewWillDisappear:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1viewWillDisappear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillDisappear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","op":"replace","value":"STPPaymentOptionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1preferredStatusBarStyle\/title","value":"preferredStatusBarStyle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1preferredStatusBarStyle\/fragments","op":"replace","value":[{"text":"preferredStatusBarStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"value":[{"kind":"text","text":"- "},{"text":"viewWillAppear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1viewWillAppear(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init(coder:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init(theme:)\/title","value":"initWithTheme:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithTheme:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init(theme:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init(nibName:bundle:)\/title","value":"initWithNibName:bundle:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1init(nibName:bundle:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/title","value":"STPCoreViewController"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCoreViewController"}]},{"value":"viewDidLoad","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1viewDidLoad()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController~1viewDidLoad()\/fragments","op":"replace"}]}]}
