{"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPCoreScrollViewController","modules":[{"name":"Stripe"}],"title":"STPCoreScrollViewController","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCoreScrollViewController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCoreScrollViewController"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/scrollView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/viewDidLayoutSubviews()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/viewDidLoad()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreScrollViewController"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripe\/stpcorescrollviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpcorescrollviewcontroller"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController"},"abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"references":{"doc://com.stripe.stripe-ios/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.stripe.stripe-ios/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/initWithTheme:":{"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/initwiththeme:","title":"initWithTheme:","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/initWithTheme:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTheme:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTheme:"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.stripe.stripe-ios/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/viewDidLayoutSubviews()":{"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/viewdidlayoutsubviews()","title":"viewDidLayoutSubviews()","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-ios/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","role":"symbol","abstract":[{"text":"This is the base class for all Stripe scroll view controllers. It is intended","type":"text"},{"text":" ","type":"text"},{"text":"for use only by Stripe classes, you should not subclass it yourself in your app.","type":"text"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCoreScrollViewController","kind":"identifier"}],"navigatorTitle":[{"text":"STPCoreScrollViewController","kind":"identifier"}],"kind":"symbol","title":"STPCoreScrollViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/initWithCoder:":{"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/initwithcoder:","title":"initWithCoder:","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/viewDidLoad()":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/viewDidLoad()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/viewdidload()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":":nodoc:"}],"title":"viewDidLoad()"},"doc://com.stripe.stripe-ios/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController":{"url":"\/documentation\/stripe\/stpcoreviewcontroller","abstract":[{"type":"text","text":"This is the base class for all Stripe view controllers. It is intended for use"},{"type":"text","text":" "},{"text":"only by Stripe classes, you should not subclass it yourself in your app.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It theming, back\/cancel button management, and other shared logic for"},{"text":" ","type":"text"},{"type":"text","text":"Stripe view controllers."}],"kind":"symbol","type":"topic","title":"STPCoreViewController","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreViewController"}],"navigatorTitle":[{"text":"STPCoreViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/scrollView":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/scrollView","role":"symbol","abstract":[{"text":"This returns the scroll view being managed by the view controller","type":"text"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/scrollview","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":": "},{"text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"scrollView"}],"kind":"symbol","title":"scrollView"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController":{"role":"symbol","title":"STPCoreTableViewController","type":"topic","kind":"symbol","url":"\/documentation\/stripe\/stpcoretableviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCoreTableViewController","kind":"identifier"}],"navigatorTitle":[{"text":"STPCoreTableViewController","kind":"identifier"}],"abstract":[{"text":"This is the base class for all Stripe scroll view controllers. It is intended","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"text":"It inherits from STPCoreScrollViewController and changes the type of the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"created scroll view to UITableView, as well as other shared table view logic."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/initWithNibName:bundle:":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/initWithNibName:bundle:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/initwithnibname:bundle:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"abstract":[],"title":"initWithNibName:bundle:"},"doc://com.stripe.stripe-ios/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPCoreScrollViewController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCoreScrollViewController"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPCoreScrollViewController"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/scrollView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/initWithCoder:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/initWithNibName:bundle:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/initWithTheme:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/viewDidLayoutSubviews()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/viewDidLoad()"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"],"type":"inheritedBy","title":"Inherited By"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"STPCoreScrollViewController","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController","text":"STPCoreViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCoreViewController"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLayoutSubviews","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/title","value":"STPCoreScrollViewController"},{"value":[{"text":"STPCoreScrollViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/fragments"},{"value":"viewDidLoad","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1viewDidLoad()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1viewDidLoad()\/fragments","op":"replace"},{"value":"STPCoreViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/fragments","op":"replace","value":[{"text":"STPCoreViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1scrollView\/title","value":"scrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1scrollView\/fragments","value":[{"kind":"identifier","text":"scrollView"}]},{"op":"replace","value":"STPCoreTableViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCoreTableViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
