{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcoretableviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpcoretableviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It inherits from STPCoreScrollViewController and changes the type of the"},{"type":"text","text":" "},{"type":"text","text":"created scroll view to UITableView, as well as other shared table view logic."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"}],"title":"STPCoreTableViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Stripe@objc(cs)STPCoreTableViewController","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPCoreTableViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView(_:heightForHeaderInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/viewWillAppear(_:)"]}],"references":{"doc://com.stripe.stripe-ios/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring"},"doc://com.stripe.stripe-ios/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer"},"doc://com.stripe.stripe-ios/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller\/initwithnibname:bundle:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller\/viewwillappear(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController":{"role":"symbol","title":"STPCoreScrollViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreScrollViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreScrollViewController"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller"},"doc://com.stripe.stripe-ios/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/initWithTheme:":{"role":"symbol","title":"initWithTheme:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTheme:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/initWithTheme:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTheme:"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller\/initwiththeme:"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewController":{"role":"symbol","title":"STPBankSelectionViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankSelectionViewController"}],"abstract":[{"type":"text","text":"This view controller displays a list of banks of the specified type, allowing the user to select one to pay from."},{"type":"text","text":" "},{"type":"text","text":"Once a bank is selected, it will return a PaymentMethodParams object, which you can use to confirm a PaymentIntent"},{"type":"text","text":" "},{"type":"text","text":"or inspect to obtain details about the selected bank."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewController"}],"url":"\/documentation\/stripe\/stpbankselectionviewcontroller"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/tableView(_:heightForHeaderInSection:)":{"role":"symbol","title":"tableView(_:heightForHeaderInSection:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForHeaderInSection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView(_:heightForHeaderInSection:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller\/tableview(_:heightforheaderinsection:)"},"doc://com.stripe.stripe-ios/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller\/initwithcoder:"},"doc://com.stripe.stripe-ios/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"role":"symbol","title":"STPAddCardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"}],"abstract":[{"type":"text","text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewController"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller"},"doc://com.stripe.stripe-ios/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/tableView":{"role":"symbol","title":"tableView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This points to the same object as "},{"type":"codeVoice","code":"STPCoreScrollViewController"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"scrollView"},{"type":"text","text":" "},{"type":"text","text":"property but with the type cast to "},{"type":"codeVoice","code":"UITableView"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tableView"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller\/tableview"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController":{"role":"symbol","title":"STPCoreTableViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It inherits from STPCoreScrollViewController and changes the type of the"},{"type":"text","text":" "},{"type":"text","text":"created scroll view to UITableView, as well as other shared table view logic."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreTableViewController"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"role":"symbol","title":"STPShippingAddressViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewController"}],"abstract":[{"type":"text","text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPCoreTableViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPCoreTableViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPCoreTableViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/initWithCoder:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/initWithNibName:bundle:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/initWithTheme:","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView(_:heightForHeaderInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/viewWillAppear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCoreScrollViewController","text":"STPCoreScrollViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/title","value":"STPCoreScrollViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreScrollViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/title","value":"STPBankSelectionViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1tableView(_:heightForHeaderInSection:)\/title","value":"tableView:heightForHeaderInSection:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1tableView(_:heightForHeaderInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1tableView\/title","value":"tableView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1tableView\/fragments","value":[{"kind":"identifier","text":"tableView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/title","value":"STPCoreTableViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreTableViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title","value":"STPShippingAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
