{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"role":"symbol","externalID":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"roleHeading":"Protocol","modules":[{"name":"Stripe"}],"title":"STPCustomerEphemeralKeyProvider","symbolKind":"protocol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider"},"abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"text":" ","type":"text"},{"text":"It provides a way for Stripe utility classes to request a new ephemeral key from","type":"text"},{"text":" ","type":"text"},{"text":"your backend, which it will use to retrieve and update Stripe API objects.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripe\/stpcustomerephemeralkeyprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpcustomerephemeralkeyprovider"]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider\/createCustomerKey(withAPIVersion:completion:)"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPEphemeralKeyProvider"],"title":"Inherited By","type":"inheritedBy","kind":"relationships"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPEphemeralKeyProvider":{"kind":"symbol","abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPEphemeralKeyProvider","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPEphemeralKeyProvider","url":"\/documentation\/stripe\/stpephemeralkeyprovider","role":"symbol","deprecated":false,"title":"STPEphemeralKeyProvider","type":"topic","navigatorTitle":[{"text":"STPEphemeralKeyProvider","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerEphemeralKeyProvider":{"role":"symbol","abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"text":" ","type":"text"},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"title":"STPCustomerEphemeralKeyProvider","navigatorTitle":[{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","url":"\/documentation\/stripe\/stpcustomerephemeralkeyprovider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerEphemeralKeyProvider/createCustomerKey(withAPIVersion:completion:)":{"abstract":[{"text":"Creates a new ephemeral key for retrieving and updating a Stripe customer.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"On your backend, you should create a new ephemeral key for the Stripe customer"},{"type":"text","text":" "},{"type":"text","text":"associated with your user, and return the raw JSON response from the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"For an example Ruby implementation of this API, refer to our example backend:"},{"type":"text","text":" "},{"text":"https:\/\/github.com\/stripe\/example-mobile-backend\/blob\/v18.1.0\/web.rb","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Back in your iOS app, once you have a response from this API, call the provided"},{"type":"text","text":" "},{"text":"completion block with the JSON response, or an error if one occurred.","type":"text"}],"role":"symbol","url":"\/documentation\/stripe\/stpcustomerephemeralkeyprovider\/createcustomerkey(withapiversion:completion:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createCustomerKey","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAPIVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments30STPJSONResponseCompletionBlocka","text":"STPJSONResponseCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"createCustomerKeyWithAPIVersion:completion:"}],"title":"createCustomerKey(withAPIVersion:completion:)","required":true,"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider\/createCustomerKey(withAPIVersion:completion:)"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPCustomerEphemeralKeyProvider"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider\/createCustomerKey(withAPIVersion:completion:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"]},{"title":"Inherited By","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPEphemeralKeyProvider"],"kind":"relationships","type":"inheritedBy"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPEphemeralKeyProvider","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPEphemeralKeyProvider\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPEphemeralKeyProvider\/fragments","value":[{"kind":"identifier","text":"STPEphemeralKeyProvider"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/title","value":"STPCustomerEphemeralKeyProvider","op":"replace"},{"op":"replace","value":[{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/fragments"},{"op":"replace","value":"createCustomerKeyWithAPIVersion:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider~1createCustomerKey(withAPIVersion:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider~1createCustomerKey(withAPIVersion:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createCustomerKeyWithAPIVersion:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
