{"abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"text":"It provides a way for Stripe utility classes to request a new ephemeral key from","type":"text"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"kind":"symbol","deprecationSummary":[{"inlineContent":[{"type":"text","text":"use `STPCustomerEphemeralKeyProvider` or `STPIssuingCardEphemeralKeyProvider` depending on the type of key that will be fetched."}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpephemeralkeyprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpephemeralkeyprovider"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPEphemeralKeyProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider","text":"STPCustomerEphemeralKeyProvider"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Depending on the type of key that will@objc  be fetched."}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPEphemeralKeyProvider","interfaceLanguage":"swift"},"metadata":{"title":"STPEphemeralKeyProvider","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPEphemeralKeyProvider","kind":"identifier"}],"modules":[{"name":"Stripe"}],"roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"text":"STPEphemeralKeyProvider","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(pl)STPEphemeralKeyProvider","platforms":[]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","type":"topic","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","title":"Stripe","abstract":[]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerEphemeralKeyProvider":{"abstract":[{"text":"You should make your application’s API client conform to this interface.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"title":"STPCustomerEphemeralKeyProvider","navigatorTitle":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"url":"\/documentation\/stripe\/stpcustomerephemeralkeyprovider"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPEphemeralKeyProvider":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPEphemeralKeyProvider","abstract":[{"text":"You should make your application’s API client conform to this interface.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"text":" ","type":"text"},{"text":"your backend, which it will use to retrieve and update Stripe API objects.","type":"text"}],"kind":"symbol","title":"STPEphemeralKeyProvider","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPEphemeralKeyProvider"}],"navigatorTitle":[{"text":"STPEphemeralKeyProvider","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/stripe\/stpephemeralkeyprovider","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"STPEphemeralKeyProvider","op":"replace","path":"\/metadata\/title"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPEphemeralKeyProvider"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"STPEphemeralKeyProvider"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":null,"op":"add"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"STPEphemeralKeyProvider","kind":"identifier"},{"text":" <","kind":"text"},{"text":"STPCustomerEphemeralKeyProvider","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/title","value":"STPCustomerEphemeralKeyProvider"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/navigatorTitle","value":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPEphemeralKeyProvider\/title","value":"STPEphemeralKeyProvider","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPEphemeralKeyProvider\/fragments","value":[{"text":"STPEphemeralKeyProvider","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPEphemeralKeyProvider\/navigatorTitle","value":[{"text":"STPEphemeralKeyProvider","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}