{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)UIViewController"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller"]}],"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(coder:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(nibName:bundle:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(requestConfiguration:delegate:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/delegate"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/viewDidLoad()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/canAddPaymentPass()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"title":"STPFakeAddPaymentPassViewController","modules":[{"name":"Stripe"}],"roleHeading":"Class","externalID":"c:@M@Stripe@objc(cs)STPFakeAddPaymentPassViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"symbolKind":"class"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"This class is a piece of fake UI that is intended to mimic "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":", and can be used to develop against the Stripe API in ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"testmode only"}]},{"text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to ","type":"text"},{"code":"STPFakeAddPaymentPassViewController","type":"codeVoice"},{"text":" in your app with ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","type":"topic","role":"collection","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/init(coder:)":{"title":"init(coder:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(coder:)","abstract":[{"type":"text","text":":nodoc:"}]},"doc://com.stripe.stripe-ios/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController":{"url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller","navigatorTitle":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"title":"STPFakeAddPaymentPassViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This class is a piece of fake UI that is intended to mimic "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":", and can be used to develop against the Stripe API in "},{"inlineContent":[{"type":"text","text":"testmode only"}],"type":"emphasis"},{"type":"text","text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to "},{"type":"codeVoice","code":"STPFakeAddPaymentPassViewController"},{"type":"text","text":" in your app with "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets .","type":"text"}]},"doc://com.stripe.stripe-ios/objc(cs)UIViewController":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/viewDidLoad()":{"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/viewdidload()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","title":"viewDidLoad()","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/viewDidLoad()","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/init(nibName:bundle:)":{"role":"symbol","navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"title":"init(nibName:bundle:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(nibName:bundle:)","abstract":[{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(nibname:bundle:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"nibName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.stripe.stripe-ios/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer"},"doc://com.stripe.stripe-ios/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding"},"doc://com.stripe.stripe-ios/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-ios/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer"},"doc://com.stripe.stripe-ios/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-ios/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/delegate":{"title":"delegate","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PKAddPaymentPassViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PKAddPaymentPassViewControllerDelegate"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/delegate","abstract":[]},"doc://com.stripe.stripe-ios/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.stripe.stripe-ios/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.stripe.stripe-ios/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/init(requestConfiguration:delegate:)":{"title":"init(requestConfiguration:delegate:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(requestConfiguration:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"requestConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PKAddPaymentPassRequestConfiguration","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PKAddPaymentPassViewControllerDelegate","text":"PKAddPaymentPassViewControllerDelegate"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRequestConfiguration:delegate:"}],"url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(requestconfiguration:delegate:)","abstract":[]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/canAddPaymentPass()":{"role":"symbol","navigatorTitle":[{"text":"canAddPaymentPass","kind":"identifier"}],"title":"canAddPaymentPass()","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/canAddPaymentPass()","abstract":[],"url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/canaddpaymentpass()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"canAddPaymentPass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPFakeAddPaymentPassViewController","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/delegate"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(coder:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(nibName:bundle:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(requestConfiguration:delegate:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/viewDidLoad()"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/canAddPaymentPass()"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)UIViewController"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(coder:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPFakeAddPaymentPassViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/fragments","value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/navigatorTitle","value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace"},{"op":"replace","value":"viewDidLoad","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1viewDidLoad()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1viewDidLoad()\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(nibName:bundle:)\/title","op":"replace","value":"initWithNibName:bundle:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNibName:bundle:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(nibName:bundle:)\/fragments"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1delegate\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(requestConfiguration:delegate:)\/title","value":"initWithRequestConfiguration:delegate:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(requestConfiguration:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRequestConfiguration:delegate:"}],"op":"replace"},{"value":"canAddPaymentPass","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1canAddPaymentPass()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"canAddPaymentPass","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1canAddPaymentPass()\/fragments"}]}]}