{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider\/createIssuingCardKey(withAPIVersion:completion:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"text":" ","type":"text"},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"metadata":{"navigatorTitle":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"modules":[{"name":"Stripe"}],"symbolKind":"protocol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"title":"STPIssuingCardEphemeralKeyProvider","role":"symbol","externalID":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider"},"variants":[{"paths":["\/documentation\/stripe\/stpissuingcardephemeralkeyprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpissuingcardephemeralkeyprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPIssuingCardEphemeralKeyProvider/createIssuingCardKey(withAPIVersion:completion:)":{"url":"\/documentation\/stripe\/stpissuingcardephemeralkeyprovider\/createissuingcardkey(withapiversion:completion:)","navigatorTitle":[{"text":"createIssuingCardKeyWithAPIVersion:completion:","kind":"identifier"}],"title":"createIssuingCardKey(withAPIVersion:completion:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider\/createIssuingCardKey(withAPIVersion:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createIssuingCardKey"},{"text":"(","kind":"text"},{"text":"withAPIVersion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments30STPJSONResponseCompletionBlocka","text":"STPJSONResponseCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Creates a new ephemeral key for retrieving and updating a Stripe Issuing Card.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"On your backend, you should create a new ephemeral key for your logged-in user’s"},{"type":"text","text":" "},{"text":"primary Issuing Card, and return the raw JSON response from the Stripe API.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For an example Ruby implementation of this API, refer to our example backend:"},{"type":"text","text":" "},{"text":"https:\/\/github.com\/stripe\/example-mobile-backend\/blob\/v18.1.0\/web.rb","type":"text"},{"type":"text","text":" "},{"text":"Back in your iOS app, once you have a response from this API, call the provided","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"completion block with the JSON response, or an error if one occurred."}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"title":"Stripe","url":"\/documentation\/stripe","type":"topic","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPIssuingCardEphemeralKeyProvider":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"title":"STPIssuingCardEphemeralKeyProvider","kind":"symbol","url":"\/documentation\/stripe\/stpissuingcardephemeralkeyprovider","type":"topic","role":"symbol","navigatorTitle":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"text":" ","type":"text"},{"text":"It provides a way for Stripe utility classes to request a new ephemeral key from","type":"text"},{"type":"text","text":" "},{"text":"your backend, which it will use to retrieve and update Stripe API objects.","type":"text"}]},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"STPIssuingCardEphemeralKeyProvider","op":"replace"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"}],"op":"replace"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider\/createIssuingCardKey(withAPIVersion:completion:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider~1createIssuingCardKey(withAPIVersion:completion:)\/title","op":"replace","value":"createIssuingCardKeyWithAPIVersion:completion:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider~1createIssuingCardKey(withAPIVersion:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"createIssuingCardKeyWithAPIVersion:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/title","value":"STPIssuingCardEphemeralKeyProvider"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/fragments","value":[{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/navigatorTitle","value":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}