{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"An "},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"text":" object to your ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"metadata":{"title":"STPPaymentConfiguration","navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentConfiguration","kind":"identifier"}],"modules":[{"name":"Stripe"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentConfiguration","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripe\/stppaymentconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/additionalPaymentOptions","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/appleMerchantIdentifier","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/applePayEnabled","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/availableCountries","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/canDeletePaymentOptions","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/cardScanningEnabled","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/companyName","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/description","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/fpxEnabled","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/publishableKey","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredBillingAddressFields","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredShippingAddressFields","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shippingType","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/stripeAccount","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/verifyPrefilledShippingAddress"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/copy(with:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shared"]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/applePayEnabled":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/applePayEnabled","url":"\/documentation\/stripe\/stppaymentconfiguration\/applepayenabled","title":"applePayEnabled","abstract":[{"type":"text","text":"The user is allowed to pay with Apple Pay if it’s configured and available on their device."}],"navigatorTitle":[{"kind":"identifier","text":"applePayEnabled"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/canDeletePaymentOptions":{"navigatorTitle":[{"kind":"identifier","text":"canDeletePaymentOptions"}],"title":"canDeletePaymentOptions","url":"\/documentation\/stripe\/stppaymentconfiguration\/candeletepaymentoptions","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/canDeletePaymentOptions","abstract":[{"text":"Determines whether or not the user is able to delete payment options","type":"text"},{"text":" ","type":"text"},{"text":"This is only relevant to the ","type":"text"},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" which, if"},{"type":"text","text":" "},{"type":"text","text":"enabled, will allow the user to delete payment options by tapping the “Edit”"},{"type":"text","text":" "},{"text":"button in the navigation bar or by swiping left on a payment option and tapping","type":"text"},{"type":"text","text":" "},{"text":"“Delete”. Currently, the user is not allowed to delete the selected payment","type":"text"},{"type":"text","text":" "},{"text":"option but this may change in the future.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default value is YES but will only work if "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"text":" is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"initialized with a "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" either through the "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" "},{"text":"or directly as an init parameter.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"canDeletePaymentOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.stripe.stripe-ios/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/verifyPrefilledShippingAddress":{"navigatorTitle":[{"kind":"identifier","text":"verifyPrefilledShippingAddress"}],"title":"verifyPrefilledShippingAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/verifyPrefilledShippingAddress","url":"\/documentation\/stripe\/stppaymentconfiguration\/verifyprefilledshippingaddress","abstract":[{"type":"text","text":"Whether the user should be prompted to verify prefilled shipping information."},{"text":" ","type":"text"},{"text":"The default value is YES.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"verifyPrefilledShippingAddress","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-ios/SH":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/requiredShippingAddressFields":{"abstract":[{"text":"The shipping address fields the user must fill out when prompted for their","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"shipping info. Set to nil if shipping address is not required."},{"text":" ","type":"text"},{"type":"text","text":"The default value is nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredShippingAddressFields","role":"symbol","title":"requiredShippingAddressFields","type":"topic","url":"\/documentation\/stripe\/stppaymentconfiguration\/requiredshippingaddressfields","navigatorTitle":[{"kind":"identifier","text":"requiredShippingAddressFields"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredShippingAddressFields"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","text":"STPContactField"},{"text":">?","kind":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"url":"\/documentation\/stripe\/stppaymentconfiguration","role":"symbol","navigatorTitle":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"title":"STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"text":" ","type":"text"},{"type":"text","text":"You provide an "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"when making a charge. The configuration generally has settings that"},{"type":"text","text":" "},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"text":"is specific to a single particular payment instance.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/appleMerchantIdentifier":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"appleMerchantIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The Apple Merchant Identifier to use during Apple Pay transactions. To create"},{"text":" ","type":"text"},{"text":"one of these, see our guide at https:\/\/stripe.com\/docs\/apple-pay . You","type":"text"},{"type":"text","text":" "},{"type":"text","text":"must set this to a valid identifier in order to automatically enable Apple Pay."}],"title":"appleMerchantIdentifier","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/appleMerchantIdentifier","url":"\/documentation\/stripe\/stppaymentconfiguration\/applemerchantidentifier","navigatorTitle":[{"text":"appleMerchantIdentifier","kind":"identifier"}]},"doc://com.stripe.stripe-ios/objc(pl)NSCopying":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/shared":{"navigatorTitle":[{"kind":"identifier","text":"sharedConfiguration"}],"abstract":[{"text":"This is a convenience singleton configuration that uses the default values for","type":"text"},{"type":"text","text":" "},{"text":"every property","type":"text"}],"title":"shared","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shared","role":"symbol","url":"\/documentation\/stripe\/stppaymentconfiguration\/shared","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/publishableKey":{"url":"\/documentation\/stripe\/stppaymentconfiguration\/publishablekey","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"publishableKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"If you used STPPaymentConfiguration.shared.publishableKey, use STPAPIClient.shared.publishableKey instead.  The SDK uses STPAPIClient.shared to make API requests by default."},{"text":" ","type":"text"},{"text":"Your Stripe publishable key","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/publishableKey","kind":"symbol","title":"publishableKey","navigatorTitle":[{"text":"publishableKey","kind":"identifier"}],"deprecated":false,"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/init":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","url":"\/documentation\/stripe\/stppaymentconfiguration\/init","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/init","type":"topic","title":"init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/companyName":{"abstract":[{"text":"The name of your company, for displaying to the user during payment flows. For","type":"text"},{"text":" ","type":"text"},{"text":"example, when using Apple Pay, the payment sheet’s final line item will read","type":"text"},{"text":" ","type":"text"},{"text":"“PAY {companyName}”.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The default value is the name of your iOS application which is derived from the"},{"text":" ","type":"text"},{"code":"kCFBundleNameKey","type":"codeVoice"},{"type":"text","text":" of "},{"code":"Bundle.main","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"companyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"companyName","kind":"identifier"}],"title":"companyName","url":"\/documentation\/stripe\/stppaymentconfiguration\/companyname","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/companyName","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/requiredBillingAddressFields":{"abstract":[{"text":"The billing address fields the user must fill out when prompted for their","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment details. These fields will all be present on the returned PaymentMethod from"},{"type":"text","text":" "},{"type":"text","text":"Stripe."},{"text":" ","type":"text"},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"STPBillingAddressFieldsPostalCode"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredBillingAddressFields","role":"symbol","title":"requiredBillingAddressFields","type":"topic","url":"\/documentation\/stripe\/stppaymentconfiguration\/requiredbillingaddressfields","navigatorTitle":[{"kind":"identifier","text":"requiredBillingAddressFields"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredBillingAddressFields"},{"text":": ","kind":"text"},{"text":"STPBillingAddressFields","preciseIdentifier":"c:@M@Stripe@E@STPBillingAddressFields","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/SQ":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/description":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":":nodoc:"}],"title":"description","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/description","url":"\/documentation\/stripe\/stppaymentconfiguration\/description","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/copy(with:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"abstract":[{"text":":nodoc:","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"NSZone","kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/copy(with:)","url":"\/documentation\/stripe\/stppaymentconfiguration\/copy(with:)","title":"copy(with:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/additionalPaymentOptions":{"title":"additionalPaymentOptions","type":"topic","url":"\/documentation\/stripe\/stppaymentconfiguration\/additionalpaymentoptions","deprecated":false,"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/additionalPaymentOptions","abstract":[{"type":"text","text":"An enum value representing which payment options you will accept from your user"},{"type":"text","text":" "},{"type":"text","text":"in addition to credit cards."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalPaymentOptions"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"additionalPaymentOptions","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/stripeAccount":{"type":"topic","url":"\/documentation\/stripe\/stppaymentconfiguration\/stripeaccount","deprecated":false,"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"If you used STPPaymentConfiguration.shared.stripeAccount, use STPAPIClient.shared.stripeAccount instead.  The SDK uses STPAPIClient.shared to make API requests by default."},{"text":" ","type":"text"},{"text":"In order to perform API requests on behalf of a connected account, e.g. to","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"create charges for a connected account, set this property to the ID of the"},{"text":" ","type":"text"},{"text":"account for which this request is being made.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"stripeAccount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stripeAccount"}],"title":"stripeAccount","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/stripeAccount"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/fpxEnabled":{"url":"\/documentation\/stripe\/stppaymentconfiguration\/fpxenabled","abstract":[{"type":"text","text":"The user is allowed to pay with FPX."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/fpxEnabled","kind":"symbol","title":"fpxEnabled","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fpxEnabled"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fpxEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/shippingType":{"url":"\/documentation\/stripe\/stppaymentconfiguration\/shippingtype","abstract":[{"type":"text","text":"The type of shipping for this purchase. This property sets the labels displayed"},{"text":" ","type":"text"},{"text":"when the user is prompted for shipping info, and whether they should also be","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"asked to select a shipping method."},{"type":"text","text":" "},{"type":"text","text":"The default value is STPShippingTypeShipping."}],"role":"symbol","kind":"symbol","type":"topic","title":"shippingType","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shippingType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shippingType"},{"text":": ","kind":"text"},{"text":"STPShippingType","preciseIdentifier":"c:@M@Stripe@E@STPShippingType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"shippingType","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/availableCountries":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/availableCountries","kind":"symbol","role":"symbol","title":"availableCountries","type":"topic","url":"\/documentation\/stripe\/stppaymentconfiguration\/availablecountries","navigatorTitle":[{"text":"availableCountries","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"availableCountries"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"abstract":[{"text":"The set of countries supported when entering an address. This property accepts","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a set of ISO 2-character country codes."},{"text":" ","type":"text"},{"type":"text","text":"The default value is all known countries. Setting this property will limit"},{"type":"text","text":" "},{"type":"text","text":"the available countries to your selected set."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/cardScanningEnabled":{"type":"topic","abstract":[{"type":"text","text":"Determines whether STPAddCardViewController allows the user to"},{"text":" ","type":"text"},{"text":"scan cards using the camera on devices running iOS 13 or later.","type":"text"},{"text":" ","type":"text"},{"text":"To use this feature, you must also set the ","type":"text"},{"type":"codeVoice","code":"NSCameraUsageDescription"},{"type":"text","text":" "},{"type":"text","text":"value in your app’s Info.plist."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/cardScanningEnabled","url":"\/documentation\/stripe\/stppaymentconfiguration\/cardscanningenabled","title":"cardScanningEnabled","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardScanningEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"cardScanningEnabled"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentConfiguration"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/additionalPaymentOptions","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/appleMerchantIdentifier","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/applePayEnabled","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/availableCountries","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/canDeletePaymentOptions","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/cardScanningEnabled","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/companyName","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/description","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/fpxEnabled","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/publishableKey","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredBillingAddressFields","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredShippingAddressFields","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shippingType","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/stripeAccount","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/verifyPrefilledShippingAddress"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/copy(with:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/init"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shared"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentConfiguration"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1applePayEnabled\/title","value":"applePayEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1applePayEnabled\/fragments","value":[{"kind":"identifier","text":"applePayEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1canDeletePaymentOptions\/title","value":"canDeletePaymentOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1canDeletePaymentOptions\/fragments","value":[{"text":"canDeletePaymentOptions","kind":"identifier"}]},{"op":"replace","value":"verifyPrefilledShippingAddress","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1verifyPrefilledShippingAddress\/title"},{"op":"replace","value":[{"text":"verifyPrefilledShippingAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1verifyPrefilledShippingAddress\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1requiredShippingAddressFields\/title","value":"requiredShippingAddressFields","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1requiredShippingAddressFields\/fragments","value":[{"text":"requiredShippingAddressFields","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"text":"STPPaymentConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1appleMerchantIdentifier\/title","op":"replace","value":"appleMerchantIdentifier"},{"value":[{"kind":"identifier","text":"appleMerchantIdentifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1appleMerchantIdentifier\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1shared\/title","op":"replace","value":"sharedConfiguration"},{"value":[{"text":"sharedConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1shared\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1publishableKey\/title","value":"publishableKey","op":"replace"},{"value":[{"text":"publishableKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1publishableKey\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1companyName\/title","op":"replace","value":"companyName"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1companyName\/fragments","value":[{"text":"companyName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1requiredBillingAddressFields\/title","value":"requiredBillingAddressFields"},{"op":"replace","value":[{"text":"requiredBillingAddressFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1requiredBillingAddressFields\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1copy(with:)\/title","value":"copyWithZone:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1copy(with:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1additionalPaymentOptions\/title","value":"additionalPaymentOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1additionalPaymentOptions\/fragments","value":[{"text":"additionalPaymentOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1stripeAccount\/title","value":"stripeAccount"},{"op":"replace","value":[{"text":"stripeAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1stripeAccount\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1fpxEnabled\/title","op":"replace","value":"fpxEnabled"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1fpxEnabled\/fragments","value":[{"text":"fpxEnabled","kind":"identifier"}],"op":"replace"},{"value":"shippingType","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1shippingType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1shippingType\/fragments","op":"replace","value":[{"text":"shippingType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1availableCountries\/title","op":"replace","value":"availableCountries"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1availableCountries\/fragments","value":[{"text":"availableCountries","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1cardScanningEnabled\/title","value":"cardScanningEnabled","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1cardScanningEnabled\/fragments","op":"replace","value":[{"text":"cardScanningEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
