{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/s8SendableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"type":"text","text":" "},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":", so you can either"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"as the "},{"type":"codeVoice","code":"rootViewController"},{"type":"text","text":" and then present the "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" onto an existing"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"type":"codeVoice","code":"presentPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"title":"STPPaymentOptionsViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:apiAdapter:delegate:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:customerContext:delegate:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(paymentContext:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewControllerFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/apiClient","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/defaultPaymentMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/paymentOptionsViewControllerFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/prefilledInformation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewController(_:didCreatePaymentMethod:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewControllerDidCancel(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/dismiss(withCompletion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/viewDidAppear(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/viewDidLayoutSubviews()"]}],"references":{"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/init(paymentContext:)":{"role":"symbol","title":"init(paymentContext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates a new payment methods view controller."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(paymentContext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPaymentContext:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(paymentcontext:)"},"doc://com.stripe.stripe-ios/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/paymentOptionsViewControllerFooterView":{"role":"symbol","title":"paymentOptionsViewControllerFooterView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A view that will be placed as the footer of the view controller when it is"},{"type":"text","text":" "},{"type":"text","text":"showing a list of saved payment methods to select from."},{"type":"text","text":" "},{"type":"text","text":"When the footer view needs to be resized, it will be sent a"},{"type":"text","text":" "},{"type":"codeVoice","code":"sizeThatFits:"},{"type":"text","text":" call. The view should respond correctly to this method in order"},{"type":"text","text":" "},{"type":"text","text":"to be sized and positioned properly."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/paymentOptionsViewControllerFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/paymentoptionsviewcontrollerfooterview"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreViewController":{"role":"symbol","title":"STPCoreViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe view controllers. It is intended for use"},{"type":"text","text":" "},{"type":"text","text":"only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It theming, back\/cancel button management, and other shared logic for"},{"type":"text","text":" "},{"type":"text","text":"Stripe view controllers."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreViewController"}],"url":"\/documentation\/stripe\/stpcoreviewcontroller"},"doc://com.stripe.stripe-ios/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/addCardViewControllerFooterView":{"role":"symbol","title":"addCardViewControllerFooterView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewControllerFooterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A view that will be placed as the footer of the view controller when it is"},{"type":"text","text":" "},{"type":"text","text":"showing the add card view."},{"type":"text","text":" "},{"type":"text","text":"When the footer view needs to be resized, it will be sent a"},{"type":"text","text":" "},{"type":"codeVoice","code":"sizeThatFits:"},{"type":"text","text":" call. The view should respond correctly to this method in order"},{"type":"text","text":" "},{"type":"text","text":"to be sized and positioned properly."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewControllerFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCardViewControllerFooterView"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/addcardviewcontrollerfooterview"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/apiClient":{"role":"symbol","title":"apiClient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"abstract":[{"type":"text","text":"The API Client to use to make requests."},{"type":"text","text":" "},{"type":"text","text":"Defaults to STPAPIClient.shared"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/apiClient","kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/apiclient"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"role":"symbol","title":"STPPaymentOptionsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"type":"text","text":" "},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":", so you can either"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"as the "},{"type":"codeVoice","code":"rootViewController"},{"type":"text","text":" and then present the "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" onto an existing"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"type":"codeVoice","code":"presentPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/defaultPaymentMethod":{"role":"symbol","title":"defaultPaymentMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultPaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/defaultPaymentMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultPaymentMethod"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/defaultpaymentmethod"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer"},"doc://com.stripe.stripe-ios/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding"},"doc://com.stripe.stripe-ios/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring"},"doc://com.stripe.stripe-ios/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/init(configuration:theme:customerContext:delegate:)":{"role":"symbol","title":"init(configuration:theme:customerContext:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customerContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewControllerDelegate","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new payment methods view controller without using a"},{"type":"text","text":" "},{"type":"text","text":"payment context."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:customerContext:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:theme:customerContext:delegate:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(configuration:theme:customercontext:delegate:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/dismiss(withCompletion:)":{"role":"symbol","title":"dismiss(withCompletion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCompletion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"If you’re pushing "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" onto an existing"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"‘s stack, you should use this method to dismiss it,"},{"type":"text","text":" "},{"type":"text","text":"since it may have pushed an additional add card view controller onto the"},{"type":"text","text":" "},{"type":"text","text":"navigation controller’s stack."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/dismiss(withCompletion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/dismiss(withcompletion:)"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.stripe.stripe-ios\/s8SendableP"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment"},"doc://com.stripe.stripe-ios/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/addCardViewControllerDidCancel(_:)":{"role":"symbol","title":"addCardViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the user cancels adding a card. You should dismiss (or pop) the"},{"type":"text","text":" "},{"type":"text","text":"view controller at this point."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewControllerDidCancel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCardViewControllerDidCancel:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/addcardviewcontrollerdidcancel(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/viewdidappear(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/init(configuration:theme:apiAdapter:delegate:)":{"role":"symbol","title":"init(configuration:theme:apiAdapter:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":", "},{"kind":"externalParam","text":"apiAdapter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPBackendAPIAdapter","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewControllerDelegate","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Note: Instead of providing your own backend API adapter, we recommend using"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which will manage retrieving and updating a"},{"type":"text","text":" "},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"type":"text","text":" "},{"type":"text","text":"Initializes a new payment methods view controller without using"},{"type":"text","text":" "},{"type":"text","text":"a payment context."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:apiAdapter:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:theme:apiAdapter:delegate:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(configuration:theme:apiadapter:delegate:)"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/addCardViewController(_:didCreatePaymentMethod:completion:)":{"role":"symbol","title":"addCardViewController(_:didCreatePaymentMethod:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user successfully adds a card and Stripe returns a"},{"type":"text","text":" "},{"type":"text","text":"Payment Method."},{"type":"text","text":" "},{"type":"text","text":"You should send the PaymentMethod to your backend to store it on a customer, and then"},{"type":"text","text":" "},{"type":"text","text":"call the provided "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when that call is finished. If an error"},{"type":"text","text":" "},{"type":"text","text":"occurs while talking to your backend, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":", otherwise,"},{"type":"text","text":" "},{"type":"text","text":"dismiss (or pop) the view controller."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewController(_:didCreatePaymentMethod:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCardViewController:didCreatePaymentMethod:completion:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/addcardviewcontroller(_:didcreatepaymentmethod:completion:)"},"doc://com.stripe.stripe-ios/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/prefilledInformation":{"role":"symbol","title":"prefilledInformation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefilledInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPUserInformation","preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If you’ve already collected some information from your user, you can set it"},{"type":"text","text":" "},{"type":"text","text":"here and it’ll be automatically filled out when possible\/appropriate in any UI"},{"type":"text","text":" "},{"type":"text","text":"that the payment context creates."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/prefilledInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prefilledInformation"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/prefilledinformation"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate":{"role":"symbol","title":"STPAddCardViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPAddCardViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":" "},{"type":"text","text":"successfully creates a card token or is cancelled. It has internal error-handling"},{"type":"text","text":" "},{"type":"text","text":"logic, so there’s no error case to deal with."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/viewDidLayoutSubviews()":{"role":"symbol","title":"viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/viewDidLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/viewdidlayoutsubviews()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentOptionsViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewControllerFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/defaultPaymentMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/paymentOptionsViewControllerFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/prefilledInformation"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewController(_:didCreatePaymentMethod:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewControllerDidCancel(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/dismiss(withCompletion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:apiAdapter:delegate:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:customerContext:delegate:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(paymentContext:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/viewDidAppear(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/viewDidLayoutSubviews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCoreViewController","text":"STPCoreViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(paymentContext:)\/title","value":"initWithPaymentContext:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(paymentContext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1paymentOptionsViewControllerFooterView\/title","value":"paymentOptionsViewControllerFooterView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1paymentOptionsViewControllerFooterView\/fragments","value":[{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/title","value":"STPCoreViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1addCardViewControllerFooterView\/title","value":"addCardViewControllerFooterView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1addCardViewControllerFooterView\/fragments","value":[{"kind":"identifier","text":"addCardViewControllerFooterView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","value":"STPPaymentOptionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1defaultPaymentMethod\/title","value":"defaultPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1defaultPaymentMethod\/fragments","value":[{"kind":"identifier","text":"defaultPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(configuration:theme:customerContext:delegate:)\/title","value":"initWithConfiguration:theme:customerContext:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(configuration:theme:customerContext:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:theme:customerContext:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1dismiss(withCompletion:)\/title","value":"dismissWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1dismiss(withCompletion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1addCardViewControllerDidCancel(_:)\/title","value":"addCardViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1addCardViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewControllerDidCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(configuration:theme:apiAdapter:delegate:)\/title","value":"initWithConfiguration:theme:apiAdapter:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(configuration:theme:apiAdapter:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:theme:apiAdapter:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1addCardViewController(_:didCreatePaymentMethod:completion:)\/title","value":"addCardViewController:didCreatePaymentMethod:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1addCardViewController(_:didCreatePaymentMethod:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreatePaymentMethod:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1prefilledInformation\/title","value":"prefilledInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1prefilledInformation\/fragments","value":[{"kind":"identifier","text":"prefilledInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/title","value":"STPAddCardViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
