{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContextDelegate"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontextdelegate"]},{"paths":["\/documentation\/stripe\/stppaymentcontextdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"metadata":{"role":"symbol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPPaymentContextDelegate","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(pl)STPPaymentContextDelegate","symbolKind":"protocol","modules":[{"name":"Stripe"}],"title":"STPPaymentContextDelegate","navigatorTitle":[{"text":"STPPaymentContextDelegate","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Implement "},{"type":"codeVoice","code":"STPPaymentContextDelegate"},{"text":" to get notified when a payment context changes, finishes, encounters errors, etc. In practice, if your app has a “checkout screen view controller”, that is a good candidate to implement this protocol.","type":"text"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didCreatePaymentResult:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFailToLoadWithError:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFinishWith:error:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didUpdateShippingAddress:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContextDidChange(_:)"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"]}],"references":{"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContext(_:didUpdateShippingAddress:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","text":"STPPaymentContext"},{"text":", ","kind":"text"},{"text":"didUpdateShippingAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPShippingMethodsCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didupdateshippingaddress:completion:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didUpdateShippingAddress:completion:)","title":"paymentContext(_:didUpdateShippingAddress:completion:)","navigatorTitle":[{"text":"paymentContext:didUpdateShippingAddress:completion:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Inside this method, you should verify that you can ship to the given address.","type":"text"},{"type":"text","text":" "},{"text":"You should call the completion block with the results of your validation","type":"text"},{"text":" ","type":"text"},{"text":"and the available shipping methods for the given address. If you don’t implement","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"this method, the user won’t be prompted to select a shipping method and all"},{"type":"text","text":" "},{"text":"addresses will be valid. If you call the completion block with nil or an","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"empty array of shipping methods, the user won’t be prompted to select a"},{"text":" ","type":"text"},{"type":"text","text":"shipping method."}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContext(_:didFailToLoadWithError:)":{"abstract":[{"text":"Called when the payment context encounters an error when fetching its initial set of data. A few ways to handle this are:","type":"text"}],"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didfailtoloadwitherror:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentContext"},{"text":"(","kind":"text"},{"text":"STPPaymentContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"text":", ","kind":"text"},{"text":"didFailToLoadWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paymentContext:didFailToLoadWithError:","kind":"identifier"}],"title":"paymentContext(_:didFailToLoadWithError:)","required":true,"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFailToLoadWithError:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContextDidChange(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentContextDidChange"},{"kind":"text","text":"("},{"text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontextdidchange(_:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"paymentContextDidChange:"}],"type":"topic","title":"paymentContextDidChange(_:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContextDidChange(_:)","abstract":[{"type":"text","text":"This is called every time the contents of the payment context change. When this is called, you should update your app’s UI to reflect the current state of the payment context. For example, if you have a checkout page with a “selected payment method” row, you should update its payment method with "},{"code":"paymentContext.selectedPaymentOption.label","type":"codeVoice"},{"type":"text","text":". If that checkout page has a “buy” button, you should enable\/disable it depending on the result of "},{"code":"paymentContext.isReadyForPayment","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContext(_:didFinishWith:error:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentContext"},{"kind":"text","text":"("},{"text":"STPPaymentContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"paymentContext:didFinishWith:error:","kind":"identifier"}],"title":"paymentContext(_:didFinishWith:error:)","required":true,"url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didfinishwith:error:)","role":"symbol","abstract":[{"text":"This is invoked by an ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" when it is finished. This will be called after the payment is done and all necessary UI has been dismissed. You should inspect the returned "},{"code":"status","type":"codeVoice"},{"type":"text","text":" and behave appropriately. For example: if it’s "},{"code":"STPPaymentStatusSuccess","type":"codeVoice"},{"text":", show the user a receipt. If it’s ","type":"text"},{"type":"codeVoice","code":"STPPaymentStatusError"},{"text":", inform the user of the error. If it’s ","type":"text"},{"type":"codeVoice","code":"STPPaymentStatusUserCancellation"},{"text":", do nothing.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFinishWith:error:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContext(_:didCreatePaymentResult:completion:)":{"type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"paymentContext:didCreatePaymentResult:completion:"}],"abstract":[{"type":"text","text":"Inside this method, you should make a call to your backend API to make a PaymentIntent with that Customer + payment method, and invoke the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when that is done."}],"title":"paymentContext(_:didCreatePaymentResult:completion:)","url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didcreatepaymentresult:completion:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didCreatePaymentResult:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"kind":"text","text":", "},{"text":"didCreatePaymentResult","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentResult","kind":"typeIdentifier","text":"STPPaymentResult"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments21STPPaymentStatusBlocka","text":"STPPaymentStatusBlock"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate","kind":"symbol","role":"symbol","abstract":[{"text":"Implement ","type":"text"},{"code":"STPPaymentContextDelegate","type":"codeVoice"},{"type":"text","text":" to get notified when a payment context changes, finishes, encounters errors, etc. In practice, if your app has a “checkout screen view controller”, that is a good candidate to implement this protocol."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentContextDelegate"}],"type":"topic","url":"\/documentation\/stripe\/stppaymentcontextdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContextDelegate"}],"title":"STPPaymentContextDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentContextDelegate"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentContextDelegate","kind":"identifier"}]},{"value":[{"text":"STPPaymentContextDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didCreatePaymentResult:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFailToLoadWithError:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFinishWith:error:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didUpdateShippingAddress:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContextDidChange(_:)"],"title":"Instance Methods"}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentContextDelegate"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"paymentContext:didUpdateShippingAddress:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didUpdateShippingAddress:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"paymentContext:didUpdateShippingAddress:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didUpdateShippingAddress:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didFailToLoadWithError:)\/title","value":"paymentContext:didFailToLoadWithError:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentContext:didFailToLoadWithError:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didFailToLoadWithError:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContextDidChange(_:)\/title","value":"paymentContextDidChange:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContextDidChange(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"paymentContextDidChange:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didFinishWith:error:)\/title","op":"replace","value":"paymentContext:didFinishWith:error:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didFinishWith:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentContext:didFinishWith:error:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didCreatePaymentResult:completion:)\/title","value":"paymentContext:didCreatePaymentResult:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didCreatePaymentResult:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentContext:didCreatePaymentResult:completion:"}]},{"op":"replace","value":"STPPaymentContextDelegate","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/title"},{"op":"replace","value":[{"text":"STPPaymentContextDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/fragments"}]}]}
