{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/image","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/isReusable","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/label","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/templateImage"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPPaymentOption","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"STPApplePay"},{"type":"text","text":", which represents that the user wants to pay with"},{"text":" ","type":"text"},{"type":"text","text":"Apple Pay"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":".  Only "},{"code":"STPPaymentMethod.type == STPPaymentMethodTypeCard","type":"codeVoice"},{"text":" and","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentMethod.type == STPPaymentMethodTypeFPX","type":"codeVoice"},{"type":"text","text":" are supported by "},{"code":"STPPaymentContext","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"and "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":". This should be used with non-reusable payment method, such"},{"text":" ","type":"text"},{"text":"as FPX and iDEAL. Instead of reaching out to Stripe to create a PaymentMethod, you can","type":"text"},{"type":"text","text":" "},{"text":"pass an STPPaymentMethodParams directly to Stripe when confirming a PaymentIntent.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"},{"inlineContent":[{"text":"in a custom integration.","type":"text"}],"type":"paragraph"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Protocol","externalID":"c:@M@Stripe@objc(pl)STPPaymentOption","symbolKind":"protocol","title":"STPPaymentOption","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOption"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentOption","kind":"identifier"}],"modules":[{"name":"Stripe"}]},"abstract":[{"type":"text","text":"This protocol represents a payment method that a user can select and use to"},{"text":" ","type":"text"},{"type":"text","text":"pay."},{"type":"text","text":" "},{"type":"text","text":"The classes that conform to it and are supported by the UI:"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentoption"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCard","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodParams","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSource"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption/templateImage":{"required":true,"kind":"symbol","abstract":[{"text":"A small (32 x 20 points) logo image representing the payment method that can be","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"used as template for tinted icons."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"templateImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/templateImage","url":"\/documentation\/stripe\/stppaymentoption\/templateimage","role":"symbol","title":"templateImage","type":"topic","navigatorTitle":[{"kind":"identifier","text":"templateImage"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption":{"kind":"symbol","abstract":[{"type":"text","text":"This protocol represents a payment method that a user can select and use to"},{"type":"text","text":" "},{"type":"text","text":"pay."},{"type":"text","text":" "},{"type":"text","text":"The classes that conform to it and are supported by the UI:"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOption","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","url":"\/documentation\/stripe\/stppaymentoption","role":"symbol","title":"STPPaymentOption","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOption"}]},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPApplePayPaymentOption":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayPaymentOption","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPApplePayPaymentOption"}],"url":"\/documentation\/stripe\/stpapplepaypaymentoption","type":"topic","title":"STPApplePayPaymentOption","kind":"symbol","role":"symbol","abstract":[{"text":"An empty class representing that the user wishes to pay via Apple Pay. This can","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"be checked on an "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":", e.g:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethodParams":{"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodParams"}],"title":"STPPaymentMethodParams","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentmethodparams"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripe\/stppaymentmethod","title":"STPPaymentMethod","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethod","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPSource":{"url":"\/documentation\/stripe\/stpsource","kind":"symbol","abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSource","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"role":"symbol","title":"STPSource","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption/image":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"required":true,"abstract":[{"text":"A small (32 x 20 points) logo image representing the payment method. For","type":"text"},{"type":"text","text":" "},{"text":"example, the Visa logo for a Visa card, or the Apple Pay logo.","type":"text"}],"navigatorTitle":[{"text":"image","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentoption\/image","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/image","type":"topic","kind":"symbol","title":"image","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption/label":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"label"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/stripe\/stppaymentoption\/label","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/label","title":"label","navigatorTitle":[{"text":"label","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A string describing the payment method, such as “Apple Pay” or “Visa 4242”.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCard":{"type":"topic","title":"STPCard","kind":"symbol","abstract":[{"text":"Representation of a user’s credit card details that have been tokenized with","type":"text"},{"type":"text","text":" "},{"text":"the Stripe API","type":"text"}],"url":"\/documentation\/stripe\/stpcard","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCard","navigatorTitle":[{"kind":"identifier","text":"STPCard"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCard","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption/isReusable":{"required":true,"kind":"symbol","abstract":[{"type":"text","text":"Describes whether this payment option may be used multiple times. If it is not reusable,"},{"type":"text","text":" "},{"text":"the payment method must be discarded after use.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isReusable","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/isReusable","url":"\/documentation\/stripe\/stppaymentoption\/isreusable","role":"symbol","title":"isReusable","type":"topic","navigatorTitle":[{"text":"isReusable","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentOption"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPPaymentOption","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentOption","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/image","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/isReusable","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/label","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/templateImage"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPApplePayPaymentOption"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentOption","kind":"identifier"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1templateImage\/title","value":"templateImage","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1templateImage\/fragments","value":[{"kind":"identifier","text":"templateImage"}],"op":"replace"},{"op":"replace","value":"STPPaymentOption","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/title"},{"op":"replace","value":[{"text":"STPPaymentOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/title","value":"STPApplePayPaymentOption"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPApplePayPaymentOption\/fragments","value":[{"text":"STPApplePayPaymentOption","kind":"identifier"}]},{"value":"image","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1image\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1image\/fragments","value":[{"text":"image","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1label\/title","value":"label"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1label\/fragments","value":[{"kind":"identifier","text":"label"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1isReusable\/title","value":"isReusable"},{"value":[{"kind":"identifier","text":"isReusable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1isReusable\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
