{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/init(cardId:certificates:nonce:nonceSignature:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/cardId","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificates","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificatesBase64","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonce","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceHex","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignature","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignatureHex"],"generated":true}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"]}],"variants":[{"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppushprovisioningdetailsparams"]}],"abstract":[{"text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API.","type":"text"},{"type":"text","text":" "},{"text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"modules":[{"name":"Stripe"}],"symbolKind":"class","title":"STPPushProvisioningDetailsParams","roleHeading":"Class","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningDetailsParams"},"sections":[],"references":{"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/nonceHex":{"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncehex","kind":"symbol","title":"nonceHex","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonceHex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceHex","type":"topic","navigatorTitle":[{"text":"nonceHex","kind":"identifier"}],"abstract":[{"type":"text","text":"Implemented for convenience - the Stripe API expects the nonce as a hex-encoded string."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/certificatesBase64":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificatesBase64","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/certificatesbase64","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"certificatesBase64","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"title":"certificatesBase64","navigatorTitle":[{"kind":"identifier","text":"certificatesBase64"}],"abstract":[{"type":"text","text":"Implemented for convenience - the Stripe API expects the certificate chain as an array of base64-encoded strings."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/cardId":{"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/cardid","kind":"symbol","title":"cardId","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/cardId","type":"topic","navigatorTitle":[{"text":"cardId","kind":"identifier"}],"abstract":[{"type":"text","text":"The Stripe ID of the Issuing card object to retrieve details for."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/certificates":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificates","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/certificates","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"certificates"},{"kind":"text","text":": ["},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"]"}],"title":"certificates","navigatorTitle":[{"text":"certificates","kind":"identifier"}],"abstract":[{"type":"text","text":"An array of certificates that should be used to encrypt the card details."}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"title":"Stripe","role":"collection","abstract":[],"url":"\/documentation\/stripe","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/nonce":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonce","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/nonce","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"nonce","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"title":"nonce","navigatorTitle":[{"text":"nonce","kind":"identifier"}],"abstract":[{"type":"text","text":"A nonce that should be used during the encryption of the card details."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/nonceSignature":{"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncesignature","kind":"symbol","title":"nonceSignature","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonceSignature"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignature","type":"topic","navigatorTitle":[{"text":"nonceSignature","kind":"identifier"}],"abstract":[{"type":"text","text":"A nonce signature that should be used during the encryption of the card details."}]},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/init(cardId:certificates:nonce:nonceSignature:)":{"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/init(cardid:certificates:nonce:noncesignature:)","kind":"symbol","title":"init(cardId:certificates:nonce:nonceSignature:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"cardId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"certificates","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"nonce"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonceSignature"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/init(cardId:certificates:nonce:nonceSignature:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCardId:certificates:nonce:nonceSignature:"}],"abstract":[{"type":"text","text":"Instantiates a new params object with the provided attributes."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams/nonceSignatureHex":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignatureHex","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppushprovisioningdetailsparams\/noncesignaturehex","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"nonceSignatureHex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"nonceSignatureHex","navigatorTitle":[{"kind":"identifier","text":"nonceSignatureHex"}],"abstract":[{"type":"text","text":"Implemented for convenience - the Stripe API expects the nonce signature as a hex-encoded string."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningDetailsParams":{"url":"\/documentation\/stripe\/stppushprovisioningdetailsparams","kind":"symbol","title":"STPPushProvisioningDetailsParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}],"abstract":[{"type":"text","text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPPushProvisioningDetailsParams"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/cardId","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificates","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/certificatesBase64","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonce","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceHex","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignature","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/nonceSignatureHex"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningDetailsParams\/init(cardId:certificates:nonce:nonceSignature:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceHex\/title","op":"replace","value":"nonceHex"},{"value":[{"kind":"identifier","text":"nonceHex"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceHex\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1certificatesBase64\/title","op":"replace","value":"certificatesBase64"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1certificatesBase64\/fragments","value":[{"text":"certificatesBase64","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1cardId\/title","value":"cardId"},{"value":[{"kind":"identifier","text":"cardId"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1cardId\/fragments"},{"value":"certificates","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1certificates\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1certificates\/fragments","value":[{"text":"certificates","kind":"identifier"}],"op":"replace"},{"value":"nonce","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonce\/title"},{"value":[{"text":"nonce","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonce\/fragments"},{"op":"replace","value":"nonceSignature","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceSignature\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceSignature\/fragments","op":"replace","value":[{"kind":"identifier","text":"nonceSignature"}]},{"value":"initWithCardId:certificates:nonce:nonceSignature:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1init(cardId:certificates:nonce:nonceSignature:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1init(cardId:certificates:nonce:nonceSignature:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCardId:certificates:nonce:nonceSignature:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceSignatureHex\/title","value":"nonceSignatureHex"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams~1nonceSignatureHex\/fragments","value":[{"kind":"identifier","text":"nonceSignatureHex"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/title","value":"STPPushProvisioningDetailsParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/fragments","value":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningDetailsParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPushProvisioningDetailsParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
