{"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/init(keyProvider:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/apiClient"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/retrievePin(_:verificationId:oneTimeCode:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/updatePin(_:newPin:verificationId:oneTimeCode:completion:)"],"generated":true,"anchor":"Instance-Methods"}],"sections":[],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService"},"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPPinManagementService","role":"symbol","title":"STPPinManagementService","platforms":[],"modules":[{"name":"Stripe"}],"symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPinManagementService","kind":"identifier"}],"navigatorTitle":[{"text":"STPPinManagementService","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPinManagementService","kind":"identifier"}],"languages":["swift"]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements"}]}],"variants":[{"paths":["\/documentation\/stripe\/stppinmanagementservice"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppinmanagementservice"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"abstract":[{"type":"text","text":"STPAPIClient extensions to manage PIN on Stripe Issuing cards"}],"references":{"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService/apiClient":{"kind":"symbol","type":"topic","title":"apiClient","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/apiClient","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"apiClient"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"deprecated":true,"url":"\/documentation\/stripe\/stppinmanagementservice\/apiclient","abstract":[{"text":"The API Client to use to make requests.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to STPAPIClient.shared"}]},"doc://com.stripe.stripe-ios/SH":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService/retrievePin(_:verificationId:oneTimeCode:completion:)":{"abstract":[{"text":"Retrieves a PIN number for a given card,","type":"text"},{"type":"text","text":" "},{"text":"this call is asynchronous, implement the completion block to receive the updates","type":"text"}],"kind":"symbol","deprecated":true,"role":"symbol","title":"retrievePin(_:verificationId:oneTimeCode:completion:)","navigatorTitle":[{"text":"retrievePin:verificationId:oneTimeCode:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"retrievePin","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"verificationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"oneTimeCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments21STPPinCompletionBlocka","kind":"typeIdentifier","text":"STPPinCompletionBlock"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/retrievePin(_:verificationId:oneTimeCode:completion:)","url":"\/documentation\/stripe\/stppinmanagementservice\/retrievepin(_:verificationid:onetimecode:completion:)"},"doc://com.stripe.stripe-ios/SQ":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService/updatePin(_:newPin:verificationId:oneTimeCode:completion:)":{"navigatorTitle":[{"text":"updatePin:newPin:verificationId:oneTimeCode:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"Updates a PIN number for a given card,"},{"type":"text","text":" "},{"type":"text","text":"this call is asynchronous, implement the completion block to receive the updates"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/updatePin(_:newPin:verificationId:oneTimeCode:completion:)","title":"updatePin(_:newPin:verificationId:oneTimeCode:completion:)","deprecated":true,"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/stripe\/stppinmanagementservice\/updatepin(_:newpin:verificationid:onetimecode:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updatePin","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newPin"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"verificationId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oneTimeCode"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments21STPPinCompletionBlocka","text":"STPPinCompletionBlock"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService/init(keyProvider:)":{"role":"symbol","abstract":[{"type":"text","text":"Create a STPPinManagementService, you must provide an implementation of STPIssuingCardEphemeralKeyProvider"}],"deprecated":true,"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stppinmanagementservice\/init(keyprovider:)","navigatorTitle":[{"text":"initWithKeyProvider:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/init(keyProvider:)","kind":"symbol","type":"topic","title":"init(keyProvider:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService":{"abstract":[{"text":"STPAPIClient extensions to manage PIN on Stripe Issuing cards","type":"text"}],"type":"topic","deprecated":true,"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService","navigatorTitle":[{"text":"STPPinManagementService","kind":"identifier"}],"title":"STPPinManagementService","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPinManagementService"}],"url":"\/documentation\/stripe\/stppinmanagementservice"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","url":"\/documentation\/stripe","title":"Stripe","role":"collection"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPPinManagementService","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPPinManagementService","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPinManagementService"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/init(keyProvider:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/retrievePin(_:verificationId:oneTimeCode:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/updatePin(_:newPin:verificationId:oneTimeCode:completion:)"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPinManagementService"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1retrievePin(_:verificationId:oneTimeCode:completion:)\/title","value":"retrievePin:verificationId:oneTimeCode:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"retrievePin:verificationId:oneTimeCode:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1retrievePin(_:verificationId:oneTimeCode:completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1updatePin(_:newPin:verificationId:oneTimeCode:completion:)\/title","value":"updatePin:newPin:verificationId:oneTimeCode:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"updatePin:newPin:verificationId:oneTimeCode:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1updatePin(_:newPin:verificationId:oneTimeCode:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1init(keyProvider:)\/title","value":"initWithKeyProvider:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithKeyProvider:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1init(keyProvider:)\/fragments"},{"value":"STPPinManagementService","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/title"},{"value":[{"kind":"identifier","text":"STPPinManagementService"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/navigatorTitle","op":"replace","value":[{"text":"STPPinManagementService","kind":"identifier"}]}]}]}