{"variants":[{"paths":["\/documentation\/stripe\/stppushprovisioningcontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppushprovisioningcontext"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"This class makes it easier to implement “Push Provisioning”, the process by which an end-user can add a card to their Apple Pay wallet without having to type their number. This process is mediated by an Apple class called "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"text":"; this class will help you implement that class’ delegate methods. Note that this flow requires a special entitlement from Apple; for more information please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets .","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/init(keyProvider:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/apiClient"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)"],"generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Class","symbolKind":"class","title":"STPPushProvisioningContext","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningContext","navigatorTitle":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"modules":[{"name":"Stripe"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPushProvisioningContext"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPushProvisioningContext"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"sections":[],"references":{"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/apiClient":{"title":"apiClient","abstract":[{"text":"The API Client to use to make requests.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to STPAPIClient.shared","type":"text"}],"url":"\/documentation\/stripe\/stppushprovisioningcontext\/apiclient","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/apiClient","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","url":"\/documentation\/stripe\/stppushprovisioningcontext\/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)","abstract":[{"text":"This method lines up with the method of the same name on ","type":"text"},{"code":"PKAddPaymentPassViewControllerDelegate","type":"codeVoice"},{"text":". You should implement that protocol in your own app, and when that method is called, call this method on your ","type":"text"},{"type":"codeVoice","code":"STPPushProvisioningContext"},{"text":". This in turn will first initiate a call to your ","type":"text"},{"code":"keyProvider","type":"codeVoice"},{"type":"text","text":" (see above) to obtain an Ephemeral Key, then make a call to the Stripe Issuing API to fetch an encrypted payload for the card in question, then return that payload to iOS."}],"title":"addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addPaymentPassViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController","text":"PKAddPaymentPassViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"generateRequestWithCertificateChain"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nonceSignature"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest","text":"PKAddPaymentPassRequest","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","abstract":[],"type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)":{"title":"requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)","abstract":[{"text":"This is a helper method to generate a PKAddPaymentPassRequestConfiguration that will work with","type":"text"},{"text":" ","type":"text"},{"text":"Stripe’s Issuing APIs. Pass the returned configuration object to ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"initWithRequestConfiguration:delegate:"},{"type":"text","text":" initializer."}],"url":"\/documentation\/stripe\/stppushprovisioningcontext\/requestconfiguration(withname:description:last4:brand:primaryaccountidentifier:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"last4","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"brand","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":", ","kind":"text"},{"text":"primaryAccountIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:"}]},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-ios/SH":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/init(keyProvider:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/init(keyProvider:)","url":"\/documentation\/stripe\/stppushprovisioningcontext\/init(keyprovider:)","abstract":[{"type":"text","text":"In order to retreive the encrypted payload that PKAddPaymentPassViewController expects, the Stripe SDK must talk to the Stripe API. As this requires privileged access, you must write a “key provider” that generates an Ephemeral Key on your backend and provides it to the SDK when requested. For more information, see https:\/\/stripe.com\/docs\/mobile\/ios\/basic#ephemeral-key"}],"title":"init(keyProvider:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPIssuingCardEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithKeyProvider:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/requestConfiguration(withName:description:last4:brand:)":{"title":"requestConfiguration(withName:description:last4:brand:)","abstract":[{"type":"text","text":"This is a helper method to generate a PKAddPaymentPassRequestConfiguration that will work with"},{"type":"text","text":" "},{"text":"Stripe’s Issuing APIs. Pass the returned configuration object to ","type":"text"},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"initWithRequestConfiguration:delegate:"},{"text":" initializer.","type":"text"}],"deprecated":true,"url":"\/documentation\/stripe\/stppushprovisioningcontext\/requestconfiguration(withname:description:last4:brand:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestConfiguration","kind":"identifier"},{"kind":"text","text":"("},{"text":"withName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"last4","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"brand"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","text":"PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"requestConfigurationWithName:description:last4:brand:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext","url":"\/documentation\/stripe\/stppushprovisioningcontext","abstract":[{"type":"text","text":"This class makes it easier to implement “Push Provisioning”, the process by which an end-user can add a card to their Apple Pay wallet without having to type their number. This process is mediated by an Apple class called "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":"; this class will help you implement that class’ delegate methods. Note that this flow requires a special entitlement from Apple; for more information please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}],"title":"STPPushProvisioningContext","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPushProvisioningContext"}],"navigatorTitle":[{"text":"STPPushProvisioningContext","kind":"identifier"}]},"doc://com.stripe.stripe-ios/SQ":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"STPPushProvisioningContext","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPushProvisioningContext","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPushProvisioningContext"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/init(keyProvider:)"],"generated":true,"anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)"],"title":"Type Methods","anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPushProvisioningContext"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)\/title","value":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)\/fragments"},{"value":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1init(keyProvider:)\/title","value":"initWithKeyProvider:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1init(keyProvider:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithKeyProvider:","kind":"identifier"}],"op":"replace"},{"value":"requestConfigurationWithName:description:last4:brand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1requestConfiguration(withName:description:last4:brand:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1requestConfiguration(withName:description:last4:brand:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"requestConfigurationWithName:description:last4:brand:"}]},{"op":"replace","value":"STPPushProvisioningContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/title"},{"value":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/navigatorTitle","value":[{"text":"STPPushProvisioningContext","kind":"identifier"}]}]}]}