{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentOptionsViewControllerDelegate"},{"type":"text","text":" responds when a user selects a"},{"type":"text","text":" "},{"type":"text","text":"payment option from (or cancels) an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":". In both"},{"type":"text","text":" "},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"type":"text","text":" "},{"type":"text","text":"it off the navigation stack, or dismissing it)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"title":"STPPaymentOptionsViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didFailToLoadWithError:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didSelect:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidCancel(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidFinish(_:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContext"}],"url":"\/documentation\/stripe\/stppaymentcontext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate/paymentOptionsViewController(_:didFailToLoadWithError:)":{"navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewController:didFailToLoadWithError:"}],"role":"symbol","title":"paymentOptionsViewController(_:didFailToLoadWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToLoadWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the view controller encounters an error fetching the user’s"},{"type":"text","text":" "},{"type":"text","text":"payment options from its API adapter. You should dismiss the view controller"},{"type":"text","text":" "},{"type":"text","text":"when this is called."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didFailToLoadWithError:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontroller(_:didfailtoloadwitherror:)"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate/paymentOptionsViewController(_:didSelect:)":{"navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}],"role":"symbol","title":"paymentOptionsViewController(_:didSelect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user either makes a selection, or adds a new card."},{"type":"text","text":" "},{"type":"text","text":"This will be triggered after the view controller loads with the user’s current"},{"type":"text","text":" "},{"type":"text","text":"selection (if they have one) and then subsequently when they change their"},{"type":"text","text":" "},{"type":"text","text":"choice. You should use this callback to update any necessary UI in your app"},{"type":"text","text":" "},{"type":"text","text":"that displays the user’s currently selected payment method. You should "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" "},{"type":"text","text":"dismiss the view controller at this point, instead do this in"},{"type":"text","text":" "},{"type":"codeVoice","code":"paymentOptionsViewControllerDidFinish:"},{"type":"text","text":". "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"will also call the necessary methods on your API adapter, so you don’t need to"},{"type":"text","text":" "},{"type":"text","text":"call them directly during this method."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didSelect:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontroller(_:didselect:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate/paymentOptionsViewControllerDidFinish(_:)":{"navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish:"}],"role":"symbol","title":"paymentOptionsViewControllerDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user selects or adds a payment method, so it will often"},{"type":"text","text":" "},{"type":"text","text":"be called immediately after calling "},{"type":"codeVoice","code":"paymentOptionsViewController:didSelectPaymentOption:"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You should dismiss the view controller when this is called."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidFinish(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontrollerdidfinish(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate/paymentOptionsViewControllerDidCancel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel:"}],"role":"symbol","title":"paymentOptionsViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user taps “cancel”."},{"type":"text","text":" "},{"type":"text","text":"You should dismiss the view controller when this is called."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidCancel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontrollerdidcancel(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate":{"role":"symbol","title":"STPPaymentOptionsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentOptionsViewControllerDelegate"},{"type":"text","text":" responds when a user selects a"},{"type":"text","text":" "},{"type":"text","text":"payment option from (or cancels) an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":". In both"},{"type":"text","text":" "},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"type":"text","text":" "},{"type":"text","text":"it off the navigation stack, or dismissing it)."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentOptionsViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didFailToLoadWithError:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didSelect:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidCancel(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidFinish(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewController(_:didFailToLoadWithError:)\/title","value":"paymentOptionsViewController:didFailToLoadWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewController(_:didFailToLoadWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didFailToLoadWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewController(_:didSelect:)\/title","value":"paymentOptionsViewController:didSelectPaymentOption:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewController(_:didSelect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewControllerDidFinish(_:)\/title","value":"paymentOptionsViewControllerDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewControllerDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewControllerDidCancel(_:)\/title","value":"paymentOptionsViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/title","value":"STPPaymentOptionsViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
