{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView","interfaceLanguage":"swift"},"metadata":{"title":"STPPaymentActivityIndicatorView","modules":[{"name":"Stripe"}],"navigatorTitle":[{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentActivityIndicatorView","role":"symbol","symbolKind":"class"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)UIView"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/objc(pl)CALayerDelegate","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/s8SendableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearance","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UICoordinateSpace","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIDynamicItem","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusItem","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusItemContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UILargeContentViewerItem","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To"}],"kind":"symbol","abstract":[{"type":"text","text":"This class can be used wherever you’d use a "},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"text":" and is intended to have a similar API. It renders as a spinning circle with a gap in it, similar to what you see in the App Store app or in the Apple Pay dialog when making a purchase. To change its color, set the ","type":"text"},{"code":"tintColor","type":"codeVoice"},{"type":"text","text":" property."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}]}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/animating","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/hidesWhenStopped","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/tintColor"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/layoutSubviews()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/setAnimating(_:animated:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"references":{"doc://com.stripe.stripe-ios/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/setAnimating(_:animated:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/setAnimating(_:animated:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAnimating","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"setAnimating(_:animated:)","url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/setanimating(_:animated:)","abstract":[{"type":"text","text":"Tell the view to start or stop spinning. If "},{"code":"hidesWhenStopped","type":"codeVoice"},{"type":"text","text":" is true, it will fade in\/out if animated is true."}],"navigatorTitle":[{"kind":"identifier","text":"setAnimating:animated:"}],"type":"topic"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearance"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)UIView"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView":{"type":"topic","abstract":[{"type":"text","text":"This class can be used wherever you’d use a "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":" and is intended to have a similar API. It renders as a spinning circle with a gap in it, similar to what you see in the App Store app or in the Apple Pay dialog when making a purchase. To change its color, set the ","type":"text"},{"type":"codeVoice","code":"tintColor"},{"type":"text","text":" property."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView","title":"STPPaymentActivityIndicatorView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"url":"\/documentation\/stripe\/stppaymentactivityindicatorview","navigatorTitle":[{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}]},"doc://com.stripe.stripe-ios/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/layoutSubviews()":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/layoutSubviews()","kind":"symbol","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"title":"layoutSubviews()","url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/layoutsubviews()","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/hidesWhenStopped":{"type":"topic","abstract":[{"text":"If true, the view will hide when it is not spinning. Default is true.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/hidesWhenStopped","title":"hidesWhenStopped","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hidesWhenStopped","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/hideswhenstopped","navigatorTitle":[{"text":"hidesWhenStopped","kind":"identifier"}]},"doc://com.stripe.stripe-ios/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.stripe.stripe-ios/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)CALayerDelegate"},"doc://com.stripe.stripe-ios/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding"},"doc://com.stripe.stripe-ios/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UILargeContentViewerItem"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/tintColor":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/tintColor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tintColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"!","kind":"text"}],"title":"tintColor","url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/tintcolor","abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"text":"tintColor","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-ios/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://com.stripe.stripe-ios/SH":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-ios/SQ":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-ios/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://com.stripe.stripe-ios/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.stripe.stripe-ios/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-ios/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-ios/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-ios/s8SendableP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://com.stripe.stripe-ios/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/animating":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Whether or not the view is animating.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animating"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"animating","kind":"identifier"}],"title":"animating","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/animating","url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/animating"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentActivityIndicatorView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}]},{"value":[{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/animating","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/hidesWhenStopped","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/tintColor"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/layoutSubviews()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/setAnimating(_:animated:)"],"title":"Instance Methods"}]},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)UIView"],"title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentActivityIndicatorView"},{"kind":"text","text":" : "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"setAnimating:animated:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1setAnimating(_:animated:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1setAnimating(_:animated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setAnimating:animated:","kind":"identifier"}],"op":"replace"},{"value":"STPPaymentActivityIndicatorView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/fragments","value":[{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"layoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1layoutSubviews()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1hidesWhenStopped\/title","value":"hidesWhenStopped"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1hidesWhenStopped\/fragments","value":[{"kind":"identifier","text":"hidesWhenStopped"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1tintColor\/title","value":"tintColor"},{"op":"replace","value":[{"kind":"identifier","text":"tintColor"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1tintColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1animating\/title","value":"animating"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1animating\/fragments","value":[{"text":"animating","kind":"identifier"}]}]}]}
