{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"abstract":[{"type":"text","text":"When you’re using "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" to request your user’s payment details, this is the object that will be returned to your application when they’ve successfully made a payment."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#submit-payment-intents"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/init(paymentOption:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentMethodParams","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentOption"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"]}],"metadata":{"title":"STPPaymentResult","externalID":"c:@M@Stripe@objc(cs)STPPaymentResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentResult","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"Stripe"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentResult"}],"roleHeading":"Class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentResult","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentresult"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentresult"]}],"references":{"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult/init(paymentOption:)":{"navigatorTitle":[{"text":"initWithPaymentOption:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paymentOption","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","text":"STPPaymentOption"},{"text":"?)","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentresult\/init(paymentoption:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/init(paymentOption:)","abstract":[{"type":"text","text":"Initializes the payment result with a given payment option. This is invoked by "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" internally; you shouldn’t have to call it directly."}],"title":"init(paymentOption:)"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult/paymentMethod":{"navigatorTitle":[{"text":"paymentMethod","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentresult\/paymentmethod","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentMethod","abstract":[{"type":"text","text":"The payment method that the user has selected. This may come from a variety of different payment methods, such as an Apple Pay payment or a stored credit card. - seealso: STPPaymentMethod.h"},{"text":" ","type":"text"},{"type":"text","text":"If paymentMethod is nil, paymentMethodParams will be populated instead."}],"title":"paymentMethod"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult/paymentOption":{"abstract":[{"text":"The STPPaymentOption that was used to initialize this STPPaymentResult, either an STPPaymentMethod or an STPPaymentMethodParams.","type":"text"}],"role":"symbol","url":"\/documentation\/stripe\/stppaymentresult\/paymentoption","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","text":"STPPaymentOption"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paymentOption"}],"title":"paymentOption","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentOption"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult/paymentMethodParams":{"url":"\/documentation\/stripe\/stppaymentresult\/paymentmethodparams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentMethodParams"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentMethodParams","role":"symbol","kind":"symbol","title":"paymentMethodParams","abstract":[{"type":"text","text":"The parameters for a payment method that the user has selected. This is"},{"text":" ","type":"text"},{"type":"text","text":"populated for non-reusable payment methods, such as FPX and iDEAL. - seealso: STPPaymentMethodParams.h"},{"type":"text","text":" "},{"type":"text","text":"If paymentMethodParams is nil, paymentMethod will be populated instead."}]},"doc://com.stripe.stripe-ios/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult":{"abstract":[{"type":"text","text":"When you’re using "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" to request your user’s payment details, this is the object that will be returned to your application when they’ve successfully made a payment.","type":"text"},{"text":" ","type":"text"},{"text":"See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#submit-payment-intents","type":"text"}],"role":"symbol","url":"\/documentation\/stripe\/stppaymentresult","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentResult"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentResult"}],"title":"STPPaymentResult","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult"},"doc://com.stripe.stripe-ios/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentResult"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentResult","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPPaymentResult","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentMethodParams","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentOption"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/init(paymentOption:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"STPPaymentResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"initWithPaymentOption:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1init(paymentOption:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1init(paymentOption:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPaymentOption:","kind":"identifier"}]},{"value":"paymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentMethod\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentMethod\/fragments","value":[{"text":"paymentMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentOption\/title","op":"replace","value":"paymentOption"},{"value":[{"text":"paymentOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentOption\/fragments"},{"value":"paymentMethodParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentMethodParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentMethodParams\/fragments","op":"replace","value":[{"text":"paymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/title","op":"replace","value":"STPPaymentResult"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentResult"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
