{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPPaymentContext) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentcontext"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAuthenticationContext","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"title":"STPPaymentContext","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Stripe@objc(cs)STPPaymentContext","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentContext"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:configuration:theme:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:configuration:theme:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/addCardViewControllerFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/apiAdapter","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/apiClient","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/applePayLaterAvailability","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/configuration","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/defaultPaymentMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/delegate","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/hostViewController","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/largeTitleDisplayMode","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/loading","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/modalPresentationStyle","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentAmount","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentCountry","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentCurrency","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptions","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentSummaryItems","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/prefilledInformation","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/selectedPaymentOption","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/selectedShippingMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddress","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingMethods","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/theme"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/authenticationPresentingViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didFailToLoadWithError:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didSelect:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerDidCancel(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerDidFinish(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/prepare(forPresentation:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentPaymentOptionsViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentShippingViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/pushPaymentOptionsViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/pushShippingViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/requestPayment()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/retryLoading()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didEnter:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewControllerDidCancel(_:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/init(apiAdapter:configuration:theme:)":{"role":"symbol","title":"init(apiAdapter:configuration:theme:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiAdapter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPBackendAPIAdapter","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Note: Instead of providing your own backend API adapter, we recommend using"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which will manage retrieving and updating a"},{"type":"text","text":" "},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"type":"text","text":" "},{"type":"text","text":"Initializes a new Payment Context with the provided API adapter and configuration."},{"type":"text","text":" "},{"type":"text","text":"After this class is initialized, you should also make sure to set its "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":" properties."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:configuration:theme:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithApiAdapter:configuration:theme:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/init(apiadapter:configuration:theme:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/shippingMethods":{"role":"symbol","title":"shippingMethods","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"An array of STPShippingMethod objects that describe the supported shipping methods. May be nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingMethods","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shippingMethods"}],"url":"\/documentation\/stripe\/stppaymentcontext\/shippingmethods"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/init(customerContext:configuration:theme:)":{"role":"symbol","title":"init(customerContext:configuration:theme:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customerContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a new Payment Context with the provided customer context, configuration,"},{"type":"text","text":" "},{"type":"text","text":"and theme. After this class is initialized, you should also make sure to set its"},{"type":"text","text":" "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":" properties."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:configuration:theme:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCustomerContext:configuration:theme:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/init(customercontext:configuration:theme:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptionsViewControllerDidCancel(_:)":{"role":"symbol","title":"paymentOptionsViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user taps “cancel”."},{"type":"text","text":" "},{"type":"text","text":"You should dismiss the view controller when this is called."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerDidCancel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontrollerdidcancel(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate":{"role":"symbol","title":"STPShippingAddressViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPShippingAddressViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" receives an address, completes with an address, or is cancelled."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/applePayLaterAvailability":{"role":"symbol","title":"applePayLaterAvailability","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayLaterAvailability"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKApplePayLaterAvailability","preciseIdentifier":"c:@E@PKApplePayLaterAvailability"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/applePayLaterAvailability","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"applePayLaterAvailability"}],"url":"\/documentation\/stripe\/stppaymentcontext\/applepaylateravailability"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentCountry":{"role":"symbol","title":"paymentCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The two-letter country code for the country where the payment will be processed."},{"type":"text","text":" "},{"type":"text","text":"You should set this to the country your Stripe account is in. Defaults to “US”."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentCountry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentCountry"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentcountry"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/defaultPaymentMethod":{"role":"symbol","title":"defaultPaymentMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultPaymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/defaultPaymentMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultPaymentMethod"}],"url":"\/documentation\/stripe\/stppaymentcontext\/defaultpaymentmethod"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptionsViewController(_:didSelect:)":{"role":"symbol","title":"paymentOptionsViewController(_:didSelect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user either makes a selection, or adds a new card."},{"type":"text","text":" "},{"type":"text","text":"This will be triggered after the view controller loads with the user’s current"},{"type":"text","text":" "},{"type":"text","text":"selection (if they have one) and then subsequently when they change their"},{"type":"text","text":" "},{"type":"text","text":"choice. You should use this callback to update any necessary UI in your app"},{"type":"text","text":" "},{"type":"text","text":"that displays the user’s currently selected payment method. You should "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" "},{"type":"text","text":"dismiss the view controller at this point, instead do this in"},{"type":"text","text":" "},{"type":"codeVoice","code":"paymentOptionsViewControllerDidFinish:"},{"type":"text","text":". "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"will also call the necessary methods on your API adapter, so you don’t need to"},{"type":"text","text":" "},{"type":"text","text":"call them directly during this method."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didSelect:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontroller(_:didselect:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentContextDelegate","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentContextDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This delegate will be notified when the payment context’s contents change. - seealso: STPPaymentContextDelegate"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/stripe\/stppaymentcontext\/delegate"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/largeTitleDisplayMode":{"role":"symbol","title":"largeTitleDisplayMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"largeTitleDisplayMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINavigationItem","preciseIdentifier":"c:objc(cs)UINavigationItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"LargeTitleDisplayMode","preciseIdentifier":"c:@E@UINavigationItemLargeTitleDisplayMode"}],"abstract":[{"type":"text","text":"The mode to use when displaying the title of the navigation bar in all view"},{"type":"text","text":" "},{"type":"text","text":"controllers presented by the context. The default value is "},{"type":"codeVoice","code":"automatic"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"which causes the title to use the same styling as the previously displayed"},{"type":"text","text":" "},{"type":"text","text":"navigation item (if the view controller is pushed onto the "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"If the "},{"type":"codeVoice","code":"prefersLargeTitles"},{"type":"text","text":" property of the "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":"‘s navigation bar"},{"type":"text","text":" "},{"type":"text","text":"is false, this property has no effect and the navigation item’s title is always"},{"type":"text","text":" "},{"type":"text","text":"displayed as a small title."},{"type":"text","text":" "},{"type":"text","text":"If the view controller is presented modally, "},{"type":"codeVoice","code":"automatic"},{"type":"text","text":" and"},{"type":"text","text":" "},{"type":"codeVoice","code":"never"},{"type":"text","text":" always result in a navigation bar with a small title."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/largeTitleDisplayMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"largeTitleDisplayMode"}],"url":"\/documentation\/stripe\/stppaymentcontext\/largetitledisplaymode"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/prepare(forPresentation:)":{"role":"symbol","title":"prepare(forPresentation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method is called before presenting a UIViewController for authentication."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/prepare(forPresentation:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareAuthenticationContextForPresentation:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/prepare(forpresentation:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/presentPaymentOptionsViewController()":{"role":"symbol","title":"presentPaymentOptionsViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentPaymentOptionsViewController"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This creates, configures, and appropriately presents an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"on top of the payment context’s "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":". It’ll be dismissed automatically"},{"type":"text","text":" "},{"type":"text","text":"when the user is done selecting their payment method."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentPaymentOptionsViewController()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentPaymentOptionsViewController"}],"url":"\/documentation\/stripe\/stppaymentcontext\/presentpaymentoptionsviewcontroller()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentAmount":{"role":"symbol","title":"paymentAmount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The amount of money you’re requesting from the user, in the smallest currency"},{"type":"text","text":" "},{"type":"text","text":"unit for the selected currency. For example, to indicate $10 USD, use 1000"},{"type":"text","text":" "},{"type":"text","text":"(i.e. 1000 cents). For more information, see https:\/\/stripe.com\/docs\/api\/payment_intents\/create#create_payment_intent-amount"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentAmount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentAmount"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentamount"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/modalPresentationStyle":{"role":"symbol","title":"modalPresentationStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"modalPresentationStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIModalPresentationStyle","preciseIdentifier":"c:@E@UIModalPresentationStyle"}],"abstract":[{"type":"text","text":"The presentation style used for all view controllers presented modally by the context."},{"type":"text","text":" "},{"type":"text","text":"Since custom transition styles are not supported, you should set this to either"},{"type":"text","text":" "},{"type":"codeVoice","code":"UIModalPresentationFullScreen"},{"type":"text","text":", "},{"type":"codeVoice","code":"UIModalPresentationPageSheet"},{"type":"text","text":", or "},{"type":"codeVoice","code":"UIModalPresentationFormSheet"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"UIModalPresentationFullScreen"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/modalPresentationStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modalPresentationStyle"}],"url":"\/documentation\/stripe\/stppaymentcontext\/modalpresentationstyle"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/selectedShippingMethod":{"role":"symbol","title":"selectedShippingMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedShippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user’s currently selected shipping method. May be nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/selectedShippingMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedShippingMethod"}],"url":"\/documentation\/stripe\/stppaymentcontext\/selectedshippingmethod"},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptionsViewController(_:didFailToLoadWithError:)":{"role":"symbol","title":"paymentOptionsViewController(_:didFailToLoadWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToLoadWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the view controller encounters an error fetching the user’s"},{"type":"text","text":" "},{"type":"text","text":"payment options from its API adapter. You should dismiss the view controller"},{"type":"text","text":" "},{"type":"text","text":"when this is called."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didFailToLoadWithError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewController:didFailToLoadWithError:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontroller(_:didfailtoloadwitherror:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/shippingAddressViewController(_:didEnter:completion:)":{"role":"symbol","title":"shippingAddressViewController(_:didEnter:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user enters a shipping address and taps next. You"},{"type":"text","text":" "},{"type":"text","text":"should validate the address and determine what shipping methods are available,"},{"type":"text","text":" "},{"type":"text","text":"and call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when finished. If an error occurrs, call"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block with the error. Otherwise, call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" "},{"type":"text","text":"block with a nil error and an array of available shipping methods. If you don’t"},{"type":"text","text":" "},{"type":"text","text":"need to collect a shipping method, you may pass an empty array or nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didEnter:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontroller(_:didenter:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/init(customerContext:)":{"role":"symbol","title":"init(customerContext:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"customerContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is a convenience initializer; it is equivalent to calling"},{"type":"text","text":" "},{"type":"codeVoice","code":"init(customerContext:customerContext configuration:STPPaymentConfiguration.shared theme:STPTheme.defaultTheme"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCustomerContext:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/init(customercontext:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/retryLoading()":{"role":"symbol","title":"retryLoading()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retryLoading"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"paymentContext:didFailToLoadWithError:"},{"type":"text","text":" is called on your delegate, you"},{"type":"text","text":" "},{"type":"text","text":"can in turn call this method to try loading again (if that hasn’t been called,"},{"type":"text","text":" "},{"type":"text","text":"calling this will do nothing). If retrying in turn fails, "},{"type":"codeVoice","code":"paymentContext:didFailToLoadWithError:"},{"type":"text","text":" "},{"type":"text","text":"will be called again (and you can again call this to keep retrying, etc)."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/retryLoading()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"retryLoading"}],"url":"\/documentation\/stripe\/stppaymentcontext\/retryloading()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/prefilledInformation":{"role":"symbol","title":"prefilledInformation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefilledInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPUserInformation","preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If you’ve already collected some information from your user, you can set it here and it’ll be automatically filled out when possible\/appropriate in any UI that the payment context creates."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/prefilledInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prefilledInformation"}],"url":"\/documentation\/stripe\/stppaymentcontext\/prefilledinformation"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/presentShippingViewController()":{"role":"symbol","title":"presentShippingViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentShippingViewController"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This creates, configures, and appropriately presents a view controller for"},{"type":"text","text":" "},{"type":"text","text":"collecting shipping address and shipping method on top of the payment context’s"},{"type":"text","text":" "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":". It’ll be dismissed automatically when the user is done"},{"type":"text","text":" "},{"type":"text","text":"entering their shipping info."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentShippingViewController()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentShippingViewController"}],"url":"\/documentation\/stripe\/stppaymentcontext\/presentshippingviewcontroller()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/pushShippingViewController()":{"role":"symbol","title":"pushShippingViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushShippingViewController"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This creates, configures, and appropriately pushes a view controller for"},{"type":"text","text":" "},{"type":"text","text":"collecting shipping address and shipping method onto the navigation stack of"},{"type":"text","text":" "},{"type":"text","text":"the context’s "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":". It’ll be popped automatically when the"},{"type":"text","text":" "},{"type":"text","text":"user is done entering their shipping info."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/pushShippingViewController()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushShippingViewController"}],"url":"\/documentation\/stripe\/stppaymentcontext\/pushshippingviewcontroller()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/configuration":{"role":"symbol","title":"configuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"}],"abstract":[{"type":"text","text":"The configuration for the payment context to use internally. - seealso: STPPaymentConfiguration.h"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/configuration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"url":"\/documentation\/stripe\/stppaymentcontext\/configuration"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/apiAdapter":{"role":"symbol","title":"apiAdapter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiAdapter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPBackendAPIAdapter","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter"}],"abstract":[{"type":"text","text":"Note: Instead of providing your own backend API adapter, we recommend using"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which will manage retrieving and updating a"},{"type":"text","text":" "},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"type":"text","text":" "},{"type":"text","text":"The API adapter the payment context will use to fetch and modify its contents."},{"type":"text","text":" "},{"type":"text","text":"You need to make a class conforming to this protocol that talks to your server."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/apiAdapter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"apiAdapter"}],"url":"\/documentation\/stripe\/stppaymentcontext\/apiadapter"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/shippingAddressViewController(_:didFinishWith:shippingMethod:)":{"role":"symbol","title":"shippingAddressViewController(_:didFinishWith:shippingMethod:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"This is called when the user selects a shipping method. If no shipping methods are given, or if the shipping type doesn’t require a shipping method, this will be called after the user has a shipping address and your validation has succeeded. After updating your app with the user’s shipping info, you should dismiss (or pop) the view controller. Note that if "},{"type":"codeVoice","code":"shippingMethod"},{"type":"text","text":" is non-nil, there will be an additional shipping methods view controller on the navigation controller’s stack."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontroller(_:didfinishwith:shippingmethod:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptions":{"role":"symbol","title":"paymentOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The available payment options the user can choose between. May be nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptions"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptions"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/loading":{"role":"symbol","title":"loading","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not the payment context is currently loading information from the network."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/loading","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loading"}],"url":"\/documentation\/stripe\/stppaymentcontext\/loading"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/init(apiAdapter:)":{"role":"symbol","title":"init(apiAdapter:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiAdapter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPBackendAPIAdapter","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Note: Instead of providing your own backend API adapter, we recommend using"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which will manage retrieving and updating a"},{"type":"text","text":" "},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"type":"text","text":" "},{"type":"text","text":"This is a convenience initializer; it is equivalent to calling"},{"type":"text","text":" "},{"type":"codeVoice","code":"init(apiAdapter:apiAdapter configuration:STPPaymentConfiguration.shared theme:STPTheme.defaultTheme)"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithApiAdapter:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/init(apiadapter:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/requestPayment()":{"role":"symbol","title":"requestPayment()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestPayment"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Requests payment from the user. This may need to present some supplemental UI"},{"type":"text","text":" "},{"type":"text","text":"to the user, in which case it will be presented on the payment context’s"},{"type":"text","text":" "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":". For instance, if they’ve selected Apple Pay as their"},{"type":"text","text":" "},{"type":"text","text":"payment method, calling this method will show the payment sheet. If the user"},{"type":"text","text":" "},{"type":"text","text":"has a card on file, this will use that without presenting any additional UI."},{"type":"text","text":" "},{"type":"text","text":"After this is called, the "},{"type":"codeVoice","code":"paymentContext:didCreatePaymentResult:completion:"},{"type":"text","text":" "},{"type":"text","text":"and "},{"type":"codeVoice","code":"paymentContext:didFinishWithStatus:error:"},{"type":"text","text":" methods will be called on the"},{"type":"text","text":" "},{"type":"text","text":"context’s "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/requestPayment()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestPayment"}],"url":"\/documentation\/stripe\/stppaymentcontext\/requestpayment()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/shippingAddress":{"role":"symbol","title":"shippingAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user’s shipping address. May be nil."},{"type":"text","text":" "},{"type":"text","text":"If you’ve already collected a shipping address from your user, you may"},{"type":"text","text":" "},{"type":"text","text":"prefill it by setting a shippingAddress in PaymentContext’s prefilledInformation."},{"type":"text","text":" "},{"type":"text","text":"When your user enters a new shipping address, PaymentContext will save it to"},{"type":"text","text":" "},{"type":"text","text":"the current customer object. When PaymentContext loads, if you haven’t"},{"type":"text","text":" "},{"type":"text","text":"manually set a prefilled value, any shipping information saved on the customer"},{"type":"text","text":" "},{"type":"text","text":"will be used to prefill the shipping address form. Note that because your"},{"type":"text","text":" "},{"type":"text","text":"customer’s email may not be the same as the email provided with their shipping"},{"type":"text","text":" "},{"type":"text","text":"info, PaymentContext will not prefill the shipping form’s email using your"},{"type":"text","text":" "},{"type":"text","text":"customer’s email."},{"type":"text","text":" "},{"type":"text","text":"You should not rely on the shipping information stored on the Stripe customer"},{"type":"text","text":" "},{"type":"text","text":"for order fulfillment, as your user may change this information if they make"},{"type":"text","text":" "},{"type":"text","text":"multiple purchases. We recommend adding shipping information when you create"},{"type":"text","text":" "},{"type":"text","text":"a charge (which can also help prevent fraud), or saving it to your own"},{"type":"text","text":" "},{"type":"text","text":"database. https:\/\/stripe.com\/docs\/api\/payment_intents\/create#create_payment_intent-shipping"},{"type":"text","text":" "},{"type":"text","text":"Note: by default, your user will still be prompted to verify a prefilled"},{"type":"text","text":" "},{"type":"text","text":"shipping address. To change this behavior, you can set"},{"type":"text","text":" "},{"type":"codeVoice","code":"verifyPrefilledShippingAddress"},{"type":"text","text":" to NO in your "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shippingAddress"}],"url":"\/documentation\/stripe\/stppaymentcontext\/shippingaddress"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/pushPaymentOptionsViewController()":{"role":"symbol","title":"pushPaymentOptionsViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushPaymentOptionsViewController"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This creates, configures, and appropriately pushes an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"onto the navigation stack of the context’s "},{"type":"codeVoice","code":"hostViewController"},{"type":"text","text":". It’ll be popped"},{"type":"text","text":" "},{"type":"text","text":"automatically when the user is done selecting their payment method."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/pushPaymentOptionsViewController()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pushPaymentOptionsViewController"}],"url":"\/documentation\/stripe\/stppaymentcontext\/pushpaymentoptionsviewcontroller()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/addCardViewControllerFooterView":{"role":"symbol","title":"addCardViewControllerFooterView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewControllerFooterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A view that will be placed as the footer of the add card view controller."},{"type":"text","text":" "},{"type":"text","text":"When the footer view needs to be resized, it will be sent a"},{"type":"text","text":" "},{"type":"codeVoice","code":"sizeThatFits:"},{"type":"text","text":" call. The view should respond correctly to this method in order"},{"type":"text","text":" "},{"type":"text","text":"to be sized and positioned properly."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/addCardViewControllerFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCardViewControllerFooterView"}],"url":"\/documentation\/stripe\/stppaymentcontext\/addcardviewcontrollerfooterview"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentSummaryItems":{"role":"symbol","title":"paymentSummaryItems","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentSummaryItems"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PKPaymentSummaryItem","preciseIdentifier":"c:objc(cs)PKPaymentSummaryItem"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"If you support Apple Pay, you can optionally set the PKPaymentSummaryItems"},{"type":"text","text":" "},{"type":"text","text":"you want to display here instead of using "},{"type":"codeVoice","code":"paymentAmount"},{"type":"text","text":". Note that the"},{"type":"text","text":" "},{"type":"text","text":"grand total (the amount of the last summary item) must be greater than zero."},{"type":"text","text":" "},{"type":"text","text":"If not set, a single summary item will be automatically generated using"},{"type":"text","text":" "},{"type":"codeVoice","code":"paymentAmount"},{"type":"text","text":" and your configuration’s "},{"type":"codeVoice","code":"companyName"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentSummaryItems","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentSummaryItems"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentsummaryitems"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/theme":{"role":"symbol","title":"theme","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"}],"abstract":[{"type":"text","text":"The visual appearance that will be used by any views that the context generates. - seealso: STPTheme.h"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/theme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"theme"}],"url":"\/documentation\/stripe\/stppaymentcontext\/theme"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentCurrency":{"role":"symbol","title":"paymentCurrency","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCurrency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The three-letter currency code for the currency of the payment (i.e. USD, GBP,"},{"type":"text","text":" "},{"type":"text","text":"JPY, etc). Defaults to “USD”."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentCurrency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentCurrency"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentcurrency"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/shippingAddressViewControllerDidCancel(_:)":{"role":"symbol","title":"shippingAddressViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the user cancels entering a shipping address. You should dismiss (or pop) the view controller at this point."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewControllerDidCancel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/shippingaddressviewcontrollerdidcancel(_:)"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContext"}],"url":"\/documentation\/stripe\/stppaymentcontext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAuthenticationContext":{"role":"symbol","title":"STPAuthenticationContext","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAuthenticationContext"}],"abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"type":"text","text":" provides information required to present authentication challenges"},{"type":"text","text":" "},{"type":"text","text":"to a user."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAuthenticationContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAuthenticationContext"}],"url":"\/documentation\/stripe\/stpauthenticationcontext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/hostViewController":{"role":"symbol","title":"hostViewController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The view controller that any additional UI will be presented on. If you have a “checkout view controller” in your app, that should be used as the host view controller."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/hostViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hostViewController"}],"url":"\/documentation\/stripe\/stppaymentcontext\/hostviewcontroller"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/selectedPaymentOption":{"role":"symbol","title":"selectedPaymentOption","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedPaymentOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The user’s currently selected payment option. May be nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/selectedPaymentOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedPaymentOption"}],"url":"\/documentation\/stripe\/stppaymentcontext\/selectedpaymentoption"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/authenticationPresentingViewController()":{"role":"symbol","title":"authenticationPresentingViewController()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"The Stripe SDK will modally present additional view controllers on top"},{"type":"text","text":" "},{"type":"text","text":"of the "},{"type":"codeVoice","code":"authenticationPresentingViewController"},{"type":"text","text":" when required for user"},{"type":"text","text":" "},{"type":"text","text":"authentication, like in the Challenge Flow for 3DS2 transactions."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/authenticationPresentingViewController()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"url":"\/documentation\/stripe\/stppaymentcontext\/authenticationpresentingviewcontroller()"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate":{"role":"symbol","title":"STPPaymentOptionsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentOptionsViewControllerDelegate"},{"type":"text","text":" responds when a user selects a"},{"type":"text","text":" "},{"type":"text","text":"payment option from (or cancels) an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":". In both"},{"type":"text","text":" "},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"type":"text","text":" "},{"type":"text","text":"it off the navigation stack, or dismissing it)."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptionsViewControllerDidFinish(_:)":{"role":"symbol","title":"paymentOptionsViewControllerDidFinish(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user selects or adds a payment method, so it will often"},{"type":"text","text":" "},{"type":"text","text":"be called immediately after calling "},{"type":"codeVoice","code":"paymentOptionsViewController:didSelectPaymentOption:"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You should dismiss the view controller when this is called."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerDidFinish(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish:"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontrollerdidfinish(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/paymentOptionsViewControllerFooterView":{"role":"symbol","title":"paymentOptionsViewControllerFooterView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A view that will be placed as the footer of the payment options selection"},{"type":"text","text":" "},{"type":"text","text":"view controller."},{"type":"text","text":" "},{"type":"text","text":"When the footer view needs to be resized, it will be sent a"},{"type":"text","text":" "},{"type":"codeVoice","code":"sizeThatFits:"},{"type":"text","text":" call. The view should respond correctly to this method in order"},{"type":"text","text":" "},{"type":"text","text":"to be sized and positioned properly."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerFooterView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"}],"url":"\/documentation\/stripe\/stppaymentcontext\/paymentoptionsviewcontrollerfooterview"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext/apiClient":{"role":"symbol","title":"apiClient","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"abstract":[{"type":"text","text":"The API Client to use to make requests."},{"type":"text","text":" "},{"type":"text","text":"Defaults to STPAPIClient.shared"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/apiClient","kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stppaymentcontext\/apiclient"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentContext"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/addCardViewControllerFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/apiAdapter","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/applePayLaterAvailability","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/configuration","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/defaultPaymentMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/delegate","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/hostViewController","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/largeTitleDisplayMode","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/loading","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/modalPresentationStyle","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentAmount","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentCountry","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentCurrency","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptions","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerFooterView","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentSummaryItems","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/prefilledInformation","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/selectedPaymentOption","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/selectedShippingMethod","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddress","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingMethods","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/theme"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/authenticationPresentingViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(apiAdapter:configuration:theme:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/init(customerContext:configuration:theme:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didFailToLoadWithError:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewController(_:didSelect:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerDidCancel(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/paymentOptionsViewControllerDidFinish(_:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/prepare(forPresentation:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentPaymentOptionsViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/presentShippingViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/pushPaymentOptionsViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/pushShippingViewController()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/requestPayment()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/retryLoading()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didEnter:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext\/shippingAddressViewControllerDidCancel(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(apiAdapter:configuration:theme:)\/title","value":"initWithApiAdapter:configuration:theme:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(apiAdapter:configuration:theme:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithApiAdapter:configuration:theme:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingMethods\/title","value":"shippingMethods"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingMethods\/fragments","value":[{"kind":"identifier","text":"shippingMethods"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(customerContext:configuration:theme:)\/title","value":"initWithCustomerContext:configuration:theme:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(customerContext:configuration:theme:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCustomerContext:configuration:theme:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewControllerDidCancel(_:)\/title","value":"paymentOptionsViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/title","value":"STPShippingAddressViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1applePayLaterAvailability\/title","value":"applePayLaterAvailability"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1applePayLaterAvailability\/fragments","value":[{"kind":"identifier","text":"applePayLaterAvailability"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentCountry\/title","value":"paymentCountry"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentCountry\/fragments","value":[{"kind":"identifier","text":"paymentCountry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1defaultPaymentMethod\/title","value":"defaultPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1defaultPaymentMethod\/fragments","value":[{"kind":"identifier","text":"defaultPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewController(_:didSelect:)\/title","value":"paymentOptionsViewController:didSelectPaymentOption:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewController(_:didSelect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1largeTitleDisplayMode\/title","value":"largeTitleDisplayMode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1largeTitleDisplayMode\/fragments","value":[{"kind":"identifier","text":"largeTitleDisplayMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1prepare(forPresentation:)\/title","value":"prepareAuthenticationContextForPresentation:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1prepare(forPresentation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareAuthenticationContextForPresentation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1presentPaymentOptionsViewController()\/title","value":"presentPaymentOptionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1presentPaymentOptionsViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentPaymentOptionsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentAmount\/title","value":"paymentAmount"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentAmount\/fragments","value":[{"kind":"identifier","text":"paymentAmount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1modalPresentationStyle\/title","value":"modalPresentationStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1modalPresentationStyle\/fragments","value":[{"kind":"identifier","text":"modalPresentationStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1selectedShippingMethod\/title","value":"selectedShippingMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1selectedShippingMethod\/fragments","value":[{"kind":"identifier","text":"selectedShippingMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewController(_:didFailToLoadWithError:)\/title","value":"paymentOptionsViewController:didFailToLoadWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewController(_:didFailToLoadWithError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didFailToLoadWithError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewController(_:didEnter:completion:)\/title","value":"shippingAddressViewController:didEnterAddress:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewController(_:didEnter:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(customerContext:)\/title","value":"initWithCustomerContext:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(customerContext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCustomerContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1retryLoading()\/title","value":"retryLoading"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1retryLoading()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retryLoading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1prefilledInformation\/title","value":"prefilledInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1prefilledInformation\/fragments","value":[{"kind":"identifier","text":"prefilledInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1presentShippingViewController()\/title","value":"presentShippingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1presentShippingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentShippingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1pushShippingViewController()\/title","value":"pushShippingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1pushShippingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushShippingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1configuration\/title","value":"configuration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1configuration\/fragments","value":[{"kind":"identifier","text":"configuration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1apiAdapter\/title","value":"apiAdapter"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1apiAdapter\/fragments","value":[{"kind":"identifier","text":"apiAdapter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewController(_:didFinishWith:shippingMethod:)\/title","value":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewController(_:didFinishWith:shippingMethod:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptions\/title","value":"paymentOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptions\/fragments","value":[{"kind":"identifier","text":"paymentOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1loading\/title","value":"loading"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1loading\/fragments","value":[{"kind":"identifier","text":"loading"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(apiAdapter:)\/title","value":"initWithApiAdapter:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1init(apiAdapter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithApiAdapter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1requestPayment()\/title","value":"requestPayment"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1requestPayment()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestPayment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddress\/title","value":"shippingAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddress\/fragments","value":[{"kind":"identifier","text":"shippingAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1pushPaymentOptionsViewController()\/title","value":"pushPaymentOptionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1pushPaymentOptionsViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pushPaymentOptionsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1addCardViewControllerFooterView\/title","value":"addCardViewControllerFooterView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1addCardViewControllerFooterView\/fragments","value":[{"kind":"identifier","text":"addCardViewControllerFooterView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentSummaryItems\/title","value":"paymentSummaryItems"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentSummaryItems\/fragments","value":[{"kind":"identifier","text":"paymentSummaryItems"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1theme\/title","value":"theme"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1theme\/fragments","value":[{"kind":"identifier","text":"theme"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentCurrency\/title","value":"paymentCurrency"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentCurrency\/fragments","value":[{"kind":"identifier","text":"paymentCurrency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewControllerDidCancel(_:)\/title","value":"shippingAddressViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1shippingAddressViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1hostViewController\/title","value":"hostViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1hostViewController\/fragments","value":[{"kind":"identifier","text":"hostViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1selectedPaymentOption\/title","value":"selectedPaymentOption"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1selectedPaymentOption\/fragments","value":[{"kind":"identifier","text":"selectedPaymentOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1authenticationPresentingViewController()\/title","value":"authenticationPresentingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1authenticationPresentingViewController()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationPresentingViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/title","value":"STPPaymentOptionsViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewControllerDidFinish(_:)\/title","value":"paymentOptionsViewControllerDidFinish:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewControllerDidFinish(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewControllerFooterView\/title","value":"paymentOptionsViewControllerFooterView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext~1paymentOptionsViewControllerFooterView\/fragments","value":[{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
