{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/s8SendableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIScrollViewDelegate","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDataSource","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDelegate","doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(paymentContext:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/delegate"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/dismiss(withCompletion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:heightForHeaderInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/viewDidAppear(_:)"],"title":"Instance Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/UITableViewDataSource-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/UITableViewDelegate-Implementations"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController"},"sections":[],"abstract":[{"type":"text","text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPShippingAddressViewController","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpshippingaddressviewcontroller"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"class","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPShippingAddressViewController","title":"STPShippingAddressViewController","navigatorTitle":[{"text":"STPShippingAddressViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPShippingAddressViewController","kind":"identifier"}],"roleHeading":"Class"},"references":{"doc://com.stripe.stripe-ios/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/tableView(_:heightForHeaderInSection:)":{"role":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"title":"tableView(_:heightForHeaderInSection:)","navigatorTitle":[{"text":"tableView:heightForHeaderInSection:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:heightForHeaderInSection:)","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/tableview(_:heightforheaderinsection:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForHeaderInSection"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIAppearanceContainer"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/init()":{"role":"symbol","abstract":[{"type":"text","text":"A convenience initializer; equivalent to calling "},{"code":"init(configuration: STPPaymentConfiguration.shared theme: STPTheme.defaultTheme currency:\"\" shippingAddress:nil selectedShippingMethod:nil prefilledInformation:nil)","type":"codeVoice"},{"type":"text","text":"."}],"title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init()","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/UITableViewDelegate-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/UITableViewDelegate-Implementations","abstract":[],"title":"UITableViewDelegate Implementations","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/uitableviewdelegate-implementations","type":"topic","role":"collectionGroup","kind":"article"},"doc://com.stripe.stripe-ios/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-ios/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/dismiss(withCompletion:)":{"role":"symbol","abstract":[{"text":"If you’re pushing ","type":"text"},{"code":"STPShippingAddressViewController","type":"codeVoice"},{"type":"text","text":" onto an existing "},{"type":"codeVoice","code":"UINavigationController"},{"text":"‘s stack, you should use this method to dismiss it, since it may have pushed an additional shipping method view controller onto the navigation controller’s stack.","type":"text"}],"title":"dismiss(withCompletion:)","navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/dismiss(withCompletion:)","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/dismiss(withcompletion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withCompletion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPVoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/objc(pl)UITableViewDataSource":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDataSource","title":"UITableViewDataSource","type":"unresolvable"},"doc://com.stripe.stripe-ios/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-ios/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.stripe.stripe-ios/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://com.stripe.stripe-ios/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/init(paymentContext:)":{"role":"symbol","abstract":[{"text":"Initializes a new ","type":"text"},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" with the given payment context and sets the payment context as its delegate."}],"title":"init(paymentContext:)","navigatorTitle":[{"kind":"identifier","text":"initWithPaymentContext:"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(paymentContext:)","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/init(paymentcontext:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paymentContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","kind":"typeIdentifier","text":"STPPaymentContext"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/delegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"text":"STPShippingAddressViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPShippingAddressViewControllerDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"The view controller’s delegate. This must be set before showing the view controller in order for it to work properly. - seealso: STPShippingAddressViewControllerDelegate","type":"text"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/delegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/delegate"},"doc://com.stripe.stripe-ios/SQ":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-ios/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/UITableViewDataSource-Implementations":{"role":"collectionGroup","abstract":[],"title":"UITableViewDataSource Implementations","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/UITableViewDataSource-Implementations","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/uitableviewdatasource-implementations","kind":"article"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)":{"role":"symbol","abstract":[{"type":"text","text":"Initializes a new "},{"code":"STPShippingAddressCardViewController","type":"codeVoice"},{"text":" with the provided parameters.","type":"text"}],"title":"init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)","navigatorTitle":[{"text":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/init(configuration:theme:currency:shippingaddress:selectedshippingmethod:prefilledinformation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"text":", ","kind":"text"},{"text":"theme","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"shippingAddress"},{"kind":"text","text":": "},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"selectedShippingMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PKShippingMethod","kind":"typeIdentifier","text":"PKShippingMethod"},{"kind":"text","text":"?, "},{"text":"prefilledInformation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPUserInformation","kind":"typeIdentifier","text":"STPUserInformation"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/objc(pl)UIScrollViewDelegate":{"title":"UIKit.UIScrollViewDelegate","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIScrollViewDelegate"},"doc://com.stripe.stripe-ios/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIStateRestoring"},"doc://com.stripe.stripe-ios/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIFocusEnvironment"},"doc://com.stripe.stripe-ios/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITraitEnvironment"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController/viewDidAppear(_:)":{"role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"title":"viewDidAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/viewDidAppear(_:)","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller\/viewdidappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController":{"kind":"symbol","abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It inherits from STPCoreScrollViewController and changes the type of the"},{"type":"text","text":" "},{"text":"created scroll view to UITableView, as well as other shared table view logic.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","role":"symbol","title":"STPCoreTableViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreTableViewController"}]},"doc://com.stripe.stripe-ios/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewController":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"type":"topic","abstract":[{"text":"This view controller contains a shipping address collection form. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":". Depending on your configuration’s shippingType, the view controller may present a shipping method selection form after the user enters an address."}],"title":"STPShippingAddressViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController","url":"\/documentation\/stripe\/stpshippingaddressviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPShippingAddressViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-ios/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s8SendableP","title":"Swift.Sendable"},"doc://com.stripe.stripe-ios/objc(pl)UITableViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDelegate","title":"UITableViewDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPShippingAddressViewController"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPShippingAddressViewController"}],"path":"\/metadata\/fragments"},{"value":[{"text":"STPShippingAddressViewController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/delegate"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/dismiss(withCompletion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init()","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/init(paymentContext:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/tableView(_:heightForHeaderInSection:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/viewDidAppear(_:)"],"title":"Instance Methods"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/UITableViewDataSource-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewController\/UITableViewDelegate-Implementations"]}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDataSource","doc:\/\/com.stripe.stripe-ios\/objc(pl)UITableViewDelegate"],"type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewController"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","text":"STPCoreTableViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCoreTableViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"tableView:heightForHeaderInSection:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1tableView(_:heightForHeaderInSection:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1tableView(_:heightForHeaderInSection:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:heightForHeaderInSection:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init()\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1dismiss(withCompletion:)\/title","op":"replace","value":"dismissWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1dismiss(withCompletion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dismissWithCompletion:","kind":"identifier"}]},{"value":"initWithPaymentContext:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init(paymentContext:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init(paymentContext:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPaymentContext:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1delegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)\/title","value":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1init(configuration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:theme:currency:shippingAddress:selectedShippingMethod:prefilledInformation:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController~1viewDidAppear(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/title","op":"replace","value":"STPCoreTableViewController"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCoreTableViewController"}]},{"value":"STPShippingAddressViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewController\/fragments","value":[{"text":"STPShippingAddressViewController","kind":"identifier"}],"op":"replace"}]}]}
