{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPShippingAddressViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" receives an address, completes with an address, or is cancelled."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"title":"STPShippingAddressViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@Stripe@objc(pl)STPShippingAddressViewControllerDelegate","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didEnter:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewControllerDidCancel(_:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate":{"role":"symbol","title":"STPShippingAddressViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPShippingAddressViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPShippingAddressViewController"},{"type":"text","text":" receives an address, completes with an address, or is cancelled."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate/shippingAddressViewController(_:didFinishWith:shippingMethod:)":{"navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"}],"role":"symbol","title":"shippingAddressViewController(_:didFinishWith:shippingMethod:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PKShippingMethod","preciseIdentifier":"c:objc(cs)PKShippingMethod"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"This is called when the user selects a shipping method. If no shipping methods are given, or if the shipping type doesn’t require a shipping method, this will be called after the user has a shipping address and your validation has succeeded. After updating your app with the user’s shipping info, you should dismiss (or pop) the view controller. Note that if "},{"type":"codeVoice","code":"shippingMethod"},{"type":"text","text":" is non-nil, there will be an additional shipping methods view controller on the navigation controller’s stack."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontroller(_:didfinishwith:shippingmethod:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","title":"STPPaymentContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentContext"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and modifying the customer."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContext"}],"url":"\/documentation\/stripe\/stppaymentcontext"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate/shippingAddressViewController(_:didEnter:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}],"role":"symbol","title":"shippingAddressViewController(_:didEnter:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user enters a shipping address and taps next. You"},{"type":"text","text":" "},{"type":"text","text":"should validate the address and determine what shipping methods are available,"},{"type":"text","text":" "},{"type":"text","text":"and call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when finished. If an error occurrs, call"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block with the error. Otherwise, call the "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" "},{"type":"text","text":"block with a nil error and an array of available shipping methods. If you don’t"},{"type":"text","text":" "},{"type":"text","text":"need to collect a shipping method, you may pass an empty array or nil."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didEnter:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontroller(_:didenter:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingAddressViewControllerDelegate/shippingAddressViewControllerDidCancel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"}],"role":"symbol","title":"shippingAddressViewControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPShippingAddressViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPShippingAddressViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the user cancels entering a shipping address. You should dismiss (or pop) the view controller at this point."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewControllerDidCancel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpshippingaddressviewcontrollerdelegate\/shippingaddressviewcontrollerdidcancel(_:)"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"STPShippingAddressViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didEnter:completion:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewController(_:didFinishWith:shippingMethod:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingAddressViewControllerDelegate\/shippingAddressViewControllerDidCancel(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/title","value":"STPShippingAddressViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPShippingAddressViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewController(_:didFinishWith:shippingMethod:)\/title","value":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewController(_:didFinishWith:shippingMethod:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didFinishWithAddress:shippingMethod:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewController(_:didEnter:completion:)\/title","value":"shippingAddressViewController:didEnterAddress:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewController(_:didEnter:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewController:didEnterAddress:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewControllerDidCancel(_:)\/title","value":"shippingAddressViewControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingAddressViewControllerDelegate~1shippingAddressViewControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shippingAddressViewControllerDidCancel:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
