{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpshippingstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpshippingstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An enum representing the status of a shipping address validation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingStatus"}],"title":"STPShippingStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@Stripe@E@STPShippingStatus","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPShippingStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/invalid","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/valid"]},{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus/valid":{"role":"symbol","title":"STPShippingStatus.valid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"abstract":[{"type":"text","text":"The shipping address is valid."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/valid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingStatusValid"}],"url":"\/documentation\/stripe\/stpshippingstatus\/valid"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpshippingstatus\/rawrepresentable-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-ios\/SY"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus/invalid":{"role":"symbol","title":"STPShippingStatus.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"The shipping address is invalid."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingStatusInvalid"}],"url":"\/documentation\/stripe\/stpshippingstatus\/invalid"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpshippingstatus\/equatable-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpshippingstatus\/customstringconvertible-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stpshippingstatus\/init(rawvalue:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus":{"role":"symbol","title":"STPShippingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingStatus"}],"abstract":[{"type":"text","text":"An enum representing the status of a shipping address validation."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingStatus"}],"url":"\/documentation\/stripe\/stpshippingstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPShippingStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPShippingStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPShippingStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/invalid","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/valid"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus~1valid\/title","value":"STPShippingStatusValid"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus~1valid\/fragments","value":[{"kind":"identifier","text":"STPShippingStatusValid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus~1invalid\/title","value":"STPShippingStatusInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus~1invalid\/fragments","value":[{"kind":"identifier","text":"STPShippingStatusInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus\/title","value":"STPShippingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus\/fragments","value":[{"kind":"identifier","text":"STPShippingStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
