{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpshippingtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpshippingtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH","doc:\/\/com.stripe.stripe-ios\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"These values control the labels used in the shipping info collection form."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingType"}],"title":"STPShippingType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@Stripe@E@STPShippingType","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPShippingType"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/delivery","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/shipping"]},{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType/shipping":{"role":"symbol","title":"STPShippingType.shipping","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"}],"abstract":[{"type":"text","text":"Shipping the purchase to the provided address using a third-party"},{"type":"text","text":" "},{"type":"text","text":"shipping company."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/shipping","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingTypeShipping"}],"url":"\/documentation\/stripe\/stpshippingtype\/shipping"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpshippingtype\/customstringconvertible-implementations"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpshippingtype\/equatable-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stpshippingtype\/rawrepresentable-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType":{"role":"symbol","title":"STPShippingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingType"}],"abstract":[{"type":"text","text":"These values control the labels used in the shipping info collection form."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingType"}],"url":"\/documentation\/stripe\/stpshippingtype"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stpshippingtype\/init(rawvalue:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType/delivery":{"role":"symbol","title":"STPShippingType.delivery","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delivery"}],"abstract":[{"type":"text","text":"Delivering the purchase by the seller."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/delivery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingTypeDelivery"}],"url":"\/documentation\/stripe\/stpshippingtype\/delivery"},"doc://com.stripe.stripe-ios/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-ios\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPShippingType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPShippingType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPShippingType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/delivery","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType\/shipping"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType~1shipping\/title","value":"STPShippingTypeShipping"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType~1shipping\/fragments","value":[{"kind":"identifier","text":"STPShippingTypeShipping"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType\/title","value":"STPShippingType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType\/fragments","value":[{"kind":"identifier","text":"STPShippingType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType~1delivery\/title","value":"STPShippingTypeDelivery"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType~1delivery\/fragments","value":[{"kind":"identifier","text":"STPShippingTypeDelivery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
