{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTheme"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stptheme"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stptheme"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTheme"}],"title":"STPTheme","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@Stripe@objc(cs)STPTheme","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/accentColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/barStyle","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/emphasisFont","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/errorColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/font","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/largeFont","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/primaryBackgroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/primaryForegroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/quaternaryBackgroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/secondaryBackgroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/secondaryForegroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/smallFont","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/tertiaryBackgroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/tertiaryForegroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/translucentNavigationBar"]},{"title":"Type Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/defaultTheme"]},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/default()"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/NSCopying-Implementations"],"generated":true}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/translucentNavigationBar":{"role":"symbol","title":"translucentNavigationBar","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"translucentNavigationBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether the navigation bar for any view controllers"},{"type":"text","text":" "},{"type":"text","text":"presented modally by the SDK should be translucent. The default value is YES."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/translucentNavigationBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"translucentNavigationBar"}],"url":"\/documentation\/stripe\/stptheme\/translucentnavigationbar"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/errorColor":{"role":"symbol","title":"errorColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The error color of this theme - it will be used for rendering any error messages or views."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/errorColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorColor"}],"url":"\/documentation\/stripe\/stptheme\/errorcolor"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/smallFont":{"role":"symbol","title":"smallFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[{"type":"text","text":"This font is automatically derived from the font, with a slightly lower point size, and will be used for supplementary labels."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/smallFont","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"smallFont"}],"url":"\/documentation\/stripe\/stptheme\/smallfont"},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/largeFont":{"role":"symbol","title":"largeFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"largeFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[{"type":"text","text":"This font is automatically derived from the font, with a larger point size, and will be used for large labels such as SMS code entry."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/largeFont","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"largeFont"}],"url":"\/documentation\/stripe\/stptheme\/largefont"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/primaryBackgroundColor":{"role":"symbol","title":"primaryBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The primary background color of the theme. This will be used as the "},{"type":"codeVoice","code":"backgroundColor"},{"type":"text","text":" for any views with this theme."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/primaryBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primaryBackgroundColor"}],"url":"\/documentation\/stripe\/stptheme\/primarybackgroundcolor"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"role":"symbol","title":"STPTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTheme"}],"abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}],"url":"\/documentation\/stripe\/stptheme"},"doc://com.stripe.stripe-ios/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/stripe\/stptheme\/init"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/tertiaryBackgroundColor":{"role":"symbol","title":"tertiaryBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tertiaryBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"This color is automatically derived by reducing the alpha of the "},{"type":"codeVoice","code":"primaryBackgroundColor"},{"type":"text","text":" and is used as a section border color in table view cells."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/tertiaryBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tertiaryBackgroundColor"}],"url":"\/documentation\/stripe\/stptheme\/tertiarybackgroundcolor"},"doc://com.stripe.stripe-ios/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-ios\/SQ"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/quaternaryBackgroundColor":{"role":"symbol","title":"quaternaryBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quaternaryBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"This color is automatically derived by reducing the brightness of the "},{"type":"codeVoice","code":"primaryBackgroundColor"},{"type":"text","text":" and is used as a separator color in table view cells."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/quaternaryBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"quaternaryBackgroundColor"}],"url":"\/documentation\/stripe\/stptheme\/quaternarybackgroundcolor"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/accentColor":{"role":"symbol","title":"accentColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accentColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The accent color of this theme - it will be used for any buttons and other elements on a view that are important to highlight."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/accentColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accentColor"}],"url":"\/documentation\/stripe\/stptheme\/accentcolor"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/font":{"role":"symbol","title":"font","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[{"type":"text","text":"The font to be used for all views using this theme. Make sure to select an appropriate size."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/font","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"font"}],"url":"\/documentation\/stripe\/stptheme\/font"},"doc://com.stripe.stripe-ios/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-ios\/SH"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/primaryForegroundColor":{"role":"symbol","title":"primaryForegroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryForegroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The primary foreground color of this theme. This will be used as the text color for any important labels in a view with this theme (such as the text color for a text field that the user needs to fill out)."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/primaryForegroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primaryForegroundColor"}],"url":"\/documentation\/stripe\/stptheme\/primaryforegroundcolor"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/NSCopying-Implementations":{"role":"collectionGroup","title":"NSCopying Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/NSCopying-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripe\/stptheme\/nscopying-implementations"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/defaultTheme":{"role":"symbol","title":"defaultTheme","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"}],"abstract":[{"type":"text","text":"The default theme used by all Stripe UI. All themable UI classes, such as "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":", have one initializer that takes a "},{"type":"codeVoice","code":"theme"},{"type":"text","text":" and one that does not. If you use the one that does not, the default theme will be used to customize that view controller’s appearance."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/defaultTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultTheme"}],"url":"\/documentation\/stripe\/stptheme\/defaulttheme"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/tertiaryForegroundColor":{"role":"symbol","title":"tertiaryForegroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tertiaryForegroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"This color is automatically derived from the "},{"type":"codeVoice","code":"secondaryForegroundColor"},{"type":"text","text":" with a lower alpha component, used for disabled text."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/tertiaryForegroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tertiaryForegroundColor"}],"url":"\/documentation\/stripe\/stptheme\/tertiaryforegroundcolor"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/barStyle":{"role":"symbol","title":"barStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarStyle","preciseIdentifier":"c:@E@UIBarStyle"}],"abstract":[{"type":"text","text":"The navigation bar style to use for any view controllers presented modally"},{"type":"text","text":" "},{"type":"text","text":"by the SDK. The default value will be determined based on the brightness"},{"type":"text","text":" "},{"type":"text","text":"of the theme’s "},{"type":"codeVoice","code":"secondaryBackgroundColor"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/barStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"barStyle"}],"url":"\/documentation\/stripe\/stptheme\/barstyle"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/secondaryForegroundColor":{"role":"symbol","title":"secondaryForegroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryForegroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The secondary foreground color of this theme. This will be used as the text color for any supplementary labels in a view with this theme (such as the placeholder color for a text field that the user needs to fill out)."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/secondaryForegroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secondaryForegroundColor"}],"url":"\/documentation\/stripe\/stptheme\/secondaryforegroundcolor"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/secondaryBackgroundColor":{"role":"symbol","title":"secondaryBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The secondary background color of this theme. This will be used as the "},{"type":"codeVoice","code":"backgroundColor"},{"type":"text","text":" for any supplemental views inside a view with this theme - for example, a "},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" will set it’s cells’ background color to this value."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/secondaryBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secondaryBackgroundColor"}],"url":"\/documentation\/stripe\/stptheme\/secondarybackgroundcolor"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/emphasisFont":{"role":"symbol","title":"emphasisFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"emphasisFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[{"type":"text","text":"The medium-weight font to be used for all bold text in views using this theme. Make sure to select an appropriate size."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/emphasisFont","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"emphasisFont"}],"url":"\/documentation\/stripe\/stptheme\/emphasisfont"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/default()":{"role":"symbol","title":"default()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/default()","kind":"symbol","type":"topic","deprecated":false,"url":"\/documentation\/stripe\/stptheme\/default()"},"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject"},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPTheme"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPTheme"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPTheme"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/accentColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/barStyle","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/emphasisFont","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/errorColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/font","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/largeFont","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/primaryBackgroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/primaryForegroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/quaternaryBackgroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/secondaryBackgroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/secondaryForegroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/smallFont","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/tertiaryBackgroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/tertiaryForegroundColor","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/translucentNavigationBar"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/init"]},{"title":"Type Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/defaultTheme"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/NSCopying-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTheme"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1translucentNavigationBar\/title","value":"translucentNavigationBar"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1translucentNavigationBar\/fragments","value":[{"kind":"identifier","text":"translucentNavigationBar"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1errorColor\/title","value":"errorColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1errorColor\/fragments","value":[{"kind":"identifier","text":"errorColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1smallFont\/title","value":"smallFont"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1smallFont\/fragments","value":[{"kind":"identifier","text":"smallFont"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1largeFont\/title","value":"largeFont"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1largeFont\/fragments","value":[{"kind":"identifier","text":"largeFont"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1primaryBackgroundColor\/title","value":"primaryBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1primaryBackgroundColor\/fragments","value":[{"kind":"identifier","text":"primaryBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","value":"STPTheme"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","value":[{"kind":"identifier","text":"STPTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1tertiaryBackgroundColor\/title","value":"tertiaryBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1tertiaryBackgroundColor\/fragments","value":[{"kind":"identifier","text":"tertiaryBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1quaternaryBackgroundColor\/title","value":"quaternaryBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1quaternaryBackgroundColor\/fragments","value":[{"kind":"identifier","text":"quaternaryBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1accentColor\/title","value":"accentColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1accentColor\/fragments","value":[{"kind":"identifier","text":"accentColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1font\/title","value":"font"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1font\/fragments","value":[{"kind":"identifier","text":"font"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1primaryForegroundColor\/title","value":"primaryForegroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1primaryForegroundColor\/fragments","value":[{"kind":"identifier","text":"primaryForegroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1defaultTheme\/title","value":"defaultTheme"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1defaultTheme\/fragments","value":[{"kind":"identifier","text":"defaultTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1tertiaryForegroundColor\/title","value":"tertiaryForegroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1tertiaryForegroundColor\/fragments","value":[{"kind":"identifier","text":"tertiaryForegroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1barStyle\/title","value":"barStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1barStyle\/fragments","value":[{"kind":"identifier","text":"barStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1secondaryForegroundColor\/title","value":"secondaryForegroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1secondaryForegroundColor\/fragments","value":[{"kind":"identifier","text":"secondaryForegroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1secondaryBackgroundColor\/title","value":"secondaryBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1secondaryBackgroundColor\/fragments","value":[{"kind":"identifier","text":"secondaryBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1emphasisFont\/title","value":"emphasisFont"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1emphasisFont\/fragments","value":[{"kind":"identifier","text":"emphasisFont"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
