{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPUserInformation","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-ios\/s7CVarArgP","doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-ios\/SQ","doc:\/\/com.stripe.stripe-ios\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"You can use this class to specify information that you’ve already collected"},{"text":" ","type":"text"},{"text":"from your user. You can then set the ","type":"text"},{"type":"codeVoice","code":"prefilledInformation"},{"text":" property on","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":", etc and it will pre-fill"},{"text":" ","type":"text"},{"text":"this information whenever possible.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/billingAddress","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/shippingAddress"]},{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/copy(with:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/setBillingAddress(with:)"],"title":"Instance Methods"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpuserinformation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpuserinformation"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPUserInformation"}],"externalID":"c:@M@Stripe@objc(cs)STPUserInformation","modules":[{"name":"Stripe"}],"role":"symbol","title":"STPUserInformation","navigatorTitle":[{"text":"STPUserInformation","kind":"identifier"}],"roleHeading":"Class"},"references":{"doc://com.stripe.stripe-ios/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation/init":{"role":"symbol","url":"\/documentation\/stripe\/stpuserinformation\/init","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/init"},"doc://com.stripe.stripe-ios/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-ios/SQ":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation/setBillingAddress(with:)":{"kind":"symbol","navigatorTitle":[{"text":"setBillingAddressWithBillingDetails:","kind":"identifier"}],"url":"\/documentation\/stripe\/stpuserinformation\/setbillingaddress(with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setBillingAddress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":")"}],"abstract":[{"text":"A convenience method to populate ","type":"text"},{"type":"codeVoice","code":"billingAddress"},{"type":"text","text":" with a PaymentMethod’s billing details."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/setBillingAddress(with:)","title":"setBillingAddress(with:)","type":"topic"},"doc://com.stripe.stripe-ios/SH":{"identifier":"doc:\/\/com.stripe.stripe-ios\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation/billingAddress":{"kind":"symbol","abstract":[{"text":"The user’s billing address. When set, the add card form will be filled with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"this address. The user will also have the option to fill their shipping address"},{"type":"text","text":" "},{"text":"using this address.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"billingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/billingAddress","url":"\/documentation\/stripe\/stpuserinformation\/billingaddress","role":"symbol","title":"billingAddress","type":"topic","navigatorTitle":[{"kind":"identifier","text":"billingAddress"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation":{"title":"STPUserInformation","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPUserInformation"}],"abstract":[{"type":"text","text":"You can use this class to specify information that you’ve already collected"},{"text":" ","type":"text"},{"type":"text","text":"from your user. You can then set the "},{"code":"prefilledInformation","type":"codeVoice"},{"type":"text","text":" property on"},{"text":" ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPAddCardViewController"},{"text":", etc and it will pre-fill","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"this information whenever possible."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPUserInformation","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripe\/stpuserinformation"},"doc://com.stripe.stripe-ios/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-ios\/s7CVarArgP"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation/copy(with:)":{"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/copy(with:)","url":"\/documentation\/stripe\/stpuserinformation\/copy(with:)","role":"symbol","title":"copy(with:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation/shippingAddress":{"kind":"symbol","abstract":[{"type":"text","text":"The user’s shipping address. When set, the shipping address form will be filled"},{"type":"text","text":" "},{"type":"text","text":"with this address. The user will also have the option to fill their billing"},{"text":" ","type":"text"},{"text":"address using this address.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shippingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","text":"STPAddress"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/shippingAddress","url":"\/documentation\/stripe\/stpuserinformation\/shippingaddress","role":"symbol","title":"shippingAddress","type":"topic","navigatorTitle":[{"text":"shippingAddress","kind":"identifier"}]},"doc://com.stripe.stripe-ios/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-ios\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-ios/objc(pl)NSCopying":{"identifier":"doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"STPUserInformation","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPUserInformation","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPUserInformation"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/billingAddress","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/shippingAddress"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/copy(with:)","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/init","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/setBillingAddress(with:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-ios\/objc(pl)NSCopying"],"kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPUserInformation"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1setBillingAddress(with:)\/title","value":"setBillingAddressWithBillingDetails:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1setBillingAddress(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setBillingAddressWithBillingDetails:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1billingAddress\/title","value":"billingAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1billingAddress\/fragments","value":[{"text":"billingAddress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/title","value":"STPUserInformation","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/fragments","value":[{"text":"STPUserInformation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1copy(with:)\/title","op":"replace","value":"copyWithZone:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"copyWithZone:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1copy(with:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1shippingAddress\/title","value":"shippingAddress"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1shippingAddress\/fragments","value":[{"text":"shippingAddress","kind":"identifier"}],"op":"replace"}]}]}
