{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(paymentOptionsViewController:didSelectPaymentOption:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentOptionsViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","text":"STPPaymentOption"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"paymentOptionsViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the view controller in question"}]}]},{"name":"paymentOption","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the selected payment method"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontroller(_:didselect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontroller(_:didselect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didSelect:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is called when the user either makes a selection, or adds a new card."},{"type":"text","text":" "},{"type":"text","text":"This will be triggered after the view controller loads with the user’s current"},{"type":"text","text":" "},{"type":"text","text":"selection (if they have one) and then subsequently when they change their"},{"type":"text","text":" "},{"type":"text","text":"choice. You should use this callback to update any necessary UI in your app"},{"type":"text","text":" "},{"type":"text","text":"that displays the user’s currently selected payment method. You should "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" "},{"type":"text","text":"dismiss the view controller at this point, instead do this in"},{"type":"text","text":" "},{"type":"codeVoice","code":"paymentOptionsViewControllerDidFinish:"},{"type":"text","text":". "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"will also call the necessary methods on your API adapter, so you don’t need to"},{"type":"text","text":" "},{"type":"text","text":"call them directly during this method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"kind":"text","text":")"}],"title":"paymentOptionsViewController(_:didSelect:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate(im)paymentOptionsViewController:didSelectPaymentOption:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate":{"role":"symbol","title":"STPPaymentOptionsViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentOptionsViewControllerDelegate"},{"type":"text","text":" responds when a user selects a"},{"type":"text","text":" "},{"type":"text","text":"payment option from (or cancels) an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":". In both"},{"type":"text","text":" "},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"type":"text","text":" "},{"type":"text","text":"it off the navigation stack, or dismissing it)."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate/paymentOptionsViewController(_:didSelect:)":{"role":"symbol","title":"paymentOptionsViewController(_:didSelect:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user either makes a selection, or adds a new card."},{"type":"text","text":" "},{"type":"text","text":"This will be triggered after the view controller loads with the user’s current"},{"type":"text","text":" "},{"type":"text","text":"selection (if they have one) and then subsequently when they change their"},{"type":"text","text":" "},{"type":"text","text":"choice. You should use this callback to update any necessary UI in your app"},{"type":"text","text":" "},{"type":"text","text":"that displays the user’s currently selected payment method. You should "},{"type":"emphasis","inlineContent":[{"type":"text","text":"not"}]},{"type":"text","text":" "},{"type":"text","text":"dismiss the view controller at this point, instead do this in"},{"type":"text","text":" "},{"type":"codeVoice","code":"paymentOptionsViewControllerDidFinish:"},{"type":"text","text":". "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"will also call the necessary methods on your API adapter, so you don’t need to"},{"type":"text","text":" "},{"type":"text","text":"call them directly during this method."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didSelect:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontroller(_:didselect:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"role":"symbol","title":"STPPaymentOptionsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"type":"text","text":" "},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":", so you can either"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"as the "},{"type":"codeVoice","code":"rootViewController"},{"type":"text","text":" and then present the "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" onto an existing"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"type":"codeVoice","code":"presentPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption":{"role":"symbol","title":"STPPaymentOption","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOption"}],"abstract":[{"type":"text","text":"This protocol represents a payment method that a user can select and use to"},{"type":"text","text":" "},{"type":"text","text":"pay."},{"type":"text","text":" "},{"type":"text","text":"The classes that conform to it and are supported by the UI:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOption"}],"url":"\/documentation\/stripe\/stppaymentoption"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"paymentOptionsViewController:didSelectPaymentOption:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentOptionsViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentOptionsViewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectPaymentOption:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<STPPaymentOption>","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPPaymentOption"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentOption"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/title","value":"STPPaymentOptionsViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewController(_:didSelect:)\/title","value":"paymentOptionsViewController:didSelectPaymentOption:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewController(_:didSelect:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didSelectPaymentOption:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","value":"STPPaymentOptionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/title","value":"STPPaymentOption"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/fragments","value":[{"kind":"identifier","text":"STPPaymentOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
