{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontroller(_:didfailtoloadwitherror:)"]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontroller(_:didfailtoloadwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"This is called when the view controller encounters an error fetching the user’s","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment options from its API adapter. You should dismiss the view controller"},{"type":"text","text":" "},{"type":"text","text":"when this is called."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentOptionsViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentOptionsViewController"},{"kind":"text","text":": "},{"text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"},{"text":", ","kind":"text"},{"text":"didFailToLoadWithError","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"paymentOptionsViewController","content":[{"inlineContent":[{"type":"text","text":"the view controller in question"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"the error that occurred"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didFailToLoadWithError:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"paymentOptionsViewController:didFailToLoadWithError:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","required":true,"role":"symbol","title":"paymentOptionsViewController(_:didFailToLoadWithError:)","externalID":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate(im)paymentOptionsViewController:didFailToLoadWithError:","modules":[{"name":"Stripe"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"text":"didFailToLoadWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"title":"STPPaymentOptionsViewController","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller","navigatorTitle":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","role":"symbol","abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"text":" ","type":"text"},{"text":"which they can select between. They can also add credit cards to the list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":", so you can either","type":"text"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"as the ","type":"text"},{"type":"codeVoice","code":"rootViewController"},{"text":" and then present the ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"text":"or push a new ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate/paymentOptionsViewController(_:didFailToLoadWithError:)":{"required":true,"kind":"symbol","abstract":[{"text":"This is called when the view controller encounters an error fetching the user’s","type":"text"},{"text":" ","type":"text"},{"text":"payment options from its API adapter. You should dismiss the view controller","type":"text"},{"text":" ","type":"text"},{"text":"when this is called.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailToLoadWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewController(_:didFailToLoadWithError:)","url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontroller(_:didfailtoloadwitherror:)","role":"symbol","title":"paymentOptionsViewController(_:didFailToLoadWithError:)","type":"topic","navigatorTitle":[{"text":"paymentOptionsViewController:didFailToLoadWithError:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate","title":"STPPaymentOptionsViewControllerDelegate","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","kind":"symbol","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentOptionsViewControllerDelegate"},{"type":"text","text":" responds when a user selects a"},{"text":" ","type":"text"},{"type":"text","text":"payment option from (or cancels) an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":". In both"},{"text":" ","type":"text"},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"type":"text","text":" "},{"text":"it off the navigation stack, or dismissing it).","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paymentOptionsViewController:didFailToLoadWithError:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentOptionsViewController:didFailToLoadWithError:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"paymentOptionsViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentOptionsViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFailToLoadWithError:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"STPPaymentOptionsViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},{"value":"paymentOptionsViewController:didFailToLoadWithError:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewController(_:didFailToLoadWithError:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewController(_:didFailToLoadWithError:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"paymentOptionsViewController:didFailToLoadWithError:","kind":"identifier"}]},{"op":"replace","value":"STPPaymentOptionsViewControllerDelegate","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
