{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontrollerdidfinish(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontrollerdidfinish(_:)"]}],"abstract":[{"text":"This is called when the user selects or adds a payment method, so it will often","type":"text"},{"type":"text","text":" "},{"text":"be called immediately after calling ","type":"text"},{"code":"paymentOptionsViewController:didSelectPaymentOption:","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You should dismiss the view controller when this is called."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidFinish(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"paymentOptionsViewControllerDidFinish(_:)","role":"symbol","externalID":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate(im)paymentOptionsViewControllerDidFinish:","modules":[{"name":"Stripe"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","required":true,"navigatorTitle":[{"text":"paymentOptionsViewControllerDidFinish:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentOptionsViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"the view controller that has finished","type":"text"}]}],"name":"paymentOptionsViewController"}]}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","abstract":[{"type":"text","text":"An "},{"code":"STPPaymentOptionsViewControllerDelegate","type":"codeVoice"},{"text":" responds when a user selects a","type":"text"},{"type":"text","text":" "},{"text":"payment option from (or cancels) an ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":". In both"},{"text":" ","type":"text"},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"text":" ","type":"text"},{"type":"text","text":"it off the navigation stack, or dismissing it)."}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate","title":"STPPaymentOptionsViewControllerDelegate","navigatorTitle":[{"text":"STPPaymentOptionsViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"title":"STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","abstract":[{"text":"This view controller presents a list of payment method options to the user,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"text":" ","type":"text"},{"text":"It must be displayed inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"text":", so you can either","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"as the ","type":"text"},{"code":"rootViewController","type":"codeVoice"},{"type":"text","text":" and then present the "},{"code":"UINavigationController","type":"codeVoice"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"text":"’s stack. You can also have ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"code":"pushPaymentOptionsViewController","type":"codeVoice"},{"text":" on it.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate/paymentOptionsViewControllerDidFinish(_:)":{"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontrollerdidfinish(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentOptionsViewControllerDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentOptionsViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This is called when the user selects or adds a payment method, so it will often"},{"type":"text","text":" "},{"type":"text","text":"be called immediately after calling "},{"type":"codeVoice","code":"paymentOptionsViewController:didSelectPaymentOption:"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"You should dismiss the view controller when this is called.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidFinish(_:)","kind":"symbol","title":"paymentOptionsViewControllerDidFinish(_:)","required":true,"navigatorTitle":[{"text":"paymentOptionsViewControllerDidFinish:","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"paymentOptionsViewControllerDidFinish:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentOptionsViewControllerDidFinish:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"paymentOptionsViewControllerDidFinish:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"paymentOptionsViewController"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/title","value":"STPPaymentOptionsViewControllerDelegate","op":"replace"},{"value":[{"text":"STPPaymentOptionsViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/fragments"},{"value":"STPPaymentOptionsViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewControllerDidFinish(_:)\/title","op":"replace","value":"paymentOptionsViewControllerDidFinish:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewControllerDidFinish(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewControllerDidFinish:"}],"op":"replace"}]}]}
