{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate"]]},"metadata":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentOptionsViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"paymentOptionsViewControllerDidCancel:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate(im)paymentOptionsViewControllerDidCancel:","title":"paymentOptionsViewControllerDidCancel(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"paymentOptionsViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentOptionsViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"paymentOptionsViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the view controller that has finished"}]}]}]}],"abstract":[{"text":"This is called when the user taps “cancel”.","type":"text"},{"type":"text","text":" "},{"text":"You should dismiss the view controller when this is called.","type":"text"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidCancel(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontrollerdidcancel(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontrollerdidcancel(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate/paymentOptionsViewControllerDidCancel(_:)":{"title":"paymentOptionsViewControllerDidCancel(_:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate\/paymentOptionsViewControllerDidCancel(_:)","role":"symbol","abstract":[{"text":"This is called when the user taps “cancel”.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You should dismiss the view controller when this is called."}],"navigatorTitle":[{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentOptionsViewControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","text":"STPPaymentOptionsViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate\/paymentoptionsviewcontrollerdidcancel(_:)","required":true,"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","abstract":[{"type":"text","text":"An "},{"code":"STPPaymentOptionsViewControllerDelegate","type":"codeVoice"},{"text":" responds when a user selects a","type":"text"},{"type":"text","text":" "},{"text":"payment option from (or cancels) an ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":". In both"},{"text":" ","type":"text"},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"text":" ","type":"text"},{"type":"text","text":"it off the navigation stack, or dismissing it)."}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate","title":"STPPaymentOptionsViewControllerDelegate","navigatorTitle":[{"text":"STPPaymentOptionsViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"title":"STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","abstract":[{"text":"This view controller presents a list of payment method options to the user,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"text":" ","type":"text"},{"text":"It must be displayed inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"text":", so you can either","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"as the ","type":"text"},{"code":"rootViewController","type":"codeVoice"},{"type":"text","text":" and then present the "},{"code":"UINavigationController","type":"codeVoice"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"text":"’s stack. You can also have ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"code":"pushPaymentOptionsViewController","type":"codeVoice"},{"text":" on it.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"paymentOptionsViewControllerDidCancel:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewControllerDidCancel:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"paymentOptionsViewControllerDidCancel:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPPaymentOptionsViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"},{"kind":"text","text":" *) "},{"text":"paymentOptionsViewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewControllerDidCancel(_:)\/title","op":"replace","value":"paymentOptionsViewControllerDidCancel:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate~1paymentOptionsViewControllerDidCancel(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"paymentOptionsViewControllerDidCancel:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/title","value":"STPPaymentOptionsViewControllerDelegate","op":"replace"},{"value":[{"text":"STPPaymentOptionsViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","op":"replace","value":"STPPaymentOptionsViewController"},{"value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
