{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodKlarnaParams"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodklarnaparams\/init"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodKlarnaParams\/init","interfaceLanguage":"occ"},"metadata":{"title":"init","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodKlarnaParams(im)init","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Method"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodKlarnaParams/init":{"url":"\/documentation\/stripepayments\/stppaymentmethodklarnaparams\/init","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodKlarnaParams\/init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodKlarnaParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodklarnaparams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodKlarnaParams"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodKlarnaParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodKlarnaParams","title":"STPPaymentMethodKlarnaParams","abstract":[{"text":"An object representing parameters used to create an Klarna Payment Method","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodKlarnaParams\/title","value":"STPPaymentMethodKlarnaParams"},{"value":[{"text":"STPPaymentMethodKlarnaParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodKlarnaParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodKlarnaParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodKlarnaParams"}],"op":"replace"}]}]}