{"hierarchy":{"paths":[[]]},"variants":[{"paths":["\/documentation\/stripefinancialconnections"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripefinancialconnections"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"content":[{"level":2,"text":"Table of contents","anchor":"Table-of-contents","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"#Features","type":"reference"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"#Requirements","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#Getting-started","isActive":true}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"#Integration","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"identifier":"#Example","isActive":true,"type":"reference"}],"type":"paragraph"}]}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"#Manual-linking","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"},{"level":2,"text":"Features","anchor":"Features","type":"heading"},{"inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Prebuilt UI"}]},{"text":": We provide ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-financialconnections\/Classes\/FinancialConnectionsSheet.html"},{"text":", a prebuilt UI that combines all the steps required for your users to linking their external financial accounts to your business.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"Data retrieved through Financial Connections can help you unlock a variety of use cases, including:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tokenized account and routing numbers let you instantly verify bank accounts for ACH Direct Debit payments."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Real-time balance data helps you avoid fees from insufficient funds failures before initiating a bank-based payment or wallet transfer."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Account ownership information, such as the name and address of the bank accountholder, helps you mitigate fraud when onboarding a customer or merchant."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Transactions data that you can use to help users track expenses, handle bills, manage their finances, and take control of their financial well-being."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Transactions and balance data helps you speed up underwriting and improve access to credit and other financial services."}]}]}],"type":"unorderedList"},{"text":"Requirements","type":"heading","level":2,"anchor":"Requirements"},{"inlineContent":[{"type":"text","text":"The Stripe Financial Connections iOS SDK is compatible with apps targeting iOS 12.0 or above."}],"type":"paragraph"},{"text":"Getting started","type":"heading","level":2,"anchor":"Getting-started"},{"text":"Integration","type":"heading","level":3,"anchor":"Integration"},{"inlineContent":[{"text":"Get started with Stripe Financial Connections ","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/financial-connections\/other-data-powered-products?platform=ios","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.10.0\/StripeFinancialConnections\/..\/Example\/FinancialConnections%20Example","isActive":true,"type":"reference"},{"text":", or ","type":"text"},{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-financialconnections\/index.html","isActive":true,"type":"reference"},{"text":" for fine-grained documentation of all the classes and methods in the SDK.","type":"text"}],"type":"paragraph"},{"text":"Example","type":"heading","level":3,"anchor":"Example"},{"inlineContent":[{"type":"reference","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.10.0\/StripeFinancialConnections\/..\/Example\/FinancialConnections%20Example","isActive":true,"overridingTitleInlineContent":[{"text":"Financial Connections Example","type":"text"}],"overridingTitle":"Financial Connections Example"},{"type":"text","text":" – This example demonstrates how to let your user link their external financial accounts."}],"type":"paragraph"},{"text":"Manual linking","type":"heading","level":2,"anchor":"Manual-linking"},{"inlineContent":[{"type":"text","text":"If you link the Stripe Financial Connections library manually, use a version from our "},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases"},{"type":"text","text":" page and make sure to embed "},{"type":"text","text":"all"},{"type":"text","text":" of the following frameworks:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"StripeFinancialConnections.xcframework","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripeCore.xcframework"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripeUICore.xcframework"}]}]}]}],"kind":"content"}],"kind":"symbol","metadata":{"modules":[{"name":"StripeFinancialConnections"}],"roleHeading":"Framework","role":"collection","title":"StripeFinancialConnections","externalID":"StripeFinancialConnections","symbolKind":"module"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Stripe Financial Connections iOS SDK lets your users securely share their financial data by linking their external financial accounts to your business in your iOS app."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections"},"topicSections":[{"generated":true,"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/FinancialConnectionsSheet"]},{"generated":true,"anchor":"Structures","title":"Structures","identifiers":["doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/FinancialConnectionsCustomManualEntryRequiredError"]},{"generated":true,"anchor":"Enumerations","title":"Enumerations","identifiers":["doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/FinancialConnectionsSheetError"]},{"generated":true,"anchor":"Extended-Modules","title":"Extended Modules","identifiers":["doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/StripeCore"]}],"references":{"doc://com.stripe.stripe-financial-connections/documentation/StripeFinancialConnections/FinancialConnectionsSheetError":{"identifier":"doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/FinancialConnectionsSheetError","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinancialConnectionsSheetError"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FinancialConnectionsSheetError"}],"kind":"symbol","abstract":[{"type":"text","text":"Errors specific to the "},{"type":"codeVoice","code":"FinancialConnectionsSheet"},{"type":"text","text":"."}],"title":"FinancialConnectionsSheetError","url":"\/documentation\/stripefinancialconnections\/financialconnectionssheeterror"},"doc://com.stripe.stripe-financial-connections/documentation/StripeFinancialConnections/FinancialConnectionsSheet":{"navigatorTitle":[{"kind":"identifier","text":"FinancialConnectionsSheet"}],"abstract":[{"type":"text","text":"A drop-in class that presents a sheet for a user to connect their financial accounts."}],"url":"\/documentation\/stripefinancialconnections\/financialconnectionssheet","title":"FinancialConnectionsSheet","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/FinancialConnectionsSheet","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinancialConnectionsSheet"}]},"doc://com.stripe.stripe-financial-connections/documentation/StripeFinancialConnections/FinancialConnectionsCustomManualEntryRequiredError":{"navigatorTitle":[{"kind":"identifier","text":"FinancialConnectionsCustomManualEntryRequiredError"}],"identifier":"doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/FinancialConnectionsCustomManualEntryRequiredError","kind":"symbol","url":"\/documentation\/stripefinancialconnections\/financialconnectionscustommanualentryrequirederror","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FinancialConnectionsCustomManualEntryRequiredError"}],"title":"FinancialConnectionsCustomManualEntryRequiredError","abstract":[],"role":"symbol","type":"topic"},"#Requirements":{"url":"#Requirements","titleInlineContent":[{"type":"text","text":"Requirements"}],"type":"link","identifier":"#Requirements","title":"Requirements"},"https://stripe.dev/stripe-ios/stripe-financialconnections/index.html":{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-financialconnections\/index.html","title":"📘 browse the SDK reference","url":"https:\/\/stripe.dev\/stripe-ios\/stripe-financialconnections\/index.html","type":"link","titleInlineContent":[{"type":"text","text":"📘 browse the SDK reference"}]},"doc://com.stripe.stripe-financial-connections/documentation/StripeFinancialConnections":{"abstract":[{"text":"Stripe Financial Connections iOS SDK lets your users securely share their financial data by linking their external financial accounts to your business in your iOS app.","type":"text"}],"role":"collection","url":"\/documentation\/stripefinancialconnections","kind":"symbol","type":"topic","title":"StripeFinancialConnections","identifier":"doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections"},"doc://com.stripe.stripe-financial-connections/documentation/StripeFinancialConnections/StripeFinancialConnectionsVersionString":{"type":"topic","abstract":[{"type":"text","text":"Project version string for StripeFinancialConnections."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/StripeFinancialConnectionsVersionString","kind":"symbol","title":"StripeFinancialConnectionsVersionString","url":"\/documentation\/stripefinancialconnections\/stripefinancialconnectionsversionstring","fragments":[{"text":"StripeFinancialConnectionsVersionString","kind":"identifier"}]},"https://stripe.com/docs/financial-connections/other-data-powered-products?platform=ios":{"url":"https:\/\/stripe.com\/docs\/financial-connections\/other-data-powered-products?platform=ios","titleInlineContent":[{"type":"text","text":"📚 iOS integration guide"}],"type":"link","identifier":"https:\/\/stripe.com\/docs\/financial-connections\/other-data-powered-products?platform=ios","title":"📚 iOS integration guide"},"doc://com.stripe.stripe-financial-connections/documentation/StripeFinancialConnections/StripeFinancialConnectionsVersionNumber":{"url":"\/documentation\/stripefinancialconnections\/stripefinancialconnectionsversionnumber","identifier":"doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/StripeFinancialConnectionsVersionNumber","type":"topic","fragments":[{"kind":"identifier","text":"StripeFinancialConnectionsVersionNumber"}],"title":"StripeFinancialConnectionsVersionNumber","abstract":[{"type":"text","text":"Project version number for StripeFinancialConnections."}],"role":"symbol","kind":"symbol"},"https://github.com/stripe/stripe-ios/tree/25.10.0/StripeFinancialConnections/../Example/FinancialConnections%20Example":{"url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.10.0\/StripeFinancialConnections\/..\/Example\/FinancialConnections%20Example","titleInlineContent":[{"type":"text","text":"example project"}],"type":"link","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.10.0\/StripeFinancialConnections\/..\/Example\/FinancialConnections%20Example","title":"example project"},"https://stripe.dev/stripe-ios/stripe-financialconnections/Classes/FinancialConnectionsSheet.html":{"type":"link","url":"https:\/\/stripe.dev\/stripe-ios\/stripe-financialconnections\/Classes\/FinancialConnectionsSheet.html","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-financialconnections\/Classes\/FinancialConnectionsSheet.html","title":"FinancialConnectionsSheet","titleInlineContent":[{"type":"codeVoice","code":"FinancialConnectionsSheet"}]},"#Integration":{"url":"#Integration","titleInlineContent":[{"type":"text","text":"Integration"}],"type":"link","identifier":"#Integration","title":"Integration"},"#Features":{"type":"link","url":"#Features","identifier":"#Features","title":"Features","titleInlineContent":[{"type":"text","text":"Features"}]},"https://github.com/stripe/stripe-ios/releases":{"url":"https:\/\/github.com\/stripe\/stripe-ios\/releases","titleInlineContent":[{"type":"text","text":"releases"}],"type":"link","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","title":"releases"},"#Manual-linking":{"type":"link","url":"#Manual-linking","identifier":"#Manual-linking","title":"Manual linking","titleInlineContent":[{"type":"text","text":"Manual linking"}]},"doc://com.stripe.stripe-financial-connections/documentation/StripeFinancialConnections/StripeCore":{"title":"StripeCore","kind":"symbol","role":"collection","url":"\/documentation\/stripefinancialconnections\/stripecore","abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/StripeCore"},"#Getting-started":{"url":"#Getting-started","titleInlineContent":[{"type":"text","text":"Getting started"}],"type":"link","identifier":"#Getting-started","title":"Getting started"},"#Example":{"type":"link","url":"#Example","identifier":"#Example","title":"Example","titleInlineContent":[{"type":"text","text":"Example"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/StripeFinancialConnectionsVersionNumber","doc:\/\/com.stripe.stripe-financial-connections\/documentation\/StripeFinancialConnections\/StripeFinancialConnectionsVersionString"],"generated":true,"title":"Variables","anchor":"Variables"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}