{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmcardoptions\/init"]}],"kind":"symbol","metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPConfirmCardOptions(im)init","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/init"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmCardOptions/init":{"url":"\/documentation\/stripepayments\/stpconfirmcardoptions\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmCardOptions":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions","url":"\/documentation\/stripepayments\/stpconfirmcardoptions","navigatorTitle":[{"kind":"identifier","text":"STPConfirmCardOptions"}],"abstract":[{"text":"Options to update a Card PaymentMethod during PaymentIntent confirmation.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPConfirmCardOptions","kind":"identifier"}],"title":"STPConfirmCardOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPConfirmCardOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions\/fragments","op":"replace","value":[{"text":"STPConfirmCardOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions\/navigatorTitle","value":[{"text":"STPConfirmCardOptions","kind":"identifier"}]}]}]}