{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmcardoptions\/stpformencodable-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmcardoptions\/stpformencodable-implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"API Collection","modules":[{"name":"StripePayments"}],"role":"collectionGroup","title":"STPFormEncodable Implementations"},"sections":[],"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/rootObjectName()"],"title":"Type Methods","anchor":"Type-Methods"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/STPFormEncodable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmCardOptions/rootObjectName()":{"title":"rootObjectName()","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmcardoptions\/rootobjectname()","role":"symbol","abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"type":"text","text":" below."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/rootObjectName()","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmCardOptions/propertyNamesToFormFieldNamesMapping()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"code":"expMonth","type":"codeVoice"},{"text":", but the Stripe API expects a field called ","type":"text"},{"code":"exp_month","type":"codeVoice"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"type":"topic","kind":"symbol","title":"propertyNamesToFormFieldNamesMapping()","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmcardoptions\/propertynamestoformfieldnamesmapping()","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/propertyNamesToFormFieldNamesMapping()"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmCardOptions":{"abstract":[{"text":"Options to update a Card PaymentMethod during PaymentIntent confirmation.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmcardoptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPConfirmCardOptions"}],"title":"STPConfirmCardOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmCardOptions"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmCardOptions\/rootObjectName()"],"anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"rootObjectName","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions~1rootObjectName()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions~1rootObjectName()\/fragments","op":"replace"},{"value":"propertyNamesToFormFieldNamesMapping","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions~1propertyNamesToFormFieldNamesMapping()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions~1propertyNamesToFormFieldNamesMapping()\/fragments","op":"replace"},{"value":"STPConfirmCardOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions\/title","op":"replace"},{"value":[{"text":"STPConfirmCardOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPConfirmCardOptions"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmCardOptions\/navigatorTitle","op":"replace"}]}]}