{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/decodedObject(fromAPIResponse:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"text":" ","type":"text"},{"text":"could not be decoded (i.e. if one of its ","type":"text"},{"code":"requiredFields","type":"codeVoice"},{"text":" is nil).","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage\/decodedobject(fromapiresponse:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage\/decodedobject(fromapiresponse:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"decodedObject(fromAPIResponse:)","symbolKind":"method","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodThreeDSecureUsage(cm)decodedObjectFromAPIResponse:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"roleHeading":"Type Method","modules":[{"name":"StripePayments"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodThreeDSecureUsage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"role":"symbol","title":"STPPaymentMethodThreeDSecureUsage","abstract":[{"text":"Contains details on how an ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodCard"},{"text":" maybe be used for 3D Secure authentication.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodThreeDSecureUsage/decodedObject(fromAPIResponse:)":{"title":"decodedObject(fromAPIResponse:)","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage\/decodedobject(fromapiresponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}]}],"name":"response"}]}},{"value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The object represented by the JSON dictionary, or nil if the object"},{"type":"text","text":" "},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"STPPaymentMethodThreeDSecureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/navigatorTitle","op":"replace"},{"value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1decodedObject(fromAPIResponse:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1decodedObject(fromAPIResponse:)\/fragments","op":"replace"}]}]}