{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/ApplePayContextDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayContext","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"context"},{"text":": ","kind":"text"},{"text":"STPApplePayContext","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext"},{"text":", ","kind":"text"},{"text":"didCompleteWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14StripeApplePay08STPAppleC7ContextC13PaymentStatusO","kind":"typeIdentifier","text":"PaymentStatus","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The status of the payment"}]}],"name":"status"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred, if any."}]}],"name":"error"}]}],"metadata":{"roleHeading":"Instance Method","title":"applePayContext(_:didCompleteWith:error:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteWith"},{"kind":"text","text":": "},{"text":"STPApplePayContext","preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"PaymentStatus","kind":"typeIdentifier","preciseIdentifier":"s:14StripeApplePay08STPAppleC7ContextC13PaymentStatusO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?)"}],"modules":[{"name":"StripeApplePay"}],"symbolKind":"method","role":"symbol","externalID":"s:14StripeApplePay0bC15ContextDelegateP05applecD0_15didCompleteWith5erroryAA08STPApplecD0C_AH13PaymentStatusOs5Error_pSgtF"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/applepaycontextdelegate\/applepaycontext(_:didcompletewith:error:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Called after the Apple Pay sheet is dismissed with the result of the payment."},{"text":" ","type":"text"},{"text":"Your implementation could stop a spinner and display a receipt view or error to the customer, for example.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/ApplePayContextDelegate\/applePayContext(_:didCompleteWith:error:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus":{"abstract":[{"type":"text","text":"An enum representing the status of a payment requested from the user."}],"kind":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PaymentStatus","kind":"identifier"}],"navigatorTitle":[{"text":"PaymentStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus","title":"STPApplePayContext.PaymentStatus","role":"symbol","type":"topic"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/ApplePayContextDelegate":{"navigatorTitle":[{"kind":"identifier","text":"ApplePayContextDelegate"}],"abstract":[{"text":"Implement the required methods of this delegate to supply a PaymentIntent to ApplePayContext and be notified of the completion of the Apple Pay payment.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You may also implement the optional delegate methods to handle shipping methods and shipping address changes e.g. to verify you can ship to the address, or update the payment amount."}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApplePayContextDelegate","kind":"identifier"}],"title":"ApplePayContextDelegate","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/ApplePayContextDelegate","url":"\/documentation\/stripeapplepay\/applepaycontextdelegate"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"title":"StripeApplePay","url":"\/documentation\/stripeapplepay","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","role":"collection","kind":"symbol","abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/ApplePayContextDelegate/applePayContext(_:didCompleteWith:error:)":{"abstract":[{"text":"Called after the Apple Pay sheet is dismissed with the result of the payment.","type":"text"},{"text":" ","type":"text"},{"text":"Your implementation could stop a spinner and display a receipt view or error to the customer, for example.","type":"text"}],"url":"\/documentation\/stripeapplepay\/applepaycontextdelegate\/applepaycontext(_:didcompletewith:error:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePayContext"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","kind":"typeIdentifier","text":"STPApplePayContext"},{"kind":"text","text":", "},{"text":"didCompleteWith","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripeApplePay@objc(cs)STPApplePayContext","text":"STPApplePayContext","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14StripeApplePay08STPAppleC7ContextC13PaymentStatusO","text":"PaymentStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/ApplePayContextDelegate\/applePayContext(_:didCompleteWith:error:)","role":"symbol","title":"applePayContext(_:didCompleteWith:error:)","required":true},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"url":"\/documentation\/stripeapplepay\/stpapplepaycontext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPApplePayContext","kind":"identifier"}],"kind":"symbol","title":"STPApplePayContext","abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"type":"text","text":" "},{"text":"Usage looks like this:","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","op":"replace","value":"STPApplePayContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","value":[{"kind":"identifier","text":"STPApplePayContext"}]},{"value":[{"text":"STPApplePayContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle"}]}]}