{"metadata":{"title":"StripeIssuing","symbolKind":"module","externalID":"StripeIssuing","role":"collection","modules":[{"name":"StripeIssuing"}],"roleHeading":"Framework"},"primaryContentSections":[{"kind":"content","content":[{"text":"Table of contents","anchor":"Table-of-contents","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#Features","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"#Requirements"}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"#Getting-started","isActive":true}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#Integration","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"#Example","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#Manual-linking","type":"reference","isActive":true}]}]}]},{"text":"Features","anchor":"Features","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"[Feature 1]"}],"type":"strong"},{"type":"text","text":": [Placeholder]"}]},{"text":"Requirements","anchor":"Requirements","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Placeholder"}]},{"text":"Getting started","anchor":"Getting-started","type":"heading","level":2},{"text":"Integration","anchor":"Integration","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Placeholder"}]},{"text":"Example","anchor":"Example","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"type":"text","text":"Placeholder"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripeissuing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripeissuing"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Classes","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPFakeAddPaymentPassViewController","doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPPinManagementService","doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPPushProvisioningContext","doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPPushProvisioningDetailsParams"],"anchor":"Classes"},{"title":"Protocols","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPCustomerEphemeralKeyProvider","doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPEphemeralKeyProvider","doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPIssuingCardEphemeralKeyProvider"],"anchor":"Protocols"}],"abstract":[{"text":"Placeholder","type":"text"}],"references":{"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/STPEphemeralKeyProvider":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPEphemeralKeyProvider","title":"STPEphemeralKeyProvider","url":"\/documentation\/stripeissuing\/stpephemeralkeyprovider","role":"symbol","deprecated":true,"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPEphemeralKeyProvider","kind":"identifier"}],"navigatorTitle":[{"text":"STPEphemeralKeyProvider","kind":"identifier"}],"abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}]},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/STPFakeAddPaymentPassViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"url":"\/documentation\/stripeissuing\/stpfakeaddpaymentpassviewcontroller","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPFakeAddPaymentPassViewController","title":"STPFakeAddPaymentPassViewController","type":"topic","abstract":[{"text":"This class is a piece of fake UI that is intended to mimic ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":", and can be used to develop against the Stripe API in ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"testmode only"}]},{"text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to ","type":"text"},{"type":"codeVoice","code":"STPFakeAddPaymentPassViewController"},{"text":" in your app with ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets .","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}]},"#Integration":{"titleInlineContent":[{"text":"Integration","type":"text"}],"url":"#Integration","identifier":"#Integration","title":"Integration","type":"link"},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing":{"title":"StripeIssuing","identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing","abstract":[{"type":"text","text":"Placeholder"}],"type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/stripeissuing"},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/STPCustomerEphemeralKeyProvider":{"url":"\/documentation\/stripeissuing\/stpcustomerephemeralkeyprovider","identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPCustomerEphemeralKeyProvider","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"title":"STPCustomerEphemeralKeyProvider","kind":"symbol","abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}]},"#Getting-started":{"identifier":"#Getting-started","type":"link","titleInlineContent":[{"text":"Getting started","type":"text"}],"title":"Getting started","url":"#Getting-started"},"#Manual-linking":{"titleInlineContent":[{"text":"Manual linking","type":"text"}],"url":"#Manual-linking","identifier":"#Manual-linking","title":"Manual linking","type":"link"},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/STPIssuingCardEphemeralKeyProvider":{"url":"\/documentation\/stripeissuing\/stpissuingcardephemeralkeyprovider","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"abstract":[{"text":"You should make your application’s API client conform to this interface.","type":"text"},{"text":" ","type":"text"},{"text":"It provides a way for Stripe utility classes to request a new ephemeral key from","type":"text"},{"text":" ","type":"text"},{"text":"your backend, which it will use to retrieve and update Stripe API objects.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPIssuingCardEphemeralKeyProvider","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"title":"STPIssuingCardEphemeralKeyProvider"},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/STPPinManagementService":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPinManagementService"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPPinManagementService","deprecated":true,"url":"\/documentation\/stripeissuing\/stppinmanagementservice","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPinManagementService"}],"kind":"symbol","abstract":[{"type":"text","text":"STPAPIClient extensions to manage PIN on Stripe Issuing cards"}],"title":"STPPinManagementService"},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/StripeIssuingVersionNumber":{"url":"\/documentation\/stripeissuing\/stripeissuingversionnumber","title":"StripeIssuingVersionNumber","abstract":[{"text":"Project version number for StripeIdentity.","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"StripeIssuingVersionNumber"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/StripeIssuingVersionNumber"},"#Requirements":{"titleInlineContent":[{"type":"text","text":"Requirements"}],"url":"#Requirements","identifier":"#Requirements","title":"Requirements","type":"link"},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/STPPushProvisioningDetailsParams":{"type":"topic","title":"STPPushProvisioningDetailsParams","role":"symbol","navigatorTitle":[{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripeissuing\/stppushprovisioningdetailsparams","identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPPushProvisioningDetailsParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningDetailsParams","kind":"identifier"}],"abstract":[{"type":"text","text":"A helper class for turning the raw certificate array, nonce, and nonce signature emitted by PKAddPaymentPassViewController into a format that is understandable by the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"If you are using STPPushProvisioningContext to implement your integration, you do not need to use this class."}]},"#Features":{"identifier":"#Features","url":"#Features","titleInlineContent":[{"type":"text","text":"Features"}],"title":"Features","type":"link"},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/StripeIssuingVersionString":{"identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/StripeIssuingVersionString","title":"StripeIssuingVersionString","abstract":[{"type":"text","text":"Project version string for StripeIdentity."}],"role":"symbol","fragments":[{"kind":"identifier","text":"StripeIssuingVersionString"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripeissuing\/stripeissuingversionstring"},"doc://com.stripe.stripe-issuing-push-provision/documentation/StripeIssuing/STPPushProvisioningContext":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPushProvisioningContext"}],"identifier":"doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/STPPushProvisioningContext","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPushProvisioningContext"}],"url":"\/documentation\/stripeissuing\/stppushprovisioningcontext","title":"STPPushProvisioningContext","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This class makes it easier to implement “Push Provisioning”, the process by which an end-user can add a card to their Apple Pay wallet without having to type their number. This process is mediated by an Apple class called "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":"; this class will help you implement that class’ delegate methods. Note that this flow requires a special entitlement from Apple; for more information please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}]},"#Example":{"identifier":"#Example","url":"#Example","titleInlineContent":[{"type":"text","text":"Example"}],"title":"Example","type":"link"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/StripeIssuingVersionNumber","doc:\/\/com.stripe.stripe-issuing-push-provision\/documentation\/StripeIssuing\/StripeIssuingVersionString"],"generated":true,"title":"Variables","anchor":"Variables"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}