{"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintent\/allresponsefields"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintent\/allresponsefields"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"]]},"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/allResponseFields"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"allResponseFields","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSetupIntent(py)allResponseFields","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"title":"STPSetupIntent","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintent","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSetupIntent","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/allResponseFields":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintent\/allresponsefields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/allResponseFields","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"type":"topic","title":"allResponseFields","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"allResponseFields","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSetupIntent","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1allResponseFields\/title","value":"allResponseFields","op":"replace"},{"value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1allResponseFields\/fragments"}]}]}