{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/lastSetupError"},"abstract":[{"text":"The setup error encountered in the previous SetupIntent confirmation.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintent\/lastsetuperror"]},{"paths":["\/documentation\/stripepayments\/stpsetupintent\/lastsetuperror"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastSetupError"},{"kind":"text","text":": "},{"text":"STPSetupIntentLastSetupError","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentLastSetupError","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupError"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntent(py)lastSetupError","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"lastSetupError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"lastSetupError","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentLastSetupError","text":"STPSetupIntentLastSetupError","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"title":"lastSetupError"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/lastSetupError":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/lastSetupError","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"lastSetupError","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentLastSetupError","text":"STPSetupIntentLastSetupError"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The setup error encountered in the previous SetupIntent confirmation."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lastSetupError"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/lastsetuperror","title":"lastSetupError","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupError":{"role":"symbol","abstract":[{"text":"A value for ","type":"text"},{"type":"codeVoice","code":"code"},{"text":" indicating the provided payment method failed authentication.\/\/\/ The error encountered in the previous SetupIntent confirmation.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperror","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupError"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupError","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntentLastSetupError"}],"type":"topic","title":"STPSetupIntentLastSetupError"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"}],"abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"role":"symbol","title":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"lastSetupError","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"lastSetupError","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupError","text":"STPSetupIntentLastSetupError","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentLastSetupError"},{"text":" * ","kind":"text"},{"text":"lastSetupError","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"lastSetupError","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1lastSetupError\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1lastSetupError\/fragments","value":[{"kind":"identifier","text":"lastSetupError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupError\/title","value":"STPSetupIntentLastSetupError"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupError\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupError"}]},{"value":[{"text":"STPSetupIntentLastSetupError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupError\/navigatorTitle"},{"value":"STPSetupIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntent"}]}]}]}