{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodTypes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","kind":"typeIdentifier","text":"STPPaymentMethodType"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethodTypes-64jp0"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodTypes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","text":"STPPaymentMethodType","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","externalID":"s:14StripePayments14STPSetupIntentC18paymentMethodTypesSayAA010STPPaymentF4TypeOGvp","roleHeading":"Instance Property","title":"paymentMethodTypes","modules":[{"name":"StripePayments"}],"symbolKind":"property"},"sections":[],"abstract":[{"type":"text","text":"The list of payment method types that this PaymentIntent is allowed to use."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintent\/paymentmethodtypes-64jp0"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"]]},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintent","role":"symbol","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","title":"STPSetupIntent","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}],"title":"STPPaymentMethodType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","abstract":[{"text":"The type of the PaymentMethod.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/paymentMethodTypes-64jp0":{"title":"paymentMethodTypes","url":"\/documentation\/stripepayments\/stpsetupintent\/paymentmethodtypes-64jp0","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethodTypes-64jp0","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The list of payment method types that this PaymentIntent is allowed to use."}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","text":"STPPaymentMethodType"},{"kind":"text","text":"]"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPSetupIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","op":"replace"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","op":"replace"},{"value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}