{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus","text":"STPSetupIntentStatus","kind":"typeIdentifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/status"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintent\/status"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintent\/status"]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPSetupIntent(py)status","symbolKind":"property","role":"symbol","title":"status","modules":[{"name":"StripePayments"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSetupIntentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentStatus"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Status of this SetupIntent."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"title":"STPSetupIntent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","url":"\/documentation\/stripepayments\/stpsetupintent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentStatus","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Status types for an STPSetupIntent"}],"title":"STPSetupIntentStatus","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentstatus","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/status":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSetupIntentStatus","preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentStatus"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/status","navigatorTitle":[{"kind":"identifier","text":"status"}],"title":"status","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/status","kind":"symbol","abstract":[{"type":"text","text":"Status of this SetupIntent."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"status"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"status","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentStatus","text":"STPSetupIntentStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/title","value":"STPSetupIntentStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/navigatorTitle","value":[{"text":"STPSetupIntentStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1status\/fragments","value":[{"text":"status","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}