{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"usage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentUsage","text":"STPSetupIntentUsage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintent\/usage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsetupintent\/usage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/usage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Indicates how the payment method is intended to be used in the future."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"usage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSetupIntentUsage","preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentUsage"}],"title":"usage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntent(py)usage","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"usage"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage":{"role":"symbol","title":"STPSetupIntentUsage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentUsage"}],"abstract":[{"type":"text","text":"Indicates how the payment method is intended to be used in the future."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsage"}],"url":"\/documentation\/stripepayments\/stpsetupintentusage"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"role":"symbol","title":"STPSetupIntent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"}],"abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"url":"\/documentation\/stripepayments\/stpsetupintent"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/usage":{"role":"symbol","title":"usage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"usage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSetupIntentUsage","preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentUsage"}],"abstract":[{"type":"text","text":"Indicates how the payment method is intended to be used in the future."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/usage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"usage"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/usage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"usage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"usage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentUsage","text":"STPSetupIntentUsage"},{"kind":"text","text":" "},{"kind":"identifier","text":"usage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/title","value":"STPSetupIntentUsage"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentUsage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1usage\/title","value":"usage"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1usage\/fragments","value":[{"kind":"identifier","text":"usage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}