{"variants":[{"paths":["\/documentation\/stripepayments\/stpcollectbankaccountparams\/collectinstantdebitsparamswithemail:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectInstantDebitsParamsWithEmail:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams(cm)collectInstantDebitsParamsWithEmail:","modules":[{"name":"StripePayments"}],"symbolKind":"method","title":"collectInstantDebitsParamsWithEmail:","roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"collectInstantDebitsParamsWithEmail:","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"collectInstantDebitsParamsWithEmail:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"collectInstantDebitsParamsWithEmail:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"email","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The customer’s email."}],"type":"paragraph"}],"name":"email"}]}],"sections":[],"abstract":[{"text":"Configures and returns an instance of ","type":"text"},{"text":"STPCollectBankAccountParams","type":"text"},{"text":" for Instant Debits","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams/collectInstantDebitsParamsWithEmail:":{"fragments":[{"text":"+ ","kind":"text"},{"text":"collectInstantDebitsParamsWithEmail:","kind":"identifier"}],"abstract":[{"type":"text","text":"Configures and returns an instance of "},{"type":"text","text":"STPCollectBankAccountParams"},{"type":"text","text":" for Instant Debits"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectInstantDebitsParamsWithEmail:","role":"symbol","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams\/collectinstantdebitsparamswithemail:","navigatorTitle":[{"text":"collectInstantDebitsParamsWithEmail:","kind":"identifier"}],"type":"topic","title":"collectInstantDebitsParamsWithEmail:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","navigatorTitle":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"abstract":[{"text":"Parameters to use with ","type":"text"},{"code":"STPBankAccountCollector","type":"codeVoice"},{"text":" to collect bank account details for payments.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"STPCollectBankAccountParams","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title","value":"STPCollectBankAccountParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}