{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectUSBankAccountParams(with:email:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(collectUSBankAccountParamsWithName:email:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectUSBankAccountParams"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The customer’s full name. ","type":"text"},{"inlineContent":[{"text":"required","type":"text"}],"type":"emphasis"}],"type":"paragraph"}],"name":"name"},{"content":[{"inlineContent":[{"text":"The customer’s email. If included, can be used to notify the customer of pending micro-deposit verification.","type":"text"}],"type":"paragraph"}],"name":"email"}],"kind":"parameters"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectUSBankAccountParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier"}],"title":"collectUSBankAccountParams(with:email:)","externalID":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams(cm)collectUSBankAccountParamsWithName:email:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"collectUSBankAccountParamsWithName:email:","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method"},"kind":"symbol","abstract":[{"text":"Configures and returns an instance of ","type":"text"},{"code":"STPCollectBankAccountParams","type":"codeVoice"},{"text":" for US Bank Accounts","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcollectbankaccountparams\/collectusbankaccountparams(with:email:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcollectbankaccountparams\/collectusbankaccountparams(with:email:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams/collectUSBankAccountParams(with:email:)":{"url":"\/documentation\/stripepayments\/stpcollectbankaccountparams\/collectusbankaccountparams(with:email:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectUSBankAccountParams(with:email:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectUSBankAccountParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier"}],"abstract":[{"text":"Configures and returns an instance of ","type":"text"},{"code":"STPCollectBankAccountParams","type":"codeVoice"},{"text":" for US Bank Accounts","type":"text"}],"type":"topic","title":"collectUSBankAccountParams(with:email:)","kind":"symbol","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"collectUSBankAccountParamsWithName:email:","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","title":"STPCollectBankAccountParams","abstract":[{"text":"Parameters to use with ","type":"text"},{"code":"STPBankAccountCollector","type":"codeVoice"},{"text":" to collect bank account details for payments.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"collectUSBankAccountParamsWithName:email:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"collectUSBankAccountParamsWithName:email:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams"},{"text":" *) ","kind":"text"},{"text":"collectUSBankAccountParamsWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"email:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"email","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"name","content":[{"inlineContent":[{"type":"text","text":"The customer’s full name. "},{"type":"emphasis","inlineContent":[{"type":"text","text":"required"}]}],"type":"paragraph"}]},{"name":"email","content":[{"inlineContent":[{"type":"text","text":"The customer’s email. If included, can be used to notify the customer of pending micro-deposit verification."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"collectUSBankAccountParamsWithName:email:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams~1collectUSBankAccountParams(with:email:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"collectUSBankAccountParamsWithName:email:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams~1collectUSBankAccountParams(with:email:)\/fragments"},{"value":"STPCollectBankAccountParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title"},{"value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments"},{"value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}