{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIBarStyle","kind":"typeIdentifier","text":"UIBarStyle"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This property controls the ","type":"text"},{"code":"UIStatusBarStyle","type":"codeVoice"},{"type":"text","text":". Set this to "},{"type":"codeVoice","code":"UIBarStyleBlack"},{"type":"text","text":" "},{"text":"to change the ","type":"text"},{"code":"statusBarStyle","type":"codeVoice"},{"type":"text","text":" to "},{"code":"UIStatusBarStyleLightContent","type":"codeVoice"},{"type":"text","text":" - even if you also set"},{"type":"text","text":" "},{"code":"barTintColor","type":"codeVoice"},{"type":"text","text":" to change the actual color of the navigation bar."}]}],"name":"Note","type":"aside"}],"kind":"content"}],"abstract":[{"text":"The navigation bar style.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to UIBarStyleDefault.","type":"text"}],"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIBarStyle","preciseIdentifier":"c:@E@UIBarStyle","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"barStyle"}],"title":"barStyle","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization(py)barStyle"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/barStyle"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/barstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/barstyle"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization/barStyle":{"type":"topic","title":"barStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UIBarStyle","kind":"typeIdentifier","text":"UIBarStyle"}],"url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/barstyle","navigatorTitle":[{"text":"barStyle","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The navigation bar style."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to UIBarStyleDefault."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/barStyle"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization":{"type":"topic","title":"STPThreeDSNavigationBarCustomization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}],"url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization","navigatorTitle":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A customization object to use to configure a UINavigationBar."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"barStyle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"barStyle"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBarStyle","text":"UIBarStyle"},{"text":" ","kind":"text"},{"text":"barStyle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1barStyle\/title","value":"barStyle","op":"replace"},{"op":"replace","value":[{"text":"barStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1barStyle\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/title","op":"replace","value":"STPThreeDSNavigationBarCustomization"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/fragments","value":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}]}]}]}