{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/barTintColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"barTintColor"}],"title":"barTintColor","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization(py)barTintColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"barTintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"barTintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The tint color of the navigation bar background."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/bartintcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/bartintcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization/barTintColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barTintColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The tint color of the navigation bar background."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil."}],"navigatorTitle":[{"kind":"identifier","text":"barTintColor"}],"title":"barTintColor","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/barTintColor","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/bartintcolor"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization":{"navigatorTitle":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"title":"STPThreeDSNavigationBarCustomization","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","abstract":[{"type":"text","text":"A customization object to use to configure a UINavigationBar."}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"barTintColor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"barTintColor"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"barTintColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1barTintColor\/title","op":"replace","value":"barTintColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1barTintColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"barTintColor"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/title","op":"replace","value":"STPThreeDSNavigationBarCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/navigatorTitle","op":"replace","value":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}]}]}]}