{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/buttonText","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"buttonText","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buttonText"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization(py)buttonText","symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/buttontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/buttontext"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The text to display for the button in the navigation bar."},{"type":"text","text":" "},{"type":"text","text":"Defaults to “Cancel”."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization/buttonText":{"url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/buttontext","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/buttonText","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The text to display for the button in the navigation bar."},{"type":"text","text":" "},{"type":"text","text":"Defaults to “Cancel”."}],"navigatorTitle":[{"kind":"identifier","text":"buttonText"}],"title":"buttonText","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"buttonText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization":{"url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A customization object to use to configure a UINavigationBar."}],"navigatorTitle":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"title":"STPThreeDSNavigationBarCustomization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"buttonText"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"buttonText","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"buttonText","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1buttonText\/title","value":"buttonText"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1buttonText\/fragments","value":[{"text":"buttonText","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/title","value":"STPThreeDSNavigationBarCustomization"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/fragments","value":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/navigatorTitle","value":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}