{"kind":"symbol","metadata":{"title":"defaultSettings()","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization(cm)defaultSettings","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"defaultSettings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"STPThreeDSNavigationBarCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization","kind":"typeIdentifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"defaultSettings","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization"]]},"abstract":[{"text":"The default settings.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultSettings"},{"text":"() -> ","kind":"text"},{"text":"STPThreeDSNavigationBarCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/defaultsettings()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/defaultsettings()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/defaultSettings()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization/defaultSettings()":{"role":"symbol","title":"defaultSettings()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/defaultSettings()","kind":"symbol","navigatorTitle":[{"text":"defaultSettings","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization","kind":"typeIdentifier","text":"STPThreeDSNavigationBarCustomization"}],"url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/defaultsettings()","abstract":[{"type":"text","text":"The default settings."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization":{"role":"symbol","title":"STPThreeDSNavigationBarCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization","abstract":[{"type":"text","text":"A customization object to use to configure a UINavigationBar."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"defaultSettings","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"STPThreeDSNavigationBarCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization"},{"text":" *) ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"defaultSettings","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1defaultSettings()\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1defaultSettings()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"defaultSettings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/title","value":"STPThreeDSNavigationBarCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/fragments","op":"replace","value":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}],"op":"replace"}]}]}