{"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/headertext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/headertext"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/headerText"},"metadata":{"symbolKind":"property","role":"symbol","title":"headerText","navigatorTitle":[{"text":"headerText","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization(py)headerText","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headerText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"The text to display in the title of the navigation bar."},{"type":"text","text":" "},{"type":"text","text":"Defaults to “Secure checkout”."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerText"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization":{"title":"STPThreeDSNavigationBarCustomization","abstract":[{"text":"A customization object to use to configure a UINavigationBar.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization/headerText":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization\/headerText","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headerText","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"headerText","url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization\/headertext","abstract":[{"type":"text","text":"The text to display in the title of the navigation bar."},{"type":"text","text":" "},{"type":"text","text":"Defaults to “Secure checkout”."}],"navigatorTitle":[{"text":"headerText","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"headerText","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"headerText"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"headerText"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/title","op":"replace","value":"STPThreeDSNavigationBarCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/navigatorTitle"},{"value":"headerText","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1headerText\/title","op":"replace"},{"value":[{"kind":"identifier","text":"headerText"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization~1headerText\/fragments","op":"replace"}]}]}