{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/billingAddress"},"abstract":[{"text":"The user’s billing address. When set, the add card form will be filled with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"this address. The user will also have the option to fill their shipping address"},{"text":" ","type":"text"},{"type":"text","text":"using this address."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation"]]},"variants":[{"paths":["\/documentation\/stripe\/stpuserinformation\/billingaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpuserinformation\/billingaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","modules":[{"name":"Stripe"}],"title":"billingAddress","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPUserInformation(py)billingAddress","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"billingAddress","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"billingAddress","kind":"identifier"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingAddress"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"details from an ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" or "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":" instance.","type":"text"}]}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"url":"\/documentation\/stripe\/stpaddress","role":"symbol","title":"STPAddress","type":"topic","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation/billingAddress":{"abstract":[{"text":"The user’s billing address. When set, the add card form will be filled with","type":"text"},{"type":"text","text":" "},{"text":"this address. The user will also have the option to fill their shipping address","type":"text"},{"type":"text","text":" "},{"type":"text","text":"using this address."}],"type":"topic","url":"\/documentation\/stripe\/stpuserinformation\/billingaddress","title":"billingAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/billingAddress","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"billingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"billingAddress"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation":{"role":"symbol","type":"topic","title":"STPUserInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPUserInformation"}],"navigatorTitle":[{"text":"STPUserInformation","kind":"identifier"}],"url":"\/documentation\/stripe\/stpuserinformation","abstract":[{"type":"text","text":"You can use this class to specify information that you’ve already collected"},{"type":"text","text":" "},{"type":"text","text":"from your user. You can then set the "},{"type":"codeVoice","code":"prefilledInformation"},{"type":"text","text":" property on"},{"type":"text","text":" "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":", etc and it will pre-fill"},{"type":"text","text":" "},{"text":"this information whenever possible.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"billingAddress","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"billingAddress"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"billingAddress"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1billingAddress\/title","value":"billingAddress"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1billingAddress\/fragments","op":"replace","value":[{"kind":"identifier","text":"billingAddress"}]},{"value":"STPUserInformation","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/fragments","value":[{"text":"STPUserInformation","kind":"identifier"}]}]}]}
