{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpuserinformation\/setbillingaddress(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpuserinformation\/setbillingaddress(with:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"setBillingAddressWithBillingDetails:"}],"externalID":"c:@M@Stripe@objc(cs)STPUserInformation(im)setBillingAddressWithBillingDetails:","symbolKind":"method","title":"setBillingAddress(with:)","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setBillingAddress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"Stripe"}]},"abstract":[{"type":"text","text":"A convenience method to populate "},{"type":"codeVoice","code":"billingAddress"},{"type":"text","text":" with a PaymentMethod’s billing details."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(setBillingAddressWithBillingDetails:) ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setBillingAddress","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/setBillingAddress(with:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation":{"role":"symbol","type":"topic","title":"STPUserInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPUserInformation"}],"navigatorTitle":[{"text":"STPUserInformation","kind":"identifier"}],"url":"\/documentation\/stripe\/stpuserinformation","abstract":[{"type":"text","text":"You can use this class to specify information that you’ve already collected"},{"type":"text","text":" "},{"type":"text","text":"from your user. You can then set the "},{"type":"codeVoice","code":"prefilledInformation"},{"type":"text","text":" property on"},{"type":"text","text":" "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":", etc and it will pre-fill"},{"type":"text","text":" "},{"text":"this information whenever possible.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethodBillingDetails":{"abstract":[{"type":"text","text":"Billing information associated with a "},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentmethodbillingdetails","title":"STPPaymentMethodBillingDetails","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodBillingDetails"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation/setBillingAddress(with:)":{"kind":"symbol","abstract":[{"type":"text","text":"A convenience method to populate "},{"code":"billingAddress","type":"codeVoice"},{"text":" with a PaymentMethod’s billing details.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"setBillingAddressWithBillingDetails:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/setBillingAddress(with:)","title":"setBillingAddress(with:)","role":"symbol","url":"\/documentation\/stripe\/stpuserinformation\/setbillingaddress(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setBillingAddress"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"setBillingAddressWithBillingDetails:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setBillingAddressWithBillingDetails:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"setBillingAddressWithBillingDetails:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"text":"billingDetails","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"STPUserInformation","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/fragments","value":[{"kind":"identifier","text":"STPUserInformation"}],"op":"replace"},{"op":"replace","value":"setBillingAddressWithBillingDetails:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1setBillingAddress(with:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1setBillingAddress(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setBillingAddressWithBillingDetails:","kind":"identifier"}],"op":"replace"}]}]}
