{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/shippingAddress","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation"]]},"metadata":{"navigatorTitle":[{"text":"shippingAddress","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@Stripe@objc(cs)STPUserInformation(py)shippingAddress","modules":[{"name":"Stripe"}],"symbolKind":"property","title":"shippingAddress","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shippingAddress","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpuserinformation\/shippingaddress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpuserinformation\/shippingaddress"]}],"kind":"symbol","abstract":[{"text":"The user’s shipping address. When set, the shipping address form will be filled","type":"text"},{"type":"text","text":" "},{"text":"with this address. The user will also have the option to fill their billing","type":"text"},{"type":"text","text":" "},{"text":"address using this address.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddress"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation":{"role":"symbol","type":"topic","title":"STPUserInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPUserInformation"}],"navigatorTitle":[{"text":"STPUserInformation","kind":"identifier"}],"url":"\/documentation\/stripe\/stpuserinformation","abstract":[{"type":"text","text":"You can use this class to specify information that you’ve already collected"},{"type":"text","text":" "},{"type":"text","text":"from your user. You can then set the "},{"type":"codeVoice","code":"prefilledInformation"},{"type":"text","text":" property on"},{"type":"text","text":" "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":", etc and it will pre-fill"},{"type":"text","text":" "},{"text":"this information whenever possible.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"url":"\/documentation\/stripe\/stpaddress","role":"symbol","title":"STPAddress","type":"topic","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPUserInformation/shippingAddress":{"role":"symbol","url":"\/documentation\/stripe\/stpuserinformation\/shippingaddress","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPUserInformation\/shippingAddress","title":"shippingAddress","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shippingAddress"},{"text":": ","kind":"text"},{"text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"The user’s shipping address. When set, the shipping address form will be filled","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"with this address. The user will also have the option to fill their billing"},{"text":" ","type":"text"},{"type":"text","text":"address using this address."}],"navigatorTitle":[{"text":"shippingAddress","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"shippingAddress","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"shippingAddress","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress","text":"STPAddress"},{"kind":"text","text":" * "},{"text":"shippingAddress","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/title","op":"replace","value":"STPUserInformation"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation\/fragments","op":"replace","value":[{"text":"STPUserInformation","kind":"identifier"}]},{"value":"shippingAddress","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1shippingAddress\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPUserInformation~1shippingAddress\/fragments","op":"replace","value":[{"kind":"identifier","text":"shippingAddress"}]}]}]}
