{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/cardParams"},"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView(py)cardParams","symbolKind":"property","title":"cardParams","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cardParams","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"cardParams","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePaymentsUI"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"A configured ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":" with the entered card number, expiration date, cvc, and"},{"type":"text","text":" "},{"text":"postal code (if applicable). If any field is invalid or incomplete then this property will return ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"You can monitor when ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"text":" has complete details by implementing","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPFormViewDelegate"},{"text":" and setting the ","type":"text"},{"type":"codeVoice","code":"STPCardFormView's"},{"type":"text","text":" "},{"code":"delegate","type":"codeVoice"},{"type":"text","text":" "},{"text":"property.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardParams"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/cardparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/cardparams"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"url":"\/documentation\/stripepaymentsui","role":"collection","title":"StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"text":" provides a multiline interface for users to input their","type":"text"},{"type":"text","text":" "},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the created "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"type":"text","text":" "},{"text":"is displayed when invalid input is detected.","type":"text"}],"title":"STPCardFormView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardFormView"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/cardParams":{"title":"cardParams","type":"topic","abstract":[{"type":"text","text":"A configured "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":" with the entered card number, expiration date, cvc, and"},{"type":"text","text":" "},{"text":"postal code (if applicable). If any field is invalid or incomplete then this property will return ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You can monitor when "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" has complete details by implementing"},{"text":" ","type":"text"},{"code":"STPFormViewDelegate","type":"codeVoice"},{"type":"text","text":" and setting the "},{"type":"codeVoice","code":"STPCardFormView's"},{"text":" ","type":"text"},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" "},{"type":"text","text":"property."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardParams","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"cardParams","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview\/cardparams","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/cardParams"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentMethodParams":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodParams","type":"topic","role":"symbol","title":"STPPaymentMethodParams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"url":"\/documentation\/stripepaymentsui\/stppaymentmethodparams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"cardParams","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"cardParams"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cardParams"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"text":"STPCardFormView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFormView"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1cardParams\/title","op":"replace","value":"cardParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1cardParams\/fragments","value":[{"kind":"identifier","text":"cardParams"}]}]}]}