{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":":nodoc:","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/SQ","doc:\/\/com.stripe.stripe-payments-ui\/SH","doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP"]}],"topicSections":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Coordinator\/cardFormView(_:didChangeToStateComplete:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/coordinator"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Coordinator"},"metadata":{"roleHeading":"Class","role":"symbol","modules":[{"name":"StripePaymentsUI"}],"externalID":"s:16StripePaymentsUI15STPCardFormViewC11CoordinatorC","symbolKind":"class","title":"STPCardFormView.Coordinator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"extendedModule":"StripePaymentsUI","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments-ui/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SH"},"doc://com.stripe.stripe-payments-ui/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui","title":"StripePaymentsUI","type":"topic"},"doc://com.stripe.stripe-payments-ui/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments-ui/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP"},"doc://com.stripe.stripe-payments-ui/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SQ"},"doc://com.stripe.stripe-payments-ui/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewDelegate":{"title":"STPCardFormViewDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormViewDelegate"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewDelegate"}],"kind":"symbol","abstract":[{"code":"STPCardFormViewDelegate","type":"codeVoice"},{"type":"text","text":" defines the interface that should be adopted to receive"},{"type":"text","text":" "},{"type":"text","text":"updates from "},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" instances."}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewdelegate"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Coordinator/cardFormView(_:didChangeToStateComplete:)":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Coordinator\/cardFormView(_:didChangeToStateComplete:)","url":"\/documentation\/stripepaymentsui\/stpcardformview\/coordinator\/cardformview(_:didchangetostatecomplete:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardFormView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPCardFormView","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView"},{"text":", ","kind":"text"},{"text":"didChangeToStateComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[{"text":":no-doc:","type":"text"}],"title":"cardFormView(_:didChangeToStateComplete:)","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"text":" provides a multiline interface for users to input their","type":"text"},{"text":" ","type":"text"},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"text":" ","type":"text"},{"text":"the created ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is displayed when invalid input is detected."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview","navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"title":"STPCardFormView","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Coordinator":{"abstract":[{"text":":nodoc:","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"title":"STPCardFormView.Coordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinator"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/coordinator","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Coordinator"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments-ui/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPCardFormViewDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/title"},{"value":[{"text":"STPCardFormViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/fragments"},{"value":[{"kind":"identifier","text":"STPCardFormViewDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/navigatorTitle"},{"value":"STPCardFormView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title"},{"value":[{"kind":"identifier","text":"STPCardFormView"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments"},{"value":[{"kind":"identifier","text":"STPCardFormView"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle"}]}]}