{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"text":"STPCardFormViewDelegate","preciseIdentifier":"c:@M@StripePaymentsUI@objc(pl)STPCardFormViewDelegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"STPCardFormViewDelegate","type":"text"}]}],"name":"See Also"}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"StripePaymentsUI"}],"title":"delegate","externalID":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView(py)delegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(pl)STPCardFormViewDelegate","text":"STPCardFormViewDelegate"},{"kind":"text","text":"?"}]},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"]]},"sections":[],"abstract":[{"type":"text","text":"The delegate to notify when the card form transitions to or from being complete."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/delegate"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"title":"STPCardFormView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"type":"topic","abstract":[{"code":"STPCardFormView","type":"codeVoice"},{"text":" provides a multiline interface for users to input their","type":"text"},{"text":" ","type":"text"},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"text":" ","type":"text"},{"text":"the created ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"text":" ","type":"text"},{"text":"is displayed when invalid input is detected.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/delegate":{"url":"\/documentation\/stripepaymentsui\/stpcardformview\/delegate","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCardFormViewDelegate","preciseIdentifier":"c:@M@StripePaymentsUI@objc(pl)STPCardFormViewDelegate"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"abstract":[{"text":"The delegate to notify when the card form transitions to or from being complete.","type":"text"}],"title":"delegate"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewDelegate":{"url":"\/documentation\/stripepaymentsui\/stpcardformviewdelegate","abstract":[{"type":"codeVoice","code":"STPCardFormViewDelegate"},{"type":"text","text":" defines the interface that should be adopted to receive"},{"type":"text","text":" "},{"type":"text","text":"updates from "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" instances."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewDelegate"}],"kind":"symbol","title":"STPCardFormViewDelegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormViewDelegate"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","kind":"symbol","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"url":"\/documentation\/stripepaymentsui","type":"topic","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<STPCardFormViewDelegate>","preciseIdentifier":"c:Qo@M@StripePaymentsUI@objc(pl)STPCardFormViewDelegate"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"text":"STPCardFormView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"text":"STPCardFormView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/title","value":"STPCardFormViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/fragments","value":[{"kind":"identifier","text":"STPCardFormViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/navigatorTitle","value":[{"text":"STPCardFormViewDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}