{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/disabledBackgroundColor"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"disabledBackgroundColor"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"disabledBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"StripePaymentsUI"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView(py)disabledBackgroundColor","title":"disabledBackgroundColor"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/disabledbackgroundcolor"]},{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/disabledbackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The background color that is automatically applied to the input fields when  ","type":"text"},{"type":"codeVoice","code":"isUserInteractionEnabled"},{"type":"text","text":" is set to `false."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"disabledBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"accessible as possible, so any customization should avoid decreasing contrast between the text and background.","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/disabledBackgroundColor":{"navigatorTitle":[{"text":"disabledBackgroundColor","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/disabledbackgroundcolor","role":"symbol","abstract":[{"type":"text","text":"The background color that is automatically applied to the input fields when  "},{"type":"codeVoice","code":"isUserInteractionEnabled"},{"type":"text","text":" is set to `false."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/disabledBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disabledBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?","kind":"text"}],"type":"topic","title":"disabledBackgroundColor","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"type":"topic","navigatorTitle":[{"text":"STPCardFormView","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" provides a multiline interface for users to input their"},{"text":" ","type":"text"},{"type":"text","text":"credit card details as well as billing postal code and provides an interface to access"},{"type":"text","text":" "},{"type":"text","text":"the created "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"text":" ","type":"text"},{"type":"text","text":"is displayed when invalid input is detected."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCardFormView","kind":"identifier"}],"title":"STPCardFormView","url":"\/documentation\/stripepaymentsui\/stpcardformview","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"disabledBackgroundColor","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"disabledBackgroundColor","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"disabledBackgroundColor","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1disabledBackgroundColor\/title","value":"disabledBackgroundColor","op":"replace"},{"value":[{"text":"disabledBackgroundColor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1disabledBackgroundColor\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView","op":"replace"},{"value":[{"kind":"identifier","text":"STPCardFormView"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments"}]}]}
