{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","kind":"typeIdentifier","text":"STPCardFormViewStyle"},{"kind":"text","text":" = .standard)"}]}]},{"kind":"parameters","parameters":[{"name":"style","content":[{"inlineContent":[{"text":"The visual style to use for this instance. @see STPCardFormViewStyle","type":"text"}],"type":"paragraph"}]}]}],"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView(im)initWithStyle:","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:"}],"modules":[{"name":"StripePaymentsUI"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCardFormViewStyle","preciseIdentifier":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol","title":"init(style:)","symbolKind":"init"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/init(style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/init(style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Public initializer for "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/init(style:)"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/init(style:)":{"navigatorTitle":[{"text":"initWithStyle:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/init(style:)","abstract":[{"text":"Public initializer for ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":"."}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/init(style:)","title":"init(style:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle","text":"STPCardFormViewStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"navigatorTitle":[{"text":"STPCardFormView","kind":"identifier"}],"title":"STPCardFormView","url":"\/documentation\/stripepaymentsui\/stpcardformview","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormView","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"text":" provides a multiline interface for users to input their","type":"text"},{"text":" ","type":"text"},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"text":" ","type":"text"},{"text":"the created ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"text":" ","type":"text"},{"text":"is displayed when invalid input is detected.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle":{"title":"STPCardFormViewStyle","abstract":[{"text":"Options for configuring the display of an ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"text":" instance.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewStyle"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormViewStyle"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui","role":"collection","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithStyle:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStyle:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPCardFormViewStyle","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","preciseIdentifier":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle"},{"kind":"text","text":") "},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"style","content":[{"inlineContent":[{"text":"The visual style to use for this instance. @see STPCardFormViewStyle","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1init(style:)\/title","op":"replace","value":"initWithStyle:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1init(style:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStyle:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","op":"replace","value":"STPCardFormView"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","op":"replace","value":[{"text":"STPCardFormView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","op":"replace","value":[{"text":"STPCardFormView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/title","op":"replace","value":"STPCardFormViewStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCardFormViewStyle"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/navigatorTitle","op":"replace","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}