{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The list of preferred networks that should be used to process"},{"type":"text","text":" "},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"type":"text","text":" "},{"type":"text","text":"network themselves."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"]]},"kind":"symbol","metadata":{"modules":[{"name":"StripePaymentsUI"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView(im)preferredNetworks","title":"preferredNetworks_objc()","navigatorTitle":[{"text":"preferredNetworks","kind":"identifier"}],"roleHeading":"Instance Method","platforms":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredNetworks_objc","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/preferredNetworks_objc()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(preferredNetworks) "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredNetworks_objc"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]?"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"The first preferred network that matches any available network will"},{"type":"text","text":" "},{"type":"text","text":"be offered to the customer. If no preferred network is applicable, the"},{"type":"text","text":" "},{"type":"text","text":"customer will select the network."}],"type":"paragraph"},{"inlineContent":[{"text":"In Objective-C, this is an array of NSNumbers representing STPCardBrands.","type":"text"},{"text":" ","type":"text"},{"text":"For example:","type":"text"},{"text":" ","type":"text"},{"text":"[textField setPreferredNetworks:@[[NSNumber numberWithInt:STPCardBrandVisa]]];","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/preferrednetworks_objc()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/preferrednetworks_objc()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/preferredNetworks_objc()":{"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredNetworks_objc","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]?","kind":"text"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview\/preferrednetworks_objc()","title":"preferredNetworks_objc()","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/preferredNetworks_objc()","navigatorTitle":[{"text":"preferredNetworks","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The list of preferred networks that should be used to process","type":"text"},{"text":" ","type":"text"},{"text":"payments made with a co-branded card if your user hasn’t selected a","type":"text"},{"text":" ","type":"text"},{"text":"network themselves.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormView","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardFormView","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","abstract":[{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" provides a multiline interface for users to input their"},{"type":"text","text":" "},{"type":"text","text":"credit card details as well as billing postal code and provides an interface to access"},{"type":"text","text":" "},{"type":"text","text":"the created "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"type":"text","text":" "},{"type":"text","text":"is displayed when invalid input is detected."}],"title":"STPCardFormView","role":"symbol","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"preferredNetworks","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"preferredNetworks","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"preferredNetworks"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"preferredNetworks","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1preferredNetworks_objc()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"preferredNetworks","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1preferredNetworks_objc()\/fragments"},{"op":"replace","value":"STPCardFormView","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title"},{"op":"replace","value":[{"text":"STPCardFormView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments"},{"op":"replace","value":[{"text":"STPCardFormView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}