{"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView(im)setPreferredNetworks:","modules":[{"name":"StripePaymentsUI"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredNetworks_objc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferredNetworks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]?)"}],"roleHeading":"Instance Method","platforms":[],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPreferredNetworks:"}],"role":"symbol","title":"setPreferredNetworks_objc(preferredNetworks:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/setPreferredNetworks_objc(preferredNetworks:)"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/setpreferrednetworks_objc(preferrednetworks:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/setpreferrednetworks_objc(preferrednetworks:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(setPreferredNetworks:) "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredNetworks_objc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferredNetworks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"]?)"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The first preferred network that matches any available network will"},{"type":"text","text":" "},{"type":"text","text":"be offered to the customer. If no preferred network is applicable, the"},{"type":"text","text":" "},{"type":"text","text":"customer will select the network."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In Objective-C, this is an array of NSNumbers representing STPCardBrands."},{"type":"text","text":" "},{"type":"text","text":"For example:"},{"type":"text","text":" "},{"type":"text","text":"[textField setPreferredNetworks:@[[NSNumber numberWithInt:STPCardBrandVisa]]];"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"The list of preferred networks that should be used to process"},{"type":"text","text":" "},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"type":"text","text":" "},{"type":"text","text":"network themselves."}],"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/setPreferredNetworks_objc(preferredNetworks:)":{"type":"topic","kind":"symbol","title":"setPreferredNetworks_objc(preferredNetworks:)","deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredNetworks_objc"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferredNetworks"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]?)"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/setpreferrednetworks_objc(preferrednetworks:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPreferredNetworks:"}],"abstract":[{"type":"text","text":"The list of preferred networks that should be used to process"},{"type":"text","text":" "},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"type":"text","text":" "},{"type":"text","text":"network themselves."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/setPreferredNetworks_objc(preferredNetworks:)","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"kind":"symbol","type":"topic","title":"STPCardFormView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview","navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" provides a multiline interface for users to input their"},{"text":" ","type":"text"},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"type":"text","text":" "},{"text":"the created ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"type":"text","text":" "},{"type":"text","text":"is displayed when invalid input is detected."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"setPreferredNetworks:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPreferredNetworks:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setPreferredNetworks:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSNumber *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preferredNetworks"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1setPreferredNetworks_objc(preferredNetworks:)\/title","value":"setPreferredNetworks:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1setPreferredNetworks_objc(preferredNetworks:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPreferredNetworks:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"kind":"identifier","text":"STPCardFormView"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFormView"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}