{"sections":[],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodRevolutPayParams(im)init","symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"init","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPayParams"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodrevolutpayparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPayParams\/init","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodRevolutPayParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPayParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodRevolutPayParams","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"STPPaymentMethodRevolutPayParams","url":"\/documentation\/stripepayments\/stppaymentmethodrevolutpayparams","navigatorTitle":[{"text":"STPPaymentMethodRevolutPayParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create a RevolutPay Payment Method","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodRevolutPayParams/init":{"title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodrevolutpayparams\/init","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPayParams\/init","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPayParams\/title","value":"STPPaymentMethodRevolutPayParams","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodRevolutPayParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPayParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPayParams\/navigatorTitle","value":[{"text":"STPPaymentMethodRevolutPayParams","kind":"identifier"}],"op":"replace"}]}]}