{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/Equatable-Implementations"},"topicSections":[{"anchor":"Operators","generated":true,"title":"Operators","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/!=(_:_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardvalidationstate\/equatable-implementations"]}],"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"type":"text","text":"value, or incomplete value."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidationstate","kind":"symbol","title":"STPCardValidationState","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidationState"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardValidationState"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/!=(_:_:)":{"role":"symbol","type":"topic","title":"!=(_:_:)","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/!=(_:_:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidationstate\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title","op":"replace","value":"STPCardValidationState"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCardValidationState"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPCardValidationState"}]}]}]}