{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incomplete"}]}]}],"abstract":[{"text":"The field’s contents are not currently valid, but could be by typing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"additional characters. For example, a CVC of “1”."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/incomplete"},"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidationstate\/incomplete"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardvalidationstate\/incomplete"]}],"metadata":{"navigatorTitle":[{"text":"STPCardValidationStateIncomplete","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPCardValidationState@STPCardValidationStateIncomplete","modules":[{"name":"StripePayments"}],"title":"STPCardValidationState.incomplete","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"incomplete","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidationState"}],"role":"symbol","abstract":[{"text":"These fields indicate whether a card field represents a valid value, invalid","type":"text"},{"text":" ","type":"text"},{"text":"value, or incomplete value.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardValidationState"}],"url":"\/documentation\/stripepayments\/stpcardvalidationstate","type":"topic","title":"STPCardValidationState"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/incomplete":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/incomplete","navigatorTitle":[{"text":"STPCardValidationStateIncomplete","kind":"identifier"}],"abstract":[{"text":"The field’s contents are not currently valid, but could be by typing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"additional characters. For example, a CVC of “1”."}],"type":"topic","url":"\/documentation\/stripepayments\/stpcardvalidationstate\/incomplete","role":"symbol","title":"STPCardValidationState.incomplete","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incomplete"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPCardValidationStateIncomplete","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"STPCardValidationStateIncomplete","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPCardValidationStateIncomplete","kind":"identifier"}]}]}},{"value":"STPCardValidationState","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments","op":"replace","value":[{"text":"STPCardValidationState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardValidationState"}]},{"value":"STPCardValidationStateIncomplete","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1incomplete\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1incomplete\/fragments","value":[{"text":"STPCardValidationStateIncomplete","kind":"identifier"}]}]}]}