{"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidationstate\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/init(rawValue:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"]]},"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","title":"init(rawValue:)","externalID":"s:14StripePayments22STPCardValidationStateO8rawValueACSgSi_tcfc","roleHeading":"Initializer","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCardValidationState"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidationState"}],"title":"STPCardValidationState","kind":"symbol","abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"type":"text","text":"value, or incomplete value."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","url":"\/documentation\/stripepayments\/stpcardvalidationstate"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/init(rawValue:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stpcardvalidationstate\/init(rawvalue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/init(rawValue:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title","value":"STPCardValidationState"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments","value":[{"text":"STPCardValidationState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle","value":[{"text":"STPCardValidationState","kind":"identifier"}]}]}]}