{"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidationstate\/invalid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardvalidationstate\/invalid"]}],"abstract":[{"type":"text","text":"The field’s contents are invalid. For example, an expiration date"},{"type":"text","text":" "},{"text":"of “13\/42”.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@StripePayments@E@STPCardValidationState@STPCardValidationStateInvalid","modules":[{"name":"StripePayments"}],"roleHeading":"Case","symbolKind":"case","title":"STPCardValidationState.invalid","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalid","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardValidationStateInvalid"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalid","kind":"identifier"}]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/invalid","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"title":"STPCardValidationState","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPCardValidationState","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","url":"\/documentation\/stripepayments\/stpcardvalidationstate","abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"text":"value, or incomplete value.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardValidationState"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/invalid":{"role":"symbol","type":"topic","title":"STPCardValidationState.invalid","navigatorTitle":[{"kind":"identifier","text":"STPCardValidationStateInvalid"}],"kind":"symbol","abstract":[{"type":"text","text":"The field’s contents are invalid. For example, an expiration date"},{"text":" ","type":"text"},{"type":"text","text":"of “13\/42”."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/invalid","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalid"}],"url":"\/documentation\/stripepayments\/stpcardvalidationstate\/invalid"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPCardValidationStateInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCardValidationStateInvalid"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPCardValidationStateInvalid"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title","op":"replace","value":"STPCardValidationState"},{"value":[{"kind":"identifier","text":"STPCardValidationState"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments"},{"op":"replace","value":[{"text":"STPCardValidationState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle"},{"op":"replace","value":"STPCardValidationStateInvalid","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1invalid\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1invalid\/fragments","value":[{"kind":"identifier","text":"STPCardValidationStateInvalid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}