{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"]]},"metadata":{"navigatorTitle":[{"text":"STPCardValidationStateValid","kind":"identifier"}],"title":"STPCardValidationState.valid","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPCardValidationState@STPCardValidationStateValid","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/valid","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidationstate\/valid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidationstate\/valid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"The field’s contents are valid. For example, a valid, 16-digit card number."},{"type":"text","text":" "},{"type":"text","text":"Note that valid values may not be complete. For example: a US Zip code can"},{"type":"text","text":" "},{"type":"text","text":"be 5 or 9 digits. A 5-digit code is Valid, but more text could be entered"},{"type":"text","text":" "},{"type":"text","text":"to transition to incomplete again. American Express CVC codes can be 3 or"},{"type":"text","text":" "},{"type":"text","text":"4 digits and both will be treated as Valid."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/valid":{"kind":"symbol","type":"topic","abstract":[{"text":"The field’s contents are valid. For example, a valid, 16-digit card number.","type":"text"},{"text":" ","type":"text"},{"text":"Note that valid values may not be complete. For example: a US Zip code can","type":"text"},{"text":" ","type":"text"},{"text":"be 5 or 9 digits. A 5-digit code is Valid, but more text could be entered","type":"text"},{"text":" ","type":"text"},{"text":"to transition to incomplete again. American Express CVC codes can be 3 or","type":"text"},{"text":" ","type":"text"},{"text":"4 digits and both will be treated as Valid.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}],"title":"STPCardValidationState.valid","navigatorTitle":[{"text":"STPCardValidationStateValid","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/valid","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidationstate\/valid"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"type":"text","text":"value, or incomplete value."}],"kind":"symbol","type":"topic","title":"STPCardValidationState","role":"symbol","navigatorTitle":[{"text":"STPCardValidationState","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcardvalidationstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardValidationState","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPCardValidationStateValid","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPCardValidationStateValid","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPCardValidationStateValid","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPCardValidationStateValid","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1valid\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardValidationStateValid"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1valid\/fragments"},{"op":"replace","value":"STPCardValidationState","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title"},{"op":"replace","value":[{"text":"STPCardValidationState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardValidationState"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}