{"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/Equatable-Implementations"},"variants":[{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus"]]},"metadata":{"title":"Equatable Implementations","modules":[{"name":"StripeApplePay"}],"role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus/!=(_:_:)":{"kind":"symbol","title":"!=(_:_:)","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/!=(_:_:)"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentStatus"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentStatus"}],"abstract":[{"type":"text","text":"An enum representing the status of a payment requested from the user."}],"title":"STPApplePayContext.PaymentStatus","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"text":" ","type":"text"},{"text":"Usage looks like this:","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","title":"STPApplePayContext","role":"symbol","kind":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPApplePayContext"}],"navigatorTitle":[{"kind":"identifier","text":"STPApplePayContext"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"abstract":[{"text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripeapplepay","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","role":"collection","title":"StripeApplePay"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","value":"STPApplePayContext"},{"value":[{"text":"STPApplePayContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPApplePayContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}