{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/error","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus\/error"]}],"abstract":[{"text":"The payment failed due to an unforeseen error, such as the user’s Internet connection being offline.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"role":"symbol","symbolKind":"case","modules":[{"name":"StripeApplePay"}],"title":"STPApplePayContext.PaymentStatus.error","roleHeading":"Case","externalID":"s:14StripeApplePay08STPAppleC7ContextC13PaymentStatusO5erroryA2EmF"},"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus/error":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus\/error","abstract":[{"text":"The payment failed due to an unforeseen error, such as the user’s Internet connection being offline.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"title":"STPApplePayContext.PaymentStatus.error","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus\/error","type":"topic","role":"symbol"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/PaymentStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PaymentStatus"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum representing the status of a payment requested from the user."}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/PaymentStatus","role":"symbol","type":"topic","url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/paymentstatus","navigatorTitle":[{"kind":"identifier","text":"PaymentStatus"}],"title":"STPApplePayContext.PaymentStatus"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"url":"\/documentation\/stripeapplepay","type":"topic","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","kind":"symbol","title":"StripeApplePay","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}],"role":"collection"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"title":"STPApplePayContext","type":"topic","role":"symbol","abstract":[{"text":"A helper class that implements Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Usage looks like this:"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPApplePayContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"url":"\/documentation\/stripeapplepay\/stpapplepaycontext","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPApplePayContext","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPApplePayContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","value":[{"text":"STPApplePayContext","kind":"identifier"}]}]}]}