{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alwaysDark","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The bank account collector will always use colors appropriate for dark mode UI.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"alwaysDark","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle@STPBankAccountCollectorUserInterfaceStyleAlwaysDark","roleHeading":"Case","title":"STPBankAccountCollectorUserInterfaceStyle.alwaysDark"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/alwaysdark"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/alwaysdark"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysDark"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle":{"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","title":"STPBankAccountCollectorUserInterfaceStyle","kind":"symbol","abstract":[{"text":"Style options for colors in the bank account collector.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/alwaysDark":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alwaysDark","kind":"identifier"}],"navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysDark","url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/alwaysdark","role":"symbol","abstract":[{"type":"text","text":"The bank account collector will always use colors appropriate for dark mode UI."}],"title":"STPBankAccountCollectorUserInterfaceStyle.alwaysDark","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/title","value":"STPBankAccountCollectorUserInterfaceStyle","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/navigatorTitle","value":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1alwaysDark\/title","value":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark","op":"replace"},{"op":"replace","value":[{"text":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1alwaysDark\/fragments"}]}]}