{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysLight"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alwaysLight","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/alwayslight"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/alwayslight"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The bank account collector will always use colors appropriate for light mode UI."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysLight"}],"externalID":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle@STPBankAccountCollectorUserInterfaceStyleAlwaysLight","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"StripePayments"}],"title":"STPBankAccountCollectorUserInterfaceStyle.alwaysLight"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/alwaysLight":{"title":"STPBankAccountCollectorUserInterfaceStyle.alwaysLight","abstract":[{"text":"The bank account collector will always use colors appropriate for light mode UI.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alwaysLight"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/alwayslight","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysLight","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle","role":"symbol","abstract":[{"text":"Style options for colors in the bank account collector.","type":"text"}],"navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"title":"STPBankAccountCollectorUserInterfaceStyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1alwaysLight\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1alwaysLight\/fragments","op":"replace"},{"value":"STPBankAccountCollectorUserInterfaceStyle","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/fragments","op":"replace"},{"value":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}