{"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"title":"STPBankAccountCollectorUserInterfaceStyle.automatic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAutomatic"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle@STPBankAccountCollectorUserInterfaceStyleAutomatic"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"(default) The bank account collector will automatically switch between light and dark mode compatible colors based on device settings.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/automatic"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/automatic"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/automatic","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/automatic":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"type":"topic","title":"STPBankAccountCollectorUserInterfaceStyle.automatic","url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/automatic","navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyleAutomatic","kind":"identifier"}],"abstract":[{"text":"(default) The bank account collector will automatically switch between light and dark mode compatible colors based on device settings.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/automatic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle","title":"STPBankAccountCollectorUserInterfaceStyle","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","abstract":[{"type":"text","text":"Style options for colors in the bank account collector."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPBankAccountCollectorUserInterfaceStyleAutomatic"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"STPBankAccountCollectorUserInterfaceStyleAutomatic","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAutomatic"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1automatic\/title","value":"STPBankAccountCollectorUserInterfaceStyleAutomatic"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1automatic\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAutomatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/title","value":"STPBankAccountCollectorUserInterfaceStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/fragments","value":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/navigatorTitle","value":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}]}]}]}