{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/hash(into:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/hash(into:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"modules":[{"name":"StripePayments","relatedModules":["Swift"]}],"title":"hash(into:)","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","extendedModule":"Swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/RawRepresentable-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/rawrepresentable-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/hash(into:)":{"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"role":"symbol","title":"hash(into:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/hash(into:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/hash(into:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle":{"abstract":[{"text":"Style options for colors in the bank account collector.","type":"text"}],"title":"STPBankAccountCollectorUserInterfaceStyle","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","role":"symbol","navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/title","op":"replace","value":"STPBankAccountCollectorUserInterfaceStyle"},{"value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/fragments","op":"replace"},{"op":"replace","value":[{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}