{"metadata":{"title":"accountHolderType","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountParams(py)accountHolderType","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountHolderType"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUSBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"accountHolderType"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams"]]},"kind":"symbol","abstract":[{"type":"text","text":"Account holder type"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountHolderType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodUSBankAccountHolderType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accountholdertype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accountholdertype"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams\/accountHolderType","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}],"kind":"symbol","title":"STPPaymentMethodUSBankAccountParams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a US Bank Account Payment Method"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams/accountHolderType":{"title":"accountHolderType","navigatorTitle":[{"text":"accountHolderType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams\/accountHolderType","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accountholdertype","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountHolderType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType","text":"STPPaymentMethodUSBankAccountHolderType"}],"abstract":[{"text":"Account holder type","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType":{"kind":"symbol","title":"STPPaymentMethodUSBankAccountHolderType","role":"symbol","abstract":[{"text":"Account holder type","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype","type":"topic","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"accountHolderType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"accountHolderType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPPaymentMethodUSBankAccountHolderType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType"},{"kind":"text","text":" "},{"text":"accountHolderType","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/title","value":"STPPaymentMethodUSBankAccountParams","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams~1accountHolderType\/title","value":"accountHolderType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams~1accountHolderType\/fragments","value":[{"text":"accountHolderType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/title","value":"STPPaymentMethodUSBankAccountHolderType"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}