{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The raw underlying account holder type string sent to the server."},{"type":"text","text":" "},{"type":"text","text":"You can use this if you want to create a param of a bank not yet supported"},{"text":" ","type":"text"},{"text":"by the current version of the SDK’s ","type":"text"},{"code":"STPPaymentMethodUSBankAccountHolderType","type":"codeVoice"},{"type":"text","text":" enum."},{"text":" ","type":"text"},{"type":"text","text":"Setting this to a value not known by the SDK causes "},{"type":"codeVoice","code":"accountHolderType"},{"type":"text","text":" to"},{"text":" ","type":"text"},{"text":"return ","type":"text"},{"type":"codeVoice","code":".unknown"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountHolderTypeString","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams\/accountHolderTypeString"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accountholdertypestring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accountholdertypestring"]}],"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountParams(py)accountHolderTypeString","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountHolderTypeString","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"accountHolderTypeString"}],"roleHeading":"Instance Property","title":"accountHolderTypeString"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams/accountHolderTypeString":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams\/accountHolderTypeString","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"accountHolderTypeString","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"accountHolderTypeString"}],"abstract":[{"type":"text","text":"The raw underlying account holder type string sent to the server."},{"text":" ","type":"text"},{"type":"text","text":"You can use this if you want to create a param of a bank not yet supported"},{"text":" ","type":"text"},{"type":"text","text":"by the current version of the SDK’s "},{"code":"STPPaymentMethodUSBankAccountHolderType","type":"codeVoice"},{"type":"text","text":" enum."},{"type":"text","text":" "},{"type":"text","text":"Setting this to a value not known by the SDK causes "},{"type":"codeVoice","code":"accountHolderType"},{"type":"text","text":" to"},{"text":" ","type":"text"},{"text":"return ","type":"text"},{"type":"codeVoice","code":".unknown"}],"title":"accountHolderTypeString","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accountholdertypestring"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams":{"role":"symbol","abstract":[{"text":"An object representing parameters used to create a US Bank Account Payment Method","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams","title":"STPPaymentMethodUSBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"accountHolderTypeString"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"accountHolderTypeString"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"accountHolderTypeString","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"accountHolderTypeString","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams~1accountHolderTypeString\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams~1accountHolderTypeString\/fragments","op":"replace","value":[{"text":"accountHolderTypeString","kind":"identifier"}]},{"value":"STPPaymentMethodUSBankAccountParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}