{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accounttype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accounttype"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountParams(py)accountType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodUSBankAccountType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType"}],"navigatorTitle":[{"text":"accountType","kind":"identifier"}],"title":"accountType"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams"]]},"abstract":[{"text":"Account type","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams\/accountType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType","text":"STPPaymentMethodUSBankAccountType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams/accountType":{"title":"accountType","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams\/accountType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType","text":"STPPaymentMethodUSBankAccountType","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/accounttype","type":"topic","navigatorTitle":[{"text":"accountType","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Account type","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType":{"title":"STPPaymentMethodUSBankAccountType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"abstract":[{"type":"text","text":"Account type"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}],"title":"STPPaymentMethodUSBankAccountParams","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams","abstract":[{"text":"An object representing parameters used to create a US Bank Account Payment Method","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"accountType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"accountType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType","text":"STPPaymentMethodUSBankAccountType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams~1accountType\/title","value":"accountType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams~1accountType\/fragments","value":[{"text":"accountType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/title","value":"STPPaymentMethodUSBankAccountType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/title","value":"STPPaymentMethodUSBankAccountParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}],"op":"replace"}]}]}