{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams\/routingNumber","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"routingNumber"}],"title":"routingNumber","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountParams(py)routingNumber","symbolKind":"property","role":"symbol","modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/routingnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/routingnumber"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams"]]},"kind":"symbol","abstract":[{"type":"text","text":"Routing number of the bank account"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams/routingNumber":{"navigatorTitle":[{"kind":"identifier","text":"routingNumber"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams\/routingnumber","kind":"symbol","abstract":[{"text":"Routing number of the bank account","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"routingNumber","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams\/routingNumber","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams":{"type":"topic","role":"symbol","title":"STPPaymentMethodUSBankAccountParams","abstract":[{"text":"An object representing parameters used to create a US Bank Account Payment Method","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"routingNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"routingNumber","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"routingNumber","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams~1routingNumber\/title","value":"routingNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams~1routingNumber\/fragments","value":[{"kind":"identifier","text":"routingNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/title","value":"STPPaymentMethodUSBankAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}