{"abstract":[{"type":"text","text":"The default settings."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsselectioncustomization\/defaultsettings()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsselectioncustomization\/defaultsettings()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization","text":"STPThreeDSSelectionCustomization","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/defaultSettings()","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization","text":"STPThreeDSSelectionCustomization","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"defaultSettings","kind":"identifier"}],"title":"defaultSettings()","modules":[{"name":"StripePayments"}],"symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization(cm)defaultSettings","role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/defaultSettings()":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/defaultSettings()","type":"topic","title":"defaultSettings()","url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/defaultsettings()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"STPThreeDSSelectionCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization"}],"role":"symbol","abstract":[{"text":"The default settings.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"defaultSettings"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization":{"abstract":[{"type":"text","text":"A customization object that configures the appearance of"},{"type":"text","text":" "},{"type":"text","text":"radio buttons and checkboxes."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}],"title":"STPThreeDSSelectionCustomization","url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"defaultSettings","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"defaultSettings","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization","kind":"typeIdentifier","text":"STPThreeDSSelectionCustomization"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1defaultSettings()\/title","value":"defaultSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1defaultSettings()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/title","value":"STPThreeDSSelectionCustomization","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/navigatorTitle","value":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}