{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primarySelectedColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"StripePayments"}],"title":"primarySelectedColor","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization(py)primarySelectedColor","navigatorTitle":[{"text":"primarySelectedColor","kind":"identifier"}]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The primary color of the selected state."},{"type":"text","text":" "},{"type":"text","text":"Defaults to blue."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/primarySelectedColor"},"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsselectioncustomization\/primaryselectedcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsselectioncustomization\/primaryselectedcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primarySelectedColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization","kind":"symbol","abstract":[{"text":"A customization object that configures the appearance of","type":"text"},{"text":" ","type":"text"},{"text":"radio buttons and checkboxes.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization","type":"topic","role":"symbol","navigatorTitle":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"title":"STPThreeDSSelectionCustomization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/primarySelectedColor":{"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/primaryselectedcolor","title":"primarySelectedColor","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primarySelectedColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"primarySelectedColor","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The primary color of the selected state."},{"type":"text","text":" "},{"type":"text","text":"Defaults to blue."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/primarySelectedColor"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"primarySelectedColor"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"primarySelectedColor"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"primarySelectedColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/title","op":"replace","value":"STPThreeDSSelectionCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/fragments","op":"replace","value":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/navigatorTitle","op":"replace","value":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1primarySelectedColor\/title","op":"replace","value":"primarySelectedColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1primarySelectedColor\/fragments","op":"replace","value":[{"text":"primarySelectedColor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}