{"metadata":{"title":"unselectedBorderColor","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization(py)unselectedBorderColor","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"unselectedBorderColor","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unselectedBorderColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol"},"abstract":[{"type":"text","text":"The color of the border drawn around the view in the unselected state."},{"type":"text","text":" "},{"type":"text","text":"Defaults to blue."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"unselectedBorderColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/unselectedBorderColor","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsselectioncustomization\/unselectedbordercolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsselectioncustomization\/unselectedbordercolor"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/unselectedBorderColor":{"role":"symbol","url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/unselectedbordercolor","type":"topic","kind":"symbol","title":"unselectedBorderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"unselectedBorderColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/unselectedBorderColor","navigatorTitle":[{"text":"unselectedBorderColor","kind":"identifier"}],"abstract":[{"type":"text","text":"The color of the border drawn around the view in the unselected state."},{"type":"text","text":" "},{"text":"Defaults to blue.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization","title":"STPThreeDSSelectionCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization","navigatorTitle":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"abstract":[{"text":"A customization object that configures the appearance of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"radio buttons and checkboxes."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"unselectedBorderColor","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"unselectedBorderColor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" * "},{"text":"unselectedBorderColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1unselectedBorderColor\/title","value":"unselectedBorderColor","op":"replace"},{"op":"replace","value":[{"text":"unselectedBorderColor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1unselectedBorderColor\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/title","value":"STPThreeDSSelectionCustomization","op":"replace"},{"op":"replace","value":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/fragments"},{"value":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/navigatorTitle","op":"replace"}]}]}