{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"A company holds this bank account.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountholdertype\/company"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccountholdertype\/company"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/company","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"STPBankAccountHolderTypeCompany","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPBankAccountHolderType@STPBankAccountHolderTypeCompany","title":"STPBankAccountHolderType.company","modules":[{"name":"StripePayments"}],"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"company","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"company","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/company":{"navigatorTitle":[{"text":"STPBankAccountHolderTypeCompany","kind":"identifier"}],"title":"STPBankAccountHolderType.company","abstract":[{"text":"A company holds this bank account.","type":"text"}],"url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/company","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/company","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"company","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType":{"navigatorTitle":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"title":"STPBankAccountHolderType","abstract":[{"type":"text","text":"The type of entity that holds a bank account."}],"url":"\/documentation\/stripepayments\/stpbankaccountholdertype","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountHolderType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPBankAccountHolderTypeCompany","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPBankAccountHolderTypeCompany","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"STPBankAccountHolderTypeCompany","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPBankAccountHolderTypeCompany","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType~1company\/title","op":"replace"},{"value":[{"text":"STPBankAccountHolderTypeCompany","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType~1company\/fragments","op":"replace"},{"value":"STPBankAccountHolderType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/title","op":"replace"},{"value":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/fragments","op":"replace"},{"value":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/navigatorTitle","op":"replace"}]}]}