{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"CustomStringConvertible Implementations","modules":[{"name":"StripePayments"}],"role":"collectionGroup"},"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountholdertype\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/description"],"title":"Instance Properties"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/description":{"abstract":[],"role":"symbol","title":"description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType":{"kind":"symbol","title":"STPBankAccountHolderType","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountHolderType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPBankAccountHolderType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountholdertype","abstract":[{"type":"text","text":"The type of entity that holds a bank account."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPBankAccountHolderType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/fragments","value":[{"text":"STPBankAccountHolderType","kind":"identifier"}]},{"value":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/navigatorTitle"}]}]}