{"kind":"symbol","sections":[],"metadata":{"title":"STPBankAccountHolderType.individual","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"individual","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPBankAccountHolderType@STPBankAccountHolderTypeIndividual","symbolKind":"case","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPBankAccountHolderTypeIndividual","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"abstract":[{"text":"An individual holds this bank account.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"individual"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/individual"},"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountholdertype\/individual"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccountholdertype\/individual"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/individual":{"role":"symbol","abstract":[{"text":"An individual holds this bank account.","type":"text"}],"title":"STPBankAccountHolderType.individual","url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/individual","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/individual","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"individual"}],"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountHolderTypeIndividual"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType":{"role":"symbol","title":"STPBankAccountHolderType","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountHolderType"}],"abstract":[{"type":"text","text":"The type of entity that holds a bank account."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountHolderType"}],"url":"\/documentation\/stripepayments\/stpbankaccountholdertype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPBankAccountHolderTypeIndividual"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPBankAccountHolderTypeIndividual","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPBankAccountHolderTypeIndividual","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType~1individual\/title","value":"STPBankAccountHolderTypeIndividual"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType~1individual\/fragments","value":[{"text":"STPBankAccountHolderTypeIndividual","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/title","value":"STPBankAccountHolderType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/fragments","value":[{"kind":"identifier","text":"STPBankAccountHolderType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/navigatorTitle","value":[{"text":"STPBankAccountHolderType","kind":"identifier"}]}]}]}