{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/description","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"s:14StripePayments23STPKlarnaPaymentMethodsO11descriptionSSvp","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","modules":[{"name":"StripePayments"}],"extendedModule":"StripePayments"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/CustomStringConvertible-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/description":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/description","abstract":[],"title":"description","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpklarnapaymentmethods","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"type":"topic","kind":"symbol","title":"STPKlarnaPaymentMethods","abstract":[{"type":"text","text":"Custom payment methods for Klarna"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/CustomStringConvertible-Implementations":{"abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/customstringconvertible-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPKlarnaPaymentMethods","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]},{"value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}