{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/equatable-implementations"]}],"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"StripePayments"}],"roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods"]]},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"abstract":[{"type":"text","text":"Custom payment methods for Klarna"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods","navigatorTitle":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"title":"STPKlarnaPaymentMethods"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/!=(_:_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","abstract":[],"title":"!=(_:_:)","role":"symbol","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/!=(_:_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title","op":"replace","value":"STPKlarnaPaymentMethods"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}