{"metadata":{"role":"symbol","extendedModule":"Swift","title":"hashValue","modules":[{"relatedModules":["Swift"],"name":"StripePayments"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@StripePayments@E@STPKlarnaPaymentMethods","symbolKind":"property","roleHeading":"Instance Property","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/hashvalue"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/hashValue"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/RawRepresentable-Implementations"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/hashValue":{"role":"symbol","abstract":[],"title":"hashValue","kind":"symbol","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/hashvalue","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/hashValue","type":"topic","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/RawRepresentable-Implementations","type":"topic","abstract":[],"kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"navigatorTitle":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"abstract":[{"type":"text","text":"Custom payment methods for Klarna"}],"title":"STPKlarnaPaymentMethods","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title","op":"replace","value":"STPKlarnaPaymentMethods"},{"value":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"op":"replace"}]}]}