{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/installments"},"metadata":{"title":"STPKlarnaPaymentMethods.installments","roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPKlarnaPaymentMethods@STPKlarnaPaymentMethodsInstallments","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"installments","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsInstallments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods"]]},"sections":[],"abstract":[{"type":"text","text":"Offer payments over an arbitrary number of installments. (a.k.a. Slice It)"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installments"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/installments"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/installments"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/installments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/installments","title":"STPKlarnaPaymentMethods.installments","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"installments"}],"url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/installments","navigatorTitle":[{"text":"STPKlarnaPaymentMethodsInstallments","kind":"identifier"}],"type":"topic","abstract":[{"text":"Offer payments over an arbitrary number of installments. (a.k.a. Slice It)","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"kind":"symbol","abstract":[{"text":"Custom payment methods for Klarna","type":"text"}],"title":"STPKlarnaPaymentMethods","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","navigatorTitle":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPKlarnaPaymentMethodsInstallments"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsInstallments"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPKlarnaPaymentMethodsInstallments","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPKlarnaPaymentMethodsInstallments","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1installments\/title"},{"value":[{"text":"STPKlarnaPaymentMethodsInstallments","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1installments\/fragments"},{"value":"STPKlarnaPaymentMethods","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title","op":"replace"},{"op":"replace","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle","op":"replace","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]}]}]}