{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/none"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/none"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/none"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Don’t specify any custom payment methods."}],"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPKlarnaPaymentMethods@STPKlarnaPaymentMethodsNone","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsNone"}],"title":"STPKlarnaPaymentMethods.none"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"navigatorTitle":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"abstract":[{"type":"text","text":"Custom payment methods for Klarna"}],"title":"STPKlarnaPaymentMethods","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/none":{"type":"topic","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/none","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/none","abstract":[{"type":"text","text":"Don’t specify any custom payment methods."}],"title":"STPKlarnaPaymentMethods.none","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsNone"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPKlarnaPaymentMethodsNone"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsNone"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPKlarnaPaymentMethodsNone","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"STPKlarnaPaymentMethods","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title"},{"value":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments","op":"replace"},{"value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle","op":"replace"},{"value":"STPKlarnaPaymentMethodsNone","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1none\/title"},{"value":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsNone"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1none\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}