{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods"]]},"abstract":[{"type":"text","text":"Offer payments over 4 installments. (a.k.a. Pay Later in 4)"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payIn4"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"payIn4","kind":"identifier"}],"navigatorTitle":[{"text":"STPKlarnaPaymentMethodsPayIn4","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPKlarnaPaymentMethods@STPKlarnaPaymentMethodsPayIn4","title":"STPKlarnaPaymentMethods.payIn4"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/payin4"]},{"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/payin4"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods","kind":"symbol","title":"STPKlarnaPaymentMethods","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"abstract":[{"text":"Custom payment methods for Klarna","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/payIn4":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/payin4","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"payIn4","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPKlarnaPaymentMethodsPayIn4","kind":"identifier"}],"abstract":[{"type":"text","text":"Offer payments over 4 installments. (a.k.a. Pay Later in 4)"}],"type":"topic","title":"STPKlarnaPaymentMethods.payIn4"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPKlarnaPaymentMethodsPayIn4"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsPayIn4"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPKlarnaPaymentMethodsPayIn4","kind":"identifier"}]}]}},{"value":"STPKlarnaPaymentMethods","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle","op":"replace","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1payIn4\/title","op":"replace","value":"STPKlarnaPaymentMethodsPayIn4"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1payIn4\/fragments","value":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsPayIn4"}],"op":"replace"}]}]}