{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4OrInstallments","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Offer payments over 4 or an arbitrary number of installments."}],"kind":"symbol","metadata":{"symbolKind":"case","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payIn4OrInstallments","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsPayIn4OrInstallments"}],"title":"STPKlarnaPaymentMethods.payIn4OrInstallments","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPKlarnaPaymentMethods@STPKlarnaPaymentMethodsPayIn4OrInstallments"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"payIn4OrInstallments","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/payin4orinstallments"]},{"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods\/payin4orinstallments"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"url":"\/documentation\/stripepayments\/stpklarnapaymentmethods","title":"STPKlarnaPaymentMethods","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"abstract":[{"type":"text","text":"Custom payment methods for Klarna"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/payIn4OrInstallments":{"url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/payin4orinstallments","type":"topic","abstract":[{"text":"Offer payments over 4 or an arbitrary number of installments.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"payIn4OrInstallments","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsPayIn4OrInstallments"}],"title":"STPKlarnaPaymentMethods.payIn4OrInstallments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4OrInstallments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPKlarnaPaymentMethodsPayIn4OrInstallments","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPKlarnaPaymentMethodsPayIn4OrInstallments","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPKlarnaPaymentMethodsPayIn4OrInstallments","kind":"identifier"}]}]},"op":"replace"},{"value":"STPKlarnaPaymentMethods","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]},{"value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1payIn4OrInstallments\/title","value":"STPKlarnaPaymentMethodsPayIn4OrInstallments"},{"value":[{"text":"STPKlarnaPaymentMethodsPayIn4OrInstallments","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1payIn4OrInstallments\/fragments"}]}]}