{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"sections":[],"metadata":{"title":"!=(_:_:)","modules":[{"name":"StripePayments","relatedModules":["Swift"]}],"extendedModule":"Swift","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@StripePayments@E@STPConnectAccountBusinessType","role":"symbol","roleHeading":"Operator","symbolKind":"op"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/Equatable-Implementations"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/!=(_:_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/!=(_:_:)":{"role":"symbol","kind":"symbol","type":"topic","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/!=(_:_:)","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/!=(_:_:)","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType":{"kind":"symbol","title":"STPConnectAccountBusinessType","abstract":[{"type":"text","text":"The business type of the Connect account."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"navigatorTitle":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/Equatable-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/Equatable-Implementations","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/equatable-implementations","abstract":[],"title":"Equatable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPConnectAccountBusinessType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/navigatorTitle","op":"replace","value":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}