{"metadata":{"title":"STPConnectAccountBusinessType.company","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountBusinessTypeCompany"}],"roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"company"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPConnectAccountBusinessType@STPConnectAccountBusinessTypeCompany","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/company"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/company"]}],"abstract":[{"type":"text","text":"This Connect account represents a company."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/company"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"company","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/company":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/company","title":"STPConnectAccountBusinessType.company","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"company","kind":"identifier"}],"abstract":[{"type":"text","text":"This Connect account represents a company."}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/company","navigatorTitle":[{"text":"STPConnectAccountBusinessTypeCompany","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType":{"type":"topic","title":"STPConnectAccountBusinessType","abstract":[{"type":"text","text":"The business type of the Connect account."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","navigatorTitle":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPConnectAccountBusinessTypeCompany","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountBusinessTypeCompany"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPConnectAccountBusinessTypeCompany","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPConnectAccountBusinessTypeCompany","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1company\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountBusinessTypeCompany"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1company\/fragments"},{"op":"replace","value":"STPConnectAccountBusinessType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/fragments"},{"op":"replace","value":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/navigatorTitle"}]}]}