{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/customstringconvertible-implementations"]}],"metadata":{"title":"CustomStringConvertible Implementations","roleHeading":"API Collection","modules":[{"name":"StripePayments"}],"role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/description"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"kind":"article","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType":{"url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype","type":"topic","title":"STPConnectAccountBusinessType","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"role":"symbol","abstract":[{"text":"The business type of the Connect account.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/description","kind":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/description","title":"description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPConnectAccountBusinessType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/fragments","value":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}]},{"value":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}