{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"individual"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Case","title":"STPConnectAccountBusinessType.individual","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPConnectAccountBusinessType@STPConnectAccountBusinessTypeIndividual","navigatorTitle":[{"text":"STPConnectAccountBusinessTypeIndividual","kind":"identifier"}],"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"individual","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/individual","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType"]]},"abstract":[{"text":"This Connect account represents an individual.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/individual"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/individual"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype","title":"STPConnectAccountBusinessType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"role":"symbol","abstract":[{"type":"text","text":"The business type of the Connect account."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPConnectAccountBusinessType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/individual":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/individual","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/individual","title":"STPConnectAccountBusinessType.individual","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountBusinessTypeIndividual"}],"role":"symbol","abstract":[{"text":"This Connect account represents an individual.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"individual"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPConnectAccountBusinessTypeIndividual"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPConnectAccountBusinessTypeIndividual","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPConnectAccountBusinessTypeIndividual","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/title","value":"STPConnectAccountBusinessType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/navigatorTitle","op":"replace","value":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1individual\/title","value":"STPConnectAccountBusinessTypeIndividual","op":"replace"},{"op":"replace","value":[{"text":"STPConnectAccountBusinessTypeIndividual","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1individual\/fragments"}]}]}