{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams\/init()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","externalID":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams(im)init","modules":[{"name":"StripePayments"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"abstract":[{"text":"Initializes an empty STPMandateCustomerAcceptanceParams.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/init()"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams":{"navigatorTitle":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}],"abstract":[{"text":"An object that contains details about the customer acceptance of the Mandate. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams","title":"STPMandateCustomerAcceptanceParams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams/init()":{"kind":"symbol","abstract":[{"type":"text","text":"Initializes an empty STPMandateCustomerAcceptanceParams."}],"role":"symbol","title":"init()","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/init()","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPMandateCustomerAcceptanceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/navigatorTitle"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams~1init()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams~1init()\/fragments"}]}]}