{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams\/onlineParams","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams(py)onlineParams","title":"onlineParams","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onlineParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams","text":"STPMandateOnlineParams"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"onlineParams","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/onlineparams"]},{"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/onlineparams"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onlineParams","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","text":"STPMandateOnlineParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"type == STPMandateCustomerAcceptanceTypeOnline"},{"text":", this value must be non-nil.","type":"text"}]}],"name":"Note","type":"aside","style":"note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams"]]},"abstract":[{"type":"text","text":"If this is a Mandate accepted online, this object contains details about the online acceptance."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams":{"abstract":[{"text":"Contains details about a Mandate accepted online. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance-online","type":"text"}],"title":"STPMandateOnlineParams","navigatorTitle":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","url":"\/documentation\/stripepayments\/stpmandateonlineparams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPMandateOnlineParams","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams/onlineParams":{"abstract":[{"type":"text","text":"If this is a Mandate accepted online, this object contains details about the online acceptance."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"onlineParams","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams","text":"STPMandateOnlineParams"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams\/onlineParams","type":"topic","title":"onlineParams","role":"symbol","navigatorTitle":[{"text":"onlineParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/onlineparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams":{"abstract":[{"text":"An object that contains details about the customer acceptance of the Mandate. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"navigatorTitle":[{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}],"kind":"symbol","title":"STPMandateCustomerAcceptanceParams","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"onlineParams","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"onlineParams"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPMandateOnlineParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"onlineParams"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/title","value":"STPMandateOnlineParams","op":"replace"},{"value":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/fragments"},{"value":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams~1onlineParams\/title","value":"onlineParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams~1onlineParams\/fragments","value":[{"kind":"identifier","text":"onlineParams"}]},{"op":"replace","value":"STPMandateCustomerAcceptanceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/fragments","value":[{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/navigatorTitle","value":[{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}