{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams\/rootObjectName()"},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"symbolKind":"method","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams(cm)rootObjectName","roleHeading":"Type Method","title":"rootObjectName()"},"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/rootobjectname()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/rootobjectname()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams":{"navigatorTitle":[{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An object that contains details about the customer acceptance of the Mandate. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance"}],"title":"STPMandateCustomerAcceptanceParams","role":"symbol","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams/rootObjectName()":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams\/rootobjectname()","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"title":"rootObjectName()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams\/rootObjectName()","abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"type":"text","text":" below."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"rootObjectName","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/title","value":"STPMandateCustomerAcceptanceParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/navigatorTitle","op":"replace","value":[{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams~1rootObjectName()\/title","op":"replace","value":"rootObjectName"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams~1rootObjectName()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}]}]}]}