{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"]]},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"CustomStringConvertible Implementations","modules":[{"name":"StripePayments"}]},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/description"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/customstringconvertible-implementations"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle":{"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}],"abstract":[{"text":"An enumeration of the case transformations that can be applied to the button’s title","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle","title":"STPThreeDSButtonTitleStyle","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/description","title":"description","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/description","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/title","value":"STPThreeDSButtonTitleStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/fragments","value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/navigatorTitle","value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}]}]}]}