{"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/default"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/default","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","title":"STPThreeDSButtonTitleStyle.default","role":"symbol","navigatorTitle":[{"text":"STPThreeDSButtonTitleStyleDefault","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle@STPThreeDSButtonTitleStyleDefault","modules":[{"name":"StripePayments"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}]},"abstract":[{"text":"Default style, doesn’t modify the title","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle":{"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}],"role":"symbol","title":"STPThreeDSButtonTitleStyle","abstract":[{"text":"An enumeration of the case transformations that can be applied to the button’s title","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/default":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/default","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"}],"title":"STPThreeDSButtonTitleStyle.default","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/default","abstract":[{"type":"text","text":"Default style, doesn’t modify the title"}],"navigatorTitle":[{"text":"STPThreeDSButtonTitleStyleDefault","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPThreeDSButtonTitleStyleDefault","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleDefault"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleDefault"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPThreeDSButtonTitleStyle","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/title"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/fragments"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/navigatorTitle"},{"value":"STPThreeDSButtonTitleStyleDefault","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1default\/title"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleDefault"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1default\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}