{"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/!=(_:_:)"],"generated":true}],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/equatable-implementations"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"]]},"metadata":{"modules":[{"name":"StripePayments"}],"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle":{"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle","abstract":[{"type":"text","text":"An enumeration of the case transformations that can be applied to the button’s title"}],"navigatorTitle":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"type":"topic","title":"STPThreeDSButtonTitleStyle"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/!=(_:_:)":{"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/!=(_:_:)","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","title":"!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/title","op":"replace","value":"STPThreeDSButtonTitleStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/fragments","op":"replace","value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}]}]}]}