{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lowercase","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/lowercase","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/lowercase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/lowercase"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Applies localizedLowercaseString to the title"}],"metadata":{"title":"STPThreeDSButtonTitleStyle.lowercase","externalID":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle@STPThreeDSButtonTitleStyleLowercase","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lowercase","kind":"identifier"}],"navigatorTitle":[{"text":"STPThreeDSButtonTitleStyleLowercase","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle":{"abstract":[{"text":"An enumeration of the case transformations that can be applied to the button’s title","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle","kind":"symbol","navigatorTitle":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"title":"STPThreeDSButtonTitleStyle","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/lowercase":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"lowercase","kind":"identifier"}],"title":"STPThreeDSButtonTitleStyle.lowercase","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/lowercase","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleLowercase"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/lowercase","abstract":[{"text":"Applies localizedLowercaseString to the title","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPThreeDSButtonTitleStyleLowercase","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPThreeDSButtonTitleStyleLowercase","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleLowercase"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/title","value":"STPThreeDSButtonTitleStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/fragments","op":"replace","value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}],"op":"replace"},{"op":"replace","value":"STPThreeDSButtonTitleStyleLowercase","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1lowercase\/title"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleLowercase"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1lowercase\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}