{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/sentencecapitalized"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/sentencecapitalized"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Applies localizedCapitalizedString to the title","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sentenceCapitalized","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/sentenceCapitalized","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleSentenceCapitalized"}],"externalID":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle@STPThreeDSButtonTitleStyleSentenceCapitalized","title":"STPThreeDSButtonTitleStyle.sentenceCapitalized","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sentenceCapitalized"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle":{"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle","title":"STPThreeDSButtonTitleStyle","kind":"symbol","abstract":[{"text":"An enumeration of the case transformations that can be applied to the button’s title","type":"text"}],"navigatorTitle":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/sentenceCapitalized":{"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/sentencecapitalized","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleSentenceCapitalized"}],"kind":"symbol","title":"STPThreeDSButtonTitleStyle.sentenceCapitalized","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/sentenceCapitalized","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Applies localizedCapitalizedString to the title"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sentenceCapitalized"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPThreeDSButtonTitleStyleSentenceCapitalized"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleSentenceCapitalized"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPThreeDSButtonTitleStyleSentenceCapitalized","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/title","op":"replace","value":"STPThreeDSButtonTitleStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/fragments","value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}]},{"value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1sentenceCapitalized\/title","value":"STPThreeDSButtonTitleStyleSentenceCapitalized","op":"replace"},{"op":"replace","value":[{"text":"STPThreeDSButtonTitleStyleSentenceCapitalized","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1sentenceCapitalized\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}