{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"uppercase","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle@STPThreeDSButtonTitleStyleUppercase","symbolKind":"case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleUppercase"}],"roleHeading":"Case","title":"STPThreeDSButtonTitleStyle.uppercase"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/uppercase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/uppercase"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Applies localizedUppercaseString to the title","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uppercase","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/uppercase"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/uppercase":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"uppercase","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/uppercase","navigatorTitle":[{"text":"STPThreeDSButtonTitleStyleUppercase","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/uppercase","abstract":[{"type":"text","text":"Applies localizedUppercaseString to the title"}],"title":"STPThreeDSButtonTitleStyle.uppercase"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle":{"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle","abstract":[{"text":"An enumeration of the case transformations that can be applied to the button’s title","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}],"title":"STPThreeDSButtonTitleStyle"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPThreeDSButtonTitleStyleUppercase"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPThreeDSButtonTitleStyleUppercase","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleUppercase"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1uppercase\/title","op":"replace","value":"STPThreeDSButtonTitleStyleUppercase"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleUppercase"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1uppercase\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/title","value":"STPThreeDSButtonTitleStyle"},{"value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
