{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"paymentOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"text":"?)","kind":"text"}],"title":"init(paymentOption:)","roleHeading":"Initializer","modules":[{"name":"Stripe"}],"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithPaymentOption:","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentResult(im)initWithPaymentOption:"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/init(paymentOption:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentresult\/init(paymentoption:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentresult\/init(paymentoption:)"]}],"abstract":[{"type":"text","text":"Initializes the payment result with a given payment option. This is invoked by "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" internally; you shouldn’t have to call it directly."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"paymentOption","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption":{"kind":"symbol","abstract":[{"type":"text","text":"This protocol represents a payment method that a user can select and use to"},{"type":"text","text":" "},{"type":"text","text":"pay."},{"type":"text","text":" "},{"type":"text","text":"The classes that conform to it and are supported by the UI:"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOption","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","url":"\/documentation\/stripe\/stppaymentoption","role":"symbol","title":"STPPaymentOption","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOption"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult/init(paymentOption:)":{"navigatorTitle":[{"text":"initWithPaymentOption:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paymentOption","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","text":"STPPaymentOption"},{"text":"?)","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentresult\/init(paymentoption:)","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/init(paymentOption:)","abstract":[{"type":"text","text":"Initializes the payment result with a given payment option. This is invoked by "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" internally; you shouldn’t have to call it directly."}],"title":"init(paymentOption:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult":{"abstract":[{"type":"text","text":"When you’re using "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" to request your user’s payment details, this is the object that will be returned to your application when they’ve successfully made a payment.","type":"text"},{"text":" ","type":"text"},{"text":"See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#submit-payment-intents","type":"text"}],"role":"symbol","url":"\/documentation\/stripe\/stppaymentresult","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentResult"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentResult"}],"title":"STPPaymentResult","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithPaymentOption:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentOption:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPaymentOption:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<STPPaymentOption>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPPaymentOption"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"paymentOption"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/title","value":"STPPaymentOption"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentOption"}]},{"op":"replace","value":"initWithPaymentOption:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1init(paymentOption:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPaymentOption:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1init(paymentOption:)\/fragments"},{"op":"replace","value":"STPPaymentResult","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/fragments","value":[{"text":"STPPaymentResult","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
