{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOption"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","text":"STPPaymentOption","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentOption"},"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPPaymentResult(py)paymentOption","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentOption"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"text":"?","kind":"text"}],"title":"paymentOption","modules":[{"name":"Stripe"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentresult\/paymentoption"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentresult\/paymentoption"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult"]]},"abstract":[{"text":"The STPPaymentOption that was used to initialize this STPPaymentResult, either an STPPaymentMethod or an STPPaymentMethodParams.","type":"text"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentResult"}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentresult","title":"STPPaymentResult","role":"symbol","abstract":[{"type":"text","text":"When you’re using "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" to request your user’s payment details, this is the object that will be returned to your application when they’ve successfully made a payment."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#submit-payment-intents"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult/paymentOption":{"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentOption","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentOption","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOption"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"paymentOption","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The STPPaymentOption that was used to initialize this STPPaymentResult, either an STPPaymentMethod or an STPPaymentMethodParams."}],"url":"\/documentation\/stripe\/stppaymentresult\/paymentoption","title":"paymentOption","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentOption"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption":{"abstract":[{"type":"text","text":"This protocol represents a payment method that a user can select and use to"},{"type":"text","text":" "},{"type":"text","text":"pay."},{"text":" ","type":"text"},{"text":"The classes that conform to it and are supported by the UI:","type":"text"}],"url":"\/documentation\/stripe\/stppaymentoption","role":"symbol","kind":"symbol","type":"topic","title":"STPPaymentOption","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOption"}],"navigatorTitle":[{"text":"STPPaymentOption","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"paymentOption","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"paymentOption","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"id<STPPaymentOption>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPPaymentOption"},{"text":" * ","kind":"text"},{"text":"paymentOption","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/title","value":"STPPaymentResult","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentResult"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentOption\/title","value":"paymentOption","op":"replace"},{"value":[{"kind":"identifier","text":"paymentOption"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentOption\/fragments"},{"value":"STPPaymentOption","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/fragments","value":[{"text":"STPPaymentOption","kind":"identifier"}]}]}]}
