{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentresult\/paymentmethodparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentresult\/paymentmethodparams"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult"]]},"abstract":[{"type":"text","text":"The parameters for a payment method that the user has selected. This is"},{"type":"text","text":" "},{"type":"text","text":"populated for non-reusable payment methods, such as FPX and iDEAL. - seealso: STPPaymentMethodParams.h"},{"text":" ","type":"text"},{"text":"If paymentMethodParams is nil, paymentMethod will be populated instead.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodParams"},{"text":"? { get }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"title":"paymentMethodParams","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentResult(py)paymentMethodParams","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodParams"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paymentMethodParams"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentMethodParams","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult":{"abstract":[{"type":"text","text":"When you’re using "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" to request your user’s payment details, this is the object that will be returned to your application when they’ve successfully made a payment.","type":"text"},{"text":" ","type":"text"},{"text":"See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#submit-payment-intents","type":"text"}],"role":"symbol","url":"\/documentation\/stripe\/stppaymentresult","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentResult"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentResult"}],"title":"STPPaymentResult","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult/paymentMethodParams":{"url":"\/documentation\/stripe\/stppaymentresult\/paymentmethodparams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"paymentMethodParams"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult\/paymentMethodParams","role":"symbol","kind":"symbol","title":"paymentMethodParams","abstract":[{"type":"text","text":"The parameters for a payment method that the user has selected. This is"},{"text":" ","type":"text"},{"type":"text","text":"populated for non-reusable payment methods, such as FPX and iDEAL. - seealso: STPPaymentMethodParams.h"},{"type":"text","text":" "},{"type":"text","text":"If paymentMethodParams is nil, paymentMethod will be populated instead."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethodParams":{"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodParams"}],"title":"STPPaymentMethodParams","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentmethodparams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"paymentMethodParams","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"paymentMethodParams"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodParams"},{"text":" * ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/title","op":"replace","value":"STPPaymentResult"},{"op":"replace","value":[{"text":"STPPaymentResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentMethodParams\/title","value":"paymentMethodParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult~1paymentMethodParams\/fragments","value":[{"text":"paymentMethodParams","kind":"identifier"}]}]}]}
