{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/failed"},"abstract":[{"text":"The redirect has failed.","type":"text"}],"metadata":{"modules":[{"name":"StripePayments"}],"title":"STPSourceRedirectStatus.failed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"externalID":"c:@M@StripePayments@E@STPSourceRedirectStatus@STPSourceRedirectStatusFailed","navigatorTitle":[{"text":"STPSourceRedirectStatusFailed","kind":"identifier"}],"role":"symbol","roleHeading":"Case","symbolKind":"case"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/failed"]},{"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus":{"role":"symbol","title":"STPSourceRedirectStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceRedirectStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Redirect status types for a Source."}],"navigatorTitle":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","type":"topic","url":"\/documentation\/stripepayments\/stpsourceredirectstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/failed":{"url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/failed","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/failed","role":"symbol","title":"STPSourceRedirectStatus.failed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The redirect has failed."}],"kind":"symbol","navigatorTitle":[{"text":"STPSourceRedirectStatusFailed","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"STPSourceRedirectStatusFailed","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPSourceRedirectStatusFailed","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPSourceRedirectStatusFailed"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/title","value":"STPSourceRedirectStatus","op":"replace"},{"op":"replace","value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/navigatorTitle","value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1failed\/title","op":"replace","value":"STPSourceRedirectStatusFailed"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1failed\/fragments","op":"replace","value":[{"text":"STPSourceRedirectStatusFailed","kind":"identifier"}]}]}]}