{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/notRequired"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/notrequired"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/notrequired"]}],"abstract":[{"type":"text","text":"The redirect should not be used."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notRequired","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notRequired","kind":"identifier"}],"symbolKind":"case","title":"STPSourceRedirectStatus.notRequired","roleHeading":"Case","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatusNotRequired"}],"externalID":"c:@M@StripePayments@E@STPSourceRedirectStatus@STPSourceRedirectStatusNotRequired"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus":{"abstract":[{"type":"text","text":"Redirect status types for a Source."}],"title":"STPSourceRedirectStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceRedirectStatus","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceredirectstatus","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/notRequired":{"type":"topic","abstract":[{"type":"text","text":"The redirect should not be used."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/notRequired","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notRequired"}],"title":"STPSourceRedirectStatus.notRequired","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/notrequired","role":"symbol","navigatorTitle":[{"text":"STPSourceRedirectStatusNotRequired","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceRedirectStatusNotRequired"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceRedirectStatusNotRequired","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceRedirectStatusNotRequired"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/title","value":"STPSourceRedirectStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/fragments","value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}]},{"value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1notRequired\/title","op":"replace","value":"STPSourceRedirectStatusNotRequired"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1notRequired\/fragments","op":"replace","value":[{"text":"STPSourceRedirectStatusNotRequired","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}