{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/pending"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus"]]},"kind":"symbol","abstract":[{"text":"The redirect is pending.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/pending"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/pending"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"STPSourceRedirectStatus.pending","externalID":"c:@M@StripePayments@E@STPSourceRedirectStatus@STPSourceRedirectStatusPending","navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatusPending"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceredirectstatus","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","abstract":[{"text":"Redirect status types for a Source.","type":"text"}],"title":"STPSourceRedirectStatus","navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceRedirectStatus"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/pending":{"navigatorTitle":[{"text":"STPSourceRedirectStatusPending","kind":"identifier"}],"title":"STPSourceRedirectStatus.pending","abstract":[{"text":"The redirect is pending.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/pending","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/pending","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"STPSourceRedirectStatusPending","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"STPSourceRedirectStatusPending","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceRedirectStatusPending"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"STPSourceRedirectStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/fragments","value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1pending\/title","value":"STPSourceRedirectStatusPending","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1pending\/fragments","value":[{"text":"STPSourceRedirectStatusPending","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}