{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/succeeded"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/succeeded"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/succeeded"]}],"metadata":{"title":"STPSourceRedirectStatus.succeeded","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatusSucceeded"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSourceRedirectStatus@STPSourceRedirectStatusSucceeded","roleHeading":"Case","modules":[{"name":"StripePayments"}]},"abstract":[{"type":"text","text":"The redirect has succeeded."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"succeeded"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus"]]},"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus":{"url":"\/documentation\/stripepayments\/stpsourceredirectstatus","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceRedirectStatus"}],"type":"topic","title":"STPSourceRedirectStatus","abstract":[{"type":"text","text":"Redirect status types for a Source."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/succeeded":{"title":"STPSourceRedirectStatus.succeeded","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/succeeded","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/succeeded","navigatorTitle":[{"text":"STPSourceRedirectStatusSucceeded","kind":"identifier"}],"type":"topic","abstract":[{"text":"The redirect has succeeded.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceRedirectStatusSucceeded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceRedirectStatusSucceeded"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceRedirectStatusSucceeded"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/title","value":"STPSourceRedirectStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceRedirectStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceRedirectStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1succeeded\/title","value":"STPSourceRedirectStatusSucceeded","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1succeeded\/fragments","value":[{"kind":"identifier","text":"STPSourceRedirectStatusSucceeded"}],"op":"replace"}]}]}