{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"title":"STPSourceRedirectStatus.unknown","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSourceRedirectStatus@STPSourceRedirectStatusUnknown","symbolKind":"case","role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceRedirectStatusUnknown","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/unknown"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/unknown"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The state of the redirect is unknown."}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/unknown":{"url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/unknown","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"The state of the redirect is unknown."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatusUnknown"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/unknown","role":"symbol","title":"STPSourceRedirectStatus.unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","title":"STPSourceRedirectStatus","type":"topic","navigatorTitle":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceredirectstatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceRedirectStatus"}],"abstract":[{"text":"Redirect status types for a Source.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceRedirectStatusUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"STPSourceRedirectStatusUnknown","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPSourceRedirectStatusUnknown","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPSourceRedirectStatusUnknown","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1unknown\/title"},{"value":[{"kind":"identifier","text":"STPSourceRedirectStatusUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1unknown\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/title","op":"replace","value":"STPSourceRedirectStatus"},{"op":"replace","value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceRedirectStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}