{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization","text":"STPThreeDSLabelCustomization"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"The default settings."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedslabelcustomization\/defaultsettings()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedslabelcustomization\/defaultsettings()"]}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization\/defaultSettings()","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization(cm)defaultSettings","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"defaultSettings"}],"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultSettings"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization","kind":"typeIdentifier","text":"STPThreeDSLabelCustomization"}],"title":"defaultSettings()","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSLabelCustomization":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization","url":"\/documentation\/stripepayments\/stpthreedslabelcustomization","type":"topic","abstract":[{"text":"A customization object to use to configure the UI of a text label.","type":"text"}],"navigatorTitle":[{"text":"STPThreeDSLabelCustomization","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"STPThreeDSLabelCustomization","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSLabelCustomization"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSLabelCustomization/defaultSettings()":{"role":"symbol","navigatorTitle":[{"text":"defaultSettings","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedslabelcustomization\/defaultsettings()","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization","kind":"typeIdentifier","text":"STPThreeDSLabelCustomization"}],"abstract":[{"type":"text","text":"The default settings."}],"title":"defaultSettings()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization\/defaultSettings()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"defaultSettings","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"defaultSettings"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization","text":"STPThreeDSLabelCustomization"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"defaultSettings"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"STPThreeDSLabelCustomization","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/title"},{"value":[{"text":"STPThreeDSLabelCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPThreeDSLabelCustomization"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/navigatorTitle"},{"op":"replace","value":"defaultSettings","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization~1defaultSettings()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization~1defaultSettings()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"defaultSettings","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}