{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedslabelcustomization\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization(im)init","role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization\/init","interfaceLanguage":"occ"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSLabelCustomization/init":{"url":"\/documentation\/stripepayments\/stpthreedslabelcustomization\/init","role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization\/init","abstract":[],"kind":"symbol","title":"init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSLabelCustomization":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSLabelCustomization"}],"type":"topic","abstract":[{"text":"A customization object to use to configure the UI of a text label.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedslabelcustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSLabelCustomization"}],"kind":"symbol","role":"symbol","title":"STPThreeDSLabelCustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/title","value":"STPThreeDSLabelCustomization","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSLabelCustomization"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/navigatorTitle","value":[{"text":"STPThreeDSLabelCustomization","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}