{"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails\/decodedobject(fromapiresponse:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":" "},{"text":"response","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"response","content":[{"inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"type":"text","text":" "},{"text":"could not be decoded (i.e. if one of its ","type":"text"},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"title":"decodedObject(fromAPIResponse:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails(cm)decodedObjectFromAPIResponse:"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails"]]},"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/decodedObject(fromAPIResponse:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/decodedObject(fromAPIResponse:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/decodedobject(fromapiresponse:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"kind":"symbol","title":"decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceSEPADebitDetails"}],"url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails","title":"STPSourceSEPADebitDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","abstract":[{"type":"text","text":"This class provides typed access to the contents of an STPSource "},{"code":"details","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"dictionary for SEPA Debit sources."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceSEPADebitDetails","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"},{"kind":"text","text":"("},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"response","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1decodedObject(fromAPIResponse:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1decodedObject(fromAPIResponse:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"value":"STPSourceSEPADebitDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/fragments","value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/navigatorTitle","op":"replace","value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}]}]}]}