{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The account’s fingerprint.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails\/fingerprint"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails\/fingerprint"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/fingerprint"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingerprint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"fingerprint","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails(py)fingerprint","navigatorTitle":[{"kind":"identifier","text":"fingerprint"}],"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingerprint"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails":{"title":"STPSourceSEPADebitDetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceSEPADebitDetails"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This class provides typed access to the contents of an STPSource "},{"type":"codeVoice","code":"details"},{"type":"text","text":" "},{"text":"dictionary for SEPA Debit sources.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/fingerprint":{"type":"topic","title":"fingerprint","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fingerprint"}],"url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/fingerprint","abstract":[{"text":"The account’s fingerprint.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/fingerprint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fingerprint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"fingerprint"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"fingerprint"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"fingerprint","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPSourceSEPADebitDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/fragments","op":"replace","value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/navigatorTitle","value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1fingerprint\/title","value":"fingerprint","op":"replace"},{"value":[{"text":"fingerprint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1fingerprint\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}