{"metadata":{"modules":[{"name":"StripePayments"}],"title":"last4","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"last4"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails(py)last4","navigatorTitle":[{"text":"last4","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails\/last4"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails\/last4"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"The last 4 digits of the account number.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/last4","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails":{"title":"STPSourceSEPADebitDetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceSEPADebitDetails"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This class provides typed access to the contents of an STPSource "},{"type":"codeVoice","code":"details"},{"type":"text","text":" "},{"text":"dictionary for SEPA Debit sources.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/last4":{"title":"last4","type":"topic","navigatorTitle":[{"kind":"identifier","text":"last4"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/last4","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/last4","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"The last 4 digits of the account number."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"last4","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"last4"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"last4"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/title","value":"STPSourceSEPADebitDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/fragments","value":[{"kind":"identifier","text":"STPSourceSEPADebitDetails"}]},{"value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1last4\/title","value":"last4","op":"replace"},{"value":[{"text":"last4","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1last4\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}