{"abstract":[{"text":"The reference of the mandate accepted by your customer.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails\/mandatereference"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails\/mandatereference"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/mandateReference"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"mandateReference","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"mandateReference"}],"title":"mandateReference","role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails(py)mandateReference","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mandateReference","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","role":"symbol","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails","abstract":[{"text":"This class provides typed access to the contents of an STPSource ","type":"text"},{"code":"details","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"dictionary for SEPA Debit sources."}],"type":"topic","title":"STPSourceSEPADebitDetails","kind":"symbol","navigatorTitle":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/mandateReference":{"url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/mandatereference","abstract":[{"text":"The reference of the mandate accepted by your customer.","type":"text"}],"title":"mandateReference","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/mandateReference","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mandateReference"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mandateReference","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"mandateReference"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"mandateReference"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"mandateReference","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/title","value":"STPSourceSEPADebitDetails","op":"replace"},{"op":"replace","value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceSEPADebitDetails"}],"op":"replace"},{"value":"mandateReference","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1mandateReference\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1mandateReference\/fragments","op":"replace","value":[{"text":"mandateReference","kind":"identifier"}]}]}]}