{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"},{"kind":"text","text":") "},{"kind":"identifier","text":"brandFromString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"string"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/brandfromstring:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/brandFromString:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"brandFromString:"}],"title":"brandFromString:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard(cm)brandFromString:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"brandFromString:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"role":"symbol","title":"STPCardBrand","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardBrand"}],"abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"url":"\/documentation\/stripepayments\/stpcardbrand"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"role":"symbol","title":"STPPaymentMethodCard","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCard"}],"abstract":[{"type":"text","text":"Contains details about a user’s credit card."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCard"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcard"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard/brandFromString:":{"role":"symbol","title":"brandFromString:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"brandFromString:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/brandFromString:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"brandFromString:"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcard\/brandfromstring:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","value":"STPCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"kind":"identifier","text":"STPCardBrand"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title","value":"STPPaymentMethodCard"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCard"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
