{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/cardArt","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodCardArt","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardArt","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardArt","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"cardArt","kind":"identifier"},{"text":";","kind":"text"}]}]}],"metadata":{"fragments":[{"text":"cardArt","kind":"identifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"cardArt"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard(py)cardArt","title":"cardArt"},"abstract":[{"text":"Card art, if available","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/cardart"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"type":"topic","abstract":[{"type":"text","text":"Contains details about a user’s credit card."}],"title":"STPPaymentMethodCard","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCard","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","url":"\/documentation\/stripepayments\/stppaymentmethodcard","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardArt":{"type":"topic","title":"STPPaymentMethodCardArt","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardArt","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodcardart","fragments":[{"text":"STPPaymentMethodCardArt","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard/cardArt":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/cardArt","kind":"symbol","role":"symbol","title":"cardArt","fragments":[{"text":"cardArt","kind":"identifier"}],"abstract":[{"type":"text","text":"Card art, if available"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcard\/cardart"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title","value":"STPPaymentMethodCard"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCard"}]}]}]}