{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard(cm)decodedObjectFromAPIResponse:","title":"decodedObject(fromAPIResponse:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"StripePayments"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"text":"fromAPIResponse","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"type":"text","text":" "},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"code":"requiredFields","type":"codeVoice"},{"type":"text","text":" is nil)."}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/decodedobject(fromapiresponse:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard/decodedObject(fromAPIResponse:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/decodedObject(fromAPIResponse:)","title":"decodedObject(fromAPIResponse:)","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcard\/decodedobject(fromapiresponse:)","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"url":"\/documentation\/stripepayments\/stppaymentmethodcard","title":"STPPaymentMethodCard","abstract":[{"type":"text","text":"Contains details about a user’s credit card."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCard"}],"navigatorTitle":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"response"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1decodedObject(fromAPIResponse:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title","op":"replace","value":"STPPaymentMethodCard"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCard"}]},{"value":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}
