{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/displayBrand"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard"]]},"metadata":{"modules":[{"name":"StripePayments"}],"title":"displayBrand","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard(py)displayBrand","fragments":[{"text":"displayBrand","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"displayBrand"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"displayBrand"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/displaybrand"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Contains information about the card’s display brand"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard/displayBrand":{"url":"\/documentation\/stripepayments\/stppaymentmethodcard\/displaybrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/displayBrand","title":"displayBrand","kind":"symbol","role":"symbol","fragments":[{"text":"displayBrand","kind":"identifier"}],"abstract":[{"text":"Contains information about the card’s display brand","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"abstract":[{"text":"Contains details about a user’s credit card.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcard","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCard","kind":"identifier"}],"title":"STPPaymentMethodCard","type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCard","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title","op":"replace","value":"STPPaymentMethodCard"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCard"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodCard","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}