{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardNetworks","text":"STPPaymentMethodCardNetworks","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardNetworks"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/networks"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"networks"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard(py)networks","symbolKind":"property","roleHeading":"Instance Property","title":"networks","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardNetworks","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardNetworks"},{"kind":"text","text":"?"}]},"abstract":[{"type":"text","text":"Contains information about card networks that can be used to process the payment."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/networks"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/networks"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard/networks":{"navigatorTitle":[{"kind":"identifier","text":"networks"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcard\/networks","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"networks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardNetworks","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardNetworks"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"text":"Contains information about card networks that can be used to process the payment.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/networks","role":"symbol","type":"topic","title":"networks"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardNetworks":{"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardnetworks","abstract":[{"type":"codeVoice","code":"STPPaymentMethodCardNetworks"},{"type":"text","text":" contains information about card networks that can be used to process a payment."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardNetworks"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardNetworks"}],"title":"STPPaymentMethodCardNetworks","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardNetworks","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcard","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","title":"STPPaymentMethodCard","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCard","kind":"identifier"}],"abstract":[{"type":"text","text":"Contains details about a user’s credit card."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"networks","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"networks"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardNetworks","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardNetworks","text":"STPPaymentMethodCardNetworks"},{"kind":"text","text":" * "},{"kind":"identifier","text":"networks"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"networks","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1networks\/title","op":"replace"},{"value":[{"text":"networks","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1networks\/fragments","op":"replace"},{"value":"STPPaymentMethodCardNetworks","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardNetworks\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodCardNetworks","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardNetworks\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardNetworks"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardNetworks\/navigatorTitle","op":"replace"},{"value":"STPPaymentMethodCard","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/navigatorTitle","op":"replace"}]}]}