{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/threeDSecureUsage","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard(py)threeDSecureUsage","role":"symbol","symbolKind":"property","title":"threeDSecureUsage","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threeDSecureUsage"},{"kind":"text","text":": "},{"text":"STPPaymentMethodThreeDSecureUsage","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodThreeDSecureUsage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"threeDSecureUsage","kind":"identifier"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/threedsecureusage"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/threedsecureusage"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"threeDSecureUsage","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodThreeDSecureUsage","text":"STPPaymentMethodThreeDSecureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage","kind":"typeIdentifier"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Contains details on how this Card maybe be used for 3D Secure authentication."}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard/threeDSecureUsage":{"kind":"symbol","navigatorTitle":[{"text":"threeDSecureUsage","kind":"identifier"}],"abstract":[{"type":"text","text":"Contains details on how this Card maybe be used for 3D Secure authentication."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/threeDSecureUsage","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threeDSecureUsage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodThreeDSecureUsage","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodThreeDSecureUsage"},{"text":"?","kind":"text"}],"title":"threeDSecureUsage","url":"\/documentation\/stripepayments\/stppaymentmethodcard\/threedsecureusage","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"navigatorTitle":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCard","kind":"identifier"}],"abstract":[{"type":"text","text":"Contains details about a user’s credit card."}],"role":"symbol","type":"topic","title":"STPPaymentMethodCard"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodThreeDSecureUsage":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage","type":"topic","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage","title":"STPPaymentMethodThreeDSecureUsage","abstract":[{"type":"text","text":"Contains details on how an "},{"code":"STPPaymentMethodCard","type":"codeVoice"},{"type":"text","text":" maybe be used for 3D Secure authentication."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"threeDSecureUsage","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"threeDSecureUsage"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodThreeDSecureUsage","text":"STPPaymentMethodThreeDSecureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"threeDSecureUsage"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"threeDSecureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1threeDSecureUsage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"threeDSecureUsage"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1threeDSecureUsage\/fragments"},{"value":"STPPaymentMethodCard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments","value":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/navigatorTitle","value":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/title","value":"STPPaymentMethodThreeDSecureUsage"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodThreeDSecureUsage"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodThreeDSecureUsage"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/navigatorTitle"}]}]}