{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/wallet"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/wallet"]}],"sections":[],"abstract":[{"type":"text","text":"If this Card is part of a Card Wallet, this contains the details of the Card Wallet."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/wallet","interfaceLanguage":"swift"},"metadata":{"title":"wallet","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wallet"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardWallet","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard(py)wallet","navigatorTitle":[{"text":"wallet","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"wallet","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet","text":"STPPaymentMethodCardWallet","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet","kind":"typeIdentifier"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard/wallet":{"url":"\/documentation\/stripepayments\/stppaymentmethodcard\/wallet","title":"wallet","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"wallet","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet","text":"STPPaymentMethodCardWallet"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/wallet","role":"symbol","abstract":[{"type":"text","text":"If this Card is part of a Card Wallet, this contains the details of the Card Wallet."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"wallet"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"url":"\/documentation\/stripepayments\/stppaymentmethodcard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","abstract":[{"text":"Contains details about a user’s credit card.","type":"text"}],"title":"STPPaymentMethodCard","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCard"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCard"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet","abstract":[{"type":"text","text":"A Card Wallet."}],"type":"topic","title":"STPPaymentMethodCardWallet","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"wallet"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"wallet","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet","text":"STPPaymentMethodCardWallet","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"wallet"},{"kind":"text","text":";"}]}]}},{"value":"wallet","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1wallet\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1wallet\/fragments","value":[{"kind":"identifier","text":"wallet"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title","op":"replace","value":"STPPaymentMethodCard"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCard"}]},{"value":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/navigatorTitle"},{"value":"STPPaymentMethodCardWallet","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]},{"op":"replace","value":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}