{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodsatispay\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodsatispay\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSatispay"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSatispay\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodSatispay(cm)decodedObjectFromAPIResponse:","role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"title":"decodedObject(fromAPIResponse:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"text":"fromAPIResponse","kind":"externalParam"},{"kind":"text","text":" "},{"text":"response","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSatispay":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodSatispay"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodSatispay","kind":"identifier"}],"title":"STPPaymentMethodSatispay","abstract":[{"type":"text","text":"The Satispay Payment Method."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSatispay","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodsatispay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSatispay/decodedObject(fromAPIResponse:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSatispay\/decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stppaymentmethodsatispay\/decodedobject(fromapiresponse:)","kind":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic","title":"decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"response"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"STPPaymentMethodSatispay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSatispay\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSatispay\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodSatispay"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodSatispay"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSatispay\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSatispay~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSatispay~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]}]}]}