{"abstract":[{"type":"text","text":"The set of countries supported when entering an address. This property accepts"},{"text":" ","type":"text"},{"type":"text","text":"a set of ISO 2-character country codes."},{"text":" ","type":"text"},{"type":"text","text":"The default value is all known countries. Setting this property will limit"},{"text":" ","type":"text"},{"text":"the available countries to your selected set.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"availableCountries","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/availablecountries"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/availablecountries"]}],"sections":[],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"availableCountries","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"availableCountries","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(py)availableCountries","modules":[{"name":"Stripe"}],"title":"availableCountries"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/availableCountries","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"type":"topic","title":"STPPaymentConfiguration","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"text":" ","type":"text"},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"text":"will not change from payment to payment and thus is reusable, while the context","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentconfiguration","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/availableCountries":{"kind":"symbol","abstract":[{"type":"text","text":"The set of countries supported when entering an address. This property accepts"},{"text":" ","type":"text"},{"text":"a set of ISO 2-character country codes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The default value is all known countries. Setting this property will limit"},{"type":"text","text":" "},{"type":"text","text":"the available countries to your selected set."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"availableCountries","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/availableCountries","url":"\/documentation\/stripe\/stppaymentconfiguration\/availablecountries","role":"symbol","title":"availableCountries","type":"topic","navigatorTitle":[{"text":"availableCountries","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"availableCountries","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"availableCountries","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"availableCountries"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentConfiguration","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","op":"replace","value":[{"text":"STPPaymentConfiguration","kind":"identifier"}]},{"value":"availableCountries","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1availableCountries\/title"},{"value":[{"text":"availableCountries","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1availableCountries\/fragments"}]}]}
