{"variants":[{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/candeletepaymentoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/candeletepaymentoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canDeletePaymentOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(py)canDeletePaymentOptions","modules":[{"name":"Stripe"}],"roleHeading":"Instance Property","symbolKind":"property","title":"canDeletePaymentOptions","navigatorTitle":[{"kind":"identifier","text":"canDeletePaymentOptions"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/canDeletePaymentOptions"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"canDeletePaymentOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"abstract":[{"type":"text","text":"Determines whether or not the user is able to delete payment options"},{"text":" ","type":"text"},{"type":"text","text":"This is only relevant to the "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" which, if"},{"type":"text","text":" "},{"type":"text","text":"enabled, will allow the user to delete payment options by tapping the “Edit”"},{"type":"text","text":" "},{"text":"button in the navigation bar or by swiping left on a payment option and tapping","type":"text"},{"type":"text","text":" "},{"text":"“Delete”. Currently, the user is not allowed to delete the selected payment","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"option but this may change in the future."},{"text":" ","type":"text"},{"type":"text","text":"Default value is YES but will only work if "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" is"},{"type":"text","text":" "},{"type":"text","text":"initialized with a "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" either through the "},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" ","type":"text"},{"text":"or directly as an init parameter.","type":"text"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"url":"\/documentation\/stripe\/stppaymentconfiguration","role":"symbol","navigatorTitle":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"title":"STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"text":" ","type":"text"},{"type":"text","text":"You provide an "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"when making a charge. The configuration generally has settings that"},{"type":"text","text":" "},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"text":"is specific to a single particular payment instance.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/canDeletePaymentOptions":{"navigatorTitle":[{"kind":"identifier","text":"canDeletePaymentOptions"}],"title":"canDeletePaymentOptions","url":"\/documentation\/stripe\/stppaymentconfiguration\/candeletepaymentoptions","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/canDeletePaymentOptions","abstract":[{"text":"Determines whether or not the user is able to delete payment options","type":"text"},{"text":" ","type":"text"},{"text":"This is only relevant to the ","type":"text"},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" which, if"},{"type":"text","text":" "},{"type":"text","text":"enabled, will allow the user to delete payment options by tapping the “Edit”"},{"type":"text","text":" "},{"text":"button in the navigation bar or by swiping left on a payment option and tapping","type":"text"},{"type":"text","text":" "},{"text":"“Delete”. Currently, the user is not allowed to delete the selected payment","type":"text"},{"type":"text","text":" "},{"text":"option but this may change in the future.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default value is YES but will only work if "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"text":" is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"initialized with a "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" either through the "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" "},{"text":"or directly as an init parameter.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"canDeletePaymentOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"canDeletePaymentOptions","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"canDeletePaymentOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"canDeletePaymentOptions","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentConfiguration","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1canDeletePaymentOptions\/title","value":"canDeletePaymentOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1canDeletePaymentOptions\/fragments","value":[{"kind":"identifier","text":"canDeletePaymentOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
