{"metadata":{"role":"symbol","modules":[{"name":"Stripe"}],"navigatorTitle":[{"text":"cardScanningEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cardScanningEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(py)cardScanningEnabled","title":"cardScanningEnabled"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardScanningEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"https:\/\/github.com\/stripe\/stripe-ios\/issues"},{"type":"text","text":" "},{"text":"The default value is currently NO. This will be changed in a future update.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Determines whether STPAddCardViewController allows the user to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"scan cards using the camera on devices running iOS 13 or later."},{"text":" ","type":"text"},{"text":"To use this feature, you must also set the ","type":"text"},{"code":"NSCameraUsageDescription","type":"codeVoice"},{"text":" ","type":"text"},{"text":"value in your app’s Info.plist.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/cardscanningenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/cardscanningenabled"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/cardScanningEnabled"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/cardScanningEnabled":{"url":"\/documentation\/stripe\/stppaymentconfiguration\/cardscanningenabled","type":"topic","title":"cardScanningEnabled","navigatorTitle":[{"text":"cardScanningEnabled","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Determines whether STPAddCardViewController allows the user to"},{"type":"text","text":" "},{"text":"scan cards using the camera on devices running iOS 13 or later.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"To use this feature, you must also set the "},{"type":"codeVoice","code":"NSCameraUsageDescription"},{"text":" ","type":"text"},{"text":"value in your app’s Info.plist.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/cardScanningEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardScanningEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"type":"topic","title":"STPPaymentConfiguration","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"text":" ","type":"text"},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"text":"will not change from payment to payment and thus is reusable, while the context","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentconfiguration","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"cardScanningEnabled","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"cardScanningEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardScanningEnabled"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1cardScanningEnabled\/title","value":"cardScanningEnabled"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1cardScanningEnabled\/fragments","value":[{"text":"cardScanningEnabled","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
