{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"companyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/companyname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/companyname"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/companyName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The name of your company, for displaying to the user during payment flows. For"},{"type":"text","text":" "},{"type":"text","text":"example, when using Apple Pay, the payment sheet’s final line item will read"},{"type":"text","text":" "},{"type":"text","text":"“PAY {companyName}”."},{"type":"text","text":" "},{"type":"text","text":"The default value is the name of your iOS application which is derived from the"},{"type":"text","text":" "},{"type":"codeVoice","code":"kCFBundleNameKey"},{"type":"text","text":" of "},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"companyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"companyName","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(py)companyName","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"companyName"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"role":"symbol","title":"STPPaymentConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentConfiguration"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"type":"text","text":"You provide an "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" object to your "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" "},{"type":"text","text":"when making a charge. The configuration generally has settings that"},{"type":"text","text":" "},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"url":"\/documentation\/stripe\/stppaymentconfiguration"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/companyName":{"role":"symbol","title":"companyName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"companyName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The name of your company, for displaying to the user during payment flows. For"},{"type":"text","text":" "},{"type":"text","text":"example, when using Apple Pay, the payment sheet’s final line item will read"},{"type":"text","text":" "},{"type":"text","text":"“PAY {companyName}”."},{"type":"text","text":" "},{"type":"text","text":"The default value is the name of your iOS application which is derived from the"},{"type":"text","text":" "},{"type":"codeVoice","code":"kCFBundleNameKey"},{"type":"text","text":" of "},{"type":"codeVoice","code":"Bundle.main"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/companyName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"companyName"}],"url":"\/documentation\/stripe\/stppaymentconfiguration\/companyname"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"companyName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"companyName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"companyName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"kind":"identifier","text":"STPPaymentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1companyName\/title","value":"companyName"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1companyName\/fragments","value":[{"kind":"identifier","text":"companyName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
