{"metadata":{"role":"symbol","symbolKind":"property","platforms":[],"modules":[{"name":"Stripe"}],"title":"publishableKey","externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(py)publishableKey","navigatorTitle":[{"text":"publishableKey","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"publishableKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"If you used STPPaymentConfiguration.shared.publishableKey, use STPAPIClient.shared.publishableKey instead. If you passed a STPPaymentConfiguration instance to an SDK component, create an STPAPIClient, set publishableKey on it, and set the SDK component's APIClient property."}],"type":"paragraph"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"publishableKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"aside","name":"See Also","content":[{"inlineContent":[{"type":"text","text":"https:\/\/dashboard.stripe.com\/account\/apikeys"}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/publishablekey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/publishablekey"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"sections":[],"abstract":[{"text":"If you used STPPaymentConfiguration.shared.publishableKey, use STPAPIClient.shared.publishableKey instead.  The SDK uses STPAPIClient.shared to make API requests by default.","type":"text"},{"text":" ","type":"text"},{"text":"Your Stripe publishable key","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/publishableKey","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/publishableKey":{"kind":"symbol","abstract":[{"type":"text","text":"If you used STPPaymentConfiguration.shared.publishableKey, use STPAPIClient.shared.publishableKey instead.  The SDK uses STPAPIClient.shared to make API requests by default."},{"text":" ","type":"text"},{"type":"text","text":"Your Stripe publishable key"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"publishableKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/publishableKey","url":"\/documentation\/stripe\/stppaymentconfiguration\/publishablekey","role":"symbol","deprecated":false,"title":"publishableKey","type":"topic","navigatorTitle":[{"kind":"identifier","text":"publishableKey"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"type":"topic","title":"STPPaymentConfiguration","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"text":" ","type":"text"},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"text":"will not change from payment to payment and thus is reusable, while the context","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentconfiguration","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"publishableKey","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"publishableKey","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"publishableKey"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1publishableKey\/title","value":"publishableKey"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1publishableKey\/fragments","value":[{"text":"publishableKey","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","op":"replace","value":"STPPaymentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"kind":"identifier","text":"STPPaymentConfiguration"}]}]}]}
