{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/requiredbillingaddressfields"]},{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/requiredbillingaddressfields"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The billing address fields the user must fill out when prompted for their"},{"text":" ","type":"text"},{"type":"text","text":"payment details. These fields will all be present on the returned PaymentMethod from"},{"type":"text","text":" "},{"text":"Stripe.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"STPBillingAddressFieldsPostalCode"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredBillingAddressFields","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@E@STPBillingAddressFields","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields","text":"STPBillingAddressFields"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"aside","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create#create_payment_method-billing_details","type":"text"}]}],"style":"note"}]}],"metadata":{"navigatorTitle":[{"text":"requiredBillingAddressFields","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(py)requiredBillingAddressFields","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"requiredBillingAddressFields","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@E@STPBillingAddressFields","text":"STPBillingAddressFields","kind":"typeIdentifier"}],"symbolKind":"property","title":"requiredBillingAddressFields","role":"symbol","modules":[{"name":"Stripe"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredBillingAddressFields"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBillingAddressFields":{"url":"\/documentation\/stripe\/stpbillingaddressfields","role":"symbol","navigatorTitle":[{"text":"STPBillingAddressFields","kind":"identifier"}],"title":"STPBillingAddressFields","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBillingAddressFields","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"What set of billing address information you need to collect from your user."}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"url":"\/documentation\/stripe\/stppaymentconfiguration","role":"symbol","navigatorTitle":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"title":"STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"text":" ","type":"text"},{"type":"text","text":"You provide an "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"when making a charge. The configuration generally has settings that"},{"type":"text","text":" "},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"text":"is specific to a single particular payment instance.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/requiredBillingAddressFields":{"abstract":[{"text":"The billing address fields the user must fill out when prompted for their","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment details. These fields will all be present on the returned PaymentMethod from"},{"type":"text","text":" "},{"type":"text","text":"Stripe."},{"text":" ","type":"text"},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"STPBillingAddressFieldsPostalCode"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredBillingAddressFields","role":"symbol","title":"requiredBillingAddressFields","type":"topic","url":"\/documentation\/stripe\/stppaymentconfiguration\/requiredbillingaddressfields","navigatorTitle":[{"kind":"identifier","text":"requiredBillingAddressFields"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredBillingAddressFields"},{"text":": ","kind":"text"},{"text":"STPBillingAddressFields","preciseIdentifier":"c:@M@Stripe@E@STPBillingAddressFields","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"requiredBillingAddressFields","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"requiredBillingAddressFields"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@E@STPBillingAddressFields","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBillingAddressFields","text":"STPBillingAddressFields"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredBillingAddressFields"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/title","value":"STPBillingAddressFields","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBillingAddressFields\/fragments","value":[{"text":"STPBillingAddressFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"value":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1requiredBillingAddressFields\/title","op":"replace","value":"requiredBillingAddressFields"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1requiredBillingAddressFields\/fragments","op":"replace","value":[{"kind":"identifier","text":"requiredBillingAddressFields"}]}]}]}
