{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredShippingAddressFields","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiredShippingAddressFields","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","text":"STPContactField"},{"text":">?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Instance Property","role":"symbol","title":"requiredShippingAddressFields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredShippingAddressFields"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"},{"text":">?","kind":"text"}],"navigatorTitle":[{"text":"requiredShippingAddressFields","kind":"identifier"}],"modules":[{"name":"Stripe"}],"symbolKind":"property","externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(py)requiredShippingAddressFields"},"abstract":[{"type":"text","text":"The shipping address fields the user must fill out when prompted for their"},{"type":"text","text":" "},{"type":"text","text":"shipping info. Set to nil if shipping address is not required."},{"text":" ","type":"text"},{"text":"The default value is nil.","type":"text"}],"variants":[{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/requiredshippingaddressfields"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/requiredshippingaddressfields"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPContactField":{"navigatorTitle":[{"text":"STPContactField","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"STPContactField","url":"\/documentation\/stripe\/stpcontactfield","abstract":[{"type":"text","text":"Contains constants that represent different parts of a users contact\/address information."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPContactField"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPContactField"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/requiredShippingAddressFields":{"kind":"symbol","abstract":[{"text":"The shipping address fields the user must fill out when prompted for their","type":"text"},{"type":"text","text":" "},{"type":"text","text":"shipping info. Set to nil if shipping address is not required."},{"type":"text","text":" "},{"type":"text","text":"The default value is nil."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredShippingAddressFields"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"},{"text":">?","kind":"text"}],"url":"\/documentation\/stripe\/stppaymentconfiguration\/requiredshippingaddressfields","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/requiredShippingAddressFields","role":"symbol","title":"requiredShippingAddressFields","type":"topic","navigatorTitle":[{"text":"requiredShippingAddressFields","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"type":"topic","title":"STPPaymentConfiguration","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"text":" ","type":"text"},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"text":"will not change from payment to payment and thus is reusable, while the context","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentconfiguration","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"requiredShippingAddressFields","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"requiredShippingAddressFields"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<STPContactField *>"},{"text":" * ","kind":"text"},{"text":"requiredShippingAddressFields","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1requiredShippingAddressFields\/title","op":"replace","value":"requiredShippingAddressFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1requiredShippingAddressFields\/fragments","value":[{"kind":"identifier","text":"requiredShippingAddressFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"text":"STPPaymentConfiguration","kind":"identifier"}]}]}]}
