{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(sharedConfiguration) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shared","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is a convenience singleton configuration that uses the default values for"},{"type":"text","text":" "},{"type":"text","text":"every property"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"}],"title":"shared","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(cpy)sharedConfiguration","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"sharedConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"}],"abstract":[{"type":"text","text":"This is a convenience singleton configuration that uses the default values for"},{"type":"text","text":" "},{"type":"text","text":"every property"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedConfiguration"}],"url":"\/documentation\/stripe\/stppaymentconfiguration\/shared"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"role":"symbol","title":"STPPaymentConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentConfiguration"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"type":"text","text":"You provide an "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" object to your "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" "},{"type":"text","text":"when making a charge. The configuration generally has settings that"},{"type":"text","text":" "},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"url":"\/documentation\/stripe\/stppaymentconfiguration"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"sharedConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sharedConfiguration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sharedConfiguration"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1shared\/title","value":"sharedConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1shared\/fragments","value":[{"kind":"identifier","text":"sharedConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"kind":"identifier","text":"STPPaymentConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}