{"metadata":{"role":"symbol","title":"shippingType","roleHeading":"Instance Property","externalID":"c:@M@Stripe@objc(cs)STPPaymentConfiguration(py)shippingType","modules":[{"name":"Stripe"}],"symbolKind":"property","navigatorTitle":[{"text":"shippingType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shippingType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@E@STPShippingType","text":"STPShippingType"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shippingType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@E@STPShippingType","kind":"typeIdentifier","text":"STPShippingType","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentconfiguration\/shippingtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentconfiguration\/shippingtype"]}],"kind":"symbol","abstract":[{"type":"text","text":"The type of shipping for this purchase. This property sets the labels displayed"},{"text":" ","type":"text"},{"text":"when the user is prompted for shipping info, and whether they should also be","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"asked to select a shipping method."},{"type":"text","text":" "},{"type":"text","text":"The default value is STPShippingTypeShipping."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shippingType","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingType":{"url":"\/documentation\/stripe\/stpshippingtype","abstract":[{"type":"text","text":"These values control the labels used in the shipping info collection form."}],"role":"symbol","title":"STPShippingType","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingType"}],"navigatorTitle":[{"text":"STPShippingType","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration/shippingType":{"url":"\/documentation\/stripe\/stppaymentconfiguration\/shippingtype","abstract":[{"type":"text","text":"The type of shipping for this purchase. This property sets the labels displayed"},{"text":" ","type":"text"},{"text":"when the user is prompted for shipping info, and whether they should also be","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"asked to select a shipping method."},{"type":"text","text":" "},{"type":"text","text":"The default value is STPShippingTypeShipping."}],"role":"symbol","kind":"symbol","type":"topic","title":"shippingType","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration\/shippingType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shippingType"},{"text":": ","kind":"text"},{"text":"STPShippingType","preciseIdentifier":"c:@M@Stripe@E@STPShippingType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"shippingType","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"url":"\/documentation\/stripe\/stppaymentconfiguration","role":"symbol","navigatorTitle":[{"text":"STPPaymentConfiguration","kind":"identifier"}],"title":"STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"An ","type":"text"},{"code":"STPPaymentConfiguration","type":"codeVoice"},{"type":"text","text":" represents all the options you can set or change"},{"type":"text","text":" "},{"type":"text","text":"around a payment."},{"text":" ","type":"text"},{"type":"text","text":"You provide an "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"when making a charge. The configuration generally has settings that"},{"type":"text","text":" "},{"type":"text","text":"will not change from payment to payment and thus is reusable, while the context"},{"type":"text","text":" "},{"text":"is specific to a single particular payment instance.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"shippingType"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"shippingType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingType","text":"STPShippingType","preciseIdentifier":"c:@M@Stripe@E@STPShippingType"},{"kind":"text","text":" "},{"text":"shippingType","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType\/title","value":"STPShippingType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingType\/fragments","value":[{"text":"STPShippingType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1shippingType\/title","op":"replace","value":"shippingType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration~1shippingType\/fragments","value":[{"text":"shippingType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPPaymentConfiguration","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"text":"STPPaymentConfiguration","kind":"identifier"}]}]}]}
