{"abstract":[{"text":"Account token type","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stptokentype\/account"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stptokentype\/account"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"symbolKind":"case","navigatorTitle":[{"text":"STPTokenTypeAccount","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPTokenType@STPTokenTypeAccount","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"account","kind":"identifier"}],"roleHeading":"Case","title":"STPTokenType.account","modules":[{"name":"StripePayments"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"account","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/account","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/account":{"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Account token type"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/account","title":"STPTokenType.account","url":"\/documentation\/stripepayments\/stptokentype\/account","navigatorTitle":[{"text":"STPTokenTypeAccount","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"account"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType":{"url":"\/documentation\/stripepayments\/stptokentype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPTokenType","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPTokenType","kind":"identifier"}],"abstract":[{"type":"text","text":"Possible Token types"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","title":"STPTokenType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPTokenTypeAccount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPTokenTypeAccount","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPTokenTypeAccount"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPTokenTypeAccount","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1account\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPTokenTypeAccount"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1account\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/title","value":"STPTokenType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/fragments","value":[{"kind":"identifier","text":"STPTokenType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPTokenType"}]}]}]}