{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/card","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPTokenTypeCard"}],"title":"STPTokenType.card","externalID":"c:@M@StripePayments@E@STPTokenType@STPTokenTypeCard","role":"symbol","modules":[{"name":"StripePayments"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stptokentype\/card"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stptokentype\/card"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Card token type"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType":{"navigatorTitle":[{"text":"STPTokenType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stptokentype","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPTokenType","kind":"identifier"}],"abstract":[{"type":"text","text":"Possible Token types"}],"title":"STPTokenType","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/card":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"card","kind":"identifier"}],"abstract":[{"text":"Card token type","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPTokenTypeCard"}],"title":"STPTokenType.card","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/card","url":"\/documentation\/stripepayments\/stptokentype\/card","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPTokenTypeCard","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPTokenTypeCard","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPTokenTypeCard","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"STPTokenType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/title"},{"value":[{"kind":"identifier","text":"STPTokenType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPTokenType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1card\/title","value":"STPTokenTypeCard"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1card\/fragments","op":"replace","value":[{"text":"STPTokenTypeCard","kind":"identifier"}]}]}]}