{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stptokentype\/cvcupdate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stptokentype\/cvcupdate"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPTokenType@STPTokenTypeCvcUpdate","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvcUpdate"}],"navigatorTitle":[{"kind":"identifier","text":"STPTokenTypeCvcUpdate"}],"role":"symbol","title":"STPTokenType.cvcUpdate"},"sections":[],"abstract":[{"text":"CVC update token type","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cvcUpdate","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/cvcUpdate","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/cvcUpdate":{"navigatorTitle":[{"kind":"identifier","text":"STPTokenTypeCvcUpdate"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cvcUpdate"}],"title":"STPTokenType.cvcUpdate","url":"\/documentation\/stripepayments\/stptokentype\/cvcupdate","role":"symbol","abstract":[{"type":"text","text":"CVC update token type"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/cvcUpdate","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType":{"navigatorTitle":[{"text":"STPTokenType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stptokentype","type":"topic","title":"STPTokenType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTokenType","kind":"identifier"}],"abstract":[{"type":"text","text":"Possible Token types"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPTokenTypeCvcUpdate","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPTokenTypeCvcUpdate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPTokenTypeCvcUpdate"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPTokenTypeCvcUpdate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1cvcUpdate\/title"},{"value":[{"text":"STPTokenTypeCvcUpdate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1cvcUpdate\/fragments"},{"value":"STPTokenType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/title"},{"value":[{"text":"STPTokenType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/fragments"},{"value":[{"text":"STPTokenType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/navigatorTitle"}]}]}