{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stptokentype\/init(rawvalue:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/init(rawValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType"]]},"sections":[],"metadata":{"externalID":"s:14StripePayments12STPTokenTypeO8rawValueACSgSi_tcfc","roleHeading":"Initializer","modules":[{"name":"StripePayments"}],"title":"init(rawValue:)","role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTokenType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stptokentype","navigatorTitle":[{"text":"STPTokenType","kind":"identifier"}],"abstract":[{"type":"text","text":"Possible Token types"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","kind":"symbol","title":"STPTokenType"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stptokentype\/init(rawvalue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPTokenType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/title","op":"replace"},{"value":[{"text":"STPTokenType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/fragments","op":"replace"},{"value":[{"text":"STPTokenType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/navigatorTitle","op":"replace"}]}]}