{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stptokentype\/rawrepresentable-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/RawRepresentable-Implementations"},"kind":"article","metadata":{"title":"RawRepresentable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/hashValue"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/hash(into:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/hashValue":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/hashValue","kind":"symbol","type":"topic","title":"hashValue","url":"\/documentation\/stripepayments\/stptokentype\/hashvalue","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType":{"kind":"symbol","type":"topic","title":"STPTokenType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTokenType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","navigatorTitle":[{"kind":"identifier","text":"STPTokenType"}],"abstract":[{"text":"Possible Token types","type":"text"}],"url":"\/documentation\/stripepayments\/stptokentype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/hash(into:)":{"url":"\/documentation\/stripepayments\/stptokentype\/hash(into:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"hash(into:)","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/hash(into:)","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/title","value":"STPTokenType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/fragments","value":[{"kind":"identifier","text":"STPTokenType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/navigatorTitle","value":[{"text":"STPTokenType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}