{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodtwint\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodtwint\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","roleHeading":"Instance Property","title":"description","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodTwint(py)description","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodTwint"]]},"sections":[],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodTwint\/description","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodTwint/description":{"abstract":[{"type":"text","text":":nodoc:"}],"title":"description","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtwint\/description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodTwint\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodTwint":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTwint"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtwint","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A TWINT Payment Method."}],"title":"STPPaymentMethodTwint","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodTwint","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodTwint"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodTwint~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodTwint~1description\/fragments"},{"value":"STPPaymentMethodTwint","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodTwint\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTwint"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodTwint\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTwint"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodTwint\/navigatorTitle"}]}]}