{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPalParams"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPalParams\/init"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodpaypalparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayPalParams(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"modules":[{"name":"StripePayments"}],"role":"symbol","title":"init","symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayPalParams/init":{"url":"\/documentation\/stripepayments\/stppaymentmethodpaypalparams\/init","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPalParams\/init","title":"init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayPalParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPayPalParams","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodPayPalParams","kind":"identifier"}],"title":"STPPaymentMethodPayPalParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPalParams","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodpaypalparams","abstract":[{"text":"An object representing parameters used to create a PayPal Payment Method :nodoc:","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPalParams\/title","value":"STPPaymentMethodPayPalParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPalParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodPayPalParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPalParams\/navigatorTitle","value":[{"text":"STPPaymentMethodPayPalParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}