{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/accountholdertype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/accountholdertype"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountHolderType"},{"kind":"text","text":": "},{"text":"STPBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/accountHolderType"},"abstract":[{"type":"text","text":"The type of entity that holds the account."},{"text":" ","type":"text"},{"text":"Defaults to STPBankAccountHolderTypeIndividual.","type":"text"}],"metadata":{"title":"accountHolderType","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"accountHolderType"}],"externalID":"c:@M@StripePayments@objc(cs)STPBankAccountParams(py)accountHolderType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountHolderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPBankAccountHolderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams/accountHolderType":{"title":"accountHolderType","url":"\/documentation\/stripepayments\/stpbankaccountparams\/accountholdertype","abstract":[{"type":"text","text":"The type of entity that holds the account."},{"type":"text","text":" "},{"type":"text","text":"Defaults to STPBankAccountHolderTypeIndividual."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/accountHolderType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountHolderType"},{"text":": ","kind":"text"},{"text":"STPBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"accountHolderType","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","title":"STPBankAccountHolderType","navigatorTitle":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPBankAccountHolderType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountholdertype","abstract":[{"type":"text","text":"The type of entity that holds a bank account."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"url":"\/documentation\/stripepayments\/stpbankaccountparams","abstract":[{"text":"Representation of a user’s bank account details. You can assemble these with","type":"text"},{"type":"text","text":" "},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"type":"text","text":" "},{"text":"an STPAPIClient.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountParams"}],"role":"symbol","kind":"symbol","title":"STPBankAccountParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accountHolderType"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountHolderType"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType","text":"STPBankAccountHolderType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"accountHolderType","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"accountHolderType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1accountHolderType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1accountHolderType\/fragments","value":[{"text":"accountHolderType","kind":"identifier"}]},{"op":"replace","value":"STPBankAccountHolderType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPBankAccountHolderType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","value":"STPBankAccountParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPBankAccountParams"}],"op":"replace"}]}]}
