{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/accountnumber"]},{"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/accountnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"accountNumber","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPBankAccountParams(py)accountNumber","role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"accountNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"accountNumber"},"abstract":[{"type":"text","text":"The account number for the bank account. Currently must be a checking account."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/accountNumber"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountParams"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountparams","kind":"symbol","title":"STPBankAccountParams","type":"topic","abstract":[{"type":"text","text":"Representation of a user’s bank account details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"text":" ","type":"text"},{"type":"text","text":"an STPAPIClient."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams/accountNumber":{"url":"\/documentation\/stripepayments\/stpbankaccountparams\/accountnumber","abstract":[{"type":"text","text":"The account number for the bank account. Currently must be a checking account."}],"navigatorTitle":[{"kind":"identifier","text":"accountNumber"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/accountNumber","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"accountNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"accountNumber","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"accountNumber","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountNumber"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"accountNumber"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPBankAccountParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title"},{"op":"replace","value":[{"text":"STPBankAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPBankAccountParams"}]},{"op":"replace","value":"accountNumber","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1accountNumber\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1accountNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"accountNumber"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}