{"kind":"symbol","metadata":{"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPBankAccountParams(py)accountHolderName","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"accountHolderName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"title":"accountHolderName","navigatorTitle":[{"text":"accountHolderName","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/accountHolderName"},"abstract":[{"text":"The name of the person or business that owns the bank account.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountHolderName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/accountholdername"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/accountholdername"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"url":"\/documentation\/stripepayments\/stpbankaccountparams","abstract":[{"text":"Representation of a user’s bank account details. You can assemble these with","type":"text"},{"type":"text","text":" "},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"type":"text","text":" "},{"text":"an STPAPIClient.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountParams"}],"role":"symbol","kind":"symbol","title":"STPBankAccountParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams/accountHolderName":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountparams\/accountholdername","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/accountHolderName","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountHolderName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"accountHolderName","kind":"identifier"}],"title":"accountHolderName","role":"symbol","abstract":[{"type":"text","text":"The name of the person or business that owns the bank account."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"accountHolderName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"accountHolderName"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"accountHolderName"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","value":"STPBankAccountParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPBankAccountParams"}],"op":"replace"},{"op":"replace","value":"accountHolderName","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1accountHolderName\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1accountHolderName\/fragments","value":[{"kind":"identifier","text":"accountHolderName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
