{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:"},{"type":"text","text":" "},{"type":"text","text":"var cardParams = STPCardParams()"},{"type":"text","text":" "},{"type":"text","text":"\/\/ add card values"},{"type":"text","text":" "},{"type":"text","text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]"},{"type":"text","text":" "},{"type":"text","text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/additionalAPIParameters"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"]]},"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPBankAccountParams(py)additionalAPIParameters","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"title":"additionalAPIParameters"},"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/additionalapiparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/additionalapiparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams/additionalAPIParameters":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"abstract":[{"text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:","type":"text"},{"text":" ","type":"text"},{"text":"var cardParams = STPCardParams()","type":"text"},{"text":" ","type":"text"},{"text":"\/\/ add card values","type":"text"},{"text":" ","type":"text"},{"text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]","type":"text"},{"text":" ","type":"text"},{"text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);","type":"text"}],"title":"additionalAPIParameters","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/additionalAPIParameters","url":"\/documentation\/stripepayments\/stpbankaccountparams\/additionalapiparameters"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"abstract":[{"type":"text","text":"Representation of a user’s bank account details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"title":"STPBankAccountParams","url":"\/documentation\/stripepayments\/stpbankaccountparams","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountParams"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountParams"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"additionalAPIParameters"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"additionalAPIParameters"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1additionalAPIParameters\/title","op":"replace","value":"additionalAPIParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1additionalAPIParameters\/fragments","value":[{"kind":"identifier","text":"additionalAPIParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","value":"STPBankAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","value":[{"text":"STPBankAccountParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle","value":[{"text":"STPBankAccountParams","kind":"identifier"}]}]}]}