{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/currency"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/currency"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"]]},"sections":[],"kind":"symbol","abstract":[{"text":"The default currency for the bank account.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currency"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPBankAccountParams(py)currency","roleHeading":"Instance Property","title":"currency","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"currency","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/currency"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams/currency":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/currency","url":"\/documentation\/stripepayments\/stpbankaccountparams\/currency","navigatorTitle":[{"text":"currency","kind":"identifier"}],"type":"topic","title":"currency","abstract":[{"type":"text","text":"The default currency for the bank account."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","url":"\/documentation\/stripepayments\/stpbankaccountparams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountParams"}],"navigatorTitle":[{"text":"STPBankAccountParams","kind":"identifier"}],"abstract":[{"text":"Representation of a user’s bank account details. You can assemble these with","type":"text"},{"text":" ","type":"text"},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"text":" ","type":"text"},{"text":"an STPAPIClient.","type":"text"}],"role":"symbol","title":"STPBankAccountParams","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"currency"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"currency","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"currency"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1currency\/title","value":"currency"},{"value":[{"kind":"identifier","text":"currency"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1currency\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","value":"STPBankAccountParams","op":"replace"},{"op":"replace","value":[{"text":"STPBankAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPBankAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}