{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/init()"]}],"metadata":{"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","externalID":"c:@M@StripePayments@objc(cs)STPBankAccountParams(im)init","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","roleHeading":"Initializer","modules":[{"name":"StripePayments"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/init()"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Initializes an empty STPBankAccountParams."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"title":"STPBankAccountParams","role":"symbol","abstract":[{"text":"Representation of a user’s bank account details. You can assemble these with","type":"text"},{"text":" ","type":"text"},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"text":" ","type":"text"},{"text":"an STPAPIClient.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","navigatorTitle":[{"text":"STPBankAccountParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountParams","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams/init()":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"text":"Initializes an empty STPBankAccountParams.","type":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/init()","title":"init()","role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountparams\/init()"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","value":"STPBankAccountParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPBankAccountParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle","value":[{"text":"STPBankAccountParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"}]}]}