{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/last4"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountparams\/last4"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","title":"last4","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPBankAccountParams(py)last4","roleHeading":"Instance Property","navigatorTitle":[{"text":"last4","kind":"identifier"}],"role":"symbol"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/last4","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"last4"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The last 4 digits of the bank account’s account number, if it’s been set,"},{"type":"text","text":" "},{"type":"text","text":"otherwise nil."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams/last4":{"navigatorTitle":[{"text":"last4","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams\/last4","type":"topic","kind":"symbol","role":"symbol","title":"last4","url":"\/documentation\/stripepayments\/stpbankaccountparams\/last4","abstract":[{"type":"text","text":"The last 4 digits of the bank account’s account number, if it’s been set,"},{"type":"text","text":" "},{"type":"text","text":"otherwise nil."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountParams"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Representation of a user’s bank account details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","title":"STPBankAccountParams","url":"\/documentation\/stripepayments\/stpbankaccountparams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"last4","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"last4","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"last4","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1last4\/title","op":"replace"},{"value":[{"text":"last4","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams~1last4\/fragments","op":"replace"},{"value":"STPBankAccountParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","op":"replace"},{"value":[{"text":"STPBankAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","op":"replace"},{"value":[{"text":"STPBankAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}