{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/!=(_:_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","role":"symbol","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"navigatorTitle":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"abstract":[{"type":"text","text":"The type of customer acceptance information included with the Mandate."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType","type":"topic","title":"STPMandateCustomerAcceptanceType","kind":"symbol","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/title","value":"STPMandateCustomerAcceptanceType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/fragments","value":[{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/navigatorTitle","value":[{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}