{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"A Mandate that was accepted offline."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/offline","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/offline"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/offline"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType"]]},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"STPMandateCustomerAcceptanceTypeOffline","kind":"identifier"}],"title":"STPMandateCustomerAcceptanceType.offline","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPMandateCustomerAcceptanceType@STPMandateCustomerAcceptanceTypeOffline","role":"symbol","symbolKind":"case"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/offline":{"type":"topic","abstract":[{"type":"text","text":"A Mandate that was accepted offline."}],"url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/offline","role":"symbol","navigatorTitle":[{"text":"STPMandateCustomerAcceptanceTypeOffline","kind":"identifier"}],"kind":"symbol","title":"STPMandateCustomerAcceptanceType.offline","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/offline","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of customer acceptance information included with the Mandate."}],"kind":"symbol","navigatorTitle":[{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"title":"STPMandateCustomerAcceptanceType"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPMandateCustomerAcceptanceTypeOffline","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceTypeOffline"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceTypeOffline"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPMandateCustomerAcceptanceTypeOffline","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType~1offline\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceTypeOffline"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType~1offline\/fragments"},{"op":"replace","value":"STPMandateCustomerAcceptanceType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/title"},{"op":"replace","value":[{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}