{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/online","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Mandate that was accepted online."}],"metadata":{"externalID":"c:@M@StripePayments@E@STPMandateCustomerAcceptanceType@STPMandateCustomerAcceptanceTypeOnline","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"STPMandateCustomerAcceptanceTypeOnline","kind":"identifier"}],"symbolKind":"case","title":"STPMandateCustomerAcceptanceType.online","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"online","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"online"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/online"]},{"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/online"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/online":{"abstract":[{"type":"text","text":"A Mandate that was accepted online."}],"role":"symbol","navigatorTitle":[{"text":"STPMandateCustomerAcceptanceTypeOnline","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/online","type":"topic","title":"STPMandateCustomerAcceptanceType.online","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/online","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"online"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType","title":"STPMandateCustomerAcceptanceType","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype","abstract":[{"text":"The type of customer acceptance information included with the Mandate.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"navigatorTitle":[{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"STPMandateCustomerAcceptanceTypeOnline","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPMandateCustomerAcceptanceTypeOnline","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPMandateCustomerAcceptanceTypeOnline","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPMandateCustomerAcceptanceTypeOnline","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType~1online\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType~1online\/fragments","value":[{"text":"STPMandateCustomerAcceptanceTypeOnline","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPMandateCustomerAcceptanceType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/title"},{"op":"replace","value":[{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/navigatorTitle","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}