{"abstract":[{"type":"text","text":":nodoc:"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"] { get }"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/allresponsefields"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/allresponsefields"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails\/allResponseFields","interfaceLanguage":"swift"},"metadata":{"title":"allResponseFields","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails(py)allResponseFields"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails/allResponseFields":{"title":"allResponseFields","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/allresponsefields","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails\/allResponseFields","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails":{"navigatorTitle":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"abstract":[{"text":"Contains Multibanco details necessary for the customer to complete the payment.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails","url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails","title":"STPIntentActionMultibancoDisplayDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"allResponseFields","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails~1allResponseFields\/title","value":"allResponseFields","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/title","value":"STPIntentActionMultibancoDisplayDetails"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionMultibancoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/fragments"},{"value":[{"kind":"identifier","text":"STPIntentActionMultibancoDisplayDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}