{"metadata":{"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails(py)entity","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"entity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"entity"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","title":"entity","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"entity","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails\/entity","interfaceLanguage":"swift"},"abstract":[{"text":"The multibanco entity number","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/entity"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/entity"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails/entity":{"abstract":[{"text":"The multibanco entity number","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/entity","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"entity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails\/entity","type":"topic","title":"entity","navigatorTitle":[{"kind":"identifier","text":"entity"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails":{"kind":"symbol","abstract":[{"text":"Contains Multibanco details necessary for the customer to complete the payment.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails","role":"symbol","title":"STPIntentActionMultibancoDisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"entity"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"entity"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"entity"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails~1entity\/title","value":"entity","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails~1entity\/fragments","value":[{"kind":"identifier","text":"entity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/title","value":"STPIntentActionMultibancoDisplayDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/fragments","value":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionMultibancoDisplayDetails"}]}]}]}