{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails(py)expiresAt","title":"expiresAt","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"expiresAt"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails\/expiresAt"},"sections":[],"abstract":[{"type":"text","text":"The expiry date of the multibanco voucher."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/expiresat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/expiresat"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}]}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails/expiresAt":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"}],"title":"expiresAt","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails\/expiresAt","role":"symbol","navigatorTitle":[{"text":"expiresAt","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/expiresat","abstract":[{"type":"text","text":"The expiry date of the multibanco voucher."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails","role":"symbol","title":"STPIntentActionMultibancoDisplayDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Contains Multibanco details necessary for the customer to complete the payment.","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails","navigatorTitle":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"expiresAt","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"expiresAt","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"expiresAt"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"expiresAt","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails~1expiresAt\/title"},{"op":"replace","value":[{"text":"expiresAt","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails~1expiresAt\/fragments"},{"op":"replace","value":"STPIntentActionMultibancoDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/title"},{"op":"replace","value":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/fragments"},{"op":"replace","value":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}