{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/reference"]},{"paths":["\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/reference"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reference"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"metadata":{"title":"reference","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"reference","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails(py)reference","navigatorTitle":[{"text":"reference","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"sections":[],"abstract":[{"text":"Multibanco reference number","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails\/reference"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails/reference":{"role":"symbol","title":"reference","kind":"symbol","navigatorTitle":[{"text":"reference","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reference","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails\/reference","url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails\/reference","type":"topic","abstract":[{"type":"text","text":"Multibanco reference number"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionMultibancoDisplayDetails":{"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpintentactionmultibancodisplaydetails","title":"STPIntentActionMultibancoDisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionMultibancoDisplayDetails","abstract":[{"type":"text","text":"Contains Multibanco details necessary for the customer to complete the payment."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"reference"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"reference","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"reference","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"reference","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails~1reference\/title"},{"value":[{"text":"reference","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails~1reference\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/title","value":"STPIntentActionMultibancoDisplayDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/fragments","value":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionMultibancoDisplayDetails\/navigatorTitle","value":[{"text":"STPIntentActionMultibancoDisplayDetails","kind":"identifier"}],"op":"replace"}]}]}