{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)confirmPaymentIntentWithParams:completion:","title":"confirmPaymentIntent(with:completion:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"StripeCore"},"abstract":[{"text":"Confirms the PaymentIntent object with the provided params object.","type":"text"},{"text":" ","type":"text"},{"text":"At a minimum, the params object must include the ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/confirmpaymentintent(with:completion:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/confirmPaymentIntent(with:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(confirmPaymentIntentWithParams:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentIntentConfirmParams","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka","text":"STPPaymentIntentCompletionBlock","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCompletionBlock"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"paymentIntentConfirmParams","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"STPPaymentIntentConfirmParams","type":"codeVoice"},{"type":"text","text":" to pass to "},{"code":"\/confirm","type":"codeVoice"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback to run with the returned PaymentIntent object, or an error."}]}]}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the "},{"code":"confirmPayment:withAuthenticationContext:completion:","type":"codeVoice"},{"type":"text","text":" method on "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" instead"},{"type":"text","text":" "},{"type":"text","text":"of calling this method directly. It handles any authentication necessary for you."}]}],"type":"aside","style":"note"},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent","isActive":true}]}],"type":"aside","style":"note"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"type":"topic","title":"STPPaymentIntentConfirmParams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCompletionBlock":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentcompletionblock","abstract":[{"text":"A callback to be run with a PaymentIntent response from the Stripe API.","type":"text"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentCompletionBlock"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCompletionBlock"}],"type":"topic","title":"STPPaymentIntentCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCompletionBlock","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/confirmPaymentIntent(with:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/confirmPaymentIntent(with:completion:)","abstract":[{"text":"Confirms the PaymentIntent object with the provided params object.","type":"text"},{"text":" ","type":"text"},{"text":"At a minimum, the params object must include the ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka","text":"STPPaymentIntentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/confirmpaymentintent(with:completion:)","title":"confirmPaymentIntent(with:completion:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","abstract":[],"title":"StripeCore","url":"\/documentation\/stripepayments\/stripecore","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","kind":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"type":"topic","title":"STPAPIClient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"identifier"}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"https://stripe.com/docs/api#confirm_payment_intent":{"title":"Stripe API reference","url":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent","identifier":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"type":"link"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","value":"STPPaymentIntentConfirmParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]}]}]}