{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/confirmSetupIntent(with:expand:completion:)"},"metadata":{"externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)confirmSetupIntentWithParams:expand:completion:","extendedModule":"StripeCore","title":"confirmSetupIntent(with:expand:completion:)","roleHeading":"Instance Method","symbolKind":"method","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSetupIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSetupIntentCompletionBlock","preciseIdentifier":"s:14StripePayments29STPSetupIntentCompletionBlocka"},{"kind":"text","text":")"}]},"abstract":[{"text":"Confirms the SetupIntent object with the provided params object.","type":"text"},{"text":" ","type":"text"},{"text":"At a minimum, the params object must include the ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/confirmsetupintent(with:expand:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(confirmSetupIntentWithParams:expand:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"setupIntentParams","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"STPSetupIntentCompletionBlock","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentCompletionBlock","preciseIdentifier":"s:14StripePayments29STPSetupIntentCompletionBlocka"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPSetupIntentConfirmParams"},{"type":"text","text":" to pass to "},{"type":"codeVoice","code":"\/confirm"}],"type":"paragraph"}],"name":"setupIntentParams"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An array of string keys to expand on the returned SetupIntent object. These strings should match one or more of the parameter names that are marked as expandable.","type":"text"}]}],"name":"expand"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The callback to run with the returned PaymentIntent object, or an error.","type":"text"}]}],"name":"completion"}],"kind":"parameters"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the "},{"code":"confirmSetupIntent:withAuthenticationContext:completion:","type":"codeVoice"},{"type":"text","text":" method on "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" instead"},{"type":"text","text":" "},{"type":"text","text":"of calling this method directly. It handles any authentication necessary for you."}]}],"style":"note","type":"aside"},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","type":"reference","isActive":true}]}],"style":"note","type":"aside"},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object"}]}],"style":"note","type":"aside"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"title":"STPAPIClient","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","kind":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","url":"\/documentation\/stripepayments\/stripecore","type":"topic","abstract":[],"role":"collection","title":"StripeCore","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/confirmSetupIntent(with:expand:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/confirmSetupIntent(with:expand:completion:)","title":"confirmSetupIntent(with:expand:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments29STPSetupIntentCompletionBlocka","text":"STPSetupIntentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/confirmsetupintent(with:expand:completion:)","abstract":[{"text":"Confirms the SetupIntent object with the provided params object.","type":"text"},{"text":" ","type":"text"},{"text":"At a minimum, the params object must include the ","type":"text"},{"type":"codeVoice","code":"clientSecret"},{"text":".","type":"text"}]},"https://stripe.com/docs/api/setup_intents/object":{"type":"link","identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","title":"Stripe API reference","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentCompletionBlock":{"title":"STPSetupIntentCompletionBlock","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentcompletionblock","kind":"symbol","abstract":[{"type":"text","text":"A callback to be run with a PaymentIntent response from the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentCompletionBlock","role":"symbol","navigatorTitle":[{"text":"STPSetupIntentCompletionBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentCompletionBlock","kind":"identifier"}]},"https://stripe.com/docs/api/setup_intents/confirm":{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"title":"Stripe API reference","type":"link","url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"title":"STPSetupIntentConfirmParams","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"type":"text","text":" "},{"type":"text","text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app."},{"type":"text","text":" "},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"type":"text","text":".  Otherwise, it will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"type":"text","text":", and suggest additional actions via "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Instead of passing this to ","type":"text"},{"code":"STPAPIClient.confirmSetupIntent(...)","type":"codeVoice"},{"text":" directly, we recommend using ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" to handle any additional steps for you.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","op":"replace","value":"STPSetupIntentConfirmParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","op":"replace","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}