{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/confirmSetupIntent(with:expand:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"metadata":{"roleHeading":"Instance Method","extendedModule":"StripeCore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent"}],"externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE18confirmSetupIntent4with6expandAD08STPSetupG0CAD0jG13ConfirmParamsC_SaySSGSgtYaKF","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"role":"symbol","title":"confirmSetupIntent(with:expand:)","symbolKind":"method"},"abstract":[{"text":"Confirms the SetupIntent object with the provided params object.","type":"text"},{"text":" ","type":"text"},{"text":"At a minimum, the params object must include the ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/confirmsetupintent(with:expand:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"setupIntentParams","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]? = nil) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"setupIntentParams","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentConfirmParams"},{"text":" to pass to ","type":"text"},{"type":"codeVoice","code":"\/confirm"}],"type":"paragraph"}]},{"name":"expand","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of string keys to expand on the returned SetupIntent object. These strings should match one or more of the parameter names that are marked as expandable."}]}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A SetupIntent object."}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"Use the ","type":"text"},{"type":"codeVoice","code":"confirmSetupIntent:withAuthenticationContext:completion:"},{"text":" method on ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" instead","type":"text"},{"text":" ","type":"text"},{"text":"of calling this method directly. It handles any authentication necessary for you.","type":"text"}]}],"type":"aside","style":"note"},{"name":"Throws","content":[{"inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}],"type":"paragraph"}],"type":"aside","style":"note"},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","isActive":true}]}],"type":"aside","style":"note"},{"name":"See Also","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","type":"reference","isActive":true}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"https://stripe.com/docs/api/setup_intents/object":{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","title":"Stripe API reference","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","type":"link"},"https://stripe.com/docs/api/setup_intents/confirm":{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","title":"Stripe API reference","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","type":"link"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"title":"STPSetupIntentConfirmParams","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"text":".  Otherwise, it will transition to ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"text":", and suggest additional actions via ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Instead of passing this to ","type":"text"},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"text":" directly, we recommend using ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" to handle any additional steps for you.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","url":"\/documentation\/stripepayments\/stpsetupintent","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"role":"symbol","title":"STPSetupIntent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/confirmSetupIntent(with:expand:)":{"abstract":[{"text":"Confirms the SetupIntent object with the provided params object.","type":"text"},{"text":" ","type":"text"},{"text":"At a minimum, the params object must include the ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/confirmsetupintent(with:expand:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","kind":"typeIdentifier","text":"STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","kind":"typeIdentifier","text":"STPSetupIntent"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/confirmSetupIntent(with:expand:)","title":"confirmSetupIntent(with:expand:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"url":"\/documentation\/stripepayments\/stripecore","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","type":"topic","title":"StripeCore","abstract":[],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"title":"STPAPIClient","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"STPSetupIntentConfirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","op":"replace"},{"value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","op":"replace"},{"value":"STPSetupIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","op":"replace"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}