{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/confirmsetupintent(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Confirms the SetupIntent object with the provided params object."},{"type":"text","text":" "},{"type":"text","text":"At a minimum, the params object must include the "},{"type":"codeVoice","code":"clientSecret"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(confirmSetupIntentWithParams:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"setupIntentParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments29STPSetupIntentCompletionBlocka","text":"STPSetupIntentCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentCompletionBlock"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPSetupIntentConfirmParams"},{"type":"text","text":" to pass to "},{"type":"codeVoice","code":"\/confirm"}]}],"name":"setupIntentParams"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback to run with the returned PaymentIntent object, or an error."}]}],"name":"completion"}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the "},{"type":"codeVoice","code":"confirmSetupIntent:withAuthenticationContext:completion:"},{"type":"text","text":" method on "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" instead"},{"type":"text","text":" "},{"type":"text","text":"of calling this method directly. It handles any authentication necessary for you."}]}]},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","isActive":true}]}]}],"kind":"content"}],"metadata":{"extendedModule":"StripeCore","roleHeading":"Instance Method","title":"confirmSetupIntent(with:completion:)","role":"symbol","externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)confirmSetupIntentWithParams:completion:","symbolKind":"method","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments29STPSetupIntentCompletionBlocka","text":"STPSetupIntentCompletionBlock"},{"kind":"text","text":")"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/confirmSetupIntent(with:completion:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentCompletionBlock":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentCompletionBlock","kind":"identifier"}],"abstract":[{"type":"text","text":"A callback to be run with a PaymentIntent response from the Stripe API."}],"navigatorTitle":[{"text":"STPSetupIntentCompletionBlock","kind":"identifier"}],"title":"STPSetupIntentCompletionBlock","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentCompletionBlock","url":"\/documentation\/stripepayments\/stpsetupintentcompletionblock"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"kind":"symbol","abstract":[{"type":"text","text":"STPAPIClient extensions for working with PaymentMethod objects."}],"role":"symbol","title":"STPAPIClient","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/confirmSetupIntent(with:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPSetupIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPSetupIntentCompletionBlock","preciseIdentifier":"s:14StripePayments29STPSetupIntentCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"confirmSetupIntent(with:completion:)","abstract":[{"type":"text","text":"Confirms the SetupIntent object with the provided params object."},{"type":"text","text":" "},{"type":"text","text":"At a minimum, the params object must include the "},{"type":"codeVoice","code":"clientSecret"},{"type":"text","text":"."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/confirmSetupIntent(with:completion:)","kind":"symbol","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/confirmsetupintent(with:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"title":"STPSetupIntentConfirmParams","abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"text":".  Otherwise, it will transition to ","type":"text"},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"text":", and suggest additional actions via ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Instead of passing this to ","type":"text"},{"code":"STPAPIClient.confirmSetupIntent(...)","type":"codeVoice"},{"text":" directly, we recommend using ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" to handle any additional steps for you.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams"},"https://stripe.com/docs/api/setup_intents/confirm":{"title":"Stripe API reference","identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","type":"link"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"abstract":[],"title":"StripeCore","role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","type":"topic","url":"\/documentation\/stripepayments\/stripecore"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","value":"STPSetupIntentConfirmParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}