{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createPaymentMethod(with:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"paymentMethodParams","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":" to pass to ","type":"text"},{"type":"codeVoice","code":"\/v1\/payment_methods"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The created PaymentMethod object.","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","style":"note","name":"Throws","content":[{"inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}],"type":"paragraph"}]},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create","type":"reference"}]}]}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"}],"modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE19createPaymentMethod4withAD010STPPaymentG0CAD0iG6ParamsC_tYaKF","extendedModule":"StripeCore","title":"createPaymentMethod(with:)","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createpaymentmethod(with:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Creates a PaymentMethod object with the provided params object."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createPaymentMethod(with:)":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createpaymentmethod(with:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates a PaymentMethod object with the provided params object."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","text":"STPPaymentMethod"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createPaymentMethod(with:)","role":"symbol","title":"createPaymentMethod(with:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"kind":"symbol","abstract":[],"role":"collection","title":"StripeCore","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","url":"\/documentation\/stripepayments\/stripecore"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"identifier","text":"STPAPIClient"}],"kind":"symbol","abstract":[{"type":"text","text":"STPAPIClient extensions for working with PaymentMethod objects."}],"role":"symbol","title":"STPAPIClient","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"kind":"symbol","title":"STPPaymentMethod","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"kind":"symbol","title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"type":"topic"},"https://stripe.com/docs/api/payment_methods/create":{"titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"type":"link","url":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create","title":"Stripe API reference","identifier":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace"}]}]}