{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withBankAccount:completion:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(createTokenWithBankAccount:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBankAccount","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"bankAccount","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","text":"STPBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","text":"STPTokenCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The user’s bank account details."}],"type":"paragraph"}],"name":"bankAccount"},{"content":[{"inlineContent":[{"type":"text","text":"The callback to run with the returned Stripe token (and any errors that may have occurred)."}],"type":"paragraph"}],"name":"completion"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#create_bank_account_token","isActive":true}],"type":"paragraph"}],"style":"note","name":"See Also"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBankAccount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams","text":"STPBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","extendedModule":"StripeCore","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createTokenWithBankAccount:completion:","title":"createToken(withBankAccount:completion:)"},"abstract":[{"type":"text","text":"Converts an STPBankAccount object into a Stripe token using the Stripe API."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withbankaccount:completion:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createToken(withBankAccount:completion:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withBankAccount:completion:)","kind":"symbol","role":"symbol","title":"createToken(withBankAccount:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBankAccount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPTokenCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Converts an STPBankAccount object into a Stripe token using the Stripe API."}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withbankaccount:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","role":"symbol","type":"topic","abstract":[{"type":"text","text":"STPAPIClient extensions for working with PaymentMethod objects."}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenCompletionBlock":{"type":"topic","title":"STPTokenCompletionBlock","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","navigatorTitle":[{"text":"STPTokenCompletionBlock","kind":"identifier"}],"abstract":[{"type":"text","text":"A callback to be run with a token response from the Stripe API."}],"url":"\/documentation\/stripepayments\/stptokencompletionblock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTokenCompletionBlock","kind":"identifier"}]},"https://stripe.com/docs/api#create_bank_account_token":{"type":"link","identifier":"https:\/\/stripe.com\/docs\/api#create_bank_account_token","url":"https:\/\/stripe.com\/docs\/api#create_bank_account_token","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"title":"Stripe API reference"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"type":"topic","abstract":[{"type":"text","text":"Representation of a user’s bank account details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"title":"STPBankAccountParams","role":"symbol","navigatorTitle":[{"text":"STPBankAccountParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","url":"\/documentation\/stripepayments\/stpbankaccountparams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"url":"\/documentation\/stripepayments\/stripecore","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","role":"collection","type":"topic","abstract":[],"title":"StripeCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","op":"replace","value":"STPBankAccountParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","op":"replace","value":[{"text":"STPBankAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccountParams","kind":"identifier"}]}]}]}