{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSSNLast4"},{"kind":"text","text":" "},{"kind":"internalParam","text":"ssnLast4"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"ssnLast4","content":[{"type":"paragraph","inlineContent":[{"text":"The last 4 digits of the user’s SSN.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"A Stripe token."}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}],"name":"Throws","style":"note","type":"aside"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/api#create_pii_token","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"See Also","style":"note","type":"aside"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withSSNLast4:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"createToken(withSSNLast4:)","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE11createToken12withSSNLast4AD8STPTokenCSS_tYaKF","extendedModule":"StripeCore","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withSSNLast4","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","kind":"typeIdentifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"abstract":[{"text":"Converts the last 4 SSN digits into a Stripe token using the Stripe API.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withssnlast4:)"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","url":"\/documentation\/stripepayments\/stripecore","type":"topic","abstract":[],"role":"collection","title":"StripeCore","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"title":"STPAPIClient","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","kind":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stptoken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","navigatorTitle":[{"kind":"identifier","text":"STPToken"}],"title":"STPToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPToken"}],"abstract":[{"text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly.","type":"text"}]},"https://stripe.com/docs/api#create_pii_token":{"titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"title":"Stripe API reference","type":"link","identifier":"https:\/\/stripe.com\/docs\/api#create_pii_token","url":"https:\/\/stripe.com\/docs\/api#create_pii_token"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createToken(withSSNLast4:)":{"abstract":[{"text":"Converts the last 4 SSN digits into a Stripe token using the Stripe API.","type":"text"}],"title":"createToken(withSSNLast4:)","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withssnlast4:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withSSNLast4:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withSSNLast4","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPToken","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title"},{"value":[{"text":"STPToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments"},{"value":[{"text":"STPToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle"}]}]}