{"metadata":{"roleHeading":"Instance Method","externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createSourceWithParams:completion:","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"title":"createSource(with:completion:)","extendedModule":"StripeCore","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments24STPSourceCompletionBlocka","kind":"typeIdentifier","text":"STPSourceCompletionBlock"},{"kind":"text","text":")"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Creates a Source object using the provided details.","type":"text"},{"text":" ","type":"text"},{"text":"Note: in order to create a source on a connected account, you can set your","type":"text"},{"text":" ","type":"text"},{"text":"API client’s ","type":"text"},{"code":"stripeAccount","type":"codeVoice"},{"text":" property to the ID of the account.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createSourceWithParams:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceParams"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"preciseIdentifier":"s:14StripePayments24STPSourceCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCompletionBlock","kind":"typeIdentifier","text":"STPSourceCompletionBlock"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"sourceParams","content":[{"inlineContent":[{"type":"text","text":"The details of the source to create."}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The callback to run with the returned Source object, or an error."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"name":"See Also","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#create_source"}],"type":"paragraph"}]},{"name":"See Also","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges"}],"type":"paragraph"}]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createsource(with:completion:)-6w1jx"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createSource(with:completion:)-6w1jx","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"title":"StripeCore","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","abstract":[],"url":"\/documentation\/stripepayments\/stripecore","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","title":"STPAPIClient","role":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"type":"topic","kind":"symbol"},"https://stripe.com/docs/api#create_source":{"title":"Stripe API reference","url":"https:\/\/stripe.com\/docs\/api#create_source","identifier":"https:\/\/stripe.com\/docs\/api#create_source","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"type":"link"},"https://stripe.com/docs/sources/connect#creating-direct-charges":{"title":"Creating direct charges on connected accounts","url":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges","identifier":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges","titleInlineContent":[{"text":"Creating direct charges on connected accounts","type":"text"}],"type":"link"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCompletionBlock":{"url":"\/documentation\/stripepayments\/stpsourcecompletionblock","navigatorTitle":[{"text":"STPSourceCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCompletionBlock","title":"STPSourceCompletionBlock","role":"symbol","abstract":[{"type":"text","text":"A callback to be run with a source response from the Stripe API."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCompletionBlock","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"symbol","title":"STPSourceParams","url":"\/documentation\/stripepayments\/stpsourceparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createSource(with:completion:)-6w1jx":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createsource(with:completion:)-6w1jx","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createSource(with:completion:)-6w1jx","title":"createSource(with:completion:)","role":"symbol","abstract":[{"text":"Creates a Source object using the provided details.","type":"text"},{"text":" ","type":"text"},{"text":"Note: in order to create a source on a connected account, you can set your","type":"text"},{"text":" ","type":"text"},{"text":"API client’s ","type":"text"},{"code":"stripeAccount","type":"codeVoice"},{"text":" property to the ID of the account.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createSource"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"STPSourceCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments24STPSourceCompletionBlocka"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"text":"STPSourceParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}