{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createTokenWithConnectAccount:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConnectAccount"},{"kind":"text","text":" "},{"kind":"internalParam","text":"account"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","text":"STPConnectAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","text":"STPTokenCompletionBlock","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka"},{"kind":"text","text":"?)"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The Connect Account parameters. Cannot be nil.","type":"text"}]}],"name":"account"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The callback to run with the returned Stripe token (and any errors that may have occurred).","type":"text"}]}],"name":"completion"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Converts an "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":" object into a Stripe token using the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"This allows the connected account to accept the Terms of Service, and\/or send Legal Entity information."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withConnectAccount:completion:)"},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withconnectaccount:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConnectAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountParams","text":"STPConnectAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock"},{"kind":"text","text":"?)"}],"modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"roleHeading":"Instance Method","externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createTokenWithConnectAccount:completion:","role":"symbol","extendedModule":"StripeCore","title":"createToken(withConnectAccount:completion:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenCompletionBlock":{"navigatorTitle":[{"kind":"identifier","text":"STPTokenCompletionBlock"}],"abstract":[{"text":"A callback to be run with a token response from the Stripe API.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","url":"\/documentation\/stripepayments\/stptokencompletionblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTokenCompletionBlock"}],"title":"STPTokenCompletionBlock"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createToken(withConnectAccount:completion:)":{"abstract":[{"text":"Converts an ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":" object into a Stripe token using the Stripe API.","type":"text"},{"text":" ","type":"text"},{"text":"This allows the connected account to accept the Terms of Service, and\/or send Legal Entity information.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withConnectAccount:completion:)","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withconnectaccount:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConnectAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountParams","text":"STPConnectAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock"},{"kind":"text","text":"?)"}],"title":"createToken(withConnectAccount:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","abstract":[],"title":"StripeCore","url":"\/documentation\/stripepayments\/stripecore","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","kind":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"type":"topic","title":"STPAPIClient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","role":"symbol","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"identifier"}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams","kind":"symbol","abstract":[{"text":"Parameters for creating a Connect Account token.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConnectAccountParams"}],"navigatorTitle":[{"text":"STPConnectAccountParams","kind":"identifier"}],"type":"topic","title":"STPConnectAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPConnectAccountParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title"},{"value":[{"kind":"identifier","text":"STPConnectAccountParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments"},{"value":[{"kind":"identifier","text":"STPConnectAccountParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle"}]}]}