{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCard"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cardParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","text":"STPCardParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","text":"STPToken"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The user’s card details."}],"type":"paragraph"}],"name":"cardParams"}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"A Stripe token."}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","name":"Throws","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}]},{"type":"aside","name":"See Also","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#create_card_token","isActive":true}]}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withCard:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withcard:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"}],"externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE11createToken8withCardAD8STPTokenCAD13STPCardParamsC_tYaKF","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"roleHeading":"Instance Method","title":"createToken(withCard:)","symbolKind":"method","role":"symbol","extendedModule":"StripeCore"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"abstract":[{"text":"Converts an ","type":"text"},{"code":"STPCardParams","type":"codeVoice"},{"text":" object into a Stripe token using the Stripe API.","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","type":"topic","title":"StripeCore","url":"\/documentation\/stripepayments\/stripecore","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPToken","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPToken","kind":"identifier"}],"abstract":[{"text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","url":"\/documentation\/stripepayments\/stptoken","type":"topic","role":"symbol","title":"STPToken"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","kind":"symbol","title":"STPCardParams","type":"topic","url":"\/documentation\/stripepayments\/stpcardparams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardParams"}],"abstract":[{"text":"Representation of a user’s credit card details. You can assemble these with","type":"text"},{"text":" ","type":"text"},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"text":" ","type":"text"},{"text":"an STPAPIClient.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createToken(withCard:)":{"role":"symbol","kind":"symbol","title":"createToken(withCard:)","abstract":[{"text":"Converts an ","type":"text"},{"code":"STPCardParams","type":"codeVoice"},{"text":" object into a Stripe token using the Stripe API.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCard"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","kind":"typeIdentifier","text":"STPCardParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","kind":"typeIdentifier","text":"STPToken"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withcard:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withCard:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"https://stripe.com/docs/api#create_card_token":{"identifier":"https:\/\/stripe.com\/docs\/api#create_card_token","title":"Stripe API reference","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"type":"link","url":"https:\/\/stripe.com\/docs\/api#create_card_token"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"type":"topic","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"abstract":[{"type":"text","text":"STPAPIClient extensions for working with PaymentMethod objects."}],"title":"STPAPIClient","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title","op":"replace","value":"STPToken"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","op":"replace","value":[{"text":"STPToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle","op":"replace","value":[{"text":"STPToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title","op":"replace","value":"STPCardParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments","op":"replace","value":[{"text":"STPCardParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle","op":"replace","value":[{"text":"STPCardParams","kind":"identifier"}]}]}]}