{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBankAccount"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bankAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams","text":"STPBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","text":"STPToken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"bankAccount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user’s bank account details."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"A Stripe token.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}],"type":"aside","style":"note","name":"Throws"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"https:\/\/stripe.com\/docs\/api#create_bank_account_token","type":"reference"}]}],"type":"aside","style":"note","name":"See Also"}]}],"abstract":[{"type":"text","text":"Converts an "},{"type":"codeVoice","code":"STPBankAccount"},{"type":"text","text":" object into a Stripe token using the Stripe API."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withBankAccount:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withbankaccount:)"]}],"metadata":{"externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE11createToken15withBankAccountAD8STPTokenCAD07STPBankI6ParamsC_tYaKF","title":"createToken(withBankAccount:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBankAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams","text":"STPBankAccountParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","text":"STPToken"}],"modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"StripeCore"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createToken(withBankAccount:)":{"kind":"symbol","abstract":[{"text":"Converts an ","type":"text"},{"type":"codeVoice","code":"STPBankAccount"},{"text":" object into a Stripe token using the Stripe API.","type":"text"}],"title":"createToken(withBankAccount:)","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withbankaccount:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBankAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withBankAccount:)"},"https://stripe.com/docs/api#create_bank_account_token":{"identifier":"https:\/\/stripe.com\/docs\/api#create_bank_account_token","url":"https:\/\/stripe.com\/docs\/api#create_bank_account_token","title":"Stripe API reference","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"type":"link"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"url":"\/documentation\/stripepayments\/stptoken","kind":"symbol","title":"STPToken","role":"symbol","abstract":[{"type":"text","text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPToken","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","navigatorTitle":[{"text":"STPToken","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"abstract":[{"text":"Representation of a user’s bank account details. You can assemble these with","type":"text"},{"text":" ","type":"text"},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"text":" ","type":"text"},{"text":"an STPAPIClient.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPBankAccountParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountParams","kind":"identifier"}],"title":"STPBankAccountParams","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","url":"\/documentation\/stripepayments\/stpbankaccountparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"url":"\/documentation\/stripepayments\/stripecore","type":"topic","title":"StripeCore","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"kind":"symbol","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","role":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPToken","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title"},{"op":"replace","value":[{"text":"STPToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPToken"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle"},{"op":"replace","value":"STPBankAccountParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title"},{"op":"replace","value":[{"text":"STPBankAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPBankAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}