{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createRadarSession()","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"text":"Creates a Radar Session.","type":"text"}],"metadata":{"title":"createRadarSession()","roleHeading":"Instance Method","extendedModule":"StripeCore","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE18createRadarSessionAD08STPRadarG0CyYaKF","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createRadarSession","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPRadarSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"}],"modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createradarsession()"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createRadarSession"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","kind":"typeIdentifier","text":"STPRadarSession","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"STPRadarSession"},{"type":"text","text":" instance."}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"See https:\/\/stripe.com\/docs\/radar\/radar-session"}],"type":"paragraph"}],"name":"Note"},{"type":"aside","style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"StripeAPI.advancedFraudSignalsEnabled","type":"codeVoice"},{"text":" must be ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" to use this method.","type":"text"}],"type":"paragraph"}],"name":"Note"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"See ","type":"text"},{"code":"STPRadarSession","type":"codeVoice"}]}],"name":"Note"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"references":{"https://stripe.com/docs/radar/radar-session":{"url":"https:\/\/stripe.com\/docs\/radar\/radar-session","title":"Radar Session","titleInlineContent":[{"text":"Radar Session","type":"text"}],"type":"link","identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarSession":{"url":"\/documentation\/stripepayments\/stpradarsession","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","title":"STPRadarSession","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRadarSession","kind":"identifier"}],"navigatorTitle":[{"text":"STPRadarSession","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"url":"\/documentation\/stripepayments\/stripecore","abstract":[],"kind":"symbol","role":"collection","title":"StripeCore","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"kind":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"type":"topic","title":"STPAPIClient","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createRadarSession()":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createradarsession()","abstract":[{"type":"text","text":"Creates a Radar Session."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createRadarSession","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPRadarSession","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createRadarSession()","title":"createRadarSession()","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/title","value":"STPRadarSession"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/fragments","value":[{"text":"STPRadarSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/navigatorTitle","value":[{"text":"STPRadarSession","kind":"identifier"}]}]}]}