{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(createTokenWithCard:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withCard","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cardParams","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","text":"STPCardParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The user’s card details."}],"type":"paragraph"}],"name":"cardParams"},{"content":[{"inlineContent":[{"type":"text","text":"The callback to run with the returned Stripe token (and any errors that may have occurred)."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#create_card_token","isActive":true}],"type":"paragraph"}],"style":"note","name":"See Also"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withCard:completion:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Converts an STPCardParams object into a Stripe token using the Stripe API."}],"metadata":{"symbolKind":"method","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"roleHeading":"Instance Method","title":"createToken(withCard:completion:)","role":"symbol","extendedModule":"StripeCore","externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createTokenWithCard:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCard"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","kind":"typeIdentifier","text":"STPCardParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","kind":"typeIdentifier","text":"STPTokenCompletionBlock"},{"kind":"text","text":")"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withcard:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"url":"\/documentation\/stripepayments\/stripecore","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","role":"collection","type":"topic","abstract":[],"title":"StripeCore"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"title":"STPCardParams","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","navigatorTitle":[{"text":"STPCardParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of a user’s credit card details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"url":"\/documentation\/stripepayments\/stpcardparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","role":"symbol","type":"topic","abstract":[{"type":"text","text":"STPAPIClient extensions for working with PaymentMethod objects."}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createToken(withCard:completion:)":{"type":"topic","title":"createToken(withCard:completion:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createToken(withCard:completion:)","abstract":[{"type":"text","text":"Converts an STPCardParams object into a Stripe token using the Stripe API."}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createtoken(withcard:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","text":"STPCardParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"https://stripe.com/docs/api#create_card_token":{"titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"url":"https:\/\/stripe.com\/docs\/api#create_card_token","identifier":"https:\/\/stripe.com\/docs\/api#create_card_token","type":"link","title":"Stripe API reference"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenCompletionBlock":{"type":"topic","title":"STPTokenCompletionBlock","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","navigatorTitle":[{"text":"STPTokenCompletionBlock","kind":"identifier"}],"abstract":[{"type":"text","text":"A callback to be run with a token response from the Stripe API."}],"url":"\/documentation\/stripepayments\/stptokencompletionblock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTokenCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPCardParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title","op":"replace"},{"value":[{"text":"STPCardParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments","op":"replace"},{"value":[{"text":"STPCardParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle","op":"replace"}]}]}