{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createSource(with:)","interfaceLanguage":"swift"},"metadata":{"extendedModule":"StripeCore","role":"symbol","roleHeading":"Instance Method","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE12createSource4withAD9STPSourceCAD0H6ParamsC_tYaKF","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"title":"createSource(with:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource"}]},"abstract":[{"text":"Creates a Source object using the provided details.","type":"text"},{"text":" ","type":"text"},{"text":"Note: in order to create a source on a connected account, you can set your","type":"text"},{"text":" ","type":"text"},{"text":"API client’s ","type":"text"},{"code":"stripeAccount","type":"codeVoice"},{"text":" property to the ID of the account.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createsource(with:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sourceParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","text":"STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"sourceParams","content":[{"type":"paragraph","inlineContent":[{"text":"The details of the source to create.","type":"text"}]}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A Source object."}]}],"kind":"content"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"style":"note","name":"Throws","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}]},{"style":"note","name":"See Also","type":"aside","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/api#create_source","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"style":"note","name":"See Also","type":"aside","content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges"}],"type":"paragraph"}]}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createSource(with:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"Creates a Source object using the provided details."},{"type":"text","text":" "},{"type":"text","text":"Note: in order to create a source on a connected account, you can set your"},{"type":"text","text":" "},{"type":"text","text":"API client’s "},{"type":"codeVoice","code":"stripeAccount"},{"type":"text","text":" property to the ID of the account."}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createsource(with:)","kind":"symbol","title":"createSource(with:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createSource(with:)","type":"topic"},"https://stripe.com/docs/sources/connect#creating-direct-charges":{"title":"Creating direct charges on connected accounts","titleInlineContent":[{"type":"text","text":"Creating direct charges on connected accounts"}],"identifier":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges","url":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges","type":"link"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"type":"topic","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"abstract":[{"type":"text","text":"STPAPIClient extensions for working with PaymentMethod objects."}],"title":"STPAPIClient","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","type":"topic","title":"StripeCore","url":"\/documentation\/stripepayments\/stripecore","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"title":"STPSource","url":"\/documentation\/stripepayments\/stpsource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSource"}],"navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"https://stripe.com/docs/api#create_source":{"title":"Stripe API reference","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"identifier":"https:\/\/stripe.com\/docs\/api#create_source","url":"https:\/\/stripe.com\/docs\/api#create_source","type":"link"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"symbol","abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceparams","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"title":"STPSourceParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceParams"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","op":"replace","value":"STPSource"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","op":"replace","value":[{"text":"STPSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","op":"replace","value":[{"text":"STPSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","op":"replace","value":"STPSourceParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}