{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/createpaymentmethod(with:completion:)-1svpk"]}],"metadata":{"externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createPaymentMethodWithParams:completion:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCompletionBlock","preciseIdentifier":"s:14StripePayments31STPPaymentMethodCompletionBlocka"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"createPaymentMethod(with:completion:)","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"role":"symbol","extendedModule":"StripeCore"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createPaymentMethod(with:completion:)-1svpk"},"abstract":[{"text":"Creates a PaymentMethod object with the provided params object.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createPaymentMethodWithParams:completion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethodParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","text":"STPPaymentMethodParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments31STPPaymentMethodCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCompletionBlock","text":"STPPaymentMethodCompletionBlock"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":" to pass to ","type":"text"},{"type":"codeVoice","code":"\/v1\/payment_methods"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"paymentMethodParams"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback to run with the returned PaymentMethod object, or an error."}]}],"name":"completion"}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"style":"note","type":"aside","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create","type":"reference"}]}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"abstract":[{"type":"text","text":"STPAPIClient extensions for working with PaymentMethod objects."}],"fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient"}],"title":"STPAPIClient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient"},"https://stripe.com/docs/api/payment_methods/create":{"title":"Stripe API reference","url":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create","type":"link","identifier":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create","titleInlineContent":[{"type":"text","text":"Stripe API reference"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCompletionBlock":{"navigatorTitle":[{"text":"STPPaymentMethodCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCompletionBlock","url":"\/documentation\/stripepayments\/stppaymentmethodcompletionblock","abstract":[{"type":"text","text":"A callback to be run with a PaymentMethod response from the Stripe API."}],"role":"symbol","kind":"symbol","type":"topic","title":"STPPaymentMethodCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/createPaymentMethod(with:completion:)-1svpk":{"title":"createPaymentMethod(with:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCompletionBlock","preciseIdentifier":"s:14StripePayments31STPPaymentMethodCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/createPaymentMethod(with:completion:)-1svpk","abstract":[{"text":"Creates a PaymentMethod object with the provided params object.","type":"text"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/createpaymentmethod(with:completion:)-1svpk","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","type":"topic","title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"role":"collection","abstract":[],"url":"\/documentation\/stripepayments\/stripecore","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","title":"StripeCore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"}]}]}