{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withId"},{"kind":"text","text":" "},{"kind":"internalParam","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":" "},{"kind":"internalParam","text":"secret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","kind":"typeIdentifier","text":"STPSource","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"}]}],"kind":"declarations"},{"parameters":[{"name":"identifier","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier of the source to be retrieved."}]}]},{"name":"secret","content":[{"inlineContent":[{"type":"text","text":"The client secret of the source."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A Source object."}],"type":"paragraph"}],"kind":"content"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}],"type":"paragraph"}],"name":"Throws","style":"note"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#retrieve_source","isActive":true}],"type":"paragraph"}],"name":"See Also","style":"note"}],"kind":"content"}],"kind":"symbol","abstract":[{"type":"text","text":"Retrieves the Source object with the given ID."}],"sections":[],"metadata":{"extendedModule":"StripeCore","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE14retrieveSource6withId12clientSecretAD9STPSourceCSS_SStYaKF","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","kind":"typeIdentifier"}],"title":"retrieveSource(withId:clientSecret:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/retrievesource(withid:clientsecret:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/retrieveSource(withId:clientSecret:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"kind":"symbol","abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"navigatorTitle":[{"text":"STPSource","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsource","title":"STPSource","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}]},"https://stripe.com/docs/api#retrieve_source":{"type":"link","identifier":"https:\/\/stripe.com\/docs\/api#retrieve_source","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"url":"https:\/\/stripe.com\/docs\/api#retrieve_source","title":"Stripe API reference"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"type":"topic","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"title":"STPAPIClient","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/retrieveSource(withId:clientSecret:)":{"kind":"symbol","title":"retrieveSource(withId:clientSecret:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/retrieveSource(withId:clientSecret:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/retrievesource(withid:clientsecret:)","abstract":[{"type":"text","text":"Retrieves the Source object with the given ID."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"url":"\/documentation\/stripepayments\/stripecore","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","type":"topic","title":"StripeCore","abstract":[],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","op":"replace","value":"STPSource"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","op":"replace","value":[{"text":"STPSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","op":"replace","value":[{"text":"STPSource","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}