{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/retrievepaymentintent(withclientsecret:expand:)"]}],"abstract":[{"text":"Retrieves the PaymentIntent object using the given secret.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/retrievePaymentIntent(withClientSecret:expand:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrievePaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withClientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"}],"title":"retrievePaymentIntent(withClientSecret:expand:)","roleHeading":"Instance Method","extendedModule":"StripeCore","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE21retrievePaymentIntent16withClientSecret6expandAD010STPPaymentG0CSS_SaySSGSgtYaKF","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrievePaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withClientSecret"},{"kind":"text","text":" "},{"kind":"internalParam","text":"secret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]? = nil) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"secret","content":[{"inlineContent":[{"type":"text","text":"The client secret of the payment intent to be retrieved."}],"type":"paragraph"}]},{"name":"expand","content":[{"inlineContent":[{"text":"An array of string keys to expand on the returned PaymentIntent object. These strings should match one or more of the parameter names that are marked as expandable.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A PaymentIntent object.","type":"text"}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"The error that occurred making the Stripe API request.","type":"text"}]}],"style":"note"},{"type":"aside","name":"See Also","content":[{"inlineContent":[{"type":"text","text":"[Stripe API reference](https:\/\/stripe.com\/docs\/api#retrieve_payment_intent]"}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"abstract":[],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","kind":"symbol","url":"\/documentation\/stripepayments\/stripecore","title":"StripeCore","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintent","navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"title":"STPPaymentIntent","role":"symbol","abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/retrievePaymentIntent(withClientSecret:expand:)":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/retrievepaymentintent(withclientsecret:expand:)","title":"retrievePaymentIntent(withClientSecret:expand:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrievePaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withClientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent"}],"kind":"symbol","abstract":[{"type":"text","text":"Retrieves the PaymentIntent object using the given secret."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/retrievePaymentIntent(withClientSecret:expand:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"abstract":[{"type":"text","text":"STPAPIClient extensions for working with PaymentMethod objects."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","kind":"symbol","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"title":"STPAPIClient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","value":[{"text":"STPPaymentIntent","kind":"identifier"}]}]}]}