{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withClientSecret","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"secret","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]? = nil) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"typeIdentifier"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The client secret of the SetupIntent to be retrieved.","type":"text"}],"type":"paragraph"}],"name":"secret"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An array of string keys to expand on the returned SetupIntent object. These strings should match one or more of the parameter names that are marked as expandable.","type":"text"}]}],"name":"expand"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A SetupIntent object."}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}],"type":"aside","style":"note","name":"Throws"},{"content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/retrieve","type":"reference","isActive":true}],"type":"paragraph"}],"type":"aside","style":"note","name":"See Also"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","isActive":true,"type":"reference"}],"type":"paragraph"}],"type":"aside","style":"note","name":"See Also"}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/retrievesetupintent(withclientsecret:expand:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/retrieveSetupIntent(withClientSecret:expand:)","interfaceLanguage":"swift"},"metadata":{"title":"retrieveSetupIntent(withClientSecret:expand:)","role":"symbol","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"extendedModule":"StripeCore","roleHeading":"Instance Method","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE19retrieveSetupIntent16withClientSecret6expandAD08STPSetupG0CSS_SaySSGSgtYaKF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withClientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"}],"symbolKind":"method"},"abstract":[{"text":"Retrieves the SetupIntent object using the given secret.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","url":"\/documentation\/stripepayments\/stripecore","type":"topic","abstract":[],"role":"collection","title":"StripeCore","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"title":"STPAPIClient","fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","kind":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient"},"https://stripe.com/docs/api/setup_intents/retrieve":{"url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/retrieve","type":"link","title":"Stripe API reference","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/retrieve"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/retrieveSetupIntent(withClientSecret:expand:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/retrieveSetupIntent(withClientSecret:expand:)","abstract":[{"type":"text","text":"Retrieves the SetupIntent object using the given secret."}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/retrievesetupintent(withclientsecret:expand:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withClientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPSetupIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","kind":"typeIdentifier"}],"kind":"symbol","title":"retrieveSetupIntent(withClientSecret:expand:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"title":"STPSetupIntent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"type":"topic","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"url":"\/documentation\/stripepayments\/stpsetupintent","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"}]},"https://stripe.com/docs/api/setup_intents/object":{"url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","type":"link","title":"Stripe API reference","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object"}},"variantOverrides":[{"patch":[{"value":"STPSetupIntent","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}