{"metadata":{"role":"symbol","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE19updatePaymentMethod4with07paymentG12UpdateParams18ephemeralKeySecret10completionySS_AD010STPPaymentgjK0CSSyAD0pG0CSg_s5Error_pSgtctF","extendedModule":"StripeCore","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"roleHeading":"Instance Method","title":"updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:completion:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodUpdateParams"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams","kind":"typeIdentifier","text":"STPPaymentMethodUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ephemeralKeySecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments31STPPaymentMethodCompletionBlocka","kind":"typeIdentifier","text":"STPPaymentMethodCompletionBlock"},{"kind":"text","text":")"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:completion:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updatePaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethodId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentMethodUpdateParams","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams","kind":"typeIdentifier","text":"STPPaymentMethodUpdateParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ephemeralKeySecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCompletionBlock","preciseIdentifier":"s:14StripePayments31STPPaymentMethodCompletionBlocka","text":"STPPaymentMethodCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"paymentMethodId","content":[{"inlineContent":[{"text":"Identifier of the payment method to be updated","type":"text"}],"type":"paragraph"}]},{"name":"paymentMethodUpdateParams","content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"STPPaymentMethodUpdateParams","type":"codeVoice"},{"text":" to pass to ","type":"text"},{"code":"\/v1\/payment_methods\/update","type":"codeVoice"},{"text":".  Cannot be nil.","type":"text"}],"type":"paragraph"}]},{"name":"ephemeralKeySecret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Customer Ephemeral Key secret to be used"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The callback to run with the returned "},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" object, or an error."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"style":"note","name":"See Also","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Update","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/updatepaymentmethod(with:paymentmethodupdateparams:ephemeralkeysecret:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Updates a PaymentMethod object with the provided params object."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams":{"abstract":[{"type":"text","text":"An object representing parameters used to update a PaymentMethod object."}],"url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams","role":"symbol","type":"topic","navigatorTitle":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"kind":"symbol","title":"STPPaymentMethodUpdateParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:completion:)":{"abstract":[{"text":"Updates a PaymentMethod object with the provided params object.","type":"text"}],"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/updatepaymentmethod(with:paymentmethodupdateparams:ephemeralkeysecret:completion:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:completion:)","role":"symbol","title":"updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updatePaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"paymentMethodUpdateParams","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUpdateParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams"},{"text":", ","kind":"text"},{"text":"ephemeralKeySecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments31STPPaymentMethodCompletionBlocka"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCompletionBlock":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCompletionBlock"}],"abstract":[{"text":"A callback to be run with a PaymentMethod response from the Stripe API.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethodCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCompletionBlock","url":"\/documentation\/stripepayments\/stppaymentmethodcompletionblock","title":"STPPaymentMethodCompletionBlock"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","type":"topic","role":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"role":"collection","type":"topic","url":"\/documentation\/stripepayments\/stripecore","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","kind":"symbol","abstract":[],"title":"StripeCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentMethodUpdateParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}]}]}]}