{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"sections":[],"abstract":[{"text":"Updates a PaymentMethod object with the provided params object.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/updatepaymentmethod(with:paymentmethodupdateparams:ephemeralkeysecret:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updatePaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"paymentMethodId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentMethodUpdateParams","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams","text":"STPPaymentMethodUpdateParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams"},{"text":", ","kind":"text"},{"text":"ephemeralKeySecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Identifier of the payment method to be updated"}],"type":"paragraph"}],"name":"paymentMethodId"},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPPaymentMethodUpdateParams"},{"type":"text","text":" to pass to "},{"type":"codeVoice","code":"\/v1\/payment_methods\/update"},{"type":"text","text":".  Cannot be nil."}],"type":"paragraph"}],"name":"paymentMethodUpdateParams"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The Customer Ephemeral Key secret to be used","type":"text"}]}],"name":"ephemeralKeySecret"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns the updated "},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" or throws an error if the operation failed."}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"name":"See Also","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Update"}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)","interfaceLanguage":"swift"},"metadata":{"title":"updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)","roleHeading":"Instance Method","role":"symbol","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE19updatePaymentMethod4with07paymentG12UpdateParams18ephemeralKeySecretAD010STPPaymentG0CSS_AD0ogjK0CSStYaKF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodUpdateParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams","text":"STPPaymentMethodUpdateParams"},{"text":", ","kind":"text"},{"text":"ephemeralKeySecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"}],"extendedModule":"StripeCore","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"symbolKind":"method"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"kind":"symbol","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","role":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"fragments":[{"text":"extension","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"url":"\/documentation\/stripepayments\/stripecore","type":"topic","title":"StripeCore","kind":"symbol","abstract":[],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams":{"navigatorTitle":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to update a PaymentMethod object.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"type":"topic","title":"STPPaymentMethodUpdateParams","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)":{"title":"updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)","abstract":[{"type":"text","text":"Updates a PaymentMethod object with the provided params object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/updatepaymentmethod(with:paymentmethodupdateparams:ephemeralkeysecret:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"paymentMethodUpdateParams","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams","text":"STPPaymentMethodUpdateParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ephemeralKeySecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"title":"STPPaymentMethod","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/title","value":"STPPaymentMethodUpdateParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUpdateParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodUpdateParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"op":"replace"}]}]}