{"metadata":{"roleHeading":"Instance Method","title":"verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)","extendedModule":"StripeCore","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE36verifyPaymentIntentWithMicrodeposits12clientSecret14descriptorCodeAD010STPPaymentG0CSS_SStYaKF","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyPaymentIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"descriptorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"abstract":[{"type":"text","text":"Verify a customer’s bank account with micro-deposits"},{"type":"text","text":" "},{"type":"text","text":"This function should only be called when the PaymentIntent is in the "},{"type":"codeVoice","code":"requires_action"},{"type":"text","text":" "},{"type":"text","text":"state and "},{"type":"codeVoice","code":"next_action.type"},{"type":"text","text":" equals "},{"type":"codeVoice","code":"verify_with_microdeposits"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyPaymentIntentWithMicrodeposits"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"descriptorCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"type":"text","text":"The client secret of the PaymentIntent."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A unique, 6-digit descriptor code that starts with SM that was sent as statement descriptor to the bank account.","type":"text"}],"type":"paragraph"}],"name":"descriptorCode"}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"The verified PaymentIntent object.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"name":"Throws","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}],"type":"paragraph"}]}],"kind":"content"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/verifypaymentintentwithmicrodeposits(clientsecret:descriptorcode:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","title":"STPAPIClient","role":"symbol","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"fragments":[{"kind":"keyword","text":"extension"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"type":"topic","title":"STPPaymentIntent","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntent"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/verifypaymentintentwithmicrodeposits(clientsecret:descriptorcode:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)","title":"verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Verify a customer’s bank account with micro-deposits"},{"type":"text","text":" "},{"type":"text","text":"This function should only be called when the PaymentIntent is in the "},{"type":"codeVoice","code":"requires_action"},{"type":"text","text":" "},{"type":"text","text":"state and "},{"type":"codeVoice","code":"next_action.type"},{"type":"text","text":" equals "},{"type":"codeVoice","code":"verify_with_microdeposits"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyPaymentIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"descriptorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"title":"StripeCore","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","abstract":[],"url":"\/documentation\/stripepayments\/stripecore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","op":"replace","value":"STPPaymentIntent"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","op":"replace","value":[{"text":"STPPaymentIntent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}