{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient"]]},"sections":[],"abstract":[{"type":"text","text":"Verify a customer’s bank account with micro-deposits"},{"type":"text","text":" "},{"type":"text","text":"This function should only be called when the SetupIntent is in the "},{"code":"requires_action","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"state and "},{"code":"next_action.type","type":"codeVoice"},{"type":"text","text":" equals "},{"code":"verify_with_microdeposits","type":"codeVoice"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifySetupIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"firstAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secondAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"type":"text","text":"The client secret of the SetupIntent."}],"type":"paragraph"}]},{"name":"firstAmount","content":[{"inlineContent":[{"text":"The amount, in cents of USD, equal to the value of the first micro-deposit sent to the bank account.","type":"text"}],"type":"paragraph"}]},{"name":"secondAmount","content":[{"inlineContent":[{"text":"The amount, in cents of USD, equal to the value of the second micro-deposit sent to the bank account.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The verified SetupIntent object."}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"style":"note","type":"aside","content":[{"inlineContent":[{"text":"The error that occurred making the Stripe API request.","type":"text"}],"type":"paragraph"}],"name":"Throws"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/verifySetupIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)"},"metadata":{"role":"symbol","roleHeading":"Instance Method","title":"verifySetupIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE34verifySetupIntentWithMicrodeposits12clientSecret11firstAmount06secondM0AD08STPSetupG0CSS_S2itYaKF","extendedModule":"StripeCore","symbolKind":"method","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifySetupIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"firstAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secondAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent","kind":"typeIdentifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stripecore\/stpapiclient\/verifysetupintentwithmicrodeposits(clientsecret:firstamount:secondamount:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"}],"kind":"symbol","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","url":"\/documentation\/stripepayments\/stpsetupintent","title":"STPSetupIntent","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient/verifySetupIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)":{"url":"\/documentation\/stripepayments\/stripecore\/stpapiclient\/verifysetupintentwithmicrodeposits(clientsecret:firstamount:secondamount:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient\/verifySetupIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifySetupIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"firstAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"secondAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"}],"abstract":[{"text":"Verify a customer’s bank account with micro-deposits","type":"text"},{"text":" ","type":"text"},{"text":"This function should only be called when the SetupIntent is in the ","type":"text"},{"code":"requires_action","type":"codeVoice"},{"text":" ","type":"text"},{"text":"state and ","type":"text"},{"code":"next_action.type","type":"codeVoice"},{"text":" equals ","type":"text"},{"code":"verify_with_microdeposits","type":"codeVoice"}],"role":"symbol","kind":"symbol","title":"verifySetupIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore","type":"topic","abstract":[],"role":"collection","url":"\/documentation\/stripepayments\/stripecore","kind":"symbol","title":"StripeCore"},"doc://com.stripe.stripe-payments/documentation/StripePayments/StripeCore/STPAPIClient":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"type":"topic","abstract":[{"text":"STPAPIClient extensions for working with PaymentMethod objects.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"extension"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/StripeCore\/STPAPIClient","url":"\/documentation\/stripepayments\/stripecore\/stpapiclient","title":"STPAPIClient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","value":[{"text":"STPSetupIntent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntent"}]}]}]}