{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountaddress\/init"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress"]]},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"init","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress(im)init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress":{"abstract":[{"type":"text","text":"An address to use with "},{"code":"STPConnectAccountParams","type":"codeVoice"},{"type":"text","text":"."}],"title":"STPConnectAccountAddress","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountaddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountAddress"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountAddress"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/init":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/init","type":"topic","title":"init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/title","value":"STPConnectAccountAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountAddress"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPConnectAccountAddress"}],"op":"replace"}]}]}