{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/postalCode"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"postalCode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postalCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress(py)postalCode","navigatorTitle":[{"text":"postalCode","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postalCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountaddress\/postalcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountaddress\/postalcode"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"ZIP or postal code."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress":{"type":"topic","abstract":[{"text":"An address to use with ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/stripepayments\/stpconnectaccountaddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountAddress","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountAddress"}],"role":"symbol","title":"STPConnectAccountAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/postalCode":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalCode"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/postalcode","abstract":[{"type":"text","text":"ZIP or postal code."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/postalCode","title":"postalCode","navigatorTitle":[{"kind":"identifier","text":"postalCode"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"postalCode","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"postalCode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"postalCode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPConnectAccountAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/navigatorTitle"},{"op":"replace","value":"postalCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1postalCode\/title"},{"op":"replace","value":[{"text":"postalCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1postalCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}