{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"becomeFirstResponder"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"]]},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"becomeFirstResponder","kind":"identifier"}],"modules":[{"name":"StripePaymentsUI"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"becomeFirstResponder"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField(im)becomeFirstResponder","title":"becomeFirstResponder()"},"sections":[],"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/becomeFirstResponder()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/becomefirstresponder()"]},{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/becomefirstresponder()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/becomeFirstResponder()":{"title":"becomeFirstResponder()","kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/becomefirstresponder()","navigatorTitle":[{"text":"becomeFirstResponder","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/becomeFirstResponder()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"becomeFirstResponder","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"url":"\/documentation\/stripepaymentsui","role":"collection","type":"topic","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPMultiFormTextField","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPMultiFormTextField","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield","kind":"symbol","title":"STPMultiFormTextField","abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"becomeFirstResponder","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"becomeFirstResponder","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"becomeFirstResponder"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"becomeFirstResponder","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1becomeFirstResponder()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"becomeFirstResponder"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1becomeFirstResponder()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPMultiFormTextField"}]},{"value":[{"text":"STPMultiFormTextField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle"}]}]}