{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/focusNextForm()","interfaceLanguage":"swift"},"abstract":[{"text":"Calling this method will make the next incomplete STPFormTextField in ","type":"text"},{"code":"formTextFields","type":"codeVoice"},{"text":" become the first responder.","type":"text"},{"text":" ","type":"text"},{"text":"If all of the form text fields are already complete, then the last field in ","type":"text"},{"code":"formTextFields","type":"codeVoice"},{"text":" will become the first responder.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focusNextForm","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"focusNextForm","kind":"identifier"}],"role":"symbol","title":"focusNextForm()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"focusNextForm","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField(im)focusNextForm","symbolKind":"method"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/focusnextform()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/focusnextform()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"role":"collection","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/focusNextForm()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"focusNextForm"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Calling this method will make the next incomplete STPFormTextField in "},{"code":"formTextFields","type":"codeVoice"},{"type":"text","text":" become the first responder."},{"type":"text","text":" "},{"type":"text","text":"If all of the form text fields are already complete, then the last field in "},{"code":"formTextFields","type":"codeVoice"},{"type":"text","text":" will become the first responder."}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/focusnextform()","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/focusNextForm()","title":"focusNextForm()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"focusNextForm"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMultiFormTextField","kind":"identifier"}],"navigatorTitle":[{"text":"STPMultiFormTextField","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield","role":"symbol","title":"STPMultiFormTextField"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"focusNextForm","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"focusNextForm"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"focusNextForm","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1focusNextForm()\/title","value":"focusNextForm","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1focusNextForm()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"focusNextForm","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","value":[{"text":"STPMultiFormTextField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle","value":[{"text":"STPMultiFormTextField","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}