{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formFont"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formFont","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formfont"]},{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formfont"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"formFont","kind":"identifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField(py)formFont","title":"formFont","modules":[{"name":"StripePaymentsUI"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"formFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"The font used in each child field. Default is "},{"code":".body","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/formFont":{"navigatorTitle":[{"text":"formFont","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formFont","title":"formFont","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formfont","kind":"symbol","abstract":[{"type":"text","text":"The font used in each child field. Default is "},{"code":".body","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formFont","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","kind":"symbol","type":"topic","title":"STPMultiFormTextField","navigatorTitle":[{"text":"STPMultiFormTextField","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPMultiFormTextField","kind":"identifier"}],"abstract":[{"text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"role":"collection","url":"\/documentation\/stripepaymentsui","title":"StripePaymentsUI"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"formFont","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"formFont","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"formFont"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"formFont","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formFont\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formFont\/fragments","op":"replace","value":[{"text":"formFont","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField"},{"op":"replace","value":[{"text":"STPMultiFormTextField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments"},{"value":[{"kind":"identifier","text":"STPMultiFormTextField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}