{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/initWithCoder:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"StripePaymentsUI"}],"symbolKind":"method","title":"initWithCoder:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField(im)initWithCoder:","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/initWithCoder:":{"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/initwithcoder:","abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"title":"initWithCoder:","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPMultiFormTextField","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield","kind":"symbol","abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"role":"symbol","title":"STPMultiFormTextField","navigatorTitle":[{"kind":"identifier","text":"STPMultiFormTextField"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"STPMultiFormTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","op":"replace"},{"value":[{"text":"STPMultiFormTextField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments"},{"value":[{"kind":"identifier","text":"STPMultiFormTextField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}