{"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/isfirstresponder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/isfirstresponder"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":":nodoc:","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/isFirstResponder","interfaceLanguage":"swift"},"sections":[],"metadata":{"navigatorTitle":[{"text":"isFirstResponder","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFirstResponder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"property","externalID":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField(py)isFirstResponder","title":"isFirstResponder","modules":[{"name":"StripePaymentsUI"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFirstResponder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"]]},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui","kind":"symbol","role":"collection","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/isFirstResponder":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/isFirstResponder","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/isfirstresponder","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFirstResponder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","title":"isFirstResponder","abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"text":"isFirstResponder","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"role":"symbol","navigatorTitle":[{"text":"STPMultiFormTextField","kind":"identifier"}],"abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMultiFormTextField","kind":"identifier"}],"title":"STPMultiFormTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isFirstResponder"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isFirstResponder","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFirstResponder"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1isFirstResponder\/title","op":"replace","value":"isFirstResponder"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1isFirstResponder\/fragments","op":"replace","value":[{"text":"isFirstResponder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","op":"replace","value":"STPMultiFormTextField"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPMultiFormTextField"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle","op":"replace","value":[{"text":"STPMultiFormTextField","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}