{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupError\/paymentMethod"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupError"]]},"abstract":[{"type":"text","text":"The PaymentMethod object for errors returned on a request involving a PaymentMethod."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperror\/paymentmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperror\/paymentmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentLastSetupError(py)paymentMethod","title":"paymentMethod","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"paymentMethod"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":"? { get }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupError":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupError","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperror","abstract":[{"text":"A value for ","type":"text"},{"code":"code","type":"codeVoice"},{"text":" indicating the provided payment method failed authentication.\/\/\/ The error encountered in the previous SetupIntent confirmation.","type":"text"}],"title":"STPSetupIntentLastSetupError","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupError"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentLastSetupError"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupError/paymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupError\/paymentMethod","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperror\/paymentmethod","abstract":[{"type":"text","text":"The PaymentMethod object for errors returned on a request involving a PaymentMethod."}],"title":"paymentMethod","navigatorTitle":[{"kind":"identifier","text":"paymentMethod"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","role":"symbol","title":"STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"url":"\/documentation\/stripepayments\/stppaymentmethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"paymentMethod","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"paymentMethod","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"paymentMethod","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSetupIntentLastSetupError","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupError\/title","op":"replace"},{"value":[{"text":"STPSetupIntentLastSetupError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupError\/fragments","op":"replace"},{"value":[{"text":"STPSetupIntentLastSetupError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupError\/navigatorTitle","op":"replace"},{"value":"paymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupError~1paymentMethod\/title","op":"replace"},{"value":[{"text":"paymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupError~1paymentMethod\/fragments","op":"replace"},{"value":"STPPaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","op":"replace"},{"value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}