{"kind":"symbol","sections":[],"abstract":[{"text":"The API Client to use to make requests.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to STPAPIClient.shared"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/apiClient","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"apiClient","externalID":"s:6Stripe23STPPinManagementServiceC9apiClient0A4Core12STPAPIClientCvp","platforms":[],"roleHeading":"Instance Property","modules":[{"name":"Stripe"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAPIClient","kind":"typeIdentifier"}]}]}],"variants":[{"paths":["\/documentation\/stripe\/stppinmanagementservice\/apiclient"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService/apiClient":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/apiClient","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient","kind":"typeIdentifier"}],"deprecated":true,"title":"apiClient","role":"symbol","kind":"symbol","url":"\/documentation\/stripe\/stppinmanagementservice\/apiclient","abstract":[{"text":"The API Client to use to make requests.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to STPAPIClient.shared","type":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAPIClient":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAPIClient","title":"STPAPIClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient"}],"url":"\/documentation\/stripe\/stpapiclient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService":{"type":"topic","url":"\/documentation\/stripe\/stppinmanagementservice","deprecated":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPinManagementService"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService","navigatorTitle":[{"kind":"identifier","text":"STPPinManagementService"}],"title":"STPPinManagementService","abstract":[{"type":"text","text":"STPAPIClient extensions to manage PIN on Stripe Issuing cards"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","role":"collection","title":"Stripe","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/title","op":"replace","value":"STPPinManagementService"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/fragments","value":[{"kind":"identifier","text":"STPPinManagementService"}]},{"value":[{"text":"STPPinManagementService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}