{"abstract":[{"type":"text","text":"Create a STPPinManagementService, you must provide an implementation of STPIssuingCardEphemeralKeyProvider"}],"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPPinManagementService(im)initWithKeyProvider:","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPIssuingCardEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","platforms":[],"title":"init(keyProvider:)","navigatorTitle":[{"kind":"identifier","text":"initWithKeyProvider:"}],"modules":[{"name":"Stripe"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/init(keyProvider:)","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripe\/stppinmanagementservice\/init(keyprovider:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppinmanagementservice\/init(keyprovider:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService":{"abstract":[{"text":"STPAPIClient extensions to manage PIN on Stripe Issuing cards","type":"text"}],"type":"topic","deprecated":true,"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService","navigatorTitle":[{"text":"STPPinManagementService","kind":"identifier"}],"title":"STPPinManagementService","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPinManagementService"}],"url":"\/documentation\/stripe\/stppinmanagementservice"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService/init(keyProvider:)":{"role":"symbol","abstract":[{"type":"text","text":"Create a STPPinManagementService, you must provide an implementation of STPIssuingCardEphemeralKeyProvider"}],"deprecated":true,"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"keyProvider","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stppinmanagementservice\/init(keyprovider:)","navigatorTitle":[{"text":"initWithKeyProvider:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/init(keyProvider:)","kind":"symbol","type":"topic","title":"init(keyProvider:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPIssuingCardEphemeralKeyProvider":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"}],"abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"type":"text","text":" "},{"type":"text","text":"It provides a way for Stripe utility classes to request a new ephemeral key from"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"title":"STPIssuingCardEphemeralKeyProvider","role":"symbol","url":"\/documentation\/stripe\/stpissuingcardephemeralkeyprovider","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","url":"\/documentation\/stripe","title":"Stripe","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithKeyProvider:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithKeyProvider:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithKeyProvider:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider","text":"id<STPIssuingCardEphemeralKeyProvider>"},{"text":") ","kind":"text"},{"text":"keyProvider","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/title","value":"STPPinManagementService","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/fragments","value":[{"text":"STPPinManagementService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/navigatorTitle","value":[{"text":"STPPinManagementService","kind":"identifier"}],"op":"replace"},{"value":"initWithKeyProvider:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1init(keyProvider:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithKeyProvider:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1init(keyProvider:)\/fragments"},{"op":"replace","value":"STPIssuingCardEphemeralKeyProvider","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/title"},{"value":[{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/fragments"},{"value":[{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/navigatorTitle","op":"replace"}]}]}