{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrievePin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cardId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"verificationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oneTimeCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"STPPinCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments21STPPinCompletionBlocka"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"text":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements","type":"text"}],"type":"paragraph"}],"variants":[{"paths":["\/documentation\/stripe\/stppinmanagementservice\/retrievepin(_:verificationid:onetimecode:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppinmanagementservice\/retrievepin(_:verificationid:onetimecode:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService"]]},"metadata":{"modules":[{"name":"Stripe"}],"symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPPinManagementService(im)retrievePin:verificationId:oneTimeCode:completion:","roleHeading":"Instance Method","platforms":[{"deprecatedAt":"100000.0","message":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"deprecatedAt":"100000.0","message":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"deprecatedAt":"100000.0","message":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrievePin","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"verificationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"oneTimeCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments21STPPinCompletionBlocka","text":"STPPinCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"retrievePin:verificationId:oneTimeCode:completion:","kind":"identifier"}],"role":"symbol","title":"retrievePin(_:verificationId:oneTimeCode:completion:)"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/retrievePin(_:verificationId:oneTimeCode:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Retrieves a PIN number for a given card,"},{"type":"text","text":" "},{"type":"text","text":"this call is asynchronous, implement the completion block to receive the updates"}],"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService":{"url":"\/documentation\/stripe\/stppinmanagementservice","navigatorTitle":[{"kind":"identifier","text":"STPPinManagementService"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService","abstract":[{"type":"text","text":"STPAPIClient extensions to manage PIN on Stripe Issuing cards"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPinManagementService"}],"title":"STPPinManagementService","type":"topic","role":"symbol","deprecated":true,"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService/retrievePin(_:verificationId:oneTimeCode:completion:)":{"deprecated":true,"title":"retrievePin(_:verificationId:oneTimeCode:completion:)","navigatorTitle":[{"text":"retrievePin:verificationId:oneTimeCode:completion:","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Retrieves a PIN number for a given card,","type":"text"},{"text":" ","type":"text"},{"text":"this call is asynchronous, implement the completion block to receive the updates","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/retrievePin(_:verificationId:oneTimeCode:completion:)","url":"\/documentation\/stripe\/stppinmanagementservice\/retrievepin(_:verificationid:onetimecode:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrievePin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"verificationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"oneTimeCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPinCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments21STPPinCompletionBlocka"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS"},{"deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"retrievePin:verificationId:oneTimeCode:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrievePin:verificationId:oneTimeCode:completion:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"retrievePin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cardId"},{"kind":"text","text":" "},{"kind":"identifier","text":"verificationId:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"verificationId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"oneTimeCode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"oneTimeCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"STPIssuingCardPin","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIssuingCardPin"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPinStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPinStatus"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements"}]}],"path":"\/deprecationSummary","op":"replace"},{"value":"STPPinManagementService","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/title","op":"replace"},{"value":[{"text":"STPPinManagementService","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPinManagementService"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/navigatorTitle","op":"replace"},{"value":"retrievePin:verificationId:oneTimeCode:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1retrievePin(_:verificationId:oneTimeCode:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"retrievePin:verificationId:oneTimeCode:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1retrievePin(_:verificationId:oneTimeCode:completion:)\/fragments","op":"replace"}]}]}