{"abstract":[{"type":"text","text":"Updates a PIN number for a given card,"},{"type":"text","text":" "},{"type":"text","text":"this call is asynchronous, implement the completion block to receive the updates"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppinmanagementservice\/updatepin(_:newpin:verificationid:onetimecode:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppinmanagementservice\/updatepin(_:newpin:verificationid:onetimecode:completion:)"]}],"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updatePin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cardId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"newPin","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"verificationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"oneTimeCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:14StripePayments21STPPinCompletionBlocka","text":"STPPinCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/updatePin(_:newPin:verificationId:oneTimeCode:completion:)"},"metadata":{"modules":[{"name":"Stripe"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","platforms":[{"beta":false,"unavailable":false,"name":"iOS","deprecated":false,"deprecatedAt":"100000.0","message":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements"},{"beta":false,"unavailable":false,"name":"iPadOS","deprecated":false,"deprecatedAt":"100000.0","message":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements"},{"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecated":false,"deprecatedAt":"100000.0","message":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements"}],"externalID":"c:@M@Stripe@objc(cs)STPPinManagementService(im)updatePin:newPin:verificationId:oneTimeCode:completion:","title":"updatePin(_:newPin:verificationId:oneTimeCode:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newPin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"verificationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oneTimeCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPinCompletionBlock","preciseIdentifier":"s:14StripePayments21STPPinCompletionBlocka"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"updatePin:newPin:verificationId:oneTimeCode:completion:"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService/updatePin(_:newPin:verificationId:oneTimeCode:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService\/updatePin(_:newPin:verificationId:oneTimeCode:completion:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Updates a PIN number for a given card,"},{"type":"text","text":" "},{"type":"text","text":"this call is asynchronous, implement the completion block to receive the updates"}],"title":"updatePin(_:newPin:verificationId:oneTimeCode:completion:)","url":"\/documentation\/stripe\/stppinmanagementservice\/updatepin(_:newpin:verificationid:onetimecode:completion:)","type":"topic","navigatorTitle":[{"text":"updatePin:newPin:verificationId:oneTimeCode:completion:","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePin"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newPin"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"verificationId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"oneTimeCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPinCompletionBlock","preciseIdentifier":"s:14StripePayments21STPPinCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPinManagementService":{"url":"\/documentation\/stripe\/stppinmanagementservice","navigatorTitle":[{"kind":"identifier","text":"STPPinManagementService"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPinManagementService","abstract":[{"type":"text","text":"STPAPIClient extensions to manage PIN on Stripe Issuing cards"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPinManagementService"}],"title":"STPPinManagementService","type":"topic","role":"symbol","deprecated":true,"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","abstract":[],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"deprecatedAt":"100000.0","name":"iOS","unavailable":false,"deprecated":false},{"beta":false,"deprecatedAt":"100000.0","name":"iPadOS","unavailable":false,"deprecated":false},{"beta":false,"deprecatedAt":"100000.0","name":"Mac Catalyst","unavailable":false,"deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updatePin:newPin:verificationId:oneTimeCode:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"updatePin:newPin:verificationId:oneTimeCode:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"updatePin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cardId"},{"kind":"text","text":" "},{"kind":"identifier","text":"newPin:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"newPin","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"verificationId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"verificationId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"oneTimeCode:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"oneTimeCode"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^)("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIssuingCardPin","kind":"typeIdentifier","text":"STPIssuingCardPin"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripePayments@E@STPPinStatus","kind":"typeIdentifier","text":"STPPinStatus"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/deprecationSummary","value":[{"inlineContent":[{"text":"Please use Issuing Elements instead: https:\/\/stripe.com\/docs\/issuing\/elements","type":"text"}],"type":"paragraph"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1updatePin(_:newPin:verificationId:oneTimeCode:completion:)\/title","value":"updatePin:newPin:verificationId:oneTimeCode:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService~1updatePin(_:newPin:verificationId:oneTimeCode:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updatePin:newPin:verificationId:oneTimeCode:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/title","value":"STPPinManagementService"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/fragments","value":[{"text":"STPPinManagementService","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPinManagementService\/navigatorTitle","value":[{"text":"STPPinManagementService","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}