{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIGestureRecognizerDelegate.gestureRecognizer(_:shouldReceive:)"},{"type":"text","text":"."}],"metadata":{"role":"symbol","modules":[{"name":"StripePaymentSheet"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"extendedModule":"StripePaymentSheet","roleHeading":"Instance Method","title":"gestureRecognizer(_:shouldReceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:@CM@StripePaymentSheet@objc(cs)STPAddressViewController(im)gestureRecognizer:shouldReceiveTouch:"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/gestureRecognizer(_:shouldReceive:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIGestureRecognizerDelegate-Implementations"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIGestureRecognizer","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":", ","kind":"text"},{"text":"shouldReceive","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"touch","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/gesturerecognizer(_:shouldreceive:)"]},{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/gesturerecognizer(_:shouldreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"type":"topic","navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"abstract":[{"text":"A view controller that collects a name and an address, with full localization and autocomplete.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AddressViewController"}],"role":"symbol","title":"AddressViewController"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/UIGestureRecognizerDelegate-Implementations":{"type":"topic","title":"UIGestureRecognizerDelegate Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIGestureRecognizerDelegate-Implementations","kind":"article","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/uigesturerecognizerdelegate-implementations"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/gestureRecognizer(_:shouldReceive:)":{"type":"topic","title":"gestureRecognizer(_:shouldReceive:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/gestureRecognizer(_:shouldReceive:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"gestureRecognizer","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/gesturerecognizer(_:shouldreceive:)","navigatorTitle":[{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"abstract":[{"text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app.","type":"text"}],"role":"collection","title":"StripePaymentSheet","kind":"symbol","url":"\/documentation\/stripepaymentsheet","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"gestureRecognizer:shouldReceiveTouch:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"gestureRecognizer:"},{"text":"(","kind":"text"},{"text":"UIGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGestureRecognizer"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"gestureRecognizer"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldReceiveTouch:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"touch"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","value":"STPAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","value":[{"text":"STPAddressViewController","kind":"identifier"}]},{"value":"gestureRecognizer:shouldReceiveTouch:","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1gestureRecognizer(_:shouldReceive:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1gestureRecognizer(_:shouldReceive:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
