{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/presentationControllerWillDismiss(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIAdaptivePresentationControllerDelegate.presentationControllerWillDismiss(_:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"title":"presentationControllerWillDismiss(_:)","extendedModule":"StripePaymentSheet","modules":[{"name":"StripePaymentSheet"}],"navigatorTitle":[{"text":"presentationControllerWillDismiss:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@CM@StripePaymentSheet@objc(cs)STPAddressViewController(im)presentationControllerWillDismiss:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationControllerWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationControllerWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"presentationController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier","text":"UIPresentationController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/presentationcontrollerwilldismiss(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/presentationcontrollerwilldismiss(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"url":"\/documentation\/stripepaymentsheet","role":"collection","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","title":"StripePaymentSheet","abstract":[{"type":"text","text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app."}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","title":"AddressViewController","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressViewController"}],"abstract":[{"text":"A view controller that collects a name and an address, with full localization and autocomplete.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/presentationControllerWillDismiss(_:)":{"title":"presentationControllerWillDismiss(_:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/presentationControllerWillDismiss(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerWillDismiss"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier","text":"UIPresentationController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"presentationControllerWillDismiss:"}],"role":"symbol","abstract":[],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/presentationcontrollerwilldismiss(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"presentationControllerWillDismiss:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"presentationControllerWillDismiss:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"presentationControllerWillDismiss:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"presentationController","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPAddressViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPAddressViewController"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPAddressViewController"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle"},{"op":"replace","value":"presentationControllerWillDismiss:","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1presentationControllerWillDismiss(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentationControllerWillDismiss:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1presentationControllerWillDismiss(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}