{"variants":[{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIAdaptivePresentationControllerDelegate-Implementations"},"kind":"article","metadata":{"modules":[{"name":"StripePaymentSheet"}],"role":"collectionGroup","roleHeading":"API Collection","title":"UIAdaptivePresentationControllerDelegate Implementations"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/presentationControllerWillDismiss(_:)"],"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/presentationControllerWillDismiss(_:)":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/presentationcontrollerwilldismiss(_:)","navigatorTitle":[{"kind":"identifier","text":"presentationControllerWillDismiss:"}],"role":"symbol","title":"presentationControllerWillDismiss(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerWillDismiss"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIPresentationController","text":"UIPresentationController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/presentationControllerWillDismiss(_:)"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AddressViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A view controller that collects a name and an address, with full localization and autocomplete."}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","title":"AddressViewController","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","navigatorTitle":[{"kind":"identifier","text":"AddressViewController"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"role":"collection","type":"topic","title":"StripePaymentSheet","url":"\/documentation\/stripepaymentsheet","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","kind":"symbol","abstract":[{"type":"text","text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/presentationControllerWillDismiss(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"presentationControllerWillDismiss:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1presentationControllerWillDismiss(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentationControllerWillDismiss:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1presentationControllerWillDismiss(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","value":"STPAddressViewController","op":"replace"},{"value":[{"kind":"identifier","text":"STPAddressViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle","value":[{"text":"STPAddressViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}