{"identifier":{"url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIGestureRecognizerDelegate-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/gestureRecognizer(_:shouldReceive:)"]}],"metadata":{"modules":[{"name":"StripePaymentSheet"}],"role":"collectionGroup","title":"UIGestureRecognizerDelegate Implementations","roleHeading":"API Collection"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/uigesturerecognizerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/uigesturerecognizerdelegate-implementations"]}],"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/gestureRecognizer(_:shouldReceive:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"gestureRecognizer"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIGestureRecognizer","kind":"typeIdentifier","text":"UIGestureRecognizer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldReceive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITouch","kind":"typeIdentifier","text":"UITouch"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","title":"gestureRecognizer(_:shouldReceive:)","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/gestureRecognizer(_:shouldReceive:)","abstract":[],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/gesturerecognizer(_:shouldreceive:)","navigatorTitle":[{"kind":"identifier","text":"gestureRecognizer:shouldReceiveTouch:"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"title":"AddressViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AddressViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","type":"topic","abstract":[{"text":"A view controller that collects a name and an address, with full localization and autocomplete.","type":"text"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"title":"StripePaymentSheet","role":"collection","abstract":[{"text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsheet"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/gestureRecognizer(_:shouldReceive:)"],"anchor":"Instance-Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1gestureRecognizer(_:shouldReceive:)\/title","value":"gestureRecognizer:shouldReceiveTouch:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1gestureRecognizer(_:shouldReceive:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"gestureRecognizer:shouldReceiveTouch:","kind":"identifier"}]},{"value":"STPAddressViewController","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","op":"replace"},{"value":[{"text":"STPAddressViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPAddressViewController"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle","op":"replace"}]}]}