{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/viewDidLoad()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@StripePaymentSheet@objc(cs)STPAddressViewController(im)viewDidLoad","role":"symbol","modules":[{"name":"StripePaymentSheet"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"title":"viewDidLoad()","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/viewdidload()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/viewdidload()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}]}]}],"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"abstract":[{"text":"A view controller that collects a name and an address, with full localization and autocomplete.","type":"text"}],"kind":"symbol","title":"AddressViewController","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AddressViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","title":"StripePaymentSheet","abstract":[{"type":"text","text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app."}],"url":"\/documentation\/stripepaymentsheet","type":"topic","role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/viewDidLoad()":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/viewDidLoad()","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/viewdidload()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"type":"topic","title":"viewDidLoad()","abstract":[],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"viewDidLoad","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"viewDidLoad","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPAddressViewController","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAddressViewController"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle","op":"replace","value":[{"text":"STPAddressViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1viewDidLoad()\/fragments"}]}]}