{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/canceled"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The source, which was chargeable, has expired because it was not used to"},{"type":"text","text":" "},{"type":"text","text":"make a charge request within a specified amount of time."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceStatusCanceled"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSourceStatus@STPSourceStatusCanceled","modules":[{"name":"StripePayments"}],"role":"symbol","title":"STPSourceStatus.canceled"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcestatus\/canceled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcestatus\/canceled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/canceled":{"title":"STPSourceStatus.canceled","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/canceled","abstract":[{"text":"The source, which was chargeable, has expired because it was not used to","type":"text"},{"text":" ","type":"text"},{"text":"make a charge request within a specified amount of time.","type":"text"}],"navigatorTitle":[{"text":"STPSourceStatusCanceled","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcestatus\/canceled","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"title":"STPSourceStatus","role":"symbol","abstract":[{"text":"Status types for a Source","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","navigatorTitle":[{"text":"STPSourceStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourcestatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceStatus","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPSourceStatusCanceled","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceStatusCanceled"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPSourceStatusCanceled"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1canceled\/title","op":"replace","value":"STPSourceStatusCanceled"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1canceled\/fragments","op":"replace","value":[{"text":"STPSourceStatusCanceled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title","op":"replace","value":"STPSourceStatus"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments","op":"replace","value":[{"text":"STPSourceStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/navigatorTitle","op":"replace","value":[{"text":"STPSourceStatus","kind":"identifier"}]}]}]}