{"abstract":[{"text":"The source is ready to use. The customer action has been completed or the","type":"text"},{"text":" ","type":"text"},{"text":"payment method requires no customer action.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chargeable"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcestatus\/chargeable"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcestatus\/chargeable"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/chargeable","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chargeable"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSourceStatus@STPSourceStatusChargeable","navigatorTitle":[{"kind":"identifier","text":"STPSourceStatusChargeable"}],"title":"STPSourceStatus.chargeable","role":"symbol","symbolKind":"case"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"kind":"symbol","abstract":[{"text":"Status types for a Source","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcestatus","title":"STPSourceStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceStatus","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceStatus","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/chargeable":{"title":"STPSourceStatus.chargeable","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcestatus\/chargeable","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chargeable","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPSourceStatusChargeable","kind":"identifier"}],"abstract":[{"text":"The source is ready to use. The customer action has been completed or the","type":"text"},{"text":" ","type":"text"},{"text":"payment method requires no customer action.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/chargeable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceStatusChargeable"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPSourceStatusChargeable","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPSourceStatusChargeable","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title","op":"replace","value":"STPSourceStatus"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments","op":"replace","value":[{"text":"STPSourceStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/navigatorTitle","op":"replace","value":[{"text":"STPSourceStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1chargeable\/title","op":"replace","value":"STPSourceStatusChargeable"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1chargeable\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceStatusChargeable"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}