{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"]]},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSourceStatus@STPSourceStatusConsumed","title":"STPSourceStatus.consumed","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consumed","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"STPSourceStatusConsumed","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"consumed"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"The source has been used. This status only applies to single-use sources.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcestatus\/consumed"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcestatus\/consumed"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/consumed"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/consumed":{"abstract":[{"type":"text","text":"The source has been used. This status only applies to single-use sources."}],"navigatorTitle":[{"text":"STPSourceStatusConsumed","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourcestatus\/consumed","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"consumed","kind":"identifier"}],"title":"STPSourceStatus.consumed","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/consumed"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","abstract":[{"text":"Status types for a Source","type":"text"}],"navigatorTitle":[{"text":"STPSourceStatus","kind":"identifier"}],"kind":"symbol","title":"STPSourceStatus","type":"topic","url":"\/documentation\/stripepayments\/stpsourcestatus","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPSourceStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceStatusConsumed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceStatusConsumed","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSourceStatusConsumed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"STPSourceStatusConsumed","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1consumed\/title"},{"value":[{"text":"STPSourceStatusConsumed","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1consumed\/fragments"},{"value":"STPSourceStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title"},{"value":[{"kind":"identifier","text":"STPSourceStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}