{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"]]},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"StripePayments"}],"title":"CustomStringConvertible Implementations"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/CustomStringConvertible-Implementations"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/description"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcestatus\/customstringconvertible-implementations"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/description":{"title":"description","abstract":[],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/stripepayments\/stpsourcestatus\/description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","role":"symbol","url":"\/documentation\/stripepayments\/stpsourcestatus","kind":"symbol","title":"STPSourceStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceStatus"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceStatus"}],"abstract":[{"type":"text","text":"Status types for a Source"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title","value":"STPSourceStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/navigatorTitle","value":[{"text":"STPSourceStatus","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}