{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/failed"},"metadata":{"externalID":"c:@M@StripePayments@E@STPSourceStatus@STPSourceStatusFailed","navigatorTitle":[{"text":"STPSourceStatusFailed","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"title":"STPSourceStatus.failed","roleHeading":"Case"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcestatus\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcestatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Your customer has not taken the required action or revoked your access"},{"type":"text","text":" "},{"type":"text","text":"(e.g., did not authorize the payment with their bank or canceled their"},{"type":"text","text":" "},{"type":"text","text":"mandate acceptance for SEPA direct debits)."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/failed":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/failed","role":"symbol","navigatorTitle":[{"text":"STPSourceStatusFailed","kind":"identifier"}],"title":"STPSourceStatus.failed","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcestatus\/failed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"abstract":[{"type":"text","text":"Your customer has not taken the required action or revoked your access"},{"type":"text","text":" "},{"type":"text","text":"(e.g., did not authorize the payment with their bank or canceled their"},{"type":"text","text":" "},{"type":"text","text":"mandate acceptance for SEPA direct debits)."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceStatus"}],"url":"\/documentation\/stripepayments\/stpsourcestatus","abstract":[{"text":"Status types for a Source","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceStatus"}],"role":"symbol","title":"STPSourceStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPSourceStatusFailed","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPSourceStatusFailed"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"STPSourceStatusFailed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPSourceStatusFailed","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1failed\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1failed\/fragments","value":[{"kind":"identifier","text":"STPSourceStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title","value":"STPSourceStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments","value":[{"text":"STPSourceStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/navigatorTitle","value":[{"text":"STPSourceStatus","kind":"identifier"}]}]}]}