{"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcestatus\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/hashValue"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/hash(into:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"RawRepresentable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/hashValue":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/hashValue","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"role":"symbol","title":"hashValue","url":"\/documentation\/stripepayments\/stpsourcestatus\/hashvalue","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceStatus"}],"role":"symbol","title":"STPSourceStatus","abstract":[{"type":"text","text":"Status types for a Source"}],"url":"\/documentation\/stripepayments\/stpsourcestatus","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","navigatorTitle":[{"kind":"identifier","text":"STPSourceStatus"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/hash(into:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepayments\/stpsourcestatus\/hash(into:)","title":"hash(into:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/hash(into:)","type":"topic","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPSourceStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceStatus"}]}]}]}