{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcestatus\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcestatus\/unknown"]}],"abstract":[{"type":"text","text":"The source status is unknown."}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/unknown","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"STPSourceStatusUnknown","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPSourceStatus@STPSourceStatusUnknown","roleHeading":"Case","symbolKind":"case","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"title":"STPSourceStatus.unknown","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/unknown":{"abstract":[{"text":"The source status is unknown.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcestatus\/unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceStatusUnknown"}],"title":"STPSourceStatus.unknown","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/unknown","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"title":"STPSourceStatus","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","type":"topic","navigatorTitle":[{"text":"STPSourceStatus","kind":"identifier"}],"abstract":[{"text":"Status types for a Source","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcestatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPSourceStatusUnknown","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPSourceStatusUnknown","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPSourceStatusUnknown"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1unknown\/title","op":"replace","value":"STPSourceStatusUnknown"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1unknown\/fragments","op":"replace","value":[{"text":"STPSourceStatusUnknown","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title","op":"replace","value":"STPSourceStatus"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments","op":"replace","value":[{"text":"STPSourceStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/navigatorTitle","op":"replace","value":[{"text":"STPSourceStatus","kind":"identifier"}]}]}]}