{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"text":"This method lines up with the method of the same name on ","type":"text"},{"code":"PKAddPaymentPassViewControllerDelegate","type":"codeVoice"},{"text":". You should implement that protocol in your own app, and when that method is called, call this method on your ","type":"text"},{"type":"codeVoice","code":"STPPushProvisioningContext"},{"text":". This in turn will first initiate a call to your ","type":"text"},{"code":"keyProvider","type":"codeVoice"},{"type":"text","text":" (see above) to obtain an Ephemeral Key, then make a call to the Stripe Issuing API to fetch an encrypted payload for the card in question, then return that payload to iOS."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addPaymentPassViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"generateRequestWithCertificateChain"},{"kind":"text","text":" "},{"text":"certificates","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nonceSignature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":" ","kind":"text"},{"text":"handler","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"PKAddPaymentPassRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]}],"metadata":{"symbolKind":"method","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningContext(im)addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addPaymentPassViewController"},{"kind":"text","text":"("},{"text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"generateRequestWithCertificateChain"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"], ","kind":"text"},{"text":"nonce","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"nonceSignature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest","text":"PKAddPaymentPassRequest"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)"]},{"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)":{"navigatorTitle":[{"text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","abstract":[{"text":"This method lines up with the method of the same name on ","type":"text"},{"code":"PKAddPaymentPassViewControllerDelegate","type":"codeVoice"},{"type":"text","text":". You should implement that protocol in your own app, and when that method is called, call this method on your "},{"type":"codeVoice","code":"STPPushProvisioningContext"},{"type":"text","text":". This in turn will first initiate a call to your "},{"type":"codeVoice","code":"keyProvider"},{"text":" (see above) to obtain an Ephemeral Key, then make a call to the Stripe Issuing API to fetch an encrypted payload for the card in question, then return that payload to iOS.","type":"text"}],"role":"symbol","title":"addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)","type":"topic","url":"\/documentation\/stripe\/stppushprovisioningcontext\/addpaymentpassviewcontroller(_:generaterequestwithcertificatechain:nonce:noncesignature:completionhandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addPaymentPassViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PKAddPaymentPassViewController","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"generateRequestWithCertificateChain","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"nonce"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nonceSignature","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest","text":"PKAddPaymentPassRequest","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext":{"title":"STPPushProvisioningContext","navigatorTitle":[{"kind":"identifier","text":"STPPushProvisioningContext"}],"url":"\/documentation\/stripe\/stppushprovisioningcontext","role":"symbol","type":"topic","abstract":[{"type":"text","text":"This class makes it easier to implement “Push Provisioning”, the process by which an end-user can add a card to their Apple Pay wallet without having to type their number. This process is mediated by an Apple class called "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"text":"; this class will help you implement that class’ delegate methods. Note that this flow requires a special entitlement from Apple; for more information please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets .","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPushProvisioningContext"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","title":"Stripe","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addPaymentPassViewController:"},{"text":"(","kind":"text"},{"text":"PKAddPaymentPassViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"generateRequestWithCertificateChain:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSData *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"certificates"},{"kind":"text","text":" "},{"kind":"identifier","text":"nonce:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"text":"nonce","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nonceSignature:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"text":"nonceSignature","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequest","text":"PKAddPaymentPassRequest"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"handler","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)\/title","value":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1addPaymentPassViewController(_:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addPaymentPassViewController:generateRequestWithCertificateChain:nonce:nonceSignature:completionHandler:"}]},{"value":"STPPushProvisioningContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/title"},{"value":[{"kind":"identifier","text":"STPPushProvisioningContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/navigatorTitle","value":[{"text":"STPPushProvisioningContext","kind":"identifier"}]}]}]}