{"abstract":[{"type":"text","text":"The API Client to use to make requests."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to STPAPIClient.shared"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/apiClient","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/apiclient"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"apiClient","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAPIClient","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"title":"apiClient","symbolKind":"property","modules":[{"name":"Stripe"}],"role":"symbol","externalID":"s:6Stripe26STPPushProvisioningContextC9apiClient0A4Core12STPAPIClientCvp"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/apiClient":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiClient"},{"text":": ","kind":"text"},{"text":"STPAPIClient","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"role":"symbol","title":"apiClient","abstract":[{"text":"The API Client to use to make requests.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to STPAPIClient.shared"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stppushprovisioningcontext\/apiclient","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/apiClient"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPushProvisioningContext"}],"role":"symbol","title":"STPPushProvisioningContext","abstract":[{"type":"text","text":"This class makes it easier to implement “Push Provisioning”, the process by which an end-user can add a card to their Apple Pay wallet without having to type their number. This process is mediated by an Apple class called "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":"; this class will help you implement that class’ delegate methods. Note that this flow requires a special entitlement from Apple; for more information please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets .","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripe\/stppushprovisioningcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"type":"topic","url":"\/documentation\/stripe","title":"Stripe","kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","abstract":[]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAPIClient":{"title":"STPAPIClient","kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stpapiclient","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIClient"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAPIClient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPushProvisioningContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/fragments","value":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/navigatorTitle","value":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"op":"replace"}]}]}