{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/init(keyprovider:)"]},{"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/init(keyprovider:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"In order to retreive the encrypted payload that PKAddPaymentPassViewController expects, the Stripe SDK must talk to the Stripe API. As this requires privileged access, you must write a “key provider” that generates an Ephemeral Key on your backend and provides it to the SDK when requested. For more information, see https:\/\/stripe.com\/docs\/mobile\/ios\/basic#ephemeral-key","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keyProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider","preciseIdentifier":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider","text":"STPIssuingCardEphemeralKeyProvider"},{"text":")","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/init(keyProvider:)"},"sections":[],"metadata":{"roleHeading":"Initializer","modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningContext(im)initWithKeyProvider:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keyProvider"},{"kind":"text","text":": "},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithKeyProvider:","kind":"identifier"}],"title":"init(keyProvider:)","role":"symbol","symbolKind":"init"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPIssuingCardEphemeralKeyProvider":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider","navigatorTitle":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"url":"\/documentation\/stripe\/stpissuingcardephemeralkeyprovider","role":"symbol","title":"STPIssuingCardEphemeralKeyProvider","abstract":[{"type":"text","text":"You should make your application’s API client conform to this interface."},{"text":" ","type":"text"},{"text":"It provides a way for Stripe utility classes to request a new ephemeral key from","type":"text"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/init(keyProvider:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"keyProvider"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider","text":"STPIssuingCardEphemeralKeyProvider"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithKeyProvider:","kind":"identifier"}],"abstract":[{"text":"In order to retreive the encrypted payload that PKAddPaymentPassViewController expects, the Stripe SDK must talk to the Stripe API. As this requires privileged access, you must write a “key provider” that generates an Ephemeral Key on your backend and provides it to the SDK when requested. For more information, see https:\/\/stripe.com\/docs\/mobile\/ios\/basic#ephemeral-key","type":"text"}],"url":"\/documentation\/stripe\/stppushprovisioningcontext\/init(keyprovider:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/init(keyProvider:)","type":"topic","kind":"symbol","title":"init(keyProvider:)","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext","url":"\/documentation\/stripe\/stppushprovisioningcontext","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPushProvisioningContext"}],"title":"STPPushProvisioningContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningContext","kind":"identifier"}],"type":"topic","abstract":[{"text":"This class makes it easier to implement “Push Provisioning”, the process by which an end-user can add a card to their Apple Pay wallet without having to type their number. This process is mediated by an Apple class called ","type":"text"},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":"; this class will help you implement that class’ delegate methods. Note that this flow requires a special entitlement from Apple; for more information please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithKeyProvider:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithKeyProvider:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithKeyProvider:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider","kind":"typeIdentifier","text":"id<STPIssuingCardEphemeralKeyProvider>"},{"text":" *) ","kind":"text"},{"text":"keyProvider","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"STPIssuingCardEphemeralKeyProvider","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/title","op":"replace"},{"value":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1init(keyProvider:)\/title","op":"replace","value":"initWithKeyProvider:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1init(keyProvider:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithKeyProvider:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/title","op":"replace","value":"STPPushProvisioningContext"},{"value":[{"kind":"identifier","text":"STPPushProvisioningContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
