{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/requestconfiguration(withname:description:last4:brand:primaryaccountidentifier:)"]},{"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/requestconfiguration(withname:description:last4:brand:primaryaccountidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)"},"abstract":[{"type":"text","text":"This is a helper method to generate a PKAddPaymentPassRequestConfiguration that will work with"},{"type":"text","text":" "},{"type":"text","text":"Stripe’s Issuing APIs. Pass the returned configuration object to "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"text":"’s ","type":"text"},{"type":"codeVoice","code":"initWithRequestConfiguration:delegate:"},{"text":" initializer.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestConfiguration"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withName"},{"kind":"text","text":" "},{"text":"name","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"last4","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"primaryAccountIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"PKAddPaymentPassRequestConfiguration","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Your cardholder’s name. Example: John Appleseed","type":"text"}]}],"name":"name"},{"content":[{"inlineContent":[{"type":"text","text":"A localized description of your card’s name. This will appear in Apple’s UI as “{description} will be available in Wallet”. Example: Platinum Rewards Card"}],"type":"paragraph"}],"name":"description"},{"name":"last4","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The last 4 of the card to be added to the user’s Apple Pay wallet. Example: 4242"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The brand of the card. Example: ","type":"text"},{"code":"STPCardBrandVisa","type":"codeVoice"}]}],"name":"brand"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"primary_account_identifier","type":"codeVoice"},{"type":"text","text":" value from the issued card."}]}],"name":"primaryAccountIdentifier"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:"}],"externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningContext(cm)requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:","modules":[{"name":"Stripe"}],"roleHeading":"Type Method","title":"requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)","role":"symbol","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestConfiguration"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"last4","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"},{"text":", ","kind":"text"},{"text":"primaryAccountIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"PKAddPaymentPassRequestConfiguration","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration"}]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","type":"topic","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","title":"Stripe","abstract":[]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppushprovisioningcontext\/requestconfiguration(withname:description:last4:brand:primaryaccountidentifier:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestConfiguration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"last4","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"brand"},{"text":": ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":", ","kind":"text"},{"text":"primaryAccountIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) -> "},{"text":"PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration"}],"title":"requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)","navigatorTitle":[{"text":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)","abstract":[{"type":"text","text":"This is a helper method to generate a PKAddPaymentPassRequestConfiguration that will work with"},{"text":" ","type":"text"},{"type":"text","text":"Stripe’s Issuing APIs. Pass the returned configuration object to "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"initWithRequestConfiguration:delegate:"},{"type":"text","text":" initializer."}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCardBrand":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardBrand"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCardBrand","navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}],"type":"topic","url":"\/documentation\/stripe\/stpcardbrand","kind":"symbol","role":"symbol","title":"STPCardBrand"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext":{"type":"topic","title":"STPPushProvisioningContext","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext","navigatorTitle":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"abstract":[{"text":"This class makes it easier to implement “Push Provisioning”, the process by which an end-user can add a card to their Apple Pay wallet without having to type their number. This process is mediated by an Apple class called ","type":"text"},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":"; this class will help you implement that class’ delegate methods. Note that this flow requires a special entitlement from Apple; for more information please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPushProvisioningContext","kind":"identifier"}],"url":"\/documentation\/stripe\/stppushprovisioningcontext"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier","text":"PKAddPaymentPassRequestConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"requestConfigurationWithName:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"name"},{"text":" ","kind":"text"},{"text":"description:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"description","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"last4:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"last4","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"primaryAccountIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"primaryAccountIdentifier","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"text":"Your cardholder’s name. Example: John Appleseed","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A localized description of your card’s name. This will appear in Apple’s UI as “{description} will be available in Wallet”. Example: Platinum Rewards Card","type":"text"}]}],"name":"description"},{"content":[{"inlineContent":[{"text":"The last 4 of the card to be added to the user’s Apple Pay wallet. Example: 4242","type":"text"}],"type":"paragraph"}],"name":"last4"},{"name":"brand","content":[{"inlineContent":[{"type":"text","text":"The brand of the card. Example: "},{"code":"STPCardBrandVisa","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"primary_account_identifier","type":"codeVoice"},{"type":"text","text":" value from the issued card."}]}],"name":"primaryAccountIdentifier"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)\/title","value":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"requestConfigurationWithName:description:last4:brand:primaryAccountIdentifier:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)\/fragments"},{"op":"replace","value":"STPPushProvisioningContext","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPushProvisioningContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/navigatorTitle","value":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}