{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestConfiguration"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"kind":"text","text":" "},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"last4"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"brand"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"PKAddPaymentPassRequestConfiguration","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Your cardholder’s name. Example: John Appleseed","type":"text"}]}],"name":"name"},{"content":[{"inlineContent":[{"text":"A localized description of your card’s name. This will appear in Apple’s UI as “{description} will be available in Wallet”. Example: Platinum Rewards Card","type":"text"}],"type":"paragraph"}],"name":"description"},{"content":[{"inlineContent":[{"text":"The last 4 of the card to be added to the user’s Apple Pay wallet. Example: 4242","type":"text"}],"type":"paragraph"}],"name":"last4"},{"name":"brand","content":[{"inlineContent":[{"type":"text","text":"The brand of the card. Example: "},{"code":"STPCardBrandVisa","type":"codeVoice"}],"type":"paragraph"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/requestconfiguration(withname:description:last4:brand:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppushprovisioningcontext\/requestconfiguration(withname:description:last4:brand:)"]}],"abstract":[{"type":"text","text":"This is a helper method to generate a PKAddPaymentPassRequestConfiguration that will work with"},{"type":"text","text":" "},{"type":"text","text":"Stripe’s Issuing APIs. Pass the returned configuration object to "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":"’s ","type":"text"},{"code":"initWithRequestConfiguration:delegate:","type":"codeVoice"},{"type":"text","text":" initializer."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use `requestConfiguration(withName:description:last4:brand:primaryAccountIdentifier:)` instead."}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"requestConfiguration(withName:description:last4:brand:)","role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPPushProvisioningContext(cm)requestConfigurationWithName:description:last4:brand:","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestConfiguration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"last4"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"brand"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","text":"PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"requestConfigurationWithName:description:last4:brand:","kind":"identifier"}],"platforms":[],"symbolKind":"method","modules":[{"name":"Stripe"}]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","role":"collection","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext/requestConfiguration(withName:description:last4:brand:)":{"abstract":[{"type":"text","text":"This is a helper method to generate a PKAddPaymentPassRequestConfiguration that will work with"},{"type":"text","text":" "},{"text":"Stripe’s Issuing APIs. Pass the returned configuration object to ","type":"text"},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":"’s "},{"code":"initWithRequestConfiguration:delegate:","type":"codeVoice"},{"type":"text","text":" initializer."}],"kind":"symbol","deprecated":true,"url":"\/documentation\/stripe\/stppushprovisioningcontext\/requestconfiguration(withname:description:last4:brand:)","title":"requestConfiguration(withName:description:last4:brand:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestConfiguration"},{"text":"(","kind":"text"},{"text":"withName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"last4","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"brand"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","text":"PKAddPaymentPassRequestConfiguration"}],"navigatorTitle":[{"text":"requestConfigurationWithName:description:last4:brand:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext\/requestConfiguration(withName:description:last4:brand:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPushProvisioningContext":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPushProvisioningContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"url":"\/documentation\/stripe\/stppushprovisioningcontext","abstract":[{"type":"text","text":"This class makes it easier to implement “Push Provisioning”, the process by which an end-user can add a card to their Apple Pay wallet without having to type their number. This process is mediated by an Apple class called "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":"; this class will help you implement that class’ delegate methods. Note that this flow requires a special entitlement from Apple; for more information please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPushProvisioningContext","title":"STPPushProvisioningContext"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCardBrand":{"abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"url":"\/documentation\/stripe\/stpcardbrand","role":"symbol","kind":"symbol","title":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCardBrand","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"requestConfigurationWithName:description:last4:brand:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"requestConfigurationWithName:description:last4:brand:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"PKAddPaymentPassRequestConfiguration","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"requestConfigurationWithName:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"description:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"description"},{"text":" ","kind":"text"},{"text":"last4:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"last4"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"brand"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"name","content":[{"inlineContent":[{"text":"Your cardholder’s name. Example: John Appleseed","type":"text"}],"type":"paragraph"}]},{"name":"description","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A localized description of your card’s name. This will appear in Apple’s UI as “{description} will be available in Wallet”. Example: Platinum Rewards Card"}]}]},{"name":"last4","content":[{"type":"paragraph","inlineContent":[{"text":"The last 4 of the card to be added to the user’s Apple Pay wallet. Example: 4242","type":"text"}]}]},{"name":"brand","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand of the card. Example: "},{"code":"STPCardBrandVisa","type":"codeVoice"}]}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1requestConfiguration(withName:description:last4:brand:)\/title","value":"requestConfigurationWithName:description:last4:brand:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"requestConfigurationWithName:description:last4:brand:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext~1requestConfiguration(withName:description:last4:brand:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/title","value":"STPPushProvisioningContext"},{"value":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPushProvisioningContext\/navigatorTitle","value":[{"text":"STPPushProvisioningContext","kind":"identifier"}],"op":"replace"}]}]}