{"metadata":{"role":"collectionGroup","title":"STPAPIResponseDecodable Implementations","modules":[{"name":"StripePayments"}],"roleHeading":"API Collection"},"kind":"article","topicSections":[{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/decodedObject(fromAPIResponse:)"]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits\/stpapiresponsedecodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits\/stpapiresponsedecodable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/STPAPIResponseDecodable-Implementations"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits/decodedObject(fromAPIResponse:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/decodedObject(fromAPIResponse:)","kind":"symbol","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits\/decodedobject(fromapiresponse:)","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"type":"topic","role":"symbol","title":"decodedObject(fromAPIResponse:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits","url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}],"kind":"symbol","title":"STPIntentActionVerifyWithMicrodeposits","type":"topic","role":"symbol","abstract":[{"text":"Contains details describing microdeposits verification flow for US Bank Accounts.","type":"text"}],"navigatorTitle":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/decodedObject(fromAPIResponse:)"],"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1decodedObject(fromAPIResponse:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1decodedObject(fromAPIResponse:)\/fragments"},{"value":"STPIntentActionVerifyWithMicrodeposits","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/title"},{"value":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/fragments"},{"value":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/navigatorTitle"}]}]}