#include "MediaPipeSPMGraphReferencesInternal.h"

#define MEDIAPIPE_SPM_SYMBOL(name, symbol) \
    extern void name(void) __asm(symbol)

MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMImageCloneCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api220ImageCloneCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMImagePropertiesCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api225ImagePropertiesCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMImageToTensorCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api223ImageToTensorCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMInferenceCalculatorCpuGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api226InferenceCalculatorCpuImplEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMInferenceCalculatorMetalGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api228InferenceCalculatorMetalImplEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMTensorsToDetectionsCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api229TensorsToDetectionsCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMTensorsToFloatsCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api225TensorsToFloatsCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMTensorsToLandmarksCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api228TensorsToLandmarksCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMTensorsToClassificationCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api233TensorsToClassificationCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMLandmarksSmoothingCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api232LandmarksSmoothingCalculatorImplEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMLandmarksToMatrixCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api227LandmarksToMatrixCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMLandmarksToTensorCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api231LandmarksToTensorCalculatorImplEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMLandmarksRefinementCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api233LandmarksRefinementCalculatorImplEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMGetNormalizedRectVectorItemCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api223GetVectorItemCalculatorINS_14NormalizedRectEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMGetNormalizedLandmarkListVectorItemCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api223GetVectorItemCalculatorINS_22NormalizedLandmarkListEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMGetClassificationListVectorItemCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api223GetVectorItemCalculatorINS_18ClassificationListEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMGetDetectionVectorItemCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api223GetVectorItemCalculatorINS_9DetectionEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMSsdAnchorsCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_20SsdAnchorsCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMDetectionProjectionCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_29DetectionProjectionCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMDetectionTransformationCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api233DetectionTransformationCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMNonMaxSuppressionCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_27NonMaxSuppressionCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMClipNormalizedRectVectorSizeCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_24ClipVectorSizeCalculatorINS_14NormalizedRectEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMClipDetectionVectorSizeCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_24ClipVectorSizeCalculatorINS_9DetectionEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMDetectionLetterboxRemovalCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_35DetectionLetterboxRemovalCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMDetectionsToRectsCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_27DetectionsToRectsCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMRectTransformationCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_28RectTransformationCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMGateCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_14GateCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMAssociationNormRectCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_29AssociationNormRectCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMCollectionHasMinSizeCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_30CollectionHasMinSizeCalculatorINSt3__16vectorINS_14NormalizedRectENS3_9allocatorIS5_EEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMPreviousLoopbackCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_4api226PreviousLoopbackCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMPassThroughCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_21PassThroughCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMSplitTensorVectorCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_21SplitVectorCalculatorINS_6TensorELb1EEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMSplitNormalizedRectVectorCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_21SplitVectorCalculatorINS_14NormalizedRectELb0EEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMSplitNormalizedLandmarkListCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_37SplitNormalizedLandmarkListCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMSplitNormalizedLandmarkListVectorCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_21SplitVectorCalculatorINS_22NormalizedLandmarkListELb0EEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMSplitClassificationListVectorCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_21SplitVectorCalculatorINS_18ClassificationListELb0EEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMLandmarkLetterboxRemovalCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_34LandmarkLetterboxRemovalCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMLandmarkProjectionCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_28LandmarkProjectionCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMLandmarksToDetectionCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_30LandmarksToDetectionCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMThresholdingCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_22ThresholdingCalculatorEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMBeginNormalizedRectLoopCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_19BeginLoopCalculatorINSt3__16vectorINS_14NormalizedRectENS3_9allocatorIS5_EEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMBeginNormalizedLandmarkListLoopCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_19BeginLoopCalculatorINSt3__16vectorINS_22NormalizedLandmarkListENS3_9allocatorIS5_EEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMBeginDetectionLoopCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_19BeginLoopCalculatorINSt3__16vectorINS_9DetectionENS3_9allocatorIS5_EEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMEndNormalizedRectLoopCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_17EndLoopCalculatorINSt3__16vectorINS_14NormalizedRectENS3_9allocatorIS5_EEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMEndNormalizedLandmarkListLoopCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_17EndLoopCalculatorINSt3__16vectorINS_22NormalizedLandmarkListENS3_9allocatorIS5_EEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMEndClassificationListLoopCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_17EndLoopCalculatorINSt3__16vectorINS_18ClassificationListENS3_9allocatorIS5_EEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMEndBoolLoopCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_17EndLoopCalculatorINSt3__16vectorIbNS3_9allocatorIbEEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMEndFloatLoopCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_17EndLoopCalculatorINSt3__16vectorIfNS3_9allocatorIfEEEEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMConcatenateNormalizedLandmarkListCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_27ConcatenateVectorCalculatorINS_22NormalizedLandmarkListEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMConcatenateClassificationListCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_27ConcatenateVectorCalculatorINS_18ClassificationListEEEvE11GetContractEPNS_18CalculatorContractE");
MEDIAPIPE_SPM_SYMBOL(MediaPipeSPMModelResourcesCalculatorGetContract, "__ZN9mediapipe8internal24CalculatorBaseFactoryForINS_5tasks4core24ModelResourcesCalculatorEvE11GetContractEPNS_18CalculatorContractE");

static const MediaPipeSPMSymbolReference calculatorReferences[] = {
    MediaPipeSPMImageCloneCalculatorGetContract,
    MediaPipeSPMImagePropertiesCalculatorGetContract,
    MediaPipeSPMImageToTensorCalculatorGetContract,
    MediaPipeSPMInferenceCalculatorCpuGetContract,
    MediaPipeSPMInferenceCalculatorMetalGetContract,
    MediaPipeSPMTensorsToDetectionsCalculatorGetContract,
    MediaPipeSPMTensorsToFloatsCalculatorGetContract,
    MediaPipeSPMTensorsToLandmarksCalculatorGetContract,
    MediaPipeSPMTensorsToClassificationCalculatorGetContract,
    MediaPipeSPMLandmarksSmoothingCalculatorGetContract,
    MediaPipeSPMLandmarksToMatrixCalculatorGetContract,
    MediaPipeSPMLandmarksToTensorCalculatorGetContract,
    MediaPipeSPMLandmarksRefinementCalculatorGetContract,
    MediaPipeSPMGetNormalizedRectVectorItemCalculatorGetContract,
    MediaPipeSPMGetNormalizedLandmarkListVectorItemCalculatorGetContract,
    MediaPipeSPMGetClassificationListVectorItemCalculatorGetContract,
    MediaPipeSPMGetDetectionVectorItemCalculatorGetContract,
    MediaPipeSPMSsdAnchorsCalculatorGetContract,
    MediaPipeSPMDetectionProjectionCalculatorGetContract,
    MediaPipeSPMDetectionTransformationCalculatorGetContract,
    MediaPipeSPMNonMaxSuppressionCalculatorGetContract,
    MediaPipeSPMClipNormalizedRectVectorSizeCalculatorGetContract,
    MediaPipeSPMClipDetectionVectorSizeCalculatorGetContract,
    MediaPipeSPMDetectionLetterboxRemovalCalculatorGetContract,
    MediaPipeSPMDetectionsToRectsCalculatorGetContract,
    MediaPipeSPMRectTransformationCalculatorGetContract,
    MediaPipeSPMGateCalculatorGetContract,
    MediaPipeSPMAssociationNormRectCalculatorGetContract,
    MediaPipeSPMCollectionHasMinSizeCalculatorGetContract,
    MediaPipeSPMPreviousLoopbackCalculatorGetContract,
    MediaPipeSPMPassThroughCalculatorGetContract,
    MediaPipeSPMSplitTensorVectorCalculatorGetContract,
    MediaPipeSPMSplitNormalizedRectVectorCalculatorGetContract,
    MediaPipeSPMSplitNormalizedLandmarkListCalculatorGetContract,
    MediaPipeSPMSplitNormalizedLandmarkListVectorCalculatorGetContract,
    MediaPipeSPMSplitClassificationListVectorCalculatorGetContract,
    MediaPipeSPMLandmarkLetterboxRemovalCalculatorGetContract,
    MediaPipeSPMLandmarkProjectionCalculatorGetContract,
    MediaPipeSPMLandmarksToDetectionCalculatorGetContract,
    MediaPipeSPMThresholdingCalculatorGetContract,
    MediaPipeSPMBeginNormalizedRectLoopCalculatorGetContract,
    MediaPipeSPMBeginNormalizedLandmarkListLoopCalculatorGetContract,
    MediaPipeSPMBeginDetectionLoopCalculatorGetContract,
    MediaPipeSPMEndNormalizedRectLoopCalculatorGetContract,
    MediaPipeSPMEndNormalizedLandmarkListLoopCalculatorGetContract,
    MediaPipeSPMEndClassificationListLoopCalculatorGetContract,
    MediaPipeSPMEndBoolLoopCalculatorGetContract,
    MediaPipeSPMEndFloatLoopCalculatorGetContract,
    MediaPipeSPMConcatenateNormalizedLandmarkListCalculatorGetContract,
    MediaPipeSPMConcatenateClassificationListCalculatorGetContract,
    MediaPipeSPMModelResourcesCalculatorGetContract,
};

void MediaPipeSPMKeepFaceLandmarkerCalculatorReferences(void) {
    MediaPipeSPMKeepSymbolReferences(
        calculatorReferences,
        sizeof(calculatorReferences) / sizeof(calculatorReferences[0])
    );
}
