{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/cancel()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"StripePayments"}],"role":"symbol","title":"cancel()","roleHeading":"Instance Method","externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(im)cancel","navigatorTitle":[{"text":"cancel","kind":"identifier"}],"symbolKind":"method"},"abstract":[{"text":"Dismisses any presented views and stops listening for any","type":"text"},{"text":" ","type":"text"},{"text":"app opens or callbacks. The completion block will not be fired.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/cancel()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/cancel()"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"title":"STPRedirectContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContext"}],"abstract":[{"type":"text","text":"This is a helper class for handling redirects associated with STPSource and"},{"type":"text","text":" "},{"text":"STPPaymentIntents.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Init and retain an instance with the Source or PaymentIntent you want to handle,"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"type":"text","text":"when the redirect completes."},{"text":" ","type":"text"},{"text":"Due to the nature of iOS, very little concrete information can be gained","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"during this process, as all actions take place in either the Safari app"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"type":"text","text":" "},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"text":" ","type":"text"},{"text":"for both app foregrounds and url callbacks received in the app delegate.","type":"text"},{"type":"text","text":" "},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"type":"text","text":" "},{"type":"text","text":"have not actually completed the necessary actions to authorize the charge."},{"type":"text","text":" "},{"type":"text","text":"You should not use either this class, nor "},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":", as a way"},{"type":"text","text":" "},{"type":"text","text":"to determine when you should charge the Source or to determine if the redirect"},{"type":"text","text":" "},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"text":" ","type":"text"},{"text":"state changes and to make the charge.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContext"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/cancel()":{"abstract":[{"text":"Dismisses any presented views and stops listening for any","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"app opens or callbacks. The completion block will not be fired."}],"url":"\/documentation\/stripepayments\/stpredirectcontext\/cancel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","title":"cancel()","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/cancel()","navigatorTitle":[{"kind":"identifier","text":"cancel"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"cancel","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"STPRedirectContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"text":"STPRedirectContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPRedirectContext"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1cancel()\/title","value":"cancel","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"cancel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1cancel()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}