{"variants":[{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/handleurlcallback:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"handleURLCallback:"}],"role":"symbol","title":"handleURLCallback:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleURLCallback:"}],"externalID":"c:@CM@StripePayments@objc(cs)STPRedirectContext(im)handleURLCallback:","modules":[{"name":"StripePayments"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/handleURLCallback:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"handleURLCallback:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"abstract":[{"type":"text","text":":nodoc:"}],"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/handleURLCallback:":{"title":"handleURLCallback:","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontext\/handleurlcallback:","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"handleURLCallback:","kind":"identifier"}],"navigatorTitle":[{"text":"handleURLCallback:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/handleURLCallback:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"url":"\/documentation\/stripepayments\/stpredirectcontext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","title":"STPRedirectContext","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"abstract":[{"text":"This is a helper class for handling redirects associated with STPSource and","type":"text"},{"text":" ","type":"text"},{"text":"STPPaymentIntents.","type":"text"},{"text":" ","type":"text"},{"text":"Init and retain an instance with the Source or PaymentIntent you want to handle,","type":"text"},{"text":" ","type":"text"},{"text":"then choose a redirect method. The context will fire the completion handler","type":"text"},{"type":"text","text":" "},{"text":"when the redirect completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"type":"text","text":" "},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"type":"text","text":" "},{"text":"or the sandboxed SFSafariViewController class. The context attempts to","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"type":"text","text":" "},{"text":"for both app foregrounds and url callbacks received in the app delegate.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"However, it is possible the when the redirect is “completed”, the user may"},{"text":" ","type":"text"},{"text":"have not actually completed the necessary actions to authorize the charge.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You should not use either this class, nor "},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":", as a way"},{"text":" ","type":"text"},{"text":"to determine when you should charge the Source or to determine if the redirect","type":"text"},{"type":"text","text":" "},{"type":"text","text":"was successful. Use Stripe webhooks on your backend server to listen for Source"},{"type":"text","text":" "},{"type":"text","text":"state changes and to make the charge."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","value":"STPRedirectContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"text":"STPRedirectContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","value":[{"text":"STPRedirectContext","kind":"identifier"}],"op":"replace"}]}]}