{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"abstract":[{"text":"Initializer for context from an ","type":"text"},{"type":"codeVoice","code":"STPSource"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","text":"STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"STPRedirectContextSourceCompletionBlock","preciseIdentifier":"s:14StripePayments39STPRedirectContextSourceCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextSourceCompletionBlock"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"content":[{"inlineContent":[{"text":"You must ensure that the returnURL set up in the created source","type":"text"},{"type":"text","text":" "},{"type":"text","text":"correctly goes to your app so that users can be returned once"},{"type":"text","text":" "},{"type":"text","text":"they complete the redirect in the web broswer."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameters:"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"source: The source that needs user redirect action to be taken."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"completion: A block to fire when the action is believed to have"},{"text":" ","type":"text"},{"text":"been completed.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns: nil if the specified source is not a redirect-flow source. Otherwise"},{"text":" ","type":"text"},{"text":"a new context object.","type":"text"}]}]}],"type":"unorderedList"}],"type":"aside","name":"Note","style":"note"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Execution of the completion block does not necessarily mean the user","type":"text"},{"type":"text","text":" "},{"type":"text","text":"successfully performed the redirect action. You should listen for source status"},{"text":" ","type":"text"},{"type":"text","text":"change webhooks on your backend to determine the result of a redirect."}]}],"name":"Note","type":"aside","style":"note"}]}],"metadata":{"title":"init(source:completion:)","externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(im)initWithSource:completion:","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithSource:completion:"}],"symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments39STPRedirectContextSourceCompletionBlocka","kind":"typeIdentifier","text":"STPRedirectContextSourceCompletionBlock"},{"kind":"text","text":")"}],"modules":[{"name":"StripePayments"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(source:completion:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/init(source:completion:)"]},{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/init(source:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"role":"symbol","title":"STPSource","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","abstract":[{"type":"text","text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources"}],"url":"\/documentation\/stripepayments\/stpsource","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSource","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextSourceCompletionBlock":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextSourceCompletionBlock","type":"topic","role":"symbol","abstract":[{"text":"A callback that is executed when the context believes the redirect action has been completed.","type":"text"}],"url":"\/documentation\/stripepayments\/stpredirectcontextsourcecompletionblock","title":"STPRedirectContextSourceCompletionBlock","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRedirectContextSourceCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextSourceCompletionBlock"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/init(source:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(source:completion:)","kind":"symbol","title":"init(source:completion:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"text":"STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments39STPRedirectContextSourceCompletionBlocka","text":"STPRedirectContextSourceCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"text":"Initializer for context from an ","type":"text"},{"type":"codeVoice","code":"STPSource"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"initWithSource:completion:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpredirectcontext\/init(source:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"type":"topic","kind":"symbol","title":"STPRedirectContext","role":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext","abstract":[{"text":"This is a helper class for handling redirects associated with STPSource and","type":"text"},{"type":"text","text":" "},{"text":"STPPaymentIntents.","type":"text"},{"type":"text","text":" "},{"text":"Init and retain an instance with the Source or PaymentIntent you want to handle,","type":"text"},{"type":"text","text":" "},{"text":"then choose a redirect method. The context will fire the completion handler","type":"text"},{"type":"text","text":" "},{"type":"text","text":"when the redirect completes."},{"type":"text","text":" "},{"text":"Due to the nature of iOS, very little concrete information can be gained","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"during this process, as all actions take place in either the Safari app"},{"type":"text","text":" "},{"text":"or the sandboxed SFSafariViewController class. The context attempts to","type":"text"},{"text":" ","type":"text"},{"text":"detect when the user has completed the necessary redirect action by listening","type":"text"},{"type":"text","text":" "},{"text":"for both app foregrounds and url callbacks received in the app delegate.","type":"text"},{"text":" ","type":"text"},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"have not actually completed the necessary actions to authorize the charge."},{"text":" ","type":"text"},{"text":"You should not use either this class, nor ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"text":", as a way","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to determine when you should charge the Source or to determine if the redirect"},{"text":" ","type":"text"},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"state changes and to make the charge."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContext"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithSource:completion:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSource:completion:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithSource:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"},{"kind":"text","text":" *) "},{"text":"source","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"STPSource","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title"},{"op":"replace","value":[{"text":"STPSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","value":[{"text":"STPSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1init(source:completion:)\/title","value":"initWithSource:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1init(source:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSource:completion:","kind":"identifier"}]},{"value":"STPRedirectContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPRedirectContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPRedirectContext"}],"op":"replace"}]}]}