{"kind":"symbol","abstract":[{"text":"Initializer for context from an ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This should be used when the ","type":"text"},{"code":"status","type":"codeVoice"},{"type":"text","text":" is "},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresAction"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If the next action involves a redirect, this init method will return a non-nil object."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/init(paymentintent:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/init(paymentintent:completion:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"paymentIntent"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments46STPRedirectContextPaymentIntentCompletionBlocka","text":"STPRedirectContextPaymentIntentCompletionBlock"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"paymentIntent","content":[{"inlineContent":[{"text":"The STPPaymentIntent that needs a redirect.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"A block to fire when the action is believed to have"},{"text":" ","type":"text"},{"text":"been completed.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"Execution of the completion block does not necessarily mean the user","type":"text"},{"text":" ","type":"text"},{"text":"successfully performed the redirect action.","type":"text"}]}],"type":"aside","style":"note"}]}],"sections":[],"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"paymentIntent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments46STPRedirectContextPaymentIntentCompletionBlocka","kind":"typeIdentifier","text":"STPRedirectContextPaymentIntentCompletionBlock"},{"kind":"text","text":")"}],"role":"symbol","title":"init(paymentIntent:completion:)","externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(im)initWithPaymentIntent:completion:","navigatorTitle":[{"text":"initWithPaymentIntent:completion:","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"init"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(paymentIntent:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextPaymentIntentCompletionBlock":{"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContextPaymentIntentCompletionBlock"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextPaymentIntentCompletionBlock","title":"STPRedirectContextPaymentIntentCompletionBlock","type":"topic","abstract":[{"text":"A callback that is executed when the context believes the redirect action has been completed.","type":"text"}],"url":"\/documentation\/stripepayments\/stpredirectcontextpaymentintentcompletionblock","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextPaymentIntentCompletionBlock"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/init(paymentIntent:completion:)":{"title":"init(paymentIntent:completion:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(paymentIntent:completion:)","url":"\/documentation\/stripepayments\/stpredirectcontext\/init(paymentintent:completion:)","abstract":[{"type":"text","text":"Initializer for context from an "},{"code":"STPPaymentIntent","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"This should be used when the ","type":"text"},{"code":"status","type":"codeVoice"},{"type":"text","text":" is "},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresAction"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the next action involves a redirect, this init method will return a non-nil object."}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"paymentIntent","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"STPRedirectContextPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments46STPRedirectContextPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithPaymentIntent:completion:","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntent"}],"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","url":"\/documentation\/stripepayments\/stppaymentintent","title":"STPPaymentIntent"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"kind":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","title":"STPRedirectContext","url":"\/documentation\/stripepayments\/stpredirectcontext","abstract":[{"text":"This is a helper class for handling redirects associated with STPSource and","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"STPPaymentIntents."},{"text":" ","type":"text"},{"type":"text","text":"Init and retain an instance with the Source or PaymentIntent you want to handle,"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"text":"when the redirect completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"text":" ","type":"text"},{"type":"text","text":"during this process, as all actions take place in either the Safari app"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"text":" ","type":"text"},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"type":"text","text":" "},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"text":" ","type":"text"},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"type":"text","text":" "},{"type":"text","text":"have not actually completed the necessary actions to authorize the charge."},{"text":" ","type":"text"},{"text":"You should not use either this class, nor ","type":"text"},{"code":"STPAPIClient","type":"codeVoice"},{"text":", as a way","type":"text"},{"type":"text","text":" "},{"text":"to determine when you should charge the Source or to determine if the redirect","type":"text"},{"text":" ","type":"text"},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"text":" ","type":"text"},{"text":"state changes and to make the charge.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithPaymentIntent:completion:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPaymentIntent:completion:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithPaymentIntent:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"},{"text":" *) ","kind":"text"},{"text":"paymentIntent","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The STPPaymentIntent that needs a redirect."}]}],"name":"paymentIntent"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"A block to fire when the action is believed to have","type":"text"},{"type":"text","text":" "},{"text":"been completed.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Nil if the provided PaymentIntent does not need a redirect. Otherwise"},{"type":"text","text":" "},{"type":"text","text":"a new context object."}],"type":"paragraph"}]},"op":"add","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1init(paymentIntent:completion:)\/title","value":"initWithPaymentIntent:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPaymentIntent:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1init(paymentIntent:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"text":"STPPaymentIntent","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle"},{"value":"STPRedirectContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"text":"STPRedirectContext","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPRedirectContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","op":"replace"}]}]}