{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentationController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPresented"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":"?, ","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPresentationController","text":"UIPresentationController"},{"kind":"text","text":"?"}],"title":"presentationController(forPresented:presenting:source:)","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(im)presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/presentationcontroller(forpresented:presenting:source:)"]},{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/presentationcontroller(forpresented:presenting:source:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/presentationController(forPresented:presenting:source:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"presentationController","kind":"identifier"},{"kind":"text","text":"("},{"text":"forPresented","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"presented"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"presenting","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPresentationController","text":"UIPresentationController"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"role":"symbol","title":"STPRedirectContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContext"}],"navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","type":"topic","abstract":[{"type":"text","text":"This is a helper class for handling redirects associated with STPSource and"},{"type":"text","text":" "},{"text":"STPPaymentIntents.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Init and retain an instance with the Source or PaymentIntent you want to handle,"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"text":" ","type":"text"},{"text":"when the redirect completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"text":" ","type":"text"},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"text":" ","type":"text"},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"type":"text","text":" "},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"text":" ","type":"text"},{"type":"text","text":"However, it is possible the when the redirect is “completed”, the user may"},{"text":" ","type":"text"},{"text":"have not actually completed the necessary actions to authorize the charge.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You should not use either this class, nor "},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":", as a way"},{"type":"text","text":" "},{"text":"to determine when you should charge the Source or to determine if the redirect","type":"text"},{"type":"text","text":" "},{"type":"text","text":"was successful. Use Stripe webhooks on your backend server to listen for Source"},{"type":"text","text":" "},{"type":"text","text":"state changes and to make the charge."}],"url":"\/documentation\/stripepayments\/stpredirectcontext"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/presentationController(forPresented:presenting:source:)":{"url":"\/documentation\/stripepayments\/stpredirectcontext\/presentationcontroller(forpresented:presenting:source:)","role":"symbol","navigatorTitle":[{"text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","kind":"identifier"}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"presenting","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/presentationController(forPresented:presenting:source:)","title":"presentationController(forPresented:presenting:source:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIPresentationController","text":"UIPresentationController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"presentationControllerForPresentedViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"presented"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentingViewController:"},{"kind":"text","text":"("},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"presenting"},{"kind":"text","text":" "},{"text":"sourceViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":" *) ","kind":"text"},{"text":"source","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"STPRedirectContext","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","op":"replace"},{"value":[{"text":"STPRedirectContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPRedirectContext"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1presentationController(forPresented:presenting:source:)\/title","value":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1presentationController(forPresented:presenting:source:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","kind":"identifier"}]}]}]}