{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"safariViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SFSafariViewController","kind":"typeIdentifier","text":"SFSafariViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCompleteInitialLoad"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"didLoadSuccessfully"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"safariViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteInitialLoad"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"safariViewController:didCompleteInitialLoad:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","extendedModule":"StripePayments","symbolKind":"method","modules":[{"name":"StripePayments"}],"title":"safariViewController(_:didCompleteInitialLoad:)","externalID":"c:@CM@StripePayments@objc(cs)STPRedirectContext(im)safariViewController:didCompleteInitialLoad:"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:didCompleteInitialLoad:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontroller(_:didcompleteinitialload:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontroller(_:didcompleteinitialload:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/SFSafariViewControllerDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations","kind":"article","url":"\/documentation\/stripepayments\/stpredirectcontext\/sfsafariviewcontrollerdelegate-implementations","title":"SFSafariViewControllerDelegate Implementations","abstract":[],"role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/safariViewController(_:didCompleteInitialLoad:)":{"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"safariViewController:didCompleteInitialLoad:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:didCompleteInitialLoad:)","url":"\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontroller(_:didcompleteinitialload:)","title":"safariViewController(_:didCompleteInitialLoad:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"safariViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SFSafariViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"text":", ","kind":"text"},{"text":"didCompleteInitialLoad","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext","title":"STPRedirectContext","abstract":[{"text":"This is a helper class for handling redirects associated with STPSource and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"STPPaymentIntents."},{"type":"text","text":" "},{"type":"text","text":"Init and retain an instance with the Source or PaymentIntent you want to handle,"},{"text":" ","type":"text"},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"type":"text","text":"when the redirect completes."},{"type":"text","text":" "},{"text":"Due to the nature of iOS, very little concrete information can be gained","type":"text"},{"type":"text","text":" "},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"text":" ","type":"text"},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"type":"text","text":" "},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"type":"text","text":" "},{"type":"text","text":"However, it is possible the when the redirect is “completed”, the user may"},{"text":" ","type":"text"},{"type":"text","text":"have not actually completed the necessary actions to authorize the charge."},{"type":"text","text":" "},{"text":"You should not use either this class, nor ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"text":", as a way","type":"text"},{"type":"text","text":" "},{"text":"to determine when you should charge the Source or to determine if the redirect","type":"text"},{"type":"text","text":" "},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"type":"text","text":" "},{"type":"text","text":"state changes and to make the charge."}],"role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"safariViewController:didCompleteInitialLoad:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"safariViewController:didCompleteInitialLoad:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"safariViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SFSafariViewController","kind":"typeIdentifier","text":"SFSafariViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCompleteInitialLoad:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"didLoadSuccessfully"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewController(_:didCompleteInitialLoad:)\/title","op":"replace","value":"safariViewController:didCompleteInitialLoad:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewController(_:didCompleteInitialLoad:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"safariViewController:didCompleteInitialLoad:","kind":"identifier"}]},{"op":"replace","value":"STPRedirectContext","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title"},{"op":"replace","value":[{"text":"STPRedirectContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","op":"replace","value":[{"text":"STPRedirectContext","kind":"identifier"}]}]}]}