{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"safariViewControllerDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":":nodoc:"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewControllerDidFinish(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontrollerdidfinish(_:)"]},{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontrollerdidfinish(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"safariViewControllerDidFinish:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"StripePayments"}],"symbolKind":"method","extendedModule":"StripePayments","externalID":"c:@CM@StripePayments@objc(cs)STPRedirectContext(im)safariViewControllerDidFinish:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"safariViewControllerDidFinish","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"safariViewControllerDidFinish(_:)"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/SFSafariViewControllerDelegate-Implementations":{"url":"\/documentation\/stripepayments\/stpredirectcontext\/sfsafariviewcontrollerdelegate-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic","title":"SFSafariViewControllerDelegate Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}],"title":"STPRedirectContext","kind":"symbol","abstract":[{"type":"text","text":"This is a helper class for handling redirects associated with STPSource and"},{"text":" ","type":"text"},{"type":"text","text":"STPPaymentIntents."},{"text":" ","type":"text"},{"type":"text","text":"Init and retain an instance with the Source or PaymentIntent you want to handle,"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"type":"text","text":"when the redirect completes."},{"type":"text","text":" "},{"text":"Due to the nature of iOS, very little concrete information can be gained","type":"text"},{"type":"text","text":" "},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"text":" ","type":"text"},{"text":"or the sandboxed SFSafariViewController class. The context attempts to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"text":" ","type":"text"},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"type":"text","text":" "},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"type":"text","text":" "},{"type":"text","text":"have not actually completed the necessary actions to authorize the charge."},{"text":" ","type":"text"},{"type":"text","text":"You should not use either this class, nor "},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":", as a way"},{"type":"text","text":" "},{"text":"to determine when you should charge the Source or to determine if the redirect","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"was successful. Use Stripe webhooks on your backend server to listen for Source"},{"type":"text","text":" "},{"type":"text","text":"state changes and to make the charge."}],"type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontext","role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/safariViewControllerDidFinish(_:)":{"title":"safariViewControllerDidFinish(_:)","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"safariViewControllerDidFinish"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewControllerDidFinish(_:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontrollerdidfinish(_:)","navigatorTitle":[{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"safariViewControllerDidFinish:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"safariViewControllerDidFinish:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"safariViewControllerDidFinish:"},{"kind":"text","text":"("},{"text":"SFSafariViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","value":"STPRedirectContext","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"text":"STPRedirectContext","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPRedirectContext"}]},{"op":"replace","value":"safariViewControllerDidFinish:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewControllerDidFinish(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"safariViewControllerDidFinish:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewControllerDidFinish(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}