{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/sfsafariviewcontrollerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/sfsafariviewcontrollerdelegate-implementations"]}],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:didCompleteInitialLoad:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:initialLoadDidRedirectTo:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewControllerDidFinish(_:)"],"title":"Instance Methods","generated":true}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"SFSafariViewControllerDelegate Implementations","modules":[{"name":"StripePayments"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/safariViewController(_:initialLoadDidRedirectTo:)":{"navigatorTitle":[{"kind":"identifier","text":"safariViewController:initialLoadDidRedirectToURL:"}],"url":"\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontroller(_:initialloaddidredirectto:)","role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safariViewController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"initialLoadDidRedirectTo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"title":"safariViewController(_:initialLoadDidRedirectTo:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:initialLoadDidRedirectTo:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/safariViewController(_:didCompleteInitialLoad:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"safariViewController:didCompleteInitialLoad:","kind":"identifier"}],"title":"safariViewController(_:didCompleteInitialLoad:)","url":"\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontroller(_:didcompleteinitialload:)","abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:didCompleteInitialLoad:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safariViewController"},{"text":"(","kind":"text"},{"text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCompleteInitialLoad"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"url":"\/documentation\/stripepayments\/stpredirectcontext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","title":"STPRedirectContext","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"abstract":[{"text":"This is a helper class for handling redirects associated with STPSource and","type":"text"},{"text":" ","type":"text"},{"text":"STPPaymentIntents.","type":"text"},{"text":" ","type":"text"},{"text":"Init and retain an instance with the Source or PaymentIntent you want to handle,","type":"text"},{"text":" ","type":"text"},{"text":"then choose a redirect method. The context will fire the completion handler","type":"text"},{"type":"text","text":" "},{"text":"when the redirect completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"type":"text","text":" "},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"type":"text","text":" "},{"text":"or the sandboxed SFSafariViewController class. The context attempts to","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"type":"text","text":" "},{"text":"for both app foregrounds and url callbacks received in the app delegate.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"However, it is possible the when the redirect is “completed”, the user may"},{"text":" ","type":"text"},{"text":"have not actually completed the necessary actions to authorize the charge.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You should not use either this class, nor "},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":", as a way"},{"text":" ","type":"text"},{"text":"to determine when you should charge the Source or to determine if the redirect","type":"text"},{"type":"text","text":" "},{"type":"text","text":"was successful. Use Stripe webhooks on your backend server to listen for Source"},{"type":"text","text":" "},{"type":"text","text":"state changes and to make the charge."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/safariViewControllerDidFinish(_:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontrollerdidfinish(_:)","abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","title":"safariViewControllerDidFinish(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"safariViewControllerDidFinish","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"safariViewControllerDidFinish:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewControllerDidFinish(_:)","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:didCompleteInitialLoad:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:initialLoadDidRedirectTo:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewControllerDidFinish(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"safariViewController:initialLoadDidRedirectToURL:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewController(_:initialLoadDidRedirectTo:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"safariViewController:initialLoadDidRedirectToURL:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewController(_:initialLoadDidRedirectTo:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewController(_:didCompleteInitialLoad:)\/title","op":"replace","value":"safariViewController:didCompleteInitialLoad:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"safariViewController:didCompleteInitialLoad:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewController(_:didCompleteInitialLoad:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","value":"STPRedirectContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"kind":"identifier","text":"STPRedirectContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","value":[{"text":"STPRedirectContext","kind":"identifier"}]},{"op":"replace","value":"safariViewControllerDidFinish:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewControllerDidFinish(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewControllerDidFinish(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"safariViewControllerDidFinish:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}