{"abstract":[{"type":"text","text":"Starts a redirect flow by calling "},{"code":"openURL","type":"codeVoice"},{"type":"text","text":" to bounce the user out to"},{"type":"text","text":" "},{"type":"text","text":"the Safari app."},{"text":" ","type":"text"},{"type":"text","text":"The context will listen for app open notifications and fire its completion"},{"type":"text","text":" "},{"type":"text","text":"block the next time the user re-opens the app (either manually or via url)"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/startsafariappredirectflow()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/startsafariappredirectflow()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"text":"startSafariAppRedirectFlow","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(im)startSafariAppRedirectFlow","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startSafariAppRedirectFlow"},{"kind":"text","text":"()"}],"title":"startSafariAppRedirectFlow()","roleHeading":"Instance Method","modules":[{"name":"StripePayments"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startSafariAppRedirectFlow","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"name":"Note","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method does nothing if the context is not in the"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPRedirectContextStateNotStarted"},{"type":"text","text":" state."}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariAppRedirectFlow()"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"title":"STPRedirectContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContext"}],"abstract":[{"type":"text","text":"This is a helper class for handling redirects associated with STPSource and"},{"type":"text","text":" "},{"text":"STPPaymentIntents.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Init and retain an instance with the Source or PaymentIntent you want to handle,"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"type":"text","text":"when the redirect completes."},{"text":" ","type":"text"},{"text":"Due to the nature of iOS, very little concrete information can be gained","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"during this process, as all actions take place in either the Safari app"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"type":"text","text":" "},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"text":" ","type":"text"},{"text":"for both app foregrounds and url callbacks received in the app delegate.","type":"text"},{"type":"text","text":" "},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"type":"text","text":" "},{"type":"text","text":"have not actually completed the necessary actions to authorize the charge."},{"type":"text","text":" "},{"type":"text","text":"You should not use either this class, nor "},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":", as a way"},{"type":"text","text":" "},{"type":"text","text":"to determine when you should charge the Source or to determine if the redirect"},{"type":"text","text":" "},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"text":" ","type":"text"},{"text":"state changes and to make the charge.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContext"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/startSafariAppRedirectFlow()":{"abstract":[{"text":"Starts a redirect flow by calling ","type":"text"},{"type":"codeVoice","code":"openURL"},{"text":" to bounce the user out to","type":"text"},{"text":" ","type":"text"},{"text":"the Safari app.","type":"text"},{"type":"text","text":" "},{"text":"The context will listen for app open notifications and fire its completion","type":"text"},{"type":"text","text":" "},{"type":"text","text":"block the next time the user re-opens the app (either manually or via url)"}],"url":"\/documentation\/stripepayments\/stpredirectcontext\/startsafariappredirectflow()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSafariAppRedirectFlow"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","title":"startSafariAppRedirectFlow()","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariAppRedirectFlow()","navigatorTitle":[{"kind":"identifier","text":"startSafariAppRedirectFlow"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"startSafariAppRedirectFlow"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startSafariAppRedirectFlow"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"startSafariAppRedirectFlow","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"STPRedirectContext","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"text":"STPRedirectContext","kind":"identifier"}]},{"value":[{"text":"STPRedirectContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startSafariAppRedirectFlow()\/title","value":"startSafariAppRedirectFlow","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startSafariAppRedirectFlow()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startSafariAppRedirectFlow"}]}]}]}