{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/startsafariviewcontrollerredirectflow(from:)"]},{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/startsafariviewcontrollerredirectflow(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(startSafariViewControllerRedirectFlowFromViewController:) "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startSafariViewControllerRedirectFlow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"presentingViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"content":[{"inlineContent":[{"text":"This method does nothing if the context is not in the","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPRedirectContextStateNotStarted"},{"type":"text","text":" state."}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter presentingViewController: The view controller to present the Safari"},{"type":"text","text":" "},{"text":"view controller from.","type":"text"}]}]}],"type":"unorderedList"}],"style":"note","type":"aside","name":"Note"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariViewControllerRedirectFlow(from:)"},"metadata":{"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(im)startSafariViewControllerRedirectFlowFromViewController:","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"startSafariViewControllerRedirectFlowFromViewController:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","title":"startSafariViewControllerRedirectFlow(from:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSafariViewControllerRedirectFlow"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"sections":[],"abstract":[{"text":"Starts a redirect flow by presenting an SFSafariViewController in your app","type":"text"},{"type":"text","text":" "},{"type":"text","text":"from the passed in view controller."},{"type":"text","text":" "},{"type":"text","text":"You must ensure that your app delegate listens for  the "},{"type":"codeVoice","code":"returnURL"},{"text":" that you","type":"text"},{"type":"text","text":" "},{"type":"text","text":"set on the Stripe object, and forwards it to the Stripe SDK so that the"},{"text":" ","type":"text"},{"text":"context can be notified when the redirect is completed and dismiss the","type":"text"},{"type":"text","text":" "},{"text":"view controller. See ","type":"text"},{"type":"codeVoice","code":"StripeAPI.handleStripeURLCallback(with url:)]"},{"text":" ","type":"text"},{"text":"The context will listen for both received URLs and app open notifications","type":"text"},{"type":"text","text":" "},{"text":"and fire its completion block when either the URL is received, or the next","type":"text"},{"text":" ","type":"text"},{"text":"time the app is foregrounded.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/startSafariViewControllerRedirectFlow(from:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startSafariViewControllerRedirectFlowFromViewController:"}],"abstract":[{"type":"text","text":"Starts a redirect flow by presenting an SFSafariViewController in your app"},{"text":" ","type":"text"},{"type":"text","text":"from the passed in view controller."},{"text":" ","type":"text"},{"type":"text","text":"You must ensure that your app delegate listens for  the "},{"type":"codeVoice","code":"returnURL"},{"text":" that you","type":"text"},{"type":"text","text":" "},{"type":"text","text":"set on the Stripe object, and forwards it to the Stripe SDK so that the"},{"type":"text","text":" "},{"text":"context can be notified when the redirect is completed and dismiss the","type":"text"},{"text":" ","type":"text"},{"text":"view controller. See ","type":"text"},{"code":"StripeAPI.handleStripeURLCallback(with url:)]","type":"codeVoice"},{"text":" ","type":"text"},{"text":"The context will listen for both received URLs and app open notifications","type":"text"},{"type":"text","text":" "},{"text":"and fire its completion block when either the URL is received, or the next","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"time the app is foregrounded."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariViewControllerRedirectFlow(from:)","title":"startSafariViewControllerRedirectFlow(from:)","url":"\/documentation\/stripepayments\/stpredirectcontext\/startsafariviewcontrollerredirectflow(from:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startSafariViewControllerRedirectFlow","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext","title":"STPRedirectContext","abstract":[{"text":"This is a helper class for handling redirects associated with STPSource and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"STPPaymentIntents."},{"type":"text","text":" "},{"type":"text","text":"Init and retain an instance with the Source or PaymentIntent you want to handle,"},{"text":" ","type":"text"},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"type":"text","text":"when the redirect completes."},{"type":"text","text":" "},{"text":"Due to the nature of iOS, very little concrete information can be gained","type":"text"},{"type":"text","text":" "},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"text":" ","type":"text"},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"type":"text","text":" "},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"type":"text","text":" "},{"type":"text","text":"However, it is possible the when the redirect is “completed”, the user may"},{"text":" ","type":"text"},{"type":"text","text":"have not actually completed the necessary actions to authorize the charge."},{"type":"text","text":" "},{"text":"You should not use either this class, nor ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"text":", as a way","type":"text"},{"type":"text","text":" "},{"text":"to determine when you should charge the Source or to determine if the redirect","type":"text"},{"type":"text","text":" "},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"type":"text","text":" "},{"type":"text","text":"state changes and to make the charge."}],"role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"startSafariViewControllerRedirectFlowFromViewController:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startSafariViewControllerRedirectFlowFromViewController:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"startSafariViewControllerRedirectFlowFromViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"presentingViewController"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"startSafariViewControllerRedirectFlowFromViewController:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startSafariViewControllerRedirectFlow(from:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startSafariViewControllerRedirectFlow(from:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startSafariViewControllerRedirectFlowFromViewController:","kind":"identifier"}],"op":"replace"},{"value":"STPRedirectContext","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"text":"STPRedirectContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPRedirectContext"}],"op":"replace"}]}]}