{"kind":"symbol","sections":[],"metadata":{"title":"startRedirectFlow(from:)","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"startRedirectFlowFromViewController:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(im)startRedirectFlowFromViewController:","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startRedirectFlow"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"abstract":[{"text":"Starts a redirect flow.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You must ensure that your app delegate listens for  the "},{"code":"returnURL","type":"codeVoice"},{"text":" that you","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"set on the Stripe object, and forwards it to the Stripe SDK so that the"},{"type":"text","text":" "},{"text":"context can be notified when the redirect is completed and dismiss the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"view controller. See "},{"type":"codeVoice","code":"StripeAPI.handleURLCallback(with url:)"},{"text":" ","type":"text"},{"type":"text","text":"The context will listen for both received URLs and app open notifications"},{"text":" ","type":"text"},{"type":"text","text":"and fire its completion block when either the URL is received, or the next"},{"text":" ","type":"text"},{"type":"text","text":"time the app is foregrounded."},{"type":"text","text":" "},{"type":"text","text":"The context will initiate the flow by presenting a SFSafariViewController"},{"type":"text","text":" "},{"type":"text","text":"instance from the passsed in view controller. If you want more manual control"},{"text":" ","type":"text"},{"text":"over the redirect method, you can use ","type":"text"},{"type":"codeVoice","code":"startSafariViewControllerRedirectFlowFromViewController"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"code":"startSafariAppRedirectFlow","type":"codeVoice"},{"text":" ","type":"text"},{"text":"If the redirect supports a native app, and that app is is installed on the user’s","type":"text"},{"text":" ","type":"text"},{"text":"device, this call will do a direct app-to-app redirect instead of showing","type":"text"},{"type":"text","text":" "},{"text":"a web url.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(startRedirectFlowFromViewController:) ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startRedirectFlow"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"presentingViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"This method does nothing if the context is not in the","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPRedirectContextStateNotStarted"},{"text":" state.","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"text":"Parameter presentingViewController: The view controller to present the Safari","type":"text"},{"type":"text","text":" "},{"text":"view controller from.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}],"name":"Note","type":"aside","style":"note"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpredirectcontext\/startredirectflow(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/startredirectflow(from:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startRedirectFlow(from:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContext"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","title":"STPRedirectContext","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpredirectcontext","type":"topic","abstract":[{"type":"text","text":"This is a helper class for handling redirects associated with STPSource and"},{"type":"text","text":" "},{"type":"text","text":"STPPaymentIntents."},{"text":" ","type":"text"},{"text":"Init and retain an instance with the Source or PaymentIntent you want to handle,","type":"text"},{"type":"text","text":" "},{"text":"then choose a redirect method. The context will fire the completion handler","type":"text"},{"text":" ","type":"text"},{"text":"when the redirect completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"text":" ","type":"text"},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"type":"text","text":" "},{"text":"detect when the user has completed the necessary redirect action by listening","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"type":"text","text":" "},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"have not actually completed the necessary actions to authorize the charge."},{"type":"text","text":" "},{"text":"You should not use either this class, nor ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"text":", as a way","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to determine when you should charge the Source or to determine if the redirect"},{"type":"text","text":" "},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"state changes and to make the charge."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/startRedirectFlow(from:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startRedirectFlow","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startRedirectFlow(from:)","title":"startRedirectFlow(from:)","navigatorTitle":[{"kind":"identifier","text":"startRedirectFlowFromViewController:"}],"url":"\/documentation\/stripepayments\/stpredirectcontext\/startredirectflow(from:)","type":"topic","abstract":[{"text":"Starts a redirect flow.","type":"text"},{"type":"text","text":" "},{"text":"You must ensure that your app delegate listens for  the ","type":"text"},{"type":"codeVoice","code":"returnURL"},{"type":"text","text":" that you"},{"type":"text","text":" "},{"text":"set on the Stripe object, and forwards it to the Stripe SDK so that the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"context can be notified when the redirect is completed and dismiss the"},{"type":"text","text":" "},{"text":"view controller. See ","type":"text"},{"type":"codeVoice","code":"StripeAPI.handleURLCallback(with url:)"},{"type":"text","text":" "},{"type":"text","text":"The context will listen for both received URLs and app open notifications"},{"type":"text","text":" "},{"type":"text","text":"and fire its completion block when either the URL is received, or the next"},{"text":" ","type":"text"},{"type":"text","text":"time the app is foregrounded."},{"type":"text","text":" "},{"text":"The context will initiate the flow by presenting a SFSafariViewController","type":"text"},{"text":" ","type":"text"},{"text":"instance from the passsed in view controller. If you want more manual control","type":"text"},{"type":"text","text":" "},{"type":"text","text":"over the redirect method, you can use "},{"code":"startSafariViewControllerRedirectFlowFromViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"or ","type":"text"},{"type":"codeVoice","code":"startSafariAppRedirectFlow"},{"text":" ","type":"text"},{"text":"If the redirect supports a native app, and that app is is installed on the user’s","type":"text"},{"type":"text","text":" "},{"type":"text","text":"device, this call will do a direct app-to-app redirect instead of showing"},{"type":"text","text":" "},{"text":"a web url.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"startRedirectFlowFromViewController:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startRedirectFlowFromViewController:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"startRedirectFlowFromViewController:"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"presentingViewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","value":"STPRedirectContext"},{"value":[{"text":"STPRedirectContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments"},{"value":[{"kind":"identifier","text":"STPRedirectContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle"},{"value":"startRedirectFlowFromViewController:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startRedirectFlow(from:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startRedirectFlow(from:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"startRedirectFlowFromViewController:"}]}]}]}