{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPRedirectContextState","text":"STPRedirectContextState","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/state","interfaceLanguage":"swift"},"abstract":[{"text":"The current state of the context.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/state"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/state"]}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPRedirectContextState","preciseIdentifier":"c:@M@StripePayments@E@STPRedirectContextState","kind":"typeIdentifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(py)state","role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"state"}],"title":"state"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"url":"\/documentation\/stripepayments\/stpredirectcontext","kind":"symbol","abstract":[{"text":"This is a helper class for handling redirects associated with STPSource and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"STPPaymentIntents."},{"type":"text","text":" "},{"text":"Init and retain an instance with the Source or PaymentIntent you want to handle,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"text":" ","type":"text"},{"text":"when the redirect completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"text":" ","type":"text"},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"type":"text","text":" "},{"text":"or the sandboxed SFSafariViewController class. The context attempts to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"text":" ","type":"text"},{"text":"for both app foregrounds and url callbacks received in the app delegate.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"However, it is possible the when the redirect is “completed”, the user may"},{"type":"text","text":" "},{"text":"have not actually completed the necessary actions to authorize the charge.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You should not use either this class, nor "},{"code":"STPAPIClient","type":"codeVoice"},{"text":", as a way","type":"text"},{"text":" ","type":"text"},{"text":"to determine when you should charge the Source or to determine if the redirect","type":"text"},{"type":"text","text":" "},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"state changes and to make the charge."}],"role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","title":"STPRedirectContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRedirectContext","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState":{"title":"STPRedirectContextState","abstract":[{"text":"Possible states for the redirect context to be in","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRedirectContextState","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextState"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState","role":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontextstate"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/state":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/state","title":"state","url":"\/documentation\/stripepayments\/stpredirectcontext\/state","abstract":[{"text":"The current state of the context.","type":"text"}],"navigatorTitle":[{"text":"state","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPRedirectContextState","preciseIdentifier":"c:@M@StripePayments@E@STPRedirectContextState","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"state","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"state","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState","text":"STPRedirectContextState","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPRedirectContextState"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"STPRedirectContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPRedirectContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments"},{"value":[{"kind":"identifier","text":"STPRedirectContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/title","value":"STPRedirectContextState","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/fragments","value":[{"text":"STPRedirectContextState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/navigatorTitle","value":[{"text":"STPRedirectContextState","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"state","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1state\/title"},{"value":[{"text":"state","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1state\/fragments","op":"replace"}]}]}