{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/CustomStringConvertible-Implementations"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/description"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"StripePayments"}],"title":"CustomStringConvertible Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/description":{"type":"topic","abstract":[],"title":"description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/description","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/description","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus","kind":"symbol","role":"symbol","title":"STPSourceCard3DSecureStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"The status of this card’s 3D Secure support."}],"navigatorTitle":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPSourceCard3DSecureStatus","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/title"},{"value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/navigatorTitle"}]}]}