{"abstract":[{"type":"text","text":"3D Secure is not supported on this card."}],"sections":[],"metadata":{"symbolKind":"case","title":"STPSourceCard3DSecureStatus.notSupported","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusNotSupported"}],"modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus@STPSourceCard3DSecureStatusNotSupported"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/notSupported","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/notsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/notsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/notSupported":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/notSupported","title":"STPSourceCard3DSecureStatus.notSupported","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusNotSupported"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"abstract":[{"type":"text","text":"3D Secure is not supported on this card."}],"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/notsupported"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus":{"title":"STPSourceCard3DSecureStatus","role":"symbol","navigatorTitle":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus","abstract":[{"type":"text","text":"The status of this card’s 3D Secure support."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPSourceCard3DSecureStatusNotSupported","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPSourceCard3DSecureStatusNotSupported","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusNotSupported"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPSourceCard3DSecureStatusNotSupported","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1notSupported\/title"},{"op":"replace","value":[{"text":"STPSourceCard3DSecureStatusNotSupported","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1notSupported\/fragments"},{"op":"replace","value":"STPSourceCard3DSecureStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/title"},{"op":"replace","value":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}