{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"3D Secure is optional. It is not required nor recommended for successful charging,","type":"text"},{"text":" ","type":"text"},{"text":"but can be performed to help reduce the likelihood of fraud.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optional"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"title":"STPSourceCard3DSecureStatus.optional","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optional","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusOptional"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus@STPSourceCard3DSecureStatusOptional","role":"symbol"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/optional"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/optional"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/optional"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/optional":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/optional","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/optional","navigatorTitle":[{"text":"STPSourceCard3DSecureStatusOptional","kind":"identifier"}],"title":"STPSourceCard3DSecureStatus.optional","abstract":[{"text":"3D Secure is optional. It is not required nor recommended for successful charging,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"but can be performed to help reduce the likelihood of fraud."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optional"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"title":"STPSourceCard3DSecureStatus","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus","navigatorTitle":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The status of this card’s 3D Secure support."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceCard3DSecureStatusOptional"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceCard3DSecureStatusOptional","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPSourceCard3DSecureStatusOptional","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1optional\/title","value":"STPSourceCard3DSecureStatusOptional","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1optional\/fragments","op":"replace","value":[{"text":"STPSourceCard3DSecureStatusOptional","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/title","op":"replace","value":"STPSourceCard3DSecureStatus"},{"op":"replace","value":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}