{"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/recommended"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/recommended"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"3D Secure is recommended. The process is not required, but it is highly recommended"},{"type":"text","text":" "},{"type":"text","text":"and has minimal impact to your conversion rate."}],"metadata":{"roleHeading":"Case","title":"STPSourceCard3DSecureStatus.recommended","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus@STPSourceCard3DSecureStatusRecommended","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusRecommended"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"recommended"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/recommended"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recommended","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/recommended":{"type":"topic","navigatorTitle":[{"text":"STPSourceCard3DSecureStatusRecommended","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"STPSourceCard3DSecureStatus.recommended","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/recommended","abstract":[{"type":"text","text":"3D Secure is recommended. The process is not required, but it is highly recommended"},{"type":"text","text":" "},{"type":"text","text":"and has minimal impact to your conversion rate."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/recommended","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recommended","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus","navigatorTitle":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"title":"STPSourceCard3DSecureStatus","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"type":"topic","abstract":[{"text":"The status of this card’s 3D Secure support.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPSourceCard3DSecureStatusRecommended","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceCard3DSecureStatusRecommended","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSourceCard3DSecureStatusRecommended","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1recommended\/title","value":"STPSourceCard3DSecureStatusRecommended","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1recommended\/fragments","value":[{"text":"STPSourceCard3DSecureStatusRecommended","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/title","value":"STPSourceCard3DSecureStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}