{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/required"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"]]},"abstract":[{"text":"3D Secure is required. This card must be converted into a 3D Secure","type":"text"},{"text":" ","type":"text"},{"text":"source for a charge on it to be successful.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/required"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/required"]}],"metadata":{"externalID":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus@STPSourceCard3DSecureStatusRequired","modules":[{"name":"StripePayments"}],"title":"STPSourceCard3DSecureStatus.required","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"STPSourceCard3DSecureStatusRequired","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus","title":"STPSourceCard3DSecureStatus","abstract":[{"text":"The status of this card’s 3D Secure support.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/required":{"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/required","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/required","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"abstract":[{"text":"3D Secure is required. This card must be converted into a 3D Secure","type":"text"},{"text":" ","type":"text"},{"text":"source for a charge on it to be successful.","type":"text"}],"kind":"symbol","type":"topic","title":"STPSourceCard3DSecureStatus.required","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusRequired"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceCard3DSecureStatusRequired"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusRequired"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusRequired"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/title","value":"STPSourceCard3DSecureStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1required\/title","value":"STPSourceCard3DSecureStatusRequired"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1required\/fragments","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusRequired"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}