{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/unknown"]},{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus@STPSourceCard3DSecureStatusUnknown","symbolKind":"case","modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusUnknown"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"roleHeading":"Case","title":"STPSourceCard3DSecureStatus.unknown"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/unknown","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"text":"The status of 3D Secure support on this card is unknown.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/unknown":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The status of 3D Secure support on this card is unknown."}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusUnknown"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/unknown","type":"topic","title":"STPSourceCard3DSecureStatus.unknown","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus":{"role":"symbol","abstract":[{"type":"text","text":"The status of this card’s 3D Secure support."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"title":"STPSourceCard3DSecureStatus","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPSourceCard3DSecureStatusUnknown","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusUnknown"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusUnknown"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"STPSourceCard3DSecureStatusUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1unknown\/title"},{"value":[{"text":"STPSourceCard3DSecureStatusUnknown","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1unknown\/fragments"},{"value":"STPSourceCard3DSecureStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/fragments","op":"replace","value":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}]},{"value":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/navigatorTitle"}]}]}