{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/STPAPIResponseDecodable-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/decodedobject(fromapiresponse:)"]}],"sections":[],"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"roleHeading":"Type Method","extendedModule":"StripePayments","modules":[{"name":"StripePayments"}],"externalID":"c:@CM@StripePayments@objc(cs)STPIntentActionPromptPayDisplayQrCode(cm)decodedObjectFromAPIResponse:","title":"decodedObject(fromAPIResponse:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"response"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}],"type":"paragraph"}],"name":"response"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The object represented by the JSON dictionary, or nil if the object"},{"text":" ","type":"text"},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"text":" is nil).","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode/STPAPIResponseDecodable-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/stpapiresponsedecodable-implementations","title":"STPAPIResponseDecodable Implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/STPAPIResponseDecodable-Implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode/decodedObject(fromAPIResponse:)":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/decodedobject(fromapiresponse:)","title":"decodedObject(fromAPIResponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode":{"kind":"symbol","abstract":[{"type":"text","text":"Contains instructions for presenting the QR code required to complete a PromptPay payment."},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentActionPromptPayDisplayQrCode","type":"codeVoice"},{"text":".","type":"text"}],"title":"STPIntentActionPromptPayDisplayQrCode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionPromptPayDisplayQrCode"}],"url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"decodedObjectFromAPIResponse:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"response","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/title","op":"replace","value":"STPIntentActionPromptPayDisplayQrCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/fragments","value":[{"kind":"identifier","text":"STPIntentActionPromptPayDisplayQrCode"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/navigatorTitle","op":"replace","value":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}