{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"hostedInstructionsURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/hostedInstructionsURL"},"abstract":[{"type":"text","text":"The URL to open which contains instructions on how to complete the payment."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/hostedinstructionsurl"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/hostedinstructionsurl"]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostedInstructionsURL"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionPromptPayDisplayQrCode(py)hostedInstructionsURL","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hostedInstructionsURL"}],"title":"hostedInstructionsURL","modules":[{"name":"StripePayments"}]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode":{"title":"STPIntentActionPromptPayDisplayQrCode","kind":"symbol","abstract":[{"text":"Contains instructions for presenting the QR code required to complete a PromptPay payment.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentActionPromptPayDisplayQrCode"},{"text":".","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode/hostedInstructionsURL":{"title":"hostedInstructionsURL","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/hostedinstructionsurl","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/hostedInstructionsURL","navigatorTitle":[{"text":"hostedInstructionsURL","kind":"identifier"}],"abstract":[{"type":"text","text":"The URL to open which contains instructions on how to complete the payment."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"hostedInstructionsURL","kind":"identifier"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hostedInstructionsURL"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"hostedInstructionsURL"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" * "},{"kind":"identifier","text":"hostedInstructionsURL"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPIntentActionPromptPayDisplayQrCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/title"},{"value":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/navigatorTitle","value":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1hostedInstructionsURL\/title","op":"replace","value":"hostedInstructionsURL"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1hostedInstructionsURL\/fragments","op":"replace","value":[{"kind":"identifier","text":"hostedInstructionsURL"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}