{"abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"type":"codeVoice","code":"expMonth"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAmazonPayParams"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAmazonPayParams\/propertyNamesToFormFieldNamesMapping()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodamazonpayparams\/propertynamestoformfieldnamesmapping()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodamazonpayparams\/propertynamestoformfieldnamesmapping()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAmazonPayParams(cm)propertyNamesToFormFieldNamesMapping","navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"role":"symbol","modules":[{"name":"StripePayments"}],"title":"propertyNamesToFormFieldNamesMapping()","symbolKind":"method"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAmazonPayParams/propertyNamesToFormFieldNamesMapping()":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"url":"\/documentation\/stripepayments\/stppaymentmethodamazonpayparams\/propertynamestoformfieldnamesmapping()","type":"topic","kind":"symbol","title":"propertyNamesToFormFieldNamesMapping()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAmazonPayParams\/propertyNamesToFormFieldNamesMapping()","navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"type":"codeVoice","code":"expMonth"},{"text":", but the Stripe API expects a field called ","type":"text"},{"type":"codeVoice","code":"exp_month"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAmazonPayParams":{"title":"STPPaymentMethodAmazonPayParams","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodAmazonPayParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAmazonPayParams"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodamazonpayparams","abstract":[{"type":"text","text":"An object representing parameters used to create a AmazonPay Payment Method"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAmazonPayParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"propertyNamesToFormFieldNamesMapping","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"propertyNamesToFormFieldNamesMapping","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAmazonPayParams~1propertyNamesToFormFieldNamesMapping()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAmazonPayParams~1propertyNamesToFormFieldNamesMapping()\/fragments"},{"value":"STPPaymentMethodAmazonPayParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAmazonPayParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAmazonPayParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodAmazonPayParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAmazonPayParams\/navigatorTitle","value":[{"text":"STPPaymentMethodAmazonPayParams","kind":"identifier"}]}]}]}