{"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPContactField(cpy)emailAddress","title":"emailAddress","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"emailAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","kind":"typeIdentifier"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"emailAddress","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcontactfield\/emailaddress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcontactfield\/emailaddress"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/emailAddress"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"emailAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","text":"STPContactField","kind":"typeIdentifier"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"The contact’s email address"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/emailAddress":{"url":"\/documentation\/stripepayments\/stpcontactfield\/emailaddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/emailAddress","kind":"symbol","navigatorTitle":[{"text":"emailAddress","kind":"identifier"}],"title":"emailAddress","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"emailAddress"},{"text":": ","kind":"text"},{"text":"STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","kind":"typeIdentifier"}],"abstract":[{"text":"The contact’s email address","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField":{"url":"\/documentation\/stripepayments\/stpcontactfield","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","kind":"symbol","navigatorTitle":[{"text":"STPContactField","kind":"identifier"}],"title":"STPContactField","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPContactField"}],"abstract":[{"text":"Contains constants that represent different parts of a users contact\/address information.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"emailAddress","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"emailAddress","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","text":"STPContactField","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"emailAddress"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1emailAddress\/title","value":"emailAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1emailAddress\/fragments","value":[{"kind":"identifier","text":"emailAddress"}]},{"op":"replace","value":"STPContactField","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/fragments","value":[{"text":"STPContactField","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPContactField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/navigatorTitle"}]}]}