{"sections":[],"abstract":[{"text":"The contact’s name.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcontactfield\/name"]},{"paths":["\/documentation\/stripepayments\/stpcontactfield\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"name"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPContactField(cpy)name","symbolKind":"property","role":"symbol","title":"name","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"text":"STPContactField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}],"roleHeading":"Type Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPContactField","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/name","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/name":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/name","type":"topic","abstract":[{"text":"The contact’s name.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcontactfield\/name","title":"name","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"text":"STPContactField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}],"navigatorTitle":[{"kind":"identifier","text":"name"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","type":"topic","abstract":[{"text":"Contains constants that represent different parts of a users contact\/address information.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcontactfield","title":"STPContactField","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPContactField"}],"navigatorTitle":[{"text":"STPContactField","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"name"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"name","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"STPContactField","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"},{"text":" * ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"name","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1name\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1name\/fragments","value":[{"kind":"identifier","text":"name"}]},{"value":"STPContactField","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/fragments","value":[{"text":"STPContactField","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPContactField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}