{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/phoneNumber"},"sections":[],"metadata":{"navigatorTitle":[{"text":"phoneNumber","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"phoneNumber","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","text":"STPContactField"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPContactField(cpy)phoneNumber"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","text":"STPContactField"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"abstract":[{"text":"The contact’s phone number.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcontactfield\/phonenumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcontactfield\/phonenumber"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/phoneNumber":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"phoneNumber"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/phoneNumber","title":"phoneNumber","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}],"abstract":[{"text":"The contact’s phone number.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcontactfield\/phonenumber"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPContactField"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","title":"STPContactField","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPContactField"}],"abstract":[{"text":"Contains constants that represent different parts of a users contact\/address information.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcontactfield"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"phoneNumber","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"phoneNumber"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","kind":"typeIdentifier","text":"STPContactField","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField"},{"kind":"text","text":" * "},{"kind":"identifier","text":"phoneNumber"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"phoneNumber","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1phoneNumber\/title"},{"value":[{"kind":"identifier","text":"phoneNumber"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1phoneNumber\/fragments"},{"value":"STPContactField","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/title"},{"value":[{"kind":"identifier","text":"STPContactField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/fragments"},{"value":[{"kind":"identifier","text":"STPContactField"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}