{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField"]]},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPContactField(cpy)postalAddress","symbolKind":"property","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"postalAddress","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"postalAddress","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPContactField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}],"title":"postalAddress","roleHeading":"Type Property"},"abstract":[{"type":"text","text":"The contact’s full physical address."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcontactfield\/postaladdress"]},{"paths":["\/documentation\/stripepayments\/stpcontactfield\/postaladdress"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"postalAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","kind":"typeIdentifier","text":"STPContactField"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/postalAddress","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Contains constants that represent different parts of a users contact\/address information."}],"url":"\/documentation\/stripepayments\/stpcontactfield","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPContactField","kind":"identifier"}],"title":"STPContactField","navigatorTitle":[{"kind":"identifier","text":"STPContactField"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/postalAddress":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The contact’s full physical address."}],"navigatorTitle":[{"kind":"identifier","text":"postalAddress"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalAddress"},{"text":": ","kind":"text"},{"text":"STPContactField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcontactfield\/postaladdress","title":"postalAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/postalAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"postalAddress"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"postalAddress","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","text":"STPContactField"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"postalAddress"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/title","value":"STPContactField"},{"value":[{"text":"STPContactField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/navigatorTitle","value":[{"text":"STPContactField","kind":"identifier"}],"op":"replace"},{"value":"postalAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1postalAddress\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1postalAddress\/fragments","op":"replace","value":[{"text":"postalAddress","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}