{"variants":[{"paths":["\/documentation\/stripepayments\/stpcontactfield\/rawvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:14StripePayments15STPContactFieldC8rawValueSSvp","symbolKind":"property","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawValue"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","title":"rawValue"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/rawValue","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.rawValue","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/rawValue":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/stripepayments\/stpcontactfield\/rawvalue","type":"topic","title":"rawValue","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/rawValue"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Contains constants that represent different parts of a users contact\/address information."}],"url":"\/documentation\/stripepayments\/stpcontactfield","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPContactField","kind":"identifier"}],"title":"STPContactField","navigatorTitle":[{"kind":"identifier","text":"STPContactField"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPContactField","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/title"},{"value":[{"kind":"identifier","text":"STPContactField"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/navigatorTitle","value":[{"kind":"identifier","text":"STPContactField"}]}]}]}