{"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/init(companyName:)"],"title":"Initializers","anchor":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/becsDebitFormDelegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formBackgroundColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formFont","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formTextColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/paymentMethodParams"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)"]}],"abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"type":"text","text":" "},{"type":"text","text":"For additional customization options - seealso: STPFormTextFieldContainer"}],"kind":"symbol","sections":[],"metadata":{"title":"STPAUBECSDebitFormView","symbolKind":"class","roleHeading":"Class","modules":[{"name":"StripePaymentsUI"}],"role":"symbol","externalID":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView","navigatorTitle":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAUBECSDebitFormView","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"],"kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)CALayerDelegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/SQ","doc:\/\/com.stripe.stripe-payments-ui\/SH","doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearance","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UICoordinateSpace","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIDynamicItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItemContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UILargeContentViewerItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIScrollViewDelegate","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextFieldDelegate","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextViewDelegate","doc:\/\/com.stripe.stripe-payments-ui\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments-ui/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"kind":"symbol","title":"STPFormTextFieldContainer","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","navigatorTitle":[{"kind":"identifier","text":"STPFormTextFieldContainer"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","abstract":[{"text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormTextFieldContainer","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"systemLayoutSizeFitting","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"text":"withHorizontalFittingPriority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UILayoutPriority","kind":"typeIdentifier","preciseIdentifier":"c:@T@UILayoutPriority"},{"kind":"text","text":", "},{"text":"verticalFittingPriority","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UILayoutPriority","text":"UILayoutPriority","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"title":"systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/systemlayoutsizefitting(_:withhorizontalfittingpriority:verticalfittingpriority:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"title":"STPMultiFormTextField","type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMultiFormTextField"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","abstract":[{"text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPMultiFormTextField"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIScrollViewDelegate":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIScrollViewDelegate","type":"unresolvable","title":"UIKit.UIScrollViewDelegate"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/formFont":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formFont","type":"topic","abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"text":"formFont","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/formfont","role":"symbol","title":"formFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"formFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://com.stripe.stripe-payments-ui/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://com.stripe.stripe-payments-ui/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/paymentMethodParams":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":"?","kind":"text"}],"title":"paymentMethodParams","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"This property will return a non-nil value if and only if the form is in a complete state. The ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":" instance","type":"text"},{"type":"text","text":" "},{"text":"will have it’s ","type":"text"},{"code":"auBECSDebit","type":"codeVoice"},{"type":"text","text":" property populated with the values input in this form."}],"navigatorTitle":[{"kind":"identifier","text":"paymentMethodParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/paymentMethodParams","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/paymentmethodparams"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"title":"STPAUBECSDebitFormView","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"type":"text","text":" "},{"type":"text","text":"For additional customization options - seealso: STPFormTextFieldContainer"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"navigatorTitle":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments-ui/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/becsDebitFormDelegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"becsDebitFormDelegate"},{"kind":"text","text":": "},{"text":"STPAUBECSDebitFormViewDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(pl)STPAUBECSDebitFormViewDelegate"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/becsDebitFormDelegate","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/becsdebitformdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"becsDebitFormDelegate"}],"type":"topic","abstract":[{"type":"text","text":"The delegate to inform about changes to this STPAUBECSDebitFormView instance."}],"title":"becsDebitFormDelegate"},"doc://com.stripe.stripe-payments-ui/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/init(companyName:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"companyName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(companyName:)","navigatorTitle":[{"text":"initWithCompanyName:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/init(companyName:)","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/init(companyname:)","abstract":[]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/formTextColor":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formTextColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"formTextColor","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"text":"formTextColor","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formTextColor","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/formtextcolor"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/formBackgroundColor":{"abstract":[{"type":"text","text":"The background color for the form text fields. Defaults to .systemBackground on iOS 13.0 and later, .white on earlier iOS versions."}],"title":"formBackgroundColor","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/formbackgroundcolor","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formBackgroundColor","navigatorTitle":[{"kind":"identifier","text":"formBackgroundColor"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-payments-ui/objc(pl)UITextViewDelegate":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextViewDelegate","type":"unresolvable","title":"UITextViewDelegate"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSCoding":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://com.stripe.stripe-payments-ui/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UITextFieldDelegate":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextFieldDelegate","type":"unresolvable","title":"UIKit.UITextFieldDelegate"},"doc://com.stripe.stripe-payments-ui/s8SendableP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPAUBECSDebitFormView","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/becsDebitFormDelegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formBackgroundColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formFont","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formTextColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/paymentMethodParams"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/init(companyName:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)"],"generated":true,"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextViewDelegate"],"type":"conformsTo","kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPAUBECSDebitFormView","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField","text":"STPMultiFormTextField"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title","value":"STPFormTextFieldContainer","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments","value":[{"kind":"identifier","text":"STPFormTextFieldContainer"}],"op":"replace"},{"value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle"},{"value":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField","op":"replace"},{"value":[{"text":"STPMultiFormTextField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPMultiFormTextField"}],"op":"replace"},{"value":"formFont","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1formFont\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1formFont\/fragments","value":[{"text":"formFont","kind":"identifier"}],"op":"replace"},{"value":"paymentMethodParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1paymentMethodParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1paymentMethodParams\/fragments","value":[{"kind":"identifier","text":"paymentMethodParams"}],"op":"replace"},{"value":"STPAUBECSDebitFormView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title"},{"value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1becsDebitFormDelegate\/title","value":"becsDebitFormDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1becsDebitFormDelegate\/fragments","value":[{"kind":"identifier","text":"becsDebitFormDelegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1init(companyName:)\/title","value":"initWithCompanyName:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCompanyName:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1init(companyName:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1formTextColor\/title","op":"replace","value":"formTextColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1formTextColor\/fragments","value":[{"text":"formTextColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1formBackgroundColor\/title","value":"formBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1formBackgroundColor\/fragments","value":[{"kind":"identifier","text":"formBackgroundColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}