{"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol","role":"symbol","navigatorTitle":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"modules":[{"name":"StripePaymentsUI"}],"externalID":"c:@M@StripePaymentsUI@objc(pl)STPAUBECSDebitFormViewDelegate","title":"STPAUBECSDebitFormViewDelegate"},"abstract":[{"text":"STPAUBECSDebitFormViewDelegate provides methods for STPAUBECSDebitFormView to inform its delegate","type":"text"},{"text":" ","type":"text"},{"text":"of when the form has been completed.","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate\/auBECSDebitForm(_:didChangeToStateComplete:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormViewDelegate/auBECSDebitForm(_:didChangeToStateComplete:)":{"abstract":[{"type":"text","text":"Called when the form transitions from complete to incomplete or vice-versa."}],"kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"auBECSDebitForm:didChangeToStateComplete:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"auBECSDebitForm"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView","text":"STPAUBECSDebitFormView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeToStateComplete"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate\/auBECSDebitForm(_:didChangeToStateComplete:)","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate\/aubecsdebitform(_:didchangetostatecomplete:)","title":"auBECSDebitForm(_:didChangeToStateComplete:)","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormViewDelegate":{"navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate","type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"}],"title":"STPAUBECSDebitFormViewDelegate","abstract":[{"type":"text","text":"STPAUBECSDebitFormViewDelegate provides methods for STPAUBECSDebitFormView to inform its delegate"},{"type":"text","text":" "},{"type":"text","text":"of when the form has been completed."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","role":"collection","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"STPAUBECSDebitFormViewDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate\/auBECSDebitForm(_:didChangeToStateComplete:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"auBECSDebitForm:didChangeToStateComplete:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate~1auBECSDebitForm(_:didChangeToStateComplete:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"auBECSDebitForm:didChangeToStateComplete:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate~1auBECSDebitForm(_:didChangeToStateComplete:)\/fragments"},{"value":"STPAUBECSDebitFormViewDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/title"},{"value":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/fragments"},{"value":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}