{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" provides a multiline interface for users to input their"},{"type":"text","text":" "},{"type":"text","text":"credit card details as well as billing postal code and provides an interface to access"},{"text":" ","type":"text"},{"type":"text","text":"the created "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":".","type":"text"},{"text":" ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"type":"text","text":" "},{"text":"is displayed when invalid input is detected.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformview"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardFormView","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardFormView","kind":"identifier"}],"roleHeading":"Class","title":"STPCardFormView","modules":[{"name":"StripePaymentsUI"}],"role":"symbol","externalID":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView","symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)CALayerDelegate","doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/SQ","doc:\/\/com.stripe.stripe-payments-ui\/SH","doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearance","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UICoordinateSpace","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIDynamicItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItemContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UILargeContentViewerItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-payments-ui\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIUserActivityRestoring"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Coordinator"],"anchor":"Classes","title":"Classes"},{"title":"Structures","anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable"]},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/init(style:)"],"title":"Initializers","anchor":"Initializers"},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/backgroundColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/cardParams","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/delegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/disabledBackgroundColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/isUserInteractionEnabled","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/onBehalfOf","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/preferredNetworks-swift.property"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/preferredNetworks_objc()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/setPreferredNetworks_objc(preferredNetworks:)"],"generated":true}],"references":{"https://docs.stripe.com/connect/charges#on_behalf_of":{"url":"https:\/\/docs.stripe.com\/connect\/charges#on_behalf_of","type":"link","identifier":"https:\/\/docs.stripe.com\/connect\/charges#on_behalf_of","titleInlineContent":[{"type":"text","text":"use cases"}],"title":"use cases"},"doc://com.stripe.stripe-payments-ui/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Representable"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Representable"}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable","title":"STPCardFormView.Representable","abstract":[{"type":"text","text":"A SwiftUI representation of STPCardFormView"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-payments-ui/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Coordinator":{"title":"STPCardFormView.Coordinator","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Coordinator","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Coordinator","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/coordinator"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/init(style:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle","text":"STPCardFormViewStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Public initializer for "},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":"."}],"title":"init(style:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/init(style:)","url":"\/documentation\/stripepaymentsui\/stpcardformview\/init(style:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithStyle:","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.stripe.stripe-payments-ui/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/5UIKit23UITraitChangeObservableP"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusItem":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/preferredNetworks_objc()":{"title":"preferredNetworks_objc()","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredNetworks_objc"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"]?","kind":"text"}],"abstract":[{"type":"text","text":"The list of preferred networks that should be used to process"},{"type":"text","text":" "},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"text":" ","type":"text"},{"text":"network themselves.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/preferrednetworks_objc()","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/preferredNetworks_objc()","navigatorTitle":[{"text":"preferredNetworks","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/cardParams":{"title":"cardParams","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardParams"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams"},{"text":"?","kind":"text"}],"abstract":[{"text":"A configured ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"text":" with the entered card number, expiration date, cvc, and","type":"text"},{"type":"text","text":" "},{"type":"text","text":"postal code (if applicable). If any field is invalid or incomplete then this property will return "},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"You can monitor when ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"text":" has complete details by implementing","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPFormViewDelegate"},{"text":" and setting the ","type":"text"},{"code":"STPCardFormView's","type":"codeVoice"},{"type":"text","text":" "},{"type":"codeVoice","code":"delegate"},{"text":" ","type":"text"},{"text":"property.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/cardparams","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/cardParams","navigatorTitle":[{"text":"cardParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/disabledBackgroundColor":{"title":"disabledBackgroundColor","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disabledBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"text":"The background color that is automatically applied to the input fields when  ","type":"text"},{"code":"isUserInteractionEnabled","type":"codeVoice"},{"text":" is set to `false.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/disabledbackgroundcolor","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/disabledBackgroundColor","navigatorTitle":[{"text":"disabledBackgroundColor","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UICoordinateSpace"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/backgroundColor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/backgroundColor","title":"backgroundColor","url":"\/documentation\/stripepaymentsui\/stpcardformview\/backgroundcolor","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/isUserInteractionEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isUserInteractionEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"title":"isUserInteractionEnabled","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/isUserInteractionEnabled","url":"\/documentation\/stripepaymentsui\/stpcardformview\/isuserinteractionenabled","type":"topic","role":"symbol","navigatorTitle":[{"text":"userInteractionEnabled","kind":"identifier"}]},"https://docs.stripe.com/api/payment_intents/create#create_payment_intent-on_behalf_of":{"url":"https:\/\/docs.stripe.com\/api\/payment_intents\/create#create_payment_intent-on_behalf_of","type":"link","identifier":"https:\/\/docs.stripe.com\/api\/payment_intents\/create#create_payment_intent-on_behalf_of","titleInlineContent":[{"text":"on_behalf_of","type":"text"}],"title":"on_behalf_of"},"doc://com.stripe.stripe-payments-ui/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" provides a multiline interface for users to input their"},{"text":" ","type":"text"},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"type":"text","text":" "},{"text":"the created ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"type":"text","text":" "},{"text":"is displayed when invalid input is detected.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui\/stpcardformview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"title":"STPCardFormView","role":"symbol"},"doc://com.stripe.stripe-payments-ui/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView":{"url":"\/documentation\/stripepaymentsui\/stpformview","title":"STPFormView","navigatorTitle":[{"kind":"identifier","text":"STPFormView"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","abstract":[{"code":"STPFormView","type":"codeVoice"},{"type":"text","text":" is a base class for the Stripe SDK’s form input UI. You should use one of the available subclasses"},{"type":"text","text":" "},{"type":"text","text":"("},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":") rather than instantiating an "},{"code":"STPFormView","type":"codeVoice"},{"text":" instance directly.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFormView","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/s8SendableP":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/onBehalfOf":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"onBehalfOf","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"The account (if any) for which the funds of the intent are intended.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The Stripe account ID (if any) which is the business of record."},{"text":" ","type":"text"},{"text":"See ","type":"text"},{"identifier":"https:\/\/docs.stripe.com\/connect\/charges#on_behalf_of","isActive":true,"type":"reference"},{"text":" to determine if this option is relevant for your integration.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This should match the "},{"type":"reference","identifier":"https:\/\/docs.stripe.com\/api\/payment_intents\/create#create_payment_intent-on_behalf_of","isActive":true},{"text":" ","type":"text"},{"text":"provided on the Intent used when confirming payment.","type":"text"}],"title":"onBehalfOf","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/onBehalfOf","url":"\/documentation\/stripepaymentsui\/stpcardformview\/onbehalfof","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments-ui/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/preferredNetworks-swift.property":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredNetworks","kind":"identifier"},{"kind":"text","text":": ["},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":"]?","kind":"text"}],"kind":"symbol","abstract":[{"text":"The list of preferred networks that should be used to process","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"type":"text","text":" "},{"text":"network themselves.","type":"text"}],"title":"preferredNetworks","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/preferredNetworks-swift.property","url":"\/documentation\/stripepaymentsui\/stpcardformview\/preferrednetworks-swift.property","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/setPreferredNetworks_objc(preferredNetworks:)":{"role":"symbol","abstract":[{"text":"The list of preferred networks that should be used to process","type":"text"},{"type":"text","text":" "},{"type":"text","text":"payments made with a co-branded card if your user hasn’t selected a"},{"text":" ","type":"text"},{"text":"network themselves.","type":"text"}],"kind":"symbol","title":"setPreferredNetworks_objc(preferredNetworks:)","navigatorTitle":[{"kind":"identifier","text":"setPreferredNetworks:"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/setpreferrednetworks_objc(preferrednetworks:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/setPreferredNetworks_objc(preferredNetworks:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPreferredNetworks_objc"},{"text":"(","kind":"text"},{"text":"preferredNetworks","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/delegate":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPCardFormViewDelegate","preciseIdentifier":"c:@M@StripePaymentsUI@objc(pl)STPCardFormViewDelegate"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"The delegate to notify when the card form transitions to or from being complete.","type":"text"}],"title":"delegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/delegate","url":"\/documentation\/stripepaymentsui\/stpcardformview\/delegate","type":"topic","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIDynamicItem","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPCardFormView","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"STPCardFormView","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPCardFormView","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/backgroundColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/cardParams","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/delegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/disabledBackgroundColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/isUserInteractionEnabled"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/init(style:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/preferredNetworks_objc()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/setPreferredNetworks_objc(preferredNetworks:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","text":"STPFormView","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPFormView","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1init(style:)\/title","value":"initWithStyle:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithStyle:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1init(style:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1preferredNetworks_objc()\/title","op":"replace","value":"preferredNetworks"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1preferredNetworks_objc()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preferredNetworks"}]},{"value":"cardParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1cardParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1cardParams\/fragments","value":[{"text":"cardParams","kind":"identifier"}]},{"op":"replace","value":"disabledBackgroundColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1disabledBackgroundColor\/title"},{"value":[{"kind":"identifier","text":"disabledBackgroundColor"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1disabledBackgroundColor\/fragments"},{"value":"backgroundColor","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1backgroundColor\/title"},{"value":[{"kind":"identifier","text":"backgroundColor"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1backgroundColor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1isUserInteractionEnabled\/title","value":"userInteractionEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1isUserInteractionEnabled\/fragments","value":[{"kind":"identifier","text":"userInteractionEnabled"}]},{"value":"STPCardFormView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"kind":"identifier","text":"STPCardFormView"}]},{"op":"replace","value":[{"text":"STPCardFormView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/title","op":"replace","value":"STPFormView"},{"value":[{"text":"STPFormView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/navigatorTitle","value":[{"text":"STPFormView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1setPreferredNetworks_objc(preferredNetworks:)\/title","op":"replace","value":"setPreferredNetworks:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1setPreferredNetworks_objc(preferredNetworks:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"setPreferredNetworks:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1delegate\/title","value":"delegate"},{"op":"replace","value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView~1delegate\/fragments"}]}]}