{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"abstract":[{"code":"STPCardFormViewDelegate","type":"codeVoice"},{"text":" defines the interface that should be adopted to receive","type":"text"},{"text":" ","type":"text"},{"text":"updates from ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" instances."}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate\/cardFormView(_:didChangeToStateComplete:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Coordinator"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormViewDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformviewdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformviewdelegate"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"symbolKind":"protocol","roleHeading":"Protocol","role":"symbol","modules":[{"name":"StripePaymentsUI"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardFormViewDelegate","kind":"identifier"}],"externalID":"c:@M@StripePaymentsUI@objc(pl)STPCardFormViewDelegate","navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewDelegate"}],"title":"STPCardFormViewDelegate"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Coordinator":{"abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","title":"STPCardFormView.Coordinator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Coordinator"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Coordinator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stpcardformview\/coordinator"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardFormViewDelegate"}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewdelegate","type":"topic","abstract":[{"code":"STPCardFormViewDelegate","type":"codeVoice"},{"type":"text","text":" defines the interface that should be adopted to receive"},{"type":"text","text":" "},{"type":"text","text":"updates from "},{"type":"codeVoice","code":"STPCardFormView"},{"text":" instances.","type":"text"}],"navigatorTitle":[{"text":"STPCardFormViewDelegate","kind":"identifier"}],"title":"STPCardFormViewDelegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewDelegate/cardFormView(_:didChangeToStateComplete:)":{"kind":"symbol","title":"cardFormView(_:didChangeToStateComplete:)","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cardFormView:didChangeToStateComplete:"}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewdelegate\/cardformview(_:didchangetostatecomplete:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardFormView","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPCardFormView","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPCardFormView"},{"text":", ","kind":"text"},{"text":"didChangeToStateComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate\/cardFormView(_:didChangeToStateComplete:)","abstract":[{"text":"Delegate method that is called when all of the form view’s required inputs","type":"text"},{"text":" ","type":"text"},{"text":"are complete or transition away from all being complete. These transitions","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"correspond to "},{"code":"cardForView.cardParams","type":"codeVoice"},{"type":"text","text":" returning a nil value or not."}]},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"STPCardFormViewDelegate","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPCardFormViewDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFormViewDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate\/cardFormView(_:didChangeToStateComplete:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"STPCardFormViewDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/title","value":"STPCardFormViewDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"STPCardFormViewDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFormViewDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate~1cardFormView(_:didChangeToStateComplete:)\/title","value":"cardFormView:didChangeToStateComplete:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate~1cardFormView(_:didChangeToStateComplete:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cardFormView:didChangeToStateComplete:","kind":"identifier"}]}]}]}