{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormViewStyle","kind":"identifier"}]}]}],"abstract":[{"text":"Options for configuring the display of an ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"text":" instance.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewStyle"}],"modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Enumeration","role":"symbol","externalID":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle","symbolKind":"enum","title":"STPCardFormViewStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormViewStyle"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformviewstyle"]},{"paths":["\/documentation\/stripepaymentsui\/stpcardformviewstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/borderless","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/standard"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/s8CopyableP","doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/SQ","doc:\/\/com.stripe.stripe-payments-ui\/SH","doc:\/\/com.stripe.stripe-payments-ui\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","abstract":[],"kind":"article","role":"collectionGroup","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/standard":{"navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewStyleStandard"}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/standard","abstract":[{"type":"text","text":"Draws the form in a rounded rect with full separators between"},{"type":"text","text":" "},{"type":"text","text":"each input field."}],"kind":"symbol","title":"STPCardFormViewStyle.standard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/standard","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments-ui/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s8CopyableP"},"doc://com.stripe.stripe-payments-ui/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/borderless":{"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/borderless","abstract":[{"text":"Draws the form without an outer border and underlines under","type":"text"},{"text":" ","type":"text"},{"text":"each input field.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderless"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/borderless","kind":"symbol","type":"topic","title":"STPCardFormViewStyle.borderless","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewStyleBorderless"}]},"doc://com.stripe.stripe-payments-ui/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments-ui/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SY"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/Equatable-Implementations","kind":"article","type":"topic","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/equatable-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormViewStyle","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle","role":"symbol","navigatorTitle":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Options for configuring the display of an "},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" instance."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","title":"STPCardFormViewStyle"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/init(rawvalue:)","role":"symbol","kind":"symbol","abstract":[]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","kind":"symbol","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"url":"\/documentation\/stripepaymentsui","type":"topic","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/RawRepresentable-Implementations","kind":"article","type":"topic","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments-ui/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPCardFormViewStyle","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPCardFormViewStyle"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPCardFormViewStyle"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/borderless","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle\/standard"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormViewStyle","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"STPCardFormViewStyleStandard","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle~1standard\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFormViewStyleStandard"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle~1standard\/fragments"},{"op":"replace","value":"STPCardFormViewStyleBorderless","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle~1borderless\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFormViewStyleBorderless"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle~1borderless\/fragments"},{"op":"replace","value":"STPCardFormViewStyle","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/title"},{"op":"replace","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/fragments"},{"op":"replace","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/navigatorTitle"}]}]}