{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(pl)STPFormTextFieldContainer","title":"STPFormTextFieldContainer","navigatorTitle":[{"kind":"identifier","text":"STPFormTextFieldContainer"}],"roleHeading":"Protocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormTextFieldContainer"}],"symbolKind":"protocol","modules":[{"name":"StripePaymentsUI"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formCursorColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formFont","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formKeyboardAppearance","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formPlaceholderColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextErrorColor"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"abstract":[{"type":"text","text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain."}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"],"title":"Conforming Types","type":"conformingTypes","kind":"relationships"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormTextFieldContainer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"type":"topic","abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"type":"text","text":" "},{"type":"text","text":"For additional customization options - seealso: STPFormTextFieldContainer"}],"role":"symbol","title":"STPAUBECSDebitFormView","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formTextErrorColor":{"title":"formTextErrorColor","kind":"symbol","abstract":[{"type":"text","text":"The text color to be used when the user has entered invalid information,"},{"type":"text","text":" "},{"type":"text","text":"such as an invalid card number."},{"type":"text","text":" "},{"type":"text","text":"Default is "},{"code":".red","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextErrorColor","navigatorTitle":[{"kind":"identifier","text":"formTextErrorColor"}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formtexterrorcolor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTextErrorColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"required":true},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMultiFormTextField","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","title":"STPMultiFormTextField","role":"symbol","navigatorTitle":[{"text":"STPMultiFormTextField","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formPlaceholderColor":{"abstract":[{"type":"text","text":"The text placeholder color used in each child field."},{"type":"text","text":" "},{"type":"text","text":"This will also set the color of the card placeholder icon."},{"type":"text","text":" "},{"type":"text","text":"Default is "},{"code":".placeholderText","type":"codeVoice"},{"type":"text","text":" on iOS 13.0 and "},{"code":".lightGray","type":"codeVoice"},{"type":"text","text":" on earlier versions."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formPlaceholderColor","required":true,"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"formPlaceholderColor"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formplaceholdercolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formPlaceholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"title":"formPlaceholderColor"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formFont":{"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formfont","title":"formFont","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"}],"navigatorTitle":[{"kind":"identifier","text":"formFont"}],"required":true,"abstract":[{"type":"text","text":"The font used in each child field. Default is "},{"code":".body","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formFont","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formCursorColor":{"title":"formCursorColor","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formCursorColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formCursorColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"abstract":[{"text":"The cursor color for the field.","type":"text"},{"text":" ","type":"text"},{"text":"This is a proxy for the view’s tintColor property, exposed for clarity only","type":"text"},{"text":" ","type":"text"},{"text":"(in other words, calling setCursorColor is identical to calling setTintColor).","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formcursorcolor","required":true,"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"formCursorColor","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formTextColor":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formtextcolor","kind":"symbol","type":"topic","title":"formTextColor","abstract":[{"type":"text","text":"The text color to be used when entering valid text. Default is "},{"code":".label","type":"codeVoice"},{"type":"text","text":" on iOS 13.0 and later and "},{"code":".darkText","type":"codeVoice"},{"type":"text","text":" on earlier versions."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"formTextColor"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextColor"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui","role":"collection","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formKeyboardAppearance":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The keyboard appearance for the field."},{"type":"text","text":" "},{"type":"text","text":"Default is "},{"code":".default","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formkeyboardappearance","navigatorTitle":[{"text":"formKeyboardAppearance","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formKeyboardAppearance","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formKeyboardAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIKeyboardAppearance","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance"}],"required":true,"title":"formKeyboardAppearance","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"abstract":[{"type":"text","text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","kind":"symbol","title":"STPFormTextFieldContainer","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormTextFieldContainer","kind":"identifier"}],"navigatorTitle":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"STPFormTextFieldContainer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormTextFieldContainer"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formCursorColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formFont","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formKeyboardAppearance","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formPlaceholderColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextErrorColor"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformingTypes","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"],"kind":"relationships","title":"Conforming Types"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormTextFieldContainer","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title","value":"STPAUBECSDebitFormView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle","value":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formTextErrorColor\/title","value":"formTextErrorColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formTextErrorColor\/fragments","value":[{"kind":"identifier","text":"formTextErrorColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","value":[{"text":"STPMultiFormTextField","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPMultiFormTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formPlaceholderColor\/title","value":"formPlaceholderColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formPlaceholderColor\/fragments","value":[{"kind":"identifier","text":"formPlaceholderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formFont\/title","value":"formFont"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formFont\/fragments","value":[{"kind":"identifier","text":"formFont"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formCursorColor\/title","value":"formCursorColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formCursorColor\/fragments","value":[{"kind":"identifier","text":"formCursorColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formTextColor\/title","value":"formTextColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formTextColor\/fragments","value":[{"kind":"identifier","text":"formTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formKeyboardAppearance\/title","value":"formKeyboardAppearance"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formKeyboardAppearance\/fragments","value":[{"kind":"identifier","text":"formKeyboardAppearance"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title","value":"STPFormTextFieldContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormTextFieldContainer"}]}]}]}