{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpformview"]},{"paths":["\/documentation\/stripepaymentsui\/stpformview"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/canBecomeFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/canResignFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isUserInteractionEnabled"],"anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/becomeFirstResponder()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/resignFirstResponder()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView"},"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPFormView","kind":"identifier"}],"navigatorTitle":[{"text":"STPFormView","kind":"identifier"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPFormView","role":"symbol","modules":[{"name":"StripePaymentsUI"}],"title":"STPFormView","roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"abstract":[{"type":"codeVoice","code":"STPFormView"},{"type":"text","text":" is a base class for the Stripe SDK’s form input UI. You should use one of the available subclasses"},{"type":"text","text":" "},{"type":"text","text":"("},{"type":"codeVoice","code":"STPCardFormView"},{"text":") rather than instantiating an ","type":"text"},{"code":"STPFormView","type":"codeVoice"},{"type":"text","text":" instance directly."}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)CALayerDelegate","doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/SQ","doc:\/\/com.stripe.stripe-payments-ui\/SH","doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearance","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UICoordinateSpace","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIDynamicItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItemContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UILargeContentViewerItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-payments-ui\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIUserActivityRestoring"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFormView"}]}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/isFirstResponder":{"kind":"symbol","title":"isFirstResponder","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isFirstResponder","navigatorTitle":[{"kind":"identifier","text":"isFirstResponder"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFirstResponder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpformview\/isfirstresponder"},"doc://com.stripe.stripe-payments-ui/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/canResignFirstResponder":{"title":"canResignFirstResponder","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canResignFirstResponder"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"canResignFirstResponder","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/canResignFirstResponder","url":"\/documentation\/stripepaymentsui\/stpformview\/canresignfirstresponder","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","title":"StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"title":"STPCardFormView","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","type":"topic","abstract":[{"code":"STPCardFormView","type":"codeVoice"},{"text":" provides a multiline interface for users to input their","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"credit card details as well as billing postal code and provides an interface to access"},{"type":"text","text":" "},{"type":"text","text":"the created "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCardFormView"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is displayed when invalid input is detected."}],"role":"symbol","navigatorTitle":[{"text":"STPCardFormView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormView","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView":{"abstract":[{"code":"STPFormView","type":"codeVoice"},{"type":"text","text":" is a base class for the Stripe SDK’s form input UI. You should use one of the available subclasses"},{"text":" ","type":"text"},{"text":"(","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":") rather than instantiating an "},{"type":"codeVoice","code":"STPFormView"},{"type":"text","text":" instance directly."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormView"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","title":"STPFormView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFormView","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpformview","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/isUserInteractionEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isUserInteractionEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isUserInteractionEnabled","navigatorTitle":[{"kind":"identifier","text":"userInteractionEnabled"}],"url":"\/documentation\/stripepaymentsui\/stpformview\/isuserinteractionenabled","abstract":[{"type":"text","text":":nodoc:"}],"title":"isUserInteractionEnabled","type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/becomeFirstResponder()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"becomeFirstResponder","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/becomeFirstResponder()","title":"becomeFirstResponder()","abstract":[{"text":":nodoc:","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"becomeFirstResponder"}],"url":"\/documentation\/stripepaymentsui\/stpformview\/becomefirstresponder()"},"doc://com.stripe.stripe-payments-ui/objc(cs)UIView":{"title":"UIView","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)UIView","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/canBecomeFirstResponder":{"type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpformview\/canbecomefirstresponder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"canBecomeFirstResponder","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/canBecomeFirstResponder","kind":"symbol","title":"canBecomeFirstResponder","navigatorTitle":[{"kind":"identifier","text":"canBecomeFirstResponder"}],"role":"symbol"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearance","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView/resignFirstResponder()":{"abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"kind":"identifier","text":"resignFirstResponder"}],"title":"resignFirstResponder()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resignFirstResponder","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/resignFirstResponder()","url":"\/documentation\/stripepaymentsui\/stpformview\/resignfirstresponder()","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"STPFormView","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"STPFormView"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormView"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/canBecomeFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/canResignFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/isUserInteractionEnabled"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/becomeFirstResponder()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView\/resignFirstResponder()"],"anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)UIView"]},{"title":"Inherited By","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"],"kind":"relationships","type":"inheritedBy"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormView"},{"kind":"text","text":" : "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"isFirstResponder","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1isFirstResponder\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1isFirstResponder\/fragments","op":"replace","value":[{"text":"isFirstResponder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1canResignFirstResponder\/title","value":"canResignFirstResponder"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1canResignFirstResponder\/fragments","value":[{"kind":"identifier","text":"canResignFirstResponder"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"text":"STPCardFormView","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPCardFormView"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/title","value":"STPFormView","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFormView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormView"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1isUserInteractionEnabled\/title","op":"replace","value":"userInteractionEnabled"},{"value":[{"kind":"identifier","text":"userInteractionEnabled"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1isUserInteractionEnabled\/fragments","op":"replace"},{"value":"becomeFirstResponder","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1becomeFirstResponder()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"becomeFirstResponder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1becomeFirstResponder()\/fragments","op":"replace"},{"op":"replace","value":"canBecomeFirstResponder","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1canBecomeFirstResponder\/title"},{"value":[{"text":"canBecomeFirstResponder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1canBecomeFirstResponder\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1resignFirstResponder()\/title","op":"replace","value":"resignFirstResponder"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView~1resignFirstResponder()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resignFirstResponder"}]}]}]}