{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield"]},{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"metadata":{"title":"STPMultiFormTextField","symbolKind":"class","navigatorTitle":[{"text":"STPMultiFormTextField","kind":"identifier"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField","role":"symbol","modules":[{"name":"StripePaymentsUI"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPMultiFormTextField","kind":"identifier"}],"roleHeading":"Class"},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/canBecomeFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/canResignFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formCursorColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formFont","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formKeyboardAppearance","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formPlaceholderColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formTextColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formTextErrorColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/isFirstResponder"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/becomeFirstResponder()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/focusNextForm()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/resignFirstResponder()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textField(_:shouldChangeCharactersIn:replacementString:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldDidBeginEditing(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldDidEndEditing(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldShouldReturn(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMultiFormTextField"}]}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)UIView"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)CALayerDelegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/SQ","doc:\/\/com.stripe.stripe-payments-ui\/SH","doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearance","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UICoordinateSpace","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIDynamicItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItemContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UILargeContentViewerItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextFieldDelegate","doc:\/\/com.stripe.stripe-payments-ui\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments-ui/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/canBecomeFirstResponder":{"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/canbecomefirstresponder","kind":"symbol","type":"topic","title":"canBecomeFirstResponder","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"canBecomeFirstResponder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"canBecomeFirstResponder","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/canBecomeFirstResponder"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/isFirstResponder":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFirstResponder","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":":nodoc:","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/isfirstresponder","title":"isFirstResponder","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/isFirstResponder","navigatorTitle":[{"kind":"identifier","text":"isFirstResponder"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UICoordinateSpace"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIUserActivityRestoring"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/formFont":{"title":"formFont","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formFont","navigatorTitle":[{"kind":"identifier","text":"formFont"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formfont","abstract":[{"text":"The font used in each child field. Default is ","type":"text"},{"type":"codeVoice","code":".body"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formFont"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/resignFirstResponder()":{"kind":"symbol","title":"resignFirstResponder()","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"resignFirstResponder"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/resignFirstResponder()","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/resignfirstresponder()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resignFirstResponder","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield","abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","navigatorTitle":[{"kind":"identifier","text":"STPMultiFormTextField"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMultiFormTextField"}],"type":"topic","title":"STPMultiFormTextField"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/canResignFirstResponder":{"type":"topic","title":"canResignFirstResponder","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canResignFirstResponder"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/canresignfirstresponder","role":"symbol","navigatorTitle":[{"text":"canResignFirstResponder","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/canResignFirstResponder"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/textField(_:shouldChangeCharactersIn:replacementString:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textField(_:shouldChangeCharactersIn:replacementString:)","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/textfield(_:shouldchangecharactersin:replacementstring:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textField","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextField","kind":"typeIdentifier","text":"UITextField"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange","text":"NSRange"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"replacementString"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"title":"textField(_:shouldChangeCharactersIn:replacementString:)"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/focusNextForm()":{"kind":"symbol","title":"focusNextForm()","abstract":[{"text":"Calling this method will make the next incomplete STPFormTextField in ","type":"text"},{"code":"formTextFields","type":"codeVoice"},{"type":"text","text":" become the first responder."},{"type":"text","text":" "},{"text":"If all of the form text fields are already complete, then the last field in ","type":"text"},{"type":"codeVoice","code":"formTextFields"},{"type":"text","text":" will become the first responder."}],"type":"topic","navigatorTitle":[{"text":"focusNextForm","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/focusNextForm()","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/focusnextform()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"focusNextForm","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIDynamicItem"},"doc://com.stripe.stripe-payments-ui/objc(pl)UITextFieldDelegate":{"title":"UITextFieldDelegate","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextFieldDelegate"},"doc://com.stripe.stripe-payments-ui/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/5UIKit23UITraitChangeObservableP"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/formPlaceholderColor":{"title":"formPlaceholderColor","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formPlaceholderColor","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formPlaceholderColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formplaceholdercolor","abstract":[{"type":"text","text":"The text placeholder color used in each child field."},{"type":"text","text":" "},{"type":"text","text":"This will also set the color of the card placeholder icon."},{"type":"text","text":" "},{"text":"Default is ","type":"text"},{"type":"codeVoice","code":".placeholderText"},{"text":" on iOS 13.0 and ","type":"text"},{"type":"codeVoice","code":".lightGray"},{"type":"text","text":" on earlier versions."}],"navigatorTitle":[{"kind":"identifier","text":"formPlaceholderColor"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAccessibilityIdentification","title":"UIKit.UIAccessibilityIdentification","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)CALayerDelegate","title":"QuartzCore.CALayerDelegate","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","title":"STPAUBECSDebitFormView","abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"type":"text","text":" "},{"text":"For additional customization options - seealso: STPFormTextFieldContainer","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","navigatorTitle":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/textFieldShouldReturn(_:)":{"kind":"symbol","title":"textFieldShouldReturn(_:)","abstract":[{"text":":nodoc:","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"textFieldShouldReturn:"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldShouldReturn(_:)","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/textfieldshouldreturn(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldShouldReturn","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/formTextColor":{"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formtextcolor","kind":"symbol","type":"topic","title":"formTextColor","abstract":[{"type":"text","text":"The text color to be used when entering valid text. Default is "},{"type":"codeVoice","code":".label"},{"type":"text","text":" on iOS 13.0 and later and "},{"code":".darkText","type":"codeVoice"},{"type":"text","text":" on earlier versions."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formTextColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"formTextColor","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formTextColor"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/textFieldDidBeginEditing(_:)":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/textfielddidbeginediting(_:)","title":"textFieldDidBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldDidBeginEditing"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"kind":"identifier","text":"textFieldDidBeginEditing:"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldDidBeginEditing(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"title":"StripePaymentsUI","type":"topic","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments-ui/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments-ui/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItem","title":"UIKit.UIFocusItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIPopoverPresentationControllerSourceItem","title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(cs)UIView":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)UIView","title":"UIView","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/initWithCoder:":{"abstract":[],"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/initwithcoder:","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/initWithCoder:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","title":"initWithCoder:","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/formTextErrorColor":{"kind":"symbol","title":"formTextErrorColor","abstract":[{"text":"The text color to be used when the user has entered invalid information,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"such as an invalid card number."},{"text":" ","type":"text"},{"type":"text","text":"Default is "},{"type":"codeVoice","code":".red"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"formTextErrorColor","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formTextErrorColor","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formtexterrorcolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"formTextErrorColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/textFieldDidEndEditing(_:)":{"title":"textFieldDidEndEditing(_:)","role":"symbol","kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldDidEndEditing(_:)","navigatorTitle":[{"kind":"identifier","text":"textFieldDidEndEditing:"}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/textfielddidendediting(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldDidEndEditing"},{"kind":"text","text":"("},{"text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"navigatorTitle":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"abstract":[{"text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","title":"STPFormTextFieldContainer","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormTextFieldContainer"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s8SendableP","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/becomeFirstResponder()":{"kind":"symbol","title":"becomeFirstResponder()","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","navigatorTitle":[{"text":"becomeFirstResponder","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/becomeFirstResponder()","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/becomefirstresponder()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"becomeFirstResponder"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.stripe.stripe-payments-ui/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UIResponderStandardEditActions"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/formKeyboardAppearance":{"kind":"symbol","title":"formKeyboardAppearance","abstract":[{"type":"text","text":"The keyboard appearance for the field."},{"type":"text","text":" "},{"text":"Default is ","type":"text"},{"type":"codeVoice","code":".default"},{"text":".","type":"text"}],"type":"topic","navigatorTitle":[{"text":"formKeyboardAppearance","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formKeyboardAppearance","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formkeyboardappearance","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"formKeyboardAppearance","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance"}]},"doc://com.stripe.stripe-payments-ui/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/initWithFrame:":{"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/initWithFrame:","title":"initWithFrame:","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/initwithframe:","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithFrame:","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/formCursorColor":{"abstract":[{"text":"The cursor color for the field.","type":"text"},{"type":"text","text":" "},{"text":"This is a proxy for the view’s tintColor property, exposed for clarity only","type":"text"},{"type":"text","text":" "},{"type":"text","text":"(in other words, calling setCursorColor is identical to calling setTintColor)."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formCursorColor","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formcursorcolor","title":"formCursorColor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"formCursorColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"navigatorTitle":[{"text":"formCursorColor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"STPMultiFormTextField","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPMultiFormTextField"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPMultiFormTextField","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/canBecomeFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/canResignFirstResponder","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formCursorColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formFont","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formKeyboardAppearance","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formPlaceholderColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formTextColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formTextErrorColor","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/isFirstResponder"],"anchor":"Instance-Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/becomeFirstResponder()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/focusNextForm()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/initWithCoder:","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/initWithFrame:","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/resignFirstResponder()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textField(_:shouldChangeCharactersIn:replacementString:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldDidBeginEditing(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldDidEndEditing(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/textFieldShouldReturn(_:)"],"generated":true}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)UIView"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"inheritedBy","title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)UITextFieldDelegate"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMultiFormTextField","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}]}],"kind":"declarations"}},{"op":"replace","value":"canBecomeFirstResponder","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1canBecomeFirstResponder\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1canBecomeFirstResponder\/fragments","value":[{"text":"canBecomeFirstResponder","kind":"identifier"}],"op":"replace"},{"value":"isFirstResponder","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1isFirstResponder\/title"},{"value":[{"text":"isFirstResponder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1isFirstResponder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formFont\/title","value":"formFont"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formFont\/fragments","value":[{"kind":"identifier","text":"formFont"}]},{"value":"resignFirstResponder","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1resignFirstResponder()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"resignFirstResponder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1resignFirstResponder()\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","value":[{"text":"STPMultiFormTextField","kind":"identifier"}]},{"value":[{"text":"STPMultiFormTextField","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle"},{"value":"canResignFirstResponder","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1canResignFirstResponder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"canResignFirstResponder"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1canResignFirstResponder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1textField(_:shouldChangeCharactersIn:replacementString:)\/title","value":"textField:shouldChangeCharactersInRange:replacementString:"},{"value":[{"kind":"text","text":"- "},{"text":"textField:shouldChangeCharactersInRange:replacementString:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1textField(_:shouldChangeCharactersIn:replacementString:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1focusNextForm()\/title","op":"replace","value":"focusNextForm"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1focusNextForm()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"focusNextForm"}]},{"value":"formPlaceholderColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formPlaceholderColor\/title","op":"replace"},{"value":[{"kind":"identifier","text":"formPlaceholderColor"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formPlaceholderColor\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title","op":"replace","value":"STPAUBECSDebitFormView"},{"value":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}]},{"value":"textFieldShouldReturn:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1textFieldShouldReturn(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1textFieldShouldReturn(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textFieldShouldReturn:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formTextColor\/title","value":"formTextColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formTextColor\/fragments","value":[{"kind":"identifier","text":"formTextColor"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1textFieldDidBeginEditing(_:)\/title","value":"textFieldDidBeginEditing:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1textFieldDidBeginEditing(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textFieldDidBeginEditing:","kind":"identifier"}],"op":"replace"},{"value":"formTextErrorColor","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formTextErrorColor\/title"},{"value":[{"text":"formTextErrorColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formTextErrorColor\/fragments"},{"value":"textFieldDidEndEditing:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1textFieldDidEndEditing(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"textFieldDidEndEditing:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1textFieldDidEndEditing(_:)\/fragments"},{"op":"replace","value":"STPFormTextFieldContainer","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]},{"value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1becomeFirstResponder()\/title","op":"replace","value":"becomeFirstResponder"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1becomeFirstResponder()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"becomeFirstResponder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formKeyboardAppearance\/title","value":"formKeyboardAppearance"},{"value":[{"kind":"identifier","text":"formKeyboardAppearance"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formKeyboardAppearance\/fragments"},{"value":"formCursorColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formCursorColor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formCursorColor\/fragments","value":[{"kind":"identifier","text":"formCursorColor"}]}]}]}