{"metadata":{"role":"symbol","roleHeading":"Protocol","modules":[{"name":"StripePaymentsUI"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"externalID":"c:@M@StripePaymentsUI@objc(pl)STPPaymentCardTextFieldDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"symbolKind":"protocol","title":"STPPaymentCardTextFieldDelegate"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"abstract":[{"text":"This protocol allows a delegate to be notified when a payment text field’s","type":"text"},{"type":"text","text":" "},{"text":"contents change, which can in turn be used to take further actions depending","type":"text"},{"type":"text","text":" "},{"type":"text","text":"on the validity of its contents."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate"]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditing(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingCVC(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingExpiration(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingNumber(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingPostalCode(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidChange(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditing(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingCVC(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingExpiration(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingNumber(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingPostalCode(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldWillEndEditing(forReturn:)"],"generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/Coordinator"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"title":"StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui","type":"topic"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidEndEditing(_:)":{"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendediting(_:)","role":"symbol","type":"topic","abstract":[{"text":"Called when editing ends in the text field as a whole.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This callback is always preceded by an callback for which"},{"type":"text","text":" "},{"type":"text","text":"specific subfield of the view ended its editing."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditing(_:)","kind":"symbol","navigatorTitle":[{"text":"paymentCardTextFieldDidEndEditing:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidEndEditing","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"paymentCardTextFieldDidEndEditing(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidEndEditingNumber(_:)":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingNumber(_:)","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendeditingnumber(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentCardTextFieldDidEndEditingNumber","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingNumber:"}],"type":"topic","kind":"symbol","title":"paymentCardTextFieldDidEndEditingNumber(_:)","abstract":[{"type":"text","text":"Called when editing ends in the payment card field’s number field."}],"required":true},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField/Representable/Coordinator":{"navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField\/Representable\/Coordinator","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/representable\/coordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Coordinator","kind":"identifier"}],"type":"topic","title":"STPPaymentCardTextField.Representable.Coordinator","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidEndEditingCVC(_:)":{"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendeditingcvc(_:)","role":"symbol","type":"topic","abstract":[{"text":"Called when editing ends in the payment card field’s CVC field.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingCVC(_:)","kind":"symbol","navigatorTitle":[{"text":"paymentCardTextFieldDidEndEditingCVC:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingCVC"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"paymentCardTextFieldDidEndEditingCVC(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"STPPaymentCardTextFieldDelegate","abstract":[{"text":"This protocol allows a delegate to be notified when a payment text field’s","type":"text"},{"type":"text","text":" "},{"type":"text","text":"contents change, which can in turn be used to take further actions depending"},{"type":"text","text":" "},{"type":"text","text":"on the validity of its contents."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidEndEditingPostalCode(_:)":{"navigatorTitle":[{"text":"paymentCardTextFieldDidEndEditingPostalCode:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingPostalCode(_:)","required":true,"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendeditingpostalcode(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidEndEditingPostalCode","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"paymentCardTextFieldDidEndEditingPostalCode(_:)","kind":"symbol","abstract":[{"type":"text","text":"Called when editing ends in the payment card field’s ZIP\/postal code field."}],"role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidChange(_:)":{"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidchange(_:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Called when either the card number, expiration, or CVC changes. At this point,"},{"text":" ","type":"text"},{"type":"text","text":"one can call "},{"code":"isValid","type":"codeVoice"},{"type":"text","text":" on the text field to determine, for example,"},{"type":"text","text":" "},{"type":"text","text":"whether or not to enable a button to submit the form. Example:"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidChange(_:)","required":true,"kind":"symbol","navigatorTitle":[{"text":"paymentCardTextFieldDidChange:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidChange"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":")","kind":"text"}],"title":"paymentCardTextFieldDidChange(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidBeginEditingCVC(_:)":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingCVC(_:)","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingcvc(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingCVC"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingCVC:"}],"type":"topic","kind":"symbol","title":"paymentCardTextFieldDidBeginEditingCVC(_:)","abstract":[{"type":"text","text":"Called when editing begins in the payment card field’s CVC field."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidBeginEditingNumber(_:)":{"navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingNumber:"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingNumber(_:)","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingnumber(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingNumber","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"text":")","kind":"text"}],"type":"topic","title":"paymentCardTextFieldDidBeginEditingNumber(_:)","kind":"symbol","abstract":[{"type":"text","text":"Called when editing begins in the payment card field’s number field."}],"role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidEndEditingExpiration(_:)":{"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendeditingexpiration(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingExpiration"},{"text":"(","kind":"text"},{"text":"STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"required":true,"role":"symbol","abstract":[{"type":"text","text":"Called when editing ends in the payment card field’s expiration field."}],"navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingExpiration:"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingExpiration(_:)","title":"paymentCardTextFieldDidEndEditingExpiration(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldWillEndEditing(forReturn:)":{"required":true,"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfieldwillendediting(forreturn:)","navigatorTitle":[{"text":"paymentCardTextFieldWillEndEditingForReturn:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditing"},{"text":"(","kind":"text"},{"text":"forReturn","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Notification that the user pressed the ","type":"text"},{"type":"codeVoice","code":"return"},{"type":"text","text":" key after completely filling"},{"text":" ","type":"text"},{"type":"text","text":"out the STPPaymentCardTextField with data that passes validation."},{"text":" ","type":"text"},{"type":"text","text":"The Stripe SDK is going to "},{"code":"resignFirstResponder","type":"codeVoice"},{"text":" on the ","type":"text"},{"type":"codeVoice","code":"STPPaymentCardTextField"},{"type":"text","text":" "},{"type":"text","text":"to dismiss the keyboard after this delegate method returns, however if your app wants"},{"type":"text","text":" "},{"type":"text","text":"to do something more (ex: move first responder to another field), this is a good"},{"text":" ","type":"text"},{"type":"text","text":"opportunity to do that."},{"type":"text","text":" "},{"type":"text","text":"This is delivered "},{"inlineContent":[{"type":"text","text":"before"}],"type":"emphasis"},{"type":"text","text":" the corresponding "},{"type":"codeVoice","code":"paymentCardTextFieldDidEndEditing:"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldWillEndEditing(forReturn:)","title":"paymentCardTextFieldWillEndEditing(forReturn:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidBeginEditingExpiration(_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingExpiration(_:)","kind":"symbol","type":"topic","title":"paymentCardTextFieldDidBeginEditingExpiration(_:)","abstract":[{"type":"text","text":"Called when editing begins in the payment card field’s expiration field."}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingexpiration(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentCardTextFieldDidBeginEditingExpiration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paymentCardTextFieldDidBeginEditingExpiration:","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidBeginEditingPostalCode(_:)":{"required":true,"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingpostalcode(_:)","navigatorTitle":[{"text":"paymentCardTextFieldDidBeginEditingPostalCode:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentCardTextFieldDidBeginEditingPostalCode","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","kind":"typeIdentifier","text":"STPPaymentCardTextField"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Called when editing begins in the payment card field’s ZIP\/postal code field.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingPostalCode(_:)","title":"paymentCardTextFieldDidBeginEditingPostalCode(_:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidBeginEditing(_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditing(_:)","kind":"symbol","type":"topic","title":"paymentCardTextFieldDidBeginEditing(_:)","abstract":[{"text":"Called when editing begins in the text field as a whole.","type":"text"},{"type":"text","text":" "},{"text":"After receiving this callback, you will always also receive a callback for which","type":"text"},{"type":"text","text":" "},{"type":"text","text":"specific subfield of the view began editing."}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbeginediting(_:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditing:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentCardTextFieldDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditing(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingCVC(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingExpiration(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingNumber(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingPostalCode(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidChange(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditing(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingCVC(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingExpiration(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingNumber(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingPostalCode(_:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldWillEndEditing(forReturn:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"],"kind":"relationships"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditing(_:)\/title","value":"paymentCardTextFieldDidEndEditing:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditing(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"paymentCardTextFieldDidEndEditing:","kind":"identifier"}]},{"value":"paymentCardTextFieldDidEndEditingNumber:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingNumber(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingNumber(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingNumber:"}],"op":"replace"},{"op":"replace","value":"paymentCardTextFieldDidEndEditingCVC:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingCVC(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingCVC(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidEndEditingCVC:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title","value":"STPPaymentCardTextFieldDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments","value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}]},{"value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle"},{"value":"paymentCardTextFieldDidEndEditingPostalCode:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingPostalCode(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingPostalCode(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingPostalCode:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidChange(_:)\/title","value":"paymentCardTextFieldDidChange:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidChange:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidChange(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingCVC(_:)\/title","op":"replace","value":"paymentCardTextFieldDidBeginEditingCVC:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingCVC(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingCVC:","kind":"identifier"}]},{"value":"paymentCardTextFieldDidBeginEditingNumber:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingNumber(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingNumber(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingNumber:"}]},{"value":"paymentCardTextFieldDidEndEditingExpiration:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingExpiration(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingExpiration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"paymentCardTextFieldDidEndEditingExpiration:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldWillEndEditing(forReturn:)\/title","op":"replace","value":"paymentCardTextFieldWillEndEditingForReturn:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditingForReturn:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldWillEndEditing(forReturn:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingExpiration(_:)\/title","op":"replace","value":"paymentCardTextFieldDidBeginEditingExpiration:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingExpiration(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingExpiration:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingPostalCode(_:)\/title","value":"paymentCardTextFieldDidBeginEditingPostalCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingPostalCode(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingPostalCode:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditing(_:)\/title","value":"paymentCardTextFieldDidBeginEditing:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditing:"}]}]}]}