{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBankParams"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodpaybybankparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBankParams\/init"},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBankParams(im)init","modules":[{"name":"StripePayments"}],"title":"init"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayByBankParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPayByBankParams","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodpaybybankparams","title":"STPPaymentMethodPayByBankParams","navigatorTitle":[{"text":"STPPaymentMethodPayByBankParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Pay by Bank Payment Method"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBankParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayByBankParams/init":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBankParams\/init","kind":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodpaybybankparams\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBankParams\/title","value":"STPPaymentMethodPayByBankParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBankParams\/fragments","value":[{"text":"STPPaymentMethodPayByBankParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBankParams\/navigatorTitle","value":[{"text":"STPPaymentMethodPayByBankParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}