{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/description"],"generated":true,"anchor":"Instance-Properties"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType"]]},"metadata":{"modules":[{"name":"StripePayments"}],"role":"collectionGroup","title":"CustomStringConvertible Implementations","roleHeading":"API Collection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/customstringconvertible-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/CustomStringConvertible-Implementations"},"kind":"article","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","title":"description","abstract":[],"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/description","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/description","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"navigatorTitle":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpklarnalineitemtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItemType"}],"abstract":[{"type":"text","text":"The type of the Klarna line item."}],"title":"STPKlarnaLineItemType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPKlarnaLineItemType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments","value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/navigatorTitle","value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}