{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"hasher"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/hash(into:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/hash(into:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/RawRepresentable-Implementations"]]},"sections":[],"metadata":{"role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@StripePayments@E@STPKlarnaLineItemType","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"modules":[{"relatedModules":["Swift"],"name":"StripePayments"}],"title":"hash(into:)","extendedModule":"Swift","roleHeading":"Instance Method","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]}},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"text":".","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/hash(into:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/hash(into:)","abstract":[],"kind":"symbol","title":"hash(into:)","type":"topic","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/hash(into:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpklarnalineitemtype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","type":"topic","role":"symbol","title":"STPKlarnaLineItemType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItemType"}],"abstract":[{"text":"The type of the Klarna line item.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","value":"STPKlarnaLineItemType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments","value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/navigatorTitle","value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}