{"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/init(rawvalue:)"]}],"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"externalID":"s:14StripePayments21STPKlarnaLineItemTypeO8rawValueACSgSi_tcfc","roleHeading":"Initializer","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/init(rawValue:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","url":"\/documentation\/stripepayments\/stpklarnalineitemtype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPKlarnaLineItemType","kind":"identifier"}],"navigatorTitle":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"STPKlarnaLineItemType","abstract":[{"type":"text","text":"The type of the Klarna line item."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/init(rawvalue:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/init(rawValue:)"}},"variantOverrides":[{"patch":[{"value":"STPKlarnaLineItemType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments"},{"op":"replace","value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}