{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/shipping","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/shipping"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/shipping"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType"]]},"metadata":{"symbolKind":"case","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPKlarnaLineItemTypeShipping","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPKlarnaLineItemType@STPKlarnaLineItemTypeShipping","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shipping"}],"role":"symbol","roleHeading":"Case","title":"STPKlarnaLineItemType.shipping"},"abstract":[{"type":"text","text":"The line item for shipping costs"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"kind":"symbol","title":"STPKlarnaLineItemType","navigatorTitle":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItemType"}],"url":"\/documentation\/stripepayments\/stpklarnalineitemtype","role":"symbol","abstract":[{"type":"text","text":"The type of the Klarna line item."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/shipping":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemTypeShipping"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/shipping","url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/shipping","kind":"symbol","title":"STPKlarnaLineItemType.shipping","abstract":[{"type":"text","text":"The line item for shipping costs"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPKlarnaLineItemTypeShipping"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPKlarnaLineItemTypeShipping"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPKlarnaLineItemTypeShipping","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","op":"replace","value":"STPKlarnaLineItemType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments","op":"replace","value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/navigatorTitle","value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1shipping\/title","value":"STPKlarnaLineItemTypeShipping","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1shipping\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPKlarnaLineItemTypeShipping"}]}]}]}