{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKU","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemTypeSKU"}],"title":"STPKlarnaLineItemType.SKU","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPKlarnaLineItemType@STPKlarnaLineItemTypeSKU","role":"symbol","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType"]]},"abstract":[{"type":"text","text":"The line item for a product"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SKU","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/sku"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/sku"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/SKU"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/SKU":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/SKU","title":"STPKlarnaLineItemType.SKU","role":"symbol","abstract":[{"text":"The line item for a product","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SKU"}],"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/sku","navigatorTitle":[{"text":"STPKlarnaLineItemTypeSKU","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"type":"topic","abstract":[{"type":"text","text":"The type of the Klarna line item."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"title":"STPKlarnaLineItemType","url":"\/documentation\/stripepayments\/stpklarnalineitemtype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItemType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"STPKlarnaLineItemTypeSKU","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPKlarnaLineItemTypeSKU","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPKlarnaLineItemTypeSKU","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1SKU\/title","value":"STPKlarnaLineItemTypeSKU"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1SKU\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPKlarnaLineItemTypeSKU"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","value":"STPKlarnaLineItemType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments","value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/navigatorTitle","value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}]}]}]}