{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTheme:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","text":"STPTheme"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"theme"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcorescrollviewcontroller\/initwiththeme:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/initWithTheme:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTheme:"}],"title":"initWithTheme:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPCoreScrollViewController(im)initWithTheme:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTheme:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"role":"symbol","title":"STPTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTheme"}],"abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}],"url":"\/documentation\/stripe\/stptheme"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/initWithTheme:":{"role":"symbol","title":"initWithTheme:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTheme:"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/initWithTheme:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTheme:"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/initwiththeme:"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController":{"role":"symbol","title":"STPCoreScrollViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreScrollViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreScrollViewController"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","value":"STPTheme"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","value":[{"kind":"identifier","text":"STPTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/title","value":"STPCoreScrollViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreScrollViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
