{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpcorescrollviewcontroller\/scrollview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpcorescrollviewcontroller\/scrollview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/scrollView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This returns the scroll view being managed by the view controller"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"}],"title":"scrollView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@Stripe@objc(cs)STPCoreScrollViewController(py)scrollView","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"scrollView"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/scrollView":{"role":"symbol","title":"scrollView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"}],"abstract":[{"type":"text","text":"This returns the scroll view being managed by the view controller"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/scrollView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scrollView"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/scrollview"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController":{"role":"symbol","title":"STPCoreScrollViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreScrollViewController"}],"abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreScrollViewController"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"scrollView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"scrollView"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"scrollView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1scrollView\/title","value":"scrollView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1scrollView\/fragments","value":[{"kind":"identifier","text":"scrollView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/title","value":"STPCoreScrollViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreScrollViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}