{"abstract":[{"type":"text","text":":nodoc:"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcorescrollviewcontroller\/viewdidlayoutsubviews()"]},{"paths":["\/documentation\/stripe\/stpcorescrollviewcontroller\/viewdidlayoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/viewDidLayoutSubviews()"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"symbolKind":"method","role":"symbol","title":"viewDidLayoutSubviews()","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@Stripe@objc(cs)STPCoreScrollViewController(im)viewDidLayoutSubviews"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController/viewDidLayoutSubviews()":{"url":"\/documentation\/stripe\/stpcorescrollviewcontroller\/viewdidlayoutsubviews()","title":"viewDidLayoutSubviews()","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController\/viewDidLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreScrollViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreScrollViewController","role":"symbol","abstract":[{"text":"This is the base class for all Stripe scroll view controllers. It is intended","type":"text"},{"text":" ","type":"text"},{"text":"for use only by Stripe classes, you should not subclass it yourself in your app.","type":"text"}],"url":"\/documentation\/stripe\/stpcorescrollviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCoreScrollViewController","kind":"identifier"}],"navigatorTitle":[{"text":"STPCoreScrollViewController","kind":"identifier"}],"kind":"symbol","title":"STPCoreScrollViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"viewDidLayoutSubviews","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"viewDidLayoutSubviews","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1viewDidLayoutSubviews()\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController~1viewDidLayoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"op":"replace"},{"value":"STPCoreScrollViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/title"},{"value":[{"kind":"identifier","text":"STPCoreScrollViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreScrollViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
