{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodlinkparams\/credentials"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams\/credentials","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"credentials"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams"]]},"abstract":[{"type":"text","text":":nodoc:"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodLinkParams(py)credentials","navigatorTitle":[{"text":"credentials","kind":"identifier"}],"title":"credentials","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"credentials","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodLinkParams/credentials":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams\/credentials","fragments":[{"text":"credentials","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripepayments\/stppaymentmethodlinkparams\/credentials","title":"credentials"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodLinkParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams","title":"STPPaymentMethodLinkParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodLinkParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodlinkparams","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create an Link Payment Method"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodLinkParams"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPPaymentMethodLinkParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodLinkParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodLinkParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}