{"metadata":{"roleHeading":"Instance Method","title":"init","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodLinkParams(im)init","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"symbolKind":"method","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodlinkparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams\/init","interfaceLanguage":"occ"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodLinkParams/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","abstract":[],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams\/init","url":"\/documentation\/stripepayments\/stppaymentmethodlinkparams\/init"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodLinkParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodLinkParams","kind":"identifier"}],"title":"STPPaymentMethodLinkParams","abstract":[{"text":"An object representing parameters used to create an Link Payment Method","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodLinkParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodlinkparams"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/title","value":"STPPaymentMethodLinkParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodLinkParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodLinkParams"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}