{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"paymentDetailsID"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"abstract":[{"type":"text","text":":nodoc:"}],"metadata":{"fragments":[{"kind":"identifier","text":"paymentDetailsID"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"paymentDetailsID"}],"title":"paymentDetailsID","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodLinkParams(py)paymentDetailsID"},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams\/paymentDetailsID","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodlinkparams\/paymentdetailsid"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodLinkParams/paymentDetailsID":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodlinkparams\/paymentdetailsid","abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol","title":"paymentDetailsID","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams\/paymentDetailsID","fragments":[{"text":"paymentDetailsID","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodLinkParams":{"navigatorTitle":[{"text":"STPPaymentMethodLinkParams","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodlinkparams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodLinkParams","abstract":[{"text":"An object representing parameters used to create an Link Payment Method","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodLinkParams","kind":"identifier"}],"role":"symbol","title":"STPPaymentMethodLinkParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/title","value":"STPPaymentMethodLinkParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/fragments","value":[{"text":"STPPaymentMethodLinkParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodLinkParams\/navigatorTitle","value":[{"text":"STPPaymentMethodLinkParams","kind":"identifier"}]}]}]}