{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","text":"STPPaymentMethodCardParams"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Only a card’s ","type":"text"},{"code":"cvc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"expMonth","type":"codeVoice"},{"text":", ","type":"text"},{"code":"expYear","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"networks.preferred","type":"codeVoice"},{"text":" can be updated.","type":"text"}]}],"style":"note","name":"Note","type":"aside"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/card","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodupdateparams\/card"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodupdateparams\/card"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"card","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams(py)card","role":"symbol","navigatorTitle":[{"text":"card","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"If this is a card PaymentMethod, this contains the user’s card details.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams","abstract":[{"text":"An object representing parameters used to update a PaymentMethod object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"kind":"symbol","title":"STPPaymentMethodUpdateParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","url":"\/documentation\/stripepayments\/stppaymentmethodcardparams","type":"topic","title":"STPPaymentMethodCardParams","abstract":[{"type":"text","text":"The user’s card details."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardParams"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/card":{"kind":"symbol","type":"topic","abstract":[{"text":"If this is a card PaymentMethod, this contains the user’s card details.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/card","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/card","title":"card","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"card","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"card","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"card"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"card"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodUpdateParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUpdateParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/navigatorTitle","value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/title","value":"STPPaymentMethodCardParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/fragments","value":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCardParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1card\/title","value":"card","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1card\/fragments","value":[{"text":"card","kind":"identifier"}],"op":"replace"}]}]}