{"kind":"article","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodupdateparams\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodupdateparams\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams"]]},"sections":[],"topicSections":[{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/rootObjectName()"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/STPFormEncodable-Implementations"},"metadata":{"title":"STPFormEncodable Implementations","roleHeading":"API Collection","modules":[{"name":"StripePayments"}],"role":"collectionGroup"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/propertyNamesToFormFieldNamesMapping()":{"url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/propertynamestoformfieldnamesmapping()","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/propertyNamesToFormFieldNamesMapping()","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"type":"codeVoice","code":"expMonth"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"title":"propertyNamesToFormFieldNamesMapping()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams","type":"topic","title":"STPPaymentMethodUpdateParams","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUpdateParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUpdateParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to update a PaymentMethod object."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/rootObjectName()":{"title":"rootObjectName()","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/rootobjectname()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/rootObjectName()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/rootObjectName()"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"propertyNamesToFormFieldNamesMapping","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1propertyNamesToFormFieldNamesMapping()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1propertyNamesToFormFieldNamesMapping()\/fragments"},{"value":"STPPaymentMethodUpdateParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/title"},{"value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/fragments"},{"value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/navigatorTitle"},{"value":"rootObjectName","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1rootObjectName()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1rootObjectName()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}