{"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"AddressViewController"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","title":"AddressViewController","modules":[{"name":"StripePaymentSheet"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AddressViewController","kind":"identifier"}],"externalID":"c:@M@StripePaymentSheet@objc(cs)STPAddressViewController"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)NSCoding","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payment-sheet\/s7CVarArgP","doc:\/\/com.stripe.stripe-payment-sheet\/s8CopyableP","doc:\/\/com.stripe.stripe-payment-sheet\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payment-sheet\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payment-sheet\/SQ","doc:\/\/com.stripe.stripe-payment-sheet\/SH","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIAdaptivePresentationControllerDelegate","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIAppearanceContainer","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIContentContainer","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIFocusEnvironment","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIStateRestoring","doc:\/\/com.stripe.stripe-payment-sheet\/5UIKit23UITraitChangeObservableP","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UITraitEnvironment","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPAddressViewController) ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AddressViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"It uses "},{"type":"codeVoice","code":"navigationItem"},{"type":"text","text":" and can push a view controller, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"https:\/\/stripe.com\/docs\/elements\/address-element?platform=ios","type":"text"}]}],"style":"note","name":"See Also","type":"aside"}],"kind":"content"}],"abstract":[{"type":"text","text":"A view controller that collects a name and an address, with full localization and autocomplete."}],"variants":[{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller"]}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/AddressDetails","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct"],"anchor":"Structures","generated":true,"title":"Structures"},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/init(configuration:delegate:)"],"generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/configuration-swift.property","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/delegate"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/viewDidAppear(_:)","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/viewDidLoad()"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIAdaptivePresentationControllerDelegate-Implementations","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIGestureRecognizerDelegate-Implementations"]}],"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct":{"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"AddressViewController.Configuration","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration for an "},{"code":"AddressViewController","type":"codeVoice"},{"text":" instance.","type":"text"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/viewDidLoad()":{"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/viewdidload()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"role":"symbol","title":"viewDidLoad()","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/viewDidLoad()"},"doc://com.stripe.stripe-payment-sheet/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)NSExtensionRequestHandling"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UITraitEnvironment"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIGestureRecognizerDelegate","title":"UIGestureRecognizerDelegate"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://com.stripe.stripe-payment-sheet/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payment-sheet/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(cs)UIViewController","title":"UIViewController"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/viewDidAppear(_:)":{"kind":"symbol","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/viewdidappear(_:)","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/viewDidAppear(_:)","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIAdaptivePresentationControllerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIAdaptivePresentationControllerDelegate","title":"UIAdaptivePresentationControllerDelegate"},"doc://com.stripe.stripe-payment-sheet/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/configuration-swift.property":{"abstract":[{"type":"text","text":"Configuration containing e.g. appearance styling properties, default values, etc."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/configuration-swift.property","type":"topic","title":"configuration","kind":"symbol","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.property"},"doc://com.stripe.stripe-payment-sheet/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"title":"StripePaymentSheet","role":"collection","url":"\/documentation\/stripepaymentsheet","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","kind":"symbol","abstract":[{"text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app.","type":"text"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/init(configuration:delegate:)":{"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/init(configuration:delegate:)","type":"topic","role":"symbol","title":"init(configuration:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV","text":"Configuration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18StripePaymentSheet29AddressViewControllerDelegateP","text":"AddressViewControllerDelegate"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/init(configuration:delegate:)","kind":"symbol","abstract":[{"text":"Initializes an ","type":"text"},{"type":"codeVoice","code":"AddressViewController"},{"text":".","type":"text"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/AddressDetails":{"navigatorTitle":[{"kind":"identifier","text":"AddressDetails"}],"abstract":[{"text":"The customer data collected by ","type":"text"},{"code":"AddressViewController","type":"codeVoice"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/addressdetails","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/AddressDetails","role":"symbol","type":"topic","title":"AddressViewController.AddressDetails","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressDetails"}]},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/UIAdaptivePresentationControllerDelegate-Implementations":{"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations","role":"collectionGroup","title":"UIAdaptivePresentationControllerDelegate Implementations","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIAdaptivePresentationControllerDelegate-Implementations","type":"topic","kind":"article","abstract":[]},"doc://com.stripe.stripe-payment-sheet/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/delegate":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AddressViewControllerDelegate","preciseIdentifier":"s:18StripePaymentSheet29AddressViewControllerDelegateP"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The delegate, notified when the customer completes or cancels."}],"kind":"symbol","title":"delegate","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/delegate"},"doc://com.stripe.stripe-payment-sheet/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://com.stripe.stripe-payment-sheet/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.stripe.stripe-payment-sheet/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payment-sheet/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payment-sheet/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","title":"AddressViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AddressViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AddressViewController"}],"type":"topic","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","abstract":[{"text":"A view controller that collects a name and an address, with full localization and autocomplete.","type":"text"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/UIGestureRecognizerDelegate-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIGestureRecognizerDelegate-Implementations","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/uigesturerecognizerdelegate-implementations","abstract":[],"type":"topic","kind":"article","title":"UIGestureRecognizerDelegate Implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payment-sheet/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPAddressViewController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPAddressViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPAddressViewController","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/viewDidAppear(_:)","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/viewDidLoad()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIAdaptivePresentationControllerDelegate-Implementations","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/UIGestureRecognizerDelegate-Implementations"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/objc(cs)UIViewController"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIAdaptivePresentationControllerDelegate","doc:\/\/com.stripe.stripe-payment-sheet\/objc(pl)UIGestureRecognizerDelegate"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"STPAddressViewController","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1viewDidLoad()\/fragments"},{"value":"viewDidAppear:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1viewDidAppear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}]},{"op":"replace","value":"STPAddressViewController","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","value":[{"kind":"identifier","text":"STPAddressViewController"}]},{"value":[{"text":"STPAddressViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle","op":"replace"}]}]}