{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate"]]},"abstract":[{"text":"Called when the form transitions from complete to incomplete or vice-versa.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate\/auBECSDebitForm(_:didChangeToStateComplete:)"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"auBECSDebitForm"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"form","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPAUBECSDebitFormView","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeToStateComplete"},{"text":" ","kind":"text"},{"text":"complete","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"STPAUBECSDebitFormView","type":"codeVoice"},{"type":"text","text":" instance whose completion state has changed"}],"type":"paragraph"}],"name":"form"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Whether the form is considered complete and can generate an ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"text":" instance.","type":"text"}]}],"name":"complete"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate\/aubecsdebitform(_:didchangetostatecomplete:)"]},{"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate\/aubecsdebitform(_:didchangetostatecomplete:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"StripePaymentsUI"}],"required":true,"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"auBECSDebitForm"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView","kind":"typeIdentifier","text":"STPAUBECSDebitFormView"},{"kind":"text","text":", "},{"text":"didChangeToStateComplete","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:@M@StripePaymentsUI@objc(pl)STPAUBECSDebitFormViewDelegate(im)auBECSDebitForm:didChangeToStateComplete:","navigatorTitle":[{"text":"auBECSDebitForm:didChangeToStateComplete:","kind":"identifier"}],"title":"auBECSDebitForm(_:didChangeToStateComplete:)"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormViewDelegate":{"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate","role":"symbol","type":"topic","title":"STPAUBECSDebitFormViewDelegate","navigatorTitle":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"STPAUBECSDebitFormViewDelegate provides methods for STPAUBECSDebitFormView to inform its delegate"},{"type":"text","text":" "},{"text":"of when the form has been completed.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormViewDelegate/auBECSDebitForm(_:didChangeToStateComplete:)":{"role":"symbol","navigatorTitle":[{"text":"auBECSDebitForm:didChangeToStateComplete:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Called when the form transitions from complete to incomplete or vice-versa.","type":"text"}],"type":"topic","title":"auBECSDebitForm(_:didChangeToStateComplete:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate\/auBECSDebitForm(_:didChangeToStateComplete:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"auBECSDebitForm"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView","text":"STPAUBECSDebitFormView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didChangeToStateComplete","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate\/aubecsdebitform(_:didchangetostatecomplete:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","role":"symbol","type":"topic","title":"STPAUBECSDebitFormView","navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"kind":"symbol","abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"type":"text","text":" "},{"text":"For additional customization options - seealso: STPFormTextFieldContainer","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"auBECSDebitForm:didChangeToStateComplete:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"auBECSDebitForm:didChangeToStateComplete:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"auBECSDebitForm:"},{"text":"(","kind":"text"},{"text":"STPAUBECSDebitFormView","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"form"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didChangeToStateComplete:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"complete","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"STPAUBECSDebitFormView","type":"codeVoice"},{"type":"text","text":" instance whose completion state has changed"}],"type":"paragraph"}],"name":"form"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the form is considered complete and can generate an "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":" instance.","type":"text"}]}],"name":"complete"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"STPAUBECSDebitFormViewDelegate","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/fragments","value":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate~1auBECSDebitForm(_:didChangeToStateComplete:)\/title","value":"auBECSDebitForm:didChangeToStateComplete:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"auBECSDebitForm:didChangeToStateComplete:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate~1auBECSDebitForm(_:didChangeToStateComplete:)\/fragments"},{"value":"STPAUBECSDebitFormView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"op":"replace"}]}]}