{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatesource:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatesource:completion:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"This method is deprecated as of v16.0.0 (https:\/\/github.com\/stripe\/stripe-ios\/blob\/master\/MIGRATING.md#migrating-from-versions–1600)."},{"text":" ","type":"text"},{"text":"To use this class, migrate your integration from Charges to PaymentIntents. See https:\/\/stripe.com\/docs\/payments\/payment-intents\/migration\/charges#read","type":"text"}],"sections":[],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use addCardViewController(_:didCreatePaymentMethod:completion:) instead and migrate your integration to PaymentIntents. See https:\/\/stripe.com\/docs\/payments\/payment-intents\/migration\/charges#read"}],"type":"paragraph"}],"metadata":{"modules":[{"name":"Stripe"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addCardViewController"},{"text":"(","kind":"text"},{"text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didCreateSource","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","kind":"typeIdentifier","text":"STPSource"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"platforms":[],"symbolKind":"method","required":true,"externalID":"c:@M@Stripe@objc(pl)STPAddCardViewControllerDelegate(im)addCardViewController:didCreateSource:completion:","roleHeading":"Instance Method","role":"symbol","title":"addCardViewController(_:didCreateSource:completion:)","navigatorTitle":[{"text":"addCardViewController:didCreateSource:completion:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateSource:completion:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addCardViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"addCardViewController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","text":"STPAddCardViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didCreateSource","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"source"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPSource":{"url":"\/documentation\/stripe\/stpsource","kind":"symbol","abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSource","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"role":"symbol","title":"STPSource","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPAddCardViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPAddCardViewController"},{"text":" ","type":"text"},{"type":"text","text":"successfully creates a card token or is cancelled. It has internal error-handling"},{"text":" ","type":"text"},{"text":"logic, so there’s no error case to deal with.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddCardViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate","role":"symbol","title":"STPAddCardViewControllerDelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"url":"\/documentation\/stripe\/stperrorblock","navigatorTitle":[{"text":"STPErrorBlock","kind":"identifier"}],"abstract":[{"text":"A block that may optionally be called with an error.","type":"text"}],"title":"STPErrorBlock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPErrorBlock","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate/addCardViewController(_:didCreateSource:completion:)":{"deprecated":false,"navigatorTitle":[{"text":"addCardViewController:didCreateSource:completion:","kind":"identifier"}],"abstract":[{"type":"text","text":"This method is deprecated as of v16.0.0 (https:\/\/github.com\/stripe\/stripe-ios\/blob\/master\/MIGRATING.md#migrating-from-versions–1600)."},{"type":"text","text":" "},{"type":"text","text":"To use this class, migrate your integration from Charges to PaymentIntents. See https:\/\/stripe.com\/docs\/payments\/payment-intents\/migration\/charges#read"}],"type":"topic","required":true,"role":"symbol","url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatesource:completion:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateSource:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addCardViewController"},{"text":"(","kind":"text"},{"text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didCreateSource","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","kind":"typeIdentifier","text":"STPSource"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"title":"addCardViewController(_:didCreateSource:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"addCardViewController:didCreateSource:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"addCardViewController:didCreateSource:completion:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"addCardViewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPAddCardViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":" *) "},{"text":"addCardViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCreateSource:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"source"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/title","value":"STPAddCardViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/fragments","value":[{"text":"STPAddCardViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController"},{"value":[{"text":"STPAddCardViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","op":"replace"},{"value":"addCardViewController:didCreateSource:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreateSource:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreateSource:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreateSource:completion:"}]}]}]}
