{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@Stripe@objc(pl)STPAddCardViewControllerDelegate(im)addCardViewController:didCreatePaymentMethod:completion:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addCardViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPAddCardViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"text":": ","kind":"text"},{"text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments13STPErrorBlocka","kind":"typeIdentifier","text":"STPErrorBlock"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"addCardViewController(_:didCreatePaymentMethod:completion:)","modules":[{"name":"Stripe"}],"required":true,"role":"symbol","navigatorTitle":[{"text":"addCardViewController:didCreatePaymentMethod:completion:","kind":"identifier"}]},"abstract":[{"type":"text","text":"This is called when the user successfully adds a card and Stripe returns a"},{"text":" ","type":"text"},{"text":"Payment Method.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You should send the PaymentMethod to your backend to store it on a customer, and then"},{"text":" ","type":"text"},{"type":"text","text":"call the provided "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when that call is finished. If an error"},{"type":"text","text":" "},{"type":"text","text":"occurs while talking to your backend, call "},{"code":"completion(error)","type":"codeVoice"},{"type":"text","text":", otherwise,"},{"type":"text","text":" "},{"type":"text","text":"dismiss (or pop) the view controller."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addCardViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"addCardViewController","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","text":"STPAddCardViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"paymentMethod"},{"text":": ","kind":"text"},{"text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the view controller that successfully created a token"}]}],"name":"addCardViewController"},{"name":"paymentMethod","content":[{"inlineContent":[{"type":"text","text":"the Payment Method that was created. - seealso: STPPaymentMethod"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"call this callback when you’re done sending the token to your backend","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatepaymentmethod:completion:)"]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatepaymentmethod:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreatePaymentMethod:completion:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate/addCardViewController(_:didCreatePaymentMethod:completion:)":{"type":"topic","role":"symbol","title":"addCardViewController(_:didCreatePaymentMethod:completion:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreatePaymentMethod:completion:)","required":true,"kind":"symbol","abstract":[{"type":"text","text":"This is called when the user successfully adds a card and Stripe returns a"},{"text":" ","type":"text"},{"text":"Payment Method.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You should send the PaymentMethod to your backend to store it on a customer, and then"},{"text":" ","type":"text"},{"type":"text","text":"call the provided "},{"code":"completion","type":"codeVoice"},{"type":"text","text":" block when that call is finished. If an error"},{"type":"text","text":" "},{"type":"text","text":"occurs while talking to your backend, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":", otherwise,"},{"type":"text","text":" "},{"type":"text","text":"dismiss (or pop) the view controller."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addCardViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","kind":"typeIdentifier","text":"STPAddCardViewController"},{"kind":"text","text":", "},{"text":"didCreatePaymentMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"addCardViewController:didCreatePaymentMethod:completion:","kind":"identifier"}],"url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatepaymentmethod:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate":{"type":"topic","role":"symbol","title":"STPAddCardViewControllerDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","kind":"symbol","abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"STPAddCardViewControllerDelegate"},{"text":" is notified when an ","type":"text"},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":" "},{"type":"text","text":"successfully creates a card token or is cancelled. It has internal error-handling"},{"type":"text","text":" "},{"text":"logic, so there’s no error case to deal with.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethod":{"abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","role":"symbol","title":"STPPaymentMethod","url":"\/documentation\/stripe\/stppaymentmethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"title":"STPAddCardViewController","abstract":[{"type":"text","text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"}],"navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"type":"topic","title":"STPErrorBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"navigatorTitle":[{"text":"STPErrorBlock","kind":"identifier"}],"url":"\/documentation\/stripe\/stperrorblock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"addCardViewController:didCreatePaymentMethod:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"addCardViewController:didCreatePaymentMethod:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addCardViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"addCardViewController"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didCreatePaymentMethod:"},{"text":"(","kind":"text"},{"text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethod"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreatePaymentMethod:completion:)\/title","op":"replace","value":"addCardViewController:didCreatePaymentMethod:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreatePaymentMethod:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreatePaymentMethod:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/title","value":"STPAddCardViewControllerDelegate"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/fragments","op":"replace","value":[{"text":"STPAddCardViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","value":[{"text":"STPAddCardViewController","kind":"identifier"}]}]}]}
