{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"addCardViewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","text":"STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreateToken"},{"kind":"text","text":" "},{"kind":"internalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","text":"STPToken"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatetoken:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatetoken:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateToken:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method is deprecated as of v16.0.0 (https:\/\/github.com\/stripe\/stripe-ios\/blob\/master\/MIGRATING.md#migrating-from-versions–1600)."},{"type":"text","text":" "},{"type":"text","text":"To use this class, migrate your integration from Charges to PaymentIntents. See https:\/\/stripe.com\/docs\/payments\/payment-intents\/migration\/charges#read"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"addCardViewController:didCreateToken:completion:"}],"role":"symbol","title":"addCardViewController(_:didCreateToken:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreateToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@Stripe@objc(pl)STPAddCardViewControllerDelegate(im)addCardViewController:didCreateToken:completion:","modules":[{"name":"Stripe"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use addCardViewController(_:didCreatePaymentMethod:completion:) instead and migrate your integration to PaymentIntents. See https:\/\/stripe.com\/docs\/payments\/payment-intents\/migration\/charges#read"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"role":"symbol","title":"STPErrorBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPErrorBlock"}],"url":"\/documentation\/stripe\/stperrorblock"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"role":"symbol","title":"STPAddCardViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewController"}],"abstract":[{"type":"text","text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewController"}],"url":"\/documentation\/stripe\/stpaddcardviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate/addCardViewController(_:didCreateToken:completion:)":{"deprecated":false,"role":"symbol","title":"addCardViewController(_:didCreateToken:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreateToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method is deprecated as of v16.0.0 (https:\/\/github.com\/stripe\/stripe-ios\/blob\/master\/MIGRATING.md#migrating-from-versions–1600)."},{"type":"text","text":" "},{"type":"text","text":"To use this class, migrate your integration from Charges to PaymentIntents. See https:\/\/stripe.com\/docs\/payments\/payment-intents\/migration\/charges#read"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate\/addCardViewController(_:didCreateToken:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCardViewController:didCreateToken:completion:"}],"url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate\/addcardviewcontroller(_:didcreatetoken:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPToken":{"role":"symbol","title":"STPToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPToken"}],"abstract":[{"type":"text","text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPToken"}],"url":"\/documentation\/stripe\/stptoken"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewControllerDelegate":{"role":"symbol","title":"STPAddCardViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPAddCardViewControllerDelegate"},{"type":"text","text":" is notified when an "},{"type":"codeVoice","code":"STPAddCardViewController"},{"type":"text","text":" "},{"type":"text","text":"successfully creates a card token or is cancelled. It has internal error-handling"},{"type":"text","text":" "},{"type":"text","text":"logic, so there’s no error case to deal with."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}],"url":"\/documentation\/stripe\/stpaddcardviewcontrollerdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addCardViewController:didCreateToken:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreateToken:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addCardViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","text":"STPAddCardViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"addCardViewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCreateToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","text":"STPToken"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"token"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title","value":"STPAddCardViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreateToken:completion:)\/title","value":"addCardViewController:didCreateToken:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate~1addCardViewController(_:didCreateToken:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCardViewController:didCreateToken:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/title","value":"STPAddCardViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPAddCardViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
