{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/!=(_:_:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/Equatable-Implementations"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpredirectcontexterror\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"metadata":{"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@StripePayments@E@STPRedirectContextError","title":"!=(_:_:)","extendedModule":"Swift","roleHeading":"Operator","modules":[{"relatedModules":["Swift"],"name":"StripePayments"}],"symbolKind":"op","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/!=(_:_:)":{"url":"\/documentation\/stripepayments\/stpredirectcontexterror\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/Equatable-Implementations":{"kind":"article","url":"\/documentation\/stripepayments\/stpredirectcontexterror\/equatable-implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/Equatable-Implementations","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontexterror","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPRedirectContextError","kind":"identifier"}],"abstract":[{"type":"text","text":"Error codes specific to "},{"type":"codeVoice","code":"STPRedirectContext"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError","title":"STPRedirectContextError","type":"topic","navigatorTitle":[{"text":"STPRedirectContextError","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/title","value":"STPRedirectContextError","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPRedirectContextError"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/navigatorTitle","value":[{"text":"STPRedirectContextError","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}