{"kind":"symbol","metadata":{"title":"STPRedirectContextError.appRedirectError","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"appRedirectError"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPRedirectContextError@STPRedirectContextAppRedirectError","navigatorTitle":[{"text":"STPRedirectContextAppRedirectError","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/appRedirectError"},"abstract":[{"code":"STPRedirectContext","type":"codeVoice"},{"type":"text","text":" failed to redirect to the app to complete the payment."},{"text":" ","type":"text"},{"text":"This could be because the app is not installed on the user’s device.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPRedirectContextAppRedirectError) ","kind":"text"},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"appRedirectError","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontexterror\/appredirecterror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontexterror\/appredirecterror"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError","url":"\/documentation\/stripepayments\/stpredirectcontexterror","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContextError"}],"type":"topic","abstract":[{"text":"Error codes specific to ","type":"text"},{"type":"codeVoice","code":"STPRedirectContext"}],"title":"STPRedirectContextError","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextError"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/appRedirectError":{"url":"\/documentation\/stripepayments\/stpredirectcontexterror\/appredirecterror","abstract":[{"type":"codeVoice","code":"STPRedirectContext"},{"type":"text","text":" failed to redirect to the app to complete the payment."},{"type":"text","text":" "},{"type":"text","text":"This could be because the app is not installed on the user’s device."}],"type":"topic","title":"STPRedirectContextError.appRedirectError","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appRedirectError"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/appRedirectError","kind":"symbol","navigatorTitle":[{"text":"STPRedirectContextAppRedirectError","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"STPRedirectContextAppRedirectError","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPRedirectContextAppRedirectError"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPRedirectContextAppRedirectError"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/title","op":"replace","value":"STPRedirectContextError"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/fragments","op":"replace","value":[{"text":"STPRedirectContextError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/navigatorTitle","value":[{"kind":"identifier","text":"STPRedirectContextError"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError~1appRedirectError\/title","op":"replace","value":"STPRedirectContextAppRedirectError"},{"value":[{"kind":"identifier","text":"STPRedirectContextAppRedirectError"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError~1appRedirectError\/fragments","op":"replace"}]}]}