{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontexterror\/hashvalue"]}],"metadata":{"role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@StripePayments@E@STPRedirectContextError","extendedModule":"Swift","title":"hashValue","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"relatedModules":["Swift"],"name":"StripePayments"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/hashValue","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/RawRepresentable-Implementations"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/hashValue":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/hashValue","role":"symbol","title":"hashValue","type":"topic","abstract":[],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/stripepayments\/stpredirectcontexterror\/hashvalue"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError":{"role":"symbol","abstract":[{"type":"text","text":"Error codes specific to "},{"code":"STPRedirectContext","type":"codeVoice"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError","kind":"symbol","navigatorTitle":[{"text":"STPRedirectContextError","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpredirectcontexterror","type":"topic","title":"STPRedirectContextError","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRedirectContextError","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/stripepayments\/stpredirectcontexterror\/rawrepresentable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/title","op":"replace","value":"STPRedirectContextError"},{"value":[{"text":"STPRedirectContextError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/navigatorTitle","value":[{"kind":"identifier","text":"STPRedirectContextError"}]}]}]}