{"abstract":[{"type":"text","text":"Owner’s verified billing address. Values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","text":"STPPaymentMethodAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletmasterpass\/billingaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletmasterpass\/billingaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletMasterpass\/billingAddress"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"billingAddress"}],"role":"symbol","title":"billingAddress","modules":[{"name":"StripePayments"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletMasterpass(py)billingAddress"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletMasterpass"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletMasterpass/billingAddress":{"title":"billingAddress","kind":"symbol","abstract":[{"type":"text","text":"Owner’s verified billing address. Values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletmasterpass\/billingaddress","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletMasterpass\/billingAddress","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"billingAddress"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodaddress","kind":"symbol","abstract":[{"type":"text","text":"The billing address, a property on "},{"type":"codeVoice","code":"STPPaymentMethodBillingDetails"}],"title":"STPPaymentMethodAddress","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAddress"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodAddress"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletMasterpass":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletMasterpass","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletmasterpass","kind":"symbol","title":"STPPaymentMethodCardWalletMasterpass","abstract":[{"type":"text","text":"A Masterpass Card Wallet"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletMasterpass"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletMasterpass"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"billingAddress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"billingAddress","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress"},{"text":" * ","kind":"text"},{"text":"billingAddress","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletMasterpass~1billingAddress\/title","value":"billingAddress"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletMasterpass~1billingAddress\/fragments","op":"replace","value":[{"text":"billingAddress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/title","op":"replace","value":"STPPaymentMethodAddress"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/fragments","op":"replace","value":[{"text":"STPPaymentMethodAddress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodAddress"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletMasterpass\/title","op":"replace","value":"STPPaymentMethodCardWalletMasterpass"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletMasterpass\/fragments","op":"replace","value":[{"text":"STPPaymentMethodCardWalletMasterpass","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletMasterpass\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletMasterpass"}]}]}]}