{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"case","title":"STPPinStatus.ephemeralKeyError","role":"symbol","navigatorTitle":[{"text":"STPPinStatusEphemeralKeyError","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPinStatus@STPPinStatusEphemeralKeyError","modules":[{"name":"StripePayments"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ephemeralKeyError","kind":"identifier"}]},"abstract":[{"text":"An error occured while retrieving the ephemeral key","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ephemeralKeyError","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/ephemeralKeyError"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppinstatus\/ephemeralkeyerror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppinstatus\/ephemeralkeyerror"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"type":"topic","url":"\/documentation\/stripepayments\/stppinstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","abstract":[{"type":"text","text":"An enum representing the success and error states of PIN management"}],"title":"STPPinStatus","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPinStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPinStatus"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/ephemeralKeyError":{"type":"topic","url":"\/documentation\/stripepayments\/stppinstatus\/ephemeralkeyerror","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/ephemeralKeyError","abstract":[{"text":"An error occured while retrieving the ephemeral key","type":"text"}],"title":"STPPinStatus.ephemeralKeyError","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPinStatusEphemeralKeyError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ephemeralKeyError","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPinStatusEphemeralKeyError","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPinStatusEphemeralKeyError","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPinStatusEphemeralKeyError"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title","value":"STPPinStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","value":[{"text":"STPPinStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle","value":[{"text":"STPPinStatus","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1ephemeralKeyError\/title","value":"STPPinStatusEphemeralKeyError","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1ephemeralKeyError\/fragments","value":[{"text":"STPPinStatusEphemeralKeyError","kind":"identifier"}],"op":"replace"}]}]}