{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationCodeIncorrect","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@StripePayments@E@STPPinStatus@STPPinStatusErrorVerificationCodeIncorrect","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorVerificationCodeIncorrect","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPinStatusErrorVerificationCodeIncorrect"}],"title":"STPPinStatus.errorVerificationCodeIncorrect"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorVerificationCodeIncorrect"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppinstatus\/errorverificationcodeincorrect"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppinstatus\/errorverificationcodeincorrect"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"abstract":[{"text":"The one-time code was incorrect","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","role":"symbol","url":"\/documentation\/stripepayments\/stppinstatus","navigatorTitle":[{"kind":"identifier","text":"STPPinStatus"}],"title":"STPPinStatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPinStatus","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An enum representing the success and error states of PIN management","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/errorVerificationCodeIncorrect":{"title":"STPPinStatus.errorVerificationCodeIncorrect","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationCodeIncorrect","url":"\/documentation\/stripepayments\/stppinstatus\/errorverificationcodeincorrect","abstract":[{"text":"The one-time code was incorrect","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorVerificationCodeIncorrect","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPinStatusErrorVerificationCodeIncorrect"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"STPPinStatusErrorVerificationCodeIncorrect","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"STPPinStatusErrorVerificationCodeIncorrect"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPPinStatusErrorVerificationCodeIncorrect","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPinStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","value":[{"kind":"identifier","text":"STPPinStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPPinStatus"}]},{"value":"STPPinStatusErrorVerificationCodeIncorrect","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationCodeIncorrect\/title"},{"value":[{"text":"STPPinStatusErrorVerificationCodeIncorrect","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationCodeIncorrect\/fragments"}]}]}
