{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@StripePayments@E@STPPinStatus@STPPinStatusErrorVerificationExpired","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPinStatusErrorVerificationExpired","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorVerificationExpired","kind":"identifier"}],"symbolKind":"case","title":"STPPinStatus.errorVerificationExpired","roleHeading":"Case","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppinstatus\/errorverificationexpired"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppinstatus\/errorverificationexpired"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorVerificationExpired"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"The verification object was expired","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationExpired"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/errorVerificationExpired":{"navigatorTitle":[{"text":"STPPinStatusErrorVerificationExpired","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorVerificationExpired","kind":"identifier"}],"abstract":[{"type":"text","text":"The verification object was expired"}],"url":"\/documentation\/stripepayments\/stppinstatus\/errorverificationexpired","type":"topic","title":"STPPinStatus.errorVerificationExpired","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationExpired"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"type":"topic","kind":"symbol","abstract":[{"text":"An enum representing the success and error states of PIN management","type":"text"}],"navigatorTitle":[{"text":"STPPinStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPinStatus","kind":"identifier"}],"role":"symbol","title":"STPPinStatus","url":"\/documentation\/stripepayments\/stppinstatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPinStatusErrorVerificationExpired"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPinStatusErrorVerificationExpired","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPPinStatusErrorVerificationExpired","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationExpired\/title","value":"STPPinStatusErrorVerificationExpired"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationExpired\/fragments","value":[{"text":"STPPinStatusErrorVerificationExpired","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title","value":"STPPinStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","value":[{"kind":"identifier","text":"STPPinStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPPinStatus"}]}]}]}