{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorVerificationTooManyAttempts","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","title":"STPPinStatus.errorVerificationTooManyAttempts","externalID":"c:@M@StripePayments@E@STPPinStatus@STPPinStatusErrorVerificationTooManyAttempts","symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"errorVerificationTooManyAttempts","kind":"identifier"}],"navigatorTitle":[{"text":"STPPinStatusErrorVerificationTooManyAttempts","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppinstatus\/errorverificationtoomanyattempts"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppinstatus\/errorverificationtoomanyattempts"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationTooManyAttempts"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The verification object has been attempted too many times"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/errorVerificationTooManyAttempts":{"abstract":[{"type":"text","text":"The verification object has been attempted too many times"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationTooManyAttempts","url":"\/documentation\/stripepayments\/stppinstatus\/errorverificationtoomanyattempts","role":"symbol","title":"STPPinStatus.errorVerificationTooManyAttempts","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorVerificationTooManyAttempts"}],"navigatorTitle":[{"kind":"identifier","text":"STPPinStatusErrorVerificationTooManyAttempts"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","navigatorTitle":[{"kind":"identifier","text":"STPPinStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPinStatus"}],"url":"\/documentation\/stripepayments\/stppinstatus","title":"STPPinStatus","abstract":[{"type":"text","text":"An enum representing the success and error states of PIN management"}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPPinStatusErrorVerificationTooManyAttempts"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPinStatusErrorVerificationTooManyAttempts","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPinStatusErrorVerificationTooManyAttempts"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"STPPinStatusErrorVerificationTooManyAttempts","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationTooManyAttempts\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationTooManyAttempts\/fragments","value":[{"kind":"identifier","text":"STPPinStatusErrorVerificationTooManyAttempts"}],"op":"replace"},{"op":"replace","value":"STPPinStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","op":"replace","value":[{"text":"STPPinStatus","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPinStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}