{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"STPPinStatus.errorVerificationAlreadyRedeemed","externalID":"c:@M@StripePayments@E@STPPinStatus@STPPinStatusErrorVerificationAlreadyRedeemed","role":"symbol","roleHeading":"Case","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorVerificationAlreadyRedeemed"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPPinStatusErrorVerificationAlreadyRedeemed"}]},"abstract":[{"type":"text","text":"The verification object was already redeemed"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationAlreadyRedeemed","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stppinstatus\/errorverificationalreadyredeemed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppinstatus\/errorverificationalreadyredeemed"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorVerificationAlreadyRedeemed"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPinStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppinstatus","type":"topic","role":"symbol","kind":"symbol","title":"STPPinStatus","navigatorTitle":[{"kind":"identifier","text":"STPPinStatus"}],"abstract":[{"text":"An enum representing the success and error states of PIN management","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/errorVerificationAlreadyRedeemed":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorVerificationAlreadyRedeemed"}],"kind":"symbol","title":"STPPinStatus.errorVerificationAlreadyRedeemed","type":"topic","abstract":[{"text":"The verification object was already redeemed","type":"text"}],"url":"\/documentation\/stripepayments\/stppinstatus\/errorverificationalreadyredeemed","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationAlreadyRedeemed","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPinStatusErrorVerificationAlreadyRedeemed"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPPinStatusErrorVerificationAlreadyRedeemed"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPinStatusErrorVerificationAlreadyRedeemed","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPinStatusErrorVerificationAlreadyRedeemed"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title","op":"replace","value":"STPPinStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","value":[{"text":"STPPinStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPinStatus"}]},{"value":"STPPinStatusErrorVerificationAlreadyRedeemed","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationAlreadyRedeemed\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationAlreadyRedeemed\/fragments","value":[{"kind":"identifier","text":"STPPinStatusErrorVerificationAlreadyRedeemed"}]}]}]}