{"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"API Collection","role":"collectionGroup","title":"RawRepresentable Implementations"},"variants":[{"paths":["\/documentation\/stripepayments\/stppinstatus\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/hashValue"]},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/hash(into:)"],"title":"Instance Methods"}],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPinStatus"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPinStatus"}],"abstract":[{"type":"text","text":"An enum representing the success and error states of PIN management"}],"type":"topic","title":"STPPinStatus","role":"symbol","url":"\/documentation\/stripepayments\/stppinstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/hash(into:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"hash(into:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/hash(into:)","role":"symbol","kind":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"url":"\/documentation\/stripepayments\/stppinstatus\/hash(into:)","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/hashValue":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/hashValue","kind":"symbol","title":"hashValue","abstract":[],"role":"symbol","type":"topic","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"url":"\/documentation\/stripepayments\/stppinstatus\/hashvalue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title","value":"STPPinStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","value":[{"text":"STPPinStatus","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPPinStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}