{"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppinstatus\/success"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppinstatus\/success"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The verification object was already redeemed"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"success","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","role":"symbol","title":"STPPinStatus.success","externalID":"c:@M@StripePayments@E@STPPinStatus@STPPinStatusSuccess","navigatorTitle":[{"text":"STPPinStatusSuccess","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/success","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPinStatus","kind":"identifier"}],"title":"STPPinStatus","abstract":[{"type":"text","text":"An enum representing the success and error states of PIN management"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPinStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","kind":"symbol","url":"\/documentation\/stripepayments\/stppinstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/success":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"title":"STPPinStatus.success","abstract":[{"type":"text","text":"The verification object was already redeemed"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPinStatusSuccess","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/success","kind":"symbol","url":"\/documentation\/stripepayments\/stppinstatus\/success"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPPinStatusSuccess","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPPinStatusSuccess"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"identifier","text":"STPPinStatusSuccess"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPinStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPinStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPinStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle","op":"replace"},{"value":"STPPinStatusSuccess","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1success\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPinStatusSuccess"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1success\/fragments","op":"replace"}]}]}