{"identifier":{"url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/AdditionalFields-swift.struct\/FieldConfiguration\/required","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/AdditionalFields-swift.struct","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/AdditionalFields-swift.struct\/FieldConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/additionalfields-swift.struct\/fieldconfiguration\/required"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"The field is displayed, but the customer is required to fill it in. If the customer doesn’t, the sheet displays an error and disables the continue button."}],"metadata":{"externalID":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV16AdditionalFieldsV05FieldG0O8requiredyA2ImF","symbolKind":"case","roleHeading":"Case","title":"AddressViewController.Configuration.AdditionalFields.FieldConfiguration.required","modules":[{"name":"StripePaymentSheet"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"required","kind":"identifier"}],"role":"symbol"},"sections":[],"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/AdditionalFields-swift.struct/FieldConfiguration":{"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/additionalfields-swift.struct\/fieldconfiguration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FieldConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Whether a field should be hidden, optional, or required."}],"role":"symbol","title":"AddressViewController.Configuration.AdditionalFields.FieldConfiguration","navigatorTitle":[{"text":"FieldConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/AdditionalFields-swift.struct\/FieldConfiguration","type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct":{"type":"topic","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct","title":"AddressViewController.Configuration","abstract":[{"text":"Configuration for an ","type":"text"},{"code":"AddressViewController","type":"codeVoice"},{"text":" instance.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/AdditionalFields-swift.struct":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/AdditionalFields-swift.struct","abstract":[{"type":"text","text":"Configuration related to the collection of additional fields beyond the physical address."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalFields"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdditionalFields"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/additionalfields-swift.struct","title":"AddressViewController.Configuration.AdditionalFields"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressViewController"}],"title":"AddressViewController","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","abstract":[{"type":"text","text":"A view controller that collects a name and an address, with full localization and autocomplete."}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/AdditionalFields-swift.struct/FieldConfiguration/required":{"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/additionalfields-swift.struct\/fieldconfiguration\/required","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"required","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The field is displayed, but the customer is required to fill it in. If the customer doesn’t, the sheet displays an error and disables the continue button."}],"role":"symbol","title":"AddressViewController.Configuration.AdditionalFields.FieldConfiguration.required","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/AdditionalFields-swift.struct\/FieldConfiguration\/required","type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","title":"StripePaymentSheet","url":"\/documentation\/stripepaymentsheet","kind":"symbol","type":"topic","abstract":[{"text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","value":"STPAddressViewController"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAddressViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle","value":[{"text":"STPAddressViewController","kind":"identifier"}]}]}]}
