{"metadata":{"extendedModule":"StripePayments","modules":[{"name":"StripePayments"}],"externalID":"c:@CM@StripePayments@objc(cs)STPIntentActionCashAppRedirectToApp(cm)decodedObjectFromAPIResponse:","role":"symbol","roleHeading":"Type Method","title":"decodedObject(fromAPIResponse:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"STPAPIResponseDecodable.decodedObject(fromAPIResponse:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp\/decodedobject(fromapiresponse:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp\/decodedobject(fromapiresponse:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionCashAppRedirectToApp/decodedObject(fromAPIResponse:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"abstract":[],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"title":"decodedObject(fromAPIResponse:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp\/decodedObject(fromAPIResponse:)","type":"topic","url":"\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp\/decodedobject(fromapiresponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionCashAppRedirectToApp":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionCashAppRedirectToApp","kind":"identifier"}],"abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"code":"STPIntentActionCashAppRedirectToApp","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"STPIntentActionCashAppRedirectToApp","kind":"identifier"}],"title":"STPIntentActionCashAppRedirectToApp","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp","url":"\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/title","value":"STPIntentActionCashAppRedirectToApp"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/fragments","value":[{"kind":"identifier","text":"STPIntentActionCashAppRedirectToApp"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionCashAppRedirectToApp"}]}]}]}