{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp"]]},"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods","title":"Type Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp\/STPAPIResponseDecodable-Implementations","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"collectionGroup","title":"STPAPIResponseDecodable Implementations","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp\/stpapiresponsedecodable-implementations"]},{"paths":["\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp\/stpapiresponsedecodable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionCashAppRedirectToApp/decodedObject(fromAPIResponse:)":{"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp\/decodedObject(fromAPIResponse:)","kind":"symbol","title":"decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp\/decodedobject(fromapiresponse:)","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionCashAppRedirectToApp":{"role":"symbol","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App."},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentActionCashAppRedirectToApp","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/stripepayments\/stpintentactioncashappredirecttoapp","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionCashAppRedirectToApp"}],"title":"STPIntentActionCashAppRedirectToApp","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionCashAppRedirectToApp"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionCashAppRedirectToApp\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"op":"replace"},{"value":"STPIntentActionCashAppRedirectToApp","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/fragments","value":[{"text":"STPIntentActionCashAppRedirectToApp","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionCashAppRedirectToApp\/navigatorTitle","value":[{"text":"STPIntentActionCashAppRedirectToApp","kind":"identifier"}]}]}]}