{"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSourceUsage@STPSourceUsageReusable","symbolKind":"case","title":"STPSourceUsage.reusable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reusable"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceUsageReusable"}],"role":"symbol","roleHeading":"Case"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/reusable","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reusable"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceusage\/reusable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceusage\/reusable"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The source can be reused."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage":{"url":"\/documentation\/stripepayments\/stpsourceusage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceUsage"}],"abstract":[{"type":"text","text":"Usage types for a Source"}],"kind":"symbol","type":"topic","title":"STPSourceUsage","navigatorTitle":[{"kind":"identifier","text":"STPSourceUsage"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/reusable":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/reusable","kind":"symbol","title":"STPSourceUsage.reusable","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reusable"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceUsageReusable"}],"url":"\/documentation\/stripepayments\/stpsourceusage\/reusable","abstract":[{"text":"The source can be reused.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPSourceUsageReusable","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceUsageReusable"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPSourceUsageReusable","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPSourceUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/navigatorTitle"},{"op":"replace","value":"STPSourceUsageReusable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1reusable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceUsageReusable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1reusable\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}