{"metadata":{"externalID":"c:@M@StripePayments@E@STPSourceUsage@STPSourceUsageSingleUse","role":"symbol","title":"STPSourceUsage.singleUse","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleUse","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPSourceUsageSingleUse","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleUse","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/singleUse","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"The source can only be used once.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceusage\/singleuse"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceusage\/singleuse"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage":{"role":"symbol","title":"STPSourceUsage","navigatorTitle":[{"kind":"identifier","text":"STPSourceUsage"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage","url":"\/documentation\/stripepayments\/stpsourceusage","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPSourceUsage","kind":"identifier"}],"abstract":[{"type":"text","text":"Usage types for a Source"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/singleUse":{"role":"symbol","url":"\/documentation\/stripepayments\/stpsourceusage\/singleuse","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/singleUse","title":"STPSourceUsage.singleUse","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceUsageSingleUse"}],"abstract":[{"type":"text","text":"The source can only be used once."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"singleUse","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceUsageSingleUse"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPSourceUsageSingleUse","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceUsageSingleUse"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/title","value":"STPSourceUsage"},{"op":"replace","value":[{"text":"STPSourceUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/fragments"},{"value":[{"text":"STPSourceUsage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1singleUse\/title","value":"STPSourceUsageSingleUse"},{"value":[{"kind":"identifier","text":"STPSourceUsageSingleUse"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1singleUse\/fragments"}]}]}