{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/unknown","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage"]]},"abstract":[{"text":"The source’s usage is unknown.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceusage\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceusage\/unknown"]}],"sections":[],"metadata":{"externalID":"c:@M@StripePayments@E@STPSourceUsage@STPSourceUsageUnknown","modules":[{"name":"StripePayments"}],"symbolKind":"case","roleHeading":"Case","title":"STPSourceUsage.unknown","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceUsageUnknown"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceUsage","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceusage","abstract":[{"type":"text","text":"Usage types for a Source"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage","role":"symbol","title":"STPSourceUsage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceUsage"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/unknown":{"navigatorTitle":[{"text":"STPSourceUsageUnknown","kind":"identifier"}],"abstract":[{"type":"text","text":"The source’s usage is unknown."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/unknown","kind":"symbol","title":"STPSourceUsage.unknown","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourceusage\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceUsageUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceUsageUnknown"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPSourceUsageUnknown","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/title","value":"STPSourceUsage"},{"value":[{"text":"STPSourceUsage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceUsage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1unknown\/title","value":"STPSourceUsageUnknown"},{"value":[{"text":"STPSourceUsageUnknown","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1unknown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}