{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlmaParams"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodalmaparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlmaParams(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init"},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlmaParams\/init"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlmaParams":{"type":"topic","role":"symbol","title":"STPPaymentMethodAlmaParams","kind":"symbol","abstract":[{"text":"An object representing parameters used to create a Alma Payment Method","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlmaParams","url":"\/documentation\/stripepayments\/stppaymentmethodalmaparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAlmaParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodAlmaParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlmaParams/init":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlmaParams\/init","url":"\/documentation\/stripepayments\/stppaymentmethodalmaparams\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentMethodAlmaParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlmaParams\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodAlmaParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlmaParams\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodAlmaParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlmaParams\/navigatorTitle"}]}]}