{"kind":"symbol","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"metadata":{"symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet(cm)decodedObjectFromAPIResponse:","modules":[{"name":"StripePayments"}],"title":"decodedObject(fromAPIResponse:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"response","content":[{"inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"text":" ","type":"text"},{"text":"could not be decoded (i.e. if one of its ","type":"text"},{"type":"codeVoice","code":"requiredFields"},{"text":" is nil).","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet\/decodedobject(fromapiresponse:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet\/decodedobject(fromapiresponse:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/decodedObject(fromAPIResponse:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/decodedObject(fromAPIResponse:)","type":"topic","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/decodedobject(fromapiresponse:)","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"title":"decodedObject(fromAPIResponse:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWallet"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet","kind":"symbol","title":"STPPaymentMethodCardWallet","abstract":[{"type":"text","text":"A Card Wallet."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"response","content":[{"type":"paragraph","inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}]}]}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"text":" ","type":"text"},{"text":"could not be decoded (i.e. if one of its ","type":"text"},{"code":"requiredFields","type":"codeVoice"},{"text":" is nil).","type":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1decodedObject(fromAPIResponse:)\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1decodedObject(fromAPIResponse:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/title","op":"replace","value":"STPPaymentMethodCardWallet"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}