{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet\/masterpass"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet\/masterpass"]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"masterpass"}],"role":"symbol","title":"masterpass","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet(py)masterpass","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"masterpass","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardWalletMasterpass","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletMasterpass"},{"text":"?","kind":"text"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"masterpass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardWalletMasterpass","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletMasterpass","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletMasterpass"},{"kind":"text","text":"? { get }"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Contains additional Masterpass information, if the type of the Card Wallet is "},{"type":"codeVoice","code":"STPPaymentMethodCardWalletTypeMasterpass"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/masterpass","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/masterpass":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"masterpass","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletMasterpass","text":"STPPaymentMethodCardWalletMasterpass","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Contains additional Masterpass information, if the type of the Card Wallet is "},{"type":"codeVoice","code":"STPPaymentMethodCardWalletTypeMasterpass"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/masterpass","title":"masterpass","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/masterpass","type":"topic","navigatorTitle":[{"text":"masterpass","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet","navigatorTitle":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet","title":"STPPaymentMethodCardWallet","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"abstract":[{"type":"text","text":"A Card Wallet."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletMasterpass":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletMasterpass","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletmasterpass","kind":"symbol","title":"STPPaymentMethodCardWalletMasterpass","abstract":[{"type":"text","text":"A Masterpass Card Wallet"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletMasterpass"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletMasterpass"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"masterpass"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"masterpass","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletMasterpass","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletMasterpass","text":"STPPaymentMethodCardWalletMasterpass","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"masterpass","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1masterpass\/title","op":"replace","value":"masterpass"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1masterpass\/fragments","op":"replace","value":[{"kind":"identifier","text":"masterpass"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/title","op":"replace","value":"STPPaymentMethodCardWallet"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/fragments","op":"replace","value":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletMasterpass\/title","op":"replace","value":"STPPaymentMethodCardWalletMasterpass"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletMasterpass\/fragments","op":"replace","value":[{"text":"STPPaymentMethodCardWalletMasterpass","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletMasterpass\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodCardWalletMasterpass","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}