{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet\/type"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The type of the Card Wallet. A matching property is populated if the type is "},{"code":"STPPaymentMethodCardWalletTypeMasterpass","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"STPPaymentMethodCardWalletTypeVisaCheckout","type":"codeVoice"},{"type":"text","text":" containing additional information specific to the Card Wallet type."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/type"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType","text":"STPPaymentMethodCardWalletType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","kind":"typeIdentifier"},{"kind":"text","text":" { get }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet(py)type","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardWalletType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"type"}],"title":"type","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet"]]},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","title":"STPPaymentMethodCardWalletType","abstract":[{"type":"text","text":"The type of Card Wallet."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/type":{"abstract":[{"type":"text","text":"The type of the Card Wallet. A matching property is populated if the type is "},{"type":"codeVoice","code":"STPPaymentMethodCardWalletTypeMasterpass"},{"type":"text","text":" or "},{"type":"codeVoice","code":"STPPaymentMethodCardWalletTypeVisaCheckout"},{"type":"text","text":" containing additional information specific to the Card Wallet type."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardWalletType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType"}],"title":"type","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/type","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/type","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet":{"kind":"symbol","abstract":[{"type":"text","text":"A Card Wallet."}],"title":"STPPaymentMethodCardWallet","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"type","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType","text":"STPPaymentMethodCardWalletType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/title","op":"replace","value":"STPPaymentMethodCardWalletType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/fragments","value":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/navigatorTitle"},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1type\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/title","value":"STPPaymentMethodCardWallet","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}