{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visaCheckout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout","text":"STPPaymentMethodCardWalletVisaCheckout"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"visaCheckout","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"visaCheckout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardWalletVisaCheckout","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout"},{"kind":"text","text":"?"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet(py)visaCheckout","navigatorTitle":[{"kind":"identifier","text":"visaCheckout"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/visaCheckout"},"kind":"symbol","abstract":[{"text":"Contains additional Visa Checkout information, if the type of the Card Wallet is ","type":"text"},{"code":"STPPaymentMethodCardWalletTypeVisaCheckout","type":"codeVoice"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet\/visacheckout"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet\/visacheckout"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout":{"abstract":[{"text":"A Visa Checkout Card Wallet","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"title":"STPPaymentMethodCardWalletVisaCheckout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet":{"abstract":[{"type":"text","text":"A Card Wallet."}],"kind":"symbol","title":"STPPaymentMethodCardWallet","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/visaCheckout":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/visacheckout","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visaCheckout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout","text":"STPPaymentMethodCardWalletVisaCheckout","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"visaCheckout","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/visaCheckout","navigatorTitle":[{"text":"visaCheckout","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Contains additional Visa Checkout information, if the type of the Card Wallet is ","type":"text"},{"code":"STPPaymentMethodCardWalletTypeVisaCheckout","type":"codeVoice"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"visaCheckout"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"visaCheckout"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout"},{"text":" * ","kind":"text"},{"text":"visaCheckout","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentMethodCardWalletVisaCheckout","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/title"},{"value":[{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/fragments"},{"value":[{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/navigatorTitle"},{"value":"STPPaymentMethodCardWallet","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/title"},{"value":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/fragments"},{"value":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/navigatorTitle"},{"value":"visaCheckout","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1visaCheckout\/title"},{"value":[{"text":"visaCheckout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1visaCheckout\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}