//
// StripeAPIConfiguration+Version.swift
//
// This file was generated by update_version.sh
// Do not edit this file directly.
// Instead, edit the `VERSION` file and run `ci_scripts/update_version.sh`
//

import Foundation

extension StripeAPIConfiguration {
    /// The current version of this library.
    public static let STPSDKVersion = "24.12.1"

    // NOTE: `STPSDKVersion` must be a hard-coded static string instead of
    // dynamically generated from the bundle's `CFBundleShortVersionString` to
    // ensure the correct value is returned when the SDK is statically linked.

}
