{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24Params"]]},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24Params(im)init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodprzelewy24params\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24Params\/init"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPrzelewy24Params":{"title":"STPPaymentMethodPrzelewy24Params","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24Params","type":"topic","abstract":[{"text":"An object representing parameters used to create a Przelewy24 Payment Method","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodprzelewy24params","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodPrzelewy24Params","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodPrzelewy24Params","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPrzelewy24Params/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodprzelewy24params\/init","title":"init","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24Params\/init","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24Params\/title","value":"STPPaymentMethodPrzelewy24Params"},{"op":"replace","value":[{"text":"STPPaymentMethodPrzelewy24Params","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24Params\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24Params\/navigatorTitle","value":[{"text":"STPPaymentMethodPrzelewy24Params","kind":"identifier"}],"op":"replace"}]}]}