{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"errorColor"}],"symbolKind":"property","externalID":"c:@M@Stripe@objc(cs)STPTheme(py)errorColor","roleHeading":"Instance Property","title":"errorColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"modules":[{"name":"Stripe"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripe\/stptheme\/errorcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stptheme\/errorcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/errorColor","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The error color of this theme - it will be used for rendering any error messages or views."}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/errorColor":{"kind":"symbol","abstract":[{"type":"text","text":"The error color of this theme - it will be used for rendering any error messages or views."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/errorColor","url":"\/documentation\/stripe\/stptheme\/errorcolor","role":"symbol","title":"errorColor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorColor"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","type":"topic","abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"title":"STPTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTheme","kind":"identifier"}],"url":"\/documentation\/stripe\/stptheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"errorColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"errorColor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"errorColor"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1errorColor\/title","value":"errorColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1errorColor\/fragments","value":[{"kind":"identifier","text":"errorColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","value":"STPTheme"},{"value":[{"kind":"identifier","text":"STPTheme"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments"}]}]}
