{"variants":[{"paths":["\/documentation\/stripe\/stptheme\/nscopying-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stptheme\/nscopying-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/NSCopying-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/copy(with:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"Stripe"}],"role":"collectionGroup","title":"NSCopying Implementations"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"role":"symbol","title":"STPTheme","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTheme"}],"abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}],"url":"\/documentation\/stripe\/stptheme"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/copy(with:)":{"role":"symbol","title":"copy(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSZone","preciseIdentifier":"s:10ObjectiveC6NSZoneV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/copy(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"url":"\/documentation\/stripe\/stptheme\/copy(with:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/copy(with:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","value":"STPTheme"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","value":[{"kind":"identifier","text":"STPTheme"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1copy(with:)\/title","value":"copyWithZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1copy(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
