{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"symbolKind":"property","externalID":"c:@M@Stripe@objc(cs)STPTheme(py)primaryBackgroundColor","navigatorTitle":[{"kind":"identifier","text":"primaryBackgroundColor"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"primaryBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"primaryBackgroundColor","modules":[{"name":"Stripe"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/primaryBackgroundColor"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryBackgroundColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stptheme\/primarybackgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stptheme\/primarybackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The primary background color of the theme. This will be used as the "},{"type":"codeVoice","code":"backgroundColor"},{"text":" for any views with this theme.","type":"text"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/primaryBackgroundColor":{"kind":"symbol","abstract":[{"type":"text","text":"The primary background color of the theme. This will be used as the "},{"code":"backgroundColor","type":"codeVoice"},{"type":"text","text":" for any views with this theme."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"primaryBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/primaryBackgroundColor","url":"\/documentation\/stripe\/stptheme\/primarybackgroundcolor","role":"symbol","title":"primaryBackgroundColor","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primaryBackgroundColor"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","type":"topic","abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"title":"STPTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTheme","kind":"identifier"}],"url":"\/documentation\/stripe\/stptheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"primaryBackgroundColor"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"primaryBackgroundColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"primaryBackgroundColor"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"primaryBackgroundColor","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1primaryBackgroundColor\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1primaryBackgroundColor\/fragments","op":"replace","value":[{"text":"primaryBackgroundColor","kind":"identifier"}]},{"value":"STPTheme","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","value":[{"kind":"identifier","text":"STPTheme"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
