{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quaternaryBackgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/stripe\/stptheme\/quaternarybackgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stptheme\/quaternarybackgroundcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPTheme(py)quaternaryBackgroundColor","title":"quaternaryBackgroundColor","role":"symbol","navigatorTitle":[{"text":"quaternaryBackgroundColor","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"Stripe"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"quaternaryBackgroundColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/quaternaryBackgroundColor"},"kind":"symbol","abstract":[{"type":"text","text":"This color is automatically derived by reducing the brightness of the "},{"type":"codeVoice","code":"primaryBackgroundColor"},{"text":" and is used as a separator color in table view cells.","type":"text"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/quaternaryBackgroundColor":{"kind":"symbol","title":"quaternaryBackgroundColor","navigatorTitle":[{"kind":"identifier","text":"quaternaryBackgroundColor"}],"role":"symbol","abstract":[{"type":"text","text":"This color is automatically derived by reducing the brightness of the "},{"type":"codeVoice","code":"primaryBackgroundColor"},{"type":"text","text":" and is used as a separator color in table view cells."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"quaternaryBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"url":"\/documentation\/stripe\/stptheme\/quaternarybackgroundcolor","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/quaternaryBackgroundColor","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPTheme","kind":"identifier"}],"navigatorTitle":[{"text":"STPTheme","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stptheme","kind":"symbol","abstract":[{"text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information.","type":"text"}],"title":"STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"quaternaryBackgroundColor","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"quaternaryBackgroundColor","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"quaternaryBackgroundColor","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1quaternaryBackgroundColor\/title","value":"quaternaryBackgroundColor","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1quaternaryBackgroundColor\/fragments","value":[{"text":"quaternaryBackgroundColor","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPTheme","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","value":[{"text":"STPTheme","kind":"identifier"}]}]}]}
