{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stptheme\/smallfont"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stptheme\/smallfont"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/smallFont","interfaceLanguage":"swift"},"metadata":{"title":"smallFont","navigatorTitle":[{"kind":"identifier","text":"smallFont"}],"externalID":"c:@M@Stripe@objc(cs)STPTheme(py)smallFont","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"smallFont"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"modules":[{"name":"Stripe"}]},"abstract":[{"type":"text","text":"This font is automatically derived from the font, with a slightly lower point size, and will be used for supplementary labels."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smallFont"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme/smallFont":{"kind":"symbol","title":"smallFont","navigatorTitle":[{"text":"smallFont","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This font is automatically derived from the font, with a slightly lower point size, and will be used for supplementary labels."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"smallFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"}],"url":"\/documentation\/stripe\/stptheme\/smallfont","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme\/smallFont","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPTheme","kind":"identifier"}],"navigatorTitle":[{"text":"STPTheme","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stptheme","kind":"symbol","abstract":[{"text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information.","type":"text"}],"title":"STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"smallFont","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"smallFont"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"smallFont","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1smallFont\/title","value":"smallFont"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme~1smallFont\/fragments","value":[{"kind":"identifier","text":"smallFont"}]},{"op":"replace","value":"STPTheme","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title"},{"op":"replace","value":[{"text":"STPTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments"}]}]}
