{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createIssuingCardKeyWithAPIVersion:completion:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createIssuingCardKey"},{"kind":"text","text":"("},{"text":"withAPIVersion","kind":"externalParam"},{"kind":"text","text":" "},{"text":"apiVersion","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPJSONResponseCompletionBlock","preciseIdentifier":"s:14StripePayments30STPJSONResponseCompletionBlocka","text":"STPJSONResponseCompletionBlock"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"apiVersion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Stripe API version to use when creating a key."},{"type":"text","text":" "},{"text":"You should pass this parameter to your backend, and use it to set the API version","type":"text"},{"type":"text","text":" "},{"type":"text","text":"in your key creation request. Passing this version parameter ensures that the"},{"type":"text","text":" "},{"type":"text","text":"Stripe SDK can always parse the ephemeral key response from your server."}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Call this callback when you’re done fetching a new ephemeral"},{"text":" ","type":"text"},{"type":"text","text":"key from your backend. For example, "},{"type":"codeVoice","code":"completion(json, nil)"},{"type":"text","text":" (if your call succeeds)"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"code":"completion(nil, error)","type":"codeVoice"},{"type":"text","text":" if an error is returned."}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider\/createIssuingCardKey(withAPIVersion:completion:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"text":"Creates a new ephemeral key for retrieving and updating a Stripe Issuing Card.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"On your backend, you should create a new ephemeral key for your logged-in user’s"},{"type":"text","text":" "},{"type":"text","text":"primary Issuing Card, and return the raw JSON response from the Stripe API."},{"text":" ","type":"text"},{"type":"text","text":"For an example Ruby implementation of this API, refer to our example backend:"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/github.com\/stripe\/example-mobile-backend\/blob\/v18.1.0\/web.rb"},{"type":"text","text":" "},{"text":"Back in your iOS app, once you have a response from this API, call the provided","type":"text"},{"type":"text","text":" "},{"type":"text","text":"completion block with the JSON response, or an error if one occurred."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpissuingcardephemeralkeyprovider\/createissuingcardkey(withapiversion:completion:)"]},{"paths":["\/documentation\/stripe\/stpissuingcardephemeralkeyprovider\/createissuingcardkey(withapiversion:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"createIssuingCardKey(withAPIVersion:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createIssuingCardKey"},{"kind":"text","text":"("},{"text":"withAPIVersion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPJSONResponseCompletionBlock","preciseIdentifier":"s:14StripePayments30STPJSONResponseCompletionBlocka"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@Stripe@objc(pl)STPIssuingCardEphemeralKeyProvider(im)createIssuingCardKeyWithAPIVersion:completion:","modules":[{"name":"Stripe"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"createIssuingCardKeyWithAPIVersion:completion:"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider"]]},"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPJSONResponseCompletionBlock":{"title":"STPJSONResponseCompletionBlock","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPJSONResponseCompletionBlock","role":"symbol","navigatorTitle":[{"text":"STPJSONResponseCompletionBlock","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"STPJSONResponseCompletionBlock","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripe\/stpjsonresponsecompletionblock","abstract":[{"type":"text","text":"A callback to be run with a JSON response."}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"title":"Stripe","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/stripe","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","abstract":[]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPIssuingCardEphemeralKeyProvider/createIssuingCardKey(withAPIVersion:completion:)":{"type":"topic","url":"\/documentation\/stripe\/stpissuingcardephemeralkeyprovider\/createissuingcardkey(withapiversion:completion:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider\/createIssuingCardKey(withAPIVersion:completion:)","title":"createIssuingCardKey(withAPIVersion:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createIssuingCardKeyWithAPIVersion:completion:"}],"kind":"symbol","abstract":[{"text":"Creates a new ephemeral key for retrieving and updating a Stripe Issuing Card.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"On your backend, you should create a new ephemeral key for your logged-in user’s"},{"text":" ","type":"text"},{"type":"text","text":"primary Issuing Card, and return the raw JSON response from the Stripe API."},{"text":" ","type":"text"},{"type":"text","text":"For an example Ruby implementation of this API, refer to our example backend:"},{"text":" ","type":"text"},{"text":"https:\/\/github.com\/stripe\/example-mobile-backend\/blob\/v18.1.0\/web.rb","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Back in your iOS app, once you have a response from this API, call the provided"},{"type":"text","text":" "},{"type":"text","text":"completion block with the JSON response, or an error if one occurred."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createIssuingCardKey","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAPIVersion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments30STPJSONResponseCompletionBlocka","text":"STPJSONResponseCompletionBlock"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPIssuingCardEphemeralKeyProvider":{"type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"}],"url":"\/documentation\/stripe\/stpissuingcardephemeralkeyprovider","abstract":[{"text":"You should make your application’s API client conform to this interface.","type":"text"},{"text":" ","type":"text"},{"text":"It provides a way for Stripe utility classes to request a new ephemeral key from","type":"text"},{"type":"text","text":" "},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"title":"STPIssuingCardEphemeralKeyProvider","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPIssuingCardEphemeralKeyProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"createIssuingCardKeyWithAPIVersion:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createIssuingCardKeyWithAPIVersion:completion:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"createIssuingCardKeyWithAPIVersion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"apiVersion"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"apiVersion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Stripe API version to use when creating a key."},{"type":"text","text":" "},{"type":"text","text":"You should pass this parameter to your backend, and use it to set the API version"},{"text":" ","type":"text"},{"type":"text","text":"in your key creation request. Passing this version parameter ensures that the"},{"type":"text","text":" "},{"text":"Stripe SDK can always parse the ephemeral key response from your server.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Call this callback when you’re done fetching a new ephemeral"},{"type":"text","text":" "},{"text":"key from your backend. For example, ","type":"text"},{"type":"codeVoice","code":"completion(json, nil)"},{"type":"text","text":" (if your call succeeds)"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"type":"codeVoice","code":"completion(nil, error)"},{"type":"text","text":" if an error is returned."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}},{"op":"replace","value":"createIssuingCardKeyWithAPIVersion:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider~1createIssuingCardKey(withAPIVersion:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"createIssuingCardKeyWithAPIVersion:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider~1createIssuingCardKey(withAPIVersion:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/title","value":"STPIssuingCardEphemeralKeyProvider"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIssuingCardEphemeralKeyProvider"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPIssuingCardEphemeralKeyProvider\/navigatorTitle","value":[{"text":"STPIssuingCardEphemeralKeyProvider","kind":"identifier"}],"op":"replace"}]}]}