{"abstract":[{"text":"Returns brand API string value from given card brand.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(apiValueFromCardBrand:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]},{"parameters":[{"name":"brand","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"STPCardBrand","type":"codeVoice"},{"type":"text","text":" to transform into a string."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"String"},{"type":"text","text":" representing the card brand. This could be “visa”,"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardbrandutilities\/apivalue(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardbrandutilities\/apivalue(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities\/apiValue(from:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities"]]},"metadata":{"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPCardBrandUtilities(cm)apiValueFromCardBrand:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"StripePayments"}],"title":"apiValue(from:)","navigatorTitle":[{"text":"apiValueFromCardBrand:","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrandUtilities/apiValue(from:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities\/apiValue(from:)","title":"apiValue(from:)","abstract":[{"type":"text","text":"Returns brand API string value from given card brand."}],"url":"\/documentation\/stripepayments\/stpcardbrandutilities\/apivalue(from:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"apiValueFromCardBrand:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","url":"\/documentation\/stripepayments\/stpcardbrand","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"title":"STPCardBrand","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrandUtilities":{"title":"STPCardBrandUtilities","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardBrandUtilities"}],"type":"topic","abstract":[{"type":"text","text":"Contains "},{"type":"codeVoice","code":"STPStringFromCardBrand"}],"url":"\/documentation\/stripepayments\/stpcardbrandutilities","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardBrandUtilities"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"apiValueFromCardBrand:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"apiValueFromCardBrand:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"apiValueFromCardBrand:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"brand","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPCardBrand"},{"type":"text","text":" to transform into a string."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"String"},{"type":"text","text":" representing the card brand. This could be “visa”,"}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities~1apiValue(from:)\/title","value":"apiValueFromCardBrand:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities~1apiValue(from:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"apiValueFromCardBrand:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","value":"STPCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"text":"STPCardBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","value":[{"text":"STPCardBrand","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/title","value":"STPCardBrandUtilities"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/fragments","value":[{"kind":"identifier","text":"STPCardBrandUtilities"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/navigatorTitle","value":[{"text":"STPCardBrandUtilities","kind":"identifier"}]}]}]}