{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities\/init"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardbrandutilities\/init"]}],"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@StripePayments@objc(cs)STPCardBrandUtilities(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrandUtilities/init":{"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities\/init","url":"\/documentation\/stripepayments\/stpcardbrandutilities\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrandUtilities":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardBrandUtilities","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcardbrandutilities","abstract":[{"text":"Contains ","type":"text"},{"code":"STPStringFromCardBrand","type":"codeVoice"}],"navigatorTitle":[{"text":"STPCardBrandUtilities","kind":"identifier"}],"title":"STPCardBrandUtilities","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/title","value":"STPCardBrandUtilities","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/fragments","value":[{"text":"STPCardBrandUtilities","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPCardBrandUtilities"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/navigatorTitle"}]}]}