{"metadata":{"navigatorTitle":[{"text":"stringFromCardBrand:","kind":"identifier"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPCardBrandUtilities(cm)stringFromCardBrand:","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stringFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"stringFrom(_:)","modules":[{"name":"StripePayments"}]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardbrandutilities\/stringfrom(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardbrandutilities\/stringfrom(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities\/stringFrom(_:)"},"abstract":[{"type":"text","text":"Returns a string representation for the provided card brand;"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"type":"codeVoice","code":"STPCardBrandUtilities.stringFrom(brand: .visa) == \"Visa\""},{"type":"text","text":"."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(stringFromCardBrand:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringFrom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand you want to convert to a string"}]}],"name":"brand"}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A string representing the brand, suitable for displaying to a user.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrandUtilities":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities","url":"\/documentation\/stripepayments\/stpcardbrandutilities","title":"STPCardBrandUtilities","type":"topic","abstract":[{"text":"Contains ","type":"text"},{"type":"codeVoice","code":"STPStringFromCardBrand"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrandUtilities","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardBrandUtilities","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrandUtilities/stringFrom(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringFromCardBrand:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringFrom"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"stringFrom(_:)","abstract":[{"type":"text","text":"Returns a string representation for the provided card brand;"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"type":"codeVoice","code":"STPCardBrandUtilities.stringFrom(brand: .visa) == \"Visa\""},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrandUtilities\/stringFrom(_:)","role":"symbol","url":"\/documentation\/stripepayments\/stpcardbrandutilities\/stringfrom(_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}],"title":"STPCardBrand","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"stringFromCardBrand:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"stringFromCardBrand:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"stringFromCardBrand:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"},{"text":") ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"brand","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand you want to convert to a string"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A string representing the brand, suitable for displaying to a user.","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"STPCardBrandUtilities","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/title"},{"value":[{"text":"STPCardBrandUtilities","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/fragments"},{"value":[{"kind":"identifier","text":"STPCardBrandUtilities"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities\/navigatorTitle"},{"value":"stringFromCardBrand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities~1stringFrom(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFromCardBrand:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrandUtilities~1stringFrom(_:)\/fragments"},{"value":"STPCardBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}