{"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualverification\/additionaldocument"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualverification\/additionaldocument"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"additionalDocument","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualVerification(py)additionalDocument","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalDocument","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountVerificationDocument","text":"STPConnectAccountVerificationDocument","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"additionalDocument","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification\/additionalDocument"},"kind":"symbol","abstract":[{"type":"text","text":"A document showing address, either a passport, local ID card, or utility bill from a well-known utility company."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalDocument"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPConnectAccountVerificationDocument","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountVerificationDocument"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualVerification/additionalDocument":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification\/additionalDocument","role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountindividualverification\/additionaldocument","title":"additionalDocument","abstract":[{"text":"A document showing address, either a passport, local ID card, or utility bill from a well-known utility company.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"additionalDocument"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalDocument"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountVerificationDocument","kind":"typeIdentifier","text":"STPConnectAccountVerificationDocument"},{"kind":"text","text":"?"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualVerification":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountindividualverification","abstract":[{"type":"text","text":"The individual’s verification document information for use with "},{"type":"codeVoice","code":"STPConnectAccountIndividualParams"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountIndividualVerification","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPConnectAccountIndividualVerification","kind":"identifier"}],"title":"STPConnectAccountIndividualVerification","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountVerificationDocument":{"title":"STPConnectAccountVerificationDocument","abstract":[{"type":"text","text":"An identifying document, either a passport or local ID card for use with "},{"code":"STPConnectAccountIndividualVerification","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountVerificationDocument"}],"navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountVerificationDocument"}],"url":"\/documentation\/stripepayments\/stpconnectaccountverificationdocument","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"additionalDocument","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"additionalDocument"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountVerificationDocument","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument","text":"STPConnectAccountVerificationDocument"},{"kind":"text","text":" * "},{"kind":"identifier","text":"additionalDocument"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification~1additionalDocument\/title","value":"additionalDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification~1additionalDocument\/fragments","value":[{"text":"additionalDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/title","value":"STPConnectAccountIndividualVerification"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountIndividualVerification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/navigatorTitle","value":[{"kind":"identifier","text":"STPConnectAccountIndividualVerification"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument\/title","value":"STPConnectAccountVerificationDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountVerificationDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument\/navigatorTitle","value":[{"text":"STPConnectAccountVerificationDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}