{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualVerification(im)init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualverification\/init"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification\/init","interfaceLanguage":"occ"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualVerification/init":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification\/init","title":"init","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconnectaccountindividualverification\/init","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualVerification":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification","abstract":[{"text":"The individual’s verification document information for use with ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountIndividualParams"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountIndividualVerification","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconnectaccountindividualverification","title":"STPConnectAccountIndividualVerification","navigatorTitle":[{"text":"STPConnectAccountIndividualVerification","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/title","op":"replace","value":"STPConnectAccountIndividualVerification"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountIndividualVerification"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountIndividualVerification"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}