{"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceparams\/alipayparams(withamount:currency:returnurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/alipayparams(withamount:currency:returnurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayParams(withAmount:currency:returnURL:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"alipayParamsWithAmount:currency:returnURL:"}],"title":"alipayParams(withAmount:currency:returnURL:)","roleHeading":"Type Method","role":"symbol","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)alipayParamsWithAmount:currency:returnURL:","extendedModule":"StripePayments","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"alipayParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}]},"abstract":[{"text":"Creates params for a single-use Alipay source","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipayParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"amount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"amount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount to charge the customer."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The currency the payment is being created in."}]}],"name":"currency"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the customer should be redirected to after they have"},{"type":"text","text":" "},{"type":"text","text":"successfully verified the payment."}]}],"name":"returnURL"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An STPSourceParams object populated with the provided values"}]}]},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Alipay#Create-Source"}]}],"style":"note","name":"See Also"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"title":"STPSourceParams","url":"\/documentation\/stripepayments\/stpsourceparams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/alipayParams(withAmount:currency:returnURL:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayParams(withAmount:currency:returnURL:)","url":"\/documentation\/stripepayments\/stpsourceparams\/alipayparams(withamount:currency:returnurl:)","title":"alipayParams(withAmount:currency:returnURL:)","navigatorTitle":[{"kind":"identifier","text":"alipayParamsWithAmount:currency:returnURL:"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"alipayParams"},{"kind":"text","text":"("},{"text":"withAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Creates params for a single-use Alipay source"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"alipayParamsWithAmount:currency:returnURL:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"alipayParamsWithAmount:currency:returnURL:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"alipayParamsWithAmount:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"amount","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currency:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"currency","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"returnURL"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"amount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount to charge the customer."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The currency the payment is being created in.","type":"text"}]}],"name":"currency"},{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the customer should be redirected to after they have"},{"type":"text","text":" "},{"type":"text","text":"successfully verified the payment."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An STPSourceParams object populated with the provided values"}]}],"kind":"content"}},{"value":"STPSourceParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"value":"alipayParamsWithAmount:currency:returnURL:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1alipayParams(withAmount:currency:returnURL:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1alipayParams(withAmount:currency:returnURL:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"alipayParamsWithAmount:currency:returnURL:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}