{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"StripePayments"}],"extendedModule":"StripePayments","navigatorTitle":[{"text":"alipayReusableParamsWithCurrency:returnURL:","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)alipayReusableParamsWithCurrency:returnURL:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alipayReusableParams"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCurrency"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}],"symbolKind":"method","role":"symbol","title":"alipayReusableParams(withCurrency:returnURL:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alipayReusableParams"},{"kind":"text","text":"("},{"text":"withCurrency","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"currency","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The currency the payment is being created in."}],"type":"paragraph"}],"name":"currency"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the customer should be redirected to after they have"},{"type":"text","text":" "},{"type":"text","text":"successfully verified the payment."}]}],"name":"returnURL"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"An STPSourceParams object populated with the provided values"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"name":"See Also","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Alipay#Create-Source"}],"type":"paragraph"}],"style":"note","type":"aside"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayReusableParams(withCurrency:returnURL:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/alipayreusableparams(withcurrency:returnurl:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/alipayreusableparams(withcurrency:returnurl:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"sections":[],"abstract":[{"type":"text","text":"Creates params for a reusable Alipay source"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"url":"\/documentation\/stripepayments\/stpsourceparams","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"title":"STPSourceParams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"role":"symbol","abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/alipayReusableParams(withCurrency:returnURL:)":{"abstract":[{"type":"text","text":"Creates params for a reusable Alipay source"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"alipayReusableParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCurrency"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/alipayreusableparams(withcurrency:returnurl:)","navigatorTitle":[{"text":"alipayReusableParamsWithCurrency:returnURL:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayReusableParams(withCurrency:returnURL:)","kind":"symbol","type":"topic","title":"alipayReusableParams(withCurrency:returnURL:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"alipayReusableParamsWithCurrency:returnURL:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"alipayReusableParamsWithCurrency:returnURL:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"alipayReusableParamsWithCurrency:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"currency","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"returnURL","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":{"kind":"parameters","parameters":[{"name":"currency","content":[{"inlineContent":[{"type":"text","text":"The currency the payment is being created in."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the customer should be redirected to after they have"},{"type":"text","text":" "},{"type":"text","text":"successfully verified the payment."}]}],"name":"returnURL"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An STPSourceParams object populated with the provided values"}],"type":"paragraph"}],"kind":"content"}},{"value":"STPSourceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","op":"replace"},{"value":[{"text":"STPSourceParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1alipayReusableParams(withCurrency:returnURL:)\/title","value":"alipayReusableParamsWithCurrency:returnURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1alipayReusableParams(withCurrency:returnURL:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"alipayReusableParamsWithCurrency:returnURL:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}