{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/epsparams(withamount:name:returnurl:statementdescriptor:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/epsparams(withamount:name:returnurl:statementdescriptor:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Create params for an EPS source"}],"metadata":{"externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)epsParamsWithAmount:name:returnURL:statementDescriptor:","title":"epsParams(withAmount:name:returnURL:statementDescriptor:)","role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","extendedModule":"StripePayments","navigatorTitle":[{"kind":"identifier","text":"epsParamsWithAmount:name:returnURL:statementDescriptor:"}],"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"epsParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statementDescriptor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"epsParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAmount"},{"text":" ","kind":"text"},{"text":"amount","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"statementDescriptor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The amount to charge the customer.","type":"text"}],"type":"paragraph"}],"name":"amount"},{"name":"name","content":[{"type":"paragraph","inlineContent":[{"text":"The full name of the account holder.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the customer should be redirected to"},{"type":"text","text":" "},{"type":"text","text":"after the authorization process."}]}],"name":"returnURL"},{"content":[{"inlineContent":[{"text":"A custom statement descriptor for the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"payment (optional)."}],"type":"paragraph"}],"name":"statementDescriptor"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An STPSourceParams object populated with the provided values.","type":"text"}]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"name":"See Also","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Eps","type":"text"}]}]}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/epsParams(withAmount:name:returnURL:statementDescriptor:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams","kind":"symbol","title":"STPSourceParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/epsParams(withAmount:name:returnURL:statementDescriptor:)":{"title":"epsParams(withAmount:name:returnURL:statementDescriptor:)","kind":"symbol","role":"symbol","abstract":[{"text":"Create params for an EPS source","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/epsparams(withamount:name:returnurl:statementdescriptor:)","navigatorTitle":[{"text":"epsParamsWithAmount:name:returnURL:statementDescriptor:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/epsParams(withAmount:name:returnURL:statementDescriptor:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"epsParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"statementDescriptor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"epsParamsWithAmount:name:returnURL:statementDescriptor:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"epsParamsWithAmount:name:returnURL:statementDescriptor:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"},{"text":" *) ","kind":"text"},{"text":"epsParamsWithAmount:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"amount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"returnURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"statementDescriptor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"statementDescriptor"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"amount","content":[{"inlineContent":[{"type":"text","text":"The amount to charge the customer."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The full name of the account holder.","type":"text"}]}],"name":"name"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the customer should be redirected to"},{"type":"text","text":" "},{"text":"after the authorization process.","type":"text"}]}],"name":"returnURL"},{"name":"statementDescriptor","content":[{"inlineContent":[{"text":"A custom statement descriptor for the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"payment (optional)."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An STPSourceParams object populated with the provided values."}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1epsParams(withAmount:name:returnURL:statementDescriptor:)\/title","value":"epsParamsWithAmount:name:returnURL:statementDescriptor:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1epsParams(withAmount:name:returnURL:statementDescriptor:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"epsParamsWithAmount:name:returnURL:statementDescriptor:","kind":"identifier"}]}]}]}
