{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/flow","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flow"},{"text":": ","kind":"text"},{"text":"STPSourceFlow","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow","kind":"typeIdentifier"}],"title":"flow","navigatorTitle":[{"text":"flow","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceParams(py)flow"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"flow","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPSourceFlow","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The authentication flow of the source to create. "},{"code":"flow","type":"codeVoice"},{"type":"text","text":" may be “redirect”,"},{"text":" ","type":"text"},{"text":"“receiver”, “verification”, or “none”. It is generally inferred unless a type","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"supports multiple flows."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/flow"]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/flow"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams","role":"symbol","title":"STPSourceParams","type":"topic","abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"url":"\/documentation\/stripepayments\/stpsourceflow","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPSourceFlow","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceFlow","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Authentication flows for a Source","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","title":"STPSourceFlow"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/flow":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"flow"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/flow","abstract":[{"type":"text","text":"The authentication flow of the source to create. "},{"code":"flow","type":"codeVoice"},{"type":"text","text":" may be “redirect”,"},{"text":" ","type":"text"},{"text":"“receiver”, “verification”, or “none”. It is generally inferred unless a type","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"supports multiple flows."}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"flow"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceFlow","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/flow","title":"flow"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"flow"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"flow","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow","text":"STPSourceFlow","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"flow","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"STPSourceParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"text":"STPSourceParams","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle"},{"value":"STPSourceFlow","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments","value":[{"text":"STPSourceFlow","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceFlow"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1flow\/title","op":"replace","value":"flow"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1flow\/fragments","value":[{"text":"flow","kind":"identifier"}]}]}]}