{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/idealParams(withAmount:name:returnURL:statementDescriptor:bank:)"},"metadata":{"externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)idealParamsWithAmount:name:returnURL:statementDescriptor:bank:","role":"symbol","extendedModule":"StripePayments","navigatorTitle":[{"kind":"identifier","text":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","symbolKind":"method","title":"idealParams(withAmount:name:returnURL:statementDescriptor:bank:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idealParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAmount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"statementDescriptor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"bank"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}]},"sections":[],"abstract":[{"type":"text","text":"Creates params for an iDEAL source."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"idealParams","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAmount","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"amount","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"statementDescriptor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bank"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"amount","content":[{"type":"paragraph","inlineContent":[{"text":"The amount to charge the customer in EUR.","type":"text"}]}]},{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) The full name of the account holder."}]}]},{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL the customer should be redirected to after","type":"text"},{"type":"text","text":" "},{"type":"text","text":"they have successfully verified the payment."}]}]},{"name":"statementDescriptor","content":[{"inlineContent":[{"type":"text","text":"(Optional) A custom statement descriptor for t"},{"type":"text","text":" "},{"type":"text","text":"he payment."}],"type":"paragraph"}]},{"name":"bank","content":[{"inlineContent":[{"text":"(Optional) The customer’s bank.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Ideal#Create-Source"}]}],"style":"note","name":"See Also","type":"aside"},{"style":"note","content":[{"inlineContent":[{"text":"The currency for iDEAL must be “eur”. This will be set automatically","type":"text"},{"text":" ","type":"text"},{"text":"for you.","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns: an STPSourceParams object populated with the provided values."}]}]}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/idealparams(withamount:name:returnurl:statementdescriptor:bank:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/idealparams(withamount:name:returnurl:statementdescriptor:bank:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/idealParams(withAmount:name:returnURL:statementDescriptor:bank:)":{"url":"\/documentation\/stripepayments\/stpsourceparams\/idealparams(withamount:name:returnurl:statementdescriptor:bank:)","abstract":[{"text":"Creates params for an iDEAL source.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/idealParams(withAmount:name:returnURL:statementDescriptor:bank:)","title":"idealParams(withAmount:name:returnURL:statementDescriptor:bank:)","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idealParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"statementDescriptor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"bank","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"}],"navigatorTitle":[{"kind":"identifier","text":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams","role":"symbol","title":"STPSourceParams","type":"topic","abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},{"text":" *) ","kind":"text"},{"text":"idealParamsWithAmount:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"amount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"returnURL:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"returnURL","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"statementDescriptor:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"statementDescriptor","kind":"internalParam"},{"kind":"text","text":" "},{"text":"bank:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bank"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"amount","content":[{"inlineContent":[{"text":"The amount to charge the customer in EUR.","type":"text"}],"type":"paragraph"}]},{"name":"name","content":[{"inlineContent":[{"type":"text","text":"(Optional) The full name of the account holder."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The URL the customer should be redirected to after","type":"text"},{"type":"text","text":" "},{"type":"text","text":"they have successfully verified the payment."}],"type":"paragraph"}],"name":"returnURL"},{"content":[{"inlineContent":[{"type":"text","text":"(Optional) A custom statement descriptor for t"},{"type":"text","text":" "},{"type":"text","text":"he payment."}],"type":"paragraph"}],"name":"statementDescriptor"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) The customer’s bank."}]}],"name":"bank"}]},"op":"replace"},{"op":"replace","value":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1idealParams(withAmount:name:returnURL:statementDescriptor:bank:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1idealParams(withAmount:name:returnURL:statementDescriptor:bank:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","op":"replace","value":"STPSourceParams"},{"op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}