{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)"},"metadata":{"extendedModule":"StripePayments","externalID":"s:14StripePayments15STPSourceParamsC06klarnaD013withReturnURL8currency15purchaseCountry5items20customPaymentMethodsACSS_S2SSayAA17STPKlarnaLineItemCGSayAA0pnO0OGtFZ","modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"klarnaParams","kind":"identifier"},{"kind":"text","text":"("},{"text":"withReturnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"purchaseCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"text":": [","kind":"text"},{"text":"STPKlarnaLineItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"text":"], ","kind":"text"},{"text":"customPaymentMethods","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"STPKlarnaPaymentMethods","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaPaymentMethods"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"title":"klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","symbolKind":"method"},"abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"klarnaParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withReturnURL"},{"kind":"text","text":" "},{"text":"returnURL","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"purchaseCountry"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"items"},{"text":": [","kind":"text"},{"text":"STPKlarnaLineItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"customPaymentMethods"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaPaymentMethods","text":"STPKlarnaPaymentMethods","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}]}]},{"parameters":[{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL the customer should be redirected to after","type":"text"},{"type":"text","text":" "},{"type":"text","text":"they have successfully verified the payment."}]}]},{"name":"currency","content":[{"inlineContent":[{"type":"text","text":"The currency the payment is being created in."}],"type":"paragraph"}]},{"name":"purchaseCountry","content":[{"inlineContent":[{"text":"The ISO-3166 2-letter country code of the customer’s location.","type":"text"}],"type":"paragraph"}]},{"name":"items","content":[{"inlineContent":[{"type":"text","text":"An array of STPKlarnaLineItems. Klarna will present these in the confirmation"},{"type":"text","text":" "},{"text":"dialog. The total amount charged will be a sum of the ","type":"text"},{"type":"codeVoice","code":"totalAmount"},{"type":"text","text":" of each of these items."}],"type":"paragraph"}]},{"name":"customPaymentMethods","content":[{"inlineContent":[{"type":"text","text":"Required for customers located in the US. This determines whether Pay Later and\/or Slice It"},{"type":"text","text":" "},{"text":"is offered to a US customer.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"An STPSourceParams object populated with the provided values.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Klarna#Create-Source"}],"type":"paragraph"}],"style":"note","name":"See Also","type":"aside"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","url":"\/documentation\/stripepayments\/stpsourceparams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceParams"}],"kind":"symbol","title":"STPSourceParams","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"url":"\/documentation\/stripepayments\/stpklarnalineitem","title":"STPKlarnaLineItem","type":"topic","abstract":[{"text":"An object representing a line item in a Klarna source.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPKlarnaLineItem","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","navigatorTitle":[{"text":"STPKlarnaLineItem","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods","kind":"symbol","title":"STPKlarnaPaymentMethods","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"abstract":[{"text":"Custom payment methods for Klarna","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"klarnaParams","kind":"identifier"},{"kind":"text","text":"("},{"text":"withReturnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currency"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purchaseCountry"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"items","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem","text":"STPKlarnaLineItem"},{"text":"], ","kind":"text"},{"text":"customPaymentMethods","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"STPKlarnaPaymentMethods","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaPaymentMethods"},{"text":"]) -> ","kind":"text"},{"text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"title":"klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams\/klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title","value":"STPKlarnaLineItem"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments","value":[{"text":"STPKlarnaLineItem","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/navigatorTitle"},{"value":"STPKlarnaPaymentMethods","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments","value":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}]}]}]}