{"abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:billingaddress:billingfirstname:billinglastname:billingdob:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"s:14StripePayments15STPSourceParamsC06klarnaD013withReturnURL8currency15purchaseCountry5items20customPaymentMethods14billingAddress0P9FirstName0p4LastS00P3DOBACSS_S2SSayAA17STPKlarnaLineItemCGSayAA0vnO0OGAA10STPAddressCSgSSSgAwA14STPDateOfBirthCSgtFZ","title":"klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","extendedModule":"StripePayments","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"klarnaParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withReturnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"purchaseCountry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"text":"STPKlarnaLineItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"kind":"text","text":"], "},{"text":"customPaymentMethods","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"STPKlarnaPaymentMethods","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaPaymentMethods","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"billingAddress","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?, "},{"text":"billingFirstName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingLastName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"billingDOB","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPDateOfBirth","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth"},{"text":"?) -> ","kind":"text"},{"text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier"}],"roleHeading":"Type Method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"klarnaParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withReturnURL","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purchaseCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"items","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","text":"STPKlarnaLineItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"customPaymentMethods"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaPaymentMethods","text":"STPKlarnaPaymentMethods","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"billingAddress","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"address"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"? = nil, ","kind":"text"},{"text":"billingFirstName","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"firstName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"billingLastName","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"billingDOB","kind":"externalParam"},{"kind":"text","text":" "},{"text":"dateOfBirth","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth","kind":"typeIdentifier","text":"STPDateOfBirth","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth"},{"kind":"text","text":"? = nil) -> "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The URL the customer should be redirected to after","type":"text"},{"type":"text","text":" "},{"type":"text","text":"they have successfully verified the payment."}],"type":"paragraph"}],"name":"returnURL"},{"name":"currency","content":[{"inlineContent":[{"type":"text","text":"The currency the payment is being created in."}],"type":"paragraph"}]},{"name":"purchaseCountry","content":[{"inlineContent":[{"type":"text","text":"The ISO-3166 2-letter country code of the customer’s location."}],"type":"paragraph"}]},{"name":"items","content":[{"inlineContent":[{"type":"text","text":"An array of STPKlarnaLineItems. Klarna will present these on the confirmation"},{"text":" ","type":"text"},{"text":"page. The total amount charged will be a sum of the ","type":"text"},{"type":"codeVoice","code":"totalAmount"},{"type":"text","text":" of each of these items."}],"type":"paragraph"}]},{"name":"customPaymentMethods","content":[{"inlineContent":[{"text":"Required for customers located in the US. This determines whether Pay Later and\/or Slice It","type":"text"},{"text":" ","type":"text"},{"text":"is offered to a US customer.","type":"text"}],"type":"paragraph"}]},{"name":"address","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An STPAddress for the customer. At a minimum, an "},{"code":"email","type":"codeVoice"},{"text":", ","type":"text"},{"code":"line1","type":"codeVoice"},{"text":", ","type":"text"},{"code":"postalCode","type":"codeVoice"},{"type":"text","text":", "},{"code":"city","type":"codeVoice"},{"type":"text","text":", and "},{"code":"country","type":"codeVoice"},{"text":" must be provided.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The address’ "},{"code":"name","type":"codeVoice"},{"text":" will be ignored in favor of the ","type":"text"},{"code":"firstName and ","type":"codeVoice"},{"type":"text","text":"lastName` parameters."}]}]},{"name":"firstName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The customer’s first name."}]}]},{"content":[{"inlineContent":[{"text":"The customer’s last name.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the provided information is missing a line1, postal code, city, email, or first\/last name, or if the country code is"},{"text":" ","type":"text"},{"text":"outside the specified country, no address information will be sent to Klarna, and Klarna will prompt the customer to provide their address.","type":"text"}],"type":"paragraph"}],"name":"lastName"},{"content":[{"inlineContent":[{"text":"The customer’s date of birth. This will be used by Klarna for a credit check in some EU countries.","type":"text"},{"type":"text","text":" "},{"text":"The optional fields (address, firstName, lastName, and dateOfBirth) can be provided to skip Klarna’s customer information form.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If this information is missing, Klarna will prompt the customer for these values during checkout."},{"type":"text","text":" "},{"text":"Be careful with this option: If the provided information is invalid,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Klarna may reject the transaction without giving the customer a chance to correct it."}],"type":"paragraph"}],"name":"dateOfBirth"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"An STPSourceParams object populated with the provided values."}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"name":"See Also","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Klarna#Create-Source","type":"text"}]}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"title":"STPKlarnaPaymentMethods","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"url":"\/documentation\/stripepayments\/stpklarnapaymentmethods","abstract":[{"text":"Custom payment methods for Klarna","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)":{"title":"klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"klarnaParams"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withReturnURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"purchaseCountry","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem","text":"STPKlarnaLineItem"},{"text":"], ","kind":"text"},{"text":"customPaymentMethods","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"STPKlarnaPaymentMethods","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaPaymentMethods"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"billingAddress"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","text":"STPAddress"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"billingFirstName"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"billingLastName","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingDOB"},{"text":": ","kind":"text"},{"text":"STPDateOfBirth","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","url":"\/documentation\/stripepayments\/stpsourceparams\/klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:billingaddress:billingfirstname:billinglastname:billingdob:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"url":"\/documentation\/stripepayments\/stpsourceparams","abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"}],"kind":"symbol","type":"topic","title":"STPSourceParams","role":"symbol","navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"type":"topic","role":"symbol","title":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","url":"\/documentation\/stripepayments\/stpaddress","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"title":"STPKlarnaLineItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPKlarnaLineItem"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","url":"\/documentation\/stripepayments\/stpklarnalineitem","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object representing a line item in a Klarna source."}],"navigatorTitle":[{"text":"STPKlarnaLineItem","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth":{"abstract":[{"type":"text","text":"An individual’s date of birth."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/stripe.com\/docs\/api\/tokens\/create_account#create_account_token-account-individual-dob"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPDateOfBirth","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpdateofbirth","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth","navigatorTitle":[{"kind":"identifier","text":"STPDateOfBirth"}],"title":"STPDateOfBirth"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title","value":"STPKlarnaPaymentMethods"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments","op":"replace","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","value":"STPAddress"},{"value":[{"text":"STPAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPAddress"}]},{"op":"replace","value":"STPKlarnaLineItem","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title"},{"value":[{"text":"STPKlarnaLineItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/navigatorTitle","value":[{"kind":"identifier","text":"STPKlarnaLineItem"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/title","op":"replace","value":"STPDateOfBirth"},{"value":[{"text":"STPDateOfBirth","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/fragments","op":"replace"},{"value":[{"text":"STPDateOfBirth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}