{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/masterpassparams(withcartid:transactionid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/masterpassparams(withcartid:transactionid:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/masterpassParams(withCartId:transactionId:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Type Method","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)masterpassParamsWithCartId:transactionId:","modules":[{"name":"StripePayments"}],"symbolKind":"method","extendedModule":"StripePayments","navigatorTitle":[{"kind":"identifier","text":"masterpassParamsWithCartId:transactionId:"}],"role":"symbol","title":"masterpassParams(withCartId:transactionId:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"masterpassParams"},{"kind":"text","text":"("},{"text":"withCartId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transactionId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"masterpassParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCartId"},{"text":" ","kind":"text"},{"text":"cartId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"transactionId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Masterpass"}]}],"type":"aside","style":"note","name":"See Also"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Creating an STPSource with these params will give you a"},{"type":"text","text":" "},{"type":"text","text":"source with type == STPSourceTypeCard"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"Parameters:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"cartId: The cartId from a "},{"type":"codeVoice","code":"MCCCheckoutResponse"},{"type":"text","text":" object."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"transactionId: The transactionid from a ","type":"text"},{"code":"MCCCheckoutResponse","type":"codeVoice"},{"type":"text","text":" object."}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"text","text":"Returns: An STPSourceParams object populated with the provided values."}],"type":"paragraph"}]}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Creates params for a card source created from Masterpass."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/masterpassParams(withCartId:transactionId:)":{"abstract":[{"text":"Creates params for a card source created from Masterpass.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/masterpassParams(withCartId:transactionId:)","url":"\/documentation\/stripepayments\/stpsourceparams\/masterpassparams(withcartid:transactionid:)","navigatorTitle":[{"text":"masterpassParamsWithCartId:transactionId:","kind":"identifier"}],"role":"symbol","title":"masterpassParams(withCartId:transactionId:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"masterpassParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCartId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"transactionId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"title":"STPSourceParams","url":"\/documentation\/stripepayments\/stpsourceparams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"masterpassParamsWithCartId:transactionId:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"masterpassParamsWithCartId:transactionId:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"kind":"text","text":" *) "},{"text":"masterpassParamsWithCartId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cartId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transactionId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"transactionId"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1masterpassParams(withCartId:transactionId:)\/title","value":"masterpassParamsWithCartId:transactionId:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1masterpassParams(withCartId:transactionId:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"masterpassParamsWithCartId:transactionId:","kind":"identifier"}],"op":"replace"},{"value":"STPSourceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"text":"STPSourceParams","kind":"identifier"}]}]}]}