{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"objc_klarnaParams"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withReturnURL"},{"kind":"text","text":" "},{"kind":"internalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purchaseCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem","text":"STPKlarnaLineItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"customPaymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"billingAddress"},{"kind":"text","text":" "},{"kind":"internalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingFirstName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"firstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingLastName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingDOB"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth","text":"STPDateOfBirth"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the customer should be redirected to after"},{"type":"text","text":" "},{"type":"text","text":"they have successfully verified the payment."}]}]},{"name":"currency","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The currency the payment is being created in."}]}]},{"name":"purchaseCountry","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ISO-3166 2-letter country code of the customer’s location."}]}]},{"name":"items","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of STPKlarnaLineItems. Klarna will present these on the confirmation"},{"type":"text","text":" "},{"type":"text","text":"page. The total amount charged will be a sum of the "},{"type":"codeVoice","code":"totalAmount"},{"type":"text","text":" of each of these items."}]}]},{"name":"customPaymentMethods","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required for customers located in the US. This determines whether Pay Later and\/or Slice It"},{"type":"text","text":" "},{"type":"text","text":"is offered to a US customer."}]}]},{"name":"address","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An STPAddress for the customer. At a minimum, an "},{"type":"codeVoice","code":"email"},{"type":"text","text":", "},{"type":"codeVoice","code":"line1"},{"type":"text","text":", "},{"type":"codeVoice","code":"postalCode"},{"type":"text","text":", "},{"type":"codeVoice","code":"city"},{"type":"text","text":", and "},{"type":"codeVoice","code":"country"},{"type":"text","text":" must be provided."},{"type":"text","text":" "},{"type":"text","text":"The address’ "},{"type":"codeVoice","code":"name"},{"type":"text","text":" will be ignored in favor of the "},{"type":"codeVoice","code":"firstName and "},{"type":"text","text":"lastName` parameters."}]}]},{"name":"firstName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The customer’s first name."}]}]},{"name":"lastName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The customer’s last name."},{"type":"text","text":" "},{"type":"text","text":"If the provided information is missing a line1, postal code, city, email, or first\/last name, or if the country code is"},{"type":"text","text":" "},{"type":"text","text":"outside the specified country, no address information will be sent to Klarna, and Klarna will prompt the customer to provide their address."}]}]},{"name":"dateOfBirth","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The customer’s date of birth. This will be used by Klarna for a credit check in some EU countries."},{"type":"text","text":" "},{"type":"text","text":"The optional fields (address, firstName, lastName, and dateOfBirth) can be provided to skip Klarna’s customer information form."},{"type":"text","text":" "},{"type":"text","text":"If this information is missing, Klarna will prompt the customer for these values during checkout."},{"type":"text","text":" "},{"type":"text","text":"Be careful with this option: If the provided information is invalid,"},{"type":"text","text":" "},{"type":"text","text":"Klarna may reject the transaction without giving the customer a chance to correct it."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"an STPSourceParams object populated with the provided values."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"https:\/\/stripe.com\/docs\/sources\/klarna#create-source"}]}],"type":"aside","name":"See Also"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceparams\/objc_klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:billingaddress:billingfirstname:billinglastname:billingdob:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/objc_klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:billingaddress:billingfirstname:billinglastname:billingdob:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:"}],"role":"symbol","title":"objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"objc_klarnaParams"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withReturnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purchaseCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"STPKlarnaLineItem","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"customPaymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"billingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingFirstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingLastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingDOB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPDateOfBirth","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"symbolKind":"method","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:","modules":[{"name":"StripePayments"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"role":"symbol","title":"STPSourceParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)":{"role":"symbol","title":"objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"objc_klarnaParams"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withReturnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purchaseCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"STPKlarnaLineItem","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"customPaymentMethods"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"billingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingFirstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingLastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingDOB"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPDateOfBirth","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/objc_klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:billingaddress:billingfirstname:billinglastname:billingdob:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"role":"symbol","title":"STPAddress","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAddress"}],"url":"\/documentation\/stripepayments\/stpaddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPDateOfBirth":{"role":"symbol","title":"STPDateOfBirth","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPDateOfBirth"}],"abstract":[{"type":"text","text":"An individual’s date of birth."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/stripe.com\/docs\/api\/tokens\/create_account#create_account_token-account-individual-dob"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPDateOfBirth"}],"url":"\/documentation\/stripepayments\/stpdateofbirth"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"role":"symbol","title":"STPKlarnaLineItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPKlarnaLineItem"}],"abstract":[{"type":"text","text":"An object representing a line item in a Klarna source."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"url":"\/documentation\/stripepayments\/stpklarnalineitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"klarnaParamsWithReturnURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"returnURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"currency"},{"kind":"text","text":" "},{"kind":"identifier","text":"purchaseCountry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"purchaseCountry"},{"kind":"text","text":" "},{"kind":"identifier","text":"items:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<STPKlarnaLineItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"items"},{"kind":"text","text":" "},{"kind":"identifier","text":"customPaymentMethods:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"customPaymentMethods"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingAddress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"address"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingFirstName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"firstName"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingLastName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lastName"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingDOB:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPDateOfBirth","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth","text":"STPDateOfBirth"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dateOfBirth"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)\/title","value":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","value":"STPAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","value":[{"kind":"identifier","text":"STPAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/title","value":"STPDateOfBirth"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPDateOfBirth\/fragments","value":[{"kind":"identifier","text":"STPDateOfBirth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title","value":"STPKlarnaLineItem"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments","value":[{"kind":"identifier","text":"STPKlarnaLineItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
