{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"objc_klarnaParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withReturnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"purchaseCountry","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem","text":"STPKlarnaLineItem"},{"text":"], ","kind":"text"},{"text":"customPaymentMethods","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"role":"symbol","extendedModule":"StripePayments","navigatorTitle":[{"text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:","kind":"identifier"}],"title":"objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:","symbolKind":"method","platforms":[],"roleHeading":"Type Method"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceparams\/objc_klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/objc_klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:)"]}],"abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"objc_klarnaParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withReturnURL"},{"kind":"text","text":" "},{"text":"returnURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"purchaseCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"items","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","text":"STPKlarnaLineItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"customPaymentMethods"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL the customer should be redirected to after"},{"text":" ","type":"text"},{"text":"they have successfully verified the payment.","type":"text"}]}],"name":"returnURL"},{"name":"currency","content":[{"type":"paragraph","inlineContent":[{"text":"The currency the payment is being created in.","type":"text"}]}]},{"name":"purchaseCountry","content":[{"inlineContent":[{"type":"text","text":"The ISO-3166 2-letter country code of the customer’s location."}],"type":"paragraph"}]},{"name":"items","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of STPKlarnaLineItems. Klarna will present these in the confirmation"},{"type":"text","text":" "},{"type":"text","text":"dialog. The total amount charged will be a sum of the "},{"type":"codeVoice","code":"totalAmount"},{"text":" of each of these items.","type":"text"}]}]},{"name":"customPaymentMethods","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required for customers located in the US. This determines whether Pay Later and\/or Slice It"},{"type":"text","text":" "},{"text":"is offered to a US customer.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"An STPSourceParams object populated with the provided values.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Klarna#Create-Source"}]}],"style":"note","name":"See Also"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)":{"url":"\/documentation\/stripepayments\/stpsourceparams\/objc_klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"objc_klarnaParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withReturnURL"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"purchaseCountry","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"items","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"STPKlarnaLineItem","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"customPaymentMethods"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"]) -> ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"role":"symbol","navigatorTitle":[{"text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:","kind":"identifier"}],"title":"objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","abstract":[{"text":"Creates params for a Klarna source.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"title":"STPKlarnaLineItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPKlarnaLineItem"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","url":"\/documentation\/stripepayments\/stpklarnalineitem","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object representing a line item in a Klarna source."}],"navigatorTitle":[{"text":"STPKlarnaLineItem","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"url":"\/documentation\/stripepayments\/stpsourceparams","abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"}],"kind":"symbol","type":"topic","title":"STPSourceParams","role":"symbol","navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"kind":"text","text":" *) "},{"text":"klarnaParamsWithReturnURL:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"returnURL"},{"text":" ","kind":"text"},{"text":"currency:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"currency"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purchaseCountry:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"purchaseCountry"},{"kind":"text","text":" "},{"kind":"identifier","text":"items:"},{"kind":"text","text":"("},{"text":"NSArray<STPKlarnaLineItem *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"items"},{"text":" ","kind":"text"},{"text":"customPaymentMethods:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSNumber *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"customPaymentMethods","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL the customer should be redirected to after","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"they have successfully verified the payment."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The currency the payment is being created in."}]}],"name":"currency"},{"name":"purchaseCountry","content":[{"inlineContent":[{"type":"text","text":"The ISO-3166 2-letter country code of the customer’s location."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of STPKlarnaLineItems. Klarna will present these in the confirmation"},{"type":"text","text":" "},{"text":"dialog. The total amount charged will be a sum of the ","type":"text"},{"type":"codeVoice","code":"totalAmount"},{"type":"text","text":" of each of these items."}]}],"name":"items"},{"name":"customPaymentMethods","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Required for customers located in the US. This determines whether Pay Later and\/or Slice It"},{"type":"text","text":" "},{"type":"text","text":"is offered to a US customer."}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An STPSourceParams object populated with the provided values.","type":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)\/title","op":"replace","value":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title","value":"STPKlarnaLineItem","op":"replace"},{"value":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/navigatorTitle","value":[{"kind":"identifier","text":"STPKlarnaLineItem"}]},{"value":"STPSourceParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}