{"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"method","navigatorTitle":[{"text":"p24ParamsWithAmount:currency:email:name:returnURL:","kind":"identifier"}],"extendedModule":"StripePayments","roleHeading":"Type Method","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)p24ParamsWithAmount:currency:email:name:returnURL:","title":"p24Params(withAmount:currency:email:name:returnURL:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"p24Params"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/p24Params(withAmount:currency:email:name:returnURL:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Creates params for a P24 source"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/p24params(withamount:currency:email:name:returnurl:)"]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/p24params(withamount:currency:email:name:returnurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"p24Params","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAmount"},{"text":" ","kind":"text"},{"text":"amount","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"email"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"returnURL"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The amount to charge the customer.","type":"text"}]}],"name":"amount"},{"name":"currency","content":[{"inlineContent":[{"text":"The currency the payment is being created in (this must be","type":"text"},{"type":"text","text":" "},{"type":"text","text":"EUR or PLN)"}],"type":"paragraph"}]},{"name":"email","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The email address of the account holder."}]}]},{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The full name of the account holder (optional)."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The URL the customer should be redirected to after they have"}],"type":"paragraph"}],"name":"returnURL"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"An STPSourceParams object populated with the provided values.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"aside","name":"See Also","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"https:\/\/stripe.com\/docs\/sources\/p24#create-source","type":"text"}]}]}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"url":"\/documentation\/stripepayments\/stpsourceparams","abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"}],"kind":"symbol","type":"topic","title":"STPSourceParams","role":"symbol","navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/p24Params(withAmount:currency:email:name:returnURL:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/p24Params(withAmount:currency:email:name:returnURL:)","url":"\/documentation\/stripepayments\/stpsourceparams\/p24params(withamount:currency:email:name:returnurl:)","title":"p24Params(withAmount:currency:email:name:returnURL:)","abstract":[{"type":"text","text":"Creates params for a P24 source"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"p24Params","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAmount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"email"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"p24ParamsWithAmount:currency:email:name:returnURL:","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"p24ParamsWithAmount:currency:email:name:returnURL:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"p24ParamsWithAmount:currency:email:name:returnURL:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"p24ParamsWithAmount:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"amount"},{"kind":"text","text":" "},{"text":"currency:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"currency","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"email:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"email","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"kind":"text","text":" "},{"text":"returnURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"returnURL","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"The amount to charge the customer.","type":"text"}],"type":"paragraph"}],"name":"amount"},{"content":[{"inlineContent":[{"type":"text","text":"The currency the payment is being created in (this must be"},{"type":"text","text":" "},{"type":"text","text":"EUR or PLN)"}],"type":"paragraph"}],"name":"currency"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The email address of the account holder."}]}],"name":"email"},{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The full name of the account holder (optional)."}]}]},{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL the customer should be redirected to after they have","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"An STPSourceParams object populated with the provided values.","type":"text"}]}]}},{"op":"replace","value":"STPSourceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1p24Params(withAmount:currency:email:name:returnURL:)\/title","value":"p24ParamsWithAmount:currency:email:name:returnURL:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1p24Params(withAmount:currency:email:name:returnURL:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"p24ParamsWithAmount:currency:email:name:returnURL:","kind":"identifier"}],"op":"replace"}]}]}