{"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawTypeString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The raw underlying type string sent to the server."},{"type":"text","text":" "},{"type":"text","text":"Generally you should use "},{"type":"codeVoice","code":"type"},{"type":"text","text":" instead unless you have a reason not to."},{"type":"text","text":" "},{"type":"text","text":"You can use this if you want to create a param of a type not yet supported"},{"type":"text","text":" "},{"type":"text","text":"by the current version of the SDK’s "},{"type":"codeVoice","code":"STPSourceType"},{"type":"text","text":" enum."},{"type":"text","text":" "},{"type":"text","text":"Setting this to a value not known by the SDK causes "},{"type":"codeVoice","code":"type"},{"type":"text","text":" to"},{"type":"text","text":" "},{"type":"text","text":"return "},{"type":"codeVoice","code":"STPSourceTypeUnknown"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/rawtypestring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/rawtypestring"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/rawTypeString"},"metadata":{"symbolKind":"property","modules":[{"name":"StripePayments"}],"title":"rawTypeString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawTypeString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"rawTypeString"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPSourceParams(py)rawTypeString"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"kind":"symbol","abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"role":"symbol","title":"STPSourceParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/rawTypeString":{"url":"\/documentation\/stripepayments\/stpsourceparams\/rawtypestring","kind":"symbol","title":"rawTypeString","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawTypeString","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The raw underlying type string sent to the server."},{"type":"text","text":" "},{"type":"text","text":"Generally you should use "},{"type":"codeVoice","code":"type"},{"type":"text","text":" instead unless you have a reason not to."},{"type":"text","text":" "},{"type":"text","text":"You can use this if you want to create a param of a type not yet supported"},{"type":"text","text":" "},{"type":"text","text":"by the current version of the SDK’s "},{"type":"codeVoice","code":"STPSourceType"},{"type":"text","text":" enum."},{"type":"text","text":" "},{"type":"text","text":"Setting this to a value not known by the SDK causes "},{"type":"codeVoice","code":"type"},{"type":"text","text":" to"},{"type":"text","text":" "},{"type":"text","text":"return "},{"type":"codeVoice","code":"STPSourceTypeUnknown"}],"navigatorTitle":[{"text":"rawTypeString","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/rawTypeString"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"rawTypeString","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rawTypeString"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"rawTypeString","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1rawTypeString\/title","value":"rawTypeString","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1rawTypeString\/fragments","value":[{"kind":"identifier","text":"rawTypeString"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}