{"kind":"symbol","abstract":[{"type":"text","text":"Parameters required for the redirect flow. Required if the source is"},{"text":" ","type":"text"},{"text":"authenticated by a redirect (","type":"text"},{"type":"codeVoice","code":"flow"},{"type":"text","text":" is “redirect”)."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/redirect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/redirect"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirect"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirect"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceParams(py)redirect","navigatorTitle":[{"text":"redirect","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"redirect","symbolKind":"property","role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirect","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/redirect":{"url":"\/documentation\/stripepayments\/stpsourceparams\/redirect","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirect"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Parameters required for the redirect flow. Required if the source is"},{"type":"text","text":" "},{"type":"text","text":"authenticated by a redirect ("},{"type":"codeVoice","code":"flow"},{"text":" is “redirect”).","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirect","navigatorTitle":[{"text":"redirect","kind":"identifier"}],"title":"redirect"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"url":"\/documentation\/stripepayments\/stpsourceparams","abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"}],"title":"STPSourceParams","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"redirect","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"redirect"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"redirect"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1redirect\/title","op":"replace","value":"redirect"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1redirect\/fragments","value":[{"kind":"identifier","text":"redirect"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceParams"}]}]}]}