{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/sepadebitparams(withname:iban:addressline1:city:postalcode:country:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/sepadebitparams(withname:iban:addressline1:city:postalcode:country:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Creates params for a SEPA Debit source.","type":"text"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:"}],"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sepaDebitParams"},{"kind":"text","text":"("},{"text":"withName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"iban","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addressLine1"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"city"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"postalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"country","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:","title":"sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)","extendedModule":"StripePayments","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sepaDebitParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withName"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"iban"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addressLine1"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"city","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"postalCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"country"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) -> "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The full name of the account holder."}],"type":"paragraph"}],"name":"name"},{"content":[{"inlineContent":[{"text":"The IBAN number for the bank account you wish to debit.","type":"text"}],"type":"paragraph"}],"name":"iban"},{"name":"addressLine1","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) The bank account holder’s first address line."}]}]},{"name":"city","content":[{"inlineContent":[{"type":"text","text":"(Optional) The bank account holder’s city."}],"type":"paragraph"}]},{"name":"postalCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) The bank account holder’s postal code."}]}]},{"name":"country","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) The bank account holder’s two-letter"},{"text":" ","type":"text"},{"text":"country code.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Sepa-Debit#Create-Source","type":"text"}]}],"type":"aside","style":"note","name":"See Also"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The currency for SEPA Debit must be “eur”. This will be set automatically"},{"type":"text","text":" "},{"text":"for you.","type":"text"}]},{"items":[{"content":[{"inlineContent":[{"type":"text","text":"Returns: an STPSourceParams object populated with the provided values."}],"type":"paragraph"}]}],"type":"unorderedList"}],"name":"Note","type":"aside"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"title":"STPSourceParams","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sepaDebitParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"iban","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"addressLine1","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"city"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"postalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/sepadebitparams(withname:iban:addressline1:city:postalcode:country:)","title":"sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)","role":"symbol","abstract":[{"text":"Creates params for a SEPA Debit source.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"sepaDebitParamsWithName:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"iban:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"iban"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addressLine1:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"addressLine1","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"city:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"city"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalCode:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"postalCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"country:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"country"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The full name of the account holder."}]}],"name":"name"},{"content":[{"inlineContent":[{"text":"The IBAN number for the bank account you wish to debit.","type":"text"}],"type":"paragraph"}],"name":"iban"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) The bank account holder’s first address line."}]}],"name":"addressLine1"},{"name":"city","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) The bank account holder’s city."}]}]},{"name":"postalCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) The bank account holder’s postal code."}]}]},{"name":"country","content":[{"type":"paragraph","inlineContent":[{"text":"(Optional) The bank account holder’s two-letter","type":"text"},{"text":" ","type":"text"},{"text":"country code.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"STPSourceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)\/title","value":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:"},{"value":[{"text":"+ ","kind":"text"},{"text":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}