{"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceparams\/sofortparams(withamount:returnurl:country:statementdescriptor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/sofortparams(withamount:returnurl:country:statementdescriptor:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sofortParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"country","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"statementDescriptor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"navigatorTitle":[{"kind":"identifier","text":"sofortParamsWithAmount:returnURL:country:statementDescriptor:"}],"title":"sofortParams(withAmount:returnURL:country:statementDescriptor:)","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)sofortParamsWithAmount:returnURL:country:statementDescriptor:","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","extendedModule":"StripePayments"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sofortParams(withAmount:returnURL:country:statementDescriptor:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sofortParams","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"amount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"country"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"statementDescriptor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The amount to charge the customer in EUR.","type":"text"}]}],"name":"amount"},{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL the customer should be redirected to after","type":"text"},{"type":"text","text":" "},{"type":"text","text":"they have successfully verified the payment."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The country code of the customer’s bank.","type":"text"}]}],"name":"country"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"(Optional) A custom statement descriptor for"},{"type":"text","text":" "},{"text":"the payment.","type":"text"}]}],"name":"statementDescriptor"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"name":"See Also","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Sofort#Create-Source","type":"text"}]}],"style":"note"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"text":"The currency for Sofort must be “eur”. This will be set automatically","type":"text"},{"type":"text","text":" "},{"text":"for you.","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Returns: an STPSourceParams object populated with the provided values.","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}]}],"abstract":[{"text":"Creates params for a Sofort source.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/sofortParams(withAmount:returnURL:country:statementDescriptor:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams\/sofortparams(withamount:returnurl:country:statementdescriptor:)","type":"topic","abstract":[{"text":"Creates params for a Sofort source.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sofortParams(withAmount:returnURL:country:statementDescriptor:)","role":"symbol","title":"sofortParams(withAmount:returnURL:country:statementDescriptor:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sofortParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"statementDescriptor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"sofortParamsWithAmount:returnURL:country:statementDescriptor:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"url":"\/documentation\/stripepayments\/stpsourceparams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","role":"symbol","abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"title":"STPSourceParams","kind":"symbol","navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceParams","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"sofortParamsWithAmount:returnURL:country:statementDescriptor:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sofortParamsWithAmount:returnURL:country:statementDescriptor:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},{"kind":"text","text":" *) "},{"text":"sofortParamsWithAmount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"amount"},{"kind":"text","text":" "},{"text":"returnURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"returnURL","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"country:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"country","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"statementDescriptor:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"statementDescriptor","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"amount","content":[{"type":"paragraph","inlineContent":[{"text":"The amount to charge the customer in EUR.","type":"text"}]}]},{"name":"returnURL","content":[{"type":"paragraph","inlineContent":[{"text":"The URL the customer should be redirected to after","type":"text"},{"type":"text","text":" "},{"type":"text","text":"they have successfully verified the payment."}]}]},{"name":"country","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The country code of the customer’s bank."}]}]},{"name":"statementDescriptor","content":[{"inlineContent":[{"type":"text","text":"(Optional) A custom statement descriptor for"},{"type":"text","text":" "},{"type":"text","text":"the payment."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1sofortParams(withAmount:returnURL:country:statementDescriptor:)\/title","op":"replace","value":"sofortParamsWithAmount:returnURL:country:statementDescriptor:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sofortParamsWithAmount:returnURL:country:statementDescriptor:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1sofortParams(withAmount:returnURL:country:statementDescriptor:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSourceParams"}]}]}]}