{"metadata":{"title":"threeDSecureParams(withAmount:currency:returnURL:card:)","extendedModule":"StripePayments","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)threeDSecureParamsWithAmount:currency:returnURL:card:","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDSecureParams"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"card"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"}],"symbolKind":"method","modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"threeDSecureParamsWithAmount:currency:returnURL:card:"}],"role":"symbol"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/threeDSecureParams(withAmount:currency:returnURL:card:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceparams\/threedsecureparams(withamount:currency:returnurl:card:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/threedsecureparams(withamount:currency:returnurl:card:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threeDSecureParams"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"amount","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"card","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The amount to charge the customer.","type":"text"}],"type":"paragraph"}],"name":"amount"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The currency the payment is being created in."}]}],"name":"currency"},{"content":[{"inlineContent":[{"text":"The URL the customer should be redirected to after they have","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"successfully verified the payment."}],"type":"paragraph"}],"name":"returnURL"},{"name":"card","content":[{"inlineContent":[{"text":"The ID of the card source.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"text":"An STPSourceParams object populated with the provided card details.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"name":"See Also","style":"note","type":"aside","content":[{"inlineContent":[{"text":"https:\/\/stripe.com\/docs\/sources\/three-d-secure#create-3ds-source","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"abstract":[{"type":"text","text":"Creates params for a 3DS source."}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","title":"STPSourceParams","navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceparams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/threeDSecureParams(withAmount:currency:returnURL:card:)":{"title":"threeDSecureParams(withAmount:currency:returnURL:card:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threeDSecureParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"card"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams\/threedsecureparams(withamount:currency:returnurl:card:)","abstract":[{"type":"text","text":"Creates params for a 3DS source."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/threeDSecureParams(withAmount:currency:returnURL:card:)","navigatorTitle":[{"kind":"identifier","text":"threeDSecureParamsWithAmount:currency:returnURL:card:"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"threeDSecureParamsWithAmount:currency:returnURL:card:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"threeDSecureParamsWithAmount:currency:returnURL:card:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},{"text":" *) ","kind":"text"},{"text":"threeDSecureParamsWithAmount:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"amount"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"currency"},{"text":" ","kind":"text"},{"kind":"identifier","text":"returnURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"returnURL"},{"kind":"text","text":" "},{"text":"card:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"card","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"amount","content":[{"type":"paragraph","inlineContent":[{"text":"The amount to charge the customer.","type":"text"}]}]},{"name":"currency","content":[{"inlineContent":[{"text":"The currency the payment is being created in.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The URL the customer should be redirected to after they have","type":"text"},{"type":"text","text":" "},{"type":"text","text":"successfully verified the payment."}],"type":"paragraph"}],"name":"returnURL"},{"name":"card","content":[{"inlineContent":[{"text":"The ID of the card source.","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An STPSourceParams object populated with the provided card details."}],"type":"paragraph"}],"kind":"content"}},{"value":"STPSourceParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1threeDSecureParams(withAmount:currency:returnURL:card:)\/title","value":"threeDSecureParamsWithAmount:currency:returnURL:card:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"threeDSecureParamsWithAmount:currency:returnURL:card:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1threeDSecureParams(withAmount:currency:returnURL:card:)\/fragments"}]}]}