{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"usage"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"usage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceUsage","preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage"}],"title":"usage","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceParams(py)usage","symbolKind":"property"},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/usage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"abstract":[{"text":"Whether this source should be reusable or not. ","type":"text"},{"type":"codeVoice","code":"usage"},{"text":" may be “reusable” or","type":"text"},{"text":" ","type":"text"},{"text":"“single_use”. Some source types may or may not be reusable by construction,","type":"text"},{"text":" ","type":"text"},{"text":"while other may leave the option at creation.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceparams\/usage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/usage"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"usage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage","kind":"typeIdentifier","text":"STPSourceUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"symbol","title":"STPSourceParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/usage":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage","text":"STPSourceUsage","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/usage","navigatorTitle":[{"text":"usage","kind":"identifier"}],"abstract":[{"type":"text","text":"Whether this source should be reusable or not. "},{"type":"codeVoice","code":"usage"},{"type":"text","text":" may be “reusable” or"},{"type":"text","text":" "},{"type":"text","text":"“single_use”. Some source types may or may not be reusable by construction,"},{"type":"text","text":" "},{"type":"text","text":"while other may leave the option at creation."}],"type":"topic","title":"usage","url":"\/documentation\/stripepayments\/stpsourceparams\/usage","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceUsage"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceUsage"}],"url":"\/documentation\/stripepayments\/stpsourceusage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage","kind":"symbol","role":"symbol","title":"STPSourceUsage","type":"topic","abstract":[{"text":"Usage types for a Source","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"usage","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"usage"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage","text":"STPSourceUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage"},{"kind":"text","text":" "},{"kind":"identifier","text":"usage"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSourceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","op":"replace"},{"value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","op":"replace"},{"value":"usage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1usage\/title","op":"replace"},{"value":[{"text":"usage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1usage\/fragments","op":"replace"},{"value":"STPSourceUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/title","op":"replace"},{"value":[{"text":"STPSourceUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/fragments","op":"replace"},{"value":[{"text":"STPSourceUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/navigatorTitle","op":"replace"}]}]}