{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"visaCheckoutParams"},{"kind":"text","text":"("},{"text":"withCallId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"callId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"aside","content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Visa-Checkout","type":"text"}],"type":"paragraph"}],"style":"note","name":"See Also"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Creating an STPSource with these params will give you a","type":"text"},{"type":"text","text":" "},{"text":"source with type == STPSourceTypeCard","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameter callId: The callId property from a "},{"code":"VisaCheckoutResult","type":"codeVoice"},{"type":"text","text":" object."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns: An STPSourceParams object populated with the provided values."}]}]}]}],"style":"note","type":"aside","name":"Note"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"abstract":[{"type":"text","text":"Creates params for a card source created from Visa Checkout."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/visaCheckoutParams(withCallId:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/visacheckoutparams(withcallid:)"]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/visacheckoutparams(withcallid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"extendedModule":"StripePayments","role":"symbol","navigatorTitle":[{"text":"visaCheckoutParamsWithCallId:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","title":"visaCheckoutParams(withCallId:)","externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)visaCheckoutParamsWithCallId:","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"visaCheckoutParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCallId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/visaCheckoutParams(withCallId:)":{"role":"symbol","title":"visaCheckoutParams(withCallId:)","url":"\/documentation\/stripepayments\/stpsourceparams\/visacheckoutparams(withcallid:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/visaCheckoutParams(withCallId:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"visaCheckoutParamsWithCallId:"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visaCheckoutParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withCallId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}],"abstract":[{"type":"text","text":"Creates params for a card source created from Visa Checkout."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams","navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceParams"}],"title":"STPSourceParams"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"visaCheckoutParamsWithCallId:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"visaCheckoutParamsWithCallId:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"text":" *) ","kind":"text"},{"text":"visaCheckoutParamsWithCallId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"callId","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"visaCheckoutParamsWithCallId:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1visaCheckoutParams(withCallId:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"visaCheckoutParamsWithCallId:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1visaCheckoutParams(withCallId:)\/fragments","op":"replace"},{"value":"STPSourceParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}