{"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceparams\/wechatpay(withamount:currency:appid:statementdescriptor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/wechatpay(withamount:currency:appid:statementdescriptor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(wechatPayParamsWithAmount:currency:appId:statementDescriptor:) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"wechatPay","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":" "},{"text":"amount","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statementDescriptor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"This feature is in private beta."}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Parameters:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"amount:               The amount to charge the customer."}]}]},{"content":[{"inlineContent":[{"text":"currency:             The currency of the payment","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"appId:                Your WeChat-provided application id. WeChat Pay uses"},{"text":" ","type":"text"},{"type":"text","text":"this as the redirect URL scheme"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"statementDescriptor:  A custom statement descriptor for the payment (optional)."}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"text":"Returns: An STPSourceParams object populated with the provided values.","type":"text"}],"type":"paragraph"}]}]}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/wechatPay(withAmount:currency:appId:statementDescriptor:)"},"abstract":[{"text":"Create params for a WeChat Pay native app redirect source","type":"text"}],"metadata":{"title":"wechatPay(withAmount:currency:appId:statementDescriptor:)","modules":[{"name":"StripePayments"}],"externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(cm)wechatPayParamsWithAmount:currency:appId:statementDescriptor:","extendedModule":"StripePayments","roleHeading":"Type Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wechatPay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"statementDescriptor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}]},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams","kind":"symbol","title":"STPSourceParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/wechatPay(withAmount:currency:appId:statementDescriptor:)":{"kind":"symbol","title":"wechatPay(withAmount:currency:appId:statementDescriptor:)","type":"topic","navigatorTitle":[{"text":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"wechatPay"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currency"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"statementDescriptor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"abstract":[{"text":"Create params for a WeChat Pay native app redirect source","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/wechatPay(withAmount:currency:appId:statementDescriptor:)","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams\/wechatpay(withamount:currency:appid:statementdescriptor:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"wechatPayParamsWithAmount:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"amount","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currency:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"currency","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appId:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"appId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"statementDescriptor:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"statementDescriptor"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"STPSourceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title"},{"op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"op":"replace","value":[{"text":"STPSourceParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1wechatPay(withAmount:currency:appId:statementDescriptor:)\/title","op":"replace","value":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:"},{"value":[{"kind":"text","text":"+ "},{"text":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1wechatPay(withAmount:currency:appId:statementDescriptor:)\/fragments"}]}]}
