{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)affirm","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"affirm","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"affirm","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirm","text":"STPPaymentMethodAffirm"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"affirm","kind":"identifier"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"affirm","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirm","text":"STPPaymentMethodAffirm","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirm"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/affirm"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/affirm"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/affirm","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"If this is an Affirm PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeAffirm"},{"type":"text","text":"), this contains additional details."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/affirm":{"abstract":[{"type":"text","text":"If this is an Affirm PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypeAffirm","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/affirm","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/affirm","title":"affirm","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"affirm"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirm","kind":"typeIdentifier","text":"STPPaymentMethodAffirm"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"affirm"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","title":"STPPaymentMethod","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAffirm":{"title":"STPPaymentMethodAffirm","abstract":[{"type":"text","text":"The Affirm Payment Method."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirm","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodAffirm"}],"url":"\/documentation\/stripepayments\/stppaymentmethodaffirm","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAffirm"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"affirm"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"affirm","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodAffirm","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirm","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirm"},{"kind":"text","text":" * "},{"kind":"identifier","text":"affirm"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"affirm","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1affirm\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"affirm"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1affirm\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirm\/title","value":"STPPaymentMethodAffirm","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentMethodAffirm","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirm\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirm\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodAffirm"}]}]}]}
