{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/afterpayClearpay"},"metadata":{"role":"symbol","title":"afterpayClearpay","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afterpayClearpay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpay","text":"STPPaymentMethodAfterpayClearpay"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)afterpayClearpay","navigatorTitle":[{"kind":"identifier","text":"afterpayClearpay"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afterpayClearpay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAfterpayClearpay","text":"STPPaymentMethodAfterpayClearpay"},{"kind":"text","text":"? { get }"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/afterpayclearpay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/afterpayclearpay"]}],"abstract":[{"text":"If this is an AfterpayClearpay PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeAfterpayClearpay","type":"codeVoice"},{"text":"), this contains additional details. :nodoc:","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/afterpayClearpay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/afterpayClearpay","type":"topic","kind":"symbol","role":"symbol","title":"afterpayClearpay","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"afterpayClearpay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAfterpayClearpay","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpay","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"If this is an AfterpayClearpay PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeAfterpayClearpay","type":"codeVoice"},{"text":"), this contains additional details. :nodoc:","type":"text"}],"navigatorTitle":[{"text":"afterpayClearpay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/afterpayclearpay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAfterpayClearpay":{"title":"STPPaymentMethodAfterpayClearpay","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAfterpayClearpay","navigatorTitle":[{"text":"STPPaymentMethodAfterpayClearpay","kind":"identifier"}],"abstract":[{"type":"text","text":"An AfterpayClearpay Payment Method."}],"url":"\/documentation\/stripepayments\/stppaymentmethodafterpayclearpay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAfterpayClearpay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"url":"\/documentation\/stripepayments\/stppaymentmethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"title":"STPPaymentMethod","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"afterpayClearpay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"afterpayClearpay"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodAfterpayClearpay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAfterpayClearpay","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpay","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"afterpayClearpay","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1afterpayClearpay\/title","value":"afterpayClearpay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1afterpayClearpay\/fragments","value":[{"kind":"identifier","text":"afterpayClearpay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAfterpayClearpay\/title","value":"STPPaymentMethodAfterpayClearpay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAfterpayClearpay\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodAfterpayClearpay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAfterpayClearpay\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodAfterpayClearpay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethod"}]}]}]}