{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alipay"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipay","kind":"typeIdentifier","text":"STPPaymentMethodAlipay","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipay"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/alipay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/alipay"]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)alipay","title":"alipay","navigatorTitle":[{"kind":"identifier","text":"alipay"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alipay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodAlipay","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipay"},{"kind":"text","text":"?"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/alipay","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"If this is an Alipay PaymentMethod (ie "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeAlipay"},{"type":"text","text":"), this contains additional detailsl"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/alipay":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipay","text":"STPPaymentMethodAlipay","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"alipay","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/alipay","abstract":[{"type":"text","text":"If this is an Alipay PaymentMethod (ie "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeAlipay"},{"type":"text","text":"), this contains additional detailsl"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod\/alipay","title":"alipay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"title":"STPPaymentMethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"role":"symbol","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipay":{"kind":"symbol","abstract":[{"type":"text","text":"Contains details for an Alipay Payment Method."}],"title":"STPPaymentMethodAlipay","url":"\/documentation\/stripepayments\/stppaymentmethodalipay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipay","navigatorTitle":[{"text":"STPPaymentMethodAlipay","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAlipay","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"alipay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"alipay","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipay","text":"STPPaymentMethodAlipay","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipay"},{"text":" * ","kind":"text"},{"text":"alipay","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1alipay\/title","value":"alipay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1alipay\/fragments","value":[{"kind":"identifier","text":"alipay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipay\/title","value":"STPPaymentMethodAlipay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipay\/fragments","value":[{"text":"STPPaymentMethodAlipay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipay\/navigatorTitle","value":[{"text":"STPPaymentMethodAlipay","kind":"identifier"}]}]}]}