{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/aubecsdebit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/aubecsdebit"]}],"metadata":{"symbolKind":"property","title":"auBECSDebit","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)auBECSDebit","role":"symbol","navigatorTitle":[{"text":"auBECSDebit","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"auBECSDebit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAUBECSDebit","kind":"typeIdentifier","text":"STPPaymentMethodAUBECSDebit"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"auBECSDebit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAUBECSDebit","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAUBECSDebit"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/auBECSDebit","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"abstract":[{"type":"text","text":"If this is an AU BECS Debit PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypeAUBECSDebit","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAUBECSDebit"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit","abstract":[{"text":"An AU BECS Debit Payment Method.","type":"text"}],"title":"STPPaymentMethodAUBECSDebit","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/auBECSDebit":{"abstract":[{"text":"If this is an AU BECS Debit PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeAUBECSDebit"},{"type":"text","text":"), this contains additional details."}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/aubecsdebit","navigatorTitle":[{"text":"auBECSDebit","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"auBECSDebit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAUBECSDebit","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAUBECSDebit","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"auBECSDebit","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/auBECSDebit"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"role":"symbol","type":"topic","title":"STPPaymentMethod","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"auBECSDebit","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"auBECSDebit"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"STPPaymentMethodAUBECSDebit","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAUBECSDebit"},{"kind":"text","text":" * "},{"text":"auBECSDebit","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"STPPaymentMethodAUBECSDebit","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodAUBECSDebit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1auBECSDebit\/title","value":"auBECSDebit"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1auBECSDebit\/fragments","op":"replace","value":[{"text":"auBECSDebit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}