{"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)bacsDebit","role":"symbol","roleHeading":"Instance Property","title":"bacsDebit","navigatorTitle":[{"kind":"identifier","text":"bacsDebit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bacsDebit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBacsDebit","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebit"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"If this is a Bacs Debit PaymentMethod (ie "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeBacsDebit"},{"type":"text","text":"), this contains additional details."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bacsDebit"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebit","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebit","kind":"typeIdentifier","text":"STPPaymentMethodBacsDebit"},{"kind":"text","text":"? { get }"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/bacsdebit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/bacsdebit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bacsDebit","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/bacsDebit":{"url":"\/documentation\/stripepayments\/stppaymentmethod\/bacsdebit","navigatorTitle":[{"text":"bacsDebit","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bacsDebit","title":"bacsDebit","role":"symbol","abstract":[{"type":"text","text":"If this is a Bacs Debit PaymentMethod (ie "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeBacsDebit"},{"type":"text","text":"), this contains additional details."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bacsDebit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebit","text":"STPPaymentMethodBacsDebit","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethod","kind":"identifier"}],"title":"STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebit":{"type":"topic","title":"STPPaymentMethodBacsDebit","navigatorTitle":[{"text":"STPPaymentMethodBacsDebit","kind":"identifier"}],"abstract":[{"text":"A Bacs Debit Payment Method.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBacsDebit"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebit","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebit","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"bacsDebit"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"bacsDebit","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebit","kind":"typeIdentifier","text":"STPPaymentMethodBacsDebit","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bacsDebit"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1bacsDebit\/title","op":"replace","value":"bacsDebit"},{"op":"replace","value":[{"text":"bacsDebit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1bacsDebit\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","op":"replace","value":"STPPaymentMethod"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodBacsDebit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebit\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebit\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodBacsDebit"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebit\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBacsDebit"}],"op":"replace"}]}]}