{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bancontact"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontact","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontact","kind":"typeIdentifier","text":"STPPaymentMethodBancontact"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/bancontact"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/bancontact"]}],"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"bancontact"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bancontact"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontact","text":"STPPaymentMethodBancontact"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)bancontact","role":"symbol","title":"bancontact"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bancontact"},"abstract":[{"type":"text","text":"If this is a Bancontact PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeBancontact"},{"type":"text","text":"), this contains additional details."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/bancontact":{"url":"\/documentation\/stripepayments\/stppaymentmethod\/bancontact","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bancontact","role":"symbol","abstract":[{"type":"text","text":"If this is a Bancontact PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeBancontact"},{"type":"text","text":"), this contains additional details."}],"type":"topic","title":"bancontact","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bancontact"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontact","kind":"typeIdentifier","text":"STPPaymentMethodBancontact"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"bancontact"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBancontact":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBancontact"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodbancontact","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodBancontact","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontact","abstract":[{"type":"text","text":"A Bancontact Payment Method."}],"title":"STPPaymentMethodBancontact","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"url":"\/documentation\/stripepayments\/stppaymentmethod","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"type":"topic","title":"STPPaymentMethod"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bancontact","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"bancontact","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontact","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontact","text":"STPPaymentMethodBancontact","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bancontact","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"bancontact","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1bancontact\/title"},{"value":[{"text":"bancontact","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1bancontact\/fragments"},{"value":"STPPaymentMethodBancontact","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontact\/title"},{"value":[{"text":"STPPaymentMethodBancontact","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontact\/fragments"},{"value":[{"text":"STPPaymentMethodBancontact","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontact\/navigatorTitle"},{"value":"STPPaymentMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}