{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billie"},"abstract":[{"type":"text","text":"If this is a Billie PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeBillie"},{"type":"text","text":"), this contains additional details."}],"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)billie","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billie"},{"kind":"text","text":": "},{"text":"STPPaymentMethodBillie","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillie"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"billie"}],"roleHeading":"Instance Property","title":"billie","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"billie","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodBillie","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillie","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillie"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/billie"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/billie"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethod","kind":"identifier"}],"title":"STPPaymentMethod","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/billie":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billie","url":"\/documentation\/stripepayments\/stppaymentmethod\/billie","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billie"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillie","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillie"},{"text":"?","kind":"text"}],"abstract":[{"text":"If this is a Billie PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeBillie","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"title":"billie","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"billie"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillie":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillie","url":"\/documentation\/stripepayments\/stppaymentmethodbillie","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodBillie","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The Billie Payment Method."}],"navigatorTitle":[{"text":"STPPaymentMethodBillie","kind":"identifier"}],"title":"STPPaymentMethodBillie","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"billie"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"billie","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodBillie","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillie","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillie"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"billie"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1billie\/title","value":"billie"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1billie\/fragments","op":"replace","value":[{"kind":"identifier","text":"billie"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillie\/title","value":"STPPaymentMethodBillie","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillie\/fragments","value":[{"text":"STPPaymentMethodBillie","kind":"identifier"}]},{"value":[{"text":"STPPaymentMethodBillie","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillie\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}