{"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"billingDetails"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)billingDetails","role":"symbol","title":"billingDetails","modules":[{"name":"StripePayments"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billingDetails"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billingDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/billingdetails"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/billingdetails"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"url":"\/documentation\/stripepayments\/stppaymentmethod","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethod"}],"title":"STPPaymentMethod","type":"topic","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/billingDetails":{"abstract":[{"type":"text","text":"Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods."}],"title":"billingDetails","url":"\/documentation\/stripepayments\/stppaymentmethod\/billingdetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billingDetails","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"billingDetails","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","role":"symbol","abstract":[{"type":"text","text":"Billing information associated with a "},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","type":"topic","title":"STPPaymentMethodBillingDetails","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"billingDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"billingDetails","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":" * "},{"text":"billingDetails","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"STPPaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"},{"value":"billingDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1billingDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1billingDetails\/fragments","value":[{"text":"billingDetails","kind":"identifier"}]},{"value":"STPPaymentMethodBillingDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"op":"replace"}]}]}