{"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"property","title":"cashApp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cashApp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCashApp","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCashApp","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)cashApp","navigatorTitle":[{"text":"cashApp","kind":"identifier"}],"roleHeading":"Instance Property"},"abstract":[{"text":"If this is an Cash App PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeCashApp","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/cashApp"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cashApp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCashApp","text":"STPPaymentMethodCashApp","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCashApp"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/cashapp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/cashapp"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/cashApp":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cashApp"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCashApp","kind":"typeIdentifier","text":"STPPaymentMethodCashApp"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/cashapp","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/cashApp","title":"cashApp","abstract":[{"type":"text","text":"If this is an Cash App PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeCashApp"},{"type":"text","text":"), this contains additional details."}],"navigatorTitle":[{"kind":"identifier","text":"cashApp"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCashApp":{"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcashapp","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCashApp"}],"type":"topic","abstract":[{"type":"text","text":"The CashApp Payment Method."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCashApp","title":"STPPaymentMethodCashApp","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCashApp"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"type":"topic","role":"symbol","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","title":"STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cashApp"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"cashApp"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCashApp","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCashApp","kind":"typeIdentifier","text":"STPPaymentMethodCashApp"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cashApp"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"cashApp","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1cashApp\/title"},{"op":"replace","value":[{"kind":"identifier","text":"cashApp"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1cashApp\/fragments"},{"op":"replace","value":"STPPaymentMethodCashApp","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCashApp\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodCashApp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCashApp\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodCashApp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCashApp\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}