{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"crypto","kind":"identifier"}],"roleHeading":"Instance Property","title":"crypto","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)crypto","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"crypto","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCrypto","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCrypto","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/crypto"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/crypto"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"crypto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCrypto","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto","text":"STPPaymentMethodCrypto"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"If this is a Crypto PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeCrypto","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/crypto","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCrypto":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcrypto","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCrypto","kind":"identifier"}],"type":"topic","abstract":[{"text":"The Crypto Payment Method.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto","navigatorTitle":[{"text":"STPPaymentMethodCrypto","kind":"identifier"}],"title":"STPPaymentMethodCrypto"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/crypto":{"type":"topic","title":"crypto","url":"\/documentation\/stripepayments\/stppaymentmethod\/crypto","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/crypto","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"crypto","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCrypto","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCrypto","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"If this is a Crypto PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeCrypto","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"navigatorTitle":[{"text":"crypto","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"type":"topic","role":"symbol","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"title":"STPPaymentMethod","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"crypto"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"crypto"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPPaymentMethodCrypto","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCrypto","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto"},{"kind":"text","text":" * "},{"kind":"identifier","text":"crypto"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto\/title","value":"STPPaymentMethodCrypto"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCrypto"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCrypto"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1crypto\/title","value":"crypto"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1crypto\/fragments","value":[{"text":"crypto","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}