{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/grabPay"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"sections":[],"abstract":[{"type":"text","text":"If this is a GrabPay PaymentMethod (ie "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeGrabPay"},{"type":"text","text":"), this contains additional details."}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/grabpay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/grabpay"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"grabPay","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)grabPay","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grabPay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGrabPay","text":"STPPaymentMethodGrabPay","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"grabPay","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grabPay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGrabPay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay","text":"STPPaymentMethodGrabPay","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"type":"topic","title":"STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/grabPay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/grabPay","title":"grabPay","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod\/grabpay","abstract":[{"type":"text","text":"If this is a GrabPay PaymentMethod (ie "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeGrabPay"},{"type":"text","text":"), this contains additional details."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"grabPay","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grabPay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodGrabPay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGrabPay"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodGrabPay":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodgrabpay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay","title":"STPPaymentMethodGrabPay","navigatorTitle":[{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"A GrabPay PaymentMethod","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"grabPay","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"grabPay"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGrabPay","text":"STPPaymentMethodGrabPay"},{"kind":"text","text":" * "},{"kind":"identifier","text":"grabPay"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"},{"op":"replace","value":"grabPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1grabPay\/title"},{"op":"replace","value":[{"kind":"identifier","text":"grabPay"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1grabPay\/fragments"},{"op":"replace","value":"STPPaymentMethodGrabPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay\/navigatorTitle"}]}]}