{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/klarna"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/klarna"]}],"abstract":[{"type":"text","text":"If this is an Klarna PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeKlarna"},{"type":"text","text":"), this contains additional details."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"klarna"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodKlarna","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodKlarna","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodKlarna"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"klarna","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)klarna","navigatorTitle":[{"text":"klarna","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"klarna"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodKlarna","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodKlarna"},{"kind":"text","text":"?"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/klarna","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"kind":"symbol","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"role":"symbol","title":"STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"url":"\/documentation\/stripepayments\/stppaymentmethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/klarna":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/klarna","abstract":[{"type":"text","text":"If this is an Klarna PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeKlarna"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","title":"klarna","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"klarna","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodKlarna","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodKlarna"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/klarna","navigatorTitle":[{"text":"klarna","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodKlarna":{"kind":"symbol","abstract":[{"type":"text","text":"The Klarna Payment Method."}],"role":"symbol","title":"STPPaymentMethodKlarna","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodKlarna","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodklarna","navigatorTitle":[{"text":"STPPaymentMethodKlarna","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodKlarna"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"klarna"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"klarna"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodKlarna","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodKlarna","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodKlarna","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"klarna","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1klarna\/title","value":"klarna"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1klarna\/fragments","value":[{"kind":"identifier","text":"klarna"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodKlarna\/title","value":"STPPaymentMethodKlarna"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodKlarna\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodKlarna"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodKlarna\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodKlarna"}]}]}]}