{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/mobilePay","interfaceLanguage":"swift"},"abstract":[{"text":"If this is a MobilePay PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeMobilePay"},{"text":"), this contains additional details.","type":"text"}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mobilePay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodMobilePay","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMobilePay"},{"kind":"text","text":"?"}],"role":"symbol","title":"mobilePay","navigatorTitle":[{"text":"mobilePay","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)mobilePay","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mobilePay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMobilePay","kind":"typeIdentifier","text":"STPPaymentMethodMobilePay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMobilePay"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/mobilepay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/mobilepay"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"kind":"symbol","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"title":"STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethod","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/mobilePay":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mobilePay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMobilePay","text":"STPPaymentMethodMobilePay"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/mobilepay","title":"mobilePay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/mobilePay","abstract":[{"type":"text","text":"If this is a MobilePay PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeMobilePay"},{"text":"), this contains additional details.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"mobilePay","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMobilePay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMobilePay","kind":"symbol","role":"symbol","abstract":[{"text":"The MobilePay Payment Method.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodMobilePay"}],"title":"STPPaymentMethodMobilePay","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodmobilepay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodMobilePay","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"mobilePay","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mobilePay"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodMobilePay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMobilePay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMobilePay"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"mobilePay"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"STPPaymentMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1mobilePay\/title","value":"mobilePay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1mobilePay\/fragments","value":[{"kind":"identifier","text":"mobilePay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMobilePay\/title","value":"STPPaymentMethodMobilePay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMobilePay\/fragments","value":[{"text":"STPPaymentMethodMobilePay","kind":"identifier"}]}]}]}
