{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"abstract":[{"text":"If this is a Multibanco PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeMultibanco","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"multibanco","kind":"identifier"}],"symbolKind":"property","title":"multibanco","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multibanco","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodMultibanco","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibanco","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)multibanco","role":"symbol"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"multibanco"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodMultibanco","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibanco","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibanco"},{"kind":"text","text":"? { get }"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/multibanco"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/multibanco"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/multibanco"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibanco":{"url":"\/documentation\/stripepayments\/stppaymentmethodmultibanco","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodMultibanco"}],"title":"STPPaymentMethodMultibanco","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodMultibanco"}],"abstract":[{"text":"The Multibanco Payment Method.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibanco","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/multibanco":{"abstract":[{"type":"text","text":"If this is a Multibanco PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypeMultibanco","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod\/multibanco","navigatorTitle":[{"text":"multibanco","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/multibanco","title":"multibanco","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multibanco","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodMultibanco","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibanco","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"type":"topic","role":"symbol","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"title":"STPPaymentMethod","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"multibanco","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"multibanco"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibanco","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibanco","text":"STPPaymentMethodMultibanco"},{"kind":"text","text":" * "},{"kind":"identifier","text":"multibanco"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibanco\/title","value":"STPPaymentMethodMultibanco"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodMultibanco"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibanco\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodMultibanco"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibanco\/navigatorTitle"},{"op":"replace","value":"multibanco","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1multibanco\/title"},{"op":"replace","value":[{"text":"multibanco","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1multibanco\/fragments"},{"op":"replace","value":"STPPaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"}]}]}