{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"netBanking","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodNetBanking","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodNetBanking","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBanking"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"sections":[],"abstract":[{"text":"If this is a NetBanking PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeNetBanking","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/netbanking"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/netbanking"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/netBanking","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"netBanking","kind":"identifier"}],"title":"netBanking","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"netBanking"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodNetBanking","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodNetBanking"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)netBanking","symbolKind":"property","modules":[{"name":"StripePayments"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/netBanking":{"title":"netBanking","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"netBanking","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodNetBanking","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodNetBanking"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/netbanking","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/netBanking","navigatorTitle":[{"text":"netBanking","kind":"identifier"}],"abstract":[{"text":"If this is a NetBanking PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeNetBanking"},{"text":"), this contains additional details.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"type":"topic","title":"STPPaymentMethod","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodNetBanking":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodNetBanking"}],"url":"\/documentation\/stripepayments\/stppaymentmethodnetbanking","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodNetBanking"}],"kind":"symbol","title":"STPPaymentMethodNetBanking","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBanking","abstract":[{"text":"A NetBanking Payment Method.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"netBanking"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"netBanking"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBanking","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodNetBanking","text":"STPPaymentMethodNetBanking"},{"text":" * ","kind":"text"},{"text":"netBanking","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1netBanking\/title","op":"replace","value":"netBanking"},{"value":[{"kind":"identifier","text":"netBanking"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1netBanking\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"value":"STPPaymentMethodNetBanking","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBanking\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBanking\/fragments","op":"replace","value":[{"text":"STPPaymentMethodNetBanking","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBanking\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodNetBanking","kind":"identifier"}]}]}]}