{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payByBank"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodPayByBank","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBank"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"payByBank","kind":"identifier"}],"title":"payByBank","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)payByBank","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"role":"symbol"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/payByBank","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"abstract":[{"text":"If this is a Pay by Bank PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypePayByBank","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payByBank","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBank","kind":"typeIdentifier","text":"STPPaymentMethodPayByBank","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBank"},{"kind":"text","text":"? { get }"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/paybybank"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/paybybank"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayByBank":{"navigatorTitle":[{"text":"STPPaymentMethodPayByBank","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodpaybybank","title":"STPPaymentMethodPayByBank","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPayByBank","kind":"identifier"}],"abstract":[{"type":"text","text":"The Pay by Bank Payment Method."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBank","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod","title":"STPPaymentMethod","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/payByBank":{"navigatorTitle":[{"text":"payByBank","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/paybybank","title":"payByBank","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payByBank","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodPayByBank","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBank","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"If this is a Pay by Bank PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypePayByBank"},{"type":"text","text":"), this contains additional details."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/payByBank","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"payByBank","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"payByBank"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBank","text":"STPPaymentMethodPayByBank","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBank"},{"text":" * ","kind":"text"},{"text":"payByBank","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentMethodPayByBank","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBank\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodPayByBank"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBank\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodPayByBank"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBank\/navigatorTitle"},{"value":"STPPaymentMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"},{"value":"payByBank","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1payByBank\/title"},{"value":[{"kind":"identifier","text":"payByBank"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1payByBank\/fragments"}]}]}