{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/paypal"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/paypal"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"payPal","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodPayPal","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayPal","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPal"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"If this is a PayPal PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypePayPal","type":"codeVoice"},{"text":"), this contains additional details. :nodoc:","type":"text"}],"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"payPal","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodPayPal","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayPal"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"payPal","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)payPal","title":"payPal"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/payPal","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayPal":{"title":"STPPaymentMethodPayPal","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodPayPal"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPayPal","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPal","type":"topic","abstract":[{"type":"text","text":"A PayPal Payment Method. :nodoc:"}],"url":"\/documentation\/stripepayments\/stppaymentmethodpaypal"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/payPal":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/payPal","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"payPal","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodPayPal","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayPal"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"If this is a PayPal PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypePayPal","type":"codeVoice"},{"type":"text","text":"), this contains additional details. :nodoc:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"payPal"}],"title":"payPal","url":"\/documentation\/stripepayments\/stppaymentmethod\/paypal","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"title":"STPPaymentMethod","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"payPal","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"payPal"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"STPPaymentMethodPayPal","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayPal","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPal"},{"kind":"text","text":" * "},{"kind":"identifier","text":"payPal"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"STPPaymentMethodPayPal","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPal\/title"},{"value":[{"text":"STPPaymentMethodPayPal","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPal\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPal\/navigatorTitle","value":[{"text":"STPPaymentMethodPayPal","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1payPal\/title","op":"replace","value":"payPal"},{"value":[{"kind":"identifier","text":"payPal"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1payPal\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}]}]}]}