{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)przelewy24","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"przelewy24"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodPrzelewy24","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24"},{"text":"?","kind":"text"}],"title":"przelewy24","navigatorTitle":[{"kind":"identifier","text":"przelewy24"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/przelewy24","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"If this is a Przelewy24 PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypePrzelewy24"},{"type":"text","text":"), this contains additional details."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"przelewy24"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24","kind":"typeIdentifier","text":"STPPaymentMethodPrzelewy24","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/przelewy24"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/przelewy24"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethod","title":"STPPaymentMethod","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/przelewy24":{"title":"przelewy24","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"przelewy24"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24","text":"STPPaymentMethodPrzelewy24","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/przelewy24","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/przelewy24","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"przelewy24"}],"type":"topic","abstract":[{"text":"If this is a Przelewy24 PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypePrzelewy24","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPrzelewy24":{"url":"\/documentation\/stripepayments\/stppaymentmethodprzelewy24","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Przelewy24 Payment Method."}],"title":"STPPaymentMethodPrzelewy24","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodPrzelewy24"}],"navigatorTitle":[{"text":"STPPaymentMethodPrzelewy24","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"przelewy24","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"przelewy24","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24","kind":"typeIdentifier","text":"STPPaymentMethodPrzelewy24","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24"},{"kind":"text","text":" * "},{"text":"przelewy24","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"},{"value":"przelewy24","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1przelewy24\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"przelewy24"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1przelewy24\/fragments"},{"op":"replace","value":"STPPaymentMethodPrzelewy24","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/fragments","op":"replace","value":[{"text":"STPPaymentMethodPrzelewy24","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/navigatorTitle","value":[{"text":"STPPaymentMethodPrzelewy24","kind":"identifier"}]}]}]}