{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/shopPay"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/shoppay"]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)shopPay","navigatorTitle":[{"text":"shopPay","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"shopPay","role":"symbol","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"identifier","text":"shopPay"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"abstract":[{"text":"If this is a ShopPay PaymentMethod (i.e. ","type":"text"},{"text":"self.type == STPPaymentMethodTypeShopPay","type":"text"},{"text":"), this contains additional details.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodShopPay","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodShopPay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPay","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"shopPay","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/shopPay":{"role":"symbol","title":"shopPay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/shopPay","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/shoppay","abstract":[{"type":"text","text":"If this is a ShopPay PaymentMethod (i.e. "},{"text":"self.type == STPPaymentMethodTypeShopPay","type":"text"},{"text":"), this contains additional details.","type":"text"}],"kind":"symbol","fragments":[{"text":"shopPay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPay":{"title":"STPPaymentMethodShopPay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPay","abstract":[{"type":"text","text":"ShopPay Payment Method."}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"STPPaymentMethodShopPay"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodshoppay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"title":"STPPaymentMethod","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}]}]}]}