{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sunbit","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sunbit"},{"kind":"text","text":": "},{"text":"STPPaymentMethodSunbit","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSunbit"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"sunbit","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"sunbit","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)sunbit"},"abstract":[{"text":"If this is a Sunbit PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeSunibt"},{"type":"text","text":"), this contains additional details."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sunbit"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodSunbit","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSunbit","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSunbit"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/sunbit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/sunbit"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","type":"topic","title":"STPPaymentMethod","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSunbit":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSunbit","type":"topic","abstract":[{"type":"text","text":"The Sunbit Payment Method."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodSunbit","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodsunbit","role":"symbol","kind":"symbol","title":"STPPaymentMethodSunbit","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodSunbit"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/sunbit":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sunbit","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sunbit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodSunbit","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSunbit"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/sunbit","abstract":[{"text":"If this is a Sunbit PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeSunibt"},{"type":"text","text":"), this contains additional details."}],"title":"sunbit","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sunbit"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sunbit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"sunbit"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodSunbit","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSunbit","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSunbit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sunbit"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSunbit\/title","value":"STPPaymentMethodSunbit","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSunbit\/fragments","value":[{"text":"STPPaymentMethodSunbit","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSunbit\/navigatorTitle","value":[{"text":"STPPaymentMethodSunbit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1sunbit\/title","value":"sunbit"},{"value":[{"text":"sunbit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1sunbit\/fragments"}]}]}