{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swish","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSwish","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSwish","text":"STPPaymentMethodSwish","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/swish"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/swish"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/swish","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If this is a Swish PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypeSwish","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"swish"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swish"},{"kind":"text","text":": "},{"text":"STPPaymentMethodSwish","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSwish"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)swish","role":"symbol","title":"swish"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSwish":{"type":"topic","title":"STPPaymentMethodSwish","navigatorTitle":[{"text":"STPPaymentMethodSwish","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSwish","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodSwish","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodswish","abstract":[{"text":"A Swish Payment Method.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"url":"\/documentation\/stripepayments\/stppaymentmethod","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"type":"topic","title":"STPPaymentMethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/swish":{"type":"topic","title":"swish","navigatorTitle":[{"text":"swish","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/swish","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swish","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodSwish","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSwish"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/swish","abstract":[{"text":"If this is a Swish PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeSwish","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"swish"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"swish","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSwish","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSwish","text":"STPPaymentMethodSwish","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"swish","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSwish\/title","value":"STPPaymentMethodSwish"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSwish\/fragments","value":[{"text":"STPPaymentMethodSwish","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSwish\/navigatorTitle","value":[{"text":"STPPaymentMethodSwish","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1swish\/title","value":"swish"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1swish\/fragments","value":[{"text":"swish","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}