{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usBankAccount"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUSBankAccount","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"If this is a US Bank Account PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeUSBankAccount"},{"type":"text","text":"), this contains additional details."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/usbankaccount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod\/usbankaccount"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usBankAccount"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUSBankAccount","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"usBankAccount","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","title":"usBankAccount","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)usBankAccount"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/usBankAccount","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","title":"STPPaymentMethod","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/usBankAccount":{"title":"usBankAccount","navigatorTitle":[{"text":"usBankAccount","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"usBankAccount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUSBankAccount","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount"},{"kind":"text","text":"?"}],"abstract":[{"text":"If this is a US Bank Account PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeUSBankAccount","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/usbankaccount","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/usBankAccount","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"abstract":[{"type":"text","text":"A US Bank Account Payment Method (ACH)"}],"title":"STPPaymentMethodUSBankAccount","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"usBankAccount","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"usBankAccount","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","text":"STPPaymentMethodUSBankAccount","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount"},{"kind":"text","text":" * "},{"text":"usBankAccount","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"},{"op":"replace","value":"usBankAccount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1usBankAccount\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1usBankAccount\/fragments","op":"replace","value":[{"text":"usBankAccount","kind":"identifier"}]},{"value":"STPPaymentMethodUSBankAccount","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/fragments","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}]}]}]}
