{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/wero"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wero"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodWero","kind":"typeIdentifier","text":"STPPaymentMethodWero","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodWero"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"]]},"abstract":[{"text":"If this is a Wero PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeWero","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/wero"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod\/wero"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"wero","kind":"identifier"}],"title":"wero","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod(py)wero","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wero","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodWero","text":"STPPaymentMethodWero","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/wero":{"abstract":[{"text":"If this is a Wero PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeWero"},{"text":"), this contains additional details.","type":"text"}],"kind":"symbol","title":"wero","navigatorTitle":[{"kind":"identifier","text":"wero"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/wero","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"wero"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodWero","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodWero"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/wero","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"type":"topic","title":"STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodWero":{"title":"STPPaymentMethodWero","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodWero","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodWero"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodWero"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The Wero Payment Method."}],"url":"\/documentation\/stripepayments\/stppaymentmethodwero"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"wero","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"wero"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodWero","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodWero","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodWero"},{"text":" * ","kind":"text"},{"text":"wero","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"wero","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1wero\/title"},{"op":"replace","value":[{"kind":"identifier","text":"wero"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1wero\/fragments"},{"op":"replace","value":"STPPaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodWero","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodWero\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodWero","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodWero\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodWero"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodWero\/navigatorTitle"}]}]}