{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReusable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoption\/isreusable"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentoption\/isreusable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/isReusable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Describes whether this payment option may be used multiple times. If it is not reusable,"},{"type":"text","text":" "},{"type":"text","text":"the payment method must be discarded after use."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"isReusable"}],"role":"symbol","title":"isReusable","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReusable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"c:@M@Stripe@objc(pl)STPPaymentOption(py)isReusable","required":true,"modules":[{"name":"Stripe"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption/isReusable":{"navigatorTitle":[{"kind":"identifier","text":"isReusable"}],"role":"symbol","title":"isReusable","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReusable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Describes whether this payment option may be used multiple times. If it is not reusable,"},{"type":"text","text":" "},{"type":"text","text":"the payment method must be discarded after use."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption\/isReusable","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stppaymentoption\/isreusable"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOption":{"role":"symbol","title":"STPPaymentOption","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOption"}],"abstract":[{"type":"text","text":"This protocol represents a payment method that a user can select and use to"},{"type":"text","text":" "},{"type":"text","text":"pay."},{"type":"text","text":" "},{"type":"text","text":"The classes that conform to it and are supported by the UI:"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOption"}],"url":"\/documentation\/stripe\/stppaymentoption"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isReusable"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isReusable"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isReusable"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1isReusable\/title","value":"isReusable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption~1isReusable\/fragments","value":[{"kind":"identifier","text":"isReusable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/title","value":"STPPaymentOption"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOption\/fragments","value":[{"kind":"identifier","text":"STPPaymentOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}