{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodiDEAL"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodideal\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodideal\/decodedobject(fromapiresponse:)"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"modules":[{"name":"StripePayments"}],"symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodiDEAL(cm)decodedObjectFromAPIResponse:","roleHeading":"Type Method","title":"decodedObject(fromAPIResponse:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"text":"fromAPIResponse","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}]}],"name":"response"}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"The object represented by the JSON dictionary, or nil if the object"},{"type":"text","text":" "},{"text":"could not be decoded (i.e. if one of its ","type":"text"},{"type":"codeVoice","code":"requiredFields"},{"text":" is nil).","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodiDEAL\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodiDEAL/decodedObject(fromAPIResponse:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"kind":"symbol","type":"topic","title":"decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stppaymentmethodideal\/decodedobject(fromapiresponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodiDEAL\/decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodiDEAL":{"kind":"symbol","abstract":[{"text":"An iDEAL Payment Method.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodideal","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodiDEAL"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodiDEAL","title":"STPPaymentMethodiDEAL","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodiDEAL","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"decodedObjectFromAPIResponse:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodiDEAL~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodiDEAL~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"value":"STPPaymentMethodiDEAL","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodiDEAL\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodiDEAL\/fragments","value":[{"text":"STPPaymentMethodiDEAL","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodiDEAL\/navigatorTitle","value":[{"text":"STPPaymentMethodiDEAL","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}