{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/additionalAPIParameters","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"additionalAPIParameters","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams(py)additionalAPIParameters","symbolKind":"property","navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"modules":[{"name":"StripePayments"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"STPFormEncodable.additionalAPIParameters","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/additionalapiparameters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/additionalapiparameters"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams/additionalAPIParameters":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/additionalAPIParameters","title":"additionalAPIParameters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"kind":"symbol","url":"\/documentation\/stripepayments\/stpmandateonlineparams\/additionalapiparameters"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams":{"abstract":[{"type":"text","text":"Contains details about a Mandate accepted online. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance-online"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateOnlineParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","kind":"symbol","type":"topic","title":"STPMandateOnlineParams","role":"symbol","url":"\/documentation\/stripepayments\/stpmandateonlineparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"additionalAPIParameters","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"additionalAPIParameters"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams~1additionalAPIParameters\/title","value":"additionalAPIParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams~1additionalAPIParameters\/fragments","value":[{"kind":"identifier","text":"additionalAPIParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/title","value":"STPMandateOnlineParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/fragments","value":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"op":"replace"}]}]}