{"variants":[{"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/decodedobjectfromapiresponse:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams"]]},"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","externalID":"c:@CM@StripePayments@objc(cs)STPMandateOnlineParams(cm)decodedObjectFromAPIResponse:","title":"decodedObjectFromAPIResponse:","fragments":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/decodedObjectFromAPIResponse:","interfaceLanguage":"occ"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams":{"kind":"symbol","title":"STPMandateOnlineParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateOnlineParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"abstract":[{"type":"text","text":"Contains details about a Mandate accepted online. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance-online"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpmandateonlineparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams/decodedObjectFromAPIResponse:":{"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/decodedObjectFromAPIResponse:","type":"topic","kind":"symbol","title":"decodedObjectFromAPIResponse:","role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"url":"\/documentation\/stripepayments\/stpmandateonlineparams\/decodedobjectfromapiresponse:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/title","value":"STPMandateOnlineParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/fragments","value":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/navigatorTitle","value":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}