{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"inferFromClient","kind":"identifier"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams"]]},"metadata":{"symbolKind":"property","title":"inferFromClient","externalID":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams(py)inferFromClient","fragments":[{"kind":"identifier","text":"inferFromClient"}],"navigatorTitle":[{"text":"inferFromClient","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/inferfromclient"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/inferFromClient"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams/inferFromClient":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/inferFromClient","title":"inferFromClient","fragments":[{"text":"inferFromClient","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpmandateonlineparams\/inferfromclient","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams":{"abstract":[{"text":"Contains details about a Mandate accepted online. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance-online","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpmandateonlineparams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPMandateOnlineParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"type":"topic","title":"STPMandateOnlineParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/title","value":"STPMandateOnlineParams"},{"value":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/navigatorTitle","op":"replace"}]}]}