{"variants":[{"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/init(ipaddress:useragent:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/init(ipaddress:useragent:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"init","modules":[{"name":"StripePayments"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithIPAddress:userAgent:"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ipAddress","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userAgent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams(im)initWithIPAddress:userAgent:","title":"init(ipAddress:userAgent:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithIPAddress:userAgent:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"ipAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userAgent"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The IP address from which the Mandate was accepted by the customer."}]}],"name":"ipAddress"},{"name":"userAgent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user agent of the browser from which the Mandate was accepted by the customer."}]}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/init(ipAddress:userAgent:)","interfaceLanguage":"swift"},"abstract":[{"text":"Initializes an STPMandateOnlineParams.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams":{"abstract":[{"type":"text","text":"Contains details about a Mandate accepted online. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance-online"}],"url":"\/documentation\/stripepayments\/stpmandateonlineparams","kind":"symbol","title":"STPMandateOnlineParams","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateOnlineParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams/init(ipAddress:userAgent:)":{"kind":"symbol","navigatorTitle":[{"text":"initWithIPAddress:userAgent:","kind":"identifier"}],"title":"init(ipAddress:userAgent:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/init(ipAddress:userAgent:)","url":"\/documentation\/stripepayments\/stpmandateonlineparams\/init(ipaddress:useragent:)","abstract":[{"text":"Initializes an STPMandateOnlineParams.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ipAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userAgent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithIPAddress:userAgent:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIPAddress:userAgent:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithIPAddress:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ipAddress"},{"kind":"text","text":" "},{"text":"userAgent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userAgent"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"ipAddress","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The IP address from which the Mandate was accepted by the customer."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The user agent of the browser from which the Mandate was accepted by the customer."}]}],"name":"userAgent"}]}},{"op":"add","path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"A new STPMandateOnlineParams instance with the specified parameters.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"value":"STPMandateOnlineParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/fragments","value":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPMandateOnlineParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams~1init(ipAddress:userAgent:)\/title","value":"initWithIPAddress:userAgent:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams~1init(ipAddress:userAgent:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithIPAddress:userAgent:","kind":"identifier"}]}]}]}