{"abstract":[{"type":"text","text":"The IP address from which the Mandate was accepted by the customer."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ipAddress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ipAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"StripePayments"}],"title":"ipAddress","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPMandateOnlineParams(py)ipAddress","symbolKind":"property","navigatorTitle":[{"text":"ipAddress","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/ipaddress"]},{"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/ipaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/ipAddress"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams/ipAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/ipAddress","type":"topic","abstract":[{"type":"text","text":"The IP address from which the Mandate was accepted by the customer."}],"url":"\/documentation\/stripepayments\/stpmandateonlineparams\/ipaddress","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ipAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"ipAddress","kind":"identifier"}],"role":"symbol","title":"ipAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPMandateOnlineParams"}],"type":"topic","title":"STPMandateOnlineParams","url":"\/documentation\/stripepayments\/stpmandateonlineparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","navigatorTitle":[{"kind":"identifier","text":"STPMandateOnlineParams"}],"abstract":[{"type":"text","text":"Contains details about a Mandate accepted online. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance-online"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"ipAddress","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ipAddress","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"ipAddress","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams~1ipAddress\/title","value":"ipAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams~1ipAddress\/fragments","op":"replace","value":[{"kind":"identifier","text":"ipAddress"}]},{"value":"STPMandateOnlineParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/fragments","value":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/navigatorTitle","value":[{"text":"STPMandateOnlineParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}