{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/rootobjectname()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpmandateonlineparams\/rootobjectname()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/rootObjectName()","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@CM@StripePayments@objc(cs)STPMandateOnlineParams(cm)rootObjectName","roleHeading":"Type Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rootObjectName"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"extendedModule":"StripePayments","title":"rootObjectName()"},"abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"text":" below.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/STPFormEncodable-Implementations"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams/rootObjectName()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/rootObjectName()","title":"rootObjectName()","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"type":"topic","url":"\/documentation\/stripepayments\/stpmandateonlineparams\/rootobjectname()","kind":"symbol","abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"type":"text","text":" below."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams/STPFormEncodable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams\/STPFormEncodable-Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stpmandateonlineparams\/stpformencodable-implementations","kind":"article","type":"topic","title":"STPFormEncodable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateOnlineParams":{"url":"\/documentation\/stripepayments\/stpmandateonlineparams","kind":"symbol","type":"topic","abstract":[{"text":"Contains details about a Mandate accepted online. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance-online","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateOnlineParams","navigatorTitle":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"role":"symbol","title":"STPMandateOnlineParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPMandateOnlineParams","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"rootObjectName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams~1rootObjectName()\/title","value":"rootObjectName","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams~1rootObjectName()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/title","value":"STPMandateOnlineParams"},{"value":[{"text":"STPMandateOnlineParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateOnlineParams\/navigatorTitle","op":"replace","value":[{"text":"STPMandateOnlineParams","kind":"identifier"}]}]}]}