{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodpaypayparams\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayPayParams(im)init","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPayParams\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPayParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayPayParams":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodPayPayParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a PayPay Payment Method :nodoc:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodPayPayParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPayParams","url":"\/documentation\/stripepayments\/stppaymentmethodpaypayparams","kind":"symbol","title":"STPPaymentMethodPayPayParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayPayParams/init":{"kind":"symbol","title":"init","abstract":[],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodpaypayparams\/init","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayPayParams\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPayParams\/title","op":"replace","value":"STPPaymentMethodPayPayParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPayParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodPayPayParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayPayParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodPayPayParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}