{"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceklarnadetails\/clienttoken"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceklarnadetails\/clienttoken"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceKlarnaDetails\/clientToken","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPSourceKlarnaDetails(py)clientToken","navigatorTitle":[{"kind":"identifier","text":"clientToken"}],"modules":[{"name":"StripePayments"}],"role":"symbol","title":"clientToken","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceKlarnaDetails"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"The Klarna-specific client token. This may be used with the Klarna SDK."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"name":"See Also","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Developers.Klarna.Com\/Documentation\/In-App\/Ios\/Steps-Klarna-Payments-Native\/#Initialization"}]}],"style":"note"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceKlarnaDetails/clientToken":{"url":"\/documentation\/stripepayments\/stpsourceklarnadetails\/clienttoken","title":"clientToken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceKlarnaDetails\/clientToken","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"clientToken","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"The Klarna-specific client token. This may be used with the Klarna SDK.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceKlarnaDetails":{"title":"STPSourceKlarnaDetails","type":"topic","url":"\/documentation\/stripepayments\/stpsourceklarnadetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceKlarnaDetails","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceKlarnaDetails","kind":"identifier"}],"abstract":[{"type":"text","text":"Details of a Klarna source."}],"navigatorTitle":[{"text":"STPSourceKlarnaDetails","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"clientToken"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clientToken"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"clientToken"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceKlarnaDetails~1clientToken\/title","value":"clientToken"},{"op":"replace","value":[{"text":"clientToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceKlarnaDetails~1clientToken\/fragments"},{"value":"STPSourceKlarnaDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceKlarnaDetails\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceKlarnaDetails\/fragments","op":"replace","value":[{"text":"STPSourceKlarnaDetails","kind":"identifier"}]},{"value":[{"text":"STPSourceKlarnaDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceKlarnaDetails\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}