{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/brand(forNumber:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(brandForNumber:) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forNumber","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cardNumber","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"typeIdentifier"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A card number, or partial card number. For","type":"text"},{"text":" ","type":"text"},{"text":"example, @“4242”, @“5555555555554444”, or @“123”.","type":"text"}]}],"name":"cardNumber"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The brand for that card number. The example parameters would"},{"type":"text","text":" "},{"type":"text","text":"return STPCardBrandVisa, STPCardBrandMasterCard, and"},{"type":"text","text":" "},{"type":"text","text":"STPCardBrandUnknown, respectively."}],"type":"paragraph"}]}],"metadata":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"brandForNumber:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"}],"externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)brandForNumber:","title":"brand(forNumber:)","roleHeading":"Type Method","modules":[{"name":"StripePayments"}],"symbolKind":"method"},"abstract":[{"text":"The card brand for a card number or substring thereof.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/brand(fornumber:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/brand(fornumber:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"This class contains static methods to validate card numbers, expiration dates,"},{"type":"text","text":" "},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"type":"text","text":" "},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"title":"STPCardValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardValidator","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","url":"\/documentation\/stripepayments\/stpcardvalidator","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/brand(forNumber:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/brand(forNumber:)","type":"topic","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"brandForNumber:"}],"title":"brand(forNumber:)","abstract":[{"text":"The card brand for a card number or substring thereof.","type":"text"}],"url":"\/documentation\/stripepayments\/stpcardvalidator\/brand(fornumber:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"title":"STPCardBrand","navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcardbrand","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardBrand"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"brandForNumber:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"brandForNumber:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") "},{"kind":"identifier","text":"brandForNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A card number, or partial card number. For","type":"text"},{"text":" ","type":"text"},{"text":"example, @“4242”, @“5555555555554444”, or @“123”.","type":"text"}]}],"name":"cardNumber"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The brand for that card number. The example parameters would","type":"text"},{"text":" ","type":"text"},{"text":"return STPCardBrandVisa, STPCardBrandMasterCard, and","type":"text"},{"text":" ","type":"text"},{"text":"STPCardBrandUnknown, respectively.","type":"text"}]}],"kind":"content"}},{"value":"STPCardValidator","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","op":"replace"},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPCardValidator"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","op":"replace"},{"value":"brandForNumber:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1brand(forNumber:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"brandForNumber:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1brand(forNumber:)\/fragments","op":"replace"},{"value":"STPCardBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","op":"replace"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","op":"replace"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","op":"replace"}]}]}