{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(fragmentLengthForCardBrand:) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fragmentLength"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"text":"brand","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand to return the fragment length for."}]}],"name":"brand"}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"The final fragment length card numbers associated with that brand use.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/fragmentLength(for:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"abstract":[{"type":"text","text":"The length of the final grouping of digits to use when formatting a card number"},{"text":" ","type":"text"},{"text":"for display.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For example, Visa cards display their final 4 numbers, e.g. “4242”, while"},{"type":"text","text":" "},{"text":"American Express cards display their final 5 digits, e.g. “10005”.","type":"text"}],"metadata":{"title":"fragmentLength(for:)","navigatorTitle":[{"text":"fragmentLengthForCardBrand:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Type Method","externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)fragmentLengthForCardBrand:","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fragmentLength","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","modules":[{"name":"StripePayments"}]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/fragmentlength(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/fragmentlength(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/fragmentLength(for:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fragmentLength"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"fragmentLength(for:)","navigatorTitle":[{"kind":"identifier","text":"fragmentLengthForCardBrand:"}],"type":"topic","abstract":[{"type":"text","text":"The length of the final grouping of digits to use when formatting a card number"},{"text":" ","type":"text"},{"text":"for display.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, Visa cards display their final 4 numbers, e.g. “4242”, while"},{"text":" ","type":"text"},{"text":"American Express cards display their final 5 digits, e.g. “10005”.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/fragmentlength(for:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/fragmentLength(for:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"title":"STPCardBrand","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCardValidator","kind":"identifier"}],"title":"STPCardValidator","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This class contains static methods to validate card numbers, expiration dates,"},{"text":" ","type":"text"},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"type":"text","text":" "},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","url":"\/documentation\/stripepayments\/stpcardvalidator","navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"fragmentLengthForCardBrand:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"fragmentLengthForCardBrand:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"fragmentLengthForCardBrand:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The brand to return the fragment length for.","type":"text"}],"type":"paragraph"}],"name":"brand"}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"The final fragment length card numbers associated with that brand use."}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1fragmentLength(for:)\/title","op":"replace","value":"fragmentLengthForCardBrand:"},{"value":[{"kind":"text","text":"+ "},{"text":"fragmentLengthForCardBrand:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1fragmentLength(for:)\/fragments","op":"replace"},{"value":"STPCardBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title"},{"value":[{"kind":"identifier","text":"STPCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","value":"STPCardValidator"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","value":[{"kind":"identifier","text":"STPCardValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardValidator"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}