{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardvalidator\/init"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/init","interfaceLanguage":"occ"},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(im)init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","title":"init","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}],"title":"STPCardValidator","abstract":[{"text":"This class contains static methods to validate card numbers, expiration dates,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"type":"text","text":" "},{"text":"see https:\/\/stripe.com\/docs\/testing","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcardvalidator","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardValidator","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/init":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcardvalidator\/init","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/init","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPCardValidator","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","op":"replace"},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","op":"replace","value":[{"text":"STPCardValidator","kind":"identifier"}]}]}]}