{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/lengths(for:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"abstract":[{"text":"The possible number lengths for cards associated with a card brand. For","type":"text"},{"text":" ","type":"text"},{"text":"example, Discover card numbers contain 16 characters, while American Express","type":"text"},{"type":"text","text":" "},{"type":"text","text":"cards contain 15 characters."}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"lengthsForCardBrand:"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"lengths","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":">","kind":"text"}],"symbolKind":"method","title":"lengths(for:)","modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)lengthsForCardBrand:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(lengthsForCardBrand:) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"lengths","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"text":"brand","kind":"internalParam"},{"kind":"text","text":": "},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"brand","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand to return lengths for."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The set of possible lengths cards associated with that brand can be.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/lengths(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/lengths(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"symbol","title":"STPCardBrand","url":"\/documentation\/stripepayments\/stpcardbrand","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardBrand"}],"role":"symbol","navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"abstract":[{"text":"This class contains static methods to validate card numbers, expiration dates,","type":"text"},{"type":"text","text":" "},{"text":"and CVCs. For a list of test card numbers to use with this code,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardValidator"}],"title":"STPCardValidator","navigatorTitle":[{"kind":"identifier","text":"STPCardValidator"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/lengths(for:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lengths"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"lengthsForCardBrand:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcardvalidator\/lengths(for:)","title":"lengths(for:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/lengths(for:)","kind":"symbol","abstract":[{"text":"The possible number lengths for cards associated with a card brand. For","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"example, Discover card numbers contain 16 characters, while American Express"},{"type":"text","text":" "},{"type":"text","text":"cards contain 15 characters."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"lengthsForCardBrand:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"lengthsForCardBrand:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSNumber *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"lengthsForCardBrand:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"},{"text":") ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The brand to return lengths for.","type":"text"}],"type":"paragraph"}],"name":"brand"}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The set of possible lengths cards associated with that brand can be."}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","value":"STPCardBrand","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"kind":"identifier","text":"STPCardBrand"}]},{"value":[{"kind":"identifier","text":"STPCardBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","op":"replace"},{"value":"STPCardValidator","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPCardValidator"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","value":[{"text":"STPCardValidator","kind":"identifier"}]},{"value":"lengthsForCardBrand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1lengths(for:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"lengthsForCardBrand:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1lengths(for:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}