{"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/maxcvclength(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/maxcvclength(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The max CVC length for a card brand (for example, American Express CVCs are"},{"type":"text","text":" "},{"type":"text","text":"4 digits, while all others are 3)."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxCVCLength(for:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(maxCVCLengthForCardBrand:) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxCVCLength"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"name":"brand","content":[{"inlineContent":[{"text":"The brand to return the max CVC length for.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum length of CVC numbers for cards associated with that brand."}]}]}],"sections":[],"metadata":{"title":"maxCVCLength(for:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxCVCLength"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"text":"maxCVCLengthForCardBrand:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)maxCVCLengthForCardBrand:","modules":[{"name":"StripePayments"}],"roleHeading":"Type Method"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/maxCVCLength(for:)":{"title":"maxCVCLength(for:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"maxCVCLength","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"maxCVCLengthForCardBrand:","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The max CVC length for a card brand (for example, American Express CVCs are"},{"text":" ","type":"text"},{"type":"text","text":"4 digits, while all others are 3)."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxCVCLength(for:)","url":"\/documentation\/stripepayments\/stpcardvalidator\/maxcvclength(for:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardValidator"}],"navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class contains static methods to validate card numbers, expiration dates,"},{"type":"text","text":" "},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"text":" ","type":"text"},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","kind":"symbol","title":"STPCardValidator","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCardBrand","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"title":"STPCardBrand","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"maxCVCLengthForCardBrand:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"maxCVCLengthForCardBrand:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"text":"maxCVCLengthForCardBrand:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The brand to return the max CVC length for.","type":"text"}],"type":"paragraph"}],"name":"brand"}]},"path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The maximum length of CVC numbers for cards associated with that brand."}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1maxCVCLength(for:)\/title","value":"maxCVCLengthForCardBrand:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"maxCVCLengthForCardBrand:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1maxCVCLength(for:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","value":"STPCardValidator"},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","op":"replace","value":[{"text":"STPCardValidator","kind":"identifier"}]},{"value":"STPCardBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments"},{"value":[{"kind":"identifier","text":"STPCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle"}]}]}