{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxLength(for:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(maxLengthForCardBrand:) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxLength","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"brand","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The brand to return the max length for."}],"type":"paragraph"}],"name":"brand"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The maximum length card numbers associated with that brand could be.","type":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardvalidator\/maxlength(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardvalidator\/maxlength(for:)"]}],"sections":[],"abstract":[{"type":"text","text":"The maximum possible length the number of a card associated with the specified"},{"text":" ","type":"text"},{"text":"brand could be.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, Visa cards could be either 13 or 16 characters, so this method"},{"type":"text","text":" "},{"type":"text","text":"would return 16 for the that card brand."}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"maxLength","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)maxLengthForCardBrand:","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"text":"maxLengthForCardBrand:","kind":"identifier"}],"title":"maxLength(for:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/maxLength(for:)":{"url":"\/documentation\/stripepayments\/stpcardvalidator\/maxlength(for:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxLength"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxLengthForCardBrand:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxLength(for:)","kind":"symbol","abstract":[{"type":"text","text":"The maximum possible length the number of a card associated with the specified"},{"type":"text","text":" "},{"type":"text","text":"brand could be."},{"text":" ","type":"text"},{"text":"For example, Visa cards could be either 13 or 16 characters, so this method","type":"text"},{"type":"text","text":" "},{"type":"text","text":"would return 16 for the that card brand."}],"title":"maxLength(for:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"title":"STPCardBrand","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCardBrand","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","url":"\/documentation\/stripepayments\/stpcardbrand","navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"abstract":[{"type":"text","text":"This class contains static methods to validate card numbers, expiration dates,"},{"type":"text","text":" "},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"type":"text","text":" "},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","url":"\/documentation\/stripepayments\/stpcardvalidator","navigatorTitle":[{"kind":"identifier","text":"STPCardValidator"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidator"}],"title":"STPCardValidator","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"maxLengthForCardBrand:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"maxLengthForCardBrand:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"maxLengthForCardBrand:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The brand to return the max length for.","type":"text"}],"type":"paragraph"}],"name":"brand"}],"kind":"parameters"}},{"value":{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"The maximum length card numbers associated with that brand could be.","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1maxLength(for:)\/title","value":"maxLengthForCardBrand:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1maxLength(for:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"maxLengthForCardBrand:","kind":"identifier"}]},{"op":"replace","value":"STPCardBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardBrand"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","value":"STPCardValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","value":[{"text":"STPCardValidator","kind":"identifier"}]},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}