{"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/possiblebrands(forcard:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"abstract":[{"text":"Returns available brands for the provided card details.","type":"text"}],"metadata":{"role":"symbol","title":"possibleBrands(forCard:completion:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"possibleBrands"},{"kind":"text","text":"("},{"text":"forCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","kind":"typeIdentifier","text":"STPPaymentMethodCardParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":">, "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":">) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"StripePayments"}],"externalID":"s:14StripePayments16STPCardValidatorC14possibleBrands7forCard10completionyAA016STPPaymentMethodH6ParamsC_ys6ResultOyShyAA0C5BrandOGs5Error_pGctFZ","roleHeading":"Type Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"possibleBrands","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forCard"},{"text":" ","kind":"text"},{"text":"cardParams","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","text":"STPPaymentMethodCardParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Will be called with the set of available STPCardBrands or an error."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Card-Brand-Choice","type":"text"}]}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/possibleBrands(forCard:completion:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardValidator"}],"navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class contains static methods to validate card numbers, expiration dates,"},{"type":"text","text":" "},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"text":" ","type":"text"},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","kind":"symbol","title":"STPCardValidator","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/possibleBrands(forCard:completion:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"possibleBrands","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCard","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethodCardParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"},{"text":">, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepayments\/stpcardvalidator\/possiblebrands(forcard:completion:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/possibleBrands(forCard:completion:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Returns available brands for the provided card details."}],"title":"possibleBrands(forCard:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams":{"title":"STPPaymentMethodCardParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardParams"}],"abstract":[{"text":"The user’s card details.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardparams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The various card brands to which a payment card can belong."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCardBrand","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","navigatorTitle":[{"kind":"identifier","text":"STPCardBrand"}],"title":"STPCardBrand","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPCardValidator","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","op":"replace","value":[{"text":"STPCardValidator","kind":"identifier"}]},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/title","value":"STPPaymentMethodCardParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardParams"}],"op":"replace"},{"value":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/navigatorTitle","op":"replace"},{"value":"STPCardBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","op":"replace"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","value":[{"text":"STPCardBrand","kind":"identifier"}]}]}]}