{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(sanitizedNumericStringForString:) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sanitizedNumericString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"string","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/sanitizednumericstring(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/sanitizednumericstring(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/sanitizedNumericString(for:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Returns a copy of the passed string with all non-numeric characters removed."}],"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"sanitizedNumericStringForString:","kind":"identifier"}],"roleHeading":"Type Method","externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)sanitizedNumericStringForString:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sanitizedNumericString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"sanitizedNumericString(for:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/sanitizedNumericString(for:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sanitizedNumericString"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"sanitizedNumericString(for:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sanitizedNumericStringForString:"}],"url":"\/documentation\/stripepayments\/stpcardvalidator\/sanitizednumericstring(for:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/sanitizedNumericString(for:)","abstract":[{"text":"Returns a copy of the passed string with all non-numeric characters removed.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"kind":"symbol","type":"topic","title":"STPCardValidator","url":"\/documentation\/stripepayments\/stpcardvalidator","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardValidator","kind":"identifier"}],"abstract":[{"text":"This class contains static methods to validate card numbers, expiration dates,","type":"text"},{"text":" ","type":"text"},{"text":"and CVCs. For a list of test card numbers to use with this code,","type":"text"},{"text":" ","type":"text"},{"text":"see https:\/\/stripe.com\/docs\/testing","type":"text"}],"navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sanitizedNumericStringForString:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"sanitizedNumericStringForString:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sanitizedNumericStringForString:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"string","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"sanitizedNumericStringForString:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1sanitizedNumericString(for:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1sanitizedNumericString(for:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sanitizedNumericStringForString:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","value":"STPCardValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","value":[{"text":"STPCardValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardValidator"}]}]}]}