{"abstract":[{"type":"text","text":"Whether or not the target string contains only numeric characters."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(stringIsNumeric:) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stringIsNumeric","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"string"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"kind":"symbol","metadata":{"symbolKind":"method","roleHeading":"Type Method","role":"symbol","title":"stringIsNumeric(_:)","externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)stringIsNumeric:","navigatorTitle":[{"text":"stringIsNumeric:","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stringIsNumeric","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/stringIsNumeric(_:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardvalidator\/stringisnumeric(_:)"]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/stringisnumeric(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"url":"\/documentation\/stripepayments\/stpcardvalidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardValidator"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardValidator"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","abstract":[{"text":"This class contains static methods to validate card numbers, expiration dates,","type":"text"},{"text":" ","type":"text"},{"text":"and CVCs. For a list of test card numbers to use with this code,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"title":"STPCardValidator"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/stringIsNumeric(_:)":{"title":"stringIsNumeric(_:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/stringIsNumeric(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stringIsNumeric:"}],"kind":"symbol","abstract":[{"type":"text","text":"Whether or not the target string contains only numeric characters."}],"type":"topic","url":"\/documentation\/stripepayments\/stpcardvalidator\/stringisnumeric(_:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stringIsNumeric","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"stringIsNumeric:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringIsNumeric:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"stringIsNumeric:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"string"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPCardValidator","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title"},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments"},{"op":"replace","value":[{"text":"STPCardValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle"},{"value":"stringIsNumeric:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1stringIsNumeric(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1stringIsNumeric(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"stringIsNumeric:","kind":"identifier"}],"op":"replace"}]}]}