{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Validates an expiration year, passed as a string representing the final"},{"type":"text","text":" "},{"type":"text","text":"2 digits of the year."},{"type":"text","text":" "},{"type":"text","text":"This considers the period between the current year until 2099 as valid times."},{"type":"text","text":" "},{"type":"text","text":"An example valid year value would be “16” (assuming the current year, as"},{"type":"text","text":" "},{"type":"text","text":"determined by NSDate.date, is 2015)."},{"type":"text","text":" "},{"type":"text","text":"Will return STPCardValidationStateInvalid for a month\/year combination that"},{"type":"text","text":" "},{"type":"text","text":"is earlier than the current date (i.e. @“15” and @“04” in October 2015)."},{"type":"text","text":" "},{"type":"text","text":"Example invalid year values are “00”, “a”, and “13”. Any 1-digit year string"},{"type":"text","text":" "},{"type":"text","text":"will return STPCardValidationStateIncomplete."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(validationStateForExpirationYear:inMonth:) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forExpirationYear","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"expirationYear","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inMonth"},{"kind":"text","text":" "},{"kind":"internalParam","text":"expirationMonth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"STPCardValidationState","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"expirationYear","content":[{"type":"paragraph","inlineContent":[{"text":"A string representing a 2-digit expiration year for a","type":"text"},{"text":" ","type":"text"},{"text":"payment card.","type":"text"}]}]},{"name":"expirationMonth","content":[{"type":"paragraph","inlineContent":[{"text":"A string representing a valid 2-digit expiration month","type":"text"},{"text":" ","type":"text"},{"text":"for a payment card. If the month is invalid","type":"text"},{"text":" ","type":"text"},{"text":"(see ","type":"text"},{"code":"validationStateForExpirationMonth","type":"codeVoice"},{"text":"), this will","type":"text"},{"text":" ","type":"text"},{"text":"return STPCardValidationStateInvalid.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"STPCardValidationStateValid if the year is valid,"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateInvalid if the year is invalid, or"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateIncomplete if the year is a substring of a valid"},{"type":"text","text":" "},{"type":"text","text":"year (e.g. @“1” or @“2”)."}]}]}],"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)validationStateForExpirationYear:inMonth:","navigatorTitle":[{"text":"validationStateForExpirationYear:inMonth:","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forExpirationYear","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"inMonth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","text":"STPCardValidationState","kind":"typeIdentifier"}],"symbolKind":"method","title":"validationState(forExpirationYear:inMonth:)","roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forexpirationyear:inmonth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forexpirationyear:inmonth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationYear:inMonth:)"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"kind":"symbol","title":"STPCardValidationState","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidationstate","abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"type":"text","text":"value, or incomplete value."}],"navigatorTitle":[{"text":"STPCardValidationState","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardValidationState","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forExpirationYear:inMonth:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forExpirationYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inMonth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","text":"STPCardValidationState"}],"url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forexpirationyear:inmonth:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validationStateForExpirationYear:inMonth:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationYear:inMonth:)","abstract":[{"type":"text","text":"Validates an expiration year, passed as a string representing the final"},{"type":"text","text":" "},{"type":"text","text":"2 digits of the year."},{"type":"text","text":" "},{"type":"text","text":"This considers the period between the current year until 2099 as valid times."},{"type":"text","text":" "},{"type":"text","text":"An example valid year value would be “16” (assuming the current year, as"},{"type":"text","text":" "},{"type":"text","text":"determined by NSDate.date, is 2015)."},{"type":"text","text":" "},{"type":"text","text":"Will return STPCardValidationStateInvalid for a month\/year combination that"},{"type":"text","text":" "},{"type":"text","text":"is earlier than the current date (i.e. @“15” and @“04” in October 2015)."},{"type":"text","text":" "},{"type":"text","text":"Example invalid year values are “00”, “a”, and “13”. Any 1-digit year string"},{"type":"text","text":" "},{"type":"text","text":"will return STPCardValidationStateIncomplete."}],"role":"symbol","title":"validationState(forExpirationYear:inMonth:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardValidator"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","kind":"symbol","title":"STPCardValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidator"}],"url":"\/documentation\/stripepayments\/stpcardvalidator","abstract":[{"text":"This class contains static methods to validate card numbers, expiration dates,","type":"text"},{"text":" ","type":"text"},{"text":"and CVCs. For a list of test card numbers to use with this code,","type":"text"},{"text":" ","type":"text"},{"text":"see https:\/\/stripe.com\/docs\/testing","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"validationStateForExpirationYear:inMonth:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"validationStateForExpirationYear:inMonth:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier","text":"STPCardValidationState","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"},{"kind":"text","text":") "},{"kind":"identifier","text":"validationStateForExpirationYear:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expirationYear"},{"kind":"text","text":" "},{"kind":"identifier","text":"inMonth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expirationMonth"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A string representing a 2-digit expiration year for a"},{"type":"text","text":" "},{"type":"text","text":"payment card."}]}],"name":"expirationYear"},{"content":[{"inlineContent":[{"type":"text","text":"A string representing a valid 2-digit expiration month"},{"type":"text","text":" "},{"type":"text","text":"for a payment card. If the month is invalid"},{"type":"text","text":" "},{"type":"text","text":"(see "},{"type":"codeVoice","code":"validationStateForExpirationMonth"},{"type":"text","text":"), this will"},{"type":"text","text":" "},{"type":"text","text":"return STPCardValidationStateInvalid."}],"type":"paragraph"}],"name":"expirationMonth"}]},"op":"replace"},{"value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"STPCardValidationStateValid if the year is valid,"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateInvalid if the year is invalid, or"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateIncomplete if the year is a substring of a valid"},{"type":"text","text":" "},{"type":"text","text":"year (e.g. @“1” or @“2”)."}]}]},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"STPCardValidationState","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title","op":"replace"},{"value":[{"text":"STPCardValidationState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments","op":"replace"},{"value":[{"text":"STPCardValidationState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle","op":"replace"},{"value":"validationStateForExpirationYear:inMonth:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forExpirationYear:inMonth:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"validationStateForExpirationYear:inMonth:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forExpirationYear:inMonth:)\/fragments","op":"replace"},{"value":"STPCardValidator","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPCardValidator"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","op":"replace"},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","op":"replace"}]}]}