{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(validationStateForCard:) "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCard"},{"text":" ","kind":"text"},{"text":"card","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","kind":"typeIdentifier","text":"STPCardValidationState"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The card details to validate."}],"type":"paragraph"}],"name":"card"}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"STPCardValidationStateValid if all fields are valid,"},{"text":" ","type":"text"},{"type":"text","text":"STPCardValidationStateInvalid if any field is invalid, or"},{"text":" ","type":"text"},{"type":"text","text":"STPCardValidationStateIncomplete if all fields are either incomplete or valid."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"abstract":[{"type":"text","text":"Validates the given card details."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCard:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)validationStateForCard:","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"kind":"text","text":"("},{"text":"forCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","text":"STPCardParams","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","text":"STPCardValidationState","kind":"typeIdentifier"}],"symbolKind":"method","role":"symbol","roleHeading":"Type Method","title":"validationState(forCard:)","navigatorTitle":[{"kind":"identifier","text":"validationStateForCard:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forcard:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forcard:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forCard:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCard:)","title":"validationState(forCard:)","abstract":[{"type":"text","text":"Validates the given card details."}],"navigatorTitle":[{"kind":"identifier","text":"validationStateForCard:"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forcard:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCard"},{"text":": ","kind":"text"},{"text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"STPCardValidationState","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","abstract":[{"type":"text","text":"Representation of a user’s credit card details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"title":"STPCardParams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardParams"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcardparams","navigatorTitle":[{"kind":"identifier","text":"STPCardParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"navigatorTitle":[{"kind":"identifier","text":"STPCardValidationState"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcardvalidationstate","abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"type":"text","text":"value, or incomplete value."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","title":"STPCardValidationState","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidationState"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardValidator"}],"navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class contains static methods to validate card numbers, expiration dates,"},{"type":"text","text":" "},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"text":" ","type":"text"},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","kind":"symbol","title":"STPCardValidator","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"validationStateForCard:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"validationStateForCard:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","kind":"typeIdentifier","text":"STPCardValidationState","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState"},{"kind":"text","text":") "},{"kind":"identifier","text":"validationStateForCard:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams"},{"kind":"text","text":" *) "},{"text":"card","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The card details to validate.","type":"text"}],"type":"paragraph"}],"name":"card"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"STPCardValidationStateValid if all fields are valid,"},{"text":" ","type":"text"},{"type":"text","text":"STPCardValidationStateInvalid if any field is invalid, or"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateIncomplete if all fields are either incomplete or valid."}],"type":"paragraph"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forCard:)\/title","value":"validationStateForCard:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"validationStateForCard:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forCard:)\/fragments"},{"op":"replace","value":"STPCardParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title"},{"op":"replace","value":[{"text":"STPCardParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments"},{"op":"replace","value":[{"text":"STPCardParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle"},{"value":"STPCardValidationState","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments","value":[{"kind":"identifier","text":"STPCardValidationState"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle","value":[{"text":"STPCardValidationState","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","value":"STPCardValidator"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","op":"replace","value":[{"text":"STPCardValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}