{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"metadata":{"navigatorTitle":[{"text":"validationStateForCVC:cardBrand:","kind":"identifier"}],"role":"symbol","title":"validationState(forCVC:cardBrand:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCVC","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cardBrand","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"STPCardValidationState","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)validationStateForCVC:cardBrand:","roleHeading":"Type Method","modules":[{"name":"StripePayments"}],"symbolKind":"method"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forcvc:cardbrand:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forcvc:cardbrand:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCVC:cardBrand:)"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(validationStateForCVC:cardBrand:) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCVC","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cvc","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"cardBrand","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","text":"STPCardValidationState","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The CVC to validate","type":"text"}]}],"name":"cvc"},{"content":[{"inlineContent":[{"type":"text","text":"The card brand (can be determined from the card’s number"},{"type":"text","text":" "},{"type":"text","text":"using "},{"code":"brandForNumber","type":"codeVoice"},{"type":"text","text":")"}],"type":"paragraph"}],"name":"brand"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Whether the CVC represents a valid CVC for that card brand. For"},{"type":"text","text":" "},{"type":"text","text":"example, would return STPCardValidationStateValid for @“123” and"},{"type":"text","text":" "},{"type":"text","text":"STPCardBrandVisa, STPCardValidationStateValid for @“1234” and"},{"type":"text","text":" "},{"type":"text","text":"STPCardBrandAmericanExpress, STPCardValidationStateIncomplete for @“12” and"},{"type":"text","text":" "},{"type":"text","text":"STPCardBrandVisa, and STPCardValidationStateInvalid for @“12345” and any brand."}],"type":"paragraph"}]}],"abstract":[{"text":"Validates a card’s CVC, passed as a numeric string, for the given card brand.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"type":"text","text":"value, or incomplete value."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardValidationState"}],"url":"\/documentation\/stripepayments\/stpcardvalidationstate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidationState"}],"title":"STPCardValidationState"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","url":"\/documentation\/stripepayments\/stpcardvalidator","navigatorTitle":[{"kind":"identifier","text":"STPCardValidator"}],"kind":"symbol","title":"STPCardValidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidator"}],"abstract":[{"text":"This class contains static methods to validate card numbers, expiration dates,","type":"text"},{"text":" ","type":"text"},{"text":"and CVCs. For a list of test card numbers to use with this code,","type":"text"},{"text":" ","type":"text"},{"text":"see https:\/\/stripe.com\/docs\/testing","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forCVC:cardBrand:)":{"navigatorTitle":[{"text":"validationStateForCVC:cardBrand:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Validates a card’s CVC, passed as a numeric string, for the given card brand.","type":"text"}],"title":"validationState(forCVC:cardBrand:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCVC:cardBrand:)","url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forcvc:cardbrand:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forCVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cardBrand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","text":"STPCardValidationState"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}],"kind":"symbol","title":"STPCardBrand","type":"topic","abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","url":"\/documentation\/stripepayments\/stpcardbrand","role":"symbol","navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"validationStateForCVC:cardBrand:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"validationStateForCVC:cardBrand:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","text":"STPCardValidationState","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState"},{"kind":"text","text":") "},{"kind":"identifier","text":"validationStateForCVC:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cvc"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardBrand:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The CVC to validate"}]}],"name":"cvc"},{"content":[{"inlineContent":[{"text":"The card brand (can be determined from the card’s number","type":"text"},{"text":" ","type":"text"},{"text":"using ","type":"text"},{"type":"codeVoice","code":"brandForNumber"},{"text":")","type":"text"}],"type":"paragraph"}],"name":"brand"}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the CVC represents a valid CVC for that card brand. For"},{"type":"text","text":" "},{"type":"text","text":"example, would return STPCardValidationStateValid for @“123” and"},{"type":"text","text":" "},{"type":"text","text":"STPCardBrandVisa, STPCardValidationStateValid for @“1234” and"},{"type":"text","text":" "},{"type":"text","text":"STPCardBrandAmericanExpress, STPCardValidationStateIncomplete for @“12” and"},{"type":"text","text":" "},{"type":"text","text":"STPCardBrandVisa, and STPCardValidationStateInvalid for @“12345” and any brand."}]}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title","value":"STPCardValidationState","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments","value":[{"text":"STPCardValidationState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardValidationState"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","value":"STPCardValidator","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","value":[{"text":"STPCardValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","value":[{"text":"STPCardValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forCVC:cardBrand:)\/title","value":"validationStateForCVC:cardBrand:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forCVC:cardBrand:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"validationStateForCVC:cardBrand:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title","value":"STPCardBrand","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments","value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle","value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}