{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forNumber:validatingCardBrand:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(fornumber:validatingcardbrand:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(fornumber:validatingcardbrand:)"]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)validationStateForNumber:validatingCardBrand:","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"kind":"text","text":"("},{"text":"forNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"validatingCardBrand","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier","text":"STPCardValidationState"}],"title":"validationState(forNumber:validatingCardBrand:)","navigatorTitle":[{"text":"validationStateForNumber:validatingCardBrand:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"StripePayments"}],"role":"symbol"},"sections":[],"abstract":[{"type":"text","text":"Validates a card number, passed as a string. This will return"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateInvalid for numbers that are too short or long, contain"},{"type":"text","text":" "},{"type":"text","text":"invalid characters, do not pass Luhn validation, or (optionally) do not match"},{"text":" ","type":"text"},{"type":"text","text":"a number format issued by a major card brand."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(validationStateForNumber:validatingCardBrand:) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationState"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forNumber"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"cardNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"validatingCardBrand"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"STPCardValidationState","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"cardNumber","content":[{"inlineContent":[{"type":"text","text":"The card number to validate. Ex. @“4242424242424242”"}],"type":"paragraph"}]},{"name":"validatingCardBrand","content":[{"inlineContent":[{"text":"Whether or not to enforce that the number appears to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"be issued by a major card brand (or could be). For example, no issuing card"},{"type":"text","text":" "},{"type":"text","text":"network currently issues card numbers beginning with the digit 9; if an"},{"type":"text","text":" "},{"type":"text","text":"otherwise correct-length and luhn-valid card number beginning with 9"},{"type":"text","text":" "},{"type":"text","text":"(example: 9999999999999995) were passed to this method, it would return"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateInvalid if this parameter were YES and"},{"text":" ","type":"text"},{"type":"text","text":"STPCardValidationStateValid if this parameter were NO. If unsure, you should"},{"type":"text","text":" "},{"type":"text","text":"use YES for this value."}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"STPCardValidationStateValid if the number is valid,","type":"text"},{"type":"text","text":" "},{"text":"STPCardValidationStateInvalid if the number is invalid, or","type":"text"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateIncomplete if the number is a substring of a valid"},{"text":" ","type":"text"},{"type":"text","text":"card (e.g. @“4242”)."}]}],"kind":"content"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"navigatorTitle":[{"text":"STPCardValidationState","kind":"identifier"}],"title":"STPCardValidationState","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidationState"}],"url":"\/documentation\/stripepayments\/stpcardvalidationstate","abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"text":" ","type":"text"},{"type":"text","text":"value, or incomplete value."}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"url":"\/documentation\/stripepayments\/stpcardvalidator","type":"topic","abstract":[{"type":"text","text":"This class contains static methods to validate card numbers, expiration dates,"},{"text":" ","type":"text"},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"type":"text","text":" "},{"text":"see https:\/\/stripe.com\/docs\/testing","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardValidator","kind":"identifier"}],"title":"STPCardValidator","navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forNumber:validatingCardBrand:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forNumber:validatingCardBrand:)","navigatorTitle":[{"kind":"identifier","text":"validationStateForNumber:validatingCardBrand:"}],"kind":"symbol","type":"topic","title":"validationState(forNumber:validatingCardBrand:)","abstract":[{"type":"text","text":"Validates a card number, passed as a string. This will return"},{"text":" ","type":"text"},{"type":"text","text":"STPCardValidationStateInvalid for numbers that are too short or long, contain"},{"type":"text","text":" "},{"type":"text","text":"invalid characters, do not pass Luhn validation, or (optionally) do not match"},{"type":"text","text":" "},{"type":"text","text":"a number format issued by a major card brand."}],"url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(fornumber:validatingcardbrand:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"validatingCardBrand","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier","text":"STPCardValidationState"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","value":"validationStateForNumber:validatingCardBrand:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"validationStateForNumber:validatingCardBrand:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","text":"STPCardValidationState"},{"text":") ","kind":"text"},{"kind":"identifier","text":"validationStateForNumber:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cardNumber"},{"kind":"text","text":" "},{"text":"validatingCardBrand:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"validatingCardBrand"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"cardNumber","content":[{"type":"paragraph","inlineContent":[{"text":"The card number to validate. Ex. @“4242424242424242”","type":"text"}]}]},{"name":"validatingCardBrand","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether or not to enforce that the number appears to"},{"type":"text","text":" "},{"type":"text","text":"be issued by a major card brand (or could be). For example, no issuing card"},{"text":" ","type":"text"},{"text":"network currently issues card numbers beginning with the digit 9; if an","type":"text"},{"type":"text","text":" "},{"type":"text","text":"otherwise correct-length and luhn-valid card number beginning with 9"},{"text":" ","type":"text"},{"type":"text","text":"(example: 9999999999999995) were passed to this method, it would return"},{"text":" ","type":"text"},{"type":"text","text":"STPCardValidationStateInvalid if this parameter were YES and"},{"text":" ","type":"text"},{"type":"text","text":"STPCardValidationStateValid if this parameter were NO. If unsure, you should"},{"type":"text","text":" "},{"text":"use YES for this value.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"STPCardValidationStateValid if the number is valid,"},{"type":"text","text":" "},{"type":"text","text":"STPCardValidationStateInvalid if the number is invalid, or"},{"text":" ","type":"text"},{"text":"STPCardValidationStateIncomplete if the number is a substring of a valid","type":"text"},{"type":"text","text":" "},{"type":"text","text":"card (e.g. @“4242”)."}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","value":"STPCardValidationState","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title"},{"value":[{"text":"STPCardValidationState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardValidationState"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","value":"STPCardValidator","op":"replace"},{"op":"replace","value":[{"text":"STPCardValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","value":[{"text":"STPCardValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forNumber:validatingCardBrand:)\/title","value":"validationStateForNumber:validatingCardBrand:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forNumber:validatingCardBrand:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"validationStateForNumber:validatingCardBrand:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}