{"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forexpirationmonth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forexpirationmonth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"]]},"metadata":{"title":"validationState(forExpirationMonth:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forExpirationMonth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"STPCardValidationState","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState"}],"externalID":"c:@M@StripePayments@objc(cs)STPCardValidator(cm)validationStateForExpirationMonth:","modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"validationStateForExpirationMonth:"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationMonth:)","interfaceLanguage":"swift"},"abstract":[{"text":"Validates an expiration month, passed as an (optionally 0-padded) string.","type":"text"},{"text":" ","type":"text"},{"text":"Example valid values are “3”, “12”, and “08”. Example invalid values are “99”,","type":"text"},{"text":" ","type":"text"},{"text":"“a”, and “00”. Incomplete values include “0” and “1”.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(validationStateForExpirationMonth:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forExpirationMonth"},{"kind":"text","text":" "},{"kind":"internalParam","text":"expirationMonth"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"STPCardValidationState","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A string representing a 2-digit expiration month for a","type":"text"},{"text":" ","type":"text"},{"text":"payment card.","type":"text"}]}],"name":"expirationMonth"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"STPCardValidationStateValid if the month is valid,","type":"text"},{"text":" ","type":"text"},{"text":"STPCardValidationStateInvalid if the month is invalid, or","type":"text"},{"text":" ","type":"text"},{"text":"STPCardValidationStateIncomplete if the month is a substring of a valid","type":"text"},{"text":" ","type":"text"},{"text":"month (e.g. @“0” or @“1”).","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"title":"STPCardValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidator"}],"url":"\/documentation\/stripepayments\/stpcardvalidator","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","type":"topic","abstract":[{"type":"text","text":"This class contains static methods to validate card numbers, expiration dates,"},{"type":"text","text":" "},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"type":"text","text":" "},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardValidator"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardValidationState","kind":"identifier"}],"abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"type":"text","text":"value, or incomplete value."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","url":"\/documentation\/stripepayments\/stpcardvalidationstate","kind":"symbol","title":"STPCardValidationState","role":"symbol","navigatorTitle":[{"text":"STPCardValidationState","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forExpirationMonth:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationState"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forExpirationMonth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier","text":"STPCardValidationState"}],"title":"validationState(forExpirationMonth:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationMonth:)","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forexpirationmonth:)","abstract":[{"text":"Validates an expiration month, passed as an (optionally 0-padded) string.","type":"text"},{"text":" ","type":"text"},{"text":"Example valid values are “3”, “12”, and “08”. Example invalid values are “99”,","type":"text"},{"text":" ","type":"text"},{"text":"“a”, and “00”. Incomplete values include “0” and “1”.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validationStateForExpirationMonth:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"validationStateForExpirationMonth:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"validationStateForExpirationMonth:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","text":"STPCardValidationState","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validationStateForExpirationMonth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"expirationMonth","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A string representing a 2-digit expiration month for a","type":"text"},{"text":" ","type":"text"},{"text":"payment card.","type":"text"}]}],"name":"expirationMonth"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"STPCardValidationStateValid if the month is valid,","type":"text"},{"text":" ","type":"text"},{"text":"STPCardValidationStateInvalid if the month is invalid, or","type":"text"},{"text":" ","type":"text"},{"text":"STPCardValidationStateIncomplete if the month is a substring of a valid","type":"text"},{"text":" ","type":"text"},{"text":"month (e.g. @“0” or @“1”).","type":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","value":"STPCardValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","value":[{"text":"STPCardValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title","value":"STPCardValidationState"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments","value":[{"text":"STPCardValidationState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle","value":[{"text":"STPCardValidationState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forExpirationMonth:)\/title","value":"validationStateForExpirationMonth:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forExpirationMonth:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"validationStateForExpirationMonth:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}