{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualparams\/dateofbirth"]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualparams\/dateofbirth"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation14DateComponentsV","text":"DateComponents","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"dateOfBirth","symbolKind":"property","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams(py)dateOfBirth","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams\/dateOfBirth"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams"]]},"abstract":[{"type":"text","text":"The individual’s date of birth."},{"type":"text","text":" "},{"type":"text","text":"Must include "},{"type":"codeVoice","code":"day"},{"type":"text","text":", "},{"type":"codeVoice","code":"month"},{"text":", and ","type":"text"},{"code":"year","type":"codeVoice"},{"text":", and only those fields are used.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"text":"DateComponents","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation14DateComponentsV"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams":{"url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams","navigatorTitle":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"role":"symbol","title":"STPConnectAccountIndividualParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Information about the person represented by the account for use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams/dateOfBirth":{"navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"role":"symbol","kind":"symbol","title":"dateOfBirth","abstract":[{"type":"text","text":"The individual’s date of birth."},{"type":"text","text":" "},{"text":"Must include ","type":"text"},{"code":"day","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"month"},{"text":", and ","type":"text"},{"type":"codeVoice","code":"year"},{"type":"text","text":", and only those fields are used."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams\/dateOfBirth","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation14DateComponentsV","text":"DateComponents","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams\/dateofbirth"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"dateOfBirth"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"dateOfBirth","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSDateComponents","preciseIdentifier":"c:objc(cs)NSDateComponents"},{"text":" * ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPConnectAccountIndividualParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/fragments","op":"replace","value":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/navigatorTitle","value":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams~1dateOfBirth\/title","op":"replace","value":"dateOfBirth"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams~1dateOfBirth\/fragments","value":[{"text":"dateOfBirth","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}