{"abstract":[{"type":"text","text":"The Kana variation of the the individual’s primary address (Japan only)."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kanaAddress"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","text":"STPConnectAccountAddress"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"kanaAddress","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams(py)kanaAddress","roleHeading":"Instance Property","navigatorTitle":[{"text":"kanaAddress","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"kanaAddress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","text":"STPConnectAccountAddress"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"StripePayments"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams\/kanaAddress","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualparams\/kanaaddress"]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualparams\/kanaaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConnectAccountAddress"}],"title":"STPConnectAccountAddress","url":"\/documentation\/stripepayments\/stpconnectaccountaddress","navigatorTitle":[{"text":"STPConnectAccountAddress","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"An address to use with "},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"title":"STPConnectAccountIndividualParams","url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountIndividualParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Information about the person represented by the account for use with ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams/kanaAddress":{"title":"kanaAddress","url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams\/kanaaddress","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kanaAddress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","text":"STPConnectAccountAddress"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"The Kana variation of the the individual’s primary address (Japan only)."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams\/kanaAddress","navigatorTitle":[{"text":"kanaAddress","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"kanaAddress","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"kanaAddress","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","text":"STPConnectAccountAddress"},{"kind":"text","text":" * "},{"text":"kanaAddress","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPConnectAccountAddress","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/title"},{"value":[{"kind":"identifier","text":"STPConnectAccountAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/fragments","op":"replace"},{"value":"STPConnectAccountIndividualParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountIndividualParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams~1kanaAddress\/title","op":"replace","value":"kanaAddress"},{"value":[{"kind":"identifier","text":"kanaAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams~1kanaAddress\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
