{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualparams\/lastname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualparams\/lastname"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The individual’s last name."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"title":"lastName","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams(py)lastName","navigatorTitle":[{"kind":"identifier","text":"lastName"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams\/lastName"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams/lastName":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lastName"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams\/lastName","title":"lastName","url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams\/lastname","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The individual’s last name."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams":{"url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Information about the person represented by the account for use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"title":"STPConnectAccountIndividualParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"lastName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"lastName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"lastName"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams~1lastName\/title","value":"lastName"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams~1lastName\/fragments","value":[{"kind":"identifier","text":"lastName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/title","value":"STPConnectAccountIndividualParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountIndividualParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPConnectAccountIndividualParams"}]}]}]}