{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualparams\/verification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountindividualparams\/verification"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualVerification","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification","kind":"typeIdentifier","text":"STPConnectAccountIndividualVerification"},{"kind":"text","text":"?"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams(py)verification","navigatorTitle":[{"kind":"identifier","text":"verification"}],"symbolKind":"property","title":"verification","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualVerification","text":"STPConnectAccountIndividualVerification"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams\/verification"},"sections":[],"abstract":[{"type":"text","text":"The individual’s verification document information."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams/verification":{"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams\/verification","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams\/verification","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPConnectAccountIndividualVerification","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualVerification","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"verification","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The individual’s verification document information."}],"title":"verification"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams":{"url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams","navigatorTitle":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"type":"topic","title":"STPConnectAccountIndividualParams","abstract":[{"text":"Information about the person represented by the account for use with ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualVerification":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountIndividualVerification"}],"navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountIndividualVerification"}],"url":"\/documentation\/stripepayments\/stpconnectaccountindividualverification","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification","abstract":[{"type":"text","text":"The individual’s verification document information for use with "},{"type":"codeVoice","code":"STPConnectAccountIndividualParams"},{"type":"text","text":"."}],"kind":"symbol","title":"STPConnectAccountIndividualVerification","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"verification","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"verification","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualVerification","text":"STPConnectAccountIndividualVerification","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualVerification"},{"text":" * ","kind":"text"},{"text":"verification","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams~1verification\/title","value":"verification","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams~1verification\/fragments","op":"replace","value":[{"kind":"identifier","text":"verification"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/title","op":"replace","value":"STPConnectAccountIndividualParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountIndividualParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/navigatorTitle","op":"replace","value":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/title","op":"replace","value":"STPConnectAccountIndividualVerification"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/fragments","op":"replace","value":[{"text":"STPConnectAccountIndividualVerification","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualVerification\/navigatorTitle","op":"replace","value":[{"text":"STPConnectAccountIndividualVerification","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}