{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentcapturemethod\/automaticasync"]},{"paths":["\/documentation\/stripepayments\/stppaymentintentcapturemethod\/automaticasync"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"STPPaymentIntentCaptureMethodAutomaticAsync","kind":"identifier"}],"symbolKind":"case","title":"STPPaymentIntentCaptureMethod.automaticAsync","role":"symbol","roleHeading":"Case","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentCaptureMethod@STPPaymentIntentCaptureMethodAutomaticAsync","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automaticAsync"}]},"abstract":[{"type":"text","text":"Asynchronously capture funds when the customer authorizes the payment."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"automaticAsync","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"style":"note","content":[{"inlineContent":[{"type":"text","text":"Recommended over "},{"type":"codeVoice","code":"CaptureMethod.automatic"},{"text":" due to improved latency, but may require additional integration changes.","type":"text"}],"type":"paragraph"}],"name":"Note","type":"aside"},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Payments\/Payment-Intents\/Asynchronous-Capture-Automatic-Async","type":"text"}]}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/automaticAsync"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/automaticAsync":{"navigatorTitle":[{"text":"STPPaymentIntentCaptureMethodAutomaticAsync","kind":"identifier"}],"abstract":[{"type":"text","text":"Asynchronously capture funds when the customer authorizes the payment."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"automaticAsync","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/automaticAsync","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/automaticasync","title":"STPPaymentIntentCaptureMethod.automaticAsync","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod":{"role":"symbol","title":"STPPaymentIntentCaptureMethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"abstract":[{"text":"Capture methods for a STPPaymentIntent","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentIntentCaptureMethodAutomaticAsync","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentCaptureMethodAutomaticAsync","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPPaymentIntentCaptureMethodAutomaticAsync","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1automaticAsync\/title","value":"STPPaymentIntentCaptureMethodAutomaticAsync"},{"value":[{"text":"STPPaymentIntentCaptureMethodAutomaticAsync","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1automaticAsync\/fragments"},{"value":"STPPaymentIntentCaptureMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/title"},{"value":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/navigatorTitle","value":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}