{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod"]]},"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","role":"symbol","externalID":"s:14StripePayments29STPPaymentIntentCaptureMethodO8rawValueACSgSi_tcfc","title":"init(rawValue:)"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/init(rawValue:)"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentcapturemethod\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/init(rawValue:)","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod","role":"symbol","abstract":[{"type":"text","text":"Capture methods for a STPPaymentIntent"}],"title":"STPPaymentIntentCaptureMethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPPaymentIntentCaptureMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}