{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/manual","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentcapturemethod\/manual"]},{"paths":["\/documentation\/stripepayments\/stppaymentintentcapturemethod\/manual"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"STPPaymentIntentCaptureMethod.manual","navigatorTitle":[{"text":"STPPaymentIntentCaptureMethodManual","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentIntentCaptureMethod@STPPaymentIntentCaptureMethodManual","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manual"}],"modules":[{"name":"StripePayments"}]},"abstract":[{"type":"text","text":"The PaymentIntent must be manually captured once it has the status"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresCapture"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/manual":{"navigatorTitle":[{"text":"STPPaymentIntentCaptureMethodManual","kind":"identifier"}],"title":"STPPaymentIntentCaptureMethod.manual","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/manual","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/manual","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"manual"}],"abstract":[{"type":"text","text":"The PaymentIntent must be manually captured once it has the status"},{"text":" ","type":"text"},{"code":"STPPaymentIntentStatusRequiresCapture","type":"codeVoice"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod":{"abstract":[{"type":"text","text":"Capture methods for a STPPaymentIntent"}],"url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}],"role":"symbol","title":"STPPaymentIntentCaptureMethod","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPPaymentIntentCaptureMethodManual","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodManual"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodManual"}]}]}},{"value":"STPPaymentIntentCaptureMethodManual","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1manual\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentCaptureMethodManual","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1manual\/fragments"},{"value":"STPPaymentIntentCaptureMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/fragments","op":"replace","value":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}]}]}]}
