{"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"API Collection","role":"collectionGroup","title":"RawRepresentable Implementations"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentcapturemethod\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod"]]},"kind":"article","sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/hashValue"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/hash(into:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture methods for a STPPaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod","type":"topic","title":"STPPaymentIntentCaptureMethod","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/hash(into:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/hash(into:)","type":"topic","title":"hash(into:)","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/hash(into:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/hashValue":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/hashValue","type":"topic","kind":"symbol","title":"hashValue","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/hashvalue","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntentCaptureMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/fragments","op":"replace"},{"value":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/navigatorTitle","op":"replace"}]}]}