//
//  Enums+CustomStringConvertible.swift
//  Stripe
//
//  Autogenerated by generate_objc_enum_string_values.rb
//  Copyright © 2021 Stripe, Inc. All rights reserved.
//

import SwiftUI

/// :nodoc:
extension STPBankSelectionMethod: CustomStringConvertible {
    public var description: String {
        switch self {
        case .FPX:
            return "FPX"
        case .unknown:
            return "unknown"
        }
    }
}

/// :nodoc:
extension STPBillingAddressFields: CustomStringConvertible {
    public var description: String {
        switch self {
        case .full:
            return "full"
        case .name:
            return "name"
        case .none:
            return "none"
        case .postalCode:
            return "postalCode"
        case .zip:
            return "zip"
        }
    }
}

/// :nodoc:
extension STPShippingStatus: CustomStringConvertible {
    public var description: String {
        switch self {
        case .invalid:
            return "invalid"
        case .valid:
            return "valid"
        }
    }
}

/// :nodoc:
extension STPShippingType: CustomStringConvertible {
    public var description: String {
        switch self {
        case .delivery:
            return "delivery"
        case .shipping:
            return "shipping"
        }
    }
}
