{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/businesstype"]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/businesstype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The business type."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"businessType","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPConnectAccountBusinessType","preciseIdentifier":"c:@M@StripePayments@E@STPConnectAccountBusinessType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"businessType","navigatorTitle":[{"text":"businessType","kind":"identifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams(py)businessType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"businessType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPConnectAccountBusinessType","text":"STPConnectAccountBusinessType"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/businessType"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/businessType":{"abstract":[{"type":"text","text":"The business type."}],"title":"businessType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/businessType","navigatorTitle":[{"text":"businessType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountparams\/businesstype","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"businessType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPConnectAccountBusinessType","text":"STPConnectAccountBusinessType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType":{"navigatorTitle":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"title":"STPConnectAccountBusinessType","abstract":[{"text":"The business type of the Connect account.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountParams","kind":"identifier"}],"type":"topic","kind":"symbol","title":"STPConnectAccountParams","url":"\/documentation\/stripepayments\/stpconnectaccountparams","abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"businessType","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"businessType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPConnectAccountBusinessType","preciseIdentifier":"c:@M@StripePayments@E@STPConnectAccountBusinessType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"businessType"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"businessType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1businessType\/title"},{"value":[{"kind":"identifier","text":"businessType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1businessType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/title","value":"STPConnectAccountBusinessType","op":"replace"},{"value":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title","op":"replace","value":"STPConnectAccountParams"},{"value":[{"text":"STPConnectAccountParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}