{"metadata":{"navigatorTitle":[{"text":"initWithCompany:","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams(im)initWithCompany:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"company"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams","text":"STPConnectAccountCompanyParams","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"init","modules":[{"name":"StripePayments"}],"role":"symbol","title":"init(company:)","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/init(company:)"]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/init(company:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(company:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"company","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPConnectAccountCompanyParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Information about the company or business"},{"type":"text","text":" "},{"type":"text","text":"This init method cannot change the "},{"type":"codeVoice","code":"tosShownAndAccepted"},{"text":" parameter. Use","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"initWithTosShownAndAccepted:company:"},{"text":" instead if you need to do that.","type":"text"}]}],"name":"company"}]}],"abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":" with the provided "},{"code":"company","type":"codeVoice"},{"type":"text","text":" dictionary."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Information about the company or business to use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"title":"STPConnectAccountCompanyParams","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"kind":"symbol","abstract":[{"text":"Parameters for creating a Connect Account token.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"title":"STPConnectAccountParams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPConnectAccountParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","url":"\/documentation\/stripepayments\/stpconnectaccountparams","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init(company:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(company:)","navigatorTitle":[{"text":"initWithCompany:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize "},{"code":"STPConnectAccountParams","type":"codeVoice"},{"type":"text","text":" with the provided "},{"type":"codeVoice","code":"company"},{"text":" dictionary.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init(company:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"company","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPConnectAccountCompanyParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","title":"init(company:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithCompany:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCompany:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCompany:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","text":"STPConnectAccountCompanyParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams"},{"text":" *) ","kind":"text"},{"text":"company","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title","value":"STPConnectAccountCompanyParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}]},{"value":"STPConnectAccountParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountParams"}],"op":"replace"},{"value":"initWithCompany:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(company:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCompany:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(company:)\/fragments"}]}]}
