{"abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":" with tosShownAndAccepted = YES"},{"type":"text","text":" "},{"type":"text","text":"This method cannot be called with "},{"type":"codeVoice","code":"wasAccepted == NO"},{"type":"text","text":", guarded by a "},{"type":"codeVoice","code":"NSParameterAssert()"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Use this init method if you want to set the "},{"type":"codeVoice","code":"tosShownAndAccepted"},{"type":"text","text":" parameter. If you"},{"type":"text","text":" "},{"type":"text","text":"don’t, use the "},{"type":"codeVoice","code":"initWithIndividual:"},{"type":"text","text":" version instead."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/init(tosshownandaccepted:individual:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/init(tosshownandaccepted:individual:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:individual:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"init","role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTosShownAndAccepted:individual:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"tosShownAndAccepted"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"individual"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams","kind":"typeIdentifier","text":"STPConnectAccountIndividualParams"},{"kind":"text","text":")"}],"roleHeading":"Initializer","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams(im)initWithTosShownAndAccepted:individual:","modules":[{"name":"StripePayments"}],"title":"init(tosShownAndAccepted:individual:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"tosShownAndAccepted","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"wasAccepted","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"individual","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPConnectAccountIndividualParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams"},{"text":")","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"wasAccepted","content":[{"type":"paragraph","inlineContent":[{"text":"Must be YES, but only if the user was shown & accepted the ToS","type":"text"}]}]},{"name":"individual","content":[{"type":"paragraph","inlineContent":[{"text":"Information about the person represented by the account. See ","type":"text"},{"code":"STPConnectAccountIndividualParams","type":"codeVoice"},{"text":".","type":"text"}]}]}],"kind":"parameters"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init(tosShownAndAccepted:individual:)":{"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithTosShownAndAccepted:individual:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize "},{"code":"STPConnectAccountParams","type":"codeVoice"},{"type":"text","text":" with tosShownAndAccepted = YES"},{"type":"text","text":" "},{"type":"text","text":"This method cannot be called with "},{"code":"wasAccepted == NO","type":"codeVoice"},{"type":"text","text":", guarded by a "},{"code":"NSParameterAssert()","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Use this init method if you want to set the "},{"code":"tosShownAndAccepted","type":"codeVoice"},{"type":"text","text":" parameter. If you"},{"type":"text","text":" "},{"type":"text","text":"don’t, use the "},{"code":"initWithIndividual:","type":"codeVoice"},{"type":"text","text":" version instead."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:individual:)","title":"init(tosShownAndAccepted:individual:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"tosShownAndAccepted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"individual","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPConnectAccountIndividualParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init(tosshownandaccepted:individual:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams","title":"STPConnectAccountIndividualParams","navigatorTitle":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Information about the person represented by the account for use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPConnectAccountParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountParams","kind":"identifier"}],"abstract":[{"text":"Parameters for creating a Connect Account token.","type":"text"}],"title":"STPConnectAccountParams","url":"\/documentation\/stripepayments\/stpconnectaccountparams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithTosShownAndAccepted:individual:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTosShownAndAccepted:individual:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTosShownAndAccepted:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"wasAccepted"},{"kind":"text","text":" "},{"kind":"identifier","text":"individual:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams","kind":"typeIdentifier","text":"STPConnectAccountIndividualParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"individual"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"wasAccepted","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must be YES, but only if the user was shown & accepted the ToS"}]}]},{"name":"individual","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Information about the person represented by the account. See "},{"type":"codeVoice","code":"STPConnectAccountIndividualParams"},{"type":"text","text":"."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"initWithTosShownAndAccepted:individual:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(tosShownAndAccepted:individual:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTosShownAndAccepted:individual:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(tosShownAndAccepted:individual:)\/fragments"},{"value":"STPConnectAccountIndividualParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/title"},{"value":[{"kind":"identifier","text":"STPConnectAccountIndividualParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/fragments"},{"value":[{"kind":"identifier","text":"STPConnectAccountIndividualParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/navigatorTitle"},{"value":"STPConnectAccountParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title"},{"value":[{"kind":"identifier","text":"STPConnectAccountParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments"},{"value":[{"kind":"identifier","text":"STPConnectAccountParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle"}]}]}