{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountParams"},{"text":" with the provided ","type":"text"},{"type":"codeVoice","code":"individual"},{"text":" dictionary.","type":"text"}],"metadata":{"roleHeading":"Initializer","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams(im)initWithIndividual:","title":"init(individual:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"individual","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPConnectAccountIndividualParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithIndividual:","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"individual"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams","kind":"typeIdentifier","text":"STPConnectAccountIndividualParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"individual","content":[{"type":"paragraph","inlineContent":[{"text":"Information about the person represented by the account","type":"text"},{"text":" ","type":"text"},{"text":"This init method cannot change the ","type":"text"},{"type":"codeVoice","code":"tosShownAndAccepted"},{"text":" parameter. Use","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"initWithTosShownAndAccepted:individual:"},{"text":" instead if you need to do that.","type":"text"}]}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(individual:)"},"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/init(individual:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/init(individual:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountParams"}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams","title":"STPConnectAccountParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init(individual:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithIndividual:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"individual"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPConnectAccountIndividualParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(individual:)","kind":"symbol","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":" with the provided "},{"type":"codeVoice","code":"individual"},{"type":"text","text":" dictionary."}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init(individual:)","title":"init(individual:)","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountIndividualParams":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams","navigatorTitle":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"abstract":[{"text":"Information about the person represented by the account for use with ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconnectaccountindividualparams","title":"STPConnectAccountIndividualParams","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithIndividual:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIndividual:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithIndividual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPConnectAccountIndividualParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountIndividualParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams"},{"text":" *) ","kind":"text"},{"text":"individual","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"individual","content":[{"type":"paragraph","inlineContent":[{"text":"Information about the person represented by the account","type":"text"},{"text":" ","type":"text"},{"text":"This init method cannot change the ","type":"text"},{"code":"tosShownAndAccepted","type":"codeVoice"},{"text":" parameter. Use","type":"text"},{"text":" ","type":"text"},{"code":"initWithTosShownAndAccepted:individual:","type":"codeVoice"},{"text":" instead if you need to do that.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"STPConnectAccountParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title"},{"op":"replace","value":[{"text":"STPConnectAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments"},{"op":"replace","value":[{"text":"STPConnectAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle"},{"op":"replace","value":"initWithIndividual:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(individual:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithIndividual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(individual:)\/fragments"},{"op":"replace","value":"STPConnectAccountIndividualParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/title"},{"op":"replace","value":[{"text":"STPConnectAccountIndividualParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountIndividualParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountIndividualParams\/navigatorTitle"}]}]}