{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted-17zb6","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Boolean indicating that the Terms Of Service were shown to the user &"},{"type":"text","text":" "},{"type":"text","text":"the user accepted them."}],"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tosShownAndAccepted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:14StripePayments23STPConnectAccountParamsC19tosShownAndAcceptedSbSgvp","title":"tosShownAndAccepted"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tosShownAndAccepted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted-17zb6"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/tosShownAndAccepted-17zb6":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted-17zb6","type":"topic","abstract":[{"text":"Boolean indicating that the Terms Of Service were shown to the user &","type":"text"},{"text":" ","type":"text"},{"text":"the user accepted them.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted-17zb6","title":"tosShownAndAccepted","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tosShownAndAccepted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountParams","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","navigatorTitle":[{"text":"STPConnectAccountParams","kind":"identifier"}],"title":"STPConnectAccountParams","type":"topic","abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title","value":"STPConnectAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments","value":[{"text":"STPConnectAccountParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle","value":[{"text":"STPConnectAccountParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}