{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted_objc"},"metadata":{"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams(py)tosShownAndAccepted","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tosShownAndAccepted_objc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"platforms":[],"title":"tosShownAndAccepted_objc","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"tosShownAndAccepted"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(tosShownAndAccepted) ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tosShownAndAccepted_objc","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"abstract":[{"text":"Boolean indicating that the Terms Of Service were shown to the user &","type":"text"},{"text":" ","type":"text"},{"text":"the user accepted them.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted_objc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted_objc"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/tosShownAndAccepted_objc":{"abstract":[{"text":"Boolean indicating that the Terms Of Service were shown to the user &","type":"text"},{"text":" ","type":"text"},{"text":"the user accepted them.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted_objc","navigatorTitle":[{"text":"tosShownAndAccepted","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted_objc","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tosShownAndAccepted_objc"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"deprecated":true,"type":"topic","title":"tosShownAndAccepted_objc"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams","abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountParams"}],"type":"topic","title":"STPConnectAccountParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"tosShownAndAccepted","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"tosShownAndAccepted","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"tosShownAndAccepted"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"op":"replace","value":"tosShownAndAccepted","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1tosShownAndAccepted_objc\/title"},{"op":"replace","value":[{"kind":"identifier","text":"tosShownAndAccepted"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1tosShownAndAccepted_objc\/fragments"},{"value":"STPConnectAccountParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title"},{"op":"replace","value":[{"text":"STPConnectAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle"}]}]}