{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"title":"tosShownAndAccepted","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"tosShownAndAccepted","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams(py)tosShownAndAccepted","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"tosShownAndAccepted","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted"]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tosShownAndAccepted"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"abstract":[{"text":"Boolean indicating that the Terms Of Service were shown to the user &","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the user accepted them."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/tosShownAndAccepted":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"tosShownAndAccepted","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted","abstract":[{"type":"text","text":"Boolean indicating that the Terms Of Service were shown to the user &"},{"type":"text","text":" "},{"text":"the user accepted them.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted","title":"tosShownAndAccepted","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tosShownAndAccepted"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams","type":"topic","title":"STPConnectAccountParams","abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountParams","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"tosShownAndAccepted","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"tosShownAndAccepted","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"tosShownAndAccepted"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"tosShownAndAccepted","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1tosShownAndAccepted\/title"},{"value":[{"text":"tosShownAndAccepted","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1tosShownAndAccepted\/fragments"},{"value":"STPConnectAccountParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments","value":[{"text":"STPConnectAccountParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountParams"}]}]}]}