{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextStateCompleted"}],"externalID":"c:@M@StripePayments@E@STPRedirectContextState@STPRedirectContextStateCompleted","modules":[{"name":"StripePayments"}],"title":"STPRedirectContextState.completed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed"}],"role":"symbol","symbolKind":"case","roleHeading":"Case"},"kind":"symbol","abstract":[{"type":"text","text":"Redirect has completed."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/completed","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"completed","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontextstate\/completed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontextstate\/completed"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState":{"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPRedirectContextState"}],"abstract":[{"type":"text","text":"Possible states for the redirect context to be in"}],"url":"\/documentation\/stripepayments\/stpredirectcontextstate","navigatorTitle":[{"text":"STPRedirectContextState","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState","title":"STPRedirectContextState"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/completed":{"navigatorTitle":[{"text":"STPRedirectContextStateCompleted","kind":"identifier"}],"title":"STPRedirectContextState.completed","url":"\/documentation\/stripepayments\/stpredirectcontextstate\/completed","abstract":[{"type":"text","text":"Redirect has completed."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completed"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/completed"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPRedirectContextStateCompleted"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPRedirectContextStateCompleted","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPRedirectContextStateCompleted"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/title","value":"STPRedirectContextState"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/fragments","value":[{"kind":"identifier","text":"STPRedirectContextState"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPRedirectContextState"}]},{"value":"STPRedirectContextStateCompleted","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1completed\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPRedirectContextStateCompleted"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1completed\/fragments"}]}]}