{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontextstate\/init(rawvalue:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/init(rawValue:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Initializer","symbolKind":"init","externalID":"s:14StripePayments23STPRedirectContextStateO8rawValueACSgSi_tcfc","modules":[{"name":"StripePayments"}],"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"role":"symbol"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stpredirectcontextstate\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/init(rawValue:)","kind":"symbol","type":"topic","title":"init(rawValue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState":{"url":"\/documentation\/stripepayments\/stpredirectcontextstate","title":"STPRedirectContextState","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextState"}],"abstract":[{"text":"Possible states for the redirect context to be in","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRedirectContextState","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState"}},"variantOverrides":[{"patch":[{"value":"STPRedirectContextState","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/fragments","value":[{"text":"STPRedirectContextState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/navigatorTitle","op":"replace","value":[{"text":"STPRedirectContextState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}