{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Redirect is in progress.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/inProgress","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"inProgress","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState"]]},"metadata":{"title":"STPRedirectContextState.inProgress","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inProgress"}],"externalID":"c:@M@StripePayments@E@STPRedirectContextState@STPRedirectContextStateInProgress","symbolKind":"case","navigatorTitle":[{"text":"STPRedirectContextStateInProgress","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","role":"symbol"},"variants":[{"paths":["\/documentation\/stripepayments\/stpredirectcontextstate\/inprogress"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontextstate\/inprogress"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/inProgress":{"url":"\/documentation\/stripepayments\/stpredirectcontextstate\/inprogress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/inProgress","role":"symbol","kind":"symbol","abstract":[{"text":"Redirect is in progress.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPRedirectContextStateInProgress","kind":"identifier"}],"title":"STPRedirectContextState.inProgress","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inProgress"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState":{"title":"STPRedirectContextState","abstract":[{"text":"Possible states for the redirect context to be in","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRedirectContextState","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextState"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState","role":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontextstate"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPRedirectContextStateInProgress"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPRedirectContextStateInProgress"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPRedirectContextStateInProgress","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPRedirectContextStateInProgress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1inProgress\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1inProgress\/fragments","op":"replace","value":[{"text":"STPRedirectContextStateInProgress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/title","value":"STPRedirectContextState"},{"value":[{"text":"STPRedirectContextState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/navigatorTitle","value":[{"text":"STPRedirectContextState","kind":"identifier"}]}]}]}