{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState"]]},"metadata":{"title":"STPRedirectContextState.notStarted","roleHeading":"Case","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPRedirectContextStateNotStarted","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPRedirectContextState@STPRedirectContextStateNotStarted","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notStarted"}]},"abstract":[{"text":"Initialized, but redirect not started.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notStarted"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/notStarted","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontextstate\/notstarted"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontextstate\/notstarted"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/notStarted":{"title":"STPRedirectContextState.notStarted","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/notStarted","type":"topic","abstract":[{"text":"Initialized, but redirect not started.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextStateNotStarted"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontextstate\/notstarted","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notStarted"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontextstate","title":"STPRedirectContextState","role":"symbol","abstract":[{"text":"Possible states for the redirect context to be in","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContextState"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextState"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"STPRedirectContextStateNotStarted","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPRedirectContextStateNotStarted","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPRedirectContextStateNotStarted"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1notStarted\/title","value":"STPRedirectContextStateNotStarted"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1notStarted\/fragments","value":[{"kind":"identifier","text":"STPRedirectContextStateNotStarted"}]},{"value":"STPRedirectContextState","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/fragments","op":"replace","value":[{"text":"STPRedirectContextState","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
