{"sections":[],"abstract":[{"type":"codeVoice","code":"authenticationTimeout"},{"text":" is the total time allowed for a user to complete a 3DS2 authentication","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"interaction, in minutes.  This value "},{"type":"emphasis","inlineContent":[{"text":"must","type":"text"}]},{"type":"text","text":" be at least 5 minutes."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 10 minutes."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/authenticationTimeout","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationTimeout"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticationTimeout","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"authenticationTimeout","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings(py)authenticationTimeout","symbolKind":"property","title":"authenticationTimeout","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings\/authenticationtimeout"]},{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings\/authenticationtimeout"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings/authenticationTimeout":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationTimeout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticationTimeout"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings\/authenticationtimeout","title":"authenticationTimeout","abstract":[{"type":"codeVoice","code":"authenticationTimeout"},{"type":"text","text":" is the total time allowed for a user to complete a 3DS2 authentication"},{"text":" ","type":"text"},{"type":"text","text":"interaction, in minutes.  This value "},{"inlineContent":[{"type":"text","text":"must"}],"type":"emphasis"},{"text":" be at least 5 minutes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to 10 minutes."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/authenticationTimeout"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings":{"type":"topic","abstract":[{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"text":" provides customization options for 3DS2 authentication flows in your app.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings","navigatorTitle":[{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}],"role":"symbol","title":"STPThreeDSCustomizationSettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"authenticationTimeout","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"authenticationTimeout"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"authenticationTimeout","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1authenticationTimeout\/title","value":"authenticationTimeout"},{"value":[{"text":"authenticationTimeout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1authenticationTimeout\/fragments"},{"value":"STPThreeDSCustomizationSettings","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/title"},{"op":"replace","value":[{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/fragments"},{"value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}