{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings","text":"STPThreeDSCustomizationSettings"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings\/defaultsettings()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings\/defaultsettings()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/defaultSettings()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns an "},{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"type":"text","text":" preconfigured with the default"},{"type":"text","text":" "},{"type":"text","text":"Stripe UI settings and a 10 minute "},{"type":"codeVoice","code":"authenticationTimeout"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"defaultSettings"}],"role":"symbol","title":"defaultSettings()","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"STPThreeDSCustomizationSettings","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings"}],"symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings(cm)defaultSettings","modules":[{"name":"StripePayments"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use STPThreeDSCustomizationSettings() instead of STPThreeDSCustomizationSettings.defaultSettings()."}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings":{"role":"symbol","title":"STPThreeDSCustomizationSettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"abstract":[{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"type":"text","text":" provides customization options for 3DS2 authentication flows in your app."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings/defaultSettings()":{"deprecated":false,"role":"symbol","title":"defaultSettings()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"STPThreeDSCustomizationSettings","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings"}],"abstract":[{"type":"text","text":"Returns an "},{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"type":"text","text":" preconfigured with the default"},{"type":"text","text":" "},{"type":"text","text":"Stripe UI settings and a 10 minute "},{"type":"codeVoice","code":"authenticationTimeout"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/defaultSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultSettings"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings\/defaultsettings()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"defaultSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings","text":"STPThreeDSCustomizationSettings"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/title","value":"STPThreeDSCustomizationSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1defaultSettings()\/title","value":"defaultSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1defaultSettings()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
