{"metadata":{"symbolKind":"method","title":"init","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings(im)init"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/init","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings\/init","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/init","role":"symbol","kind":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings":{"type":"topic","title":"STPThreeDSCustomizationSettings","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings","url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"type":"text","text":" provides customization options for 3DS2 authentication flows in your app."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPThreeDSCustomizationSettings","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/title"},{"value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/fragments"},{"value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/navigatorTitle"}]}]}