{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/uiCustomization","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"codeVoice","code":"uiCustomization"},{"type":"text","text":" can be used to provide custom UI settings for the authentication"},{"type":"text","text":" "},{"text":"challenge screens presented during a Three Domain Secure authentication. For more information see","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"our guide on supporting 3DS2 in your iOS application."},{"text":" ","type":"text"},{"text":"Note: It’s important to configure this object appropriately before calling any ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" APIs.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"text":" ","type":"text"},{"text":"make to your ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"text":" instance.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization.defaultSettings()"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"uiCustomization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","text":"STPThreeDSUICustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings\/uicustomization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings\/uicustomization"]}],"metadata":{"title":"uiCustomization","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"uiCustomization"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings(py)uiCustomization","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"uiCustomization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPThreeDSUICustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSUICustomization","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"type":"text","text":" "},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" APIs."},{"type":"text","text":" "},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"type":"text","text":" "},{"type":"text","text":"make to your "},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"text":" instance.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","title":"STPThreeDSUICustomization","type":"topic","role":"symbol","navigatorTitle":[{"text":"STPThreeDSUICustomization","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings":{"role":"symbol","url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"navigatorTitle":[{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}],"abstract":[{"code":"STPThreeDSCustomizationSettings","type":"codeVoice"},{"text":" provides customization options for 3DS2 authentication flows in your app.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings","title":"STPThreeDSCustomizationSettings","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings/uiCustomization":{"title":"uiCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/uiCustomization","url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings\/uicustomization","abstract":[{"type":"codeVoice","code":"uiCustomization"},{"text":" can be used to provide custom UI settings for the authentication","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"challenge screens presented during a Three Domain Secure authentication. For more information see"},{"type":"text","text":" "},{"type":"text","text":"our guide on supporting 3DS2 in your iOS application."},{"type":"text","text":" "},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" APIs."},{"text":" ","type":"text"},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"text":" ","type":"text"},{"type":"text","text":"make to your "},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"type":"text","text":" instance."},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization.defaultSettings()"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"uiCustomization","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uiCustomization"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization","kind":"typeIdentifier","text":"STPThreeDSUICustomization"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"uiCustomization","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"uiCustomization"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization","text":"STPThreeDSUICustomization"},{"kind":"text","text":" * "},{"text":"uiCustomization","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","value":"STPThreeDSUICustomization","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}]},{"value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/title","value":"STPThreeDSCustomizationSettings"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/fragments","value":[{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1uiCustomization\/title","op":"replace","value":"uiCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1uiCustomization\/fragments","op":"replace","value":[{"text":"uiCustomization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}