{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAfter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAfter"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"expiresAfter"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","title":"expiresAfter","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionOXXODisplayDetails(py)expiresAfter"},"kind":"symbol","abstract":[{"type":"text","text":"The timestamp after which the OXXO voucher expires."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/expiresafter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/expiresafter"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/expiresAfter"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails/expiresAfter":{"abstract":[{"type":"text","text":"The timestamp after which the OXXO voucher expires."}],"role":"symbol","kind":"symbol","title":"expiresAfter","navigatorTitle":[{"kind":"identifier","text":"expiresAfter"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAfter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/expiresafter","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/expiresAfter"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionOXXODisplayDetails"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionOXXODisplayDetails"}],"abstract":[{"type":"text","text":"Contains OXXO details necessary for the customer to complete the payment."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails","type":"topic","title":"STPIntentActionOXXODisplayDetails","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"expiresAfter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"expiresAfter"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDate","preciseIdentifier":"c:objc(cs)NSDate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"expiresAfter","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1expiresAfter\/title","op":"replace","value":"expiresAfter"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1expiresAfter\/fragments","op":"replace","value":[{"kind":"identifier","text":"expiresAfter"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/title","op":"replace","value":"STPIntentActionOXXODisplayDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionOXXODisplayDetails"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionOXXODisplayDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}