{"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"number"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"number","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPIntentActionOXXODisplayDetails(py)number","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"number","symbolKind":"property","role":"symbol"},"abstract":[{"text":"OXXO reference number.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"number","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/number","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/number"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/number"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails":{"url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionOXXODisplayDetails"}],"kind":"symbol","abstract":[{"text":"Contains OXXO details necessary for the customer to complete the payment.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails","title":"STPIntentActionOXXODisplayDetails","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails/number":{"abstract":[{"type":"text","text":"OXXO reference number."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"number","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/number","title":"number","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"number"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/number"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"number","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"number","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"number"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/title","value":"STPIntentActionOXXODisplayDetails","op":"replace"},{"op":"replace","value":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionOXXODisplayDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1number\/title","op":"replace","value":"number"},{"value":[{"text":"number","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1number\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}