{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountReceived"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"amountReceived"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcereceiver\/amountreceived"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcereceiver\/amountreceived"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The total amount received by the receiver source.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPSourceReceiver(py)amountReceived","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"amountReceived","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"amountReceived","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"amountReceived"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceReceiver","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information related to a source’s receiver flow.","type":"text"}],"title":"STPSourceReceiver","role":"symbol","url":"\/documentation\/stripepayments\/stpsourcereceiver","navigatorTitle":[{"kind":"identifier","text":"STPSourceReceiver"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver/amountReceived":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountReceived","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amountReceived","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"amountReceived","abstract":[{"text":"The total amount received by the receiver source.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourcereceiver\/amountreceived","navigatorTitle":[{"kind":"identifier","text":"amountReceived"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"amountReceived","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"amountReceived","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"text":"amountReceived","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"STPSourceReceiver","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver\/fragments","value":[{"kind":"identifier","text":"STPSourceReceiver"}]},{"value":[{"kind":"identifier","text":"STPSourceReceiver"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1amountReceived\/title","value":"amountReceived","op":"replace"},{"value":[{"kind":"identifier","text":"amountReceived"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1amountReceived\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}