{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authorizeWithURL"}],"platforms":[],"role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentIntentSourceActionType@STPPaymentIntentSourceActionTypeAuthorizeWithURL","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"STPPaymentIntentSourceActionTypeAuthorizeWithURL","kind":"identifier"}],"title":"STPPaymentIntentSourceActionType.authorizeWithURL","modules":[{"name":"StripePayments"}]},"deprecationSummary":[{"inlineContent":[{"text":"Use STPIntentActionType instead","type":"text"}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/authorizeWithURL","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"authorizeWithURL","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/authorizewithurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/authorizewithurl"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The payment intent needs to be authorized by the user. We provide","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPRedirectContext"},{"type":"text","text":" to handle the url redirections necessary."}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/authorizeWithURL":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"authorizeWithURL","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/authorizewithurl","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/authorizeWithURL","role":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSourceActionTypeAuthorizeWithURL"}],"kind":"symbol","title":"STPPaymentIntentSourceActionType.authorizeWithURL","type":"topic","abstract":[{"type":"text","text":"The payment intent needs to be authorized by the user. We provide"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPRedirectContext"},{"type":"text","text":" to handle the url redirections necessary."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType":{"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","title":"STPPaymentIntentSourceActionType","abstract":[{"type":"text","text":"Types of Source Actions from a "},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":", when the payment intent","type":"text"},{"type":"text","text":" "},{"text":"status is ","type":"text"},{"code":"STPPaymentIntentStatusRequiresSourceAction","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentIntentSourceActionTypeAuthorizeWithURL"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentSourceActionTypeAuthorizeWithURL","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPPaymentIntentSourceActionTypeAuthorizeWithURL","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType~1authorizeWithURL\/title","value":"STPPaymentIntentSourceActionTypeAuthorizeWithURL","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionTypeAuthorizeWithURL"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType~1authorizeWithURL\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/title","value":"STPPaymentIntentSourceActionType"},{"value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}