{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/CustomStringConvertible-Implementations"]]},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/description"]}],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"s:14StripePayments32STPPaymentIntentSourceActionTypeO11descriptionSSvp","platforms":[],"extendedModule":"StripePayments","title":"description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/description","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use STPIntentActionType instead"}],"type":"paragraph"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType":{"type":"topic","title":"STPPaymentIntentSourceActionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype","kind":"symbol","abstract":[{"text":"Types of Source Actions from a ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"type":"text","text":", when the payment intent"},{"type":"text","text":" "},{"text":"status is ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresSourceAction"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/description":{"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/description","deprecated":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"title":"description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/description","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/CustomStringConvertible-Implementations":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/CustomStringConvertible-Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/title","value":"STPPaymentIntentSourceActionType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/fragments","op":"replace","value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"op":"replace"}]}]}