{"kind":"article","metadata":{"title":"Equatable Implementations","modules":[{"name":"StripePayments"}],"roleHeading":"API Collection","role":"collectionGroup"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType"]]},"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/!=(_:_:)"],"generated":true,"title":"Operators"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/equatable-implementations"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","kind":"symbol","title":"STPPaymentIntentSourceActionType","type":"topic","abstract":[{"text":"Types of Source Actions from a ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":", when the payment intent"},{"text":" ","type":"text"},{"type":"text","text":"status is "},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresSourceAction"},{"text":".","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/!=(_:_:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/!=(_:_:)","role":"symbol","type":"topic","abstract":[],"title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntentSourceActionType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/fragments","op":"replace","value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}]}]}]}