{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/hashValue","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/RawRepresentable-Implementations"]]},"metadata":{"extendedModule":"Swift","roleHeading":"Instance Property","title":"hashValue","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@StripePayments@E@STPPaymentIntentSourceActionType","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"modules":[{"name":"StripePayments","relatedModules":["Swift"]}]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/hashvalue"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","title":"STPPaymentIntentSourceActionType","abstract":[{"type":"text","text":"Types of Source Actions from a "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":", when the payment intent"},{"type":"text","text":" "},{"text":"status is ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresSourceAction"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype","type":"topic","deprecated":true,"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/RawRepresentable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/hashValue":{"type":"topic","title":"hashValue","kind":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/hashvalue","abstract":[],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/hashValue"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntentSourceActionType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/title"},{"op":"replace","value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"op":"replace"}]}]}