{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/init(rawvalue:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/init(rawValue:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":[],"externalID":"s:14StripePayments32STPPaymentIntentSourceActionTypeO8rawValueACSgSi_tcfc","title":"init(rawValue:)","symbolKind":"init","role":"symbol","roleHeading":"Initializer"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use STPIntentActionType instead","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/init(rawValue:)","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/init(rawvalue:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"deprecated":true,"title":"STPPaymentIntentSourceActionType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","abstract":[{"text":"Types of Source Actions from a ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"text":", when the payment intent","type":"text"},{"text":" ","type":"text"},{"text":"status is ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresSourceAction"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPPaymentIntentSourceActionType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/title"},{"op":"replace","value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}]}]}]}