{"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"platforms":[],"role":"symbol","title":"STPPaymentIntentSourceActionType.unknown","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSourceActionTypeUnknown"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentSourceActionType@STPPaymentIntentSourceActionTypeUnknown","roleHeading":"Case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/unknown"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/unknown","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"This is an unknown source action, that’s been added since the SDK"},{"text":" ","type":"text"},{"type":"text","text":"was last updated."},{"text":" ","type":"text"},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"nextSourceAction.allResponseFields"},{"type":"text","text":" "},{"text":"for custom handling.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType"]]},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use STPIntentActionType instead"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType":{"abstract":[{"text":"Types of Source Actions from a ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":", when the payment intent"},{"text":" ","type":"text"},{"type":"text","text":"status is "},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresSourceAction"},{"type":"text","text":"."}],"title":"STPPaymentIntentSourceActionType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype","kind":"symbol","role":"symbol","deprecated":true,"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"navigatorTitle":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/unknown":{"deprecated":true,"abstract":[{"type":"text","text":"This is an unknown source action, that’s been added since the SDK"},{"type":"text","text":" "},{"text":"was last updated.","type":"text"},{"type":"text","text":" "},{"text":"Update your SDK, or use the ","type":"text"},{"code":"nextSourceAction.allResponseFields","type":"codeVoice"},{"type":"text","text":" "},{"text":"for custom handling.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/unknown","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentSourceActionTypeUnknown","kind":"identifier"}],"title":"STPPaymentIntentSourceActionType.unknown","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/unknown","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPPaymentIntentSourceActionTypeUnknown","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"STPPaymentIntentSourceActionTypeUnknown","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPPaymentIntentSourceActionTypeUnknown","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"STPPaymentIntentSourceActionType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/title"},{"value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/fragments"},{"value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType~1unknown\/title","value":"STPPaymentIntentSourceActionTypeUnknown","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType~1unknown\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionTypeUnknown"}]}]}]}