{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFailToLoadWithError:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"paymentContext","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","text":"STPPaymentContext"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToLoadWithError"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"paymentContext","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the payment context that encountered the error"}]}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"the error that was encountered"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you’re showing the user a checkout page, dismiss the checkout page when this is called and present the error to the user."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Present the error to the user using a "},{"type":"codeVoice","code":"UIAlertController"},{"text":" with two buttons: Retry and Cancel. If they cancel, dismiss your UI. If they Retry, call ","type":"text"},{"type":"codeVoice","code":"retryLoading"},{"text":" on the payment context.","type":"text"},{"type":"text","text":" "},{"text":"To make it harder to get your UI into a bad state, this won’t be called until the context’s ","type":"text"},{"code":"hostViewController","type":"codeVoice"},{"type":"text","text":" has finished appearing."}]}]}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Called when the payment context encounters an error when fetching its initial set of data. A few ways to handle this are:"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didfailtoloadwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didfailtoloadwitherror:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate"]]},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"Stripe"}],"title":"paymentContext(_:didFailToLoadWithError:)","symbolKind":"method","required":true,"externalID":"c:@M@Stripe@objc(pl)STPPaymentContextDelegate(im)paymentContext:didFailToLoadWithError:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentContext"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"text":", ","kind":"text"},{"text":"didFailToLoadWithError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paymentContext:didFailToLoadWithError:","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate":{"url":"\/documentation\/stripe\/stppaymentcontextdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentContextDelegate","kind":"identifier"}],"abstract":[{"text":"Implement ","type":"text"},{"type":"codeVoice","code":"STPPaymentContextDelegate"},{"type":"text","text":" to get notified when a payment context changes, finishes, encounters errors, etc. In practice, if your app has a “checkout screen view controller”, that is a good candidate to implement this protocol."}],"type":"topic","kind":"symbol","title":"STPPaymentContextDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContextDelegate"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContext(_:didFailToLoadWithError:)":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didfailtoloadwitherror:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFailToLoadWithError:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFailToLoadWithError"},{"kind":"text","text":": "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"paymentContext:didFailToLoadWithError:"}],"type":"topic","abstract":[{"type":"text","text":"Called when the payment context encounters an error when fetching its initial set of data. A few ways to handle this are:"}],"title":"paymentContext(_:didFailToLoadWithError:)","required":true,"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"type":"topic","title":"STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and modifying the customer.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"paymentContext:didFailToLoadWithError:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentContext:didFailToLoadWithError:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"paymentContext:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"typeIdentifier","text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"kind":"text","text":" *) "},{"text":"paymentContext","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didFailToLoadWithError:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"STPPaymentContextDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentContextDelegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didFailToLoadWithError:)\/title","op":"replace","value":"paymentContext:didFailToLoadWithError:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didFailToLoadWithError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentContext:didFailToLoadWithError:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"text":"STPPaymentContext","kind":"identifier"}],"op":"replace"}]}]}
