{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentContext"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"kind":"text","text":" "},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentStatus","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"paymentContext","content":[{"inlineContent":[{"type":"text","text":"The payment context that finished"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The status of the payment - "},{"code":"STPPaymentStatusSuccess","type":"codeVoice"},{"type":"text","text":" if it succeeded, "},{"type":"codeVoice","code":"STPPaymentStatusError"},{"text":" if it failed with an error (in which case the ","type":"text"},{"type":"codeVoice","code":"error"},{"type":"text","text":" parameter will be non-nil), "},{"code":"STPPaymentStatusUserCancellation","type":"codeVoice"},{"type":"text","text":" if the user canceled the payment."}]}],"name":"status"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"An error that occurred, if any.","type":"text"}]}]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@Stripe@objc(pl)STPPaymentContextDelegate(im)paymentContext:didFinishWith:error:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","text":"STPPaymentContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishWith","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus","text":"STPPaymentStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"title":"paymentContext(_:didFinishWith:error:)","roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"symbolKind":"method","required":true,"navigatorTitle":[{"text":"paymentContext:didFinishWith:error:","kind":"identifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"This is invoked by an "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" when it is finished. This will be called after the payment is done and all necessary UI has been dismissed. You should inspect the returned "},{"type":"codeVoice","code":"status"},{"type":"text","text":" and behave appropriately. For example: if it’s "},{"code":"STPPaymentStatusSuccess","type":"codeVoice"},{"type":"text","text":", show the user a receipt. If it’s "},{"type":"codeVoice","code":"STPPaymentStatusError"},{"text":", inform the user of the error. If it’s ","type":"text"},{"code":"STPPaymentStatusUserCancellation","type":"codeVoice"},{"text":", do nothing.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFinishWith:error:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didfinishwith:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didfinishwith:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate":{"url":"\/documentation\/stripe\/stppaymentcontextdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentContextDelegate","kind":"identifier"}],"abstract":[{"text":"Implement ","type":"text"},{"type":"codeVoice","code":"STPPaymentContextDelegate"},{"type":"text","text":" to get notified when a payment context changes, finishes, encounters errors, etc. In practice, if your app has a “checkout screen view controller”, that is a good candidate to implement this protocol."}],"type":"topic","kind":"symbol","title":"STPPaymentContextDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContextDelegate"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContext(_:didFinishWith:error:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"paymentContext:didFinishWith:error:","kind":"identifier"}],"abstract":[{"text":"This is invoked by an ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" when it is finished. This will be called after the payment is done and all necessary UI has been dismissed. You should inspect the returned "},{"code":"status","type":"codeVoice"},{"text":" and behave appropriately. For example: if it’s ","type":"text"},{"code":"STPPaymentStatusSuccess","type":"codeVoice"},{"type":"text","text":", show the user a receipt. If it’s "},{"code":"STPPaymentStatusError","type":"codeVoice"},{"type":"text","text":", inform the user of the error. If it’s "},{"code":"STPPaymentStatusUserCancellation","type":"codeVoice"},{"type":"text","text":", do nothing."}],"type":"topic","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","text":"STPPaymentContext"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishWith"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus","text":"STPPaymentStatus","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didFinishWith:error:)","title":"paymentContext(_:didFinishWith:error:)","url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didfinishwith:error:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"type":"topic","title":"STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and modifying the customer.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentStatus":{"abstract":[{"text":"An enum representing the status of a payment requested from the user.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentStatus","kind":"identifier"}],"title":"STPPaymentStatus","type":"topic","kind":"symbol","navigatorTitle":[{"text":"STPPaymentStatus","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentstatus","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"paymentContext:didFinishWith:error:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentContext:didFinishWith:error:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"paymentContext:"},{"text":"(","kind":"text"},{"text":"STPPaymentContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"kind":"text","text":" *) "},{"text":"paymentContext","kind":"internalParam"},{"kind":"text","text":" "},{"text":"didFinishWith:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentStatus","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"STPPaymentContextDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/fragments","value":[{"text":"STPPaymentContextDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didFinishWith:error:)\/title","value":"paymentContext:didFinishWith:error:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentContext:didFinishWith:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didFinishWith:error:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","value":"STPPaymentContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"kind":"identifier","text":"STPPaymentContext"}]}]}]}
