{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didUpdateShippingAddress:completion:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate"]]},"metadata":{"title":"paymentContext(_:didUpdateShippingAddress:completion:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateShippingAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"text":")","kind":"text"}],"externalID":"c:@M@Stripe@objc(pl)STPPaymentContextDelegate(im)paymentContext:didUpdateShippingAddress:completion:","navigatorTitle":[{"kind":"identifier","text":"paymentContext:didUpdateShippingAddress:completion:"}],"role":"symbol","required":true,"modules":[{"name":"Stripe"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didupdateshippingaddress:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didupdateshippingaddress:completion:)"]}],"kind":"symbol","abstract":[{"text":"Inside this method, you should verify that you can ship to the given address.","type":"text"},{"text":" ","type":"text"},{"text":"You should call the completion block with the results of your validation","type":"text"},{"text":" ","type":"text"},{"text":"and the available shipping methods for the given address. If you don’t implement","type":"text"},{"type":"text","text":" "},{"type":"text","text":"this method, the user won’t be prompted to select a shipping method and all"},{"type":"text","text":" "},{"type":"text","text":"addresses will be valid. If you call the completion block with nil or an"},{"type":"text","text":" "},{"text":"empty array of shipping methods, the user won’t be prompted to select a","type":"text"},{"type":"text","text":" "},{"text":"shipping method.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","text":"STPPaymentContext"},{"text":", ","kind":"text"},{"text":"didUpdateShippingAddress","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"address"},{"text":": ","kind":"text"},{"text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingMethodsCompletionBlock","text":"STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context that updated its shipping address"}]}],"name":"paymentContext"},{"name":"address","content":[{"type":"paragraph","inlineContent":[{"text":"The current shipping address","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Call this block when you’re done validating the shipping","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"address and calculating available shipping methods. If you call the completion"},{"text":" ","type":"text"},{"text":"block with nil or an empty array of shipping methods, the user won’t be prompted","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to select a shipping method."}]}],"name":"completion"}],"kind":"parameters"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"this address will be anonymized. For example, in the US, it will only include the","type":"text"},{"text":" ","type":"text"},{"text":"city, state, and zip code. The payment context will have the user’s complete","type":"text"},{"type":"text","text":" "},{"type":"text","text":"shipping address by the time "},{"type":"codeVoice","code":"paymentContext:didFinishWithStatus:error"},{"type":"text","text":" is"},{"type":"text","text":" "},{"type":"text","text":"called."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"type":"topic","title":"STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and modifying the customer.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"url":"\/documentation\/stripe\/stpaddress","role":"symbol","title":"STPAddress","type":"topic","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContext(_:didUpdateShippingAddress:completion:)":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didupdateshippingaddress:completion:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didUpdateShippingAddress:completion:)","title":"paymentContext(_:didUpdateShippingAddress:completion:)","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"text":", ","kind":"text"},{"text":"didUpdateShippingAddress","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","text":"STPAddress"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPShippingMethodsCompletionBlock","preciseIdentifier":"s:6Stripe33STPShippingMethodsCompletionBlocka"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"Inside this method, you should verify that you can ship to the given address.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You should call the completion block with the results of your validation"},{"type":"text","text":" "},{"type":"text","text":"and the available shipping methods for the given address. If you don’t implement"},{"text":" ","type":"text"},{"type":"text","text":"this method, the user won’t be prompted to select a shipping method and all"},{"type":"text","text":" "},{"type":"text","text":"addresses will be valid. If you call the completion block with nil or an"},{"type":"text","text":" "},{"type":"text","text":"empty array of shipping methods, the user won’t be prompted to select a"},{"type":"text","text":" "},{"type":"text","text":"shipping method."}],"navigatorTitle":[{"kind":"identifier","text":"paymentContext:didUpdateShippingAddress:completion:"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingMethodsCompletionBlock":{"role":"symbol","url":"\/documentation\/stripe\/stpshippingmethodscompletionblock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingMethodsCompletionBlock","title":"STPShippingMethodsCompletionBlock","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"STPShippingMethodsCompletionBlock","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A callback to be run with a validation result and shipping methods for a"},{"type":"text","text":" "},{"type":"text","text":"shipping address."}],"navigatorTitle":[{"text":"STPShippingMethodsCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate":{"url":"\/documentation\/stripe\/stppaymentcontextdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentContextDelegate","kind":"identifier"}],"abstract":[{"text":"Implement ","type":"text"},{"type":"codeVoice","code":"STPPaymentContextDelegate"},{"type":"text","text":" to get notified when a payment context changes, finishes, encounters errors, etc. In practice, if your app has a “checkout screen view controller”, that is a good candidate to implement this protocol."}],"type":"topic","kind":"symbol","title":"STPPaymentContextDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContextDelegate"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"paymentContext:didUpdateShippingAddress:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentContext:didUpdateShippingAddress:completion:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"paymentContext:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","text":"STPPaymentContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentContext"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didUpdateShippingAddress:"},{"kind":"text","text":"("},{"text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"},{"text":" *) ","kind":"text"},{"text":"address","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(enum STPShippingStatus, NSError *, NSArray<PKShippingMethod *> *, PKShippingMethod *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#$@M@Stripe@E@STPShippingStatus#*$objc(cs)NSError#*Q$objc(cs)NSArray#*$objc(cs)PKShippingMethod)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title","op":"replace","value":"STPPaymentContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","op":"replace","value":[{"text":"STPPaymentContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didUpdateShippingAddress:completion:)\/title","value":"paymentContext:didUpdateShippingAddress:completion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"paymentContext:didUpdateShippingAddress:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didUpdateShippingAddress:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/title","value":"STPPaymentContextDelegate"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/fragments","value":[{"text":"STPPaymentContextDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
