{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"paymentContext"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","text":"STPPaymentContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCreatePaymentResult"},{"text":" ","kind":"text"},{"text":"paymentResult","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentResult","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentResult"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"STPPaymentStatusBlock","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentStatusBlock","preciseIdentifier":"s:14StripePayments21STPPaymentStatusBlocka"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The context that succeeded"}],"type":"paragraph"}],"name":"paymentContext"},{"name":"paymentResult","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Information associated with the payment that you can pass to your server. You should go to your backend API with this payment result and use the PaymentIntent API to complete the payment. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#submit-payment-intents Once that’s done call the "},{"code":"completion","type":"codeVoice"},{"text":" block with any error that occurred (or none, if the payment succeeded). - seealso: STPPaymentResult.h","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this block when you’re done creating a payment intent (or subscription, etc) on your backend. If it succeeded, call "},{"code":"completion(STPPaymentStatusSuccess, nil)","type":"codeVoice"},{"type":"text","text":". If it failed with an error, call "},{"type":"codeVoice","code":"completion(STPPaymentStatusError, error)"},{"text":". If the user canceled, call ","type":"text"},{"type":"codeVoice","code":"completion(STPPaymentStatusUserCancellation, nil)"},{"type":"text","text":"."}]}],"name":"completion"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didcreatepaymentresult:completion:)"]},{"paths":["\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didcreatepaymentresult:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Inside this method, you should make a call to your backend API to make a PaymentIntent with that Customer + payment method, and invoke the ","type":"text"},{"code":"completion","type":"codeVoice"},{"text":" block when that is done.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"title":"paymentContext(_:didCreatePaymentResult:completion:)","navigatorTitle":[{"text":"paymentContext:didCreatePaymentResult:completion:","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(pl)STPPaymentContextDelegate(im)paymentContext:didCreatePaymentResult:completion:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext"},{"text":", ","kind":"text"},{"text":"didCreatePaymentResult","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentResult","text":"STPPaymentResult"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments21STPPaymentStatusBlocka","text":"STPPaymentStatusBlock"},{"text":")","kind":"text"}],"modules":[{"name":"Stripe"}]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didCreatePaymentResult:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate":{"url":"\/documentation\/stripe\/stppaymentcontextdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentContextDelegate","kind":"identifier"}],"abstract":[{"text":"Implement ","type":"text"},{"type":"codeVoice","code":"STPPaymentContextDelegate"},{"type":"text","text":" to get notified when a payment context changes, finishes, encounters errors, etc. In practice, if your app has a “checkout screen view controller”, that is a good candidate to implement this protocol."}],"type":"topic","kind":"symbol","title":"STPPaymentContextDelegate","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentContextDelegate"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContext":{"role":"symbol","url":"\/documentation\/stripe\/stppaymentcontext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentContext","kind":"identifier"}],"type":"topic","title":"STPPaymentContext","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" keeps track of all of the state around a payment. It will manage fetching a user’s saved payment methods, tracking any information they select, and prompting them for required additional information before completing their purchase. It can be used to power your application’s “payment confirmation” page with just a few lines of code."},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"text":" also provides a unified interface to multiple payment methods - for example, you can write a single integration to accept both credit card payments and Apple Pay.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" saves information about a user’s payment methods to a Stripe customer object, and requires an "},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and modifying the customer.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentStatusBlock":{"url":"\/documentation\/stripe\/stppaymentstatusblock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentStatusBlock"}],"abstract":[{"text":"A block called with a payment status and an optional error.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentStatusBlock","kind":"symbol","title":"STPPaymentStatusBlock","navigatorTitle":[{"text":"STPPaymentStatusBlock","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentContextDelegate/paymentContext(_:didCreatePaymentResult:completion:)":{"url":"\/documentation\/stripe\/stppaymentcontextdelegate\/paymentcontext(_:didcreatepaymentresult:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentContext","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","text":"STPPaymentContext"},{"text":", ","kind":"text"},{"text":"didCreatePaymentResult","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentResult"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentStatusBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments21STPPaymentStatusBlocka"},{"text":")","kind":"text"}],"abstract":[{"text":"Inside this method, you should make a call to your backend API to make a PaymentIntent with that Customer + payment method, and invoke the ","type":"text"},{"code":"completion","type":"codeVoice"},{"type":"text","text":" block when that is done."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContextDelegate\/paymentContext(_:didCreatePaymentResult:completion:)","kind":"symbol","title":"paymentContext(_:didCreatePaymentResult:completion:)","required":true,"navigatorTitle":[{"text":"paymentContext:didCreatePaymentResult:completion:","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentResult"}],"kind":"symbol","url":"\/documentation\/stripe\/stppaymentresult","title":"STPPaymentResult","role":"symbol","abstract":[{"type":"text","text":"When you’re using "},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" to request your user’s payment details, this is the object that will be returned to your application when they’ve successfully made a payment."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#submit-payment-intents"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"paymentContext:didCreatePaymentResult:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentContext:didCreatePaymentResult:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"paymentContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentContext","kind":"typeIdentifier","text":"STPPaymentContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentContext"},{"kind":"text","text":" "},{"kind":"identifier","text":"didCreatePaymentResult:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentResult","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentResult","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentResult"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#$@M@StripePayments@E@STPPaymentStatus#*$objc(cs)NSError)","text":"void (^)(enum STPPaymentStatus, NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentContextDelegate","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate\/fragments","value":[{"text":"STPPaymentContextDelegate","kind":"identifier"}],"op":"replace"},{"value":"STPPaymentContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContext\/fragments","value":[{"text":"STPPaymentContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didCreatePaymentResult:completion:)\/title","value":"paymentContext:didCreatePaymentResult:completion:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentContextDelegate~1paymentContext(_:didCreatePaymentResult:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentContext:didCreatePaymentResult:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/title","value":"STPPaymentResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentResult\/fragments","value":[{"text":"STPPaymentResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
