{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType"]]},"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeCompany"}],"title":"STPPaymentMethodUSBankAccountHolderType.company","externalID":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType@STPPaymentMethodUSBankAccountHolderTypeCompany","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"company"}],"role":"symbol","modules":[{"name":"StripePayments"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/company"},"abstract":[{"type":"text","text":"Account belongs to a company"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/company"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/company"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"company","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/company":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeCompany"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/company","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/company","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Account belongs to a company"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"company"}],"type":"topic","title":"STPPaymentMethodUSBankAccountHolderType.company"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType":{"type":"topic","abstract":[{"text":"Account holder type","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"title":"STPPaymentMethodUSBankAccountHolderType","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentMethodUSBankAccountHolderTypeCompany","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountHolderTypeCompany","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeCompany"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1company\/title","value":"STPPaymentMethodUSBankAccountHolderTypeCompany","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1company\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeCompany"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/title","value":"STPPaymentMethodUSBankAccountHolderType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"op":"replace"}]}]}