{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/CustomStringConvertible-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/description"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"s:14StripePayments39STPPaymentMethodUSBankAccountHolderTypeO11descriptionSSvp","modules":[{"name":"StripePayments"}],"title":"description","roleHeading":"Instance Property","role":"symbol","extendedModule":"StripePayments","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype","title":"STPPaymentMethodUSBankAccountHolderType","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"abstract":[{"type":"text","text":"Account holder type"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/description":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/description","title":"description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/customstringconvertible-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"STPPaymentMethodUSBankAccountHolderType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}