{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/individual"},"metadata":{"role":"symbol","title":"STPPaymentMethodUSBankAccountHolderType.individual","modules":[{"name":"StripePayments"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"individual"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType@STPPaymentMethodUSBankAccountHolderTypeIndividual","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeIndividual"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"individual"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/individual"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/individual"]}],"abstract":[{"text":"Account belongs to an individual","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/individual":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/individual","type":"topic","kind":"symbol","role":"symbol","title":"STPPaymentMethodUSBankAccountHolderType.individual","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"individual","kind":"identifier"}],"abstract":[{"text":"Account belongs to an individual","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderTypeIndividual","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/individual"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType":{"type":"topic","abstract":[{"type":"text","text":"Account holder type"}],"title":"STPPaymentMethodUSBankAccountHolderType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodUSBankAccountHolderTypeIndividual"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeIndividual"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"STPPaymentMethodUSBankAccountHolderTypeIndividual","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1individual\/title","value":"STPPaymentMethodUSBankAccountHolderTypeIndividual"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1individual\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeIndividual"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/title","value":"STPPaymentMethodUSBankAccountHolderType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}]}]}]}