{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/unknown"]}],"abstract":[{"type":"text","text":"This is an unknown type that’s been added since the SDK"},{"type":"text","text":" "},{"type":"text","text":"was last updated."},{"type":"text","text":" "},{"type":"text","text":"Update your SDK, or use the "},{"code":"allResponseFields","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"for custom handling."}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"symbolKind":"case","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType@STPPaymentMethodUSBankAccountHolderTypeUnknown","title":"STPPaymentMethodUSBankAccountHolderType.unknown","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderTypeUnknown","kind":"identifier"}],"roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/unknown"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype","title":"STPPaymentMethodUSBankAccountHolderType","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"abstract":[{"text":"Account holder type","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/unknown":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/unknown","title":"STPPaymentMethodUSBankAccountHolderType.unknown","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderTypeUnknown","kind":"identifier"}],"abstract":[{"text":"This is an unknown type that’s been added since the SDK","type":"text"},{"text":" ","type":"text"},{"text":"was last updated.","type":"text"},{"text":" ","type":"text"},{"text":"Update your SDK, or use the ","type":"text"},{"type":"codeVoice","code":"allResponseFields"},{"text":" ","type":"text"},{"text":"for custom handling.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodUSBankAccountHolderTypeUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountHolderTypeUnknown","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"STPPaymentMethodUSBankAccountHolderTypeUnknown","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/title","value":"STPPaymentMethodUSBankAccountHolderType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1unknown\/title","value":"STPPaymentMethodUSBankAccountHolderTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1unknown\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountHolderTypeUnknown","kind":"identifier"}]}]}]}