{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/allResponseFields","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPIntentActionPayNowDisplayQrCode(py)allResponseFields","symbolKind":"property","title":"allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/allresponsefields"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/allresponsefields"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode/allResponseFields":{"abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"allResponseFields","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/allresponsefields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/allResponseFields"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}],"title":"STPIntentActionPayNowDisplayQrCode","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}],"kind":"symbol","abstract":[{"text":"Contains instructions for presenting the QR code required to complete a PayNow payment.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentActionPayNowDisplayQrCode","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"allResponseFields"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"allResponseFields","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"kind":"text","text":" * "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1allResponseFields\/title","op":"replace","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/title","value":"STPIntentActionPayNowDisplayQrCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/fragments","value":[{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/navigatorTitle","value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}