{"metadata":{"title":"hostedInstructionsURL","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"hostedInstructionsURL","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionPayNowDisplayQrCode(py)hostedInstructionsURL","navigatorTitle":[{"text":"hostedInstructionsURL","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/hostedinstructionsurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/hostedinstructionsurl"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The URL to open which contains instructions on how to complete the payment.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/hostedInstructionsURL"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hostedInstructionsURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode/hostedInstructionsURL":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hostedInstructionsURL","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/hostedInstructionsURL","title":"hostedInstructionsURL","abstract":[{"type":"text","text":"The URL to open which contains instructions on how to complete the payment."}],"navigatorTitle":[{"text":"hostedInstructionsURL","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/hostedinstructionsurl"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode":{"type":"topic","navigatorTitle":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"title":"STPIntentActionPayNowDisplayQrCode","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode","kind":"symbol","abstract":[{"text":"Contains instructions for presenting the QR code required to complete a PayNow payment.","type":"text"},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentActionPayNowDisplayQrCode","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"hostedInstructionsURL"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"hostedInstructionsURL","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"hostedInstructionsURL"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"hostedInstructionsURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1hostedInstructionsURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"hostedInstructionsURL"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1hostedInstructionsURL\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/title","op":"replace","value":"STPIntentActionPayNowDisplayQrCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/fragments","value":[{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/navigatorTitle","op":"replace","value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}]}]}]}