{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/animating","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview\/animating"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview\/animating"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Whether or not the view is animating."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animating"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animating","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","externalID":"c:@M@Stripe@objc(cs)STPPaymentActivityIndicatorView(py)animating","symbolKind":"property","modules":[{"name":"Stripe"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"animating"}],"title":"animating"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/animating":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"animating","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[{"text":"Whether or not the view is animating.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/animating","url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/animating","type":"topic","role":"symbol","navigatorTitle":[{"text":"animating","kind":"identifier"}],"title":"animating"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"kind":"symbol","abstract":[{"text":"This class can be used wherever you’d use a ","type":"text"},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"type":"text","text":" and is intended to have a similar API. It renders as a spinning circle with a gap in it, similar to what you see in the App Store app or in the Apple Pay dialog when making a purchase. To change its color, set the "},{"type":"codeVoice","code":"tintColor"},{"type":"text","text":" property."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView","url":"\/documentation\/stripe\/stppaymentactivityindicatorview","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"title":"STPPaymentActivityIndicatorView"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"animating"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"animating","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"animating","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"animating","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1animating\/title","op":"replace"},{"value":[{"text":"animating","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1animating\/fragments"},{"value":"STPPaymentActivityIndicatorView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/title"},{"value":[{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
