{"variants":[{"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview\/hideswhenstopped"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview\/hideswhenstopped"]}],"sections":[],"abstract":[{"type":"text","text":"If true, the view will hide when it is not spinning. Default is true."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/hidesWhenStopped","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView"]]},"metadata":{"modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentActivityIndicatorView(py)hidesWhenStopped","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hidesWhenStopped","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"hidesWhenStopped"}],"title":"hidesWhenStopped","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hidesWhenStopped","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/hidesWhenStopped":{"type":"topic","abstract":[{"text":"If true, the view will hide when it is not spinning. Default is true.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/hidesWhenStopped","title":"hidesWhenStopped","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hidesWhenStopped","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/hideswhenstopped","navigatorTitle":[{"text":"hidesWhenStopped","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView":{"type":"topic","abstract":[{"type":"text","text":"This class can be used wherever you’d use a "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":" and is intended to have a similar API. It renders as a spinning circle with a gap in it, similar to what you see in the App Store app or in the Apple Pay dialog when making a purchase. To change its color, set the ","type":"text"},{"type":"codeVoice","code":"tintColor"},{"type":"text","text":" property."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView","title":"STPPaymentActivityIndicatorView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"url":"\/documentation\/stripe\/stppaymentactivityindicatorview","navigatorTitle":[{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"hidesWhenStopped","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"hidesWhenStopped","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hidesWhenStopped"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1hidesWhenStopped\/title","value":"hidesWhenStopped","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1hidesWhenStopped\/fragments","value":[{"kind":"identifier","text":"hidesWhenStopped"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/title","value":"STPPaymentActivityIndicatorView"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/fragments","value":[{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}],"op":"replace"}]}]}
