{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/layoutSubviews()","interfaceLanguage":"swift"},"abstract":[{"text":":nodoc:","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview\/layoutsubviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview\/layoutsubviews()"]}],"metadata":{"symbolKind":"method","role":"symbol","title":"layoutSubviews()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentActivityIndicatorView(im)layoutSubviews","modules":[{"name":"Stripe"}]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView":{"type":"topic","abstract":[{"type":"text","text":"This class can be used wherever you’d use a "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":" and is intended to have a similar API. It renders as a spinning circle with a gap in it, similar to what you see in the App Store app or in the Apple Pay dialog when making a purchase. To change its color, set the ","type":"text"},{"type":"codeVoice","code":"tintColor"},{"type":"text","text":" property."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView","title":"STPPaymentActivityIndicatorView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"url":"\/documentation\/stripe\/stppaymentactivityindicatorview","navigatorTitle":[{"text":"STPPaymentActivityIndicatorView","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/layoutSubviews()":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/layoutSubviews()","kind":"symbol","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"title":"layoutSubviews()","url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/layoutsubviews()","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"layoutSubviews"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"STPPaymentActivityIndicatorView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/fragments","value":[{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1layoutSubviews()\/title","value":"layoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1layoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
