{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAnimating","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animating"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setAnimating","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentActivityIndicatorView(im)setAnimating:animated:","role":"symbol","symbolKind":"method","title":"setAnimating(_:animated:)","navigatorTitle":[{"text":"setAnimating:animated:","kind":"identifier"}],"modules":[{"name":"Stripe"}],"roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/setAnimating(_:animated:)"},"variants":[{"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview\/setanimating(_:animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentactivityindicatorview\/setanimating(_:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Tell the view to start or stop spinning. If ","type":"text"},{"code":"hidesWhenStopped","type":"codeVoice"},{"type":"text","text":" is true, it will fade in\/out if animated is true."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView/setAnimating(_:animated:)":{"kind":"symbol","title":"setAnimating(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setAnimating","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView\/setAnimating(_:animated:)","type":"topic","url":"\/documentation\/stripe\/stppaymentactivityindicatorview\/setanimating(_:animated:)","navigatorTitle":[{"kind":"identifier","text":"setAnimating:animated:"}],"abstract":[{"text":"Tell the view to start or stop spinning. If ","type":"text"},{"code":"hidesWhenStopped","type":"codeVoice"},{"type":"text","text":" is true, it will fade in\/out if animated is true."}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentActivityIndicatorView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"kind":"symbol","abstract":[{"text":"This class can be used wherever you’d use a ","type":"text"},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"type":"text","text":" and is intended to have a similar API. It renders as a spinning circle with a gap in it, similar to what you see in the App Store app or in the Apple Pay dialog when making a purchase. To change its color, set the "},{"type":"codeVoice","code":"tintColor"},{"type":"text","text":" property."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentActivityIndicatorView","url":"\/documentation\/stripe\/stppaymentactivityindicatorview","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"title":"STPPaymentActivityIndicatorView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setAnimating:animated:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setAnimating:animated:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setAnimating:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animating"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animated:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1setAnimating(_:animated:)\/title","value":"setAnimating:animated:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView~1setAnimating(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setAnimating:animated:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/title","value":"STPPaymentActivityIndicatorView"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentActivityIndicatorView\/fragments","value":[{"kind":"identifier","text":"STPPaymentActivityIndicatorView"}],"op":"replace"}]}]}
