{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/rootObjectName()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument"]]},"kind":"symbol","abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"metadata":{"extendedModule":"StripePayments","role":"symbol","externalID":"c:@CM@StripePayments@objc(cs)STPConnectAccountVerificationDocument(cm)rootObjectName","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Type Method","title":"rootObjectName()","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountverificationdocument\/rootobjectname()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountverificationdocument\/rootobjectname()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountVerificationDocument":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument","title":"STPConnectAccountVerificationDocument","url":"\/documentation\/stripepayments\/stpconnectaccountverificationdocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountVerificationDocument"}],"navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountVerificationDocument"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An identifying document, either a passport or local ID card for use with "},{"code":"STPConnectAccountIndividualVerification","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountVerificationDocument/rootObjectName()":{"title":"rootObjectName()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/rootObjectName()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpconnectaccountverificationdocument\/rootobjectname()","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"rootObjectName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument\/title","op":"replace","value":"STPConnectAccountVerificationDocument"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument\/fragments","op":"replace","value":[{"text":"STPConnectAccountVerificationDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument\/navigatorTitle","op":"replace","value":[{"text":"STPConnectAccountVerificationDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument~1rootObjectName()\/title","op":"replace","value":"rootObjectName"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument~1rootObjectName()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}]}]}]}