{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"StripePayments"}],"role":"collectionGroup","title":"STPFormEncodable Implementations"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/STPFormEncodable-Implementations","interfaceLanguage":"swift"},"kind":"article","topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/rootObjectName()"],"generated":true}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountverificationdocument\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountverificationdocument\/stpformencodable-implementations"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountVerificationDocument":{"title":"STPConnectAccountVerificationDocument","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountVerificationDocument"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPConnectAccountVerificationDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"An identifying document, either a passport or local ID card for use with "},{"type":"codeVoice","code":"STPConnectAccountIndividualVerification"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument","url":"\/documentation\/stripepayments\/stpconnectaccountverificationdocument","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountVerificationDocument/propertyNamesToFormFieldNamesMapping()":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/propertyNamesToFormFieldNamesMapping()","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"type":"topic","kind":"symbol","title":"propertyNamesToFormFieldNamesMapping()","role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountverificationdocument\/propertynamestoformfieldnamesmapping()","abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"code":"expMonth","type":"codeVoice"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountVerificationDocument/rootObjectName()":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"title":"rootObjectName()","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/rootObjectName()","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountverificationdocument\/rootobjectname()"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountVerificationDocument\/rootObjectName()"],"title":"Type Methods","generated":true}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument\/title","value":"STPConnectAccountVerificationDocument","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountVerificationDocument"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument~1propertyNamesToFormFieldNamesMapping()\/title","value":"propertyNamesToFormFieldNamesMapping","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument~1propertyNamesToFormFieldNamesMapping()\/fragments","op":"replace"},{"op":"replace","value":"rootObjectName","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument~1rootObjectName()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"rootObjectName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountVerificationDocument~1rootObjectName()\/fragments"}]}]}
