//
// FinancialConnectionsSessionsGenerateHostedUrlBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore

struct FinancialConnectionsSessionsGenerateHostedUrlBody: Encodable {
    let clientSecret: String
    let fullscreen: Bool
    let hideCloseButton: Bool
    let appReturnUrl: String?
}
