{"kind":"symbol","abstract":[{"text":"The tax ID of the customer (CPF for individuals or CNPJ for businesses).","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taxID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Supported formats:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"XXX.XXX.XXX-XX","type":"codeVoice"},{"type":"text","text":" or "},{"code":"XXXXXXXXXXX","type":"codeVoice"},{"type":"text","text":" for CPF"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"XX.XXX.XXX\/XXXX-XX","type":"codeVoice"},{"type":"text","text":" or "},{"code":"XXXXXXXXXXXXXX","type":"codeVoice"},{"type":"text","text":" for CNPJ"}],"type":"paragraph"}]}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBoletoParams"]]},"metadata":{"role":"symbol","title":"taxID","symbolKind":"property","navigatorTitle":[{"text":"taxID","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taxID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodBoletoParams(py)taxID","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodboletoparams\/taxid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodboletoparams\/taxid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBoletoParams\/taxID"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBoletoParams/taxID":{"type":"topic","kind":"symbol","abstract":[{"text":"The tax ID of the customer (CPF for individuals or CNPJ for businesses).","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"taxID"}],"url":"\/documentation\/stripepayments\/stppaymentmethodboletoparams\/taxid","title":"taxID","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBoletoParams\/taxID","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"taxID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBoletoParams":{"type":"topic","kind":"symbol","abstract":[{"text":"An object representing parameters used to create a Boleto Payment Method","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBoletoParams"}],"url":"\/documentation\/stripepayments\/stppaymentmethodboletoparams","title":"STPPaymentMethodBoletoParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBoletoParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBoletoParams"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"taxID","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"taxID","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"taxID","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"taxID","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBoletoParams~1taxID\/title"},{"op":"replace","value":[{"kind":"identifier","text":"taxID"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBoletoParams~1taxID\/fragments"},{"op":"replace","value":"STPPaymentMethodBoletoParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBoletoParams\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodBoletoParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBoletoParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBoletoParams\/navigatorTitle","value":[{"text":"STPPaymentMethodBoletoParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}