{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodTwintParams"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodTwintParams\/init","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodTwintParams(im)init","modules":[{"name":"StripePayments"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtwintparams\/init"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodTwintParams/init":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodTwintParams\/init","url":"\/documentation\/stripepayments\/stppaymentmethodtwintparams\/init","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodTwintParams":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodTwintParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create a TWINT Payment Method","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethodTwintParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtwintparams","title":"STPPaymentMethodTwintParams","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodTwintParams"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodTwintParams\/title","op":"replace","value":"STPPaymentMethodTwintParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodTwintParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodTwintParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodTwintParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodTwintParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}