{"variants":[{"paths":["\/documentation\/stripepayments\/stpapiclient\/confirmsetupintent(with:expand:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmSetupIntent"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"setupIntentParams"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","text":"STPSetupIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expand"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]? = nil) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"setupIntentParams","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"STPSetupIntentConfirmParams","type":"codeVoice"},{"type":"text","text":" to pass to "},{"code":"\/confirm","type":"codeVoice"}]}]},{"name":"expand","content":[{"type":"paragraph","inlineContent":[{"text":"An array of string keys to expand on the returned SetupIntent object. These strings should match one or more of the parameter names that are marked as expandable.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A SetupIntent object.","type":"text"}]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Use the "},{"code":"confirmSetupIntent:withAuthenticationContext:completion:","type":"codeVoice"},{"type":"text","text":" method on "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" instead"},{"type":"text","text":" "},{"type":"text","text":"of calling this method directly. It handles any authentication necessary for you."}],"type":"paragraph"}],"style":"note"},{"content":[{"inlineContent":[{"text":"The error that occurred making the Stripe API request.","type":"text"}],"type":"paragraph"}],"name":"Throws","style":"note","type":"aside"},{"type":"aside","name":"See Also","style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"name":"See Also","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","isActive":true,"type":"reference"}]}],"type":"aside"}],"kind":"content"}],"abstract":[{"type":"text","text":"Confirms the SetupIntent object with the provided params object."},{"type":"text","text":" "},{"text":"At a minimum, the params object must include the ","type":"text"},{"type":"codeVoice","code":"clientSecret"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE18confirmSetupIntent4with6expandAD08STPSetupG0CAD0jG13ConfirmParamsC_SaySSGSgtYaKF","extendedModule":"StripeCore","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"roleHeading":"Instance Method","title":"confirmSetupIntent(with:expand:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPSetupIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expand"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","kind":"typeIdentifier","text":"STPSetupIntent"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/confirmSetupIntent(with:expand:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"type":"topic","title":"STPSetupIntentConfirmParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"type":"text","text":" "},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"type":"text","text":".  Otherwise, it will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"text":", and suggest additional actions via ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"type":"text","text":" directly, we recommend using "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to handle any additional steps for you."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"},"https://stripe.com/docs/api/setup_intents/object":{"type":"link","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","title":"Stripe API reference","url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/confirmSetupIntent(with:expand:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/confirmSetupIntent(with:expand:)","abstract":[{"text":"Confirms the SetupIntent object with the provided params object.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"At a minimum, the params object must include the "},{"type":"codeVoice","code":"clientSecret"},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/confirmsetupintent(with:expand:)","title":"confirmSetupIntent(with:expand:)"},"https://stripe.com/docs/api/setup_intents/confirm":{"type":"link","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm","title":"Stripe API reference","url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/confirm"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"title":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntent"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","type":"topic","url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPSetupIntentConfirmParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","op":"replace","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","value":[{"text":"STPSetupIntent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"text":"STPSetupIntent","kind":"identifier"}]}]}]}