{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/confirmpaymentintent(with:expand:completion:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/confirmPaymentIntent(with:expand:completion:)","interfaceLanguage":"swift"},"metadata":{"title":"confirmPaymentIntent(with:expand:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)confirmPaymentIntentWithParams:expand:completion:","symbolKind":"method","extendedModule":"StripeCore","role":"symbol","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}]},"kind":"symbol","abstract":[{"text":"Confirms the PaymentIntent object with the provided params object.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"At a minimum, the params object must include the "},{"type":"codeVoice","code":"clientSecret"},{"type":"text","text":"."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(confirmPaymentIntentWithParams:expand:completion:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmPaymentIntent"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentIntentConfirmParams"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams"},{"kind":"text","text":", "},{"text":"expand","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCompletionBlock","text":"STPPaymentIntentCompletionBlock"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"STPPaymentIntentConfirmParams","type":"codeVoice"},{"type":"text","text":" to pass to "},{"code":"\/confirm","type":"codeVoice"}],"type":"paragraph"}],"name":"paymentIntentConfirmParams"},{"name":"expand","content":[{"inlineContent":[{"type":"text","text":"An array of string keys to expand on the returned PaymentIntent object. These strings should match one or more of the parameter names that are marked as expandable."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The callback to run with the returned PaymentIntent object, or an error."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the "},{"code":"confirmPayment:withAuthenticationContext:completion:","type":"codeVoice"},{"type":"text","text":" method on "},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" instead","type":"text"},{"type":"text","text":" "},{"type":"text","text":"of calling this method directly. It handles any authentication necessary for you."}]}],"name":"Note","style":"note","type":"aside"},{"content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent"}],"type":"paragraph"}],"style":"note","name":"See Also","type":"aside"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/api\/payment_intents\/object","isActive":true,"type":"reference"}]}],"style":"note","type":"aside","name":"See Also"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"title":"STPPaymentIntentConfirmParams","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCompletionBlock":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCompletionBlock","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentcompletionblock","title":"STPPaymentIntentCompletionBlock","abstract":[{"text":"A callback to be run with a PaymentIntent response from the Stripe API.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentCompletionBlock"}],"navigatorTitle":[{"text":"STPPaymentIntentCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"https://stripe.com/docs/api/payment_intents/object":{"identifier":"https:\/\/stripe.com\/docs\/api\/payment_intents\/object","title":"Stripe API reference","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"type":"link","url":"https:\/\/stripe.com\/docs\/api\/payment_intents\/object"},"https://stripe.com/docs/api#confirm_payment_intent":{"type":"link","identifier":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"url":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent","title":"Stripe API reference"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","type":"topic","title":"STPAPIClient","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/confirmPaymentIntent(with:expand:completion:)":{"title":"confirmPaymentIntent(with:expand:completion:)","type":"topic","url":"\/documentation\/stripepayments\/stpapiclient\/confirmpaymentintent(with:expand:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmPaymentIntent"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expand"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/confirmPaymentIntent(with:expand:completion:)","abstract":[{"type":"text","text":"Confirms the PaymentIntent object with the provided params object."},{"text":" ","type":"text"},{"text":"At a minimum, the params object must include the ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPPaymentIntentConfirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]}]}]}