{"abstract":[{"type":"text","text":"Confirms the PaymentIntent object with the provided params object."},{"text":" ","type":"text"},{"text":"At a minimum, the params object must include the ","type":"text"},{"type":"codeVoice","code":"clientSecret"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/confirmPaymentIntent(with:completion:)"},"metadata":{"roleHeading":"Instance Method","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)confirmPaymentIntentWithParams:completion:","title":"confirmPaymentIntent(with:completion:)","extendedModule":"StripeCore","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentIntentParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka"},{"kind":"text","text":")"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(confirmPaymentIntentWithParams:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmPaymentIntent"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"text":"paymentIntentParams","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams","text":"STPPaymentIntentParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka","text":"STPPaymentIntentCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"style":"note","name":"See Also","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api#Confirm_payment_intent","type":"text"}]}]},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"text":"Use the ","type":"text"},{"code":"confirmPayment:withAuthenticationContext:completion:","type":"codeVoice"},{"text":" method on ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" instead","type":"text"},{"text":" ","type":"text"},{"text":"of calling this method directly. It handles any authentication necessary for you. - seealso: https:\/\/stripe.com\/docs\/payments\/3d-secure","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Parameters:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"paymentIntentParams:  The ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentParams"},{"type":"text","text":" to pass to "},{"type":"codeVoice","code":"\/confirm"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"completion:           The callback to run with the returned PaymentIntent object, or an error.","type":"text"}]}]}]}]}]}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/confirmpaymentintent(with:completion:)"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/confirmPaymentIntent(with:completion:)":{"abstract":[{"type":"text","text":"Confirms the PaymentIntent object with the provided params object."},{"type":"text","text":" "},{"type":"text","text":"At a minimum, the params object must include the "},{"code":"clientSecret","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/confirmPaymentIntent(with:completion:)","url":"\/documentation\/stripepayments\/stpapiclient\/confirmpaymentintent(with:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmPaymentIntent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments31STPPaymentIntentCompletionBlocka","text":"STPPaymentIntentCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"confirmPaymentIntent(with:completion:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"title":"STPAPIClient","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentParams"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","title":"STPPaymentIntentParams","url":"\/documentation\/stripepayments\/stppaymentintentparams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCompletionBlock":{"abstract":[{"text":"A callback to be run with a PaymentIntent response from the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCompletionBlock","url":"\/documentation\/stripepayments\/stppaymentintentcompletionblock","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCompletionBlock"}],"title":"STPPaymentIntentCompletionBlock","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntentParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","op":"replace","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentParams"}]}]}]}