{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"confirmPaymentIntent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"paymentIntentParams","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]? = nil) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"paymentIntentParams","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentParams"},{"type":"text","text":" to pass to "},{"code":"\/confirm","type":"codeVoice"}],"type":"paragraph"}]},{"name":"expand","content":[{"inlineContent":[{"text":"An array of string keys to expand on the returned PaymentIntent object. These strings should match one or more of the parameter names that are marked as expandable.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A PaymentIntent object."}]}],"kind":"content"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use the "},{"type":"codeVoice","code":"confirmPayment:withAuthenticationContext:completion:"},{"text":" method on ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" instead"},{"type":"text","text":" "},{"type":"text","text":"of calling this method directly. It handles any authentication necessary for you."}]}],"name":"Note","type":"aside","style":"note"},{"type":"aside","style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}]},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent","type":"reference","isActive":true}]}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/confirmPaymentIntent(with:expand:)","interfaceLanguage":"swift"},"metadata":{"extendedModule":"StripeCore","roleHeading":"Instance Method","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE20confirmPaymentIntent4with6expandAD010STPPaymentG0CAD0jG13ConfirmParamsC_SaySSGSgtYaKF","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"}],"symbolKind":"method","title":"confirmPaymentIntent(with:expand:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Confirms the PaymentIntent object with the provided params object."},{"type":"text","text":" "},{"type":"text","text":"At a minimum, the params object must include the "},{"type":"codeVoice","code":"clientSecret"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/confirmpaymentintent(with:expand:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"title":"STPAPIClient","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"url":"\/documentation\/stripepayments\/stpapiclient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/confirmPaymentIntent(with:expand:)":{"url":"\/documentation\/stripepayments\/stpapiclient\/confirmpaymentintent(with:expand:)","abstract":[{"type":"text","text":"Confirms the PaymentIntent object with the provided params object."},{"type":"text","text":" "},{"type":"text","text":"At a minimum, the params object must include the "},{"type":"codeVoice","code":"clientSecret"},{"text":".","type":"text"}],"type":"topic","title":"confirmPaymentIntent(with:expand:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/confirmPaymentIntent(with:expand:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmPaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintent","abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"title":"STPPaymentIntent","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"kind":"symbol","title":"STPPaymentIntentConfirmParams","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"That PaymentMethod or Source can either be:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]},"https://stripe.com/docs/api#confirm_payment_intent":{"identifier":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent","type":"link","url":"https:\/\/stripe.com\/docs\/api#confirm_payment_intent","title":"Stripe API reference","titleInlineContent":[{"text":"Stripe API reference","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent"},{"op":"replace","value":[{"text":"STPPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","op":"replace","value":"STPPaymentIntentConfirmParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]},{"op":"replace","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle"}]}]}