{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createpaymentmethod(with:)"]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE19createPaymentMethod4withAD010STPPaymentG0CAD0iG6ParamsC_tYaKF","symbolKind":"method","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"extendedModule":"StripeCore","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier"}],"title":"createPaymentMethod(with:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"paymentMethodParams"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"paymentMethodParams","content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":" to pass to "},{"type":"codeVoice","code":"\/v1\/payment_methods"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The created PaymentMethod object."}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"style":"note","type":"aside","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"The error that occurred making the Stripe API request.","type":"text"}]}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create","isActive":true,"type":"reference"}]}],"style":"note","name":"See Also"}],"kind":"content"}],"abstract":[{"text":"Creates a PaymentMethod object with the provided params object.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createPaymentMethod(with:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"https://stripe.com/docs/api/payment_methods/create":{"titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"url":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create","identifier":"https:\/\/stripe.com\/docs\/api\/payment_methods\/create","type":"link","title":"Stripe API reference"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"title":"STPAPIClient","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"url":"\/documentation\/stripepayments\/stpapiclient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodparams","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"role":"symbol","type":"topic","title":"STPPaymentMethod","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createPaymentMethod(with:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/createpaymentmethod(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentMethod","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"}],"abstract":[{"type":"text","text":"Creates a PaymentMethod object with the provided params object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createPaymentMethod(with:)","title":"createPaymentMethod(with:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"value":[{"kind":"identifier","text":"STPPaymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethod"}]}]}]}