{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createtoken(withcard:completion:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(createTokenWithCard:completion:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"text":"(","kind":"text"},{"text":"withCard","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cardParams","kind":"internalParam"},{"kind":"text","text":": "},{"text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" ","kind":"text"},{"text":"STPTokenCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The user’s card details. Cannot be nil. - seealso: https:\/\/stripe.com\/docs\/api#create_card_token","type":"text"}]}],"name":"cardParams"},{"name":"completion","content":[{"inlineContent":[{"text":"The callback to run with the returned Stripe token (and any errors that may have occurred).","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withCard:completion:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"withCard","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","text":"STPCardParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock"},{"text":")","kind":"text"}],"title":"createToken(withCard:completion:)","roleHeading":"Instance Method","extendedModule":"StripeCore","externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createTokenWithCard:completion:","role":"symbol","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Converts an STPCardParams object into a Stripe token using the Stripe API."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createToken(withCard:completion:)":{"abstract":[{"type":"text","text":"Converts an STPCardParams object into a Stripe token using the Stripe API."}],"title":"createToken(withCard:completion:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withCard:completion:)","url":"\/documentation\/stripepayments\/stpapiclient\/createtoken(withcard:completion:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCard"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","text":"STPCardParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenCompletionBlock":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTokenCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPTokenCompletionBlock"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","title":"STPTokenCompletionBlock","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stptokencompletionblock","abstract":[{"text":"A callback to be run with a token response from the Stripe API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"abstract":[{"text":"Representation of a user’s credit card details. You can assemble these with","type":"text"},{"text":" ","type":"text"},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"type":"text","text":" "},{"text":"an STPAPIClient.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpcardparams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","navigatorTitle":[{"text":"STPCardParams","kind":"identifier"}],"title":"STPCardParams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIClient"}],"type":"topic","url":"\/documentation\/stripepayments\/stpapiclient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","title":"STPAPIClient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title","value":"STPCardParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments","op":"replace","value":[{"text":"STPCardParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle","value":[{"text":"STPCardParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}