{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createSource","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"sourceParams","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"sourceParams","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The details of the source to create."}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A Source object."}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"name":"Throws","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}],"type":"paragraph"}]},{"style":"note","type":"aside","name":"See Also","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"https:\/\/stripe.com\/docs\/api#create_source","isActive":true,"type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges","type":"reference","isActive":true}]}],"name":"See Also","type":"aside","style":"note"}]}],"sections":[],"abstract":[{"text":"Creates a Source object using the provided details.","type":"text"},{"text":" ","type":"text"},{"text":"Note: in order to create a source on a connected account, you can set your","type":"text"},{"type":"text","text":" "},{"text":"API client’s ","type":"text"},{"type":"codeVoice","code":"stripeAccount"},{"type":"text","text":" property to the ID of the account."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createsource(with:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"metadata":{"role":"symbol","symbolKind":"method","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE12createSource4withAD9STPSourceCAD0H6ParamsC_tYaKF","extendedModule":"StripeCore","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"roleHeading":"Instance Method","title":"createSource(with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createSource"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createSource(with:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"title":"STPSource","url":"\/documentation\/stripepayments\/stpsource","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","type":"topic","kind":"symbol","abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"navigatorTitle":[{"text":"STPSource","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","type":"topic","url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"},"https://stripe.com/docs/api#create_source":{"titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"title":"Stripe API reference","url":"https:\/\/stripe.com\/docs\/api#create_source","type":"link","identifier":"https:\/\/stripe.com\/docs\/api#create_source"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"url":"\/documentation\/stripepayments\/stpsourceparams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"abstract":[{"text":"An object representing parameters used to create a Source object.","type":"text"}],"title":"STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createSource(with:)":{"role":"symbol","abstract":[{"type":"text","text":"Creates a Source object using the provided details."},{"type":"text","text":" "},{"text":"Note: in order to create a source on a connected account, you can set your","type":"text"},{"type":"text","text":" "},{"type":"text","text":"API client’s "},{"code":"stripeAccount","type":"codeVoice"},{"text":" property to the ID of the account.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createSource","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource","kind":"typeIdentifier"}],"title":"createSource(with:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createSource(with:)","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpapiclient\/createsource(with:)"},"https://stripe.com/docs/sources/connect#creating-direct-charges":{"titleInlineContent":[{"text":"Creating direct charges on connected accounts","type":"text"}],"title":"Creating direct charges on connected accounts","url":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges","type":"link","identifier":"https:\/\/stripe.com\/docs\/sources\/connect#creating-direct-charges"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","op":"replace","value":"STPSource"},{"value":[{"kind":"identifier","text":"STPSource"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","value":[{"text":"STPSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"text":"STPSourceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace"}]}]}