{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withSSNLast4:)"},"metadata":{"externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE11createToken12withSSNLast4AD8STPTokenCSS_tYaKF","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withSSNLast4"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"}],"title":"createToken(withSSNLast4:)","extendedModule":"StripeCore","symbolKind":"method","role":"symbol","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createtoken(withssnlast4:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createToken"},{"text":"(","kind":"text"},{"text":"withSSNLast4","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"ssnLast4"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","text":"STPToken","kind":"typeIdentifier"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The last 4 digits of the user’s SSN."}],"type":"paragraph"}],"name":"ssnLast4"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A Stripe token."}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"content":[{"inlineContent":[{"text":"The error that occurred making the Stripe API request.","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Throws","style":"note"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"https:\/\/stripe.com\/docs\/api#create_pii_token","type":"reference","isActive":true}]}],"name":"See Also","type":"aside","style":"note"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Converts the last 4 SSN digits into a Stripe token using the Stripe API."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createToken(withSSNLast4:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createToken"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withSSNLast4"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","text":"STPToken"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withSSNLast4:)","type":"topic","abstract":[{"type":"text","text":"Converts the last 4 SSN digits into a Stripe token using the Stripe API."}],"title":"createToken(withSSNLast4:)","url":"\/documentation\/stripepayments\/stpapiclient\/createtoken(withssnlast4:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","kind":"symbol","url":"\/documentation\/stripepayments\/stpapiclient","title":"STPAPIClient","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"title":"STPToken","url":"\/documentation\/stripepayments\/stptoken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","kind":"symbol","abstract":[{"type":"text","text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPToken","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPToken"}]},"https://stripe.com/docs/api#create_pii_token":{"identifier":"https:\/\/stripe.com\/docs\/api#create_pii_token","type":"link","url":"https:\/\/stripe.com\/docs\/api#create_pii_token","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"title":"Stripe API reference"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title","op":"replace","value":"STPToken"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","value":[{"text":"STPToken","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPToken"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle"}]}]}