{"sections":[],"abstract":[{"type":"text","text":"Converts an "},{"type":"codeVoice","code":"STPCardParams"},{"text":" object into a Stripe token using the Stripe API.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCard"},{"kind":"text","text":" "},{"text":"cardParams","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"STPToken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"cardParams","content":[{"type":"paragraph","inlineContent":[{"text":"The user’s card details.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A Stripe token."}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}],"style":"note","name":"Throws","type":"aside"},{"type":"aside","name":"See Also","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#create_card_token","isActive":true}]}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpapiclient\/createtoken(withcard:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","role":"symbol","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"extendedModule":"StripeCore","title":"createToken(withCard:)","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE11createToken8withCardAD8STPTokenCAD13STPCardParamsC_tYaKF","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"text":"(","kind":"text"},{"text":"withCard","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","text":"STPCardParams"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withCard:)"},"kind":"symbol","references":{"https://stripe.com/docs/api#create_card_token":{"identifier":"https:\/\/stripe.com\/docs\/api#create_card_token","type":"link","title":"Stripe API reference","url":"https:\/\/stripe.com\/docs\/api#create_card_token","titleInlineContent":[{"text":"Stripe API reference","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"title":"STPToken","abstract":[{"text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly.","type":"text"}],"navigatorTitle":[{"text":"STPToken","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPToken"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","url":"\/documentation\/stripepayments\/stptoken","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"url":"\/documentation\/stripepayments\/stpcardparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","title":"STPCardParams","navigatorTitle":[{"text":"STPCardParams","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Representation of a user’s credit card details. You can assemble these with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","type":"topic","url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createToken(withCard:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCard"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","text":"STPCardParams","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"STPToken","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"}],"abstract":[{"text":"Converts an ","type":"text"},{"code":"STPCardParams","type":"codeVoice"},{"type":"text","text":" object into a Stripe token using the Stripe API."}],"role":"symbol","title":"createToken(withCard:)","url":"\/documentation\/stripepayments\/stpapiclient\/createtoken(withcard:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withCard:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title","value":"STPToken"},{"value":[{"text":"STPToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPToken"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title","value":"STPCardParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments","value":[{"kind":"identifier","text":"STPCardParams"}]},{"op":"replace","value":[{"text":"STPCardParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle"}]}]}