{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withConnectAccount:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(createTokenWithConnectAccount:completion:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createToken","kind":"identifier"},{"kind":"text","text":"("},{"text":"withConnectAccount","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"account"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","text":"STPConnectAccountParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The Connect Account parameters. Cannot be nil.","type":"text"}]}],"name":"account"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"The callback to run with the returned Stripe token (and any errors that may have occurred)."}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"metadata":{"externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createTokenWithConnectAccount:completion:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createToken"},{"text":"(","kind":"text"},{"text":"withConnectAccount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountParams","text":"STPConnectAccountParams"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","title":"createToken(withConnectAccount:completion:)","extendedModule":"StripeCore","symbolKind":"method","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}]},"variants":[{"paths":["\/documentation\/stripepayments\/stpapiclient\/createtoken(withconnectaccount:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Converts an "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"text":" object into a Stripe token using the Stripe API.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This allows the connected account to accept the Terms of Service, and\/or send Legal Entity information."}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"url":"\/documentation\/stripepayments\/stpapiclient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient"}],"title":"STPAPIClient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","role":"symbol","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createToken(withConnectAccount:completion:)":{"kind":"symbol","title":"createToken(withConnectAccount:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withConnectAccount:completion:)","abstract":[{"type":"text","text":"Converts an "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":" object into a Stripe token using the Stripe API."},{"text":" ","type":"text"},{"text":"This allows the connected account to accept the Terms of Service, and\/or send Legal Entity information.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/createtoken(withconnectaccount:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConnectAccount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountParams","text":"STPConnectAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock"},{"kind":"text","text":"?)"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountparams","title":"STPConnectAccountParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPConnectAccountParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenCompletionBlock":{"abstract":[{"text":"A callback to be run with a token response from the Stripe API.","type":"text"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"STPTokenCompletionBlock","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stptokencompletionblock","kind":"symbol","navigatorTitle":[{"text":"STPTokenCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","title":"STPTokenCompletionBlock","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title","value":"STPConnectAccountParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments","value":[{"text":"STPConnectAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle","value":[{"text":"STPConnectAccountParams","kind":"identifier"}],"op":"replace"}]}]}