{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createPaymentMethod(with:additionalPaymentUserAgentValues:)"},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"additionalPaymentUserAgentValues"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier"}],"roleHeading":"Instance Method","extendedModule":"StripeCore","title":"createPaymentMethod(with:additionalPaymentUserAgentValues:)","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE19createPaymentMethod4with010additionalF15UserAgentValuesAD010STPPaymentG0CAD0mG6ParamsC_SaySSGtYaKF","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}]},"abstract":[{"type":"text","text":"Creates a PaymentMethod object with the provided params object."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createPaymentMethod","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"paymentMethodParams"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},{"text":", ","kind":"text"},{"text":"additionalPaymentUserAgentValues","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"paymentMethodParams","content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"text":" to pass to ","type":"text"},{"type":"codeVoice","code":"\/v1\/payment_methods"},{"type":"text","text":".  Cannot be nil."}],"type":"paragraph"}]},{"name":"additionalPaymentUserAgentValues","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A list of values to append to the "},{"type":"codeVoice","code":"payment_user_agent"},{"type":"text","text":" parameter sent in the request. e.g. "},{"type":"codeVoice","code":"[\"deferred-intent\", \"autopm\"]"},{"text":" will append “; deferred-intent; autopm” to the ","type":"text"},{"type":"codeVoice","code":"payment_user_agent"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The returned PaymentMethod object.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"name":"See Also","style":"note","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Create"}],"type":"paragraph"}],"type":"aside"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createpaymentmethod(with:additionalpaymentuseragentvalues:)"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodParams"}],"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"role":"symbol","title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createPaymentMethod(with:additionalPaymentUserAgentValues:)":{"title":"createPaymentMethod(with:additionalPaymentUserAgentValues:)","abstract":[{"type":"text","text":"Creates a PaymentMethod object with the provided params object."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"additionalPaymentUserAgentValues"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/createpaymentmethod(with:additionalpaymentuseragentvalues:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createPaymentMethod(with:additionalPaymentUserAgentValues:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient"}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpapiclient","title":"STPAPIClient","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethod"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod","kind":"symbol","title":"STPPaymentMethod","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","op":"replace","value":"STPPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle"}]}]}