{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createSource(with:completion:)-6w1jx","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a Source object using the provided details."},{"text":" ","type":"text"},{"text":"Note: in order to create a source on a connected account, you can set your","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"API client’s "},{"code":"stripeAccount","type":"codeVoice"},{"type":"text","text":" property to the ID of the account."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createSource","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceCompletionBlock","preciseIdentifier":"s:14StripePayments24STPSourceCompletionBlocka"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","extendedModule":"StripeCore","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"role":"symbol","externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createSourceWithParams:completion:","title":"createSource(with:completion:)","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createsource(with:completion:)-6w1jx"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(createSourceWithParams:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createSource","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"sourceParams","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCompletionBlock","text":"STPSourceCompletionBlock","preciseIdentifier":"s:14StripePayments24STPSourceCompletionBlocka","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"sourceParams","content":[{"type":"paragraph","inlineContent":[{"text":"The details of the source to create. Cannot be nil. - seealso: https:\/\/stripe.com\/docs\/api#create_source","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The callback to run with the returned Source object, or an error.","type":"text"}]}],"name":"completion"}]},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Connect#Creating-Direct-Charges"}],"type":"paragraph"}],"name":"See Also"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createSource(with:completion:)-6w1jx":{"kind":"symbol","title":"createSource(with:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createSource(with:completion:)-6w1jx","abstract":[{"text":"Creates a Source object using the provided details.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Note: in order to create a source on a connected account, you can set your"},{"type":"text","text":" "},{"text":"API client’s ","type":"text"},{"code":"stripeAccount","type":"codeVoice"},{"text":" property to the ID of the account.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/createsource(with:completion:)-6w1jx","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createSource"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceCompletionBlock","preciseIdentifier":"s:14StripePayments24STPSourceCompletionBlocka"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"url":"\/documentation\/stripepayments\/stpapiclient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient"}],"title":"STPAPIClient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","role":"symbol","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"type":"topic","title":"STPSourceParams","url":"\/documentation\/stripepayments\/stpsourceparams","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCompletionBlock":{"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceCompletionBlock"}],"navigatorTitle":[{"text":"STPSourceCompletionBlock","kind":"identifier"}],"type":"topic","title":"STPSourceCompletionBlock","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcecompletionblock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCompletionBlock","abstract":[{"text":"A callback to be run with a source response from the Stripe API.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPSourceParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle"}]}]}