{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createRadarSession","kind":"identifier"},{"kind":"text","text":"() "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"STPRadarSession","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A "},{"code":"STPRadarSession","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"text":"See https:\/\/stripe.com\/docs\/radar\/radar-session","type":"text"}],"type":"paragraph"}]},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"StripeAPI.advancedFraudSignalsEnabled"},{"type":"text","text":" must be "},{"type":"codeVoice","code":"true"},{"type":"text","text":" to use this method."}]}],"name":"Note"},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"See "},{"code":"STPRadarSession","type":"codeVoice"}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createradarsession()"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"metadata":{"modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createRadarSession","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPRadarSession","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"}],"title":"createRadarSession()","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"StripeCore","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE18createRadarSessionAD08STPRadarG0CyYaKF"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createRadarSession()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a Radar Session."}],"sections":[],"references":{"https://stripe.com/docs/radar/radar-session":{"type":"link","url":"https:\/\/stripe.com\/docs\/radar\/radar-session","title":"Radar Session","identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session","titleInlineContent":[{"type":"text","text":"Radar Session"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"title":"STPAPIClient","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"url":"\/documentation\/stripepayments\/stpapiclient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarSession":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","role":"symbol","url":"\/documentation\/stripepayments\/stpradarsession","type":"topic","abstract":[{"type":"text","text":"A "},{"identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session","isActive":true,"type":"reference"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRadarSession"}],"navigatorTitle":[{"kind":"identifier","text":"STPRadarSession"}],"kind":"symbol","title":"STPRadarSession"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createRadarSession()":{"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/createradarsession()","title":"createRadarSession()","abstract":[{"type":"text","text":"Creates a Radar Session."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createRadarSession()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createRadarSession","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPRadarSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPRadarSession","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/title"},{"value":[{"text":"STPRadarSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/navigatorTitle","value":[{"kind":"identifier","text":"STPRadarSession"}]}]}]}