{"abstract":[{"type":"text","text":"Converts an "},{"code":"STPBankAccount","type":"codeVoice"},{"type":"text","text":" object into a Stripe token using the Stripe API."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createtoken(withbankaccount:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withBankAccount:)"},"metadata":{"role":"symbol","title":"createToken(withBankAccount:)","roleHeading":"Instance Method","extendedModule":"StripeCore","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withBankAccount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams","kind":"typeIdentifier","text":"STPBankAccountParams"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"}],"externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE11createToken15withBankAccountAD8STPTokenCAD07STPBankI6ParamsC_tYaKF","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBankAccount"},{"kind":"text","text":" "},{"text":"bankAccount","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","kind":"typeIdentifier","text":"STPBankAccountParams"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","kind":"typeIdentifier","text":"STPToken"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The user’s bank account details."}],"type":"paragraph"}],"name":"bankAccount"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A Stripe token.","type":"text"}],"type":"paragraph"}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"style":"note","name":"Throws","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}]},{"style":"note","type":"aside","name":"See Also","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api#create_bank_account_token","isActive":true}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createToken(withBankAccount:)":{"url":"\/documentation\/stripepayments\/stpapiclient\/createtoken(withbankaccount:)","role":"symbol","abstract":[{"type":"text","text":"Converts an "},{"code":"STPBankAccount","type":"codeVoice"},{"type":"text","text":" object into a Stripe token using the Stripe API."}],"title":"createToken(withBankAccount:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBankAccount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withBankAccount:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPToken"}],"navigatorTitle":[{"text":"STPToken","kind":"identifier"}],"title":"STPToken","url":"\/documentation\/stripepayments\/stptoken","abstract":[{"text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly.","type":"text"}]},"https://stripe.com/docs/api#create_bank_account_token":{"identifier":"https:\/\/stripe.com\/docs\/api#create_bank_account_token","type":"link","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"title":"Stripe API reference","url":"https:\/\/stripe.com\/docs\/api#create_bank_account_token"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"navigatorTitle":[{"text":"STPBankAccountParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","title":"STPBankAccountParams","abstract":[{"type":"text","text":"Representation of a user’s bank account details. You can assemble these with"},{"text":" ","type":"text"},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"text":"an STPAPIClient.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"title":"STPAPIClient","url":"\/documentation\/stripepayments\/stpapiclient","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"type":"topic","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient"}]}},"variantOverrides":[{"patch":[{"value":"STPToken","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","value":[{"kind":"identifier","text":"STPToken"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPToken"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","op":"replace","value":"STPBankAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","value":[{"kind":"identifier","text":"STPBankAccountParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle","value":[{"text":"STPBankAccountParams","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}