{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(createTokenWithBankAccount:completion:) "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createToken","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withBankAccount"},{"text":" ","kind":"text"},{"text":"bankAccount","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams","text":"STPBankAccountParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","text":"STPTokenCompletionBlock","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"bankAccount","content":[{"inlineContent":[{"type":"text","text":"The user’s bank account details. Cannot be nil. - seealso: https:\/\/stripe.com\/docs\/api#create_bank_account_token"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback to run with the returned Stripe token (and any errors that may have occurred)."}]}],"name":"completion"}],"kind":"parameters"}],"kind":"symbol","abstract":[{"text":"Converts an STPBankAccount object into a Stripe token using the Stripe API.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/createtoken(withbankaccount:completion:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withBankAccount:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"metadata":{"externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)createTokenWithBankAccount:completion:","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createToken"},{"kind":"text","text":"("},{"text":"withBankAccount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","kind":"typeIdentifier","text":"STPTokenCompletionBlock"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"createToken(withBankAccount:completion:)","symbolKind":"method","extendedModule":"StripeCore"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/createToken(withBankAccount:completion:)":{"kind":"symbol","abstract":[{"type":"text","text":"Converts an STPBankAccount object into a Stripe token using the Stripe API."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createToken"},{"text":"(","kind":"text"},{"text":"withBankAccount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPTokenCompletionBlocka","text":"STPTokenCompletionBlock"},{"kind":"text","text":")"}],"url":"\/documentation\/stripepayments\/stpapiclient\/createtoken(withbankaccount:completion:)","title":"createToken(withBankAccount:completion:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/createToken(withBankAccount:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountParams","url":"\/documentation\/stripepayments\/stpbankaccountparams","type":"topic","title":"STPBankAccountParams","abstract":[{"type":"text","text":"Representation of a user’s bank account details. You can assemble these with"},{"type":"text","text":" "},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"text":" ","type":"text"},{"text":"an STPAPIClient.","type":"text"}],"navigatorTitle":[{"text":"STPBankAccountParams","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenCompletionBlock":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTokenCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPTokenCompletionBlock"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","title":"STPTokenCompletionBlock","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stptokencompletionblock","abstract":[{"text":"A callback to be run with a token response from the Stripe API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIClient"}],"type":"topic","url":"\/documentation\/stripepayments\/stpapiclient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","title":"STPAPIClient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/title","op":"replace","value":"STPBankAccountParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/fragments","value":[{"text":"STPBankAccountParams","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPBankAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountParams\/navigatorTitle"}]}]}