{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"StripeCore","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveSetupIntent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withClientSecret"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?) "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"STPSetupIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","kind":"typeIdentifier"}],"role":"symbol","title":"retrieveSetupIntent(withClientSecret:expand:)","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE19retrieveSetupIntent16withClientSecret6expandAD08STPSetupG0CSS_SaySSGSgtYaKF","symbolKind":"method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/retrieveSetupIntent(withClientSecret:expand:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/retrievesetupintent(withclientsecret:expand:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"retrieveSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withClientSecret"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"secret"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"expand","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]? = nil) ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The client secret of the SetupIntent to be retrieved.","type":"text"}]}],"name":"secret"},{"content":[{"inlineContent":[{"type":"text","text":"An array of string keys to expand on the returned SetupIntent object. These strings should match one or more of the parameter names that are marked as expandable."}],"type":"paragraph"}],"name":"expand"}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"A SetupIntent object.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"style":"note","name":"Throws","type":"aside","content":[{"inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/retrieve","type":"reference"}],"type":"paragraph"}],"name":"See Also","type":"aside","style":"note"},{"name":"See Also","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","isActive":true}]}],"style":"note"}]}],"abstract":[{"text":"Retrieves the SetupIntent object using the given secret.","type":"text"}],"sections":[],"references":{"https://stripe.com/docs/api/setup_intents/retrieve":{"identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/retrieve","type":"link","title":"Stripe API reference","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/retrieve"},"https://stripe.com/docs/api/setup_intents/object":{"title":"Stripe API reference","type":"link","identifier":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object","titleInlineContent":[{"type":"text","text":"Stripe API reference"}],"url":"https:\/\/stripe.com\/docs\/api\/setup_intents\/object"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","abstract":[{"text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSetupIntent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"title":"STPSetupIntent","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"title":"STPAPIClient","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"url":"\/documentation\/stripepayments\/stpapiclient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/retrieveSetupIntent(withClientSecret:expand:)":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/retrievesetupintent(withclientsecret:expand:)","abstract":[{"text":"Retrieves the SetupIntent object using the given secret.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/retrieveSetupIntent(withClientSecret:expand:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"retrieveSetupIntent"},{"text":"(","kind":"text"},{"text":"withClientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expand"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?) "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"}],"title":"retrieveSetupIntent(withClientSecret:expand:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","op":"replace","value":"STPSetupIntent"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","op":"replace","value":[{"text":"STPSetupIntent","kind":"identifier"}]},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}