{"metadata":{"roleHeading":"Instance Method","title":"retrieveSource(withId:clientSecret:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"retrieveSource","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"STPSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource"}],"symbolKind":"method","role":"symbol","extendedModule":"StripeCore","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE14retrieveSource6withId12clientSecretAD9STPSourceCSS_SStYaKF","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Retrieves the Source object with the given ID.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"retrieveSource","kind":"identifier"},{"kind":"text","text":"("},{"text":"withId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"clientSecret"},{"text":" ","kind":"text"},{"text":"secret","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"identifier","content":[{"inlineContent":[{"type":"text","text":"The identifier of the source to be retrieved."}],"type":"paragraph"}]},{"name":"secret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The client secret of the source."}]}]}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A Source object.","type":"text"}]}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"aside","style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"text":"The error that occurred making the Stripe API request.","type":"text"}]}]},{"type":"aside","style":"note","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/api#retrieve_source","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"See Also"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/retrieveSource(withId:clientSecret:)"},"variants":[{"paths":["\/documentation\/stripepayments\/stpapiclient\/retrievesource(withid:clientsecret:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/retrieveSource(withId:clientSecret:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/retrieveSource(withId:clientSecret:)","abstract":[{"type":"text","text":"Retrieves the Source object with the given ID."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"retrieveSource","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"STPSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/retrievesource(withid:clientsecret:)","title":"retrieveSource(withId:clientSecret:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"title":"STPSource","url":"\/documentation\/stripepayments\/stpsource","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","type":"topic","kind":"symbol","abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"navigatorTitle":[{"text":"STPSource","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","type":"topic","url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"},"https://stripe.com/docs/api#retrieve_source":{"identifier":"https:\/\/stripe.com\/docs\/api#retrieve_source","type":"link","title":"Stripe API reference","titleInlineContent":[{"text":"Stripe API reference","type":"text"}],"url":"https:\/\/stripe.com\/docs\/api#retrieve_source"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","op":"replace","value":"STPSource"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","value":[{"kind":"identifier","text":"STPSource"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPSource"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","op":"replace"}]}]}