{"metadata":{"title":"retrievePaymentIntent(withClientSecret:expand:)","roleHeading":"Instance Method","role":"symbol","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE21retrievePaymentIntent16withClientSecret6expandAD010STPPaymentG0CSS_SaySSGSgtYaKF","extendedModule":"StripeCore","symbolKind":"method","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrievePaymentIntent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withClientSecret"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?) "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent","kind":"typeIdentifier"}]},"abstract":[{"text":"Retrieves the PaymentIntent object using the given secret.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"retrievePaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withClientSecret"},{"kind":"text","text":" "},{"text":"secret","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expand"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]? = nil) ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent"}],"platforms":["iOS"]}]},{"parameters":[{"name":"secret","content":[{"inlineContent":[{"type":"text","text":"The client secret of the payment intent to be retrieved."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"An array of string keys to expand on the returned PaymentIntent object. These strings should match one or more of the parameter names that are marked as expandable.","type":"text"}],"type":"paragraph"}],"name":"expand"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"A PaymentIntent object.","type":"text"}],"type":"paragraph"}]},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"name":"Throws","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}]}],"style":"note"},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"[Stripe API reference](https:\/\/stripe.com\/docs\/api#retrieve_payment_intent]"}]}],"style":"note","type":"aside"}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/retrievepaymentintent(withclientsecret:expand:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/retrievePaymentIntent(withClientSecret:expand:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintent","type":"topic","abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntent","kind":"identifier"}],"title":"STPPaymentIntent","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"title":"STPAPIClient","url":"\/documentation\/stripepayments\/stpapiclient","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"type":"topic","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIClient"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/retrievePaymentIntent(withClientSecret:expand:)":{"url":"\/documentation\/stripepayments\/stpapiclient\/retrievepaymentintent(withclientsecret:expand:)","title":"retrievePaymentIntent(withClientSecret:expand:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/retrievePaymentIntent(withClientSecret:expand:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrievePaymentIntent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withClientSecret"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"expand","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?) "},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Retrieves the PaymentIntent object using the given secret."}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"value":[{"text":"STPPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle"}]}]}