{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpapiclient\/updatepaymentmethod(with:paymentmethodupdateparams:ephemeralkeysecret:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE19updatePaymentMethod4with07paymentG12UpdateParams18ephemeralKeySecretAD010STPPaymentG0CSS_AD0ogjK0CSStYaKF","role":"symbol","title":"updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)","extendedModule":"StripeCore","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updatePaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodUpdateParams"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodUpdateParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ephemeralKeySecret"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","text":"STPPaymentMethod"}],"modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updatePaymentMethod"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethodId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"paymentMethodUpdateParams","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams","text":"STPPaymentMethodUpdateParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ephemeralKeySecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","text":"STPPaymentMethod"}],"languages":["swift"]}]},{"parameters":[{"name":"paymentMethodId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Identifier of the payment method to be updated"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPPaymentMethodUpdateParams"},{"type":"text","text":" to pass to "},{"code":"\/v1\/payment_methods\/update","type":"codeVoice"},{"text":".  Cannot be nil.","type":"text"}]}],"name":"paymentMethodUpdateParams"},{"name":"ephemeralKeySecret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Customer Ephemeral Key secret to be used"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Returns the updated ","type":"text"},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" or throws an error if the operation failed."}]}],"kind":"content"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"style":"note","type":"aside","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Update","type":"text"}]}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Updates a PaymentMethod object with the provided params object."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"role":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updatePaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"paymentMethodUpdateParams","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUpdateParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"ephemeralKeySecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","text":"STPPaymentMethod"}],"url":"\/documentation\/stripepayments\/stpapiclient\/updatepaymentmethod(with:paymentmethodupdateparams:ephemeralkeysecret:)","role":"symbol","type":"topic","title":"updatePaymentMethod(with:paymentMethodUpdateParams:ephemeralKeySecret:)","abstract":[{"type":"text","text":"Updates a PaymentMethod object with the provided params object."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUpdateParams"}],"abstract":[{"text":"An object representing parameters used to update a PaymentMethod object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams","title":"STPPaymentMethodUpdateParams","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethod"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"url":"\/documentation\/stripepayments\/stppaymentmethod","title":"STPPaymentMethod","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/title","op":"replace","value":"STPPaymentMethodUpdateParams"},{"value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/navigatorTitle","value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}]},{"op":"replace","value":"STPPaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"op":"replace"}]}]}