{"abstract":[{"type":"text","text":"Uses the Stripe file upload API to upload an image. This can be used for"},{"text":" ","type":"text"},{"text":"identity verification and evidence disputes.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"purpose"},{"text":": ","kind":"text"},{"text":"STPFilePurpose","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments22STPFileCompletionBlocka","text":"STPFileCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"extendedModule":"StripeCore","modules":[{"name":"StripePayments","relatedModules":["StripeCore"]}],"symbolKind":"method","externalID":"c:@CM@StripePayments@StripeCore@objc(cs)STPAPIClient(im)uploadImage:purpose:completion:","roleHeading":"Instance Method","title":"uploadImage(_:purpose:completion:)","role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/uploadImage(_:purpose:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(uploadImage:purpose:completion:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"uploadImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purpose"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","text":"STPFilePurpose","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPFileCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFileCompletionBlock","preciseIdentifier":"s:14StripePayments22STPFileCompletionBlocka"},{"text":"?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The image to be uploaded. The maximum allowed file size is 16MB","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for identity documents and 5MB for evidence disputes. Cannot be nil."},{"type":"text","text":" "},{"type":"text","text":"Your image will be automatically resized down if you pass in one that"},{"text":" ","type":"text"},{"text":"is too large","type":"text"}]}],"name":"image"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The purpose of this file. This can be either an identifying"},{"text":" ","type":"text"},{"type":"text","text":"document or an evidence dispute."}]}],"name":"purpose"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"The callback to run with the returned Stripe file","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"(and any errors that may have occurred)."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"aside","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/File-Upload","type":"text"}]}],"style":"note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/uploadimage(_:purpose:completion:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/uploadImage(_:purpose:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/uploadImage(_:purpose:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"uploadImage","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":", ","kind":"text"},{"text":"purpose","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","text":"STPFilePurpose","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPFileCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments22STPFileCompletionBlocka"},{"kind":"text","text":"?)"}],"title":"uploadImage(_:purpose:completion:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Uses the Stripe file upload API to upload an image. This can be used for"},{"type":"text","text":" "},{"text":"identity verification and evidence disputes.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/uploadimage(_:purpose:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFilePurpose"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","url":"\/documentation\/stripepayments\/stpfilepurpose","abstract":[{"type":"text","text":"The purpose of the uploaded file."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFilePurpose","kind":"identifier"}],"title":"STPFilePurpose"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFileCompletionBlock":{"abstract":[{"text":"A callback to be run with a file response from the Stripe API.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPFileCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFileCompletionBlock","url":"\/documentation\/stripepayments\/stpfilecompletionblock","title":"STPFileCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"STPFileCompletionBlock","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"role":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title","value":"STPFilePurpose"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments","value":[{"text":"STPFilePurpose","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/navigatorTitle","value":[{"text":"STPFilePurpose","kind":"identifier"}]}]}]}