{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/verifyPaymentIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)"},"metadata":{"roleHeading":"Instance Method","extendedModule":"StripeCore","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"verifyPaymentIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"firstAmount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"secondAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent"}],"title":"verifyPaymentIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE36verifyPaymentIntentWithMicrodeposits12clientSecret11firstAmount06secondM0AD010STPPaymentG0CSS_S2itYaKF","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Verify a customer’s bank account with micro-deposits"},{"type":"text","text":" "},{"type":"text","text":"This function should only be called when the PaymentIntent is in the "},{"code":"requires_action","type":"codeVoice"},{"text":" ","type":"text"},{"text":"state and ","type":"text"},{"code":"next_action.type","type":"codeVoice"},{"text":" equals ","type":"text"},{"type":"codeVoice","code":"verify_with_microdeposits"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyPaymentIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"firstAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"secondAmount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","text":"STPPaymentIntent","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"type":"text","text":"The client secret of the PaymentIntent."}],"type":"paragraph"}]},{"name":"firstAmount","content":[{"type":"paragraph","inlineContent":[{"text":"The amount, in cents of USD, equal to the value of the first micro-deposit sent to the bank account.","type":"text"}]}]},{"name":"secondAmount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The amount, in cents of USD, equal to the value of the second micro-deposit sent to the bank account."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"The verified PaymentIntent object.","type":"text"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"aside","content":[{"inlineContent":[{"text":"The error that occurred making the Stripe API request.","type":"text"}],"type":"paragraph"}],"name":"Throws","style":"note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/verifypaymentintentwithmicrodeposits(clientsecret:firstamount:secondamount:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","type":"topic","title":"STPAPIClient","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/verifyPaymentIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)":{"abstract":[{"text":"Verify a customer’s bank account with micro-deposits","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This function should only be called when the PaymentIntent is in the "},{"code":"requires_action","type":"codeVoice"},{"text":" ","type":"text"},{"text":"state and ","type":"text"},{"code":"next_action.type","type":"codeVoice"},{"text":" equals ","type":"text"},{"code":"verify_with_microdeposits","type":"codeVoice"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/verifyPaymentIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyPaymentIntentWithMicrodeposits"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"firstAmount"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"secondAmount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"}],"title":"verifyPaymentIntentWithMicrodeposits(clientSecret:firstAmount:secondAmount:)","url":"\/documentation\/stripepayments\/stpapiclient\/verifypaymentintentwithmicrodeposits(clientsecret:firstamount:secondamount:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"title":"STPPaymentIntent","abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentIntent","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}