{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpapiclient\/verifysetupintentwithmicrodeposits(clientsecret:descriptorcode:)"]}],"metadata":{"role":"symbol","title":"verifySetupIntentWithMicrodeposits(clientSecret:descriptorCode:)","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE34verifySetupIntentWithMicrodeposits12clientSecret14descriptorCodeAD08STPSetupG0CSS_SStYaKF","symbolKind":"method","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"extendedModule":"StripeCore","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"verifySetupIntentWithMicrodeposits","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"descriptorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"}],"roleHeading":"Instance Method"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"verifySetupIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"descriptorCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","kind":"typeIdentifier"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The client secret of the SetupIntent.","type":"text"}],"type":"paragraph"}],"name":"clientSecret"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A unique, 6-digit descriptor code that starts with SM that was sent as statement descriptor to the bank account."}]}],"name":"descriptorCode"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The verified SetupIntent object."}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"content":[{"inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}],"type":"paragraph"}],"style":"note","name":"Throws","type":"aside"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/verifySetupIntentWithMicrodeposits(clientSecret:descriptorCode:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"abstract":[{"text":"Verify a customer’s bank account with micro-deposits","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This function should only be called when the PaymentIntent is in the "},{"type":"codeVoice","code":"requires_action"},{"type":"text","text":" "},{"type":"text","text":"state and "},{"type":"codeVoice","code":"next_action.type"},{"text":" equals ","type":"text"},{"type":"codeVoice","code":"verify_with_microdeposits"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/verifySetupIntentWithMicrodeposits(clientSecret:descriptorCode:)":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpapiclient\/verifysetupintentwithmicrodeposits(clientsecret:descriptorcode:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifySetupIntentWithMicrodeposits","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"descriptorCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"}],"abstract":[{"type":"text","text":"Verify a customer’s bank account with micro-deposits"},{"type":"text","text":" "},{"type":"text","text":"This function should only be called when the PaymentIntent is in the "},{"type":"codeVoice","code":"requires_action"},{"type":"text","text":" "},{"type":"text","text":"state and "},{"code":"next_action.type","type":"codeVoice"},{"text":" equals ","type":"text"},{"type":"codeVoice","code":"verify_with_microdeposits"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/verifySetupIntentWithMicrodeposits(clientSecret:descriptorCode:)","title":"verifySetupIntentWithMicrodeposits(clientSecret:descriptorCode:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","abstract":[{"text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSetupIntent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"title":"STPSetupIntent","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"title":"STPAPIClient","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPAPIClient","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIClient"}],"url":"\/documentation\/stripepayments\/stpapiclient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent","op":"replace"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"text":"STPSetupIntent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}