{"variants":[{"paths":["\/documentation\/stripepayments\/stpapiclient\/verifypaymentintentwithmicrodeposits(clientsecret:descriptorcode:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)","externalID":"s:10StripeCore12STPAPIClientC0A8PaymentsE36verifyPaymentIntentWithMicrodeposits12clientSecret14descriptorCodeAD010STPPaymentG0CSS_SStYaKF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyPaymentIntentWithMicrodeposits"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"descriptorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent"}],"role":"symbol","modules":[{"relatedModules":["StripeCore"],"name":"StripePayments"}],"symbolKind":"method","extendedModule":"StripeCore","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Verify a customer’s bank account with micro-deposits"},{"text":" ","type":"text"},{"type":"text","text":"This function should only be called when the PaymentIntent is in the "},{"type":"codeVoice","code":"requires_action"},{"text":" ","type":"text"},{"type":"text","text":"state and "},{"type":"codeVoice","code":"next_action.type"},{"text":" equals ","type":"text"},{"type":"codeVoice","code":"verify_with_microdeposits"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyPaymentIntentWithMicrodeposits","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"descriptorCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"kind":"keyword","text":"async"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","kind":"typeIdentifier","text":"STPPaymentIntent"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The client secret of the PaymentIntent.","type":"text"}]}],"name":"clientSecret"},{"name":"descriptorCode","content":[{"type":"paragraph","inlineContent":[{"text":"A unique, 6-digit descriptor code that starts with SM that was sent as statement descriptor to the bank account.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The verified PaymentIntent object.","type":"text"}]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"aside","style":"note","name":"Throws","content":[{"inlineContent":[{"type":"text","text":"The error that occurred making the Stripe API request."}],"type":"paragraph"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"url":"\/documentation\/stripepayments\/stppaymentintent","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"title":"STPPaymentIntent","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntent"}],"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient/verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)":{"kind":"symbol","type":"topic","title":"verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)","url":"\/documentation\/stripepayments\/stpapiclient\/verifypaymentintentwithmicrodeposits(clientsecret:descriptorcode:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"verifyPaymentIntentWithMicrodeposits","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"descriptorCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"}],"abstract":[{"type":"text","text":"Verify a customer’s bank account with micro-deposits"},{"text":" ","type":"text"},{"type":"text","text":"This function should only be called when the PaymentIntent is in the "},{"type":"codeVoice","code":"requires_action"},{"text":" ","type":"text"},{"type":"text","text":"state and "},{"code":"next_action.type","type":"codeVoice"},{"type":"text","text":" equals "},{"type":"codeVoice","code":"verify_with_microdeposits"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient\/verifyPaymentIntentWithMicrodeposits(clientSecret:descriptorCode:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIClient":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A client for making connections to the Stripe API."}],"navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"title":"STPAPIClient","type":"topic","url":"\/documentation\/stripepayments\/stpapiclient","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIClient"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPPaymentIntent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title"},{"value":[{"text":"STPPaymentIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments"},{"value":[{"text":"STPPaymentIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","op":"replace"}]}]}