{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui"]}],"metadata":{"role":"collection","title":"StripePaymentsUI","externalID":"StripePaymentsUI","symbolKind":"module","roleHeading":"Framework","modules":[{"name":"StripePaymentsUI"}]},"kind":"symbol","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"topicSections":[{"title":"Classes","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"],"anchor":"Classes"},{"title":"Protocols","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"],"anchor":"Protocols"},{"title":"Enumerations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle"],"anchor":"Enumerations"}],"hierarchy":{"paths":[[]]},"sections":[],"primaryContentSections":[{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"It contains:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/","isActive":true},{"type":"text","text":", a single-line interface for users to input their credit card details."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stpcardformview","type":"reference","isActive":true},{"type":"text","text":", a multi-line interface for users to input their credit card details."}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stpaubecsdebitformview"},{"type":"text","text":", a UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."}],"type":"paragraph"}]}]},{"type":"heading","level":2,"text":"Table of contents","anchor":"Table-of-contents"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"#Requirements"}]}]},{"content":[{"inlineContent":[{"identifier":"#Getting-started","type":"reference","isActive":true}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"#Integration"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#Example","type":"reference","isActive":true}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"identifier":"#Manual-linking","type":"reference","isActive":true}],"type":"paragraph"}]}]},{"type":"heading","level":2,"text":"Requirements","anchor":"Requirements"},{"inlineContent":[{"text":"The StripePaymentsUI module is compatible with apps targeting iOS 13.0 or above.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Getting started","anchor":"Getting-started"},{"type":"heading","level":3,"text":"Integration","anchor":"Integration"},{"inlineContent":[{"type":"text","text":"Get started with our "},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios&ui=custom","isActive":true},{"type":"text","text":" and "},{"type":"reference","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.3.1\/StripePaymentsUI\/\/Example","isActive":true},{"type":"text","text":", or "},{"type":"reference","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui","isActive":true},{"type":"text","text":" for fine-grained documentation of all the classes and methods in the SDK."}],"type":"paragraph"},{"type":"heading","level":3,"text":"Example","anchor":"Example"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/stripe-samples\/accept-a-payment\/tree\/main\/custom-payment-flow\/client\/ios-swiftui","type":"reference","isActive":true},{"text":" ","type":"text"},{"text":"– This example demonstrates how to collect payment information on iOS using ","type":"text"},{"type":"codeVoice","code":"STPPaymentCardTextField"},{"text":".","type":"text"}]}]}]},{"type":"heading","level":2,"text":"Manual linking","anchor":"Manual-linking"},{"inlineContent":[{"text":"If you link this library manually, use a version from our ","type":"text"},{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","isActive":true,"type":"reference"},{"text":" page and make sure to embed ","type":"text"},{"text":"all","type":"text"},{"text":" of the following frameworks:","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripeCore.xcframework"}]}]},{"content":[{"inlineContent":[{"code":"StripeUICore.xcframework","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"Stripe3DS2.xcframework"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripePayments.xcframework"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"StripePaymentsUI.xcframework"}],"type":"paragraph"}]}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"#Example":{"identifier":"#Example","title":"Example","type":"link","titleInlineContent":[{"type":"text","text":"Example"}],"url":"#Example"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview","type":"topic","title":"STPCardFormView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","abstract":[{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" provides a multiline interface for users to input their"},{"type":"text","text":" "},{"type":"text","text":"credit card details as well as billing postal code and provides an interface to access"},{"type":"text","text":" "},{"type":"text","text":"the created "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"type":"text","text":" "},{"type":"text","text":"is displayed when invalid input is detected."}],"role":"symbol"},"https://stripe.dev/stripe-ios/stripepaymentsui/documentation/stripepaymentsui":{"url":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui","type":"link","title":"📘 browse the SDK reference","titleInlineContent":[{"text":"📘 browse the SDK reference","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STP_Internal_CardBrandView":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STP_Internal_CardBrandView","type":"topic","title":"STP_Internal_CardBrandView","fragments":[{"kind":"identifier","text":"STP_Internal_CardBrandView"}],"url":"\/documentation\/stripepaymentsui\/stp_internal_cardbrandview","abstract":[{"text":"A view that displays a card brand icon\/logo, or an icon to help the user locate the CVC","type":"text"},{"text":" ","type":"text"},{"text":"for a specific card brand.","type":"text"},{"text":" ","type":"text"},{"text":"For internal SDK use only","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardNumberInputTextField":{"abstract":[],"kind":"symbol","title":"STPCardNumberInputTextField","role":"symbol","type":"topic","fragments":[{"text":"STPCardNumberInputTextField","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardNumberInputTextField","url":"\/documentation\/stripepaymentsui\/stpcardnumberinputtextfield"},"https://github.com/stripe/stripe-ios/tree/25.3.1/StripePaymentsUI//Example":{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.3.1\/StripePaymentsUI\/\/Example","title":"example projects","type":"link","titleInlineContent":[{"type":"text","text":"example projects"}],"url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.3.1\/StripePaymentsUI\/\/Example"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextField":{"role":"symbol","abstract":[],"url":"\/documentation\/stripepaymentsui\/stpformtextfield","fragments":[{"kind":"identifier","text":"STPFormTextField"}],"kind":"symbol","title":"STPFormTextField","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextField"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"abstract":[{"text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","title":"STPFormTextFieldContainer","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormTextFieldContainer"}],"navigatorTitle":[{"kind":"identifier","text":"STPFormTextFieldContainer"}]},"https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=custom":{"identifier":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios&ui=custom","title":"📚 integration guides","type":"link","titleInlineContent":[{"type":"text","text":"📚 integration guides"}],"url":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios&ui=custom"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPostalCodeInputTextField":{"url":"\/documentation\/stripepaymentsui\/stppostalcodeinputtextfield","kind":"symbol","title":"STPPostalCodeInputTextField","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"STPPostalCodeInputTextField"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPostalCodeInputTextField"},"#Integration":{"url":"#Integration","identifier":"#Integration","type":"link","title":"Integration","titleInlineContent":[{"type":"text","text":"Integration"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewDelegate":{"url":"\/documentation\/stripepaymentsui\/stpcardformviewdelegate","role":"symbol","title":"STPCardFormViewDelegate","navigatorTitle":[{"kind":"identifier","text":"STPCardFormViewDelegate"}],"type":"topic","kind":"symbol","abstract":[{"type":"codeVoice","code":"STPCardFormViewDelegate"},{"text":" defines the interface that should be adopted to receive","type":"text"},{"text":" ","type":"text"},{"text":"updates from ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"text":" instances.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormViewDelegate"}]},"https://github.com/stripe/stripe-ios/releases":{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","title":"releases","type":"link","titleInlineContent":[{"type":"text","text":"releases"}],"url":"https:\/\/github.com\/stripe\/stripe-ios\/releases"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"kind":"symbol","title":"STPPaymentCardTextField","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextField"}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","role":"symbol"},"#Getting-started":{"url":"#Getting-started","identifier":"#Getting-started","type":"link","title":"Getting started","titleInlineContent":[{"type":"text","text":"Getting started"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"role":"collection","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormView":{"navigatorTitle":[{"text":"STPFormView","kind":"identifier"}],"type":"topic","title":"STPFormView","url":"\/documentation\/stripepaymentsui\/stpformview","abstract":[{"type":"codeVoice","code":"STPFormView"},{"type":"text","text":" is a base class for the Stripe SDK’s form input UI. You should use one of the available subclasses"},{"type":"text","text":" "},{"type":"text","text":"("},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":") rather than instantiating an "},{"type":"codeVoice","code":"STPFormView"},{"type":"text","text":" instance directly."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormView","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPGenericInputPickerField":{"title":"STPGenericInputPickerField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPGenericInputPickerField","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpgenericinputpickerfield","fragments":[{"kind":"identifier","text":"STPGenericInputPickerField"}],"role":"symbol"},"#Manual-linking":{"identifier":"#Manual-linking","title":"Manual linking","type":"link","titleInlineContent":[{"type":"text","text":"Manual linking"}],"url":"#Manual-linking"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCountryPickerInputField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCountryPickerInputField","type":"topic","title":"STPCountryPickerInputField","abstract":[],"fragments":[{"text":"STPCountryPickerInputField","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpcountrypickerinputfield","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"This protocol allows a delegate to be notified when a payment text field’s"},{"type":"text","text":" "},{"type":"text","text":"contents change, which can in turn be used to take further actions depending"},{"type":"text","text":" "},{"type":"text","text":"on the validity of its contents."}],"navigatorTitle":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","title":"STPPaymentCardTextFieldDelegate","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPStringUtils":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPStringUtils","url":"\/documentation\/stripepaymentsui\/stpstringutils","fragments":[{"text":"STPStringUtils","kind":"identifier"}],"abstract":[],"type":"topic","title":"STPStringUtils"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFloatingPlaceholderTextField":{"url":"\/documentation\/stripepaymentsui\/stpfloatingplaceholdertextfield","title":"STPFloatingPlaceholderTextField","abstract":[{"text":"A ","type":"text"},{"text":"UITextField","type":"text"},{"text":" subclass that moves the placeholder text to the top leading side of the field","type":"text"},{"text":" ","type":"text"},{"text":"instead of hiding it upon text entry or editing.","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"STPFloatingPlaceholderTextField"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFloatingPlaceholderTextField","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/StripePaymentsUIVersionNumber":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/StripePaymentsUIVersionNumber","title":"StripePaymentsUIVersionNumber","abstract":[{"text":"Project version number for StripePaymentsUI.","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"StripePaymentsUIVersionNumber"}],"url":"\/documentation\/stripepaymentsui\/stripepaymentsuiversionnumber","type":"topic"},"https://stripe.dev/stripe-ios/stripepaymentsui/documentation/stripepaymentsui/stpaubecsdebitformview":{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stpaubecsdebitformview","title":"STPAUBECSDebitFormView","type":"link","url":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stpaubecsdebitformview","titleInlineContent":[{"type":"text","text":"STPAUBECSDebitFormView"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPhoneNumberValidator":{"title":"STPPhoneNumberValidator","url":"\/documentation\/stripepaymentsui\/stpphonenumbervalidator","role":"symbol","kind":"symbol","fragments":[{"text":"STPPhoneNumberValidator","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPhoneNumberValidator"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPostalCodeRequirement":{"type":"topic","url":"\/documentation\/stripepaymentsui\/stppostalcoderequirement","fragments":[{"text":"STPPostalCodeRequirement","kind":"identifier"}],"role":"symbol","title":"STPPostalCodeRequirement","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPostalCodeRequirement","kind":"symbol","abstract":[]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPValidatedTextField":{"type":"topic","abstract":[{"type":"text","text":"A UITextField that changes the text color, based on the validity of"},{"type":"text","text":" "},{"type":"text","text":"its contents."},{"type":"text","text":" "},{"type":"text","text":"This does "},{"type":"text","text":"not"},{"type":"text","text":" (currently?) have any logic or hooks for determining whether"},{"type":"text","text":" "},{"type":"text","text":"the contents are valid, that must be done by something else."}],"fragments":[{"text":"STPValidatedTextField","kind":"identifier"}],"title":"STPValidatedTextField","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpvalidatedtextfield","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPValidatedTextField"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"type":"text","text":" "},{"type":"text","text":"For additional customization options - seealso: STPFormTextFieldContainer"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","navigatorTitle":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"type":"topic","title":"STPAUBECSDebitFormView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"},"https://stripe.dev/stripe-ios/stripepaymentsui/documentation/stripepaymentsui/stpcardformview":{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stpcardformview","title":"STPCardFormView","type":"link","url":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stpcardformview","titleInlineContent":[{"type":"text","text":"STPCardFormView"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary":{"title":"STPImageLibrary","url":"\/documentation\/stripepaymentsui\/stpimagelibrary","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPImageLibrary"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPImageLibrary"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This class lets you access card icons used by the Stripe SDK. All icons are 32 x 20 points."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary"},"https://github.com/stripe-samples/accept-a-payment/tree/main/custom-payment-flow/client/ios-swiftui":{"identifier":"https:\/\/github.com\/stripe-samples\/accept-a-payment\/tree\/main\/custom-payment-flow\/client\/ios-swiftui","titleInlineContent":[{"type":"text","text":"Accept a Payment Example"}],"title":"Accept a Payment Example","url":"https:\/\/github.com\/stripe-samples\/accept-a-payment\/tree\/main\/custom-payment-flow\/client\/ios-swiftui","type":"link"},"#Requirements":{"identifier":"#Requirements","title":"Requirements","type":"link","url":"#Requirements","titleInlineContent":[{"type":"text","text":"Requirements"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPInputTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPInputTextField","title":"STPInputTextField","role":"symbol","url":"\/documentation\/stripepaymentsui\/stpinputtextfield","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"STPInputTextField"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPostalCodeValidator":{"type":"topic","url":"\/documentation\/stripepaymentsui\/stppostalcodevalidator","fragments":[{"text":"STPPostalCodeValidator","kind":"identifier"}],"role":"symbol","title":"STPPostalCodeValidator","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPostalCodeValidator","kind":"symbol","abstract":[]},"https://stripe.dev/stripe-ios/stripepaymentsui/documentation/stripepaymentsui/stppaymentcardtextfield/":{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/","title":"STPPaymentCardTextField","type":"link","url":"https:\/\/stripe.dev\/stripe-ios\/stripepaymentsui\/documentation\/stripepaymentsui\/stppaymentcardtextfield\/","titleInlineContent":[{"type":"text","text":"STPPaymentCardTextField"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/StripePaymentsUIVersionString":{"url":"\/documentation\/stripepaymentsui\/stripepaymentsuiversionstring","abstract":[{"type":"text","text":"Project version string for StripePaymentsUI."}],"kind":"symbol","title":"StripePaymentsUIVersionString","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/StripePaymentsUIVersionString","role":"symbol","fragments":[{"kind":"identifier","text":"StripePaymentsUIVersionString"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormViewDelegate":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"title":"STPAUBECSDebitFormViewDelegate","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate","type":"topic","abstract":[{"type":"text","text":"STPAUBECSDebitFormViewDelegate provides methods for STPAUBECSDebitFormView to inform its delegate"},{"type":"text","text":" "},{"type":"text","text":"of when the form has been completed."}],"navigatorTitle":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle":{"title":"STPCardFormViewStyle","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormViewStyle","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle","navigatorTitle":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","role":"symbol","abstract":[{"text":"Options for configuring the display of an ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"text":" instance.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardCVCInputTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardCVCInputTextField","kind":"symbol","role":"symbol","type":"topic","abstract":[],"title":"STPCardCVCInputTextField","fragments":[{"text":"STPCardCVCInputTextField","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpcardcvcinputtextfield"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMultiFormTextField","kind":"identifier"}],"navigatorTitle":[{"text":"STPMultiFormTextField","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","abstract":[{"type":"text","text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed."}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield","role":"symbol","title":"STPMultiFormTextField"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardCVCInputTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardNumberInputTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCountryPickerInputField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFloatingPlaceholderTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPGenericInputPickerField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPInputTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPhoneNumberValidator","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPostalCodeInputTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPostalCodeValidator","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPStringUtils","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPValidatedTextField","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STP_Internal_CardBrandView"],"anchor":"Classes","generated":true,"title":"Classes"},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewDelegate","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"],"anchor":"Protocols","generated":true,"title":"Protocols"},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/StripePaymentsUIVersionNumber","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/StripePaymentsUIVersionString"],"anchor":"Variables","generated":true,"title":"Variables"},{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPostalCodeRequirement"],"anchor":"Enumerations","generated":true,"title":"Enumerations"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"kind":"identifier","text":"STPCardFormView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFormView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title","value":"STPFormTextFieldContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments","value":[{"kind":"identifier","text":"STPFormTextFieldContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormTextFieldContainer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/title","value":"STPCardFormViewDelegate"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCardFormViewDelegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPCardFormViewDelegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace","value":"STPPaymentCardTextField"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/title","op":"replace","value":"STPFormView"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/fragments","op":"replace","value":[{"text":"STPFormView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormView\/navigatorTitle","op":"replace","value":[{"text":"STPFormView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title","op":"replace","value":"STPPaymentCardTextFieldDelegate"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments","op":"replace","value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title","op":"replace","value":"STPAUBECSDebitFormView"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments","op":"replace","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/title","op":"replace","value":"STPImageLibrary"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPImageLibrary"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/navigatorTitle","op":"replace","value":[{"text":"STPImageLibrary","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/title","op":"replace","value":"STPAUBECSDebitFormViewDelegate"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/title","op":"replace","value":"STPCardFormViewStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/fragments","op":"replace","value":[{"text":"STPCardFormViewStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPCardFormViewStyle"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","op":"replace","value":"STPMultiFormTextField"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPMultiFormTextField"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle","op":"replace","value":[{"text":"STPMultiFormTextField","kind":"identifier"}]}]}]}