{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(bankSelectionViewController:didCreatePaymentMethodParams:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bankSelectionViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bankViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPBankSelectionViewController","text":"STPBankSelectionViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethodParams"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"paymentMethodParams"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodParams","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"bankViewController","content":[{"inlineContent":[{"text":"the view controller that created the PaymentMethodParams","type":"text"}],"type":"paragraph"}]},{"name":"paymentMethodParams","content":[{"type":"paragraph","inlineContent":[{"text":"the PaymentMethodParams that was created. - seealso: STPPaymentMethodParams","type":"text"}]}]}],"kind":"parameters"}],"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate\/bankselectionviewcontroller(_:didcreatepaymentmethodparams:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate\/bankselectionviewcontroller(_:didcreatepaymentmethodparams:)"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@Stripe@objc(pl)STPBankSelectionViewControllerDelegate(im)bankSelectionViewController:didCreatePaymentMethodParams:","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankSelectionViewController"},{"kind":"text","text":"("},{"text":"STPBankSelectionViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPBankSelectionViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethodParams"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"bankSelectionViewController:didCreatePaymentMethodParams:","kind":"identifier"}],"role":"symbol","modules":[{"name":"Stripe"}],"title":"bankSelectionViewController(_:didCreatePaymentMethodParams:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate\/bankSelectionViewController(_:didCreatePaymentMethodParams:)"},"abstract":[{"text":"This is called when the user selects a bank.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You can use the returned PaymentMethodParams to confirm a PaymentIntent, or inspect"},{"type":"text","text":" "},{"type":"text","text":"it to obtain details about the selected bank."},{"type":"text","text":" "},{"type":"text","text":"Once you’re done, you’ll want to dismiss (or pop) the view controller."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethodParams":{"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodParams"}],"title":"STPPaymentMethodParams","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentmethodparams"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewControllerDelegate":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}],"title":"STPBankSelectionViewControllerDelegate","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPBankSelectionViewControllerDelegate"},{"type":"text","text":" is notified when a user selects a bank."}],"navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewControllerDelegate"}],"kind":"symbol","url":"\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewControllerDelegate/bankSelectionViewController(_:didCreatePaymentMethodParams:)":{"title":"bankSelectionViewController(_:didCreatePaymentMethodParams:)","required":true,"url":"\/documentation\/stripe\/stpbankselectionviewcontrollerdelegate\/bankselectionviewcontroller(_:didcreatepaymentmethodparams:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bankSelectionViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPBankSelectionViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPBankSelectionViewController"},{"kind":"text","text":", "},{"text":"didCreatePaymentMethodParams","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewControllerDelegate\/bankSelectionViewController(_:didCreatePaymentMethodParams:)","abstract":[{"text":"This is called when the user selects a bank.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can use the returned PaymentMethodParams to confirm a PaymentIntent, or inspect"},{"type":"text","text":" "},{"text":"it to obtain details about the selected bank.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Once you’re done, you’ll want to dismiss (or pop) the view controller."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bankSelectionViewController:didCreatePaymentMethodParams:"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionViewController":{"kind":"symbol","abstract":[{"type":"text","text":"This view controller displays a list of banks of the specified type, allowing the user to select one to pay from."},{"text":" ","type":"text"},{"text":"Once a bank is selected, it will return a PaymentMethodParams object, which you can use to confirm a PaymentIntent","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"or inspect to obtain details about the selected bank."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController","url":"\/documentation\/stripe\/stpbankselectionviewcontroller","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionViewController"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankSelectionViewController","kind":"identifier"}],"title":"STPBankSelectionViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bankSelectionViewController:didCreatePaymentMethodParams:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bankSelectionViewController:didCreatePaymentMethodParams:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"bankSelectionViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionViewController","text":"STPBankSelectionViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPBankSelectionViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"bankViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didCreatePaymentMethodParams:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paymentMethodParams","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"STPBankSelectionViewControllerDelegate","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate\/fragments","value":[{"text":"STPBankSelectionViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate~1bankSelectionViewController(_:didCreatePaymentMethodParams:)\/title","value":"bankSelectionViewController:didCreatePaymentMethodParams:"},{"value":[{"text":"- ","kind":"text"},{"text":"bankSelectionViewController:didCreatePaymentMethodParams:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewControllerDelegate~1bankSelectionViewController(_:didCreatePaymentMethodParams:)\/fragments","op":"replace"},{"op":"replace","value":"STPBankSelectionViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionViewController\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionViewController"}],"op":"replace"}]}]}
