{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPStringFromCardBrand"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpstringfromcardbrand\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","externalID":"c:@M@StripePayments@objc(cs)STPStringFromCardBrand(im)init","role":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"StripePayments"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPStringFromCardBrand\/init","interfaceLanguage":"occ"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPStringFromCardBrand/init":{"abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPStringFromCardBrand\/init","type":"topic","title":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/stripepayments\/stpstringfromcardbrand\/init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPStringFromCardBrand":{"title":"STPStringFromCardBrand","deprecated":true,"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPStringFromCardBrand","kind":"identifier"}],"abstract":[{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripepayments\/stpstringfromcardbrand","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPStringFromCardBrand"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPStringFromCardBrand"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPStringFromCardBrand\/title","op":"replace","value":"STPStringFromCardBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPStringFromCardBrand\/fragments","value":[{"text":"STPStringFromCardBrand","kind":"identifier"}]},{"value":[{"text":"STPStringFromCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPStringFromCardBrand\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}