{"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/!=(_:_:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/Equatable-Implementations"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Operator","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"relatedModules":["Swift"],"name":"StripePayments"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","role":"symbol","extendedModule":"Swift","symbolKind":"op"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/Equatable-Implementations","type":"topic","kind":"article","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/equatable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","abstract":[{"text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes.","type":"text"},{"text":" ","type":"text"},{"text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"}],"title":"STPPaymentIntentSetupFutureUsage"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/!=(_:_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/!=(_:_:)","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/!=(_:_:)","type":"topic","abstract":[],"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"patch":[{"value":"STPPaymentIntentSetupFutureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments","op":"replace","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}