{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/none","interfaceLanguage":"swift"},"metadata":{"title":"STPPaymentIntentSetupFutureUsage.none","role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageNone"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage@STPPaymentIntentSetupFutureUsageNone","symbolKind":"case"},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/none"]}],"sections":[],"abstract":[{"type":"text","text":"No value was provided."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/none":{"abstract":[{"type":"text","text":"No value was provided."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/none","role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsageNone","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/none","title":"STPPaymentIntentSetupFutureUsage.none"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","title":"STPPaymentIntentSetupFutureUsage","navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"abstract":[{"text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes.","type":"text"},{"text":" ","type":"text"},{"text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentSetupFutureUsageNone"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPPaymentIntentSetupFutureUsageNone","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPPaymentIntentSetupFutureUsageNone","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"STPPaymentIntentSetupFutureUsageNone","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1none\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1none\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageNone"}],"op":"replace"},{"value":"STPPaymentIntentSetupFutureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}