{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offSession"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/offSession"},"abstract":[{"text":"Indicates you intend to reuse the payment method when the customer may or may not be in your checkout flow.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/offsession"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/offsession"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage@STPPaymentIntentSetupFutureUsageOffSession","roleHeading":"Case","modules":[{"name":"StripePayments"}],"symbolKind":"case","title":"STPPaymentIntentSetupFutureUsage.offSession","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageOffSession"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offSession","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/offSession":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageOffSession"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/offSession","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offSession"}],"title":"STPPaymentIntentSetupFutureUsage.offSession","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/offsession","abstract":[{"text":"Indicates you intend to reuse the payment method when the customer may or may not be in your checkout flow.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"title":"STPPaymentIntentSetupFutureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","abstract":[{"type":"text","text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"type":"text","text":" "},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPPaymentIntentSetupFutureUsageOffSession","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPPaymentIntentSetupFutureUsageOffSession","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageOffSession"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentIntentSetupFutureUsageOffSession","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1offSession\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageOffSession"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1offSession\/fragments","op":"replace"},{"value":"STPPaymentIntentSetupFutureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}