{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSession"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/onsession"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/onsession"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsageOnSession","kind":"identifier"}],"title":"STPPaymentIntentSetupFutureUsage.onSession","roleHeading":"Case","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage@STPPaymentIntentSetupFutureUsageOnSession","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSession","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/onSession","interfaceLanguage":"swift"},"abstract":[{"text":"Indicates you intend to only reuse the payment method when the customer is in your checkout flow.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/onSession":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onSession","kind":"identifier"}],"title":"STPPaymentIntentSetupFutureUsage.onSession","navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsageOnSession","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/onSession","role":"symbol","abstract":[{"type":"text","text":"Indicates you intend to only reuse the payment method when the customer is in your checkout flow."}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/onsession"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"abstract":[{"type":"text","text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"type":"text","text":" "},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"role":"symbol","type":"topic","title":"STPPaymentIntentSetupFutureUsage","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentIntentSetupFutureUsageOnSession","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPPaymentIntentSetupFutureUsageOnSession","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageOnSession"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentIntentSetupFutureUsageOnSession","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1onSession\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageOnSession"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1onSession\/fragments"},{"op":"replace","value":"STPPaymentIntentSetupFutureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title"},{"op":"replace","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}