{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/rawrepresentable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/hashValue"],"anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/hash(into:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"API Collection","role":"collectionGroup","title":"RawRepresentable Implementations"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/hash(into:)":{"title":"hash(into:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/hash(into:)","kind":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/hash(into:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"type":"topic","title":"STPPaymentIntentSetupFutureUsage","abstract":[{"text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes.","type":"text"},{"text":" ","type":"text"},{"text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/hashValue":{"title":"hashValue","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/hashvalue","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/hashValue","role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPPaymentIntentSetupFutureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}