{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toCustomer"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"paymentMethod","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A valid Payment Method"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this callback when you’re done adding the payment method"},{"type":"text","text":" "},{"type":"text","text":"to the customer on your backend. For example, "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":" (if your call succeeds)"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" if an error is returned."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpbackendapiadapter\/attachpaymentmethod(tocustomer:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpbackendapiadapter\/attachpaymentmethod(tocustomer:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/attachPaymentMethod(toCustomer:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a Payment Method to a customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"type":"text","text":" "},{"type":"text","text":"Then, call the Attach method on the Payment Method with that customer’s ID"},{"type":"text","text":" "},{"type":"text","text":"( https:\/\/stripe.com\/docs\/api\/payment_methods\/attach ). If this API call succeeds,"},{"type":"text","text":" "},{"type":"text","text":"call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that"},{"type":"text","text":" "},{"type":"text","text":"occurred."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"attachPaymentMethodToCustomer:completion:"}],"role":"symbol","title":"attachPaymentMethod(toCustomer:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toCustomer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter(im)attachPaymentMethodToCustomer:completion:","required":true,"modules":[{"name":"Stripe"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethod":{"role":"symbol","title":"STPPaymentMethod","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"url":"\/documentation\/stripe\/stppaymentmethod"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"role":"symbol","title":"STPBackendAPIAdapter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBackendAPIAdapter"}],"abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which implements "},{"type":"text","text":" "},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"url":"\/documentation\/stripe\/stpbackendapiadapter"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/attachPaymentMethod(toCustomer:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"attachPaymentMethodToCustomer:completion:"}],"role":"symbol","title":"attachPaymentMethod(toCustomer:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachPaymentMethod"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toCustomer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Adds a Payment Method to a customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"type":"text","text":" "},{"type":"text","text":"Then, call the Attach method on the Payment Method with that customer’s ID"},{"type":"text","text":" "},{"type":"text","text":"( https:\/\/stripe.com\/docs\/api\/payment_methods\/attach ). If this API call succeeds,"},{"type":"text","text":" "},{"type":"text","text":"call "},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that"},{"type":"text","text":" "},{"type":"text","text":"occurred."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/attachPaymentMethod(toCustomer:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpbackendapiadapter\/attachpaymentmethod(tocustomer:completion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"role":"symbol","title":"STPErrorBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPErrorBlock"}],"url":"\/documentation\/stripe\/stperrorblock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"attachPaymentMethodToCustomer:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"attachPaymentMethodToCustomer:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"attachPaymentMethodToCustomer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title","value":"STPBackendAPIAdapter"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1attachPaymentMethod(toCustomer:completion:)\/title","value":"attachPaymentMethodToCustomer:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1attachPaymentMethod(toCustomer:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"attachPaymentMethodToCustomer:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
