{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Deletes the given Payment Method from the customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"text":" ","type":"text"},{"text":"Call the Detach method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/detach )","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"on the Payment Method. If this API call succeeds, call "},{"code":"completion(nil)","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"text":" with the error that occurred.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/detachPaymentMethod(fromCustomer:completion:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detachPaymentMethod"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromCustomer"},{"kind":"text","text":" "},{"text":"paymentMethod","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","text":"STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The Payment Method to delete from the customer","type":"text"}]}],"name":"paymentMethod"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Call this callback when you’re done deleting the Payment Method"},{"text":" ","type":"text"},{"type":"text","text":"from the customer on your backend. For example, "},{"type":"codeVoice","code":"completion(nil)"},{"text":" (if your call","type":"text"},{"type":"text","text":" "},{"text":"succeeds) or ","type":"text"},{"type":"codeVoice","code":"completion(error)"},{"text":" if an error is returned.","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter"]]},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"detachPaymentMethodFromCustomer:completion:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"detachPaymentMethod","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromCustomer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"required":true,"title":"detachPaymentMethod(fromCustomer:completion:)","modules":[{"name":"Stripe"}],"symbolKind":"method","externalID":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter(im)detachPaymentMethodFromCustomer:completion:","role":"symbol"},"variants":[{"paths":["\/documentation\/stripe\/stpbackendapiadapter\/detachpaymentmethod(fromcustomer:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbackendapiadapter\/detachpaymentmethod(fromcustomer:completion:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"type":"topic","title":"STPErrorBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"navigatorTitle":[{"text":"STPErrorBlock","kind":"identifier"}],"url":"\/documentation\/stripe\/stperrorblock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"abstract":[{"text":"A “bridge” from our pre-built UI (","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"text":" ","type":"text"},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"text":" ","type":"text"},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":", which implements ","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"title":"STPBackendAPIAdapter","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPBackendAPIAdapter","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol","url":"\/documentation\/stripe\/stpbackendapiadapter"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethod":{"abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","role":"symbol","title":"STPPaymentMethod","url":"\/documentation\/stripe\/stppaymentmethod","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethod"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethod"}],"kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/detachPaymentMethod(fromCustomer:completion:)":{"kind":"symbol","url":"\/documentation\/stripe\/stpbackendapiadapter\/detachpaymentmethod(fromcustomer:completion:)","abstract":[{"type":"text","text":"Deletes the given Payment Method from the customer."},{"text":" ","type":"text"},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"text":"Call the Detach method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/detach )","type":"text"},{"type":"text","text":" "},{"text":"on the Payment Method. If this API call succeeds, call ","type":"text"},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"type":"topic","title":"detachPaymentMethod(fromCustomer:completion:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/detachPaymentMethod(fromCustomer:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachPaymentMethod"},{"text":"(","kind":"text"},{"text":"fromCustomer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"detachPaymentMethodFromCustomer:completion:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"detachPaymentMethodFromCustomer:completion:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"detachPaymentMethodFromCustomer:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"detachPaymentMethodFromCustomer:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"STPBackendAPIAdapter","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"op":"replace"},{"op":"replace","value":"detachPaymentMethodFromCustomer:completion:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1detachPaymentMethod(fromCustomer:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"detachPaymentMethodFromCustomer:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1detachPaymentMethod(fromCustomer:completion:)\/fragments","op":"replace"}]}]}
