{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPaymentMethodsForCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodsCompletionBlock","preciseIdentifier":"s:14StripePayments32STPPaymentMethodsCompletionBlocka","text":"STPPaymentMethodsCompletionBlock"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this callback with the list of Payment Methods attached to the"},{"type":"text","text":" "},{"type":"text","text":"customer.  For example, "},{"type":"codeVoice","code":"completion(paymentMethods)"},{"type":"text","text":" (if your call succeeds) or"},{"type":"text","text":" "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" if an error is returned."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpbackendapiadapter\/listpaymentmethodsforcustomer(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpbackendapiadapter\/listpaymentmethodsforcustomer(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/listPaymentMethodsForCustomer(completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Retrieves a list of Payment Methods attached to a customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"Call the list method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/list )"},{"type":"text","text":" "},{"type":"text","text":"with the Stripe customer. If this API call succeeds, call "},{"type":"codeVoice","code":"completion(paymentMethods)"},{"type":"text","text":" "},{"type":"text","text":"with the list of PaymentMethods. Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error"},{"type":"text","text":" "},{"type":"text","text":"that occurred."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}],"role":"symbol","title":"listPaymentMethodsForCustomer(completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPaymentMethodsForCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodsCompletionBlock","preciseIdentifier":"s:14StripePayments32STPPaymentMethodsCompletionBlocka"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter(im)listPaymentMethodsForCustomerWithCompletion:","required":true,"modules":[{"name":"Stripe"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethodsCompletionBlock":{"role":"symbol","title":"STPPaymentMethodsCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodsCompletionBlock"}],"abstract":[{"type":"text","text":"A callback to be run with an array of PaymentMethods response from the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethodsCompletionBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodsCompletionBlock"}],"url":"\/documentation\/stripe\/stppaymentmethodscompletionblock"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"role":"symbol","title":"STPBackendAPIAdapter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBackendAPIAdapter"}],"abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which implements "},{"type":"text","text":" "},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"url":"\/documentation\/stripe\/stpbackendapiadapter"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/listPaymentMethodsForCustomer(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}],"role":"symbol","title":"listPaymentMethodsForCustomer(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"listPaymentMethodsForCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodsCompletionBlock","preciseIdentifier":"s:14StripePayments32STPPaymentMethodsCompletionBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Retrieves a list of Payment Methods attached to a customer."},{"type":"text","text":" "},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"Call the list method ( https:\/\/stripe.com\/docs\/api\/payment_methods\/list )"},{"type":"text","text":" "},{"type":"text","text":"with the Stripe customer. If this API call succeeds, call "},{"type":"codeVoice","code":"completion(paymentMethods)"},{"type":"text","text":" "},{"type":"text","text":"with the list of PaymentMethods. Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error"},{"type":"text","text":" "},{"type":"text","text":"that occurred."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/listPaymentMethodsForCustomer(completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/stripe\/stpbackendapiadapter\/listpaymentmethodsforcustomer(completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"listPaymentMethodsForCustomerWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSArray<STPPaymentMethod *> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title","value":"STPBackendAPIAdapter"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1listPaymentMethodsForCustomer(completion:)\/title","value":"listPaymentMethodsForCustomerWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1listPaymentMethodsForCustomer(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"listPaymentMethodsForCustomerWithCompletion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
