{"metadata":{"navigatorTitle":[{"text":"retrieveCustomer:","kind":"identifier"}],"title":"retrieveCustomer(_:)","role":"symbol","symbolKind":"method","required":true,"externalID":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter(im)retrieveCustomer:","modules":[{"name":"Stripe"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrieveCustomer"},{"text":"(","kind":"text"},{"text":"STPCustomerCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments26STPCustomerCompletionBlocka"},{"text":"?)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"retrieveCustomer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments26STPCustomerCompletionBlocka","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerCompletionBlock","text":"STPCustomerCompletionBlock"},{"text":"?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call this callback when you’re done fetching and parsing the above information from your backend. For example, "},{"type":"codeVoice","code":"completion(customer, nil)"},{"type":"text","text":" (if your call succeeds) or "},{"code":"completion(nil, error)","type":"codeVoice"},{"type":"text","text":" if an error is returned."}]}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"content":[{"inlineContent":[{"text":"STPCard","type":"text"}],"type":"paragraph"}],"name":"See Also","type":"aside","style":"note"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripe\/stpbackendapiadapter\/retrievecustomer(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpbackendapiadapter\/retrievecustomer(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Retrieve the customer to be displayed inside a payment context."},{"type":"text","text":" "},{"type":"text","text":"If you are not using STPCustomerContext:"},{"text":" ","type":"text"},{"text":"On your backend, retrieve the Stripe customer associated with your currently","type":"text"},{"text":" ","type":"text"},{"text":"logged-in user ( https:\/\/stripe.com\/docs\/api#retrieve_customer ), and return","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the raw JSON response from the Stripe API. Back in your iOS app, after you’ve"},{"type":"text","text":" "},{"text":"called this API, deserialize your API response into an ","type":"text"},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" object"},{"text":" ","type":"text"},{"type":"text","text":"(you can use the "},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"text":" class to do this).","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/retrieveCustomer(_:)"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/retrieveCustomer(_:)":{"abstract":[{"type":"text","text":"Retrieve the customer to be displayed inside a payment context."},{"text":" ","type":"text"},{"type":"text","text":"If you are not using STPCustomerContext:"},{"type":"text","text":" "},{"text":"On your backend, retrieve the Stripe customer associated with your currently","type":"text"},{"type":"text","text":" "},{"text":"logged-in user ( https:\/\/stripe.com\/docs\/api#retrieve_customer ), and return","type":"text"},{"type":"text","text":" "},{"text":"the raw JSON response from the Stripe API. Back in your iOS app, after you’ve","type":"text"},{"type":"text","text":" "},{"type":"text","text":"called this API, deserialize your API response into an "},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" object"},{"type":"text","text":" "},{"type":"text","text":"(you can use the "},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"text":" class to do this).","type":"text"}],"role":"symbol","url":"\/documentation\/stripe\/stpbackendapiadapter\/retrievecustomer(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"retrieveCustomer","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPCustomerCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments26STPCustomerCompletionBlocka"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"retrieveCustomer:"}],"title":"retrieveCustomer(_:)","required":true,"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/retrieveCustomer(_:)"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPBackendAPIAdapter","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripe\/stpbackendapiadapter","title":"STPBackendAPIAdapter","abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":", which implements "},{"text":" ","type":"text"},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerCompletionBlock":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerCompletionBlock","title":"STPCustomerCompletionBlock","abstract":[{"type":"text","text":"A callback to be run with a customer response from the Stripe API."}],"role":"symbol","navigatorTitle":[{"text":"STPCustomerCompletionBlock","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"STPCustomerCompletionBlock","kind":"identifier"}],"url":"\/documentation\/stripe\/stpcustomercompletionblock"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"retrieveCustomer:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"retrieveCustomer:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"retrieveCustomer:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$@M@StripePayments@objc(cs)STPCustomer#*$objc(cs)NSError)","text":"void (^)(STPCustomer *, NSError *)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1retrieveCustomer(_:)\/title","op":"replace","value":"retrieveCustomer:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"retrieveCustomer:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1retrieveCustomer(_:)\/fragments"},{"value":"STPBackendAPIAdapter","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title"},{"value":[{"text":"STPBackendAPIAdapter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments"}]}]}
