{"abstract":[{"text":"Sets the given shipping address on the customer.","type":"text"},{"text":" ","type":"text"},{"text":"If you are implementing your own ","type":"text"},{"text":":","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"text":" ","type":"text"},{"text":"Then, call the Customer Update method ( https:\/\/stripe.com\/docs\/api#update_customer )","type":"text"},{"type":"text","text":" "},{"type":"text","text":"specifying shipping to be the given shipping address. If this API call succeeds,"},{"type":"text","text":" "},{"text":"call ","type":"text"},{"code":"completion(nil)","type":"codeVoice"},{"text":". Otherwise, call ","type":"text"},{"code":"completion(error)","type":"codeVoice"},{"type":"text","text":" with the error that occurred."}],"metadata":{"modules":[{"name":"Stripe"}],"title":"updateCustomer(withShippingAddress:completion:)","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateCustomer","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withShippingAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","text":"STPAddress"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"updateCustomerWithShippingAddress:completion:"}],"required":true,"externalID":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter(im)updateCustomerWithShippingAddress:completion:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateCustomer"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withShippingAddress"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"shipping"},{"kind":"text","text":": "},{"text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPErrorBlock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"shipping","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The shipping address to set on the customer"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"call this callback when you’re done updating the customer on"},{"type":"text","text":" "},{"text":"your backend. For example, ","type":"text"},{"code":"completion(nil)","type":"codeVoice"},{"type":"text","text":" (if your call succeeds) or"},{"type":"text","text":" "},{"code":"completion(error)","type":"codeVoice"},{"type":"text","text":" if an error is returned."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"https:\/\/stripe.com\/docs\/api#update_customer"}],"type":"paragraph"}],"name":"See Also","style":"note"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/updateCustomer(withShippingAddress:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpbackendapiadapter\/updatecustomer(withshippingaddress:completion:)"]},{"paths":["\/documentation\/stripe\/stpbackendapiadapter\/updatecustomer(withshippingaddress:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter/updateCustomer(withShippingAddress:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter\/updateCustomer(withShippingAddress:completion:)","title":"updateCustomer(withShippingAddress:completion:)","url":"\/documentation\/stripe\/stpbackendapiadapter\/updatecustomer(withshippingaddress:completion:)","abstract":[{"type":"text","text":"Sets the given shipping address on the customer."},{"text":" ","type":"text"},{"type":"text","text":"If you are implementing your own "},{"type":"text","text":":"},{"type":"text","text":" "},{"type":"text","text":"On your backend, retrieve the Stripe customer associated with your logged-in user."},{"text":" ","type":"text"},{"type":"text","text":"Then, call the Customer Update method ( https:\/\/stripe.com\/docs\/api#update_customer )"},{"text":" ","type":"text"},{"text":"specifying shipping to be the given shipping address. If this API call succeeds,","type":"text"},{"type":"text","text":" "},{"text":"call ","type":"text"},{"type":"codeVoice","code":"completion(nil)"},{"type":"text","text":". Otherwise, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":" with the error that occurred."}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateCustomer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withShippingAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments13STPErrorBlocka","text":"STPErrorBlock"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"updateCustomerWithShippingAddress:completion:","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"abstract":[{"text":"A “bridge” from our pre-built UI (","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"text":" ","type":"text"},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"text":" ","type":"text"},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":", which implements ","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"title":"STPBackendAPIAdapter","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPBackendAPIAdapter","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol","url":"\/documentation\/stripe\/stpbackendapiadapter"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"type":"topic","title":"STPErrorBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPErrorBlock"}],"abstract":[{"type":"text","text":"A block that may optionally be called with an error."}],"navigatorTitle":[{"text":"STPErrorBlock","kind":"identifier"}],"url":"\/documentation\/stripe\/stperrorblock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddress":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAddress"}],"navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"url":"\/documentation\/stripe\/stpaddress","role":"symbol","title":"STPAddress","type":"topic","abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"updateCustomerWithShippingAddress:completion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"updateCustomerWithShippingAddress:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateCustomerWithShippingAddress:"},{"text":"(","kind":"text"},{"text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddress"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"shipping"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void (^)(NSError *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1updateCustomer(withShippingAddress:completion:)\/title","value":"updateCustomerWithShippingAddress:completion:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCustomerWithShippingAddress:completion:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter~1updateCustomer(withShippingAddress:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title","value":"STPBackendAPIAdapter"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","value":[{"kind":"identifier","text":"STPBackendAPIAdapter"}]}]}]}
