{"metadata":{"roleHeading":"Instance Property","title":"bankAccount","navigatorTitle":[{"text":"bankAccount","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPToken(py)bankAccount","modules":[{"name":"StripePayments"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bankAccount"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccount","text":"STPBankAccount","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/bankAccount"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stptoken\/bankaccount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stptoken\/bankaccount"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bankAccount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","text":"STPBankAccount","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccount"},{"text":"? { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"The bank account details that were used to create the token. Will only be set if the token was created with a bank account, otherwise it will be nil."}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/bankAccount":{"abstract":[{"type":"text","text":"The bank account details that were used to create the token. Will only be set if the token was created with a bank account, otherwise it will be nil."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bankAccount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPBankAccount","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccount"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/bankAccount","type":"topic","url":"\/documentation\/stripepayments\/stptoken\/bankaccount","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"bankAccount","kind":"identifier"}],"title":"bankAccount"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","url":"\/documentation\/stripepayments\/stpbankaccount","navigatorTitle":[{"text":"STPBankAccount","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Representation of a user’s bank account details that have been tokenized with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the Stripe API."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPBankAccount","kind":"identifier"}],"title":"STPBankAccount"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","title":"STPToken","abstract":[{"type":"text","text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly."}],"kind":"symbol","navigatorTitle":[{"text":"STPToken","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stptoken","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPToken","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bankAccount","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bankAccount"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"STPBankAccount","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccount","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bankAccount","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"bankAccount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1bankAccount\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bankAccount"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1bankAccount\/fragments","op":"replace"},{"value":"STPBankAccount","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/fragments","value":[{"kind":"identifier","text":"STPBankAccount"}]},{"value":[{"text":"STPBankAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/navigatorTitle","op":"replace"},{"value":"STPToken","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","value":[{"kind":"identifier","text":"STPToken"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle","value":[{"kind":"identifier","text":"STPToken"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}