{"abstract":[{"text":"The credit card details that were used to create the token. Will only be set if the token was created via a credit card or Apple Pay, otherwise it will be","type":"text"},{"type":"text","text":" "},{"text":"nil.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"},{"text":": ","kind":"text"},{"text":"STPCard","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken"]]},"kind":"symbol","metadata":{"title":"card","symbolKind":"property","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"card","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCard","text":"STPCard"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPToken(py)card","navigatorTitle":[{"kind":"identifier","text":"card"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/card"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stptoken\/card"]},{"paths":["\/documentation\/stripepayments\/stptoken\/card"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/card":{"url":"\/documentation\/stripepayments\/stptoken\/card","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"card","kind":"identifier"}],"abstract":[{"type":"text","text":"The credit card details that were used to create the token. Will only be set if the token was created via a credit card or Apple Pay, otherwise it will be"},{"type":"text","text":" "},{"type":"text","text":"nil."}],"title":"card","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/card","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"},{"kind":"text","text":": "},{"text":"STPCard","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCard","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPToken"}],"navigatorTitle":[{"kind":"identifier","text":"STPToken"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","title":"STPToken","url":"\/documentation\/stripepayments\/stptoken","abstract":[{"type":"text","text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly."}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCard","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpcard","navigatorTitle":[{"text":"STPCard","kind":"identifier"}],"title":"STPCard","type":"topic","abstract":[{"type":"text","text":"Representation of a user’s credit card details that have been tokenized with"},{"text":" ","type":"text"},{"type":"text","text":"the Stripe API"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"card","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"card","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPCard","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"},{"kind":"text","text":" * "},{"kind":"identifier","text":"card"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"card","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1card\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1card\/fragments","op":"replace","value":[{"text":"card","kind":"identifier"}]},{"value":"STPToken","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle","value":[{"kind":"identifier","text":"STPToken"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/title","value":"STPCard","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/fragments","value":[{"kind":"identifier","text":"STPCard"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/navigatorTitle","value":[{"text":"STPCard","kind":"identifier"}],"op":"replace"}]}]}