{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/type","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPTokenType","kind":"typeIdentifier","text":"STPTokenType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType"},{"kind":"text","text":" { get }"}],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stptoken\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stptoken\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPTokenType","text":"STPTokenType"}],"symbolKind":"property","title":"type","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPToken(py)type","navigatorTitle":[{"kind":"identifier","text":"type"}]},"abstract":[{"type":"text","text":"The type of this token."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","url":"\/documentation\/stripepayments\/stptokentype","abstract":[{"type":"text","text":"Possible Token types"}],"title":"STPTokenType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTokenType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPTokenType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/type":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/type","role":"symbol","abstract":[{"text":"The type of this token.","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"type":"topic","kind":"symbol","title":"type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPTokenType","text":"STPTokenType","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPToken"}],"navigatorTitle":[{"kind":"identifier","text":"STPToken"}],"title":"STPToken","type":"topic","abstract":[{"type":"text","text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","url":"\/documentation\/stripepayments\/stptoken","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","preciseIdentifier":"c:@M@StripePayments@E@STPTokenType","text":"STPTokenType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/title","op":"replace","value":"STPTokenType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/fragments","op":"replace","value":[{"text":"STPTokenType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPTokenType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1type\/title","op":"replace","value":"type"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1type\/fragments","op":"replace","value":[{"text":"type","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title","op":"replace","value":"STPToken"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPToken"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle","op":"replace","value":[{"text":"STPToken","kind":"identifier"}]}]}]}