{"metadata":{"modules":[{"name":"Stripe"}],"symbolKind":"case","title":"STPBankSelectionMethod.FPX","externalID":"c:@M@Stripe@E@STPBankSelectionMethod@STPBankSelectionMethodFPX","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FPX","kind":"identifier"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionMethodFPX"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"FPX (Malaysia)"}],"variants":[{"paths":["\/documentation\/stripe\/stpbankselectionmethod\/fpx"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpbankselectionmethod\/fpx"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FPX"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/FPX"},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod/FPX":{"navigatorTitle":[{"text":"STPBankSelectionMethodFPX","kind":"identifier"}],"title":"STPBankSelectionMethod.FPX","url":"\/documentation\/stripe\/stpbankselectionmethod\/fpx","kind":"symbol","abstract":[{"type":"text","text":"FPX (Malaysia)"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FPX"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/FPX","type":"topic","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod":{"title":"STPBankSelectionMethod","abstract":[{"text":"The payment methods supported by STPBankSelectionViewController.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPBankSelectionMethod","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPBankSelectionMethod","kind":"identifier"}],"url":"\/documentation\/stripe\/stpbankselectionmethod","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPBankSelectionMethodFPX"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionMethodFPX"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPBankSelectionMethodFPX"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod~1FPX\/title","value":"STPBankSelectionMethodFPX"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod~1FPX\/fragments","value":[{"text":"STPBankSelectionMethodFPX","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/title","value":"STPBankSelectionMethod"},{"value":[{"kind":"identifier","text":"STPBankSelectionMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
