{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/unknown","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod"]]},"kind":"symbol","metadata":{"title":"STPBankSelectionMethod.unknown","modules":[{"name":"Stripe"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"externalID":"c:@M@Stripe@E@STPBankSelectionMethod@STPBankSelectionMethodUnknown","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"STPBankSelectionMethodUnknown","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpbankselectionmethod\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpbankselectionmethod\/unknown"]}],"sections":[],"abstract":[{"type":"text","text":"An unknown payment method"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPBankSelectionMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"The payment methods supported by STPBankSelectionViewController."}],"title":"STPBankSelectionMethod","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod","url":"\/documentation\/stripe\/stpbankselectionmethod","navigatorTitle":[{"text":"STPBankSelectionMethod","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBankSelectionMethod/unknown":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBankSelectionMethod\/unknown","navigatorTitle":[{"kind":"identifier","text":"STPBankSelectionMethodUnknown"}],"kind":"symbol","role":"symbol","title":"STPBankSelectionMethod.unknown","url":"\/documentation\/stripe\/stpbankselectionmethod\/unknown","abstract":[{"type":"text","text":"An unknown payment method"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPBankSelectionMethodUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"STPBankSelectionMethodUnknown"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"STPBankSelectionMethodUnknown","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/title","value":"STPBankSelectionMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod\/fragments","value":[{"text":"STPBankSelectionMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod~1unknown\/title","op":"replace","value":"STPBankSelectionMethodUnknown"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBankSelectionMethod~1unknown\/fragments","value":[{"kind":"identifier","text":"STPBankSelectionMethodUnknown"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
