{"kind":"symbol","metadata":{"symbolKind":"init","title":"init(itemType:itemDescription:quantity:totalAmount:)","navigatorTitle":[{"text":"initWithItemType:itemDescription:quantity:totalAmount:","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"itemType"},{"kind":"text","text":": "},{"text":"STPKlarnaLineItemType","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"itemDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"quantity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"totalAmount"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem(im)initWithItemType:itemDescription:quantity:totalAmount:","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem"]]},"abstract":[{"type":"text","text":"Initialize this "},{"type":"codeVoice","code":"STPKlarnaLineItem"},{"text":" with a set of parameters.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitem\/init(itemtype:itemdescription:quantity:totalamount:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitem\/init(itemtype:itemdescription:quantity:totalamount:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"itemType","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","text":"STPKlarnaLineItemType","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"itemDescription","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"quantity"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalAmount"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"name":"itemType","content":[{"type":"paragraph","inlineContent":[{"text":"The line item’s type.","type":"text"}]}]},{"name":"itemDescription","content":[{"inlineContent":[{"type":"text","text":"The human-readable description for the line item."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The quantity to display for this line item."}],"type":"paragraph"}],"name":"quantity"},{"name":"totalAmount","content":[{"type":"paragraph","inlineContent":[{"text":"The total price of this line item.","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/init(itemType:itemDescription:quantity:totalAmount:)"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","title":"STPKlarnaLineItem","url":"\/documentation\/stripepayments\/stpklarnalineitem","abstract":[{"text":"An object representing a line item in a Klarna source.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItem"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/init(itemType:itemDescription:quantity:totalAmount:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/init(itemType:itemDescription:quantity:totalAmount:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"itemType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType","text":"STPKlarnaLineItemType"},{"text":", ","kind":"text"},{"text":"itemDescription","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"quantity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":", "},{"text":"totalAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(itemType:itemDescription:quantity:totalAmount:)","url":"\/documentation\/stripepayments\/stpklarnalineitem\/init(itemtype:itemdescription:quantity:totalamount:)","navigatorTitle":[{"kind":"identifier","text":"initWithItemType:itemDescription:quantity:totalAmount:"}],"type":"topic","kind":"symbol","abstract":[{"text":"Initialize this ","type":"text"},{"code":"STPKlarnaLineItem","type":"codeVoice"},{"text":" with a set of parameters.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItemType"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpklarnalineitemtype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","role":"symbol","abstract":[{"type":"text","text":"The type of the Klarna line item."}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"type":"topic","title":"STPKlarnaLineItemType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithItemType:itemDescription:quantity:totalAmount:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithItemType:itemDescription:quantity:totalAmount:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithItemType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","kind":"typeIdentifier","text":"STPKlarnaLineItemType"},{"text":") ","kind":"text"},{"text":"itemType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"itemDescription:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"itemDescription","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"quantity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"quantity","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalAmount:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"totalAmount"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The line item’s type.","type":"text"}]}],"name":"itemType"},{"name":"itemDescription","content":[{"type":"paragraph","inlineContent":[{"text":"The human-readable description for the line item.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The quantity to display for this line item."}],"type":"paragraph"}],"name":"quantity"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The total price of this line item.","type":"text"}]}],"name":"totalAmount"}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title","op":"replace","value":"STPKlarnaLineItem"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments","value":[{"text":"STPKlarnaLineItem","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPKlarnaLineItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/navigatorTitle"},{"op":"replace","value":"initWithItemType:itemDescription:quantity:totalAmount:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1init(itemType:itemDescription:quantity:totalAmount:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1init(itemType:itemDescription:quantity:totalAmount:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithItemType:itemDescription:quantity:totalAmount:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","value":"STPKlarnaLineItemType"},{"value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/navigatorTitle","value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"op":"replace"}]}]}