{"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpklarnalineitem\/itemtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitem\/itemtype"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/itemType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The line item’s type. One of "},{"type":"codeVoice","code":"sku"},{"type":"text","text":" (for a product), "},{"type":"codeVoice","code":"tax"},{"type":"text","text":" (for taxes), or "},{"type":"codeVoice","code":"shipping"},{"type":"text","text":" (for shipping costs)."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"itemType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","text":"STPKlarnaLineItemType","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"StripePayments"}],"title":"itemType","navigatorTitle":[{"text":"itemType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"itemType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPKlarnaLineItemType","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem(py)itemType"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"title":"STPKlarnaLineItem","url":"\/documentation\/stripepayments\/stpklarnalineitem","abstract":[{"type":"text","text":"An object representing a line item in a Klarna source."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItem"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"kind":"symbol","title":"STPKlarnaLineItemType","navigatorTitle":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItemType"}],"url":"\/documentation\/stripepayments\/stpklarnalineitemtype","role":"symbol","abstract":[{"type":"text","text":"The type of the Klarna line item."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/itemType":{"abstract":[{"type":"text","text":"The line item’s type. One of "},{"type":"codeVoice","code":"sku"},{"type":"text","text":" (for a product), "},{"code":"tax","type":"codeVoice"},{"text":" (for taxes), or ","type":"text"},{"type":"codeVoice","code":"shipping"},{"text":" (for shipping costs).","type":"text"}],"role":"symbol","title":"itemType","navigatorTitle":[{"text":"itemType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/itemType","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"itemType","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPKlarnaLineItemType","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpklarnalineitem\/itemtype"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"itemType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"itemType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPKlarnaLineItemType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPKlarnaLineItem","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments","value":[{"text":"STPKlarnaLineItem","kind":"identifier"}]},{"value":[{"text":"STPKlarnaLineItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","op":"replace","value":"STPKlarnaLineItemType"},{"value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments"},{"value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1itemType\/title","value":"itemType"},{"value":[{"kind":"identifier","text":"itemType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1itemType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}