{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpklarnalineitem\/quantity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpklarnalineitem\/quantity"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/quantity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The quantity to display for this line item."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"title":"quantity","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem(py)quantity","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"quantity"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/quantity":{"role":"symbol","title":"quantity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"quantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"abstract":[{"type":"text","text":"The quantity to display for this line item."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/quantity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"quantity"}],"url":"\/documentation\/stripepayments\/stpklarnalineitem\/quantity"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"role":"symbol","title":"STPKlarnaLineItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPKlarnaLineItem"}],"abstract":[{"type":"text","text":"An object representing a line item in a Klarna source."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"url":"\/documentation\/stripepayments\/stpklarnalineitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"quantity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"quantity"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"quantity"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1quantity\/title","value":"quantity"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1quantity\/fragments","value":[{"kind":"identifier","text":"quantity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title","value":"STPKlarnaLineItem"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments","value":[{"kind":"identifier","text":"STPKlarnaLineItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}