{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalAmount"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpklarnalineitem\/totalamount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpklarnalineitem\/totalamount"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"totalAmount"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"}],"navigatorTitle":[{"kind":"identifier","text":"totalAmount"}],"roleHeading":"Instance Property","role":"symbol","title":"totalAmount","externalID":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem(py)totalAmount"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The total price of this line item.","type":"text"},{"text":" ","type":"text"},{"text":"Note: This is the total price after multiplying by the quantity, not","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the price of an individual item. It is denominated in the currency"},{"type":"text","text":" "},{"type":"text","text":"of the STPSourceParams which contains it."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/totalAmount"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","abstract":[{"type":"text","text":"An object representing a line item in a Klarna source."}],"title":"STPKlarnaLineItem","kind":"symbol","url":"\/documentation\/stripepayments\/stpklarnalineitem","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPKlarnaLineItem","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItem"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/totalAmount":{"abstract":[{"text":"The total price of this line item.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Note: This is the total price after multiplying by the quantity, not"},{"text":" ","type":"text"},{"text":"the price of an individual item. It is denominated in the currency","type":"text"},{"text":" ","type":"text"},{"text":"of the STPSourceParams which contains it.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"totalAmount","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/totalAmount","title":"totalAmount","url":"\/documentation\/stripepayments\/stpklarnalineitem\/totalamount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalAmount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"totalAmount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"totalAmount","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"totalAmount"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title","value":"STPKlarnaLineItem","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments"},{"value":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/navigatorTitle","op":"replace"},{"value":"totalAmount","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1totalAmount\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1totalAmount\/fragments","value":[{"kind":"identifier","text":"totalAmount"}],"op":"replace"}]}]}