{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/credit","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"credit"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"STPCardFundingTypeCredit","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"STPCardFundingType.credit","externalID":"c:@M@StripePayments@E@STPCardFundingType@STPCardFundingTypeCredit","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"credit","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType"]]},"kind":"symbol","abstract":[{"type":"text","text":"Credit card funding"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardfundingtype\/credit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardfundingtype\/credit"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/credit":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Credit card funding"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/credit","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardfundingtype\/credit","title":"STPCardFundingType.credit","navigatorTitle":[{"text":"STPCardFundingTypeCredit","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"credit","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"abstract":[{"type":"text","text":"The various funding sources for a payment card."}],"url":"\/documentation\/stripepayments\/stpcardfundingtype","title":"STPCardFundingType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCardFundingType","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardFundingType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPCardFundingTypeCredit"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPCardFundingTypeCredit","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"STPCardFundingTypeCredit","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1credit\/title","op":"replace","value":"STPCardFundingTypeCredit"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFundingTypeCredit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1credit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title","value":"STPCardFundingType"},{"op":"replace","value":[{"text":"STPCardFundingType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments"},{"value":[{"text":"STPCardFundingType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}