{"metadata":{"title":"CustomStringConvertible Implementations","roleHeading":"API Collection","modules":[{"name":"StripePayments"}],"role":"collectionGroup"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardfundingtype\/customstringconvertible-implementations"]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/description"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFundingType"}],"type":"topic","title":"STPCardFundingType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","navigatorTitle":[{"kind":"identifier","text":"STPCardFundingType"}],"role":"symbol","abstract":[{"type":"text","text":"The various funding sources for a payment card."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardfundingtype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/description":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/description","kind":"symbol","abstract":[],"title":"description","role":"symbol","url":"\/documentation\/stripepayments\/stpcardfundingtype\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title","value":"STPCardFundingType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments","value":[{"kind":"identifier","text":"STPCardFundingType"}]},{"op":"replace","value":[{"text":"STPCardFundingType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle"}]}]}