{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/debit"},"variants":[{"paths":["\/documentation\/stripepayments\/stpcardfundingtype\/debit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardfundingtype\/debit"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType"]]},"abstract":[{"text":"Debit card funding","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debit","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"title":"STPCardFundingType.debit","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debit","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPCardFundingType@STPCardFundingTypeDebit","roleHeading":"Case","navigatorTitle":[{"text":"STPCardFundingTypeDebit","kind":"identifier"}]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/debit":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardfundingtype\/debit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debit"}],"title":"STPCardFundingType.debit","abstract":[{"type":"text","text":"Debit card funding"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/debit","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardFundingTypeDebit"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","url":"\/documentation\/stripepayments\/stpcardfundingtype","kind":"symbol","title":"STPCardFundingType","navigatorTitle":[{"text":"STPCardFundingType","kind":"identifier"}],"abstract":[{"type":"text","text":"The various funding sources for a payment card."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFundingType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPCardFundingTypeDebit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPCardFundingTypeDebit","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPCardFundingTypeDebit"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1debit\/title","value":"STPCardFundingTypeDebit"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1debit\/fragments","value":[{"kind":"identifier","text":"STPCardFundingTypeDebit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title","value":"STPCardFundingType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments","value":[{"text":"STPCardFundingType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle","value":[{"text":"STPCardFundingType","kind":"identifier"}]}]}]}