{"metadata":{"title":"STPCardFundingType.other","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"STPCardFundingTypeOther","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPCardFundingType@STPCardFundingTypeOther"},"kind":"symbol","abstract":[{"type":"text","text":"An other or unknown type of funding source."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardfundingtype\/other"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardfundingtype\/other"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/other"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","type":"topic","url":"\/documentation\/stripepayments\/stpcardfundingtype","kind":"symbol","title":"STPCardFundingType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFundingType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardFundingType"}],"abstract":[{"type":"text","text":"The various funding sources for a payment card."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/other":{"title":"STPCardFundingType.other","navigatorTitle":[{"text":"STPCardFundingTypeOther","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/other","role":"symbol","url":"\/documentation\/stripepayments\/stpcardfundingtype\/other","abstract":[{"text":"An other or unknown type of funding source.","type":"text"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPCardFundingTypeOther","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCardFundingTypeOther"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPCardFundingTypeOther","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"STPCardFundingType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCardFundingType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFundingType"}],"op":"replace"},{"value":"STPCardFundingTypeOther","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1other\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1other\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCardFundingTypeOther"}]}]}]}