//
// VerificationPageRequirements.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageRequirements: StripeDecodable, Equatable {
    enum Missing: String, Codable, Equatable {
        case biometricConsent = "biometric_consent"
        case idDocumentBack = "id_document_back"
        case idDocumentFront = "id_document_front"
        case idDocumentType = "id_document_type"
    }
    let missing: [Missing]
    var _allResponseFieldsStorage: NonEncodableParameters?
}
