//
// VerificationPageStaticContentSelfieModels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentSelfieModels: StripeDecodable, Equatable {
    let faceDetectorUrl: String
    let faceMeshBlazeUrl: String
    let faceMeshUrl: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
