//
// VerificationPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore


/** A VerificationPage contains the static content and initial state that is required for Stripe Identity&#x27;s native mobile SDKs to render the verification flow. */

struct VerificationPage: StripeDecodable, Equatable {
    enum Status: String, Codable, Equatable {
        case canceled = "canceled"
        case processing = "processing"
        case requiresInput = "requires_input"
        case verified = "verified"
    }
    var biometricConsent: VerificationPageStaticContentConsentPage
    var documentCapture: VerificationPageStaticContentDocumentCapturePage
    var documentSelect: VerificationPageStaticContentDocumentSelectPage
    /** Ephemeral API Key used to update the associated VerificationSession. */
    var ephemeralApiKey: String
    /** The short-lived URL that can be used in the case that the client cannot support the VerificationSession. */
    var fallbackUrl: String
    /** Unique identifier for the object. */
    var id: String
    var individual: VerificationPageStaticContentIndividualPage
    /** Has the value &#x60;true&#x60; if the object exists in live mode or the value &#x60;false&#x60; if the object exists in test mode. */
    var livemode: Bool
    var requirements: VerificationPageRequirements
    var selfie: VerificationPageStaticContentSelfiePage
    /** Status of the associated VerificationSession. */
    var status: Status
    /** If true, the associated VerificationSession has been submitted for processing. */
    var submitted: Bool
    var success: VerificationPageStaticContentTextPage
    var trainingConsent: VerificationPageStaticContentConsentPage
    /** If true, the client cannot support the VerificationSession. */
    var unsupportedClient: Bool
    var welcome: VerificationPageStaticContentTextPage
    var _allResponseFieldsStorage: NonEncodableParameters?
}
