//
// VerificationPageStaticContentSelfieModels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore

extension StripeAPI { 
    
    struct VerificationPageStaticContentSelfieModels: Decodable, Equatable {
        let faceDetectorMinIou: Decimal
        let faceDetectorMinScore: Decimal
        let faceDetectorUrl: String
    }
    
}
