//
// VerificationPageStaticContentSelfiePage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore

extension StripeAPI { 

    struct VerificationPageStaticContentSelfiePage: Decodable, Equatable {
        let autocaptureTimeout: Int
        let filePurpose: String
        let highResImageCompressionQuality: Decimal
        let highResImageCropPadding: Decimal
        let highResImageMaxDimension: Int
        let lowResImageCompressionQuality: Decimal
        let lowResImageMaxDimension: Int
        let maxCenteredThresholdX: Decimal
        let maxCenteredThresholdY: Decimal
        let maxCoverageThreshold: Decimal
        let minCoverageThreshold: Decimal
        let minEdgeThreshold: Decimal
        let models: VerificationPageStaticContentSelfieModels
        let numSamples: Int
        let sampleInterval: Int
    }

}
