//
// VerificationPageRequirements.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageRequirements: StripeDecodable, Equatable {
    enum Missing: String, Codable, Equatable { 
        case address = "address"
        case biometricConsent = "biometric_consent"
        case dob = "dob"
        case email = "email"
        case face = "face"
        case idDocumentBack = "id_document_back"
        case idDocumentFront = "id_document_front"
        case idDocumentType = "id_document_type"
        case idNumber = "id_number"
        case name = "name"
        case phoneNumber = "phone_number"
        case trainingConsent = "training_consent"
    }
    var missing: [Missing]
    var _allResponseFieldsStorage: NonEncodableParameters?
}
