//
// VerificationPageStaticContentConsentPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore

extension StripeAPI {

    struct VerificationPageStaticContentConsentPage: Decodable, Equatable {
        let acceptButtonText: String
        let declineButtonText: String
        let privacyPolicy: String
        let title: String?
        let scrollToContinueButtonText: String
        let lines: [VerificationPageStaticConsentLineContent]
    }

}
