//
// VerificationPageStaticContentDocumentCapturePage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import CoreGraphics
@_spi(STP) import StripeCore



struct VerificationPageStaticContentDocumentCapturePage: StripeDecodable, Equatable {
    let autocaptureTimeout: Int
    let filePurpose: String
    let highResImageCompressionQuality: CGFloat
    let highResImageCropPadding: CGFloat
    let highResImageMaxDimension: Int
    let lowResImageCompressionQuality: CGFloat
    let lowResImageMaxDimension: Int
    let models: VerificationPageStaticContentDocumentCaptureModels
    let requireLiveCapture: Bool

    var _allResponseFieldsStorage: NonEncodableParameters?
}
