//
// VerificationPageStaticContentDocumentCaptureModels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentDocumentCaptureModels: StripeDecodable, Equatable {
    let idDetectorUrl: String
    let mbPlausibilityBackUrl: String
    let mbPlausibilityFrontUrl: String
    let mbSupportUrl: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
