//
// VerificationPageStaticContentConsentPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentConsentPage: StripeDecodable {
    var acceptButtonText: String
    var body: String
    var declineButtonText: String
    var title: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
