//
// VerificationPageStaticContentTextPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentTextPage: StripeDecodable, Equatable {
    var body: String
    var buttonText: String
    var title: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
