//
// VerificationPageStaticContentSelfieModels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentSelfieModels: StripeDecodable {
    var faceDetectorUrl: String
    var faceMeshBlazeUrl: String
    var faceMeshUrl: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
