//
// VerificationPageStaticContentDocumentCaptureModels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentDocumentCaptureModels: StripeDecodable, Equatable {
    var idDetectorUrl: String
    var mbPlausibilityBackUrl: String
    var mbPlausibilityFrontUrl: String
    var mbSupportUrl: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
