//
// VerificationPageStaticContentSelfiePage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentSelfiePage: StripeDecodable, Equatable {
    let imageCropPadding: Decimal
    let models: VerificationPageStaticContentSelfieModels
    var _allResponseFieldsStorage: NonEncodableParameters?
}
