//
// VerificationPageStaticContentDocumentCapturePage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentDocumentCapturePage: StripeDecodable {
    var imageCropPadding: Decimal
    var models: VerificationPageStaticContentDocumentCaptureModels
    var requireLiveCapture: Bool
    var _allResponseFieldsStorage: NonEncodableParameters?
}
