//
// VerificationPageStaticContentIndividualPage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageStaticContentIndividualPage: StripeDecodable, Equatable {
    let addressCountries: [String:String]
    let buttonText: String
    let idNumberCountries: [String:String]
    let title: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
