{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"If a customer was successfully parsed from the response, it will be set here. Otherwise, this value wil be nil (and the ","type":"text"},{"type":"codeVoice","code":"error"},{"text":" property will explain what went wrong).","type":"text"}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCustomerDeserializer(py)customer","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPCustomer","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCustomer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"customer","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"customer","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/customer","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customer","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","text":"STPCustomer","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCustomer"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer\/customer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer\/customer"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomer"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomer"}],"kind":"symbol","title":"STPCustomer","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPCustomer"},{"type":"text","text":" represents a deserialized Customer object from the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to instantiate an "},{"type":"codeVoice","code":"STPCustomer"},{"type":"text","text":" – you should instead use"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" to manage retrieving and updating a customer."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","url":"\/documentation\/stripepayments\/stpcustomer"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer/customer":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"customer"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCustomer","kind":"typeIdentifier","text":"STPCustomer"},{"kind":"text","text":"?"}],"title":"customer","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"customer"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/customer","kind":"symbol","abstract":[{"type":"text","text":"If a customer was successfully parsed from the response, it will be set here. Otherwise, this value wil be nil (and the "},{"code":"error","type":"codeVoice"},{"type":"text","text":" property will explain what went wrong)."}],"url":"\/documentation\/stripepayments\/stpcustomerdeserializer\/customer"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer":{"navigatorTitle":[{"kind":"identifier","text":"STPCustomerDeserializer"}],"kind":"symbol","abstract":[{"type":"text","text":"Use "},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"type":"text","text":" to convert a response from the Stripe API into an "},{"code":"STPCustomer","type":"codeVoice"},{"text":" object. ","type":"text"},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"text":" expects the JSON response to be in the exact same format as the Stripe API.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerDeserializer"}],"url":"\/documentation\/stripepayments\/stpcustomerdeserializer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer","role":"symbol","title":"STPCustomerDeserializer","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"customer","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"customer","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCustomer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","text":"STPCustomer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"customer"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/title","value":"STPCustomer","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/fragments","value":[{"text":"STPCustomer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/navigatorTitle","value":[{"kind":"identifier","text":"STPCustomer"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1customer\/title","value":"customer","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1customer\/fragments","value":[{"text":"customer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/title","value":"STPCustomerDeserializer","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/fragments","value":[{"kind":"identifier","text":"STPCustomerDeserializer"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/navigatorTitle","value":[{"text":"STPCustomerDeserializer","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}