{"metadata":{"symbolKind":"property","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPCustomerDeserializer(py)error","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"error"}],"role":"symbol","title":"error"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"If the deserializer failed to parse a customer, this property will explain why (and the ","type":"text"},{"code":"customer","type":"codeVoice"},{"type":"text","text":" property will be nil)."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/error","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomerDeserializer","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcustomerdeserializer","kind":"symbol","navigatorTitle":[{"text":"STPCustomerDeserializer","kind":"identifier"}],"title":"STPCustomerDeserializer","type":"topic","role":"symbol","abstract":[{"text":"Use ","type":"text"},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"text":" to convert a response from the Stripe API into an ","type":"text"},{"type":"codeVoice","code":"STPCustomer"},{"type":"text","text":" object. "},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"text":" expects the JSON response to be in the exact same format as the Stripe API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer/error":{"title":"error","url":"\/documentation\/stripepayments\/stpcustomerdeserializer\/error","role":"symbol","navigatorTitle":[{"text":"error","kind":"identifier"}],"abstract":[{"text":"If the deserializer failed to parse a customer, this property will explain why (and the ","type":"text"},{"type":"codeVoice","code":"customer"},{"type":"text","text":" property will be nil)."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/error","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"error"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"error"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/title","value":"STPCustomerDeserializer"},{"value":[{"text":"STPCustomerDeserializer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/navigatorTitle","value":[{"kind":"identifier","text":"STPCustomerDeserializer"}]},{"value":"error","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1error\/title","op":"replace"},{"value":[{"text":"error","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1error\/fragments"}]}]}