{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCustomerDeserializer(im)initWithJsonResponse:","title":"init(jsonResponse:)","role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"jsonResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"initWithJsonResponse:","kind":"identifier"}],"roleHeading":"Initializer"},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(jsonResponse:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer\/init(jsonresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer\/init(jsonresponse:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer"]]},"kind":"symbol","abstract":[{"type":"text","text":"Initializes a customer deserializer with a JSON dictionary. This JSON should be"},{"text":" ","type":"text"},{"text":"in the exact same format as what the Stripe API returns. If it’s successfully","type":"text"},{"text":" ","type":"text"},{"text":"parsed, the ","type":"text"},{"type":"codeVoice","code":"customer"},{"text":" parameter will be present after initialization;","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"otherwise "},{"type":"codeVoice","code":"error"},{"text":" will be present.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"jsonResponse"},{"kind":"text","text":" "},{"text":"json","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A JSON dictionary."}]}],"name":"json"}],"kind":"parameters"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer/init(jsonResponse:)":{"title":"init(jsonResponse:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jsonResponse"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"url":"\/documentation\/stripepayments\/stpcustomerdeserializer\/init(jsonresponse:)","type":"topic","abstract":[{"text":"Initializes a customer deserializer with a JSON dictionary. This JSON should be","type":"text"},{"type":"text","text":" "},{"text":"in the exact same format as what the Stripe API returns. If it’s successfully","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"parsed, the "},{"type":"codeVoice","code":"customer"},{"type":"text","text":" parameter will be present after initialization;"},{"text":" ","type":"text"},{"type":"text","text":"otherwise "},{"type":"codeVoice","code":"error"},{"text":" will be present.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(jsonResponse:)","navigatorTitle":[{"kind":"identifier","text":"initWithJsonResponse:"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer":{"url":"\/documentation\/stripepayments\/stpcustomerdeserializer","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer","abstract":[{"type":"text","text":"Use "},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"type":"text","text":" to convert a response from the Stripe API into an "},{"type":"codeVoice","code":"STPCustomer"},{"type":"text","text":" object. "},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"text":" expects the JSON response to be in the exact same format as the Stripe API.","type":"text"}],"navigatorTitle":[{"text":"STPCustomerDeserializer","kind":"identifier"}],"role":"symbol","type":"topic","title":"STPCustomerDeserializer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCustomerDeserializer","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithJsonResponse:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithJsonResponse:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithJsonResponse:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"json","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A JSON dictionary."}]}],"name":"json"}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1init(jsonResponse:)\/title","value":"initWithJsonResponse:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithJsonResponse:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1init(jsonResponse:)\/fragments"},{"value":"STPCustomerDeserializer","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/fragments","value":[{"text":"STPCustomerDeserializer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/navigatorTitle","value":[{"text":"STPCustomerDeserializer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}