{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(data:urlResponse:error:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"urlResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"data","content":[{"inlineContent":[{"text":"An ","type":"text"},{"code":"NSData","type":"codeVoice"},{"text":" object representing encoded JSON for a Customer object","type":"text"}],"type":"paragraph"}]},{"name":"urlResponse","content":[{"inlineContent":[{"text":"The URL response obtained from the ","type":"text"},{"code":"NSURLSessionTask","type":"codeVoice"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"Any error that occurred from the URL session task (if this","type":"text"},{"text":" ","type":"text"},{"text":"is non-nil, the ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" property will be set to this value after initialization).","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"metadata":{"role":"symbol","title":"init(data:urlResponse:error:)","modules":[{"name":"StripePayments"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"urlResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse","text":"URLResponse"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?)"}],"symbolKind":"init","externalID":"c:@M@StripePayments@objc(cs)STPCustomerDeserializer(im)initWithData:urlResponse:error:","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:urlResponse:error:"}]},"abstract":[{"text":"Initialize a customer deserializer. The ","type":"text"},{"code":"data","type":"codeVoice"},{"text":", ","type":"text"},{"code":"urlResponse","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" ","type":"text"},{"text":"parameters are intended to be passed from an ","type":"text"},{"code":"NSURLSessionDataTask","type":"codeVoice"},{"text":" callback.","type":"text"},{"text":" ","type":"text"},{"text":"After it has been initialized, you can inspect the ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"customer","type":"codeVoice"},{"text":" ","type":"text"},{"text":"properties to see if the deserialization was successful. If ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" is nil,","type":"text"},{"text":" ","type":"text"},{"code":"customer","type":"codeVoice"},{"text":" will be non-nil (and vice versa).","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer\/init(data:urlresponse:error:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer\/init(data:urlresponse:error:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer/init(data:urlResponse:error:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(data:urlResponse:error:)","type":"topic","kind":"symbol","role":"symbol","title":"init(data:urlResponse:error:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"urlResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Initialize a customer deserializer. The ","type":"text"},{"code":"data","type":"codeVoice"},{"text":", ","type":"text"},{"code":"urlResponse","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" ","type":"text"},{"text":"parameters are intended to be passed from an ","type":"text"},{"code":"NSURLSessionDataTask","type":"codeVoice"},{"text":" callback.","type":"text"},{"text":" ","type":"text"},{"text":"After it has been initialized, you can inspect the ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"customer","type":"codeVoice"},{"text":" ","type":"text"},{"text":"properties to see if the deserialization was successful. If ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" is nil,","type":"text"},{"text":" ","type":"text"},{"code":"customer","type":"codeVoice"},{"text":" will be non-nil (and vice versa).","type":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithData:urlResponse:error:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcustomerdeserializer\/init(data:urlresponse:error:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer":{"url":"\/documentation\/stripepayments\/stpcustomerdeserializer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Use ","type":"text"},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"text":" to convert a response from the Stripe API into an ","type":"text"},{"code":"STPCustomer","type":"codeVoice"},{"text":" object. ","type":"text"},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"text":" expects the JSON response to be in the exact same format as the Stripe API.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPCustomerDeserializer"}],"title":"STPCustomerDeserializer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerDeserializer"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithData:urlResponse:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:urlResponse:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"urlResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"urlResponse","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"data","content":[{"inlineContent":[{"text":"An ","type":"text"},{"code":"NSData","type":"codeVoice"},{"text":" object representing encoded JSON for a Customer object","type":"text"}],"type":"paragraph"}]},{"name":"urlResponse","content":[{"inlineContent":[{"text":"The URL response obtained from the ","type":"text"},{"code":"NSURLSessionTask","type":"codeVoice"}],"type":"paragraph"}]},{"name":"error","content":[{"inlineContent":[{"text":"Any error that occurred from the URL session task (if this","type":"text"},{"text":" ","type":"text"},{"text":"is non-nil, the ","type":"text"},{"code":"error","type":"codeVoice"},{"text":" property will be set to this value after initialization).","type":"text"}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1init(data:urlResponse:error:)\/title","value":"initWithData:urlResponse:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1init(data:urlResponse:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:urlResponse:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/title","value":"STPCustomerDeserializer"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/fragments","value":[{"kind":"identifier","text":"STPCustomerDeserializer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/navigatorTitle","value":[{"kind":"identifier","text":"STPCustomerDeserializer"}]}]}]}