{"kind":"article","sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/description"],"title":"Instance Properties","anchor":"Instance-Properties"}],"metadata":{"modules":[{"name":"StripePayments"}],"role":"collectionGroup","roleHeading":"API Collection","title":"CustomStringConvertible Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/customstringconvertible-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/CustomStringConvertible-Implementations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus":{"title":"STPSourceVerificationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceVerificationStatus","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceverificationstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Verification status types for a Source."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceVerificationStatus"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus/description":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/stripepayments\/stpsourceverificationstatus\/description","title":"description","kind":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPSourceVerificationStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/title","op":"replace"},{"value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/fragments"},{"value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/navigatorTitle"}]}]}