{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"Equatable Implementations","modules":[{"name":"StripePayments"}],"roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","topicSections":[{"anchor":"Operators","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/!=(_:_:)"],"title":"Operators"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus":{"role":"symbol","type":"topic","abstract":[{"text":"Verification status types for a Source.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceVerificationStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceverificationstatus","title":"STPSourceVerificationStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","navigatorTitle":[{"text":"STPSourceVerificationStatus","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus/!=(_:_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/!=(_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","title":"!=(_:_:)","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceverificationstatus\/!=(_:_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPSourceVerificationStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/title"},{"op":"replace","value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/navigatorTitle","value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}