{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/failed"]},{"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceVerificationStatusFailed"}],"title":"STPSourceVerificationStatus.failed","externalID":"c:@M@StripePayments@E@STPSourceVerificationStatus@STPSourceVerificationStatusFailed","modules":[{"name":"StripePayments"}],"symbolKind":"case","roleHeading":"Case"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/failed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The verification has failed."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus":{"type":"topic","role":"symbol","title":"STPSourceVerificationStatus","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceverificationstatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceVerificationStatus","kind":"identifier"}],"abstract":[{"text":"Verification status types for a Source.","type":"text"}],"navigatorTitle":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus/failed":{"kind":"symbol","title":"STPSourceVerificationStatus.failed","navigatorTitle":[{"text":"STPSourceVerificationStatusFailed","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/failed","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failed","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceverificationstatus\/failed","role":"symbol","abstract":[{"type":"text","text":"The verification has failed."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceVerificationStatusFailed"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceVerificationStatusFailed","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceVerificationStatusFailed"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"STPSourceVerificationStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/fragments","value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/navigatorTitle","value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"op":"replace"},{"value":"STPSourceVerificationStatusFailed","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus~1failed\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus~1failed\/fragments","value":[{"text":"STPSourceVerificationStatusFailed","kind":"identifier"}]}]}]}