{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pending"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pending"}],"title":"STPSourceVerificationStatus.pending","roleHeading":"Case","navigatorTitle":[{"text":"STPSourceVerificationStatusPending","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSourceVerificationStatus@STPSourceVerificationStatusPending"},"kind":"symbol","abstract":[{"type":"text","text":"The verification is pending."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/pending","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/pending"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/pending"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus/pending":{"abstract":[{"text":"The verification is pending.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/pending","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pending","kind":"identifier"}],"title":"STPSourceVerificationStatus.pending","navigatorTitle":[{"text":"STPSourceVerificationStatusPending","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourceverificationstatus\/pending"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus":{"type":"topic","role":"symbol","title":"STPSourceVerificationStatus","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceverificationstatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceVerificationStatus","kind":"identifier"}],"abstract":[{"text":"Verification status types for a Source.","type":"text"}],"navigatorTitle":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceVerificationStatusPending"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceVerificationStatusPending"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPSourceVerificationStatusPending"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus~1pending\/title","value":"STPSourceVerificationStatusPending"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus~1pending\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceVerificationStatusPending"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/title","value":"STPSourceVerificationStatus"},{"op":"replace","value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/navigatorTitle","value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}