{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/succeeded"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/succeeded"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/succeeded","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The verification has succeeeded."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"title":"STPSourceVerificationStatus.succeeded","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSourceVerificationStatus@STPSourceVerificationStatusSucceeded","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceVerificationStatusSucceeded"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus/succeeded":{"role":"symbol","title":"STPSourceVerificationStatus.succeeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"abstract":[{"type":"text","text":"The verification has succeeeded."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/succeeded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceVerificationStatusSucceeded"}],"url":"\/documentation\/stripepayments\/stpsourceverificationstatus\/succeeded"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus":{"role":"symbol","title":"STPSourceVerificationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceVerificationStatus"}],"abstract":[{"type":"text","text":"Verification status types for a Source."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceVerificationStatus"}],"url":"\/documentation\/stripepayments\/stpsourceverificationstatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceVerificationStatusSucceeded"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceVerificationStatusSucceeded"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPSourceVerificationStatusSucceeded"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus~1succeeded\/title","value":"STPSourceVerificationStatusSucceeded"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus~1succeeded\/fragments","value":[{"kind":"identifier","text":"STPSourceVerificationStatusSucceeded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/title","value":"STPSourceVerificationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/fragments","value":[{"kind":"identifier","text":"STPSourceVerificationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}