{"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"title":"STPSourceVerificationStatus.unknown","externalID":"c:@M@StripePayments@E@STPSourceVerificationStatus@STPSourceVerificationStatusUnknown","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPSourceVerificationStatusUnknown"}],"symbolKind":"case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"The state of the verification is unknown."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/unknown"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/unknown"]},{"paths":["\/documentation\/stripepayments\/stpsourceverificationstatus\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus":{"url":"\/documentation\/stripepayments\/stpsourceverificationstatus","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus","navigatorTitle":[{"kind":"identifier","text":"STPSourceVerificationStatus"}],"title":"STPSourceVerificationStatus","abstract":[{"type":"text","text":"Verification status types for a Source."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceVerificationStatus"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceVerificationStatus/unknown":{"kind":"symbol","navigatorTitle":[{"text":"STPSourceVerificationStatusUnknown","kind":"identifier"}],"abstract":[{"type":"text","text":"The state of the verification is unknown."}],"url":"\/documentation\/stripepayments\/stpsourceverificationstatus\/unknown","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceVerificationStatus\/unknown","title":"STPSourceVerificationStatus.unknown","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"STPSourceVerificationStatusUnknown","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"STPSourceVerificationStatusUnknown","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceVerificationStatusUnknown"}]}]},"path":"\/primaryContentSections\/0"},{"value":"STPSourceVerificationStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/title","op":"replace"},{"op":"replace","value":[{"text":"STPSourceVerificationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceVerificationStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus~1unknown\/title","op":"replace","value":"STPSourceVerificationStatusUnknown"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceVerificationStatus~1unknown\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceVerificationStatusUnknown"}]}]}]}
