{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(createCustomerKeyWithAPIVersion:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createCustomerKey"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAPIVersion"},{"text":" ","kind":"text"},{"text":"apiVersion","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPJSONResponseCompletionBlock","preciseIdentifier":"s:14StripePayments30STPJSONResponseCompletionBlocka","kind":"typeIdentifier","text":"STPJSONResponseCompletionBlock"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The Stripe API version to use when creating a key.","type":"text"},{"text":" ","type":"text"},{"text":"You should pass this parameter to your backend, and use it to set the API version","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"in your key creation request. Passing this version parameter ensures that the"},{"text":" ","type":"text"},{"type":"text","text":"Stripe SDK can always parse the ephemeral key response from your server."}],"type":"paragraph"}],"name":"apiVersion"},{"content":[{"inlineContent":[{"text":"Call this callback when you’re done fetching a new ephemeral","type":"text"},{"type":"text","text":" "},{"type":"text","text":"key from your backend. For example, "},{"code":"completion(json, nil)","type":"codeVoice"},{"text":" (if your call succeeds)","type":"text"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"code":"completion(nil, error)","type":"codeVoice"},{"text":" if an error is returned.","type":"text"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcustomerephemeralkeyprovider\/createcustomerkey(withapiversion:completion:)"]},{"paths":["\/documentation\/stripe\/stpcustomerephemeralkeyprovider\/createcustomerkey(withapiversion:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider\/createCustomerKey(withAPIVersion:completion:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"createCustomerKeyWithAPIVersion:completion:"}],"externalID":"c:@M@Stripe@objc(pl)STPCustomerEphemeralKeyProvider(im)createCustomerKeyWithAPIVersion:completion:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createCustomerKey","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAPIVersion"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPJSONResponseCompletionBlock","preciseIdentifier":"s:14StripePayments30STPJSONResponseCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"title":"createCustomerKey(withAPIVersion:completion:)","modules":[{"name":"Stripe"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider"]]},"abstract":[{"type":"text","text":"Creates a new ephemeral key for retrieving and updating a Stripe customer."},{"type":"text","text":" "},{"type":"text","text":"On your backend, you should create a new ephemeral key for the Stripe customer"},{"type":"text","text":" "},{"type":"text","text":"associated with your user, and return the raw JSON response from the Stripe API."},{"type":"text","text":" "},{"text":"For an example Ruby implementation of this API, refer to our example backend:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/github.com\/stripe\/example-mobile-backend\/blob\/v18.1.0\/web.rb"},{"text":" ","type":"text"},{"text":"Back in your iOS app, once you have a response from this API, call the provided","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"completion block with the JSON response, or an error if one occurred."}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","title":"Stripe","role":"collection","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerEphemeralKeyProvider/createCustomerKey(withAPIVersion:completion:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"createCustomerKeyWithAPIVersion:completion:"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider\/createCustomerKey(withAPIVersion:completion:)","title":"createCustomerKey(withAPIVersion:completion:)","abstract":[{"type":"text","text":"Creates a new ephemeral key for retrieving and updating a Stripe customer."},{"type":"text","text":" "},{"text":"On your backend, you should create a new ephemeral key for the Stripe customer","type":"text"},{"type":"text","text":" "},{"text":"associated with your user, and return the raw JSON response from the Stripe API.","type":"text"},{"type":"text","text":" "},{"text":"For an example Ruby implementation of this API, refer to our example backend:","type":"text"},{"type":"text","text":" "},{"text":"https:\/\/github.com\/stripe\/example-mobile-backend\/blob\/v18.1.0\/web.rb","type":"text"},{"text":" ","type":"text"},{"text":"Back in your iOS app, once you have a response from this API, call the provided","type":"text"},{"type":"text","text":" "},{"type":"text","text":"completion block with the JSON response, or an error if one occurred."}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createCustomerKey"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAPIVersion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"STPJSONResponseCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments30STPJSONResponseCompletionBlocka"},{"text":")","kind":"text"}],"url":"\/documentation\/stripe\/stpcustomerephemeralkeyprovider\/createcustomerkey(withapiversion:completion:)","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerEphemeralKeyProvider":{"navigatorTitle":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"type":"topic","abstract":[{"text":"You should make your application’s API client conform to this interface.","type":"text"},{"text":" ","type":"text"},{"text":"It provides a way for Stripe utility classes to request a new ephemeral key from","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"your backend, which it will use to retrieve and update Stripe API objects."}],"url":"\/documentation\/stripe\/stpcustomerephemeralkeyprovider","title":"STPCustomerEphemeralKeyProvider","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerEphemeralKeyProvider","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPJSONResponseCompletionBlock":{"abstract":[{"type":"text","text":"A callback to be run with a JSON response."}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"STPJSONResponseCompletionBlock","kind":"identifier"}],"title":"STPJSONResponseCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPJSONResponseCompletionBlock","kind":"symbol","navigatorTitle":[{"text":"STPJSONResponseCompletionBlock","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stpjsonresponsecompletionblock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"createCustomerKeyWithAPIVersion:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createCustomerKeyWithAPIVersion:completion:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"createCustomerKeyWithAPIVersion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"apiVersion"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The Stripe API version to use when creating a key."},{"type":"text","text":" "},{"type":"text","text":"You should pass this parameter to your backend, and use it to set the API version"},{"type":"text","text":" "},{"type":"text","text":"in your key creation request. Passing this version parameter ensures that the"},{"text":" ","type":"text"},{"type":"text","text":"Stripe SDK can always parse the ephemeral key response from your server."}],"type":"paragraph"}],"name":"apiVersion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Call this callback when you’re done fetching a new ephemeral","type":"text"},{"type":"text","text":" "},{"type":"text","text":"key from your backend. For example, "},{"type":"codeVoice","code":"completion(json, nil)"},{"type":"text","text":" (if your call succeeds)"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"code":"completion(nil, error)","type":"codeVoice"},{"text":" if an error is returned.","type":"text"}]}],"name":"completion"}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider~1createCustomerKey(withAPIVersion:completion:)\/title","op":"replace","value":"createCustomerKeyWithAPIVersion:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"createCustomerKeyWithAPIVersion:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider~1createCustomerKey(withAPIVersion:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/title","value":"STPCustomerEphemeralKeyProvider"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/fragments","value":[{"text":"STPCustomerEphemeralKeyProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPCustomerEphemeralKeyProvider"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerEphemeralKeyProvider\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}