{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"title":"allResponseFields","externalID":"c:@M@StripePayments@objc(cs)STPIssuingCardPin(py)allResponseFields","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]},"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"type":"text","text":" "},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIssuingCardPin"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIssuingCardPin\/allResponseFields","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpissuingcardpin\/allresponsefields"]},{"paths":["\/documentation\/stripepayments\/stpissuingcardpin\/allresponsefields"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIssuingCardPin":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIssuingCardPin","url":"\/documentation\/stripepayments\/stpissuingcardpin","navigatorTitle":[{"text":"STPIssuingCardPin","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Information related to a Stripe Issuing card, including the PIN","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIssuingCardPin","kind":"identifier"}],"title":"STPIssuingCardPin"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIssuingCardPin/allResponseFields":{"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIssuingCardPin\/allResponseFields","title":"allResponseFields","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpissuingcardpin\/allresponsefields","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"allResponseFields"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"allResponseFields","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"allResponseFields","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"STPIssuingCardPin","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIssuingCardPin\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIssuingCardPin\/fragments","value":[{"text":"STPIssuingCardPin","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIssuingCardPin\/navigatorTitle","value":[{"text":"STPIssuingCardPin","kind":"identifier"}]},{"value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIssuingCardPin~1allResponseFields\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIssuingCardPin~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}