{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/clientattributionmetadata"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/clientAttributionMetadata","interfaceLanguage":"occ"},"sections":[],"abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPClientAttributionMetadata","text":"STPClientAttributionMetadata","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"clientAttributionMetadata","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"title":"clientAttributionMetadata","navigatorTitle":[{"text":"clientAttributionMetadata","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(py)clientAttributionMetadata","fragments":[{"text":"clientAttributionMetadata","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","title":"STPSetupIntentConfirmParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"type":"text","text":" "},{"type":"text","text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app."},{"type":"text","text":" "},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"type":"text","text":".  Otherwise, it will transition to "},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"type":"text","text":", and suggest additional actions via "},{"code":"nextAction","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"code":"STPAPIClient.confirmSetupIntent(...)","type":"codeVoice"},{"type":"text","text":" directly, we recommend using "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to handle any additional steps for you."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/clientAttributionMetadata":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/clientAttributionMetadata","fragments":[{"text":"clientAttributionMetadata","kind":"identifier"}],"kind":"symbol","title":"clientAttributionMetadata","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/clientattributionmetadata","abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPSetupIntentConfirmParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title"},{"value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments"},{"value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle"}]}]}