{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/init(clientSecret:paymentMethodType:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"paymentMethodType"},{"kind":"text","text":": "},{"text":"STPPaymentMethodType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"clientSecret","content":[{"inlineContent":[{"text":"The client secret for this SetupIntent","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The known type of the SetupIntent’s attached PaymentMethod"}]}],"name":"paymentMethodType"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentMethodType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","kind":"typeIdentifier","text":"STPPaymentMethodType"},{"text":")","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(im)initWithClientSecret:paymentMethodType:","title":"init(clientSecret:paymentMethodType:)","roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithClientSecret:paymentMethodType:"}],"modules":[{"name":"StripePayments"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"abstract":[{"text":"Initialize this ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentConfirmParams"},{"text":" with a ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"type":"text","text":" and "},{"code":"paymentMethodType","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Use this initializer for SetupIntents that already have a PaymentMethod attached."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/init(clientsecret:paymentmethodtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/init(clientsecret:paymentmethodtype:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/init(clientSecret:paymentMethodType:)":{"title":"init(clientSecret:paymentMethodType:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"paymentMethodType"},{"kind":"text","text":": "},{"text":"STPPaymentMethodType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/init(clientsecret:paymentmethodtype:)","abstract":[{"type":"text","text":"Initialize this "},{"code":"STPSetupIntentConfirmParams","type":"codeVoice"},{"text":" with a ","type":"text"},{"type":"codeVoice","code":"clientSecret"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"paymentMethodType"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Use this initializer for SetupIntents that already have a PaymentMethod attached."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/init(clientSecret:paymentMethodType:)","navigatorTitle":[{"text":"initWithClientSecret:paymentMethodType:","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"title":"STPSetupIntentConfirmParams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"type":"text","text":" "},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"text":".  Otherwise, it will transition to ","type":"text"},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"type":"text","text":", and suggest additional actions via "},{"code":"nextAction","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Instead of passing this to ","type":"text"},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"type":"text","text":" directly, we recommend using "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to handle any additional steps for you."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodType"}],"abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"title":"STPPaymentMethodType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithClientSecret:paymentMethodType:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithClientSecret:paymentMethodType:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithClientSecret:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"clientSecret"},{"text":" ","kind":"text"},{"text":"paymentMethodType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodType","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"paymentMethodType"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"clientSecret","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The client secret for this SetupIntent"}]}]},{"content":[{"inlineContent":[{"text":"The known type of the SetupIntent’s attached PaymentMethod","type":"text"}],"type":"paragraph"}],"name":"paymentMethodType"}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1init(clientSecret:paymentMethodType:)\/title","op":"replace","value":"initWithClientSecret:paymentMethodType:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1init(clientSecret:paymentMethodType:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithClientSecret:paymentMethodType:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","op":"replace","value":"STPSetupIntentConfirmParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},{"op":"replace","value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodType"}]}]}]}