{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"abstract":[{"type":"text","text":"Details about the Mandate to create."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/mandateData"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mandateData"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPMandateDataParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If this value is null, the SDK will set this to an internal value indicating that the mandate data should be inferred from the current context if it’s required for "},{"type":"codeVoice","code":"self.paymentMethodType"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/mandatedata"]},{"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/mandatedata"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(py)mandateData","symbolKind":"property","title":"mandateData","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mandateData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPMandateDataParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"mandateData","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/mandateData":{"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/mandatedata","abstract":[{"type":"text","text":"Details about the Mandate to create."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mandateData"}],"type":"topic","title":"mandateData","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/mandateData","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mandateData","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","kind":"typeIdentifier","text":"STPMandateDataParams"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"title":"STPSetupIntentConfirmParams","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"type":"text","text":" "},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"text":".  Otherwise, it will transition to ","type":"text"},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"text":", and suggest additional actions via ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Instead of passing this to ","type":"text"},{"code":"STPAPIClient.confirmSetupIntent(...)","type":"codeVoice"},{"text":" directly, we recommend using ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to handle any additional steps for you."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateDataParams":{"navigatorTitle":[{"text":"STPMandateDataParams","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This object contains details about the Mandate to create. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateDataParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpmandatedataparams","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","title":"STPMandateDataParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mandateData","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"mandateData"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"STPMandateDataParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mandateData"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"mandateData","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1mandateData\/title","op":"replace"},{"value":[{"text":"mandateData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1mandateData\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","value":"STPSetupIntentConfirmParams"},{"value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle"},{"value":"STPMandateDataParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/title"},{"value":[{"kind":"identifier","text":"STPMandateDataParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/fragments","op":"replace"},{"value":[{"text":"STPMandateDataParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/navigatorTitle"}]}]}
