{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodParams","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/paymentmethodparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/paymentmethodparams"]}],"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(py)paymentMethodParams","symbolKind":"property","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","title":"paymentMethodParams","navigatorTitle":[{"kind":"identifier","text":"paymentMethodParams"}]},"abstract":[{"text":"Provide a supported ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":" object, and Stripe will create a","type":"text"},{"text":" ","type":"text"},{"text":"PaymentMethod during PaymentIntent confirmation.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"aside","style":"note","content":[{"inlineContent":[{"text":"Alternative to ","type":"text"},{"code":"paymentMethodId","type":"codeVoice"}],"type":"paragraph"}],"name":"Note"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodparams","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/paymentMethodParams":{"abstract":[{"type":"text","text":"Provide a supported "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":" object, and Stripe will create a"},{"type":"text","text":" "},{"type":"text","text":"PaymentMethod during PaymentIntent confirmation."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodParams","role":"symbol","navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}],"type":"topic","title":"paymentMethodParams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/paymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","type":"topic","title":"STPSetupIntentConfirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"text":".  Otherwise, it will transition to ","type":"text"},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"text":", and suggest additional actions via ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Instead of passing this to ","type":"text"},{"code":"STPAPIClient.confirmSetupIntent(...)","type":"codeVoice"},{"text":" directly, we recommend using ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" to handle any additional steps for you.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"paymentMethodParams","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"paymentMethodParams","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace","value":"STPPaymentMethodParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1paymentMethodParams\/title","op":"replace","value":"paymentMethodParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1paymentMethodParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"paymentMethodParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","op":"replace","value":"STPSetupIntentConfirmParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","op":"replace","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","op":"replace","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]}]}]}