{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodID"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/paymentmethodid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/paymentmethodid"]}],"metadata":{"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(py)paymentMethodID","title":"paymentMethodID","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"text":"paymentMethodID","kind":"identifier"}]},"abstract":[{"text":"Provide an already created PaymentMethod’s id, and it will be used to confirm the SetupIntent.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Alternative to "},{"code":"paymentMethodParams","type":"codeVoice"}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","kind":"symbol","title":"STPSetupIntentConfirmParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"text":".  Otherwise, it will transition to ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"text":", and suggest additional actions via ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Instead of passing this to ","type":"text"},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"text":" directly, we recommend using ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" to handle any additional steps for you.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/paymentMethodID":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodID","title":"paymentMethodID","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"paymentMethodID","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/paymentmethodid","abstract":[{"type":"text","text":"Provide an already created PaymentMethod’s id, and it will be used to confirm the SetupIntent."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paymentMethodID","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"paymentMethodID"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"paymentMethodID","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPSetupIntentConfirmParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title"},{"value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments"},{"value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle"},{"value":"paymentMethodID","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1paymentMethodID\/title"},{"value":[{"kind":"identifier","text":"paymentMethodID"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1paymentMethodID\/fragments"}]}]}