{"abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"code":"expMonth","type":"codeVoice"},{"type":"text","text":", but the Stripe API expects a field called "},{"code":"exp_month","type":"codeVoice"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/propertyNamesToFormFieldNamesMapping()"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/propertynamestoformfieldnamesmapping()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/propertynamestoformfieldnamesmapping()"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"title":"propertyNamesToFormFieldNamesMapping()","symbolKind":"method","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(cm)propertyNamesToFormFieldNamesMapping","roleHeading":"Type Method","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/propertyNamesToFormFieldNamesMapping()":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/propertynamestoformfieldnamesmapping()","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/propertyNamesToFormFieldNamesMapping()","abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"code":"expMonth","type":"codeVoice"},{"text":", but the Stripe API expects a field called ","type":"text"},{"code":"exp_month","type":"codeVoice"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"title":"propertyNamesToFormFieldNamesMapping()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"title":"STPSetupIntentConfirmParams","abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"text":" ","type":"text"},{"type":"text","text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app."},{"text":" ","type":"text"},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"text":".  Otherwise, it will transition to ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"type":"text","text":", and suggest additional actions via "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"text":" directly, we recommend using ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle any additional steps for you."}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"propertyNamesToFormFieldNamesMapping","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1propertyNamesToFormFieldNamesMapping()\/title","value":"propertyNamesToFormFieldNamesMapping","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","value":"STPSetupIntentConfirmParams"},{"op":"replace","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments"},{"value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","op":"replace"}]}]}