{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Radar options that may contain HCaptcha token"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/radaroptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/radarOptions"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarOptions","text":"STPRadarOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarOptions"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"radarOptions"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"radarOptions","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(py)radarOptions","navigatorTitle":[{"kind":"identifier","text":"radarOptions"}],"modules":[{"name":"StripePayments"}],"title":"radarOptions"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/radarOptions":{"role":"symbol","fragments":[{"text":"radarOptions","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/radaroptions","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/radarOptions","abstract":[{"type":"text","text":"Radar options that may contain HCaptcha token"}],"type":"topic","title":"radarOptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"type":"text","text":" "},{"type":"text","text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app."},{"type":"text","text":" "},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"type":"text","text":".  Otherwise, it will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"type":"text","text":", and suggest additional actions via "},{"code":"nextAction","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Instead of passing this to "},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"type":"text","text":" directly, we recommend using "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle any additional steps for you."}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"kind":"symbol","type":"topic","title":"STPSetupIntentConfirmParams","role":"symbol","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarOptions":{"url":"\/documentation\/stripepayments\/stpradaroptions","kind":"symbol","role":"symbol","abstract":[{"text":"Values for STPRadarOptions","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarOptions","type":"topic","title":"STPRadarOptions","fragments":[{"kind":"identifier","text":"STPRadarOptions"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","value":"STPSetupIntentConfirmParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}