{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/returnurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/returnurl"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/returnURL","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"kind":"symbol","abstract":[{"text":"The URL to redirect your customer back to after they authenticate or cancel","type":"text"},{"text":" ","type":"text"},{"text":"their payment on the payment method’s app or site.","type":"text"},{"text":" ","type":"text"},{"text":"This should probably be a URL that opens your iOS app.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"returnURL"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","title":"returnURL","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(py)returnURL","roleHeading":"Instance Property","role":"symbol"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/returnURL":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/returnURL","navigatorTitle":[{"kind":"identifier","text":"returnURL"}],"role":"symbol","title":"returnURL","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/returnurl","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"text":"The URL to redirect your customer back to after they authenticate or cancel","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"their payment on the payment method’s app or site."},{"type":"text","text":" "},{"type":"text","text":"This should probably be a URL that opens your iOS app."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"type":"topic","role":"symbol","abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"text":".  Otherwise, it will transition to ","type":"text"},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"text":", and suggest additional actions via ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Instead of passing this to ","type":"text"},{"code":"STPAPIClient.confirmSetupIntent(...)","type":"codeVoice"},{"text":" directly, we recommend using ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" to handle any additional steps for you.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"title":"STPSetupIntentConfirmParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"returnURL"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"returnURL","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1returnURL\/title","value":"returnURL"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1returnURL\/fragments","value":[{"kind":"identifier","text":"returnURL"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","value":"STPSetupIntentConfirmParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"op":"replace"}]}]}