{"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/usestripesdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/usestripesdk"]}],"sections":[],"abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any SetupIntent next actions.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If set to false, STPSetupIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser."},{"type":"text","text":" "},{"text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your","type":"text"},{"type":"text","text":" "},{"text":"app.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(py)useStripeSDK","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"useStripeSDK","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"useStripeSDK","kind":"identifier"}],"role":"symbol","title":"useStripeSDK"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useStripeSDK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"type":"text","text":".  Otherwise, it will transition to "},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"text":", and suggest additional actions via ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Instead of passing this to ","type":"text"},{"code":"STPAPIClient.confirmSetupIntent(...)","type":"codeVoice"},{"type":"text","text":" directly, we recommend using "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle any additional steps for you."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"title":"STPSetupIntentConfirmParams","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/useStripeSDK":{"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/usestripesdk","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useStripeSDK"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"useStripeSDK","kind":"identifier"}],"abstract":[{"type":"text","text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any SetupIntent next actions."},{"text":" ","type":"text"},{"type":"text","text":"If set to false, STPSetupIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser."},{"text":" ","type":"text"},{"type":"text","text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your"},{"text":" ","type":"text"},{"type":"text","text":"app."}],"title":"useStripeSDK","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"useStripeSDK","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"useStripeSDK","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"useStripeSDK"}],"platforms":["iOS"]}]}},{"value":"STPSetupIntentConfirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1useStripeSDK\/title","op":"replace","value":"useStripeSDK"},{"value":[{"kind":"identifier","text":"useStripeSDK"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1useStripeSDK\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
