{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK_objc"},"sections":[],"kind":"symbol","abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any SetupIntent next actions.","type":"text"},{"text":" ","type":"text"},{"text":"If set to false, STPSetupIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser.","type":"text"},{"text":" ","type":"text"},{"text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your","type":"text"},{"text":" ","type":"text"},{"text":"app.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(useStripeSDK) "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useStripeSDK_objc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useStripeSDK_objc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"useStripeSDK_objc","role":"symbol","platforms":[],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams(py)useStripeSDK","symbolKind":"property","navigatorTitle":[{"text":"useStripeSDK","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/usestripesdk_objc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams\/usestripesdk_objc"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","title":"STPSetupIntentConfirmParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"type":"text","text":" "},{"type":"text","text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app."},{"type":"text","text":" "},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"type":"text","text":".  Otherwise, it will transition to "},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"type":"text","text":", and suggest additional actions via "},{"code":"nextAction","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"code":"STPAPIClient.confirmSetupIntent(...)","type":"codeVoice"},{"type":"text","text":" directly, we recommend using "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to handle any additional steps for you."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/useStripeSDK_objc":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK_objc","abstract":[{"type":"text","text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any SetupIntent next actions."},{"type":"text","text":" "},{"type":"text","text":"If set to false, STPSetupIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser."},{"type":"text","text":" "},{"type":"text","text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your"},{"type":"text","text":" "},{"type":"text","text":"app."}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/usestripesdk_objc","role":"symbol","deprecated":true,"title":"useStripeSDK_objc","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useStripeSDK_objc","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"useStripeSDK","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"useStripeSDK"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"useStripeSDK"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"useStripeSDK"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","op":"replace","value":"STPSetupIntentConfirmParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1useStripeSDK_objc\/title","op":"replace","value":"useStripeSDK"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1useStripeSDK_objc\/fragments","op":"replace","value":[{"text":"useStripeSDK","kind":"identifier"}]}]}]}