use_frameworks!

target 'CocoapodsTest' do
  platform :ios, '13.0'
  use_frameworks!
  pod 'Stripe', path: '../../../..'
  pod 'StripeIdentity', path: '../../../..'
  pod 'StripeFinancialConnections', path: '../../../..'
  pod 'StripeCardScan', path: '../../../..'
  pod 'StripeApplePay', path: '../../../..'
  pod 'StripeCameraCore', path: '../../../..'
  pod 'StripeConnect', path: '../../../..'
  pod 'StripeCore', path: '../../../..'
  pod 'StripeUICore', path: '../../../..'
  pod 'StripePayments', path: '../../../..'
  pod 'StripePaymentsUI', path: '../../../..'
  pod 'StripePaymentSheet', path: '../../../..'

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
    end
    
    # Set APPLICATION_EXTENSION_API_ONLY for StripeCore when building for app extensions
    installer.pods_project.targets.each do |target|
      if target.name == 'StripeCore'
        target.build_configurations.each do |config|
          # Set the flag to enable conditional compilation
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = '$(inherited) APPLICATION_EXTENSION_API_ONLY'
        end
      end
    end
  end

  target 'CocoapodsTestTests' do
    inherit! :search_paths
  end
end

target 'TestExtension' do
  platform :ios, '13.0'
  use_frameworks!
  pod 'StripeApplePay', path: '../../../..'
  pod 'StripeCore', path: '../../../..'
end
