{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAPI"}],"externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeAPI","title":"STPSetupIntentLastSetupErrorType.API","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"API","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"StripePayments"}]},"abstract":[{"type":"text","text":"An error with the Stripe API."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/api"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/api"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"API"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/API"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The type of the error represented by "},{"code":"STPSetupIntentLastSetupError","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Some STPSetupIntentLastError properties are only populated for certain error types."}],"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype","title":"STPSetupIntentLastSetupErrorType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/API":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeAPI","kind":"identifier"}],"abstract":[{"text":"An error with the Stripe API.","type":"text"}],"title":"STPSetupIntentLastSetupErrorType.API","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/API","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"API"}],"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/api","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"STPSetupIntentLastSetupErrorTypeAPI","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAPI"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSetupIntentLastSetupErrorTypeAPI","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title","value":"STPSetupIntentLastSetupErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1API\/title","value":"STPSetupIntentLastSetupErrorTypeAPI"},{"value":[{"text":"STPSetupIntentLastSetupErrorTypeAPI","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1API\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}