{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPSetupIntentLastSetupErrorTypeAPIConnection) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiConnection"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"An error connecting to Stripe’s API."}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/apiConnection","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeAPIConnection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiConnection"}],"modules":[{"name":"StripePayments"}],"title":"STPSetupIntentLastSetupErrorType.apiConnection","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAPIConnection"}],"role":"symbol","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/apiconnection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/apiconnection"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/apiConnection":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/apiConnection","role":"symbol","kind":"symbol","type":"topic","title":"STPSetupIntentLastSetupErrorType.apiConnection","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/apiconnection","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAPIConnection"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiConnection"}],"abstract":[{"type":"text","text":"An error connecting to Stripe’s API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"abstract":[{"type":"text","text":"The type of the error represented by "},{"type":"codeVoice","code":"STPSetupIntentLastSetupError"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Some STPSetupIntentLastError properties are only populated for certain error types."}],"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype","title":"STPSetupIntentLastSetupErrorType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPSetupIntentLastSetupErrorTypeAPIConnection","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorTypeAPIConnection","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAPIConnection"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1apiConnection\/title","value":"STPSetupIntentLastSetupErrorTypeAPIConnection","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1apiConnection\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAPIConnection"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title","value":"STPSetupIntentLastSetupErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/navigatorTitle","value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"op":"replace"}]}]}