{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/authentication"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"authentication","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/authentication"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/authentication"]}],"abstract":[{"type":"text","text":"A failure to authenticate your customer."}],"sections":[],"metadata":{"symbolKind":"case","title":"STPSetupIntentLastSetupErrorType.authentication","role":"symbol","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeAuthentication","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"authentication","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeAuthentication","modules":[{"name":"StripePayments"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The type of the error represented by "},{"type":"codeVoice","code":"STPSetupIntentLastSetupError"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Some STPSetupIntentLastError properties are only populated for certain error types.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType","type":"topic","title":"STPSetupIntentLastSetupErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/authentication":{"abstract":[{"type":"text","text":"A failure to authenticate your customer."}],"title":"STPSetupIntentLastSetupErrorType.authentication","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authentication"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/authentication","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/authentication","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAuthentication"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPSetupIntentLastSetupErrorTypeAuthentication"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAuthentication"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPSetupIntentLastSetupErrorTypeAuthentication","kind":"identifier"}],"languages":["occ"]}]}},{"value":"STPSetupIntentLastSetupErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1authentication\/title","value":"STPSetupIntentLastSetupErrorTypeAuthentication","op":"replace"},{"op":"replace","value":[{"text":"STPSetupIntentLastSetupErrorTypeAuthentication","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1authentication\/fragments"}]}]}
