{"abstract":[{"text":"Card errors are the most common type of error you should expect to handle.","type":"text"},{"text":" ","type":"text"},{"text":"They result when the user enters a card that can’t be charged for some reason.","type":"text"},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"type":"codeVoice","code":"declineCode"},{"text":" property for the decline code.  The ","type":"text"},{"type":"codeVoice","code":"message"},{"text":" property contains a message you can show to your users.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/card"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/card"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeCard","kind":"identifier"}],"title":"STPSetupIntentLastSetupErrorType.card","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeCard"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/card","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/card":{"abstract":[{"text":"Card errors are the most common type of error you should expect to handle.","type":"text"},{"text":" ","type":"text"},{"text":"They result when the user enters a card that can’t be charged for some reason.","type":"text"},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"code":"declineCode","type":"codeVoice"},{"text":" property for the decline code.  The ","type":"text"},{"code":"message","type":"codeVoice"},{"text":" property contains a message you can show to your users.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/card","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeCard"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/card","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"}],"type":"topic","role":"symbol","title":"STPSetupIntentLastSetupErrorType.card"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"kind":"symbol","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"type":"topic","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPSetupIntentLastSetupError","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Some STPSetupIntentLastError properties are only populated for certain error types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType","title":"STPSetupIntentLastSetupErrorType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPSetupIntentLastSetupErrorTypeCard","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPSetupIntentLastSetupErrorTypeCard","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSetupIntentLastSetupErrorTypeCard","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSetupIntentLastSetupErrorTypeCard","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1card\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeCard"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1card\/fragments","op":"replace"},{"value":"STPSetupIntentLastSetupErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title","op":"replace"},{"value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments","op":"replace"},{"value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/navigatorTitle","op":"replace"}]}]}