{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Keys for idempotent requests can only be used with the same parameters they were first used with.","type":"text"}],"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Case","title":"STPSetupIntentLastSetupErrorType.idempotency","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idempotency","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeIdempotency","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeIdempotency","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/idempotency"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/idempotency"]},{"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/idempotency"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"idempotency","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/idempotency":{"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/idempotency","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Keys for idempotent requests can only be used with the same parameters they were first used with."}],"kind":"symbol","title":"STPSetupIntentLastSetupErrorType.idempotency","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/idempotency","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"idempotency"}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeIdempotency","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"title":"STPSetupIntentLastSetupErrorType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType","abstract":[{"type":"text","text":"The type of the error represented by "},{"type":"codeVoice","code":"STPSetupIntentLastSetupError"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Some STPSetupIntentLastError properties are only populated for certain error types."}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPSetupIntentLastSetupErrorTypeIdempotency","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPSetupIntentLastSetupErrorTypeIdempotency","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"STPSetupIntentLastSetupErrorTypeIdempotency","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"STPSetupIntentLastSetupErrorTypeIdempotency","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1idempotency\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1idempotency\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorTypeIdempotency","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title","value":"STPSetupIntentLastSetupErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/navigatorTitle","value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}]}]}]}