{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"]]},"abstract":[{"type":"text","text":"Too many requests hit the API too quickly."}],"kind":"symbol","metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeRateLimit"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rateLimit","kind":"identifier"}],"title":"STPSetupIntentLastSetupErrorType.rateLimit","externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeRateLimit"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/rateLimit","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/ratelimit"]},{"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/ratelimit"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateLimit"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/rateLimit":{"title":"STPSetupIntentLastSetupErrorType.rateLimit","type":"topic","abstract":[{"type":"text","text":"Too many requests hit the API too quickly."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateLimit"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/rateLimit","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/ratelimit","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeRateLimit"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType","role":"symbol","type":"topic","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPSetupIntentLastSetupError","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Some STPSetupIntentLastError properties are only populated for certain error types.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"kind":"symbol","title":"STPSetupIntentLastSetupErrorType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPSetupIntentLastSetupErrorTypeRateLimit"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPSetupIntentLastSetupErrorTypeRateLimit","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPSetupIntentLastSetupErrorTypeRateLimit","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPSetupIntentLastSetupErrorTypeRateLimit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1rateLimit\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1rateLimit\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorTypeRateLimit","kind":"identifier"}],"op":"replace"},{"value":"STPSetupIntentLastSetupErrorType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title"},{"op":"replace","value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
