{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/unknown"]}],"abstract":[{"type":"text","text":"An unknown error type."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/unknown","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeUnknown","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeUnknown","kind":"identifier"}],"title":"STPSetupIntentLastSetupErrorType.unknown","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"roleHeading":"Case","role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype","title":"STPSetupIntentLastSetupErrorType","abstract":[{"text":"The type of the error represented by ","type":"text"},{"type":"codeVoice","code":"STPSetupIntentLastSetupError"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Some STPSetupIntentLastError properties are only populated for certain error types.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/unknown":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An unknown error type."}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeUnknown","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/unknown","title":"STPSetupIntentLastSetupErrorType.unknown","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPSetupIntentLastSetupErrorTypeUnknown","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeUnknown"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"STPSetupIntentLastSetupErrorTypeUnknown","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSetupIntentLastSetupErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments","op":"replace"},{"value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/navigatorTitle","op":"replace"},{"value":"STPSetupIntentLastSetupErrorTypeUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1unknown\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1unknown\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}