{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formFont","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"formFont","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePaymentsUI@objc(pl)STPFormTextFieldContainer(py)formFont","modules":[{"name":"StripePaymentsUI"}],"title":"formFont","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}]},"abstract":[{"text":"The font used in each child field. Default is ","type":"text"},{"type":"codeVoice","code":".body"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formfont"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formfont"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formFont":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formFont","abstract":[{"text":"The font used in each child field. Default is ","type":"text"},{"type":"codeVoice","code":".body"},{"text":".","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formFont"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"title":"formFont","type":"topic","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formfont","required":true,"navigatorTitle":[{"kind":"identifier","text":"formFont"}],"role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFormTextFieldContainer"}],"navigatorTitle":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain.","type":"text"}],"role":"symbol","title":"STPFormTextFieldContainer"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"url":"\/documentation\/stripepaymentsui","role":"collection","type":"topic","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"formFont","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"formFont","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":" * ","kind":"text"},{"text":"formFont","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"formFont","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formFont\/title","op":"replace"},{"value":[{"kind":"identifier","text":"formFont"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formFont\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title","op":"replace","value":"STPFormTextFieldContainer"},{"value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}