{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formCursorColor"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formCursorColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"The cursor color for the field.","type":"text"},{"text":" ","type":"text"},{"text":"This is a proxy for the view’s tintColor property, exposed for clarity only","type":"text"},{"text":" ","type":"text"},{"text":"(in other words, calling setCursorColor is identical to calling setTintColor).","type":"text"}],"metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@StripePaymentsUI@objc(pl)STPFormTextFieldContainer(py)formCursorColor","navigatorTitle":[{"text":"formCursorColor","kind":"identifier"}],"title":"formCursorColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formCursorColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"required":true,"modules":[{"name":"StripePaymentsUI"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formcursorcolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formcursorcolor"]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"abstract":[{"type":"text","text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","kind":"symbol","title":"STPFormTextFieldContainer","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormTextFieldContainer","kind":"identifier"}],"navigatorTitle":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formCursorColor":{"title":"formCursorColor","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formCursorColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formCursorColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"abstract":[{"text":"The cursor color for the field.","type":"text"},{"text":" ","type":"text"},{"text":"This is a proxy for the view’s tintColor property, exposed for clarity only","type":"text"},{"text":" ","type":"text"},{"text":"(in other words, calling setCursorColor is identical to calling setTintColor).","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formcursorcolor","required":true,"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"formCursorColor","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui","role":"collection","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"formCursorColor","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"formCursorColor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"formCursorColor"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title","value":"STPFormTextFieldContainer","op":"replace"},{"value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments"},{"value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle"},{"value":"formCursorColor","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formCursorColor\/title"},{"value":[{"text":"formCursorColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formCursorColor\/fragments"}]}]}