{"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@StripePaymentsUI@objc(pl)STPFormTextFieldContainer(py)formTextErrorColor","role":"symbol","title":"formTextErrorColor","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"formTextErrorColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"modules":[{"name":"StripePaymentsUI"}],"required":true,"navigatorTitle":[{"text":"formTextErrorColor","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer"]]},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formtexterrorcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formtexterrorcolor"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextErrorColor"},"abstract":[{"type":"text","text":"The text color to be used when the user has entered invalid information,"},{"text":" ","type":"text"},{"type":"text","text":"such as an invalid card number."},{"text":" ","type":"text"},{"text":"Default is ","type":"text"},{"type":"codeVoice","code":".red"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"dynamic","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTextErrorColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","role":"collection","url":"\/documentation\/stripepaymentsui","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formTextErrorColor":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"formTextErrorColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formtexterrorcolor","title":"formTextErrorColor","type":"topic","required":true,"navigatorTitle":[{"text":"formTextErrorColor","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The text color to be used when the user has entered invalid information,"},{"text":" ","type":"text"},{"type":"text","text":"such as an invalid card number."},{"text":" ","type":"text"},{"text":"Default is ","type":"text"},{"code":".red","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextErrorColor","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","abstract":[{"type":"text","text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain."}],"title":"STPFormTextFieldContainer","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormTextFieldContainer"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPFormTextFieldContainer","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"formTextErrorColor","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"formTextErrorColor","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"formTextErrorColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"formTextErrorColor","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formTextErrorColor\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formTextErrorColor\/fragments","value":[{"text":"formTextErrorColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title","value":"STPFormTextFieldContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormTextFieldContainer"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}