{"abstract":[{"type":"text","text":"The text placeholder color used in each child field."},{"type":"text","text":" "},{"type":"text","text":"This will also set the color of the card placeholder icon."},{"type":"text","text":" "},{"type":"text","text":"Default is "},{"type":"codeVoice","code":".placeholderText"},{"type":"text","text":" on iOS 13.0 and "},{"type":"codeVoice","code":".lightGray"},{"type":"text","text":" on earlier versions."}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formPlaceholderColor","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formPlaceholderColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formPlaceholderColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"formPlaceholderColor","kind":"identifier"}],"modules":[{"name":"StripePaymentsUI"}],"symbolKind":"property","required":true,"title":"formPlaceholderColor","externalID":"c:@M@StripePaymentsUI@objc(pl)STPFormTextFieldContainer(py)formPlaceholderColor","roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formplaceholdercolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formplaceholdercolor"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formPlaceholderColor":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formPlaceholderColor","required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formPlaceholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"title":"formPlaceholderColor","abstract":[{"type":"text","text":"The text placeholder color used in each child field."},{"type":"text","text":" "},{"type":"text","text":"This will also set the color of the card placeholder icon."},{"type":"text","text":" "},{"type":"text","text":"Default is "},{"code":".placeholderText","type":"codeVoice"},{"type":"text","text":" on iOS 13.0 and "},{"code":".lightGray","type":"codeVoice"},{"type":"text","text":" on earlier versions."}],"navigatorTitle":[{"kind":"identifier","text":"formPlaceholderColor"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formplaceholdercolor","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","type":"topic","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"abstract":[{"type":"text","text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPFormTextFieldContainer","kind":"identifier"}],"navigatorTitle":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","type":"topic","title":"STPFormTextFieldContainer","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"formPlaceholderColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"formPlaceholderColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"formPlaceholderColor"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formPlaceholderColor\/title","value":"formPlaceholderColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formPlaceholderColor\/fragments","value":[{"kind":"identifier","text":"formPlaceholderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title","value":"STPFormTextFieldContainer"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]}]}]}