{"abstract":[{"text":"The text color to be used when entering valid text. Default is ","type":"text"},{"type":"codeVoice","code":".label"},{"text":" on iOS 13.0 and later and ","type":"text"},{"code":".darkText","type":"codeVoice"},{"text":" on earlier versions.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextColor","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formtextcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formtextcolor"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"dynamic","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTextColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"formTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"StripePaymentsUI"}],"externalID":"c:@M@StripePaymentsUI@objc(pl)STPFormTextFieldContainer(py)formTextColor","required":true,"navigatorTitle":[{"text":"formTextColor","kind":"identifier"}],"title":"formTextColor"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer"]]},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","title":"STPFormTextFieldContainer","navigatorTitle":[{"kind":"identifier","text":"STPFormTextFieldContainer"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPFormTextFieldContainer","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formTextColor":{"title":"formTextColor","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The text color to be used when entering valid text. Default is "},{"code":".label","type":"codeVoice"},{"text":" on iOS 13.0 and later and ","type":"text"},{"type":"codeVoice","code":".darkText"},{"text":" on earlier versions.","type":"text"}],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formTextColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"formTextColor","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formTextColor","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formtextcolor","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"formTextColor"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"formTextColor"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" * ","kind":"text"},{"text":"formTextColor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"STPFormTextFieldContainer","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}]},{"value":"formTextColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formTextColor\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formTextColor\/fragments","value":[{"kind":"identifier","text":"formTextColor"}]}]}]}