{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formKeyboardAppearance"},"abstract":[{"text":"The keyboard appearance for the field.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default is "},{"type":"codeVoice","code":".default"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@StripePaymentsUI@objc(pl)STPFormTextFieldContainer(py)formKeyboardAppearance","required":true,"modules":[{"name":"StripePaymentsUI"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"formKeyboardAppearance","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UIKeyboardAppearance","kind":"typeIdentifier","text":"UIKeyboardAppearance"}],"roleHeading":"Instance Property","title":"formKeyboardAppearance","navigatorTitle":[{"text":"formKeyboardAppearance","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formkeyboardappearance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formkeyboardappearance"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"dynamic","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formKeyboardAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","title":"StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer":{"abstract":[{"type":"text","text":"STPFormTextFieldContainer is a protocol that views can conform to to provide customization properties for the field form views that they contain."}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPFormTextFieldContainer"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer","kind":"symbol","title":"STPFormTextFieldContainer","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFormTextFieldContainer"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPFormTextFieldContainer/formKeyboardAppearance":{"url":"\/documentation\/stripepaymentsui\/stpformtextfieldcontainer\/formkeyboardappearance","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPFormTextFieldContainer\/formKeyboardAppearance","abstract":[{"type":"text","text":"The keyboard appearance for the field."},{"text":" ","type":"text"},{"type":"text","text":"Default is "},{"code":".default","type":"codeVoice"},{"text":".","type":"text"}],"required":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"formKeyboardAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIKeyboardAppearance","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance"}],"navigatorTitle":[{"text":"formKeyboardAppearance","kind":"identifier"}],"title":"formKeyboardAppearance","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"formKeyboardAppearance","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"formKeyboardAppearance"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"formKeyboardAppearance","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/title","value":"STPFormTextFieldContainer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/fragments","value":[{"kind":"identifier","text":"STPFormTextFieldContainer"}]},{"op":"replace","value":[{"text":"STPFormTextFieldContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer\/navigatorTitle"},{"op":"replace","value":"formKeyboardAppearance","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formKeyboardAppearance\/title"},{"op":"replace","value":[{"text":"formKeyboardAppearance","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPFormTextFieldContainer~1formKeyboardAppearance\/fragments"}]}]}