{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/CustomStringConvertible-Implementations"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentusage\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/description","interfaceLanguage":"swift"},"metadata":{"title":"description","role":"symbol","externalID":"s:14StripePayments19STPSetupIntentUsageO11descriptionSSvp","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"extendedModule":"StripePayments"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/description","title":"description","role":"symbol","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentusage\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage":{"type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentusage","title":"STPSetupIntentUsage","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntentUsage"}],"abstract":[{"type":"text","text":"Indicates how the payment method is intended to be used in the future."}],"navigatorTitle":[{"text":"STPSetupIntentUsage","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/CustomStringConvertible-Implementations":{"title":"CustomStringConvertible Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpsetupintentusage\/customstringconvertible-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/CustomStringConvertible-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/title","value":"STPSetupIntentUsage"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/fragments","value":[{"text":"STPSetupIntentUsage","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPSetupIntentUsage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/navigatorTitle"}]}]}