{"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentusage\/offsession"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsetupintentusage\/offsession"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offSession"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsageOffSession"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSetupIntentUsage@STPSetupIntentUsageOffSession","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offSession"}],"roleHeading":"Case","role":"symbol","title":"STPSetupIntentUsage.offSession"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Indicates you intend to reuse the payment method when the customer may or may not be in your checkout flow."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/offSession"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/offSession":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"offSession"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsageOffSession"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentusage\/offsession","title":"STPSetupIntentUsage.offSession","abstract":[{"text":"Indicates you intend to reuse the payment method when the customer may or may not be in your checkout flow.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/offSession"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage":{"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsage"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentusage","abstract":[{"type":"text","text":"Indicates how the payment method is intended to be used in the future."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentUsage","kind":"identifier"}],"title":"STPSetupIntentUsage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPSetupIntentUsageOffSession","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPSetupIntentUsageOffSession"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPSetupIntentUsageOffSession","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPSetupIntentUsageOffSession","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1offSession\/title"},{"value":[{"text":"STPSetupIntentUsageOffSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1offSession\/fragments","op":"replace"},{"value":"STPSetupIntentUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/fragments","op":"replace"},{"value":[{"text":"STPSetupIntentUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/navigatorTitle","op":"replace"}]}]}