{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/onSession"},"abstract":[{"text":"Indicates you intend to only reuse the payment method when the customer is in your checkout flow.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onSession","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentusage\/onsession"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentusage\/onsession"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","title":"STPSetupIntentUsage.onSession","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"onSession","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntentUsageOnSession","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSetupIntentUsage@STPSetupIntentUsageOnSession","symbolKind":"case"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/onSession":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onSession"}],"title":"STPSetupIntentUsage.onSession","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsageOnSession"}],"abstract":[{"text":"Indicates you intend to only reuse the payment method when the customer is in your checkout flow.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/onSession","url":"\/documentation\/stripepayments\/stpsetupintentusage\/onsession"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentusage","title":"STPSetupIntentUsage","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentUsage"}],"abstract":[{"type":"text","text":"Indicates how the payment method is intended to be used in the future."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","role":"symbol","navigatorTitle":[{"text":"STPSetupIntentUsage","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPSetupIntentUsageOnSession"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentUsageOnSession"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPSetupIntentUsageOnSession","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"STPSetupIntentUsageOnSession","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1onSession\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1onSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentUsageOnSession"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/title","op":"replace","value":"STPSetupIntentUsage"},{"value":[{"kind":"identifier","text":"STPSetupIntentUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
