{"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentusage\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentusage\/unknown"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSetupIntentUsage@STPSetupIntentUsageUnknown","navigatorTitle":[{"text":"STPSetupIntentUsageUnknown","kind":"identifier"}],"title":"STPSetupIntentUsage.unknown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/unknown","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage"]]},"abstract":[{"type":"text","text":"Unknown value.  Update your SDK, or use "},{"type":"codeVoice","code":"allResponseFields"},{"type":"text","text":" for custom handling."}],"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/unknown":{"url":"\/documentation\/stripepayments\/stpsetupintentusage\/unknown","kind":"symbol","title":"STPSetupIntentUsage.unknown","abstract":[{"text":"Unknown value.  Update your SDK, or use ","type":"text"},{"code":"allResponseFields","type":"codeVoice"},{"text":" for custom handling.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsageUnknown"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage":{"title":"STPSetupIntentUsage","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentUsage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsage"}],"abstract":[{"type":"text","text":"Indicates how the payment method is intended to be used in the future."}],"url":"\/documentation\/stripepayments\/stpsetupintentusage"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSetupIntentUsageUnknown"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"STPSetupIntentUsageUnknown","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPSetupIntentUsageUnknown","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1unknown\/title","op":"replace","value":"STPSetupIntentUsageUnknown"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentUsageUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1unknown\/fragments"},{"op":"replace","value":"STPSetupIntentUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/fragments","op":"replace","value":[{"text":"STPSetupIntentUsage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/navigatorTitle","value":[{"text":"STPSetupIntentUsage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}