{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/becsdebitformdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/becsdebitformdelegate"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"becsDebitFormDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate","preciseIdentifier":"c:@M@StripePaymentsUI@objc(pl)STPAUBECSDebitFormViewDelegate","text":"STPAUBECSDebitFormViewDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"sections":[],"abstract":[{"type":"text","text":"The delegate to inform about changes to this STPAUBECSDebitFormView instance."}],"metadata":{"title":"becsDebitFormDelegate","modules":[{"name":"StripePaymentsUI"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"becsDebitFormDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(pl)STPAUBECSDebitFormViewDelegate","text":"STPAUBECSDebitFormViewDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"becsDebitFormDelegate","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView(py)becsDebitFormDelegate","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/becsDebitFormDelegate"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormViewDelegate":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormViewDelegate","navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformviewdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormViewDelegate"}],"type":"topic","abstract":[{"type":"text","text":"STPAUBECSDebitFormViewDelegate provides methods for STPAUBECSDebitFormView to inform its delegate"},{"type":"text","text":" "},{"type":"text","text":"of when the form has been completed."}],"kind":"symbol","title":"STPAUBECSDebitFormViewDelegate","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"type":"topic","abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"type":"text","text":" "},{"type":"text","text":"For additional customization options - seealso: STPFormTextFieldContainer"}],"kind":"symbol","title":"STPAUBECSDebitFormView","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/becsDebitFormDelegate":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"becsDebitFormDelegate"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/becsDebitFormDelegate","title":"becsDebitFormDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"becsDebitFormDelegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAUBECSDebitFormViewDelegate","preciseIdentifier":"c:@M@StripePaymentsUI@objc(pl)STPAUBECSDebitFormViewDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/becsdebitformdelegate","role":"symbol","abstract":[{"type":"text","text":"The delegate to inform about changes to this STPAUBECSDebitFormView instance."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"becsDebitFormDelegate","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"becsDebitFormDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<STPAUBECSDebitFormViewDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@StripePaymentsUI@objc(pl)STPAUBECSDebitFormViewDelegate"},{"text":" ","kind":"text"},{"text":"becsDebitFormDelegate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPAUBECSDebitFormViewDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/title"},{"value":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/fragments"},{"value":[{"text":"STPAUBECSDebitFormViewDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormViewDelegate\/navigatorTitle"},{"value":"STPAUBECSDebitFormView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title"},{"value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments"},{"value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle"},{"value":"becsDebitFormDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1becsDebitFormDelegate\/title"},{"value":[{"text":"becsDebitFormDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1becsDebitFormDelegate\/fragments"}]}]}