{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formFont","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView(py)formFont","modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"formFont","kind":"identifier"}],"role":"symbol","title":"formFont","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formFont","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"]]},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/formfont"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/formfont"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/formFont":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/formFont","abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"kind":"identifier","text":"formFont"}],"title":"formFont","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"formFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/formfont","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","title":"STPAUBECSDebitFormView","abstract":[{"text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments.","type":"text"},{"text":" ","type":"text"},{"text":"For additional customization options - seealso: STPFormTextFieldContainer","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"title":"StripePaymentsUI","type":"topic","url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"formFont","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"formFont","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"formFont","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"formFont","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1formFont\/title"},{"value":[{"text":"formFont","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1formFont\/fragments"},{"value":"STPAUBECSDebitFormView","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title"},{"value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments"},{"value":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle"}]}]}