{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"]]},"kind":"symbol","abstract":[{"type":"text","text":"This property will return a non-nil value if and only if the form is in a complete state. The "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"will have it’s "},{"type":"codeVoice","code":"auBECSDebit"},{"type":"text","text":" property populated with the values input in this form."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/paymentmethodparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/paymentmethodparams"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePaymentsUI"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView(py)paymentMethodParams","title":"paymentMethodParams","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":"?","kind":"text"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/paymentMethodParams","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/paymentMethodParams":{"abstract":[{"type":"text","text":"This property will return a non-nil value if and only if the form is in a complete state. The "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":" instance"},{"type":"text","text":" "},{"type":"text","text":"will have it’s "},{"type":"codeVoice","code":"auBECSDebit"},{"type":"text","text":" property populated with the values input in this form."}],"title":"paymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/paymentMethodParams","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/paymentmethodparams","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"type":"topic","role":"symbol","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","title":"STPAUBECSDebitFormView","navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"abstract":[{"text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments.","type":"text"},{"text":" ","type":"text"},{"text":"For additional customization options - seealso: STPFormTextFieldContainer","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","title":"StripePaymentsUI","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paymentMethodParams","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"paymentMethodParams"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"paymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1paymentMethodParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"paymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1paymentMethodParams\/fragments"},{"op":"replace","value":"STPAUBECSDebitFormView","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title"},{"op":"replace","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments"},{"op":"replace","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}