{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemLayoutSizeFitting"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"targetSize","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":", ","kind":"text"},{"text":"withHorizontalFittingPriority","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"horizontalFittingPriority","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UILayoutPriority","text":"UILayoutPriority"},{"kind":"text","text":", "},{"text":"verticalFittingPriority","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UILayoutPriority","text":"UILayoutPriority","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":":nodoc:"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/systemlayoutsizefitting(_:withhorizontalfittingpriority:verticalfittingpriority:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/systemlayoutsizefitting(_:withhorizontalfittingpriority:verticalfittingpriority:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView(im)systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:","roleHeading":"Instance Method","title":"systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)","symbolKind":"method","modules":[{"name":"StripePaymentsUI"}],"navigatorTitle":[{"text":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"systemLayoutSizeFitting","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withHorizontalFittingPriority"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@UILayoutPriority","text":"UILayoutPriority","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"verticalFittingPriority"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@UILayoutPriority","kind":"typeIdentifier","text":"UILayoutPriority"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","url":"\/documentation\/stripepaymentsui","type":"topic","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"abstract":[{"type":"text","text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments."},{"text":" ","type":"text"},{"type":"text","text":"For additional customization options - seealso: STPFormTextFieldContainer"}],"navigatorTitle":[{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","title":"STPAUBECSDebitFormView","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)":{"kind":"symbol","title":"systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemLayoutSizeFitting"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withHorizontalFittingPriority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UILayoutPriority","text":"UILayoutPriority"},{"kind":"text","text":", "},{"text":"verticalFittingPriority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UILayoutPriority","kind":"typeIdentifier","preciseIdentifier":"c:@T@UILayoutPriority"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"text":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/systemlayoutsizefitting(_:withhorizontalfittingpriority:verticalfittingpriority:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"systemLayoutSizeFittingSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"targetSize"},{"text":" ","kind":"text"},{"text":"withHorizontalFittingPriority:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UILayoutPriority","preciseIdentifier":"c:@T@UILayoutPriority"},{"text":") ","kind":"text"},{"text":"horizontalFittingPriority","kind":"internalParam"},{"kind":"text","text":" "},{"text":"verticalFittingPriority:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UILayoutPriority","text":"UILayoutPriority"},{"text":") ","kind":"text"},{"text":"verticalFittingPriority","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"STPAUBECSDebitFormView","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)\/title","value":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1systemLayoutSizeFitting(_:withHorizontalFittingPriority:verticalFittingPriority:)\/fragments"}]}]}