{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"hash","externalID":"c:@M@StripePayments@objc(cs)STPFile(py)hash","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"abstract":[{"text":":nodoc:","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpfile\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfile\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/hash"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/hash":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","title":"hash","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/hash","url":"\/documentation\/stripepayments\/stpfile\/hash"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile":{"url":"\/documentation\/stripepayments\/stpfile","role":"symbol","title":"STPFile","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFile","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of a file upload object in the Stripe API."}],"navigatorTitle":[{"text":"STPFile","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1hash\/fragments"},{"value":"STPFile","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/title"},{"value":[{"kind":"identifier","text":"STPFile"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/fragments"},{"value":[{"kind":"identifier","text":"STPFile"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}