{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"purpose","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","text":"STPFilePurpose","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose"},{"text":" { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/File-Upload","type":"text"}]}],"style":"note","type":"aside"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/purpose"},"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"purpose","navigatorTitle":[{"kind":"identifier","text":"purpose"}],"externalID":"c:@M@StripePayments@objc(cs)STPFile(py)purpose","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"purpose"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","text":"STPFilePurpose"}]},"sections":[],"abstract":[{"type":"text","text":"The purpose of this file. This can be either an identifing document or an evidence dispute."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfile\/purpose"]},{"paths":["\/documentation\/stripepayments\/stpfile\/purpose"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile":{"navigatorTitle":[{"kind":"identifier","text":"STPFile"}],"url":"\/documentation\/stripepayments\/stpfile","abstract":[{"type":"text","text":"Representation of a file upload object in the Stripe API."}],"type":"topic","role":"symbol","title":"STPFile","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFile","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/purpose":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/purpose","role":"symbol","kind":"symbol","abstract":[{"text":"The purpose of this file. This can be either an identifing document or an evidence dispute.","type":"text"}],"title":"purpose","type":"topic","url":"\/documentation\/stripepayments\/stpfile\/purpose","navigatorTitle":[{"kind":"identifier","text":"purpose"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purpose"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","kind":"typeIdentifier","text":"STPFilePurpose"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"abstract":[{"text":"The purpose of the uploaded file.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFilePurpose"}],"title":"STPFilePurpose","url":"\/documentation\/stripepayments\/stpfilepurpose","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFilePurpose"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"purpose","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"purpose"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","text":"STPFilePurpose","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purpose"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/title","value":"STPFile","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/fragments","op":"replace","value":[{"text":"STPFile","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPFile"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/navigatorTitle"},{"value":"purpose","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1purpose\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1purpose\/fragments","value":[{"text":"purpose","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title","op":"replace","value":"STPFilePurpose"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments","value":[{"text":"STPFilePurpose","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPFilePurpose"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/navigatorTitle"}]}]}