{"variants":[{"paths":["\/documentation\/stripepayments\/stpfile\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfile\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { get }"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPFile(py)type","modules":[{"name":"StripePayments"}],"title":"type","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property"},"kind":"symbol","sections":[],"abstract":[{"text":"The file type. This can be “jpg”, “png”, or “pdf”.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/type","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile":{"role":"symbol","url":"\/documentation\/stripepayments\/stpfile","type":"topic","navigatorTitle":[{"text":"STPFile","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile","title":"STPFile","kind":"symbol","abstract":[{"type":"text","text":"Representation of a file upload object in the Stripe API."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFile","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/type":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The file type. This can be “jpg”, “png”, or “pdf”."}],"title":"type","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpfile\/type","navigatorTitle":[{"kind":"identifier","text":"type"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"type","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"type"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPFile","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/fragments","value":[{"kind":"identifier","text":"STPFile"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/navigatorTitle","op":"replace","value":[{"text":"STPFile","kind":"identifier"}]},{"op":"replace","value":"type","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1type\/title"},{"value":[{"kind":"identifier","text":"type"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1type\/fragments","op":"replace"}]}]}