{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/alipayhandleredirect"]},{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/alipayhandleredirect"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alipayHandleRedirect"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeAlipayHandleRedirect"}],"roleHeading":"Case","title":"STPIntentActionType.alipayHandleRedirect","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeAlipayHandleRedirect","modules":[{"name":"StripePayments"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/alipayHandleRedirect"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alipayHandleRedirect"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPIntentActionType","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"type":"topic","title":"STPIntentActionType","url":"\/documentation\/stripepayments\/stpintentactiontype","abstract":[{"text":"Types of next actions for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/alipayHandleRedirect":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"alipayHandleRedirect","kind":"identifier"}],"abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/alipayHandleRedirect","kind":"symbol","title":"STPIntentActionType.alipayHandleRedirect","url":"\/documentation\/stripepayments\/stpintentactiontype\/alipayhandleredirect","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeAlipayHandleRedirect"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPIntentActionTypeAlipayHandleRedirect"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPIntentActionTypeAlipayHandleRedirect"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPIntentActionTypeAlipayHandleRedirect"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPIntentActionType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPIntentActionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1alipayHandleRedirect\/title","value":"STPIntentActionTypeAlipayHandleRedirect","op":"replace"},{"op":"replace","value":[{"text":"STPIntentActionTypeAlipayHandleRedirect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1alipayHandleRedirect\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}