{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/BLIKAuthorize","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"The action type for BLIK payment methods. The customer must authorize the transaction in their banking app within 1 minute.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"STPIntentActionType.BLIKAuthorize","symbolKind":"case","modules":[{"name":"StripePayments"}],"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeBLIKAuthorize"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BLIKAuthorize"}],"externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeBLIKAuthorize"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BLIKAuthorize"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/blikauthorize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/blikauthorize"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/BLIKAuthorize":{"abstract":[{"text":"The action type for BLIK payment methods. The customer must authorize the transaction in their banking app within 1 minute.","type":"text"}],"kind":"symbol","title":"STPIntentActionType.BLIKAuthorize","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/BLIKAuthorize","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BLIKAuthorize"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeBLIKAuthorize"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/blikauthorize"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"type":"topic","abstract":[{"text":"Types of next actions for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","title":"STPIntentActionType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPIntentActionTypeBLIKAuthorize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPIntentActionTypeBLIKAuthorize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPIntentActionTypeBLIKAuthorize","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1BLIKAuthorize\/title","value":"STPIntentActionTypeBLIKAuthorize"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1BLIKAuthorize\/fragments","value":[{"text":"STPIntentActionTypeBLIKAuthorize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"text":"STPIntentActionType","kind":"identifier"}]}]}]}