{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/boletodisplaydetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/boletodisplaydetails"]}],"abstract":[{"text":"The action type is Boleto payment. We provide ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to display the Boleto voucher."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/boletoDisplayDetails"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"boletoDisplayDetails","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"sections":[],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"boletoDisplayDetails","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionTypeBoletoDisplayDetails","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeBoletoDisplayDetails","title":"STPIntentActionType.boletoDisplayDetails"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/boletoDisplayDetails":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"boletoDisplayDetails"}],"title":"STPIntentActionType.boletoDisplayDetails","url":"\/documentation\/stripepayments\/stpintentactiontype\/boletodisplaydetails","navigatorTitle":[{"text":"STPIntentActionTypeBoletoDisplayDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/boletoDisplayDetails","abstract":[{"type":"text","text":"The action type is Boleto payment. We provide "},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" to display the Boleto voucher.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","title":"STPIntentActionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"abstract":[{"text":"Types of next actions for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPIntentActionTypeBoletoDisplayDetails","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"STPIntentActionTypeBoletoDisplayDetails"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPIntentActionTypeBoletoDisplayDetails"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1boletoDisplayDetails\/title","op":"replace","value":"STPIntentActionTypeBoletoDisplayDetails"},{"value":[{"text":"STPIntentActionTypeBoletoDisplayDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1boletoDisplayDetails\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"text":"STPIntentActionType","kind":"identifier"}]}]}]}