{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cashAppRedirectToApp"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/cashappredirecttoapp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/cashappredirecttoapp"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/cashAppRedirectToApp","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"metadata":{"externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeCashAppRedirectToApp","title":"STPIntentActionType.cashAppRedirectToApp","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cashAppRedirectToApp"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeCashAppRedirectToApp"}],"role":"symbol"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/cashAppRedirectToApp":{"role":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype\/cashappredirecttoapp","abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeCashAppRedirectToApp"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/cashAppRedirectToApp","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cashAppRedirectToApp"}],"title":"STPIntentActionType.cashAppRedirectToApp"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","title":"STPIntentActionType","url":"\/documentation\/stripepayments\/stpintentactiontype","kind":"symbol","abstract":[{"type":"text","text":"Types of next actions for "},{"code":"STPPaymentIntent","type":"codeVoice"},{"type":"text","text":" and "},{"code":"STPSetupIntent","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" will handle any next actions for you."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionType"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPIntentActionTypeCashAppRedirectToApp","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPIntentActionTypeCashAppRedirectToApp","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPIntentActionTypeCashAppRedirectToApp","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPIntentActionTypeCashAppRedirectToApp","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1cashAppRedirectToApp\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1cashAppRedirectToApp\/fragments","value":[{"kind":"identifier","text":"STPIntentActionTypeCashAppRedirectToApp"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPIntentActionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionType"}],"op":"replace"}]}]}