{"kind":"symbol","sections":[],"metadata":{"title":"hashValue","symbolKind":"property","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"extendedModule":"Swift","roleHeading":"Instance Property","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@StripePayments@E@STPIntentActionType","modules":[{"relatedModules":["Swift"],"name":"StripePayments"}]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/RawRepresentable-Implementations"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/hashValue","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/hashValue":{"type":"topic","kind":"symbol","abstract":[],"role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hashValue","url":"\/documentation\/stripepayments\/stpintentactiontype\/hashvalue","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/hashValue"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"title":"STPIntentActionType","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"abstract":[{"text":"Types of next actions for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" will handle any next actions for you."}],"url":"\/documentation\/stripepayments\/stpintentactiontype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPIntentActionType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/RawRepresentable-Implementations":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/RawRepresentable-Implementations","kind":"article","url":"\/documentation\/stripepayments\/stpintentactiontype\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}