{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"metadata":{"roleHeading":"Initializer","title":"init(rawValue:)","role":"symbol","externalID":"s:14StripePayments19STPIntentActionTypeO8rawValueACSgSi_tcfc","modules":[{"name":"StripePayments"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/init(rawValue:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/init(rawvalue:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPIntentActionType","kind":"identifier"}],"abstract":[{"type":"text","text":"Types of next actions for "},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"kind":"symbol","title":"STPIntentActionType","type":"topic","url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stpintentactiontype\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionType"}]}]}]}