{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multibancoDisplayDetails"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/multibancoDisplayDetails"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/multibancodisplaydetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/multibancodisplaydetails"]}],"kind":"symbol","metadata":{"title":"STPIntentActionType.multibancoDisplayDetails","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeMultibancoDisplayDetails","role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multibancoDisplayDetails"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeMultibancoDisplayDetails"}],"symbolKind":"case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The action type is Multibanco payment. We provide ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to display the Multibanco voucher."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"type":"topic","abstract":[{"text":"Types of next actions for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","title":"STPIntentActionType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/multibancoDisplayDetails":{"type":"topic","title":"STPIntentActionType.multibancoDisplayDetails","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/multibancoDisplayDetails","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multibancoDisplayDetails"}],"abstract":[{"type":"text","text":"The action type is Multibanco payment. We provide "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to display the Multibanco voucher."}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/multibancodisplaydetails","navigatorTitle":[{"text":"STPIntentActionTypeMultibancoDisplayDetails","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPIntentActionTypeMultibancoDisplayDetails","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeMultibancoDisplayDetails"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPIntentActionTypeMultibancoDisplayDetails"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPIntentActionType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1multibancoDisplayDetails\/title","value":"STPIntentActionTypeMultibancoDisplayDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1multibancoDisplayDetails\/fragments","value":[{"text":"STPIntentActionTypeMultibancoDisplayDetails","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}