{"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/oxxodisplaydetails"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/oxxodisplaydetails"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/OXXODisplayDetails","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OXXODisplayDetails"}],"navigatorTitle":[{"text":"STPIntentActionTypeOXXODisplayDetails","kind":"identifier"}],"role":"symbol","roleHeading":"Case","title":"STPIntentActionType.OXXODisplayDetails","externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeOXXODisplayDetails","symbolKind":"case","modules":[{"name":"StripePayments"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"The action type is OXXO payment. We provide ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to display"},{"type":"text","text":" "},{"text":"the OXXO voucher.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OXXODisplayDetails"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"kind":"symbol","abstract":[{"type":"text","text":"Types of next actions for "},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"role":"symbol","type":"topic","title":"STPIntentActionType","url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/OXXODisplayDetails":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"OXXODisplayDetails","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The action type is OXXO payment. We provide "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to display"},{"type":"text","text":" "},{"type":"text","text":"the OXXO voucher."}],"navigatorTitle":[{"text":"STPIntentActionTypeOXXODisplayDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/oxxodisplaydetails","title":"STPIntentActionType.OXXODisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/OXXODisplayDetails"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPIntentActionTypeOXXODisplayDetails"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeOXXODisplayDetails"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"STPIntentActionTypeOXXODisplayDetails","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPIntentActionType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"value":[{"kind":"identifier","text":"STPIntentActionType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1OXXODisplayDetails\/title","value":"STPIntentActionTypeOXXODisplayDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1OXXODisplayDetails\/fragments","op":"replace","value":[{"text":"STPIntentActionTypeOXXODisplayDetails","kind":"identifier"}]}]}]}