{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/payNowDisplayQrCode","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PayNow."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/paynowdisplayqrcode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/paynowdisplayqrcode"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypePayNowDisplayQrCode","navigatorTitle":[{"text":"STPIntentActionTypePayNowDisplayQrCode","kind":"identifier"}],"roleHeading":"Case","title":"STPIntentActionType.payNowDisplayQrCode","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"payNowDisplayQrCode"}],"symbolKind":"case","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"payNowDisplayQrCode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/payNowDisplayQrCode":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"payNowDisplayQrCode","kind":"identifier"}],"kind":"symbol","title":"STPIntentActionType.payNowDisplayQrCode","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypePayNowDisplayQrCode"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/paynowdisplayqrcode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/payNowDisplayQrCode","abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PayNow."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"type":"topic","title":"STPIntentActionType","abstract":[{"text":"Types of next actions for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" will handle any next actions for you."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionType"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","value":"STPIntentActionTypePayNowDisplayQrCode","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPIntentActionTypePayNowDisplayQrCode"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPIntentActionTypePayNowDisplayQrCode","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"STPIntentActionTypePayNowDisplayQrCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1payNowDisplayQrCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1payNowDisplayQrCode\/fragments","value":[{"text":"STPIntentActionTypePayNowDisplayQrCode","kind":"identifier"}]},{"value":"STPIntentActionType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","op":"replace","value":[{"text":"STPIntentActionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}