{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/promptpayDisplayQrCode"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"title":"STPIntentActionType.promptpayDisplayQrCode","symbolKind":"case","roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypePromptpayDisplayQrCode"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptpayDisplayQrCode"}],"externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypePromptpayDisplayQrCode","modules":[{"name":"StripePayments"}]},"sections":[],"abstract":[{"text":"Contains details for displaying the QR code required for PromptPay.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptpayDisplayQrCode"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/promptpaydisplayqrcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/promptpaydisplayqrcode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/promptpayDisplayQrCode":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"promptpayDisplayQrCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionTypePromptpayDisplayQrCode","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PromptPay."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/promptpayDisplayQrCode","title":"STPIntentActionType.promptpayDisplayQrCode","url":"\/documentation\/stripepayments\/stpintentactiontype\/promptpaydisplayqrcode","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"type":"topic","abstract":[{"text":"Types of next actions for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","title":"STPIntentActionType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionType"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPIntentActionTypePromptpayDisplayQrCode","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPIntentActionTypePromptpayDisplayQrCode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPIntentActionTypePromptpayDisplayQrCode"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPIntentActionTypePromptpayDisplayQrCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1promptpayDisplayQrCode\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1promptpayDisplayQrCode\/fragments","value":[{"kind":"identifier","text":"STPIntentActionTypePromptpayDisplayQrCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPIntentActionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}