{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/redirectToURL","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeRedirectToURL","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"redirectToURL"}],"role":"symbol","title":"STPIntentActionType.redirectToURL","navigatorTitle":[{"text":"STPIntentActionTypeRedirectToURL","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"sections":[],"abstract":[{"type":"text","text":"The payment intent needs to be authorized by the user. We provide"},{"text":" ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" to handle the url redirections necessary."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectToURL"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/redirecttourl"]},{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/redirecttourl"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/redirectToURL":{"abstract":[{"text":"The payment intent needs to be authorized by the user. We provide","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" to handle the url redirections necessary.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectToURL"}],"title":"STPIntentActionType.redirectToURL","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/redirectToURL","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeRedirectToURL"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/redirecttourl","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPIntentActionType","kind":"identifier"}],"abstract":[{"type":"text","text":"Types of next actions for "},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"STPSetupIntent","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"kind":"symbol","title":"STPIntentActionType","type":"topic","url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"STPIntentActionTypeRedirectToURL","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPIntentActionTypeRedirectToURL","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPIntentActionTypeRedirectToURL"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1redirectToURL\/title","value":"STPIntentActionTypeRedirectToURL","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1redirectToURL\/fragments","value":[{"text":"STPIntentActionTypeRedirectToURL","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace"}]}]}