{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/swishHandleRedirect","interfaceLanguage":"swift"},"metadata":{"title":"STPIntentActionType.swishHandleRedirect","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeSwishHandleRedirect","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"STPIntentActionTypeSwishHandleRedirect","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swishHandleRedirect","kind":"identifier"}]},"abstract":[{"text":"Contains details for redirecting to the Swish app.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swishHandleRedirect","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/swishhandleredirect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/swishhandleredirect"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/swishHandleRedirect":{"navigatorTitle":[{"text":"STPIntentActionTypeSwishHandleRedirect","kind":"identifier"}],"title":"STPIntentActionType.swishHandleRedirect","type":"topic","kind":"symbol","abstract":[{"text":"Contains details for redirecting to the Swish app.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swishHandleRedirect","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/swishHandleRedirect","role":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype\/swishhandleredirect"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","title":"STPIntentActionType","url":"\/documentation\/stripepayments\/stpintentactiontype","kind":"symbol","abstract":[{"type":"text","text":"Types of next actions for "},{"code":"STPPaymentIntent","type":"codeVoice"},{"type":"text","text":" and "},{"code":"STPSetupIntent","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" will handle any next actions for you."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionType"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPIntentActionTypeSwishHandleRedirect","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPIntentActionTypeSwishHandleRedirect","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPIntentActionTypeSwishHandleRedirect"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPIntentActionTypeSwishHandleRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1swishHandleRedirect\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionTypeSwishHandleRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1swishHandleRedirect\/fragments","op":"replace"},{"value":"STPIntentActionType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","op":"replace"},{"value":[{"text":"STPIntentActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","op":"replace"}]}]}