{"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"title":"STPIntentActionType.unknown","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeUnknown"}],"externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeUnknown"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/unknown"},"abstract":[{"text":"This is an unknown action that’s been added since the SDK","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"was last updated."},{"text":" ","type":"text"},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"nextAction.allResponseFields"},{"type":"text","text":" "},{"text":"for custom handling.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"kind":"symbol","abstract":[{"type":"text","text":"Types of next actions for "},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"You shouldn’t need to inspect this yourself; ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" will handle any next actions for you.","type":"text"}],"role":"symbol","type":"topic","title":"STPIntentActionType","url":"\/documentation\/stripepayments\/stpintentactiontype","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/unknown":{"type":"topic","abstract":[{"text":"This is an unknown action that’s been added since the SDK","type":"text"},{"type":"text","text":" "},{"type":"text","text":"was last updated."},{"text":" ","type":"text"},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"nextAction.allResponseFields"},{"text":" ","type":"text"},{"type":"text","text":"for custom handling."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/unknown","url":"\/documentation\/stripepayments\/stpintentactiontype\/unknown","role":"symbol","title":"STPIntentActionType.unknown","navigatorTitle":[{"text":"STPIntentActionTypeUnknown","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPIntentActionTypeUnknown"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPIntentActionTypeUnknown"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPIntentActionTypeUnknown"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","op":"replace","value":"STPIntentActionType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"text":"STPIntentActionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1unknown\/title","value":"STPIntentActionTypeUnknown"},{"value":[{"kind":"identifier","text":"STPIntentActionTypeUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1unknown\/fragments","op":"replace"}]}]}