{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upiAwaitNotification"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/upiawaitnotification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/upiawaitnotification"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/upiAwaitNotification","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The action type for UPI payment methods. The customer must complete the transaction in their banking app within 5 minutes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upiAwaitNotification"}],"title":"STPIntentActionType.upiAwaitNotification","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeUpiAwaitNotification","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeUpiAwaitNotification"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"role":"symbol","title":"STPIntentActionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionType"}],"abstract":[{"type":"text","text":"Types of next actions for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" will handle any next actions for you."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionType"}],"url":"\/documentation\/stripepayments\/stpintentactiontype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/upiAwaitNotification":{"role":"symbol","title":"STPIntentActionType.upiAwaitNotification","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"upiAwaitNotification"}],"abstract":[{"type":"text","text":"The action type for UPI payment methods. The customer must complete the transaction in their banking app within 5 minutes."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/upiAwaitNotification","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeUpiAwaitNotification"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/upiawaitnotification"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPIntentActionTypeUpiAwaitNotification"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPIntentActionTypeUpiAwaitNotification"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPIntentActionTypeUpiAwaitNotification"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1upiAwaitNotification\/title","value":"STPIntentActionTypeUpiAwaitNotification"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1upiAwaitNotification\/fragments","value":[{"kind":"identifier","text":"STPIntentActionTypeUpiAwaitNotification"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}