{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The payment intent requires additional action handled by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":"."}],"metadata":{"modules":[{"name":"StripePayments"}],"title":"STPIntentActionType.useStripeSDK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"useStripeSDK"}],"externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeUseStripeSDK","navigatorTitle":[{"text":"STPIntentActionTypeUseStripeSDK","kind":"identifier"}],"symbolKind":"case","role":"symbol","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/useStripeSDK"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useStripeSDK","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/usestripesdk"]},{"paths":["\/documentation\/stripepayments\/stpintentactiontype\/usestripesdk"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/useStripeSDK":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"useStripeSDK","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/usestripesdk","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/useStripeSDK","title":"STPIntentActionType.useStripeSDK","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeUseStripeSDK"}],"abstract":[{"type":"text","text":"The payment intent requires additional action handled by "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":"."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","abstract":[{"text":"Types of next actions for ","type":"text"},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" will handle any next actions for you."}],"url":"\/documentation\/stripepayments\/stpintentactiontype","title":"STPIntentActionType","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPIntentActionTypeUseStripeSDK","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPIntentActionTypeUseStripeSDK","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPIntentActionTypeUseStripeSDK"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1useStripeSDK\/title","op":"replace","value":"STPIntentActionTypeUseStripeSDK"},{"value":[{"text":"STPIntentActionTypeUseStripeSDK","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1useStripeSDK\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","value":"STPIntentActionType"},{"value":[{"kind":"identifier","text":"STPIntentActionType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}