{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyWithMicrodeposits"}],"title":"STPIntentActionType.verifyWithMicrodeposits","modules":[{"name":"StripePayments"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeVerifyWithMicrodeposits","navigatorTitle":[{"text":"STPIntentActionTypeVerifyWithMicrodeposits","kind":"identifier"}]},"abstract":[{"type":"text","text":"Contains details describing the microdeposits verification flow for US Bank Account payments"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyWithMicrodeposits"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/verifyWithMicrodeposits","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/verifywithmicrodeposits"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/verifywithmicrodeposits"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionType"}],"title":"STPIntentActionType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","abstract":[{"type":"text","text":"Types of next actions for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"code":"STPSetupIntent","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" will handle any next actions for you."}],"url":"\/documentation\/stripepayments\/stpintentactiontype","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/verifyWithMicrodeposits":{"type":"topic","title":"STPIntentActionType.verifyWithMicrodeposits","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeVerifyWithMicrodeposits"}],"abstract":[{"type":"text","text":"Contains details describing the microdeposits verification flow for US Bank Account payments"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyWithMicrodeposits"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype\/verifywithmicrodeposits","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/verifyWithMicrodeposits","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPIntentActionTypeVerifyWithMicrodeposits"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeVerifyWithMicrodeposits"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPIntentActionTypeVerifyWithMicrodeposits"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title","op":"replace","value":"STPIntentActionType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1verifyWithMicrodeposits\/title","op":"replace","value":"STPIntentActionTypeVerifyWithMicrodeposits"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1verifyWithMicrodeposits\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeVerifyWithMicrodeposits"}]}]}]}