{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"]]},"metadata":{"symbolKind":"case","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPIntentActionType@STPIntentActionTypeWeChatPayRedirectToApp","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"weChatPayRedirectToApp"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeWeChatPayRedirectToApp"}],"title":"STPIntentActionType.weChatPayRedirectToApp","roleHeading":"Case"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/weChatPayRedirectToApp","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to the WeChat Pay App."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/wechatpayredirecttoapp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactiontype\/wechatpayredirecttoapp"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPayRedirectToApp","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"role":"symbol","type":"topic","title":"STPIntentActionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"abstract":[{"type":"text","text":"Types of next actions for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" will handle any next actions for you."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","kind":"symbol","navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactiontype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/weChatPayRedirectToApp":{"title":"STPIntentActionType.weChatPayRedirectToApp","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype\/wechatpayredirecttoapp","navigatorTitle":[{"text":"STPIntentActionTypeWeChatPayRedirectToApp","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPayRedirectToApp","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/weChatPayRedirectToApp","type":"topic","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to the WeChat Pay App."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPIntentActionTypeWeChatPayRedirectToApp","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPIntentActionTypeWeChatPayRedirectToApp","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPIntentActionTypeWeChatPayRedirectToApp","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPIntentActionType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1weChatPayRedirectToApp\/title","op":"replace","value":"STPIntentActionTypeWeChatPayRedirectToApp"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1weChatPayRedirectToApp\/fragments","op":"replace","value":[{"text":"STPIntentActionTypeWeChatPayRedirectToApp","kind":"identifier"}]}]}]}