{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp\/nativeURL"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp\/nativeurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp\/nativeurl"]}],"metadata":{"title":"nativeURL","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"nativeURL","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionWechatPayRedirectToApp(py)nativeURL","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}]},"abstract":[{"text":"The native URL you must redirect your customer to in order to authenticate the payment.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp"]]},"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionWechatPayRedirectToApp":{"title":"STPIntentActionWechatPayRedirectToApp","kind":"symbol","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to WeChat Pay app."},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentActionWechatPayRedirectToApp"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentActionWechatPayRedirectToApp","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionWechatPayRedirectToApp","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionWechatPayRedirectToApp/nativeURL":{"title":"nativeURL","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp\/nativeURL","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nativeURL"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"nativeURL","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp\/nativeurl","abstract":[{"type":"text","text":"The native URL you must redirect your customer to in order to authenticate the payment."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"nativeURL"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nativeURL"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"nativeURL"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/title","value":"STPIntentActionWechatPayRedirectToApp","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionWechatPayRedirectToApp"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionWechatPayRedirectToApp"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/navigatorTitle"},{"op":"replace","value":"nativeURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp~1nativeURL\/title"},{"value":[{"kind":"identifier","text":"nativeURL"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp~1nativeURL\/fragments","op":"replace"}]}]}