{"topicSections":[{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp\/decodedObject(fromAPIResponse:)"]}],"metadata":{"role":"collectionGroup","title":"STPAPIResponseDecodable Implementations","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp\/stpapiresponsedecodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp\/stpapiresponsedecodable-implementations"]}],"kind":"article","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp\/STPAPIResponseDecodable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionWechatPayRedirectToApp":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to WeChat Pay app."},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentActionWechatPayRedirectToApp"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp","title":"STPIntentActionWechatPayRedirectToApp","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentActionWechatPayRedirectToApp","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionWechatPayRedirectToApp","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionWechatPayRedirectToApp/decodedObject(fromAPIResponse:)":{"title":"decodedObject(fromAPIResponse:)","type":"topic","role":"symbol","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"an "},{"code":"NSDictionary","type":"codeVoice"},{"type":"text","text":") into an instance of the class."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"text":"fromAPIResponse","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"url":"\/documentation\/stripepayments\/stpintentactionwechatpayredirecttoapp\/decodedobject(fromapiresponse:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp\/decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionWechatPayRedirectToApp\/decodedObject(fromAPIResponse:)"],"title":"Type Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/title","value":"STPIntentActionWechatPayRedirectToApp"},{"value":[{"text":"STPIntentActionWechatPayRedirectToApp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp\/navigatorTitle","op":"replace","value":[{"text":"STPIntentActionWechatPayRedirectToApp","kind":"identifier"}]},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp~1decodedObject(fromAPIResponse:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionWechatPayRedirectToApp~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
