{"abstract":[{"type":"text","text":"The reference of the mandate accepted by your customer. - seealso: https:\/\/stripe.com\/docs\/api\/sources\/create#create_source-mandate"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodsepadebit\/mandate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodsepadebit\/mandate"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSEPADebit\/mandate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mandate"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSEPADebit"]]},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodSEPADebit(py)mandate","roleHeading":"Instance Property","symbolKind":"property","title":"mandate","role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mandate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"mandate"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSEPADebit/mandate":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSEPADebit\/mandate","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodsepadebit\/mandate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mandate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The reference of the mandate accepted by your customer. - seealso: https:\/\/stripe.com\/docs\/api\/sources\/create#create_source-mandate"}],"role":"symbol","navigatorTitle":[{"text":"mandate","kind":"identifier"}],"kind":"symbol","title":"mandate"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSEPADebit":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodSEPADebit"}],"abstract":[{"type":"text","text":"A SEPA Debit Payment Method."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSEPADebit","role":"symbol","title":"STPPaymentMethodSEPADebit","url":"\/documentation\/stripepayments\/stppaymentmethodsepadebit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodSEPADebit"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mandate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"mandate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"mandate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSEPADebit~1mandate\/title","value":"mandate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSEPADebit~1mandate\/fragments","value":[{"text":"mandate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSEPADebit\/title","value":"STPPaymentMethodSEPADebit"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSEPADebit\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodSEPADebit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSEPADebit\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodSEPADebit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}