{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bankCodeFrom","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"brand","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPFPXBankBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"isBusiness","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand you want to convert to an FPX bank code"}]}],"name":"brand"},{"content":[{"inlineContent":[{"type":"text","text":"Requests the code for the business version of this bank brand, which may be different from the code used for individual accounts"}],"type":"paragraph"}],"name":"isBusiness"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A string representing the brand, suitable for checking against the FPX status API.","type":"text"}]}]}],"sections":[],"abstract":[{"type":"text","text":"Returns the code identifying the provided bank brand in the FPX status API;"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"type":"codeVoice","code":"STPIdentifierFromFPXBankBrand(STPCardBrandUob) ==  @\"UOB0226\""},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank"]]},"metadata":{"roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bankCodeFrom","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"externalID":"c:@M@StripePayments@objc(cs)STPFPXBank(cm)bankCodeFrom::","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bankCodeFrom::"}],"modules":[{"name":"StripePayments"}],"title":"bankCodeFrom(_:_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/bankCodeFrom(_:_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/bankcodefrom(_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/bankcodefrom(_:_:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank","role":"symbol","abstract":[{"type":"text","text":"Convenience methods for using FPX bank brands."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFPXBank"}],"navigatorTitle":[{"text":"STPFPXBank","kind":"identifier"}],"title":"STPFPXBank","kind":"symbol","url":"\/documentation\/stripepayments\/stpfpxbank"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/bankCodeFrom(_:_:)":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bankCodeFrom::"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bankCodeFrom","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand"},{"kind":"text","text":", "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpfpxbank\/bankcodefrom(_:_:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/bankCodeFrom(_:_:)","abstract":[{"type":"text","text":"Returns the code identifying the provided bank brand in the FPX status API;"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"type":"codeVoice","code":"STPIdentifierFromFPXBankBrand(STPCardBrandUob) ==  @\"UOB0226\""},{"type":"text","text":"."}],"kind":"symbol","title":"bankCodeFrom(_:_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","title":"STPFPXBankBrand","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFPXBankBrand"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bankCodeFrom::"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bankCodeFrom::"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bankCodeFrom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"brand"},{"kind":"text","text":" "},{"text":":","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isBusiness"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/title","value":"STPFPXBank"},{"value":[{"kind":"identifier","text":"STPFPXBank"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1bankCodeFrom(_:_:)\/title","op":"replace","value":"bankCodeFrom::"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1bankCodeFrom(_:_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"bankCodeFrom::"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","op":"replace","value":"STPFPXBankBrand"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"text":"STPFPXBankBrand","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
