{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/brandFrom(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Returns a bank brand provided a string representation identifying a bank brand;","type":"text"},{"text":" ","type":"text"},{"text":"i.e. ","type":"text"},{"code":"STPFPXBankBrandFromIdentifier(@\"uob\") == STPCardBrandUob","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brandFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"STPFPXBankBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The identifier for the brand"}]}],"name":"identifier"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The STPFPXBankBrand enum value"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/brandfrom(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/brandfrom(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandFrom"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand","kind":"typeIdentifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPFPXBank(cm)brandFrom:","modules":[{"name":"StripePayments"}],"symbolKind":"method","navigatorTitle":[{"text":"brandFrom:","kind":"identifier"}],"title":"brandFrom(_:)","role":"symbol"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/brandFrom(_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/brandFrom(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brandFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","kind":"typeIdentifier","text":"STPFPXBankBrand"}],"type":"topic","abstract":[{"text":"Returns a bank brand provided a string representation identifying a bank brand;","type":"text"},{"text":" ","type":"text"},{"text":"i.e. ","type":"text"},{"code":"STPFPXBankBrandFromIdentifier(@\"uob\") == STPCardBrandUob","type":"codeVoice"},{"text":".","type":"text"}],"title":"brandFrom(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"brandFrom:"}],"url":"\/documentation\/stripepayments\/stpfpxbank\/brandfrom(_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"type":"topic","kind":"symbol","title":"STPFPXBankBrand","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"}],"abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"navigatorTitle":[{"text":"STPFPXBankBrand","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","url":"\/documentation\/stripepayments\/stpfpxbankbrand","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank":{"navigatorTitle":[{"text":"STPFPXBank","kind":"identifier"}],"abstract":[{"text":"Convenience methods for using FPX bank brands.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank","title":"STPFPXBank","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBank","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpfpxbank","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"brandFrom:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"brandFrom:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand"},{"text":") ","kind":"text"},{"text":"brandFrom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The identifier for the brand","type":"text"}]}],"name":"identifier"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The STPFPXBankBrand enum value","type":"text"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"brandFrom:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1brandFrom(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"brandFrom:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1brandFrom(_:)\/fragments"},{"op":"replace","value":"STPFPXBankBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title"},{"op":"replace","value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments"},{"op":"replace","value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle"},{"op":"replace","value":"STPFPXBank","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPFPXBank"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPFPXBank"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}