{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/identifierfrom(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/identifierfrom(_:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/identifierFrom(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank"]]},"sections":[],"abstract":[{"text":"Returns a string representation identifying the provided bank brand;","type":"text"},{"text":" ","type":"text"},{"text":"i.e. ","type":"text"},{"code":"STPIdentifierFromFPXBankBrand(STPCardBrandUob) ==  @\"uob\"","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifierFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPFPXBankBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The brand you want to convert to a string"}]}],"name":"brand"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"A string representing the brand, suitable for using with the Stripe API.","type":"text"}]}],"kind":"content"}],"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"title":"identifierFrom(_:)","roleHeading":"Type Method","navigatorTitle":[{"text":"identifierFrom:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPFPXBank(cm)identifierFrom:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifierFrom","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/identifierFrom(_:)":{"navigatorTitle":[{"text":"identifierFrom:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpfpxbank\/identifierfrom(_:)","abstract":[{"text":"Returns a string representation identifying the provided bank brand;","type":"text"},{"text":" ","type":"text"},{"text":"i.e. ","type":"text"},{"code":"STPIdentifierFromFPXBankBrand(STPCardBrandUob) ==  @\"uob\"","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","title":"identifierFrom(_:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/identifierFrom(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifierFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPFPXBankBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank":{"title":"STPFPXBank","navigatorTitle":[{"kind":"identifier","text":"STPFPXBank"}],"abstract":[{"type":"text","text":"Convenience methods for using FPX bank brands."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBank"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbank","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBankBrand"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","title":"STPFPXBankBrand","url":"\/documentation\/stripepayments\/stpfpxbankbrand","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"identifierFrom:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"identifierFrom:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"identifierFrom:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPFPXBankBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand"},{"kind":"text","text":") "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"brand","content":[{"inlineContent":[{"type":"text","text":"The brand you want to convert to a string"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A string representing the brand, suitable for using with the Stripe API."}]}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"identifierFrom:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1identifierFrom(_:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"identifierFrom:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1identifierFrom(_:)\/fragments","op":"replace"},{"value":"STPFPXBank","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/title","op":"replace"},{"value":[{"text":"STPFPXBank","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPFPXBank"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/navigatorTitle","op":"replace"},{"value":"STPFPXBankBrand","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","op":"replace"},{"value":[{"text":"STPFPXBankBrand","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","op":"replace"}]}]}