{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/init"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/init","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank"]]},"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPFPXBank(im)init","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbank\/init","title":"init","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBank"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank","title":"STPFPXBank","abstract":[{"type":"text","text":"Convenience methods for using FPX bank brands."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFPXBank"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpfpxbank"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPFPXBank","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPFPXBank"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPFPXBank"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/navigatorTitle","op":"replace"}]}]}