{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPFPXBank(cm)stringFrom:","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFrom:"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","modules":[{"name":"StripePayments"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stringFrom","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"stringFrom(_:)"},"abstract":[{"type":"text","text":"Returns a string representation for the provided bank brand;"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"code":"STPFPXBank.stringFrom(brand:.uob) == \"UOB Bank\"","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/stringFrom(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringFrom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The brand you want to convert to a string"}],"type":"paragraph"}],"name":"brand"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"A string representing the brand, suitable for displaying to a user.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/stringfrom(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfpxbank\/stringfrom(_:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/stringFrom(_:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Returns a string representation for the provided bank brand;"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"code":"STPFPXBank.stringFrom(brand:.uob) == \"UOB Bank\"","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFrom:"}],"url":"\/documentation\/stripepayments\/stpfpxbank\/stringfrom(_:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/stringFrom(_:)","title":"stringFrom(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stringFrom"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","kind":"typeIdentifier","text":"STPFPXBankBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank":{"navigatorTitle":[{"text":"STPFPXBank","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpfpxbank","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBank"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank","abstract":[{"type":"text","text":"Convenience methods for using FPX bank brands."}],"title":"STPFPXBank","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"role":"symbol","navigatorTitle":[{"text":"STPFPXBankBrand","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand","title":"STPFPXBankBrand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"stringFrom:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"stringFrom:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"stringFrom:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand"},{"kind":"text","text":") "},{"kind":"internalParam","text":"brand"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The brand you want to convert to a string","type":"text"}]}],"name":"brand"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"A string representing the brand, suitable for displaying to a user."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"stringFrom:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1stringFrom(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stringFrom:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1stringFrom(_:)\/fragments"},{"value":"STPFPXBank","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/title"},{"value":[{"kind":"identifier","text":"STPFPXBank"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/fragments"},{"value":[{"kind":"identifier","text":"STPFPXBank"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/navigatorTitle"},{"value":"STPFPXBankBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}