{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"StripePayments"}],"title":"Equatable Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/!=(_:_:)"],"anchor":"Operators"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/equatable-implementations"]}],"kind":"article","sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/!=(_:_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/!=(_:_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","type":"topic","title":"!=(_:_:)","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/!=(_:_:)","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","title":"STPPaymentHandlerErrorCode","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Error codes generated by "},{"code":"STPPaymentHandler","type":"codeVoice"}],"navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","value":"STPPaymentHandlerErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]}]}]}