{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/intentStatusErrorCode","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerIntentStatusErrorCode","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intentStatusErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode.intentStatusErrorCode","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"STPPaymentHandlerIntentStatusErrorCode","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPPaymentHandlerIntentStatusErrorCode) ","kind":"text"},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intentStatusErrorCode","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"abstract":[{"text":"The PaymentIntent or SetupIntent status cannot be resolved by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":".","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/intentstatuserrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/intentstatuserrorcode"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"title":"STPPaymentHandlerErrorCode","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Error codes generated by "},{"type":"codeVoice","code":"STPPaymentHandler"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/intentStatusErrorCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/intentStatusErrorCode","type":"topic","kind":"symbol","abstract":[{"text":"The PaymentIntent or SetupIntent status cannot be resolved by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"intentStatusErrorCode"}],"title":"STPPaymentHandlerErrorCode.intentStatusErrorCode","role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/intentstatuserrorcode","navigatorTitle":[{"text":"STPPaymentHandlerIntentStatusErrorCode","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"STPPaymentHandlerIntentStatusErrorCode","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPPaymentHandlerIntentStatusErrorCode"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"identifier","text":"STPPaymentHandlerIntentStatusErrorCode"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentHandlerErrorCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]},{"value":"STPPaymentHandlerIntentStatusErrorCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1intentStatusErrorCode\/title"},{"value":[{"text":"STPPaymentHandlerIntentStatusErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1intentStatusErrorCode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}