{"kind":"symbol","metadata":{"title":"STPPaymentHandlerErrorCode.invalidClientSecret","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPaymentHandlerInvalidClientSecret","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerInvalidClientSecret","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidClientSecret","kind":"identifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"The provided PaymentIntent of SetupIntent client secret does not match the expected pattern for client secrets."},{"type":"text","text":" "},{"type":"text","text":"Make sure that your server is returning the correct value and that is being passed to "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":"."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/invalidClientSecret"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPPaymentHandlerInvalidClientSecret) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidClientSecret"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/invalidclientsecret"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/invalidclientsecret"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"title":"STPPaymentHandlerErrorCode","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"abstract":[{"type":"text","text":"Error codes generated by "},{"code":"STPPaymentHandler","type":"codeVoice"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/invalidClientSecret":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidClientSecret","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The provided PaymentIntent of SetupIntent client secret does not match the expected pattern for client secrets."},{"type":"text","text":" "},{"type":"text","text":"Make sure that your server is returning the correct value and that is being passed to "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/invalidclientsecret","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/invalidClientSecret","navigatorTitle":[{"text":"STPPaymentHandlerInvalidClientSecret","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode.invalidClientSecret"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentHandlerInvalidClientSecret"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerInvalidClientSecret"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPaymentHandlerInvalidClientSecret"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","value":"STPPaymentHandlerErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1invalidClientSecret\/title","value":"STPPaymentHandlerInvalidClientSecret"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1invalidClientSecret\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerInvalidClientSecret"}]}]}]}