{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"The payment method requires a return URL and one was not provided. Your integration should provide one in your "},{"type":"codeVoice","code":"STPPaymentIntentConfirmParams"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"STPSetupIntentConfirmParams"},{"type":"text","text":" object if you call "},{"type":"codeVoice","code":"STPPaymentHandler.confirm..."},{"type":"text","text":" or when you call  "},{"type":"codeVoice","code":"STPPaymentHandler.handleNextAction"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPPaymentHandlerMissingReturnURL) ","kind":"text"},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"missingReturnURL","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"missingReturnURL","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerMissingReturnURL","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPaymentHandlerMissingReturnURL","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode.missingReturnURL"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/missingReturnURL"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/missingreturnurl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/missingreturnurl"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/missingReturnURL":{"navigatorTitle":[{"text":"STPPaymentHandlerMissingReturnURL","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/missingreturnurl","kind":"symbol","abstract":[{"text":"The payment method requires a return URL and one was not provided. Your integration should provide one in your ","type":"text"},{"code":"STPPaymentIntentConfirmParams","type":"codeVoice"},{"text":"\/","type":"text"},{"code":"STPSetupIntentConfirmParams","type":"codeVoice"},{"text":" object if you call ","type":"text"},{"code":"STPPaymentHandler.confirm...","type":"codeVoice"},{"text":" or when you call  ","type":"text"},{"code":"STPPaymentHandler.handleNextAction","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/missingReturnURL","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"missingReturnURL","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode.missingReturnURL"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"title":"STPPaymentHandlerErrorCode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","abstract":[{"type":"text","text":"Error codes generated by "},{"type":"codeVoice","code":"STPPaymentHandler"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentHandlerMissingReturnURL"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentHandlerMissingReturnURL","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentHandlerMissingReturnURL"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1missingReturnURL\/title","value":"STPPaymentHandlerMissingReturnURL"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerMissingReturnURL"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1missingReturnURL\/fragments"},{"op":"replace","value":"STPPaymentHandlerErrorCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title"},{"op":"replace","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}