{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"abstract":[{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" does not support concurrent actions."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/noConcurrentActionsErrorCode"},"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noConcurrentActionsErrorCode","kind":"identifier"}],"role":"symbol","title":"STPPaymentHandlerErrorCode.noConcurrentActionsErrorCode","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"STPPaymentHandlerNoConcurrentActionsErrorCode","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerNoConcurrentActionsErrorCode"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPPaymentHandlerNoConcurrentActionsErrorCode) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noConcurrentActionsErrorCode"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/noconcurrentactionserrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/noconcurrentactionserrorcode"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/noConcurrentActionsErrorCode":{"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/noconcurrentactionserrorcode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/noConcurrentActionsErrorCode","title":"STPPaymentHandlerErrorCode.noConcurrentActionsErrorCode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noConcurrentActionsErrorCode","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" does not support concurrent actions.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentHandlerNoConcurrentActionsErrorCode","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","title":"STPPaymentHandlerErrorCode","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"abstract":[{"text":"Error codes generated by ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentHandlerNoConcurrentActionsErrorCode","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerNoConcurrentActionsErrorCode"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentHandlerNoConcurrentActionsErrorCode"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentHandlerNoConcurrentActionsErrorCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1noConcurrentActionsErrorCode\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1noConcurrentActionsErrorCode\/fragments","op":"replace","value":[{"text":"STPPaymentHandlerNoConcurrentActionsErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","op":"replace","value":"STPPaymentHandlerErrorCode"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}