{"metadata":{"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPaymentHandlerNotAuthenticatedErrorCode","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerNotAuthenticatedErrorCode","symbolKind":"case","role":"symbol","roleHeading":"Case","title":"STPPaymentHandlerErrorCode.notAuthenticatedErrorCode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notAuthenticatedErrorCode","kind":"identifier"}]},"abstract":[{"type":"text","text":"The transaction did not authenticate (e.g. user entered the wrong code)."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPPaymentHandlerNotAuthenticatedErrorCode) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthenticatedErrorCode"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/notauthenticatederrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/notauthenticatederrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/notAuthenticatedErrorCode","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","title":"STPPaymentHandlerErrorCode","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"abstract":[{"text":"Error codes generated by ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/notAuthenticatedErrorCode":{"type":"topic","title":"STPPaymentHandlerErrorCode.notAuthenticatedErrorCode","abstract":[{"type":"text","text":"The transaction did not authenticate (e.g. user entered the wrong code)."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/notAuthenticatedErrorCode","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerNotAuthenticatedErrorCode"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthenticatedErrorCode"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/notauthenticatederrorcode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentHandlerNotAuthenticatedErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentHandlerNotAuthenticatedErrorCode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPaymentHandlerNotAuthenticatedErrorCode"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","value":"STPPaymentHandlerErrorCode"},{"value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments"},{"value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle"},{"value":"STPPaymentHandlerNotAuthenticatedErrorCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1notAuthenticatedErrorCode\/title"},{"value":[{"kind":"identifier","text":"STPPaymentHandlerNotAuthenticatedErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1notAuthenticatedErrorCode\/fragments"}]}]}