{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/paymenterrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/paymenterrorcode"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(STPPaymentHandlerPaymentErrorCode) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"paymentErrorCode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentHandlerPaymentErrorCode","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerPaymentErrorCode","title":"STPPaymentHandlerErrorCode.paymentErrorCode"},"abstract":[{"type":"text","text":"There was an error confirming the Intent."},{"type":"text","text":" "},{"type":"text","text":"Inspect the "},{"code":"paymentIntent.lastPaymentError","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"setupIntent.lastSetupError","type":"codeVoice"},{"text":" property.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/paymentErrorCode","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","title":"STPPaymentHandlerErrorCode","role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","abstract":[{"type":"text","text":"Error codes generated by "},{"code":"STPPaymentHandler","type":"codeVoice"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/paymentErrorCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/paymentErrorCode","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/paymenterrorcode","role":"symbol","abstract":[{"text":"There was an error confirming the Intent.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Inspect the "},{"code":"paymentIntent.lastPaymentError","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"setupIntent.lastSetupError","type":"codeVoice"},{"text":" property.","type":"text"}],"kind":"symbol","type":"topic","title":"STPPaymentHandlerErrorCode.paymentErrorCode","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerPaymentErrorCode"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentHandlerPaymentErrorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerPaymentErrorCode"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentHandlerPaymentErrorCode"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"STPPaymentHandlerErrorCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title"},{"value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments"},{"value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle"},{"op":"replace","value":"STPPaymentHandlerPaymentErrorCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1paymentErrorCode\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1paymentErrorCode\/fragments","op":"replace","value":[{"text":"STPPaymentHandlerPaymentErrorCode","kind":"identifier"}]}]}]}