{"sections":[],"metadata":{"navigatorTitle":[{"text":"STPPaymentHandlerRequiresPaymentMethodErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode.requiresPaymentMethodErrorCode","symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerRequiresPaymentMethodErrorCode","modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresPaymentMethodErrorCode","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresPaymentMethodErrorCode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requirespaymentmethoderrorcode"]},{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requirespaymentmethoderrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPPaymentHandlerRequiresPaymentMethodErrorCode) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresPaymentMethodErrorCode"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Attach a payment method to the PaymentIntent or SetupIntent before using "},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","abstract":[{"text":"Error codes generated by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"}],"navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"role":"symbol","title":"STPPaymentHandlerErrorCode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/requiresPaymentMethodErrorCode":{"title":"STPPaymentHandlerErrorCode.requiresPaymentMethodErrorCode","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresPaymentMethodErrorCode","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requirespaymentmethoderrorcode","abstract":[{"type":"text","text":"Attach a payment method to the PaymentIntent or SetupIntent before using "},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresPaymentMethodErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerRequiresPaymentMethodErrorCode"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentHandlerRequiresPaymentMethodErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerRequiresPaymentMethodErrorCode"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentHandlerRequiresPaymentMethodErrorCode"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"STPPaymentHandlerErrorCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace"},{"value":"STPPaymentHandlerRequiresPaymentMethodErrorCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiresPaymentMethodErrorCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiresPaymentMethodErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerRequiresPaymentMethodErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}