{"abstract":[{"type":"text","text":"Indicates that the action requires an authentication app, but either the app is not installed or the request to switch to the app was denied."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredAppNotAvailable"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerRequiredAppNotAvailableErrorCode","title":"STPPaymentHandlerErrorCode.requiredAppNotAvailable","symbolKind":"case","navigatorTitle":[{"text":"STPPaymentHandlerRequiredAppNotAvailableErrorCode","kind":"identifier"}],"roleHeading":"Case"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(STPPaymentHandlerRequiredAppNotAvailableErrorCode) "},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiredAppNotAvailable"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requiredappnotavailable"]},{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requiredappnotavailable"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiredAppNotAvailable","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/requiredAppNotAvailable":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerRequiredAppNotAvailableErrorCode"}],"abstract":[{"type":"text","text":"Indicates that the action requires an authentication app, but either the app is not installed or the request to switch to the app was denied."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredAppNotAvailable"}],"title":"STPPaymentHandlerErrorCode.requiredAppNotAvailable","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiredAppNotAvailable","role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requiredappnotavailable","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode","type":"topic","navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","abstract":[{"type":"text","text":"Error codes generated by "},{"code":"STPPaymentHandler","type":"codeVoice"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentHandlerRequiredAppNotAvailableErrorCode","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerRequiredAppNotAvailableErrorCode"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPPaymentHandlerRequiredAppNotAvailableErrorCode","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiredAppNotAvailable\/title","op":"replace","value":"STPPaymentHandlerRequiredAppNotAvailableErrorCode"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerRequiredAppNotAvailableErrorCode"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiredAppNotAvailable\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","op":"replace","value":"STPPaymentHandlerErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]}]}]}