{"metadata":{"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerRequiresAuthenticationContextErrorCode","modules":[{"name":"StripePayments"}],"role":"symbol","title":"STPPaymentHandlerErrorCode.requiresAuthenticationContextErrorCode","navigatorTitle":[{"text":"STPPaymentHandlerRequiresAuthenticationContextErrorCode","kind":"identifier"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresAuthenticationContextErrorCode"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresAuthenticationContextErrorCode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPPaymentHandlerRequiresAuthenticationContextErrorCode) ","kind":"text"},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requiresAuthenticationContextErrorCode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Payment requires a valid ","type":"text"},{"type":"codeVoice","code":"STPAuthenticationContext"},{"type":"text","text":".  Make sure your presentingViewController isn’t already presenting."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requiresauthenticationcontexterrorcode"]},{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requiresauthenticationcontexterrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/requiresAuthenticationContextErrorCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresAuthenticationContextErrorCode","role":"symbol","abstract":[{"text":"Payment requires a valid ","type":"text"},{"type":"codeVoice","code":"STPAuthenticationContext"},{"type":"text","text":".  Make sure your presentingViewController isn’t already presenting."}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requiresauthenticationcontexterrorcode","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresAuthenticationContextErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerRequiresAuthenticationContextErrorCode"}],"kind":"symbol","title":"STPPaymentHandlerErrorCode.requiresAuthenticationContextErrorCode"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","kind":"symbol","abstract":[{"type":"text","text":"Error codes generated by "},{"code":"STPPaymentHandler","type":"codeVoice"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"STPPaymentHandlerRequiresAuthenticationContextErrorCode","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentHandlerRequiresAuthenticationContextErrorCode","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentHandlerRequiresAuthenticationContextErrorCode"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"STPPaymentHandlerRequiresAuthenticationContextErrorCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiresAuthenticationContextErrorCode\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiresAuthenticationContextErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerRequiresAuthenticationContextErrorCode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","value":"STPPaymentHandlerErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}]}]}]}