{"abstract":[{"type":"text","text":"There was an error in the Stripe3DS2 SDK."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPPaymentHandlerStripe3DS2ErrorCode) ","kind":"text"},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripe3DS2ErrorCode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripe3DS2ErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentHandlerStripe3DS2ErrorCode","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerStripe3DS2ErrorCode","modules":[{"name":"StripePayments"}],"title":"STPPaymentHandlerErrorCode.stripe3DS2ErrorCode"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/stripe3DS2ErrorCode","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/stripe3ds2errorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/stripe3ds2errorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/stripe3DS2ErrorCode":{"abstract":[{"type":"text","text":"There was an error in the Stripe3DS2 SDK."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerStripe3DS2ErrorCode"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/stripe3ds2errorcode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripe3DS2ErrorCode"}],"kind":"symbol","type":"topic","title":"STPPaymentHandlerErrorCode.stripe3DS2ErrorCode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/stripe3DS2ErrorCode"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode","abstract":[{"text":"Error codes generated by ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentHandlerStripe3DS2ErrorCode"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPPaymentHandlerStripe3DS2ErrorCode","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentHandlerStripe3DS2ErrorCode"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1stripe3DS2ErrorCode\/title","op":"replace","value":"STPPaymentHandlerStripe3DS2ErrorCode"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1stripe3DS2ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerStripe3DS2ErrorCode"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","op":"replace","value":"STPPaymentHandlerErrorCode"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","op":"replace","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]}]}]}