{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/timedouterrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/timedouterrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The action timed out.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/timedOutErrorCode"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(STPPaymentHandlerTimedOutErrorCode) ","kind":"text"},{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timedOutErrorCode"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"title":"STPPaymentHandlerErrorCode.timedOutErrorCode","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timedOutErrorCode"}],"navigatorTitle":[{"text":"STPPaymentHandlerTimedOutErrorCode","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerTimedOutErrorCode","modules":[{"name":"StripePayments"}],"roleHeading":"Case"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","kind":"symbol","abstract":[{"type":"text","text":"Error codes generated by "},{"code":"STPPaymentHandler","type":"codeVoice"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/timedOutErrorCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/timedOutErrorCode","role":"symbol","abstract":[{"type":"text","text":"The action timed out."}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/timedouterrorcode","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"timedOutErrorCode"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerTimedOutErrorCode"}],"kind":"symbol","title":"STPPaymentHandlerErrorCode.timedOutErrorCode"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentHandlerTimedOutErrorCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"STPPaymentHandlerTimedOutErrorCode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPPaymentHandlerTimedOutErrorCode"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","op":"replace","value":"STPPaymentHandlerErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle"},{"value":"STPPaymentHandlerTimedOutErrorCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1timedOutErrorCode\/title"},{"value":[{"kind":"identifier","text":"STPPaymentHandlerTimedOutErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1timedOutErrorCode\/fragments"}]}]}