{"abstract":[{"text":"Indicates that the action requires an authentication method not recognized or supported by the SDK.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/unsupportedAuthenticationErrorCode","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/unsupportedauthenticationerrorcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode\/unsupportedauthenticationerrorcode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"STPPaymentHandlerUnsupportedAuthenticationErrorCode","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode@STPPaymentHandlerUnsupportedAuthenticationErrorCode","title":"STPPaymentHandlerErrorCode.unsupportedAuthenticationErrorCode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedAuthenticationErrorCode","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(STPPaymentHandlerUnsupportedAuthenticationErrorCode) "},{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsupportedAuthenticationErrorCode"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/unsupportedAuthenticationErrorCode":{"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/unsupportedauthenticationerrorcode","abstract":[{"type":"text","text":"Indicates that the action requires an authentication method not recognized or supported by the SDK."}],"title":"STPPaymentHandlerErrorCode.unsupportedAuthenticationErrorCode","navigatorTitle":[{"text":"STPPaymentHandlerUnsupportedAuthenticationErrorCode","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedAuthenticationErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/unsupportedAuthenticationErrorCode","role":"symbol","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"abstract":[{"type":"text","text":"Error codes generated by "},{"type":"codeVoice","code":"STPPaymentHandler"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","kind":"symbol","title":"STPPaymentHandlerErrorCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentHandlerUnsupportedAuthenticationErrorCode","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerUnsupportedAuthenticationErrorCode"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"STPPaymentHandlerUnsupportedAuthenticationErrorCode","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentHandlerUnsupportedAuthenticationErrorCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1unsupportedAuthenticationErrorCode\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1unsupportedAuthenticationErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerUnsupportedAuthenticationErrorCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","value":"STPPaymentHandlerErrorCode","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"op":"replace"}]}]}