{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession"]]},"sections":[],"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpradarsession\/allresponsefields"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpradarsession\/allresponsefields"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession\/allResponseFields"},"metadata":{"title":"allResponseFields","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPRadarSession(py)allResponseFields","modules":[{"name":"StripePayments"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarSession":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRadarSession","kind":"identifier"}],"kind":"symbol","title":"STPRadarSession","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","abstract":[{"type":"text","text":"A "},{"identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"STPRadarSession","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpradarsession"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarSession/allResponseFields":{"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession\/allResponseFields","kind":"symbol","url":"\/documentation\/stripepayments\/stpradarsession\/allresponsefields","title":"allResponseFields"},"https://stripe.com/docs/radar/radar-session":{"type":"link","identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session","titleInlineContent":[{"type":"text","text":"Radar Session"}],"url":"https:\/\/stripe.com\/docs\/radar\/radar-session","title":"Radar Session"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"allResponseFields","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary"},{"text":" * ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/title","value":"STPRadarSession","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPRadarSession"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/navigatorTitle","value":[{"kind":"identifier","text":"STPRadarSession"}],"op":"replace"},{"value":"allResponseFields","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession~1allResponseFields\/title"},{"value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession~1allResponseFields\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}