{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?) -> ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","kind":"typeIdentifier","text":"STPRadarSession","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"response","content":[{"inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"text":" is nil).","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpradarsession\/decodedobject(fromapiresponse:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpradarsession\/decodedobject(fromapiresponse:)"]}],"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPRadarSession(cm)decodedObjectFromAPIResponse:","title":"decodedObject(fromAPIResponse:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"text":"STPRadarSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarSession/decodedObject(fromAPIResponse:)":{"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"url":"\/documentation\/stripepayments\/stpradarsession\/decodedobject(fromapiresponse:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession\/decodedObject(fromAPIResponse:)","type":"topic","title":"decodedObject(fromAPIResponse:)","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"text":"fromAPIResponse","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> "},{"text":"STPRadarSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarSession":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRadarSession","kind":"identifier"}],"navigatorTitle":[{"text":"STPRadarSession","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpradarsession","abstract":[{"text":"A ","type":"text"},{"isActive":true,"identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session","type":"reference"},{"text":".","type":"text"}],"title":"STPRadarSession","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","role":"symbol"},"https://stripe.com/docs/radar/radar-session":{"titleInlineContent":[{"text":"Radar Session","type":"text"}],"url":"https:\/\/stripe.com\/docs\/radar\/radar-session","identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session","type":"link","title":"Radar Session"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"decodedObjectFromAPIResponse:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession","kind":"typeIdentifier","text":"STPRadarSession"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession~1decodedObject(fromAPIResponse:)\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession~1decodedObject(fromAPIResponse:)\/fragments"},{"op":"replace","value":"STPRadarSession","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPRadarSession"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/fragments"},{"op":"replace","value":[{"text":"STPRadarSession","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}
