{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout\/allResponseFields","interfaceLanguage":"swift"},"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/allresponsefields"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/allresponsefields"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"] { get }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"role":"symbol","title":"allResponseFields","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout(py)allResponseFields"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout/allResponseFields":{"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout\/allResponseFields","url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/allresponsefields","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"role":"symbol","title":"allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout","abstract":[{"text":"A Visa Checkout Card Wallet","type":"text"}],"title":"STPPaymentMethodCardWalletVisaCheckout","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"navigatorTitle":[{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"allResponseFields","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"allResponseFields","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"allResponseFields","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout~1allResponseFields\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}]},{"op":"replace","value":"STPPaymentMethodCardWalletVisaCheckout","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/fragments","value":[{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/navigatorTitle"}]}]}