{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout\/billingAddress","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/billingaddress"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/billingaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"billingAddress","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"billingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","text":"STPPaymentMethodAddress","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"billingAddress","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout(py)billingAddress","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}]},"abstract":[{"text":"Owner’s verified billing address. Values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","text":"STPPaymentMethodAddress"},{"text":"? { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout"]]},"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout","kind":"symbol","type":"topic","abstract":[{"text":"A Visa Checkout Card Wallet","type":"text"}],"title":"STPPaymentMethodCardWalletVisaCheckout","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"navigatorTitle":[{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout/billingAddress":{"kind":"symbol","abstract":[{"text":"Owner’s verified billing address. Values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement.","type":"text"}],"navigatorTitle":[{"text":"billingAddress","kind":"identifier"}],"title":"billingAddress","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout\/billingAddress","url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/billingaddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingAddress"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","text":"STPPaymentMethodAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAddress":{"abstract":[{"type":"text","text":"The billing address, a property on "},{"code":"STPPaymentMethodBillingDetails","type":"codeVoice"}],"url":"\/documentation\/stripepayments\/stppaymentmethodaddress","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAddress","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodAddress","kind":"identifier"}],"title":"STPPaymentMethodAddress"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"billingAddress","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"billingAddress"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","text":"STPPaymentMethodAddress"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"billingAddress"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"STPPaymentMethodCardWalletVisaCheckout","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout~1billingAddress\/title","value":"billingAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout~1billingAddress\/fragments","value":[{"kind":"identifier","text":"billingAddress"}],"op":"replace"},{"value":"STPPaymentMethodAddress","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}