{"metadata":{"title":"decodedObject(fromAPIResponse:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout(cm)decodedObjectFromAPIResponse:","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"roleHeading":"Type Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"response","content":[{"inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The object represented by the JSON dictionary, or nil if the object"},{"type":"text","text":" "},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout":{"abstract":[{"text":"A Visa Checkout Card Wallet","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"title":"STPPaymentMethodCardWalletVisaCheckout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout/decodedObject(fromAPIResponse:)":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/decodedobject(fromapiresponse:)","title":"decodedObject(fromAPIResponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout\/decodedObject(fromAPIResponse:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"response","content":[{"inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"text":" ","type":"text"},{"text":"could not be decoded (i.e. if one of its ","type":"text"},{"code":"requiredFields","type":"codeVoice"},{"text":" is nil).","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"STPPaymentMethodCardWalletVisaCheckout","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/title"},{"value":[{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/fragments"},{"value":[{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/navigatorTitle"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout~1decodedObject(fromAPIResponse:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout~1decodedObject(fromAPIResponse:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}