{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout\/shippingAddress"},"metadata":{"navigatorTitle":[{"text":"shippingAddress","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property","title":"shippingAddress","roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout(py)shippingAddress","modules":[{"name":"StripePayments"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/shippingaddress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/shippingaddress"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","kind":"typeIdentifier","text":"STPPaymentMethodAddress"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Owner’s verified shipping address. Values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout":{"type":"topic","abstract":[{"text":"A Visa Checkout Card Wallet","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodCardWalletVisaCheckout","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout","title":"STPPaymentMethodCardWalletVisaCheckout"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAddress":{"abstract":[{"type":"text","text":"The billing address, a property on "},{"code":"STPPaymentMethodBillingDetails","type":"codeVoice"}],"kind":"symbol","type":"topic","title":"STPPaymentMethodAddress","url":"\/documentation\/stripepayments\/stppaymentmethodaddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAddress","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodAddress","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletVisaCheckout/shippingAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletVisaCheckout\/shippingAddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","kind":"typeIdentifier","text":"STPPaymentMethodAddress"},{"kind":"text","text":"?"}],"title":"shippingAddress","url":"\/documentation\/stripepayments\/stppaymentmethodcardwalletvisacheckout\/shippingaddress","abstract":[{"text":"Owner’s verified shipping address. Values are verified or provided by the payment method directly (and if supported) at the time of authorization or settlement.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"shippingAddress"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"shippingAddress","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"shippingAddress"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPPaymentMethodAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shippingAddress"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodCardWalletVisaCheckout","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletVisaCheckout"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/navigatorTitle"},{"op":"replace","value":"shippingAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout~1shippingAddress\/title"},{"op":"replace","value":[{"kind":"identifier","text":"shippingAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletVisaCheckout~1shippingAddress\/fragments"}]}]}