{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodbillingdetails\/address"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodbillingdetails\/address"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"address"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails(py)address","title":"address","modules":[{"name":"StripePayments"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"address"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","kind":"typeIdentifier","text":"STPPaymentMethodAddress"},{"text":"?","kind":"text"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails\/address"},"abstract":[{"type":"text","text":"Billing address."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails/address":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"address"}],"abstract":[{"type":"text","text":"Billing address."}],"title":"address","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails\/address","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails\/address","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","kind":"typeIdentifier","text":"STPPaymentMethodAddress"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","abstract":[{"type":"text","text":"Billing information associated with a "},{"type":"codeVoice","code":"STPPaymentMethod"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"title":"STPPaymentMethodBillingDetails","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAddress":{"title":"STPPaymentMethodAddress","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodaddress","kind":"symbol","abstract":[{"type":"text","text":"The billing address, a property on "},{"type":"codeVoice","code":"STPPaymentMethodBillingDetails"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAddress","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodAddress","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"address","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"address","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","kind":"typeIdentifier","text":"STPPaymentMethodAddress"},{"text":" * ","kind":"text"},{"text":"address","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails~1address\/title","value":"address"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails~1address\/fragments","value":[{"kind":"identifier","text":"address"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/title","value":"STPPaymentMethodAddress"},{"value":[{"text":"STPPaymentMethodAddress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodAddress"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}