{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodbillingdetails\/phone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodbillingdetails\/phone"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Billing phone number (including extension)."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails\/phone","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"]]},"metadata":{"title":"phone","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails(py)phone","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"phone"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails/phone":{"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Billing phone number (including extension)."}],"navigatorTitle":[{"text":"phone","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails\/phone","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails\/phone","title":"phone"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"abstract":[{"text":"Billing information associated with a ","type":"text"},{"code":"STPPaymentMethod","type":"codeVoice"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}],"title":"STPPaymentMethodBillingDetails","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"phone","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"phone","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"phone"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"phone","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails~1phone\/title","op":"replace"},{"value":[{"text":"phone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails~1phone\/fragments","op":"replace"},{"value":"STPPaymentMethodBillingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","op":"replace"}]}]}