{"kind":"symbol","variants":[{"paths":["\/documentation\/stripepaymentsheet"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsheet"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[[]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElement","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElementViewModel","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/StripeCustomerAdapter"],"anchor":"Classes"},{"generated":true,"title":"Protocols","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewControllerDelegate","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerAdapter","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElementDelegate"],"anchor":"Protocols"},{"generated":true,"title":"Structures","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressElement","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerEphemeralKey","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerSessionClientSecret","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElementView"],"anchor":"Structures"},{"generated":true,"title":"Type Aliases","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElementResult"],"anchor":"Type-Aliases"},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerPaymentOption","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerSheetError","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheetError","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheetResult"],"anchor":"Enumerations"},{"generated":true,"title":"Extended Modules","identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/Swift","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/SwiftUICore"],"anchor":"Extended-Modules"}],"metadata":{"roleHeading":"Framework","modules":[{"name":"StripePaymentSheet"}],"externalID":"StripePaymentSheet","role":"collection","title":"StripePaymentSheet","symbolKind":"module"},"abstract":[{"type":"text","text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"content","content":[{"text":"Table of contents","type":"heading","level":2,"anchor":"Table-of-contents"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"#Features"}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"#Requirements"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"#Getting-started"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"#Integration","type":"reference"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"#Example","isActive":true}],"type":"paragraph"}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"#Manual-linking","type":"reference"}],"type":"paragraph"}]}]},{"text":"Requirements","anchor":"Requirements","level":2,"type":"heading"},{"inlineContent":[{"text":"The StripePaymentSheet module is compatible with apps targeting iOS 13.0 or above.","type":"text"}],"type":"paragraph"},{"text":"Getting started","anchor":"Getting-started","level":2,"type":"heading"},{"text":"Integration","anchor":"Integration","level":3,"type":"heading"},{"inlineContent":[{"type":"text","text":"Get started with our "},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios&ui=payment-sheet"},{"type":"text","text":" and "},{"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.17.0\/StripePaymentSheet\/\/Example"},{"type":"text","text":", or "},{"isActive":true,"type":"reference","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-paymentsheet\/index.html"},{"type":"text","text":" for fine-grained documentation of all the classes and methods in the SDK."}],"type":"paragraph"},{"text":"Example","anchor":"Example","level":3,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.17.0\/StripePaymentSheet\/Example\/PaymentSheet%20Example","type":"reference","isActive":true}]},{"items":[{"content":[{"inlineContent":[{"text":"This example demonstrates how to build a payment flow using ","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios","isActive":true,"type":"reference"},{"type":"text","text":", an embeddable native UI component that lets you accept "},{"identifier":"https:\/\/stripe.com\/docs\/payments\/payment-methods\/integration-options#payment-method-product-support","isActive":true,"type":"reference"},{"type":"text","text":" with a single integration."}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"type":"unorderedList"},{"anchor":"Manual-linking","type":"heading","level":2,"text":"Manual linking"},{"type":"paragraph","inlineContent":[{"text":"If you link this library manually, use a version from our ","type":"text"},{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","isActive":true,"type":"reference"},{"text":" page and make sure to embed ","type":"text"},{"text":"all","type":"text"},{"text":" of the following frameworks:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripeCore.xcframework"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripeUICore.xcframework"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"Stripe3DS2.xcframework","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"StripePayments.xcframework","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripePaymentsUI.xcframework"}]}]},{"content":[{"inlineContent":[{"code":"StripeApplePay.xcframework","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"StripePaymentSheet.xcframework","type":"codeVoice"}],"type":"paragraph"}]}]}]}],"references":{"https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet":{"title":"📚 integration guides","identifier":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios&ui=payment-sheet","titleInlineContent":[{"type":"text","text":"📚 integration guides"}],"type":"link","url":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios&ui=payment-sheet"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/CustomerEphemeralKey":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerEphemeralKey","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomerEphemeralKey"}],"type":"topic","abstract":[{"type":"text","text":"An ephemeral key for the Stripe Customer"}],"url":"\/documentation\/stripepaymentsheet\/customerephemeralkey","title":"CustomerEphemeralKey","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomerEphemeralKey"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressElement":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressElement","kind":"symbol","role":"symbol","url":"\/documentation\/stripepaymentsheet\/addresselement","navigatorTitle":[{"kind":"identifier","text":"AddressElement"}],"title":"AddressElement","abstract":[{"text":"A SwiftUI view that presents an address collection interface with full localization and autocomplete.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AddressElement"}],"type":"topic"},"https://github.com/stripe/stripe-ios/tree/25.17.0/StripePaymentSheet//Example":{"url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.17.0\/StripePaymentSheet\/\/Example","type":"link","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.17.0\/StripePaymentSheet\/\/Example","title":"example projects","titleInlineContent":[{"type":"text","text":"example projects"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/StripeCustomerAdapter":{"role":"symbol","url":"\/documentation\/stripepaymentsheet\/stripecustomeradapter","type":"topic","title":"StripeCustomerAdapter","navigatorTitle":[{"text":"StripeCustomerAdapter","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StripeCustomerAdapter","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"StripeCustomerAdapter","type":"codeVoice"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"text":" ","type":"text"},{"text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific","type":"text"},{"text":" ","type":"text"},{"text":"customer object. If your current user logs out of your app and a new user logs in,","type":"text"},{"text":" ","type":"text"},{"text":"be sure to create a new instance of ","type":"text"},{"code":"StripeCustomerAdapter","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/StripeCustomerAdapter","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/CustomerSessionClientSecret":{"type":"topic","url":"\/documentation\/stripepaymentsheet\/customersessionclientsecret","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomerSessionClientSecret"}],"navigatorTitle":[{"kind":"identifier","text":"CustomerSessionClientSecret"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerSessionClientSecret","role":"symbol","kind":"symbol","title":"CustomerSessionClientSecret"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/EmbeddedPaymentElementView":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElementView","kind":"symbol","role":"symbol","url":"\/documentation\/stripepaymentsheet\/embeddedpaymentelementview","navigatorTitle":[{"text":"EmbeddedPaymentElementView","kind":"identifier"}],"title":"EmbeddedPaymentElementView","abstract":[{"type":"text","text":"A SwiftUI view that displays payment methods. It can present a sheet to collect more details or display saved payment methods."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedPaymentElementView","kind":"identifier"}],"type":"topic"},"https://stripe.com/docs/payments/payment-methods/integration-options#payment-method-product-support":{"title":"10+ payment methods","type":"link","titleInlineContent":[{"type":"text","text":"10+ payment methods"}],"identifier":"https:\/\/stripe.com\/docs\/payments\/payment-methods\/integration-options#payment-method-product-support","url":"https:\/\/stripe.com\/docs\/payments\/payment-methods\/integration-options#payment-method-product-support"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/PaymentSheetError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSheetError"}],"abstract":[{"type":"text","text":"Errors specific to PaymentSheet itself"}],"url":"\/documentation\/stripepaymentsheet\/paymentsheeterror","navigatorTitle":[{"kind":"identifier","text":"PaymentSheetError"}],"kind":"symbol","role":"symbol","title":"PaymentSheetError","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheetError"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/CustomerSheet":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerSheet","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomerSheet","kind":"identifier"}],"url":"\/documentation\/stripepaymentsheet\/customersheet","abstract":[],"type":"topic","title":"CustomerSheet","role":"symbol","navigatorTitle":[{"text":"CustomerSheet","kind":"identifier"}]},"https://github.com/stripe/stripe-ios/tree/25.17.0/StripePaymentSheet/Example/PaymentSheet%20Example":{"url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.17.0\/StripePaymentSheet\/Example\/PaymentSheet%20Example","titleInlineContent":[{"text":"Prebuilt UI","type":"text"}],"type":"link","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.17.0\/StripePaymentSheet\/Example\/PaymentSheet%20Example","title":"Prebuilt UI"},"#Features":{"identifier":"#Features","type":"link","title":"Features","url":"#Features","titleInlineContent":[{"type":"text","text":"Features"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressViewControllerDelegate"}],"abstract":[{"type":"text","text":"A delegate for "},{"type":"codeVoice","code":"AddressViewController"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"AddressViewControllerDelegate"}],"kind":"symbol","title":"AddressViewControllerDelegate","url":"\/documentation\/stripepaymentsheet\/addressviewcontrollerdelegate","type":"topic"},"#Getting-started":{"title":"Getting started","type":"link","titleInlineContent":[{"type":"text","text":"Getting started"}],"identifier":"#Getting-started","url":"#Getting-started"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"abstract":[{"type":"text","text":"A view controller that collects a name and an address, with full localization and autocomplete."}],"title":"AddressViewController","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressViewController"}],"navigatorTitle":[{"kind":"identifier","text":"AddressViewController"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsheet","title":"StripePaymentSheet","abstract":[{"text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/Swift":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/Swift","type":"topic","abstract":[],"url":"\/documentation\/stripepaymentsheet\/swift","title":"Swift","role":"collection"},"#Requirements":{"url":"#Requirements","titleInlineContent":[{"text":"Requirements","type":"text"}],"type":"link","identifier":"#Requirements","title":"Requirements"},"https://stripe.dev/stripe-ios/stripe-paymentsheet/index.html":{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-paymentsheet\/index.html","type":"link","title":"📘 browse the SDK reference","url":"https:\/\/stripe.dev\/stripe-ios\/stripe-paymentsheet\/index.html","titleInlineContent":[{"type":"text","text":"📘 browse the SDK reference"}]},"#Example":{"title":"Example","type":"link","titleInlineContent":[{"type":"text","text":"Example"}],"identifier":"#Example","url":"#Example"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/STPElementsSession":{"url":"\/documentation\/stripepaymentsheet\/stpelementssession","title":"STPElementsSession","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/STPElementsSession","type":"topic","fragments":[{"kind":"identifier","text":"STPElementsSession"}],"kind":"symbol","abstract":[{"type":"text","text":"The response returned by v1\/elements\/sessions"}],"role":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/CustomerPaymentOption":{"url":"\/documentation\/stripepaymentsheet\/customerpaymentoption","title":"CustomerPaymentOption","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerPaymentOption","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomerPaymentOption"}],"navigatorTitle":[{"kind":"identifier","text":"CustomerPaymentOption"}],"abstract":[{"type":"text","text":"A representation of a Payment Method option, used for persisting the user’s default payment method."}],"type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/EmbeddedPaymentElement":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElement","title":"EmbeddedPaymentElement","abstract":[{"text":"An object that manages a view that displays payment methods and completes a checkout.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedPaymentElement","kind":"identifier"}],"url":"\/documentation\/stripepaymentsheet\/embeddedpaymentelement","kind":"symbol","type":"topic","navigatorTitle":[{"text":"EmbeddedPaymentElement","kind":"identifier"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/PaymentSheetResult":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSheetResult"}],"abstract":[{"type":"text","text":"The result of an attempt to confirm a PaymentIntent or SetupIntent"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheetResult","navigatorTitle":[{"kind":"identifier","text":"PaymentSheetResult"}],"kind":"symbol","title":"PaymentSheetResult","url":"\/documentation\/stripepaymentsheet\/paymentsheetresult","type":"topic"},"#Integration":{"url":"#Integration","type":"link","identifier":"#Integration","title":"Integration","titleInlineContent":[{"type":"text","text":"Integration"}]},"https://github.com/stripe/stripe-ios/releases":{"title":"releases","type":"link","titleInlineContent":[{"type":"text","text":"releases"}],"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","url":"https:\/\/github.com\/stripe\/stripe-ios\/releases"},"https://stripe.com/docs/payments/accept-a-payment?platform=ios":{"type":"link","title":"PaymentSheet","url":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios","titleInlineContent":[{"code":"PaymentSheet","type":"codeVoice"}],"identifier":"https:\/\/stripe.com\/docs\/payments\/accept-a-payment?platform=ios"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/EmbeddedPaymentElementViewModel":{"abstract":[{"type":"text","text":"A view model that manages an "},{"type":"codeVoice","code":"EmbeddedPaymentElement"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElementViewModel","url":"\/documentation\/stripepaymentsheet\/embeddedpaymentelementviewmodel","title":"EmbeddedPaymentElementViewModel","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbeddedPaymentElementViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"EmbeddedPaymentElementViewModel"}],"role":"symbol"},"#Manual-linking":{"type":"link","title":"Manual linking","url":"#Manual-linking","titleInlineContent":[{"type":"text","text":"Manual linking"}],"identifier":"#Manual-linking"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/StripePaymentSheetVersionNumber":{"url":"\/documentation\/stripepaymentsheet\/stripepaymentsheetversionnumber","title":"StripePaymentSheetVersionNumber","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/StripePaymentSheetVersionNumber","type":"topic","fragments":[{"kind":"identifier","text":"StripePaymentSheetVersionNumber"}],"kind":"symbol","abstract":[{"type":"text","text":"Project version number for StripePaymentSheet."}],"role":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/StripePaymentSheetVersionString":{"role":"symbol","url":"\/documentation\/stripepaymentsheet\/stripepaymentsheetversionstring","type":"topic","title":"StripePaymentSheetVersionString","fragments":[{"kind":"identifier","text":"StripePaymentSheetVersionString"}],"abstract":[{"type":"text","text":"Project version string for StripePaymentSheet."}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/StripePaymentSheetVersionString","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/InstantBankPaymentsController":{"url":"\/documentation\/stripepaymentsheet\/instantbankpaymentscontroller","title":"InstantBankPaymentsController","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/InstantBankPaymentsController","type":"topic","fragments":[{"kind":"identifier","text":"InstantBankPaymentsController"}],"kind":"symbol","abstract":[{"type":"text","text":"InstantBankPaymentsController"},{"type":"text","text":" encapsulates the Link payment flow, allowing you to let your customers pay with their Link account."},{"type":"text","text":" "},{"type":"text","text":"This feature is currently invite-only. To accept payments, "},{"type":"text","text":"use the Mobile Payment Element."}],"role":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/PaymentSheet":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSheet"}],"abstract":[{"type":"text","text":"A drop-in class that presents a sheet for a customer to complete their payment"}],"navigatorTitle":[{"kind":"identifier","text":"PaymentSheet"}],"url":"\/documentation\/stripepaymentsheet\/paymentsheet","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet","title":"PaymentSheet","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/SwiftUICore":{"role":"collection","title":"SwiftUICore","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/stripepaymentsheet\/swiftuicore","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/SwiftUICore"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/EmbeddedPaymentElementResult":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElementResult","title":"EmbeddedPaymentElementResult","abstract":[],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmbeddedPaymentElementResult","kind":"identifier"}],"url":"\/documentation\/stripepaymentsheet\/embeddedpaymentelementresult","kind":"symbol","type":"topic","navigatorTitle":[{"text":"EmbeddedPaymentElementResult","kind":"identifier"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/CustomerSheetError":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerSheetError","role":"symbol","navigatorTitle":[{"text":"CustomerSheetError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomerSheetError","kind":"identifier"}],"title":"CustomerSheetError","abstract":[],"url":"\/documentation\/stripepaymentsheet\/customersheeterror"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/STP_Internal_DownloadManager":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/STP_Internal_DownloadManager","title":"STP_Internal_DownloadManager","abstract":[{"type":"text","text":"For internal SDK use only."}],"role":"symbol","fragments":[{"kind":"identifier","text":"STP_Internal_DownloadManager"}],"url":"\/documentation\/stripepaymentsheet\/stp_internal_downloadmanager","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/CustomerAdapter":{"url":"\/documentation\/stripepaymentsheet\/customeradapter","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/CustomerAdapter","type":"topic","abstract":[{"text":"A “bridge” from wallet mode to your backend to fetch Customer-related information.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"type":"codeVoice","code":"StripeCustomerAdapter"},{"type":"text","text":", which implements "},{"type":"text","text":" "},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."},{"type":"text","text":" "},{"type":"text","text":"If you would prefer retrieving and updating your Stripe customer object via"},{"type":"text","text":" "},{"type":"text","text":"your own backend instead of using "},{"type":"codeVoice","code":"StripeCustomerAdapter"},{"type":"text","text":", you should make your"},{"type":"text","text":" "},{"type":"text","text":"application’s API client conform to this interface."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomerAdapter"}],"navigatorTitle":[{"kind":"identifier","text":"CustomerAdapter"}],"title":"CustomerAdapter","kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/EmbeddedPaymentElementDelegate":{"url":"\/documentation\/stripepaymentsheet\/embeddedpaymentelementdelegate","title":"EmbeddedPaymentElementDelegate","navigatorTitle":[{"text":"EmbeddedPaymentElementDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/EmbeddedPaymentElementDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"EmbeddedPaymentElementDelegate","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Classes","title":"Classes","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/InstantBankPaymentsController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/STPElementsSession","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/STP_Internal_DownloadManager"]},{"anchor":"Variables","title":"Variables","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/StripePaymentSheetVersionNumber","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/StripePaymentSheetVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","value":"STPAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","value":[{"kind":"identifier","text":"STPAddressViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle","value":[{"text":"STPAddressViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}