{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpshippingstatus\/invalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stpshippingstatus\/invalid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/invalid","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The shipping address is invalid."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"title":"STPShippingStatus.invalid","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Stripe@E@STPShippingStatus@STPShippingStatusInvalid","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"STPShippingStatusInvalid"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus/invalid":{"role":"symbol","title":"STPShippingStatus.invalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"abstract":[{"type":"text","text":"The shipping address is invalid."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/invalid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingStatusInvalid"}],"url":"\/documentation\/stripe\/stpshippingstatus\/invalid"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus":{"role":"symbol","title":"STPShippingStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPShippingStatus"}],"abstract":[{"type":"text","text":"An enum representing the status of a shipping address validation."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPShippingStatus"}],"url":"\/documentation\/stripe\/stpshippingstatus"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[{"type":"text","text":"The Stripe iOS SDK makes it quick and easy to build an excellent payment experience in your iOS app. We provide powerful and customizable UI screens and elements that can be used out-of-the-box to collect your users’ payment details. We also expose the low-level APIs that power those UIs so that you can build fully custom experiences."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPShippingStatusInvalid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPShippingStatusInvalid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPShippingStatusInvalid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus~1invalid\/title","value":"STPShippingStatusInvalid"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus~1invalid\/fragments","value":[{"kind":"identifier","text":"STPShippingStatusInvalid"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus\/title","value":"STPShippingStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus\/fragments","value":[{"kind":"identifier","text":"STPShippingStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}