{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/valid"},"metadata":{"role":"symbol","modules":[{"name":"Stripe"}],"title":"STPShippingStatus.valid","roleHeading":"Case","externalID":"c:@M@Stripe@E@STPShippingStatus@STPShippingStatusValid","navigatorTitle":[{"text":"STPShippingStatusValid","kind":"identifier"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"valid"}]},"sections":[],"abstract":[{"type":"text","text":"The shipping address is valid."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpshippingstatus\/valid"]},{"paths":["\/documentation\/stripe\/stpshippingstatus\/valid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}]}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enum representing the status of a shipping address validation."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPShippingStatus"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus","title":"STPShippingStatus","url":"\/documentation\/stripe\/stpshippingstatus","navigatorTitle":[{"text":"STPShippingStatus","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPShippingStatus/valid":{"abstract":[{"type":"text","text":"The shipping address is valid."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPShippingStatus\/valid","role":"symbol","title":"STPShippingStatus.valid","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}],"navigatorTitle":[{"text":"STPShippingStatusValid","kind":"identifier"}],"url":"\/documentation\/stripe\/stpshippingstatus\/valid","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPShippingStatusValid","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPShippingStatusValid","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPShippingStatusValid"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus\/title","value":"STPShippingStatus","op":"replace"},{"value":[{"text":"STPShippingStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus~1valid\/title","value":"STPShippingStatusValid"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPShippingStatus~1valid\/fragments","value":[{"text":"STPShippingStatusValid","kind":"identifier"}],"op":"replace"}]}]}
