{"identifier":{"url":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[[]]},"variants":[{"paths":["\/documentation\/stripeconnect"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripeconnect"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"StripeConnect"}],"externalID":"StripeConnect","title":"StripeConnect","roleHeading":"Framework","symbolKind":"module","role":"collection"},"topicSections":[{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/AccountOnboardingController","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/EmbeddedComponentManager","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPAPIClient","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPAppInfo","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPError","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeAPI"]},{"identifiers":["doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/AccountOnboardingControllerDelegate","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/SafeEnumCodable","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/SafeEnumDecodable","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/UnknownFieldsCodable","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/UnknownFieldsDecodable","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/UnknownFieldsEncodable"],"generated":true,"title":"Protocols","anchor":"Protocols"},{"title":"Structures","anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/AccountCollectionOptions","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/EmbeddedComponentError","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/FinancialConnectionsEvent","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/NonEncodableParameters"]},{"anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeCoreVersionNumber","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeCoreVersionString"],"title":"Variables"},{"identifiers":["doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPCardErrorCode","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPErrorCode"],"anchor":"Enumerations","generated":true,"title":"Enumerations"},{"anchor":"Extended-Modules","title":"Extended Modules","identifiers":["doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/Foundation"],"generated":true}],"abstract":[{"type":"text","text":"Use Connect embedded components to add connected account dashboard functionality to your app. The Stripe Connect iOS SDK and supporting API allow you to grant your users access to Stripe products directly in your dashboard."}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Table of contents","type":"heading","anchor":"Table-of-contents"},{"items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"#Supported-components","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#Requirements","isActive":true}]}]},{"content":[{"inlineContent":[{"identifier":"#Getting-started","isActive":true,"type":"reference"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"#Integration","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.0.1\/StripeConnect\/Example"}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#Manual-linking","type":"reference","isActive":true}]}]}],"type":"unorderedList"},{"anchor":"Supported-components","text":"Supported components","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The following Connect embedded component is supported in the iOS SDK:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/account-onboarding?platform=ios","isActive":true},{"type":"text","text":": Show a localized onboarding form that validates data."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/payments?platform=ios","isActive":true},{"text":": Shows payments and allows users to view payment details and manage disputes.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"isActive":true,"type":"reference","identifier":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/payouts?platform=ios"},{"type":"text","text":": Shows payouts and allows your users to perform payouts."}],"type":"paragraph"}]}]},{"type":"heading","text":"Requirements","anchor":"Requirements","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"StripeConnect","type":"codeVoice"},{"type":"text","text":" module is compatible with apps targeting iOS 15.0 or above."}]},{"anchor":"Getting-started","level":2,"type":"heading","text":"Getting started"},{"text":"Integration","level":3,"anchor":"Integration","type":"heading"},{"inlineContent":[{"type":"text","text":"Get started with Connect embedded components "},{"identifier":"https:\/\/docs.stripe.com\/connect\/get-started-connect-embedded-components?platform=ios","type":"reference","isActive":true},{"type":"text","text":" and "},{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.0.1\/StripeConnect\/..\/Example\/StripeConnectExample","isActive":true,"type":"reference"},{"text":", or ","type":"text"},{"type":"reference","identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-connect\/index.html","isActive":true},{"type":"text","text":" for fine-grained documentation of all the classes and methods in the SDK."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"The Connect SDK requires access to the device’s camera to capture identity documents. To enable your app to request camera permissions, set ","type":"text"},{"code":"NSCameraUsageDescription","type":"codeVoice"},{"text":" in your app’s plist and provide a reason for accessing the camera (e.g. “This app uses the camera to take a picture of your identity documents”).","type":"text"}]},{"anchor":"Example","text":"Example","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"overridingTitle":"StripeConnect Example","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.0.1\/StripeConnect\/..\/Example\/StripeConnectExample","type":"reference","isActive":true,"overridingTitleInlineContent":[{"text":"StripeConnect Example","type":"text"}]},{"text":" – This example demonstrates how to integrate connect embedded components in your app.","type":"text"}]},{"type":"heading","text":"Manual linking","anchor":"Manual-linking","level":2},{"inlineContent":[{"type":"text","text":"If you link the Stripe Connect library manually, use a version from our "},{"isActive":true,"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","type":"reference"},{"type":"text","text":" page and make sure to embed "},{"type":"text","text":"all"},{"type":"text","text":" of the following frameworks:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"StripeConnect.xcframework","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"StripeCore.xcframework"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"StripeFinancialConnections.xcframework","type":"codeVoice"}]}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"StripeUICore.xcframework"}],"type":"paragraph"}]}]}]}],"references":{"#Requirements":{"titleInlineContent":[{"type":"text","text":"Requirements"}],"identifier":"#Requirements","title":"Requirements","url":"#Requirements","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/STPCardErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"STPCardErrorCode"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCardErrorCode","kind":"identifier"}],"title":"STPCardErrorCode","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPCardErrorCode","url":"\/documentation\/stripeconnect\/stpcarderrorcode","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Possible string values you may receive when there was an error tokenizing a card."}]},"#Getting-started":{"titleInlineContent":[{"type":"text","text":"Getting started"}],"identifier":"#Getting-started","title":"Getting started","url":"#Getting-started","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect":{"role":"collection","kind":"symbol","url":"\/documentation\/stripeconnect","title":"StripeConnect","type":"topic","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect","abstract":[{"type":"text","text":"Use Connect embedded components to add connected account dashboard functionality to your app. The Stripe Connect iOS SDK and supporting API allow you to grant your users access to Stripe products directly in your dashboard."}]},"https://github.com/stripe/stripe-ios/releases":{"titleInlineContent":[{"type":"text","text":"releases"}],"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","title":"releases","url":"https:\/\/github.com\/stripe\/stripe-ios\/releases","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/AccountOnboardingControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"AccountOnboardingControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/AccountOnboardingControllerDelegate","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Delegate of an "},{"type":"codeVoice","code":"AccountOnboardingController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccountOnboardingControllerDelegate"}],"url":"\/documentation\/stripeconnect\/accountonboardingcontrollerdelegate","title":"AccountOnboardingControllerDelegate"},"https://docs.stripe.com/connect/get-started-connect-embedded-components?platform=ios":{"titleInlineContent":[{"type":"text","text":"📚 iOS integration guide"}],"identifier":"https:\/\/docs.stripe.com\/connect\/get-started-connect-embedded-components?platform=ios","title":"📚 iOS integration guide","url":"https:\/\/docs.stripe.com\/connect\/get-started-connect-embedded-components?platform=ios","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/UnknownFieldsCodable":{"role":"symbol","type":"topic","title":"UnknownFieldsCodable","kind":"symbol","navigatorTitle":[{"text":"UnknownFieldsCodable","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/UnknownFieldsCodable","url":"\/documentation\/stripeconnect\/unknownfieldscodable","abstract":[{"type":"text","text":"A protocol that conforms to both UnknownFieldsEncodable and UnknownFieldsDecodable."},{"text":" ","type":"text"},{"text":":nodoc:","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UnknownFieldsCodable","kind":"identifier"}]},"https://stripe.dev/stripe-ios/stripe-connect/index.html":{"titleInlineContent":[{"type":"text","text":"📘 browse the SDK reference"}],"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-connect\/index.html","title":"📘 browse the SDK reference","url":"https:\/\/stripe.dev\/stripe-ios\/stripe-connect\/index.html","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/UnknownFieldsEncodable":{"abstract":[{"type":"text","text":"An Encodable object that allows unknown fields to be set."},{"type":"text","text":" "},{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/UnknownFieldsEncodable","type":"topic","title":"UnknownFieldsEncodable","navigatorTitle":[{"text":"UnknownFieldsEncodable","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripeconnect\/unknownfieldsencodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UnknownFieldsEncodable"}],"kind":"symbol"},"#Manual-linking":{"titleInlineContent":[{"type":"text","text":"Manual linking"}],"identifier":"#Manual-linking","title":"Manual linking","url":"#Manual-linking","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/AccountCollectionOptions":{"abstract":[{"text":"Collection options for account onboarding","type":"text"}],"type":"topic","url":"\/documentation\/stripeconnect\/accountcollectionoptions","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/AccountCollectionOptions","navigatorTitle":[{"text":"AccountCollectionOptions","kind":"identifier"}],"kind":"symbol","title":"AccountCollectionOptions","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccountCollectionOptions"}]},"doc://com.stripe.stripe-connect/documentation/StripeConnect/STPAPIClient":{"url":"\/documentation\/stripeconnect\/stpapiclient","navigatorTitle":[{"text":"STPAPIClient","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIClient","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPAPIClient","abstract":[{"text":"A client for making connections to the Stripe API.","type":"text"}],"kind":"symbol","title":"STPAPIClient"},"https://github.com/stripe/stripe-ios/tree/25.0.1/StripeConnect/../Example/StripeConnectExample":{"titleInlineContent":[{"type":"text","text":"example project"}],"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.0.1\/StripeConnect\/..\/Example\/StripeConnectExample","title":"example project","url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.0.1\/StripeConnect\/..\/Example\/StripeConnectExample","type":"link"},"https://docs.stripe.com/connect/supported-embedded-components/account-onboarding?platform=ios":{"titleInlineContent":[{"inlineContent":[{"type":"text","text":"Account onboarding"}],"type":"strong"}],"identifier":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/account-onboarding?platform=ios","title":"Account onboarding","url":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/account-onboarding?platform=ios","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/STPAppInfo":{"navigatorTitle":[{"kind":"identifier","text":"STPAppInfo"}],"abstract":[{"text":"Libraries wrapping the Stripe SDK should use this object to provide information about the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"library, and set it in on "},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":"."}],"title":"STPAppInfo","role":"symbol","kind":"symbol","url":"\/documentation\/stripeconnect\/stpappinfo","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPAppInfo","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAppInfo"}],"type":"topic"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/StripeCoreVersionNumber":{"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeCoreVersionNumber","title":"StripeCoreVersionNumber","type":"topic","kind":"symbol","url":"\/documentation\/stripeconnect\/stripecoreversionnumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"StripeCoreVersionNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"abstract":[],"role":"symbol"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/AccountOnboardingController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccountOnboardingController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/AccountOnboardingController","kind":"symbol","type":"topic","abstract":[{"text":"A view controller representing an account-onboarding component","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccountOnboardingController"}],"url":"\/documentation\/stripeconnect\/accountonboardingcontroller","title":"AccountOnboardingController"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/SafeEnumDecodable":{"abstract":[{"type":"text","text":"A Decodable enum that sets an “unparsable” case"},{"text":" ","type":"text"},{"text":"instead of failing on values that are unknown to the SDK.","type":"text"},{"type":"text","text":" "},{"type":"text","text":":nodoc:"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/SafeEnumDecodable","title":"SafeEnumDecodable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SafeEnumDecodable"}],"kind":"symbol","url":"\/documentation\/stripeconnect\/safeenumdecodable","navigatorTitle":[{"text":"SafeEnumDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-connect/documentation/StripeConnect/EmbeddedComponentError":{"title":"EmbeddedComponentError","url":"\/documentation\/stripeconnect\/embeddedcomponenterror","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmbeddedComponentError"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/EmbeddedComponentError","navigatorTitle":[{"text":"EmbeddedComponentError","kind":"identifier"}],"abstract":[{"text":"An error that can occur loading a Connect embedded component","type":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/FinancialConnectionsEvent":{"abstract":[],"type":"topic","url":"\/documentation\/stripeconnect\/financialconnectionsevent","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FinancialConnectionsEvent","kind":"identifier"}],"navigatorTitle":[{"text":"FinancialConnectionsEvent","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/FinancialConnectionsEvent","kind":"symbol","title":"FinancialConnectionsEvent"},"#Supported-components":{"titleInlineContent":[{"type":"text","text":"Supported components"}],"identifier":"#Supported-components","title":"Supported components","url":"#Supported-components","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/Foundation":{"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/Foundation","title":"Foundation","type":"topic","kind":"symbol","url":"\/documentation\/stripeconnect\/foundation","abstract":[],"role":"collection"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/EmbeddedComponentManager":{"title":"EmbeddedComponentManager","kind":"symbol","navigatorTitle":[{"text":"EmbeddedComponentManager","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/EmbeddedComponentManager","role":"symbol","abstract":[{"type":"text","text":"Manages Connect embedded components"}],"type":"topic","url":"\/documentation\/stripeconnect\/embeddedcomponentmanager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EmbeddedComponentManager","kind":"identifier"}]},"doc://com.stripe.stripe-connect/documentation/StripeConnect/StripeCoreVersionString":{"abstract":[],"title":"StripeCoreVersionString","role":"symbol","kind":"symbol","url":"\/documentation\/stripeconnect\/stripecoreversionstring","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeCoreVersionString","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"StripeCoreVersionString","kind":"identifier"},{"kind":"text","text":": <<error type>>"}],"type":"topic"},"https://docs.stripe.com/connect/supported-embedded-components/payments?platform=ios":{"titleInlineContent":[{"type":"strong","inlineContent":[{"text":"Payments","type":"text"}]}],"identifier":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/payments?platform=ios","title":"Payments","url":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/payments?platform=ios","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/SafeEnumCodable":{"type":"topic","abstract":[{"text":"A Codable enum that sets an “unparsable” case","type":"text"},{"type":"text","text":" "},{"text":"instead of failing on values that are unknown to the SDK.","type":"text"},{"type":"text","text":" "},{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripeconnect\/safeenumcodable","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/SafeEnumCodable","navigatorTitle":[{"kind":"identifier","text":"SafeEnumCodable"}],"kind":"symbol","title":"SafeEnumCodable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SafeEnumCodable","kind":"identifier"}]},"#Integration":{"titleInlineContent":[{"text":"Integration","type":"text"}],"identifier":"#Integration","title":"Integration","url":"#Integration","type":"link"},"https://github.com/stripe/stripe-ios/tree/25.0.1/StripeConnect/Example":{"titleInlineContent":[{"text":"Example","type":"text"}],"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.0.1\/StripeConnect\/Example","title":"Example","url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.0.1\/StripeConnect\/Example","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/UnknownFieldsDecodable":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnknownFieldsDecodable"}],"navigatorTitle":[{"kind":"identifier","text":"UnknownFieldsDecodable"}],"kind":"symbol","abstract":[{"text":"A Decodable object that retains unknown fields.","type":"text"},{"text":" ","type":"text"},{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/UnknownFieldsDecodable","title":"UnknownFieldsDecodable","type":"topic","url":"\/documentation\/stripeconnect\/unknownfieldsdecodable"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/STPErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"STPErrorCode"}],"title":"STPErrorCode","kind":"symbol","url":"\/documentation\/stripeconnect\/stperrorcode","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPErrorCode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPErrorCode"}],"type":"topic","abstract":[{"text":"Possible error code values for NSErrors with the ","type":"text"},{"code":"StripeDomain","type":"codeVoice"},{"type":"text","text":" domain."}],"role":"symbol"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/StripeConnectVersionNumber":{"abstract":[{"text":"Project version number for StripeConnect.","type":"text"}],"title":"StripeConnectVersionNumber","role":"symbol","kind":"symbol","url":"\/documentation\/stripeconnect\/stripeconnectversionnumber","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeConnectVersionNumber","fragments":[{"text":"StripeConnectVersionNumber","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/StripeConnectVersionString":{"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeConnectVersionString","title":"StripeConnectVersionString","type":"topic","kind":"symbol","url":"\/documentation\/stripeconnect\/stripeconnectversionstring","fragments":[{"text":"StripeConnectVersionString","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version string for StripeConnect."}],"role":"symbol"},"https://docs.stripe.com/connect/supported-embedded-components/payouts?platform=ios":{"titleInlineContent":[{"type":"strong","inlineContent":[{"text":"Payouts","type":"text"}]}],"identifier":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/payouts?platform=ios","title":"Payouts","url":"https:\/\/docs.stripe.com\/connect\/supported-embedded-components\/payouts?platform=ios","type":"link"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/NonEncodableParameters":{"navigatorTitle":[{"text":"NonEncodableParameters","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NonEncodableParameters","abstract":[{"text":"This should not be used directly.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Use the "},{"code":"additionalParameters","type":"codeVoice"},{"type":"text","text":" and "},{"code":"allResponseFields","type":"codeVoice"},{"text":" accessors instead.","type":"text"},{"text":" ","type":"text"},{"text":":nodoc:","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"NonEncodableParameters","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/NonEncodableParameters","url":"\/documentation\/stripeconnect\/nonencodableparameters"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/StripeAPI":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StripeAPI"}],"url":"\/documentation\/stripeconnect\/stripeapi","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeAPI","navigatorTitle":[{"kind":"identifier","text":"StripeAPI"}],"title":"StripeAPI","abstract":[{"text":"A top-level class that imports the rest of the Stripe SDK.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-connect/documentation/StripeConnect/STPError":{"identifier":"doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/STPError","url":"\/documentation\/stripeconnect\/stperror","role":"symbol","abstract":[{"text":"Top-level class for Stripe error constants.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPError"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPError","kind":"identifier"}],"kind":"symbol","title":"STPError","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[{"generated":true,"anchor":"Variables","title":"Variables","identifiers":["doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeConnectVersionNumber","doc:\/\/com.stripe.stripe-connect\/documentation\/StripeConnect\/StripeConnectVersionString"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null}]}]}