{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams(im)init","title":"init","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams\/init","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodbancontactparams\/init"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBancontactParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams","kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a Bancontact Payment Method"}],"title":"STPPaymentMethodBancontactParams","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbancontactparams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBancontactParams/init":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams\/init","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodbancontactparams\/init","abstract":[],"title":"init","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/title","op":"replace","value":"STPPaymentMethodBancontactParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodBancontactParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodBancontactParams","kind":"identifier"}]}]}]}