{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkSettings"},"metadata":{"symbolKind":"class","modules":[{"name":"StripePayments"}],"title":"STP_Internal_LinkSettings","fragments":[{"kind":"identifier","text":"STP_Internal_LinkSettings"}],"navigatorTitle":[{"kind":"identifier","text":"STP_Internal_LinkSettings"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STP_Internal_LinkSettings","roleHeading":"Class"},"abstract":[{"type":"text","text":"For internal SDK use only"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkSettings\/allResponseFields"],"anchor":"Instance-Properties","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkSettings\/decodedObjectFromAPIResponse:"],"anchor":"Type-Methods","generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STP_Internal_LinkSettings"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stp_internal_linksettings"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"title":"STPAPIResponseDecodable","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STP_Internal_LinkSettings/decodedObjectFromAPIResponse:":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"title":"decodedObjectFromAPIResponse:","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkSettings\/decodedObjectFromAPIResponse:","kind":"symbol","url":"\/documentation\/stripepayments\/stp_internal_linksettings\/decodedobjectfromapiresponse:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STP_Internal_LinkSettings/allResponseFields":{"fragments":[{"kind":"identifier","text":"allResponseFields"}],"title":"allResponseFields","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkSettings\/allResponseFields","kind":"symbol","url":"\/documentation\/stripepayments\/stp_internal_linksettings\/allresponsefields"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STP_Internal_LinkSettings":{"kind":"symbol","abstract":[{"type":"text","text":"For internal SDK use only"}],"role":"symbol","title":"STP_Internal_LinkSettings","fragments":[{"kind":"identifier","text":"STP_Internal_LinkSettings"}],"url":"\/documentation\/stripepayments\/stp_internal_linksettings","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkSettings"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]}]}]}