{"sections":[],"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/stripepayments\/stp_internal_linkaccountsession"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"STP_Internal_LinkAccountSession"}],"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"identifier","text":"STP_Internal_LinkAccountSession"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STP_Internal_LinkAccountSession","title":"STP_Internal_LinkAccountSession"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkAccountSession"},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkAccountSession\/allResponseFields"],"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkAccountSession\/decodedObjectFromAPIResponse:"],"generated":true,"anchor":"Type-Methods"}],"abstract":[{"text":"For internal SDK use only","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"STP_Internal_LinkAccountSession","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STP_Internal_LinkAccountSession/allResponseFields":{"fragments":[{"text":"allResponseFields","kind":"identifier"}],"abstract":[],"title":"allResponseFields","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stp_internal_linkaccountsession\/allresponsefields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkAccountSession\/allResponseFields","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STP_Internal_LinkAccountSession":{"kind":"symbol","abstract":[{"type":"text","text":"For internal SDK use only"}],"title":"STP_Internal_LinkAccountSession","type":"topic","role":"symbol","fragments":[{"text":"STP_Internal_LinkAccountSession","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stp_internal_linkaccountsession","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkAccountSession"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STP_Internal_LinkAccountSession/decodedObjectFromAPIResponse:":{"title":"decodedObjectFromAPIResponse:","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STP_Internal_LinkAccountSession\/decodedObjectFromAPIResponse:","role":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stp_internal_linkaccountsession\/decodedobjectfromapiresponse:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"type":"topic","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"title":"STPAPIResponseDecodable","navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"}]}]}