{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextWillDismiss(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationPresentingViewController()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/configureSafariViewController(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/prepare(forPresentation:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"metadata":{"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAuthenticationContext"}],"navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","symbolKind":"protocol","title":"STPAuthenticationContext","modules":[{"name":"StripePayments"}]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPAuthenticationContext","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"text":" provides information required to present authentication challenges","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to a user."}],"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/prepare(forPresentation:)":{"type":"topic","abstract":[{"text":"This method is called before presenting a UIViewController for authentication.","type":"text"}],"url":"\/documentation\/stripepayments\/stpauthenticationcontext\/prepare(forpresentation:)","kind":"symbol","navigatorTitle":[{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"}],"role":"symbol","title":"prepare(forPresentation:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepare"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forPresentation"},{"text":": ","kind":"text"},{"text":"STPVoidBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/prepare(forPresentation:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/authenticationContextWillDismiss(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationContextWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextWillDismiss(_:)","abstract":[{"type":"text","text":"This method is called when an authentication UIViewController is about to be dismissed."},{"type":"text","text":" "},{"type":"text","text":"Implement this method to prepare your UI for the authentication view controller to be dismissed. For example,"},{"text":" ","type":"text"},{"type":"text","text":"if you requested authentication while displaying an STPBankSelectionViewController, you may want to hide"},{"text":" ","type":"text"},{"type":"text","text":"it to return the user to your desired view controller."}],"url":"\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationcontextwilldismiss(_:)","navigatorTitle":[{"kind":"identifier","text":"authenticationContextWillDismissViewController:"}],"kind":"symbol","title":"authenticationContextWillDismiss(_:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/configureSafariViewController(_:)":{"title":"configureSafariViewController(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureSafariViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepayments\/stpauthenticationcontext\/configuresafariviewcontroller(_:)","abstract":[{"type":"text","text":"This method is called before presenting an SFSafariViewController for web-based authentication."},{"type":"text","text":" "},{"text":"Implement this method to configure the ","type":"text"},{"type":"codeVoice","code":"SFSafariViewController"},{"text":" instance, e.g. ","type":"text"},{"type":"codeVoice","code":"viewController.preferredBarTintColor = MyBarTintColor"}],"navigatorTitle":[{"text":"configureSafariViewController:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/configureSafariViewController(_:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/authenticationPresentingViewController()":{"required":true,"url":"\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationpresentingviewcontroller()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationPresentingViewController"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The Stripe SDK will modally present additional view controllers on top"},{"type":"text","text":" "},{"text":"of the ","type":"text"},{"type":"codeVoice","code":"authenticationPresentingViewController"},{"type":"text","text":" when required for user"},{"text":" ","type":"text"},{"text":"authentication, like in the Challenge Flow for 3DS2 transactions.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationPresentingViewController()","navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"role":"symbol","title":"authenticationPresentingViewController()","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/authenticationContextDidDismissViewController:":{"url":"\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationcontextdiddismissviewcontroller:","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextDidDismissViewController:","fragments":[{"kind":"text","text":"- "},{"text":"authenticationContextDidDismissViewController:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"authenticationContextDidDismissViewController:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This method is called when an authentication UIViewController has been dismissed."},{"text":" ","type":"text"},{"type":"text","text":"Implement this method to have your UI respond to the authentication view controller to being dismissed. For example,"},{"text":" ","type":"text"},{"text":"if you requested authentication while displaying an STPBankSelectionViewController, you may want to hide","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"it to return the user to your desired view controller."}],"kind":"symbol","title":"authenticationContextDidDismissViewController:"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","url":"\/documentation\/stripepayments\/stpauthenticationcontext","abstract":[{"code":"STPAuthenticationContext","type":"codeVoice"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to a user."}],"title":"STPAuthenticationContext","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAuthenticationContext"}],"navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"STPAuthenticationContext","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPAuthenticationContext"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextDidDismissViewController:","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextWillDismiss(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationPresentingViewController()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/configureSafariViewController(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/prepare(forPresentation:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAuthenticationContext"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1prepare(forPresentation:)\/title","value":"prepareAuthenticationContextForPresentation:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1prepare(forPresentation:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1authenticationContextWillDismiss(_:)\/title","value":"authenticationContextWillDismissViewController:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1authenticationContextWillDismiss(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"authenticationContextWillDismissViewController:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1configureSafariViewController(_:)\/title","value":"configureSafariViewController:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1configureSafariViewController(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"configureSafariViewController:"}],"op":"replace"},{"value":"authenticationPresentingViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1authenticationPresentingViewController()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"authenticationPresentingViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1authenticationPresentingViewController()\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title","op":"replace","value":"STPAuthenticationContext"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"op":"replace"}]}]}