{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"title":"STPAddress","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddress","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPAddress","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(cnContact:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(paymentMethodBillingDetails:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(pkContact:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/city","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/email","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/line1","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/line2","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/phone","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/postalCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/state"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/pkContactValue()"],"title":"Instance Methods","generated":true},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/shippingInfoForCharge(with:shippingMethod:)"],"title":"Type Methods","generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/NSCopying-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPAPIResponseDecodable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPFormEncodable-Implementations"],"title":"Default Implementations","generated":true}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/s9EscapableP","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To","kind":"relationships"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddress","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"STPAddress Contains an address as represented by the Stripe API.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/STPAPIResponseDecodable-Implementations":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPAPIResponseDecodable-Implementations","kind":"article","role":"collectionGroup","title":"STPAPIResponseDecodable Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stpaddress\/stpapiresponsedecodable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/init()":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init()","kind":"symbol","role":"symbol","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Initializes an empty STPAddress.","type":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/init()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/postalCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/postalCode","type":"topic","kind":"symbol","role":"symbol","title":"postalCode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"postalCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The postal code in which the user resides (e.g. “90210”)"}],"navigatorTitle":[{"text":"postalCode","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/postalcode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"url":"\/documentation\/stripepayments\/stpformencodable","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","role":"symbol","type":"topic","abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}],"title":"STPFormEncodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/pkContactValue()":{"type":"topic","title":"pkContactValue()","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/pkContactValue()","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"PKContactValue","kind":"identifier"}],"abstract":[{"text":"Generates a PassKit contact representation of this STPAddress.","type":"text"}],"url":"\/documentation\/stripepayments\/stpaddress\/pkcontactvalue()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pkContactValue","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKContact","text":"PKContact","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/NSCopying-Implementations":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/NSCopying-Implementations","kind":"article","role":"collectionGroup","title":"NSCopying Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stpaddress\/nscopying-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/phone":{"type":"topic","title":"phone","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/phone","navigatorTitle":[{"kind":"identifier","text":"phone"}],"abstract":[{"text":"The phone number of the address (e.g. “8885551212”)","type":"text"}],"url":"\/documentation\/stripepayments\/stpaddress\/phone","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"url":"\/documentation\/stripepayments\/stpaddress","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","role":"symbol","type":"topic","abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"title":"STPAddress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddress","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/init(paymentMethodBillingDetails:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(paymentMethodBillingDetails:)","kind":"symbol","role":"symbol","title":"init(paymentMethodBillingDetails:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paymentMethodBillingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Initializes a new STPAddress with data from STPPaymentMethodBillingDetails.","type":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithPaymentMethodBillingDetails:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/init(paymentmethodbillingdetails:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/email":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/email","type":"topic","kind":"symbol","role":"symbol","title":"email","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The email of the address (e.g. “jane@doe.com”)"}],"navigatorTitle":[{"kind":"identifier","text":"email"}],"url":"\/documentation\/stripepayments\/stpaddress\/email"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/name":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/name","kind":"symbol","role":"symbol","title":"name","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The user’s full name (e.g. “Jane Doe”)","type":"text"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/name"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/line1":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/line1","type":"topic","kind":"symbol","role":"symbol","title":"line1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"line1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The first line of the user’s street address (e.g. “123 Fake St”)"}],"navigatorTitle":[{"kind":"identifier","text":"line1"}],"url":"\/documentation\/stripepayments\/stpaddress\/line1"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/city":{"type":"topic","abstract":[{"text":"The city in which the user resides (e.g. “San Francisco”)","type":"text"}],"title":"city","role":"symbol","navigatorTitle":[{"text":"city","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"city","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/city","url":"\/documentation\/stripepayments\/stpaddress\/city","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/additionalAPIParameters":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/additionalAPIParameters","kind":"symbol","role":"symbol","title":"additionalAPIParameters","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/additionalapiparameters"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/shippingInfoForCharge(with:shippingMethod:)":{"title":"shippingInfoForCharge(with:shippingMethod:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/shippingInfoForCharge(with:shippingMethod:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"shippingInfoForChargeWithAddress:shippingMethod:"}],"abstract":[{"type":"text","text":"When creating a charge on your backend, you can attach shipping information"},{"type":"text","text":" "},{"type":"text","text":"to prevent fraud on a physical good. You can use this method to turn your user’s"},{"type":"text","text":" "},{"type":"text","text":"shipping address and selected shipping method into a hash suitable for attaching"},{"type":"text","text":" "},{"type":"text","text":"to a charge. You should pass this to your backend, and use it as the "},{"code":"shipping","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"parameter when creating a charge."}],"url":"\/documentation\/stripepayments\/stpaddress\/shippinginfoforcharge(with:shippingmethod:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shippingInfoForCharge"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"shippingMethod"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKShippingMethod","text":"PKShippingMethod"},{"kind":"text","text":"?) -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}]},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/STPFormEncodable-Implementations":{"url":"\/documentation\/stripepayments\/stpaddress\/stpformencodable-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPFormEncodable-Implementations","kind":"article","role":"collectionGroup","type":"topic","abstract":[],"title":"STPFormEncodable Implementations"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/s9EscapableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s9EscapableP","title":"Swift.Escapable"},"doc://com.stripe.stripe-payments/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","title":"NSCopying"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/line2":{"type":"topic","abstract":[{"text":"The apartment, floor number, etc of the user’s street address (e.g. “Apartment 1A”)","type":"text"}],"title":"line2","role":"symbol","navigatorTitle":[{"text":"line2","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"line2","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/line2","url":"\/documentation\/stripepayments\/stpaddress\/line2","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/state":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/state","kind":"symbol","role":"symbol","title":"state","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"state","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The state in which the user resides (e.g. “CA”)","type":"text"}],"navigatorTitle":[{"text":"state","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/state"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/init(cnContact:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(cnContact:)","kind":"symbol","role":"symbol","title":"init(cnContact:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cnContact","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CNContact","text":"CNContact","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Initializes a new STPAddress with a contact from the Contacts framework.","type":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithCNContact:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/init(cncontact:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/init(pkContact:)":{"type":"topic","abstract":[{"text":"Initializes a new STPAddress with data from an PassKit contact.","type":"text"}],"title":"init(pkContact:)","role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithPKContact:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pkContact","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)PKContact","text":"PKContact","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(pkContact:)","url":"\/documentation\/stripepayments\/stpaddress\/init(pkcontact:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/allResponseFields":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/allResponseFields","kind":"symbol","role":"symbol","title":"allResponseFields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/allresponsefields"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress/country":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/country","kind":"symbol","role":"symbol","title":"country","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"The ISO country code of the address (e.g. “US”)","type":"text"}],"navigatorTitle":[{"text":"country","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress\/country"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"title":"STPAPIResponseDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIResponseDecodable"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPAddress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPAddress","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPAddress","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/city","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/email","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/line1","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/line2","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/phone","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/postalCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/state"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(cnContact:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(paymentMethodBillingDetails:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/init(pkContact:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/pkContactValue()"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/shippingInfoForCharge(with:shippingMethod:)"],"anchor":"Type-Methods"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/NSCopying-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPAPIResponseDecodable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress\/STPFormEncodable-Implementations"],"anchor":"Default-Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddress","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1postalCode\/title","value":"postalCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1postalCode\/fragments","value":[{"text":"postalCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","value":"STPFormEncodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1pkContactValue()\/title","value":"PKContactValue"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1pkContactValue()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"PKContactValue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1phone\/title","value":"phone"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1phone\/fragments","value":[{"text":"phone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","value":"STPAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","value":[{"text":"STPAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"text":"STPAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(paymentMethodBillingDetails:)\/title","value":"initWithPaymentMethodBillingDetails:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(paymentMethodBillingDetails:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPaymentMethodBillingDetails:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1email\/title","value":"email"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1email\/fragments","value":[{"text":"email","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1line1\/title","value":"line1"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1line1\/fragments","value":[{"text":"line1","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1city\/title","value":"city"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1city\/fragments","value":[{"text":"city","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1additionalAPIParameters\/title","value":"additionalAPIParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1additionalAPIParameters\/fragments","value":[{"text":"additionalAPIParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1shippingInfoForCharge(with:shippingMethod:)\/title","value":"shippingInfoForChargeWithAddress:shippingMethod:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1shippingInfoForCharge(with:shippingMethod:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"shippingInfoForChargeWithAddress:shippingMethod:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1line2\/title","value":"line2"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1line2\/fragments","value":[{"text":"line2","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1state\/fragments","value":[{"text":"state","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(cnContact:)\/title","value":"initWithCNContact:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(cnContact:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCNContact:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(pkContact:)\/title","value":"initWithPKContact:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1init(pkContact:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPKContact:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1allResponseFields\/title","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1country\/title","value":"country"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress~1country\/fragments","value":[{"text":"country","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}