{"metadata":{"navigatorTitle":[{"text":"STPBankAccount","kind":"identifier"}],"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccount","kind":"identifier"}],"roleHeading":"Class","title":"STPBankAccount","externalID":"c:@M@StripePayments@objc(cs)STPBankAccount","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"text":"Representation of a user’s bank account details that have been tokenized with","type":"text"},{"text":" ","type":"text"},{"text":"the Stripe API.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/accountHolderName","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/accountHolderType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/bankAccountId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/bankName","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/fingerprint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/routingNumber","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/stripeID"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccount"}]}]},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api#Bank_accounts"}],"type":"paragraph"}],"style":"note","name":"See Also"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccount"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"kind":"relationships","type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/stripeID":{"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccount\/stripeid","role":"symbol","kind":"symbol","abstract":[{"text":"The Stripe ID of the source.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripeID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/stripeID","navigatorTitle":[{"text":"stripeID","kind":"identifier"}],"title":"stripeID"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/decodedObject(fromAPIResponse:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"title":"decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"url":"\/documentation\/stripepayments\/stpbankaccount\/decodedobject(fromapiresponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/isEqual(_:)":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","title":"isEqual(_:)","url":"\/documentation\/stripepayments\/stpbankaccount\/isequal(_:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/country":{"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccount\/country","navigatorTitle":[{"kind":"identifier","text":"country"}],"title":"country","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/country","abstract":[{"type":"text","text":"Two-letter ISO code representing the country the bank account is located in."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"country"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount":{"navigatorTitle":[{"kind":"identifier","text":"STPBankAccount"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount","title":"STPBankAccount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccount"}],"abstract":[{"type":"text","text":"Representation of a user’s bank account details that have been tokenized with"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccount"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/status":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPBankAccountStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountStatus"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"abstract":[{"type":"text","text":"The validation status of the bank account. - seealso: STPBankAccountStatus"}],"kind":"symbol","role":"symbol","title":"status","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/status","url":"\/documentation\/stripepayments\/stpbankaccount\/status"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","kind":"symbol","abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"title":"STPAPIResponseDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/accountHolderType":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"accountHolderType"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountHolderType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountHolderType"}],"type":"topic","abstract":[{"text":"The type of entity that holds the account.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/accountHolderType","title":"accountHolderType","url":"\/documentation\/stripepayments\/stpbankaccount\/accountholdertype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/last4":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/last4","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"last4"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/last4","type":"topic","abstract":[{"text":"The last 4 digits of the account number.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"last4"}],"kind":"symbol","title":"last4"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocol":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSourceProtocol","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to this protocol can be attached to a Stripe Customer object"},{"type":"text","text":" "},{"type":"text","text":"as a payment source."}],"title":"STPSourceProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/allResponseFields":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"url":"\/documentation\/stripepayments\/stpbankaccount\/allresponsefields","title":"allResponseFields","role":"symbol","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/bankName":{"type":"topic","title":"bankName","role":"symbol","abstract":[{"type":"text","text":"The name of the bank that owns the account."}],"url":"\/documentation\/stripepayments\/stpbankaccount\/bankname","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/bankName","navigatorTitle":[{"text":"bankName","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bankName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/bankAccountId":{"deprecated":true,"role":"symbol","kind":"symbol","title":"bankAccountId","abstract":[{"type":"text","text":"The Stripe ID for the bank account."}],"navigatorTitle":[{"kind":"identifier","text":"bankAccountId"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/bankaccountid","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/bankAccountId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankAccountId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/currency":{"abstract":[{"type":"text","text":"The default currency for the bank account."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccount\/currency","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/currency","title":"currency","kind":"symbol","navigatorTitle":[{"text":"currency","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/hash":{"kind":"symbol","title":"hash","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/hash","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/fingerprint":{"type":"topic","abstract":[{"type":"text","text":"A proxy for the account number, this uniquely identifies the account and can be"},{"type":"text","text":" "},{"type":"text","text":"used to compare equality of different bank accounts."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingerprint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/fingerprint","navigatorTitle":[{"text":"fingerprint","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/fingerprint","role":"symbol","title":"fingerprint","kind":"symbol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/routingNumber":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/routingNumber","title":"routingNumber","url":"\/documentation\/stripepayments\/stpbankaccount\/routingnumber","navigatorTitle":[{"kind":"identifier","text":"routingNumber"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"routingNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","abstract":[{"text":"The routing number for the bank account. This should be the ACH routing number,","type":"text"},{"text":" ","type":"text"},{"text":"not the wire routing number.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccount/accountHolderName":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountHolderName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpbankaccount\/accountholdername","role":"symbol","navigatorTitle":[{"text":"accountHolderName","kind":"identifier"}],"abstract":[{"type":"text","text":"The name of the person or business that owns the bank account."}],"title":"accountHolderName","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/accountHolderName","kind":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"STPBankAccount","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPBankAccount","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPBankAccount"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/accountHolderName","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/accountHolderType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/bankAccountId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/bankName","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/fingerprint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/routingNumber","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/stripeID"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/isEqual(_:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccount\/decodedObject(fromAPIResponse:)"],"generated":true,"title":"Type Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccount","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1stripeID\/title","value":"stripeID"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1stripeID\/fragments","value":[{"kind":"identifier","text":"stripeID"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1country\/title","value":"country"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1country\/fragments","value":[{"text":"country","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/title","value":"STPBankAccount"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/fragments","value":[{"kind":"identifier","text":"STPBankAccount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount\/navigatorTitle","value":[{"kind":"identifier","text":"STPBankAccount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1status\/title","value":"status"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1status\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1accountHolderType\/title","value":"accountHolderType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1accountHolderType\/fragments","value":[{"text":"accountHolderType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1last4\/title","value":"last4"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1last4\/fragments","value":[{"kind":"identifier","text":"last4"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/title","value":"STPSourceProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/fragments","value":[{"kind":"identifier","text":"STPSourceProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1allResponseFields\/title","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1bankName\/title","value":"bankName"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1bankName\/fragments","value":[{"text":"bankName","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1bankAccountId\/title","value":"bankAccountId"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1bankAccountId\/fragments","value":[{"text":"bankAccountId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1currency\/title","value":"currency"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1currency\/fragments","value":[{"kind":"identifier","text":"currency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1fingerprint\/title","value":"fingerprint"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1fingerprint\/fragments","value":[{"kind":"identifier","text":"fingerprint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1routingNumber\/title","value":"routingNumber"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1routingNumber\/fragments","value":[{"kind":"identifier","text":"routingNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1accountHolderName\/title","value":"accountHolderName"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccount~1accountHolderName\/fragments","value":[{"text":"accountHolderName","kind":"identifier"}]}]}]}