{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysDark","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysLight","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/automatic"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s15BitwiseCopyableP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY","doc:\/\/com.stripe.stripe-payments\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"role":"symbol","symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"externalID":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","title":"STPBankAccountCollectorUserInterfaceStyle"},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@frozen"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Style options for colors in the bank account collector."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/automatic":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/automatic","type":"topic","kind":"symbol","role":"symbol","title":"STPBankAccountCollectorUserInterfaceStyle.automatic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"automatic","kind":"identifier"}],"abstract":[{"type":"text","text":"(default) The bank account collector will automatically switch between light and dark mode compatible colors based on device settings."}],"navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyleAutomatic","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/automatic"},"doc://com.stripe.stripe-payments/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s15BitwiseCopyableP","type":"unresolvable","title":"Swift.BitwiseCopyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/alwaysDark":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysDark","type":"topic","kind":"symbol","role":"symbol","title":"STPBankAccountCollectorUserInterfaceStyle.alwaysDark","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alwaysDark","kind":"identifier"}],"abstract":[{"type":"text","text":"The bank account collector will always use colors appropriate for dark mode UI."}],"navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/alwaysdark"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/alwaysLight":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysLight","type":"topic","kind":"symbol","role":"symbol","title":"STPBankAccountCollectorUserInterfaceStyle.alwaysLight","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alwaysLight","kind":"identifier"}],"abstract":[{"type":"text","text":"The bank account collector will always use colors appropriate for light mode UI."}],"navigatorTitle":[{"text":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/alwayslight"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/rawrepresentable-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","type":"topic","abstract":[],"title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/s8SendableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/equatable-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/Equatable-Implementations","kind":"article","role":"collectionGroup","type":"topic","abstract":[],"title":"Equatable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle":{"url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Style options for colors in the bank account collector."}],"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}],"title":"STPBankAccountCollectorUserInterfaceStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollectorUserInterfaceStyle/init(rawValue:)":{"type":"topic","abstract":[],"title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/init(rawValue:)","url":"\/documentation\/stripepayments\/stpbankaccountcollectoruserinterfacestyle\/init(rawvalue:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPBankAccountCollectorUserInterfaceStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysDark","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/alwaysLight","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollectorUserInterfaceStyle\/automatic"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollectorUserInterfaceStyle","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1automatic\/title","value":"STPBankAccountCollectorUserInterfaceStyleAutomatic"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1automatic\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAutomatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1alwaysDark\/title","value":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1alwaysDark\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAlwaysDark"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1alwaysLight\/title","value":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle~1alwaysLight\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyleAlwaysLight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/title","value":"STPBankAccountCollectorUserInterfaceStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollectorUserInterfaceStyle\/navigatorTitle","value":[{"kind":"identifier","text":"STPBankAccountCollectorUserInterfaceStyle"}]}]}]}