{"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"STPBankAccountStatus","externalID":"c:@M@StripePayments@E@STPBankAccountStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountStatus"}],"roleHeading":"Enumeration","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountStatus"}]},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/errored","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/new","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/validated","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verificationFailed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verified"]},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountstatus"]},{"paths":["\/documentation\/stripepayments\/stpbankaccountstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountStatus"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","abstract":[{"type":"text","text":"Possible validation states for a bank account."}],"references":{"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/RawRepresentable-Implementations","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/verificationFailed":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verificationFailed","role":"symbol","title":"STPBankAccountStatus.verificationFailed","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/verificationfailed","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verificationFailed"}],"navigatorTitle":[{"text":"STPBankAccountStatusVerificationFailed","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Verification for this bank account has failed."}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/verified":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verified","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/verified","title":"STPBankAccountStatus.verified","role":"symbol","abstract":[{"type":"text","text":"Bank account verification has succeeded."}],"navigatorTitle":[{"text":"STPBankAccountStatusVerified","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verified"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/Equatable-Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/equatable-implementations","title":"Equatable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus":{"role":"symbol","abstract":[{"text":"Possible validation states for a bank account.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","title":"STPBankAccountStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountStatus"}],"url":"\/documentation\/stripepayments\/stpbankaccountstatus","kind":"symbol","navigatorTitle":[{"text":"STPBankAccountStatus","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/stripepayments\/stpbankaccountstatus\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/CustomStringConvertible-Implementations":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/CustomStringConvertible-Implementations","role":"collectionGroup","title":"CustomStringConvertible Implementations","kind":"article","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/customstringconvertible-implementations","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/errored":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errored"}],"role":"symbol","title":"STPBankAccountStatus.errored","abstract":[{"text":"A transfer sent to this bank account has failed.","type":"text"}],"url":"\/documentation\/stripepayments\/stpbankaccountstatus\/errored","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/errored","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountStatusErrored"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/validated":{"navigatorTitle":[{"text":"STPBankAccountStatusValidated","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/validated","type":"topic","abstract":[{"type":"text","text":"Stripe has determined this bank account exists."}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/validated","title":"STPBankAccountStatus.validated","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"validated","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/new":{"abstract":[{"type":"text","text":"The account has had no activity or validation performed"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"new"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/new","navigatorTitle":[{"text":"STPBankAccountStatusNew","kind":"identifier"}],"role":"symbol","title":"STPBankAccountStatus.new","kind":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/new","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"STPBankAccountStatus","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPBankAccountStatus","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPBankAccountStatus"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/errored","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/new","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/validated","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verificationFailed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verified"],"generated":true,"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"STPBankAccountStatusVerificationFailed","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1verificationFailed\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1verificationFailed\/fragments","value":[{"kind":"identifier","text":"STPBankAccountStatusVerificationFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1verified\/title","value":"STPBankAccountStatusVerified"},{"value":[{"kind":"identifier","text":"STPBankAccountStatusVerified"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1verified\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/title","op":"replace","value":"STPBankAccountStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/fragments","value":[{"kind":"identifier","text":"STPBankAccountStatus"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPBankAccountStatus"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1errored\/title","value":"STPBankAccountStatusErrored","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1errored\/fragments","value":[{"kind":"identifier","text":"STPBankAccountStatusErrored"}]},{"value":"STPBankAccountStatusValidated","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1validated\/title"},{"value":[{"kind":"identifier","text":"STPBankAccountStatusValidated"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1validated\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1new\/title","op":"replace","value":"STPBankAccountStatusNew"},{"op":"replace","value":[{"text":"STPBankAccountStatusNew","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1new\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}