{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountcollector"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Class","symbolKind":"class","title":"STPBankAccountCollector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountCollector"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPBankAccountCollector"},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(apiClient:style:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(style:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/apiClient","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/style"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:params:from:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:params:from:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)"]},{"anchor":"Type-Aliases","generated":true,"title":"Type Aliases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/style":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/style","abstract":[{"text":"Style options for the bank account collector.","type":"text"},{"text":" ","type":"text"},{"text":"By default, the bank account collector will automatically switch between light and dark mode compatible colors based on device settings.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPBankAccountCollectorUserInterfaceStyle","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/style","title":"style"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)":{"title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onEvent"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","text":"FinancialConnectionsEvent"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","text":"STPPaymentIntent"}],"abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a PaymentIntent"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:onevent:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForSetupCompletionBlock":{"type":"topic","navigatorTitle":[{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForSetupCompletionBlock","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"identifier"}],"title":"STPBankAccountCollector.STPCollectBankAccountForSetupCompletionBlock","abstract":[],"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforsetupcompletionblock"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/apiClient":{"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/apiclient","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAPIClient","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/apiClient","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"By default "},{"type":"codeVoice","code":"sharedHandler"},{"type":"text","text":" initializes with STPAPIClient.shared."}],"title":"apiClient"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:)":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:returnurl:params:from:onevent:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForSetup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier","text":"STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onEvent"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","kind":"typeIdentifier","text":"FinancialConnectionsEvent"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","kind":"typeIdentifier","text":"STPSetupIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:)","title":"collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:)","abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a SetupIntent"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/init(style:)":{"deprecated":true,"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/init(style:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPBankAccountCollectorUserInterfaceStyle","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(style:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(style:)","navigatorTitle":[{"text":"initWithStyle:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector":{"role":"symbol","title":"STPBankAccountCollector","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector","url":"\/documentation\/stripepayments\/stpbankaccountcollector","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountCollector","kind":"identifier"}],"navigatorTitle":[{"text":"STPBankAccountCollector","kind":"identifier"}],"abstract":[{"text":"A class responsible for collecting bank account information","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForSetup(clientSecret:params:from:completion:)":{"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:params:from:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:params:from:completion:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectBankAccountForSetupWithClientSecret:params:from:completion:"}],"role":"symbol","title":"collectBankAccountForSetup(clientSecret:params:from:completion:)","abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a SetupIntent"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForSetup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCollectBankAccountForSetupCompletionBlock","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)","abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and if completed successfully, link your bank account to a PaymentIntent"}],"title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForPayment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCollectBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCollectBankAccountForPaymentCompletionBlock","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForPayment(clientSecret:params:from:completion:)":{"navigatorTitle":[{"text":"collectBankAccountForPaymentWithClientSecret:params:from:completion:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:params:from:completion:)","kind":"symbol","abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"text":"and if completed successfully, link your bank account to a PaymentIntent","type":"text"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:params:from:completion:)","type":"topic","title":"collectBankAccountForPayment(clientSecret:params:from:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)":{"kind":"symbol","role":"symbol","title":"collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectBankAccountForSetup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","kind":"typeIdentifier","text":"STPCollectBankAccountParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onEvent"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","kind":"typeIdentifier","text":"FinancialConnectionsEvent"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka","kind":"typeIdentifier","text":"STPCollectBankAccountForSetupCompletionBlock"},{"kind":"text","text":")"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:returnurl:params:from:onevent:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:onEvent:completion:)","type":"topic","abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"text":"and if completed successfully, link your bank account to a SetupIntent","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/STPCollectBankAccountForPaymentCompletionBlock":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","title":"STPBankAccountCollector.STPCollectBankAccountForPaymentCompletionBlock","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/stpcollectbankaccountforpaymentcompletionblock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/STPCollectBankAccountForPaymentCompletionBlock","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/init()":{"abstract":[],"deprecated":true,"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/init()","type":"topic","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/init(apiClient:style:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(apiClient:style:)","role":"symbol","title":"init(apiClient:style:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"apiClient"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient","text":"STPAPIClient"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPBankAccountCollectorUserInterfaceStyle","text":"STPBankAccountCollectorUserInterfaceStyle"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/init(apiclient:style:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)","abstract":[{"type":"text","text":"Presents a modal from the viewController to collect bank account"},{"type":"text","text":" "},{"type":"text","text":"and if completed successfully, link your bank account to a PaymentIntent"}],"url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforpayment(clientsecret:returnurl:params:from:onevent:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","text":"STPCollectBankAccountParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onEvent","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:10StripeCore25FinancialConnectionsEventV","text":"FinancialConnectionsEvent","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD25ForPaymentCompletionBlocka","text":"STPCollectBankAccountForPaymentCompletionBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"collectBankAccountForPayment(clientSecret:returnURL:params:from:onEvent:completion:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountCollector/collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)","abstract":[{"text":"Presents a modal from the viewController to collect bank account","type":"text"},{"text":" ","type":"text"},{"text":"and if completed successfully, link your bank account to a SetupIntent","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectBankAccountForSetup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCollectBankAccountForSetupCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments23STPBankAccountCollectorC014STPCollectBankD23ForSetupCompletionBlocka"},{"text":")","kind":"text"}],"title":"collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)","url":"\/documentation\/stripepayments\/stpbankaccountcollector\/collectbankaccountforsetup(clientsecret:returnurl:params:from:completion:)","navigatorTitle":[{"text":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"STPBankAccountCollector","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPBankAccountCollector","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPBankAccountCollector","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:params:from:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:params:from:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountCollector\/init(style:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountCollector"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1init(style:)\/title","value":"initWithStyle:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1init(style:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/title","value":"STPBankAccountCollector","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/fragments","value":[{"kind":"identifier","text":"STPBankAccountCollector"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector\/navigatorTitle","value":[{"text":"STPBankAccountCollector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForSetup(clientSecret:params:from:completion:)\/title","value":"collectBankAccountForSetupWithClientSecret:params:from:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForSetup(clientSecret:params:from:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectBankAccountForSetupWithClientSecret:params:from:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)\/title","value":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForPayment(clientSecret:returnURL:params:from:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectBankAccountForPaymentWithClientSecret:returnURL:params:from:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForPayment(clientSecret:params:from:completion:)\/title","value":"collectBankAccountForPaymentWithClientSecret:params:from:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForPayment(clientSecret:params:from:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectBankAccountForPaymentWithClientSecret:params:from:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)\/title","value":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountCollector~1collectBankAccountForSetup(clientSecret:returnURL:params:from:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectBankAccountForSetupWithClientSecret:returnURL:params:from:completion:"}],"op":"replace"}]}]}