{"metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountHolderType"}],"title":"STPBankAccountHolderType","modules":[{"name":"StripePayments"}],"symbolKind":"enum","externalID":"c:@M@StripePayments@E@STPBankAccountHolderType","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/company","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/individual"],"anchor":"Enumeration-Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/init(rawValue:)"],"title":"Initializers"},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/RawRepresentable-Implementations"]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountHolderType"}]}]}],"abstract":[{"text":"The type of entity that holds a bank account.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType"},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountholdertype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountholdertype"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType":{"url":"\/documentation\/stripepayments\/stpbankaccountholdertype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType","abstract":[{"text":"The type of entity that holds a bank account.","type":"text"}],"title":"STPBankAccountHolderType","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountHolderType"}],"navigatorTitle":[{"kind":"identifier","text":"STPBankAccountHolderType"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/Equatable-Implementations","url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/equatable-implementations","type":"topic","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/CustomStringConvertible-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/CustomStringConvertible-Implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/rawrepresentable-implementations","kind":"article","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/RawRepresentable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/init(rawValue:)","url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/company":{"title":"STPBankAccountHolderType.company","navigatorTitle":[{"text":"STPBankAccountHolderTypeCompany","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/company","type":"topic","abstract":[{"type":"text","text":"A company holds this bank account."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"company","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/company","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountHolderType/individual":{"kind":"symbol","type":"topic","abstract":[{"text":"An individual holds this bank account.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/individual","url":"\/documentation\/stripepayments\/stpbankaccountholdertype\/individual","role":"symbol","title":"STPBankAccountHolderType.individual","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"individual"}],"navigatorTitle":[{"text":"STPBankAccountHolderTypeIndividual","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPBankAccountHolderType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","value":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccountHolderType","kind":"identifier"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/company","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountHolderType\/individual"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountHolderType"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"STPBankAccountHolderType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/title"},{"op":"replace","value":[{"text":"STPBankAccountHolderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType\/navigatorTitle","op":"replace","value":[{"text":"STPBankAccountHolderType","kind":"identifier"}]},{"value":"STPBankAccountHolderTypeCompany","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType~1company\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType~1company\/fragments","value":[{"kind":"identifier","text":"STPBankAccountHolderTypeCompany"}]},{"value":"STPBankAccountHolderTypeIndividual","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType~1individual\/title","op":"replace"},{"value":[{"text":"STPBankAccountHolderTypeIndividual","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountHolderType~1individual\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}