{"kind":"symbol","topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/init(setupFutureUsage:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/setupFutureUsage"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/STPFormEncodable-Implementations"],"anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"text":"Options for US Bank Account Payment Methods during PaymentIntent or SetupIntent confirmation","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConfirmUSBankAccountOptions"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"seealso https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-payment_method_options-us_bank_account"}],"type":"paragraph"}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmusbankaccountoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmusbankaccountoptions"]}],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPConfirmUSBankAccountOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","title":"STPConfirmUSBankAccountOptions","role":"symbol"},"references":{"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions/additionalAPIParameters":{"abstract":[{"type":"text","text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:"},{"type":"text","text":" "},{"type":"text","text":"var cardParams = STPCardParams()"},{"type":"text","text":" "},{"type":"text","text":"\/\/ add card values"},{"type":"text","text":" "},{"text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]","type":"text"},{"type":"text","text":" "},{"text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);","type":"text"}],"kind":"symbol","title":"additionalAPIParameters","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/additionalAPIParameters","url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/additionalapiparameters","navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions":{"title":"STPConfirmUSBankAccountOptions","kind":"symbol","abstract":[{"type":"text","text":"Options for US Bank Account Payment Methods during PaymentIntent or SetupIntent confirmation"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions","navigatorTitle":[{"kind":"identifier","text":"STPConfirmUSBankAccountOptions"}],"url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions/init(setupFutureUsage:)":{"abstract":[{"type":"text","text":"Initializer for "},{"type":"codeVoice","code":"STPConfirmUSBankAccountOptions"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"setupFutureUsage"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(setupFutureUsage:)","type":"topic","navigatorTitle":[{"text":"initWithSetupFutureUsage:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/init(setupfutureusage:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/init(setupFutureUsage:)","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions/setupFutureUsage":{"abstract":[{"text":"Indicates that you intend to make future payments with this payment method.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Providing this parameter will attach the payment method to the PaymentIntent’s Customer, if present, after the Intent is confirmed and any required actions from the user are complete. If no Customer was provided, the payment method can still be attached to a Customer after the transaction completes."}],"kind":"symbol","title":"setupFutureUsage","url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/setupfutureusage","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/setupFutureUsage","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage"}],"navigatorTitle":[{"text":"setupFutureUsage","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions/STPFormEncodable-Implementations":{"title":"STPFormEncodable Implementations","url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions\/stpformencodable-implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/STPFormEncodable-Implementations","role":"collectionGroup","abstract":[],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"title":"STPFormEncodable","url":"\/documentation\/stripepayments\/stpformencodable","kind":"symbol","abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"STPConfirmUSBankAccountOptions"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"STPConfirmUSBankAccountOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/setupFutureUsage"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/init(setupFutureUsage:)"],"anchor":"Instance-Methods"},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions\/STPFormEncodable-Implementations"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConfirmUSBankAccountOptions"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1additionalAPIParameters\/title","op":"replace","value":"additionalAPIParameters"},{"value":[{"kind":"identifier","text":"additionalAPIParameters"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1additionalAPIParameters\/fragments"},{"op":"replace","value":"STPConfirmUSBankAccountOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/title"},{"value":[{"kind":"identifier","text":"STPConfirmUSBankAccountOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/fragments"},{"value":[{"kind":"identifier","text":"STPConfirmUSBankAccountOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1init(setupFutureUsage:)\/title","value":"initWithSetupFutureUsage:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSetupFutureUsage:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1init(setupFutureUsage:)\/fragments"},{"value":"setupFutureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1setupFutureUsage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions~1setupFutureUsage\/fragments","value":[{"kind":"identifier","text":"setupFutureUsage"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","value":"STPFormEncodable","op":"replace"},{"value":[{"kind":"identifier","text":"STPFormEncodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"}]}]}