{"metadata":{"symbolKind":"class","role":"symbol","title":"STPCard","modules":[{"name":"StripePayments"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCard","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPCard","navigatorTitle":[{"text":"STPCard","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/stripepayments\/stpcard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcard"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"},"abstract":[{"text":"Representation of a user’s credit card details that have been tokenized with","type":"text"},{"text":" ","type":"text"},{"text":"the Stripe API","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/init(id:brand:last4:expMonth:expYear:funding:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/address","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressCity","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressCountry","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressLine1","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressLine2","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressState","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressZip","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/brand","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/cardId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/dynamicLast4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/expMonth","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/expYear","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/isApplePayCard","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/stripeID"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/brand(from:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/decodedObject(fromAPIResponse:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding(from:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/string(from:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCard"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api#Cards","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note","name":"See Also"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard":{"navigatorTitle":[{"text":"STPCard","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Representation of a user’s credit card details that have been tokenized with"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API"}],"url":"\/documentation\/stripepayments\/stpcard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard","role":"symbol","title":"STPCard","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCard","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/addressCity":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressCity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"The city of the cardholder’s address","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressCity","kind":"symbol","url":"\/documentation\/stripepayments\/stpcard\/addresscity","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"addressCity"}],"title":"addressCity","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/allResponseFields":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"url":"\/documentation\/stripepayments\/stpcard\/allresponsefields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"kind":"symbol","title":"allResponseFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/name":{"navigatorTitle":[{"text":"name","kind":"identifier"}],"type":"topic","abstract":[{"text":"The cardholder’s name.","type":"text"}],"title":"name","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/name","kind":"symbol","url":"\/documentation\/stripepayments\/stpcard\/name","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/last4":{"type":"topic","kind":"symbol","title":"last4","abstract":[{"type":"text","text":"The last 4 digits of the card."}],"url":"\/documentation\/stripepayments\/stpcard\/last4","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/last4","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"last4","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/funding":{"navigatorTitle":[{"kind":"identifier","text":"funding"}],"abstract":[{"type":"text","text":"The funding source for the card (credit, debit, prepaid, or other)"}],"type":"topic","title":"funding","kind":"symbol","url":"\/documentation\/stripepayments\/stpcard\/funding","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"funding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","text":"STPCardFundingType"}]},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/stripeID":{"title":"stripeID","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripeID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/stripeID","url":"\/documentation\/stripepayments\/stpcard\/stripeid","navigatorTitle":[{"kind":"identifier","text":"stripeID"}],"abstract":[{"type":"text","text":"The Stripe ID of the source."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/address":{"abstract":[{"type":"text","text":"The cardholder’s address."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/address","kind":"symbol","title":"address","role":"symbol","navigatorTitle":[{"text":"address","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpcard\/address","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/init(id:brand:last4:expMonth:expYear:funding:)":{"url":"\/documentation\/stripepayments\/stpcard\/init(id:brand:last4:expmonth:expyear:funding:)","kind":"symbol","abstract":[{"text":"Create an STPCard from a Stripe API response.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/init(id:brand:last4:expMonth:expYear:funding:)","role":"symbol","title":"init(id:brand:last4:expMonth:expYear:funding:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"brand","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":", ","kind":"text"},{"text":"last4","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expMonth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expYear"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"funding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","text":"STPCardFundingType"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithID:brand:last4:expMonth:expYear:funding:"}],"deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/addressLine2":{"type":"topic","title":"addressLine2","kind":"symbol","abstract":[{"text":"The second line of the cardholder’s address","type":"text"}],"url":"\/documentation\/stripepayments\/stpcard\/addressline2","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressLine2","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addressLine2"}],"deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressLine2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/decodedObject(fromAPIResponse:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stpcard\/decodedobject(fromapiresponse:)","title":"decodedObject(fromAPIResponse:)","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/brand(from:)":{"role":"symbol","url":"\/documentation\/stripepayments\/stpcard\/brand(from:)","navigatorTitle":[{"kind":"identifier","text":"brandFromString:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/brand(from:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"}],"kind":"symbol","title":"brand(from:)","abstract":[{"type":"text","text":"This parses a string representing a card’s brand into the appropriate"},{"type":"text","text":" "},{"type":"text","text":"STPCardBrand enum value,"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"type":"codeVoice","code":"STPCard.brand(from string: \"American Express\") == .amex"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The string values themselves are specific to Stripe as listed in the Stripe API"},{"type":"text","text":" "},{"type":"text","text":"documentation."}]},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/isEqual(_:)":{"url":"\/documentation\/stripepayments\/stpcard\/isequal(_:)","abstract":[{"text":":nodoc:","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/isEqual(_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/country":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/country","title":"country","url":"\/documentation\/stripepayments\/stpcard\/country","abstract":[{"text":"Two-letter ISO code representing the issuing country of the card.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"country","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/addressLine1":{"type":"topic","title":"addressLine1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressLine1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpcard\/addressline1","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressLine1","abstract":[{"type":"text","text":"The first line of the cardholder’s address"}],"navigatorTitle":[{"kind":"identifier","text":"addressLine1"}],"deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/hash":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/hash","abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/stripepayments\/stpcard\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","title":"hash"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/addressZip":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpcard\/addresszip","abstract":[{"text":"The zip code of the cardholder’s address","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressZip","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"addressZip","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressZip","type":"topic","navigatorTitle":[{"text":"addressZip","kind":"identifier"}],"deprecated":true,"role":"symbol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/brand":{"navigatorTitle":[{"kind":"identifier","text":"brand"}],"url":"\/documentation\/stripepayments\/stpcard\/brand","abstract":[{"type":"text","text":"The issuer of the card."}],"kind":"symbol","title":"brand","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/brand","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brand"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/string(from:)":{"url":"\/documentation\/stripepayments\/stpcard\/string(from:)","title":"string(from:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/string(from:)","kind":"symbol","abstract":[{"type":"text","text":"Returns a string representation for the provided card brand;"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"type":"codeVoice","code":"STPCard.string(from brand: .visa) == \"Visa\""},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stringFromBrand:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"title":"STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/addressState":{"abstract":[{"type":"text","text":"The state of the cardholder’s address"}],"role":"symbol","title":"addressState","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"addressState","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressState","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpcard\/addressstate"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/dynamicLast4":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/dynamicLast4","kind":"symbol","url":"\/documentation\/stripepayments\/stpcard\/dynamiclast4","type":"topic","abstract":[{"text":"For cards made with Apple Pay, this refers to the last 4 digits of the","type":"text"},{"text":" ","type":"text"},{"text":"“Device Account Number” for the tokenized card. For regular cards, it will","type":"text"},{"text":" ","type":"text"},{"text":"be nil.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dynamicLast4"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"dynamicLast4"}],"role":"symbol","title":"dynamicLast4"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/isApplePayCard":{"role":"symbol","type":"topic","kind":"symbol","title":"isApplePayCard","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isApplePayCard","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpcard\/isapplepaycard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/isApplePayCard","abstract":[{"type":"text","text":"Whether or not the card originated from Apple Pay."}],"navigatorTitle":[{"text":"isApplePayCard","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/funding(from:)":{"type":"topic","kind":"symbol","title":"funding(from:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"funding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"STPCardFundingType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"}],"url":"\/documentation\/stripepayments\/stpcard\/funding(from:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding(from:)","navigatorTitle":[{"text":"fundingFromString:","kind":"identifier"}],"abstract":[{"type":"text","text":"This parses a string representing a card’s funding type into the appropriate"},{"type":"text","text":" "},{"code":"STPCardFundingType","type":"codeVoice"},{"type":"text","text":" enum value,"},{"type":"text","text":" "},{"type":"text","text":"i.e. "},{"code":"STPCard.funding(from string:\"prepaid\") == .prepaid","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/expYear":{"title":"expYear","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expYear","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpcard\/expyear","navigatorTitle":[{"text":"expYear","kind":"identifier"}],"abstract":[{"text":"The card’s expiration year.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/expYear","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/cardId":{"url":"\/documentation\/stripepayments\/stpcard\/cardid","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"cardId","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/cardId","navigatorTitle":[{"text":"cardId","kind":"identifier"}],"abstract":[{"text":"The Stripe ID for the card.","type":"text"}],"deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/description","role":"symbol","title":"description","abstract":[{"text":":nodoc:","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/stripepayments\/stpcard\/description","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/currency":{"abstract":[{"text":"This is only applicable when tokenizing debit cards to issue payouts to managed","type":"text"},{"text":" ","type":"text"},{"text":"accounts. You should not set it otherwise. The card can then be used as a","type":"text"},{"text":" ","type":"text"},{"text":"transfer destination for funds in this currency.","type":"text"}],"role":"symbol","title":"currency","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcard\/currency","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/currency"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceProtocol","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSourceProtocol","kind":"identifier"}],"title":"STPSourceProtocol","abstract":[{"text":"Objects conforming to this protocol can be attached to a Stripe Customer object","type":"text"},{"text":" ","type":"text"},{"text":"as a payment source.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceprotocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/metadata":{"deprecated":true,"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/metadata","abstract":[{"type":"text","text":"A set of key\/value pairs associated with the card object."}],"url":"\/documentation\/stripepayments\/stpcard\/metadata","title":"metadata","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"metadata"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/expMonth":{"title":"expMonth","role":"symbol","abstract":[{"type":"text","text":"The card’s expiration month. 1-indexed (i.e. 1 == January)"}],"kind":"symbol","navigatorTitle":[{"text":"expMonth","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcard\/expmonth","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/expMonth","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expMonth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/addressCountry":{"url":"\/documentation\/stripepayments\/stpcard\/addresscountry","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressCountry","title":"addressCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"text":"The country of the cardholder’s address","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"addressCountry"}],"deprecated":true,"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPCard","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPCard","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"STPCard","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/address","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressCity","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressCountry","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressLine1","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressLine2","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressState","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressZip","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/brand","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/cardId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/dynamicLast4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/expMonth","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/expYear","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/isApplePayCard","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/stripeID"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/init(id:brand:last4:expMonth:expYear:funding:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/isEqual(_:)"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/brand(from:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/decodedObject(fromAPIResponse:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding(from:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/string(from:)"],"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"],"type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCard"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPCard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/title"},{"value":[{"text":"STPCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/fragments"},{"value":[{"text":"STPCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/navigatorTitle"},{"value":"addressCity","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressCity\/title"},{"value":[{"kind":"identifier","text":"addressCity"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressCity\/fragments"},{"value":"allResponseFields","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1allResponseFields\/title"},{"value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1allResponseFields\/fragments"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1name\/title"},{"value":[{"kind":"identifier","text":"name"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1name\/fragments"},{"value":"last4","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1last4\/title"},{"value":[{"kind":"identifier","text":"last4"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1last4\/fragments"},{"value":"funding","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1funding\/title"},{"value":[{"text":"funding","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1funding\/fragments"},{"value":"stripeID","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1stripeID\/title"},{"value":[{"text":"stripeID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1stripeID\/fragments"},{"value":"address","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1address\/title"},{"value":[{"text":"address","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1address\/fragments"},{"value":"initWithID:brand:last4:expMonth:expYear:funding:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1init(id:brand:last4:expMonth:expYear:funding:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithID:brand:last4:expMonth:expYear:funding:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1init(id:brand:last4:expMonth:expYear:funding:)\/fragments"},{"value":"addressLine2","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressLine2\/title"},{"value":[{"kind":"identifier","text":"addressLine2"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressLine2\/fragments"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1decodedObject(fromAPIResponse:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1decodedObject(fromAPIResponse:)\/fragments"},{"value":"brandFromString:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1brand(from:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"brandFromString:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1brand(from:)\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1isEqual(_:)\/fragments"},{"value":"country","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1country\/title"},{"value":[{"text":"country","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1country\/fragments"},{"value":"addressLine1","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressLine1\/title"},{"value":[{"text":"addressLine1","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressLine1\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1hash\/fragments"},{"value":"addressZip","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressZip\/title"},{"value":[{"text":"addressZip","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressZip\/fragments"},{"value":"brand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1brand\/title"},{"value":[{"kind":"identifier","text":"brand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1brand\/fragments"},{"value":"stringFromBrand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1string(from:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"stringFromBrand:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1string(from:)\/fragments"},{"value":"STPAPIResponseDecodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"value":"addressState","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressState\/title"},{"value":[{"text":"addressState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressState\/fragments"},{"value":"dynamicLast4","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1dynamicLast4\/title"},{"value":[{"text":"dynamicLast4","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1dynamicLast4\/fragments"},{"value":"isApplePayCard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1isApplePayCard\/title"},{"value":[{"text":"isApplePayCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1isApplePayCard\/fragments"},{"value":"fundingFromString:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1funding(from:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fundingFromString:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1funding(from:)\/fragments"},{"value":"expYear","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1expYear\/title"},{"value":[{"text":"expYear","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1expYear\/fragments"},{"value":"cardId","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1cardId\/title"},{"value":[{"text":"cardId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1cardId\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1description\/fragments"},{"value":"currency","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1currency\/title"},{"value":[{"text":"currency","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1currency\/fragments"},{"value":"STPSourceProtocol","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/title"},{"value":[{"kind":"identifier","text":"STPSourceProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/navigatorTitle"},{"value":"metadata","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1metadata\/title"},{"value":[{"kind":"identifier","text":"metadata"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1metadata\/fragments"},{"value":"expMonth","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1expMonth\/title"},{"value":[{"text":"expMonth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1expMonth\/fragments"},{"value":"addressCountry","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressCountry\/title"},{"value":[{"text":"addressCountry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressCountry\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}