{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardvalidationstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardvalidationstate"]}],"metadata":{"title":"STPCardValidationState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardValidationState","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"text":"STPCardValidationState","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPCardValidationState"},"sections":[],"abstract":[{"text":"These fields indicate whether a card field represents a valid value, invalid","type":"text"},{"text":" ","type":"text"},{"text":"value, or incomplete value.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/incomplete","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/invalid","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/valid"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s15BitwiseCopyableP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY","doc:\/\/com.stripe.stripe-payments\/s8SendableP"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@frozen","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardValidationState","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/incomplete":{"url":"\/documentation\/stripepayments\/stpcardvalidationstate\/incomplete","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incomplete","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/incomplete","kind":"symbol","abstract":[{"type":"text","text":"The field’s contents are not currently valid, but could be by typing"},{"type":"text","text":" "},{"type":"text","text":"additional characters. For example, a CVC of “1”."}],"title":"STPCardValidationState.incomplete","role":"symbol","navigatorTitle":[{"text":"STPCardValidationStateIncomplete","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState":{"abstract":[{"type":"text","text":"These fields indicate whether a card field represents a valid value, invalid"},{"type":"text","text":" "},{"type":"text","text":"value, or incomplete value."}],"kind":"symbol","type":"topic","title":"STPCardValidationState","role":"symbol","navigatorTitle":[{"text":"STPCardValidationState","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcardvalidationstate","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardValidationState","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/valid":{"kind":"symbol","type":"topic","abstract":[{"text":"The field’s contents are valid. For example, a valid, 16-digit card number.","type":"text"},{"text":" ","type":"text"},{"text":"Note that valid values may not be complete. For example: a US Zip code can","type":"text"},{"text":" ","type":"text"},{"text":"be 5 or 9 digits. A 5-digit code is Valid, but more text could be entered","type":"text"},{"text":" ","type":"text"},{"text":"to transition to incomplete again. American Express CVC codes can be 3 or","type":"text"},{"text":" ","type":"text"},{"text":"4 digits and both will be treated as Valid.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"valid","kind":"identifier"}],"title":"STPCardValidationState.valid","navigatorTitle":[{"text":"STPCardValidationStateValid","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/valid","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidationstate\/valid"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpcardvalidationstate\/rawrepresentable-implementations","kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/Equatable-Implementations","role":"collectionGroup","kind":"article","title":"Equatable Implementations","url":"\/documentation\/stripepayments\/stpcardvalidationstate\/equatable-implementations","abstract":[]},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/init(rawValue:)","url":"\/documentation\/stripepayments\/stpcardvalidationstate\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","title":"init(rawValue:)"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidationState/invalid":{"type":"topic","abstract":[{"type":"text","text":"The field’s contents are invalid. For example, an expiration date"},{"type":"text","text":" "},{"type":"text","text":"of “13\/42”."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalid"}],"url":"\/documentation\/stripepayments\/stpcardvalidationstate\/invalid","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/invalid","title":"STPCardValidationState.invalid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardValidationStateInvalid"}]},"doc://com.stripe.stripe-payments/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s15BitwiseCopyableP"},"doc://com.stripe.stripe-payments/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8SendableP","title":"Swift.Sendable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPCardValidationState","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardValidationState"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"STPCardValidationState","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/incomplete","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/invalid","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidationState\/valid"],"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardValidationState"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPCardValidationStateIncomplete","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1incomplete\/title"},{"op":"replace","value":[{"text":"STPCardValidationStateIncomplete","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1incomplete\/fragments"},{"op":"replace","value":"STPCardValidationState","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/title"},{"op":"replace","value":[{"text":"STPCardValidationState","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardValidationState"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState\/navigatorTitle"},{"op":"replace","value":"STPCardValidationStateValid","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1valid\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardValidationStateValid"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1valid\/fragments"},{"op":"replace","value":"STPCardValidationStateInvalid","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1invalid\/title"},{"op":"replace","value":[{"text":"STPCardValidationStateInvalid","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidationState~1invalid\/fragments"}]}]}