{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/s9EscapableP","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountAddress","kind":"identifier"}],"languages":["swift"]}]}],"abstract":[{"text":"An address to use with ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountParams"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"STPConnectAccountAddress","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","title":"STPConnectAccountAddress","modules":[{"name":"StripePayments"}],"symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountAddress","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/city","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/line1","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/line2","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/postalCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/state","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/town"],"title":"Instance Properties","generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/STPFormEncodable-Implementations"],"title":"Default Implementations","generated":true}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/description","type":"topic","kind":"symbol","title":"description","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/description","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/line2":{"navigatorTitle":[{"text":"line2","kind":"identifier"}],"title":"line2","abstract":[{"type":"text","text":"Address line 2 (e.g., apartment, suite, unit, or building)."},{"type":"text","text":" "},{"type":"text","text":"For addresses in Japan: Building details."}],"url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/line2","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/line2","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"line2","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/line1":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/line1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"line1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/line1","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"line1"}],"title":"line1","role":"symbol","abstract":[{"text":"Address line 1 (e.g., street, PO Box, or company name).","type":"text"},{"text":" ","type":"text"},{"text":"For addresses in Japan: Block or building number.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"role":"symbol","kind":"symbol","title":"STPFormEncodable","navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpformencodable","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","abstract":[{"type":"text","text":"An address to use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountAddress","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPConnectAccountAddress","kind":"identifier"}],"title":"STPConnectAccountAddress","url":"\/documentation\/stripepayments\/stpconnectaccountaddress","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/init","type":"topic","kind":"symbol","title":"init","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/init","role":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/town":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/town","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"town"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/town","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"town"}],"title":"town","role":"symbol","abstract":[{"text":"Town or cho-me.","type":"text"},{"text":" ","type":"text"},{"text":"This property only applies to Japanese addresses.","type":"text"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/city":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/city","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"city"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/city","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"city"}],"title":"city","role":"symbol","abstract":[{"text":"City, district, suburb, town, or village.","type":"text"},{"text":" ","type":"text"},{"text":"For addresses in Japan: City or ward.","type":"text"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/additionalAPIParameters":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/additionalAPIParameters","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/additionalapiparameters","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"title":"additionalAPIParameters","role":"symbol","abstract":[{"text":":nodoc:","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/postalCode":{"navigatorTitle":[{"kind":"identifier","text":"postalCode"}],"title":"postalCode","abstract":[{"text":"ZIP or postal code.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/postalcode","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/postalCode","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/state":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/state","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/state","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"state"}],"title":"state","role":"symbol","abstract":[{"text":"State, county, province, or region.","type":"text"},{"text":" ","type":"text"},{"text":"For addresses in Japan: Prefecture.","type":"text"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/s9EscapableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s9EscapableP","title":"Swift.Escapable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/STPFormEncodable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/STPFormEncodable-Implementations","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/stpformencodable-implementations","kind":"article","title":"STPFormEncodable Implementations","role":"collectionGroup","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress/country":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/country","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"country"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountaddress\/country","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"country"}],"title":"country","role":"symbol","abstract":[{"text":"Two-letter country code (ISO 3166-1 alpha-2).","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPConnectAccountAddress"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPConnectAccountAddress","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPConnectAccountAddress","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/city","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/line1","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/line2","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/postalCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/state","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/town"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/init"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress\/STPFormEncodable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountAddress","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1line2\/title","value":"line2"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1line2\/fragments","value":[{"text":"line2","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1line1\/title","value":"line1"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1line1\/fragments","value":[{"text":"line1","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","value":"STPFormEncodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/title","value":"STPConnectAccountAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/fragments","value":[{"text":"STPConnectAccountAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/navigatorTitle","value":[{"text":"STPConnectAccountAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1town\/title","value":"town"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1town\/fragments","value":[{"text":"town","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1city\/title","value":"city"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1city\/fragments","value":[{"text":"city","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1additionalAPIParameters\/title","value":"additionalAPIParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1additionalAPIParameters\/fragments","value":[{"text":"additionalAPIParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1postalCode\/title","value":"postalCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1postalCode\/fragments","value":[{"text":"postalCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1state\/title","value":"state"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1state\/fragments","value":[{"text":"state","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1country\/title","value":"country"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress~1country\/fragments","value":[{"text":"country","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}