{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtokenclientcontext"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPConfirmationTokenClientContext","fragments":[{"kind":"identifier","text":"STPConfirmationTokenClientContext"}],"navigatorTitle":[{"kind":"identifier","text":"STPConfirmationTokenClientContext"}],"roleHeading":"Class","title":"STPConfirmationTokenClientContext"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/captureMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/customer","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/mode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/onBehalfOf","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/paymentMethodConfiguration","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/paymentMethodOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/paymentMethodTypes","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/setupFutureUsage"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/init"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/propertyNamesToFormFieldNamesMapping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/rootObjectName"],"generated":true,"anchor":"Type-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmationTokenClientContext"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}],"abstract":[{"text":"Client context for a ConfirmationToken, containing information about the payment flow context.","type":"text"},{"text":" ","type":"text"},{"text":"Only includes properties that can be populated from PaymentSheet.IntentConfiguration.","type":"text"},{"text":" ","type":"text"},{"text":"seealso:","type":"text"},{"text":" ","type":"text"},{"text":"https:\/\/stripe.com\/docs\/api\/confirmation_tokens","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/customer":{"abstract":[{"text":"Customer ID","type":"text"}],"type":"topic","title":"customer","role":"symbol","fragments":[{"text":"customer","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/customer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/customer","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/rootObjectName":{"title":"rootObjectName","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/rootobjectname","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/rootObjectName","kind":"symbol","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext":{"role":"symbol","title":"STPConfirmationTokenClientContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Client context for a ConfirmationToken, containing information about the payment flow context."},{"type":"text","text":" "},{"type":"text","text":"Only includes properties that can be populated from PaymentSheet.IntentConfiguration."},{"type":"text","text":" "},{"type":"text","text":"seealso:"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/stripe.com\/docs\/api\/confirmation_tokens"}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext","fragments":[{"text":"STPConfirmationTokenClientContext","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/paymentMethodOptions":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/paymentMethodOptions","role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/paymentmethodoptions","type":"topic","fragments":[{"kind":"identifier","text":"paymentMethodOptions"}],"abstract":[{"type":"text","text":"Payment method specific options as a dictionary"}],"title":"paymentMethodOptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/additionalAPIParameters":{"title":"additionalAPIParameters","fragments":[{"kind":"identifier","text":"additionalAPIParameters"}],"type":"topic","abstract":[],"url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/additionalapiparameters","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/additionalAPIParameters","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/description","type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/description","title":"description","role":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"kind":"identifier","text":"description"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/paymentMethodTypes":{"role":"symbol","kind":"symbol","title":"paymentMethodTypes","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/paymentmethodtypes","fragments":[{"text":"paymentMethodTypes","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/paymentMethodTypes","type":"topic","abstract":[{"text":"The payment method types for the intent","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/currency":{"abstract":[{"type":"text","text":"Three-letter ISO currency code"}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/currency","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/currency","title":"currency","type":"topic","fragments":[{"text":"currency","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"init","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/propertyNamesToFormFieldNamesMapping":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/propertyNamesToFormFieldNamesMapping","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/propertynamestoformfieldnamesmapping","title":"propertyNamesToFormFieldNamesMapping"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/onBehalfOf":{"role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/onbehalfof","title":"onBehalfOf","abstract":[{"text":"The account (if any) for which the funds of the intent are intended","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/onBehalfOf","type":"topic","fragments":[{"kind":"identifier","text":"onBehalfOf"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/mode":{"kind":"symbol","abstract":[{"type":"text","text":"The mode of this intent, either “payment” or “setup”"}],"title":"mode","type":"topic","fragments":[{"text":"mode","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/mode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/mode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/setupFutureUsage":{"url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/setupfutureusage","type":"topic","fragments":[{"text":"setupFutureUsage","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/setupFutureUsage","abstract":[{"text":"Indicates how the payment method is intended to be used in the future","type":"text"}],"role":"symbol","kind":"symbol","title":"setupFutureUsage"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/captureMethod":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/capturemethod","abstract":[{"text":"Controls when the funds will be captured (payment mode only)","type":"text"}],"type":"topic","title":"captureMethod","role":"symbol","fragments":[{"kind":"identifier","text":"captureMethod"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/captureMethod"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"url":"\/documentation\/stripepayments\/stpformencodable","type":"topic","title":"STPFormEncodable","abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenClientContext/paymentMethodConfiguration":{"title":"paymentMethodConfiguration","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenClientContext\/paymentMethodConfiguration","kind":"symbol","fragments":[{"text":"paymentMethodConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration ID for the selected payment method configuration"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenclientcontext\/paymentmethodconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","value":"STPFormEncodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","value":[{"kind":"identifier","text":"STPFormEncodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormEncodable"}]}]}]}