{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"This class contains static methods to validate card numbers, expiration dates,","type":"text"},{"text":" ","type":"text"},{"text":"and CVCs. For a list of test card numbers to use with this code,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"see https:\/\/stripe.com\/docs\/testing"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCardValidator","kind":"identifier"}],"title":"STPCardValidator","modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardValidator"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPCardValidator"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/brand(forNumber:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/fragmentLength(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/lengths(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxCVCLength(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxLength(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/possibleBrands(forCard:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/possibleBrands(forNumber:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/sanitizedNumericString(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/sanitizedPostalString(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/stringIsNumeric(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCVC:cardBrand:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCard:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationMonth:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationYear:inMonth:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forNumber:validatingCardBrand:)"],"anchor":"Type-Methods","generated":true}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(STPCardValidator) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCardValidator","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/sanitizedNumericString(for:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/sanitizedNumericString(for:)","title":"sanitizedNumericString(for:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/sanitizednumericstring(for:)","type":"topic","abstract":[{"text":"Returns a copy of the passed string with all non-numeric characters removed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sanitizedNumericStringForString:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sanitizedNumericString","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/maxLength(for:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"maxLength","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"maxLengthForCardBrand:"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"The maximum possible length the number of a card associated with the specified"},{"text":" ","type":"text"},{"text":"brand could be.","type":"text"},{"text":" ","type":"text"},{"text":"For example, Visa cards could be either 13 or 16 characters, so this method","type":"text"},{"type":"text","text":" "},{"text":"would return 16 for the that card brand.","type":"text"}],"url":"\/documentation\/stripepayments\/stpcardvalidator\/maxlength(for:)","title":"maxLength(for:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxLength(for:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/possibleBrands(forNumber:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/possibleBrands(forNumber:completion:)","kind":"symbol","title":"possibleBrands(forNumber:completion:)","url":"\/documentation\/stripepayments\/stpcardvalidator\/possiblebrands(fornumber:completion:)","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"possibleBrands"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"},{"text":">, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":">) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/fragmentLength(for:)":{"abstract":[{"text":"The length of the final grouping of digits to use when formatting a card number","type":"text"},{"type":"text","text":" "},{"text":"for display.","type":"text"},{"type":"text","text":" "},{"text":"For example, Visa cards display their final 4 numbers, e.g. “4242”, while","type":"text"},{"type":"text","text":" "},{"type":"text","text":"American Express cards display their final 5 digits, e.g. “10005”."}],"url":"\/documentation\/stripepayments\/stpcardvalidator\/fragmentlength(for:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"fragmentLengthForCardBrand:","kind":"identifier"}],"title":"fragmentLength(for:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/fragmentLength(for:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fragmentLength"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/maxCVCLength(for:)":{"title":"maxCVCLength(for:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxCVCLength(for:)","type":"topic","abstract":[{"text":"The max CVC length for a card brand (for example, American Express CVCs are","type":"text"},{"type":"text","text":" "},{"type":"text","text":"4 digits, while all others are 3)."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"maxCVCLength","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"kind":"identifier","text":"maxCVCLengthForCardBrand:"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/maxcvclength(for:)","role":"symbol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator":{"navigatorTitle":[{"text":"STPCardValidator","kind":"identifier"}],"type":"topic","kind":"symbol","title":"STPCardValidator","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardValidator"}],"abstract":[{"text":"This class contains static methods to validate card numbers, expiration dates,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and CVCs. For a list of test card numbers to use with this code,"},{"type":"text","text":" "},{"text":"see https:\/\/stripe.com\/docs\/testing","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forExpirationYear:inMonth:)":{"title":"validationState(forExpirationYear:inMonth:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationYear:inMonth:)","type":"topic","abstract":[{"type":"text","text":"Validates an expiration year, passed as a string representing the final"},{"type":"text","text":" "},{"text":"2 digits of the year.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This considers the period between the current year until 2099 as valid times."},{"type":"text","text":" "},{"text":"An example valid year value would be “16” (assuming the current year, as","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"determined by NSDate.date, is 2015)."},{"type":"text","text":" "},{"type":"text","text":"Will return STPCardValidationStateInvalid for a month\/year combination that"},{"type":"text","text":" "},{"type":"text","text":"is earlier than the current date (i.e. @“15” and @“04” in October 2015)."},{"type":"text","text":" "},{"text":"Example invalid year values are “00”, “a”, and “13”. Any 1-digit year string","type":"text"},{"text":" ","type":"text"},{"text":"will return STPCardValidationStateIncomplete.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forExpirationYear"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"inMonth","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"STPCardValidationState","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState"}],"navigatorTitle":[{"text":"validationStateForExpirationYear:inMonth:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forexpirationyear:inmonth:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forCVC:cardBrand:)":{"navigatorTitle":[{"text":"validationStateForCVC:cardBrand:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"validationState(forCVC:cardBrand:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCVC:cardBrand:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationState"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forCVC"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"cardBrand","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","text":"STPCardValidationState","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Validates a card’s CVC, passed as a numeric string, for the given card brand."}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forcvc:cardbrand:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/init":{"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/init","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/sanitizedPostalString(for:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/sanitizedPostalString(for:)","title":"sanitizedPostalString(for:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/sanitizedpostalstring(for:)","type":"topic","abstract":[{"type":"text","text":"Returns a copy of the passed string with all characters removed that do not exist within a postal code."}],"navigatorTitle":[{"text":"sanitizedPostalStringForString:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sanitizedPostalString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forExpirationMonth:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationMonth:)","title":"validationState(forExpirationMonth:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forexpirationmonth:)","type":"topic","abstract":[{"type":"text","text":"Validates an expiration month, passed as an (optionally 0-padded) string."},{"type":"text","text":" "},{"text":"Example valid values are “3”, “12”, and “08”. Example invalid values are “99”,","type":"text"},{"type":"text","text":" "},{"text":"“a”, and “00”. Incomplete values include “0” and “1”.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"validationStateForExpirationMonth:"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forExpirationMonth","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"STPCardValidationState","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/brand(forNumber:)":{"title":"brand(forNumber:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/brand(forNumber:)","type":"topic","abstract":[{"text":"The card brand for a card number or substring thereof.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"}],"navigatorTitle":[{"text":"brandForNumber:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/brand(fornumber:)","role":"symbol"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forNumber:validatingCardBrand:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationState"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"validatingCardBrand","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"STPCardValidationState","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validationStateForNumber:validatingCardBrand:"}],"abstract":[{"type":"text","text":"Validates a card number, passed as a string. This will return"},{"type":"text","text":" "},{"text":"STPCardValidationStateInvalid for numbers that are too short or long, contain","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"invalid characters, do not pass Luhn validation, or (optionally) do not match"},{"text":" ","type":"text"},{"type":"text","text":"a number format issued by a major card brand."}],"kind":"symbol","type":"topic","title":"validationState(forNumber:validatingCardBrand:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forNumber:validatingCardBrand:)","url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(fornumber:validatingcardbrand:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/possibleBrands(forCard:completion:)":{"title":"possibleBrands(forCard:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/possibleBrands(forCard:completion:)","type":"topic","abstract":[{"text":"Returns available brands for the provided card details.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"possibleBrands","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forCard","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO","text":"Result"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":">, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/possiblebrands(forcard:completion:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/stringIsNumeric(_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/stringIsNumeric(_:)","title":"stringIsNumeric(_:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/stringisnumeric(_:)","type":"topic","abstract":[{"type":"text","text":"Whether or not the target string contains only numeric characters."}],"navigatorTitle":[{"text":"stringIsNumeric:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stringIsNumeric","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/validationState(forCard:)":{"title":"validationState(forCard:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCard:)","type":"topic","abstract":[{"type":"text","text":"Validates the given card details."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validationState","kind":"identifier"},{"kind":"text","text":"("},{"text":"forCard","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"STPCardValidationState","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardValidationState"}],"navigatorTitle":[{"kind":"identifier","text":"validationStateForCard:"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/validationstate(forcard:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardValidator/lengths(for:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/lengths(for:)","title":"lengths(for:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardvalidator\/lengths(for:)","type":"topic","abstract":[{"type":"text","text":"The possible number lengths for cards associated with a card brand. For"},{"text":" ","type":"text"},{"type":"text","text":"example, Discover card numbers contain 16 characters, while American Express"},{"text":" ","type":"text"},{"type":"text","text":"cards contain 15 characters."}],"navigatorTitle":[{"text":"lengthsForCardBrand:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lengths"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"kind":"text","text":">"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPCardValidator"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPCardValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/init"],"anchor":"Instance-Methods","generated":true},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/brand(forNumber:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/fragmentLength(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/lengths(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxCVCLength(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/maxLength(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/sanitizedNumericString(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/sanitizedPostalString(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/stringIsNumeric(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCVC:cardBrand:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forCard:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationMonth:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forExpirationYear:inMonth:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardValidator\/validationState(forNumber:validatingCardBrand:)"]}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"STPCardValidator","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1sanitizedNumericString(for:)\/title","value":"sanitizedNumericStringForString:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1sanitizedNumericString(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"sanitizedNumericStringForString:","kind":"identifier"}],"op":"replace"},{"value":"maxLengthForCardBrand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1maxLength(for:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1maxLength(for:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"maxLengthForCardBrand:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1fragmentLength(for:)\/title","value":"fragmentLengthForCardBrand:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1fragmentLength(for:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fragmentLengthForCardBrand:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1maxCVCLength(for:)\/title","op":"replace","value":"maxCVCLengthForCardBrand:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1maxCVCLength(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"maxCVCLengthForCardBrand:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/title","op":"replace","value":"STPCardValidator"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/fragments","value":[{"text":"STPCardValidator","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPCardValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forExpirationYear:inMonth:)\/title","op":"replace","value":"validationStateForExpirationYear:inMonth:"},{"value":[{"text":"+ ","kind":"text"},{"text":"validationStateForExpirationYear:inMonth:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forExpirationYear:inMonth:)\/fragments"},{"op":"replace","value":"validationStateForCVC:cardBrand:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forCVC:cardBrand:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"validationStateForCVC:cardBrand:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forCVC:cardBrand:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1sanitizedPostalString(for:)\/title","value":"sanitizedPostalStringForString:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1sanitizedPostalString(for:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sanitizedPostalStringForString:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forExpirationMonth:)\/title","value":"validationStateForExpirationMonth:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forExpirationMonth:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"validationStateForExpirationMonth:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1brand(forNumber:)\/title","op":"replace","value":"brandForNumber:"},{"value":[{"text":"+ ","kind":"text"},{"text":"brandForNumber:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1brand(forNumber:)\/fragments"},{"value":"validationStateForNumber:validatingCardBrand:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forNumber:validatingCardBrand:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"validationStateForNumber:validatingCardBrand:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forNumber:validatingCardBrand:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1stringIsNumeric(_:)\/title","value":"stringIsNumeric:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1stringIsNumeric(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"stringIsNumeric:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forCard:)\/title","value":"validationStateForCard:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1validationState(forCard:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"validationStateForCard:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1lengths(for:)\/title","op":"replace","value":"lengthsForCardBrand:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardValidator~1lengths(for:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"lengthsForCardBrand:"}]}]}]}