{"sections":[],"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata","interfaceLanguage":"occ"},"metadata":{"roleHeading":"Class","title":"STPClientAttributionMetadata","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPClientAttributionMetadata","modules":[{"name":"StripePayments"}],"symbolKind":"class","fragments":[{"text":"STPClientAttributionMetadata","kind":"identifier"}],"navigatorTitle":[{"text":"STPClientAttributionMetadata","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/clientSessionId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/elementsSessionConfigId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/merchantIntegrationSource","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/merchantIntegrationSubtype","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/merchantIntegrationVersion","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/paymentIntentCreationFlow","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/paymentMethodSelectionFlow"],"generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/propertyNamesToFormFieldNamesMapping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/rootObjectName"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpclientattributionmetadata"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPClientAttributionMetadata"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/clientSessionId":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/clientSessionId","url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/clientsessionid","abstract":[{"type":"text","text":"The identifier string for the session"}],"kind":"symbol","role":"symbol","title":"clientSessionId","type":"topic","fragments":[{"text":"clientSessionId","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/elementsSessionConfigId":{"abstract":[{"type":"text","text":"The identifier string for the elements session"}],"title":"elementsSessionConfigId","role":"symbol","fragments":[{"text":"elementsSessionConfigId","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/elementssessionconfigid","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/elementsSessionConfigId","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/merchantIntegrationSource":{"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/merchantintegrationsource","title":"merchantIntegrationSource","abstract":[{"type":"text","text":"The source for the merchant integration"}],"type":"topic","kind":"symbol","fragments":[{"text":"merchantIntegrationSource","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/merchantIntegrationSource"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/paymentIntentCreationFlow":{"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/paymentintentcreationflow","abstract":[{"text":"The intent creation flow for the merchant integration. Can be ","type":"text"},{"type":"text","text":"standard"},{"type":"text","text":" or "},{"type":"text","text":"deferred"}],"title":"paymentIntentCreationFlow","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/paymentIntentCreationFlow","kind":"symbol","fragments":[{"kind":"identifier","text":"paymentIntentCreationFlow"}],"type":"topic"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/paymentMethodSelectionFlow":{"role":"symbol","title":"paymentMethodSelectionFlow","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/paymentMethodSelectionFlow","abstract":[{"type":"text","text":"The payment method selection for the merchant integration. Can be "},{"text":"automatic","type":"text"},{"text":" or ","type":"text"},{"type":"text","text":"merchant_specified"}],"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/paymentmethodselectionflow","kind":"symbol","fragments":[{"text":"paymentMethodSelectionFlow","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/propertyNamesToFormFieldNamesMapping":{"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/propertynamestoformfieldnamesmapping","abstract":[],"title":"propertyNamesToFormFieldNamesMapping","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/propertyNamesToFormFieldNamesMapping","kind":"symbol","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"title":"STPFormEncodable","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","url":"\/documentation\/stripepayments\/stpformencodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPFormEncodable","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/additionalAPIParameters":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/additionalAPIParameters","abstract":[],"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/additionalapiparameters","title":"additionalAPIParameters","fragments":[{"text":"additionalAPIParameters","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/merchantIntegrationSubtype":{"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/merchantintegrationsubtype","abstract":[{"type":"text","text":"The subtype for the merchant integration"}],"title":"merchantIntegrationSubtype","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/merchantIntegrationSubtype","kind":"symbol","fragments":[{"kind":"identifier","text":"merchantIntegrationSubtype"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata":{"url":"\/documentation\/stripepayments\/stpclientattributionmetadata","title":"STPClientAttributionMetadata","kind":"symbol","fragments":[{"text":"STPClientAttributionMetadata","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/rootObjectName":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/rootObjectName","abstract":[],"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/rootobjectname","title":"rootObjectName","fragments":[{"kind":"text","text":"+ "},{"text":"rootObjectName","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPClientAttributionMetadata/merchantIntegrationVersion":{"url":"\/documentation\/stripepayments\/stpclientattributionmetadata\/merchantintegrationversion","abstract":[{"text":"The version for the merchant integration","type":"text"}],"title":"merchantIntegrationVersion","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPClientAttributionMetadata\/merchantIntegrationVersion","kind":"symbol","fragments":[{"text":"merchantIntegrationVersion","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","value":"STPFormEncodable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","value":[{"kind":"identifier","text":"STPFormEncodable"}]},{"op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}