{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer"},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/init(stripeID:defaultSource:sources:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/defaultSource","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/email","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/shippingAddress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/sources","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/stripeID"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/updateSources(filteringApplePay:)"],"title":"Instance Methods","generated":true},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/STPAPIResponseDecodable-Implementations"],"title":"Default Implementations","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomer","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcustomer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomer"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"type":"text","text":"An "},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" represents a deserialized Customer object from the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to instantiate an "},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" – you should instead use"},{"type":"text","text":" "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":" to manage retrieving and updating a customer."}],"kind":"symbol","metadata":{"symbolKind":"class","title":"STPCustomer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomer","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"STPCustomer","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPCustomer"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/shippingAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/shippingAddress","title":"shippingAddress","type":"topic","role":"symbol","abstract":[{"text":"The customer’s shipping address.","type":"text"}],"navigatorTitle":[{"text":"shippingAddress","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcustomer\/shippingaddress","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer":{"abstract":[{"text":"An ","type":"text"},{"code":"STPCustomer","type":"codeVoice"},{"text":" represents a deserialized Customer object from the Stripe API.","type":"text"},{"text":" ","type":"text"},{"text":"You shouldn’t need to instantiate an ","type":"text"},{"code":"STPCustomer","type":"codeVoice"},{"text":" – you should instead use","type":"text"},{"text":" ","type":"text"},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and updating a customer.","type":"text"}],"title":"STPCustomer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","url":"\/documentation\/stripepayments\/stpcustomer","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomer"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomer"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","title":"STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/sources":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/sources","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","text":"STPSourceProtocol"},{"kind":"text","text":"]"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpcustomer\/sources","navigatorTitle":[{"kind":"identifier","text":"sources"}],"title":"sources","abstract":[{"text":"The available payment sources the customer has (this may be an empty array).","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/stripeID":{"role":"symbol","kind":"symbol","abstract":[{"text":"The Stripe ID of the customer, e.g. ","type":"text"},{"code":"cus_1234","type":"codeVoice"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/stripeID","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripeID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"stripeID","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcustomer\/stripeid","title":"stripeID"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/updateSources(filteringApplePay:)":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcustomer\/updatesources(filteringapplepay:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSources"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filteringApplePay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"title":"updateSources(filteringApplePay:)","navigatorTitle":[{"kind":"identifier","text":"updateSourcesFilteringApplePay:"}],"abstract":[{"type":"text","text":"Replaces the customer’s "},{"type":"codeVoice","code":"sources"},{"type":"text","text":" and "},{"type":"codeVoice","code":"defaultSource"},{"type":"text","text":" based on whether or not"},{"type":"text","text":" "},{"type":"text","text":"they should include Apple Pay sources. More details on documentation for"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext includeApplePaySources"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/updateSources(filteringApplePay:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/STPAPIResponseDecodable-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/STPAPIResponseDecodable-Implementations","role":"collectionGroup","title":"STPAPIResponseDecodable Implementations","url":"\/documentation\/stripepayments\/stpcustomer\/stpapiresponsedecodable-implementations"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/init(stripeID:defaultSource:sources:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpcustomer\/init(stripeid:defaultsource:sources:)","title":"init(stripeID:defaultSource:sources:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"stripeID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"defaultSource","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPSourceProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol"},{"text":"?, ","kind":"text"},{"text":"sources","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"STPSourceProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol"},{"text":"])","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithStripeID:defaultSource:sources:","kind":"identifier"}],"abstract":[{"text":"Initialize a customer object with the provided values.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/init(stripeID:defaultSource:sources:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/defaultSource":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/defaultSource","abstract":[{"type":"text","text":"The default source used to charge the customer."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSource"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceProtocol","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpcustomer\/defaultsource","title":"defaultSource","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultSource"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/allResponseFields":{"kind":"symbol","title":"allResponseFields","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"url":"\/documentation\/stripepayments\/stpcustomer\/allresponsefields","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/allResponseFields","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/email":{"role":"symbol","abstract":[{"text":"The customer’s email address.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/email","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"email"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"email"}],"url":"\/documentation\/stripepayments\/stpcustomer\/email","title":"email"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/description":{"title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/description","url":"\/documentation\/stripepayments\/stpcustomer\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPCustomer","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPCustomer"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"STPCustomer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/defaultSource","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/email","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/shippingAddress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/sources","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/stripeID"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/init(stripeID:defaultSource:sources:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/updateSources(filteringApplePay:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/STPAPIResponseDecodable-Implementations"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"title":"Conforms To"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"shippingAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1shippingAddress\/title"},{"op":"replace","value":[{"text":"shippingAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1shippingAddress\/fragments"},{"op":"replace","value":"STPCustomer","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCustomer"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/fragments"},{"op":"replace","value":[{"text":"STPCustomer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/navigatorTitle"},{"op":"replace","value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"op":"replace","value":"sources","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1sources\/title"},{"op":"replace","value":[{"text":"sources","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1sources\/fragments"},{"op":"replace","value":"stripeID","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1stripeID\/title"},{"op":"replace","value":[{"text":"stripeID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1stripeID\/fragments"},{"op":"replace","value":"updateSourcesFilteringApplePay:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1updateSources(filteringApplePay:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateSourcesFilteringApplePay:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1updateSources(filteringApplePay:)\/fragments"},{"op":"replace","value":"initWithStripeID:defaultSource:sources:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1init(stripeID:defaultSource:sources:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithStripeID:defaultSource:sources:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1init(stripeID:defaultSource:sources:)\/fragments"},{"op":"replace","value":"defaultSource","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1defaultSource\/title"},{"op":"replace","value":[{"text":"defaultSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1defaultSource\/fragments"},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1allResponseFields\/title"},{"op":"replace","value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1allResponseFields\/fragments"},{"op":"replace","value":"email","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1email\/title"},{"op":"replace","value":[{"kind":"identifier","text":"email"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1email\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1description\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}