{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"STPCustomerCompletionBlock","kind":"identifier"},{"kind":"text","text":" = ("},{"text":"STPCustomer","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCustomer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"customer","content":[{"type":"paragraph","inlineContent":[{"text":"The Stripe customer from the response, or nil if an error occurred. - seealso: STPCustomer","type":"text"}]}]},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"The error returned from the response, or nil if none occurs."}],"type":"paragraph"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerCompletionBlock"},"metadata":{"navigatorTitle":[{"text":"STPCustomerCompletionBlock","kind":"identifier"}],"externalID":"s:14StripePayments26STPCustomerCompletionBlocka","symbolKind":"typealias","title":"STPCustomerCompletionBlock","roleHeading":"Type Alias","modules":[{"name":"StripePayments"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCustomerCompletionBlock"}],"role":"symbol"},"sections":[],"abstract":[{"text":"A callback to be run with a customer response from the Stripe API.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpcustomercompletionblock"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerCompletionBlock":{"navigatorTitle":[{"text":"STPCustomerCompletionBlock","kind":"identifier"}],"type":"topic","title":"STPCustomerCompletionBlock","abstract":[{"type":"text","text":"A callback to be run with a customer response from the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerCompletionBlock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCustomerCompletionBlock","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcustomercompletionblock"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer":{"url":"\/documentation\/stripepayments\/stpcustomer","navigatorTitle":[{"text":"STPCustomer","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","kind":"symbol","title":"STPCustomer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCustomer","kind":"identifier"}],"abstract":[{"text":"An ","type":"text"},{"code":"STPCustomer","type":"codeVoice"},{"text":" represents a deserialized Customer object from the Stripe API.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to instantiate an "},{"code":"STPCustomer","type":"codeVoice"},{"text":" – you should instead use","type":"text"},{"type":"text","text":" "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":" to manage retrieving and updating a customer."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPCustomer","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/title"},{"value":[{"text":"STPCustomer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/fragments"},{"value":[{"text":"STPCustomer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/navigatorTitle","op":"replace"}]}]}