{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions"},"abstract":[{"type":"text","text":"Options to update a Link PaymentMethod during PaymentIntent confirmation."}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"STPConfirmLinkOptions"}],"title":"STPConfirmLinkOptions","modules":[{"name":"StripePayments"}],"symbolKind":"class","fragments":[{"text":"STPConfirmLinkOptions","kind":"identifier"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPConfirmLinkOptions"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/setupFutureUsage"],"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/init"],"generated":true},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/propertyNamesToFormFieldNamesMapping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/rootObjectName"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConfirmLinkOptions"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmlinkoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmLinkOptions/rootObjectName":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/rootObjectName","type":"topic","abstract":[],"navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"title":"rootObjectName","fragments":[{"kind":"text","text":"+ "},{"text":"rootObjectName","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmlinkoptions\/rootobjectname","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmLinkOptions":{"abstract":[{"type":"text","text":"Options to update a Link PaymentMethod during PaymentIntent confirmation."}],"type":"topic","fragments":[{"kind":"identifier","text":"STPConfirmLinkOptions"}],"title":"STPConfirmLinkOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmlinkoptions","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"title":"STPFormEncodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpformencodable","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmLinkOptions/init":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmlinkoptions\/init","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmLinkOptions/propertyNamesToFormFieldNamesMapping":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/propertyNamesToFormFieldNamesMapping","type":"topic","abstract":[],"navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"title":"propertyNamesToFormFieldNamesMapping","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmlinkoptions\/propertynamestoformfieldnamesmapping","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmLinkOptions/setupFutureUsage":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/setupFutureUsage","fragments":[{"kind":"identifier","text":"setupFutureUsage"}],"abstract":[{"type":"text","text":"Indicates that you intend to make future payments with this payment method."},{"text":" ","type":"text"},{"type":"text","text":"Providing this parameter will attach the payment method to the PaymentIntent’s Customer, if present, after the Intent is confirmed and any required actions from the user are complete. If no Customer was provided, the payment method can still be attached to a Customer after the transaction completes."},{"type":"text","text":" "},{"type":"text","text":"If setup_future_usage is already set, you may only update the value from on_session to off_session."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmlinkoptions\/setupfutureusage","type":"topic","title":"setupFutureUsage"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmLinkOptions/additionalAPIParameters":{"url":"\/documentation\/stripepayments\/stpconfirmlinkoptions\/additionalapiparameters","kind":"symbol","role":"symbol","title":"additionalAPIParameters","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions\/additionalAPIParameters","fragments":[{"kind":"identifier","text":"additionalAPIParameters"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","op":"replace","value":"STPFormEncodable"},{"value":[{"text":"STPFormEncodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","op":"replace"}]}]}