{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"title":"STPContactField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPContactField","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"STPContactField"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPContactField","roleHeading":"Class","role":"symbol"},"abstract":[{"type":"text","text":"Contains constants that represent different parts of a users contact\/address information."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcontactfield"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcontactfield"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField"},"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/rawValue"],"title":"Instance Properties"},{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/emailAddress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/phoneNumber","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/postalAddress"],"title":"Type Properties"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPContactField"}],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/postalAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/postalAddress","type":"topic","kind":"symbol","abstract":[{"text":"The contact’s full physical address.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"postalAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField","kind":"typeIdentifier","text":"STPContactField"}],"navigatorTitle":[{"kind":"identifier","text":"postalAddress"}],"role":"symbol","title":"postalAddress","url":"\/documentation\/stripepayments\/stpcontactfield\/postaladdress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/rawValue":{"title":"rawValue","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/rawValue","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpcontactfield\/rawvalue","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField":{"title":"STPContactField","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField","abstract":[{"type":"text","text":"Contains constants that represent different parts of a users contact\/address information."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPContactField","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcontactfield","type":"topic","navigatorTitle":[{"text":"STPContactField","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/init(rawValue:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/init(rawValue:)","url":"\/documentation\/stripepayments\/stpcontactfield\/init(rawvalue:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/name":{"url":"\/documentation\/stripepayments\/stpcontactfield\/name","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPContactField","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/name","kind":"symbol","title":"name","abstract":[{"text":"The contact’s name.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"name"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/emailAddress":{"kind":"symbol","abstract":[{"type":"text","text":"The contact’s email address"}],"role":"symbol","navigatorTitle":[{"text":"emailAddress","kind":"identifier"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"emailAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPContactField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}],"url":"\/documentation\/stripepayments\/stpcontactfield\/emailaddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/emailAddress","title":"emailAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPContactField/phoneNumber":{"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcontactfield\/phonenumber","navigatorTitle":[{"text":"phoneNumber","kind":"identifier"}],"title":"phoneNumber","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phoneNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPContactField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPContactField"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/phoneNumber","abstract":[{"text":"The contact’s phone number.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"STPContactField","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPContactField","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPContactField"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/emailAddress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/phoneNumber","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPContactField\/postalAddress"],"anchor":"Type-Properties","title":"Type Properties","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPContactField"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1postalAddress\/title","value":"postalAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1postalAddress\/fragments","value":[{"text":"postalAddress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/title","value":"STPContactField","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/fragments","value":[{"kind":"identifier","text":"STPContactField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField\/navigatorTitle","value":[{"kind":"identifier","text":"STPContactField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1name\/title","value":"name","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1name\/fragments","value":[{"kind":"identifier","text":"name"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1emailAddress\/title","value":"emailAddress","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1emailAddress\/fragments","value":[{"text":"emailAddress","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1phoneNumber\/title","value":"phoneNumber","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPContactField~1phoneNumber\/fragments","value":[{"text":"phoneNumber","kind":"identifier"}],"op":"replace"}]}]}