{"kind":"symbol","abstract":[{"text":"The business type of the Connect account.","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountbusinesstype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountbusinesstype"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"metadata":{"symbolKind":"enum","externalID":"c:@M@StripePayments@E@STPConnectAccountBusinessType","roleHeading":"Enumeration","navigatorTitle":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePayments"}],"title":"STPConnectAccountBusinessType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/company","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/individual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/none"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/RawRepresentable-Implementations"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/none":{"url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/none","kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPConnectAccountBusinessTypeNone","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/none","title":"STPConnectAccountBusinessType.none","abstract":[{"text":"No value was provided.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType":{"abstract":[{"type":"text","text":"The business type of the Connect account."}],"title":"STPConnectAccountBusinessType","navigatorTitle":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountBusinessType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/init(rawValue:)","title":"init(rawValue:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/individual":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/individual","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/individual","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountBusinessTypeIndividual"}],"kind":"symbol","abstract":[{"text":"This Connect account represents an individual.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"individual"}],"title":"STPConnectAccountBusinessType.individual"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/company":{"role":"symbol","abstract":[{"text":"This Connect account represents a company.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"company","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/company","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/company","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountBusinessTypeCompany"}],"title":"STPConnectAccountBusinessType.company"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/Equatable-Implementations":{"kind":"article","type":"topic","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/Equatable-Implementations","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/equatable-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/CustomStringConvertible-Implementations":{"abstract":[],"title":"CustomStringConvertible Implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/CustomStringConvertible-Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/customstringconvertible-implementations"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountBusinessType/RawRepresentable-Implementations":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpconnectaccountbusinesstype\/rawrepresentable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPConnectAccountBusinessType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}]},{"value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/company","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/individual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountBusinessType\/none"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConnectAccountBusinessType"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPConnectAccountBusinessTypeNone","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1none\/title"},{"op":"replace","value":[{"text":"STPConnectAccountBusinessTypeNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1none\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/title","value":"STPConnectAccountBusinessType","op":"replace"},{"value":[{"text":"STPConnectAccountBusinessType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType\/navigatorTitle","value":[{"kind":"identifier","text":"STPConnectAccountBusinessType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1individual\/title","value":"STPConnectAccountBusinessTypeIndividual","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountBusinessTypeIndividual"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1individual\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1company\/title","value":"STPConnectAccountBusinessTypeCompany"},{"value":[{"text":"STPConnectAccountBusinessTypeCompany","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountBusinessType~1company\/fragments"}]}]}