{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmationTokenParams"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtokenparams"]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/clientAttributionMetadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/mandateData","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/paymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/paymentMethodData","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/paymentMethodOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/returnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/setAsDefaultPM","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/setupFutureUsage","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/shipping"],"generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/init"],"title":"Instance Methods","generated":true},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/propertyNamesToFormFieldNamesMapping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/rootObjectName"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams","interfaceLanguage":"occ"},"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"STPConfirmationTokenParams"}],"roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPConfirmationTokenParams","fragments":[{"text":"STPConfirmationTokenParams","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","title":"STPConfirmationTokenParams"},"abstract":[{"text":"An object representing parameters used to create a ConfirmationToken object.","type":"text"},{"type":"text","text":" "},{"text":"seealso:","type":"text"},{"type":"text","text":" "},{"text":"https:\/\/stripe.com\/docs\/api\/confirmation_tokens","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/propertyNamesToFormFieldNamesMapping":{"navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"title":"propertyNamesToFormFieldNamesMapping","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/propertynamestoformfieldnamesmapping","type":"topic","role":"symbol","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/propertyNamesToFormFieldNamesMapping"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/mandateData":{"role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/mandatedata","abstract":[{"type":"text","text":"Details about the Mandate to create."}],"type":"topic","fragments":[{"text":"mandateData","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/mandateData","title":"mandateData"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/setAsDefaultPM":{"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/setasdefaultpm","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/setAsDefaultPM","kind":"symbol","fragments":[{"text":"setAsDefaultPM","kind":"identifier"}],"title":"setAsDefaultPM","abstract":[{"text":"@YES","type":"text"},{"text":" to set this ConfirmationToken’s PaymentMethod as the associated Customer’s default","type":"text"},{"type":"text","text":" "},{"text":"This should be a boolean NSNumber, so that it can be ","type":"text"},{"type":"text","text":"nil"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/paymentMethod":{"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/paymentmethod","kind":"symbol","type":"topic","role":"symbol","title":"paymentMethod","fragments":[{"text":"paymentMethod","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/paymentMethod","abstract":[{"type":"text","text":"ID of an existing PaymentMethod to use for this ConfirmationToken."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/init":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/init","title":"init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams":{"role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a ConfirmationToken object."},{"type":"text","text":" "},{"text":"seealso:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"https:\/\/stripe.com\/docs\/api\/confirmation_tokens"}],"title":"STPConfirmationTokenParams","kind":"symbol","fragments":[{"kind":"identifier","text":"STPConfirmationTokenParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/additionalAPIParameters":{"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/additionalapiparameters","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/additionalAPIParameters","kind":"symbol","fragments":[{"kind":"identifier","text":"additionalAPIParameters"}],"title":"additionalAPIParameters","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/clientAttributionMetadata":{"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/clientattributionmetadata","kind":"symbol","type":"topic","role":"symbol","title":"clientAttributionMetadata","fragments":[{"text":"clientAttributionMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/clientAttributionMetadata","abstract":[{"type":"text","text":"Contains metadata with identifiers for the session and information about the integration"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/description","abstract":[{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/description","role":"symbol","fragments":[{"text":"description","kind":"identifier"}],"type":"topic","title":"description","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"url":"\/documentation\/stripepayments\/stpformencodable","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","title":"STPFormEncodable","abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/rootObjectName":{"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/rootobjectname","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"title":"rootObjectName","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/rootObjectName","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/shipping":{"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/shipping","kind":"symbol","type":"topic","role":"symbol","title":"shipping","fragments":[{"text":"shipping","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/shipping","abstract":[{"type":"text","text":"Shipping information to include with the ConfirmationToken."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/paymentMethodData":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/paymentMethodData","abstract":[{"type":"text","text":"Payment method details for the ConfirmationToken."}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/paymentmethoddata","role":"symbol","fragments":[{"text":"paymentMethodData","kind":"identifier"}],"type":"topic","title":"paymentMethodData","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/returnURL":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/returnURL","abstract":[{"text":"Return URL to redirect the customer back to your application after completion of 3D Secure authentication.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/returnurl","role":"symbol","fragments":[{"kind":"identifier","text":"returnURL"}],"type":"topic","title":"returnURL","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/paymentMethodOptions":{"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/paymentmethodoptions","kind":"symbol","type":"topic","role":"symbol","title":"paymentMethodOptions","fragments":[{"text":"paymentMethodOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/paymentMethodOptions","abstract":[{"type":"text","text":"Payment-method-specific configuration for this ConfirmationToken."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationTokenParams/setupFutureUsage":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationTokenParams\/setupFutureUsage","abstract":[{"type":"text","text":"Indicates that you intend to make future payments with the payment method collected during checkout."}],"url":"\/documentation\/stripepayments\/stpconfirmationtokenparams\/setupfutureusage","role":"symbol","fragments":[{"text":"setupFutureUsage","kind":"identifier"}],"type":"topic","title":"setupFutureUsage","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPFormEncodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"value":[{"kind":"identifier","text":"STPFormEncodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormEncodable"}]}]}]}