{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"title":"STPCollectBankAccountParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams","symbolKind":"class","roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams"},"kind":"symbol","abstract":[{"text":"Parameters to use with ","type":"text"},{"type":"codeVoice","code":"STPBankAccountCollector"},{"text":" to collect bank account details for payments.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectUSBankAccountParams(with:email:)"],"generated":true,"anchor":"Type-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcollectbankaccountparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcollectbankaccountparams"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams/collectInstantDebitsParamsWithEmail:":{"navigatorTitle":[{"kind":"identifier","text":"collectInstantDebitsParamsWithEmail:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectInstantDebitsParamsWithEmail:","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams\/collectinstantdebitsparamswithemail:","abstract":[{"text":"Configures and returns an instance of ","type":"text"},{"text":"STPCollectBankAccountParams","type":"text"},{"text":" for Instant Debits","type":"text"}],"kind":"symbol","title":"collectInstantDebitsParamsWithEmail:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"collectInstantDebitsParamsWithEmail:"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpcollectbankaccountparams","title":"STPCollectBankAccountParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCollectBankAccountParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Parameters to use with "},{"code":"STPBankAccountCollector","type":"codeVoice"},{"type":"text","text":" to collect bank account details for payments."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountParams/collectUSBankAccountParams(with:email:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectUSBankAccountParams(with:email:)","navigatorTitle":[{"text":"collectUSBankAccountParamsWithName:email:","kind":"identifier"}],"abstract":[{"type":"text","text":"Configures and returns an instance of "},{"type":"codeVoice","code":"STPCollectBankAccountParams"},{"text":" for US Bank Accounts","type":"text"}],"type":"topic","title":"collectUSBankAccountParams(with:email:)","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectUSBankAccountParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"STPCollectBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCollectBankAccountParams"}],"url":"\/documentation\/stripepayments\/stpcollectbankaccountparams\/collectusbankaccountparams(with:email:)"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"STPCollectBankAccountParams","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectInstantDebitsParamsWithEmail:","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountParams\/collectUSBankAccountParams(with:email:)"],"generated":true,"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCollectBankAccountParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPCollectBankAccountParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCollectBankAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/fragments"},{"op":"replace","value":[{"text":"STPCollectBankAccountParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams\/navigatorTitle"},{"op":"replace","value":"collectUSBankAccountParamsWithName:email:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams~1collectUSBankAccountParams(with:email:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"collectUSBankAccountParamsWithName:email:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountParams~1collectUSBankAccountParams(with:email:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}