{"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/s9EscapableP","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(company:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(individual:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:company:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:individual:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/businessType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/company","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/individual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted-17zb6","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted_objc"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/STPFormEncodable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"class","role":"symbol","title":"STPConnectAccountParams","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams","modules":[{"name":"StripePayments"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountParams"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountParams"}]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"aside","style":"note","name":"See Also","content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Tokens\/Create_account","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init(tosShownAndAccepted:company:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:company:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"tosShownAndAccepted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"company","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPConnectAccountCompanyParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams"},{"kind":"text","text":")"}],"title":"init(tosShownAndAccepted:company:)","url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init(tosshownandaccepted:company:)","abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":" with tosShownAndAccepted = YES"},{"type":"text","text":" "},{"type":"text","text":"This method cannot be called with "},{"type":"codeVoice","code":"wasAccepted == NO"},{"type":"text","text":", guarded by a "},{"type":"codeVoice","code":"NSParameterAssert()"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Use this init method if you want to set the "},{"type":"codeVoice","code":"tosShownAndAccepted"},{"type":"text","text":" parameter. If you"},{"type":"text","text":" "},{"type":"text","text":"don’t, use the "},{"type":"codeVoice","code":"initWithCompany:"},{"type":"text","text":" version instead."}],"navigatorTitle":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTosShownAndAccepted:company:"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/individual":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/individual","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"individual"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPConnectAccountIndividualParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams"},{"kind":"text","text":"?"}],"title":"individual","url":"\/documentation\/stripepayments\/stpconnectaccountparams\/individual","abstract":[{"text":"Information about the individual represented by the account.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"individual"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/STPFormEncodable-Implementations":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/stpformencodable-implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/STPFormEncodable-Implementations","role":"collectionGroup","title":"STPFormEncodable Implementations","abstract":[],"type":"topic"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/tosShownAndAccepted-17zb6":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted-17zb6","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tosShownAndAccepted","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}],"title":"tosShownAndAccepted","url":"\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted-17zb6","abstract":[{"type":"text","text":"Boolean indicating that the Terms Of Service were shown to the user &"},{"type":"text","text":" "},{"type":"text","text":"the user accepted them."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"type":"topic","url":"\/documentation\/stripepayments\/stpformencodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"title":"STPFormEncodable","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init(individual:)":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init(individual:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(individual:)","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIndividual:"}],"role":"symbol","title":"init(individual:)","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":" with the provided "},{"type":"codeVoice","code":"individual"},{"type":"text","text":" dictionary."}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"individual"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams","kind":"typeIdentifier","text":"STPConnectAccountIndividualParams"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/description":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/description","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","title":"description","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/businessType":{"abstract":[{"type":"text","text":"The business type."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"businessType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/businessType","kind":"symbol","title":"businessType","url":"\/documentation\/stripepayments\/stpconnectaccountparams\/businesstype","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"businessType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPConnectAccountBusinessType","kind":"typeIdentifier","text":"STPConnectAccountBusinessType"}]},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init(company:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(company:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"company"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams","text":"STPConnectAccountCompanyParams"},{"kind":"text","text":")"}],"title":"init(company:)","url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init(company:)","abstract":[{"text":"Initialize ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":" with the provided ","type":"text"},{"code":"company","type":"codeVoice"},{"type":"text","text":" dictionary."}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithCompany:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init(tosShownAndAccepted:individual:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"tosShownAndAccepted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"individual"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountIndividualParams","kind":"typeIdentifier","text":"STPConnectAccountIndividualParams"},{"kind":"text","text":")"}],"title":"init(tosShownAndAccepted:individual:)","role":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTosShownAndAccepted:individual:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:individual:)","abstract":[{"text":"Initialize ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":" with tosShownAndAccepted = YES","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method cannot be called with "},{"type":"codeVoice","code":"wasAccepted == NO"},{"type":"text","text":", guarded by a "},{"type":"codeVoice","code":"NSParameterAssert()"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Use this init method if you want to set the "},{"type":"codeVoice","code":"tosShownAndAccepted"},{"text":" parameter. If you","type":"text"},{"type":"text","text":" "},{"text":"don’t, use the ","type":"text"},{"code":"initWithIndividual:","type":"codeVoice"},{"text":" version instead.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init(tosshownandaccepted:individual:)","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/additionalAPIParameters":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"title":"additionalAPIParameters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/additionalAPIParameters","abstract":[],"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/additionalapiparameters","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/s9EscapableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s9EscapableP","type":"unresolvable","title":"Swift.Escapable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init()":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init()","kind":"symbol","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","title":"init()","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/tosShownAndAccepted_objc":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/tosshownandaccepted_objc","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted_objc","navigatorTitle":[{"kind":"identifier","text":"tosShownAndAccepted"}],"role":"symbol","title":"tosShownAndAccepted_objc","abstract":[{"type":"text","text":"Boolean indicating that the Terms Of Service were shown to the user &"},{"type":"text","text":" "},{"type":"text","text":"the user accepted them."}],"type":"topic","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tosShownAndAccepted_objc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","kind":"symbol","title":"STPConnectAccountParams","url":"\/documentation\/stripepayments\/stpconnectaccountparams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/company":{"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/company","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/company","navigatorTitle":[{"kind":"identifier","text":"company"}],"role":"symbol","title":"company","abstract":[{"type":"text","text":"Information about the company or business."}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"company"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams","text":"STPConnectAccountCompanyParams"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"STPConnectAccountParams"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPConnectAccountParams"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/businessType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/company","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/individual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/tosShownAndAccepted_objc"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(company:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(individual:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:company:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:individual:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/STPFormEncodable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(tosShownAndAccepted:company:)\/title","value":"initWithTosShownAndAccepted:company:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(tosShownAndAccepted:company:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTosShownAndAccepted:company:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1individual\/title","value":"individual"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1individual\/fragments","value":[{"kind":"identifier","text":"individual"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","op":"replace","value":"STPFormEncodable"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFormEncodable"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(individual:)\/title","op":"replace","value":"initWithIndividual:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(individual:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIndividual:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1businessType\/title","value":"businessType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1businessType\/fragments","value":[{"kind":"identifier","text":"businessType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(company:)\/title","value":"initWithCompany:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(company:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCompany:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(tosShownAndAccepted:individual:)\/title","value":"initWithTosShownAndAccepted:individual:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(tosShownAndAccepted:individual:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTosShownAndAccepted:individual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1additionalAPIParameters\/title","value":"additionalAPIParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1additionalAPIParameters\/fragments","value":[{"text":"additionalAPIParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1tosShownAndAccepted_objc\/title","value":"tosShownAndAccepted"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1tosShownAndAccepted_objc\/fragments","value":[{"kind":"identifier","text":"tosShownAndAccepted"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title","value":"STPConnectAccountParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPConnectAccountParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1company\/title","op":"replace","value":"company"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1company\/fragments","op":"replace","value":[{"text":"company","kind":"identifier"}]}]}]}