{"sections":[],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/expiresAt","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/liveMode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/paymentIntentId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/paymentMethodPreview","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/returnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/setupFutureUsage","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/setupIntentId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/stripeId"],"anchor":"Instance-Properties"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPConfirmationToken","modules":[{"name":"StripePayments"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"title":"STPConfirmationToken"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmationToken"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Confirmation_tokens","type":"text"}]}],"style":"note","name":"See Also"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"type":"text","text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments."}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtoken"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmationtoken"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/paymentIntentId":{"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/paymentintentid","role":"symbol","title":"paymentIntentId","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/paymentIntentId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentIntentId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"ID of the PaymentIntent this token was used to confirm.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/expiresAt":{"abstract":[{"text":"Time at which this ConfirmationToken expires and can no longer be used to confirm a PaymentIntent or SetupIntent.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/expiresAt","type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/expiresat","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expiresAt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","title":"expiresAt","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","kind":"symbol","title":"STPAPIResponseDecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/returnURL":{"role":"symbol","title":"returnURL","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/returnURL","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/returnurl","abstract":[{"type":"text","text":"Return URL used to confirm the intent for redirect-based methods."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/liveMode":{"title":"liveMode","abstract":[{"code":"true","type":"codeVoice"},{"text":" if the object exists in live mode or the value ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" if the object exists in test mode.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/liveMode","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/livemode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"liveMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/stripeId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripeId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/stripeid","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/stripeId","title":"stripeId","role":"symbol","abstract":[{"text":"Unique identifier for the object (e.g. ","type":"text"},{"code":"ctoken_...","type":"codeVoice"},{"text":").","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/setupIntentId":{"abstract":[{"text":"ID of the SetupIntent this token was used to confirm.","type":"text"}],"title":"setupIntentId","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/setupIntentId","type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/setupintentid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupIntentId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtoken","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmationToken","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmationToken","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken","title":"STPConfirmationToken","abstract":[{"text":"ConfirmationToken objects represent your customer’s payment details. They can be used with PaymentIntents and SetupIntents to collect payments.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/allResponseFields":{"abstract":[{"text":":nodoc:","type":"text"}],"title":"allResponseFields","kind":"symbol","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/allResponseFields","type":"topic","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/allresponsefields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/decodedObject(fromAPIResponse:)":{"role":"symbol","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/decodedobject(fromapiresponse:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/decodedObject(fromAPIResponse:)","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"title":"decodedObject(fromAPIResponse:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/created":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"}],"abstract":[{"text":"Time at which the object was created. Measured in seconds since the Unix epoch.","type":"text"}],"title":"created","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/created","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/created","role":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/description":{"abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/description","title":"description","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/shipping":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails","text":"STPPaymentIntentShippingDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/shipping","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/shipping","type":"topic","title":"shipping","abstract":[{"text":"Shipping information collected on this token.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/paymentMethodPreview":{"url":"\/documentation\/stripepayments\/stpconfirmationtoken\/paymentmethodpreview","type":"topic","kind":"symbol","title":"paymentMethodPreview","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/paymentMethodPreview","abstract":[{"text":"Non-PII preview of payment details captured by the Payment Element.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodPreview","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPreview","text":"STPPaymentMethodPreview","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmationToken/setupFutureUsage":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/setupFutureUsage","url":"\/documentation\/stripepayments\/stpconfirmationtoken\/setupfutureusage","type":"topic","title":"setupFutureUsage","abstract":[{"text":"Indicates intent to reuse the payment method.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPConfirmationToken","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPConfirmationToken","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConfirmationToken"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/description"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmationToken\/decodedObject(fromAPIResponse:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmationToken"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"op":"replace","value":"STPConfirmationToken","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/title"},{"op":"replace","value":[{"text":"STPConfirmationToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConfirmationToken"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken\/navigatorTitle"},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken~1allResponseFields\/title"},{"op":"replace","value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken~1allResponseFields\/fragments"},{"op":"replace","value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken~1decodedObject(fromAPIResponse:)\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmationToken~1description\/fragments"}]}]}