{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCustomerDeserializer"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomerdeserializer"]}],"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Use "},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"text":" to convert a response from the Stripe API into an ","type":"text"},{"type":"codeVoice","code":"STPCustomer"},{"text":" object. ","type":"text"},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"type":"text","text":" expects the JSON response to be in the exact same format as the Stripe API."}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(data:urlResponse:error:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(jsonResponse:)"],"title":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/customer","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/error"],"title":"Instance Properties","anchor":"Instance-Properties"}],"metadata":{"roleHeading":"Class","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"class","title":"STPCustomerDeserializer","externalID":"c:@M@StripePayments@objc(cs)STPCustomerDeserializer","navigatorTitle":[{"kind":"identifier","text":"STPCustomerDeserializer"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCustomerDeserializer","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer/init(jsonResponse:)":{"url":"\/documentation\/stripepayments\/stpcustomerdeserializer\/init(jsonresponse:)","title":"init(jsonResponse:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"jsonResponse"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"initWithJsonResponse:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Initializes a customer deserializer with a JSON dictionary. This JSON should be"},{"type":"text","text":" "},{"type":"text","text":"in the exact same format as what the Stripe API returns. If it’s successfully"},{"text":" ","type":"text"},{"type":"text","text":"parsed, the "},{"type":"codeVoice","code":"customer"},{"type":"text","text":" parameter will be present after initialization;"},{"type":"text","text":" "},{"text":"otherwise ","type":"text"},{"type":"codeVoice","code":"error"},{"text":" will be present.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(jsonResponse:)"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer/error":{"abstract":[{"text":"If the deserializer failed to parse a customer, this property will explain why (and the ","type":"text"},{"type":"codeVoice","code":"customer"},{"type":"text","text":" property will be nil)."}],"title":"error","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpcustomerdeserializer\/error","navigatorTitle":[{"kind":"identifier","text":"error"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/error"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Use "},{"code":"STPCustomerDeserializer","type":"codeVoice"},{"type":"text","text":" to convert a response from the Stripe API into an "},{"type":"codeVoice","code":"STPCustomer"},{"type":"text","text":" object. "},{"type":"codeVoice","code":"STPCustomerDeserializer"},{"type":"text","text":" expects the JSON response to be in the exact same format as the Stripe API."}],"title":"STPCustomerDeserializer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCustomerDeserializer","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPCustomerDeserializer"}],"url":"\/documentation\/stripepayments\/stpcustomerdeserializer","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer/init(data:urlResponse:error:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(data:urlResponse:error:)","role":"symbol","url":"\/documentation\/stripepayments\/stpcustomerdeserializer\/init(data:urlresponse:error:)","type":"topic","abstract":[{"text":"Initialize a customer deserializer. The ","type":"text"},{"code":"data","type":"codeVoice"},{"text":", ","type":"text"},{"code":"urlResponse","type":"codeVoice"},{"text":", and ","type":"text"},{"code":"error","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"parameters are intended to be passed from an "},{"code":"NSURLSessionDataTask","type":"codeVoice"},{"type":"text","text":" callback."},{"text":" ","type":"text"},{"type":"text","text":"After it has been initialized, you can inspect the "},{"type":"codeVoice","code":"error"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"customer"},{"text":" ","type":"text"},{"type":"text","text":"properties to see if the deserialization was successful. If "},{"code":"error","type":"codeVoice"},{"type":"text","text":" is nil,"},{"text":" ","type":"text"},{"type":"codeVoice","code":"customer"},{"type":"text","text":" will be non-nil (and vice versa)."}],"title":"init(data:urlResponse:error:)","navigatorTitle":[{"text":"initWithData:urlResponse:error:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"urlResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomerDeserializer/customer":{"title":"customer","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/customer","navigatorTitle":[{"text":"customer","kind":"identifier"}],"abstract":[{"type":"text","text":"If a customer was successfully parsed from the response, it will be set here. Otherwise, this value wil be nil (and the "},{"code":"error","type":"codeVoice"},{"type":"text","text":" property will explain what went wrong)."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"customer"},{"kind":"text","text":": "},{"text":"STPCustomer","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCustomer"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcustomerdeserializer\/customer"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPCustomerDeserializer","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"STPCustomerDeserializer","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPCustomerDeserializer","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/customer","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/error"]},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(data:urlResponse:error:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomerDeserializer\/init(jsonResponse:)"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomerDeserializer"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1init(jsonResponse:)\/title","value":"initWithJsonResponse:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithJsonResponse:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1init(jsonResponse:)\/fragments","op":"replace"},{"value":"error","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1error\/title"},{"value":[{"text":"error","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1error\/fragments","op":"replace"},{"value":"STPCustomerDeserializer","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/fragments","value":[{"kind":"identifier","text":"STPCustomerDeserializer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer\/navigatorTitle","value":[{"text":"STPCustomerDeserializer","kind":"identifier"}]},{"value":"initWithData:urlResponse:error:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1init(data:urlResponse:error:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1init(data:urlResponse:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithData:urlResponse:error:"}],"op":"replace"},{"value":"customer","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1customer\/title"},{"op":"replace","value":[{"text":"customer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomerDeserializer~1customer\/fragments"}]}]}