{"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/init(code:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/code","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/description"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/STPFormEncodable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"symbolKind":"class","modules":[{"name":"StripePayments"}],"roleHeading":"Class","title":"STPConfirmBLIKOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmBLIKOptions"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPConfirmBLIKOptions","navigatorTitle":[{"kind":"identifier","text":"STPConfirmBLIKOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"type":"text","text":"BLIK options to pass to `STPConfirmPaymentMethodOptions``"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConfirmBLIKOptions"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Site-Admin.Stripe.Com\/Docs\/Api\/Payment_intents\/Confirm#Confirm_payment_intent-Payment_method_options-Blik"}]}],"style":"note","type":"aside","name":"See Also"}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmblikoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconfirmblikoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions/STPFormEncodable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","title":"STPFormEncodable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/STPFormEncodable-Implementations","url":"\/documentation\/stripepayments\/stpconfirmblikoptions\/stpformencodable-implementations","abstract":[]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions/code":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"code"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"code","abstract":[{"text":"The 6-digit BLIK code that a customer has generated using their banking application.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/code","url":"\/documentation\/stripepayments\/stpconfirmblikoptions\/code","kind":"symbol","navigatorTitle":[{"text":"code","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions/additionalAPIParameters":{"navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"type":"topic","title":"additionalAPIParameters","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/additionalAPIParameters","abstract":[{"text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"var cardParams = STPCardParams()"},{"text":" ","type":"text"},{"type":"text","text":"\/\/ add card values"},{"text":" ","type":"text"},{"type":"text","text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]"},{"type":"text","text":" "},{"text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalAPIParameters"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmblikoptions\/additionalapiparameters","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions/description":{"url":"\/documentation\/stripepayments\/stpconfirmblikoptions\/description","type":"topic","title":"description","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/description","navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions/init(code:)":{"kind":"symbol","abstract":[{"type":"text","text":"Initializes STPConfirmBLIKOptions"}],"navigatorTitle":[{"text":"initWithCode:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/init(code:)","title":"init(code:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"code","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/stripepayments\/stpconfirmblikoptions\/init(code:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"url":"\/documentation\/stripepayments\/stpformencodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","type":"topic","title":"STPFormEncodable","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFormEncodable"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions":{"url":"\/documentation\/stripepayments\/stpconfirmblikoptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions","type":"topic","role":"symbol","abstract":[{"type":"text","text":"BLIK options to pass to `STPConfirmPaymentMethodOptions``"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPConfirmBLIKOptions"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmBLIKOptions","kind":"identifier"}],"title":"STPConfirmBLIKOptions"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"STPConfirmBLIKOptions","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPConfirmBLIKOptions","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"STPConfirmBLIKOptions"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/code","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/description"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/init(code:)"],"generated":true},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions\/STPFormEncodable-Implementations"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmBLIKOptions"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1code\/title","value":"code","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1code\/fragments","value":[{"text":"code","kind":"identifier"}]},{"value":"additionalAPIParameters","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1additionalAPIParameters\/title"},{"value":[{"kind":"identifier","text":"additionalAPIParameters"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1additionalAPIParameters\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1description\/title","op":"replace","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1init(code:)\/title","value":"initWithCode:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions~1init(code:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCode:","kind":"identifier"}]},{"op":"replace","value":"STPFormEncodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/title","op":"replace","value":"STPConfirmBLIKOptions"},{"value":[{"kind":"identifier","text":"STPConfirmBLIKOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/fragments"},{"value":[{"kind":"identifier","text":"STPConfirmBLIKOptions"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/navigatorTitle","op":"replace"}]}]}