{"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/JCB","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/amex","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/cartesBancaires","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/dinersClub","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/discover","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/mastercard","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/unionPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/visa"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/Comparable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardbrand"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardbrand"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand"},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s12CaseIterableP","doc:\/\/com.stripe.stripe-payments\/SL","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/Se","doc:\/\/com.stripe.stripe-payments\/SE","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}],"roleHeading":"Enumeration","title":"STPCardBrand","modules":[{"name":"StripePayments"}],"symbolKind":"enum","externalID":"c:@M@StripePayments@E@STPCardBrand","navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/unknown":{"navigatorTitle":[{"kind":"identifier","text":"STPCardBrandUnknown"}],"url":"\/documentation\/stripepayments\/stpcardbrand\/unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/unknown","kind":"symbol","abstract":[{"type":"text","text":"An unknown card brand type"}],"title":"STPCardBrand.unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/dinersClub":{"url":"\/documentation\/stripepayments\/stpcardbrand\/dinersclub","type":"topic","abstract":[{"type":"text","text":"Diners Club card"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/dinersClub","title":"STPCardBrand.dinersClub","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dinersClub","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPCardBrandDinersClub","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/Comparable-Implementations":{"title":"Comparable Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/stripepayments\/stpcardbrand\/comparable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/Comparable-Implementations"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/stripepayments\/stpcardbrand\/equatable-implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/Equatable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/JCB":{"kind":"symbol","role":"symbol","title":"STPCardBrand.JCB","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JCB","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcardbrand\/jcb","abstract":[{"type":"text","text":"JCB card"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardBrandJCB"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/JCB"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/SE":{"type":"unresolvable","title":"Swift.Encodable","identifier":"doc:\/\/com.stripe.stripe-payments\/SE"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/com.stripe.stripe-payments\/s12CaseIterableP"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/CustomStringConvertible-Implementations":{"type":"topic","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpcardbrand\/customstringconvertible-implementations","kind":"article","title":"CustomStringConvertible Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/CustomStringConvertible-Implementations","abstract":[]},"doc://com.stripe.stripe-payments/SL":{"title":"Swift.Comparable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SL"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/discover":{"type":"topic","abstract":[{"type":"text","text":"Discover card"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardBrandDiscover"}],"url":"\/documentation\/stripepayments\/stpcardbrand\/discover","title":"STPCardBrand.discover","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/discover","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"discover"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand":{"navigatorTitle":[{"text":"STPCardBrand","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand","title":"STPCardBrand","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand","type":"topic","kind":"symbol","abstract":[{"text":"The various card brands to which a payment card can belong.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/mastercard":{"role":"symbol","navigatorTitle":[{"text":"STPCardBrandMastercard","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Mastercard card","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mastercard","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/mastercard","title":"STPCardBrand.mastercard","url":"\/documentation\/stripepayments\/stpcardbrand\/mastercard"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/init(rawValue:)","title":"init(rawValue:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpcardbrand\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/RawRepresentable-Implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/unionPay":{"title":"STPCardBrand.unionPay","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/unionPay","url":"\/documentation\/stripepayments\/stpcardbrand\/unionpay","abstract":[{"type":"text","text":"UnionPay card"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unionPay","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPCardBrandUnionPay","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/Se":{"title":"Swift.Decodable","identifier":"doc:\/\/com.stripe.stripe-payments\/Se","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/visa":{"kind":"symbol","title":"STPCardBrand.visa","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"visa"}],"abstract":[{"text":"Visa card","type":"text"}],"url":"\/documentation\/stripepayments\/stpcardbrand\/visa","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/visa","navigatorTitle":[{"kind":"identifier","text":"STPCardBrandVisa"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/cartesBancaires":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cartesBancaires","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardBrandCartesBancaires","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Cartes Bancaires","type":"text"}],"title":"STPCardBrand.cartesBancaires","url":"\/documentation\/stripepayments\/stpcardbrand\/cartesbancaires","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/cartesBancaires","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardBrand/amex":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpcardbrand\/amex","title":"STPCardBrand.amex","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amex","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/amex","abstract":[{"text":"American Express card","type":"text"}],"navigatorTitle":[{"text":"STPCardBrandAmex","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPCardBrand","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"STPCardBrand"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/JCB","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/amex","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/cartesBancaires","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/dinersClub","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/discover","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/mastercard","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/unionPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardBrand\/visa"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPCardBrandUnknown","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1unknown\/title"},{"value":[{"kind":"identifier","text":"STPCardBrandUnknown"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1unknown\/fragments"},{"value":"STPCardBrandDinersClub","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1dinersClub\/title"},{"value":[{"text":"STPCardBrandDinersClub","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1dinersClub\/fragments"},{"value":"STPCardBrandJCB","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1JCB\/title"},{"value":[{"kind":"identifier","text":"STPCardBrandJCB"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1JCB\/fragments"},{"value":"STPCardBrandDiscover","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1discover\/title"},{"value":[{"text":"STPCardBrandDiscover","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1discover\/fragments"},{"value":"STPCardBrand","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/title"},{"value":[{"kind":"identifier","text":"STPCardBrand"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/fragments"},{"value":[{"text":"STPCardBrand","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand\/navigatorTitle"},{"value":"STPCardBrandMastercard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1mastercard\/title"},{"value":[{"text":"STPCardBrandMastercard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1mastercard\/fragments"},{"value":"STPCardBrandUnionPay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1unionPay\/title"},{"value":[{"kind":"identifier","text":"STPCardBrandUnionPay"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1unionPay\/fragments"},{"value":"STPCardBrandVisa","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1visa\/title"},{"value":[{"kind":"identifier","text":"STPCardBrandVisa"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1visa\/fragments"},{"value":"STPCardBrandCartesBancaires","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1cartesBancaires\/title"},{"value":[{"kind":"identifier","text":"STPCardBrandCartesBancaires"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1cartesBancaires\/fragments"},{"value":"STPCardBrandAmex","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1amex\/title"},{"value":[{"text":"STPCardBrandAmex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardBrand~1amex\/fragments"}]}]}