{"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships"}],"kind":"symbol","abstract":[{"type":"text","text":"The various funding sources for a payment card."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFundingType","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"enum","navigatorTitle":[{"text":"STPCardFundingType","kind":"identifier"}],"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFundingType"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPCardFundingType","title":"STPCardFundingType","modules":[{"name":"StripePayments"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/credit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/debit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/other","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/prepaid"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardfundingtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcardfundingtype"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/other":{"url":"\/documentation\/stripepayments\/stpcardfundingtype\/other","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/other","title":"STPCardFundingType.other","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"other","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardFundingTypeOther","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"An other or unknown type of funding source.","type":"text"}]},"doc://com.stripe.stripe-payments/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/prepaid":{"abstract":[{"text":"Prepaid card funding","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepaid","kind":"identifier"}],"title":"STPCardFundingType.prepaid","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/prepaid","url":"\/documentation\/stripepayments\/stpcardfundingtype\/prepaid","type":"topic","navigatorTitle":[{"text":"STPCardFundingTypePrepaid","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/stripepayments\/stpcardfundingtype\/customstringconvertible-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/debit":{"url":"\/documentation\/stripepayments\/stpcardfundingtype\/debit","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Debit card funding","type":"text"}],"title":"STPCardFundingType.debit","navigatorTitle":[{"kind":"identifier","text":"STPCardFundingTypeDebit"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/debit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debit"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/credit":{"title":"STPCardFundingType.credit","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/credit","url":"\/documentation\/stripepayments\/stpcardfundingtype\/credit","navigatorTitle":[{"kind":"identifier","text":"STPCardFundingTypeCredit"}],"abstract":[{"text":"Credit card funding","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"credit"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stpcardfundingtype\/equatable-implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/Equatable-Implementations","title":"Equatable Implementations","kind":"article"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpcardfundingtype\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFundingType"}],"abstract":[{"text":"The various funding sources for a payment card.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardFundingType"}],"title":"STPCardFundingType","url":"\/documentation\/stripepayments\/stpcardfundingtype","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","type":"topic"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stpcardfundingtype\/init(rawvalue:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/init(rawValue:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPCardFundingType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFundingType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFundingType"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/credit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/debit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/other","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType\/prepaid"],"anchor":"Enumeration-Cases","generated":true}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFundingType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPCardFundingTypeOther","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1other\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFundingTypeOther"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1other\/fragments"},{"op":"replace","value":"STPCardFundingTypePrepaid","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1prepaid\/title"},{"op":"replace","value":[{"text":"STPCardFundingTypePrepaid","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1prepaid\/fragments"},{"op":"replace","value":"STPCardFundingTypeDebit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1debit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFundingTypeDebit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1debit\/fragments"},{"op":"replace","value":"STPCardFundingTypeCredit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1credit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFundingTypeCredit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType~1credit\/fragments"},{"op":"replace","value":"STPCardFundingType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title"},{"op":"replace","value":[{"text":"STPCardFundingType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments"},{"op":"replace","value":[{"text":"STPCardFundingType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}