{"abstract":[{"text":"Representation of a user’s credit card details. You can assemble these with","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/init(paymentMethodParams:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/address","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressCity","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressCountry","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressLine1","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressLine2","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressState","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressZip","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/cvc","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/expMonth","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/expYear","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/number"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/copy(with:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/last4()"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/rootObjectName()"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"class","title":"STPCardParams","externalID":"c:@M@StripePayments@objc(cs)STPCardParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCardParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPCardParams","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Class","role":"symbol"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardParams","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"name":"See Also","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api#Cards"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcardparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardparams"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/number":{"abstract":[{"type":"text","text":"The card’s number."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/number","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"number"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"number","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardparams\/number","title":"number","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/init()":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/init()","url":"\/documentation\/stripepayments\/stpcardparams\/init()","type":"topic","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Initializes an empty STPCardParams.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","title":"NSCopying"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/description","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardparams\/description","title":"description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/expYear":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/expYear","kind":"symbol","abstract":[{"text":"The card’s expiration year.","type":"text"}],"type":"topic","title":"expYear","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expYear"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcardparams\/expyear","navigatorTitle":[{"kind":"identifier","text":"expYear"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/addressLine2":{"title":"addressLine2","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressLine2","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"The second line of the cardholder’s address","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addressLine2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpcardparams\/addressline2","navigatorTitle":[{"text":"addressLine2","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/last4()":{"title":"last4()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/last4()","url":"\/documentation\/stripepayments\/stpcardparams\/last4()","abstract":[{"text":"The last 4 digits of the card’s number, if it’s been set, otherwise nil.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"last4","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"last4"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/addressState":{"navigatorTitle":[{"text":"addressState","kind":"identifier"}],"abstract":[{"text":"The state of the cardholder’s address","type":"text"}],"role":"symbol","title":"addressState","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"addressState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressState","type":"topic","url":"\/documentation\/stripepayments\/stpcardparams\/addressstate"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/rootObjectName()":{"type":"topic","title":"rootObjectName()","url":"\/documentation\/stripepayments\/stpcardparams\/rootobjectname()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/rootObjectName()","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"text":" below.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/addressCity":{"navigatorTitle":[{"text":"addressCity","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressCity","url":"\/documentation\/stripepayments\/stpcardparams\/addresscity","abstract":[{"type":"text","text":"The city of the cardholder’s address"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"addressCity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"addressCity","role":"symbol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/currency":{"type":"topic","kind":"symbol","title":"currency","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/currency","url":"\/documentation\/stripepayments\/stpcardparams\/currency","abstract":[{"text":"Three-letter ISO currency code representing the currency paid out to the bank","type":"text"},{"type":"text","text":" "},{"type":"text","text":"account. This is only applicable when tokenizing debit cards to issue payouts"},{"text":" ","type":"text"},{"type":"text","text":"to managed accounts. You should not set it otherwise. The card can then be"},{"type":"text","text":" "},{"text":"used as a transfer destination for funds in this currency.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"currency","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardParams"}],"navigatorTitle":[{"text":"STPCardParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of a user’s credit card details. You can assemble these with"},{"type":"text","text":" "},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"type":"text","text":" "},{"text":"an STPAPIClient.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","title":"STPCardParams","url":"\/documentation\/stripepayments\/stpcardparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/additionalAPIParameters":{"title":"additionalAPIParameters","url":"\/documentation\/stripepayments\/stpcardparams\/additionalapiparameters","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/additionalAPIParameters","role":"symbol","navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"var cardParams = STPCardParams()"},{"text":" ","type":"text"},{"type":"text","text":"\/\/ add card values"},{"text":" ","type":"text"},{"type":"text","text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]"},{"type":"text","text":" "},{"type":"text","text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/address":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/address","abstract":[{"text":"The cardholder’s address.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"}],"navigatorTitle":[{"kind":"identifier","text":"address"}],"type":"topic","role":"symbol","kind":"symbol","title":"address","url":"\/documentation\/stripepayments\/stpcardparams\/address"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/cvc":{"abstract":[{"text":"The card’s security code, found on the back.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cvc","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cvc"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/cvc","title":"cvc","role":"symbol","url":"\/documentation\/stripepayments\/stpcardparams\/cvc"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/addressLine1":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressLine1","url":"\/documentation\/stripepayments\/stpcardparams\/addressline1","type":"topic","title":"addressLine1","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressLine1"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"addressLine1","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The first line of the cardholder’s address","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/addressZip":{"abstract":[{"type":"text","text":"The zip code of the cardholder’s address"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressZip","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardparams\/addresszip","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressZip"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","title":"addressZip","navigatorTitle":[{"kind":"identifier","text":"addressZip"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/copy(with:)":{"type":"topic","kind":"symbol","title":"copy(with:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/copy(with:)","url":"\/documentation\/stripepayments\/stpcardparams\/copy(with:)","abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"copyWithZone:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"copy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/expMonth":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/expMonth","abstract":[{"type":"text","text":"The card’s expiration month."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"expMonth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"expMonth","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"expMonth","url":"\/documentation\/stripepayments\/stpcardparams\/expmonth"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/addressCountry":{"navigatorTitle":[{"kind":"identifier","text":"addressCountry"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressCountry","url":"\/documentation\/stripepayments\/stpcardparams\/addresscountry","kind":"symbol","title":"addressCountry","abstract":[{"type":"text","text":"The country of the cardholder’s address"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressCountry","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/init(paymentMethodParams:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/init(paymentMethodParams:)","url":"\/documentation\/stripepayments\/stpcardparams\/init(paymentmethodparams:)","title":"init(paymentMethodParams:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"paymentMethodParams","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPaymentMethodParams:"}],"kind":"symbol","abstract":[{"type":"text","text":"A convenience initializer for creating a card params from a card payment method params."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/propertyNamesToFormFieldNamesMapping()":{"abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"type":"codeVoice","code":"expMonth"},{"text":", but the Stripe API expects a field called ","type":"text"},{"code":"exp_month","type":"codeVoice"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/propertyNamesToFormFieldNamesMapping()","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcardparams\/propertynamestoformfieldnamesmapping()","title":"propertyNamesToFormFieldNamesMapping()","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"type":"topic","abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"title":"STPFormEncodable","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"url":"\/documentation\/stripepayments\/stpformencodable","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/name":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpcardparams\/name","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/name","title":"name","type":"topic","navigatorTitle":[{"kind":"identifier","text":"name"}],"abstract":[{"text":"The cardholder’s name.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPCardParams"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardParams"}],"path":"\/metadata\/fragments"},{"value":[{"text":"STPCardParams","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/address","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressCity","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressCountry","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressLine1","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressLine2","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressState","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressZip","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/cvc","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/expMonth","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/expYear","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/number"],"title":"Instance Properties","anchor":"Instance-Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/copy(with:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/init(paymentMethodParams:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/last4()"],"title":"Instance Methods"},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/rootObjectName()"]}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPCardParams"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","value":"number","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1number\/title"},{"value":[{"text":"number","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1number\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1init()\/title","op":"replace","value":"init"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1init()\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1description\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1expYear\/title","op":"replace","value":"expYear"},{"value":[{"kind":"identifier","text":"expYear"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1expYear\/fragments"},{"value":"addressLine2","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressLine2\/title"},{"op":"replace","value":[{"kind":"identifier","text":"addressLine2"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressLine2\/fragments"},{"value":"last4","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1last4()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1last4()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"last4"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressState\/title","value":"addressState","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressState\/fragments","op":"replace","value":[{"text":"addressState","kind":"identifier"}]},{"value":"rootObjectName","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1rootObjectName()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1rootObjectName()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressCity\/title","value":"addressCity","op":"replace"},{"value":[{"text":"addressCity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressCity\/fragments"},{"value":"currency","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1currency\/title","op":"replace"},{"value":[{"text":"currency","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1currency\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title","value":"STPCardParams","op":"replace"},{"value":[{"text":"STPCardParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments"},{"value":[{"kind":"identifier","text":"STPCardParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1additionalAPIParameters\/title","op":"replace","value":"additionalAPIParameters"},{"value":[{"text":"additionalAPIParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1additionalAPIParameters\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1address\/title","value":"address","op":"replace"},{"value":[{"text":"address","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1address\/fragments"},{"op":"replace","value":"cvc","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1cvc\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1cvc\/fragments","op":"replace","value":[{"kind":"identifier","text":"cvc"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressLine1\/title","value":"addressLine1"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressLine1\/fragments","value":[{"text":"addressLine1","kind":"identifier"}]},{"value":"addressZip","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressZip\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressZip\/fragments","op":"replace","value":[{"kind":"identifier","text":"addressZip"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1copy(with:)\/title","value":"copyWithZone:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1copy(with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"copyWithZone:"}]},{"value":"expMonth","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1expMonth\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1expMonth\/fragments","value":[{"kind":"identifier","text":"expMonth"}],"op":"replace"},{"value":"addressCountry","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressCountry\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressCountry\/fragments","value":[{"text":"addressCountry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1init(paymentMethodParams:)\/title","op":"replace","value":"initWithPaymentMethodParams:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPaymentMethodParams:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1init(paymentMethodParams:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1propertyNamesToFormFieldNamesMapping()\/title","value":"propertyNamesToFormFieldNamesMapping","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1propertyNamesToFormFieldNamesMapping()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","value":"STPFormEncodable","op":"replace"},{"value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","op":"replace"},{"value":[{"text":"STPFormEncodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1name\/title","value":"name"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1name\/fragments","op":"replace","value":[{"kind":"identifier","text":"name"}]}]}]}