{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpemptystriperesponse"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPEmptyStripeResponse","interfaceLanguage":"occ"},"abstract":[{"text":"An STPAPIResponseDecodable implementation to use for endpoints that don’t","type":"text"},{"type":"text","text":" "},{"text":"actually return objects, like \/v1\/3ds2\/challenge_completed","type":"text"}],"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPEmptyStripeResponse\/allResponseFields"],"title":"Instance Properties"},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPEmptyStripeResponse\/decodedObjectFromAPIResponse:"],"generated":true}],"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"STPEmptyStripeResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPEmptyStripeResponse"}],"title":"STPEmptyStripeResponse","externalID":"c:@M@StripePayments@objc(cs)STPEmptyStripeResponse","symbolKind":"class","roleHeading":"Class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPEmptyStripeResponse"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","title":"STPAPIResponseDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPEmptyStripeResponse":{"abstract":[{"type":"text","text":"An STPAPIResponseDecodable implementation to use for endpoints that don’t"},{"type":"text","text":" "},{"type":"text","text":"actually return objects, like \/v1\/3ds2\/challenge_completed"}],"role":"symbol","fragments":[{"text":"STPEmptyStripeResponse","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpemptystriperesponse","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPEmptyStripeResponse","kind":"symbol","type":"topic","title":"STPEmptyStripeResponse"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPEmptyStripeResponse/allResponseFields":{"url":"\/documentation\/stripepayments\/stpemptystriperesponse\/allresponsefields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPEmptyStripeResponse\/allResponseFields","title":"allResponseFields","role":"symbol","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"allResponseFields","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPEmptyStripeResponse/decodedObjectFromAPIResponse:":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPEmptyStripeResponse\/decodedObjectFromAPIResponse:","title":"decodedObjectFromAPIResponse:","url":"\/documentation\/stripepayments\/stpemptystriperesponse\/decodedobjectfromapiresponse:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}