{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFile"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"aside","style":"note","name":"See Also","content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api#File_uploads","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"text":"Representation of a file upload object in the Stripe API.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"metadata":{"symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPFile","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFile"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"StripePayments"}],"title":"STPFile","navigatorTitle":[{"text":"STPFile","kind":"identifier"}]},"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/fileId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/purpose","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/size","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/decodedObject(fromAPIResponse:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/string(from:)"],"generated":true}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpfile"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfile"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"type":"topic","title":"STPAPIResponseDecodable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/isEqual(_:)":{"type":"topic","url":"\/documentation\/stripepayments\/stpfile\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/isEqual(_:)","title":"isEqual(_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/created":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/created","title":"created","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"created","kind":"identifier"}],"abstract":[{"type":"text","text":"The date this file was created."}],"type":"topic","url":"\/documentation\/stripepayments\/stpfile\/created","kind":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/purpose":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/purpose","role":"symbol","kind":"symbol","abstract":[{"text":"The purpose of this file. This can be either an identifing document or an evidence dispute.","type":"text"}],"title":"purpose","type":"topic","url":"\/documentation\/stripepayments\/stpfile\/purpose","navigatorTitle":[{"kind":"identifier","text":"purpose"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"purpose"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","kind":"typeIdentifier","text":"STPFilePurpose"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/fileId":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fileId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"fileId","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fileId"}],"abstract":[{"text":"The token for this file.","type":"text"}],"url":"\/documentation\/stripepayments\/stpfile\/fileid","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/fileId"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/size":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpfile\/size","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/size","abstract":[{"type":"text","text":"The file size in bytes."}],"type":"topic","title":"size","navigatorTitle":[{"text":"size","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/decodedObject(fromAPIResponse:)":{"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/decodedObject(fromAPIResponse:)","title":"decodedObject(fromAPIResponse:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpfile\/decodedobject(fromapiresponse:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/hash":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/hash","title":"hash","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpfile\/hash"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/string(from:)":{"url":"\/documentation\/stripepayments\/stpfile\/string(from:)","title":"string(from:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/string(from:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPFilePurpose","kind":"typeIdentifier","text":"STPFilePurpose"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Returns the string value for a purpose.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"stringFromPurpose:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/allResponseFields":{"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"title":"allResponseFields","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/allResponseFields","url":"\/documentation\/stripepayments\/stpfile\/allresponsefields"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile":{"navigatorTitle":[{"kind":"identifier","text":"STPFile"}],"url":"\/documentation\/stripepayments\/stpfile","abstract":[{"type":"text","text":"Representation of a file upload object in the Stripe API."}],"type":"topic","role":"symbol","title":"STPFile","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFile","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile/type":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"title":"type","abstract":[{"type":"text","text":"The file type. This can be “jpg”, “png”, or “pdf”."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/type","url":"\/documentation\/stripepayments\/stpfile\/type"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"STPFile","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPFile","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPFile","kind":"identifier"}]},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/fileId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/purpose","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/size","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/type"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/decodedObject(fromAPIResponse:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile\/string(from:)"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFile","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1created\/title","value":"created"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1created\/fragments","value":[{"text":"created","kind":"identifier"}]},{"value":"purpose","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1purpose\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1purpose\/fragments","value":[{"text":"purpose","kind":"identifier"}]},{"value":"fileId","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1fileId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1fileId\/fragments","value":[{"text":"fileId","kind":"identifier"}]},{"value":"size","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1size\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1size\/fragments","op":"replace","value":[{"text":"size","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1decodedObject(fromAPIResponse:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1hash\/title","value":"hash","op":"replace"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1hash\/fragments"},{"value":"stringFromPurpose:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1string(from:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1string(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"stringFromPurpose:","kind":"identifier"}]},{"value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1allResponseFields\/title","op":"replace"},{"value":[{"kind":"identifier","text":"allResponseFields"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1allResponseFields\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/title","value":"STPFile"},{"value":[{"text":"STPFile","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/navigatorTitle","value":[{"text":"STPFile","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"}]}]}