{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfilepurpose"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpfilepurpose"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"STPFilePurpose","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPFilePurpose","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"STPFilePurpose","kind":"identifier"}],"symbolKind":"enum","externalID":"c:@M@StripePayments@E@STPFilePurpose","role":"symbol"},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/disputeEvidence","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/identityDocument","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/unknown"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"text":"The purpose of the uploaded file.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPFilePurpose","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"style":"note","content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/File-Upload","type":"text"}],"type":"paragraph"}],"type":"aside","name":"See Also"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","url":"\/documentation\/stripepayments\/stpfilepurpose\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/unknown":{"type":"topic","abstract":[{"text":"A file of unknown purpose type","type":"text"}],"url":"\/documentation\/stripepayments\/stpfilepurpose\/unknown","kind":"symbol","navigatorTitle":[{"text":"STPFilePurposeUnknown","kind":"identifier"}],"role":"symbol","title":"STPFilePurpose.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/identityDocument":{"type":"topic","abstract":[{"type":"text","text":"Identity document file"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpfilepurpose\/identitydocument","navigatorTitle":[{"text":"STPFilePurposeIdentityDocument","kind":"identifier"}],"role":"symbol","title":"STPFilePurpose.identityDocument","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identityDocument"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/identityDocument"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpfilepurpose\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/RawRepresentable-Implementations","abstract":[]},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/disputeEvidence":{"url":"\/documentation\/stripepayments\/stpfilepurpose\/disputeevidence","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/disputeEvidence","role":"symbol","kind":"symbol","title":"STPFilePurpose.disputeEvidence","abstract":[{"type":"text","text":"Dispute evidence file"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disputeEvidence"}],"navigatorTitle":[{"text":"STPFilePurposeDisputeEvidence","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/CustomStringConvertible-Implementations":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepayments\/stpfilepurpose\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/Equatable-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/stripepayments\/stpfilepurpose\/equatable-implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/Equatable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"kind":"symbol","title":"STPFilePurpose","navigatorTitle":[{"kind":"identifier","text":"STPFilePurpose"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","url":"\/documentation\/stripepayments\/stpfilepurpose","role":"symbol","abstract":[{"text":"The purpose of the uploaded file.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFilePurpose"}],"type":"topic"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPFilePurpose"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPFilePurpose"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPFilePurpose","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/disputeEvidence","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/identityDocument","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/unknown"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFilePurpose","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1unknown\/title","value":"STPFilePurposeUnknown"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1unknown\/fragments","value":[{"text":"STPFilePurposeUnknown","kind":"identifier"}],"op":"replace"},{"value":"STPFilePurposeIdentityDocument","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1identityDocument\/title"},{"value":[{"text":"STPFilePurposeIdentityDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1identityDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1disputeEvidence\/title","value":"STPFilePurposeDisputeEvidence"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1disputeEvidence\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFilePurposeDisputeEvidence"}]},{"value":"STPFilePurpose","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments","value":[{"text":"STPFilePurpose","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPFilePurpose"}]}]}]}