{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfilecompletionblock"]}],"metadata":{"symbolKind":"typealias","navigatorTitle":[{"text":"STPFileCompletionBlock","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"STPFileCompletionBlock","kind":"identifier"}],"externalID":"s:14StripePayments22STPFileCompletionBlocka","roleHeading":"Type Alias","role":"symbol","title":"STPFileCompletionBlock","modules":[{"name":"StripePayments"}]},"abstract":[{"type":"text","text":"A callback to be run with a file response from the Stripe API."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFileCompletionBlock"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFileCompletionBlock"},{"text":" = (","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPFile","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile","text":"STPFile"},{"kind":"text","text":"?, "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The Stripe file from the response. Will be nil if an error occurs. - seealso: STPFile"}],"type":"paragraph"}],"name":"file"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The error returned from the response, or nil if none occurs. - seealso: StripeError.h for possible values.","type":"text"}]}],"name":"error"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFile":{"role":"symbol","url":"\/documentation\/stripepayments\/stpfile","type":"topic","navigatorTitle":[{"text":"STPFile","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFile","title":"STPFile","kind":"symbol","abstract":[{"type":"text","text":"Representation of a file upload object in the Stripe API."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFile","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFileCompletionBlock":{"abstract":[{"type":"text","text":"A callback to be run with a file response from the Stripe API."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFileCompletionBlock"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFileCompletionBlock","type":"topic","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFileCompletionBlock","kind":"identifier"}],"title":"STPFileCompletionBlock","url":"\/documentation\/stripepayments\/stpfilecompletionblock"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/title","value":"STPFile","op":"replace"},{"value":[{"kind":"identifier","text":"STPFile"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/fragments"},{"op":"replace","value":[{"text":"STPFile","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFile\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}