{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@StripePayments@E@STPFPXBankBrand","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"modules":[{"name":"StripePayments"}],"title":"STPFPXBankBrand","role":"symbol","symbolKind":"enum"},"abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/BSN","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/CIMB","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/HSBC","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/KFH","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RHB","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/UOB","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/affinBank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/allianceBank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ambank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankIslam","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankMuamalat","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankRakyat","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/hongLeongBank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2E","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2U","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ocbc","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/publicBank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/standardChartered","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/unknown"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/s9EscapableP","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/ambank":{"abstract":[{"text":"AmBank","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ambank","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandAmbank","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ambank","kind":"symbol","type":"topic","title":"STPFPXBankBrand.ambank","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/ambank"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/ocbc":{"abstract":[{"type":"text","text":"OCBC Bank"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ocbc","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandOcbc","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ocbc","kind":"symbol","type":"topic","title":"STPFPXBankBrand.ocbc","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/ocbc"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RawRepresentable-Implementations","kind":"article","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/rawrepresentable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/bankIslam":{"abstract":[{"type":"text","text":"Bank Islam"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankIslam"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandBankIslam"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankIslam","kind":"symbol","type":"topic","title":"STPFPXBankBrand.bankIslam","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/bankislam"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/HSBC":{"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/hsbc","abstract":[{"type":"text","text":"HSBC BANK"}],"kind":"symbol","title":"STPFPXBankBrand.HSBC","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"HSBC"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandHSBC"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/HSBC"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/s9EscapableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s9EscapableP","title":"Swift.Escapable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/unknown":{"abstract":[{"type":"text","text":"An unknown bank"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandUnknown","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/unknown","kind":"symbol","type":"topic","title":"STPFPXBankBrand.unknown","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/bankMuamalat":{"role":"symbol","abstract":[{"type":"text","text":"Bank Muamalat"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandBankMuamalat"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankMuamalat","type":"topic","title":"STPFPXBankBrand.bankMuamalat","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankMuamalat"}],"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/bankmuamalat"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/maybank2E":{"abstract":[{"type":"text","text":"Maybank2E"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maybank2E","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandMaybank2E","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2E","kind":"symbol","type":"topic","title":"STPFPXBankBrand.maybank2E","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/maybank2e"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/RHB":{"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/rhb","role":"symbol","title":"STPFPXBankBrand.RHB","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RHB","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"RHB"}],"abstract":[{"type":"text","text":"RHB Bank"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandRHB"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/publicBank":{"abstract":[{"type":"text","text":"Public Bank"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"publicBank","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandPublicBank","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/publicBank","kind":"symbol","type":"topic","title":"STPFPXBankBrand.publicBank","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/publicbank"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/Equatable-Implementations","kind":"article","type":"topic","title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/equatable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/bankRakyat":{"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandBankRakyat"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/bankrakyat","kind":"symbol","abstract":[{"type":"text","text":"Bank Rakyat"}],"title":"STPFPXBankBrand.bankRakyat","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankRakyat","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bankRakyat"}]},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/init(rawValue:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/init(rawValue:)","kind":"symbol","type":"topic","title":"init(rawValue:)","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/UOB":{"abstract":[{"type":"text","text":"UOB Bank"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UOB","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandUOB","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/UOB","kind":"symbol","type":"topic","title":"STPFPXBankBrand.UOB","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/uob"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/maybank2U":{"abstract":[{"type":"text","text":"Maybank2U"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maybank2U","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandMaybank2U","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2U","kind":"symbol","type":"topic","title":"STPFPXBankBrand.maybank2U","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/maybank2u"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/CustomStringConvertible-Implementations":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/CustomStringConvertible-Implementations","kind":"article","type":"topic","title":"CustomStringConvertible Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/customstringconvertible-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFPXBankBrand"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","kind":"symbol","type":"topic","title":"STPFPXBankBrand","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/BSN":{"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/bsn","abstract":[{"type":"text","text":"BSN"}],"kind":"symbol","title":"STPFPXBankBrand.BSN","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BSN","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandBSN","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/BSN"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/affinBank":{"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandAffinBank"}],"kind":"symbol","type":"topic","abstract":[{"text":"Affin Bank","type":"text"}],"title":"STPFPXBankBrand.affinBank","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"affinBank"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/affinBank","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/affinbank"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/allianceBank":{"abstract":[{"type":"text","text":"Alliance Bank"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allianceBank"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandAllianceBank"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/allianceBank","kind":"symbol","type":"topic","title":"STPFPXBankBrand.allianceBank","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/alliancebank"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/CIMB":{"abstract":[{"type":"text","text":"CIMB Clicks"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIMB","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandCIMB","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/CIMB","kind":"symbol","type":"topic","title":"STPFPXBankBrand.CIMB","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/cimb"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/standardChartered":{"abstract":[{"type":"text","text":"Standard Chartered"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standardChartered","kind":"identifier"}],"navigatorTitle":[{"text":"STPFPXBankBrandStandardChartered","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/standardChartered","kind":"symbol","type":"topic","title":"STPFPXBankBrand.standardChartered","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/standardchartered"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/hongLeongBank":{"url":"\/documentation\/stripepayments\/stpfpxbankbrand\/hongleongbank","abstract":[{"type":"text","text":"Hong Leong Bank"}],"kind":"symbol","title":"STPFPXBankBrand.hongLeongBank","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hongLeongBank"}],"navigatorTitle":[{"text":"STPFPXBankBrandHongLeongBank","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/hongLeongBank"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/KFH":{"abstract":[{"type":"text","text":"KFH"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"KFH"}],"navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandKFH"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/KFH","kind":"symbol","type":"topic","title":"STPFPXBankBrand.KFH","role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/kfh"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"STPFPXBankBrand"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/BSN","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/CIMB","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/HSBC","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/KFH","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/RHB","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/UOB","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/affinBank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/allianceBank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ambank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankIslam","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankMuamalat","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/bankRakyat","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/hongLeongBank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2E","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/maybank2U","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/ocbc","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/publicBank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/standardChartered","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/unknown"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFPXBankBrand","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1ambank\/title","op":"replace","value":"STPFPXBankBrandAmbank"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1ambank\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandAmbank"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1ocbc\/title","op":"replace","value":"STPFPXBankBrandOcbc"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1ocbc\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandOcbc"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankIslam\/title","op":"replace","value":"STPFPXBankBrandBankIslam"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankIslam\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandBankIslam"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1HSBC\/title","op":"replace","value":"STPFPXBankBrandHSBC"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1HSBC\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandHSBC"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1unknown\/title","op":"replace","value":"STPFPXBankBrandUnknown"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1unknown\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandUnknown"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankMuamalat\/title","op":"replace","value":"STPFPXBankBrandBankMuamalat"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankMuamalat\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandBankMuamalat"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1maybank2E\/title","op":"replace","value":"STPFPXBankBrandMaybank2E"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1maybank2E\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2E"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1RHB\/title","op":"replace","value":"STPFPXBankBrandRHB"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1RHB\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandRHB"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1publicBank\/title","op":"replace","value":"STPFPXBankBrandPublicBank"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1publicBank\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandPublicBank"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankRakyat\/title","op":"replace","value":"STPFPXBankBrandBankRakyat"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1bankRakyat\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandBankRakyat"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1UOB\/title","op":"replace","value":"STPFPXBankBrandUOB"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1UOB\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandUOB"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1maybank2U\/title","op":"replace","value":"STPFPXBankBrandMaybank2U"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1maybank2U\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandMaybank2U"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","op":"replace","value":"STPFPXBankBrand"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1BSN\/title","op":"replace","value":"STPFPXBankBrandBSN"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1BSN\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandBSN"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1affinBank\/title","op":"replace","value":"STPFPXBankBrandAffinBank"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1affinBank\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandAffinBank"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1allianceBank\/title","op":"replace","value":"STPFPXBankBrandAllianceBank"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1allianceBank\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPFPXBankBrandAllianceBank"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1CIMB\/title","value":"STPFPXBankBrandCIMB"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1CIMB\/fragments","value":[{"text":"STPFPXBankBrandCIMB","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1standardChartered\/title","value":"STPFPXBankBrandStandardChartered"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1standardChartered\/fragments","value":[{"text":"STPFPXBankBrandStandardChartered","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1hongLeongBank\/title","value":"STPFPXBankBrandHongLeongBank"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1hongLeongBank\/fragments","value":[{"text":"STPFPXBankBrandHongLeongBank","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1KFH\/title","value":"STPFPXBankBrandKFH"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1KFH\/fragments","value":[{"text":"STPFPXBankBrandKFH","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}