{"metadata":{"title":"STPFPXBank","symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFPXBank"}],"roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPFPXBank","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFPXBank","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPFPXBank","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbank"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfpxbank"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Convenience methods for using FPX bank brands."}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/bankCodeFrom(_:_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/brandFrom(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/identifierFrom(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/stringFrom(_:)"],"title":"Type Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"references":{"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/bankCodeFrom(_:_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/bankCodeFrom(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bankCodeFrom"},{"kind":"text","text":"("},{"text":"STPFPXBankBrand","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","title":"bankCodeFrom(_:_:)","abstract":[{"type":"text","text":"Returns the code identifying the provided bank brand in the FPX status API;"},{"text":" ","type":"text"},{"type":"text","text":"i.e. "},{"code":"STPIdentifierFromFPXBankBrand(STPCardBrandUob) ==  @\"UOB0226\"","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbank\/bankcodefrom(_:_:)","navigatorTitle":[{"text":"bankCodeFrom::","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank":{"url":"\/documentation\/stripepayments\/stpfpxbank","abstract":[{"type":"text","text":"Convenience methods for using FPX bank brands."}],"title":"STPFPXBank","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPFPXBank","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFPXBank"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/init":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/init","abstract":[],"type":"topic","url":"\/documentation\/stripepayments\/stpfpxbank\/init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/identifierFrom(_:)":{"type":"topic","title":"identifierFrom(_:)","url":"\/documentation\/stripepayments\/stpfpxbank\/identifierfrom(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifierFrom:"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"identifierFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPFPXBankBrand","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Returns a string representation identifying the provided bank brand;","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"i.e. "},{"type":"codeVoice","code":"STPIdentifierFromFPXBankBrand(STPCardBrandUob) ==  @\"uob\""},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/identifierFrom(_:)","kind":"symbol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/stringFrom(_:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/stringFrom(_:)","navigatorTitle":[{"kind":"identifier","text":"stringFrom:"}],"kind":"symbol","title":"stringFrom(_:)","abstract":[{"type":"text","text":"Returns a string representation for the provided bank brand;"},{"text":" ","type":"text"},{"text":"i.e. ","type":"text"},{"type":"codeVoice","code":"STPFPXBank.stringFrom(brand:.uob) == \"UOB Bank\""},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/stripepayments\/stpfpxbank\/stringfrom(_:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stringFrom"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPFPXBankBrand","preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBank/brandFrom(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"brandFrom:"}],"abstract":[{"text":"Returns a bank brand provided a string representation identifying a bank brand;","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"i.e. "},{"code":"STPFPXBankBrandFromIdentifier(@\"uob\") == STPCardBrandUob","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/brandFrom(_:)","title":"brandFrom(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brandFrom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpfpxbank\/brandfrom(_:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"STPFPXBank"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPFPXBank","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"STPFPXBank","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/bankCodeFrom(_:_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/brandFrom(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/identifierFrom(_:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBank\/stringFrom(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"STPFPXBank","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1bankCodeFrom(_:_:)\/title","value":"bankCodeFrom::","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1bankCodeFrom(_:_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"bankCodeFrom::"}]},{"value":"STPFPXBank","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/title"},{"value":[{"kind":"identifier","text":"STPFPXBank"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1identifierFrom(_:)\/title","value":"identifierFrom:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1identifierFrom(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"identifierFrom:"}]},{"value":"stringFrom:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1stringFrom(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1stringFrom(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"stringFrom:"}],"op":"replace"},{"value":"brandFrom:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1brandFrom(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBank~1brandFrom(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"brandFrom:"}],"op":"replace"}]}]}
