{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"text":"Contains instructions for presenting the QR code required to complete a PromptPay payment.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"code":"STPIntentActionPromptPayDisplayQrCode","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionPromptPayDisplayQrCode"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","modules":[{"name":"StripePayments"}],"title":"STPIntentActionPromptPayDisplayQrCode","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionPromptPayDisplayQrCode","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionPromptPayDisplayQrCode"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/hostedInstructionsURL"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/STPAPIResponseDecodable-Implementations"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"title":"STPIntentActionPromptPayDisplayQrCode","navigatorTitle":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Contains instructions for presenting the QR code required to complete a PromptPay payment."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentActionPromptPayDisplayQrCode"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode/hostedInstructionsURL":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/hostedInstructionsURL","title":"hostedInstructionsURL","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The URL to open which contains instructions on how to complete the payment."}],"navigatorTitle":[{"text":"hostedInstructionsURL","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/hostedinstructionsurl","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hostedInstructionsURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode/description":{"abstract":[{"text":":nodoc:","type":"text"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/description","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/description","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode/STPAPIResponseDecodable-Implementations":{"kind":"article","role":"collectionGroup","title":"STPAPIResponseDecodable Implementations","type":"topic","url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/stpapiresponsedecodable-implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/STPAPIResponseDecodable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"role":"symbol","title":"STPAPIResponseDecodable","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPromptPayDisplayQrCode/allResponseFields":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/allResponseFields","title":"allResponseFields","kind":"symbol","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"url":"\/documentation\/stripepayments\/stpintentactionpromptpaydisplayqrcode\/allresponsefields","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"STPIntentActionPromptPayDisplayQrCode","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPIntentActionPromptPayDisplayQrCode"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPIntentActionPromptPayDisplayQrCode"}],"op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/hostedInstructionsURL"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPromptPayDisplayQrCode\/STPAPIResponseDecodable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPIntentActionPromptPayDisplayQrCode"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"STPIntentActionPromptPayDisplayQrCode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/fragments","value":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode\/navigatorTitle","value":[{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1hostedInstructionsURL\/title","value":"hostedInstructionsURL","op":"replace"},{"value":[{"text":"hostedInstructionsURL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1hostedInstructionsURL\/fragments"},{"value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1description\/title","op":"replace"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1description\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","op":"replace","value":"STPAPIResponseDecodable"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1allResponseFields\/title","value":"allResponseFields"},{"value":[{"kind":"identifier","text":"allResponseFields"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPromptPayDisplayQrCode~1allResponseFields\/fragments","op":"replace"}]}]}