{"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits"},"kind":"symbol","abstract":[{"text":"Contains details describing microdeposits verification flow for US Bank Accounts.","type":"text"}],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPIntentActionVerifyWithMicrodeposits","role":"symbol","roleHeading":"Class","symbolKind":"class","title":"STPIntentActionVerifyWithMicrodeposits","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionVerifyWithMicrodeposits"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPIntentActionVerifyWithMicrodeposits"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/arrivalDate","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/hostedVerificationURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/microdepositType"],"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/STPAPIResponseDecodable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits/STPAPIResponseDecodable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/STPAPIResponseDecodable-Implementations","url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits\/stpapiresponsedecodable-implementations","title":"STPAPIResponseDecodable Implementations","kind":"article"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits/allResponseFields":{"title":"allResponseFields","url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits\/allresponsefields","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits":{"title":"STPIntentActionVerifyWithMicrodeposits","abstract":[{"type":"text","text":"Contains details describing microdeposits verification flow for US Bank Accounts."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionVerifyWithMicrodeposits"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits/microdepositType":{"navigatorTitle":[{"kind":"identifier","text":"microdepositType"}],"abstract":[{"type":"text","text":"The type of the microdeposit sent to the customer. Used to distinguish between different verificaion methods."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"microdepositType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPMicrodepositType","text":"STPMicrodepositType","kind":"typeIdentifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/microdepositType","url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits\/microdeposittype","title":"microdepositType","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","title":"STPAPIResponseDecodable","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits/hostedVerificationURL":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/hostedVerificationURL","kind":"symbol","title":"hostedVerificationURL","url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits\/hostedverificationurl","abstract":[{"text":"The URL for the hosted verification page, which allows customers to verify their bank account","type":"text"}],"navigatorTitle":[{"text":"hostedVerificationURL","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostedVerificationURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionVerifyWithMicrodeposits/arrivalDate":{"navigatorTitle":[{"kind":"identifier","text":"arrivalDate"}],"abstract":[{"type":"text","text":"The timestamp when the microdeposits are expected to land"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arrivalDate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/arrivalDate","url":"\/documentation\/stripepayments\/stpintentactionverifywithmicrodeposits\/arrivaldate","title":"arrivalDate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPIntentActionVerifyWithMicrodeposits"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPIntentActionVerifyWithMicrodeposits"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/arrivalDate","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/hostedVerificationURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/microdepositType"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionVerifyWithMicrodeposits\/STPAPIResponseDecodable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionVerifyWithMicrodeposits"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1allResponseFields\/title","value":"allResponseFields"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPIntentActionVerifyWithMicrodeposits","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/title"},{"op":"replace","value":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits\/navigatorTitle","value":[{"text":"STPIntentActionVerifyWithMicrodeposits","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1microdepositType\/title","value":"microdepositType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1microdepositType\/fragments","value":[{"text":"microdepositType","kind":"identifier"}],"op":"replace"},{"value":"STPAPIResponseDecodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"op":"replace","value":"hostedVerificationURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1hostedVerificationURL\/title"},{"value":[{"kind":"identifier","text":"hostedVerificationURL"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1hostedVerificationURL\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1arrivalDate\/title","value":"arrivalDate","op":"replace"},{"value":[{"text":"arrivalDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionVerifyWithMicrodeposits~1arrivalDate\/fragments","op":"replace"}]}]}