{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL"},"metadata":{"role":"symbol","navigatorTitle":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL","modules":[{"name":"StripePayments"}],"title":"STPIntentActionRedirectToURL","symbolKind":"class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionredirecttourl"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionredirecttourl"]}],"abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to another page or application.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentActionRedirectToURL"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"aside","name":"See Also","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_intents\/Object#Payment_intent_object-Next_action"}],"type":"paragraph"}],"style":"note"}]}],"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/returnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/url"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/STPAPIResponseDecodable-Implementations"],"generated":true}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"references":{"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"title":"STPAPIResponseDecodable","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL/STPAPIResponseDecodable-Implementations":{"role":"collectionGroup","title":"STPAPIResponseDecodable Implementations","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/STPAPIResponseDecodable-Implementations","url":"\/documentation\/stripepayments\/stpintentactionredirecttourl\/stpapiresponsedecodable-implementations"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/description","url":"\/documentation\/stripepayments\/stpintentactionredirecttourl\/description","abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","role":"symbol","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL/allResponseFields":{"kind":"symbol","title":"allResponseFields","type":"topic","url":"\/documentation\/stripepayments\/stpintentactionredirecttourl\/allresponsefields","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/allResponseFields","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"title":"STPIntentActionRedirectToURL","navigatorTitle":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to another page or application."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentActionRedirectToURL"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionredirecttourl"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL/url":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"}],"role":"symbol","title":"url","abstract":[{"text":"The URL you must redirect your customer to in order to authenticate the payment.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/url","url":"\/documentation\/stripepayments\/stpintentactionredirecttourl\/url","navigatorTitle":[{"text":"url","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionRedirectToURL/returnURL":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"returnURL","kind":"identifier"}],"type":"topic","title":"returnURL","abstract":[{"type":"text","text":"The return URL that’ll be redirected back to when the user is done"},{"type":"text","text":" "},{"type":"text","text":"authenticating."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/returnURL","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionredirecttourl\/returnurl"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPIntentActionRedirectToURL"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPIntentActionRedirectToURL"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/returnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/url"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionRedirectToURL\/STPAPIResponseDecodable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionRedirectToURL","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1allResponseFields\/title","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/title","value":"STPIntentActionRedirectToURL"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/fragments","value":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL\/navigatorTitle","value":[{"text":"STPIntentActionRedirectToURL","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1url\/fragments","value":[{"kind":"identifier","text":"url"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1returnURL\/title","value":"returnURL"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionRedirectToURL~1returnURL\/fragments","value":[{"text":"returnURL","kind":"identifier"}]}]}]}