{"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"inheritedBy","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentAction"],"kind":"relationships","title":"Inherited By"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"title":"STPIntentAction","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentAction","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPIntentAction"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/alipayHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/authorizeWithURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/boletoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/cashAppRedirectToApp","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/konbiniDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/multibancoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/oxxoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/payNowDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/promptPayDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/redirectToURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/swishHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/verifyWithMicrodeposits","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/weChatPayRedirectToApp"],"generated":true},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/STPAPIResponseDecodable-Implementations"],"title":"Default Implementations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentAction","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Next action details for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"code":"STPSetupIntent","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"type":"text","text":" "},{"text":"Check the ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"text":" ","type":"text"},{"text":"property for the details necessary to handle it.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentAction","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentaction"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentaction"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/alipayHandleRedirect":{"navigatorTitle":[{"text":"alipayHandleRedirect","kind":"identifier"}],"role":"symbol","title":"alipayHandleRedirect","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/alipayHandleRedirect","type":"topic","url":"\/documentation\/stripepayments\/stpintentaction\/alipayhandleredirect","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"alipayHandleRedirect","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPIntentActionAlipayHandleRedirect","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionAlipayHandleRedirect"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/oxxoDisplayDetails":{"title":"oxxoDisplayDetails","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/oxxoDisplayDetails","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"oxxoDisplayDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionOXXODisplayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionOXXODisplayDetails"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"oxxoDisplayDetails"}],"url":"\/documentation\/stripepayments\/stpintentaction\/oxxodisplaydetails","abstract":[{"type":"text","text":"The details for displaying OXXO voucher via URL, when "},{"code":"type == .OXXODisplayDetails","type":"codeVoice"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/authorizeWithURL":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/authorizeWithURL","title":"authorizeWithURL","abstract":[{"type":"text","text":"The details for authorizing via URL, when "},{"type":"codeVoice","code":"type == STPIntentActionTypeRedirectToURL"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorizeWithURL"},{"kind":"text","text":": "},{"text":"STPIntentActionRedirectToURL","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL"},{"text":"?","kind":"text"}],"kind":"symbol","deprecated":true,"navigatorTitle":[{"text":"authorizeWithURL","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentaction\/authorizewithurl"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/STPAPIResponseDecodable-Implementations":{"url":"\/documentation\/stripepayments\/stpintentaction\/stpapiresponsedecodable-implementations","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/STPAPIResponseDecodable-Implementations","abstract":[],"title":"STPAPIResponseDecodable Implementations","role":"collectionGroup","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/payNowDisplayQrCode":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentaction\/paynowdisplayqrcode","abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PayNow."}],"title":"payNowDisplayQrCode","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"payNowDisplayQrCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentActionPayNowDisplayQrCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPayNowDisplayQrCode"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"payNowDisplayQrCode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/payNowDisplayQrCode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/boletoDisplayDetails":{"title":"boletoDisplayDetails","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/boletoDisplayDetails","role":"symbol","abstract":[{"type":"text","text":"The details for displaying Boleto voucher via URL, when "},{"code":"type == .boleto","type":"codeVoice"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boletoDisplayDetails","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPIntentActionBoletoDisplayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionBoletoDisplayDetails"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"boletoDisplayDetails"}],"url":"\/documentation\/stripepayments\/stpintentaction\/boletodisplaydetails","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/swishHandleRedirect":{"title":"swishHandleRedirect","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/swishHandleRedirect","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"swishHandleRedirect"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionSwishHandleRedirect","text":"STPIntentActionSwishHandleRedirect","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"swishHandleRedirect","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentaction\/swishhandleredirect","abstract":[{"text":"Contains details for redirecting to the Swish app.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/konbiniDisplayDetails":{"type":"topic","title":"konbiniDisplayDetails","url":"\/documentation\/stripepayments\/stpintentaction\/konbinidisplaydetails","abstract":[{"type":"text","text":"Contains instructions for authenticating a Konbini payment."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"konbiniDisplayDetails"},{"text":": ","kind":"text"},{"text":"STPIntentActionKonbiniDisplayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionKonbiniDisplayDetails"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/konbiniDisplayDetails","navigatorTitle":[{"kind":"identifier","text":"konbiniDisplayDetails"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/cashAppRedirectToApp":{"url":"\/documentation\/stripepayments\/stpintentaction\/cashappredirecttoapp","kind":"symbol","title":"cashAppRedirectToApp","abstract":[{"text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cashAppRedirectToApp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionCashAppRedirectToApp","text":"STPIntentActionCashAppRedirectToApp"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"cashAppRedirectToApp","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/cashAppRedirectToApp"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIntentAction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Next action details for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Check the "},{"code":"type","type":"codeVoice"},{"type":"text","text":" to see which one it is, and then use the related"},{"text":" ","type":"text"},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentAction"},{"type":"text","text":"."}],"title":"STPIntentAction","navigatorTitle":[{"text":"STPIntentAction","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","url":"\/documentation\/stripepayments\/stpintentaction","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentAction":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentAction"}],"deprecated":true,"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentAction","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentaction","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntentAction","kind":"identifier"}],"title":"STPPaymentIntentAction","abstract":[{"type":"text","text":"Action details for an STPPaymentIntent. This is a container for"},{"text":" ","type":"text"},{"text":"the various types that are available. Check the ","type":"text"},{"code":"type","type":"codeVoice"},{"type":"text","text":" to see which one"},{"text":" ","type":"text"},{"type":"text","text":"it is, and then use the related property for the details necessary to handle it."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/type":{"title":"type","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/type","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPIntentActionType","preciseIdentifier":"c:@M@StripePayments@E@STPIntentActionType"}],"url":"\/documentation\/stripepayments\/stpintentaction\/type","navigatorTitle":[{"text":"type","kind":"identifier"}],"type":"topic","abstract":[{"text":"The type of action needed. The value of this field determines which","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"property of this object contains further details about the action."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/redirectToURL":{"url":"\/documentation\/stripepayments\/stpintentaction\/redirecttourl","type":"topic","kind":"symbol","abstract":[{"text":"The details for authorizing via URL, when ","type":"text"},{"code":"type == .redirectToURL","type":"codeVoice"}],"title":"redirectToURL","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectToURL"},{"kind":"text","text":": "},{"text":"STPIntentActionRedirectToURL","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionRedirectToURL"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"redirectToURL"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/redirectToURL"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/verifyWithMicrodeposits":{"url":"\/documentation\/stripepayments\/stpintentaction\/verifywithmicrodeposits","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Contains details describing microdeposits verification flow for US bank accounts"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/verifyWithMicrodeposits","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"verifyWithMicrodeposits","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPIntentActionVerifyWithMicrodeposits","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionVerifyWithMicrodeposits","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"verifyWithMicrodeposits","kind":"identifier"}],"title":"verifyWithMicrodeposits"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/allResponseFields":{"abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpintentaction\/allresponsefields","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/allResponseFields","title":"allResponseFields","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/weChatPayRedirectToApp":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/weChatPayRedirectToApp","title":"weChatPayRedirectToApp","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to the WeChat Pay app."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPayRedirectToApp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionWechatPayRedirectToApp","text":"STPIntentActionWechatPayRedirectToApp","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"weChatPayRedirectToApp"}],"url":"\/documentation\/stripepayments\/stpintentaction\/wechatpayredirecttoapp"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/description":{"role":"symbol","url":"\/documentation\/stripepayments\/stpintentaction\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","type":"topic","title":"description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/description","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/multibancoDisplayDetails":{"title":"multibancoDisplayDetails","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/multibancoDisplayDetails","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multibancoDisplayDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionMultibancoDisplayDetails","text":"STPIntentActionMultibancoDisplayDetails"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"multibancoDisplayDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentaction\/multibancodisplaydetails","abstract":[{"type":"text","text":"The details for displaying Multibanco voucher via URL, when "},{"type":"codeVoice","code":"type == .multibanco"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction/promptPayDisplayQrCode":{"title":"promptPayDisplayQrCode","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/promptPayDisplayQrCode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"promptPayDisplayQrCode"},{"text":": ","kind":"text"},{"text":"STPIntentActionPromptPayDisplayQrCode","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentActionPromptPayDisplayQrCode"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"promptPayDisplayQrCode","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentaction\/promptpaydisplayqrcode","abstract":[{"text":"Contains details for displaying the QR code required for PromptPay.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"title":"STPAPIResponseDecodable","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"type":"text","text":" "},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"STPIntentAction","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPIntentAction"}]},{"value":[{"kind":"identifier","text":"STPIntentAction"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/alipayHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/authorizeWithURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/boletoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/cashAppRedirectToApp","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/konbiniDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/multibancoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/oxxoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/payNowDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/promptPayDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/redirectToURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/swishHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/verifyWithMicrodeposits","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/weChatPayRedirectToApp"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction\/STPAPIResponseDecodable-Implementations"],"title":"Default Implementations"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentAction"],"kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1alipayHandleRedirect\/title","value":"alipayHandleRedirect"},{"value":[{"kind":"identifier","text":"alipayHandleRedirect"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1alipayHandleRedirect\/fragments"},{"value":"oxxoDisplayDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1oxxoDisplayDetails\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1oxxoDisplayDetails\/fragments","op":"replace","value":[{"text":"oxxoDisplayDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1authorizeWithURL\/title","value":"authorizeWithURL"},{"value":[{"kind":"identifier","text":"authorizeWithURL"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1authorizeWithURL\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1payNowDisplayQrCode\/title","value":"payNowDisplayQrCode","op":"replace"},{"value":[{"kind":"identifier","text":"payNowDisplayQrCode"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1payNowDisplayQrCode\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1boletoDisplayDetails\/title","value":"boletoDisplayDetails","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1boletoDisplayDetails\/fragments","value":[{"kind":"identifier","text":"boletoDisplayDetails"}]},{"value":"swishHandleRedirect","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1swishHandleRedirect\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1swishHandleRedirect\/fragments","value":[{"kind":"identifier","text":"swishHandleRedirect"}],"op":"replace"},{"value":"konbiniDisplayDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1konbiniDisplayDetails\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1konbiniDisplayDetails\/fragments","value":[{"text":"konbiniDisplayDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1cashAppRedirectToApp\/title","value":"cashAppRedirectToApp","op":"replace"},{"value":[{"text":"cashAppRedirectToApp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1cashAppRedirectToApp\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title","value":"STPIntentAction"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","op":"replace","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle","op":"replace","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"value":"STPPaymentIntentAction","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentAction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentAction\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentAction"}]},{"value":[{"text":"STPPaymentIntentAction","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentAction\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1type\/title","value":"type"},{"value":[{"text":"type","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1type\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1redirectToURL\/title","value":"redirectToURL"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1redirectToURL\/fragments","value":[{"kind":"identifier","text":"redirectToURL"}]},{"value":"verifyWithMicrodeposits","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1verifyWithMicrodeposits\/title","op":"replace"},{"value":[{"kind":"identifier","text":"verifyWithMicrodeposits"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1verifyWithMicrodeposits\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1allResponseFields\/title","op":"replace","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}]},{"value":"weChatPayRedirectToApp","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1weChatPayRedirectToApp\/title"},{"value":[{"kind":"identifier","text":"weChatPayRedirectToApp"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1weChatPayRedirectToApp\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1multibancoDisplayDetails\/title","value":"multibancoDisplayDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1multibancoDisplayDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"multibancoDisplayDetails"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1promptPayDisplayQrCode\/title","value":"promptPayDisplayQrCode","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction~1promptPayDisplayQrCode\/fragments","value":[{"kind":"identifier","text":"promptPayDisplayQrCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","op":"replace","value":"STPAPIResponseDecodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}