{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionboletodisplaydetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpintentactionboletodisplaydetails"]}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Class","title":"STPIntentActionBoletoDisplayDetails","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionBoletoDisplayDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionBoletoDisplayDetails","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"symbolKind":"class"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/expiresAt","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/hostedVoucherURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/number"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/decodedObject(fromAPIResponse:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"abstract":[{"type":"text","text":"Contains Boleto details necessary for the customer to complete the payment."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","kind":"symbol","title":"STPAPIResponseDecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails","abstract":[{"type":"text","text":"Contains Boleto details necessary for the customer to complete the payment."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionBoletoDisplayDetails","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPIntentActionBoletoDisplayDetails","kind":"identifier"}],"title":"STPIntentActionBoletoDisplayDetails","url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails/number":{"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/number","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"number","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"The boleto voucher number."}],"navigatorTitle":[{"text":"number","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/number","title":"number"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails/description":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails/allResponseFields":{"title":"allResponseFields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/allResponseFields","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/allresponsefields","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails/decodedObject(fromAPIResponse:)":{"url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/decodedobject(fromapiresponse:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/decodedObject(fromAPIResponse:)","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"type":"topic","title":"decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails/expiresAt":{"abstract":[{"text":"The expiry date of the boleto voucher.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"expiresAt"}],"title":"expiresAt","url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/expiresat","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/expiresAt","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionBoletoDisplayDetails/hostedVoucherURL":{"url":"\/documentation\/stripepayments\/stpintentactionboletodisplaydetails\/hostedvoucherurl","kind":"symbol","navigatorTitle":[{"text":"hostedVoucherURL","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/hostedVoucherURL","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hostedVoucherURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}],"title":"hostedVoucherURL","type":"topic","role":"symbol","abstract":[{"text":"The URL to the hosted boleto voucher page, which allows customers to view the boleto voucher.","type":"text"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPIntentActionBoletoDisplayDetails","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/expiresAt","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/hostedVoucherURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/number"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionBoletoDisplayDetails\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"type":"conformsTo","title":"Conforms To"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"op":"replace","value":"STPIntentActionBoletoDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionBoletoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails\/navigatorTitle"},{"op":"replace","value":"number","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1number\/title"},{"op":"replace","value":[{"text":"number","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1number\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1description\/fragments"},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1allResponseFields\/title"},{"op":"replace","value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1allResponseFields\/fragments"},{"op":"replace","value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1decodedObject(fromAPIResponse:)\/fragments"},{"op":"replace","value":"expiresAt","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1expiresAt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"expiresAt"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1expiresAt\/fragments"},{"op":"replace","value":"hostedVoucherURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1hostedVoucherURL\/title"},{"op":"replace","value":[{"kind":"identifier","text":"hostedVoucherURL"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionBoletoDisplayDetails~1hostedVoucherURL\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}