{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/expiresAfter","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/hostedVoucherURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/number"],"anchor":"Instance-Properties"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPIntentActionOXXODisplayDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}],"title":"STPIntentActionOXXODisplayDetails","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}],"symbolKind":"class"},"abstract":[{"text":"Contains OXXO details necessary for the customer to complete the payment.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionOXXODisplayDetails"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails/description":{"kind":"symbol","role":"symbol","title":"description","type":"topic","url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails/number":{"url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/number","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"number","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"number","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"OXXO reference number.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/number","role":"symbol","title":"number"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails/allResponseFields":{"url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/allresponsefields","type":"topic","role":"symbol","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"title":"allResponseFields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/allResponseFields","abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails":{"title":"STPIntentActionOXXODisplayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Contains OXXO details necessary for the customer to complete the payment."}],"url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails/hostedVoucherURL":{"abstract":[{"type":"text","text":"The URL for the hosted OXXO voucher page, which allows customers to view and print an OXXO voucher."}],"navigatorTitle":[{"kind":"identifier","text":"hostedVoucherURL"}],"url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/hostedvoucherurl","role":"symbol","type":"topic","kind":"symbol","title":"hostedVoucherURL","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"hostedVoucherURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/hostedVoucherURL"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails/expiresAfter":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/expiresAfter","url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/expiresafter","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expiresAfter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"expiresAfter"}],"role":"symbol","title":"expiresAfter","type":"topic","abstract":[{"type":"text","text":"The timestamp after which the OXXO voucher expires."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionOXXODisplayDetails/decodedObject(fromAPIResponse:)":{"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionoxxodisplaydetails\/decodedobject(fromapiresponse:)","title":"decodedObject(fromAPIResponse:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/decodedObject(fromAPIResponse:)","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"title":"STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPIntentActionOXXODisplayDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/expiresAfter","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/hostedVoucherURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/number"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionOXXODisplayDetails\/decodedObject(fromAPIResponse:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1number\/title","value":"number"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1number\/fragments","value":[{"text":"number","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1allResponseFields\/title","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/title","value":"STPIntentActionOXXODisplayDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/fragments","value":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails\/navigatorTitle","value":[{"text":"STPIntentActionOXXODisplayDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1hostedVoucherURL\/title","value":"hostedVoucherURL"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1hostedVoucherURL\/fragments","value":[{"text":"hostedVoucherURL","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1expiresAfter\/title","value":"expiresAfter"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1expiresAfter\/fragments","value":[{"kind":"identifier","text":"expiresAfter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionOXXODisplayDetails~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]}]}]}