{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/s9EscapableP","doc:\/\/com.stripe.stripe-payments\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPIntentActionPayNowDisplayQrCode","title":"STPIntentActionPayNowDisplayQrCode","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Contains instructions for presenting the QR code required to complete a PayNow payment.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPIntentActionPayNowDisplayQrCode","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/hostedInstructionsURL"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/STPAPIResponseDecodable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode/description":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description","abstract":[{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/description","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/description","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode/hostedInstructionsURL":{"abstract":[{"text":"The URL to open which contains instructions on how to complete the payment.","type":"text"}],"role":"symbol","kind":"symbol","title":"hostedInstructionsURL","navigatorTitle":[{"text":"hostedInstructionsURL","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hostedInstructionsURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/hostedinstructionsurl","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/hostedInstructionsURL"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}],"abstract":[{"type":"text","text":"Contains instructions for presenting the QR code required to complete a PayNow payment."},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPIntentActionPayNowDisplayQrCode"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode","type":"topic","title":"STPIntentActionPayNowDisplayQrCode","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode","role":"symbol"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"title":"STPAPIResponseDecodable","abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode/STPAPIResponseDecodable-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/stpapiresponsedecodable-implementations","kind":"article","title":"STPAPIResponseDecodable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/STPAPIResponseDecodable-Implementations"},"doc://com.stripe.stripe-payments/s9EscapableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s9EscapableP","title":"Swift.Escapable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode/allResponseFields":{"abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/allresponsefields","kind":"symbol","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"title":"allResponseFields","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/allResponseFields"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPIntentActionPayNowDisplayQrCode","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/hostedInstructionsURL"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/STPAPIResponseDecodable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1description\/title","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1description\/fragments","op":"replace"},{"value":"hostedInstructionsURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1hostedInstructionsURL\/title","op":"replace"},{"value":[{"text":"hostedInstructionsURL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1hostedInstructionsURL\/fragments","op":"replace"},{"value":"STPIntentActionPayNowDisplayQrCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/title","op":"replace"},{"value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/fragments","op":"replace"},{"value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/navigatorTitle","op":"replace"},{"value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","op":"replace"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","op":"replace"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","op":"replace"},{"value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1allResponseFields\/title","op":"replace"},{"value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1allResponseFields\/fragments","op":"replace"}]}]}