{"variants":[{"paths":["\/documentation\/stripepayments\/stpintentactiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpintentactiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"type":"text","text":"Types of next actions for "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":" and "},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" will handle any next actions for you."}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@M@StripePayments@E@STPIntentActionType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"title":"STPIntentActionType","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionType"}]},"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/BLIKAuthorize","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/OXXODisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/alipayHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/boletoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/cashAppRedirectToApp","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/konbiniDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/multibancoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/payNowDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/promptpayDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/redirectToURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/swishHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/upiAwaitNotification","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/useStripeSDK","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/verifyWithMicrodeposits","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/weChatPayRedirectToApp"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/boletoDisplayDetails":{"abstract":[{"type":"text","text":"The action type is Boleto payment. We provide "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to display the Boleto voucher."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/boletoDisplayDetails","role":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype\/boletodisplaydetails","title":"STPIntentActionType.boletoDisplayDetails","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boletoDisplayDetails","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionTypeBoletoDisplayDetails","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/init(rawValue:)":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stpintentactiontype\/init(rawvalue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/init(rawValue:)","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/cashAppRedirectToApp":{"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cashAppRedirectToApp","kind":"identifier"}],"role":"symbol","title":"STPIntentActionType.cashAppRedirectToApp","url":"\/documentation\/stripepayments\/stpintentactiontype\/cashappredirecttoapp","navigatorTitle":[{"text":"STPIntentActionTypeCashAppRedirectToApp","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/cashAppRedirectToApp","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Cash App."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/payNowDisplayQrCode":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"payNowDisplayQrCode"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/paynowdisplayqrcode","abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PayNow."}],"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypePayNowDisplayQrCode"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/payNowDisplayQrCode","title":"STPIntentActionType.payNowDisplayQrCode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/upiAwaitNotification":{"type":"topic","abstract":[{"text":"The action type for UPI payment methods. The customer must complete the transaction in their banking app within 5 minutes.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"upiAwaitNotification","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/upiawaitnotification","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/upiAwaitNotification","kind":"symbol","title":"STPIntentActionType.upiAwaitNotification","navigatorTitle":[{"text":"STPIntentActionTypeUpiAwaitNotification","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/alipayHandleRedirect":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alipayHandleRedirect"}],"title":"STPIntentActionType.alipayHandleRedirect","abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to Alipay App or website."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/alipayHandleRedirect","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeAlipayHandleRedirect"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype\/alipayhandleredirect"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/redirectToURL":{"abstract":[{"type":"text","text":"The payment intent needs to be authorized by the user. We provide"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle the url redirections necessary."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"redirectToURL","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/redirecttourl","role":"symbol","title":"STPIntentActionType.redirectToURL","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/redirectToURL","navigatorTitle":[{"text":"STPIntentActionTypeRedirectToURL","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/verifyWithMicrodeposits":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/verifyWithMicrodeposits","kind":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype\/verifywithmicrodeposits","title":"STPIntentActionType.verifyWithMicrodeposits","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Contains details describing the microdeposits verification flow for US Bank Account payments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyWithMicrodeposits","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionTypeVerifyWithMicrodeposits","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stpintentactiontype\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stpintentactiontype\/equatable-implementations","abstract":[],"role":"collectionGroup","title":"Equatable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/OXXODisplayDetails":{"title":"STPIntentActionType.OXXODisplayDetails","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OXXODisplayDetails","kind":"identifier"}],"abstract":[{"text":"The action type is OXXO payment. We provide ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" to display","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the OXXO voucher."}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/oxxodisplaydetails","navigatorTitle":[{"text":"STPIntentActionTypeOXXODisplayDetails","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/OXXODisplayDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/multibancoDisplayDetails":{"navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeMultibancoDisplayDetails"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/multibancoDisplayDetails","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"multibancoDisplayDetails"}],"abstract":[{"type":"text","text":"The action type is Multibanco payment. We provide "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to display the Multibanco voucher."}],"type":"topic","kind":"symbol","title":"STPIntentActionType.multibancoDisplayDetails","url":"\/documentation\/stripepayments\/stpintentactiontype\/multibancodisplaydetails"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType":{"navigatorTitle":[{"text":"STPIntentActionType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpintentactiontype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"}],"abstract":[{"text":"Types of next actions for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to inspect this yourself; "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" will handle any next actions for you."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType","role":"symbol","kind":"symbol","title":"STPIntentActionType","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/useStripeSDK":{"url":"\/documentation\/stripepayments\/stpintentactiontype\/usestripesdk","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeUseStripeSDK"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The payment intent requires additional action handled by "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":"."}],"title":"STPIntentActionType.useStripeSDK","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/useStripeSDK","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"useStripeSDK"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/konbiniDisplayDetails":{"type":"topic","title":"STPIntentActionType.konbiniDisplayDetails","abstract":[{"type":"text","text":"Contains instructions for completing Konbini payments."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"konbiniDisplayDetails"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/konbiniDisplayDetails","url":"\/documentation\/stripepayments\/stpintentactiontype\/konbinidisplaydetails","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeKonbiniDisplayDetails"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/unknown":{"role":"symbol","abstract":[{"text":"This is an unknown action that’s been added since the SDK","type":"text"},{"text":" ","type":"text"},{"text":"was last updated.","type":"text"},{"text":" ","type":"text"},{"text":"Update your SDK, or use the ","type":"text"},{"type":"codeVoice","code":"nextAction.allResponseFields"},{"text":" ","type":"text"},{"text":"for custom handling.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/unknown","url":"\/documentation\/stripepayments\/stpintentactiontype\/unknown","kind":"symbol","title":"STPIntentActionType.unknown","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"navigatorTitle":[{"text":"STPIntentActionTypeUnknown","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stpintentactiontype\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/CustomStringConvertible-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/promptpayDisplayQrCode":{"abstract":[{"type":"text","text":"Contains details for displaying the QR code required for PromptPay."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"promptpayDisplayQrCode"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/promptpaydisplayqrcode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/promptpayDisplayQrCode","role":"symbol","kind":"symbol","title":"STPIntentActionType.promptpayDisplayQrCode","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypePromptpayDisplayQrCode"}]},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/weChatPayRedirectToApp":{"abstract":[{"type":"text","text":"Contains instructions for authenticating a payment by redirecting your customer to the WeChat Pay App."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"weChatPayRedirectToApp"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/weChatPayRedirectToApp","role":"symbol","title":"STPIntentActionType.weChatPayRedirectToApp","url":"\/documentation\/stripepayments\/stpintentactiontype\/wechatpayredirecttoapp","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeWeChatPayRedirectToApp"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/swishHandleRedirect":{"abstract":[{"type":"text","text":"Contains details for redirecting to the Swish app."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeSwishHandleRedirect"}],"title":"STPIntentActionType.swishHandleRedirect","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/swishHandleRedirect","role":"symbol","url":"\/documentation\/stripepayments\/stpintentactiontype\/swishhandleredirect","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"swishHandleRedirect"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionType/BLIKAuthorize":{"title":"STPIntentActionType.BLIKAuthorize","abstract":[{"type":"text","text":"The action type for BLIK payment methods. The customer must authorize the transaction in their banking app within 1 minute."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/BLIKAuthorize","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"BLIKAuthorize"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentActionTypeBLIKAuthorize"}],"url":"\/documentation\/stripepayments\/stpintentactiontype\/blikauthorize","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"STPIntentActionType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPIntentActionType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPIntentActionType"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/BLIKAuthorize","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/OXXODisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/alipayHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/boletoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/cashAppRedirectToApp","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/konbiniDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/multibancoDisplayDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/payNowDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/promptpayDisplayQrCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/redirectToURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/swishHandleRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/upiAwaitNotification","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/useStripeSDK","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/verifyWithMicrodeposits","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionType\/weChatPayRedirectToApp"],"generated":true,"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentActionType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"STPIntentActionTypeBoletoDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1boletoDisplayDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeBoletoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1boletoDisplayDetails\/fragments"},{"op":"replace","value":"STPIntentActionTypeCashAppRedirectToApp","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1cashAppRedirectToApp\/title"},{"op":"replace","value":[{"text":"STPIntentActionTypeCashAppRedirectToApp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1cashAppRedirectToApp\/fragments"},{"op":"replace","value":"STPIntentActionTypePayNowDisplayQrCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1payNowDisplayQrCode\/title"},{"op":"replace","value":[{"text":"STPIntentActionTypePayNowDisplayQrCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1payNowDisplayQrCode\/fragments"},{"op":"replace","value":"STPIntentActionTypeUpiAwaitNotification","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1upiAwaitNotification\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeUpiAwaitNotification"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1upiAwaitNotification\/fragments"},{"op":"replace","value":"STPIntentActionTypeAlipayHandleRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1alipayHandleRedirect\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeAlipayHandleRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1alipayHandleRedirect\/fragments"},{"op":"replace","value":"STPIntentActionTypeRedirectToURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1redirectToURL\/title"},{"op":"replace","value":[{"text":"STPIntentActionTypeRedirectToURL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1redirectToURL\/fragments"},{"op":"replace","value":"STPIntentActionTypeVerifyWithMicrodeposits","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1verifyWithMicrodeposits\/title"},{"op":"replace","value":[{"text":"STPIntentActionTypeVerifyWithMicrodeposits","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1verifyWithMicrodeposits\/fragments"},{"op":"replace","value":"STPIntentActionTypeOXXODisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1OXXODisplayDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeOXXODisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1OXXODisplayDetails\/fragments"},{"op":"replace","value":"STPIntentActionTypeMultibancoDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1multibancoDisplayDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeMultibancoDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1multibancoDisplayDetails\/fragments"},{"op":"replace","value":"STPIntentActionType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/title"},{"op":"replace","value":[{"text":"STPIntentActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/fragments"},{"op":"replace","value":[{"text":"STPIntentActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType\/navigatorTitle"},{"op":"replace","value":"STPIntentActionTypeUseStripeSDK","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1useStripeSDK\/title"},{"op":"replace","value":[{"text":"STPIntentActionTypeUseStripeSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1useStripeSDK\/fragments"},{"op":"replace","value":"STPIntentActionTypeKonbiniDisplayDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1konbiniDisplayDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeKonbiniDisplayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1konbiniDisplayDetails\/fragments"},{"op":"replace","value":"STPIntentActionTypeUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1unknown\/title"},{"op":"replace","value":[{"text":"STPIntentActionTypeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1unknown\/fragments"},{"op":"replace","value":"STPIntentActionTypePromptpayDisplayQrCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1promptpayDisplayQrCode\/title"},{"op":"replace","value":[{"text":"STPIntentActionTypePromptpayDisplayQrCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1promptpayDisplayQrCode\/fragments"},{"op":"replace","value":"STPIntentActionTypeWeChatPayRedirectToApp","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1weChatPayRedirectToApp\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeWeChatPayRedirectToApp"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1weChatPayRedirectToApp\/fragments"},{"op":"replace","value":"STPIntentActionTypeSwishHandleRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1swishHandleRedirect\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeSwishHandleRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1swishHandleRedirect\/fragments"},{"op":"replace","value":"STPIntentActionTypeBLIKAuthorize","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1BLIKAuthorize\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPIntentActionTypeBLIKAuthorize"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionType~1BLIKAuthorize\/fragments"}]}]}