{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"metadata":{"symbolKind":"enum","title":"STPKlarnaPaymentMethods","roleHeading":"Enumeration","navigatorTitle":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPKlarnaPaymentMethods","modules":[{"name":"StripePayments"}],"role":"symbol"},"abstract":[{"type":"text","text":"Custom payment methods for Klarna"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Klarna#Create-Source"}]}],"style":"note","type":"aside","name":"See Also"}]}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/installments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/none","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4OrInstallments"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/init(rawValue:)"],"generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnapaymentmethods"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/payIn4OrInstallments":{"title":"STPKlarnaPaymentMethods.payIn4OrInstallments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4OrInstallments","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/payin4orinstallments","abstract":[{"type":"text","text":"Offer payments over 4 or an arbitrary number of installments."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"payIn4OrInstallments"}],"navigatorTitle":[{"text":"STPKlarnaPaymentMethodsPayIn4OrInstallments","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/CustomStringConvertible-Implementations":{"title":"CustomStringConvertible Implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/customstringconvertible-implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/payIn4":{"type":"topic","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/payin4","title":"STPKlarnaPaymentMethods.payIn4","abstract":[{"type":"text","text":"Offer payments over 4 installments. (a.k.a. Pay Later in 4)"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4","kind":"symbol","navigatorTitle":[{"text":"STPKlarnaPaymentMethodsPayIn4","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"payIn4","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/none":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"STPKlarnaPaymentMethodsNone","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/none","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/none","title":"STPKlarnaPaymentMethods.none","abstract":[{"type":"text","text":"Don’t specify any custom payment methods."}]},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/init(rawValue:)":{"abstract":[],"type":"topic","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/init(rawValue:)","title":"init(rawValue:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/installments":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"installments","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/installments","navigatorTitle":[{"text":"STPKlarnaPaymentMethodsInstallments","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/installments","type":"topic","abstract":[{"type":"text","text":"Offer payments over an arbitrary number of installments. (a.k.a. Slice It)"}],"title":"STPKlarnaPaymentMethods.installments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/rawrepresentable-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"type":"topic"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"navigatorTitle":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Custom payment methods for Klarna","type":"text"}],"title":"STPKlarnaPaymentMethods","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaPaymentMethods/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/Equatable-Implementations","url":"\/documentation\/stripepayments\/stpklarnapaymentmethods\/equatable-implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPKlarnaPaymentMethods"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"STPKlarnaPaymentMethods"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/installments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/none","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaPaymentMethods\/payIn4OrInstallments"],"generated":true}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPKlarnaPaymentMethods","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1payIn4OrInstallments\/title","value":"STPKlarnaPaymentMethodsPayIn4OrInstallments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1payIn4OrInstallments\/fragments","value":[{"text":"STPKlarnaPaymentMethodsPayIn4OrInstallments","kind":"identifier"}]},{"value":"STPKlarnaPaymentMethodsPayIn4","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1payIn4\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1payIn4\/fragments","value":[{"text":"STPKlarnaPaymentMethodsPayIn4","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1none\/title","value":"STPKlarnaPaymentMethodsNone","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1none\/fragments","value":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsNone"}],"op":"replace"},{"op":"replace","value":"STPKlarnaPaymentMethodsInstallments","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1installments\/title"},{"value":[{"kind":"identifier","text":"STPKlarnaPaymentMethodsInstallments"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods~1installments\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/title","op":"replace","value":"STPKlarnaPaymentMethods"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/fragments","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaPaymentMethods\/navigatorTitle","op":"replace","value":[{"text":"STPKlarnaPaymentMethods","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}