{"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitem"]}],"sections":[],"abstract":[{"type":"text","text":"An object representing a line item in a Klarna source."}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/init(itemType:itemDescription:quantity:totalAmount:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/itemDescription","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/itemType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/quantity","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/totalAmount"],"anchor":"Instance-Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPKlarnaLineItem"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Klarna#Create-Source"}]}],"name":"See Also","style":"note","type":"aside"}]}],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem","role":"symbol","roleHeading":"Class","title":"STPKlarnaLineItem","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPKlarnaLineItem","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItem"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/init(itemType:itemDescription:quantity:totalAmount:)":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Initialize this "},{"type":"codeVoice","code":"STPKlarnaLineItem"},{"type":"text","text":" with a set of parameters."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"itemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType","text":"STPKlarnaLineItemType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"itemDescription"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"quantity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"totalAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(itemType:itemDescription:quantity:totalAmount:)","url":"\/documentation\/stripepayments\/stpklarnalineitem\/init(itemtype:itemdescription:quantity:totalamount:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/init(itemType:itemDescription:quantity:totalAmount:)","navigatorTitle":[{"kind":"identifier","text":"initWithItemType:itemDescription:quantity:totalAmount:"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/itemType":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"The line item’s type. One of ","type":"text"},{"code":"sku","type":"codeVoice"},{"type":"text","text":" (for a product), "},{"type":"codeVoice","code":"tax"},{"type":"text","text":" (for taxes), or "},{"code":"shipping","type":"codeVoice"},{"text":" (for shipping costs).","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"itemType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaLineItemType","text":"STPKlarnaLineItemType"}],"title":"itemType","url":"\/documentation\/stripepayments\/stpklarnalineitem\/itemtype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/itemType","navigatorTitle":[{"kind":"identifier","text":"itemType"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/itemDescription":{"kind":"symbol","title":"itemDescription","url":"\/documentation\/stripepayments\/stpklarnalineitem\/itemdescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"itemDescription","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/itemDescription","abstract":[{"text":"The human-readable description for the line item.","type":"text"}]},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/quantity":{"kind":"symbol","title":"quantity","url":"\/documentation\/stripepayments\/stpklarnalineitem\/quantity","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"quantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"}],"navigatorTitle":[{"kind":"identifier","text":"quantity"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/quantity","abstract":[{"text":"The quantity to display for this line item.","type":"text"}]},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem/totalAmount":{"kind":"symbol","title":"totalAmount","url":"\/documentation\/stripepayments\/stpklarnalineitem\/totalamount","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalAmount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"}],"navigatorTitle":[{"kind":"identifier","text":"totalAmount"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/totalAmount","abstract":[{"text":"The total price of this line item.","type":"text"},{"type":"text","text":" "},{"text":"Note: This is the total price after multiplying by the quantity, not","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the price of an individual item. It is denominated in the currency"},{"text":" ","type":"text"},{"type":"text","text":"of the STPSourceParams which contains it."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItem":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"An object representing a line item in a Klarna source.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPKlarnaLineItem"}],"title":"STPKlarnaLineItem","url":"\/documentation\/stripepayments\/stpklarnalineitem","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem","navigatorTitle":[{"text":"STPKlarnaLineItem","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPKlarnaLineItem","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/itemDescription","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/itemType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/quantity","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/totalAmount"],"generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItem\/init(itemType:itemDescription:quantity:totalAmount:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPKlarnaLineItem"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1init(itemType:itemDescription:quantity:totalAmount:)\/title","value":"initWithItemType:itemDescription:quantity:totalAmount:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1init(itemType:itemDescription:quantity:totalAmount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithItemType:itemDescription:quantity:totalAmount:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1itemType\/title","value":"itemType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1itemType\/fragments","value":[{"kind":"identifier","text":"itemType"}]},{"value":"itemDescription","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1itemDescription\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1itemDescription\/fragments","value":[{"kind":"identifier","text":"itemDescription"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1quantity\/title","value":"quantity"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1quantity\/fragments","value":[{"text":"quantity","kind":"identifier"}]},{"value":"totalAmount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1totalAmount\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem~1totalAmount\/fragments","value":[{"text":"totalAmount","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPKlarnaLineItem","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/fragments","value":[{"text":"STPKlarnaLineItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItem\/navigatorTitle","value":[{"kind":"identifier","text":"STPKlarnaLineItem"}],"op":"replace"}]}]}