{"metadata":{"roleHeading":"Enumeration","title":"STPKlarnaLineItemType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPKlarnaLineItemType","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPKlarnaLineItemType","role":"symbol","symbolKind":"enum"},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPKlarnaLineItemType"}]}]}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/SKU","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/tax"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/RawRepresentable-Implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType"},"abstract":[{"text":"The type of the Klarna line item.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/customstringconvertible-implementations","kind":"article","title":"CustomStringConvertible Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/CustomStringConvertible-Implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/RawRepresentable-Implementations","url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/tax":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tax"}],"abstract":[{"text":"The line item for taxes","type":"text"}],"role":"symbol","title":"STPKlarnaLineItemType.tax","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemTypeTax"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/tax","url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/tax"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/SKU":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/SKU","abstract":[{"text":"The line item for a product","type":"text"}],"title":"STPKlarnaLineItemType.SKU","url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/sku","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemTypeSKU"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SKU"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/shipping":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/shipping","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shipping"}],"role":"symbol","title":"STPKlarnaLineItemType.shipping","type":"topic","navigatorTitle":[{"text":"STPKlarnaLineItemTypeShipping","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/shipping","abstract":[{"text":"The line item for shipping costs","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","kind":"symbol","role":"symbol","abstract":[{"text":"The type of the Klarna line item.","type":"text"}],"navigatorTitle":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"title":"STPKlarnaLineItemType","type":"topic","url":"\/documentation\/stripepayments\/stpklarnalineitemtype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPKlarnaLineItemType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/init(rawValue:)","role":"symbol"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/equatable-implementations","kind":"article","title":"Equatable Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/Equatable-Implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPKlarnaLineItemType","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"path":"\/metadata\/fragments"},{"value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/SKU","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/tax"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPKlarnaLineItemType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1tax\/title","value":"STPKlarnaLineItemTypeTax"},{"op":"replace","value":[{"kind":"identifier","text":"STPKlarnaLineItemTypeTax"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1tax\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1SKU\/title","op":"replace","value":"STPKlarnaLineItemTypeSKU"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1SKU\/fragments","value":[{"text":"STPKlarnaLineItemTypeSKU","kind":"identifier"}]},{"value":"STPKlarnaLineItemTypeShipping","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1shipping\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1shipping\/fragments","value":[{"text":"STPKlarnaLineItemTypeShipping","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","value":"STPKlarnaLineItemType","op":"replace"},{"value":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments"}]}]}
