{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/offline","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/online"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/RawRepresentable-Implementations"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","metadata":{"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"title":"STPMandateCustomerAcceptanceType","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"externalID":"c:@M@StripePayments@E@STPMandateCustomerAcceptanceType"},"abstract":[{"text":"The type of customer acceptance information included with the Mandate.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptancetype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmandatecustomeracceptancetype"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/CustomStringConvertible-Implementations":{"type":"topic","title":"CustomStringConvertible Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/customstringconvertible-implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/online":{"title":"STPMandateCustomerAcceptanceType.online","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/online","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPMandateCustomerAcceptanceTypeOnline","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A Mandate that was accepted online."}],"url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/online","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"online","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/init(rawValue:)","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/offline":{"url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/offline","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/offline","kind":"symbol","navigatorTitle":[{"text":"STPMandateCustomerAcceptanceTypeOffline","kind":"identifier"}],"type":"topic","title":"STPMandateCustomerAcceptanceType.offline","role":"symbol","abstract":[{"text":"A Mandate that was accepted offline.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"offline","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/equatable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType/RawRepresentable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/RawRepresentable-Implementations","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype\/rawrepresentable-implementations","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceType":{"type":"topic","abstract":[{"type":"text","text":"The type of customer acceptance information included with the Mandate."}],"title":"STPMandateCustomerAcceptanceType","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptancetype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"navigatorTitle":[{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPMandateCustomerAcceptanceType","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/offline","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceType\/online"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateCustomerAcceptanceType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPMandateCustomerAcceptanceTypeOnline","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType~1online\/title","op":"replace"},{"value":[{"text":"STPMandateCustomerAcceptanceTypeOnline","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType~1online\/fragments","op":"replace"},{"value":"STPMandateCustomerAcceptanceTypeOffline","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType~1offline\/title","op":"replace"},{"value":[{"text":"STPMandateCustomerAcceptanceTypeOffline","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType~1offline\/fragments","op":"replace"},{"value":"STPMandateCustomerAcceptanceType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceType\/navigatorTitle","op":"replace"}]}]}