{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMicrodepositType","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/amounts","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/descriptorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/unknown"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMicrodepositType","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPMicrodepositType","navigatorTitle":[{"kind":"identifier","text":"STPMicrodepositType"}],"role":"symbol","title":"STPMicrodepositType","symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"StripePayments"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/s9EscapableP","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpmicrodeposittype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmicrodeposittype"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType":{"url":"\/documentation\/stripepayments\/stpmicrodeposittype","navigatorTitle":[{"kind":"identifier","text":"STPMicrodepositType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType","title":"STPMicrodepositType","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMicrodepositType"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stpmicrodeposittype\/customstringconvertible-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/CustomStringConvertible-Implementations","kind":"article","role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"type":"topic"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/descriptorCode":{"type":"topic","url":"\/documentation\/stripepayments\/stpmicrodeposittype\/descriptorcode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/descriptorCode","abstract":[{"type":"text","text":"A single micro-deposit sent to the customer’s bank account with a unique descriptor code"}],"title":"STPMicrodepositType.descriptorCode","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPMicrodepositTypeDescriptorCode","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"descriptorCode","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/unknown":{"url":"\/documentation\/stripepayments\/stpmicrodeposittype\/unknown","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/unknown","kind":"symbol","navigatorTitle":[{"text":"STPMicrodepositTypeUnknown","kind":"identifier"}],"role":"symbol","title":"STPMicrodepositType.unknown","abstract":[{"text":"This is an unknown type that’s been added since the SDK","type":"text"},{"text":" ","type":"text"},{"text":"was last updated.","type":"text"},{"text":" ","type":"text"},{"text":"Update your SDK, or use the ","type":"text"},{"code":"allResponseFields","type":"codeVoice"},{"text":" ","type":"text"},{"text":"for custom handling.","type":"text"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/Equatable-Implementations","type":"topic","kind":"article","url":"\/documentation\/stripepayments\/stpmicrodeposittype\/equatable-implementations"},"doc://com.stripe.stripe-payments/s9EscapableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s9EscapableP","title":"Swift.Escapable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/init(rawValue:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepayments\/stpmicrodeposittype\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpmicrodeposittype\/rawrepresentable-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMicrodepositType/amounts":{"type":"topic","url":"\/documentation\/stripepayments\/stpmicrodeposittype\/amounts","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/amounts","abstract":[{"type":"text","text":"Two non-unique micro-deposits to the customer’s bank account"}],"title":"STPMicrodepositType.amounts","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPMicrodepositTypeAmounts","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amounts","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPMicrodepositType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPMicrodepositType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPMicrodepositType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/amounts","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/descriptorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMicrodepositType\/unknown"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMicrodepositType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/title","op":"replace","value":"STPMicrodepositType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPMicrodepositType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType\/navigatorTitle","value":[{"text":"STPMicrodepositType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1descriptorCode\/title","value":"STPMicrodepositTypeDescriptorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1descriptorCode\/fragments","value":[{"text":"STPMicrodepositTypeDescriptorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1unknown\/title","value":"STPMicrodepositTypeUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1unknown\/fragments","value":[{"text":"STPMicrodepositTypeUnknown","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1amounts\/title","value":"STPMicrodepositTypeAmounts"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMicrodepositType~1amounts\/fragments","value":[{"text":"STPMicrodepositTypeAmounts","kind":"identifier"}]}]}]}