{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodShopPayParams","title":"STPPaymentMethodShopPayParams","fragments":[{"kind":"identifier","text":"STPPaymentMethodShopPayParams"}],"roleHeading":"Class","navigatorTitle":[{"text":"STPPaymentMethodShopPayParams","kind":"identifier"}],"symbolKind":"class","role":"symbol"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/externalSourceId"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/init"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/propertyNamesToFormFieldNamesMapping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/rootObjectName"],"anchor":"Type-Methods","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodShopPayParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"An object representing parameters used to create a ShopPay Payment Method","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodshoppayparams"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPayParams/init":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/init","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodshoppayparams\/init","role":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPayParams/additionalAPIParameters":{"title":"additionalAPIParameters","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/additionalAPIParameters","abstract":[],"kind":"symbol","fragments":[{"kind":"identifier","text":"additionalAPIParameters"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodshoppayparams\/additionalapiparameters","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPayParams/rootObjectName":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/rootObjectName","title":"rootObjectName","role":"symbol","kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodshoppayparams\/rootobjectname","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}],"title":"STPFormEncodable","url":"\/documentation\/stripepayments\/stpformencodable","type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPayParams/externalSourceId":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/externalSourceId","role":"symbol","fragments":[{"kind":"identifier","text":"externalSourceId"}],"url":"\/documentation\/stripepayments\/stppaymentmethodshoppayparams\/externalsourceid","type":"topic","kind":"symbol","title":"externalSourceId","abstract":[{"type":"text","text":"Corresponding externalSourceId. Required."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPayParams":{"title":"STPPaymentMethodShopPayParams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodshoppayparams","fragments":[{"text":"STPPaymentMethodShopPayParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a ShopPay Payment Method"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPayParams/propertyNamesToFormFieldNamesMapping":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodshoppayparams\/propertynamestoformfieldnamesmapping","kind":"symbol","title":"propertyNamesToFormFieldNamesMapping","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams\/propertyNamesToFormFieldNamesMapping","role":"symbol","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"fragments":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"STPFormEncodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"value":[{"kind":"identifier","text":"STPFormEncodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"value":[{"text":"STPFormEncodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}