{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/automatic","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/manual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/unknown"],"title":"Enumeration Cases"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/init(rawValue:)"],"title":"Initializers"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod"},"metadata":{"title":"STPPaymentIntentConfirmationMethod","externalID":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod","role":"symbol","roleHeading":"Enumeration","symbolKind":"enum","navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}]},"abstract":[{"type":"text","text":"Confirmation methods for a STPPaymentIntent"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/automatic":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/automatic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/automatic","abstract":[{"type":"text","text":"Confirmed via secret key"}],"type":"topic","title":"STPPaymentIntentConfirmationMethod.automatic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodAutomatic"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/manual":{"abstract":[{"text":"Confirmed via publishable key","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/manual","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodManual"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/manual","kind":"symbol","role":"symbol","title":"STPPaymentIntentConfirmationMethod.manual","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/init(rawValue:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/Equatable-Implementations","kind":"article","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/equatable-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/unknown":{"title":"STPPaymentIntentConfirmationMethod.unknown","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/unknown","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/unknown","navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethodUnknown","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"abstract":[{"type":"text","text":"Unknown confirmation method"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/customstringconvertible-implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/CustomStringConvertible-Implementations","role":"collectionGroup","abstract":[],"type":"topic","title":"CustomStringConvertible Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod":{"title":"STPPaymentIntentConfirmationMethod","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"abstract":[{"text":"Confirmation methods for a STPPaymentIntent","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/RawRepresentable-Implementations","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","abstract":[],"kind":"article"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentIntentConfirmationMethod","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/automatic","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/manual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/unknown"],"anchor":"Enumeration-Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"STPPaymentIntentConfirmationMethodAutomatic","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1automatic\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodAutomatic"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1automatic\/fragments","op":"replace"},{"value":"STPPaymentIntentConfirmationMethodManual","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1manual\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentConfirmationMethodManual","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1manual\/fragments","op":"replace"},{"value":"STPPaymentIntentConfirmationMethodUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1unknown\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1unknown\/fragments","op":"replace"},{"value":"STPPaymentIntentConfirmationMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/navigatorTitle","op":"replace"}]}]}