{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/apiClient","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/simulateAppToAppRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/threeDSCustomizationSettings"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment(_:with:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPaymentIntent(params:authenticationContext:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPaymentIntent(params:authenticationContext:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(_:with:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(params:authenticationContext:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(params:authenticationContext:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forPayment:with:returnURL:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forSetupIntent:with:returnURL:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/errorDomain","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/sharedHandler"],"generated":true,"anchor":"Type-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/shared()"],"generated":true,"anchor":"Type-Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/SFSafariViewControllerDelegate-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/objc(pl)SFSafariViewControllerDelegate","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"name":"See Also","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"https:\/\/stripe.com\/docs\/payments\/3d-secure"}]}],"style":"note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandler"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentHandler","navigatorTitle":[{"text":"STPPaymentHandler","kind":"identifier"}],"title":"STPPaymentHandler","role":"symbol","symbolKind":"class"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmPaymentIntent(params:authenticationContext:)":{"title":"confirmPaymentIntent(params:authenticationContext:)","url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmpaymentintent(params:authenticationcontext:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPaymentIntent(params:authenticationContext:)","role":"symbol","abstract":[{"type":"text","text":"Confirms the PaymentIntent using the provided "},{"code":"params","type":"codeVoice"},{"type":"text","text":" and handles any next actions required to authenticate the PaymentIntent."}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","text":"STPPaymentHandlerActionStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}]},"doc://com.stripe.stripe-payments/@M@StripeCore@objc(pl)STPURLCallbackListener":{"identifier":"doc:\/\/com.stripe.stripe-payments\/@M@StripeCore@objc(pl)STPURLCallbackListener","type":"unresolvable","title":"STPURLCallbackListener"},"doc://com.stripe.stripe-payments/objc(pl)SFSafariViewControllerDelegate":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)SFSafariViewControllerDelegate","title":"SFSafariViewControllerDelegate"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/shared()":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/shared()","abstract":[{"type":"text","text":"The globally shared instance of "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":"."}],"type":"topic","role":"symbol","title":"shared()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentHandler","text":"STPPaymentHandler"}],"navigatorTitle":[{"kind":"identifier","text":"shared"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler\/shared()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/SFSafariViewControllerDelegate-Implementations":{"url":"\/documentation\/stripepayments\/stppaymenthandler\/sfsafariviewcontrollerdelegate-implementations","title":"SFSafariViewControllerDelegate Implementations","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/SFSafariViewControllerDelegate-Implementations","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmSetupIntent(params:authenticationContext:)":{"abstract":[{"text":"Confirms the SetupIntent using the provided parameters and handles any next actions required to authenticate the SetupIntent.","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(params:authenticationContext:)","title":"confirmSetupIntent(params:authenticationContext:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"params","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus"},{"text":", ","kind":"text"},{"text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?)","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(params:authenticationcontext:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)":{"abstract":[{"type":"text","text":"Handles any "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":" required to authenticate the PaymentIntent."},{"type":"text","text":" "},{"type":"text","text":"Call this method if you are using server-side confirmation."}],"title":"handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentIntentClientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","text":"STPPaymentHandlerActionStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"STPPaymentIntent","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?)"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(paymentintentclientsecret:authenticationcontext:returnurl:)"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/threeDSCustomizationSettings":{"role":"symbol","title":"threeDSCustomizationSettings","navigatorTitle":[{"kind":"identifier","text":"threeDSCustomizationSettings"}],"abstract":[{"text":"Customizable settings to use when performing 3DS2 authentication.","type":"text"},{"text":" ","type":"text"},{"text":"Note: Configure this before calling any methods.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"STPThreeDSCustomizationSettings()"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler\/threedscustomizationsettings","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/threeDSCustomizationSettings","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDSCustomizationSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPThreeDSCustomizationSettings","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings"}]},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(paymentintentclientsecret:authenticationcontext:returnurl:completion:)","abstract":[{"text":"Handles any ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"text":" required to authenticate the PaymentIntent.","type":"text"},{"text":" ","type":"text"},{"text":"Call this method if you are using server-side confirmation.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"paymentIntentClientSecret"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:"}],"title":"handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmPaymentIntent(params:authenticationContext:completion:)":{"title":"confirmPaymentIntent(params:authenticationContext:completion:)","abstract":[{"type":"text","text":"Confirms the PaymentIntent using the provided "},{"code":"params","type":"codeVoice"},{"type":"text","text":" and handles any next actions required to authenticate the PaymentIntent."}],"navigatorTitle":[{"kind":"identifier","text":"confirmPaymentIntentWithParams:authenticationContext:completion:"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmpaymentintent(params:authenticationcontext:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPaymentIntent(params:authenticationContext:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmPaymentIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/apiClient":{"url":"\/documentation\/stripepayments\/stppaymenthandler\/apiclient","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiClient","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAPIClient","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripeCore@objc(cs)STPAPIClient"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/apiClient","type":"topic","abstract":[{"type":"text","text":"By default "},{"type":"codeVoice","code":"sharedHandler"},{"type":"text","text":" initializes with STPAPIClient.shared."}],"navigatorTitle":[{"text":"apiClient","kind":"identifier"}],"role":"symbol","title":"apiClient"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)":{"abstract":[{"type":"text","text":"Handles any "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":" required to authenticate the SetupIntent."},{"type":"text","text":" "},{"type":"text","text":"Call this method if you are confirming the SetupIntent on your backend and get a status of requires_action."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)","title":"handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:)","url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(setupintentclientsecret:authenticationcontext:returnurl:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"setupIntentClientSecret"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier","text":"STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"text":" -> (","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","text":"STPPaymentHandlerActionStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent","text":"STPSetupIntent","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmSetupIntent(params:authenticationContext:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(params:authenticationContext:completion:)","title":"confirmSetupIntent(params:authenticationContext:completion:)","url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(params:authenticationcontext:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"confirmSetupIntent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSetupIntentConfirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Confirms the SetupIntent using the provided parameters and handles any next actions required to authenticate the SetupIntent."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"confirmSetupIntentWithParams:authenticationContext:completion:"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"setupIntentClientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"authenticationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(setupintentclientsecret:authenticationcontext:returnurl:completion:)","abstract":[{"text":"Handles any ","type":"text"},{"code":"nextAction","type":"codeVoice"},{"text":" required to authenticate the SetupIntent.","type":"text"},{"text":" ","type":"text"},{"text":"Call this method if you are confirming the SetupIntent on your backend and get a status of requires_action.","type":"text"}],"type":"topic","title":"handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(forPayment:with:returnURL:completion:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(forpayment:with:returnurl:completion:)","navigatorTitle":[{"text":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forPayment:with:returnURL:completion:)","deprecated":true,"title":"handleNextAction(forPayment:with:returnURL:completion:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleNextAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPayment","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleURLCallback:":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler\/handleurlcallback:","abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleURLCallback:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleURLCallback:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleURLCallback:"}],"title":"handleURLCallback:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmSetupIntent(_:with:completion:)":{"title":"confirmSetupIntent(_:with:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmSetupIntent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmsetupintent(_:with:completion:)","navigatorTitle":[{"text":"confirmSetupIntent:withAuthenticationContext:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(_:with:completion:)","abstract":[],"deprecated":true,"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/sharedHandler":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharedHandler","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentHandler","text":"STPPaymentHandler","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stppaymenthandler\/sharedhandler","kind":"symbol","navigatorTitle":[{"text":"sharedHandler","kind":"identifier"}],"title":"sharedHandler","type":"topic","abstract":[{"text":"The globally shared instance of ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/sharedHandler"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/handleNextAction(forSetupIntent:with:returnURL:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleNextAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forSetupIntent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPAuthenticationContext","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock","preciseIdentifier":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:"}],"abstract":[],"kind":"symbol","title":"handleNextAction(forSetupIntent:with:returnURL:completion:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forSetupIntent:with:returnURL:completion:)","deprecated":true,"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler\/handlenextaction(forsetupintent:with:returnurl:completion:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler":{"abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" is a utility class that confirms PaymentIntents\/SetupIntents and handles any authentication required, such as 3DS1\/3DS2 for Strong Customer Authentication.","type":"text"},{"text":" ","type":"text"},{"text":"It can present authentication UI on top of your app or redirect users out of your app (to e.g. their banking app).","type":"text"}],"title":"STPPaymentHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandler"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandler"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler","type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/errorDomain":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorDomain"}],"title":"errorDomain","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/errorDomain","url":"\/documentation\/stripepayments\/stppaymenthandler\/errordomain","abstract":[{"text":"The error domain for errors in ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":".","type":"text"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/confirmPayment(_:with:completion:)":{"kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmPayment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentIntentParams","kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments22STPPaymentIntentParamsa"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAuthenticationContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPAuthenticationContext"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment(_:with:completion:)","navigatorTitle":[{"kind":"identifier","text":"confirmPayment:withAuthenticationContext:completion:"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandler\/confirmpayment(_:with:completion:)","deprecated":true,"title":"confirmPayment(_:with:completion:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandler/simulateAppToAppRedirect":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/simulateAppToAppRedirect","url":"\/documentation\/stripepayments\/stppaymenthandler\/simulateapptoappredirect","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"When this flag is enabled, STPPaymentHandler will confirm certain PaymentMethods using"},{"type":"text","text":" "},{"type":"text","text":"Safari instead of SFSafariViewController. If you’d like to use this in your own"},{"type":"text","text":" "},{"type":"text","text":"testing or Continuous Integration platform, please see the IntegrationTester app"},{"type":"text","text":" "},{"type":"text","text":"for usage examples."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"simulateAppToAppRedirect"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"simulateAppToAppRedirect"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"simulateAppToAppRedirect"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentHandler","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandler"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentHandler"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/apiClient","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/simulateAppToAppRedirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/threeDSCustomizationSettings"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPayment(_:with:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmPaymentIntent(params:authenticationContext:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(_:with:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/confirmSetupIntent(params:authenticationContext:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forPayment:with:returnURL:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(forSetupIntent:with:returnURL:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/handleURLCallback:"],"generated":true},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/errorDomain","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/sharedHandler"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/shared()"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandler\/SFSafariViewControllerDelegate-Implementations"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)SFSafariViewControllerDelegate","doc:\/\/com.stripe.stripe-payments\/@M@StripeCore@objc(pl)STPURLCallbackListener"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandler","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1shared()\/title","value":"shared","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1shared()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"shared","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1threeDSCustomizationSettings\/title","value":"threeDSCustomizationSettings","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1threeDSCustomizationSettings\/fragments","value":[{"kind":"identifier","text":"threeDSCustomizationSettings"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)\/title","value":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(paymentIntentClientSecret:authenticationContext:returnURL:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleNextActionForPaymentIntent:authenticationContext:returnURL:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmPaymentIntent(params:authenticationContext:completion:)\/title","value":"confirmPaymentIntentWithParams:authenticationContext:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmPaymentIntent(params:authenticationContext:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmPaymentIntentWithParams:authenticationContext:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1apiClient\/title","value":"apiClient","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1apiClient\/fragments","value":[{"kind":"identifier","text":"apiClient"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmSetupIntent(params:authenticationContext:completion:)\/title","value":"confirmSetupIntentWithParams:authenticationContext:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmSetupIntent(params:authenticationContext:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"confirmSetupIntentWithParams:authenticationContext:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)\/title","value":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(setupIntentClientSecret:authenticationContext:returnURL:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextActionForSetupIntent:authenticationContext:returnURL:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(forPayment:with:returnURL:completion:)\/title","value":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(forPayment:with:returnURL:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"handleNextActionForPayment:withAuthenticationContext:returnURL:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmSetupIntent(_:with:completion:)\/title","value":"confirmSetupIntent:withAuthenticationContext:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmSetupIntent(_:with:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"confirmSetupIntent:withAuthenticationContext:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1sharedHandler\/title","value":"sharedHandler","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1sharedHandler\/fragments","value":[{"text":"sharedHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(forSetupIntent:with:returnURL:completion:)\/title","value":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1handleNextAction(forSetupIntent:with:returnURL:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleNextActionForSetupIntent:withAuthenticationContext:returnURL:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/title","value":"STPPaymentHandler","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandler"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler\/navigatorTitle","value":[{"text":"STPPaymentHandler","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1errorDomain\/title","value":"errorDomain","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1errorDomain\/fragments","value":[{"text":"errorDomain","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmPayment(_:with:completion:)\/title","value":"confirmPayment:withAuthenticationContext:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1confirmPayment(_:with:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"confirmPayment:withAuthenticationContext:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1simulateAppToAppRedirect\/title","value":"simulateAppToAppRedirect","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandler~1simulateAppToAppRedirect\/fragments","value":[{"kind":"identifier","text":"simulateAppToAppRedirect"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}