{"abstract":[{"text":"An object representing parameters used to create a Billie Payment Method","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodbillieparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodbillieparams"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillieParams"}],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams"},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/additionalAPIParameters"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/rootObjectName()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillieParams","kind":"identifier"}],"title":"STPPaymentMethodBillieParams","roleHeading":"Class","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillieParams","navigatorTitle":[{"text":"STPPaymentMethodBillieParams","kind":"identifier"}],"symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillieParams/additionalAPIParameters":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillieparams\/additionalapiparameters","navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/additionalAPIParameters","title":"additionalAPIParameters","abstract":[{"text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:","type":"text"},{"text":" ","type":"text"},{"text":"var cardParams = STPCardParams()","type":"text"},{"text":" ","type":"text"},{"text":"\/\/ add card values","type":"text"},{"text":" ","type":"text"},{"text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]","type":"text"},{"text":" ","type":"text"},{"text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);","type":"text"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"url":"\/documentation\/stripepayments\/stpformencodable","type":"topic","title":"STPFormEncodable","abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillieParams/rootObjectName()":{"navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillieparams\/rootobjectname()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/rootObjectName()","role":"symbol","kind":"symbol","type":"topic","title":"rootObjectName()","abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"type":"text","text":" below."}]},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillieParams":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillieParams"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillieparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillieParams"}],"title":"STPPaymentMethodBillieParams","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a Billie Payment Method"}],"type":"topic"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillieParams/propertyNamesToFormFieldNamesMapping()":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"type":"topic","role":"symbol","title":"propertyNamesToFormFieldNamesMapping()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/propertyNamesToFormFieldNamesMapping()","abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"code":"expMonth","type":"codeVoice"},{"type":"text","text":", but the Stripe API expects a field called "},{"code":"exp_month","type":"codeVoice"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillieparams\/propertynamestoformfieldnamesmapping()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillieParams/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","abstract":[],"title":"init","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillieparams\/init","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/init","navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodBillieParams","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodBillieParams"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodBillieParams"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/additionalAPIParameters"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/init"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams\/rootObjectName()"],"anchor":"Type-Methods","title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillieParams"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"additionalAPIParameters","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams~1additionalAPIParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"additionalAPIParameters"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams~1additionalAPIParameters\/fragments"},{"op":"replace","value":"STPFormEncodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"},{"op":"replace","value":"rootObjectName","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams~1rootObjectName()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams~1rootObjectName()\/fragments"},{"op":"replace","value":"STPPaymentMethodBillieParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodBillieParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodBillieParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams\/navigatorTitle"},{"op":"replace","value":"propertyNamesToFormFieldNamesMapping","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams~1propertyNamesToFormFieldNamesMapping()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams~1propertyNamesToFormFieldNamesMapping()\/fragments"}]}]}