{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"text":"Error codes generated by ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentHandlerErrorCode","title":"STPPaymentHandlerErrorCode","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode"},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/intentStatusErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/invalidClientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/missingReturnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/noConcurrentActionsErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/notAuthenticatedErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/paymentErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiredAppNotAvailable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresAuthenticationContextErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresPaymentMethodErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/stripe3DS2ErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/timedOutErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/unexpectedErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/unsupportedAuthenticationErrorCode"]},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/init(rawValue:)"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/RawRepresentable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymenthandlererrorcode"]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}],"abstract":[{"text":"Error codes generated by ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"}],"title":"STPPaymentHandlerErrorCode","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/requiresPaymentMethodErrorCode":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requirespaymentmethoderrorcode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requiresPaymentMethodErrorCode","kind":"identifier"}],"abstract":[{"text":"Attach a payment method to the PaymentIntent or SetupIntent before using ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","title":"STPPaymentHandlerErrorCode.requiresPaymentMethodErrorCode","role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerRequiresPaymentMethodErrorCode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresPaymentMethodErrorCode"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/RawRepresentable-Implementations","type":"topic","abstract":[],"title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/intentStatusErrorCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/intentStatusErrorCode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intentStatusErrorCode","kind":"identifier"}],"abstract":[{"type":"text","text":"The PaymentIntent or SetupIntent status cannot be resolved by "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/intentstatuserrorcode","navigatorTitle":[{"text":"STPPaymentHandlerIntentStatusErrorCode","kind":"identifier"}],"kind":"symbol","title":"STPPaymentHandlerErrorCode.intentStatusErrorCode","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/unexpectedErrorCode":{"kind":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerUnexpectedErrorCode","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unexpectedErrorCode","kind":"identifier"}],"abstract":[{"text":"The SDK encountered an unexpected error, indicating a problem with the SDK or the Stripe API.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/unexpectederrorcode","title":"STPPaymentHandlerErrorCode.unexpectedErrorCode","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/unexpectedErrorCode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/init(rawvalue:)","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/stripe3DS2ErrorCode":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripe3DS2ErrorCode","kind":"identifier"}],"abstract":[{"type":"text","text":"There was an error in the Stripe3DS2 SDK."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/stripe3DS2ErrorCode","navigatorTitle":[{"text":"STPPaymentHandlerStripe3DS2ErrorCode","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/stripe3ds2errorcode","title":"STPPaymentHandlerErrorCode.stripe3DS2ErrorCode"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/paymentErrorCode":{"abstract":[{"text":"There was an error confirming the Intent.","type":"text"},{"text":" ","type":"text"},{"text":"Inspect the ","type":"text"},{"code":"paymentIntent.lastPaymentError","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"setupIntent.lastSetupError","type":"codeVoice"},{"text":" property.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/paymenterrorcode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/paymentErrorCode","title":"STPPaymentHandlerErrorCode.paymentErrorCode","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentErrorCode"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerPaymentErrorCode"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/CustomStringConvertible-Implementations":{"role":"collectionGroup","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/customstringconvertible-implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/CustomStringConvertible-Implementations","abstract":[],"type":"topic","title":"CustomStringConvertible Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/requiredAppNotAvailable":{"abstract":[{"text":"Indicates that the action requires an authentication app, but either the app is not installed or the request to switch to the app was denied.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiredAppNotAvailable"}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requiredappnotavailable","kind":"symbol","type":"topic","role":"symbol","title":"STPPaymentHandlerErrorCode.requiredAppNotAvailable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiredAppNotAvailable","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerRequiredAppNotAvailableErrorCode"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/unsupportedAuthenticationErrorCode":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsupportedAuthenticationErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode.unsupportedAuthenticationErrorCode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/unsupportedAuthenticationErrorCode","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/unsupportedauthenticationerrorcode","type":"topic","navigatorTitle":[{"text":"STPPaymentHandlerUnsupportedAuthenticationErrorCode","kind":"identifier"}],"abstract":[{"type":"text","text":"Indicates that the action requires an authentication method not recognized or supported by the SDK."}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/invalidClientSecret":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/invalidClientSecret","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The provided PaymentIntent of SetupIntent client secret does not match the expected pattern for client secrets."},{"type":"text","text":" "},{"type":"text","text":"Make sure that your server is returning the correct value and that is being passed to "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":"."}],"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/invalidclientsecret","title":"STPPaymentHandlerErrorCode.invalidClientSecret","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidClientSecret"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerInvalidClientSecret"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/notAuthenticatedErrorCode":{"url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/notauthenticatederrorcode","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notAuthenticatedErrorCode","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentHandlerNotAuthenticatedErrorCode","kind":"identifier"}],"abstract":[{"text":"The transaction did not authenticate (e.g. user entered the wrong code).","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/notAuthenticatedErrorCode","title":"STPPaymentHandlerErrorCode.notAuthenticatedErrorCode","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/missingReturnURL":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerMissingReturnURL"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/missingreturnurl","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingReturnURL"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/missingReturnURL","title":"STPPaymentHandlerErrorCode.missingReturnURL","abstract":[{"text":"The payment method requires a return URL and one was not provided. Your integration should provide one in your ","type":"text"},{"code":"STPPaymentIntentConfirmParams","type":"codeVoice"},{"text":"\/","type":"text"},{"code":"STPSetupIntentConfirmParams","type":"codeVoice"},{"text":" object if you call ","type":"text"},{"code":"STPPaymentHandler.confirm...","type":"codeVoice"},{"text":" or when you call  ","type":"text"},{"code":"STPPaymentHandler.handleNextAction","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/requiresAuthenticationContextErrorCode":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresAuthenticationContextErrorCode","kind":"symbol","title":"STPPaymentHandlerErrorCode.requiresAuthenticationContextErrorCode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresAuthenticationContextErrorCode"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/requiresauthenticationcontexterrorcode","type":"topic","abstract":[{"text":"Payment requires a valid ","type":"text"},{"code":"STPAuthenticationContext","type":"codeVoice"},{"text":".  Make sure your presentingViewController isn’t already presenting.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerRequiresAuthenticationContextErrorCode"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/timedOutErrorCode":{"abstract":[{"type":"text","text":"The action timed out."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/timedOutErrorCode","navigatorTitle":[{"text":"STPPaymentHandlerTimedOutErrorCode","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timedOutErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode.timedOutErrorCode","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/timedouterrorcode","type":"topic","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/Equatable-Implementations","abstract":[],"type":"topic","title":"Equatable Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/equatable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerErrorCode/noConcurrentActionsErrorCode":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandlererrorcode\/noconcurrentactionserrorcode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noConcurrentActionsErrorCode","kind":"identifier"}],"title":"STPPaymentHandlerErrorCode.noConcurrentActionsErrorCode","role":"symbol","abstract":[{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" does not support concurrent actions.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/noConcurrentActionsErrorCode","navigatorTitle":[{"text":"STPPaymentHandlerNoConcurrentActionsErrorCode","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentHandlerErrorCode","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"STPPaymentHandlerErrorCode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/intentStatusErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/invalidClientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/missingReturnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/noConcurrentActionsErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/notAuthenticatedErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/paymentErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiredAppNotAvailable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresAuthenticationContextErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/requiresPaymentMethodErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/stripe3DS2ErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/timedOutErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/unexpectedErrorCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerErrorCode\/unsupportedAuthenticationErrorCode"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerErrorCode"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/title","value":"STPPaymentHandlerErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentHandlerErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiresPaymentMethodErrorCode\/title","value":"STPPaymentHandlerRequiresPaymentMethodErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiresPaymentMethodErrorCode\/fragments","value":[{"text":"STPPaymentHandlerRequiresPaymentMethodErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1intentStatusErrorCode\/title","value":"STPPaymentHandlerIntentStatusErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1intentStatusErrorCode\/fragments","value":[{"text":"STPPaymentHandlerIntentStatusErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1unexpectedErrorCode\/title","value":"STPPaymentHandlerUnexpectedErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1unexpectedErrorCode\/fragments","value":[{"text":"STPPaymentHandlerUnexpectedErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1stripe3DS2ErrorCode\/title","value":"STPPaymentHandlerStripe3DS2ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1stripe3DS2ErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerStripe3DS2ErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1paymentErrorCode\/title","value":"STPPaymentHandlerPaymentErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1paymentErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerPaymentErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiredAppNotAvailable\/title","value":"STPPaymentHandlerRequiredAppNotAvailableErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiredAppNotAvailable\/fragments","value":[{"text":"STPPaymentHandlerRequiredAppNotAvailableErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1unsupportedAuthenticationErrorCode\/title","value":"STPPaymentHandlerUnsupportedAuthenticationErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1unsupportedAuthenticationErrorCode\/fragments","value":[{"text":"STPPaymentHandlerUnsupportedAuthenticationErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1invalidClientSecret\/title","value":"STPPaymentHandlerInvalidClientSecret"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1invalidClientSecret\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerInvalidClientSecret"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1notAuthenticatedErrorCode\/title","value":"STPPaymentHandlerNotAuthenticatedErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1notAuthenticatedErrorCode\/fragments","value":[{"text":"STPPaymentHandlerNotAuthenticatedErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1missingReturnURL\/title","value":"STPPaymentHandlerMissingReturnURL"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1missingReturnURL\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerMissingReturnURL"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiresAuthenticationContextErrorCode\/title","value":"STPPaymentHandlerRequiresAuthenticationContextErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1requiresAuthenticationContextErrorCode\/fragments","value":[{"text":"STPPaymentHandlerRequiresAuthenticationContextErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1timedOutErrorCode\/title","value":"STPPaymentHandlerTimedOutErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1timedOutErrorCode\/fragments","value":[{"text":"STPPaymentHandlerTimedOutErrorCode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1noConcurrentActionsErrorCode\/title","value":"STPPaymentHandlerNoConcurrentActionsErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerErrorCode~1noConcurrentActionsErrorCode\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerNoConcurrentActionsErrorCode"}]}]}]}