{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"text":"The Crypto Payment Method.","type":"text"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodCrypto","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Docs.Stripe.Com\/Crypto\/Pay-With-Crypto"}],"type":"paragraph"}],"name":"See Also","style":"note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcrypto"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcrypto"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"metadata":{"symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCrypto","roleHeading":"Class","navigatorTitle":[{"text":"STPPaymentMethodCrypto","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCrypto"}],"role":"symbol","modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodCrypto"},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/decodedObject(fromAPIResponse:)"]}],"references":{"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCrypto/description":{"url":"\/documentation\/stripepayments\/stppaymentmethodcrypto\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/description","title":"description","role":"symbol","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCrypto/allResponseFields":{"url":"\/documentation\/stripepayments\/stppaymentmethodcrypto\/allresponsefields","kind":"symbol","role":"symbol","type":"topic","title":"allResponseFields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/allResponseFields","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCrypto":{"title":"STPPaymentMethodCrypto","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcrypto","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCrypto"}],"role":"symbol","abstract":[{"type":"text","text":"The Crypto Payment Method."}],"navigatorTitle":[{"text":"STPPaymentMethodCrypto","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCrypto/decodedObject(fromAPIResponse:)":{"url":"\/documentation\/stripepayments\/stppaymentmethodcrypto\/decodedobject(fromapiresponse:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/decodedObject(fromAPIResponse:)","title":"decodedObject(fromAPIResponse:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodCrypto"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"STPPaymentMethodCrypto"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCrypto"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/description"],"title":"Instance Properties"},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCrypto\/decodedObject(fromAPIResponse:)"],"generated":true}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodCrypto","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto~1description\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto~1allResponseFields\/title","op":"replace","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto\/title","op":"replace","value":"STPPaymentMethodCrypto"},{"value":[{"text":"STPPaymentMethodCrypto","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodCrypto","kind":"identifier"}]},{"op":"replace","value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCrypto~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}