{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"created during confirmation, by passing in a ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":" or "},{"code":"STPSourceParams","type":"codeVoice"},{"type":"text","text":" object in the "},{"type":"codeVoice","code":"paymentMethodParams"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"sourceParams"},{"text":" field","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"a pre-existing PaymentMethod or Source can be associated by passing its id in the ","type":"text"},{"type":"codeVoice","code":"paymentMethodId"},{"type":"text","text":" or "},{"type":"codeVoice","code":"sourceId"},{"type":"text","text":" field"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"or already set via your backend, either when creating or updating the PaymentIntent"}]}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api#Confirm_payment_intent","type":"text"}]}],"type":"aside","name":"See Also"}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"kind":"relationships","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/init(clientSecret:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/init(clientSecret:paymentMethodType:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/mandateData","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/receiptEmail","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/returnURL-1o0ia","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/returnUrl-1nqpe","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/savePaymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/setupFutureUsage-3vs4y","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/setupFutureUsage_objc","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/stripeId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/useStripeSDK-7bt5o","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/useStripeSDK_objc"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/NSCopying-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/STPFormEncodable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams"]},{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmparams"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentConfirmParams","navigatorTitle":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"title":"STPPaymentIntentConfirmParams","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/description":{"abstract":[{"type":"text","text":":nodoc:"}],"title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/description","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/returnUrl-1nqpe":{"role":"symbol","title":"returnUrl","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/returnurl-1nqpe","abstract":[{"text":"The URL to redirect your customer back to after they authenticate or cancel","type":"text"},{"type":"text","text":" "},{"type":"text","text":"their payment on the payment method’s app or site."},{"text":" ","type":"text"},{"type":"text","text":"This property has been renamed to "},{"code":"returnURL","type":"codeVoice"},{"text":" and deprecated.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnUrl"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"returnUrl","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/returnUrl-1nqpe","type":"topic","deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/useStripeSDK-7bt5o":{"kind":"symbol","type":"topic","title":"useStripeSDK","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/usestripesdk-7bt5o","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"useStripeSDK","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}],"abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any PaymentIntent next actions.","type":"text"},{"type":"text","text":" "},{"text":"If set to false, STPPaymentIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/useStripeSDK-7bt5o"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/useStripeSDK_objc":{"abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any PaymentIntent next actions.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If set to false, STPPaymentIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser."},{"type":"text","text":" "},{"text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your","type":"text"},{"type":"text","text":" "},{"type":"text","text":"app."}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/usestripesdk_objc","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/useStripeSDK_objc","title":"useStripeSDK_objc","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useStripeSDK_objc"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"text":"useStripeSDK","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/sourceParams":{"role":"symbol","title":"sourceParams","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/sourceparams","abstract":[{"type":"text","text":"Provide a supported "},{"code":"STPSourceParams","type":"codeVoice"},{"text":" object into here, and Stripe will create a Source","type":"text"},{"type":"text","text":" "},{"text":"during PaymentIntent confirmation.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceParams"},{"text":": ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"text":"sourceParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceParams","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/paymentMethodOptions":{"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/paymentmethodoptions","role":"symbol","title":"paymentMethodOptions","abstract":[{"text":"Options to update the associated PaymentMethod during confirmation.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentMethodOptions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPConfirmPaymentMethodOptions","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodOptions","navigatorTitle":[{"kind":"identifier","text":"paymentMethodOptions"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/NSCopying-Implementations":{"kind":"article","type":"topic","title":"NSCopying Implementations","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/nscopying-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/NSCopying-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/STPFormEncodable-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/stpformencodable-implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/STPFormEncodable-Implementations","title":"STPFormEncodable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}],"abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"title":"STPFormEncodable","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","kind":"symbol","url":"\/documentation\/stripepayments\/stpformencodable","role":"symbol","navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/confirmationToken":{"role":"symbol","title":"confirmationToken","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/confirmationtoken","abstract":[{"type":"text","text":"ID of an existing ConfirmationToken to use for this PaymentIntent confirmation."}],"fragments":[{"kind":"identifier","text":"confirmationToken"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/confirmationToken","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/radarOptions":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/radarOptions","fragments":[{"kind":"identifier","text":"radarOptions"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/radaroptions","abstract":[{"text":"Radar options that may contain HCaptcha token","type":"text"}],"title":"radarOptions","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/stripeId":{"kind":"symbol","navigatorTitle":[{"text":"stripeId","kind":"identifier"}],"type":"topic","title":"stripeId","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/stripeid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stripeId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The Stripe id of the PaymentIntent, extracted from the clientSecret."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/stripeId"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/clientSecret":{"role":"symbol","title":"clientSecret","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/clientsecret","abstract":[{"type":"text","text":"The client secret of the PaymentIntent. Required"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clientSecret"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"clientSecret","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/clientSecret","type":"topic"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/init(clientSecret:paymentMethodType:)":{"role":"symbol","title":"init(clientSecret:paymentMethodType:)","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/init(clientsecret:paymentmethodtype:)","abstract":[{"type":"text","text":"Initializes this "},{"code":"STPPaymentIntentConfirmParams","type":"codeVoice"},{"text":" with a ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"type":"text","text":" and "},{"code":"paymentMethodType","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Use this initializer for PaymentIntents that already have a PaymentMethod attached."}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodType"},{"kind":"text","text":": "},{"text":"STPPaymentMethodType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"initWithClientSecret:paymentMethodType:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/init(clientSecret:paymentMethodType:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams":{"kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams","title":"STPPaymentIntentConfirmParams","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/returnURL-1o0ia":{"role":"symbol","title":"returnURL","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/returnurl-1o0ia","abstract":[{"type":"text","text":"The URL to redirect your customer back to after they authenticate or cancel"},{"type":"text","text":" "},{"text":"their payment on the payment method’s app or site.","type":"text"},{"type":"text","text":" "},{"text":"This should probably be a URL that opens your iOS app.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"returnURL","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/returnURL-1o0ia","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/setupFutureUsage-3vs4y":{"kind":"symbol","type":"topic","title":"setupFutureUsage","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/setupfutureusage-3vs4y","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"setupFutureUsage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","text":"STPPaymentIntentSetupFutureUsage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"When provided, this property indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"text":" ","type":"text"},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/setupFutureUsage-3vs4y"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/paymentMethodParams":{"role":"symbol","title":"paymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/paymentmethodparams","abstract":[{"type":"text","text":"Provide a supported "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":" object, and Stripe will create a"},{"type":"text","text":" "},{"text":"PaymentMethod during PaymentIntent confirmation.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodParams","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/shipping":{"navigatorTitle":[{"text":"shipping","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/shipping","abstract":[{"type":"text","text":"Shipping information."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shipping","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentIntentShippingDetailsParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams"},{"text":"?","kind":"text"}],"title":"shipping","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/shipping"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/clientAttributionMetadata":{"role":"symbol","title":"clientAttributionMetadata","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/clientAttributionMetadata","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/clientattributionmetadata","abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"type":"topic","fragments":[{"kind":"identifier","text":"clientAttributionMetadata"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/sourceId":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sourceId"}],"type":"topic","title":"sourceId","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/sourceid","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Provide an already created Source’s id, and it will be used to confirm the PaymentIntent."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceId"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/receiptEmail":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"receiptEmail","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"receiptEmail"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/receiptemail","abstract":[{"type":"text","text":"Email address that the receipt for the resulting payment will be sent to."}],"title":"receiptEmail","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/receiptEmail"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/setupFutureUsage_objc":{"role":"symbol","title":"setupFutureUsage_objc","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/setupfutureusage_objc","abstract":[{"type":"text","text":"When provided, this property indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"type":"text","text":" "},{"text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This property should only be used in Objective-C. In Swift, use "},{"type":"codeVoice","code":"setupFutureUsage"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"setupFutureUsage_objc","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"setupFutureUsage"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/setupFutureUsage_objc","type":"topic"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/paymentMethodId":{"abstract":[{"text":"Provide an already created PaymentMethod’s id, and it will be used to confirm the PaymentIntent.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/paymentmethodid","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentMethodId"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodId","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentMethodId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"paymentMethodId"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","title":"NSCopying"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/savePaymentMethod":{"role":"symbol","title":"savePaymentMethod","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/savepaymentmethod","abstract":[{"type":"codeVoice","code":"@YES"},{"text":" to save this PaymentIntent’s PaymentMethod or Source to the associated Customer,","type":"text"},{"type":"text","text":" "},{"text":"if the PaymentMethod\/Source is not already attached.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This should be a boolean NSNumber, so that it can be "},{"code":"nil","type":"codeVoice"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"savePaymentMethod"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"text":"savePaymentMethod","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/savePaymentMethod","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/additionalAPIParameters":{"kind":"symbol","navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"type":"topic","title":"additionalAPIParameters","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/additionalapiparameters","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/additionalAPIParameters"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/setAsDefaultPM":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/setAsDefaultPM","title":"setAsDefaultPM","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/setasdefaultpm","abstract":[{"type":"text","text":"@YES"},{"text":" to set this PaymentIntent’s PaymentMethod as the associated Customer’s default","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This should be a boolean NSNumber, so that it can be "},{"type":"text","text":"nil"}],"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"setAsDefaultPM"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/init(clientSecret:)":{"role":"symbol","title":"init(clientSecret:)","url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/init(clientsecret:)","abstract":[{"type":"text","text":"Initialize this "},{"type":"codeVoice","code":"STPPaymentIntentConfirmParams"},{"text":" with a ","type":"text"},{"type":"codeVoice","code":"clientSecret"},{"text":", which is the only required","type":"text"},{"type":"text","text":" "},{"type":"text","text":"field."}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithClientSecret:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/init(clientSecret:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmParams/mandateData":{"url":"\/documentation\/stripepayments\/stppaymentintentconfirmparams\/mandatedata","navigatorTitle":[{"text":"mandateData","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"mandateData","abstract":[{"type":"text","text":"Details about the Mandate to create."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"mandateData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPMandateDataParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/mandateData"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"STPPaymentIntentConfirmParams","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmParams"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/clientAttributionMetadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/confirmationToken","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/mandateData","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/paymentMethodParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/radarOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/receiptEmail","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/returnURL-1o0ia","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/returnUrl-1nqpe","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/savePaymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/setAsDefaultPM","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/setupFutureUsage_objc","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/sourceParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/stripeId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/useStripeSDK_objc"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/init(clientSecret:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/init(clientSecret:paymentMethodType:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/NSCopying-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmParams\/STPFormEncodable-Implementations"],"anchor":"Default-Implementations"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmParams","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1description\/fragments"},{"value":"returnUrl","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1returnUrl-1nqpe\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1returnUrl-1nqpe\/fragments","value":[{"text":"returnUrl","kind":"identifier"}]},{"value":"useStripeSDK","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1useStripeSDK_objc\/title","op":"replace"},{"value":[{"text":"useStripeSDK","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1useStripeSDK_objc\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1sourceParams\/title","op":"replace","value":"sourceParams"},{"op":"replace","value":[{"kind":"identifier","text":"sourceParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1sourceParams\/fragments"},{"op":"replace","value":"paymentMethodOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1paymentMethodOptions\/title"},{"value":[{"kind":"identifier","text":"paymentMethodOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1paymentMethodOptions\/fragments"},{"value":"STPFormEncodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"text":"STPFormEncodable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1stripeId\/title","op":"replace","value":"stripeId"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1stripeId\/fragments","op":"replace","value":[{"kind":"identifier","text":"stripeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1clientSecret\/title","value":"clientSecret"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1clientSecret\/fragments","value":[{"text":"clientSecret","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithClientSecret:paymentMethodType:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1init(clientSecret:paymentMethodType:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1init(clientSecret:paymentMethodType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithClientSecret:paymentMethodType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/title","value":"STPPaymentIntentConfirmParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/fragments","value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}]},{"value":[{"text":"STPPaymentIntentConfirmParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1returnURL-1o0ia\/title","value":"returnURL"},{"op":"replace","value":[{"kind":"identifier","text":"returnURL"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1returnURL-1o0ia\/fragments"},{"value":"paymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1paymentMethodParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1paymentMethodParams\/fragments","value":[{"text":"paymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1shipping\/title","value":"shipping","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1shipping\/fragments","value":[{"text":"shipping","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"sourceId","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1sourceId\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1sourceId\/fragments","op":"replace","value":[{"kind":"identifier","text":"sourceId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1receiptEmail\/title","value":"receiptEmail"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1receiptEmail\/fragments","value":[{"kind":"identifier","text":"receiptEmail"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1setupFutureUsage_objc\/title","value":"setupFutureUsage","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1setupFutureUsage_objc\/fragments","value":[{"text":"setupFutureUsage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1paymentMethodId\/title","value":"paymentMethodId"},{"value":[{"text":"paymentMethodId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1paymentMethodId\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1savePaymentMethod\/title","value":"savePaymentMethod","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1savePaymentMethod\/fragments","value":[{"kind":"identifier","text":"savePaymentMethod"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1additionalAPIParameters\/title","op":"replace","value":"additionalAPIParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1additionalAPIParameters\/fragments","value":[{"text":"additionalAPIParameters","kind":"identifier"}]},{"value":"initWithClientSecret:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1init(clientSecret:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithClientSecret:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1init(clientSecret:)\/fragments"},{"op":"replace","value":"mandateData","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1mandateData\/title"},{"value":[{"kind":"identifier","text":"mandateData"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmParams~1mandateData\/fragments"}]}]}