{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentparams"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"An object representing parameters used to confirm a PaymentIntent object."},{"type":"text","text":" "},{"type":"text","text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it."},{"type":"text","text":" "},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/init(clientSecret:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/init(clientSecret:paymentMethodType:)"],"title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/mandateData","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/receiptEmail","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/returnURL-2g896","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/returnUrl-2fy22","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/savePaymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/saveSourceToCustomer","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setupFutureUsage-4tdvn","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setupFutureUsage_objc","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/sourceId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/sourceParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/stripeId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/useStripeSDK"],"anchor":"Instance-Properties","title":"Instance Properties"},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/NSCopying-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/STPFormEncodable-Implementations"]}],"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentParams","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentParams","title":"STPPaymentIntentParams"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentParams"}],"languages":["swift"]}]},{"content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"created during confirmation, by passing in a "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":" or "},{"code":"STPSourceParams","type":"codeVoice"},{"type":"text","text":" object in the "},{"code":"paymentMethodParams","type":"codeVoice"},{"type":"text","text":" or "},{"code":"sourceParams","type":"codeVoice"},{"type":"text","text":" field"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"a pre-existing PaymentMethod or Source can be associated by passing its id in the ","type":"text"},{"type":"codeVoice","code":"paymentMethodId"},{"text":" or ","type":"text"},{"code":"sourceId","type":"codeVoice"},{"type":"text","text":" field"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"or already set via your backend, either when creating or updating the PaymentIntent","type":"text"}],"type":"paragraph"}]}]},{"style":"note","content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api#Confirm_payment_intent","type":"text"}],"type":"paragraph"}],"name":"See Also","type":"aside"}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/saveSourceToCustomer":{"url":"\/documentation\/stripepayments\/stppaymentintentparams\/savesourcetocustomer","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"saveSourceToCustomer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"deprecated":true,"title":"saveSourceToCustomer","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/saveSourceToCustomer","abstract":[{"code":"@YES","type":"codeVoice"},{"type":"text","text":" to save this PaymentIntent’s Source to the associated Customer,"},{"type":"text","text":" "},{"type":"text","text":"if the Source is not already attached."},{"text":" ","type":"text"},{"type":"text","text":"This should be a boolean NSNumber, so that it can be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" "},{"text":"This property has been renamed to ","type":"text"},{"code":"savePaymentMethod","type":"codeVoice"},{"text":" and deprecated.","type":"text"}],"navigatorTitle":[{"text":"saveSourceToCustomer","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/setupFutureUsage-4tdvn":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams\/setupfutureusage-4tdvn","kind":"symbol","abstract":[{"type":"text","text":"When provided, this property indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"text":" ","type":"text"},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"title":"setupFutureUsage","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setupFutureUsage"},{"kind":"text","text":": "},{"text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setupFutureUsage-4tdvn"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/STPFormEncodable-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentintentparams\/stpformencodable-implementations","title":"STPFormEncodable Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/STPFormEncodable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/sourceParams":{"abstract":[{"text":"Provide a supported ","type":"text"},{"type":"codeVoice","code":"STPSourceParams"},{"text":" object into here, and Stripe will create a Source","type":"text"},{"type":"text","text":" "},{"text":"during PaymentIntent confirmation.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sourceParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/sourceParams","url":"\/documentation\/stripepayments\/stppaymentintentparams\/sourceparams","title":"sourceParams","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/sourceId":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sourceId"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sourceId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/sourceId","title":"sourceId","type":"topic","abstract":[{"type":"text","text":"Provide an already created Source’s id, and it will be used to confirm the PaymentIntent."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/sourceid"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/receiptEmail":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/receiptEmail","type":"topic","abstract":[{"type":"text","text":"Email address that the receipt for the resulting payment will be sent to."}],"navigatorTitle":[{"kind":"identifier","text":"receiptEmail"}],"title":"receiptEmail","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"receiptEmail","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/receiptemail","role":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSCopying":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","title":"NSCopying"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/paymentMethodId":{"abstract":[{"type":"text","text":"Provide an already created PaymentMethod’s id, and it will be used to confirm the PaymentIntent."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"paymentMethodId","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams\/paymentmethodid","title":"paymentMethodId","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodId","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/clientSecret":{"url":"\/documentation\/stripepayments\/stppaymentintentparams\/clientsecret","title":"clientSecret","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clientSecret"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clientSecret","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The client secret of the PaymentIntent. Required"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/clientSecret"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/paymentMethodOptions":{"kind":"symbol","role":"symbol","title":"paymentMethodOptions","type":"topic","abstract":[{"type":"text","text":"Options to update the associated PaymentMethod during confirmation."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentMethodOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPConfirmPaymentMethodOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodOptions","url":"\/documentation\/stripepayments\/stppaymentintentparams\/paymentmethodoptions","navigatorTitle":[{"kind":"identifier","text":"paymentMethodOptions"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentParams","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"title":"STPPaymentIntentParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams","url":"\/documentation\/stripepayments\/stppaymentintentparams","abstract":[{"text":"An object representing parameters used to confirm a PaymentIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"A PaymentIntent must have a PaymentMethod or Source associated in order to successfully confirm it.","type":"text"},{"text":" ","type":"text"},{"text":"That PaymentMethod or Source can either be:","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/additionalAPIParameters":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/additionalAPIParameters","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","title":"additionalAPIParameters","url":"\/documentation\/stripepayments\/stppaymentintentparams\/additionalapiparameters","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/setupFutureUsage_objc":{"abstract":[{"type":"text","text":"When provided, this property indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"type":"text","text":" "},{"text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This property should only be used in Objective-C. In Swift, use "},{"code":"setupFutureUsage","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"setupFutureUsage","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentparams\/setupfutureusage_objc","title":"setupFutureUsage_objc","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setupFutureUsage_objc","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupFutureUsage_objc","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/radarOptions":{"abstract":[{"text":"Radar options that may contain HCaptcha token","type":"text"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams\/radaroptions","title":"radarOptions","fragments":[{"text":"radarOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/radarOptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/mandateData":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/mandateData","type":"topic","title":"mandateData","abstract":[{"text":"Details about the Mandate to create.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/mandatedata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mandateData","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPMandateDataParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"mandateData","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/returnURL-2g896":{"role":"symbol","title":"returnURL","url":"\/documentation\/stripepayments\/stppaymentintentparams\/returnurl-2g896","type":"topic","navigatorTitle":[{"kind":"identifier","text":"returnURL"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/returnURL-2g896","abstract":[{"text":"The URL to redirect your customer back to after they authenticate or cancel","type":"text"},{"type":"text","text":" "},{"type":"text","text":"their payment on the payment method’s app or site."},{"text":" ","type":"text"},{"type":"text","text":"This should probably be a URL that opens your iOS app."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/useStripeSDK":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/useStripeSDK","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"useStripeSDK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any PaymentIntent next actions.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If set to false, STPPaymentIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser."},{"text":" ","type":"text"},{"type":"text","text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your"},{"text":" ","type":"text"},{"type":"text","text":"app."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/usestripesdk","type":"topic","navigatorTitle":[{"kind":"identifier","text":"useStripeSDK"}],"title":"useStripeSDK"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/init(clientSecret:)":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/init(clientSecret:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initialize this "},{"type":"codeVoice","code":"STPPaymentIntentParams"},{"text":" with a ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":", which is the only required","type":"text"},{"type":"text","text":" "},{"text":"field.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/init(clientsecret:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithClientSecret:"}],"title":"init(clientSecret:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/stripeId":{"title":"stripeId","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stripeId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[{"text":"The Stripe id of the PaymentIntent, extracted from the clientSecret.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams\/stripeid","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/stripeId","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"stripeId","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/init(clientSecret:paymentMethodType:)":{"abstract":[{"text":"Initializes this ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentParams"},{"type":"text","text":" with a "},{"code":"clientSecret","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"paymentMethodType"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Use this initializer for PaymentIntents that already have a PaymentMethod attached."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithClientSecret:paymentMethodType:"}],"url":"\/documentation\/stripepayments\/stppaymentintentparams\/init(clientsecret:paymentmethodtype:)","title":"init(clientSecret:paymentMethodType:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/init(clientSecret:paymentMethodType:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"clientSecret"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","kind":"typeIdentifier","text":"STPPaymentMethodType"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/savePaymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/savePaymentMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"savePaymentMethod","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentparams\/savepaymentmethod","title":"savePaymentMethod","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"savePaymentMethod"}],"type":"topic","abstract":[{"code":"@YES","type":"codeVoice"},{"text":" to save this PaymentIntent’s PaymentMethod or Source to the associated Customer,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"if the PaymentMethod\/Source is not already attached."},{"type":"text","text":" "},{"type":"text","text":"This should be a boolean NSNumber, so that it can be "},{"type":"codeVoice","code":"nil"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/shipping":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/shipping","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shipping","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams","text":"STPPaymentIntentShippingDetailsParams","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Shipping information."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/shipping","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shipping"}],"title":"shipping"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/returnUrl-2fy22":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"returnUrl","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/returnUrl-2fy22","deprecated":true,"abstract":[{"type":"text","text":"The URL to redirect your customer back to after they authenticate or cancel"},{"type":"text","text":" "},{"type":"text","text":"their payment on the payment method’s app or site."},{"text":" ","type":"text"},{"text":"This property has been renamed to ","type":"text"},{"type":"codeVoice","code":"returnURL"},{"type":"text","text":" and deprecated."}],"kind":"symbol","title":"returnUrl","type":"topic","navigatorTitle":[{"text":"returnUrl","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentparams\/returnurl-2fy22"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/setAsDefaultPM":{"role":"symbol","abstract":[{"text":"@YES","type":"text"},{"type":"text","text":" to set this PaymentIntent’s PaymentMethod as the associated Customer’s default"},{"text":" ","type":"text"},{"type":"text","text":"This should be a boolean NSNumber, so that it can be "},{"text":"nil","type":"text"}],"fragments":[{"kind":"identifier","text":"setAsDefaultPM"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/setasdefaultpm","title":"setAsDefaultPM","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setAsDefaultPM","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/clientAttributionMetadata":{"role":"symbol","fragments":[{"text":"clientAttributionMetadata","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/clientAttributionMetadata","title":"clientAttributionMetadata","type":"topic","abstract":[{"type":"text","text":"Contains metadata with identifiers for the session and information about the integration"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentparams\/clientattributionmetadata"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/NSCopying-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/NSCopying-Implementations","abstract":[],"kind":"article","url":"\/documentation\/stripepayments\/stppaymentintentparams\/nscopying-implementations","type":"topic","title":"NSCopying Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/paymentMethodParams":{"kind":"symbol","title":"paymentMethodParams","abstract":[{"text":"Provide a supported ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":" object, and Stripe will create a"},{"text":" ","type":"text"},{"type":"text","text":"PaymentMethod during PaymentIntent confirmation."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodParams","navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentparams\/paymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentParams/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentparams\/description","role":"symbol","title":"description","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"title":"STPFormEncodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpformencodable","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"STPPaymentIntentParams","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/clientAttributionMetadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/mandateData","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/paymentMethodParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/radarOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/receiptEmail","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/returnURL-2g896","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/returnUrl-2fy22","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/savePaymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/saveSourceToCustomer","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setAsDefaultPM","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/setupFutureUsage_objc","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/sourceId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/sourceParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/stripeId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/useStripeSDK"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/init(clientSecret:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/init(clientSecret:paymentMethodType:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/NSCopying-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentParams\/STPFormEncodable-Implementations"],"title":"Default Implementations"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentParams"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1saveSourceToCustomer\/title","op":"replace","value":"saveSourceToCustomer"},{"op":"replace","value":[{"text":"saveSourceToCustomer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1saveSourceToCustomer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1sourceParams\/title","value":"sourceParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1sourceParams\/fragments","value":[{"kind":"identifier","text":"sourceParams"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1sourceId\/title","value":"sourceId"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1sourceId\/fragments","value":[{"kind":"identifier","text":"sourceId"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1receiptEmail\/title","op":"replace","value":"receiptEmail"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1receiptEmail\/fragments","op":"replace","value":[{"kind":"identifier","text":"receiptEmail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1paymentMethodId\/title","value":"paymentMethodId"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1paymentMethodId\/fragments","value":[{"text":"paymentMethodId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1clientSecret\/title","value":"clientSecret"},{"op":"replace","value":[{"kind":"identifier","text":"clientSecret"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1clientSecret\/fragments"},{"value":"paymentMethodOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1paymentMethodOptions\/title"},{"value":[{"text":"paymentMethodOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1paymentMethodOptions\/fragments"},{"value":"STPPaymentIntentParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/fragments","value":[{"text":"STPPaymentIntentParams","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1additionalAPIParameters\/title","op":"replace","value":"additionalAPIParameters"},{"value":[{"text":"additionalAPIParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1additionalAPIParameters\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1setupFutureUsage_objc\/title","value":"setupFutureUsage","op":"replace"},{"value":[{"text":"setupFutureUsage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1setupFutureUsage_objc\/fragments"},{"value":"mandateData","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1mandateData\/title","op":"replace"},{"value":[{"text":"mandateData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1mandateData\/fragments"},{"value":"returnURL","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1returnURL-2g896\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1returnURL-2g896\/fragments","value":[{"text":"returnURL","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1useStripeSDK\/title","value":"useStripeSDK"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1useStripeSDK\/fragments","value":[{"text":"useStripeSDK","kind":"identifier"}]},{"value":"initWithClientSecret:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1init(clientSecret:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithClientSecret:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1init(clientSecret:)\/fragments"},{"value":"stripeId","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1stripeId\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1stripeId\/fragments","op":"replace","value":[{"kind":"identifier","text":"stripeId"}]},{"op":"replace","value":"initWithClientSecret:paymentMethodType:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1init(clientSecret:paymentMethodType:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1init(clientSecret:paymentMethodType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithClientSecret:paymentMethodType:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1savePaymentMethod\/title","value":"savePaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1savePaymentMethod\/fragments","value":[{"text":"savePaymentMethod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1shipping\/title","value":"shipping","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1shipping\/fragments","value":[{"kind":"identifier","text":"shipping"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1returnUrl-2fy22\/title","value":"returnUrl","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1returnUrl-2fy22\/fragments","value":[{"kind":"identifier","text":"returnUrl"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1paymentMethodParams\/title","value":"paymentMethodParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1paymentMethodParams\/fragments","value":[{"text":"paymentMethodParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentParams~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","op":"replace","value":"STPFormEncodable"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","value":[{"text":"STPFormEncodable","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"text":"STPFormEncodable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}