{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/description"],"anchor":"Instance-Properties","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodeps"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodeps"]}],"metadata":{"symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodEPS","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodEPS","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodEPS","modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodEPS"},"abstract":[{"text":"An EPS Payment Method.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodEPS","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Object#Payment_method_object-Eps","type":"text"}],"type":"paragraph"}],"name":"See Also","style":"note","type":"aside"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodEPS/description":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":":nodoc:"}],"title":"description","url":"\/documentation\/stripepayments\/stppaymentmethodeps\/description"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodEPS/allResponseFields":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/allResponseFields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"abstract":[],"title":"allResponseFields","url":"\/documentation\/stripepayments\/stppaymentmethodeps\/allresponsefields"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","kind":"symbol","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"title":"STPAPIResponseDecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodEPS":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS","url":"\/documentation\/stripepayments\/stppaymentmethodeps","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodEPS"}],"title":"STPPaymentMethodEPS","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodEPS"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An EPS Payment Method."}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodEPS/decodedObject(fromAPIResponse:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/decodedObject(fromAPIResponse:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"abstract":[],"title":"decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stppaymentmethodeps\/decodedobject(fromapiresponse:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentMethodEPS","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPPaymentMethodEPS","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"STPPaymentMethodEPS","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/description"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPS\/decodedObject(fromAPIResponse:)"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodEPS","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS~1description\/fragments"},{"value":"allResponseFields","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS~1allResponseFields\/title"},{"value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS~1allResponseFields\/fragments"},{"value":"STPAPIResponseDecodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"value":"STPPaymentMethodEPS","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodEPS"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodEPS"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS\/navigatorTitle"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS~1decodedObject(fromAPIResponse:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPS~1decodedObject(fromAPIResponse:)\/fragments"}]}]}