{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay"},"metadata":{"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodRevolutPay","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodRevolutPay"}],"role":"symbol","title":"STPPaymentMethodRevolutPay","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodRevolutPay"}],"modules":[{"name":"StripePayments"}]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/description"],"title":"Instance Properties"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/decodedObject(fromAPIResponse:)"],"title":"Type Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodRevolutPay","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Payments\/Revolut-Pay"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodrevolutpay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodrevolutpay"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"The RevolutPay Payment Method."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodRevolutPay/decodedObject(fromAPIResponse:)":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/decodedObject(fromAPIResponse:)","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodrevolutpay\/decodedobject(fromapiresponse:)","abstract":[],"kind":"symbol","title":"decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodRevolutPay/allResponseFields":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/allResponseFields","url":"\/documentation\/stripepayments\/stppaymentmethodrevolutpay\/allresponsefields","abstract":[{"type":"text","text":":nodoc:"}],"title":"allResponseFields","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}]},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodRevolutPay/description":{"abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodrevolutpay\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/description","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodRevolutPay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay","navigatorTitle":[{"text":"STPPaymentMethodRevolutPay","kind":"identifier"}],"title":"STPPaymentMethodRevolutPay","url":"\/documentation\/stripepayments\/stppaymentmethodrevolutpay","abstract":[{"text":"The RevolutPay Payment Method.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodRevolutPay"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodRevolutPay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodRevolutPay","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodRevolutPay"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/description"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPay\/decodedObject(fromAPIResponse:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodRevolutPay"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay~1decodedObject(fromAPIResponse:)\/fragments"},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay~1allResponseFields\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay~1description\/fragments"},{"op":"replace","value":"STPPaymentMethodRevolutPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay\/fragments","op":"replace","value":[{"text":"STPPaymentMethodRevolutPay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPay\/navigatorTitle","value":[{"text":"STPPaymentMethodRevolutPay","kind":"identifier"}],"op":"replace"}]}]}