{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcompletionblock"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"externalID":"s:14StripePayments31STPPaymentMethodCompletionBlocka","title":"STPPaymentMethodCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodCompletionBlock","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"typealias","roleHeading":"Type Alias","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCompletionBlock","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A callback to be run with a PaymentMethod response from the Stripe API."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCompletionBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The Stripe PaymentMethod from the response. Will be nil if an error occurs. - seealso: STPPaymentMethod","type":"text"}]}],"name":"paymentMethod"},{"content":[{"inlineContent":[{"type":"text","text":"The error returned from the response, or nil if none occurs. - seealso: StripeError.h for possible values."}],"type":"paragraph"}],"name":"error"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","title":"STPPaymentMethod","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCompletionBlock":{"url":"\/documentation\/stripepayments\/stppaymentmethodcompletionblock","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCompletionBlock"}],"title":"STPPaymentMethodCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCompletionBlock","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCompletionBlock"}],"abstract":[{"type":"text","text":"A callback to be run with a PaymentMethod response from the Stripe API."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethod"}]}]}]}