{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock"},"metadata":{"navigatorTitle":[{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}],"title":"STPPaymentHandlerActionSetupIntentCompletionBlock","roleHeading":"Type Alias","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"s:14StripePayments49STPPaymentHandlerActionSetupIntentCompletionBlocka","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandleractionsetupintentcompletionblock"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","text":"STPPaymentHandlerActionStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},{"kind":"text","text":", "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Completion block typedef for use in ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" methods for Setup Intents."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"type":"text","text":" represents the possible outcomes of requesting an action by "},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":". An action could be confirming and\/or handling the next action for a PaymentIntent.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"title":"STPPaymentHandlerActionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionSetupIntentCompletionBlock":{"abstract":[{"text":"Completion block typedef for use in ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" methods for Setup Intents."}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentHandlerActionSetupIntentCompletionBlock","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionSetupIntentCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionSetupIntentCompletionBlock"}],"kind":"symbol","title":"STPPaymentHandlerActionSetupIntentCompletionBlock","url":"\/documentation\/stripepayments\/stppaymenthandleractionsetupintentcompletionblock"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"title":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsetupintent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntent"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","value":"STPPaymentHandlerActionStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}]},{"op":"replace","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","op":"replace","value":"STPSetupIntent"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSetupIntent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}