{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountHolderType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/bankName","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/financialConnectionsAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/fingerprint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/linkedAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/networks","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/routingNumber"],"anchor":"Instance-Properties","generated":true},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/STPAPIResponseDecodable-Implementations"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Object#Payment_method_object-Us_bank_account","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note","name":"See Also"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount","symbolKind":"class","role":"symbol","title":"STPPaymentMethodUSBankAccount","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"roleHeading":"Class"},"abstract":[{"text":"A US Bank Account Payment Method (ACH)","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/allResponseFields":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/allResponseFields","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/allresponsefields","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"title":"allResponseFields","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/routingNumber":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/routingNumber","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/routingnumber","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"routingNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Routing number of the bank account"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"routingNumber","kind":"identifier"}],"title":"routingNumber","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/bankName":{"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/bankname","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bankName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"bankName","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/bankName","kind":"symbol","navigatorTitle":[{"text":"bankName","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"The name of the bank","type":"text"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"role":"symbol","abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"type":"text","text":" "},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"title":"STPAPIResponseDecodable","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/linkedAccount":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"linkedAccount","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/linkedaccount","type":"topic","title":"linkedAccount","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"linkedAccount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"deprecated":true,"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/linkedAccount"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/last4":{"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/last4","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"last4","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"last4","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/last4","kind":"symbol","navigatorTitle":[{"text":"last4","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Last four digits of the bank account number","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/networks":{"abstract":[{"text":"Contains information about US bank account networks that can be used","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/networks","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/networks","navigatorTitle":[{"text":"networks","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networks","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUSBankAccountNetworks","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountNetworks"},{"kind":"text","text":"?"}],"title":"networks"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/financialConnectionsAccount":{"title":"financialConnectionsAccount","abstract":[{"text":"The ID of the Financial Connections Account used to create the payment method","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/financialConnectionsAccount","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/financialconnectionsaccount","navigatorTitle":[{"text":"financialConnectionsAccount","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"financialConnectionsAccount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/fingerprint":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/fingerprint","role":"symbol","title":"fingerprint","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fingerprint"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/fingerprint","abstract":[{"text":"Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"fingerprint","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/accountType":{"title":"accountType","abstract":[{"text":"Account type","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountType","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/accounttype","navigatorTitle":[{"kind":"identifier","text":"accountType"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountType","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUSBankAccountType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/STPAPIResponseDecodable-Implementations":{"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/stpapiresponsedecodable-implementations","title":"STPAPIResponseDecodable Implementations","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/STPAPIResponseDecodable-Implementations","type":"topic","kind":"article"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"title":"STPPaymentMethodUSBankAccount","abstract":[{"type":"text","text":"A US Bank Account Payment Method (ACH)"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/accountHolderType":{"type":"topic","abstract":[{"type":"text","text":"Account holder type"}],"title":"accountHolderType","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountHolderType","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"accountHolderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType"}],"navigatorTitle":[{"text":"accountHolderType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/accountholdertype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"STPPaymentMethodUSBankAccount","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountHolderType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountType","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/bankName","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/financialConnectionsAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/fingerprint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/linkedAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/networks","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/routingNumber"],"generated":true,"anchor":"Instance-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/STPAPIResponseDecodable-Implementations"],"anchor":"Default-Implementations","generated":true}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1allResponseFields\/title","op":"replace","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1routingNumber\/title","value":"routingNumber","op":"replace"},{"value":[{"kind":"identifier","text":"routingNumber"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1routingNumber\/fragments"},{"value":"bankName","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1bankName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"bankName"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1bankName\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1linkedAccount\/title","value":"linkedAccount"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1linkedAccount\/fragments","value":[{"text":"linkedAccount","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1last4\/title","value":"last4","op":"replace"},{"value":[{"kind":"identifier","text":"last4"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1last4\/fragments"},{"value":"networks","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1networks\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1networks\/fragments","value":[{"text":"networks","kind":"identifier"}],"op":"replace"},{"value":"financialConnectionsAccount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1financialConnectionsAccount\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1financialConnectionsAccount\/fragments","value":[{"kind":"identifier","text":"financialConnectionsAccount"}]},{"op":"replace","value":"fingerprint","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1fingerprint\/title"},{"op":"replace","value":[{"text":"fingerprint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1fingerprint\/fragments"},{"value":"accountType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1accountType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1accountType\/fragments","value":[{"text":"accountType","kind":"identifier"}]},{"value":"STPPaymentMethodUSBankAccount","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/fragments","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1accountHolderType\/title","value":"accountHolderType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1accountHolderType\/fragments","value":[{"kind":"identifier","text":"accountHolderType"}]}]}]}