{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentStatusBlock"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"STPPaymentStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"inlineContent":[{"type":"text","text":"The error that occurred, if any."}],"type":"paragraph"}]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatusBlock","interfaceLanguage":"swift"},"metadata":{"externalID":"s:14StripePayments21STPPaymentStatusBlocka","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentStatusBlock","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentStatusBlock","kind":"identifier"}],"title":"STPPaymentStatusBlock","modules":[{"name":"StripePayments"}],"roleHeading":"Type Alias"},"kind":"symbol","abstract":[{"type":"text","text":"A block called with a payment status and an optional error."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentstatusblock"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentStatus","kind":"identifier"}],"title":"STPPaymentStatus","type":"topic","navigatorTitle":[{"text":"STPPaymentStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentstatus","abstract":[{"text":"An enum representing the status of a payment requested from the user.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatusBlock":{"role":"symbol","title":"STPPaymentStatusBlock","url":"\/documentation\/stripepayments\/stppaymentstatusblock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentStatusBlock"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentStatusBlock"}],"kind":"symbol","abstract":[{"text":"A block called with a payment status and an optional error.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatusBlock"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/title","value":"STPPaymentStatus","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/fragments","value":[{"kind":"identifier","text":"STPPaymentStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentStatus"}],"op":"replace"}]}]}