{"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUpdateParams","symbolKind":"class","roleHeading":"Class","role":"symbol","title":"STPPaymentMethodUpdateParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to update a PaymentMethod object."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/init(card:billingDetails:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/billingDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/card"],"generated":true,"anchor":"Instance-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/STPFormEncodable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/s9EscapableP","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"name":"See Also","style":"note","content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Update","type":"text"}],"type":"paragraph"}],"type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodupdateparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodupdateparams"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}],"title":"STPFormEncodable","abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","kind":"symbol","url":"\/documentation\/stripepayments\/stpformencodable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/additionalAPIParameters":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"title":"additionalAPIParameters","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/additionalAPIParameters","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/additionalapiparameters"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/init":{"kind":"symbol","abstract":[],"role":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/init","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/init"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/billingDetails":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"billingDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods."}],"navigatorTitle":[{"text":"billingDetails","kind":"identifier"}],"title":"billingDetails","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/billingDetails","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/billingdetails"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/s9EscapableP":{"type":"unresolvable","title":"Swift.Escapable","identifier":"doc:\/\/com.stripe.stripe-payments\/s9EscapableP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/init(card:billingDetails:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"card","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(card:billingDetails:)","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithCard:billingDetails:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/init(card:billingDetails:)","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/init(card:billingdetails:)"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/STPFormEncodable-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/stpformencodable-implementations","kind":"article","title":"STPFormEncodable Implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/STPFormEncodable-Implementations"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams/card":{"kind":"symbol","abstract":[{"type":"text","text":"If this is a card PaymentMethod, this contains the user’s card details."}],"role":"symbol","title":"card","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams\/card","navigatorTitle":[{"text":"card","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/card"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUpdateParams":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUpdateParams"}],"title":"STPPaymentMethodUpdateParams","abstract":[{"type":"text","text":"An object representing parameters used to update a PaymentMethod object."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUpdateParams"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams","url":"\/documentation\/stripepayments\/stppaymentmethodupdateparams"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentMethodUpdateParams","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/billingDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/card"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/init","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/init(card:billingDetails:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUpdateParams\/STPFormEncodable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUpdateParams"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPFormEncodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"value":[{"text":"STPFormEncodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"value":[{"text":"STPFormEncodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"},{"value":"additionalAPIParameters","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1additionalAPIParameters\/title"},{"value":[{"text":"additionalAPIParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1additionalAPIParameters\/fragments"},{"value":"billingDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1billingDetails\/title"},{"value":[{"text":"billingDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1billingDetails\/fragments"},{"value":"initWithCard:billingDetails:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1init(card:billingDetails:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCard:billingDetails:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1init(card:billingDetails:)\/fragments"},{"value":"card","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1card\/title"},{"value":[{"text":"card","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams~1card\/fragments"},{"value":"STPPaymentMethodUpdateParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/title"},{"value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/fragments"},{"value":[{"text":"STPPaymentMethodUpdateParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUpdateParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}