{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"STPPaymentIntentSourceActionType","roleHeading":"Enumeration","navigatorTitle":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentSourceActionType","modules":[{"name":"StripePayments"}],"platforms":[],"role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/authorizeWithURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/unknown"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/RawRepresentable-Implementations"]}],"deprecationSummary":[{"inlineContent":[{"text":"Use STPIntentActionType instead","type":"text"}],"type":"paragraph"}],"abstract":[{"type":"text","text":"Types of Source Actions from a "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":", when the payment intent"},{"text":" ","type":"text"},{"text":"status is ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresSourceAction"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentsourceactiontype"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/authorizeWithURL":{"type":"topic","role":"symbol","deprecated":true,"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/authorizewithurl","abstract":[{"text":"The payment intent needs to be authorized by the user. We provide","type":"text"},{"type":"text","text":" "},{"code":"STPRedirectContext","type":"codeVoice"},{"text":" to handle the url redirections necessary.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authorizeWithURL"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/authorizeWithURL","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSourceActionTypeAuthorizeWithURL"}],"title":"STPPaymentIntentSourceActionType.authorizeWithURL"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/unknown":{"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/unknown","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/unknown","title":"STPPaymentIntentSourceActionType.unknown","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"abstract":[{"type":"text","text":"This is an unknown source action, that’s been added since the SDK"},{"type":"text","text":" "},{"text":"was last updated.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"nextSourceAction.allResponseFields"},{"type":"text","text":" "},{"text":"for custom handling.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSourceActionTypeUnknown"}],"deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/customstringconvertible-implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic","title":"CustomStringConvertible Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/RawRepresentable-Implementations","type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/init(rawValue:)","type":"topic","deprecated":true},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType":{"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype","deprecated":true,"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Types of Source Actions from a "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":", when the payment intent"},{"type":"text","text":" "},{"type":"text","text":"status is "},{"code":"STPPaymentIntentStatusRequiresSourceAction","type":"codeVoice"},{"text":".","type":"text"}],"title":"STPPaymentIntentSourceActionType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSourceActionType/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentintentsourceactiontype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/Equatable-Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentSourceActionType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentIntentSourceActionType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/authorizeWithURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSourceActionType\/unknown"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentSourceActionType"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentIntentSourceActionTypeAuthorizeWithURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType~1authorizeWithURL\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType~1authorizeWithURL\/fragments","value":[{"text":"STPPaymentIntentSourceActionTypeAuthorizeWithURL","kind":"identifier"}]},{"value":"STPPaymentIntentSourceActionTypeUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType~1unknown\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType~1unknown\/fragments","value":[{"text":"STPPaymentIntentSourceActionTypeUnknown","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/title","value":"STPPaymentIntentSourceActionType"},{"value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentIntentSourceActionType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSourceActionType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}