{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"An enum representing the success and error states of PIN management","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus"},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/ephemeralKeyError","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationAlreadyRedeemed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationCodeIncorrect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationExpired","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationTooManyAttempts","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/success","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/unknownError"]},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppinstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppinstatus"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPinStatus","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"STPPinStatus","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPinStatus","kind":"identifier"}],"role":"symbol","title":"STPPinStatus","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPinStatus"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/stripepayments\/stppinstatus\/rawrepresentable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/RawRepresentable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/unknownError":{"navigatorTitle":[{"text":"STPPinStatusUnknownError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppinstatus\/unknownerror","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/unknownError","abstract":[{"text":"An unknown error occured","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"title":"STPPinStatus.unknownError","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/ephemeralKeyError":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/ephemeralKeyError","url":"\/documentation\/stripepayments\/stppinstatus\/ephemeralkeyerror","kind":"symbol","title":"STPPinStatus.ephemeralKeyError","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ephemeralKeyError","kind":"identifier"}],"navigatorTitle":[{"text":"STPPinStatusEphemeralKeyError","kind":"identifier"}],"abstract":[{"text":"An error occured while retrieving the ephemeral key","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/errorVerificationTooManyAttempts":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationTooManyAttempts","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPinStatusErrorVerificationTooManyAttempts"}],"title":"STPPinStatus.errorVerificationTooManyAttempts","url":"\/documentation\/stripepayments\/stppinstatus\/errorverificationtoomanyattempts","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorVerificationTooManyAttempts"}],"abstract":[{"text":"The verification object has been attempted too many times","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppinstatus\/init(rawvalue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/errorVerificationAlreadyRedeemed":{"role":"symbol","navigatorTitle":[{"text":"STPPinStatusErrorVerificationAlreadyRedeemed","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppinstatus\/errorverificationalreadyredeemed","abstract":[{"type":"text","text":"The verification object was already redeemed"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationAlreadyRedeemed","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"errorVerificationAlreadyRedeemed","kind":"identifier"}],"title":"STPPinStatus.errorVerificationAlreadyRedeemed"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/success":{"navigatorTitle":[{"text":"STPPinStatusSuccess","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppinstatus\/success","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/success","abstract":[{"text":"The verification object was already redeemed","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"title":"STPPinStatus.success","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stppinstatus\/customstringconvertible-implementations","type":"topic","abstract":[],"kind":"article","title":"CustomStringConvertible Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/CustomStringConvertible-Implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"title":"STPPinStatus","url":"\/documentation\/stripepayments\/stppinstatus","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","navigatorTitle":[{"text":"STPPinStatus","kind":"identifier"}],"type":"topic","abstract":[{"text":"An enum representing the success and error states of PIN management","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPinStatus"}]},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/Equatable-Implementations","url":"\/documentation\/stripepayments\/stppinstatus\/equatable-implementations","kind":"article","title":"Equatable Implementations","abstract":[],"role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/errorVerificationExpired":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorVerificationExpired","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppinstatus\/errorverificationexpired","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationExpired","abstract":[{"type":"text","text":"The verification object was expired"}],"title":"STPPinStatus.errorVerificationExpired","role":"symbol","navigatorTitle":[{"text":"STPPinStatusErrorVerificationExpired","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus/errorVerificationCodeIncorrect":{"navigatorTitle":[{"text":"STPPinStatusErrorVerificationCodeIncorrect","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppinstatus\/errorverificationcodeincorrect","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationCodeIncorrect","abstract":[{"text":"The one-time code was incorrect","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorVerificationCodeIncorrect","kind":"identifier"}],"title":"STPPinStatus.errorVerificationCodeIncorrect","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPPinStatus"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPPinStatus","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"STPPinStatus"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/ephemeralKeyError","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationAlreadyRedeemed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationCodeIncorrect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationExpired","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/errorVerificationTooManyAttempts","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/success","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus\/unknownError"]}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPinStatus"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1unknownError\/title","value":"STPPinStatusUnknownError","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1unknownError\/fragments","value":[{"kind":"identifier","text":"STPPinStatusUnknownError"}]},{"op":"replace","value":"STPPinStatusEphemeralKeyError","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1ephemeralKeyError\/title"},{"value":[{"kind":"identifier","text":"STPPinStatusEphemeralKeyError"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1ephemeralKeyError\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationTooManyAttempts\/title","value":"STPPinStatusErrorVerificationTooManyAttempts","op":"replace"},{"value":[{"text":"STPPinStatusErrorVerificationTooManyAttempts","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationTooManyAttempts\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationAlreadyRedeemed\/title","value":"STPPinStatusErrorVerificationAlreadyRedeemed","op":"replace"},{"value":[{"kind":"identifier","text":"STPPinStatusErrorVerificationAlreadyRedeemed"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationAlreadyRedeemed\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1success\/title","op":"replace","value":"STPPinStatusSuccess"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1success\/fragments","value":[{"kind":"identifier","text":"STPPinStatusSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title","value":"STPPinStatus"},{"value":[{"text":"STPPinStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle","op":"replace","value":[{"text":"STPPinStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationExpired\/title","value":"STPPinStatusErrorVerificationExpired","op":"replace"},{"op":"replace","value":[{"text":"STPPinStatusErrorVerificationExpired","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationExpired\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationCodeIncorrect\/title","value":"STPPinStatusErrorVerificationCodeIncorrect","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus~1errorVerificationCodeIncorrect\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPinStatusErrorVerificationCodeIncorrect"}]}]}]}