{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType"},"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/amexExpressCheckout","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/applePay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/googlePay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/link","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/masterpass","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/samsungPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/visaCheckout"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/init(rawValue:)"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/RawRepresentable-Implementations"]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallettype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The type of Card Wallet."}],"metadata":{"symbolKind":"enum","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Enumeration","title":"STPPaymentMethodCardWalletType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}]},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/Equatable-Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/unknown":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/unknown","navigatorTitle":[{"text":"STPPaymentMethodCardWalletTypeUnknown","kind":"identifier"}],"abstract":[{"text":"An unknown Card Wallet type.","type":"text"}],"title":"STPPaymentMethodCardWalletType.unknown","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/unknown","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/CustomStringConvertible-Implementations":{"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/CustomStringConvertible-Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/init(rawvalue:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/link":{"title":"STPPaymentMethodCardWalletType.link","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/link","role":"symbol","type":"topic","abstract":[{"text":"Link","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/link","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeLink"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/visaCheckout":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/visaCheckout","kind":"symbol","type":"topic","abstract":[{"text":"Visa Checkout","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visaCheckout","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/visacheckout","navigatorTitle":[{"text":"STPPaymentMethodCardWalletTypeVisaCheckout","kind":"identifier"}],"title":"STPPaymentMethodCardWalletType.visaCheckout","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/amexExpressCheckout":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"amexExpressCheckout"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Amex Express Checkout","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeAmexExpressCheckout"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/amexExpressCheckout","title":"STPPaymentMethodCardWalletType.amexExpressCheckout","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/amexexpresscheckout"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/googlePay":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"googlePay"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Google Pay","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeGooglePay"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/googlePay","title":"STPPaymentMethodCardWalletType.googlePay","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/googlepay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/RawRepresentable-Implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/masterpass":{"title":"STPPaymentMethodCardWalletType.masterpass","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"masterpass"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeMasterpass"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/masterpass","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/masterpass","abstract":[{"text":"Masterpass","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"type":"topic","title":"STPPaymentMethodCardWalletType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"abstract":[{"type":"text","text":"The type of Card Wallet."}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/applePay":{"title":"STPPaymentMethodCardWalletType.applePay","abstract":[{"text":"Apple Pay","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"applePay"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeApplePay"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/applepay","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/applePay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWalletType/samsungPay":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/samsungPay","title":"STPPaymentMethodCardWalletType.samsungPay","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"samsungPay"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallettype\/samsungpay","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeSamsungPay"}],"abstract":[{"text":"Samsung Pay","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodCardWalletType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/amexExpressCheckout","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/applePay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/googlePay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/link","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/masterpass","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/samsungPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWalletType\/visaCheckout"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWalletType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodCardWalletTypeUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1unknown\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1unknown\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1link\/title","value":"STPPaymentMethodCardWalletTypeLink"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1link\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeLink"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1visaCheckout\/title","value":"STPPaymentMethodCardWalletTypeVisaCheckout"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1visaCheckout\/fragments","value":[{"text":"STPPaymentMethodCardWalletTypeVisaCheckout","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1amexExpressCheckout\/title","value":"STPPaymentMethodCardWalletTypeAmexExpressCheckout"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1amexExpressCheckout\/fragments","value":[{"text":"STPPaymentMethodCardWalletTypeAmexExpressCheckout","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1googlePay\/title","value":"STPPaymentMethodCardWalletTypeGooglePay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1googlePay\/fragments","value":[{"text":"STPPaymentMethodCardWalletTypeGooglePay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1masterpass\/title","value":"STPPaymentMethodCardWalletTypeMasterpass"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1masterpass\/fragments","value":[{"text":"STPPaymentMethodCardWalletTypeMasterpass","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/title","value":"STPPaymentMethodCardWalletType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType\/navigatorTitle","value":[{"text":"STPPaymentMethodCardWalletType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1applePay\/title","value":"STPPaymentMethodCardWalletTypeApplePay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1applePay\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeApplePay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1samsungPay\/title","value":"STPPaymentMethodCardWalletTypeSamsungPay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWalletType~1samsungPay\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWalletTypeSamsungPay"}]}]}]}