{"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAUBECSDebit","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAUBECSDebit"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodAUBECSDebit"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Object#Payment_method_object-Au_becs_debit"}]}],"type":"aside","style":"note","name":"See Also"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/bsbNumber","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/fingerprint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/last4"]},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/decodedObject(fromAPIResponse:)"],"title":"Type Methods"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodaubecsdebit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodaubecsdebit"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"An AU BECS Debit Payment Method.","type":"text"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit/decodedObject(fromAPIResponse:)":{"role":"symbol","title":"decodedObject(fromAPIResponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/decodedObject(fromAPIResponse:)","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"type":"text","text":"an "},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/decodedobject(fromapiresponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit/bsbNumber":{"abstract":[{"text":"Six-digit number identifying bank and branch associated with this bank account.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/bsbNumber","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bsbNumber","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","title":"bsbNumber","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/bsbnumber","navigatorTitle":[{"text":"bsbNumber","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit/allResponseFields":{"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","title":"allResponseFields","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/allresponsefields","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/allResponseFields"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","title":"STPAPIResponseDecodable","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit/last4":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/last4","title":"last4","url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/last4","role":"symbol","type":"topic","navigatorTitle":[{"text":"last4","kind":"identifier"}],"abstract":[{"text":"Last four digits of the bank account number.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit/description":{"role":"symbol","title":"description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit","abstract":[{"text":"An AU BECS Debit Payment Method.","type":"text"}],"type":"topic","title":"STPPaymentMethodAUBECSDebit","url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAUBECSDebit"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebit/fingerprint":{"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebit\/fingerprint","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/fingerprint","navigatorTitle":[{"kind":"identifier","text":"fingerprint"}],"abstract":[{"text":"Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fingerprint"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"fingerprint"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"STPPaymentMethodAUBECSDebit","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodAUBECSDebit"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/bsbNumber","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/fingerprint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/last4"]},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebit\/decodedObject(fromAPIResponse:)"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"type":"conformsTo","title":"Conforms To"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1decodedObject(fromAPIResponse:)\/fragments"},{"op":"replace","value":"bsbNumber","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1bsbNumber\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1bsbNumber\/fragments","op":"replace","value":[{"text":"bsbNumber","kind":"identifier"}]},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1allResponseFields\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"value":"last4","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1last4\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1last4\/fragments","value":[{"text":"last4","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","value":"STPPaymentMethodAUBECSDebit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/title"},{"value":[{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit\/navigatorTitle","value":[{"text":"STPPaymentMethodAUBECSDebit","kind":"identifier"}]},{"value":"fingerprint","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1fingerprint\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebit~1fingerprint\/fragments","value":[{"kind":"identifier","text":"fingerprint"}]}]}]}