{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An object representing parameters used to create an FPX Payment Method"}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"title":"STPPaymentMethodFPXParams","modules":[{"name":"StripePayments"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodFPXParams"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/bank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/rawBankString"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/rootObjectName()"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodfpxparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodfpxparams"]}],"references":{"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"title":"STPFormEncodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpformencodable","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams/propertyNamesToFormFieldNamesMapping()":{"abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"code":"expMonth","type":"codeVoice"},{"text":", but the Stripe API expects a field called ","type":"text"},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/propertyNamesToFormFieldNamesMapping()","url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams\/propertynamestoformfieldnamesmapping()","type":"topic","kind":"symbol","title":"propertyNamesToFormFieldNamesMapping()","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"kind":"text","text":"() -> ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams/init":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/init","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams\/init","role":"symbol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams/additionalAPIParameters":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/additionalAPIParameters","type":"topic","abstract":[{"type":"text","text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:"},{"type":"text","text":" "},{"type":"text","text":"var cardParams = STPCardParams()"},{"text":" ","type":"text"},{"text":"\/\/ add card values","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]"},{"text":" ","type":"text"},{"type":"text","text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);"}],"navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"title":"additionalAPIParameters","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams\/additionalapiparameters","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams/rootObjectName()":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/rootObjectName()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rootObjectName"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"text":" below.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams\/rootobjectname()","type":"topic","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"title":"rootObjectName()"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams","title":"STPPaymentMethodFPXParams","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodFPXParams"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create an FPX Payment Method","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams/rawBankString":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/rawBankString","type":"topic","abstract":[{"type":"text","text":"The raw underlying bank string sent to the server."},{"text":" ","type":"text"},{"type":"text","text":"Generally you should use "},{"code":"bank","type":"codeVoice"},{"text":" instead unless you have a reason not to.","type":"text"},{"type":"text","text":" "},{"text":"You can use this if you want to create a param of a bank not yet supported","type":"text"},{"type":"text","text":" "},{"type":"text","text":"by the current version of the SDK’s "},{"type":"codeVoice","code":"STPFPXBankBrand"},{"type":"text","text":" enum."},{"text":" ","type":"text"},{"text":"Setting this to a value not known by the SDK causes ","type":"text"},{"code":"bank","type":"codeVoice"},{"text":" to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"return "},{"type":"codeVoice","code":"STPFPXBankBrandUnknown"}],"navigatorTitle":[{"text":"rawBankString","kind":"identifier"}],"title":"rawBankString","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBankString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams\/rawbankstring","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams/bank":{"navigatorTitle":[{"text":"bank","kind":"identifier"}],"title":"bank","abstract":[{"type":"text","text":"The customer’s bank. Required."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bank","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPFPXBankBrand","text":"STPFPXBankBrand","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/bank","url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams\/bank"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodFPXParams"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodFPXParams"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodFPXParams"}],"op":"replace"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/bank","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/rawBankString"],"title":"Instance Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/init"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/rootObjectName()"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodFPXParams"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"value":"STPFormEncodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"value":[{"kind":"identifier","text":"STPFormEncodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPFormEncodable"}],"op":"replace"},{"value":"propertyNamesToFormFieldNamesMapping","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1propertyNamesToFormFieldNamesMapping()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1additionalAPIParameters\/title","value":"additionalAPIParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1additionalAPIParameters\/fragments","value":[{"text":"additionalAPIParameters","kind":"identifier"}]},{"value":"rootObjectName","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1rootObjectName()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1rootObjectName()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}]},{"value":"STPPaymentMethodFPXParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/navigatorTitle","value":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1rawBankString\/title","value":"rawBankString"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1rawBankString\/fragments","value":[{"kind":"identifier","text":"rawBankString"}],"op":"replace"},{"op":"replace","value":"bank","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1bank\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1bank\/fragments","op":"replace","value":[{"text":"bank","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}