{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"metadata":{"title":"STPPaymentStatus","symbolKind":"enum","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentStatus","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentStatus"}],"roleHeading":"Enumeration"},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/error","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/success","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/userCancellation"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentstatus"]}],"abstract":[{"type":"text","text":"An enum representing the status of a payment requested from the user."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentStatus","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentstatus\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article","type":"topic","title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/init(rawValue:)":{"abstract":[],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentstatus\/init(rawvalue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/userCancellation":{"url":"\/documentation\/stripepayments\/stppaymentstatus\/usercancellation","abstract":[{"text":"The user cancelled the payment (for example, by hitting “cancel” in the Apple Pay dialog).","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCancellation"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentStatusUserCancellation"}],"title":"STPPaymentStatus.userCancellation","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/userCancellation"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/success":{"abstract":[{"type":"text","text":"The payment succeeded."}],"kind":"symbol","title":"STPPaymentStatus.success","navigatorTitle":[{"text":"STPPaymentStatusSuccess","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/success","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentstatus\/success","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentstatus\/customstringconvertible-implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/CustomStringConvertible-Implementations","role":"collectionGroup","kind":"article","type":"topic","title":"CustomStringConvertible Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentstatus\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/Equatable-Implementations","role":"collectionGroup","kind":"article","type":"topic","title":"Equatable Implementations"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/error":{"role":"symbol","abstract":[{"text":"The payment failed due to an unforeseen error, such as the user’s Internet connection being offline.","type":"text"}],"title":"STPPaymentStatus.error","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/error","kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPPaymentStatusError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentstatus\/error"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus":{"type":"topic","title":"STPPaymentStatus","navigatorTitle":[{"text":"STPPaymentStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentStatus","kind":"identifier"}],"abstract":[{"text":"An enum representing the status of a payment requested from the user.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentstatus"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentStatus","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentStatus","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/error","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/success","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/userCancellation"],"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentStatus","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1userCancellation\/title","value":"STPPaymentStatusUserCancellation"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1userCancellation\/fragments","value":[{"text":"STPPaymentStatusUserCancellation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1success\/title","value":"STPPaymentStatusSuccess"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1success\/fragments","value":[{"text":"STPPaymentStatusSuccess","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1error\/title","value":"STPPaymentStatusError"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1error\/fragments","value":[{"kind":"identifier","text":"STPPaymentStatusError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/title","value":"STPPaymentStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/fragments","value":[{"text":"STPPaymentStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/navigatorTitle","value":[{"text":"STPPaymentStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}