{"kind":"symbol","abstract":[{"text":"Action details for an STPPaymentIntent. This is a container for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the various types that are available. Check the "},{"type":"codeVoice","code":"type"},{"text":" to see which one","type":"text"},{"type":"text","text":" "},{"text":"it is, and then use the related property for the details necessary to handle it.","type":"text"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"deprecationSummary":[{"inlineContent":[{"text":"Use `STPIntentAction` instead.","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentaction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentaction"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentAction","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentAction","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentAction","platforms":[],"navigatorTitle":[{"text":"STPPaymentIntentAction","kind":"identifier"}],"role":"symbol","title":"STPPaymentIntentAction","symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentIntentAction","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentAction":{"kind":"symbol","abstract":[{"type":"text","text":"Action details for an STPPaymentIntent. This is a container for"},{"type":"text","text":" "},{"type":"text","text":"the various types that are available. Check the "},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one"},{"type":"text","text":" "},{"type":"text","text":"it is, and then use the related property for the details necessary to handle it."}],"navigatorTitle":[{"text":"STPPaymentIntentAction","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentAction","title":"STPPaymentIntentAction","url":"\/documentation\/stripepayments\/stppaymentintentaction","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentIntentAction","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"kind":"symbol","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"title":"STPAPIResponseDecodable","role":"symbol","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentAction":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPIntentAction"}],"abstract":[{"text":"Next action details for ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"This is a container for the various types that are available.","type":"text"},{"type":"text","text":" "},{"text":"Check the ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" to see which one it is, and then use the related"},{"type":"text","text":" "},{"type":"text","text":"property for the details necessary to handle it."},{"type":"text","text":" "},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentAction"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpintentaction","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentAction"}],"title":"STPIntentAction"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentIntentAction"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentAction"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentAction","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentAction","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","text":"STPIntentAction","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentAction"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"STPPaymentIntentAction","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentAction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentAction\/fragments","value":[{"text":"STPPaymentIntentAction","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentAction\/navigatorTitle","value":[{"text":"STPPaymentIntentAction","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","op":"replace","value":"STPAPIResponseDecodable"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"value":"STPIntentAction","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/fragments","value":[{"text":"STPIntentAction","kind":"identifier"}]},{"value":[{"text":"STPIntentAction","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentAction\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}