{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentStatus"}],"title":"STPPaymentIntentStatus","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@StripePayments@E@STPPaymentIntentStatus","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatus"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/canceled","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/processing","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresCapture","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresConfirmation","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresPaymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSource","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSourceAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/succeeded","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/unknown"]},{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/succeeded":{"role":"symbol","title":"STPPaymentIntentStatus.succeeded","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded"}],"abstract":[{"type":"text","text":"The payment has succeeded"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/succeeded","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusSucceeded"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/succeeded"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresSourceAction":{"deprecated":false,"role":"symbol","title":"STPPaymentIntentStatus.requiresSourceAction","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresSourceAction"}],"abstract":[{"type":"text","text":"The selected Source requires additional authentication steps."},{"type":"text","text":" "},{"type":"text","text":"Additional actions found via "},{"type":"codeVoice","code":"next_source_action"},{"type":"text","text":" "},{"type":"text","text":"Deprecated: Use STPPaymentIntentStatusRequiresAction instead."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSourceAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSourceAction"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requiressourceaction"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/processing":{"role":"symbol","title":"STPPaymentIntentStatus.processing","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"processing"}],"abstract":[{"type":"text","text":"Stripe is processing this PaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/processing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusProcessing"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/processing"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresAction":{"role":"symbol","title":"STPPaymentIntentStatus.requiresAction","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresAction"}],"abstract":[{"type":"text","text":"The selected PaymentMethod or Source requires additional authentication steps."},{"type":"text","text":" "},{"type":"text","text":"Additional actions found via "},{"type":"codeVoice","code":"next_action"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresAction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresAction"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requiresaction"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresConfirmation":{"role":"symbol","title":"STPPaymentIntentStatus.requiresConfirmation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresConfirmation"}],"abstract":[{"type":"text","text":"This PaymentIntent needs to be confirmed"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresConfirmation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresConfirmation"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requiresconfirmation"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresCapture":{"role":"symbol","title":"STPPaymentIntentStatus.requiresCapture","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresCapture"}],"abstract":[{"type":"text","text":"Indicates the payment must be captured, for STPPaymentIntentCaptureMethodManual"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresCapture","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresCapture"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requirescapture"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/CustomStringConvertible-Implementations":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/customstringconvertible-implementations"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresPaymentMethod":{"role":"symbol","title":"STPPaymentIntentStatus.requiresPaymentMethod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresPaymentMethod"}],"abstract":[{"type":"text","text":"This PaymentIntent requires a PaymentMethod or Source"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresPaymentMethod","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresPaymentMethod"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requirespaymentmethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/canceled":{"role":"symbol","title":"STPPaymentIntentStatus.canceled","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"abstract":[{"type":"text","text":"This PaymentIntent was canceled and cannot be changed."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/canceled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusCanceled"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/canceled"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/requiresSource":{"deprecated":false,"role":"symbol","title":"STPPaymentIntentStatus.requiresSource","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requiresSource"}],"abstract":[{"type":"text","text":"This PaymentIntent requires a Source"},{"type":"text","text":" "},{"type":"text","text":"Deprecated: Use STPPaymentIntentStatusRequiresPaymentMethod instead."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSource"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/requiressource"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/equatable-implementations"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/unknown":{"role":"symbol","title":"STPPaymentIntentStatus.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"type":"text","text":"Unknown status"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/unknown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatusUnknown"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentstatus\/rawrepresentable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentStatus":{"role":"symbol","title":"STPPaymentIntentStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentStatus"}],"abstract":[{"type":"text","text":"Status types for an STPPaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentStatus"}],"url":"\/documentation\/stripepayments\/stppaymentintentstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/canceled","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/processing","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresCapture","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresConfirmation","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresPaymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSource","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/requiresSourceAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/succeeded","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentStatus\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1succeeded\/title","value":"STPPaymentIntentStatusSucceeded"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1succeeded\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusSucceeded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresSourceAction\/title","value":"STPPaymentIntentStatusRequiresSourceAction"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresSourceAction\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSourceAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1processing\/title","value":"STPPaymentIntentStatusProcessing"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1processing\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusProcessing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresAction\/title","value":"STPPaymentIntentStatusRequiresAction"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresAction\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresAction"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresConfirmation\/title","value":"STPPaymentIntentStatusRequiresConfirmation"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresConfirmation\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresConfirmation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresCapture\/title","value":"STPPaymentIntentStatusRequiresCapture"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresCapture\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresPaymentMethod\/title","value":"STPPaymentIntentStatusRequiresPaymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresPaymentMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1canceled\/title","value":"STPPaymentIntentStatusCanceled"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1canceled\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusCanceled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresSource\/title","value":"STPPaymentIntentStatusRequiresSource"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1requiresSource\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusRequiresSource"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1unknown\/title","value":"STPPaymentIntentStatusUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus~1unknown\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatusUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/title","value":"STPPaymentIntentStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentStatus\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
