{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Enumeration","title":"STPPaymentIntentLastPaymentErrorType","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentLastPaymentErrorType","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype"]}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/s9EscapableP","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The type of the error represented by ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentLastPaymentError"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/api","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/apiConnection","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/authentication","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/idempotency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/invalidRequest","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/rateLimit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/unknown"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/CustomStringConvertible-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/CustomStringConvertible-Implementations","type":"topic","title":"CustomStringConvertible Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/customstringconvertible-implementations"},"doc://com.stripe.stripe-payments/s9EscapableP":{"title":"Swift.Escapable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s9EscapableP"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/unknown":{"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeUnknown","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/unknown","title":"STPPaymentIntentLastPaymentErrorType.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/unknown","abstract":[{"text":"An unknown error type.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/Equatable-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/Equatable-Implementations","abstract":[],"kind":"article","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/equatable-implementations","title":"Equatable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/idempotency":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"idempotency","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/idempotency","type":"topic","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeIdempotency","kind":"identifier"}],"title":"STPPaymentIntentLastPaymentErrorType.idempotency","abstract":[{"type":"text","text":"Keys for idempotent requests can only be used with the same parameters they were first used with."}],"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/idempotency"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/rateLimit":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeRateLimit"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Too many requests hit the API too quickly."}],"title":"STPPaymentIntentLastPaymentErrorType.rateLimit","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/rateLimit","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/ratelimit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rateLimit"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/invalidRequest":{"role":"symbol","abstract":[{"text":"Invalid request errors.  Typically, this is because your request has invalid parameters.","type":"text"}],"title":"STPPaymentIntentLastPaymentErrorType.invalidRequest","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/invalidRequest","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/invalidrequest","type":"topic","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidRequest","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/init(rawValue:)","abstract":[],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/apiConnection":{"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeAPIConnection","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/apiconnection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/apiConnection","abstract":[{"type":"text","text":"An error connecting to Stripe’s API."}],"role":"symbol","title":"STPPaymentIntentLastPaymentErrorType.apiConnection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"apiConnection","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/card":{"title":"STPPaymentIntentLastPaymentErrorType.card","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeCard"}],"abstract":[{"text":"Card errors are the most common type of error you should expect to handle.","type":"text"},{"text":" ","type":"text"},{"text":"They result when the user enters a card that can’t be charged for some reason.","type":"text"},{"text":" ","type":"text"},{"text":"Check the ","type":"text"},{"type":"codeVoice","code":"declineCode"},{"text":" property for the decline code.  The ","type":"text"},{"type":"codeVoice","code":"message"},{"text":" property contains a message you can show to your users.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/card","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"card"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/card"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/authentication":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authentication"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAuthentication"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/authentication","abstract":[{"text":"A failure to authenticate your customer.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/authentication","title":"STPPaymentIntentLastPaymentErrorType.authentication"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"title":"STPPaymentIntentLastPaymentErrorType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"role":"symbol","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPPaymentIntentLastPaymentError","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Some STPPaymentIntentLastPaymentError properties are only populated for certain error types."}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/rawrepresentable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentErrorType/api":{"title":"STPPaymentIntentLastPaymentErrorType.api","navigatorTitle":[{"text":"STPPaymentIntentLastPaymentErrorTypeAPI","kind":"identifier"}],"abstract":[{"type":"text","text":"An error with the Stripe API."}],"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterrortype\/api","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"api","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/api"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentIntentLastPaymentErrorType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/api","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/apiConnection","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/authentication","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/idempotency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/invalidRequest","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/rateLimit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentErrorType\/unknown"],"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1unknown\/title","value":"STPPaymentIntentLastPaymentErrorTypeUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1unknown\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1idempotency\/title","value":"STPPaymentIntentLastPaymentErrorTypeIdempotency","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1idempotency\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeIdempotency","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1rateLimit\/title","value":"STPPaymentIntentLastPaymentErrorTypeRateLimit","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1rateLimit\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeRateLimit","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1invalidRequest\/title","value":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1invalidRequest\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeInvalidRequest"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1apiConnection\/title","value":"STPPaymentIntentLastPaymentErrorTypeAPIConnection","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1apiConnection\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeAPIConnection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1card\/title","value":"STPPaymentIntentLastPaymentErrorTypeCard","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1card\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeCard","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1authentication\/title","value":"STPPaymentIntentLastPaymentErrorTypeAuthentication","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1authentication\/fragments","value":[{"text":"STPPaymentIntentLastPaymentErrorTypeAuthentication","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/title","value":"STPPaymentIntentLastPaymentErrorType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType\/navigatorTitle","value":[{"text":"STPPaymentIntentLastPaymentErrorType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1api\/title","value":"STPPaymentIntentLastPaymentErrorTypeAPI","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentErrorType~1api\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentErrorTypeAPI"}],"op":"replace"}]}]}