{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"metadata":{"role":"symbol","roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams","title":"STPPaymentMethodBacsDebitParams","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodBacsDebitParams"}],"navigatorTitle":[{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Create#Create_payment_method-Bacs_debit"}],"type":"paragraph"}],"name":"See Also"}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams"},"abstract":[{"text":"The user’s bank account details.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/accountNumber","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/sortCode"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/rootObjectName()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams/propertyNamesToFormFieldNamesMapping()":{"abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"code":"expMonth","type":"codeVoice"},{"text":", but the Stripe API expects a field called ","type":"text"},{"code":"exp_month","type":"codeVoice"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/propertyNamesToFormFieldNamesMapping()","url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams\/propertynamestoformfieldnamesmapping()","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"title":"propertyNamesToFormFieldNamesMapping()","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpformencodable","navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFormEncodable"}],"title":"STPFormEncodable","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams/sortCode":{"type":"topic","abstract":[{"text":"The sort code of the bank account (eg 10-88-00)","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sortCode","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"sortCode"}],"title":"sortCode","url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams\/sortcode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/sortCode","kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams/rootObjectName()":{"url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams\/rootobjectname()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/rootObjectName()","abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"type":"text","text":" below."}],"role":"symbol","kind":"symbol","title":"rootObjectName()","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rootObjectName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams":{"type":"topic","abstract":[{"type":"text","text":"The user’s bank account details."}],"url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"role":"symbol","title":"STPPaymentMethodBacsDebitParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodBacsDebitParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams/additionalAPIParameters":{"abstract":[{"text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:","type":"text"},{"type":"text","text":" "},{"type":"text","text":"var cardParams = STPCardParams()"},{"text":" ","type":"text"},{"text":"\/\/ add card values","type":"text"},{"type":"text","text":" "},{"text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]","type":"text"},{"type":"text","text":" "},{"type":"text","text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/additionalAPIParameters","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams\/additionalapiparameters","title":"additionalAPIParameters","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams/init":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/init","title":"init","url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams\/init","abstract":[],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams/accountNumber":{"abstract":[{"text":"The bank account number (eg 00012345)","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/accountNumber","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams\/accountnumber","title":"accountNumber","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"accountNumber","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"STPPaymentMethodBacsDebitParams","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodBacsDebitParams"}],"op":"replace"},{"op":"replace","value":[{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/accountNumber","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/sortCode"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/init"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams\/rootObjectName()"],"generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"propertyNamesToFormFieldNamesMapping","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1propertyNamesToFormFieldNamesMapping()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}]},{"value":"STPFormEncodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPFormEncodable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1sortCode\/title","op":"replace","value":"sortCode"},{"op":"replace","value":[{"text":"sortCode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1sortCode\/fragments"},{"value":"rootObjectName","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1rootObjectName()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1rootObjectName()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/title","value":"STPPaymentMethodBacsDebitParams"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBacsDebitParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBacsDebitParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1additionalAPIParameters\/title","value":"additionalAPIParameters","op":"replace"},{"value":[{"text":"additionalAPIParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1additionalAPIParameters\/fragments","op":"replace"},{"op":"replace","value":"accountNumber","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1accountNumber\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams~1accountNumber\/fragments","value":[{"text":"accountNumber","kind":"identifier"}]}]}]}