{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/affirm","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/afterpayClearpay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/alipay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/allowRedisplay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/alma","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/amazonPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/auBECSDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bacsDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bancontact","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billie","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billingDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/blik","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/boleto","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/cardPresent","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/cashApp","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/crypto","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/customerId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/eps","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/fpx","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/giropay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/grabPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/iDEAL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/klarna","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/link","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/liveMode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/mobilePay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/multibanco","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/netBanking","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/oxxo","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/payPal","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/przelewy24","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/revolutPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/satispay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sepaDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sofort","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/stripeId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sunbit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/swish","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/upi","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/usBankAccount"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/decodedObject(fromAPIResponse:)"]}],"kind":"symbol","metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"title":"STPPaymentMethod","role":"symbol","roleHeading":"Class","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},"abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethod"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"aside","name":"See Also","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods"}]}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethod"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethod"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/type":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod\/type","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/type","type":"topic","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"STPPaymentMethodType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"abstract":[{"type":"text","text":"The type of the PaymentMethod.  The corresponding, similarly named property contains additional information specific to the PaymentMethod type."},{"text":" ","type":"text"},{"text":"e.g. if the type is ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodTypeCard"},{"type":"text","text":", the "},{"code":"card","type":"codeVoice"},{"text":" property is also populated.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/allowRedisplay":{"abstract":[{"text":"This field indicates whether this payment method can be shown again to its customer in a checkout flow","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowRedisplay","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodAllowRedisplay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/allowredisplay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/allowRedisplay","navigatorTitle":[{"text":"allowRedisplay","kind":"identifier"}],"title":"allowRedisplay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/przelewy24":{"kind":"symbol","title":"przelewy24","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/przelewy24","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/przelewy24","navigatorTitle":[{"kind":"identifier","text":"przelewy24"}],"role":"symbol","abstract":[{"text":"If this is a Przelewy24 PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypePrzelewy24","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"przelewy24","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodPrzelewy24","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/affirm":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod\/affirm","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/affirm","type":"topic","title":"affirm","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"affirm"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirm","text":"STPPaymentMethodAffirm","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"affirm"}],"abstract":[{"text":"If this is an Affirm PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeAffirm"},{"type":"text","text":"), this contains additional details."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/multibanco":{"kind":"symbol","title":"multibanco","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/multibanco","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/multibanco","navigatorTitle":[{"text":"multibanco","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"If this is a Multibanco PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeMultibanco"},{"text":"), this contains additional details.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"multibanco","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibanco","text":"STPPaymentMethodMultibanco"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/oxxo":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod\/oxxo","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/oxxo","type":"topic","title":"oxxo","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"oxxo"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodOXXO","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXO"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"oxxo","kind":"identifier"}],"abstract":[{"text":"If this is an OXXO PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeOXXO"},{"type":"text","text":"), this contains additional details."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/klarna":{"kind":"symbol","title":"klarna","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/klarna","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/klarna","navigatorTitle":[{"text":"klarna","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"If this is an Klarna PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeKlarna"},{"text":"), this contains additional details.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"klarna","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodKlarna","text":"STPPaymentMethodKlarna"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/fpx":{"url":"\/documentation\/stripepayments\/stppaymentmethod\/fpx","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/fpx","type":"topic","title":"fpx","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fpx","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPX","text":"STPPaymentMethodFPX"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"fpx","kind":"identifier"}],"abstract":[{"text":"If this is an FPX PaymentMethod (ie ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeFPX"},{"text":"), this contains additional details.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/cashApp":{"kind":"symbol","title":"cashApp","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/cashapp","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/cashApp","navigatorTitle":[{"text":"cashApp","kind":"identifier"}],"role":"symbol","abstract":[{"text":"If this is an Cash App PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeCashApp"},{"text":"), this contains additional details.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cashApp"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCashApp","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCashApp"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/auBECSDebit":{"title":"auBECSDebit","kind":"symbol","abstract":[{"text":"If this is an AU BECS Debit PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeAUBECSDebit"},{"type":"text","text":"), this contains additional details."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"auBECSDebit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAUBECSDebit","text":"STPPaymentMethodAUBECSDebit","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"auBECSDebit"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/aubecsdebit","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/auBECSDebit"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/afterpayClearpay":{"abstract":[{"type":"text","text":"If this is an AfterpayClearpay PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeAfterpayClearpay"},{"text":"), this contains additional details. :nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/afterpayClearpay","title":"afterpayClearpay","url":"\/documentation\/stripepayments\/stppaymentmethod\/afterpayclearpay","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"afterpayClearpay","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpay","text":"STPPaymentMethodAfterpayClearpay"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"afterpayClearpay"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/billie":{"kind":"symbol","title":"billie","url":"\/documentation\/stripepayments\/stppaymentmethod\/billie","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billie","type":"topic","navigatorTitle":[{"text":"billie","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"If this is a Billie PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeBillie"},{"text":"), this contains additional details.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"billie","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillie","text":"STPPaymentMethodBillie"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/iDEAL":{"kind":"symbol","title":"iDEAL","url":"\/documentation\/stripepayments\/stppaymentmethod\/ideal","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/iDEAL","type":"topic","navigatorTitle":[{"text":"iDEAL","kind":"identifier"}],"role":"symbol","abstract":[{"text":"If this is a iDEAL PaymentMethod (ie ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeiDEAL"},{"text":"), this contains additional details.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"iDEAL"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodiDEAL","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodiDEAL"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/payPal":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod\/paypal","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/payPal","type":"topic","title":"payPal","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"payPal","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayPal","text":"STPPaymentMethodPayPal"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"payPal","kind":"identifier"}],"abstract":[{"type":"text","text":"If this is a PayPal PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypePayPal"},{"text":"), this contains additional details. :nodoc:","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/sepaDebit":{"kind":"symbol","title":"sepaDebit","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sepaDebit","url":"\/documentation\/stripepayments\/stppaymentmethod\/sepadebit","navigatorTitle":[{"kind":"identifier","text":"sepaDebit"}],"role":"symbol","abstract":[{"text":"If this is a SEPA Debit PaymentMethod (ie ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeSEPADebit"},{"type":"text","text":"), this contains additional details."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sepaDebit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSEPADebit","text":"STPPaymentMethodSEPADebit","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/description":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod\/description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/description","type":"topic","title":"description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[{"type":"text","text":":nodoc:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/boleto":{"kind":"symbol","title":"boleto","url":"\/documentation\/stripepayments\/stppaymentmethod\/boleto","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/boleto","type":"topic","navigatorTitle":[{"kind":"identifier","text":"boleto"}],"role":"symbol","abstract":[{"type":"text","text":"If this is an Boleto PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeBoleto"},{"type":"text","text":"), this contains additional details."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"boleto"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBoleto","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBoleto"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/blik":{"kind":"symbol","abstract":[{"type":"text","text":"If this is a BLIK PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypeBLIK","type":"codeVoice"},{"text":"), this contains additional details. :nodoc:","type":"text"}],"title":"blik","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blik"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodBLIK","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBLIK"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"blik","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/blik","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/blik"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/sunbit":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sunbit","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSunbit","text":"STPPaymentMethodSunbit"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/sunbit","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sunbit","abstract":[{"text":"If this is a Sunbit PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeSunibt"},{"text":"), this contains additional details.","type":"text"}],"title":"sunbit","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sunbit"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/alma":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alma"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlma","text":"STPPaymentMethodAlma"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"alma","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/alma","url":"\/documentation\/stripepayments\/stppaymentmethod\/alma","title":"alma","abstract":[{"text":"If this is a Alma PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeAlma","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/cardPresent":{"navigatorTitle":[{"text":"cardPresent","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/cardPresent","abstract":[{"type":"text","text":"If this is a card present PaymentMethod (ie "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeCardPresent"},{"type":"text","text":"), this contains additional details."}],"title":"cardPresent","url":"\/documentation\/stripepayments\/stppaymentmethod\/cardpresent","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cardPresent"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardPresent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardPresent"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/usBankAccount":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/usBankAccount","role":"symbol","navigatorTitle":[{"text":"usBankAccount","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"If this is a US Bank Account PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeUSBankAccount"},{"text":"), this contains additional details.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/usbankaccount","title":"usBankAccount","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"usBankAccount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount","text":"STPPaymentMethodUSBankAccount","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/decodedObject(fromAPIResponse:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/decodedObject(fromAPIResponse:)","role":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"code":"NSDictionary","type":"codeVoice"},{"type":"text","text":") into an instance of the class."}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/decodedobject(fromapiresponse:)","title":"decodedObject(fromAPIResponse:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/grabPay":{"title":"grabPay","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/grabPay","navigatorTitle":[{"text":"grabPay","kind":"identifier"}],"abstract":[{"type":"text","text":"If this is a GrabPay PaymentMethod (ie "},{"code":"self.type == STPPaymentMethodTypeGrabPay","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"grabPay","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGrabPay","text":"STPPaymentMethodGrabPay","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/grabpay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/netBanking":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/netbanking","abstract":[{"type":"text","text":"If this is a NetBanking PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeNetBanking"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","title":"netBanking","kind":"symbol","navigatorTitle":[{"text":"netBanking","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/netBanking","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"netBanking","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodNetBanking","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodNetBanking"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/shopPay":{"title":"shopPay","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/shopPay","abstract":[{"type":"text","text":"If this is a ShopPay PaymentMethod (i.e. "},{"text":"self.type == STPPaymentMethodTypeShopPay","type":"text"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","fragments":[{"text":"shopPay","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/shoppay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/revolutPay":{"title":"revolutPay","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"revolutPay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodRevolutPay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodRevolutPay"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/revolutPay","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"revolutPay"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/revolutpay","abstract":[{"text":"If this is an RevolutPay PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeRevolutPay","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/stripeId":{"url":"\/documentation\/stripepayments\/stppaymentmethod\/stripeid","kind":"symbol","title":"stripeId","type":"topic","role":"symbol","abstract":[{"text":"Unique identifier for the object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/stripeId","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stripeId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"stripeId","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/card":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/card","abstract":[{"text":"If this is a card PaymentMethod (ie ","type":"text"},{"code":"self.type == STPPaymentMethodTypeCard","type":"codeVoice"},{"text":"), this contains additional details.","type":"text"}],"role":"symbol","title":"card","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"card"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/card","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"card","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard","kind":"typeIdentifier","text":"STPPaymentMethodCard"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/initWithStripeId:type:allowRedisplay:":{"title":"initWithStripeId:type:allowRedisplay:","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/initWithStripeId:type:allowRedisplay:","navigatorTitle":[{"text":"initWithStripeId:type:allowRedisplay:","kind":"identifier"}],"abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithStripeId:type:allowRedisplay:","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/initwithstripeid:type:allowredisplay:"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","url":"\/documentation\/stripepayments\/stppaymentmethod","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethod"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"title":"STPPaymentMethod","kind":"symbol","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/sofort":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/sofort","abstract":[{"type":"text","text":"If this is a Sofort PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeSofort"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","title":"sofort","kind":"symbol","navigatorTitle":[{"text":"sofort","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sofort","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sofort","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodSofort","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSofort"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/metadata":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/metadata","abstract":[{"type":"text","text":"Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format."}],"role":"symbol","deprecated":true,"title":"metadata","kind":"symbol","navigatorTitle":[{"text":"metadata","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/metadata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/bacsDebit":{"title":"bacsDebit","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bacsDebit","navigatorTitle":[{"text":"bacsDebit","kind":"identifier"}],"abstract":[{"type":"text","text":"If this is a Bacs Debit PaymentMethod (ie "},{"code":"self.type == STPPaymentMethodTypeBacsDebit","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bacsDebit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebit","text":"STPPaymentMethodBacsDebit","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/bacsdebit"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/satispay":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/satispay","abstract":[{"type":"text","text":"If this is a Satispay PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeSatispay"},{"text":"), this contains additional details.","type":"text"}],"role":"symbol","title":"satispay","kind":"symbol","navigatorTitle":[{"text":"satispay","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/satispay","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"satispay","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodSatispay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSatispay"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/eps":{"title":"eps","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/eps","navigatorTitle":[{"kind":"identifier","text":"eps"}],"abstract":[{"type":"text","text":"If this is an EPS PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypeEPS","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"eps","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodEPS","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodEPS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/eps"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/link":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"link","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodLink","text":"STPPaymentMethodLink","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/link","url":"\/documentation\/stripepayments\/stppaymentmethod\/link","title":"link","navigatorTitle":[{"kind":"identifier","text":"link"}],"abstract":[{"type":"text","text":"If this is a Link PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeLink"},{"type":"text","text":"), this contains additional details."}]},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/liveMode":{"title":"liveMode","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/liveMode","navigatorTitle":[{"kind":"identifier","text":"liveMode"}],"abstract":[{"type":"codeVoice","code":"YES"},{"text":" if the object exists in live mode or the value ","type":"text"},{"type":"codeVoice","code":"NO"},{"type":"text","text":" if the object exists in test mode."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"liveMode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/livemode"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"kind":"symbol","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"title":"STPAPIResponseDecodable","role":"symbol","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/allResponseFields":{"title":"allResponseFields","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/allresponsefields"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/giropay":{"title":"giropay","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/giropay","navigatorTitle":[{"kind":"identifier","text":"giropay"}],"abstract":[{"type":"text","text":"If this is a giropay PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypeGiropay","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"giropay","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodGiropay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGiropay"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/giropay"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/billingDetails":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/billingdetails","abstract":[{"type":"text","text":"Billing information associated with the PaymentMethod that may be used or required by particular types of payment methods."}],"role":"symbol","title":"billingDetails","kind":"symbol","navigatorTitle":[{"text":"billingDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billingDetails","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"billingDetails","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/swish":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"swish","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodSwish","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSwish","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/swish","type":"topic","navigatorTitle":[{"kind":"identifier","text":"swish"}],"abstract":[{"text":"If this is a Swish PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeSwish"},{"type":"text","text":"), this contains additional details."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/swish","title":"swish","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/customerId":{"title":"customerId","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/customerId","navigatorTitle":[{"kind":"identifier","text":"customerId"}],"abstract":[{"type":"text","text":"The ID of the Customer to which this PaymentMethod is saved. Nil when the PaymentMethod has not been saved to a Customer."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customerId","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/customerid"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/amazonPay":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/amazonpay","abstract":[{"text":"If this is a Amazon Pay PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeAmazonPay","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","title":"amazonPay","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"amazonPay"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/amazonPay","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"amazonPay","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAmazonPay","text":"STPPaymentMethodAmazonPay"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/alipay":{"title":"alipay","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/alipay","navigatorTitle":[{"text":"alipay","kind":"identifier"}],"abstract":[{"type":"text","text":"If this is an Alipay PaymentMethod (ie "},{"code":"self.type == STPPaymentMethodTypeAlipay","type":"codeVoice"},{"type":"text","text":"), this contains additional detailsl"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"alipay","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipay","text":"STPPaymentMethodAlipay"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/alipay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/created":{"kind":"symbol","title":"created","abstract":[{"text":"Time at which the object was created. Measured in seconds since the Unix epoch.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"created","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/created","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/created"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/mobilePay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/mobilePay","type":"topic","abstract":[{"text":"If this is a MobilePay PaymentMethod (i.e. ","type":"text"},{"code":"self.type == STPPaymentMethodTypeMobilePay","type":"codeVoice"},{"type":"text","text":"), this contains additional details."}],"url":"\/documentation\/stripepayments\/stppaymentmethod\/mobilepay","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mobilePay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMobilePay","text":"STPPaymentMethodMobilePay"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"mobilePay","kind":"identifier"}],"title":"mobilePay","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/bancontact":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/bancontact","abstract":[{"text":"If this is a Bancontact PaymentMethod (i.e. ","type":"text"},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeBancontact"},{"type":"text","text":"), this contains additional details."}],"role":"symbol","title":"bancontact","kind":"symbol","navigatorTitle":[{"text":"bancontact","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bancontact","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bancontact","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontact","text":"STPPaymentMethodBancontact"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/upi":{"title":"upi","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/upi","navigatorTitle":[{"text":"upi","kind":"identifier"}],"abstract":[{"type":"text","text":"If this is a UPI PaymentMethod (i.e. "},{"code":"self.type == STPPaymentMethodTypeUPI","type":"codeVoice"},{"type":"text","text":"), this contains additional details. :nodoc:"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"upi","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUPI","kind":"typeIdentifier","text":"STPPaymentMethodUPI"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/upi"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod/crypto":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethod\/crypto","abstract":[{"type":"text","text":"If this is a Crypto PaymentMethod (i.e. "},{"type":"codeVoice","code":"self.type == STPPaymentMethodTypeCrypto"},{"text":"), this contains additional details.","type":"text"}],"role":"symbol","title":"crypto","kind":"symbol","navigatorTitle":[{"text":"crypto","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/crypto","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"crypto","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCrypto","text":"STPPaymentMethodCrypto"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPPaymentMethod","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/affirm","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/afterpayClearpay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/alipay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/allowRedisplay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/alma","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/amazonPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/auBECSDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bacsDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/bancontact","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billie","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/billingDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/blik","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/boleto","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/cardPresent","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/cashApp","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/crypto","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/customerId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/eps","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/fpx","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/giropay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/grabPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/iDEAL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/klarna","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/link","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/liveMode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/mobilePay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/multibanco","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/netBanking","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/oxxo","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/payPal","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/przelewy24","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/revolutPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/satispay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sepaDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/shopPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sofort","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/stripeId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/sunbit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/swish","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/upi","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/usBankAccount"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/initWithStripeId:type:allowRedisplay:"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod\/decodedObject(fromAPIResponse:)"]}]},{"op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethod"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"type","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1type\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1allowRedisplay\/title","value":"allowRedisplay","op":"replace"},{"op":"replace","value":[{"text":"allowRedisplay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1allowRedisplay\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1przelewy24\/title","value":"przelewy24"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1przelewy24\/fragments","value":[{"text":"przelewy24","kind":"identifier"}],"op":"replace"},{"value":"affirm","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1affirm\/title"},{"value":[{"text":"affirm","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1affirm\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1multibanco\/title","op":"replace","value":"multibanco"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1multibanco\/fragments","value":[{"kind":"identifier","text":"multibanco"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1oxxo\/title","value":"oxxo"},{"value":[{"kind":"identifier","text":"oxxo"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1oxxo\/fragments"},{"value":"klarna","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1klarna\/title"},{"value":[{"kind":"identifier","text":"klarna"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1klarna\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1fpx\/title","value":"fpx","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1fpx\/fragments","value":[{"text":"fpx","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1cashApp\/title","op":"replace","value":"cashApp"},{"value":[{"text":"cashApp","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1cashApp\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1auBECSDebit\/title","value":"auBECSDebit","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1auBECSDebit\/fragments","value":[{"text":"auBECSDebit","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1afterpayClearpay\/title","value":"afterpayClearpay","op":"replace"},{"op":"replace","value":[{"text":"afterpayClearpay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1afterpayClearpay\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1billie\/title","value":"billie"},{"op":"replace","value":[{"kind":"identifier","text":"billie"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1billie\/fragments"},{"op":"replace","value":"iDEAL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1iDEAL\/title"},{"value":[{"text":"iDEAL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1iDEAL\/fragments","op":"replace"},{"value":"payPal","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1payPal\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1payPal\/fragments","value":[{"kind":"identifier","text":"payPal"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1sepaDebit\/title","value":"sepaDebit"},{"op":"replace","value":[{"kind":"identifier","text":"sepaDebit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1sepaDebit\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1description\/title","value":"description","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1description\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1boleto\/title","value":"boleto"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1boleto\/fragments","value":[{"text":"boleto","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1blik\/title","value":"blik"},{"value":[{"text":"blik","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1blik\/fragments"},{"value":"sunbit","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1sunbit\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1sunbit\/fragments","op":"replace","value":[{"kind":"identifier","text":"sunbit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1alma\/title","value":"alma"},{"value":[{"kind":"identifier","text":"alma"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1alma\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1cardPresent\/title","op":"replace","value":"cardPresent"},{"value":[{"kind":"identifier","text":"cardPresent"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1cardPresent\/fragments"},{"value":"usBankAccount","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1usBankAccount\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1usBankAccount\/fragments","op":"replace","value":[{"kind":"identifier","text":"usBankAccount"}]},{"op":"replace","value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1decodedObject(fromAPIResponse:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace"},{"value":"grabPay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1grabPay\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1grabPay\/fragments","value":[{"text":"grabPay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1netBanking\/title","op":"replace","value":"netBanking"},{"value":[{"text":"netBanking","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1netBanking\/fragments","op":"replace"},{"value":"revolutPay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1revolutPay\/title"},{"value":[{"kind":"identifier","text":"revolutPay"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1revolutPay\/fragments"},{"op":"replace","value":"stripeId","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1stripeId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1stripeId\/fragments","value":[{"text":"stripeId","kind":"identifier"}]},{"value":"card","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1card\/title","op":"replace"},{"op":"replace","value":[{"text":"card","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1card\/fragments"},{"value":"STPPaymentMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethod"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1sofort\/title","value":"sofort"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1sofort\/fragments","value":[{"kind":"identifier","text":"sofort"}],"op":"replace"},{"op":"replace","value":"metadata","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1metadata\/title"},{"value":[{"kind":"identifier","text":"metadata"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1metadata\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1bacsDebit\/title","value":"bacsDebit","op":"replace"},{"value":[{"text":"bacsDebit","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1bacsDebit\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1satispay\/title","value":"satispay","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1satispay\/fragments","value":[{"kind":"identifier","text":"satispay"}]},{"op":"replace","value":"eps","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1eps\/title"},{"value":[{"kind":"identifier","text":"eps"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1eps\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1link\/title","value":"link"},{"value":[{"text":"link","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1link\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1liveMode\/title","value":"liveMode"},{"op":"replace","value":[{"text":"liveMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1liveMode\/fragments"},{"value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1allResponseFields\/title","value":"allResponseFields"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1giropay\/title","op":"replace","value":"giropay"},{"op":"replace","value":[{"kind":"identifier","text":"giropay"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1giropay\/fragments"},{"value":"billingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1billingDetails\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1billingDetails\/fragments","value":[{"text":"billingDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1swish\/title","value":"swish","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1swish\/fragments","value":[{"kind":"identifier","text":"swish"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1customerId\/title","value":"customerId"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1customerId\/fragments","value":[{"kind":"identifier","text":"customerId"}],"op":"replace"},{"value":"amazonPay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1amazonPay\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1amazonPay\/fragments","value":[{"kind":"identifier","text":"amazonPay"}]},{"value":"alipay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1alipay\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1alipay\/fragments","op":"replace","value":[{"text":"alipay","kind":"identifier"}]},{"value":"created","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1created\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1created\/fragments","op":"replace","value":[{"kind":"identifier","text":"created"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1mobilePay\/title","value":"mobilePay","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1mobilePay\/fragments","value":[{"text":"mobilePay","kind":"identifier"}]},{"op":"replace","value":"bancontact","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1bancontact\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1bancontact\/fragments","value":[{"kind":"identifier","text":"bancontact"}],"op":"replace"},{"value":"upi","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1upi\/title","op":"replace"},{"value":[{"text":"upi","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1upi\/fragments"},{"op":"replace","value":"crypto","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1crypto\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod~1crypto\/fragments","value":[{"text":"crypto","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}