{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"type":"text","text":"A Card Wallet."}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/masterpass","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/visaCheckout"],"anchor":"Instance-Properties"},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/decodedObject(fromAPIResponse:)"],"generated":true,"title":"Type Methods"}],"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodCardWallet","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWallet","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardWallet"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Object#Payment_method_object-Card-Wallet","type":"text"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardwallet"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/type":{"kind":"symbol","abstract":[{"type":"text","text":"The type of the Card Wallet. A matching property is populated if the type is "},{"code":"STPPaymentMethodCardWalletTypeMasterpass","type":"codeVoice"},{"type":"text","text":" or "},{"code":"STPPaymentMethodCardWalletTypeVisaCheckout","type":"codeVoice"},{"type":"text","text":" containing additional information specific to the Card Wallet type."}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/type","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodCardWalletType","text":"STPPaymentMethodCardWalletType"}],"type":"topic","navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/type","role":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/allResponseFields":{"kind":"symbol","abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"type":"text","text":" "},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"title":"allResponseFields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/allResponseFields","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/allresponsefields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","title":"STPAPIResponseDecodable","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/decodedObject(fromAPIResponse:)":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/decodedobject(fromapiresponse:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"type":"topic","title":"decodedObject(fromAPIResponse:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/description","abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet","abstract":[{"type":"text","text":"A Card Wallet."}],"type":"topic","title":"STPPaymentMethodCardWallet","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWallet","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/masterpass":{"title":"masterpass","url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/masterpass","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/masterpass","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"masterpass","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodCardWalletMasterpass","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletMasterpass"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"masterpass","kind":"identifier"}],"abstract":[{"type":"text","text":"Contains additional Masterpass information, if the type of the Card Wallet is "},{"code":"STPPaymentMethodCardWalletTypeMasterpass","type":"codeVoice"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardWallet/visaCheckout":{"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"visaCheckout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardWalletVisaCheckout","kind":"typeIdentifier","text":"STPPaymentMethodCardWalletVisaCheckout"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/visaCheckout","abstract":[{"type":"text","text":"Contains additional Visa Checkout information, if the type of the Card Wallet is "},{"type":"codeVoice","code":"STPPaymentMethodCardWalletTypeVisaCheckout"}],"title":"visaCheckout","type":"topic","navigatorTitle":[{"text":"visaCheckout","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardwallet\/visacheckout"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodCardWallet"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/masterpass","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/visaCheckout"],"anchor":"Instance-Properties","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardWallet\/decodedObject(fromAPIResponse:)"],"generated":true,"anchor":"Type-Methods"}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"kind":"relationships","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardWallet","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1allResponseFields\/title","value":"allResponseFields"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","op":"replace","value":"STPAPIResponseDecodable"},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"value":"STPPaymentMethodCardWallet","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardWallet"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet\/navigatorTitle","value":[{"text":"STPPaymentMethodCardWallet","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1masterpass\/title","value":"masterpass"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1masterpass\/fragments","value":[{"text":"masterpass","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1visaCheckout\/title","value":"visaCheckout"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardWallet~1visaCheckout\/fragments","value":[{"kind":"identifier","text":"visaCheckout"}]}]}]}