{"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage","modules":[{"name":"StripePayments"}],"title":"STPPaymentIntentSetupFutureUsage","roleHeading":"Enumeration","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"symbolKind":"enum","navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_intents\/Object#Payment_intent_object-Setup_future_usage","type":"text"}]}],"style":"note","type":"aside"}]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships"}],"abstract":[{"type":"text","text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes."},{"text":" ","type":"text"},{"type":"text","text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/none","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/offSession","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/onSession","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/unknown"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentsetupfutureusage"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/init(rawvalue:)","abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/init(rawValue:)"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/onSession":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageOnSession"}],"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/onsession","type":"topic","abstract":[{"type":"text","text":"Indicates you intend to only reuse the payment method when the customer is in your checkout flow."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSession"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/onSession","title":"STPPaymentIntentSetupFutureUsage.onSession"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/Equatable-Implementations":{"type":"topic","kind":"article","title":"Equatable Implementations","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/Equatable-Implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/none":{"url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/none","abstract":[{"type":"text","text":"No value was provided."}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"role":"symbol","title":"STPPaymentIntentSetupFutureUsage.none","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/none","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageNone"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/unknown":{"abstract":[{"text":"Unknown value.  Update your SDK, or use ","type":"text"},{"type":"codeVoice","code":"allResponseFields"},{"type":"text","text":" for custom handling."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/unknown","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageUnknown"}],"title":"STPPaymentIntentSetupFutureUsage.unknown","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/unknown","kind":"symbol"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage":{"url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}],"abstract":[{"text":"Indicates how you intend to use the payment method that your customer provides after the current payment completes.","type":"text"},{"type":"text","text":" "},{"text":"If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"}],"title":"STPPaymentIntentSetupFutureUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/customstringconvertible-implementations","kind":"article","role":"collectionGroup","type":"topic","abstract":[],"title":"CustomStringConvertible Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/RawRepresentable-Implementations","type":"topic","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/rawrepresentable-implementations","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentSetupFutureUsage/offSession":{"role":"symbol","title":"STPPaymentIntentSetupFutureUsage.offSession","url":"\/documentation\/stripepayments\/stppaymentintentsetupfutureusage\/offsession","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/offSession","type":"topic","abstract":[{"text":"Indicates you intend to reuse the payment method when the customer may or may not be in your checkout flow.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offSession"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntentSetupFutureUsageOffSession","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPPaymentIntentSetupFutureUsage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/none","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/offSession","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/onSession","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentSetupFutureUsage\/unknown"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1onSession\/title","op":"replace","value":"STPPaymentIntentSetupFutureUsageOnSession"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1onSession\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageOnSession"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1none\/title","op":"replace","value":"STPPaymentIntentSetupFutureUsageNone"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1none\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageNone"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1unknown\/title","value":"STPPaymentIntentSetupFutureUsageUnknown","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsageUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1unknown\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/title","op":"replace","value":"STPPaymentIntentSetupFutureUsage"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}]},{"value":[{"kind":"identifier","text":"STPPaymentIntentSetupFutureUsage"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1offSession\/title","value":"STPPaymentIntentSetupFutureUsageOffSession","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentSetupFutureUsage~1offSession\/fragments","value":[{"text":"STPPaymentIntentSetupFutureUsageOffSession","kind":"identifier"}],"op":"replace"}]}]}