{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/failed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/pass","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unavailable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unchecked","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unknown"],"generated":true,"anchor":"Enumeration-Cases"},{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/init(rawValue:)"],"title":"Initializers"},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"platforms":["iOS"]}]}],"abstract":[{"text":"The result of a check on a Card address or CVC.","type":"text"}],"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"roleHeading":"Enumeration","title":"STPPaymentMethodCardCheckResult","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"role":"symbol","symbolKind":"enum","externalID":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardcheckresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardcheckresult"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/CustomStringConvertible-Implementations":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/CustomStringConvertible-Implementations","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/customstringconvertible-implementations","kind":"article","role":"collectionGroup","title":"CustomStringConvertible Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/RawRepresentable-Implementations":{"role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/rawrepresentable-implementations","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/unavailable":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unavailable","url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/unavailable","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unavailable","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The check is unavailable."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultUnavailable"}],"title":"STPPaymentMethodCardCheckResult.unavailable","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/Equatable-Implementations":{"role":"collectionGroup","url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","kind":"article"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/pass":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultPass"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"pass","kind":"identifier"}],"title":"STPPaymentMethodCardCheckResult.pass","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/pass","abstract":[{"type":"text","text":"The check passed."}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/pass","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/failed":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultFailed"}],"abstract":[{"type":"text","text":"The check failed."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/failed","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/failed","kind":"symbol","role":"symbol","title":"STPPaymentMethodCardCheckResult.failed"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult","abstract":[{"type":"text","text":"The result of a check on a Card address or CVC."}],"navigatorTitle":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"title":"STPPaymentMethodCardCheckResult","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","kind":"symbol","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/init(rawvalue:)","type":"topic","kind":"symbol","role":"symbol","title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/unchecked":{"title":"STPPaymentMethodCardCheckResult.unchecked","abstract":[{"type":"text","text":"The value was not checked."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unchecked","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unchecked","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/unchecked","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultUnchecked"}],"role":"symbol"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/unknown":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultUnknown"}],"abstract":[{"text":"Represents an unknown or null value.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unknown","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/unknown","kind":"symbol","role":"symbol","title":"STPPaymentMethodCardCheckResult.unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodCardCheckResult","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"op":"replace"},{"value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/failed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/pass","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unavailable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unchecked","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unknown"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"STPPaymentMethodCardCheckResultUnavailable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1unavailable\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1unavailable\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultUnavailable"}]},{"op":"replace","value":"STPPaymentMethodCardCheckResultPass","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1pass\/title"},{"value":[{"text":"STPPaymentMethodCardCheckResultPass","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1pass\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1failed\/title","value":"STPPaymentMethodCardCheckResultFailed","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultFailed"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1failed\/fragments"},{"op":"replace","value":"STPPaymentMethodCardCheckResult","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments"},{"value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/navigatorTitle"},{"value":"STPPaymentMethodCardCheckResultUnchecked","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1unchecked\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1unchecked\/fragments","op":"replace","value":[{"text":"STPPaymentMethodCardCheckResultUnchecked","kind":"identifier"}]},{"value":"STPPaymentMethodCardCheckResultUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1unknown\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1unknown\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultUnknown"}]}]}]}