{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","kind":"relationships"}],"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodGrabPay","title":"STPPaymentMethodGrabPay","roleHeading":"Class"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodgrabpay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodgrabpay"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"type":"aside","content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Payment_methods\/Object#Payment_method_object-Grabpay","type":"text"}],"type":"paragraph"}],"name":"See Also","style":"note"}],"kind":"content"}],"abstract":[{"type":"text","text":"A GrabPay PaymentMethod"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/description"],"generated":true,"anchor":"Instance-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/decodedObject(fromAPIResponse:)"],"generated":true,"anchor":"Type-Methods"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"title":"STPAPIResponseDecodable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodGrabPay/allResponseFields":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/allResponseFields","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodgrabpay\/allresponsefields","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"title":"allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodGrabPay":{"kind":"symbol","title":"STPPaymentMethodGrabPay","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodgrabpay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodGrabPay","kind":"identifier"}],"abstract":[{"text":"A GrabPay PaymentMethod","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodGrabPay/decodedObject(fromAPIResponse:)":{"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"kind":"symbol","title":"decodedObject(fromAPIResponse:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodgrabpay\/decodedobject(fromapiresponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/decodedObject(fromAPIResponse:)","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"role":"symbol"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodGrabPay/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodgrabpay\/description","kind":"symbol","title":"description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/description","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodGrabPay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodGrabPay","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentMethodGrabPay","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/description"]},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGrabPay\/decodedObject(fromAPIResponse:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodGrabPay","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay~1allResponseFields\/title","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay\/title","value":"STPPaymentMethodGrabPay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodGrabPay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay\/navigatorTitle","value":[{"text":"STPPaymentMethodGrabPay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGrabPay~1description\/fragments","value":[{"text":"description","kind":"identifier"}]}]}]}