{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppincompletionblock"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPinCompletionBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIssuingCardPin","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIssuingCardPin","text":"STPIssuingCardPin"},{"text":"?, ","kind":"text"},{"text":"STPPinStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","preciseIdentifier":"c:@M@StripePayments@E@STPPinStatus"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"cardPin","content":[{"type":"paragraph","inlineContent":[{"text":"The Stripe card PIN from the response. Will be nil if an error occurs. - seealso: STPIssuingCardPin","type":"text"}]}]},{"name":"status","content":[{"type":"paragraph","inlineContent":[{"text":"The status to help you sort between different error state, or STPPinSuccess when succesful. - seealso: STPPinStatus for possible values.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The error returned from the response, or nil if none occurs. - seealso: StripeError.h for possible values."}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"}],"abstract":[{"text":"A callback to be run with a card PIN response from the Stripe API.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinCompletionBlock","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Alias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPinCompletionBlock","kind":"identifier"}],"externalID":"s:14StripePayments21STPPinCompletionBlocka","navigatorTitle":[{"kind":"identifier","text":"STPPinCompletionBlock"}],"modules":[{"name":"StripePayments"}],"title":"STPPinCompletionBlock","symbolKind":"typealias","role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIssuingCardPin":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIssuingCardPin","url":"\/documentation\/stripepayments\/stpissuingcardpin","navigatorTitle":[{"text":"STPIssuingCardPin","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Information related to a Stripe Issuing card, including the PIN","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPIssuingCardPin","kind":"identifier"}],"title":"STPIssuingCardPin"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinStatus":{"url":"\/documentation\/stripepayments\/stppinstatus","kind":"symbol","abstract":[{"type":"text","text":"An enum representing the success and error states of PIN management"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinStatus","role":"symbol","title":"STPPinStatus","type":"topic","navigatorTitle":[{"text":"STPPinStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPinStatus","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPinCompletionBlock":{"url":"\/documentation\/stripepayments\/stppincompletionblock","kind":"symbol","role":"symbol","title":"STPPinCompletionBlock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPinCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPinCompletionBlock","kind":"identifier"}],"abstract":[{"type":"text","text":"A callback to be run with a card PIN response from the Stripe API."}],"navigatorTitle":[{"kind":"identifier","text":"STPPinCompletionBlock"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIssuingCardPin\/title","value":"STPIssuingCardPin"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIssuingCardPin\/fragments","value":[{"kind":"identifier","text":"STPIssuingCardPin"}]},{"value":[{"text":"STPIssuingCardPin","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIssuingCardPin\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/title","value":"STPPinStatus","op":"replace"},{"value":[{"text":"STPPinStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPinStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPinStatus\/navigatorTitle"}]}]}