{"abstract":[{"type":"text","text":"Account holder type"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/company","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/individual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/unknown"],"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype"]}],"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType","title":"STPPaymentMethodUSBankAccountHolderType","symbolKind":"enum","roleHeading":"Enumeration"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/init(rawValue:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/init(rawValue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/init(rawvalue:)","abstract":[],"type":"topic","title":"init(rawValue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/CustomStringConvertible-Implementations":{"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/CustomStringConvertible-Implementations","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/rawrepresentable-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/unknown":{"abstract":[{"type":"text","text":"This is an unknown type that’s been added since the SDK"},{"type":"text","text":" "},{"type":"text","text":"was last updated."},{"text":" ","type":"text"},{"text":"Update your SDK, or use the ","type":"text"},{"code":"allResponseFields","type":"codeVoice"},{"text":" ","type":"text"},{"text":"for custom handling.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/unknown","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeUnknown"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/unknown","title":"STPPaymentMethodUSBankAccountHolderType.unknown"},"doc://com.stripe.stripe-payments/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/individual":{"abstract":[{"type":"text","text":"Account belongs to an individual"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderTypeIndividual"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/individual","kind":"symbol","title":"STPPaymentMethodUSBankAccountHolderType.individual","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/individual","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"individual","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/equatable-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/Equatable-Implementations","title":"Equatable Implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType":{"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype","title":"STPPaymentMethodUSBankAccountHolderType","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Account holder type"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType/company":{"title":"STPPaymentMethodUSBankAccountHolderType.company","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/company","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype\/company","abstract":[{"text":"Account belongs to a company","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountHolderTypeCompany","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"company"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"STPPaymentMethodUSBankAccountHolderType","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/company","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/individual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType\/unknown"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1unknown\/title","op":"replace","value":"STPPaymentMethodUSBankAccountHolderTypeUnknown"},{"op":"replace","value":[{"text":"STPPaymentMethodUSBankAccountHolderTypeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1unknown\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1individual\/title","value":"STPPaymentMethodUSBankAccountHolderTypeIndividual"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1individual\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountHolderTypeIndividual","kind":"identifier"}]},{"value":"STPPaymentMethodUSBankAccountHolderType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/title"},{"value":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1company\/title","value":"STPPaymentMethodUSBankAccountHolderTypeCompany"},{"value":[{"text":"STPPaymentMethodUSBankAccountHolderTypeCompany","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType~1company\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}