{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"}],"role":"symbol","roleHeading":"Type Alias","modules":[{"name":"StripePayments"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"}],"title":"STPPaymentHandlerActionPaymentIntentCompletionBlock","externalID":"s:14StripePayments51STPPaymentHandlerActionPaymentIntentCompletionBlocka","symbolKind":"typealias"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","abstract":[{"type":"text","text":"Completion block typedef for use in "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" methods for Payment Intents."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"text":"STPPaymentHandlerActionStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentHandlerActionStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus"},{"text":", ","kind":"text"},{"text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"},{"text":"?, ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymenthandleractionpaymentintentcompletionblock"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","title":"STPPaymentIntent","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntent"}],"kind":"symbol","abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionStatus":{"type":"topic","role":"symbol","title":"STPPaymentHandlerActionStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionstatus","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionStatus","abstract":[{"code":"STPPaymentHandlerActionStatus","type":"codeVoice"},{"text":" represents the possible outcomes of requesting an action by ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":". An action could be confirming and\/or handling the next action for a PaymentIntent.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentHandlerActionPaymentIntentCompletionBlock":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}],"url":"\/documentation\/stripepayments\/stppaymenthandleractionpaymentintentcompletionblock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentHandlerActionPaymentIntentCompletionBlock","kind":"symbol","abstract":[{"type":"text","text":"Completion block typedef for use in "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" methods for Payment Intents."}],"title":"STPPaymentHandlerActionPaymentIntentCompletionBlock"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","op":"replace","value":"STPPaymentIntent"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentIntent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/title","op":"replace","value":"STPPaymentHandlerActionStatus"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/fragments","op":"replace","value":[{"text":"STPPaymentHandlerActionStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentHandlerActionStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentHandlerActionStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}