{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodnetbankingparams"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodnetbankingparams"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams"},"kind":"symbol","topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/bank"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/rootObjectName()"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodNetBankingParams"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodNetBankingParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodNetBankingParams","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"StripePayments"}],"symbolKind":"class","title":"STPPaymentMethodNetBankingParams","navigatorTitle":[{"text":"STPPaymentMethodNetBankingParams","kind":"identifier"}],"role":"symbol"},"abstract":[{"text":"An object representing parameters used to create a NetBanking Payment Method","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodNetBankingParams/bank":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodnetbankingparams\/bank","title":"bank","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/bank","navigatorTitle":[{"text":"bank","kind":"identifier"}],"abstract":[{"type":"text","text":"Customer’s Bank Name. Required."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bank","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodNetBankingParams/init":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/init","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodnetbankingparams\/init","kind":"symbol","title":"init"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodNetBankingParams/rootObjectName()":{"role":"symbol","type":"topic","title":"rootObjectName()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/rootObjectName()","url":"\/documentation\/stripepayments\/stppaymentmethodnetbankingparams\/rootobjectname()","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodNetBankingParams/propertyNamesToFormFieldNamesMapping()":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/propertyNamesToFormFieldNamesMapping()","type":"topic","role":"symbol","abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"code":"expMonth","type":"codeVoice"},{"type":"text","text":", but the Stripe API expects a field called "},{"code":"exp_month","type":"codeVoice"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"title":"propertyNamesToFormFieldNamesMapping()","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodnetbankingparams\/propertynamestoformfieldnamesmapping()"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodNetBankingParams/additionalAPIParameters":{"title":"additionalAPIParameters","navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/additionalAPIParameters","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodnetbankingparams\/additionalapiparameters","abstract":[{"type":"text","text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:"},{"type":"text","text":" "},{"type":"text","text":"var cardParams = STPCardParams()"},{"type":"text","text":" "},{"type":"text","text":"\/\/ add card values"},{"type":"text","text":" "},{"type":"text","text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]"},{"type":"text","text":" "},{"type":"text","text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodNetBankingParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a NetBanking Payment Method"}],"navigatorTitle":[{"text":"STPPaymentMethodNetBankingParams","kind":"identifier"}],"type":"topic","title":"STPPaymentMethodNetBankingParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodnetbankingparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodNetBankingParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFormEncodable","kind":"identifier"}],"navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"title":"STPFormEncodable","url":"\/documentation\/stripepayments\/stpformencodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentMethodNetBankingParams","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodNetBankingParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodNetBankingParams"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/bank"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/init"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodNetBankingParams\/rootObjectName()"],"anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodNetBankingParams","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","value":"bank","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams~1bank\/title"},{"op":"replace","value":[{"text":"bank","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams~1bank\/fragments"},{"op":"replace","value":"rootObjectName","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams~1rootObjectName()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams~1rootObjectName()\/fragments"},{"op":"replace","value":"propertyNamesToFormFieldNamesMapping","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams~1propertyNamesToFormFieldNamesMapping()\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams~1propertyNamesToFormFieldNamesMapping()\/fragments"},{"op":"replace","value":"additionalAPIParameters","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams~1additionalAPIParameters\/title"},{"op":"replace","value":[{"text":"additionalAPIParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams~1additionalAPIParameters\/fragments"},{"op":"replace","value":"STPPaymentMethodNetBankingParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodNetBankingParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodNetBankingParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodNetBankingParams\/navigatorTitle"},{"op":"replace","value":"STPFormEncodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPFormEncodable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle"}]}]}