{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentActionType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentActionType"}],"roleHeading":"Enumeration","modules":[{"name":"StripePayments"}],"title":"STPPaymentIntentActionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentActionType","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentActionType"},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/redirectToURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/unknown"],"generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentactiontype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentactiontype"]}],"kind":"symbol","abstract":[{"text":"Types of Actions from a ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":", when the payment intent"},{"text":" ","type":"text"},{"text":"status is ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentStatusRequiresAction"},{"text":".","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/unknown":{"deprecated":true,"abstract":[{"type":"text","text":"This is an unknown action, that’s been added since the SDK"},{"text":" ","type":"text"},{"text":"was last updated.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"nextAction.allResponseFields"},{"type":"text","text":" "},{"type":"text","text":"for custom handling."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentActionTypeUnknown"}],"title":"STPPaymentIntentActionType.unknown","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/unknown","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/Equatable-Implementations":{"abstract":[],"type":"topic","title":"Equatable Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/Equatable-Implementations","url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/equatable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/init(rawValue:)":{"type":"topic","role":"symbol","kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/init(rawvalue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/customstringconvertible-implementations","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/CustomStringConvertible-Implementations","kind":"article","title":"CustomStringConvertible Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType":{"abstract":[{"type":"text","text":"Types of Actions from a "},{"code":"STPPaymentIntent","type":"codeVoice"},{"text":", when the payment intent","type":"text"},{"type":"text","text":" "},{"text":"status is ","type":"text"},{"code":"STPPaymentIntentStatusRequiresAction","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentIntentActionType","kind":"identifier"}],"type":"topic","title":"STPPaymentIntentActionType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentActionType"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType","url":"\/documentation\/stripepayments\/stppaymentintentactiontype"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentActionType/redirectToURL":{"type":"topic","role":"symbol","deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentActionTypeRedirectToURL"}],"title":"STPPaymentIntentActionType.redirectToURL","url":"\/documentation\/stripepayments\/stppaymentintentactiontype\/redirecttourl","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/redirectToURL","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"redirectToURL"}],"abstract":[{"type":"text","text":"The payment intent needs to be authorized by the user. We provide"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPRedirectContext"},{"text":" to handle the url redirections necessary.","type":"text"}]},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentIntentActionType","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentActionType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentActionType"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/redirectToURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentActionType\/unknown"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentActionType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType~1unknown\/title","value":"STPPaymentIntentActionTypeUnknown"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType~1unknown\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentActionTypeUnknown"}],"op":"replace"},{"value":"STPPaymentIntentActionType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentActionType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentActionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType~1redirectToURL\/title","value":"STPPaymentIntentActionTypeRedirectToURL","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentActionType~1redirectToURL\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentActionTypeRedirectToURL"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}