{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType"},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/AUBECSDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/EPS","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/FPX","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/OXXO","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/SEPADebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/UPI","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/USBankAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/affirm","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/afterpayClearpay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/alipay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/alma","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/amazonPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bacsDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bancontact","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/billie","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/blik","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/boleto","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/cardPresent","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/cashApp","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/crypto","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/grabPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/iDEAL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/klarna","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/konbini","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/link","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/mobilePay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/multibanco","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/netBanking","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPal","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/paynow","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/promptPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/przelewy24","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/revolutPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/satispay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/sunbit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/swish","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/twint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/weChatPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/wero","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/zip"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s12CaseIterableP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodType"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodtype"]}],"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@StripePayments@E@STPPaymentMethodType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodType"}],"title":"STPPaymentMethodType","modules":[{"name":"StripePayments"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"role":"symbol","symbolKind":"enum"},"abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/bancontact":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bancontact","role":"symbol","title":"STPPaymentMethodType.bancontact","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bancontact","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A Bancontact payment method."}],"navigatorTitle":[{"text":"STPPaymentMethodTypeBancontact","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/bancontact"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/klarna":{"type":"topic","role":"symbol","title":"STPPaymentMethodType.klarna","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/klarna","navigatorTitle":[{"text":"STPPaymentMethodTypeKlarna","kind":"identifier"}],"abstract":[{"text":"A Klarna payment method.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"klarna","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/klarna"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/sunbit":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/sunbit","role":"symbol","title":"STPPaymentMethodType.sunbit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sunbit","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A Sunbit payment method"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeSunbit","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/sunbit"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/netBanking":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/netBanking","role":"symbol","title":"STPPaymentMethodType.netBanking","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"netBanking","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A NetBanking payment method."}],"navigatorTitle":[{"text":"STPPaymentMethodTypeNetBanking","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/netbanking"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/mobilePay":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/mobilepay","abstract":[{"type":"text","text":"A MobilePay payment method"}],"title":"STPPaymentMethodType.mobilePay","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/mobilePay","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mobilePay","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodTypeMobilePay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/card":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/card","navigatorTitle":[{"text":"STPPaymentMethodTypeCard","kind":"identifier"}],"abstract":[{"text":"A card payment method.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/card","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}],"title":"STPPaymentMethodType.card"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/promptPay":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/promptpay","title":"STPPaymentMethodType.promptPay","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/promptPay","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"promptPay","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypePromptPay","kind":"identifier"}],"abstract":[{"type":"text","text":"A PromptPay payment method"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/USBankAccount":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"USBankAccount"}],"title":"STPPaymentMethodType.USBankAccount","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeUSBankAccount"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/usbankaccount","type":"topic","abstract":[{"type":"text","text":"A US Bank Account payment method (ACH)"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/USBankAccount","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/revolutPay":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeRevolutPay"}],"title":"STPPaymentMethodType.revolutPay","type":"topic","abstract":[{"text":"A RevolutPay payment method","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"revolutPay"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/revolutpay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/revolutPay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/blik":{"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeBLIK","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/blik","abstract":[{"type":"text","text":"A BLIK payment method"}],"title":"STPPaymentMethodType.blik","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/blik","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blik","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/grabPay":{"title":"STPPaymentMethodType.grabPay","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grabPay","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeGrabPay","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/grabPay","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/grabpay","abstract":[{"type":"text","text":"A GrabPay payment method."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/konbini":{"title":"STPPaymentMethodType.konbini","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"konbini","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeKonbini","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/konbini","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/konbini","abstract":[{"type":"text","text":"A Konbini payment method"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/init(rawValue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/init(rawvalue:)","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s12CaseIterableP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/satispay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/satispay","type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeSatispay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/satispay","kind":"symbol","title":"STPPaymentMethodType.satispay","abstract":[{"type":"text","text":"A Satispay payment method"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"satispay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/multibanco":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/multibanco","role":"symbol","kind":"symbol","title":"STPPaymentMethodType.multibanco","navigatorTitle":[{"text":"STPPaymentMethodTypeMultibanco","kind":"identifier"}],"type":"topic","abstract":[{"text":"A Multibanco payment method","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multibanco","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/multibanco"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/Equatable-Implementations":{"kind":"article","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/equatable-implementations","type":"topic","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/Equatable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/billie":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/billie","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeBillie","kind":"identifier"}],"title":"STPPaymentMethodType.billie","abstract":[{"type":"text","text":"A Billie payment method"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/billie","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"billie","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/payPal":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPal","title":"STPPaymentMethodType.payPal","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payPal","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/paypal","navigatorTitle":[{"text":"STPPaymentMethodTypePayPal","kind":"identifier"}],"abstract":[{"type":"text","text":"A PayPal payment method. :nodoc:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/przelewy24":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"przelewy24","kind":"identifier"}],"type":"topic","title":"STPPaymentMethodType.przelewy24","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/przelewy24","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/przelewy24","navigatorTitle":[{"text":"STPPaymentMethodTypePrzelewy24","kind":"identifier"}],"abstract":[{"type":"text","text":"A Przelewy24 Debit payment method."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/alipay":{"role":"symbol","abstract":[{"type":"text","text":"An Alipay payment method."}],"title":"STPPaymentMethodType.alipay","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/alipay","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/alipay","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipay","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeAlipay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/paynow":{"title":"STPPaymentMethodType.paynow","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypePaynow","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paynow","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/paynow","abstract":[{"type":"text","text":"A PayNow payment method"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/paynow","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/link":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"link","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPPaymentMethodTypeLink","kind":"identifier"}],"abstract":[{"type":"text","text":"A Link payment method"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/link","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/link","title":"STPPaymentMethodType.link"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/SEPADebit":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/SEPADebit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SEPADebit","kind":"identifier"}],"title":"STPPaymentMethodType.SEPADebit","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/sepadebit","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A SEPA Debit payment method."}],"navigatorTitle":[{"text":"STPPaymentMethodTypeSEPADebit","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/cashApp":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/cashApp","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cashApp"}],"title":"STPPaymentMethodType.cashApp","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/cashapp","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A CashApp payment method"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeCashApp"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/OXXO":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeOXXO"}],"title":"STPPaymentMethodType.OXXO","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"OXXO"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/oxxo","abstract":[{"type":"text","text":"An OXXO payment method."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/OXXO","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/UPI":{"abstract":[{"type":"text","text":"A UPI payment method."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/upi","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/UPI","type":"topic","title":"STPPaymentMethodType.UPI","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeUPI"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"UPI"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/unknown":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/unknown","role":"symbol","title":"STPPaymentMethodType.unknown","abstract":[{"type":"text","text":"An unknown type."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/unknown","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeUnknown"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/iDEAL":{"abstract":[{"type":"text","text":"An iDEAL payment method."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/ideal","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/iDEAL","type":"topic","title":"STPPaymentMethodType.iDEAL","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeiDEAL"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"iDEAL"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/wero":{"kind":"symbol","title":"STPPaymentMethodType.wero","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/wero","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/wero","abstract":[{"type":"text","text":"A Wero payment method"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"wero"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodTypeWero"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/CustomStringConvertible-Implementations":{"type":"topic","role":"collectionGroup","title":"CustomStringConvertible Implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/customstringconvertible-implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/zip":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/zip","abstract":[{"type":"text","text":"A Zip payment method"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/zip","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zip","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeZip","kind":"identifier"}],"title":"STPPaymentMethodType.zip"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/afterpayClearpay":{"title":"STPPaymentMethodType.afterpayClearpay","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"afterpayClearpay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/afterpayclearpay","navigatorTitle":[{"text":"STPPaymentMethodTypeAfterpayClearpay","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/afterpayClearpay","abstract":[{"text":"An AfterpayClearpay payment method","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/EPS":{"abstract":[{"type":"text","text":"An EPS payment method."}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeEPS","kind":"identifier"}],"title":"STPPaymentMethodType.EPS","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EPS","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/EPS","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/eps","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/payPay":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payPay","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypePayPay","kind":"identifier"}],"abstract":[{"type":"text","text":"A PayPay payment method"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPay","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/paypay","title":"STPPaymentMethodType.payPay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/twint":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/twint","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeTwint","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/twint","abstract":[{"text":"A TWINT payment method","type":"text"}],"title":"STPPaymentMethodType.twint","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"twint","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/crypto":{"type":"topic","abstract":[{"type":"text","text":"A Crypto payment method"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/crypto","title":"STPPaymentMethodType.crypto","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"crypto","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeCrypto","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/crypto","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/weChatPay":{"title":"STPPaymentMethodType.weChatPay","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/wechatpay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/weChatPay","kind":"symbol","abstract":[{"type":"text","text":"A WeChat Pay payment method"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPay","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeWeChatPay","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/RawRepresentable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/rawrepresentable-implementations","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/boleto":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/boleto","title":"STPPaymentMethodType.boleto","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/boleto","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boleto","kind":"identifier"}],"abstract":[{"type":"text","text":"A Boleto payment method."}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeBoleto","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/affirm":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/affirm","title":"STPPaymentMethodType.affirm","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"affirm","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/affirm","navigatorTitle":[{"text":"STPPaymentMethodTypeAffirm","kind":"identifier"}],"abstract":[{"type":"text","text":"An Affirm payment method"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/alma":{"abstract":[{"type":"text","text":"An Alma payment method"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/alma","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alma","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodTypeAlma","kind":"identifier"}],"title":"STPPaymentMethodType.alma","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/alma","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/FPX":{"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FPX","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/FPX","navigatorTitle":[{"text":"STPPaymentMethodTypeFPX","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/fpx","abstract":[{"type":"text","text":"An FPX payment method."}],"kind":"symbol","title":"STPPaymentMethodType.FPX"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/cardPresent":{"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardPresent","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/cardPresent","navigatorTitle":[{"text":"STPPaymentMethodTypeCardPresent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/cardpresent","abstract":[{"type":"text","text":"A card present payment method."}],"kind":"symbol","title":"STPPaymentMethodType.cardPresent"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/swish":{"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swish","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/swish","navigatorTitle":[{"text":"STPPaymentMethodTypeSwish","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/swish","abstract":[{"type":"text","text":"A Swish payment method"}],"kind":"symbol","title":"STPPaymentMethodType.swish"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/STPPaymentMethodTypeShopPay":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/stppaymentmethodtypeshoppay","abstract":[{"type":"text","text":"A ShopPay payment method"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/STPPaymentMethodTypeShopPay","type":"topic","fragments":[{"text":"STPPaymentMethodTypeShopPay","kind":"identifier"}],"title":"STPPaymentMethodTypeShopPay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/bacsDebit":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Bacs Debit payment method."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bacsDebit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bacsDebit","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodTypeBacsDebit","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/bacsdebit","title":"STPPaymentMethodType.bacsDebit"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/AUBECSDebit":{"kind":"symbol","title":"STPPaymentMethodType.AUBECSDebit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AUBECSDebit","kind":"identifier"}],"abstract":[{"type":"text","text":"An AU BECS Debit payment method."}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodtype\/aubecsdebit","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/AUBECSDebit","navigatorTitle":[{"text":"STPPaymentMethodTypeAUBECSDebit","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType":{"url":"\/documentation\/stripepayments\/stppaymentmethodtype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType","abstract":[{"type":"text","text":"The type of the PaymentMethod."}],"role":"symbol","title":"STPPaymentMethodType","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodType","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodType/amazonPay":{"title":"STPPaymentMethodType.amazonPay","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amazonPay","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/amazonPay","navigatorTitle":[{"text":"STPPaymentMethodTypeAmazonPay","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An AmazonPay payment method"}],"url":"\/documentation\/stripepayments\/stppaymentmethodtype\/amazonpay"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentMethodType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/AUBECSDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/EPS","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/FPX","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/OXXO","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/SEPADebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/STPPaymentMethodTypeShopPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/UPI","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/USBankAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/affirm","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/afterpayClearpay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/alipay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/alma","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/amazonPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bacsDebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/bancontact","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/billie","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/blik","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/boleto","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/cardPresent","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/cashApp","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/crypto","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/grabPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/iDEAL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/klarna","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/konbini","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/link","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/mobilePay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/multibanco","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/netBanking","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPal","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/payPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/paynow","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/promptPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/przelewy24","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/revolutPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/satispay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/sunbit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/swish","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/twint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/weChatPay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/wero","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodType\/zip"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPPaymentMethodTypeBancontact","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1bancontact\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeBancontact","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1bancontact\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeKlarna","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1klarna\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeKlarna","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1klarna\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeSunbit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1sunbit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeSunbit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1sunbit\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeNetBanking","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1netBanking\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeNetBanking"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1netBanking\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeMobilePay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1mobilePay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeMobilePay"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1mobilePay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeCard","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1card\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeCard"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1card\/fragments","op":"replace"},{"value":"STPPaymentMethodTypePromptPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1promptPay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypePromptPay"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1promptPay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeUSBankAccount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1USBankAccount\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeUSBankAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1USBankAccount\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeRevolutPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1revolutPay\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeRevolutPay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1revolutPay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeBLIK","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1blik\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeBLIK"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1blik\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeGrabPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1grabPay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeGrabPay"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1grabPay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeKonbini","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1konbini\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeKonbini"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1konbini\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeSatispay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1satispay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeSatispay"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1satispay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeMultibanco","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1multibanco\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeMultibanco","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1multibanco\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeBillie","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1billie\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeBillie"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1billie\/fragments","op":"replace"},{"value":"STPPaymentMethodTypePayPal","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1payPal\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypePayPal"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1payPal\/fragments","op":"replace"},{"value":"STPPaymentMethodTypePrzelewy24","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1przelewy24\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypePrzelewy24"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1przelewy24\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeAlipay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1alipay\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeAlipay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1alipay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypePaynow","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1paynow\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypePaynow","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1paynow\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeLink","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1link\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeLink","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1link\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeSEPADebit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1SEPADebit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeSEPADebit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1SEPADebit\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeCashApp","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1cashApp\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeCashApp","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1cashApp\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeOXXO","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1OXXO\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeOXXO","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1OXXO\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeUPI","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1UPI\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeUPI"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1UPI\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1unknown\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1unknown\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeiDEAL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1iDEAL\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeiDEAL"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1iDEAL\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeWero","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1wero\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeWero","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1wero\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeZip","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1zip\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeZip","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1zip\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeAfterpayClearpay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1afterpayClearpay\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeAfterpayClearpay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1afterpayClearpay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeEPS","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1EPS\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeEPS","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1EPS\/fragments","op":"replace"},{"value":"STPPaymentMethodTypePayPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1payPay\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypePayPay"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1payPay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeTwint","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1twint\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeTwint"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1twint\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeCrypto","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1crypto\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeCrypto","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1crypto\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeWeChatPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1weChatPay\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeWeChatPay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1weChatPay\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeBoleto","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1boleto\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeBoleto","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1boleto\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeAffirm","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1affirm\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeAffirm"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1affirm\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeAlma","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1alma\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeAlma","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1alma\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeFPX","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1FPX\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeFPX","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1FPX\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeCardPresent","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1cardPresent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeCardPresent"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1cardPresent\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeSwish","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1swish\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeSwish","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1swish\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeBacsDebit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1bacsDebit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeBacsDebit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1bacsDebit\/fragments","op":"replace"},{"value":"STPPaymentMethodTypeAUBECSDebit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1AUBECSDebit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodTypeAUBECSDebit"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1AUBECSDebit\/fragments","op":"replace"},{"value":"STPPaymentMethodType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType\/navigatorTitle","op":"replace"},{"value":"STPPaymentMethodTypeAmazonPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1amazonPay\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodTypeAmazonPay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodType~1amazonPay\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}