{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Enumeration","externalID":"c:@M@StripePayments@E@STPPaymentIntentCaptureMethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}],"title":"STPPaymentIntentCaptureMethod","role":"symbol","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentcapturemethod"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentcapturemethod"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/automatic","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/automaticAsync","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/manual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/unknown"],"generated":true},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"type":"aside","name":"See Also","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Docs.Stripe.Com\/Api\/Payment_intents\/Object#Payment_intent_object-Capture_method"}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"abstract":[{"text":"Capture methods for a STPPaymentIntent","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/unknown":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"text":"Unknown capture method","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodUnknown"}],"title":"STPPaymentIntentCaptureMethod.unknown","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/unknown","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/unknown","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/Equatable-Implementations","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/equatable-implementations","kind":"article","title":"Equatable Implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/init(rawValue:)","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/CustomStringConvertible-Implementations":{"type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/customstringconvertible-implementations","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/automatic":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/automatic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodAutomatic"}],"kind":"symbol","abstract":[{"text":"The PaymentIntent will be automatically captured","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/automatic","title":"STPPaymentIntentCaptureMethod.automatic","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/RawRepresentable-Implementations","abstract":[],"type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/rawrepresentable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod":{"url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}],"abstract":[{"text":"Capture methods for a STPPaymentIntent","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}],"title":"STPPaymentIntentCaptureMethod"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/manual":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodManual"}],"url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/manual","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/manual","type":"topic","title":"STPPaymentIntentCaptureMethod.manual","kind":"symbol","abstract":[{"text":"The PaymentIntent must be manually captured once it has the status","type":"text"},{"text":" ","type":"text"},{"code":"STPPaymentIntentStatusRequiresCapture","type":"codeVoice"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}]},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentCaptureMethod/automaticAsync":{"url":"\/documentation\/stripepayments\/stppaymentintentcapturemethod\/automaticasync","role":"symbol","abstract":[{"type":"text","text":"Asynchronously capture funds when the customer authorizes the payment."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automaticAsync"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/automaticAsync","kind":"symbol","title":"STPPaymentIntentCaptureMethod.automaticAsync","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodAutomaticAsync"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentCaptureMethod"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/automatic","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/automaticAsync","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/manual","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentCaptureMethod\/unknown"],"title":"Enumeration Cases","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1unknown\/title","value":"STPPaymentIntentCaptureMethodUnknown"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1unknown\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodUnknown"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1automatic\/title","value":"STPPaymentIntentCaptureMethodAutomatic"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1automatic\/fragments","value":[{"text":"STPPaymentIntentCaptureMethodAutomatic","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/title","value":"STPPaymentIntentCaptureMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethod"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod\/navigatorTitle","value":[{"text":"STPPaymentIntentCaptureMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1manual\/title","value":"STPPaymentIntentCaptureMethodManual"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1manual\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodManual"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1automaticAsync\/title","value":"STPPaymentIntentCaptureMethodAutomaticAsync"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentCaptureMethod~1automaticAsync\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentCaptureMethodAutomaticAsync"}]}]}]}