{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodMultibancoParams"}],"role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibancoParams","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodMultibancoParams"}],"title":"STPPaymentMethodMultibancoParams"},"sections":[],"abstract":[{"text":"An object representing parameters used to create a Multibanco Payment Method","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/additionalAPIParameters"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/rootObjectName()"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodmultibancoparams"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodmultibancoparams"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibancoParams/init":{"url":"\/documentation\/stripepayments\/stppaymentmethodmultibancoparams\/init","abstract":[],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/init","type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibancoParams/rootObjectName()":{"url":"\/documentation\/stripepayments\/stppaymentmethodmultibancoparams\/rootobjectname()","abstract":[],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/rootObjectName()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"rootObjectName()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibancoParams/additionalAPIParameters":{"url":"\/documentation\/stripepayments\/stppaymentmethodmultibancoparams\/additionalapiparameters","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/additionalAPIParameters","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalAPIParameters"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"title":"additionalAPIParameters"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibancoParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodmultibancoparams","abstract":[{"type":"text","text":"An object representing parameters used to create a Multibanco Payment Method"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodMultibancoParams"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodMultibancoParams"}],"title":"STPPaymentMethodMultibancoParams"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibancoParams/propertyNamesToFormFieldNamesMapping()":{"url":"\/documentation\/stripepayments\/stppaymentmethodmultibancoparams\/propertynamestoformfieldnamesmapping()","abstract":[],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/propertyNamesToFormFieldNamesMapping()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"title":"propertyNamesToFormFieldNamesMapping()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"type":"topic","url":"\/documentation\/stripepayments\/stpformencodable","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"title":"STPFormEncodable","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodMultibancoParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/additionalAPIParameters"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/init"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams\/rootObjectName()"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams~1rootObjectName()\/title","op":"replace","value":"rootObjectName"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams~1rootObjectName()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams~1additionalAPIParameters\/title","value":"additionalAPIParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams~1additionalAPIParameters\/fragments","value":[{"text":"additionalAPIParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/title","value":"STPPaymentMethodMultibancoParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/fragments","value":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/navigatorTitle","value":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams~1propertyNamesToFormFieldNamesMapping()\/title","op":"replace","value":"propertyNamesToFormFieldNamesMapping"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams~1propertyNamesToFormFieldNamesMapping()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","value":"STPFormEncodable"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","value":[{"text":"STPFormEncodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPFormEncodable"}]}]}]}