{"sections":[],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/supported"],"anchor":"Instance-Properties"},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/decodedObject(fromAPIResponse:)"],"generated":true}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodThreeDSecureUsage"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"abstract":[{"type":"text","text":"Contains details on how an "},{"type":"codeVoice","code":"STPPaymentMethodCard"},{"text":" maybe be used for 3D Secure authentication.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodThreeDSecureUsage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodThreeDSecureUsage","symbolKind":"class","roleHeading":"Class","title":"STPPaymentMethodThreeDSecureUsage"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","title":"STPAPIResponseDecodable","type":"topic"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodThreeDSecureUsage/decodedObject(fromAPIResponse:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage\/decodedobject(fromapiresponse:)","title":"decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodThreeDSecureUsage/supported":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/supported","url":"\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage\/supported","role":"symbol","title":"supported","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"supported","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"supported","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"YES"},{"text":" if 3D Secure is supported on this card.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodThreeDSecureUsage/allResponseFields":{"abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage\/allresponsefields","kind":"symbol","title":"allResponseFields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/allResponseFields","type":"topic"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodThreeDSecureUsage/description":{"kind":"symbol","role":"symbol","title":"description","url":"\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage\/description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/description","type":"topic","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodThreeDSecureUsage":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodThreeDSecureUsage"}],"type":"topic","abstract":[{"text":"Contains details on how an ","type":"text"},{"code":"STPPaymentMethodCard","type":"codeVoice"},{"text":" maybe be used for 3D Secure authentication.","type":"text"}],"title":"STPPaymentMethodThreeDSecureUsage","url":"\/documentation\/stripepayments\/stppaymentmethodthreedsecureusage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodThreeDSecureUsage"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodThreeDSecureUsage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"STPPaymentMethodThreeDSecureUsage"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/supported"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodThreeDSecureUsage\/decodedObject(fromAPIResponse:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"kind":"relationships","title":"Conforms To"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodThreeDSecureUsage"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1decodedObject(fromAPIResponse:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1supported\/title","op":"replace","value":"supported"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1supported\/fragments","op":"replace","value":[{"kind":"identifier","text":"supported"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1allResponseFields\/title","value":"allResponseFields"},{"value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1allResponseFields\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage~1description\/fragments"},{"value":"STPPaymentMethodThreeDSecureUsage","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/fragments","value":[{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodThreeDSecureUsage\/navigatorTitle","value":[{"text":"STPPaymentMethodThreeDSecureUsage","kind":"identifier"}],"op":"replace"}]}]}