{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stpredirectcontextstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpredirectcontextstate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"STPRedirectContextState","kind":"identifier"}],"title":"STPRedirectContextState","roleHeading":"Enumeration","externalID":"c:@M@StripePayments@E@STPRedirectContextState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPRedirectContextState"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"enum"},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/cancelled","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/completed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/inProgress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/notStarted"],"title":"Enumeration Cases"},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/init(rawValue:)"],"generated":true},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/RawRepresentable-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"abstract":[{"text":"Possible states for the redirect context to be in","type":"text"}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPRedirectContextState"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/CustomStringConvertible-Implementations":{"title":"CustomStringConvertible Implementations","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontextstate\/customstringconvertible-implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/CustomStringConvertible-Implementations"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/cancelled":{"title":"STPRedirectContextState.cancelled","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextStateCancelled"}],"type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontextstate\/cancelled","abstract":[{"type":"text","text":"Redirect has been cancelled programmatically before completing."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelled"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/cancelled"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/notStarted":{"abstract":[{"text":"Initialized, but redirect not started.","type":"text"}],"url":"\/documentation\/stripepayments\/stpredirectcontextstate\/notstarted","role":"symbol","title":"STPRedirectContextState.notStarted","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notStarted","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextStateNotStarted"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/notStarted"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/inProgress":{"title":"STPRedirectContextState.inProgress","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextStateInProgress"}],"type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontextstate\/inprogress","abstract":[{"type":"text","text":"Redirect is in progress."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"inProgress","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/inProgress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stpredirectcontextstate\/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/init(rawValue:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontextstate\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/Equatable-Implementations"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/stripepayments\/stpredirectcontextstate\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/RawRepresentable-Implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState","abstract":[{"type":"text","text":"Possible states for the redirect context to be in"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRedirectContextState","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextState"}],"type":"topic","title":"STPRedirectContextState","kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontextstate"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextState/completed":{"title":"STPRedirectContextState.completed","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextStateCompleted"}],"type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontextstate\/completed","abstract":[{"type":"text","text":"Redirect has completed."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/completed"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPRedirectContextState"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"STPRedirectContextState","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPRedirectContextState","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/cancelled","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/completed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/inProgress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextState\/notStarted"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRedirectContextState","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"STPRedirectContextStateCancelled","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1cancelled\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPRedirectContextStateCancelled"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1cancelled\/fragments"},{"op":"replace","value":"STPRedirectContextStateNotStarted","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1notStarted\/title"},{"value":[{"text":"STPRedirectContextStateNotStarted","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1notStarted\/fragments","op":"replace"},{"value":"STPRedirectContextStateInProgress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1inProgress\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1inProgress\/fragments","value":[{"kind":"identifier","text":"STPRedirectContextStateInProgress"}]},{"value":"STPRedirectContextState","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/title"},{"value":[{"kind":"identifier","text":"STPRedirectContextState"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPRedirectContextState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1completed\/title","value":"STPRedirectContextStateCompleted"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextState~1completed\/fragments","value":[{"text":"STPRedirectContextStateCompleted","kind":"identifier"}]}]}]}