{"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@StripePayments@E@STPRedirectContextError","title":"STPRedirectContextError","navigatorTitle":[{"text":"STPRedirectContextError","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPRedirectContextError","kind":"identifier"}],"symbolKind":"enum"},"abstract":[{"text":"Error codes specific to ","type":"text"},{"type":"codeVoice","code":"STPRedirectContext"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError"},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/appRedirectError"],"title":"Enumeration Cases"},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPRedirectContextError"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontexterror"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontexterror"]}],"references":{"doc://com.stripe.stripe-payments/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","url":"\/documentation\/stripepayments\/stpredirectcontexterror\/equatable-implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/Equatable-Implementations","kind":"article"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/CustomStringConvertible-Implementations":{"type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontexterror\/customstringconvertible-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/CustomStringConvertible-Implementations","abstract":[],"title":"CustomStringConvertible Implementations","role":"collectionGroup","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError":{"url":"\/documentation\/stripepayments\/stpredirectcontexterror","abstract":[{"text":"Error codes specific to ","type":"text"},{"code":"STPRedirectContext","type":"codeVoice"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContextError"}],"title":"STPRedirectContextError","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError","type":"topic","navigatorTitle":[{"text":"STPRedirectContextError","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/init(rawValue:)","role":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontexterror\/init(rawvalue:)","abstract":[]},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/appRedirectError":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"STPRedirectContextAppRedirectError","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpredirectcontexterror\/appredirecterror","title":"STPRedirectContextError.appRedirectError","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/appRedirectError","abstract":[{"type":"codeVoice","code":"STPRedirectContext"},{"text":" failed to redirect to the app to complete the payment.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This could be because the app is not installed on the user’s device."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"appRedirectError","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContextError/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/stripepayments\/stpredirectcontexterror\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/RawRepresentable-Implementations","type":"topic","abstract":[],"kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPRedirectContextError"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPRedirectContextError","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPRedirectContextError","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContextError\/appRedirectError"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPRedirectContextError"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/title","value":"STPRedirectContextError","op":"replace"},{"op":"replace","value":[{"text":"STPRedirectContextError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError\/navigatorTitle","value":[{"kind":"identifier","text":"STPRedirectContextError"}]},{"value":"STPRedirectContextAppRedirectError","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError~1appRedirectError\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContextError~1appRedirectError\/fragments","value":[{"kind":"identifier","text":"STPRedirectContextAppRedirectError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}