{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(paymentIntent:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(source:completion:)"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/state"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/cancel()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/presentationController(forPresented:presenting:source:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startRedirectFlow(from:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariAppRedirectFlow()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariViewControllerRedirectFlow(from:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/STPRedirectContextErrorDomain"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"This class dismisses any presented view controller upon deallocation.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"See https:\/\/stripe.com\/docs\/sources\/best-practices"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/objc(pl)SFSafariViewControllerDelegate","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/objc(pl)UIViewControllerTransitioningDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext"]},{"paths":["\/documentation\/stripepayments\/stpredirectcontext"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"This is a helper class for handling redirects associated with STPSource and"},{"type":"text","text":" "},{"type":"text","text":"STPPaymentIntents."},{"text":" ","type":"text"},{"type":"text","text":"Init and retain an instance with the Source or PaymentIntent you want to handle,"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"type":"text","text":"when the redirect completes."},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"type":"text","text":" "},{"text":"during this process, as all actions take place in either the Safari app","type":"text"},{"text":" ","type":"text"},{"text":"or the sandboxed SFSafariViewController class. The context attempts to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"detect when the user has completed the necessary redirect action by listening"},{"type":"text","text":" "},{"text":"for both app foregrounds and url callbacks received in the app delegate.","type":"text"},{"type":"text","text":" "},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"type":"text","text":" "},{"text":"have not actually completed the necessary actions to authorize the charge.","type":"text"},{"type":"text","text":" "},{"text":"You should not use either this class, nor ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"type":"text","text":", as a way"},{"type":"text","text":" "},{"type":"text","text":"to determine when you should charge the Source or to determine if the redirect"},{"text":" ","type":"text"},{"text":"was successful. Use Stripe webhooks on your backend server to listen for Source","type":"text"},{"type":"text","text":" "},{"type":"text","text":"state changes and to make the charge."}],"metadata":{"roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContext"}],"symbolKind":"class","modules":[{"name":"StripePayments"}],"title":"STPRedirectContext","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRedirectContext","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/startSafariViewControllerRedirectFlow(from:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startSafariViewControllerRedirectFlow"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"startSafariViewControllerRedirectFlow(from:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariViewControllerRedirectFlow(from:)","url":"\/documentation\/stripepayments\/stpredirectcontext\/startsafariviewcontrollerredirectflow(from:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"startSafariViewControllerRedirectFlowFromViewController:"}],"abstract":[{"text":"Starts a redirect flow by presenting an SFSafariViewController in your app","type":"text"},{"type":"text","text":" "},{"type":"text","text":"from the passed in view controller."},{"type":"text","text":" "},{"type":"text","text":"You must ensure that your app delegate listens for  the "},{"code":"returnURL","type":"codeVoice"},{"text":" that you","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"set on the Stripe object, and forwards it to the Stripe SDK so that the"},{"text":" ","type":"text"},{"text":"context can be notified when the redirect is completed and dismiss the","type":"text"},{"type":"text","text":" "},{"text":"view controller. See ","type":"text"},{"type":"codeVoice","code":"StripeAPI.handleStripeURLCallback(with url:)]"},{"type":"text","text":" "},{"text":"The context will listen for both received URLs and app open notifications","type":"text"},{"text":" ","type":"text"},{"text":"and fire its completion block when either the URL is received, or the next","type":"text"},{"text":" ","type":"text"},{"text":"time the app is foregrounded.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/STPRedirectContextErrorDomain":{"kind":"symbol","title":"STPRedirectContextErrorDomain","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContextErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","abstract":[{"text":"The domain for NSErrors specific to ","type":"text"},{"code":"STPRedirectContext","type":"codeVoice"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/STPRedirectContextErrorDomain","url":"\/documentation\/stripepayments\/stpredirectcontext\/stpredirectcontexterrordomain","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextErrorDomain"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/SFSafariViewControllerDelegate-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations","url":"\/documentation\/stripepayments\/stpredirectcontext\/sfsafariviewcontrollerdelegate-implementations","title":"SFSafariViewControllerDelegate Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/startSafariAppRedirectFlow()":{"abstract":[{"text":"Starts a redirect flow by calling ","type":"text"},{"code":"openURL","type":"codeVoice"},{"text":" to bounce the user out to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the Safari app."},{"type":"text","text":" "},{"text":"The context will listen for app open notifications and fire its completion","type":"text"},{"text":" ","type":"text"},{"text":"block the next time the user re-opens the app (either manually or via url)","type":"text"}],"url":"\/documentation\/stripepayments\/stpredirectcontext\/startsafariappredirectflow()","title":"startSafariAppRedirectFlow()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariAppRedirectFlow()","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSafariAppRedirectFlow"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"startSafariAppRedirectFlow"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/init(paymentIntent:completion:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"paymentIntent"},{"text":": ","kind":"text"},{"text":"STPPaymentIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntent"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPRedirectContextPaymentIntentCompletionBlock","preciseIdentifier":"s:14StripePayments46STPRedirectContextPaymentIntentCompletionBlocka"},{"kind":"text","text":")"}],"title":"init(paymentIntent:completion:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(paymentIntent:completion:)","url":"\/documentation\/stripepayments\/stpredirectcontext\/init(paymentintent:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPaymentIntent:completion:"}],"abstract":[{"type":"text","text":"Initializer for context from an "},{"type":"codeVoice","code":"STPPaymentIntent"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This should be used when the "},{"type":"codeVoice","code":"status"},{"type":"text","text":" is "},{"code":"STPPaymentIntentStatusRequiresAction","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the next action involves a redirect, this init method will return a non-nil object."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)UIViewControllerTransitioningDelegate":{"title":"UIViewControllerTransitioningDelegate","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/objc(pl)SFSafariViewControllerDelegate":{"title":"SFSafariViewControllerDelegate","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)SFSafariViewControllerDelegate"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/init(source:completion:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","text":"STPSource"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14StripePayments39STPRedirectContextSourceCompletionBlocka","text":"STPRedirectContextSourceCompletionBlock"},{"kind":"text","text":")"}],"title":"init(source:completion:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(source:completion:)","url":"\/documentation\/stripepayments\/stpredirectcontext\/init(source:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSource:completion:"}],"abstract":[{"text":"Initializer for context from an ","type":"text"},{"code":"STPSource","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/presentationController(forPresented:presenting:source:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentationController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresented"},{"text":": ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"presenting"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?, "},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":") -> "},{"text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"presentationController(forPresented:presenting:source:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/presentationController(forPresented:presenting:source:)","navigatorTitle":[{"text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext\/presentationcontroller(forpresented:presenting:source:)","abstract":[{"type":"text","text":":nodoc:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/handleURLCallback:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handleURLCallback:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/handleURLCallback:","url":"\/documentation\/stripepayments\/stpredirectcontext\/handleurlcallback:","title":"handleURLCallback:","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"handleURLCallback:"}],"abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/startRedirectFlow(from:)":{"url":"\/documentation\/stripepayments\/stpredirectcontext\/startredirectflow(from:)","kind":"symbol","abstract":[{"text":"Starts a redirect flow.","type":"text"},{"text":" ","type":"text"},{"text":"You must ensure that your app delegate listens for  the ","type":"text"},{"type":"codeVoice","code":"returnURL"},{"type":"text","text":" that you"},{"text":" ","type":"text"},{"type":"text","text":"set on the Stripe object, and forwards it to the Stripe SDK so that the"},{"type":"text","text":" "},{"type":"text","text":"context can be notified when the redirect is completed and dismiss the"},{"type":"text","text":" "},{"text":"view controller. See ","type":"text"},{"code":"StripeAPI.handleURLCallback(with url:)","type":"codeVoice"},{"type":"text","text":" "},{"text":"The context will listen for both received URLs and app open notifications","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and fire its completion block when either the URL is received, or the next"},{"text":" ","type":"text"},{"type":"text","text":"time the app is foregrounded."},{"text":" ","type":"text"},{"text":"The context will initiate the flow by presenting a SFSafariViewController","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"instance from the passsed in view controller. If you want more manual control"},{"text":" ","type":"text"},{"text":"over the redirect method, you can use ","type":"text"},{"code":"startSafariViewControllerRedirectFlowFromViewController","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"startSafariAppRedirectFlow"},{"type":"text","text":" "},{"type":"text","text":"If the redirect supports a native app, and that app is is installed on the user’s"},{"type":"text","text":" "},{"type":"text","text":"device, this call will do a direct app-to-app redirect instead of showing"},{"text":" ","type":"text"},{"type":"text","text":"a web url."}],"title":"startRedirectFlow(from:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startRedirectFlow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"startRedirectFlowFromViewController:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startRedirectFlow(from:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/cancel()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"title":"cancel()","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/cancel()","url":"\/documentation\/stripepayments\/stpredirectcontext\/cancel()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancel"}],"abstract":[{"text":"Dismisses any presented views and stops listening for any","type":"text"},{"type":"text","text":" "},{"text":"app opens or callbacks. The completion block will not be fired.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"kind":"symbol","title":"STPRedirectContext","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRedirectContext","kind":"identifier"}],"type":"topic","abstract":[{"text":"This is a helper class for handling redirects associated with STPSource and","type":"text"},{"text":" ","type":"text"},{"text":"STPPaymentIntents.","type":"text"},{"text":" ","type":"text"},{"text":"Init and retain an instance with the Source or PaymentIntent you want to handle,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"text":" ","type":"text"},{"text":"when the redirect completes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"type":"text","text":" "},{"type":"text","text":"during this process, as all actions take place in either the Safari app"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"type":"text","text":" "},{"text":"detect when the user has completed the necessary redirect action by listening","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"type":"text","text":" "},{"type":"text","text":"However, it is possible the when the redirect is “completed”, the user may"},{"type":"text","text":" "},{"text":"have not actually completed the necessary actions to authorize the charge.","type":"text"},{"text":" ","type":"text"},{"text":"You should not use either this class, nor ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"text":", as a way","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to determine when you should charge the Source or to determine if the redirect"},{"text":" ","type":"text"},{"type":"text","text":"was successful. Use Stripe webhooks on your backend server to listen for Source"},{"type":"text","text":" "},{"type":"text","text":"state changes and to make the charge."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","url":"\/documentation\/stripepayments\/stpredirectcontext","role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/state":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPRedirectContextState","text":"STPRedirectContextState"}],"title":"state","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/state","url":"\/documentation\/stripepayments\/stpredirectcontext\/state","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"state"}],"abstract":[{"text":"The current state of the context.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/@M@StripeCore@objc(pl)STPURLCallbackListener":{"identifier":"doc:\/\/com.stripe.stripe-payments\/@M@StripeCore@objc(pl)STPURLCallbackListener","title":"STPURLCallbackListener","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPRedirectContext","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"STPRedirectContext","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"STPRedirectContext"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/state"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/cancel()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/handleURLCallback:","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(paymentIntent:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/init(source:completion:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/presentationController(forPresented:presenting:source:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startRedirectFlow(from:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariAppRedirectFlow()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/startSafariViewControllerRedirectFlow(from:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/STPRedirectContextErrorDomain"],"title":"Type Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)SFSafariViewControllerDelegate","doc:\/\/com.stripe.stripe-payments\/@M@StripeCore@objc(pl)STPURLCallbackListener","doc:\/\/com.stripe.stripe-payments\/objc(pl)UIViewControllerTransitioningDelegate"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPRedirectContext"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startSafariViewControllerRedirectFlow(from:)\/title","value":"startSafariViewControllerRedirectFlowFromViewController:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"startSafariViewControllerRedirectFlowFromViewController:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startSafariViewControllerRedirectFlow(from:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1STPRedirectContextErrorDomain\/title","value":"STPRedirectContextErrorDomain"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1STPRedirectContextErrorDomain\/fragments","value":[{"kind":"identifier","text":"STPRedirectContextErrorDomain"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startSafariAppRedirectFlow()\/title","value":"startSafariAppRedirectFlow","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startSafariAppRedirectFlow()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startSafariAppRedirectFlow"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1init(paymentIntent:completion:)\/title","value":"initWithPaymentIntent:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPaymentIntent:completion:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1init(paymentIntent:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1init(source:completion:)\/title","value":"initWithSource:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSource:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1init(source:completion:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1presentationController(forPresented:presenting:source:)\/title","value":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"presentationControllerForPresentedViewController:presentingViewController:sourceViewController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1presentationController(forPresented:presenting:source:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startRedirectFlow(from:)\/title","value":"startRedirectFlowFromViewController:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1startRedirectFlow(from:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"startRedirectFlowFromViewController:","kind":"identifier"}]},{"value":"cancel","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1cancel()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"cancel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1cancel()\/fragments"},{"value":"STPRedirectContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"text":"STPRedirectContext","kind":"identifier"}],"op":"replace"},{"value":"state","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1state\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1state\/fragments","value":[{"kind":"identifier","text":"state"}],"op":"replace"}]}]}
