{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSessionCompletionBlock","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRadarSessionCompletionBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"text":"STPRadarSession","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarSession"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The RadarSession object.","type":"text"}],"type":"paragraph"}],"name":"radarSession"},{"content":[{"inlineContent":[{"text":"The error that occured, if any.","type":"text"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"}],"metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRadarSessionCompletionBlock","kind":"identifier"}],"role":"symbol","symbolKind":"typealias","roleHeading":"Type Alias","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPRadarSessionCompletionBlock"}],"externalID":"s:14StripePayments30STPRadarSessionCompletionBlocka","title":"STPRadarSessionCompletionBlock"},"abstract":[{"type":"text","text":"A callback to be run with an STPRadarSession"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpradarsessioncompletionblock"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarSession":{"url":"\/documentation\/stripepayments\/stpradarsession","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSession","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A "},{"type":"reference","identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session","isActive":true},{"type":"text","text":"."}],"navigatorTitle":[{"text":"STPRadarSession","kind":"identifier"}],"title":"STPRadarSession","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRadarSession","kind":"identifier"}]},"https://stripe.com/docs/radar/radar-session":{"title":"Radar Session","type":"link","url":"https:\/\/stripe.com\/docs\/radar\/radar-session","titleInlineContent":[{"type":"text","text":"Radar Session"}],"identifier":"https:\/\/stripe.com\/docs\/radar\/radar-session"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarSessionCompletionBlock":{"url":"\/documentation\/stripepayments\/stpradarsessioncompletionblock","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarSessionCompletionBlock","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A callback to be run with an STPRadarSession"}],"navigatorTitle":[{"text":"STPRadarSessionCompletionBlock","kind":"identifier"}],"title":"STPRadarSessionCompletionBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPRadarSessionCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPRadarSession","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/title"},{"value":[{"text":"STPRadarSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/fragments"},{"value":[{"text":"STPRadarSession","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRadarSession\/navigatorTitle"}]}]}