{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"abstract":[{"text":"Types for a Source","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcetype"]},{"paths":["\/documentation\/stripepayments\/stpsourcetype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"},"metadata":{"role":"symbol","roleHeading":"Enumeration","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceType","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceType","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPSourceType","title":"STPSourceType","symbolKind":"enum"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceType"}]}]},{"content":[{"type":"heading","level":2,"anchor":"overview","text":"Overview"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Sources","type":"text"}]}],"type":"aside","name":"See Also","style":"note"}],"kind":"content"}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/EPS","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/P24","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/SEPADebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/alipay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/bancontact","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/giropay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/iDEAL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/klarna","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/multibanco","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/sofort","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/threeDSecure","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/weChatPay"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/RawRepresentable-Implementations"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourcetype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceType"}],"title":"STPSourceType","abstract":[{"type":"text","text":"Types for a Source"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/giropay":{"abstract":[{"type":"text","text":"A Giropay source. - seealso: https:\/\/stripe.com\/docs\/sources\/giropay"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"giropay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcetype\/giropay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/giropay","navigatorTitle":[{"text":"STPSourceTypeGiropay","kind":"identifier"}],"type":"topic","role":"symbol","title":"STPSourceType.giropay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/klarna":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/klarna","title":"STPSourceType.klarna","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"klarna"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/klarna","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A Klarna source. - seealso: https:\/\/stripe.com\/docs\/sources\/klarna"}],"navigatorTitle":[{"text":"STPSourceTypeKlarna","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/weChatPay":{"abstract":[{"type":"text","text":"A WeChat Pay source. - seealso: https:\/\/stripe.com\/docs\/sources\/wechat-pay"}],"type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcetype\/wechatpay","navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeWeChatPay"}],"title":"STPSourceType.weChatPay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/weChatPay","role":"symbol"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","kind":"article","url":"\/documentation\/stripepayments\/stpsourcetype\/customstringconvertible-implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/multibanco":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/multibanco","role":"symbol","title":"STPSourceType.multibanco","abstract":[{"text":"A Multibanco source. - seealso: https:\/\/stripe.com\/docs\/sources\/multibanco","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"multibanco","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/multibanco","type":"topic","navigatorTitle":[{"text":"STPSourceTypeMultibanco","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/stripepayments\/stpsourcetype\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/P24":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/P24","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"P24","kind":"identifier"}],"title":"STPSourceType.P24","navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeP24"}],"abstract":[{"type":"text","text":"A P24 source. - seealso: https:\/\/stripe.com\/docs\/sources\/p24"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/p24"},"doc://com.stripe.stripe-payments/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/sofort":{"url":"\/documentation\/stripepayments\/stpsourcetype\/sofort","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sofort"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/sofort","title":"STPSourceType.sofort","kind":"symbol","navigatorTitle":[{"text":"STPSourceTypeSofort","kind":"identifier"}],"abstract":[{"text":"A Sofort source. - seealso: https:\/\/stripe.com\/docs\/sources\/sofort","type":"text"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/alipay":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipay","kind":"identifier"}],"abstract":[{"text":"An Alipay source. - seealso: https:\/\/stripe.com\/docs\/sources\/alipay","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/alipay","title":"STPSourceType.alipay","url":"\/documentation\/stripepayments\/stpsourcetype\/alipay","navigatorTitle":[{"text":"STPSourceTypeAlipay","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/bancontact":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bancontact"}],"navigatorTitle":[{"text":"STPSourceTypeBancontact","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourcetype\/bancontact","title":"STPSourceType.bancontact","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/bancontact","abstract":[{"type":"text","text":"A Bancontact source. - seealso: https:\/\/stripe.com\/docs\/sources\/bancontact"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/init(rawValue:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/init(rawValue:)","abstract":[],"type":"topic","title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/SEPADebit":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"SEPADebit","kind":"identifier"}],"role":"symbol","title":"STPSourceType.SEPADebit","navigatorTitle":[{"text":"STPSourceTypeSEPADebit","kind":"identifier"}],"abstract":[{"type":"text","text":"A SEPA Direct Debit source. - seealso: https:\/\/stripe.com\/docs\/sources\/sepa-debit"}],"url":"\/documentation\/stripepayments\/stpsourcetype\/sepadebit","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/SEPADebit"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/unknown":{"abstract":[{"type":"text","text":"An unknown type of source."}],"navigatorTitle":[{"text":"STPSourceTypeUnknown","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/unknown","kind":"symbol","title":"STPSourceType.unknown","url":"\/documentation\/stripepayments\/stpsourcetype\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/threeDSecure":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threeDSecure"}],"title":"STPSourceType.threeDSecure","navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeThreeDSecure"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/threeDSecure","role":"symbol","kind":"symbol","abstract":[{"text":"A 3DS card source. - seealso: https:\/\/stripe.com\/docs\/sources\/three-d-secure","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourcetype\/threedsecure"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/iDEAL":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/ideal","abstract":[{"text":"An iDEAL source. - seealso: https:\/\/stripe.com\/docs\/sources\/ideal","type":"text"}],"title":"STPSourceType.iDEAL","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iDEAL","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/iDEAL","navigatorTitle":[{"text":"STPSourceTypeiDEAL","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/EPS":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/EPS","abstract":[{"text":"An EPS source. - seealso: https:\/\/stripe.com\/docs\/sources\/eps","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourcetype\/eps","title":"STPSourceType.EPS","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EPS"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeEPS"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/Equatable-Implementations","kind":"article","abstract":[],"type":"topic","title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpsourcetype\/equatable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/card":{"navigatorTitle":[{"text":"STPSourceTypeCard","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/card","type":"topic","abstract":[{"text":"A card source. - seealso: https:\/\/stripe.com\/docs\/sources\/cards","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/card","kind":"symbol","title":"STPSourceType.card","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceType"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceType"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPSourceType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/EPS","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/P24","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/SEPADebit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/alipay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/bancontact","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/giropay","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/iDEAL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/klarna","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/multibanco","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/sofort","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/threeDSecure","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/unknown","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/weChatPay"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceType","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceType"}]},{"value":[{"kind":"identifier","text":"STPSourceType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle","op":"replace"},{"value":"STPSourceTypeGiropay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1giropay\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1giropay\/fragments","value":[{"kind":"identifier","text":"STPSourceTypeGiropay"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1klarna\/title","value":"STPSourceTypeKlarna"},{"value":[{"kind":"identifier","text":"STPSourceTypeKlarna"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1klarna\/fragments","op":"replace"},{"op":"replace","value":"STPSourceTypeWeChatPay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1weChatPay\/title"},{"value":[{"text":"STPSourceTypeWeChatPay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1weChatPay\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1multibanco\/title","value":"STPSourceTypeMultibanco","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1multibanco\/fragments","value":[{"kind":"identifier","text":"STPSourceTypeMultibanco"}]},{"value":"STPSourceTypeP24","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1P24\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1P24\/fragments","value":[{"kind":"identifier","text":"STPSourceTypeP24"}]},{"value":"STPSourceTypeSofort","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1sofort\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1sofort\/fragments","value":[{"kind":"identifier","text":"STPSourceTypeSofort"}],"op":"replace"},{"value":"STPSourceTypeAlipay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1alipay\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1alipay\/fragments","value":[{"text":"STPSourceTypeAlipay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1bancontact\/title","op":"replace","value":"STPSourceTypeBancontact"},{"value":[{"kind":"identifier","text":"STPSourceTypeBancontact"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1bancontact\/fragments","op":"replace"},{"value":"STPSourceTypeSEPADebit","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1SEPADebit\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1SEPADebit\/fragments","op":"replace","value":[{"text":"STPSourceTypeSEPADebit","kind":"identifier"}]},{"value":"STPSourceTypeUnknown","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1unknown\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceTypeUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1unknown\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1threeDSecure\/title","op":"replace","value":"STPSourceTypeThreeDSecure"},{"value":[{"kind":"identifier","text":"STPSourceTypeThreeDSecure"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1threeDSecure\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1iDEAL\/title","op":"replace","value":"STPSourceTypeiDEAL"},{"value":[{"text":"STPSourceTypeiDEAL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1iDEAL\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1EPS\/title","value":"STPSourceTypeEPS"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1EPS\/fragments","value":[{"kind":"identifier","text":"STPSourceTypeEPS"}]},{"value":"STPSourceTypeCard","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1card\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceTypeCard"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1card\/fragments"}]}]}