{"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/canceled","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/processing","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresConfirmation","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresPaymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/succeeded","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/unknown"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentStatus","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentstatus"]},{"paths":["\/documentation\/stripepayments\/stpsetupintentstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSetupIntentStatus","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPSetupIntentStatus","modules":[{"name":"StripePayments"}],"title":"STPSetupIntentStatus","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"symbolKind":"enum","roleHeading":"Enumeration","role":"symbol"},"abstract":[{"type":"text","text":"Status types for an STPSetupIntent"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/requiresConfirmation":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresConfirmation","abstract":[{"type":"text","text":"This SetupIntent needs to be confirmed"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresConfirmation"}],"title":"STPSetupIntentStatus.requiresConfirmation","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/requiresconfirmation","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresConfirmation"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stpsetupintentstatus\/customstringconvertible-implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"CustomStringConvertible Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/CustomStringConvertible-Implementations"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stpsetupintentstatus\/equatable-implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/Equatable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/requiresPaymentMethod":{"abstract":[{"type":"text","text":"This SetupIntent requires a PaymentMethod"}],"title":"STPSetupIntentStatus.requiresPaymentMethod","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/requirespaymentmethod","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requiresPaymentMethod"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresPaymentMethod"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresPaymentMethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/processing":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusProcessing"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/processing","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processing","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentstatus\/processing","title":"STPSetupIntentStatus.processing","abstract":[{"text":"Stripe is processing this SetupIntent","type":"text"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/succeeded":{"url":"\/documentation\/stripepayments\/stpsetupintentstatus\/succeeded","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"succeeded"}],"navigatorTitle":[{"text":"STPSetupIntentStatusSucceeded","kind":"identifier"}],"abstract":[{"type":"text","text":"The SetupIntent has succeeded"}],"title":"STPSetupIntentStatus.succeeded","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/succeeded"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus":{"kind":"symbol","abstract":[{"text":"Status types for an STPSetupIntent","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatus"}],"role":"symbol","title":"STPSetupIntentStatus","url":"\/documentation\/stripepayments\/stpsetupintentstatus","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/unknown":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/unknown","abstract":[{"type":"text","text":"Unknown status"}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"title":"STPSetupIntentStatus.unknown","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/unknown","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusUnknown"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/canceled":{"navigatorTitle":[{"text":"STPSetupIntentStatusCanceled","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"canceled"}],"url":"\/documentation\/stripepayments\/stpsetupintentstatus\/canceled","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/canceled","type":"topic","title":"STPSetupIntentStatus.canceled","abstract":[{"type":"text","text":"This SetupIntent was canceled and cannot be changed."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpsetupintentstatus\/rawrepresentable-implementations","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stpsetupintentstatus\/init(rawvalue:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/init(rawValue:)"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentStatus/requiresAction":{"url":"\/documentation\/stripepayments\/stpsetupintentstatus\/requiresaction","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"requiresAction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresAction"}],"abstract":[{"text":"The selected PaymentMethod requires additional authentication steps.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Additional actions found via the "},{"code":"nextAction","type":"codeVoice"},{"text":" property of ","type":"text"},{"type":"codeVoice","code":"STPSetupIntent"}],"title":"STPSetupIntentStatus.requiresAction","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresAction"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPSetupIntentStatus"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPSetupIntentStatus","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/canceled","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/processing","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresConfirmation","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/requiresPaymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/succeeded","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentStatus\/unknown"],"generated":true,"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSetupIntentStatus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresConfirmation\/title","value":"STPSetupIntentStatusRequiresConfirmation","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresConfirmation\/fragments","value":[{"text":"STPSetupIntentStatusRequiresConfirmation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresPaymentMethod\/title","value":"STPSetupIntentStatusRequiresPaymentMethod","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresPaymentMethod\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentStatusRequiresPaymentMethod"}]},{"op":"replace","value":"STPSetupIntentStatusProcessing","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1processing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentStatusProcessing"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1processing\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1succeeded\/title","op":"replace","value":"STPSetupIntentStatusSucceeded"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1succeeded\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentStatusSucceeded"}]},{"op":"replace","value":"STPSetupIntentStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/title"},{"value":[{"text":"STPSetupIntentStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus\/navigatorTitle","value":[{"text":"STPSetupIntentStatus","kind":"identifier"}]},{"value":"STPSetupIntentStatusUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1unknown\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1unknown\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentStatusUnknown"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1canceled\/title","op":"replace","value":"STPSetupIntentStatusCanceled"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1canceled\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentStatusCanceled"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresAction\/title","op":"replace","value":"STPSetupIntentStatusRequiresAction"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentStatus~1requiresAction\/fragments","value":[{"text":"STPSetupIntentStatusRequiresAction","kind":"identifier"}]}]}]}