{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"abstract":[{"type":"text","text":"Redirect status types for a Source."}],"metadata":{"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceRedirectStatus"}],"navigatorTitle":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSourceRedirectStatus","roleHeading":"Enumeration","title":"STPSourceRedirectStatus"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPSourceRedirectStatus","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/failed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/notRequired","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/pending","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/succeeded","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/unknown"],"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"references":{"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/CustomStringConvertible-Implementations":{"kind":"article","title":"CustomStringConvertible Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/customstringconvertible-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/CustomStringConvertible-Implementations"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/notRequired":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/notrequired","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/notRequired","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notRequired","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatusNotRequired"}],"abstract":[{"text":"The redirect should not be used.","type":"text"}],"title":"STPSourceRedirectStatus.notRequired","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/succeeded":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/succeeded","abstract":[{"text":"The redirect has succeeded.","type":"text"}],"title":"STPSourceRedirectStatus.succeeded","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/succeeded","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceRedirectStatusSucceeded","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/unknown":{"navigatorTitle":[{"text":"STPSourceRedirectStatusUnknown","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"abstract":[{"type":"text","text":"The state of the redirect is unknown."}],"title":"STPSourceRedirectStatus.unknown","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/unknown","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/failed":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/failed","abstract":[{"type":"text","text":"The redirect has failed."}],"title":"STPSourceRedirectStatus.failed","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/failed","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failed","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceRedirectStatusFailed","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/Equatable-Implementations","role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/equatable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/rawrepresentable-implementations","role":"collectionGroup","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/init(rawValue:)","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus":{"title":"STPSourceRedirectStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceRedirectStatus"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceredirectstatus","abstract":[{"text":"Redirect status types for a Source.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirectStatus"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/pending":{"role":"symbol","title":"STPSourceRedirectStatus.pending","abstract":[{"text":"The redirect is pending.","type":"text"}],"navigatorTitle":[{"text":"STPSourceRedirectStatusPending","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/pending","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pending","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/pending"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceRedirectStatus"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/failed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/notRequired","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/pending","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/succeeded","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/unknown"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceRedirectStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1notRequired\/title","value":"STPSourceRedirectStatusNotRequired"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1notRequired\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceRedirectStatusNotRequired"}]},{"value":"STPSourceRedirectStatusSucceeded","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1succeeded\/title"},{"value":[{"kind":"identifier","text":"STPSourceRedirectStatusSucceeded"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1succeeded\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1unknown\/title","value":"STPSourceRedirectStatusUnknown"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1unknown\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceRedirectStatusUnknown"}]},{"value":"STPSourceRedirectStatusFailed","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1failed\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1failed\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceRedirectStatusFailed"}]},{"value":"STPSourceRedirectStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/title","op":"replace"},{"value":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceRedirectStatus"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1pending\/title","value":"STPSourceRedirectStatusPending","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus~1pending\/fragments","value":[{"kind":"identifier","text":"STPSourceRedirectStatusPending"}]}]}]}