{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceSEPADebitDetails"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails","roleHeading":"Class","title":"STPSourceSEPADebitDetails"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcesepadebitdetails"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class provides typed access to the contents of an STPSource "},{"code":"details","type":"codeVoice"},{"text":" ","type":"text"},{"text":"dictionary for SEPA Debit sources.","type":"text"}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/bankCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/fingerprint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/mandateReference","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/mandateURL"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/allResponseFields":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/allResponseFields","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"text":" ","type":"text"},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"title":"allResponseFields","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/allresponsefields","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/description":{"title":"description","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/description","type":"topic","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails":{"type":"topic","role":"symbol","abstract":[{"text":"This class provides typed access to the contents of an STPSource ","type":"text"},{"type":"codeVoice","code":"details"},{"type":"text","text":" "},{"text":"dictionary for SEPA Debit sources.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceSEPADebitDetails"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","navigatorTitle":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"kind":"symbol","title":"STPSourceSEPADebitDetails","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/mandateURL":{"title":"mandateURL","kind":"symbol","abstract":[{"type":"text","text":"The details of the mandate accepted by your customer."}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/mandateurl","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/mandateURL","navigatorTitle":[{"text":"mandateURL","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mandateURL","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/fingerprint":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/fingerprint","title":"fingerprint","abstract":[{"type":"text","text":"The account’s fingerprint."}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/fingerprint","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fingerprint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"fingerprint","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/mandateReference":{"title":"mandateReference","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/mandatereference","type":"topic","abstract":[{"type":"text","text":"The reference of the mandate accepted by your customer."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mandateReference"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/mandateReference","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mandateReference","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/country":{"title":"country","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/country","type":"topic","abstract":[{"text":"Two-letter ISO code representing the country of the bank account.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"country","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/country","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","title":"STPAPIResponseDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/decodedObject(fromAPIResponse:)":{"title":"decodedObject(fromAPIResponse:)","kind":"symbol","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/decodedobject(fromapiresponse:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/decodedObject(fromAPIResponse:)","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/last4":{"title":"last4","kind":"symbol","abstract":[{"type":"text","text":"The last 4 digits of the account number."}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/last4","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/last4","navigatorTitle":[{"text":"last4","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails/bankCode":{"title":"bankCode","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails\/bankcode","type":"topic","abstract":[{"type":"text","text":"The account’s bank code."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bankCode"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/bankCode","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bankCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceSEPADebitDetails"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceSEPADebitDetails"}]},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/bankCode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/fingerprint","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/mandateReference","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/mandateURL"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails\/decodedObject(fromAPIResponse:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceSEPADebitDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1allResponseFields\/title","value":"allResponseFields","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1allResponseFields\/fragments","op":"replace","value":[{"kind":"identifier","text":"allResponseFields"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1description\/title","value":"description","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"value":"STPSourceSEPADebitDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/fragments","value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}]},{"value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/navigatorTitle"},{"op":"replace","value":"mandateURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1mandateURL\/title"},{"value":[{"text":"mandateURL","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1mandateURL\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1fingerprint\/title","value":"fingerprint"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1fingerprint\/fragments","value":[{"kind":"identifier","text":"fingerprint"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1mandateReference\/title","value":"mandateReference"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1mandateReference\/fragments","value":[{"kind":"identifier","text":"mandateReference"}]},{"op":"replace","value":"country","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1country\/title"},{"value":[{"kind":"identifier","text":"country"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1country\/fragments"},{"value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1decodedObject(fromAPIResponse:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"op":"replace","value":"last4","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1last4\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1last4\/fragments","op":"replace","value":[{"kind":"identifier","text":"last4"}]},{"value":"bankCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1bankCode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails~1bankCode\/fragments","value":[{"kind":"identifier","text":"bankCode"}]}]}]}