{"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintent"]}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/customerID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/lastSetupError","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/livemode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/nextAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethodID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethodTypes","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/stripeDescription","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/stripeID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/usage"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/decodedObject(fromAPIResponse:)"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}]}]},{"content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"name":"See Also","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api\/Setup_intents"}],"type":"paragraph"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"metadata":{"roleHeading":"Class","externalID":"c:@M@StripePayments@objc(cs)STPSetupIntent","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntent"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}],"symbolKind":"class","title":"STPSetupIntent","role":"symbol","modules":[{"name":"StripePayments"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/status":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentStatus","kind":"typeIdentifier","text":"STPSetupIntentStatus"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/status","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/status","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"status"}],"kind":"symbol","type":"topic","title":"status","abstract":[{"type":"text","text":"Status of this SetupIntent."}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","abstract":[{"text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"}],"title":"STPSetupIntent","navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintent","kind":"symbol","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/decodedObject(fromAPIResponse:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/decodedobject(fromapiresponse:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/decodedObject(fromAPIResponse:)","role":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"code":"NSDictionary","type":"codeVoice"},{"type":"text","text":") into an instance of the class."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/stripeDescription":{"url":"\/documentation\/stripepayments\/stpsetupintent\/stripedescription","type":"topic","title":"stripeDescription","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/stripeDescription","abstract":[{"type":"text","text":"An arbitrary string attached to the object. Often useful for displaying to users."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripeDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"stripeDescription"}]},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/customerID":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"customerID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/customerid","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/customerID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"customerID"}],"kind":"symbol","type":"topic","title":"customerID","abstract":[{"type":"text","text":"ID of the Customer this SetupIntent belongs to, if one exists."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/allResponseFields":{"url":"\/documentation\/stripepayments\/stpsetupintent\/allresponsefields","type":"topic","title":"allResponseFields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/allResponseFields","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/nextAction":{"role":"symbol","title":"nextAction","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintent\/nextaction","navigatorTitle":[{"kind":"identifier","text":"nextAction"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextAction"},{"kind":"text","text":": "},{"text":"STPIntentAction","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"If present, this property tells you what actions you need to take in order for your customer to set up this payment method.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/nextAction","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/paymentMethodID":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/paymentmethodid","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethodID","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentMethodID"}],"kind":"symbol","type":"topic","title":"paymentMethodID","abstract":[{"type":"text","text":"ID of the payment method used with this SetupIntent."}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"deprecated":true,"url":"\/documentation\/stripepayments\/stpsetupintent\/metadata","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/metadata","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"metadata"}],"kind":"symbol","type":"topic","title":"metadata","abstract":[{"type":"text","text":"Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/clientSecret":{"role":"symbol","kind":"symbol","title":"clientSecret","abstract":[{"type":"text","text":"The client secret of this SetupIntent. Used for client-side retrieval using a publishable key."}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"clientSecret","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/clientsecret","navigatorTitle":[{"text":"clientSecret","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/clientSecret"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/paymentMethodTypes":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentMethodTypes"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/paymentmethodtypes","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethodTypes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentMethodTypes"}],"type":"topic","kind":"symbol","title":"paymentMethodTypes","abstract":[{"text":"The list of payment method types (e.g. ","type":"text"},{"code":"[STPPaymentMethodType.card]","type":"codeVoice"},{"text":") that this SetupIntent is allowed to set up.","type":"text"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/usage":{"role":"symbol","type":"topic","title":"usage","abstract":[{"text":"Indicates how the payment method is intended to be used in the future.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPSetupIntentUsage","text":"STPSetupIntentUsage","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/usage","navigatorTitle":[{"text":"usage","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/usage"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/lastSetupError":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastSetupError"},{"text":": ","kind":"text"},{"text":"STPSetupIntentLastSetupError","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntentLastSetupError"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/lastsetuperror","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/lastSetupError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"lastSetupError"}],"type":"topic","kind":"symbol","title":"lastSetupError","abstract":[{"type":"text","text":"The setup error encountered in the previous SetupIntent confirmation."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/idFromClientSecret:":{"role":"symbol","type":"topic","title":"idFromClientSecret:","abstract":[],"kind":"symbol","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"idFromClientSecret:"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/idfromclientsecret:","navigatorTitle":[{"text":"idFromClientSecret:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/idFromClientSecret:"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"type":"topic","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"title":"STPAPIResponseDecodable","navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/description":{"role":"symbol","type":"topic","title":"description","abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/stripeID":{"navigatorTitle":[{"text":"stripeID","kind":"identifier"}],"type":"topic","abstract":[{"text":"The Stripe ID of the SetupIntent.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/stripeid","title":"stripeID","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/stripeID","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripeID"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/livemode":{"navigatorTitle":[{"text":"livemode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/livemode","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"livemode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"livemode","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Has the value "},{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the object exists in live mode or the value "},{"type":"codeVoice","code":"NO"},{"type":"text","text":" if the object exists in test mode."}],"url":"\/documentation\/stripepayments\/stpsetupintent\/livemode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/created":{"navigatorTitle":[{"kind":"identifier","text":"created"}],"type":"topic","abstract":[{"type":"text","text":"Time at which the object was created."}],"url":"\/documentation\/stripepayments\/stpsetupintent\/created","title":"created","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/created","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"created","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent/paymentMethod":{"navigatorTitle":[{"text":"paymentMethod","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethod","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentMethod"},{"kind":"text","text":": "},{"text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"kind":"text","text":"?"}],"title":"paymentMethod","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"The optionally expanded PaymentMethod used in this SetupIntent.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintent\/paymentmethod"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPSetupIntent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPSetupIntent","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/customerID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/lastSetupError","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/livemode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/nextAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethodID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/paymentMethodTypes","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/stripeDescription","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/stripeID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/usage"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/decodedObject(fromAPIResponse:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent\/idFromClientSecret:"],"title":"Type Methods"}],"path":"\/topicSections"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntent"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"op":"replace","value":"status","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1status\/title"},{"value":[{"text":"status","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1status\/fragments","op":"replace"},{"value":"STPSetupIntent","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title"},{"value":[{"text":"STPSetupIntent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"text":"STPSetupIntent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1decodedObject(fromAPIResponse:)\/fragments"},{"value":"stripeDescription","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1stripeDescription\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1stripeDescription\/fragments","value":[{"text":"stripeDescription","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1customerID\/title","op":"replace","value":"customerID"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1customerID\/fragments","value":[{"text":"customerID","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1allResponseFields\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1nextAction\/title","value":"nextAction"},{"op":"replace","value":[{"kind":"identifier","text":"nextAction"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1nextAction\/fragments"},{"value":"paymentMethodID","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1paymentMethodID\/title"},{"value":[{"kind":"identifier","text":"paymentMethodID"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1paymentMethodID\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1metadata\/title","op":"replace","value":"metadata"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1metadata\/fragments","value":[{"text":"metadata","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1clientSecret\/title","value":"clientSecret"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1clientSecret\/fragments","op":"replace","value":[{"text":"clientSecret","kind":"identifier"}]},{"value":"paymentMethodTypes","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1paymentMethodTypes\/title"},{"op":"replace","value":[{"text":"paymentMethodTypes","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1paymentMethodTypes\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1usage\/title","value":"usage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1usage\/fragments","value":[{"text":"usage","kind":"identifier"}]},{"op":"replace","value":"lastSetupError","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1lastSetupError\/title"},{"value":[{"kind":"identifier","text":"lastSetupError"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1lastSetupError\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1description\/title","value":"description"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1description\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1stripeID\/title","value":"stripeID","op":"replace"},{"value":[{"kind":"identifier","text":"stripeID"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1stripeID\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1livemode\/title","value":"livemode"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1livemode\/fragments","value":[{"kind":"identifier","text":"livemode"}]},{"value":"created","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1created\/title"},{"value":[{"text":"created","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1created\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1paymentMethod\/title","value":"paymentMethod"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent~1paymentMethod\/fragments","value":[{"text":"paymentMethod","kind":"identifier"}]}]}]}