{"metadata":{"roleHeading":"Class","modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPSourceWeChatPayDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSourceWeChatPayDetails","kind":"identifier"}],"symbolKind":"class","title":"STPSourceWeChatPayDetails","navigatorTitle":[{"kind":"identifier","text":"STPSourceWeChatPayDetails"}]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/weChatAppURL"]},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/decodedObject(fromAPIResponse:)"],"generated":true,"anchor":"Type-Methods"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcewechatpaydetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcewechatpaydetails"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceWeChatPayDetails"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Details of a WeChat Pay Source."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceWeChatPayDetails/weChatAppURL":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"weChatAppURL","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"text":"A URL to the WeChat App.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Use "},{"type":"codeVoice","code":"STPRedirectContext"},{"text":" instead of redirecting users yourself.","type":"text"}],"title":"weChatAppURL","url":"\/documentation\/stripepayments\/stpsourcewechatpaydetails\/wechatappurl","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/weChatAppURL","navigatorTitle":[{"kind":"identifier","text":"weChatAppURL"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceWeChatPayDetails/allResponseFields":{"title":"allResponseFields","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"url":"\/documentation\/stripepayments\/stpsourcewechatpaydetails\/allresponsefields","kind":"symbol","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceWeChatPayDetails/decodedObject(fromAPIResponse:)":{"title":"decodedObject(fromAPIResponse:)","role":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/decodedObject(fromAPIResponse:)","kind":"symbol","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourcewechatpaydetails\/decodedobject(fromapiresponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAPIResponseDecodable"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","title":"STPAPIResponseDecodable","abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"type":"text","text":" "},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceWeChatPayDetails/description":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/description","role":"symbol","kind":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourcewechatpaydetails\/description"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceWeChatPayDetails":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceWeChatPayDetails"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceWeChatPayDetails"}],"url":"\/documentation\/stripepayments\/stpsourcewechatpaydetails","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails","title":"STPSourceWeChatPayDetails","abstract":[{"type":"text","text":"Details of a WeChat Pay Source."}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"STPSourceWeChatPayDetails","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceWeChatPayDetails"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPSourceWeChatPayDetails","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/weChatAppURL"],"generated":true,"anchor":"Instance-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails\/decodedObject(fromAPIResponse:)"],"generated":true,"anchor":"Type-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"type":"conformsTo","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"STPSourceWeChatPayDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"weChatAppURL","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1weChatAppURL\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1weChatAppURL\/fragments","value":[{"kind":"identifier","text":"weChatAppURL"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1allResponseFields\/title","op":"replace","value":"allResponseFields"},{"op":"replace","value":[{"kind":"identifier","text":"allResponseFields"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1allResponseFields\/fragments"},{"value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1decodedObject(fromAPIResponse:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1decodedObject(fromAPIResponse:)\/fragments"},{"op":"replace","value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/title","value":"STPSourceWeChatPayDetails"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceWeChatPayDetails"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/navigatorTitle","value":[{"text":"STPSourceWeChatPayDetails","kind":"identifier"}],"op":"replace"}]}]}