{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentusage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentusage"]}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSetupIntentUsage","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsage"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPSetupIntentUsage","title":"STPSetupIntentUsage","roleHeading":"Enumeration"},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/none","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/offSession","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/onSession","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/unknown"],"title":"Enumeration Cases","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"abstract":[{"type":"text","text":"Indicates how the payment method is intended to be used in the future."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntentUsage"}],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"type":"aside","style":"note","name":"See Also","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Api\/Setup_intents\/Create#Create_setup_intent-Usage"}]}]}]}],"references":{"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/CustomStringConvertible-Implementations","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpsetupintentusage\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","abstract":[]},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage":{"abstract":[{"text":"Indicates how the payment method is intended to be used in the future.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintentusage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage","title":"STPSetupIntentUsage","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentUsage","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntentUsage","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/onSession":{"title":"STPSetupIntentUsage.onSession","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSession"}],"abstract":[{"type":"text","text":"Indicates you intend to only reuse the payment method when the customer is in your checkout flow."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/onSession","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsageOnSession"}],"url":"\/documentation\/stripepayments\/stpsetupintentusage\/onsession","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/Equatable-Implementations","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpsetupintentusage\/equatable-implementations","title":"Equatable Implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/RawRepresentable-Implementations":{"kind":"article","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/RawRepresentable-Implementations","url":"\/documentation\/stripepayments\/stpsetupintentusage\/rawrepresentable-implementations","role":"collectionGroup","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/unknown":{"abstract":[{"type":"text","text":"Unknown value.  Update your SDK, or use "},{"type":"codeVoice","code":"allResponseFields"},{"type":"text","text":" for custom handling."}],"title":"STPSetupIntentUsage.unknown","url":"\/documentation\/stripepayments\/stpsetupintentusage\/unknown","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"type":"topic","navigatorTitle":[{"text":"STPSetupIntentUsageUnknown","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/unknown"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/init(rawValue:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/init(rawValue:)","url":"\/documentation\/stripepayments\/stpsetupintentusage\/init(rawvalue:)","type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/none":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentusage\/none","navigatorTitle":[{"text":"STPSetupIntentUsageNone","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/none","type":"topic","abstract":[{"type":"text","text":"No value was provided."}],"title":"STPSetupIntentUsage.none"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentUsage/offSession":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentusage\/offsession","title":"STPSetupIntentUsage.offSession","role":"symbol","abstract":[{"type":"text","text":"Indicates you intend to reuse the payment method when the customer may or may not be in your checkout flow."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"offSession","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/offSession","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentUsageOffSession"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPSetupIntentUsage","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentUsage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntentUsage"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/none","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/offSession","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/onSession","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentUsage\/unknown"],"title":"Enumeration Cases","generated":true}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSetupIntentUsage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/title","value":"STPSetupIntentUsage"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentUsage"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage\/navigatorTitle","op":"replace","value":[{"text":"STPSetupIntentUsage","kind":"identifier"}]},{"value":"STPSetupIntentUsageOnSession","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1onSession\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1onSession\/fragments","value":[{"text":"STPSetupIntentUsageOnSession","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1unknown\/title","value":"STPSetupIntentUsageUnknown"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentUsageUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1unknown\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1none\/title","value":"STPSetupIntentUsageNone"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1none\/fragments","value":[{"text":"STPSetupIntentUsageNone","kind":"identifier"}]},{"value":"STPSetupIntentUsageOffSession","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1offSession\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentUsageOffSession"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentUsage~1offSession\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}