{"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/canceled","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/chargeable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/consumed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/failed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/pending","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/unknown"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcestatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcestatus"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceStatus","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Status types for a Source"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"},"metadata":{"title":"STPSourceStatus","role":"symbol","navigatorTitle":[{"text":"STPSourceStatus","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Enumeration","externalID":"c:@M@StripePayments@E@STPSourceStatus","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceStatus","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceStatus"}],"title":"STPSourceStatus","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcestatus","type":"topic","abstract":[{"text":"Status types for a Source","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/consumed":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consumed","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPSourceStatusConsumed","kind":"identifier"}],"title":"STPSourceStatus.consumed","abstract":[{"text":"The source has been used. This status only applies to single-use sources.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/consumed","url":"\/documentation\/stripepayments\/stpsourcestatus\/consumed"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/chargeable":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceStatusChargeable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/chargeable","url":"\/documentation\/stripepayments\/stpsourcestatus\/chargeable","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chargeable"}],"abstract":[{"text":"The source is ready to use. The customer action has been completed or the","type":"text"},{"text":" ","type":"text"},{"text":"payment method requires no customer action.","type":"text"}],"title":"STPSourceStatus.chargeable","role":"symbol"},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/unknown":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceStatusUnknown"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/unknown","url":"\/documentation\/stripepayments\/stpsourcestatus\/unknown","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"abstract":[{"text":"The source status is unknown.","type":"text"}],"title":"STPSourceStatus.unknown","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stpsourcestatus\/customstringconvertible-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/CustomStringConvertible-Implementations","kind":"article","type":"topic","role":"collectionGroup","title":"CustomStringConvertible Implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpsourcestatus\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/RawRepresentable-Implementations","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/canceled":{"role":"symbol","navigatorTitle":[{"text":"STPSourceStatusCanceled","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canceled","kind":"identifier"}],"title":"STPSourceStatus.canceled","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcestatus\/canceled","type":"topic","abstract":[{"type":"text","text":"The source, which was chargeable, has expired because it was not used to"},{"type":"text","text":" "},{"type":"text","text":"make a charge request within a specified amount of time."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/canceled"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/pending":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/pending","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceStatusPending"}],"title":"STPSourceStatus.pending","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcestatus\/pending","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pending"}],"abstract":[{"text":"The source has been created and is awaiting customer action.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","url":"\/documentation\/stripepayments\/stpsourcestatus\/init(rawvalue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpsourcestatus\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/Equatable-Implementations","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus/failed":{"url":"\/documentation\/stripepayments\/stpsourcestatus\/failed","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceStatusFailed"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/failed","title":"STPSourceStatus.failed","abstract":[{"text":"Your customer has not taken the required action or revoked your access","type":"text"},{"text":" ","type":"text"},{"text":"(e.g., did not authorize the payment with their bank or canceled their","type":"text"},{"text":" ","type":"text"},{"text":"mandate acceptance for SEPA direct debits).","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPSourceStatus","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPSourceStatus","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"STPSourceStatus","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/canceled","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/chargeable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/consumed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/failed","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/pending","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus\/unknown"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceStatus"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSourceStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments","op":"replace"},{"value":[{"text":"STPSourceStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/navigatorTitle","op":"replace"},{"value":"STPSourceStatusConsumed","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1consumed\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceStatusConsumed"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1consumed\/fragments","op":"replace"},{"value":"STPSourceStatusChargeable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1chargeable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceStatusChargeable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1chargeable\/fragments","op":"replace"},{"value":"STPSourceStatusUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1unknown\/title","op":"replace"},{"value":[{"text":"STPSourceStatusUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1unknown\/fragments","op":"replace"},{"value":"STPSourceStatusCanceled","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1canceled\/title","op":"replace"},{"value":[{"text":"STPSourceStatusCanceled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1canceled\/fragments","op":"replace"},{"value":"STPSourceStatusPending","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1pending\/title","op":"replace"},{"value":[{"text":"STPSourceStatusPending","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1pending\/fragments","op":"replace"},{"value":"STPSourceStatusFailed","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1failed\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceStatusFailed"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus~1failed\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}