{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"},"abstract":[{"text":"The status of this card’s 3D Secure support.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/notSupported","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/optional","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/recommended","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/required","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/unknown"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Https:\/\/Stripe.Com\/Docs\/Sources\/Three-D-Secure#Check-Requirement"}]}],"type":"aside","name":"See Also"}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcecard3dsecurestatus"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo"}],"metadata":{"roleHeading":"Enumeration","symbolKind":"enum","title":"STPSourceCard3DSecureStatus","role":"symbol","navigatorTitle":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus","modules":[{"name":"StripePayments"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/optional":{"title":"STPSourceCard3DSecureStatus.optional","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusOptional"}],"abstract":[{"type":"text","text":"3D Secure is optional. It is not required nor recommended for successful charging,"},{"type":"text","text":" "},{"type":"text","text":"but can be performed to help reduce the likelihood of fraud."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"optional"}],"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/optional","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/optional"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/Equatable-Implementations","abstract":[],"title":"Equatable Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/equatable-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/init(rawValue:)":{"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/init(rawValue:)","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/init(rawvalue:)","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/unknown":{"abstract":[{"type":"text","text":"The status of 3D Secure support on this card is unknown."}],"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/unknown","navigatorTitle":[{"text":"STPSourceCard3DSecureStatusUnknown","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/unknown","title":"STPSourceCard3DSecureStatus.unknown","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus","abstract":[{"type":"text","text":"The status of this card’s 3D Secure support."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus","title":"STPSourceCard3DSecureStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/notSupported":{"navigatorTitle":[{"text":"STPSourceCard3DSecureStatusNotSupported","kind":"identifier"}],"title":"STPSourceCard3DSecureStatus.notSupported","type":"topic","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/notsupported","abstract":[{"text":"3D Secure is not supported on this card.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/notSupported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notSupported","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/recommended":{"abstract":[{"type":"text","text":"3D Secure is recommended. The process is not required, but it is highly recommended"},{"type":"text","text":" "},{"type":"text","text":"and has minimal impact to your conversion rate."}],"url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/recommended","type":"topic","navigatorTitle":[{"text":"STPSourceCard3DSecureStatusRecommended","kind":"identifier"}],"title":"STPSourceCard3DSecureStatus.recommended","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recommended","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/recommended","kind":"symbol"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/required":{"abstract":[{"type":"text","text":"3D Secure is required. This card must be converted into a 3D Secure"},{"type":"text","text":" "},{"type":"text","text":"source for a charge on it to be successful."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/required","type":"topic","role":"symbol","title":"STPSourceCard3DSecureStatus.required","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/required","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"required"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusRequired"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/CustomStringConvertible-Implementations","abstract":[],"title":"CustomStringConvertible Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus\/customstringconvertible-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPSourceCard3DSecureStatus","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/notSupported","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/optional","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/recommended","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/required","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus\/unknown"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceCard3DSecureStatus"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSourceCard3DSecureStatusOptional","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1optional\/title","op":"replace"},{"value":[{"text":"STPSourceCard3DSecureStatusOptional","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1optional\/fragments","op":"replace"},{"value":"STPSourceCard3DSecureStatusUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1unknown\/title","op":"replace"},{"value":[{"text":"STPSourceCard3DSecureStatusUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1unknown\/fragments","op":"replace"},{"value":"STPSourceCard3DSecureStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/title","op":"replace"},{"value":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/navigatorTitle","op":"replace"},{"value":"STPSourceCard3DSecureStatusNotSupported","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1notSupported\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusNotSupported"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1notSupported\/fragments","op":"replace"},{"value":"STPSourceCard3DSecureStatusRecommended","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1recommended\/title","op":"replace"},{"value":[{"text":"STPSourceCard3DSecureStatusRecommended","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1recommended\/fragments","op":"replace"},{"value":"STPSourceCard3DSecureStatusRequired","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1required\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceCard3DSecureStatusRequired"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus~1required\/fragments","op":"replace"}]}]}