{"metadata":{"title":"STPSourceOwner","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceOwner"}],"navigatorTitle":[{"text":"STPSourceOwner","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceOwner","symbolKind":"class","role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/address","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/email","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/phone","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedAddress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedEmail","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedName","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedPhone"],"anchor":"Instance-Properties","generated":true},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/decodedObject(fromAPIResponse:)"],"title":"Type Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceOwner","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"Information about a source’s owner."}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceowner"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceowner"]}],"references":{"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/phone":{"title":"phone","abstract":[{"type":"text","text":"Owner’s phone number."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/phone","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"phone"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"phone","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceowner\/phone"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner":{"url":"\/documentation\/stripepayments\/stpsourceowner","abstract":[{"type":"text","text":"Information about a source’s owner."}],"type":"topic","title":"STPSourceOwner","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceOwner"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceOwner"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/verifiedAddress":{"title":"verifiedAddress","abstract":[{"type":"text","text":"Verified owner’s address."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedAddress","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"verifiedAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"verifiedAddress"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceowner\/verifiedaddress"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/verifiedName":{"title":"verifiedName","abstract":[{"type":"text","text":"Verified owner’s full name."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedName","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"verifiedName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"verifiedName"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceowner\/verifiedname"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/allResponseFields":{"url":"\/documentation\/stripepayments\/stpsourceowner\/allresponsefields","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"text":" ","type":"text"},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"type":"topic","title":"allResponseFields","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/allResponseFields","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/address":{"title":"address","abstract":[{"type":"text","text":"Owner’s address."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/address","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"address","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","kind":"typeIdentifier","text":"STPAddress"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"address","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceowner\/address"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/decodedObject(fromAPIResponse:)":{"url":"\/documentation\/stripepayments\/stpsourceowner\/decodedobject(fromapiresponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"type":"text","text":"an "},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"type":"topic","title":"decodedObject(fromAPIResponse:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/decodedObject(fromAPIResponse:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/verifiedEmail":{"title":"verifiedEmail","abstract":[{"type":"text","text":"Verified owner’s email address."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedEmail","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"verifiedEmail","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"verifiedEmail"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceowner\/verifiedemail"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/name":{"url":"\/documentation\/stripepayments\/stpsourceowner\/name","abstract":[{"type":"text","text":"Owner’s full name."}],"type":"topic","title":"name","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/name","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"name"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/email":{"title":"email","abstract":[{"type":"text","text":"Owner’s email address."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/email","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"email","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"email"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceowner\/email"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","title":"STPAPIResponseDecodable","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceOwner/verifiedPhone":{"title":"verifiedPhone","abstract":[{"text":"Verified owner’s phone number.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedPhone","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"verifiedPhone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"verifiedPhone"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceowner\/verifiedphone"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceOwner"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"STPSourceOwner","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPSourceOwner","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/address","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/email","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/name","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/phone","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedAddress","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedEmail","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedName","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/verifiedPhone"]},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceOwner\/decodedObject(fromAPIResponse:)"],"title":"Type Methods","generated":true}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceOwner","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1phone\/title","value":"phone"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1phone\/fragments","value":[{"text":"phone","kind":"identifier"}],"op":"replace"},{"value":"STPSourceOwner","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner\/title"},{"value":[{"text":"STPSourceOwner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceOwner"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedAddress\/title","value":"verifiedAddress","op":"replace"},{"value":[{"kind":"identifier","text":"verifiedAddress"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedAddress\/fragments"},{"value":"verifiedName","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedName\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedName\/fragments","value":[{"text":"verifiedName","kind":"identifier"}]},{"op":"replace","value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1allResponseFields\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1allResponseFields\/fragments","op":"replace","value":[{"kind":"identifier","text":"allResponseFields"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1address\/title","value":"address","op":"replace"},{"value":[{"kind":"identifier","text":"address"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1address\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedEmail\/title","value":"verifiedEmail","op":"replace"},{"value":[{"text":"verifiedEmail","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedEmail\/fragments"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1name\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1email\/title","value":"email","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1email\/fragments","value":[{"text":"email","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"op":"replace"},{"value":"verifiedPhone","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedPhone\/title","op":"replace"},{"value":[{"text":"verifiedPhone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceOwner~1verifiedPhone\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}