{"sections":[],"topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/returnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/url"]},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods","title":"Type Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceRedirect","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceredirect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourceredirect"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirect"}],"symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPSourceRedirect","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSourceRedirect","kind":"identifier"}],"title":"STPSourceRedirect","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Class"},"kind":"symbol","abstract":[{"text":"Information related to a source’s redirect flow.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"type":"topic","title":"STPAPIResponseDecodable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect/decodedObject(fromAPIResponse:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/decodedObject(fromAPIResponse:)","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"type":"text","text":"an "},{"code":"NSDictionary","type":"codeVoice"},{"type":"text","text":") into an instance of the class."}],"role":"symbol","type":"topic","title":"decodedObject(fromAPIResponse:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceredirect\/decodedobject(fromapiresponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect/description":{"abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/description","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceredirect\/description","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect/returnURL":{"navigatorTitle":[{"text":"returnURL","kind":"identifier"}],"type":"topic","title":"returnURL","abstract":[{"type":"text","text":"The URL you provide to redirect the customer to after they authenticated their payment."}],"url":"\/documentation\/stripepayments\/stpsourceredirect\/returnurl","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/returnURL","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect/allResponseFields":{"url":"\/documentation\/stripepayments\/stpsourceredirect\/allresponsefields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/allResponseFields","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"title":"allResponseFields","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect","url":"\/documentation\/stripepayments\/stpsourceredirect","kind":"symbol","abstract":[{"type":"text","text":"Information related to a source’s redirect flow."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceRedirect","kind":"identifier"}],"title":"STPSourceRedirect","navigatorTitle":[{"kind":"identifier","text":"STPSourceRedirect"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect/url":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/url","role":"symbol","kind":"symbol","abstract":[{"text":"The URL provided to you to redirect a customer to as part of a redirect authentication flow.","type":"text"}],"title":"url","type":"topic","url":"\/documentation\/stripepayments\/stpsourceredirect\/url","navigatorTitle":[{"kind":"identifier","text":"url"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"url","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect/status":{"type":"topic","url":"\/documentation\/stripepayments\/stpsourceredirect\/status","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/status","navigatorTitle":[{"text":"status","kind":"identifier"}],"abstract":[{"text":"The status of the redirect.","type":"text"}],"title":"status","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceRedirectStatus","text":"STPSourceRedirectStatus","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"STPSourceRedirect","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"STPSourceRedirect"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceRedirect"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/returnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/url"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/decodedObject(fromAPIResponse:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"]}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceRedirect","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1returnURL\/title","op":"replace","value":"returnURL"},{"value":[{"text":"returnURL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1returnURL\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1allResponseFields\/title","value":"allResponseFields"},{"value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1allResponseFields\/fragments"},{"value":"STPSourceRedirect","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/title"},{"value":[{"kind":"identifier","text":"STPSourceRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/navigatorTitle"},{"value":"url","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1url\/title"},{"op":"replace","value":[{"text":"url","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1url\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1status\/title","op":"replace","value":"status"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1status\/fragments","value":[{"text":"status","kind":"identifier"}],"op":"replace"}]}]}