{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype"]}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/API","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/apiConnection","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/authentication","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/idempotency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/invalidRequest","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/rateLimit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/unknown"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/init(rawValue:)"],"title":"Initializers","generated":true},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"sections":[],"abstract":[{"type":"text","text":"The type of the error represented by "},{"code":"STPSetupIntentLastSetupError","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Some STPSetupIntentLastError properties are only populated for certain error types.","type":"text"}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"StripePayments"}],"title":"STPSetupIntentLastSetupErrorType","role":"symbol","externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"kind":"relationships"}],"references":{"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/rawrepresentable-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"kind":"article","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/apiConnection":{"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeAPIConnection","kind":"identifier"}],"abstract":[{"text":"An error connecting to Stripe’s API.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"apiConnection"}],"type":"topic","title":"STPSetupIntentLastSetupErrorType.apiConnection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/apiConnection","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/apiconnection","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/card":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/card","role":"symbol","abstract":[{"text":"Card errors are the most common type of error you should expect to handle.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"They result when the user enters a card that can’t be charged for some reason."},{"type":"text","text":" "},{"text":"Check the ","type":"text"},{"type":"codeVoice","code":"declineCode"},{"type":"text","text":" property for the decline code.  The "},{"type":"codeVoice","code":"message"},{"text":" property contains a message you can show to your users.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/card","kind":"symbol","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeCard","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"card"}],"title":"STPSetupIntentLastSetupErrorType.card"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/CustomStringConvertible-Implementations":{"title":"CustomStringConvertible Implementations","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/customstringconvertible-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/CustomStringConvertible-Implementations","abstract":[],"kind":"article","role":"collectionGroup","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/idempotency":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeIdempotency"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"idempotency","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/idempotency","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/idempotency","abstract":[{"text":"Keys for idempotent requests can only be used with the same parameters they were first used with.","type":"text"}],"title":"STPSetupIntentLastSetupErrorType.idempotency"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/equatable-implementations","role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/Equatable-Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/authentication":{"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeAuthentication"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/authentication","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/authentication","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"authentication","kind":"identifier"}],"abstract":[{"text":"A failure to authenticate your customer.","type":"text"}],"role":"symbol","title":"STPSetupIntentLastSetupErrorType.authentication","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/unknown":{"url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/unknown","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeUnknown","kind":"identifier"}],"abstract":[{"type":"text","text":"An unknown error type."}],"type":"topic","role":"symbol","kind":"symbol","title":"STPSetupIntentLastSetupErrorType.unknown","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/rateLimit":{"title":"STPSetupIntentLastSetupErrorType.rateLimit","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"rateLimit","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeRateLimit"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/rateLimit","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/ratelimit","type":"topic","abstract":[{"text":"Too many requests hit the API too quickly.","type":"text"}]},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/invalidRequest":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidRequest"}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeInvalidRequest","kind":"identifier"}],"title":"STPSetupIntentLastSetupErrorType.invalidRequest","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Invalid request errors.  Typically, this is because your request has invalid parameters."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/invalidRequest","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/invalidrequest"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"title":"STPSetupIntentLastSetupErrorType","abstract":[{"text":"The type of the error represented by ","type":"text"},{"code":"STPSetupIntentLastSetupError","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Some STPSetupIntentLastError properties are only populated for certain error types."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/init(rawvalue:)","abstract":[],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/init(rawValue:)","type":"topic","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/API":{"title":"STPSetupIntentLastSetupErrorType.API","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"API","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An error with the Stripe API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/API","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/api","type":"topic","navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeAPI","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"STPSetupIntentLastSetupErrorType"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/API","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/apiConnection","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/authentication","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/idempotency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/invalidRequest","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/rateLimit","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/unknown"]}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1apiConnection\/title","value":"STPSetupIntentLastSetupErrorTypeAPIConnection"},{"value":[{"text":"STPSetupIntentLastSetupErrorTypeAPIConnection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1apiConnection\/fragments","op":"replace"},{"op":"replace","value":"STPSetupIntentLastSetupErrorTypeCard","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1card\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1card\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeCard"}]},{"value":"STPSetupIntentLastSetupErrorTypeIdempotency","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1idempotency\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1idempotency\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeIdempotency"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1authentication\/title","value":"STPSetupIntentLastSetupErrorTypeAuthentication"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1authentication\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorTypeAuthentication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1unknown\/title","value":"STPSetupIntentLastSetupErrorTypeUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1unknown\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorTypeUnknown","kind":"identifier"}],"op":"replace"},{"value":"STPSetupIntentLastSetupErrorTypeRateLimit","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1rateLimit\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1rateLimit\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeRateLimit"}],"op":"replace"},{"op":"replace","value":"STPSetupIntentLastSetupErrorTypeInvalidRequest","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1invalidRequest\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1invalidRequest\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeInvalidRequest"}],"op":"replace"},{"op":"replace","value":"STPSetupIntentLastSetupErrorType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title"},{"value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}]},{"value":"STPSetupIntentLastSetupErrorTypeAPI","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1API\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1API\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorTypeAPI","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}