{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceCardDetails"}],"symbolKind":"class","modules":[{"name":"StripePayments"}],"title":"STPSourceCardDetails","externalID":"c:@M@StripePayments@objc(cs)STPSourceCardDetails","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceCardDetails"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/brand","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/expMonth","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/expYear","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/funding","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/isApplePayCard","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/threeDSecure"]},{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/decodedObject(fromAPIResponse:)"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCardDetails","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"This class provides typed access to the contents of an STPSource "},{"type":"codeVoice","code":"details"},{"type":"text","text":" "},{"type":"text","text":"dictionary for card sources."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcecarddetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcecarddetails"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/allResponseFields":{"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"kind":"symbol","title":"allResponseFields","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/allResponseFields","url":"\/documentation\/stripepayments\/stpsourcecarddetails\/allresponsefields","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/description":{"title":"description","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/description","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpsourcecarddetails\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/funding":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/funding","url":"\/documentation\/stripepayments\/stpsourcecarddetails\/funding","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"funding","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","text":"STPCardFundingType","kind":"typeIdentifier"}],"title":"funding","navigatorTitle":[{"text":"funding","kind":"identifier"}],"abstract":[{"text":"The funding source for the card (credit, debit, prepaid, or other)","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"title":"STPAPIResponseDecodable","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceCardDetails"}],"abstract":[{"type":"text","text":"This class provides typed access to the contents of an STPSource "},{"type":"codeVoice","code":"details"},{"type":"text","text":" "},{"type":"text","text":"dictionary for card sources."}],"title":"STPSourceCardDetails","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails","navigatorTitle":[{"kind":"identifier","text":"STPSourceCardDetails"}],"url":"\/documentation\/stripepayments\/stpsourcecarddetails","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/country":{"url":"\/documentation\/stripepayments\/stpsourcecarddetails\/country","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"text":"Two-letter ISO code representing the issuing country of the card.","type":"text"}],"role":"symbol","kind":"symbol","title":"country","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/country","type":"topic","navigatorTitle":[{"text":"country","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/isApplePayCard":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isApplePayCard","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"True if this card was created through Apple Pay, false otherwise.","type":"text"}],"title":"isApplePayCard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/isApplePayCard","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcecarddetails\/isapplepaycard","navigatorTitle":[{"text":"isApplePayCard","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/expYear":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"expYear","kind":"identifier"}],"abstract":[{"text":"The card’s expiration year.","type":"text"}],"title":"expYear","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/expYear","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expYear","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpsourcecarddetails\/expyear","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/expMonth":{"role":"symbol","abstract":[{"type":"text","text":"The card’s expiration month. 1-indexed (i.e. 1 == January)"}],"title":"expMonth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"expMonth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/expMonth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"expMonth"}],"url":"\/documentation\/stripepayments\/stpsourcecarddetails\/expmonth"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/brand":{"title":"brand","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brand","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/brand","navigatorTitle":[{"text":"brand","kind":"identifier"}],"type":"topic","abstract":[{"text":"The issuer of the card.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourcecarddetails\/brand","kind":"symbol"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/decodedObject(fromAPIResponse:)":{"url":"\/documentation\/stripepayments\/stpsourcecarddetails\/decodedobject(fromapiresponse:)","kind":"symbol","role":"symbol","title":"decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/threeDSecure":{"kind":"symbol","navigatorTitle":[{"text":"threeDSecure","kind":"identifier"}],"type":"topic","abstract":[{"text":"Whether 3D Secure is supported or required by the card.","type":"text"}],"title":"threeDSecure","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threeDSecure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus","text":"STPSourceCard3DSecureStatus","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/threeDSecure","role":"symbol","url":"\/documentation\/stripepayments\/stpsourcecarddetails\/threedsecure"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/last4":{"navigatorTitle":[{"kind":"identifier","text":"last4"}],"url":"\/documentation\/stripepayments\/stpsourcecarddetails\/last4","title":"last4","kind":"symbol","abstract":[{"type":"text","text":"The last 4 digits of the card."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/last4","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"last4"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"STPSourceCardDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceCardDetails"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceCardDetails"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/brand","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/country","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/expMonth","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/expYear","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/funding","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/isApplePayCard","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/last4","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/threeDSecure"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/decodedObject(fromAPIResponse:)"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCardDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1allResponseFields\/title","value":"allResponseFields","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1funding\/title","value":"funding","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1funding\/fragments","value":[{"kind":"identifier","text":"funding"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/title","value":"STPSourceCardDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/fragments","value":[{"text":"STPSourceCardDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/navigatorTitle","value":[{"text":"STPSourceCardDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1country\/title","value":"country","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1country\/fragments","value":[{"text":"country","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1isApplePayCard\/title","value":"isApplePayCard","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1isApplePayCard\/fragments","value":[{"text":"isApplePayCard","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1expYear\/title","value":"expYear","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1expYear\/fragments","value":[{"text":"expYear","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1expMonth\/title","value":"expMonth","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1expMonth\/fragments","value":[{"kind":"identifier","text":"expMonth"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1brand\/title","value":"brand","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1brand\/fragments","value":[{"kind":"identifier","text":"brand"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1threeDSecure\/title","value":"threeDSecure","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1threeDSecure\/fragments","value":[{"text":"threeDSecure","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1last4\/title","value":"last4","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1last4\/fragments","value":[{"kind":"identifier","text":"last4"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}