{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceprotocolcompletionblock"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocolCompletionBlock"},"abstract":[{"type":"text","text":"A callback to be run with a source or card response from the Stripe API."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceProtocolCompletionBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"text":"STPSourceProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The Stripe source from the response. Will be nil if an error occurs. - seealso: STPSourceProtocol"}],"type":"paragraph"}],"name":"source"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error returned from the response, or nil if none occurs. - seealso: StripeError.h for possible values."}]}],"name":"error"}]}],"sections":[],"metadata":{"symbolKind":"typealias","roleHeading":"Type Alias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceProtocolCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceProtocolCompletionBlock","kind":"identifier"}],"title":"STPSourceProtocolCompletionBlock","modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"s:14StripePayments32STPSourceProtocolCompletionBlocka"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocolCompletionBlock":{"title":"STPSourceProtocolCompletionBlock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceProtocolCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocolCompletionBlock","abstract":[{"text":"A callback to be run with a source or card response from the Stripe API.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceprotocolcompletionblock","navigatorTitle":[{"text":"STPSourceProtocolCompletionBlock","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocol":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceProtocol"}],"title":"STPSourceProtocol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","url":"\/documentation\/stripepayments\/stpsourceprotocol","abstract":[{"type":"text","text":"Objects conforming to this protocol can be attached to a Stripe Customer object"},{"type":"text","text":" "},{"type":"text","text":"as a payment source."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPSourceProtocol","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/title"},{"value":[{"text":"STPSourceProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/navigatorTitle"}]}]}