{"abstract":[{"text":"A callback to be run with a PaymentIntent response from the Stripe API.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentCompletionBlock"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentcompletionblock"]}],"sections":[],"metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentCompletionBlock","kind":"identifier"}],"title":"STPSetupIntentCompletionBlock","symbolKind":"typealias","roleHeading":"Type Alias","externalID":"s:14StripePayments29STPSetupIntentCompletionBlocka","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentCompletionBlock"}],"modules":[{"name":"StripePayments"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentCompletionBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","text":"STPSetupIntent","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSetupIntent"},{"text":"?, ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The Stripe SetupIntent from the response. Will be nil if an error occurs. - seealso: STPSetupIntent","type":"text"}]}],"name":"setupIntent"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error returned from the response, or nil if none occurs. - seealso: StripeError.h for possible values."}]}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentCompletionBlock":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentCompletionBlock","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentCompletionBlock","abstract":[{"type":"text","text":"A callback to be run with a PaymentIntent response from the Stripe API."}],"url":"\/documentation\/stripepayments\/stpsetupintentcompletionblock","title":"STPSetupIntentCompletionBlock","type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSetupIntentCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntent":{"abstract":[{"type":"text","text":"A SetupIntent guides you through the process of setting up a customer’s payment credentials for future payments."}],"url":"\/documentation\/stripepayments\/stpsetupintent","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPSetupIntent","kind":"identifier"}],"title":"STPSetupIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntent","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/title","value":"STPSetupIntent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/fragments","value":[{"kind":"identifier","text":"STPSetupIntent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntent\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}