{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"roleHeading":"Class","modules":[{"name":"StripePayments"}],"symbolKind":"class","navigatorTitle":[{"text":"STPSource","kind":"identifier"}],"title":"STPSource","externalID":"c:@M@StripePayments@objc(cs)STPSource","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPSource","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSource"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsource"]},{"paths":["\/documentation\/stripepayments\/stpsource"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/amount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/cardDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/details","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/flow","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/klarnaDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/livemode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/owner","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/receiver","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/redirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/sepaDebitDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/stripeID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/usage","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/verification","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/weChatPayDetails"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/isEqual(_:)"],"generated":true},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/decodedObject(fromAPIResponse:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","interfaceLanguage":"swift"},"abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/usage":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/usage","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"usage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceUsage","preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage"}],"abstract":[{"text":"Whether this source should be reusable or not.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/usage","navigatorTitle":[{"kind":"identifier","text":"usage"}],"title":"usage","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/details":{"title":"details","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/details","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/details","abstract":[{"type":"text","text":"Information about the source specific to its type"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"details"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"details"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","role":"symbol","type":"topic","abstract":[{"text":"Objects conforming to STPAPIResponseDecodable can be automatically converted","type":"text"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"title":"STPAPIResponseDecodable","url":"\/documentation\/stripepayments\/stpapiresponsedecodable","navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/decodedObject(fromAPIResponse:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/decodedobject(fromapiresponse:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"text":"?","kind":"text"}],"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"type":"text","text":"an "},{"code":"NSDictionary","type":"codeVoice"},{"text":") into an instance of the class.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/decodedObject(fromAPIResponse:)","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"title":"decodedObject(fromAPIResponse:)","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/receiver":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/receiver","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"receiver"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceReceiver","kind":"typeIdentifier","text":"STPSourceReceiver"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Information related to the receiver flow. Present if the source’s flow"},{"text":" ","type":"text"},{"text":"is receiver.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/receiver","navigatorTitle":[{"kind":"identifier","text":"receiver"}],"title":"receiver","type":"topic"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/verification":{"url":"\/documentation\/stripepayments\/stpsource\/verification","role":"symbol","abstract":[{"text":"Information related to the verification flow. Present if the source’s flow","type":"text"},{"text":" ","type":"text"},{"text":"is verification.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceVerification","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceVerification"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"verification"}],"title":"verification","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/verification","type":"topic"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsource","type":"topic","title":"STPSource","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSource"}],"navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"abstract":[{"type":"text","text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/stripeID":{"url":"\/documentation\/stripepayments\/stpsource\/stripeid","role":"symbol","abstract":[{"type":"text","text":"The Stripe ID of the source."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stripeID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"stripeID"}],"title":"stripeID","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/stripeID","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocol":{"title":"STPSourceProtocol","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPSourceProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to this protocol can be attached to a Stripe Customer object"},{"text":" ","type":"text"},{"text":"as a payment source.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceprotocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceProtocol"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/owner":{"title":"owner","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/owner","abstract":[{"type":"text","text":"Information about the owner of the payment instrument."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/owner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"owner","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceOwner","text":"STPSourceOwner","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"owner"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/sepaDebitDetails":{"title":"sepaDebitDetails","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/sepaDebitDetails","abstract":[{"text":"If this is a SEPA Debit source, this property provides typed access to the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"contents of the "},{"code":"details","type":"codeVoice"},{"text":" dictionary.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsource\/sepadebitdetails","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sepaDebitDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails","kind":"typeIdentifier","text":"STPSourceSEPADebitDetails"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sepaDebitDetails"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/currency":{"title":"currency","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/currency","abstract":[{"text":"The currency associated with the source.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/currency","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currency","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/isEqual(_:)":{"title":"isEqual(_:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/isEqual(_:)","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stpsource\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/metadata":{"title":"metadata","type":"topic","role":"symbol","kind":"symbol","deprecated":true,"url":"\/documentation\/stripepayments\/stpsource\/metadata","abstract":[{"text":"A set of key\/value pairs associated with the source object.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/metadata","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"metadata","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/hash":{"title":"hash","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/hash","abstract":[{"type":"text","text":":nodoc:"}],"url":"\/documentation\/stripepayments\/stpsource\/hash","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/type":{"title":"type","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/type","abstract":[{"text":"The type of the source.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/type","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceType","text":"STPSourceType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"type","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/clientSecret":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/clientsecret","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"clientSecret","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The client secret of the source. Used for client-side fetching of a source"},{"text":" ","type":"text"},{"text":"using a publishable key.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/clientSecret","navigatorTitle":[{"kind":"identifier","text":"clientSecret"}],"title":"clientSecret","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/redirect":{"role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/redirect","type":"topic","title":"redirect","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/redirect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"redirect","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceRedirect","text":"STPSourceRedirect"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"redirect","kind":"identifier"}],"abstract":[{"text":"Information related to the redirect flow. Present if the source’s flow","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is redirect."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/flow":{"url":"\/documentation\/stripepayments\/stpsource\/flow","role":"symbol","abstract":[{"text":"The authentication flow of the source.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"flow","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPSourceFlow","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"flow"}],"title":"flow","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/flow","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/allResponseFields":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/allresponsefields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/allResponseFields","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"title":"allResponseFields","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/klarnaDetails":{"url":"\/documentation\/stripepayments\/stpsource\/klarnadetails","role":"symbol","abstract":[{"text":"If this is a Klarna source, this property provides typed access to the","type":"text"},{"text":" ","type":"text"},{"text":"contents of the ","type":"text"},{"code":"details","type":"codeVoice"},{"type":"text","text":" dictionary."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"klarnaDetails","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceKlarnaDetails","kind":"typeIdentifier","text":"STPSourceKlarnaDetails"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"klarnaDetails","kind":"identifier"}],"title":"klarnaDetails","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/klarnaDetails","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/livemode":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/livemode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"livemode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Whether or not this source was created in livemode."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/livemode","navigatorTitle":[{"kind":"identifier","text":"livemode"}],"title":"livemode","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/weChatPayDetails":{"url":"\/documentation\/stripepayments\/stpsource\/wechatpaydetails","role":"symbol","abstract":[{"text":"If this is a WeChat Pay source, this property provides typed access to the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"contents of the "},{"code":"details","type":"codeVoice"},{"text":" dictionary.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"weChatPayDetails"},{"kind":"text","text":": "},{"text":"STPSourceWeChatPayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceWeChatPayDetails","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"weChatPayDetails"}],"title":"weChatPayDetails","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/weChatPayDetails","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/created":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/created","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"created"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"When the source was created.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/created","navigatorTitle":[{"kind":"identifier","text":"created"}],"title":"created","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/status":{"url":"\/documentation\/stripepayments\/stpsource\/status","role":"symbol","abstract":[{"text":"The status of the source.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceStatus","kind":"typeIdentifier","text":"STPSourceStatus"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"title":"status","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/status","type":"topic"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/cardDetails":{"url":"\/documentation\/stripepayments\/stpsource\/carddetails","role":"symbol","abstract":[{"text":"If this is a card source, this property provides typed access to the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"contents of the "},{"code":"details","type":"codeVoice"},{"text":" dictionary.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceCardDetails","text":"STPSourceCardDetails"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cardDetails"}],"title":"cardDetails","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/cardDetails","type":"topic"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/amount":{"url":"\/documentation\/stripepayments\/stpsource\/amount","role":"symbol","abstract":[{"text":"The amount associated with the source.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"amount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"amount"}],"title":"amount","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/amount","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/description":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"STPSource"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPSource"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPSource"}],"op":"replace"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/amount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/cardDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/details","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/flow","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/klarnaDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/livemode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/owner","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/receiver","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/redirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/sepaDebitDetails","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/stripeID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/usage","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/verification","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/weChatPayDetails"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/decodedObject(fromAPIResponse:)"],"generated":true,"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1usage\/title","op":"replace","value":"usage"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1usage\/fragments","value":[{"kind":"identifier","text":"usage"}],"op":"replace"},{"value":"details","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1details\/title","op":"replace"},{"value":[{"text":"details","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1details\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable","op":"replace"},{"op":"replace","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","op":"replace"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1decodedObject(fromAPIResponse:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1decodedObject(fromAPIResponse:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1receiver\/title","value":"receiver"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1receiver\/fragments","value":[{"text":"receiver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1verification\/title","value":"verification","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1verification\/fragments","value":[{"text":"verification","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","value":"STPSource"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSource"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","value":[{"kind":"identifier","text":"STPSource"}],"op":"replace"},{"op":"replace","value":"stripeID","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1stripeID\/title"},{"value":[{"text":"stripeID","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1stripeID\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/title","value":"STPSourceProtocol"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceProtocol"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/navigatorTitle","op":"replace","value":[{"text":"STPSourceProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1owner\/title","value":"owner","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1owner\/fragments","value":[{"text":"owner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1sepaDebitDetails\/title","value":"sepaDebitDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1sepaDebitDetails\/fragments","value":[{"text":"sepaDebitDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1currency\/title","value":"currency","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1currency\/fragments","value":[{"text":"currency","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1metadata\/title","value":"metadata"},{"value":[{"text":"metadata","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1metadata\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","value":"clientSecret","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1clientSecret\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1clientSecret\/fragments","value":[{"text":"clientSecret","kind":"identifier"}]},{"op":"replace","value":"redirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1redirect\/title"},{"op":"replace","value":[{"text":"redirect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1redirect\/fragments"},{"op":"replace","value":"flow","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1flow\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1flow\/fragments","op":"replace","value":[{"kind":"identifier","text":"flow"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1allResponseFields\/title","value":"allResponseFields","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace"},{"value":"klarnaDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1klarnaDetails\/title"},{"value":[{"kind":"identifier","text":"klarnaDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1klarnaDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1livemode\/title","value":"livemode"},{"op":"replace","value":[{"text":"livemode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1livemode\/fragments"},{"value":"weChatPayDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1weChatPayDetails\/title"},{"op":"replace","value":[{"text":"weChatPayDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1weChatPayDetails\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1created\/title","op":"replace","value":"created"},{"value":[{"text":"created","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1created\/fragments"},{"value":"status","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1status\/title"},{"op":"replace","value":[{"text":"status","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1status\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1cardDetails\/title","op":"replace","value":"cardDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1cardDetails\/fragments","op":"replace","value":[{"text":"cardDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1amount\/title","value":"amount"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1amount\/fragments","value":[{"kind":"identifier","text":"amount"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1description\/title","op":"replace","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1description\/fragments","value":[{"text":"description","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}