{"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceFlow","kind":"identifier"}],"symbolKind":"enum","title":"STPSourceFlow","role":"symbol","navigatorTitle":[{"text":"STPSourceFlow","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSourceFlow"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/codeVerification","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/none","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/receiver","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/redirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/unknown"]},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceFlow","kind":"identifier"}]}]}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceflow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceflow"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"abstract":[{"text":"Authentication flows for a Source","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/CustomStringConvertible-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","url":"\/documentation\/stripepayments\/stpsourceflow\/customstringconvertible-implementations","type":"topic","abstract":[],"kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/RawRepresentable-Implementations":{"url":"\/documentation\/stripepayments\/stpsourceflow\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/RawRepresentable-Implementations","title":"RawRepresentable Implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/init(rawValue:)":{"role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/init(rawValue:)","url":"\/documentation\/stripepayments\/stpsourceflow\/init(rawvalue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/none":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/none","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceFlowNone"}],"title":"STPSourceFlow.none","url":"\/documentation\/stripepayments\/stpsourceflow\/none","role":"symbol","abstract":[{"type":"text","text":"No action is required from your customer."}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/receiver":{"title":"STPSourceFlow.receiver","kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceflow\/receiver","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"receiver","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceFlowReceiver","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/receiver","type":"topic","abstract":[{"type":"text","text":"Your customer must push funds to the account information provided."}]},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"navigatorTitle":[{"text":"STPSourceFlow","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceFlow"}],"kind":"symbol","title":"STPSourceFlow","abstract":[{"type":"text","text":"Authentication flows for a Source"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","url":"\/documentation\/stripepayments\/stpsourceflow","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/redirect":{"url":"\/documentation\/stripepayments\/stpsourceflow\/redirect","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/redirect","kind":"symbol","abstract":[{"type":"text","text":"Your customer must be redirected to their online banking service (either a website or mobile banking app) to approve the payment."}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"redirect","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceFlowRedirect"}],"title":"STPSourceFlow.redirect","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/unknown":{"type":"topic","abstract":[{"text":"The source’s flow is unknown.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceFlowUnknown"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/unknown","title":"STPSourceFlow.unknown","url":"\/documentation\/stripepayments\/stpsourceflow\/unknown","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/codeVerification":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/codeVerification","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"codeVerification"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceFlowCodeVerification"}],"title":"STPSourceFlow.codeVerification","url":"\/documentation\/stripepayments\/stpsourceflow\/codeverification","role":"symbol","abstract":[{"text":"Your customer must verify ownership of their account by providing a code that you post to the Stripe API for authentication.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stpsourceflow\/equatable-implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","value":"STPSourceFlow","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceFlow"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceFlow"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/codeVerification","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/none","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/receiver","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/redirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow\/unknown"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceFlow"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPSourceFlowNone","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1none\/title"},{"op":"replace","value":[{"text":"STPSourceFlowNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1none\/fragments"},{"value":"STPSourceFlowReceiver","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1receiver\/title"},{"value":[{"kind":"identifier","text":"STPSourceFlowReceiver"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1receiver\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title","value":"STPSourceFlow"},{"value":[{"text":"STPSourceFlow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceFlow"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/navigatorTitle"},{"op":"replace","value":"STPSourceFlowRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1redirect\/title"},{"op":"replace","value":[{"text":"STPSourceFlowRedirect","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1redirect\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1unknown\/title","value":"STPSourceFlowUnknown","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1unknown\/fragments","op":"replace","value":[{"text":"STPSourceFlowUnknown","kind":"identifier"}]},{"value":"STPSourceFlowCodeVerification","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1codeVerification\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow~1codeVerification\/fragments","value":[{"text":"STPSourceFlowCodeVerification","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}