{"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/address","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountCharged","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountReceived","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountReturned","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/description"]},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/decodedObject(fromAPIResponse:)"],"generated":true,"title":"Type Methods"}],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceReceiver","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceReceiver"}],"navigatorTitle":[{"text":"STPSourceReceiver","kind":"identifier"}],"role":"symbol","symbolKind":"class","title":"STPSourceReceiver"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver"},"abstract":[{"type":"text","text":"Information related to a source’s receiver flow."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceReceiver","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcereceiver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcereceiver"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"type":"topic","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"title":"STPAPIResponseDecodable","abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpapiresponsedecodable"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver/amountReceived":{"title":"amountReceived","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountReceived","abstract":[{"text":"The total amount received by the receiver source.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"amountReceived"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcereceiver\/amountreceived","navigatorTitle":[{"text":"amountReceived","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver/decodedObject(fromAPIResponse:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/decodedObject(fromAPIResponse:)","role":"symbol","kind":"symbol","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"type":"text","text":") into an instance of the class."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"title":"decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stpsourcereceiver\/decodedobject(fromapiresponse:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver/amountCharged":{"title":"amountCharged","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountCharged","abstract":[{"type":"text","text":"The total amount charged by you."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"amountCharged","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcereceiver\/amountcharged","navigatorTitle":[{"text":"amountCharged","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver","type":"topic","url":"\/documentation\/stripepayments\/stpsourcereceiver","navigatorTitle":[{"text":"STPSourceReceiver","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Information related to a source’s receiver flow.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceReceiver"}],"title":"STPSourceReceiver"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver/allResponseFields":{"role":"symbol","abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"text":" ","type":"text"},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"url":"\/documentation\/stripepayments\/stpsourcereceiver\/allresponsefields","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/allResponseFields","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allResponseFields","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"type":"topic","title":"allResponseFields"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver/address":{"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcereceiver\/address","title":"address","abstract":[{"text":"The address of the receiver source. This is the value that should be communicated to the customer to send their funds to.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"address","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/address"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/description","title":"description","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourcereceiver\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver/amountReturned":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountReturned","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The total amount that was returned to the customer."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"amountReturned"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"amountReturned"}],"url":"\/documentation\/stripepayments\/stpsourcereceiver\/amountreturned","title":"amountReturned","type":"topic"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPSourceReceiver","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceReceiver","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceReceiver"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/address","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountCharged","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountReceived","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/amountReturned","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/description"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver\/decodedObject(fromAPIResponse:)"],"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"],"type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceReceiver"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"op":"replace","value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1amountReceived\/title","op":"replace","value":"amountReceived"},{"op":"replace","value":[{"kind":"identifier","text":"amountReceived"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1amountReceived\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"value":"amountCharged","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1amountCharged\/title"},{"op":"replace","value":[{"text":"amountCharged","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1amountCharged\/fragments"},{"value":"STPSourceReceiver","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver\/fragments","value":[{"kind":"identifier","text":"STPSourceReceiver"}]},{"value":[{"text":"STPSourceReceiver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1allResponseFields\/title","value":"allResponseFields","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"allResponseFields"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1allResponseFields\/fragments"},{"value":"address","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1address\/title"},{"value":[{"kind":"identifier","text":"address"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1address\/fragments","op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1description\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1amountReturned\/title","value":"amountReturned"},{"op":"replace","value":[{"kind":"identifier","text":"amountReturned"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver~1amountReturned\/fragments"}]}]}