{"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"s:14StripePayments24STPSourceCompletionBlocka","navigatorTitle":[{"text":"STPSourceCompletionBlock","kind":"identifier"}],"symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"STPSourceCompletionBlock","kind":"identifier"}],"roleHeading":"Type Alias","title":"STPSourceCompletionBlock"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCompletionBlock"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceCompletionBlock","kind":"identifier"},{"kind":"text","text":" = ("},{"text":"STPSource","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSource","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Stripe source from the response. Will be nil if an error occurs. - seealso: STPSource"}]}],"name":"source"},{"name":"error","content":[{"inlineContent":[{"text":"The error returned from the response, or nil if none occurs. - seealso: StripeError.h for possible values.","type":"text"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcecompletionblock"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"A callback to be run with a source response from the Stripe API."}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCompletionBlock":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceCompletionBlock"}],"url":"\/documentation\/stripepayments\/stpsourcecompletionblock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCompletionBlock","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceCompletionBlock"}],"kind":"symbol","title":"STPSourceCompletionBlock","type":"topic","abstract":[{"text":"A callback to be run with a source response from the Stripe API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"abstract":[{"type":"text","text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources"}],"url":"\/documentation\/stripepayments\/stpsource","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSource"}],"navigatorTitle":[{"text":"STPSource","kind":"identifier"}],"kind":"symbol","title":"STPSource"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPSource","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title"},{"value":[{"text":"STPSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","op":"replace"},{"value":[{"text":"STPSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}