{"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/reusable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/singleUse","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/unknown"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourceusage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourceusage"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceUsage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Usage types for a Source","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage"},"metadata":{"navigatorTitle":[{"text":"STPSourceUsage","kind":"identifier"}],"symbolKind":"enum","role":"symbol","title":"STPSourceUsage","externalID":"c:@M@StripePayments@E@STPSourceUsage","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceUsage","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Enumeration"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/unknown":{"title":"STPSourceUsage.unknown","navigatorTitle":[{"text":"STPSourceUsageUnknown","kind":"identifier"}],"abstract":[{"type":"text","text":"The source’s usage is unknown."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourceusage\/unknown","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/singleUse":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"singleUse","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/singleUse","url":"\/documentation\/stripepayments\/stpsourceusage\/singleuse","navigatorTitle":[{"text":"STPSourceUsageSingleUse","kind":"identifier"}],"title":"STPSourceUsage.singleUse","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The source can only be used once."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/Equatable-Implementations":{"url":"\/documentation\/stripepayments\/stpsourceusage\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/Equatable-Implementations","role":"collectionGroup","kind":"article","title":"Equatable Implementations","abstract":[]},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/reusable":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reusable","kind":"identifier"}],"title":"STPSourceUsage.reusable","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/reusable","url":"\/documentation\/stripepayments\/stpsourceusage\/reusable","type":"topic","abstract":[{"type":"text","text":"The source can be reused."}],"navigatorTitle":[{"text":"STPSourceUsageReusable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/init(rawValue:)":{"url":"\/documentation\/stripepayments\/stpsourceusage\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(rawValue:)","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceUsage","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceusage","type":"topic","navigatorTitle":[{"text":"STPSourceUsage","kind":"identifier"}],"abstract":[{"type":"text","text":"Usage types for a Source"}],"kind":"symbol","title":"STPSourceUsage","role":"symbol"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/stripepayments\/stpsourceusage\/rawrepresentable-implementations","type":"topic"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/CustomStringConvertible-Implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"CustomStringConvertible Implementations","url":"\/documentation\/stripepayments\/stpsourceusage\/customstringconvertible-implementations","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPSourceUsage","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceUsage"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceUsage"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/reusable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/singleUse","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage\/unknown"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceUsage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSourceUsageUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1unknown\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceUsageUnknown"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1unknown\/fragments","op":"replace"},{"value":"STPSourceUsageSingleUse","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1singleUse\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceUsageSingleUse"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1singleUse\/fragments","op":"replace"},{"value":"STPSourceUsageReusable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1reusable\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceUsageReusable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage~1reusable\/fragments","op":"replace"},{"value":"STPSourceUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/title","op":"replace"},{"value":[{"text":"STPSourceUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/fragments","op":"replace"},{"value":[{"text":"STPSourceUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/navigatorTitle","op":"replace"}]}]}