{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api#Create_source","type":"text"}]}],"style":"note","type":"aside","name":"See Also"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams"]},{"paths":["\/documentation\/stripepayments\/stpsourceparams"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To"}],"metadata":{"title":"STPSourceParams","externalID":"c:@M@StripePayments@objc(cs)STPSourceParams","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceParams","kind":"identifier"}],"role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Class"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/init()"],"title":"Initializers","anchor":"Initializers","generated":true},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/amount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/flow","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/owner","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/rawTypeString","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/token","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/usage"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirectDictionaryWithMerchantNameIfNecessary()"],"generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayParams(withAmount:currency:returnURL:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayReusableParams(withCurrency:returnURL:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/bancontactParams(withAmount:name:returnURL:statementDescriptor:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/cardParams(withCard:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/epsParams(withAmount:name:returnURL:statementDescriptor:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/giropayParams(withAmount:name:returnURL:statementDescriptor:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/idealParams(withAmount:name:returnURL:statementDescriptor:bank:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/masterpassParams(withCartId:transactionId:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/multibancoParams(withAmount:returnURL:email:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/p24Params(withAmount:currency:email:name:returnURL:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sofortParams(withAmount:returnURL:country:statementDescriptor:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/threeDSecureParams(withAmount:currency:returnURL:card:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/visaCheckoutParams(withCallId:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/wechatPay(withAmount:currency:appId:statementDescriptor:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/NSCopying-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/STPFormEncodable-Implementations"],"anchor":"Default-Implementations","generated":true}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/usage":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"usage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage","text":"STPSourceUsage"}],"type":"topic","navigatorTitle":[{"text":"usage","kind":"identifier"}],"title":"usage","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/usage","abstract":[{"type":"text","text":"Whether this source should be reusable or not. "},{"code":"usage","type":"codeVoice"},{"type":"text","text":" may be “reusable” or"},{"type":"text","text":" "},{"text":"“single_use”. Some source types may or may not be reusable by construction,","type":"text"},{"type":"text","text":" "},{"text":"while other may leave the option at creation.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/usage"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/giropayParams(withAmount:name:returnURL:statementDescriptor:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"giropayParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statementDescriptor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams\/giropayparams(withamount:name:returnurl:statementdescriptor:)","title":"giropayParams(withAmount:name:returnURL:statementDescriptor:)","navigatorTitle":[{"text":"giropayParamsWithAmount:name:returnURL:statementDescriptor:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/giropayParams(withAmount:name:returnURL:statementDescriptor:)","role":"symbol","abstract":[{"type":"text","text":"Creates params for a Giropay source."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/owner":{"type":"topic","title":"owner","navigatorTitle":[{"kind":"identifier","text":"owner"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams\/owner","abstract":[{"type":"text","text":"Information about the owner of the payment instrument. May be used or required"},{"type":"text","text":" "},{"type":"text","text":"by particular source types."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/owner","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"owner","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"title":"STPSourceParams","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)":{"abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"klarnaParams"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withReturnURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purchaseCountry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"STPKlarnaLineItem","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"kind":"text","text":"], "},{"text":"customPaymentMethods","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"STPKlarnaPaymentMethods","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaPaymentMethods","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","url":"\/documentation\/stripepayments\/stpsourceparams\/klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:)","title":"klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/redirectDictionaryWithMerchantNameIfNecessary()":{"role":"symbol","abstract":[{"text":"Private setter allows for setting the name of the app in the returnURL so","type":"text"},{"type":"text","text":" "},{"type":"text","text":"that it can be displayed on hooks.stripe.com if the automatic redirect back"},{"text":" ","type":"text"},{"type":"text","text":"to the app fails."},{"text":" ","type":"text"},{"type":"text","text":"We intercept the reading of redirect dictionary from STPFormEncoder and replace"},{"text":" ","type":"text"},{"type":"text","text":"the value of return_url if necessary"}],"kind":"symbol","title":"redirectDictionaryWithMerchantNameIfNecessary()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirectDictionaryWithMerchantNameIfNecessary()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"redirectDictionaryWithMerchantNameIfNecessary"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/redirectdictionarywithmerchantnameifnecessary()","type":"topic","navigatorTitle":[{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sepaDebitParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"iban","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"addressLine1","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"city"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"postalCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"country","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/sepadebitparams(withname:iban:addressline1:city:postalcode:country:)","title":"sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)","role":"symbol","abstract":[{"text":"Creates params for a SEPA Debit source.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/additionalAPIParameters":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/additionalAPIParameters","title":"additionalAPIParameters","url":"\/documentation\/stripepayments\/stpsourceparams\/additionalapiparameters","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"additionalAPIParameters"}],"abstract":[{"type":"text","text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:"},{"type":"text","text":" "},{"type":"text","text":"var cardParams = STPCardParams()"},{"type":"text","text":" "},{"text":"\/\/ add card values","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]"},{"text":" ","type":"text"},{"type":"text","text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalAPIParameters"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/NSCopying-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/NSCopying-Implementations","kind":"article","title":"NSCopying Implementations","url":"\/documentation\/stripepayments\/stpsourceparams\/nscopying-implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)":{"role":"symbol","abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"kind":"symbol","title":"objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"objc_klarnaParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withReturnURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"purchaseCountry"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"items","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"STPKlarnaLineItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"customPaymentMethods"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"billingAddress"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"billingFirstName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"billingLastName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingDOB"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth","text":"STPDateOfBirth"},{"text":"?) -> ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/objc_klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:billingaddress:billingfirstname:billinglastname:billingdob:)","type":"topic","navigatorTitle":[{"text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/bancontactParams(withAmount:name:returnURL:statementDescriptor:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/bancontactParams(withAmount:name:returnURL:statementDescriptor:)","type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams\/bancontactparams(withamount:name:returnurl:statementdescriptor:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bancontactParams"},{"kind":"text","text":"("},{"text":"withAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statementDescriptor"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"navigatorTitle":[{"text":"bancontactParamsWithAmount:name:returnURL:statementDescriptor:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Creates params for a Bancontact source.","type":"text"}],"title":"bancontactParams(withAmount:name:returnURL:statementDescriptor:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/multibancoParams(withAmount:returnURL:email:)":{"navigatorTitle":[{"kind":"identifier","text":"multibancoParamsWithAmount:returnURL:email:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/multibancoParams(withAmount:returnURL:email:)","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams\/multibancoparams(withamount:returnurl:email:)","title":"multibancoParams(withAmount:returnURL:email:)","abstract":[{"text":"Create params for a Multibanco source","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"multibancoParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"email","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/alipayReusableParams(withCurrency:returnURL:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayReusableParams(withCurrency:returnURL:)","type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams\/alipayreusableparams(withcurrency:returnurl:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alipayReusableParams"},{"text":"(","kind":"text"},{"text":"withCurrency","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"}],"navigatorTitle":[{"text":"alipayReusableParamsWithCurrency:returnURL:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates params for a reusable Alipay source"}],"title":"alipayReusableParams(withCurrency:returnURL:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/p24Params(withAmount:currency:email:name:returnURL:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"p24Params"},{"kind":"text","text":"("},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"email","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/p24params(withamount:currency:email:name:returnurl:)","navigatorTitle":[{"text":"p24ParamsWithAmount:currency:email:name:returnURL:","kind":"identifier"}],"abstract":[{"text":"Creates params for a P24 source","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/p24Params(withAmount:currency:email:name:returnURL:)","title":"p24Params(withAmount:currency:email:name:returnURL:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/cardParams(withCard:)":{"kind":"symbol","abstract":[{"text":"Creates params for a Card source.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/cardParams(withCard:)","url":"\/documentation\/stripepayments\/stpsourceparams\/cardparams(withcard:)","role":"symbol","title":"cardParams(withCard:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cardParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withCard","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCardParams","text":"STPCardParams","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"navigatorTitle":[{"text":"cardParamsWithCard:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/metadata":{"navigatorTitle":[{"kind":"identifier","text":"metadata"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/metadata","role":"symbol","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams\/metadata","title":"metadata","abstract":[{"type":"text","text":"A set of key\/value pairs that you can attach to a source object."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"metadata","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/visaCheckoutParams(withCallId:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/visaCheckoutParams(withCallId:)","abstract":[{"type":"text","text":"Creates params for a card source created from Visa Checkout."}],"role":"symbol","title":"visaCheckoutParams(withCallId:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visaCheckoutParams","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withCallId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams\/visacheckoutparams(withcallid:)","navigatorTitle":[{"text":"visaCheckoutParamsWithCallId:","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/description","type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"title":"description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/init()":{"role":"symbol","abstract":[{"type":"text","text":"Initializes an empty STPSourceParams."}],"kind":"symbol","title":"init()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/init()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/currency":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currency","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/currency","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/currency","abstract":[{"text":"The currency associated with the source. This is the currency for which the source","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"will be chargeable once ready."}],"navigatorTitle":[{"text":"currency","kind":"identifier"}],"title":"currency"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/token":{"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams\/token","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/token","navigatorTitle":[{"text":"token","kind":"identifier"}],"abstract":[{"text":"An optional token used to create the source. When passed, token properties will","type":"text"},{"type":"text","text":" "},{"text":"override source parameters.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"token"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"token"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPFormEncodable","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API."}],"title":"STPFormEncodable","url":"\/documentation\/stripepayments\/stpformencodable","role":"symbol","navigatorTitle":[{"text":"STPFormEncodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/amount":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/amount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"title":"amount","abstract":[{"type":"text","text":"A positive integer in the smallest currency unit representing the"},{"text":" ","type":"text"},{"type":"text","text":"amount to charge the customer (e.g., @1099 for a €10.99 payment)."},{"text":" ","type":"text"},{"text":"Required for ","type":"text"},{"code":"single_use","type":"codeVoice"},{"type":"text","text":" sources."}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams\/amount","navigatorTitle":[{"text":"amount","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/flow":{"abstract":[{"type":"text","text":"The authentication flow of the source to create. "},{"type":"codeVoice","code":"flow"},{"text":" may be “redirect”,","type":"text"},{"type":"text","text":" "},{"text":"“receiver”, “verification”, or “none”. It is generally inferred unless a type","type":"text"},{"type":"text","text":" "},{"type":"text","text":"supports multiple flows."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow","kind":"typeIdentifier","text":"STPSourceFlow"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/flow","navigatorTitle":[{"kind":"identifier","text":"flow"}],"type":"topic","title":"flow","url":"\/documentation\/stripepayments\/stpsourceparams\/flow","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/STPFormEncodable-Implementations":{"abstract":[],"url":"\/documentation\/stripepayments\/stpsourceparams\/stpformencodable-implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/STPFormEncodable-Implementations","title":"STPFormEncodable Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/type":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"STPSourceType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceType"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourceparams\/type","abstract":[{"type":"text","text":"The type of the source to create. Required."}],"title":"type","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/type"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/rawTypeString":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/rawTypeString","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawTypeString"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"rawTypeString","kind":"identifier"}],"type":"topic","title":"rawTypeString","url":"\/documentation\/stripepayments\/stpsourceparams\/rawtypestring","abstract":[{"type":"text","text":"The raw underlying type string sent to the server."},{"type":"text","text":" "},{"text":"Generally you should use ","type":"text"},{"type":"codeVoice","code":"type"},{"type":"text","text":" instead unless you have a reason not to."},{"type":"text","text":" "},{"text":"You can use this if you want to create a param of a type not yet supported","type":"text"},{"type":"text","text":" "},{"type":"text","text":"by the current version of the SDK’s "},{"type":"codeVoice","code":"STPSourceType"},{"text":" enum.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Setting this to a value not known by the SDK causes "},{"type":"codeVoice","code":"type"},{"text":" to","type":"text"},{"type":"text","text":" "},{"text":"return ","type":"text"},{"type":"codeVoice","code":"STPSourceTypeUnknown"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/alipayParams(withAmount:currency:returnURL:)":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipayParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/alipayparams(withamount:currency:returnurl:)","navigatorTitle":[{"text":"alipayParamsWithAmount:currency:returnURL:","kind":"identifier"}],"abstract":[{"text":"Creates params for a single-use Alipay source","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayParams(withAmount:currency:returnURL:)","title":"alipayParams(withAmount:currency:returnURL:)","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/masterpassParams(withCartId:transactionId:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/masterpassParams(withCartId:transactionId:)","title":"masterpassParams(withCartId:transactionId:)","url":"\/documentation\/stripepayments\/stpsourceparams\/masterpassparams(withcartid:transactionid:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"masterpassParamsWithCartId:transactionId:","kind":"identifier"}],"abstract":[{"text":"Creates params for a card source created from Masterpass.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"masterpassParams"},{"kind":"text","text":"("},{"text":"withCartId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transactionId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}]},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)":{"abstract":[{"type":"text","text":"Creates params for a Klarna source."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"objc_klarnaParams"},{"kind":"text","text":"("},{"text":"withReturnURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"purchaseCountry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"items"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem","text":"STPKlarnaLineItem","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"customPaymentMethods"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","title":"objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","role":"symbol","url":"\/documentation\/stripepayments\/stpsourceparams\/objc_klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:)","navigatorTitle":[{"text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)":{"role":"symbol","abstract":[{"text":"Creates params for a Klarna source.","type":"text"}],"kind":"symbol","title":"klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"klarnaParams"},{"text":"(","kind":"text"},{"text":"withReturnURL","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"currency","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"purchaseCountry"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"items","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"STPKlarnaLineItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPKlarnaLineItem"},{"kind":"text","text":"], "},{"text":"customPaymentMethods","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"STPKlarnaPaymentMethods","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPKlarnaPaymentMethods"},{"text":"], ","kind":"text"},{"text":"billingAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"billingFirstName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"billingLastName","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"billingDOB","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPDateOfBirth","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPDateOfBirth"},{"kind":"text","text":"?) -> "},{"text":"STPSourceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/klarnaparams(withreturnurl:currency:purchasecountry:items:custompaymentmethods:billingaddress:billingfirstname:billinglastname:billingdob:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/redirect":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirect","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"redirect"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"redirect"}],"type":"topic","title":"redirect","url":"\/documentation\/stripepayments\/stpsourceparams\/redirect","abstract":[{"text":"Parameters required for the redirect flow. Required if the source is","type":"text"},{"type":"text","text":" "},{"type":"text","text":"authenticated by a redirect ("},{"code":"flow","type":"codeVoice"},{"type":"text","text":" is “redirect”)."}]},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/wechatPay(withAmount:currency:appId:statementDescriptor:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/wechatPay(withAmount:currency:appId:statementDescriptor:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wechatPay"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currency"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"statementDescriptor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}],"role":"symbol","navigatorTitle":[{"text":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:","kind":"identifier"}],"type":"topic","title":"wechatPay(withAmount:currency:appId:statementDescriptor:)","url":"\/documentation\/stripepayments\/stpsourceparams\/wechatpay(withamount:currency:appid:statementdescriptor:)","abstract":[{"type":"text","text":"Create params for a WeChat Pay native app redirect source"}]},"doc://com.stripe.stripe-payments/objc(pl)NSCopying":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","type":"unresolvable","title":"NSCopying"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/threeDSecureParams(withAmount:currency:returnURL:card:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threeDSecureParams"},{"kind":"text","text":"("},{"text":"withAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"returnURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"card","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","text":"STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/threedsecureparams(withamount:currency:returnurl:card:)","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/threeDSecureParams(withAmount:currency:returnURL:card:)","title":"threeDSecureParams(withAmount:currency:returnURL:card:)","abstract":[{"text":"Creates params for a 3DS source.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"threeDSecureParamsWithAmount:currency:returnURL:card:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/epsParams(withAmount:name:returnURL:statementDescriptor:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/epsParams(withAmount:name:returnURL:statementDescriptor:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"epsParams","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withAmount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"statementDescriptor"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams"}],"role":"symbol","navigatorTitle":[{"text":"epsParamsWithAmount:name:returnURL:statementDescriptor:","kind":"identifier"}],"type":"topic","title":"epsParams(withAmount:name:returnURL:statementDescriptor:)","url":"\/documentation\/stripepayments\/stpsourceparams\/epsparams(withamount:name:returnurl:statementdescriptor:)","abstract":[{"type":"text","text":"Create params for an EPS source"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/sofortParams(withAmount:returnURL:country:statementDescriptor:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sofortParams","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAmount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"returnURL","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"country","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"statementDescriptor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier","text":"STPSourceParams"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/sofortparams(withamount:returnurl:country:statementdescriptor:)","type":"topic","title":"sofortParams(withAmount:returnURL:country:statementDescriptor:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sofortParams(withAmount:returnURL:country:statementDescriptor:)","kind":"symbol","abstract":[{"type":"text","text":"Creates params for a Sofort source."}],"navigatorTitle":[{"kind":"identifier","text":"sofortParamsWithAmount:returnURL:country:statementDescriptor:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/idealParams(withAmount:name:returnURL:statementDescriptor:bank:)":{"title":"idealParams(withAmount:name:returnURL:statementDescriptor:bank:)","url":"\/documentation\/stripepayments\/stpsourceparams\/idealparams(withamount:name:returnurl:statementdescriptor:bank:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/idealParams(withAmount:name:returnURL:statementDescriptor:bank:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"idealParams","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAmount"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"returnURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"statementDescriptor","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"bank","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"text":"STPSourceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceParams","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Creates params for an iDEAL source."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceParams"}],"op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/amount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/flow","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/metadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/owner","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/rawTypeString","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirect","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/token","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/type","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/usage"]},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirectDictionaryWithMerchantNameIfNecessary()"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayParams(withAmount:currency:returnURL:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/alipayReusableParams(withCurrency:returnURL:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/bancontactParams(withAmount:name:returnURL:statementDescriptor:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/cardParams(withCard:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/epsParams(withAmount:name:returnURL:statementDescriptor:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/giropayParams(withAmount:name:returnURL:statementDescriptor:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/idealParams(withAmount:name:returnURL:statementDescriptor:bank:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/masterpassParams(withCartId:transactionId:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/multibancoParams(withAmount:returnURL:email:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/p24Params(withAmount:currency:email:name:returnURL:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/sofortParams(withAmount:returnURL:country:statementDescriptor:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/threeDSecureParams(withAmount:currency:returnURL:card:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/visaCheckoutParams(withCallId:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/wechatPay(withAmount:currency:appId:statementDescriptor:)"],"title":"Type Methods","anchor":"Type-Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/NSCopying-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/STPFormEncodable-Implementations"],"anchor":"Default-Implementations","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceParams"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1usage\/title","value":"usage"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1usage\/fragments","op":"replace","value":[{"kind":"identifier","text":"usage"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1giropayParams(withAmount:name:returnURL:statementDescriptor:)\/title","op":"replace","value":"giropayParamsWithAmount:name:returnURL:statementDescriptor:"},{"value":[{"text":"+ ","kind":"text"},{"text":"giropayParamsWithAmount:name:returnURL:statementDescriptor:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1giropayParams(withAmount:name:returnURL:statementDescriptor:)\/fragments"},{"value":"owner","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1owner\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1owner\/fragments","value":[{"kind":"identifier","text":"owner"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","value":[{"kind":"identifier","text":"STPSourceParams"}]},{"value":[{"text":"STPSourceParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1redirectDictionaryWithMerchantNameIfNecessary()\/title","value":"redirectDictionaryWithMerchantNameIfNecessary"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1redirectDictionaryWithMerchantNameIfNecessary()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"}]},{"op":"replace","value":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1sepaDebitParams(withName:iban:addressLine1:city:postalCode:country:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sepaDebitParamsWithName:iban:addressLine1:city:postalCode:country:","kind":"identifier"}]},{"op":"replace","value":"additionalAPIParameters","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1additionalAPIParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1additionalAPIParameters\/fragments","value":[{"kind":"identifier","text":"additionalAPIParameters"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)\/title","value":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:billingAddress:billingFirstName:billingLastName:billingDOB:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1bancontactParams(withAmount:name:returnURL:statementDescriptor:)\/title","value":"bancontactParamsWithAmount:name:returnURL:statementDescriptor:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"bancontactParamsWithAmount:name:returnURL:statementDescriptor:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1bancontactParams(withAmount:name:returnURL:statementDescriptor:)\/fragments"},{"value":"multibancoParamsWithAmount:returnURL:email:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1multibancoParams(withAmount:returnURL:email:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1multibancoParams(withAmount:returnURL:email:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"multibancoParamsWithAmount:returnURL:email:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1alipayReusableParams(withCurrency:returnURL:)\/title","value":"alipayReusableParamsWithCurrency:returnURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1alipayReusableParams(withCurrency:returnURL:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"alipayReusableParamsWithCurrency:returnURL:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1p24Params(withAmount:currency:email:name:returnURL:)\/title","op":"replace","value":"p24ParamsWithAmount:currency:email:name:returnURL:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1p24Params(withAmount:currency:email:name:returnURL:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"p24ParamsWithAmount:currency:email:name:returnURL:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1cardParams(withCard:)\/title","op":"replace","value":"cardParamsWithCard:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1cardParams(withCard:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"cardParamsWithCard:","kind":"identifier"}]},{"value":"metadata","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1metadata\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1metadata\/fragments","value":[{"text":"metadata","kind":"identifier"}]},{"op":"replace","value":"visaCheckoutParamsWithCallId:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1visaCheckoutParams(withCallId:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1visaCheckoutParams(withCallId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"visaCheckoutParamsWithCallId:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"value":"init","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1init()\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1init()\/fragments"},{"op":"replace","value":"currency","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1currency\/title"},{"value":[{"text":"currency","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1currency\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1token\/title","op":"replace","value":"token"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1token\/fragments","value":[{"text":"token","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPFormEncodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title"},{"op":"replace","value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments"},{"value":[{"text":"STPFormEncodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1amount\/title","value":"amount"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1amount\/fragments","value":[{"text":"amount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1flow\/title","value":"flow"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1flow\/fragments","op":"replace","value":[{"kind":"identifier","text":"flow"}]},{"value":"type","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1type\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"value":"rawTypeString","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1rawTypeString\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1rawTypeString\/fragments","value":[{"kind":"identifier","text":"rawTypeString"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1alipayParams(withAmount:currency:returnURL:)\/title","value":"alipayParamsWithAmount:currency:returnURL:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1alipayParams(withAmount:currency:returnURL:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"alipayParamsWithAmount:currency:returnURL:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1masterpassParams(withCartId:transactionId:)\/title","value":"masterpassParamsWithCartId:transactionId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1masterpassParams(withCartId:transactionId:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"masterpassParamsWithCartId:transactionId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)\/title","value":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1objc_klarnaParams(withReturnURL:currency:purchaseCountry:items:customPaymentMethods:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"klarnaParamsWithReturnURL:currency:purchaseCountry:items:customPaymentMethods:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1redirect\/title","value":"redirect","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1redirect\/fragments","value":[{"kind":"identifier","text":"redirect"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1wechatPay(withAmount:currency:appId:statementDescriptor:)\/title","value":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1wechatPay(withAmount:currency:appId:statementDescriptor:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"wechatPayParamsWithAmount:currency:appId:statementDescriptor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1threeDSecureParams(withAmount:currency:returnURL:card:)\/title","value":"threeDSecureParamsWithAmount:currency:returnURL:card:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"threeDSecureParamsWithAmount:currency:returnURL:card:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1threeDSecureParams(withAmount:currency:returnURL:card:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1epsParams(withAmount:name:returnURL:statementDescriptor:)\/title","value":"epsParamsWithAmount:name:returnURL:statementDescriptor:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1epsParams(withAmount:name:returnURL:statementDescriptor:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"epsParamsWithAmount:name:returnURL:statementDescriptor:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1sofortParams(withAmount:returnURL:country:statementDescriptor:)\/title","op":"replace","value":"sofortParamsWithAmount:returnURL:country:statementDescriptor:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1sofortParams(withAmount:returnURL:country:statementDescriptor:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sofortParamsWithAmount:returnURL:country:statementDescriptor:"}]},{"value":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1idealParams(withAmount:name:returnURL:statementDescriptor:bank:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"idealParamsWithAmount:name:returnURL:statementDescriptor:bank:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1idealParams(withAmount:name:returnURL:statementDescriptor:bank:)\/fragments"}]}]}