{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"title":"STPSetupIntentConfirmParams","modules":[{"name":"StripePayments"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPSetupIntentConfirmParams"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters to confirm a SetupIntent object."},{"type":"text","text":" "},{"type":"text","text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app."},{"type":"text","text":" "},{"type":"text","text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusSucceeded"},{"type":"text","text":".  Otherwise, it will transition to "},{"type":"codeVoice","code":"STPSetupIntentStatusRequiresAction"},{"type":"text","text":", and suggest additional actions via "},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Instead of passing this to "},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"type":"text","text":" directly, we recommend using "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" to handle any additional steps for you."}],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/init(clientSecret:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/init(clientSecret:paymentMethodType:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/mandateData","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/returnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK-5rght","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK_objc"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/copy(with:)"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/rootObjectName()"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsetupintentconfirmparams"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api\/Setup_intents\/Confirm","type":"text"}],"type":"paragraph"}],"style":"note","type":"aside","name":"See Also"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/setAsDefaultPM":{"abstract":[{"text":"@YES","type":"text"},{"text":" to set this PaymentIntent’s PaymentMethod as the associated Customer’s default","type":"text"},{"text":" ","type":"text"},{"text":"This should be a boolean NSNumber, so that it can be ","type":"text"},{"text":"nil","type":"text"}],"title":"setAsDefaultPM","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/setAsDefaultPM","role":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/setasdefaultpm","kind":"symbol","type":"topic","fragments":[{"text":"setAsDefaultPM","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/init(clientSecret:paymentMethodType:)":{"role":"symbol","kind":"symbol","title":"init(clientSecret:paymentMethodType:)","type":"topic","abstract":[{"type":"text","text":"Initialize this "},{"code":"STPSetupIntentConfirmParams","type":"codeVoice"},{"type":"text","text":" with a "},{"code":"clientSecret","type":"codeVoice"},{"type":"text","text":" and "},{"code":"paymentMethodType","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Use this initializer for SetupIntents that already have a PaymentMethod attached."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/init(clientSecret:paymentMethodType:)","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/init(clientsecret:paymentmethodtype:)","navigatorTitle":[{"text":"initWithClientSecret:paymentMethodType:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"paymentMethodType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodType","text":"STPPaymentMethodType","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/mandateData":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/mandateData","title":"mandateData","abstract":[{"type":"text","text":"Details about the Mandate to create."}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mandateData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPMandateDataParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateDataParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mandateData","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/mandatedata"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/clientAttributionMetadata":{"abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"title":"clientAttributionMetadata","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/clientattributionmetadata","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"clientAttributionMetadata"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/clientAttributionMetadata"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFormEncodable":{"abstract":[{"text":"Objects conforming to STPFormEncodable can be automatically converted to a form-encoded string, which can then be used when making requests to the Stripe API.","type":"text"}],"title":"STPFormEncodable","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFormEncodable"}],"url":"\/documentation\/stripepayments\/stpformencodable","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFormEncodable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/clientSecret":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clientSecret","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/clientsecret","title":"clientSecret","kind":"symbol","abstract":[{"text":"The client secret of the SetupIntent. Required.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/clientSecret","navigatorTitle":[{"text":"clientSecret","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/additionalAPIParameters":{"type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/additionalapiparameters","title":"additionalAPIParameters","navigatorTitle":[{"text":"additionalAPIParameters","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"You can use this property to add additional fields to an API request that are not explicitly defined by the object’s interface. This can be useful when using beta features that haven’t been added to the Stripe SDK yet. For example, if the \/v1\/tokens API began to accept a beta field called “test_field”, you might do the following:","type":"text"},{"text":" ","type":"text"},{"text":"var cardParams = STPCardParams()","type":"text"},{"text":" ","type":"text"},{"text":"\/\/ add card values","type":"text"},{"text":" ","type":"text"},{"text":"cardParams.additionalAPIParameters = [“test_field”: “example_value”]","type":"text"},{"text":" ","type":"text"},{"text":"STPAPIClient.shared.createToken(withParameters: cardParams completion:…);","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/additionalAPIParameters","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"additionalAPIParameters","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/paymentMethodID":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"text":"Provide an already created PaymentMethod’s id, and it will be used to confirm the SetupIntent.","type":"text"}],"title":"paymentMethodID","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/paymentmethodid","navigatorTitle":[{"text":"paymentMethodID","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodID","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/returnURL":{"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/returnurl","title":"returnURL","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"returnURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"returnURL","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/returnURL","role":"symbol","abstract":[{"text":"The URL to redirect your customer back to after they authenticate or cancel","type":"text"},{"text":" ","type":"text"},{"text":"their payment on the payment method’s app or site.","type":"text"},{"text":" ","type":"text"},{"text":"This should probably be a URL that opens your iOS app.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/radarOptions":{"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/radaroptions","fragments":[{"kind":"identifier","text":"radarOptions"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/radarOptions","title":"radarOptions","type":"topic","abstract":[{"type":"text","text":"Radar options that may contain HCaptcha token"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/useStripeSDK_objc":{"navigatorTitle":[{"text":"useStripeSDK","kind":"identifier"}],"deprecated":true,"title":"useStripeSDK_objc","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/usestripesdk_objc","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK_objc","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useStripeSDK_objc","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any SetupIntent next actions.","type":"text"},{"text":" ","type":"text"},{"text":"If set to false, STPSetupIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser.","type":"text"},{"text":" ","type":"text"},{"text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your","type":"text"},{"text":" ","type":"text"},{"text":"app.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/description","kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/description","type":"topic","role":"symbol","title":"description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/useStripeSDK-5rght":{"type":"topic","title":"useStripeSDK","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/usestripesdk-5rght","abstract":[{"text":"A boolean number to indicate whether you intend to use the Stripe SDK’s functionality to handle any SetupIntent next actions.","type":"text"},{"text":" ","type":"text"},{"text":"If set to false, STPSetupIntent.nextAction will only ever contain a redirect url that can be opened in a webview or mobile browser.","type":"text"},{"text":" ","type":"text"},{"text":"When set to true, the nextAction may contain information that the Stripe SDK can use to perform native authentication within your","type":"text"},{"text":" ","type":"text"},{"text":"app.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK-5rght","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useStripeSDK"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/objc(pl)NSCopying":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","title":"NSCopying","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/rootObjectName()":{"navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/rootobjectname()","role":"symbol","abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"text":" below.","type":"text"}],"type":"topic","kind":"symbol","title":"rootObjectName()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/rootObjectName()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/copy(with:)":{"title":"copy(with:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/copy(with:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyWithZone:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10ObjectiveC6NSZoneV","text":"NSZone"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"}],"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/copy(with:)","abstract":[{"type":"text","text":":nodoc:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/paymentMethodParams":{"navigatorTitle":[{"text":"paymentMethodParams","kind":"identifier"}],"abstract":[{"text":"Provide a supported ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"text":" object, and Stripe will create a","type":"text"},{"text":" ","type":"text"},{"text":"PaymentMethod during PaymentIntent confirmation.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodParams","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/paymentmethodparams","title":"paymentMethodParams","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentMethodParams","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/confirmationToken":{"fragments":[{"kind":"identifier","text":"confirmationToken"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/confirmationToken","kind":"symbol","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/confirmationtoken","title":"confirmationToken","role":"symbol","type":"topic","abstract":[{"type":"text","text":"ID of an existing ConfirmationToken to use for this SetupIntent confirmation."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams":{"navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"abstract":[{"text":"An object representing parameters to confirm a SetupIntent object.","type":"text"},{"text":" ","type":"text"},{"text":"For example, you would confirm a SetupIntent when a customer hits the “Save” button on a payment method management view in your app.","type":"text"},{"text":" ","type":"text"},{"text":"If the selected payment method does not require any additional steps from the customer, the SetupIntent’s status will transition to ","type":"text"},{"code":"STPSetupIntentStatusSucceeded","type":"codeVoice"},{"text":".  Otherwise, it will transition to ","type":"text"},{"code":"STPSetupIntentStatusRequiresAction","type":"codeVoice"},{"text":", and suggest additional actions via ","type":"text"},{"type":"codeVoice","code":"nextAction"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Instead of passing this to ","type":"text"},{"type":"codeVoice","code":"STPAPIClient.confirmSetupIntent(...)"},{"text":" directly, we recommend using ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" to handle any additional steps for you.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"title":"STPSetupIntentConfirmParams","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/propertyNamesToFormFieldNamesMapping()":{"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/propertynamestoformfieldnamesmapping()","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"code":"expMonth","type":"codeVoice"},{"text":", but the Stripe API expects a field called ","type":"text"},{"code":"exp_month","type":"codeVoice"},{"text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/propertyNamesToFormFieldNamesMapping()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"propertyNamesToFormFieldNamesMapping()","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentConfirmParams/init(clientSecret:)":{"url":"\/documentation\/stripepayments\/stpsetupintentconfirmparams\/init(clientsecret:)","navigatorTitle":[{"text":"initWithClientSecret:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Initialize this ","type":"text"},{"code":"STPSetupIntentConfirmParams","type":"codeVoice"},{"text":" with a ","type":"text"},{"code":"clientSecret","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/init(clientSecret:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"clientSecret","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(clientSecret:)","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPSetupIntentConfirmParams"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPSetupIntentConfirmParams","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/additionalAPIParameters","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/clientAttributionMetadata","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/confirmationToken","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/mandateData","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/paymentMethodParams","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/radarOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/returnURL","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/setAsDefaultPM","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/useStripeSDK_objc"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/copy(with:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/init(clientSecret:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/init(clientSecret:paymentMethodType:)"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentConfirmParams\/rootObjectName()"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSCopying","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFormEncodable"],"type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSetupIntentConfirmParams","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1init(clientSecret:paymentMethodType:)\/title","value":"initWithClientSecret:paymentMethodType:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1init(clientSecret:paymentMethodType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithClientSecret:paymentMethodType:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1mandateData\/title","value":"mandateData","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1mandateData\/fragments","value":[{"text":"mandateData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/title","value":"STPFormEncodable","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/fragments","value":[{"kind":"identifier","text":"STPFormEncodable"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFormEncodable\/navigatorTitle","value":[{"text":"STPFormEncodable","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1clientSecret\/title","value":"clientSecret","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1clientSecret\/fragments","value":[{"kind":"identifier","text":"clientSecret"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1additionalAPIParameters\/title","value":"additionalAPIParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1additionalAPIParameters\/fragments","value":[{"text":"additionalAPIParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1paymentMethodID\/title","value":"paymentMethodID","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1paymentMethodID\/fragments","value":[{"text":"paymentMethodID","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1returnURL\/title","value":"returnURL","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1returnURL\/fragments","value":[{"text":"returnURL","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1useStripeSDK_objc\/title","value":"useStripeSDK","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1useStripeSDK_objc\/fragments","value":[{"kind":"identifier","text":"useStripeSDK"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1rootObjectName()\/title","value":"rootObjectName","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1rootObjectName()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1copy(with:)\/title","value":"copyWithZone:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1copy(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"copyWithZone:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1paymentMethodParams\/title","value":"paymentMethodParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1paymentMethodParams\/fragments","value":[{"kind":"identifier","text":"paymentMethodParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/title","value":"STPSetupIntentConfirmParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/fragments","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntentConfirmParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1propertyNamesToFormFieldNamesMapping()\/title","value":"propertyNamesToFormFieldNamesMapping","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1init(clientSecret:)\/title","value":"initWithClientSecret:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentConfirmParams~1init(clientSecret:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithClientSecret:","kind":"identifier"}],"op":"replace"}]}]}