{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPThreeDSButtonCustomization","kind":"identifier"}]}]}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/init(backgroundColor:cornerRadius:)"]},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/backgroundColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/cornerRadius","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/font","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/textColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/titleStyle"],"anchor":"Instance-Properties"},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/defaultSettings(for:)"],"title":"Type Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"symbolKind":"class","title":"STPThreeDSButtonCustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","roleHeading":"Class"},"sections":[],"abstract":[{"text":"A customization object to use to configure the UI of a button.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"kind":"relationships"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/init(backgroundColor:cornerRadius:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"backgroundColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/init(backgroundColor:cornerRadius:)","role":"symbol","abstract":[{"text":"Initializes an instance of STDSButtonCustomization with the given backgroundColor and colorRadius.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/init(backgroundcolor:cornerradius:)","navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:cornerRadius:"}],"title":"init(backgroundColor:cornerRadius:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/backgroundColor":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/backgroundColor","type":"topic","abstract":[{"type":"text","text":"The background color of the button."},{"text":" ","type":"text"},{"text":"The default for .resend and .cancel is clear.","type":"text"},{"text":" ","type":"text"},{"text":"The default for .submit, .continue, and .next is blue.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/backgroundcolor","title":"backgroundColor","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/defaultSettings(for:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"STPThreeDSCustomizationButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType"},{"text":") -> ","kind":"text"},{"text":"STPThreeDSButtonCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","kind":"typeIdentifier"}],"title":"defaultSettings(for:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/defaultSettings(for:)","abstract":[{"type":"text","text":"The default settings for the provided button type."}],"navigatorTitle":[{"kind":"identifier","text":"defaultSettingsForButtonType:"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/defaultsettings(for:)","kind":"symbol","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/textColor":{"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/textcolor","abstract":[{"type":"text","text":"The text color of the title."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textColor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","title":"textColor","navigatorTitle":[{"kind":"identifier","text":"textColor"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/textColor","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/cornerRadius":{"abstract":[{"text":"The corner radius of the button. Defaults to 8.","type":"text"}],"title":"cornerRadius","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cornerRadius","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/cornerradius","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/cornerRadius","kind":"symbol"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/titleStyle":{"role":"symbol","title":"titleStyle","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/titleStyle","url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/titlestyle","abstract":[{"text":"The capitalization style of the button title.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"titleStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle","text":"STPThreeDSButtonTitleStyle","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"titleStyle","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/font":{"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/font","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/font","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"font"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"text":"?","kind":"text"}],"abstract":[{"text":"The font of the title.","type":"text"}],"navigatorTitle":[{"text":"font","kind":"identifier"}],"title":"font"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization":{"title":"STPThreeDSButtonCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"abstract":[{"text":"A customization object to use to configure the UI of a button.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization","kind":"symbol","navigatorTitle":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPThreeDSButtonCustomization"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}]},{"value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/backgroundColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/cornerRadius","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/font","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/textColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/titleStyle"]},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/init(backgroundColor:cornerRadius:)"],"anchor":"Instance-Methods"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/defaultSettings(for:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"STPThreeDSButtonCustomization","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1init(backgroundColor:cornerRadius:)\/title","op":"replace","value":"initWithBackgroundColor:cornerRadius:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1init(backgroundColor:cornerRadius:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithBackgroundColor:cornerRadius:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"backgroundColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1backgroundColor\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1backgroundColor\/fragments","value":[{"text":"backgroundColor","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1defaultSettings(for:)\/title","op":"replace","value":"defaultSettingsForButtonType:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1defaultSettings(for:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"defaultSettingsForButtonType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1textColor\/title","value":"textColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1textColor\/fragments","value":[{"kind":"identifier","text":"textColor"}],"op":"replace"},{"value":"cornerRadius","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1cornerRadius\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cornerRadius"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1cornerRadius\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1titleStyle\/title","value":"titleStyle","op":"replace"},{"value":[{"text":"titleStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1titleStyle\/fragments"},{"value":"font","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1font\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1font\/fragments","value":[{"kind":"identifier","text":"font"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/title","value":"STPThreeDSButtonCustomization","op":"replace"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/fragments","op":"replace"},{"op":"replace","value":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/navigatorTitle"}]}]}
