{"abstract":[{"text":"A callback to be run with a token response from the Stripe API.","type":"text"}],"metadata":{"roleHeading":"Type Alias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTokenCompletionBlock","kind":"identifier"}],"externalID":"s:14StripePayments23STPTokenCompletionBlocka","navigatorTitle":[{"kind":"identifier","text":"STPTokenCompletionBlock"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"typealias","title":"STPTokenCompletionBlock"},"variants":[{"paths":["\/documentation\/stripepayments\/stptokencompletionblock"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTokenCompletionBlock"},{"text":" = (","kind":"text"},{"text":"STPToken","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPToken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}]}]},{"parameters":[{"name":"token","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Stripe token from the response. Will be nil if an error occurs. - seealso: STPToken"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error returned from the response, or nil if none occurs. - seealso: StripeError.h for possible values."}]}]}],"kind":"parameters"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenCompletionBlock":{"url":"\/documentation\/stripepayments\/stptokencompletionblock","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenCompletionBlock","navigatorTitle":[{"text":"STPTokenCompletionBlock","kind":"identifier"}],"title":"STPTokenCompletionBlock","abstract":[{"type":"text","text":"A callback to be run with a token response from the Stripe API."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPTokenCompletionBlock"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","title":"STPToken","abstract":[{"type":"text","text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly."}],"kind":"symbol","navigatorTitle":[{"text":"STPToken","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stptoken","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPToken","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title","op":"replace","value":"STPToken"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","value":[{"kind":"identifier","text":"STPToken"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle","value":[{"kind":"identifier","text":"STPToken"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}