{"abstract":[{"text":"An enumeration of the case transformations that can be applied to the button’s title","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/default","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/lowercase","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/sentenceCapitalized","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/uppercase"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttontitlestyle"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"roleHeading":"Enumeration","externalID":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle","title":"STPThreeDSButtonTitleStyle","symbolKind":"enum","modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/uppercase":{"navigatorTitle":[{"text":"STPThreeDSButtonTitleStyleUppercase","kind":"identifier"}],"title":"STPThreeDSButtonTitleStyle.uppercase","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"uppercase","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/uppercase","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/uppercase","type":"topic","role":"symbol","abstract":[{"text":"Applies localizedUppercaseString to the title","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/sentenceCapitalized":{"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/sentencecapitalized","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleSentenceCapitalized"}],"kind":"symbol","title":"STPThreeDSButtonTitleStyle.sentenceCapitalized","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/sentenceCapitalized","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Applies localizedCapitalizedString to the title"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sentenceCapitalized"}]},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/RawRepresentable-Implementations","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://com.stripe.stripe-payments/SY":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/default":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"`default`"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/default","type":"topic","abstract":[{"text":"Default style, doesn’t modify the title","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/default","title":"STPThreeDSButtonTitleStyle.default","navigatorTitle":[{"text":"STPThreeDSButtonTitleStyleDefault","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/init(rawValue:)","abstract":[],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/CustomStringConvertible-Implementations":{"title":"CustomStringConvertible Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/customstringconvertible-implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle":{"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle","title":"STPThreeDSButtonTitleStyle","kind":"symbol","abstract":[{"text":"An enumeration of the case transformations that can be applied to the button’s title","type":"text"}],"navigatorTitle":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/lowercase":{"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/lowercase","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleLowercase"}],"role":"symbol","title":"STPThreeDSButtonTitleStyle.lowercase","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/lowercase","kind":"symbol","abstract":[{"text":"Applies localizedLowercaseString to the title","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lowercase"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/Equatable-Implementations","url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle\/equatable-implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"STPThreeDSButtonTitleStyle","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/default","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/lowercase","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/sentenceCapitalized","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle\/uppercase"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1uppercase\/title","value":"STPThreeDSButtonTitleStyleUppercase"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1uppercase\/fragments","value":[{"text":"STPThreeDSButtonTitleStyleUppercase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1sentenceCapitalized\/title","op":"replace","value":"STPThreeDSButtonTitleStyleSentenceCapitalized"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1sentenceCapitalized\/fragments","op":"replace","value":[{"text":"STPThreeDSButtonTitleStyleSentenceCapitalized","kind":"identifier"}]},{"value":"STPThreeDSButtonTitleStyleDefault","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1default\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1default\/fragments","value":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyleDefault"}],"op":"replace"},{"value":"STPThreeDSButtonTitleStyle","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/title"},{"value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/fragments"},{"value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1lowercase\/title","value":"STPThreeDSButtonTitleStyleLowercase","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle~1lowercase\/fragments","value":[{"text":"STPThreeDSButtonTitleStyleLowercase","kind":"identifier"}],"op":"replace"}]}]}