{"kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the different types of buttons that are able to be customized."}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/cancel","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/continue","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/next","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/resend","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/submit"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationbuttontype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"enum","title":"STPThreeDSCustomizationButtonType","navigatorTitle":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"},"references":{"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/resend":{"url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/resend","navigatorTitle":[{"text":"STPThreeDSCustomizationButtonTypeResend","kind":"identifier"}],"kind":"symbol","title":"STPThreeDSCustomizationButtonType.resend","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/resend","abstract":[{"type":"text","text":"The resend button type."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resend"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/init(rawValue:)","kind":"symbol","type":"topic","role":"symbol","title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/continue":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/continue","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/continue","kind":"symbol","title":"STPThreeDSCustomizationButtonType.continue","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeContinue"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"`continue`","kind":"identifier"}],"abstract":[{"text":"The continue button type.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"abstract":[{"text":"An enum that defines the different types of buttons that are able to be customized.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","navigatorTitle":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","kind":"symbol","type":"topic","title":"STPThreeDSCustomizationButtonType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/next":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"next","kind":"identifier"}],"title":"STPThreeDSCustomizationButtonType.next","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/next","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/next","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeNext"}],"type":"topic","abstract":[{"type":"text","text":"The next button type."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","title":"Swift.RawRepresentable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/CustomStringConvertible-Implementations","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/customstringconvertible-implementations","abstract":[],"type":"topic","role":"collectionGroup","title":"CustomStringConvertible Implementations","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/cancel":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancel"}],"title":"STPThreeDSCustomizationButtonType.cancel","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/cancel","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/cancel","navigatorTitle":[{"text":"STPThreeDSCustomizationButtonTypeCancel","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The cancel button type."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/RawRepresentable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/RawRepresentable-Implementations","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/rawrepresentable-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/Equatable-Implementations","type":"topic","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType/submit":{"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeSubmit"}],"abstract":[{"text":"The submit button type.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype\/submit","title":"STPThreeDSCustomizationButtonType.submit","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"submit","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/submit"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPThreeDSCustomizationButtonType"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/cancel","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/continue","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/next","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/resend","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType\/submit"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1resend\/title","value":"STPThreeDSCustomizationButtonTypeResend"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1resend\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeResend"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1continue\/title","op":"replace","value":"STPThreeDSCustomizationButtonTypeContinue"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1continue\/fragments","value":[{"text":"STPThreeDSCustomizationButtonTypeContinue","kind":"identifier"}]},{"value":"STPThreeDSCustomizationButtonType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle","value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPThreeDSCustomizationButtonTypeNext","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1next\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1next\/fragments","value":[{"text":"STPThreeDSCustomizationButtonTypeNext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1cancel\/title","value":"STPThreeDSCustomizationButtonTypeCancel"},{"value":[{"text":"STPThreeDSCustomizationButtonTypeCancel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1cancel\/fragments"},{"value":"STPThreeDSCustomizationButtonTypeSubmit","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1submit\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType~1submit\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonTypeSubmit"}]}]}]}