{"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/init()"],"title":"Initializers","anchor":"Initializers","generated":true},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/activityIndicatorViewStyle","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/backgroundColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/blurStyle","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/footerCustomization","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/labelCustomization","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/navigationBarCustomization","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/selectionCustomization","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/textFieldCustomization"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/buttonCustomization(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/setButtonCustomization(_:for:)"],"generated":true,"anchor":"Instance-Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/defaultSettings()"],"generated":true,"title":"Type Methods"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSUICustomization"}],"role":"symbol","navigatorTitle":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"title":"STPThreeDSUICustomization","roleHeading":"Class"},"sections":[],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"type":"text","text":" "},{"text":"Note: It’s important to configure this object appropriately before calling any ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" APIs.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"text":" ","type":"text"},{"type":"text","text":"make to your "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" instance."}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPThreeDSUICustomization","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"content":[{"inlineContent":[{"type":"text","text":"https:\/\/stripe.com\/docs\/payments\/3d-secure"}],"type":"paragraph"}],"style":"note","name":"See Also","type":"aside"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization"]},{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/activityIndicatorViewStyle":{"title":"activityIndicatorViewStyle","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/activityIndicatorViewStyle","abstract":[{"type":"text","text":"The style of "},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"type":"text","text":"s displayed."},{"type":"text","text":" "},{"type":"text","text":"This should contrast with "},{"type":"codeVoice","code":"backgroundColor"},{"text":".  Defaults to gray.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/activityindicatorviewstyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicatorViewStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","text":"UIActivityIndicatorView"},{"kind":"text","text":"."},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIActivityIndicatorViewStyle"}],"navigatorTitle":[{"kind":"identifier","text":"activityIndicatorViewStyle"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/backgroundColor":{"role":"symbol","title":"backgroundColor","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/backgroundColor","abstract":[{"type":"text","text":"The primary background color of all UIViewControllers displayed during 3D Secure authentication."},{"text":" ","type":"text"},{"text":"Defaults to white.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/backgroundcolor","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/footerCustomization":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Provides custom settings for the footer the challenge view can display containing additional details."},{"type":"text","text":" "},{"type":"text","text":"The default is "},{"code":"STPThreeDSFooterCustomization.defaultSettings()","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"footerCustomization","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization","kind":"typeIdentifier","text":"STPThreeDSFooterCustomization"}],"navigatorTitle":[{"kind":"identifier","text":"footerCustomization"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/footercustomization","role":"symbol","title":"footerCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/footerCustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/navigationBarCustomization":{"abstract":[{"type":"text","text":"Provides custom settings for the UINavigationBar of all UIViewControllers displayed during 3D Secure authentication."},{"type":"text","text":" "},{"text":"The default is ","type":"text"},{"code":"STPThreeDSNavigationBarCustomization.defaultSettings()","type":"codeVoice"},{"text":".","type":"text"}],"title":"navigationBarCustomization","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigationBarCustomization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPThreeDSNavigationBarCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/navigationBarCustomization","type":"topic","navigatorTitle":[{"text":"navigationBarCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/navigationbarcustomization","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/setButtonCustomization(_:for:)":{"title":"setButtonCustomization(_:for:)","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/setButtonCustomization(_:for:)","abstract":[{"text":"Sets a given button customization for the specified type.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/setbuttoncustomization(_:for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setButtonCustomization"},{"kind":"text","text":"("},{"text":"STPThreeDSButtonCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPThreeDSCustomizationButtonType","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setButtonCustomization:forType:","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/init()":{"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/init()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/init()","abstract":[{"type":"text","text":":nodoc:"}],"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"title":"init()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/buttonCustomization(for:)":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/buttoncustomization(for:)","abstract":[{"type":"text","text":"Retrieves a button customization object for the given button type."}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/buttonCustomization(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"buttonCustomization","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","text":"STPThreeDSCustomizationButtonType","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","text":"STPThreeDSButtonCustomization"}],"navigatorTitle":[{"kind":"identifier","text":"buttonCustomizationForButtonType:"}],"title":"buttonCustomization(for:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/defaultSettings()":{"role":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/defaultsettings()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"STPThreeDSUICustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization"}],"kind":"symbol","type":"topic","abstract":[{"text":"The default settings.  See individual properties for their default values.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/defaultSettings()","navigatorTitle":[{"kind":"identifier","text":"defaultSettings"}],"title":"defaultSettings()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"text":" provides configuration for UI elements displayed during 3D Secure authentication.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" APIs."},{"type":"text","text":" "},{"text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you","type":"text"},{"type":"text","text":" "},{"type":"text","text":"make to your "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" instance."}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","title":"STPThreeDSUICustomization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSUICustomization"}],"kind":"symbol","navigatorTitle":[{"text":"STPThreeDSUICustomization","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/selectionCustomization":{"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/selectioncustomization","role":"symbol","title":"selectionCustomization","navigatorTitle":[{"kind":"identifier","text":"selectionCustomization"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"selectionCustomization","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization","text":"STPThreeDSSelectionCustomization","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/selectionCustomization","abstract":[{"text":"Provides custom settings for radio buttons and checkboxes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The default is "},{"type":"codeVoice","code":"STPThreeDSSelectionCustomization.defaultSettings()"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/textFieldCustomization":{"role":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/textfieldcustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/textFieldCustomization","title":"textFieldCustomization","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"textFieldCustomization"}],"abstract":[{"text":"Provides custom settings for text fields.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The default is "},{"code":"STPThreeDSTextFieldCustomization.defaultSettings()","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"textFieldCustomization","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization","kind":"typeIdentifier","text":"STPThreeDSTextFieldCustomization"}]},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/labelCustomization":{"title":"labelCustomization","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"labelCustomization"},{"text":": ","kind":"text"},{"text":"STPThreeDSLabelCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/labelCustomization","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/labelcustomization","abstract":[{"text":"Provides custom settings for labels.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The default is "},{"code":"STPThreeDSLabelCustomization.defaultSettings()","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"labelCustomization","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/blurStyle":{"abstract":[{"text":"The style of the ","type":"text"},{"code":"UIBlurEffect","type":"codeVoice"},{"type":"text","text":" displayed underneath the "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"UIBlurEffectStyleLight"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/blurStyle","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/blurstyle","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"blurStyle"},{"text":": ","kind":"text"},{"text":"UIBlurEffect","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBlurEffect"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIBlurEffectStyle","text":"Style","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"blurStyle","kind":"identifier"}],"title":"blurStyle"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPThreeDSUICustomization"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/activityIndicatorViewStyle","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/backgroundColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/blurStyle","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/footerCustomization","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/labelCustomization","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/navigationBarCustomization","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/selectionCustomization","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/textFieldCustomization"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/buttonCustomization(for:)","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/init()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/setButtonCustomization(_:for:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/defaultSettings()"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSUICustomization"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"activityIndicatorViewStyle","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1activityIndicatorViewStyle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"activityIndicatorViewStyle"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1activityIndicatorViewStyle\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1backgroundColor\/title","op":"replace","value":"backgroundColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1footerCustomization\/title","op":"replace","value":"footerCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1footerCustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"footerCustomization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1navigationBarCustomization\/title","value":"navigationBarCustomization"},{"value":[{"text":"navigationBarCustomization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1navigationBarCustomization\/fragments"},{"op":"replace","value":"setButtonCustomization:forType:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1setButtonCustomization(_:for:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1setButtonCustomization(_:for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setButtonCustomization:forType:"}]},{"value":"init","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1buttonCustomization(for:)\/title","value":"buttonCustomizationForButtonType:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"buttonCustomizationForButtonType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1buttonCustomization(for:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1defaultSettings()\/title","value":"defaultSettings"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1defaultSettings()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"defaultSettings","kind":"identifier"}]},{"op":"replace","value":"STPThreeDSUICustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"op":"replace"},{"value":"selectionCustomization","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1selectionCustomization\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1selectionCustomization\/fragments","value":[{"kind":"identifier","text":"selectionCustomization"}],"op":"replace"},{"value":"textFieldCustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1textFieldCustomization\/title","op":"replace"},{"value":[{"kind":"identifier","text":"textFieldCustomization"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1textFieldCustomization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1labelCustomization\/title","value":"labelCustomization"},{"value":[{"kind":"identifier","text":"labelCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1labelCustomization\/fragments","op":"replace"},{"op":"replace","value":"blurStyle","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1blurStyle\/title"},{"value":[{"text":"blurStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1blurStyle\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}