{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}],"roleHeading":"Class","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"class","title":"STPThreeDSCustomizationSettings","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}]},"abstract":[{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"type":"text","text":" provides customization options for 3DS2 authentication flows in your app."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/authenticationTimeout","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/uiCustomization"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/defaultSettings()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedscustomizationsettings"]}],"references":{"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings/defaultSettings()":{"navigatorTitle":[{"kind":"identifier","text":"defaultSettings"}],"deprecated":true,"role":"symbol","title":"defaultSettings()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/defaultSettings()","url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings\/defaultsettings()","abstract":[{"text":"Returns an ","type":"text"},{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"type":"text","text":" preconfigured with the default"},{"type":"text","text":" "},{"text":"Stripe UI settings and a 10 minute ","type":"text"},{"code":"authenticationTimeout","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"defaultSettings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSCustomizationSettings","text":"STPThreeDSCustomizationSettings"}],"type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings/uiCustomization":{"title":"uiCustomization","abstract":[{"type":"codeVoice","code":"uiCustomization"},{"type":"text","text":" can be used to provide custom UI settings for the authentication"},{"type":"text","text":" "},{"type":"text","text":"challenge screens presented during a Three Domain Secure authentication. For more information see"},{"text":" ","type":"text"},{"text":"our guide on supporting 3DS2 in your iOS application.","type":"text"},{"type":"text","text":" "},{"text":"Note: It’s important to configure this object appropriately before calling any ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" APIs."},{"type":"text","text":" "},{"text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you","type":"text"},{"text":" ","type":"text"},{"text":"make to your ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" instance."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"STPThreeDSUICustomization.defaultSettings()"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/uiCustomization","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uiCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPThreeDSUICustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization"}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings\/uicustomization","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"uiCustomization"}],"role":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings/authenticationTimeout":{"title":"authenticationTimeout","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/authenticationTimeout","abstract":[{"type":"codeVoice","code":"authenticationTimeout"},{"type":"text","text":" is the total time allowed for a user to complete a 3DS2 authentication"},{"text":" ","type":"text"},{"type":"text","text":"interaction, in minutes.  This value "},{"inlineContent":[{"type":"text","text":"must"}],"type":"emphasis"},{"text":" be at least 5 minutes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to 10 minutes."}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings\/authenticationtimeout","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticationTimeout"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"authenticationTimeout","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings/init":{"kind":"symbol","title":"init","url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings\/init","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationSettings":{"abstract":[{"type":"codeVoice","code":"STPThreeDSCustomizationSettings"},{"type":"text","text":" provides customization options for 3DS2 authentication flows in your app."}],"url":"\/documentation\/stripepayments\/stpthreedscustomizationsettings","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"title":"STPThreeDSCustomizationSettings","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"STPThreeDSCustomizationSettings","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPThreeDSCustomizationSettings","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/authenticationTimeout","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/uiCustomization"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/init"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationSettings\/defaultSettings()"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSCustomizationSettings"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"value":"defaultSettings","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1defaultSettings()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1defaultSettings()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1uiCustomization\/title","value":"uiCustomization"},{"value":[{"text":"uiCustomization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1uiCustomization\/fragments"},{"value":"authenticationTimeout","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1authenticationTimeout\/title"},{"op":"replace","value":[{"kind":"identifier","text":"authenticationTimeout"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings~1authenticationTimeout\/fragments"},{"value":"STPThreeDSCustomizationSettings","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationSettings\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSCustomizationSettings"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}