{"abstract":[{"type":"text","text":"Possible Token types"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stptokentype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stptokentype"]}],"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/PII","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/account","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/bankAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/cvcUpdate"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPTokenType"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"text":"STPTokenType","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPTokenType","role":"symbol","title":"STPTokenType","symbolKind":"enum","modules":[{"name":"StripePayments"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPTokenType","kind":"identifier"}]},"references":{"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.stripe.stripe-payments/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/CustomStringConvertible-Implementations":{"kind":"article","type":"topic","title":"CustomStringConvertible Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/CustomStringConvertible-Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stptokentype\/customstringconvertible-implementations"},"doc://com.stripe.stripe-payments/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/cvcUpdate":{"kind":"symbol","title":"STPTokenType.cvcUpdate","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/cvcUpdate","url":"\/documentation\/stripepayments\/stptokentype\/cvcupdate","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cvcUpdate","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPTokenTypeCvcUpdate","kind":"identifier"}],"abstract":[{"text":"CVC update token type","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/PII":{"navigatorTitle":[{"kind":"identifier","text":"STPTokenTypePII"}],"title":"STPTokenType.PII","type":"topic","abstract":[{"type":"text","text":"PII token type"}],"url":"\/documentation\/stripepayments\/stptokentype\/pii","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PII"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/PII"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/RawRepresentable-Implementations":{"kind":"article","type":"topic","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stptokentype\/rawrepresentable-implementations"},"doc://com.stripe.stripe-payments/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH","type":"unresolvable"},"doc://com.stripe.stripe-payments/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/card":{"url":"\/documentation\/stripepayments\/stptokentype\/card","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/card","abstract":[{"text":"Card token type","type":"text"}],"navigatorTitle":[{"text":"STPTokenTypeCard","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}],"title":"STPTokenType.card","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/account":{"url":"\/documentation\/stripepayments\/stptokentype\/account","title":"STPTokenType.account","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/account","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"account","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"STPTokenTypeAccount","kind":"identifier"}],"abstract":[{"type":"text","text":"Account token type"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType":{"role":"symbol","abstract":[{"type":"text","text":"Possible Token types"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPTokenType"}],"title":"STPTokenType","url":"\/documentation\/stripepayments\/stptokentype","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTokenType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/bankAccount":{"title":"STPTokenType.bankAccount","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/bankAccount","kind":"symbol","url":"\/documentation\/stripepayments\/stptokentype\/bankaccount","type":"topic","abstract":[{"type":"text","text":"Bank account token type"}],"navigatorTitle":[{"text":"STPTokenTypeBankAccount","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"bankAccount","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stptokentype\/init(rawvalue:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/init(rawValue:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPTokenType/Equatable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/stripepayments\/stptokentype\/equatable-implementations","abstract":[],"kind":"article","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPTokenType"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPTokenType"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPTokenType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/PII","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/account","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/bankAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPTokenType\/cvcUpdate"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPTokenType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"STPTokenTypeCvcUpdate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1cvcUpdate\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1cvcUpdate\/fragments","value":[{"text":"STPTokenTypeCvcUpdate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1PII\/title","value":"STPTokenTypePII"},{"op":"replace","value":[{"text":"STPTokenTypePII","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1PII\/fragments"},{"value":"STPTokenTypeCard","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1card\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1card\/fragments","value":[{"text":"STPTokenTypeCard","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1account\/title","value":"STPTokenTypeAccount"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1account\/fragments","value":[{"text":"STPTokenTypeAccount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/title","op":"replace","value":"STPTokenType"},{"op":"replace","value":[{"text":"STPTokenType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/fragments"},{"value":[{"text":"STPTokenType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1bankAccount\/title","op":"replace","value":"STPTokenTypeBankAccount"},{"value":[{"kind":"identifier","text":"STPTokenTypeBankAccount"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPTokenType~1bankAccount\/fragments","op":"replace"}]}]}
