{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSFooterCustomization","kind":"identifier"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}],"title":"STPThreeDSFooterCustomization","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization","modules":[{"name":"StripePayments"}],"symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSFooterCustomization","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"The Challenge view displays a footer with additional details that"},{"type":"text","text":" "},{"type":"text","text":"expand when tapped. This object configures the appearance of that view."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/backgroundColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/chevronColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/font","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/headingFont","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/headingTextColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/textColor"]},{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/defaultSettings()"]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsfootercustomization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsfootercustomization"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/backgroundColor":{"abstract":[{"text":"The background color of the footer.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to gray.","type":"text"}],"role":"symbol","kind":"symbol","title":"backgroundColor","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/backgroundcolor","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/backgroundColor"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/headingTextColor":{"abstract":[{"text":"The color of the heading text. Defaults to black.","type":"text"}],"role":"symbol","kind":"symbol","title":"headingTextColor","navigatorTitle":[{"kind":"identifier","text":"headingTextColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headingTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/headingtextcolor","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/headingTextColor"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization":{"navigatorTitle":[{"text":"STPThreeDSFooterCustomization","kind":"identifier"}],"title":"STPThreeDSFooterCustomization","abstract":[{"type":"text","text":"The Challenge view displays a footer with additional details that"},{"type":"text","text":" "},{"type":"text","text":"expand when tapped. This object configures the appearance of that view."}],"url":"\/documentation\/stripepayments\/stpthreedsfootercustomization","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSFooterCustomization","kind":"identifier"}]},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/defaultSettings()":{"abstract":[{"type":"text","text":"The default settings."}],"role":"symbol","kind":"symbol","title":"defaultSettings()","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"STPThreeDSFooterCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/defaultsettings()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/defaultSettings()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/textColor":{"abstract":[{"type":"text","text":"The color of the text."}],"role":"symbol","kind":"symbol","title":"textColor","navigatorTitle":[{"kind":"identifier","text":"textColor"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/textcolor","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/textColor"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/headingFont":{"abstract":[{"type":"text","text":"The font to use for the heading text."}],"role":"symbol","kind":"symbol","title":"headingFont","navigatorTitle":[{"kind":"identifier","text":"headingFont"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headingFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/headingfont","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/headingFont"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/font":{"abstract":[{"type":"text","text":"The font of the text."}],"role":"symbol","kind":"symbol","title":"font","navigatorTitle":[{"kind":"identifier","text":"font"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/font","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/font"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/chevronColor":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/chevronColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chevronColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/chevroncolor","kind":"symbol","navigatorTitle":[{"text":"chevronColor","kind":"identifier"}],"title":"chevronColor","role":"symbol","abstract":[{"type":"text","text":"The color of the chevron. Defaults to a dark gray."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/init":{"abstract":[],"role":"symbol","kind":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/init","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/init"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"STPThreeDSFooterCustomization"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/backgroundColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/chevronColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/font","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/headingFont","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/headingTextColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/textColor"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/init"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/defaultSettings()"],"generated":true,"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSFooterCustomization","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1backgroundColor\/title","op":"replace","value":"backgroundColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1backgroundColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"backgroundColor"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1headingTextColor\/title","op":"replace","value":"headingTextColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1headingTextColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"headingTextColor"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/title","op":"replace","value":"STPThreeDSFooterCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1defaultSettings()\/title","op":"replace","value":"defaultSettings"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1defaultSettings()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1textColor\/title","op":"replace","value":"textColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1textColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"textColor"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1headingFont\/title","op":"replace","value":"headingFont"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1headingFont\/fragments","op":"replace","value":[{"kind":"identifier","text":"headingFont"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1font\/title","op":"replace","value":"font"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1font\/fragments","op":"replace","value":[{"kind":"identifier","text":"font"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1chevronColor\/title","op":"replace","value":"chevronColor"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1chevronColor\/fragments","op":"replace","value":[{"kind":"identifier","text":"chevronColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}