{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization"},"abstract":[{"type":"text","text":"A customization object that configures the appearance of"},{"type":"text","text":" "},{"type":"text","text":"radio buttons and checkboxes."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/primarySelectedColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/secondarySelectedColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/unselectedBackgroundColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/unselectedBorderColor"],"generated":true,"anchor":"Instance-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/defaultSettings()"],"generated":true,"anchor":"Type-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"languages":["swift"]}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"type":"conformsTo"}],"metadata":{"symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization","title":"STPThreeDSSelectionCustomization","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}],"modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsselectioncustomization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsselectioncustomization"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization","kind":"symbol","title":"STPThreeDSSelectionCustomization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization","navigatorTitle":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A customization object that configures the appearance of","type":"text"},{"text":" ","type":"text"},{"text":"radio buttons and checkboxes.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/primarySelectedColor":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/primarySelectedColor","kind":"symbol","title":"primarySelectedColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primarySelectedColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/primaryselectedcolor","navigatorTitle":[{"kind":"identifier","text":"primarySelectedColor"}],"role":"symbol","abstract":[{"text":"The primary color of the selected state.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to blue.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/unselectedBorderColor":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/unselectedBorderColor","kind":"symbol","title":"unselectedBorderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unselectedBorderColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/unselectedbordercolor","navigatorTitle":[{"kind":"identifier","text":"unselectedBorderColor"}],"role":"symbol","abstract":[{"text":"The color of the border drawn around the view in the unselected state.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to blue.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/unselectedBackgroundColor":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/unselectedBackgroundColor","role":"symbol","title":"unselectedBackgroundColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unselectedBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"kind":"symbol","abstract":[{"text":"The background color displayed in the unselected state.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to light blue.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/unselectedbackgroundcolor","navigatorTitle":[{"kind":"identifier","text":"unselectedBackgroundColor"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/secondarySelectedColor":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/secondarySelectedColor","type":"topic","abstract":[{"text":"The secondary color of the selected state (e.g. the checkmark color).","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to white.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/secondaryselectedcolor","navigatorTitle":[{"kind":"identifier","text":"secondarySelectedColor"}],"title":"secondarySelectedColor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondarySelectedColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/init":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/init","type":"topic","abstract":[],"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/init","title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization/defaultSettings()":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/defaultSettings()","type":"topic","abstract":[{"text":"The default settings.","type":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization\/defaultsettings()","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}],"title":"defaultSettings()","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization","kind":"typeIdentifier","text":"STPThreeDSSelectionCustomization"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPThreeDSSelectionCustomization","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/primarySelectedColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/secondarySelectedColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/unselectedBackgroundColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/unselectedBorderColor"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/init"]},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization\/defaultSettings()"]}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSSelectionCustomization"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPThreeDSSelectionCustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/navigatorTitle"},{"op":"replace","value":"primarySelectedColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1primarySelectedColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"primarySelectedColor"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1primarySelectedColor\/fragments"},{"op":"replace","value":"unselectedBorderColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1unselectedBorderColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"unselectedBorderColor"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1unselectedBorderColor\/fragments"},{"op":"replace","value":"unselectedBackgroundColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1unselectedBackgroundColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"unselectedBackgroundColor"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1unselectedBackgroundColor\/fragments"},{"op":"replace","value":"secondarySelectedColor","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1secondarySelectedColor\/title"},{"op":"replace","value":[{"kind":"identifier","text":"secondarySelectedColor"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1secondarySelectedColor\/fragments"},{"op":"replace","value":"defaultSettings","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1defaultSettings()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization~1defaultSettings()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}