{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"kind":"symbol","abstract":[{"text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"kind":"relationships","title":"Conforms To"}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPToken","title":"STPToken","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPToken","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPToken"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPToken","kind":"identifier"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/bankAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/debugDescription","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/livemode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/stripeID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/tokenId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/type"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/isEqual(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/decodedObject(fromAPIResponse:)"],"title":"Type Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stptoken"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stptoken"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/decodedObject(fromAPIResponse:)":{"navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/decodedObject(fromAPIResponse:)","kind":"symbol","role":"symbol","type":"topic","title":"decodedObject(fromAPIResponse:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/decodedobject(fromapiresponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/livemode":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"livemode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stptoken\/livemode","title":"livemode","abstract":[{"text":"Whether or not this token was created in livemode. Will be YES if you used your Live Publishable Key, and NO if you used your Test Publishable Key.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"livemode","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/livemode"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/bankAccount":{"navigatorTitle":[{"kind":"identifier","text":"bankAccount"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/bankAccount","kind":"symbol","role":"symbol","type":"topic","title":"bankAccount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bankAccount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPBankAccount","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPBankAccount"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The bank account details that were used to create the token. Will only be set if the token was created with a bank account, otherwise it will be nil."}],"url":"\/documentation\/stripepayments\/stptoken\/bankaccount"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/stripeID":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"stripeID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stptoken\/stripeid","title":"stripeID","abstract":[{"type":"text","text":"The Stripe ID of the source."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"stripeID","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/stripeID"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/hash","kind":"symbol","role":"symbol","type":"topic","title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/hash"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/tokenId":{"kind":"symbol","abstract":[{"text":"The value of the token. You can store this value on your server and use it to make charges and customers.","type":"text"}],"type":"topic","title":"tokenId","role":"symbol","url":"\/documentation\/stripepayments\/stptoken\/tokenid","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/tokenId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"tokenId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"tokenId"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/description":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/description","kind":"symbol","role":"symbol","type":"topic","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/created":{"role":"symbol","url":"\/documentation\/stripepayments\/stptoken\/created","abstract":[{"type":"text","text":"When the token was created."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/created","navigatorTitle":[{"kind":"identifier","text":"created"}],"title":"created","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"created"},{"kind":"text","text":": "},{"text":"Date","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/card":{"type":"topic","role":"symbol","title":"card","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPCard","kind":"typeIdentifier","text":"STPCard"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"card","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/card","abstract":[{"text":"The credit card details that were used to create the token. Will only be set if the token was created via a credit card or Apple Pay, otherwise it will be","type":"text"},{"type":"text","text":" "},{"text":"nil.","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/card","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/isEqual(_:)","kind":"symbol","role":"symbol","type":"topic","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/isequal(_:)"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocol":{"role":"symbol","url":"\/documentation\/stripepayments\/stpsourceprotocol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","abstract":[{"type":"text","text":"Objects conforming to this protocol can be attached to a Stripe Customer object"},{"text":" ","type":"text"},{"type":"text","text":"as a payment source."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceProtocol"}],"title":"STPSourceProtocol"},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","title":"STPAPIResponseDecodable","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"text":" ","type":"text"},{"type":"text","text":"from a JSON dictionary that was returned from the Stripe API."}],"navigatorTitle":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/type":{"type":"topic","role":"symbol","title":"type","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"text":"STPTokenType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPTokenType"}],"navigatorTitle":[{"text":"type","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/type","abstract":[{"text":"The type of this token.","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/type","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/allResponseFields":{"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/allResponseFields","kind":"symbol","role":"symbol","type":"topic","title":"allResponseFields","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/allresponsefields"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPToken","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stptoken","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken","title":"STPToken","navigatorTitle":[{"kind":"identifier","text":"STPToken"}],"type":"topic","abstract":[{"type":"text","text":"A token returned from submitting payment details to the Stripe API. You should not have to instantiate one of these directly."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPToken/debugDescription":{"navigatorTitle":[{"text":"debugDescription","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/debugDescription","kind":"symbol","role":"symbol","type":"topic","title":"debugDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugDescription"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stptoken\/debugdescription"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPToken"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"STPToken","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"STPToken","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/bankAccount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/card","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/debugDescription","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/hash","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/livemode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/stripeID","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/tokenId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/type"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/isEqual(_:)"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPToken\/decodedObject(fromAPIResponse:)"]}]},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPToken","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1livemode\/title","value":"livemode"},{"value":[{"text":"livemode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1livemode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1bankAccount\/title","value":"bankAccount","op":"replace"},{"value":[{"text":"bankAccount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1bankAccount\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1stripeID\/title","op":"replace","value":"stripeID"},{"value":[{"kind":"identifier","text":"stripeID"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1stripeID\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1hash\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1tokenId\/title","value":"tokenId"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1tokenId\/fragments","value":[{"kind":"identifier","text":"tokenId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1description\/title","value":"description"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1description\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1created\/title","value":"created","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1created\/fragments","value":[{"text":"created","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1card\/title","value":"card"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1card\/fragments","value":[{"kind":"identifier","text":"card"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1isEqual(_:)\/fragments"},{"op":"replace","value":"STPSourceProtocol","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/fragments","value":[{"kind":"identifier","text":"STPSourceProtocol"}],"op":"replace"},{"value":[{"text":"STPSourceProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title","value":"STPAPIResponseDecodable","op":"replace"},{"value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},{"op":"replace","value":"type","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1type\/title"},{"value":[{"kind":"identifier","text":"type"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1type\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1allResponseFields\/title","value":"allResponseFields"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/title","op":"replace","value":"STPToken"},{"value":[{"text":"STPToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/fragments","op":"replace"},{"value":[{"text":"STPToken","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1debugDescription\/title","value":"debugDescription","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"debugDescription"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPToken~1debugDescription\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}