{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedstextfieldcustomization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedstextfieldcustomization"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A customization object to use to configure the UI of a text field."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"title":"STPThreeDSTextFieldCustomization","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/borderColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/borderWidth","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/cornerRadius","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/font","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/keyboardAppearance","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/placeholderTextColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/textColor"]},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/defaultSettings()"]}],"references":{"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/cornerRadius":{"role":"symbol","title":"cornerRadius","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The corner radius of the edges of the text field. Defaults to 8."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/cornerRadius","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/cornerradius"},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/textColor":{"role":"symbol","title":"textColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The color to use for the text. Defaults to black."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/textColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textColor"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/textcolor"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization":{"role":"symbol","title":"STPThreeDSTextFieldCustomization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"abstract":[{"type":"text","text":"A customization object to use to configure the UI of a text field."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/borderColor":{"role":"symbol","title":"borderColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The color of the border of the text field. Defaults to clear."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/borderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderColor"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/bordercolor"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/borderWidth":{"role":"symbol","title":"borderWidth","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderWidth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The border width of the text field. Defaults to 2."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/borderWidth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"borderWidth"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/borderwidth"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/font":{"role":"symbol","title":"font","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The font to use for text."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/font","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"font"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/font"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/placeholderTextColor":{"role":"symbol","title":"placeholderTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The color of the placeholder text. Defaults to light gray."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/placeholderTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeholderTextColor"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/placeholdertextcolor"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/defaultSettings()":{"role":"symbol","title":"defaultSettings()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"STPThreeDSTextFieldCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization"}],"abstract":[{"type":"text","text":"The default settings."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/defaultSettings()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultSettings"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/defaultsettings()"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization/keyboardAppearance":{"role":"symbol","title":"keyboardAppearance","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"keyboardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIKeyboardAppearance","preciseIdentifier":"c:@E@UIKeyboardAppearance"}],"abstract":[{"type":"text","text":"The appearance of the keyboard. Defaults to UIKeyboardAppearanceDefault."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/keyboardAppearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"keyboardAppearance"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization\/keyboardappearance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"STPThreeDSTextFieldCustomization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/borderColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/borderWidth","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/cornerRadius","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/font","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/keyboardAppearance","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/placeholderTextColor","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/textColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/init"]},{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization\/defaultSettings()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1cornerRadius\/title","value":"cornerRadius"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1cornerRadius\/fragments","value":[{"kind":"identifier","text":"cornerRadius"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1textColor\/title","value":"textColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1textColor\/fragments","value":[{"kind":"identifier","text":"textColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/title","value":"STPThreeDSTextFieldCustomization"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1borderColor\/title","value":"borderColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1borderColor\/fragments","value":[{"kind":"identifier","text":"borderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1borderWidth\/title","value":"borderWidth"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1borderWidth\/fragments","value":[{"kind":"identifier","text":"borderWidth"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1font\/title","value":"font"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1font\/fragments","value":[{"kind":"identifier","text":"font"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1placeholderTextColor\/title","value":"placeholderTextColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1placeholderTextColor\/fragments","value":[{"kind":"identifier","text":"placeholderTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1defaultSettings()\/title","value":"defaultSettings"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1defaultSettings()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"defaultSettings"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1keyboardAppearance\/title","value":"keyboardAppearance"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization~1keyboardAppearance\/fragments","value":[{"kind":"identifier","text":"keyboardAppearance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
