{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/funding","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"funding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPCardFundingType","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType"},{"kind":"text","text":" { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcecarddetails\/funding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcecarddetails\/funding"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails"]]},"abstract":[{"text":"The funding source for the card (credit, debit, prepaid, or other)","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"funding","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"funding","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPCardFundingType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"}],"role":"symbol","navigatorTitle":[{"text":"funding","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceCardDetails(py)funding"},"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCardDetails","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails","kind":"symbol","type":"topic","abstract":[{"text":"This class provides typed access to the contents of an STPSource ","type":"text"},{"code":"details","type":"codeVoice"},{"text":" ","type":"text"},{"text":"dictionary for card sources.","type":"text"}],"navigatorTitle":[{"text":"STPSourceCardDetails","kind":"identifier"}],"title":"STPSourceCardDetails","url":"\/documentation\/stripepayments\/stpsourcecarddetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/funding":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"funding","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPCardFundingType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"}],"navigatorTitle":[{"text":"funding","kind":"identifier"}],"role":"symbol","title":"funding","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpsourcecarddetails\/funding","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/funding","abstract":[{"type":"text","text":"The funding source for the card (credit, debit, prepaid, or other)"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","abstract":[{"text":"The various funding sources for a payment card.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardFundingType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFundingType"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcardfundingtype","title":"STPCardFundingType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"funding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"funding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"STPCardFundingType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"},{"kind":"text","text":" "},{"kind":"identifier","text":"funding"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/title","value":"STPSourceCardDetails"},{"value":[{"kind":"identifier","text":"STPSourceCardDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceCardDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/navigatorTitle"},{"value":"funding","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1funding\/title"},{"value":[{"kind":"identifier","text":"funding"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1funding\/fragments"},{"value":"STPCardFundingType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title"},{"value":[{"text":"STPCardFundingType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments"},{"value":[{"kind":"identifier","text":"STPCardFundingType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle"}]}]}