{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threeDSecure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSourceCard3DSecureStatus","preciseIdentifier":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus"},{"text":" { get }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcecarddetails\/threedsecure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcecarddetails\/threedsecure"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/threeDSecure","interfaceLanguage":"swift"},"metadata":{"title":"threeDSecure","roleHeading":"Instance Property","navigatorTitle":[{"text":"threeDSecure","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDSecure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceCard3DSecureStatus","preciseIdentifier":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus"}],"externalID":"c:@M@StripePayments@objc(cs)STPSourceCardDetails(py)threeDSecure"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Whether 3D Secure is supported or required by the card.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails/threeDSecure":{"title":"threeDSecure","kind":"symbol","navigatorTitle":[{"text":"threeDSecure","kind":"identifier"}],"abstract":[{"type":"text","text":"Whether 3D Secure is supported or required by the card."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails\/threeDSecure","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threeDSecure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSourceCard3DSecureStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus"}],"url":"\/documentation\/stripepayments\/stpsourcecarddetails\/threedsecure"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails":{"navigatorTitle":[{"text":"STPSourceCardDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcecarddetails","title":"STPSourceCardDetails","abstract":[{"text":"This class provides typed access to the contents of an STPSource ","type":"text"},{"type":"codeVoice","code":"details"},{"text":" ","type":"text"},{"text":"dictionary for card sources.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceCardDetails","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCard3DSecureStatus":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceCard3DSecureStatus"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcecard3dsecurestatus","abstract":[{"type":"text","text":"The status of this card’s 3D Secure support."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus","title":"STPSourceCard3DSecureStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"threeDSecure"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"threeDSecure","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCard3DSecureStatus","text":"STPSourceCard3DSecureStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceCard3DSecureStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDSecure"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1threeDSecure\/title","value":"threeDSecure"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails~1threeDSecure\/fragments","value":[{"text":"threeDSecure","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/title","value":"STPSourceCardDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/fragments","value":[{"text":"STPSourceCardDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/navigatorTitle","value":[{"text":"STPSourceCardDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/title","value":"STPSourceCard3DSecureStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/fragments","value":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPSourceCard3DSecureStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCard3DSecureStatus\/navigatorTitle"}]}]}