{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization"]]},"abstract":[{"text":"The color of the chevron. Defaults to a dark gray.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsfootercustomization\/chevroncolor"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsfootercustomization\/chevroncolor"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chevronColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/chevronColor"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization(py)chevronColor","navigatorTitle":[{"text":"chevronColor","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chevronColor","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"symbolKind":"property","roleHeading":"Instance Property","title":"chevronColor"},"kind":"symbol","sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization":{"abstract":[{"text":"The Challenge view displays a footer with additional details that","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"expand when tapped. This object configures the appearance of that view."}],"title":"STPThreeDSFooterCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSFooterCustomization"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/chevronColor":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chevronColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"type":"topic","navigatorTitle":[{"text":"chevronColor","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/chevroncolor","kind":"symbol","title":"chevronColor","abstract":[{"type":"text","text":"The color of the chevron. Defaults to a dark gray."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/chevronColor"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"chevronColor","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"chevronColor","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" * "},{"text":"chevronColor","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/title","op":"replace","value":"STPThreeDSFooterCustomization"},{"value":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/fragments"},{"value":[{"text":"STPThreeDSFooterCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1chevronColor\/title","op":"replace","value":"chevronColor"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1chevronColor\/fragments","value":[{"text":"chevronColor","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}