{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultSettings"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization","kind":"typeIdentifier","text":"STPThreeDSFooterCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/defaultSettings()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsfootercustomization\/defaultsettings()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsfootercustomization\/defaultsettings()"]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"text":"defaultSettings","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization(cm)defaultSettings","title":"defaultSettings()","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization","text":"STPThreeDSFooterCustomization"}]},"abstract":[{"type":"text","text":"The default settings."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization/defaultSettings()":{"role":"symbol","navigatorTitle":[{"text":"defaultSettings","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSettings"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization","text":"STPThreeDSFooterCustomization"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization\/defaultSettings()","title":"defaultSettings()","abstract":[{"text":"The default settings.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsfootercustomization\/defaultsettings()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization":{"url":"\/documentation\/stripepayments\/stpthreedsfootercustomization","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSFooterCustomization"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization","abstract":[{"type":"text","text":"The Challenge view displays a footer with additional details that"},{"text":" ","type":"text"},{"type":"text","text":"expand when tapped. This object configures the appearance of that view."}],"title":"STPThreeDSFooterCustomization","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPThreeDSFooterCustomization","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"defaultSettings"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"defaultSettings"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization","kind":"typeIdentifier","text":"STPThreeDSFooterCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization"},{"kind":"text","text":" *) "},{"text":"defaultSettings","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1defaultSettings()\/title","value":"defaultSettings"},{"value":[{"text":"+ ","kind":"text"},{"text":"defaultSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization~1defaultSettings()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/title","value":"STPThreeDSFooterCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/fragments","value":[{"text":"STPThreeDSFooterCustomization","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}]}]}]}