{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/CustomStringConvertible-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentstatus\/customstringconvertible-implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"CustomStringConvertible Implementations","modules":[{"name":"StripePayments"}],"role":"collectionGroup","roleHeading":"API Collection"},"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/description"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/description":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/description","url":"\/documentation\/stripepayments\/stppaymentstatus\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus":{"kind":"symbol","abstract":[{"text":"An enum representing the status of a payment requested from the user.","type":"text"}],"title":"STPPaymentStatus","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentstatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentStatus","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/title","op":"replace","value":"STPPaymentStatus"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/fragments","value":[{"text":"STPPaymentStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}