{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentstatus\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentstatus\/error"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"case","role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"title":"STPPaymentStatus.error","externalID":"c:@M@StripePayments@E@STPPaymentStatus@STPPaymentStatusError","navigatorTitle":[{"text":"STPPaymentStatusError","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/error","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"The payment failed due to an unforeseen error, such as the user’s Internet connection being offline."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/error":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"url":"\/documentation\/stripepayments\/stppaymentstatus\/error","title":"STPPaymentStatus.error","navigatorTitle":[{"text":"STPPaymentStatusError","kind":"identifier"}],"abstract":[{"type":"text","text":"The payment failed due to an unforeseen error, such as the user’s Internet connection being offline."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/error"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus":{"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentstatus","navigatorTitle":[{"text":"STPPaymentStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentStatus","kind":"identifier"}],"title":"STPPaymentStatus","kind":"symbol","abstract":[{"type":"text","text":"An enum representing the status of a payment requested from the user."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentStatusError"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentStatusError","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentStatusError"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1error\/title","value":"STPPaymentStatusError"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1error\/fragments","value":[{"kind":"identifier","text":"STPPaymentStatusError"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/title","value":"STPPaymentStatus","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentStatus"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/fragments"},{"op":"replace","value":[{"text":"STPPaymentStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}