{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentstatus\/usercancellation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentstatus\/usercancellation"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/userCancellation","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"STPPaymentStatusUserCancellation","kind":"identifier"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentStatus@STPPaymentStatusUserCancellation","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCancellation"}],"title":"STPPaymentStatus.userCancellation"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userCancellation","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"The user cancelled the payment (for example, by hitting “cancel” in the Apple Pay dialog)."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus/userCancellation":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userCancellation","kind":"identifier"}],"abstract":[{"type":"text","text":"The user cancelled the payment (for example, by hitting “cancel” in the Apple Pay dialog)."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentStatusUserCancellation"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus\/userCancellation","url":"\/documentation\/stripepayments\/stppaymentstatus\/usercancellation","title":"STPPaymentStatus.userCancellation","kind":"symbol","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentStatus":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentStatus"}],"abstract":[{"text":"An enum representing the status of a payment requested from the user.","type":"text"}],"title":"STPPaymentStatus","url":"\/documentation\/stripepayments\/stppaymentstatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentStatus","role":"symbol","navigatorTitle":[{"text":"STPPaymentStatus","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"STPPaymentStatusUserCancellation","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentStatusUserCancellation"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPPaymentStatusUserCancellation"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1userCancellation\/title","op":"replace","value":"STPPaymentStatusUserCancellation"},{"value":[{"kind":"identifier","text":"STPPaymentStatusUserCancellation"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus~1userCancellation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/title","value":"STPPaymentStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/fragments","value":[{"text":"STPPaymentStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentStatus\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}