{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/defaultSource","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPCustomer(py)defaultSource","title":"defaultSource","navigatorTitle":[{"kind":"identifier","text":"defaultSource"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSourceProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSource","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSourceProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"},{"text":"? { get }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer"]]},"abstract":[{"type":"text","text":"The default source used to charge the customer."}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpcustomer\/defaultsource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcustomer\/defaultsource"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","url":"\/documentation\/stripepayments\/stpcustomer","navigatorTitle":[{"kind":"identifier","text":"STPCustomer"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomer"}],"abstract":[{"type":"text","text":"An "},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" represents a deserialized Customer object from the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to instantiate an "},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" – you should instead use"},{"type":"text","text":" "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":" to manage retrieving and updating a customer."}],"title":"STPCustomer","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceProtocol","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSourceProtocol","kind":"identifier"}],"title":"STPSourceProtocol","abstract":[{"text":"Objects conforming to this protocol can be attached to a Stripe Customer object","type":"text"},{"text":" ","type":"text"},{"text":"as a payment source.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceprotocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/defaultSource":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/defaultSource","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSource","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","text":"STPSourceProtocol","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"defaultSource","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpcustomer\/defaultsource","title":"defaultSource","role":"symbol","abstract":[{"type":"text","text":"The default source used to charge the customer."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"defaultSource","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"defaultSource","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<STPSourceProtocol>","preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPSourceProtocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultSource"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPCustomer","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPCustomer"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/fragments","op":"replace"},{"value":[{"text":"STPCustomer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/navigatorTitle","op":"replace"},{"value":"STPSourceProtocol","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceProtocol"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/fragments","op":"replace"},{"value":[{"text":"STPSourceProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/navigatorTitle","op":"replace"},{"value":"defaultSource","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1defaultSource\/title","op":"replace"},{"value":[{"kind":"identifier","text":"defaultSource"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1defaultSource\/fragments","op":"replace"}]}]}