{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpcustomer\/init(stripeid:defaultsource:sources:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomer\/init(stripeid:defaultsource:sources:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/init(stripeID:defaultSource:sources:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Initialize a customer object with the provided values."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"stripeID"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"defaultSource","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","kind":"typeIdentifier","text":"STPSourceProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"},{"kind":"text","text":"?, "},{"text":"sources","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","kind":"typeIdentifier","text":"STPSourceProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ID of the customer, e.g. ","type":"text"},{"type":"codeVoice","code":"cus_abc"}],"type":"paragraph"}],"name":"stripeID"},{"content":[{"inlineContent":[{"type":"text","text":"The default source of the customer, such as an "},{"type":"codeVoice","code":"STPCard"},{"type":"text","text":" object. Can be nil."}],"type":"paragraph"}],"name":"defaultSource"},{"content":[{"type":"paragraph","inlineContent":[{"text":"All of the customer’s payment sources. This might be an empty array.","type":"text"}]}],"name":"sources"}]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCustomer(im)initWithStripeID:defaultSource:sources:","navigatorTitle":[{"kind":"identifier","text":"initWithStripeID:defaultSource:sources:"}],"roleHeading":"Initializer","title":"init(stripeID:defaultSource:sources:)","modules":[{"name":"StripePayments"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"stripeID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"defaultSource","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","text":"STPSourceProtocol"},{"kind":"text","text":"?, "},{"text":"sources","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","text":"STPSourceProtocol","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"symbolKind":"init","role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/init(stripeID:defaultSource:sources:)":{"url":"\/documentation\/stripepayments\/stpcustomer\/init(stripeid:defaultsource:sources:)","abstract":[{"type":"text","text":"Initialize a customer object with the provided values."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStripeID:defaultSource:sources:"}],"title":"init(stripeID:defaultSource:sources:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"stripeID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"defaultSource","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","text":"STPSourceProtocol"},{"text":"?, ","kind":"text"},{"text":"sources","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceProtocol","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/init(stripeID:defaultSource:sources:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer":{"url":"\/documentation\/stripepayments\/stpcustomer","abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"STPCustomer"},{"type":"text","text":" represents a deserialized Customer object from the Stripe API."},{"text":" ","type":"text"},{"text":"You shouldn’t need to instantiate an ","type":"text"},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" – you should instead use"},{"type":"text","text":" "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":" to manage retrieving and updating a customer."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomer"}],"type":"topic","kind":"symbol","title":"STPCustomer","navigatorTitle":[{"kind":"identifier","text":"STPCustomer"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocol":{"url":"\/documentation\/stripepayments\/stpsourceprotocol","title":"STPSourceProtocol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Objects conforming to this protocol can be attached to a Stripe Customer object"},{"text":" ","type":"text"},{"text":"as a payment source.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","navigatorTitle":[{"text":"STPSourceProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceProtocol"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithStripeID:defaultSource:sources:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStripeID:defaultSource:sources:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStripeID:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"stripeID","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"defaultSource:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<STPSourceProtocol>","preciseIdentifier":"c:Qo@M@StripePayments@objc(pl)STPSourceProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"defaultSource","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sources:"},{"text":"(","kind":"text"},{"text":"NSArray<id<STPSourceProtocol>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sources"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"stripeID","content":[{"inlineContent":[{"text":"The ID of the customer, e.g. ","type":"text"},{"code":"cus_abc","type":"codeVoice"}],"type":"paragraph"}]},{"name":"defaultSource","content":[{"inlineContent":[{"text":"The default source of the customer, such as an ","type":"text"},{"type":"codeVoice","code":"STPCard"},{"type":"text","text":" object. Can be nil."}],"type":"paragraph"}]},{"name":"sources","content":[{"inlineContent":[{"type":"text","text":"All of the customer’s payment sources. This might be an empty array."}],"type":"paragraph"}]}]}},{"value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of STPCustomer"}]}],"kind":"content"},"op":"add","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1init(stripeID:defaultSource:sources:)\/title","value":"initWithStripeID:defaultSource:sources:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStripeID:defaultSource:sources:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1init(stripeID:defaultSource:sources:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/title","op":"replace","value":"STPCustomer"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/fragments","op":"replace","value":[{"text":"STPCustomer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/navigatorTitle","value":[{"text":"STPCustomer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/title","op":"replace","value":"STPSourceProtocol"},{"value":[{"kind":"identifier","text":"STPSourceProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceProtocol"}],"op":"replace"}]}]}