{"abstract":[{"text":"The customer’s shipping address.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcustomer\/shippingaddress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomer\/shippingaddress"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/shippingAddress"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer"]]},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPCustomer(py)shippingAddress","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"shippingAddress","kind":"identifier"}],"title":"shippingAddress"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/shippingAddress":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shippingAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/shippingAddress","navigatorTitle":[{"text":"shippingAddress","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcustomer\/shippingaddress","abstract":[{"text":"The customer’s shipping address.","type":"text"}],"title":"shippingAddress","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","url":"\/documentation\/stripepayments\/stpcustomer","navigatorTitle":[{"kind":"identifier","text":"STPCustomer"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomer"}],"abstract":[{"type":"text","text":"An "},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" represents a deserialized Customer object from the Stripe API."},{"type":"text","text":" "},{"type":"text","text":"You shouldn’t need to instantiate an "},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" – you should instead use"},{"type":"text","text":" "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":" to manage retrieving and updating a customer."}],"title":"STPCustomer","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"role":"symbol","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"title":"STPAddress","abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"type":"topic","url":"\/documentation\/stripepayments\/stpaddress","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddress","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"shippingAddress","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"shippingAddress"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":" * ","kind":"text"},{"text":"shippingAddress","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"shippingAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1shippingAddress\/title"},{"op":"replace","value":[{"text":"shippingAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1shippingAddress\/fragments"},{"op":"replace","value":"STPCustomer","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/title"},{"op":"replace","value":[{"text":"STPCustomer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPCustomer"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/navigatorTitle"},{"op":"replace","value":"STPAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title"},{"op":"replace","value":[{"text":"STPAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}