{"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCustomer(im)updateSourcesFilteringApplePay:","title":"updateSources(filteringApplePay:)","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateSources","kind":"identifier"},{"text":"(","kind":"text"},{"text":"filteringApplePay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"updateSourcesFilteringApplePay:"}]},"abstract":[{"type":"text","text":"Replaces the customer’s "},{"type":"codeVoice","code":"sources"},{"type":"text","text":" and "},{"type":"codeVoice","code":"defaultSource"},{"type":"text","text":" based on whether or not"},{"type":"text","text":" "},{"type":"text","text":"they should include Apple Pay sources. More details on documentation for"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext includeApplePaySources"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(updateSourcesFilteringApplePay:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSources"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filteringApplePay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If YES, Apple Pay sources will be ignored"}]}],"name":"filteringApplePay"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcustomer\/updatesources(filteringapplepay:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomer\/updatesources(filteringapplepay:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/updateSources(filteringApplePay:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/updateSources(filteringApplePay:)":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcustomer\/updatesources(filteringapplepay:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateSources"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filteringApplePay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"title":"updateSources(filteringApplePay:)","navigatorTitle":[{"kind":"identifier","text":"updateSourcesFilteringApplePay:"}],"abstract":[{"type":"text","text":"Replaces the customer’s "},{"type":"codeVoice","code":"sources"},{"type":"text","text":" and "},{"type":"codeVoice","code":"defaultSource"},{"type":"text","text":" based on whether or not"},{"type":"text","text":" "},{"type":"text","text":"they should include Apple Pay sources. More details on documentation for"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext includeApplePaySources"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/updateSources(filteringApplePay:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer":{"abstract":[{"text":"An ","type":"text"},{"code":"STPCustomer","type":"codeVoice"},{"text":" represents a deserialized Customer object from the Stripe API.","type":"text"},{"text":" ","type":"text"},{"text":"You shouldn’t need to instantiate an ","type":"text"},{"code":"STPCustomer","type":"codeVoice"},{"text":" – you should instead use","type":"text"},{"text":" ","type":"text"},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and updating a customer.","type":"text"}],"title":"STPCustomer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","url":"\/documentation\/stripepayments\/stpcustomer","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCustomer"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCustomer"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"updateSourcesFilteringApplePay:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateSourcesFilteringApplePay:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"updateSourcesFilteringApplePay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"filteringApplePay","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"filteringApplePay","content":[{"type":"paragraph","inlineContent":[{"text":"If YES, Apple Pay sources will be ignored","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"updateSourcesFilteringApplePay:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1updateSources(filteringApplePay:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateSourcesFilteringApplePay:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1updateSources(filteringApplePay:)\/fragments"},{"op":"replace","value":"STPCustomer","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/title"},{"op":"replace","value":[{"text":"STPCustomer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/fragments"},{"op":"replace","value":[{"text":"STPCustomer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/navigatorTitle"}]}]}