{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/DefaultAddressDetails"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18StripePaymentSheet0bC0C","kind":"typeIdentifier","text":"PaymentSheet"},{"kind":"text","text":"."},{"preciseIdentifier":"s:18StripePaymentSheet0bC0C7AddressV","text":"Address","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","title":"address","externalID":"s:18StripePaymentSheet21AddressViewControllerC13ConfigurationV07DefaultD7DetailsV7addressAA0bC0C0D0Vvp","modules":[{"name":"StripePaymentSheet"}]},"abstract":[{"type":"text","text":"The customer’s address"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/defaultaddressdetails\/address"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/DefaultAddressDetails\/address"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:18StripePaymentSheet0bC0C","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet","text":"PaymentSheet"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:18StripePaymentSheet0bC0C7AddressV","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet\/Address"}]}]}],"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct":{"type":"topic","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct","title":"AddressViewController.Configuration","abstract":[{"text":"Configuration for an ","type":"text"},{"code":"AddressViewController","type":"codeVoice"},{"text":" instance.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/DefaultAddressDetails/address":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PaymentSheet","preciseIdentifier":"s:18StripePaymentSheet0bC0C","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Address","preciseIdentifier":"s:18StripePaymentSheet0bC0C7AddressV"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/defaultaddressdetails\/address","kind":"symbol","role":"symbol","type":"topic","title":"address","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/DefaultAddressDetails\/address","abstract":[{"text":"The customer’s address","type":"text"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/Configuration-swift.struct/DefaultAddressDetails":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/Configuration-swift.struct\/DefaultAddressDetails","abstract":[{"type":"text","text":"Default values for the fields collected by "},{"code":"AddressViewController","type":"codeVoice"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DefaultAddressDetails","kind":"identifier"}],"title":"AddressViewController.Configuration.DefaultAddressDetails","role":"symbol","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/configuration-swift.struct\/defaultaddressdetails","navigatorTitle":[{"kind":"identifier","text":"DefaultAddressDetails"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/PaymentSheet":{"navigatorTitle":[{"text":"PaymentSheet","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet","title":"PaymentSheet","abstract":[{"text":"A drop-in class that presents a sheet for a customer to complete their payment","type":"text"}],"url":"\/documentation\/stripepaymentsheet\/paymentsheet","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentSheet"}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/PaymentSheet/Address":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/stripepaymentsheet\/paymentsheet\/address","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Address","kind":"identifier"}],"abstract":[{"text":"An address.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/PaymentSheet\/Address","navigatorTitle":[{"kind":"identifier","text":"Address"}],"title":"PaymentSheet.Address"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddressViewController"}],"title":"AddressViewController","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","abstract":[{"type":"text","text":"A view controller that collects a name and an address, with full localization and autocomplete."}]},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","title":"StripePaymentSheet","url":"\/documentation\/stripepaymentsheet","kind":"symbol","type":"topic","abstract":[{"text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title","op":"replace","value":"STPAddressViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","value":[{"kind":"identifier","text":"STPAddressViewController"}]},{"value":[{"text":"STPAddressViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}
