{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodaubecsdebitparams\/init"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAUBECSDebitParams(im)init","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebitParams"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebitParams\/init","interfaceLanguage":"occ"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebitParams/init":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebitParams\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebitparams\/init","type":"topic","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAUBECSDebitParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodaubecsdebitparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAUBECSDebitParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodAUBECSDebitParams","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAUBECSDebitParams","title":"STPPaymentMethodAUBECSDebitParams","role":"symbol","kind":"symbol","abstract":[{"text":"An object representing parameters used to create an AU BECS Debit Payment Method","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebitParams\/title","value":"STPPaymentMethodAUBECSDebitParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebitParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodAUBECSDebitParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAUBECSDebitParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodAUBECSDebitParams"}]}]}]}