# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# TODO(mludowise|RUN_MOBILESDK-120): Update tests for iOS 14.5 & use
# `DEFAULT_TEST_VERSION` for all applicable tests
DEFAULT_TEST_DEVICE = "iPhone 8"
DEFAULT_TEST_VERSION = "13.7"

platform :ios do
  use_cache = false

  before_all do
    setup_circle_ci
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Stripe.xcworkspace", scheme: "LocalizationTester")
  end

  lane :all_ci do
    ci_builds
    main_tests
    ui_apps_analyze_tests
    install_tests
    paymentsheet_tests
    basic_integration_tests
    linting_tests
    ui_tests
    legacy_tests_11
    legacy_tests_12
  end

  lane :linting_tests do
    preflight
    check_docs
    builds
    analyze
  end

  lane :install_tests do
    install_cocoapods_without_frameworks_objc
    installation_cocoapods_frameworks_objc
    installation_cocoapods_frameworks_swift
    installation_carthage
    installation_spm_objc
    installation_spm_swift
  end

  lane :preflight do
    Dir.chdir("..") do
      sh("./ci_scripts/check_version.rb")
      sh("./ci_scripts/check_for_new_localized_strings.sh")
    end
  end

  lane :ci_builds do
    Dir.chdir("..") do
      sh("rm -rf build-ci-tests")
      sh("./ci_scripts/test.rb --build-only --scheme StripeCore")
      sh("./ci_scripts/test.rb --build-only --scheme StripeUICore")
      sh("./ci_scripts/test.rb --build-only --scheme StripeApplePay")
      sh("./ci_scripts/test.rb --build-only --scheme StripeiOS")
      sh("./ci_scripts/test.rb --build-only --scheme StripeIdentity")
      sh("./ci_scripts/test.rb --build-only --scheme 'Basic Integration'")
      sh("./ci_scripts/test.rb --build-only --scheme 'IntegrationTester'")
      sh("./ci_scripts/test.rb --build-only --scheme 'LocalizationTester'")
      sh("./ci_scripts/test.rb --build-only --scheme 'PaymentSheet Example'")
      sh("./ci_scripts/test.rb --build-only --scheme StripeConnections")
    end
  end

  lane :stripeios_tests do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme StripeiOS --device '#{DEFAULT_TEST_DEVICE}' --version #{DEFAULT_TEST_VERSION}")
    end
  end

  lane :stripecore_tests do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme StripeCore --device '#{DEFAULT_TEST_DEVICE}' --version #{DEFAULT_TEST_VERSION}")
    end
  end

  lane :stripeidentity_tests do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme StripeIdentity --device '#{DEFAULT_TEST_DEVICE}' --version #{DEFAULT_TEST_VERSION}")
    end
  end

  lane :stripeuicore_tests do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme StripeUICore --device '#{DEFAULT_TEST_DEVICE}' --version #{DEFAULT_TEST_VERSION}")
    end
  end

  lane :stripeconnections_tests do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme StripeConnections --device '#{DEFAULT_TEST_DEVICE}' --version #{DEFAULT_TEST_VERSION}")
    end
  end

  lane :paymentsheet_tests do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme 'PaymentSheet Example' --device 'iPhone 12' --version 14.5")
    end
  end

  lane :basic_integration_tests do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme 'Basic Integration' --device 'iPhone 11' --version #{DEFAULT_TEST_VERSION}")
    end
  end

  lane :integration_all do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme 'IntegrationTester' --device 'iPhone 12 Pro Max' --version 14.5")
      sh("./ci_scripts/test.rb --scheme 'IntegrationTester' --device '#{DEFAULT_TEST_DEVICE}' --version 14.5")
    end
  end

  lane :ui_tests do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme 'LocalizationTester' --device '#{DEFAULT_TEST_DEVICE}' --version #{DEFAULT_TEST_VERSION}")
    end
  end

  lane :legacy_tests_11 do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme 'StripeiOS' --device 'iPhone 6' --version 11.4 --skip-snapshot-tests")
      sh("./ci_scripts/test.rb --scheme 'StripeCore' --device 'iPhone 6' --version 11.4 --skip-snapshot-tests")
      sh("./ci_scripts/test.rb --scheme 'StripeUICore' --device 'iPhone 6' --version 11.4 --skip-snapshot-tests")
    end
  end

  lane :legacy_tests_12 do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme 'StripeiOS' --device 'iPhone 6' --version 12.4 --skip-snapshot-tests")
      sh("./ci_scripts/test.rb --scheme 'StripeCore' --device 'iPhone 6' --version 12.4 --skip-snapshot-tests")
      sh("./ci_scripts/test.rb --scheme 'StripeUICore' --device 'iPhone 6' --version 12.4 --skip-snapshot-tests")
    end
  end

  lane :e2e_only do
    Dir.chdir("..") do
      sh("./ci_scripts/test.rb --scheme 'StripeiOS' --device '#{DEFAULT_TEST_DEVICE}' --version #{DEFAULT_TEST_VERSION} --only-test 'StripeiOS Tests/STPE2ETest'")
    end
  end

  lane :analyze do
    Dir.chdir("..") do
      sh("./ci_scripts/run_analyzer.sh")
    end
  end

  lane :builds do
    Dir.chdir("..") do
      sh("./ci_scripts/run_builds.sh")
    end
  end

  lane :install_cocoapods_without_frameworks_objc do
    Dir.chdir("..") do
      sh("./Tests/installation_tests/cocoapods/without_frameworks_objc/test.sh")
    end
  end

  lane :installation_cocoapods_frameworks_objc do
    Dir.chdir("..") do
      sh("./Tests/installation_tests/cocoapods/with_frameworks_objc/test.sh")
    end
  end

  lane :installation_cocoapods_frameworks_swift do
    Dir.chdir("..") do
      sh("./Tests/installation_tests/cocoapods/with_frameworks_swift/test.sh")
    end
  end

  lane :installation_carthage do
    Dir.chdir("..") do
      sh("./Tests/installation_tests/carthage/test.sh")
    end
  end

  lane :installation_spm_objc do
    Dir.chdir("..") do
      sh("./Tests/installation_tests/swift_package_manager/with_objc/test.sh")
    end
  end

  lane :installation_spm_swift do
    Dir.chdir("..") do
      sh("./Tests/installation_tests/swift_package_manager/with_swift/test.sh")
    end
  end

  lane :check_docs do
    Dir.chdir("..") do
      sh("./ci_scripts/check_documentation.sh")
    end
  end

  lane :tests do
    # TODO: what this?
    run_tests(scheme: "StripeiOS",
      devices: ["iPhone 8"])
  end

end
