{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams\/customerAcceptance"},"variants":[{"paths":["\/documentation\/stripepayments\/stpmandatedataparams\/customeracceptance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpmandatedataparams\/customeracceptance"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"customerAcceptance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams","text":"STPMandateCustomerAcceptanceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Details about the customer acceptance of the Mandate.","type":"text"}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPMandateDataParams(py)customerAcceptance","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerAcceptance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams","text":"STPMandateCustomerAcceptanceParams","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}],"title":"customerAcceptance","navigatorTitle":[{"text":"customerAcceptance","kind":"identifier"}],"symbolKind":"property"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateDataParams/customerAcceptance":{"title":"customerAcceptance","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customerAcceptance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams","text":"STPMandateCustomerAcceptanceParams","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams\/customerAcceptance","navigatorTitle":[{"text":"customerAcceptance","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Details about the customer acceptance of the Mandate."}],"type":"topic","url":"\/documentation\/stripepayments\/stpmandatedataparams\/customeracceptance"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateDataParams":{"navigatorTitle":[{"text":"STPMandateDataParams","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPMandateDataParams","kind":"identifier"}],"title":"STPMandateDataParams","abstract":[{"text":"This object contains details about the Mandate to create. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data","type":"text"}],"url":"\/documentation\/stripepayments\/stpmandatedataparams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams":{"url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams","abstract":[{"type":"text","text":"An object that contains details about the customer acceptance of the Mandate. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"title":"STPMandateCustomerAcceptanceParams"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"customerAcceptance","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"customerAcceptance","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams","text":"STPMandateCustomerAcceptanceParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"customerAcceptance"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams~1customerAcceptance\/title","op":"replace","value":"customerAcceptance"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams~1customerAcceptance\/fragments","op":"replace","value":[{"text":"customerAcceptance","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/title","op":"replace","value":"STPMandateDataParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPMandateDataParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPMandateDataParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/title","op":"replace","value":"STPMandateCustomerAcceptanceParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/fragments","op":"replace","value":[{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}