{"abstract":[{"type":"text","text":"Initializes an STPMandateDataParams from an STPMandateCustomerAcceptanceParams."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpmandatedataparams\/init(customeracceptance:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpmandatedataparams\/init(customeracceptance:)"]}],"metadata":{"roleHeading":"Initializer","modules":[{"name":"StripePayments"}],"title":"init(customerAcceptance:)","navigatorTitle":[{"kind":"identifier","text":"initWithCustomerAcceptance:"}],"externalID":"c:@M@StripePayments@objc(cs)STPMandateDataParams(im)initWithCustomerAcceptance:","role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"customerAcceptance","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPMandateCustomerAcceptanceParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"customerAcceptance","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPMandateCustomerAcceptanceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams\/init(customerAcceptance:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateDataParams/init(customerAcceptance:)":{"url":"\/documentation\/stripepayments\/stpmandatedataparams\/init(customeracceptance:)","abstract":[{"text":"Initializes an STPMandateDataParams from an STPMandateCustomerAcceptanceParams.","type":"text"}],"role":"symbol","title":"init(customerAcceptance:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"customerAcceptance"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPMandateCustomerAcceptanceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"initWithCustomerAcceptance:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams\/init(customerAcceptance:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateDataParams":{"abstract":[{"type":"text","text":"This object contains details about the Mandate to create. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateDataParams","url":"\/documentation\/stripepayments\/stpmandatedataparams","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPMandateDataParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPMandateDataParams","kind":"identifier"}],"role":"symbol","title":"STPMandateDataParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPMandateCustomerAcceptanceParams":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpmandatecustomeracceptanceparams","title":"STPMandateCustomerAcceptanceParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams","abstract":[{"text":"An object that contains details about the customer acceptance of the Mandate. - seealso: https:\/\/stripe.com\/docs\/api\/payment_intents\/confirm#confirm_payment_intent-mandate_data-customer_acceptance","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCustomerAcceptance:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCustomerAcceptance:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithCustomerAcceptance:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPMandateCustomerAcceptanceParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPMandateCustomerAcceptanceParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPMandateCustomerAcceptanceParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"customerAcceptance"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams~1init(customerAcceptance:)\/title","op":"replace","value":"initWithCustomerAcceptance:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams~1init(customerAcceptance:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCustomerAcceptance:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/title","value":"STPMandateDataParams","op":"replace"},{"value":[{"text":"STPMandateDataParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateDataParams\/navigatorTitle","value":[{"text":"STPMandateDataParams","kind":"identifier"}],"op":"replace"},{"value":"STPMandateCustomerAcceptanceParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/title"},{"value":[{"text":"STPMandateCustomerAcceptanceParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPMandateCustomerAcceptanceParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPMandateCustomerAcceptanceParams"}],"op":"replace"}]}]}