{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/canAddPaymentPass()"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canAddPaymentPass"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"title":"canAddPaymentPass()","externalID":"c:@M@Stripe@objc(cs)STPFakeAddPaymentPassViewController(cm)canAddPaymentPass","role":"symbol","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canAddPaymentPass"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"canAddPaymentPass"}],"roleHeading":"Type Method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/canaddpaymentpass()"]},{"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/canaddpaymentpass()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/canAddPaymentPass()":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/canAddPaymentPass()","navigatorTitle":[{"text":"canAddPaymentPass","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"canAddPaymentPass","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"canAddPaymentPass()","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/canaddpaymentpass()"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"type":"topic","title":"Stripe","url":"\/documentation\/stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController","title":"STPFakeAddPaymentPassViewController","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"abstract":[{"type":"text","text":"This class is a piece of fake UI that is intended to mimic "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":", and can be used to develop against the Stripe API in "},{"inlineContent":[{"type":"text","text":"testmode only"}],"type":"emphasis"},{"type":"text","text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to "},{"type":"codeVoice","code":"STPFakeAddPaymentPassViewController"},{"type":"text","text":" in your app with "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets .","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"canAddPaymentPass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"canAddPaymentPass"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"canAddPaymentPass","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1canAddPaymentPass()\/title","value":"canAddPaymentPass"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1canAddPaymentPass()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"canAddPaymentPass","kind":"identifier"}]},{"value":"STPFakeAddPaymentPassViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/fragments"},{"value":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/navigatorTitle"}]}]}