{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/delegate","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPFakeAddPaymentPassViewController(py)delegate","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PKAddPaymentPassViewControllerDelegate","preciseIdentifier":"c:objc(pl)PKAddPaymentPassViewControllerDelegate"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"Stripe"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PKAddPaymentPassViewControllerDelegate","preciseIdentifier":"c:objc(pl)PKAddPaymentPassViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/delegate"]},{"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/delegate":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/delegate","type":"topic","title":"delegate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PKAddPaymentPassViewControllerDelegate","text":"PKAddPaymentPassViewControllerDelegate"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController":{"role":"symbol","abstract":[{"text":"This class is a piece of fake UI that is intended to mimic ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"text":", and can be used to develop against the Stripe API in ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"testmode only"}]},{"type":"text","text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to "},{"type":"codeVoice","code":"STPFakeAddPaymentPassViewController"},{"text":" in your app with ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController","title":"STPFakeAddPaymentPassViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller","navigatorTitle":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"title":"Stripe","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/stripe","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<PKAddPaymentPassViewControllerDelegate>","preciseIdentifier":"c:Qoobjc(pl)PKAddPaymentPassViewControllerDelegate"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1delegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/title","value":"STPFakeAddPaymentPassViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/fragments","value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/navigatorTitle","value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}