{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initWithRequestConfiguration:delegate:) "},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"requestConfiguration","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","text":"PKAddPaymentPassRequestConfiguration"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)PKAddPaymentPassViewControllerDelegate","text":"PKAddPaymentPassViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(requestconfiguration:delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(requestconfiguration:delegate:)"]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"requestConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration","text":"PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"PKAddPaymentPassViewControllerDelegate","preciseIdentifier":"c:objc(pl)PKAddPaymentPassViewControllerDelegate","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","role":"symbol","modules":[{"name":"Stripe"}],"title":"init(requestConfiguration:delegate:)","externalID":"c:@M@Stripe@objc(cs)STPFakeAddPaymentPassViewController(im)initWithRequestConfiguration:delegate:","symbolKind":"init","navigatorTitle":[{"text":"initWithRequestConfiguration:delegate:","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(requestConfiguration:delegate:)"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","abstract":[],"type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController":{"abstract":[{"type":"text","text":"This class is a piece of fake UI that is intended to mimic "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":", and can be used to develop against the Stripe API in "},{"type":"emphasis","inlineContent":[{"type":"text","text":"testmode only"}]},{"text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to ","type":"text"},{"code":"STPFakeAddPaymentPassViewController","type":"codeVoice"},{"text":" in your app with ","type":"text"},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}],"kind":"symbol","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller","navigatorTitle":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController","title":"STPFakeAddPaymentPassViewController","type":"topic","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/init(requestConfiguration:delegate:)":{"title":"init(requestConfiguration:delegate:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithRequestConfiguration:delegate:"}],"type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"requestConfiguration"},{"text":": ","kind":"text"},{"text":"PKAddPaymentPassRequestConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PKAddPaymentPassViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)PKAddPaymentPassViewControllerDelegate"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(requestConfiguration:delegate:)","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(requestconfiguration:delegate:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithRequestConfiguration:delegate:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithRequestConfiguration:delegate:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRequestConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"PKAddPaymentPassRequestConfiguration","preciseIdentifier":"c:objc(cs)PKAddPaymentPassRequestConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":" "},{"text":"delegate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<PKAddPaymentPassViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)PKAddPaymentPassViewControllerDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/title","value":"STPFakeAddPaymentPassViewController"},{"value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/fragments"},{"value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(requestConfiguration:delegate:)\/title","value":"initWithRequestConfiguration:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(requestConfiguration:delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithRequestConfiguration:delegate:","kind":"identifier"}]}]}]}