{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Initializer","title":"init(coder:)","symbolKind":"init","modules":[{"name":"Stripe"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"externalID":"c:@M@Stripe@objc(cs)STPFakeAddPaymentPassViewController(im)initWithCoder:"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(coder:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":":nodoc:"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":" "},{"text":"aDecoder","kind":"internalParam"},{"kind":"text","text":": "},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(coder:)"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController":{"abstract":[{"type":"text","text":"This class is a piece of fake UI that is intended to mimic "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":", and can be used to develop against the Stripe API in "},{"type":"emphasis","inlineContent":[{"type":"text","text":"testmode only"}]},{"text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to ","type":"text"},{"code":"STPFakeAddPaymentPassViewController","type":"codeVoice"},{"text":" in your app with ","type":"text"},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}],"kind":"symbol","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller","navigatorTitle":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController","title":"STPFakeAddPaymentPassViewController","type":"topic","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","title":"Stripe","abstract":[],"type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/init(coder:)":{"title":"init(coder:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(coder:)","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(coder:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithCoder:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"aDecoder"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/title","value":"STPFakeAddPaymentPassViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/fragments","value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/navigatorTitle","value":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"op":"replace"},{"value":"initWithCoder:","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(coder:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]}]}]}