{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(nibname:bundle:)"]},{"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(nibname:bundle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nibName"},{"text":" ","kind":"text"},{"text":"nibNameOrNil","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":" "},{"text":"nibBundleOrNil","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"Bundle"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(nibName:bundle:)"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"nibName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"bundle"},{"text":": ","kind":"text"},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"text":"?)","kind":"text"}],"modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPFakeAddPaymentPassViewController(im)initWithNibName:bundle:","role":"symbol","symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"title":"init(nibName:bundle:)"},"abstract":[{"type":"text","text":":nodoc:"}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/init(nibName:bundle:)":{"title":"init(nibName:bundle:)","role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"nibName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"bundle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"Bundle"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/init(nibname:bundle:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/init(nibName:bundle:)","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController":{"navigatorTitle":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController","title":"STPFakeAddPaymentPassViewController","type":"topic","role":"symbol","abstract":[{"text":"This class is a piece of fake UI that is intended to mimic ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as ","type":"text"},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":", and can be used to develop against the Stripe API in "},{"type":"emphasis","inlineContent":[{"text":"testmode only","type":"text"}]},{"type":"text","text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to "},{"code":"STPFakeAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":" in your app with "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic","url":"\/documentation\/stripe","title":"Stripe","role":"collection","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithNibName:bundle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNibName:bundle:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithNibName:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"nibNameOrNil","kind":"internalParam"},{"kind":"text","text":" "},{"text":"bundle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSBundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *) "},{"text":"nibBundleOrNil","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(nibName:bundle:)\/title","op":"replace","value":"initWithNibName:bundle:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1init(nibName:bundle:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}]},{"value":"STPFakeAddPaymentPassViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/fragments","value":[{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/navigatorTitle","value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}