{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/viewDidLoad()","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"metadata":{"role":"symbol","externalID":"c:@M@Stripe@objc(cs)STPFakeAddPaymentPassViewController(im)viewDidLoad","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"title":"viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"Stripe"}],"roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/viewdidload()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/viewdidload()"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController/viewDidLoad()":{"role":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"viewDidLoad()","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController\/viewDidLoad()","kind":"symbol","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller\/viewdidload()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPFakeAddPaymentPassViewController":{"navigatorTitle":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"title":"STPFakeAddPaymentPassViewController","url":"\/documentation\/stripe\/stpfakeaddpaymentpassviewcontroller","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This class is a piece of fake UI that is intended to mimic "},{"type":"codeVoice","code":"PKAddPaymentPassViewController"},{"type":"text","text":". That class is restricted to apps with a special entitlement from Apple, and as such can be difficult to build and test against. This class implements the same public API as "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"text":", and can be used to develop against the Stripe API in ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"testmode only"}]},{"type":"text","text":". (Obviously it will not actually place cards into the user’s Apple Pay wallet either.) When it’s time to go to production, you may simply replace all references to "},{"code":"STPFakeAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":" in your app with "},{"code":"PKAddPaymentPassViewController","type":"codeVoice"},{"type":"text","text":" and it will continue to function. For more information on developing against this API, please see https:\/\/stripe.com\/docs\/issuing\/cards\/digital-wallets ."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPFakeAddPaymentPassViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPFakeAddPaymentPassViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","title":"Stripe","url":"\/documentation\/stripe","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLoad"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidLoad"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1viewDidLoad()\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController~1viewDidLoad()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}]},{"value":"STPFakeAddPaymentPassViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/title"},{"value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPFakeAddPaymentPassViewController\/navigatorTitle","value":[{"kind":"identifier","text":"STPFakeAddPaymentPassViewController"}],"op":"replace"}]}]}