{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"country"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodsofortparams\/country"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodsofortparams\/country"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Two-letter ISO code representing the country the bank account is located in. Required."}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams\/country","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"country"}],"title":"country","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodSofortParams(py)country","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"country","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSofortParams":{"navigatorTitle":[{"text":"STPPaymentMethodSofortParams","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodSofortParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Sofort Payment Method"}],"title":"STPPaymentMethodSofortParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodsofortparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSofortParams/country":{"url":"\/documentation\/stripepayments\/stppaymentmethodsofortparams\/country","abstract":[{"type":"text","text":"Two-letter ISO code representing the country the bank account is located in. Required."}],"role":"symbol","navigatorTitle":[{"text":"country","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"country"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams\/country","title":"country"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"country"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"country","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"country","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentMethodSofortParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodSofortParams"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodSofortParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams~1country\/title","op":"replace","value":"country"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams~1country\/fragments","value":[{"kind":"identifier","text":"country"}],"op":"replace"}]}]}