{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"init","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodSofortParams(im)init","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodsofortparams\/init"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams\/init"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSofortParams":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodSofortParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodsofortparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodSofortParams"}],"kind":"symbol","title":"STPPaymentMethodSofortParams","abstract":[{"text":"An object representing parameters used to create a Sofort Payment Method","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSofortParams/init":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams\/init","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodsofortparams\/init","abstract":[],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams\/title","value":"STPPaymentMethodSofortParams"},{"value":[{"kind":"identifier","text":"STPPaymentMethodSofortParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodSofortParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}