{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddress"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetails\/address"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetails\/address"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails"]]},"abstract":[{"type":"text","text":"Shipping address."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails\/address","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddress"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"address","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"address"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails(py)address"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsAddress":{"navigatorTitle":[{"text":"STPPaymentIntentShippingDetailsAddress","kind":"identifier"}],"title":"STPPaymentIntentShippingDetailsAddress","abstract":[{"text":"Shipping address for a PaymentIntent’s shipping details.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"code":"STPPaymentIntentShippingDetailsAddress","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"You should only use one that is part of an existing ","type":"text"},{"code":"STPPaymentMethod","type":"codeVoice"},{"text":" object.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsaddress","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsAddress","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetails/address":{"title":"address","role":"symbol","navigatorTitle":[{"text":"address","kind":"identifier"}],"abstract":[{"type":"text","text":"Shipping address."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails\/address","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentshippingdetails\/address","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetails":{"type":"topic","navigatorTitle":[{"text":"STPPaymentIntentShippingDetails","kind":"identifier"}],"abstract":[{"type":"text","text":"Shipping information for a PaymentIntent"},{"type":"text","text":" "},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPPaymentIntentShippingDetails"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"You should only use one that is part of an existing "},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails","url":"\/documentation\/stripepayments\/stppaymentintentshippingdetails","title":"STPPaymentIntentShippingDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetails","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"address"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"address"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"STPPaymentIntentShippingDetailsAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddress"},{"kind":"text","text":" * "},{"kind":"identifier","text":"address"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddress\/title","value":"STPPaymentIntentShippingDetailsAddress"},{"value":[{"text":"STPPaymentIntentShippingDetailsAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddress\/fragments","op":"replace"},{"value":[{"text":"STPPaymentIntentShippingDetailsAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddress\/navigatorTitle","op":"replace"},{"value":"address","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails~1address\/title","op":"replace"},{"value":[{"text":"address","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails~1address\/fragments","op":"replace"},{"value":"STPPaymentIntentShippingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentShippingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/fragments","op":"replace"},{"value":[{"text":"STPPaymentIntentShippingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}