{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetails\/trackingnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetails\/trackingnumber"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackingNumber"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The tracking number for a physical product, obtained from the delivery service. If multiple tracking numbers were generated for this purchase, please separate them with commas."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails"]]},"metadata":{"modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails(py)trackingNumber","roleHeading":"Instance Property","title":"trackingNumber","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trackingNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"trackingNumber","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails\/trackingNumber","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetails/trackingNumber":{"title":"trackingNumber","abstract":[{"type":"text","text":"The tracking number for a physical product, obtained from the delivery service. If multiple tracking numbers were generated for this purchase, please separate them with commas."}],"navigatorTitle":[{"text":"trackingNumber","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"trackingNumber","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails\/trackingNumber","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentshippingdetails\/trackingnumber"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetails":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetails","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetails","title":"STPPaymentIntentShippingDetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentShippingDetails"}],"type":"topic","abstract":[{"type":"text","text":"Shipping information for a PaymentIntent"},{"text":" ","type":"text"},{"type":"text","text":"You cannot directly instantiate an "},{"type":"codeVoice","code":"STPPaymentIntentShippingDetails"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"You should only use one that is part of an existing "},{"code":"STPPaymentMethod","type":"codeVoice"},{"text":" object.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintentshippingdetails"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"trackingNumber"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"trackingNumber"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"trackingNumber"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails~1trackingNumber\/title","value":"trackingNumber"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails~1trackingNumber\/fragments","value":[{"kind":"identifier","text":"trackingNumber"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/title","value":"STPPaymentIntentShippingDetails","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetails"}]},{"value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetails\/navigatorTitle"}]}]}