{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBLIKParams"]]},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rootObjectName","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"title":"rootObjectName()","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodBLIKParams(cm)rootObjectName","modules":[{"name":"StripePayments"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBLIKParams\/rootObjectName()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"type":"text","text":" below."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodblikparams\/rootobjectname()"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodblikparams\/rootobjectname()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBLIKParams/rootObjectName()":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBLIKParams\/rootObjectName()","url":"\/documentation\/stripepayments\/stppaymentmethodblikparams\/rootobjectname()","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"kind":"symbol","role":"symbol","title":"rootObjectName()","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBLIKParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a BLIK Payment Method"},{"text":" ","type":"text"},{"type":"text","text":"There are currently no parameters to pass."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBLIKParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBLIKParams","navigatorTitle":[{"text":"STPPaymentMethodBLIKParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodblikparams","role":"symbol","type":"topic","kind":"symbol","title":"STPPaymentMethodBLIKParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rootObjectName","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBLIKParams~1rootObjectName()\/title","value":"rootObjectName"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBLIKParams~1rootObjectName()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"rootObjectName","kind":"identifier"}]},{"op":"replace","value":"STPPaymentMethodBLIKParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBLIKParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBLIKParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodBLIKParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBLIKParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBLIKParams"}]}]}]}