{"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams(py)carrier","title":"carrier","navigatorTitle":[{"kind":"identifier","text":"carrier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"carrier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams\/carrier"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams\/carrier"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams\/carrier","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"carrier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams"]]},"abstract":[{"type":"text","text":"The delivery service that shipped a physical product, such as Fedex, UPS, USPS, etc."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsParams/carrier":{"url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams\/carrier","navigatorTitle":[{"text":"carrier","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams\/carrier","abstract":[{"type":"text","text":"The delivery service that shipped a physical product, such as Fedex, UPS, USPS, etc."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"carrier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"carrier"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsParams":{"url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams","role":"symbol","abstract":[{"text":"Shipping information for a PaymentIntent","type":"text"}],"title":"STPPaymentIntentShippingDetailsParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"carrier","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"carrier","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"carrier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams~1carrier\/title","value":"carrier","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams~1carrier\/fragments","value":[{"kind":"identifier","text":"carrier"}]},{"value":"STPPaymentIntentShippingDetailsParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/title"},{"value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}]}]}]}