{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams\/init(address:name:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","modules":[{"name":"StripePayments"}],"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithAddress:name:","kind":"identifier"}],"title":"init(address:name:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddressParams","text":"STPPaymentIntentShippingDetailsAddressParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsParams(im)initWithAddress:name:"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsAddressParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddressParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddressParams"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams"]]},"abstract":[{"text":"Initialize an ","type":"text"},{"type":"codeVoice","code":"STPPaymentIntentShippingDetailsParams"},{"text":" with required properties.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams\/init(address:name:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams\/init(address:name:)"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsParams/init(address:name:)":{"url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams\/init(address:name:)","role":"symbol","type":"topic","title":"init(address:name:)","kind":"symbol","abstract":[{"text":"Initialize an ","type":"text"},{"code":"STPPaymentIntentShippingDetailsParams","type":"codeVoice"},{"text":" with required properties.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams\/init(address:name:)","navigatorTitle":[{"kind":"identifier","text":"initWithAddress:name:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddressParams","kind":"typeIdentifier","text":"STPPaymentIntentShippingDetailsAddressParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsAddressParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddressParams","url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsaddressparams","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsAddressParams","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Shipping address for a PaymentIntent’s shipping details."}],"title":"STPPaymentIntentShippingDetailsAddressParams","role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentShippingDetailsAddressParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentShippingDetailsParams":{"type":"topic","kind":"symbol","title":"STPPaymentIntentShippingDetailsParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentShippingDetailsParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintentshippingdetailsparams","abstract":[{"type":"text","text":"Shipping information for a PaymentIntent"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentShippingDetailsParams","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithAddress:name:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAddress:name:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAddress:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentShippingDetailsAddressParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetailsAddressParams","kind":"typeIdentifier","text":"STPPaymentIntentShippingDetailsAddressParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"address"},{"kind":"text","text":" "},{"kind":"identifier","text":"name:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams~1init(address:name:)\/title","value":"initWithAddress:name:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams~1init(address:name:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAddress:name:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddressParams\/title","value":"STPPaymentIntentShippingDetailsAddressParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddressParams\/fragments","value":[{"text":"STPPaymentIntentShippingDetailsAddressParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsAddressParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsAddressParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/title","value":"STPPaymentIntentShippingDetailsParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentShippingDetailsParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntentShippingDetailsParams"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}