{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addCardViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"addCardViewController","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","kind":"typeIdentifier","text":"STPAddCardViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"kind":"text","text":" "},{"kind":"internalParam","text":"paymentMethod"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","text":"STPPaymentMethod","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"typeIdentifier","text":"STPErrorBlock","preciseIdentifier":"s:14StripePayments13STPErrorBlocka"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"parameters":[{"name":"addCardViewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the view controller that successfully created a token"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"the Payment Method that was created. - seealso: STPPaymentMethod"}],"type":"paragraph"}],"name":"paymentMethod"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"call this callback when you’re done sending the token to your backend","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","metadata":{"title":"addCardViewController(_:didCreatePaymentMethod:completion:)","navigatorTitle":[{"kind":"identifier","text":"addCardViewController:didCreatePaymentMethod:completion:"}],"modules":[{"name":"Stripe"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","text":"STPAddCardViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments13STPErrorBlocka","kind":"typeIdentifier","text":"STPErrorBlock"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController(im)addCardViewController:didCreatePaymentMethod:completion:","symbolKind":"method","role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewController(_:didCreatePaymentMethod:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"]]},"abstract":[{"type":"text","text":"This is called when the user successfully adds a card and Stripe returns a"},{"type":"text","text":" "},{"type":"text","text":"Payment Method."},{"type":"text","text":" "},{"text":"You should send the PaymentMethod to your backend to store it on a customer, and then","type":"text"},{"type":"text","text":" "},{"type":"text","text":"call the provided "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when that call is finished. If an error"},{"type":"text","text":" "},{"type":"text","text":"occurs while talking to your backend, call "},{"type":"codeVoice","code":"completion(error)"},{"type":"text","text":", otherwise,"},{"type":"text","text":" "},{"text":"dismiss (or pop) the view controller.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/addcardviewcontroller(_:didcreatepaymentmethod:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/addcardviewcontroller(_:didcreatepaymentmethod:completion:)"]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/addCardViewController(_:didCreatePaymentMethod:completion:)":{"kind":"symbol","abstract":[{"text":"This is called when the user successfully adds a card and Stripe returns a","type":"text"},{"type":"text","text":" "},{"text":"Payment Method.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You should send the PaymentMethod to your backend to store it on a customer, and then"},{"type":"text","text":" "},{"type":"text","text":"call the provided "},{"type":"codeVoice","code":"completion"},{"type":"text","text":" block when that call is finished. If an error"},{"text":" ","type":"text"},{"text":"occurs while talking to your backend, call ","type":"text"},{"code":"completion(error)","type":"codeVoice"},{"type":"text","text":", otherwise,"},{"type":"text","text":" "},{"text":"dismiss (or pop) the view controller.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCardViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","kind":"typeIdentifier","text":"STPAddCardViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didCreatePaymentMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments13STPErrorBlocka","kind":"typeIdentifier","text":"STPErrorBlock"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/addCardViewController(_:didCreatePaymentMethod:completion:)","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/addcardviewcontroller(_:didcreatepaymentmethod:completion:)","role":"symbol","title":"addCardViewController(_:didCreatePaymentMethod:completion:)","type":"topic","navigatorTitle":[{"text":"addCardViewController:didCreatePaymentMethod:completion:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripe\/stppaymentmethod","title":"STPPaymentMethod","abstract":[{"text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethod","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPErrorBlock":{"url":"\/documentation\/stripe\/stperrorblock","navigatorTitle":[{"text":"STPErrorBlock","kind":"identifier"}],"abstract":[{"text":"A block that may optionally be called with an error.","type":"text"}],"title":"STPErrorBlock","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPErrorBlock","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPErrorBlock","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPAddCardViewController":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController","url":"\/documentation\/stripe\/stpaddcardviewcontroller","role":"symbol","navigatorTitle":[{"text":"STPAddCardViewController","kind":"identifier"}],"abstract":[{"text":"This view controller contains a credit card entry form that the user can fill out. On submission, it will use the Stripe API to convert the user’s card details to a Stripe token. It renders a right bar button item that submits the form, so it must be shown inside a ","type":"text"},{"code":"UINavigationController","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAddCardViewController"}],"title":"STPAddCardViewController"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"title":"STPPaymentOptionsViewController","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller","navigatorTitle":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","role":"symbol","abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"text":" ","type":"text"},{"text":"which they can select between. They can also add credit cards to the list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":", so you can either","type":"text"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"as the ","type":"text"},{"type":"codeVoice","code":"rootViewController"},{"text":" and then present the ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"text":"or push a new ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"addCardViewController:didCreatePaymentMethod:completion:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addCardViewController:didCreatePaymentMethod:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"addCardViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPAddCardViewController","preciseIdentifier":"c:@M@Stripe@objc(cs)STPAddCardViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPAddCardViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"addCardViewController"},{"kind":"text","text":" "},{"text":"didCreatePaymentMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","kind":"typeIdentifier","text":"STPPaymentMethod","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentMethod"},{"kind":"text","text":" *) "},{"text":"paymentMethod","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSError)","text":"void (^)(NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"addCardViewController:didCreatePaymentMethod:completion:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1addCardViewController(_:didCreatePaymentMethod:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1addCardViewController(_:didCreatePaymentMethod:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addCardViewController:didCreatePaymentMethod:completion:","kind":"identifier"}]},{"value":"STPAddCardViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPAddCardViewController\/fragments","value":[{"text":"STPAddCardViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","value":"STPPaymentOptionsViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","op":"replace","value":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}]}]}]}
