{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultPaymentMethod","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"payment method using NSUserDefaults and displays it as the default pre-selected option.  You can override this behavior"},{"type":"text","text":" "},{"text":"by setting this property.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The Stripe ID of a payment method to display as the default pre-selected option."}]}],"kind":"content"}],"sections":[],"metadata":{"externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController(py)defaultPaymentMethod","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultPaymentMethod","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"defaultPaymentMethod"}],"roleHeading":"Instance Property","title":"defaultPaymentMethod","role":"symbol","modules":[{"name":"Stripe"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/defaultpaymentmethod"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/defaultpaymentmethod"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/defaultPaymentMethod"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"title":"STPPaymentOptionsViewController","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller","navigatorTitle":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","role":"symbol","abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"text":" ","type":"text"},{"text":"which they can select between. They can also add credit cards to the list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":", so you can either","type":"text"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"as the ","type":"text"},{"type":"codeVoice","code":"rootViewController"},{"text":" and then present the ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"text":"or push a new ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/defaultPaymentMethod":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultPaymentMethod"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/defaultPaymentMethod","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/defaultpaymentmethod","role":"symbol","title":"defaultPaymentMethod","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultPaymentMethod"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"defaultPaymentMethod"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"defaultPaymentMethod"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"defaultPaymentMethod","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"STPPaymentOptionsViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]},{"op":"replace","value":"defaultPaymentMethod","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1defaultPaymentMethod\/title"},{"value":[{"kind":"identifier","text":"defaultPaymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1defaultPaymentMethod\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
