{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(dismissWithCompletion:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCompletion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPVoidBlock-2384d","preciseIdentifier":"s:14StripePayments12STPVoidBlocka","text":"STPVoidBlock"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback to run after the view controller is dismissed."},{"type":"text","text":" "},{"type":"text","text":"You may specify nil for this parameter."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/dismiss(withcompletion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/dismiss(withcompletion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/dismiss(withCompletion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If you’re pushing "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" onto an existing"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"‘s stack, you should use this method to dismiss it,"},{"type":"text","text":" "},{"type":"text","text":"since it may have pushed an additional add card view controller onto the"},{"type":"text","text":" "},{"type":"text","text":"navigation controller’s stack."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCompletion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"kind":"text","text":"?)"}],"title":"dismiss(withCompletion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController(im)dismissWithCompletion:","modules":[{"name":"Stripe"}],"navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"]]},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"role":"collection","title":"Stripe","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","url":"\/documentation\/stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPVoidBlock-2384d":{"role":"symbol","title":"STPVoidBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPVoidBlock"}],"abstract":[{"type":"text","text":"An empty block, called with no arguments, returning nothing."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPVoidBlock-2384d","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPVoidBlock"}],"url":"\/documentation\/stripe\/stpvoidblock-2384d"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/dismiss(withCompletion:)":{"role":"symbol","title":"dismiss(withCompletion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withCompletion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"If you’re pushing "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" onto an existing"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"‘s stack, you should use this method to dismiss it,"},{"type":"text","text":" "},{"type":"text","text":"since it may have pushed an additional add card view controller onto the"},{"type":"text","text":" "},{"type":"text","text":"navigation controller’s stack."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/dismiss(withCompletion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/dismiss(withcompletion:)"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"role":"symbol","title":"STPPaymentOptionsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"type":"text","text":" "},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":", so you can either"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"as the "},{"type":"codeVoice","code":"rootViewController"},{"type":"text","text":" and then present the "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":" onto an existing"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"type":"codeVoice","code":"presentPaymentOptionsViewController"},{"type":"text","text":" "},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dismissWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissWithCompletion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dismissWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1dismiss(withCompletion:)\/title","value":"dismissWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1dismiss(withCompletion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","value":"STPPaymentOptionsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
