{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:customerContext:delegate:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"]]},"abstract":[{"type":"text","text":"Initializes a new payment methods view controller without using a"},{"type":"text","text":" "},{"type":"text","text":"payment context."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController(im)initWithConfiguration:theme:customerContext:delegate:","role":"symbol","modules":[{"name":"Stripe"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithConfiguration:theme:customerContext:delegate:","kind":"identifier"}],"title":"init(configuration:theme:customerContext:delegate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"text":", ","kind":"text"},{"text":"customerContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCustomerContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"text":", ","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate","text":"STPPaymentOptionsViewControllerDelegate"},{"kind":"text","text":")"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithConfiguration:theme:customerContext:delegate:) "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"theme","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"customerContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCustomerContext","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","text":"STPPaymentOptionsViewControllerDelegate"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"The configuration to use to determine what types of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"payment method to offer your user. - seealso: STPPaymentConfiguration.h"}],"type":"paragraph"}]},{"name":"theme","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The theme to inform the appearance of the UI."}]}]},{"name":"customerContext","content":[{"inlineContent":[{"text":"The customer context the view controller will use to","type":"text"},{"type":"text","text":" "},{"text":"fetch and modify its Stripe customer","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A delegate that will be notified when the payment","type":"text"},{"type":"text","text":" "},{"text":"methods view controller’s selection changes.","type":"text"}],"type":"paragraph"}],"name":"delegate"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"an initialized view controller."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(configuration:theme:customercontext:delegate:)"]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(configuration:theme:customercontext:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"type":"topic","title":"STPPaymentConfiguration","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"text":" ","type":"text"},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"text":"will not change from payment to payment and thus is reusable, while the context","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentconfiguration","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate","title":"STPPaymentOptionsViewControllerDelegate","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","kind":"symbol","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentOptionsViewControllerDelegate"},{"type":"text","text":" responds when a user selects a"},{"text":" ","type":"text"},{"type":"text","text":"payment option from (or cancels) an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":". In both"},{"text":" ","type":"text"},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"type":"text","text":" "},{"text":"it off the navigation stack, or dismissing it).","type":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"title":"STPPaymentOptionsViewController","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller","navigatorTitle":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","role":"symbol","abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"text":" ","type":"text"},{"text":"which they can select between. They can also add credit cards to the list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":", so you can either","type":"text"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"as the ","type":"text"},{"type":"codeVoice","code":"rootViewController"},{"text":" and then present the ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"text":"or push a new ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/init(configuration:theme:customerContext:delegate:)":{"kind":"symbol","abstract":[{"text":"Initializes a new payment methods view controller without using a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"payment context."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"theme","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","text":"STPTheme"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customerContext"},{"text":": ","kind":"text"},{"text":"STPCustomerContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"text":"STPPaymentOptionsViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:customerContext:delegate:)","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(configuration:theme:customercontext:delegate:)","role":"symbol","title":"init(configuration:theme:customerContext:delegate:)","type":"topic","navigatorTitle":[{"text":"initWithConfiguration:theme:customerContext:delegate:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","type":"topic","abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"title":"STPTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTheme","kind":"identifier"}],"url":"\/documentation\/stripe\/stptheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCustomerContext":{"kind":"symbol","abstract":[{"text":"An ","type":"text"},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" retrieves and updates a Stripe customer and their attached","type":"text"},{"type":"text","text":" "},{"text":"payment methods using an ephemeral key, a short-lived API key scoped to a specific","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"customer object. If your current user logs out of your app and a new user logs in,"},{"type":"text","text":" "},{"type":"text","text":"be sure to either create a new instance of "},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":" or clear the current"},{"text":" ","type":"text"},{"text":"instance’s cache. On your backend, be sure to create and return a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"new ephemeral key for the Customer object associated with the new user."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCustomerContext","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","url":"\/documentation\/stripe\/stpcustomercontext","role":"symbol","title":"STPCustomerContext","type":"topic","navigatorTitle":[{"text":"STPCustomerContext","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithConfiguration:theme:customerContext:delegate:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:theme:customerContext:delegate:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","kind":"typeIdentifier","text":"STPPaymentConfiguration","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"theme:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier","text":"STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"theme"},{"text":" ","kind":"text"},{"text":"customerContext:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPCustomerContext","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCustomerContext","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPCustomerContext"},{"kind":"text","text":" *) "},{"text":"customerContext","kind":"internalParam"},{"kind":"text","text":" "},{"text":"delegate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<STPPaymentOptionsViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate"},{"text":" *) ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","value":"STPPaymentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments","value":[{"text":"STPPaymentConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/title","op":"replace","value":"STPPaymentOptionsViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/fragments","value":[{"text":"STPPaymentOptionsViewControllerDelegate","kind":"identifier"}]},{"value":"STPPaymentOptionsViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"op":"replace"},{"value":"initWithConfiguration:theme:customerContext:delegate:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(configuration:theme:customerContext:delegate:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:theme:customerContext:delegate:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(configuration:theme:customerContext:delegate:)\/fragments"},{"value":"STPTheme","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPTheme"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments"},{"value":"STPCustomerContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCustomerContext\/fragments","value":[{"text":"STPCustomerContext","kind":"identifier"}]}]}]}
