{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithConfiguration:theme:apiAdapter:delegate:) "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","text":"STPPaymentConfiguration"},{"kind":"text","text":", "},{"text":"theme","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","text":"STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme"},{"text":", ","kind":"text"},{"text":"apiAdapter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPBackendAPIAdapter","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","kind":"typeIdentifier","text":"STPPaymentOptionsViewControllerDelegate","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The configuration to use to determine what types of"},{"type":"text","text":" "},{"type":"text","text":"payment method to offer your user."}]}]},{"name":"theme","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The theme to inform the appearance of the UI."}]}]},{"name":"apiAdapter","content":[{"inlineContent":[{"text":"The API adapter to use to retrieve a customer’s stored","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"payment methods and save new ones."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"A delegate that will be notified when the payment methods","type":"text"},{"type":"text","text":" "},{"type":"text","text":"view controller’s selection changes."}],"type":"paragraph"}],"name":"delegate"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(configuration:theme:apiadapter:delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(configuration:theme:apiadapter:delegate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"init(configuration:theme:apiAdapter:delegate:)","roleHeading":"Initializer","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"theme"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","text":"STPTheme"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"apiAdapter"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","text":"STPBackendAPIAdapter","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate","text":"STPPaymentOptionsViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithConfiguration:theme:apiAdapter:delegate:","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController(im)initWithConfiguration:theme:apiAdapter:delegate:","modules":[{"name":"Stripe"}],"symbolKind":"init"},"abstract":[{"text":"Note: Instead of providing your own backend API adapter, we recommend using","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPCustomerContext"},{"type":"text","text":", which will manage retrieving and updating a"},{"text":" ","type":"text"},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"type":"text","text":" "},{"type":"text","text":"Initializes a new payment methods view controller without using"},{"type":"text","text":" "},{"text":"a payment context.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:apiAdapter:delegate:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"title":"STPPaymentOptionsViewController","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller","navigatorTitle":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","role":"symbol","abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"text":" ","type":"text"},{"text":"which they can select between. They can also add credit cards to the list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":", so you can either","type":"text"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"as the ","type":"text"},{"type":"codeVoice","code":"rootViewController"},{"text":" and then present the ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"text":"or push a new ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewController","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentConfiguration":{"type":"topic","title":"STPPaymentConfiguration","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"type":"text","text":" represents all the options you can set or change"},{"text":" ","type":"text"},{"type":"text","text":"around a payment."},{"type":"text","text":" "},{"text":"You provide an ","type":"text"},{"type":"codeVoice","code":"STPPaymentConfiguration"},{"text":" object to your ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" "},{"text":"when making a charge. The configuration generally has settings that","type":"text"},{"text":" ","type":"text"},{"text":"will not change from payment to payment and thus is reusable, while the context","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is specific to a single particular payment instance."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentConfiguration","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentconfiguration","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","role":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPBackendAPIAdapter":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPBackendAPIAdapter","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripe\/stpbackendapiadapter","title":"STPBackendAPIAdapter","abstract":[{"type":"text","text":"A “bridge” from our pre-built UI ("},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":", "},{"type":"codeVoice","code":"STPPaymentOptionsViewController"},{"type":"text","text":")"},{"type":"text","text":" "},{"type":"text","text":"to your backend to fetch Customer-related information needed to power those views."},{"type":"text","text":" "},{"type":"text","text":"Typically, you will not need to implement this protocol yourself. You"},{"type":"text","text":" "},{"type":"text","text":"should instead use "},{"code":"STPCustomerContext","type":"codeVoice"},{"type":"text","text":", which implements "},{"text":" ","type":"text"},{"type":"text","text":"and manages retrieving and updating a Stripe customer for you."}],"navigatorTitle":[{"kind":"identifier","text":"STPBackendAPIAdapter"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPBackendAPIAdapter","kind":"symbol"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewControllerDelegate":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/stripe\/stppaymentoptionsviewcontrollerdelegate","title":"STPPaymentOptionsViewControllerDelegate","type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewControllerDelegate","kind":"symbol","abstract":[{"type":"text","text":"An "},{"type":"codeVoice","code":"STPPaymentOptionsViewControllerDelegate"},{"type":"text","text":" responds when a user selects a"},{"text":" ","type":"text"},{"type":"text","text":"payment option from (or cancels) an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":". In both"},{"text":" ","type":"text"},{"type":"text","text":"of these instances, you should dismiss the view controller (either by popping"},{"type":"text","text":" "},{"text":"it off the navigation stack, or dismissing it).","type":"text"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","type":"topic","abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"title":"STPTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTheme","kind":"identifier"}],"url":"\/documentation\/stripe\/stptheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/init(configuration:theme:apiAdapter:delegate:)":{"kind":"symbol","abstract":[{"type":"text","text":"Note: Instead of providing your own backend API adapter, we recommend using"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCustomerContext"},{"text":", which will manage retrieving and updating a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Stripe customer for you. - seealso: STPCustomerContext.h"},{"text":" ","type":"text"},{"type":"text","text":"Initializes a new payment methods view controller without using"},{"text":" ","type":"text"},{"type":"text","text":"a payment context."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"theme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPTheme","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme"},{"text":", ","kind":"text"},{"text":"apiAdapter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@Stripe@objc(pl)STPBackendAPIAdapter","kind":"typeIdentifier","text":"STPBackendAPIAdapter"},{"kind":"text","text":", "},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate","text":"STPPaymentOptionsViewControllerDelegate"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/init(configuration:theme:apiAdapter:delegate:)","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/init(configuration:theme:apiadapter:delegate:)","role":"symbol","title":"init(configuration:theme:apiAdapter:delegate:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:theme:apiAdapter:delegate:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithConfiguration:theme:apiAdapter:delegate:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:theme:apiAdapter:delegate:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@Stripe@objc(cs)STPPaymentConfiguration","text":"STPPaymentConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"text":"theme:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","text":"STPTheme"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"theme"},{"kind":"text","text":" "},{"text":"apiAdapter:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPBackendAPIAdapter","text":"id<STPBackendAPIAdapter>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"apiAdapter","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate:"},{"text":"(","kind":"text"},{"text":"id<STPPaymentOptionsViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@Stripe@objc(pl)STPPaymentOptionsViewControllerDelegate"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"delegate"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"STPPaymentOptionsViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments"},{"value":"STPPaymentConfiguration","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentConfiguration"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentConfiguration\/fragments"},{"op":"replace","value":"STPBackendAPIAdapter","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPBackendAPIAdapter\/fragments","op":"replace","value":[{"text":"STPBackendAPIAdapter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/title","op":"replace","value":"STPPaymentOptionsViewControllerDelegate"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"STPPaymentOptionsViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","value":"STPTheme","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments","value":[{"kind":"identifier","text":"STPTheme"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(configuration:theme:apiAdapter:delegate:)\/title","value":"initWithConfiguration:theme:apiAdapter:delegate:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:theme:apiAdapter:delegate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1init(configuration:theme:apiAdapter:delegate:)\/fragments"}]}]}
