{"kind":"symbol","abstract":[{"text":"A view that will be placed as the footer of the view controller when it is","type":"text"},{"type":"text","text":" "},{"text":"showing a list of saved payment methods to select from.","type":"text"},{"text":" ","type":"text"},{"text":"When the footer view needs to be resized, it will be sent a","type":"text"},{"type":"text","text":" "},{"code":"sizeThatFits:","type":"codeVoice"},{"type":"text","text":" call. The view should respond correctly to this method in order"},{"type":"text","text":" "},{"type":"text","text":"to be sized and positioned properly."}],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/paymentoptionsviewcontrollerfooterview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/paymentoptionsviewcontrollerfooterview"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/paymentOptionsViewControllerFooterView","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"Stripe"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController(py)paymentOptionsViewControllerFooterView","title":"paymentOptionsViewControllerFooterView","roleHeading":"Instance Property","symbolKind":"property"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/paymentOptionsViewControllerFooterView":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"}],"title":"paymentOptionsViewControllerFooterView","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/paymentOptionsViewControllerFooterView","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/paymentoptionsviewcontrollerfooterview","kind":"symbol","abstract":[{"type":"text","text":"A view that will be placed as the footer of the view controller when it is"},{"text":" ","type":"text"},{"text":"showing a list of saved payment methods to select from.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When the footer view needs to be resized, it will be sent a"},{"type":"text","text":" "},{"type":"codeVoice","code":"sizeThatFits:"},{"type":"text","text":" call. The view should respond correctly to this method in order"},{"type":"text","text":" "},{"text":"to be sized and positioned properly.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"title":"STPPaymentOptionsViewController","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller","navigatorTitle":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","role":"symbol","abstract":[{"type":"text","text":"This view controller presents a list of payment method options to the user,"},{"text":" ","type":"text"},{"text":"which they can select between. They can also add credit cards to the list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It must be displayed inside a "},{"code":"UINavigationController","type":"codeVoice"},{"text":", so you can either","type":"text"},{"type":"text","text":" "},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"text":"as the ","type":"text"},{"type":"codeVoice","code":"rootViewController"},{"text":" and then present the ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":","},{"type":"text","text":" "},{"text":"or push a new ","type":"text"},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":"’s stack. You can also have "},{"type":"codeVoice","code":"STPPaymentContext"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"or "},{"type":"codeVoice","code":"pushPaymentOptionsViewController"},{"type":"text","text":" on it."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentOptionsViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"paymentOptionsViewControllerFooterView","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":" * ","kind":"text"},{"text":"paymentOptionsViewControllerFooterView","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1paymentOptionsViewControllerFooterView\/title","value":"paymentOptionsViewControllerFooterView"},{"value":[{"kind":"identifier","text":"paymentOptionsViewControllerFooterView"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1paymentOptionsViewControllerFooterView\/fragments"},{"value":"STPPaymentOptionsViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments"}]}]}
