{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/viewDidLayoutSubviews()"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"text":"()","kind":"text"}],"externalID":"c:@M@Stripe@objc(cs)STPPaymentOptionsViewController(im)viewDidLayoutSubviews","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"title":"viewDidLayoutSubviews()"},"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"variants":[{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/viewdidlayoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripe\/stppaymentoptionsviewcontroller\/viewdidlayoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"title":"STPPaymentOptionsViewController","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController","abstract":[{"text":"This view controller presents a list of payment method options to the user,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"which they can select between. They can also add credit cards to the list."},{"text":" ","type":"text"},{"text":"It must be displayed inside a ","type":"text"},{"type":"codeVoice","code":"UINavigationController"},{"text":", so you can either","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"create a "},{"type":"codeVoice","code":"UINavigationController"},{"type":"text","text":" with an "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"as the ","type":"text"},{"code":"rootViewController","type":"codeVoice"},{"type":"text","text":" and then present the "},{"code":"UINavigationController","type":"codeVoice"},{"text":",","type":"text"},{"type":"text","text":" "},{"type":"text","text":"or push a new "},{"code":"STPPaymentOptionsViewController","type":"codeVoice"},{"text":" onto an existing","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"UINavigationController"},{"text":"’s stack. You can also have ","type":"text"},{"code":"STPPaymentContext","type":"codeVoice"},{"type":"text","text":" do this"},{"type":"text","text":" "},{"type":"text","text":"for you automatically, by calling "},{"code":"presentPaymentOptionsViewController","type":"codeVoice"},{"type":"text","text":" "},{"text":"or ","type":"text"},{"code":"pushPaymentOptionsViewController","type":"codeVoice"},{"text":" on it.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentOptionsViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller"},"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPPaymentOptionsViewController/viewDidLayoutSubviews()":{"navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"title":"viewDidLayoutSubviews()","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPPaymentOptionsViewController\/viewDidLayoutSubviews()","abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/stripe\/stppaymentoptionsviewcontroller\/viewdidlayoutsubviews()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"viewDidLayoutSubviews","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/title","op":"replace","value":"STPPaymentOptionsViewController"},{"value":[{"text":"STPPaymentOptionsViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController\/fragments","op":"replace"},{"value":"viewDidLayoutSubviews","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1viewDidLayoutSubviews()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPPaymentOptionsViewController~1viewDidLayoutSubviews()\/fragments"}]}]}
