{"abstract":[{"type":"text","text":"The corner radius of the button. Defaults to 8."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"cornerRadius","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization(py)cornerRadius","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"modules":[{"name":"StripePayments"}],"title":"cornerRadius"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/cornerradius"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/cornerradius"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/cornerRadius","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/cornerRadius":{"title":"cornerRadius","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/cornerRadius","navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/cornerradius","abstract":[{"text":"The corner radius of the button. Defaults to 8.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization":{"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","role":"symbol","url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization","abstract":[{"type":"text","text":"A customization object to use to configure the UI of a button."}],"title":"STPThreeDSButtonCustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cornerRadius"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cornerRadius","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1cornerRadius\/title","op":"replace","value":"cornerRadius"},{"value":[{"text":"cornerRadius","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1cornerRadius\/fragments","op":"replace"},{"value":"STPThreeDSButtonCustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/fragments","op":"replace"},{"value":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}