{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/defaultsettings(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/defaultsettings(for:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/defaultSettings(for:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","text":"STPThreeDSCustomizationButtonType"},{"kind":"text","text":") -> "},{"text":"STPThreeDSButtonCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization"}],"title":"defaultSettings(for:)","navigatorTitle":[{"text":"defaultSettingsForButtonType:","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization(cm)defaultSettingsForButtonType:","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(defaultSettingsForButtonType:) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultSettings","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","text":"STPThreeDSCustomizationButtonType","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","kind":"typeIdentifier","text":"STPThreeDSButtonCustomization"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The default settings for the provided button type."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"kind":"symbol","type":"topic","title":"STPThreeDSCustomizationButtonType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","abstract":[{"text":"An enum that defines the different types of buttons that are able to be customized.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"navigatorTitle":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"navigatorTitle":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","type":"topic","title":"STPThreeDSButtonCustomization","abstract":[{"text":"A customization object to use to configure the UI of a button.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/defaultSettings(for:)":{"navigatorTitle":[{"text":"defaultSettingsForButtonType:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/defaultsettings(for:)","type":"topic","title":"defaultSettings(for:)","abstract":[{"text":"The default settings for the provided button type.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/defaultSettings(for:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","kind":"typeIdentifier","text":"STPThreeDSCustomizationButtonType"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","kind":"typeIdentifier","text":"STPThreeDSButtonCustomization"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"defaultSettingsForButtonType:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"defaultSettingsForButtonType:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"STPThreeDSButtonCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization"},{"text":" *) ","kind":"text"},{"text":"defaultSettingsForButtonType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","kind":"typeIdentifier","text":"STPThreeDSCustomizationButtonType","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPThreeDSCustomizationButtonType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle","value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}]},{"value":"STPThreeDSButtonCustomization","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/title"},{"value":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/navigatorTitle","value":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"op":"replace"},{"op":"replace","value":"defaultSettingsForButtonType:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1defaultSettings(for:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"defaultSettingsForButtonType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1defaultSettings(for:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}