{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/init(backgroundColor:cornerRadius:)"},"kind":"symbol","sections":[],"abstract":[{"text":"Initializes an instance of STDSButtonCustomization with the given backgroundColor and colorRadius.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithBackgroundColor:cornerRadius:","kind":"identifier"}],"symbolKind":"init","title":"init(backgroundColor:cornerRadius:)","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization(im)initWithBackgroundColor:cornerRadius:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/init(backgroundcolor:cornerradius:)"]},{"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/init(backgroundcolor:cornerradius:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization":{"abstract":[{"text":"A customization object to use to configure the UI of a button.","type":"text"}],"kind":"symbol","title":"STPThreeDSButtonCustomization","url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/init(backgroundColor:cornerRadius:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/init(backgroundColor:cornerRadius:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/init(backgroundcolor:cornerradius:)","abstract":[{"type":"text","text":"Initializes an instance of STDSButtonCustomization with the given backgroundColor and colorRadius."}],"kind":"symbol","navigatorTitle":[{"text":"initWithBackgroundColor:cornerRadius:","kind":"identifier"}],"type":"topic","title":"init(backgroundColor:cornerRadius:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithBackgroundColor:cornerRadius:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:cornerRadius:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithBackgroundColor:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius:"},{"kind":"text","text":"("},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"STPThreeDSButtonCustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/title"},{"value":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/fragments"},{"value":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1init(backgroundColor:cornerRadius:)\/title","value":"initWithBackgroundColor:cornerRadius:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1init(backgroundColor:cornerRadius:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBackgroundColor:cornerRadius:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}