{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization"]]},"metadata":{"role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"property","title":"titleStyle","navigatorTitle":[{"text":"titleStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"titleStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle","kind":"typeIdentifier","text":"STPThreeDSButtonTitleStyle"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization(py)titleStyle","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The capitalization style of the button title."}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/titleStyle","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleStyle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPThreeDSButtonTitleStyle","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/titlestyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/titlestyle"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization":{"type":"topic","title":"STPThreeDSButtonCustomization","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization","abstract":[{"text":"A customization object to use to configure the UI of a button.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization/titleStyle":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleStyle"},{"kind":"text","text":": "},{"text":"STPThreeDSButtonTitleStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization\/titlestyle","abstract":[{"text":"The capitalization style of the button title.","type":"text"}],"role":"symbol","title":"titleStyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization\/titleStyle","navigatorTitle":[{"text":"titleStyle","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonTitleStyle":{"abstract":[{"type":"text","text":"An enumeration of the case transformations that can be applied to the button’s title"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonTitleStyle"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttontitlestyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"type":"topic","title":"STPThreeDSButtonTitleStyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"titleStyle"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"titleStyle","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"STPThreeDSButtonTitleStyle","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSButtonTitleStyle","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonTitleStyle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"titleStyle"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPThreeDSButtonCustomization","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/fragments","value":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/navigatorTitle","value":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1titleStyle\/title","value":"titleStyle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization~1titleStyle\/fragments","value":[{"kind":"identifier","text":"titleStyle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/title","value":"STPThreeDSButtonTitleStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/fragments","value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"STPThreeDSButtonTitleStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonTitleStyle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}