{"abstract":[{"text":"An Alipay source. - seealso: https:\/\/stripe.com\/docs\/sources\/alipay","type":"text"}],"sections":[],"metadata":{"title":"STPSourceType.alipay","roleHeading":"Case","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeAlipay","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"alipay","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeAlipay"}],"symbolKind":"case","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/alipay"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcetype\/alipay"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/alipay"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"alipay","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"abstract":[{"type":"text","text":"Types for a Source"}],"url":"\/documentation\/stripepayments\/stpsourcetype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceType","kind":"identifier"}],"type":"topic","title":"STPSourceType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/alipay":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"alipay","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourcetype\/alipay","title":"STPSourceType.alipay","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeAlipay"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/alipay","abstract":[{"text":"An Alipay source. - seealso: https:\/\/stripe.com\/docs\/sources\/alipay","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceTypeAlipay"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPSourceTypeAlipay","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPSourceTypeAlipay","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"STPSourceType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","value":[{"kind":"identifier","text":"STPSourceType"}],"op":"replace"},{"op":"replace","value":[{"text":"STPSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1alipay\/title","value":"STPSourceTypeAlipay"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1alipay\/fragments","op":"replace","value":[{"text":"STPSourceTypeAlipay","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}