{"sections":[],"abstract":[{"text":"A Bancontact source. - seealso: https:\/\/stripe.com\/docs\/sources\/bancontact","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/bancontact"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bancontact","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bancontact","kind":"identifier"}],"title":"STPSourceType.bancontact","navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeBancontact"}],"externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeBancontact","role":"symbol","modules":[{"name":"StripePayments"}],"roleHeading":"Case","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcetype\/bancontact"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/bancontact"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/bancontact":{"abstract":[{"type":"text","text":"A Bancontact source. - seealso: https:\/\/stripe.com\/docs\/sources\/bancontact"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/bancontact","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/bancontact","type":"topic","navigatorTitle":[{"text":"STPSourceTypeBancontact","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"bancontact","kind":"identifier"}],"title":"STPSourceType.bancontact","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"role":"symbol","abstract":[{"text":"Types for a Source","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype","title":"STPSourceType","navigatorTitle":[{"kind":"identifier","text":"STPSourceType"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceTypeBancontact"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"STPSourceTypeBancontact","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPSourceTypeBancontact","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1bancontact\/title","value":"STPSourceTypeBancontact"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceTypeBancontact"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1bancontact\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","value":[{"kind":"identifier","text":"STPSourceType"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}