{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/card"},"abstract":[{"type":"text","text":"A card source. - seealso: https:\/\/stripe.com\/docs\/sources\/cards"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcetype\/card"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcetype\/card"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeCard"}],"externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeCard","modules":[{"name":"StripePayments"}],"symbolKind":"case","role":"symbol","roleHeading":"Case","title":"STPSourceType.card","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"card","kind":"identifier"}]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/card":{"navigatorTitle":[{"text":"STPSourceTypeCard","kind":"identifier"}],"abstract":[{"type":"text","text":"A card source. - seealso: https:\/\/stripe.com\/docs\/sources\/cards"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/card","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/card","title":"STPSourceType.card","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"card"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"role":"symbol","kind":"symbol","type":"topic","title":"STPSourceType","url":"\/documentation\/stripepayments\/stpsourcetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","abstract":[{"text":"Types for a Source","type":"text"}],"navigatorTitle":[{"text":"STPSourceType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceTypeCard"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"STPSourceTypeCard"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPSourceTypeCard"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"STPSourceTypeCard","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1card\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1card\/fragments","value":[{"kind":"identifier","text":"STPSourceTypeCard"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","value":[{"text":"STPSourceType","kind":"identifier"}]}]}]}
