{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"EPS","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","title":"STPSourceType.EPS","externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeEPS","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"STPSourceTypeEPS","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/eps"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/eps"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"An EPS source. - seealso: https:\/\/stripe.com\/docs\/sources\/eps","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/EPS","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EPS"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/EPS":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EPS"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourcetype\/eps","abstract":[{"type":"text","text":"An EPS source. - seealso: https:\/\/stripe.com\/docs\/sources\/eps"}],"kind":"symbol","navigatorTitle":[{"text":"STPSourceTypeEPS","kind":"identifier"}],"title":"STPSourceType.EPS","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/EPS","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"role":"symbol","abstract":[{"text":"Types for a Source","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype","title":"STPSourceType","navigatorTitle":[{"text":"STPSourceType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"STPSourceTypeEPS","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceTypeEPS","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPSourceTypeEPS","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSourceTypeEPS","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1EPS\/title"},{"value":[{"kind":"identifier","text":"STPSourceTypeEPS"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1EPS\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","value":[{"text":"STPSourceType","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}