{"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/equatable-implementations"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"StripePayments"}],"role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/!=(_:_:)"],"title":"Operators","anchor":"Operators"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceType","kind":"identifier"}],"title":"STPSourceType","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","navigatorTitle":[{"text":"STPSourceType","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Types for a Source","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourcetype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/!=(_:_:)":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/!=(_:_:)","type":"topic","title":"!=(_:_:)","url":"\/documentation\/stripepayments\/stpsourcetype\/!=(_:_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","op":"replace","value":"STPSourceType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","op":"replace","value":[{"text":"STPSourceType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}