{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/giropay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/giropay"]}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"STPSourceTypeGiropay","kind":"identifier"}],"title":"STPSourceType.giropay","symbolKind":"case","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"giropay","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeGiropay","role":"symbol"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/giropay","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"A Giropay source. - seealso: https:\/\/stripe.com\/docs\/sources\/giropay","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"giropay","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/giropay":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"giropay"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/giropay","title":"STPSourceType.giropay","abstract":[{"text":"A Giropay source. - seealso: https:\/\/stripe.com\/docs\/sources\/giropay","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/giropay","navigatorTitle":[{"text":"STPSourceTypeGiropay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSourceType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcetype","title":"STPSourceType","abstract":[{"type":"text","text":"Types for a Source"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPSourceTypeGiropay","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"STPSourceTypeGiropay","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPSourceTypeGiropay","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1giropay\/title","value":"STPSourceTypeGiropay","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceTypeGiropay"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1giropay\/fragments"},{"value":"STPSourceType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","value":[{"text":"STPSourceType","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle"}]}]}