{"metadata":{"symbolKind":"case","title":"STPSourceType.iDEAL","navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeiDEAL"}],"externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeiDEAL","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"iDEAL","kind":"identifier"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/iDEAL","interfaceLanguage":"swift"},"abstract":[{"text":"An iDEAL source. - seealso: https:\/\/stripe.com\/docs\/sources\/ideal","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/ideal"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/ideal"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(STPSourceTypeiDEAL) ","kind":"text"},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"iDEAL","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/iDEAL":{"kind":"symbol","abstract":[{"text":"An iDEAL source. - seealso: https:\/\/stripe.com\/docs\/sources\/ideal","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourcetype\/ideal","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"iDEAL","kind":"identifier"}],"title":"STPSourceType.iDEAL","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/iDEAL","navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeiDEAL"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"abstract":[{"type":"text","text":"Types for a Source"}],"url":"\/documentation\/stripepayments\/stpsourcetype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceType","kind":"identifier"}],"type":"topic","title":"STPSourceType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceTypeiDEAL"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPSourceTypeiDEAL","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSourceTypeiDEAL","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1iDEAL\/title","value":"STPSourceTypeiDEAL","op":"replace"},{"value":[{"text":"STPSourceTypeiDEAL","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1iDEAL\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType"},{"op":"replace","value":[{"text":"STPSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments"},{"value":[{"text":"STPSourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}