{"kind":"symbol","metadata":{"symbolKind":"case","modules":[{"name":"StripePayments"}],"roleHeading":"Case","navigatorTitle":[{"text":"STPSourceTypeKlarna","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeKlarna","title":"STPSourceType.klarna","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"klarna","kind":"identifier"}]},"abstract":[{"text":"A Klarna source. - seealso: https:\/\/stripe.com\/docs\/sources\/klarna","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"klarna","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcetype\/klarna"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsourcetype\/klarna"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/klarna","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPSourceType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcetype","title":"STPSourceType","abstract":[{"type":"text","text":"Types for a Source"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/klarna":{"type":"topic","role":"symbol","abstract":[{"text":"A Klarna source. - seealso: https:\/\/stripe.com\/docs\/sources\/klarna","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/klarna","title":"STPSourceType.klarna","navigatorTitle":[{"text":"STPSourceTypeKlarna","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/klarna","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"klarna","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPSourceTypeKlarna","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPSourceTypeKlarna","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"STPSourceTypeKlarna","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSourceType"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle","value":[{"text":"STPSourceType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1klarna\/title","value":"STPSourceTypeKlarna"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1klarna\/fragments","value":[{"kind":"identifier","text":"STPSourceTypeKlarna"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}