{"kind":"symbol","abstract":[{"text":"A Multibanco source. - seealso: https:\/\/stripe.com\/docs\/sources\/multibanco","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcetype\/multibanco"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/multibanco"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/multibanco","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multibanco"}],"languages":["swift"]}]}],"sections":[],"metadata":{"title":"STPSourceType.multibanco","externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeMultibanco","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multibanco"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"STPSourceTypeMultibanco","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/multibanco":{"abstract":[{"text":"A Multibanco source. - seealso: https:\/\/stripe.com\/docs\/sources\/multibanco","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multibanco"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/multibanco","type":"topic","title":"STPSourceType.multibanco","role":"symbol","navigatorTitle":[{"text":"STPSourceTypeMultibanco","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourcetype\/multibanco"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"url":"\/documentation\/stripepayments\/stpsourcetype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","navigatorTitle":[{"kind":"identifier","text":"STPSourceType"}],"abstract":[{"type":"text","text":"Types for a Source"}],"kind":"symbol","title":"STPSourceType","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceType"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPSourceTypeMultibanco","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPSourceTypeMultibanco","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPSourceTypeMultibanco"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1multibanco\/title","op":"replace","value":"STPSourceTypeMultibanco"},{"op":"replace","value":[{"text":"STPSourceTypeMultibanco","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1multibanco\/fragments"},{"value":"STPSourceType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","value":[{"text":"STPSourceType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPSourceType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}