{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/sepadebit"]},{"paths":["\/documentation\/stripepayments\/stpsourcetype\/sepadebit"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"A SEPA Direct Debit source. - seealso: https:\/\/stripe.com\/docs\/sources\/sepa-debit"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SEPADebit"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SEPADebit","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeSEPADebit"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeSEPADebit","title":"STPSourceType.SEPADebit","roleHeading":"Case","symbolKind":"case","modules":[{"name":"StripePayments"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/SEPADebit","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/SEPADebit":{"title":"STPSourceType.SEPADebit","kind":"symbol","abstract":[{"type":"text","text":"A SEPA Direct Debit source. - seealso: https:\/\/stripe.com\/docs\/sources\/sepa-debit"}],"role":"symbol","navigatorTitle":[{"text":"STPSourceTypeSEPADebit","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourcetype\/sepadebit","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"SEPADebit","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/SEPADebit"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"role":"symbol","kind":"symbol","type":"topic","title":"STPSourceType","url":"\/documentation\/stripepayments\/stpsourcetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","abstract":[{"text":"Types for a Source","type":"text"}],"navigatorTitle":[{"text":"STPSourceType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceTypeSEPADebit"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"STPSourceTypeSEPADebit","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"STPSourceTypeSEPADebit","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPSourceTypeSEPADebit","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1SEPADebit\/title"},{"value":[{"kind":"identifier","text":"STPSourceTypeSEPADebit"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1SEPADebit\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","value":[{"kind":"identifier","text":"STPSourceType"}],"op":"replace"}]}]}
