{"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"title":"STPSourceType.sofort","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sofort","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"STPSourceTypeSofort","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeSofort"},"kind":"symbol","abstract":[{"type":"text","text":"A Sofort source. - seealso: https:\/\/stripe.com\/docs\/sources\/sofort"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sofort"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/sofort","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcetype\/sofort"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/sofort"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/sofort":{"navigatorTitle":[{"text":"STPSourceTypeSofort","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/sofort","abstract":[{"type":"text","text":"A Sofort source. - seealso: https:\/\/stripe.com\/docs\/sources\/sofort"}],"type":"topic","title":"STPSourceType.sofort","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sofort","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/sofort"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"role":"symbol","title":"STPSourceType","kind":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype","abstract":[{"type":"text","text":"Types for a Source"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"STPSourceTypeSofort"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"STPSourceTypeSofort","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"STPSourceTypeSofort"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1sofort\/title","value":"STPSourceTypeSofort","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceTypeSofort"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1sofort\/fragments"},{"value":"STPSourceType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title"},{"value":[{"text":"STPSourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments"},{"value":[{"kind":"identifier","text":"STPSourceType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle"}]}]}
