{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"metadata":{"title":"STPSourceType.threeDSecure","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"threeDSecure"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"STPSourceTypeThreeDSecure","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeThreeDSecure"},"abstract":[{"type":"text","text":"A 3DS card source. - seealso: https:\/\/stripe.com\/docs\/sources\/three-d-secure"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threeDSecure","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsourcetype\/threedsecure"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/threedsecure"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/threeDSecure"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/threeDSecure":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"threeDSecure","kind":"identifier"}],"title":"STPSourceType.threeDSecure","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSourceTypeThreeDSecure"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsourcetype\/threedsecure","abstract":[{"text":"A 3DS card source. - seealso: https:\/\/stripe.com\/docs\/sources\/three-d-secure","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/threeDSecure"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"url":"\/documentation\/stripepayments\/stpsourcetype","navigatorTitle":[{"kind":"identifier","text":"STPSourceType"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","type":"topic","abstract":[{"type":"text","text":"Types for a Source"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPSourceType","kind":"identifier"}],"title":"STPSourceType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"STPSourceTypeThreeDSecure","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPSourceTypeThreeDSecure"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"STPSourceTypeThreeDSecure","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPSourceTypeThreeDSecure","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1threeDSecure\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1threeDSecure\/fragments","op":"replace","value":[{"text":"STPSourceTypeThreeDSecure","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","value":[{"kind":"identifier","text":"STPSourceType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceType"}],"op":"replace"}]}]}