{"abstract":[{"text":"An unknown type of source.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/unknown","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"StripePayments"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"role":"symbol","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeUnknown","navigatorTitle":[{"text":"STPSourceTypeUnknown","kind":"identifier"}],"title":"STPSourceType.unknown"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/unknown"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"navigatorTitle":[{"kind":"identifier","text":"STPSourceType"}],"type":"topic","title":"STPSourceType","role":"symbol","abstract":[{"type":"text","text":"Types for a Source"}],"url":"\/documentation\/stripepayments\/stpsourcetype","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceType"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/unknown":{"url":"\/documentation\/stripepayments\/stpsourcetype\/unknown","type":"topic","navigatorTitle":[{"text":"STPSourceTypeUnknown","kind":"identifier"}],"title":"STPSourceType.unknown","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/unknown","abstract":[{"type":"text","text":"An unknown type of source."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPSourceTypeUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPSourceTypeUnknown","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"STPSourceTypeUnknown"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title","value":"STPSourceType"},{"value":[{"text":"STPSourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments"},{"value":[{"text":"STPSourceType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/navigatorTitle"},{"value":"STPSourceTypeUnknown","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1unknown\/title"},{"value":[{"text":"STPSourceTypeUnknown","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1unknown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}