{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/wechatpay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsourcetype\/wechatpay"]}],"abstract":[{"type":"text","text":"A WeChat Pay source. - seealso: https:\/\/stripe.com\/docs\/sources\/wechat-pay"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"weChatPay"}]}]}],"metadata":{"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPay","kind":"identifier"}],"role":"symbol","title":"STPSourceType.weChatPay","navigatorTitle":[{"text":"STPSourceTypeWeChatPay","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSourceType@STPSourceTypeWeChatPay"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/weChatPay"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType":{"role":"symbol","kind":"symbol","type":"topic","title":"STPSourceType","url":"\/documentation\/stripepayments\/stpsourcetype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType","abstract":[{"text":"Types for a Source","type":"text"}],"navigatorTitle":[{"text":"STPSourceType","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceType/weChatPay":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"weChatPay","kind":"identifier"}],"abstract":[{"text":"A WeChat Pay source. - seealso: https:\/\/stripe.com\/docs\/sources\/wechat-pay","type":"text"}],"role":"symbol","title":"STPSourceType.weChatPay","type":"topic","navigatorTitle":[{"text":"STPSourceTypeWeChatPay","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceType\/weChatPay","url":"\/documentation\/stripepayments\/stpsourcetype\/wechatpay"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"STPSourceTypeWeChatPay","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPSourceTypeWeChatPay","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPSourceTypeWeChatPay","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPSourceType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/title"},{"value":[{"text":"STPSourceType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1weChatPay\/title","value":"STPSourceTypeWeChatPay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceType~1weChatPay\/fragments","value":[{"text":"STPSourceTypeWeChatPay","kind":"identifier"}]}]}]}
