{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/CustomStringConvertible-Implementations"},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"CustomStringConvertible Implementations","modules":[{"name":"StripePayments"}]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/description"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfilepurpose\/customstringconvertible-implementations"]}],"kind":"article","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"abstract":[{"text":"The purpose of the uploaded file.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFilePurpose"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","navigatorTitle":[{"text":"STPFilePurpose","kind":"identifier"}],"role":"symbol","title":"STPFilePurpose","url":"\/documentation\/stripepayments\/stpfilepurpose"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/description":{"abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/description","role":"symbol","title":"description","url":"\/documentation\/stripepayments\/stpfilepurpose\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title","value":"STPFilePurpose"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments","value":[{"text":"STPFilePurpose","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"STPFilePurpose"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/navigatorTitle"}]}]}