{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/CustomStringConvertible-Implementations"]]},"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"property","externalID":"s:14StripePayments14STPFilePurposeO11descriptionSSvp","role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Instance Property","extendedModule":"StripePayments"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/description","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfilepurpose\/description"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"navigatorTitle":[{"text":"STPFilePurpose","kind":"identifier"}],"title":"STPFilePurpose","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFilePurpose","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","abstract":[{"type":"text","text":"The purpose of the uploaded file."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpfilepurpose"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/CustomStringConvertible-Implementations":{"url":"\/documentation\/stripepayments\/stpfilepurpose\/customstringconvertible-implementations","abstract":[],"title":"CustomStringConvertible Implementations","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/CustomStringConvertible-Implementations","role":"collectionGroup","kind":"article"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/description":{"title":"description","kind":"symbol","url":"\/documentation\/stripepayments\/stpfilepurpose\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/description","abstract":[],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPFilePurpose","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments","value":[{"kind":"identifier","text":"STPFilePurpose"}]},{"value":[{"kind":"identifier","text":"STPFilePurpose"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}