{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/disputeEvidence","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose"]]},"abstract":[{"text":"Dispute evidence file","type":"text"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpfilepurpose\/disputeevidence"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfilepurpose\/disputeevidence"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@StripePayments@E@STPFilePurpose@STPFilePurposeDisputeEvidence","modules":[{"name":"StripePayments"}],"title":"STPFilePurpose.disputeEvidence","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"STPFilePurposeDisputeEvidence"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disputeEvidence","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disputeEvidence","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","kind":"symbol","title":"STPFilePurpose","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPFilePurpose"}],"url":"\/documentation\/stripepayments\/stpfilepurpose","navigatorTitle":[{"kind":"identifier","text":"STPFilePurpose"}],"role":"symbol","abstract":[{"type":"text","text":"The purpose of the uploaded file."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/disputeEvidence":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/disputeEvidence","kind":"symbol","abstract":[{"text":"Dispute evidence file","type":"text"}],"title":"STPFilePurpose.disputeEvidence","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpfilepurpose\/disputeevidence","navigatorTitle":[{"text":"STPFilePurposeDisputeEvidence","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"disputeEvidence","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPFilePurposeDisputeEvidence","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPFilePurposeDisputeEvidence"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPFilePurposeDisputeEvidence","kind":"identifier"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPFilePurpose","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title"},{"value":[{"kind":"identifier","text":"STPFilePurpose"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments"},{"value":[{"kind":"identifier","text":"STPFilePurpose"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/navigatorTitle"},{"value":"STPFilePurposeDisputeEvidence","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1disputeEvidence\/title"},{"value":[{"kind":"identifier","text":"STPFilePurposeDisputeEvidence"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1disputeEvidence\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}