{"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpfilepurpose\/equatable-implementations"]}],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/!=(_:_:)"],"title":"Operators","anchor":"Operators","generated":true}],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"StripePayments"}],"role":"collectionGroup"},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"title":"STPFilePurpose","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPFilePurpose","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","url":"\/documentation\/stripepayments\/stpfilepurpose","navigatorTitle":[{"text":"STPFilePurpose","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The purpose of the uploaded file."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/!=(_:_:)":{"url":"\/documentation\/stripepayments\/stpfilepurpose\/!=(_:_:)","kind":"symbol","type":"topic","abstract":[],"title":"!=(_:_:)","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title","value":"STPFilePurpose","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments","value":[{"kind":"identifier","text":"STPFilePurpose"}],"op":"replace"},{"op":"replace","value":[{"text":"STPFilePurpose","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/navigatorTitle"}]}]}