{"metadata":{"symbolKind":"case","modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@E@STPFilePurpose@STPFilePurposeIdentityDocument","navigatorTitle":[{"text":"STPFilePurposeIdentityDocument","kind":"identifier"}],"title":"STPFilePurpose.identityDocument","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identityDocument","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/identityDocument","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose"]]},"abstract":[{"text":"Identity document file","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpfilepurpose\/identitydocument"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfilepurpose\/identitydocument"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identityDocument","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose/identityDocument":{"title":"STPFilePurpose.identityDocument","type":"topic","abstract":[{"type":"text","text":"Identity document file"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"identityDocument"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpfilepurpose\/identitydocument","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose\/identityDocument","navigatorTitle":[{"kind":"identifier","text":"STPFilePurposeIdentityDocument"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFilePurpose":{"type":"topic","url":"\/documentation\/stripepayments\/stpfilepurpose","abstract":[{"type":"text","text":"The purpose of the uploaded file."}],"navigatorTitle":[{"text":"STPFilePurpose","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFilePurpose","kind":"symbol","role":"symbol","title":"STPFilePurpose","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPFilePurpose","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPFilePurposeIdentityDocument","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"STPFilePurposeIdentityDocument","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"STPFilePurposeIdentityDocument","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPFilePurposeIdentityDocument","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1identityDocument\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPFilePurposeIdentityDocument"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose~1identityDocument\/fragments"},{"op":"replace","value":"STPFilePurpose","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPFilePurpose"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPFilePurpose"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFilePurpose\/navigatorTitle"}]}]}