{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipay"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipay(py)description"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipay\/description"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodalipay\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodalipay\/description"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipay":{"navigatorTitle":[{"text":"STPPaymentMethodAlipay","kind":"identifier"}],"title":"STPPaymentMethodAlipay","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodalipay","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipay","abstract":[{"type":"text","text":"Contains details for an Alipay Payment Method."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAlipay","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipay/description":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodalipay\/description","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipay\/description","abstract":[{"type":"text","text":":nodoc:"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentMethodAlipay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipay\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipay\/fragments","op":"replace","value":[{"text":"STPPaymentMethodAlipay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipay\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodAlipay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipay~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipay~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}