{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"alipayOptions","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipayOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPConfirmAlipayOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmAlipayOptions"},{"text":"?","kind":"text"}],"title":"alipayOptions","externalID":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions(py)alipayOptions","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"property"},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/alipayoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/alipayoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Options for an Alipay Payment Method.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipayOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPConfirmAlipayOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmAlipayOptions"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/alipayOptions"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions/alipayOptions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alipayOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmAlipayOptions","text":"STPConfirmAlipayOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"text":"Options for an Alipay Payment Method.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/alipayOptions","role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/alipayoptions","title":"alipayOptions","navigatorTitle":[{"text":"alipayOptions","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"title":"STPConfirmPaymentMethodOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","abstract":[{"text":"Options to update the associated PaymentMethod during PaymentIntent confirmation.","type":"text"}],"url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmAlipayOptions":{"url":"\/documentation\/stripepayments\/stpconfirmalipayoptions","title":"STPConfirmAlipayOptions","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"abstract":[{"type":"text","text":"Alipay options to pass to `STPConfirmPaymentMethodOptions``"}],"navigatorTitle":[{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"alipayOptions","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"alipayOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmAlipayOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions","kind":"typeIdentifier","text":"STPConfirmAlipayOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"alipayOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"alipayOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1alipayOptions\/title"},{"value":[{"text":"alipayOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1alipayOptions\/fragments"},{"value":"STPConfirmPaymentMethodOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/title"},{"value":[{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/fragments"},{"value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/navigatorTitle"},{"value":"STPConfirmAlipayOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/title"},{"value":[{"text":"STPConfirmAlipayOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/fragments"},{"value":[{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/navigatorTitle"}]}]}