{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/blikOptions"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blikOptions","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions","text":"STPConfirmBLIKOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmBLIKOptions"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"blikOptions","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions(py)blikOptions","title":"blikOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blikOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPConfirmBLIKOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmBLIKOptions"},{"text":"?","kind":"text"}],"role":"symbol"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Options for a BLIK Payment Method."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/blikoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/blikoptions"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions":{"navigatorTitle":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options to update the associated PaymentMethod during PaymentIntent confirmation."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","kind":"symbol","title":"STPConfirmPaymentMethodOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmBLIKOptions":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPConfirmBLIKOptions","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmBLIKOptions","kind":"identifier"}],"abstract":[{"text":"BLIK options to pass to `STPConfirmPaymentMethodOptions``","type":"text"}],"title":"STPConfirmBLIKOptions","url":"\/documentation\/stripepayments\/stpconfirmblikoptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions/blikOptions":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/blikOptions","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/blikoptions","navigatorTitle":[{"text":"blikOptions","kind":"identifier"}],"title":"blikOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blikOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmBLIKOptions","text":"STPConfirmBLIKOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"text":"Options for a BLIK Payment Method.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"blikOptions","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"blikOptions","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmBLIKOptions","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmBLIKOptions","text":"STPConfirmBLIKOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"blikOptions"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPConfirmPaymentMethodOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/title","op":"replace"},{"value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/fragments","op":"replace"},{"value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/navigatorTitle","op":"replace"},{"value":"STPConfirmBLIKOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/title","op":"replace"},{"value":[{"text":"STPConfirmBLIKOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/fragments","op":"replace"},{"value":[{"text":"STPConfirmBLIKOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmBLIKOptions\/navigatorTitle","op":"replace"},{"value":"blikOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1blikOptions\/title","op":"replace"},{"value":[{"text":"blikOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1blikOptions\/fragments","op":"replace"}]}]}