{"abstract":[{"type":"text","text":"Options for a Link Payment Method."}],"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions(py)linkOptions","fragments":[{"kind":"identifier","text":"linkOptions"}],"navigatorTitle":[{"text":"linkOptions","kind":"identifier"}],"title":"linkOptions","role":"symbol"},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/linkoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions","text":"STPConfirmLinkOptions","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmLinkOptions"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"linkOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/linkOptions"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmLinkOptions":{"fragments":[{"text":"STPConfirmLinkOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Options to update a Link PaymentMethod during PaymentIntent confirmation."}],"title":"STPConfirmLinkOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmLinkOptions","url":"\/documentation\/stripepayments\/stpconfirmlinkoptions","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions/linkOptions":{"abstract":[{"text":"Options for a Link Payment Method.","type":"text"}],"role":"symbol","kind":"symbol","title":"linkOptions","type":"topic","fragments":[{"kind":"identifier","text":"linkOptions"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/linkOptions","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/linkoptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions","navigatorTitle":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"Options to update the associated PaymentMethod during PaymentIntent confirmation."}],"kind":"symbol","type":"topic","title":"STPConfirmPaymentMethodOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPConfirmPaymentMethodOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/navigatorTitle"}]}]}