{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions(py)usBankAccountOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usBankAccountOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmUSBankAccountOptions","text":"STPConfirmUSBankAccountOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"usBankAccountOptions","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","title":"usBankAccountOptions","role":"symbol"},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/usbankaccountoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/usbankaccountoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Options for a US Bank Account Payment Method.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/usBankAccountOptions","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usBankAccountOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmUSBankAccountOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions","text":"STPConfirmUSBankAccountOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions/usBankAccountOptions":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"usBankAccountOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmUSBankAccountOptions","text":"STPConfirmUSBankAccountOptions"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"usBankAccountOptions"}],"abstract":[{"text":"Options for a US Bank Account Payment Method.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/usBankAccountOptions","type":"topic","kind":"symbol","title":"usBankAccountOptions","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/usbankaccountoptions","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","abstract":[{"type":"text","text":"Options to update the associated PaymentMethod during PaymentIntent confirmation."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}],"title":"STPConfirmPaymentMethodOptions","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmUSBankAccountOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmUSBankAccountOptions"}],"navigatorTitle":[{"kind":"identifier","text":"STPConfirmUSBankAccountOptions"}],"abstract":[{"text":"Options for US Bank Account Payment Methods during PaymentIntent or SetupIntent confirmation","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions","type":"topic","kind":"symbol","title":"STPConfirmUSBankAccountOptions","url":"\/documentation\/stripepayments\/stpconfirmusbankaccountoptions","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","kind":"symbol","title":"StripePayments","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"usBankAccountOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"usBankAccountOptions","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPConfirmUSBankAccountOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmUSBankAccountOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmUSBankAccountOptions"},{"text":" * ","kind":"text"},{"text":"usBankAccountOptions","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1usBankAccountOptions\/title","value":"usBankAccountOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1usBankAccountOptions\/fragments","value":[{"text":"usBankAccountOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/title","value":"STPConfirmPaymentMethodOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/fragments","value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/navigatorTitle","value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/title","value":"STPConfirmUSBankAccountOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/fragments","value":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmUSBankAccountOptions\/navigatorTitle","value":[{"text":"STPConfirmUSBankAccountOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}