{"metadata":{"navigatorTitle":[{"text":"weChatPayOptions","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions(py)weChatPayOptions","title":"weChatPayOptions","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPayOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPConfirmWeChatPayOptions","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmWeChatPayOptions","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Options for a WeChat Pay Payment Method.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"weChatPayOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmWeChatPayOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions","kind":"typeIdentifier","text":"STPConfirmWeChatPayOptions"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/weChatPayOptions"},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/wechatpayoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/wechatpayoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmWeChatPayOptions":{"title":"STPConfirmWeChatPayOptions","navigatorTitle":[{"text":"STPConfirmWeChatPayOptions","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmwechatpayoptions","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmWeChatPayOptions","kind":"identifier"}],"abstract":[{"type":"text","text":"WeChat Pay options to pass to `STPConfirmPaymentMethodOptions``"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions/weChatPayOptions":{"role":"symbol","abstract":[{"type":"text","text":"Options for a WeChat Pay Payment Method."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"weChatPayOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmWeChatPayOptions","text":"STPConfirmWeChatPayOptions"},{"kind":"text","text":"?"}],"title":"weChatPayOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"weChatPayOptions"}],"url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/wechatpayoptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/weChatPayOptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","navigatorTitle":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"kind":"symbol","title":"STPConfirmPaymentMethodOptions","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Options to update the associated PaymentMethod during PaymentIntent confirmation."}],"url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"weChatPayOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"weChatPayOptions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPConfirmWeChatPayOptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConfirmWeChatPayOptions","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"weChatPayOptions","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/title","value":"STPConfirmWeChatPayOptions"},{"value":[{"text":"STPConfirmWeChatPayOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/fragments"},{"value":[{"kind":"identifier","text":"STPConfirmWeChatPayOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/navigatorTitle"},{"value":"weChatPayOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1weChatPayOptions\/title"},{"value":[{"kind":"identifier","text":"weChatPayOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1weChatPayOptions\/fragments"},{"value":"STPConfirmPaymentMethodOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/title"},{"value":[{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/fragments"},{"value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/navigatorTitle"}]}]}