{"metadata":{"title":"propertyNamesToFormFieldNamesMapping()","symbolKind":"method","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams(cm)propertyNamesToFormFieldNamesMapping","role":"symbol","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"roleHeading":"Type Method"},"abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"type":"codeVoice","code":"expMonth"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/propertyNamesToFormFieldNamesMapping()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodfpxparams\/propertynamestoformfieldnamesmapping()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodfpxparams\/propertynamestoformfieldnamesmapping()"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams","kind":"symbol","title":"STPPaymentMethodFPXParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams","abstract":[{"type":"text","text":"An object representing parameters used to create an FPX Payment Method"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams/propertyNamesToFormFieldNamesMapping()":{"url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams\/propertynamestoformfieldnamesmapping()","title":"propertyNamesToFormFieldNamesMapping()","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/propertyNamesToFormFieldNamesMapping()","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"role":"symbol","abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"type":"codeVoice","code":"expMonth"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"propertyNamesToFormFieldNamesMapping"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/title","value":"STPPaymentMethodFPXParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodFPXParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodFPXParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1propertyNamesToFormFieldNamesMapping()\/title","value":"propertyNamesToFormFieldNamesMapping"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}