{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodfpxparams\/rawbankstring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodfpxparams\/rawbankstring"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The raw underlying bank string sent to the server."},{"text":" ","type":"text"},{"type":"text","text":"Generally you should use "},{"code":"bank","type":"codeVoice"},{"type":"text","text":" instead unless you have a reason not to."},{"text":" ","type":"text"},{"type":"text","text":"You can use this if you want to create a param of a bank not yet supported"},{"text":" ","type":"text"},{"type":"text","text":"by the current version of the SDK’s "},{"type":"codeVoice","code":"STPFPXBankBrand"},{"type":"text","text":" enum."},{"text":" ","type":"text"},{"type":"text","text":"Setting this to a value not known by the SDK causes "},{"code":"bank","type":"codeVoice"},{"text":" to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"return "},{"code":"STPFPXBankBrandUnknown","type":"codeVoice"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rawBankString","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams"]]},"metadata":{"title":"rawBankString","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawBankString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"rawBankString","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams(py)rawBankString","modules":[{"name":"StripePayments"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/rawBankString","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams/rawBankString":{"abstract":[{"type":"text","text":"The raw underlying bank string sent to the server."},{"text":" ","type":"text"},{"type":"text","text":"Generally you should use "},{"type":"codeVoice","code":"bank"},{"text":" instead unless you have a reason not to.","type":"text"},{"text":" ","type":"text"},{"text":"You can use this if you want to create a param of a bank not yet supported","type":"text"},{"type":"text","text":" "},{"type":"text","text":"by the current version of the SDK’s "},{"type":"codeVoice","code":"STPFPXBankBrand"},{"type":"text","text":" enum."},{"type":"text","text":" "},{"text":"Setting this to a value not known by the SDK causes ","type":"text"},{"code":"bank","type":"codeVoice"},{"type":"text","text":" to"},{"type":"text","text":" "},{"type":"text","text":"return "},{"type":"codeVoice","code":"STPFPXBankBrandUnknown"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"rawBankString","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"rawBankString","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams\/rawBankString","url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams\/rawbankstring","navigatorTitle":[{"text":"rawBankString","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams":{"title":"STPPaymentMethodFPXParams","abstract":[{"type":"text","text":"An object representing parameters used to create an FPX Payment Method"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams","kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"rawBankString","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"rawBankString","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rawBankString"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"rawBankString","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1rawBankString\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams~1rawBankString\/fragments","value":[{"kind":"identifier","text":"rawBankString"}],"op":"replace"},{"value":"STPPaymentMethodFPXParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodFPXParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodFPXParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}