{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/AddressDetails"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepaymentsheet\/addressviewcontroller\/addressdetails\/name"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","symbolKind":"property","title":"name","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"StripePaymentSheet"}],"externalID":"s:18StripePaymentSheet21AddressViewControllerC0D7DetailsV4nameSSSgvp","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"The customer’s full name","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/AddressDetails\/name"},"references":{"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/AddressDetails/name":{"abstract":[{"type":"text","text":"The customer’s full name"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"name","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/addressdetails\/name","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/AddressDetails\/name","kind":"symbol","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet":{"role":"collection","abstract":[{"type":"text","text":"PaymentSheet is a prebuilt UI that combines all the steps required to pay - collecting payment details, billing details, and confirming the payment - into a single sheet that displays on top of your app."}],"url":"\/documentation\/stripepaymentsheet","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet","type":"topic","title":"StripePaymentSheet"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController","abstract":[{"text":"A view controller that collects a name and an address, with full localization and autocomplete.","type":"text"}],"navigatorTitle":[{"text":"AddressViewController","kind":"identifier"}],"type":"topic","title":"AddressViewController","url":"\/documentation\/stripepaymentsheet\/addressviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AddressViewController","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payment-sheet/documentation/StripePaymentSheet/AddressViewController/AddressDetails":{"abstract":[{"type":"text","text":"The customer data collected by "},{"type":"codeVoice","code":"AddressViewController"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AddressDetails"}],"navigatorTitle":[{"kind":"identifier","text":"AddressDetails"}],"url":"\/documentation\/stripepaymentsheet\/addressviewcontroller\/addressdetails","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payment-sheet\/documentation\/StripePaymentSheet\/AddressViewController\/AddressDetails","title":"AddressViewController.AddressDetails"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPAddressViewController","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/fragments","value":[{"kind":"identifier","text":"STPAddressViewController"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payment-sheet~1documentation~1StripePaymentSheet~1AddressViewController\/navigatorTitle","value":[{"text":"STPAddressViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}