{"abstract":[{"type":"text","text":"Account type"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/accounttype"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/accounttype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountType"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountType"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType"}]}],"kind":"declarations"}],"metadata":{"title":"accountType","modules":[{"name":"StripePayments"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"accountType"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount(py)accountType","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accountType"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUSBankAccountType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/accountType":{"title":"accountType","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/accounttype","type":"topic","abstract":[{"type":"text","text":"Account type"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"accountType","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUSBankAccountType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType"}],"navigatorTitle":[{"text":"accountType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountType"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount":{"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"abstract":[{"type":"text","text":"A US Bank Account Payment Method (ACH)"}],"kind":"symbol","title":"STPPaymentMethodUSBankAccount"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType":{"abstract":[{"type":"text","text":"Account type"}],"title":"STPPaymentMethodUSBankAccountType","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"accountType","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"accountType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType"},{"kind":"text","text":" "},{"text":"accountType","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1accountType\/title","op":"replace","value":"accountType"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1accountType\/fragments","op":"replace","value":[{"text":"accountType","kind":"identifier"}]},{"value":"STPPaymentMethodUSBankAccount","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/title"},{"value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/title","value":"STPPaymentMethodUSBankAccountType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}