{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountHolderType"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"accountHolderType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountHolderType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType","kind":"typeIdentifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount(py)accountHolderType","navigatorTitle":[{"text":"accountHolderType","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accountHolderType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType","kind":"typeIdentifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/accountholdertype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/accountholdertype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Account holder type"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/accountHolderType":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/accountHolderType","kind":"symbol","role":"symbol","title":"accountHolderType","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accountHolderType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountHolderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType"}],"abstract":[{"text":"Account holder type","type":"text"}],"navigatorTitle":[{"text":"accountHolderType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/accountholdertype"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount":{"type":"topic","title":"STPPaymentMethodUSBankAccount","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"abstract":[{"text":"A US Bank Account Payment Method (ACH)","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountHolderType":{"type":"topic","abstract":[{"type":"text","text":"Account holder type"}],"title":"STPPaymentMethodUSBankAccountHolderType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountholdertype","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"accountHolderType","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"accountHolderType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountHolderType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountHolderType","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountHolderType","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"accountHolderType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"accountHolderType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1accountHolderType\/title"},{"value":[{"kind":"identifier","text":"accountHolderType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1accountHolderType\/fragments"},{"value":"STPPaymentMethodUSBankAccount","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/navigatorTitle"},{"value":"STPPaymentMethodUSBankAccountHolderType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/fragments"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountHolderType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountHolderType\/navigatorTitle"}]}]}