{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/last4"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/last4"]}],"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"last4"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount(py)last4","title":"last4"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/last4"},"abstract":[{"text":"Last four digits of the bank account number","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount":{"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","abstract":[{"type":"text","text":"A US Bank Account Payment Method (ACH)"}],"title":"STPPaymentMethodUSBankAccount","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/last4":{"navigatorTitle":[{"text":"last4","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/last4","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/last4","abstract":[{"type":"text","text":"Last four digits of the bank account number"}],"title":"last4","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"last4","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"last4","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"last4","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodUSBankAccount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/navigatorTitle"},{"op":"replace","value":"last4","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1last4\/title"},{"op":"replace","value":[{"text":"last4","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1last4\/fragments"}]}]}