{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"linkedAccount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount"]]},"sections":[],"metadata":{"platforms":[],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount(py)linkedAccount","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"linkedAccount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property","title":"linkedAccount","navigatorTitle":[{"text":"linkedAccount","kind":"identifier"}],"roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/linkedaccount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/linkedaccount"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/linkedAccount","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/linkedAccount":{"navigatorTitle":[{"text":"linkedAccount","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/linkedaccount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"linkedAccount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"deprecated":true,"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/linkedAccount","abstract":[],"title":"linkedAccount","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount":{"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","abstract":[{"type":"text","text":"A US Bank Account Payment Method (ACH)"}],"title":"STPPaymentMethodUSBankAccount","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"replace","value":[]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"linkedAccount","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"linkedAccount","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"linkedAccount","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1linkedAccount\/title","value":"linkedAccount","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1linkedAccount\/fragments","value":[{"text":"linkedAccount","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/title","value":"STPPaymentMethodUSBankAccount","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/navigatorTitle"}]}]}