{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/networks"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/networks"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networks","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountNetworks","text":"STPPaymentMethodUSBankAccountNetworks"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"networks"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"title":"networks","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccount(py)networks"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount"]]},"abstract":[{"type":"text","text":"Contains information about US bank account networks that can be used"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"networks","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountNetworks","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountNetworks","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountNetworks"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/networks","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountNetworks":{"title":"STPPaymentMethodUSBankAccountNetworks","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountNetworks"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountNetworks","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountNetworks"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountnetworks","abstract":[{"type":"text","text":"Contains information about US bank account networks that can be used"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount/networks":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networks","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountNetworks","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountNetworks","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"networks"}],"abstract":[{"type":"text","text":"Contains information about US bank account networks that can be used"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount\/networks","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount\/networks","title":"networks"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccount":{"title":"STPPaymentMethodUSBankAccount","role":"symbol","abstract":[{"text":"A US Bank Account Payment Method (ACH)","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccount","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccount","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"networks","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"networks","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountNetworks","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountNetworks","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountNetworks"},{"text":" * ","kind":"text"},{"text":"networks","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountNetworks\/title","op":"replace","value":"STPPaymentMethodUSBankAccountNetworks"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountNetworks"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountNetworks\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountNetworks\/navigatorTitle","value":[{"text":"STPPaymentMethodUSBankAccountNetworks","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1networks\/title","value":"networks","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount~1networks\/fragments","value":[{"text":"networks","kind":"identifier"}]},{"op":"replace","value":"STPPaymentMethodUSBankAccount","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/fragments","value":[{"text":"STPPaymentMethodUSBankAccount","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccount"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccount\/navigatorTitle"}]}]}