{"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/description"],"generated":true,"title":"Instance Properties"}],"metadata":{"title":"CustomStringConvertible Implementations","modules":[{"name":"StripePayments"}],"roleHeading":"API Collection","role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/CustomStringConvertible-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/customstringconvertible-implementations"]}],"kind":"article","sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult","abstract":[{"type":"text","text":"The result of a check on a Card address or CVC."}],"navigatorTitle":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"title":"STPPaymentMethodCardCheckResult","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","kind":"symbol","role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/description":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/description","role":"symbol","kind":"symbol","type":"topic","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/description","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title","value":"STPPaymentMethodCardCheckResult","op":"replace"},{"value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}