{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/description"]}],"sections":[],"metadata":{"modules":[{"name":"StripePayments"}],"extendedModule":"StripePayments","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"symbolKind":"property","title":"description","role":"symbol","externalID":"s:14StripePayments31STPPaymentMethodCardCheckResultO11descriptionSSvp","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/CustomStringConvertible-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/description","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/CustomStringConvertible-Implementations":{"kind":"article","type":"topic","title":"CustomStringConvertible Implementations","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/CustomStringConvertible-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/customstringconvertible-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"title":"STPPaymentMethodCardCheckResult","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","abstract":[{"type":"text","text":"The result of a check on a Card address or CVC."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/description":{"abstract":[],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/description","title":"description","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/description"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title","value":"STPPaymentMethodCardCheckResult","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/navigatorTitle","value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}