{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/pass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/pass"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/pass"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult"]]},"sections":[],"metadata":{"title":"STPPaymentMethodCardCheckResult.pass","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultPass"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pass"}],"roleHeading":"Case","externalID":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult@STPPaymentMethodCardCheckResultPass","symbolKind":"case","modules":[{"name":"StripePayments"}]},"kind":"symbol","abstract":[{"text":"The check passed.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pass"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"kind":"symbol","title":"STPPaymentMethodCardCheckResult","abstract":[{"type":"text","text":"The result of a check on a Card address or CVC."}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/pass":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/pass","navigatorTitle":[{"text":"STPPaymentMethodCardCheckResultPass","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/pass","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pass","kind":"identifier"}],"abstract":[{"text":"The check passed.","type":"text"}],"title":"STPPaymentMethodCardCheckResult.pass","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentMethodCardCheckResultPass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultPass"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultPass"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title","value":"STPPaymentMethodCardCheckResult"},{"value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/navigatorTitle","op":"replace"},{"value":"STPPaymentMethodCardCheckResultPass","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1pass\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodCardCheckResultPass","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1pass\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}