{"metadata":{"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPPaymentMethodCardCheckResult@STPPaymentMethodCardCheckResultUnchecked","roleHeading":"Case","navigatorTitle":[{"text":"STPPaymentMethodCardCheckResultUnchecked","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unchecked"}],"role":"symbol","modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodCardCheckResult.unchecked"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unchecked"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unchecked","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The value was not checked."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/unchecked"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/unchecked"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult/unchecked":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult\/unchecked","url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult\/unchecked","navigatorTitle":[{"text":"STPPaymentMethodCardCheckResultUnchecked","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"The value was not checked.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unchecked"}],"title":"STPPaymentMethodCardCheckResult.unchecked"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardCheckResult":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardcheckresult","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The result of a check on a Card address or CVC."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardCheckResult","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}],"title":"STPPaymentMethodCardCheckResult"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"STPPaymentMethodCardCheckResultUnchecked","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"STPPaymentMethodCardCheckResultUnchecked","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResultUnchecked"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1unchecked\/title","op":"replace","value":"STPPaymentMethodCardCheckResultUnchecked"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult~1unchecked\/fragments","value":[{"text":"STPPaymentMethodCardCheckResultUnchecked","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/title","value":"STPPaymentMethodCardCheckResult"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardCheckResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardCheckResult\/navigatorTitle","value":[{"text":"STPPaymentMethodCardCheckResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}