{"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afterpayClearpay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodAfterpayClearpayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpayParams"},{"kind":"text","text":"?"}],"title":"afterpayClearpay","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)afterpayClearpay","navigatorTitle":[{"text":"afterpayClearpay","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/afterpayClearpay","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"afterpayClearpay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodAfterpayClearpayParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAfterpayClearpayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpayParams"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"abstract":[{"type":"text","text":"If this is a Afterpay PaymentMethod, this contains additional details."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/afterpayclearpay"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/afterpayclearpay"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAfterpayClearpayParams":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAfterpayClearpayParams"}],"type":"topic","kind":"symbol","title":"STPPaymentMethodAfterpayClearpayParams","url":"\/documentation\/stripepayments\/stppaymentmethodafterpayclearpayparams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodAfterpayClearpayParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAfterpayClearpayParams","abstract":[{"type":"text","text":"An object representing parameters used to create an AfterpayClearpay Payment Method"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/afterpayClearpay":{"navigatorTitle":[{"kind":"identifier","text":"afterpayClearpay"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/afterpayClearpay","abstract":[{"text":"If this is a Afterpay PaymentMethod, this contains additional details.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"afterpayClearpay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodAfterpayClearpayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpayParams"},{"kind":"text","text":"?"}],"title":"afterpayClearpay","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/afterpayclearpay","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"afterpayClearpay","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"afterpayClearpay"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAfterpayClearpayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAfterpayClearpayParams","text":"STPPaymentMethodAfterpayClearpayParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"afterpayClearpay"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodAfterpayClearpayParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAfterpayClearpayParams\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodAfterpayClearpayParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAfterpayClearpayParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodAfterpayClearpayParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAfterpayClearpayParams\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"op":"replace","value":"afterpayClearpay","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1afterpayClearpay\/title"},{"op":"replace","value":[{"text":"afterpayClearpay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1afterpayClearpay\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}