{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/bacsDebit"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bacsDebit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams","kind":"typeIdentifier","text":"STPPaymentMethodBacsDebitParams"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"kind":"symbol","metadata":{"symbolKind":"property","title":"bacsDebit","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"bacsDebit"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)bacsDebit","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bacsDebit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams","text":"STPPaymentMethodBacsDebitParams"},{"text":"?","kind":"text"}]},"abstract":[{"text":"If this is a Bacs Debit PaymentMethod, this contains details about the bank account to debit.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/bacsdebit"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/bacsdebit"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams","url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"title":"STPPaymentMethodBacsDebitParams","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The user’s bank account details."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/bacsDebit":{"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/bacsdebit","kind":"symbol","title":"bacsDebit","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/bacsDebit","type":"topic","navigatorTitle":[{"text":"bacsDebit","kind":"identifier"}],"abstract":[{"text":"If this is a Bacs Debit PaymentMethod, this contains details about the bank account to debit.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bacsDebit","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams","kind":"typeIdentifier","text":"STPPaymentMethodBacsDebitParams"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"bacsDebit","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"bacsDebit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams","kind":"typeIdentifier","text":"STPPaymentMethodBacsDebitParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams"},{"kind":"text","text":" * "},{"text":"bacsDebit","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/title","value":"STPPaymentMethodBacsDebitParams"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBacsDebitParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/navigatorTitle","value":[{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1bacsDebit\/title","value":"bacsDebit"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1bacsDebit\/fragments","op":"replace","value":[{"text":"bacsDebit","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}