{"kind":"symbol","abstract":[{"type":"text","text":"If this is a Bancontact PaymentMethod, this contains additional details."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bancontact"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams","kind":"typeIdentifier","text":"STPPaymentMethodBancontactParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/bancontact"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/bancontact"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)bancontact","symbolKind":"property","title":"bancontact","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bancontact"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams","kind":"typeIdentifier","text":"STPPaymentMethodBancontactParams"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"bancontact"}],"role":"symbol","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/bancontact","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/bancontact":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/bancontact","kind":"symbol","title":"bancontact","abstract":[{"type":"text","text":"If this is a Bancontact PaymentMethod, this contains additional details."}],"type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/bancontact","navigatorTitle":[{"kind":"identifier","text":"bancontact"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bancontact"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBancontactParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"title":"STPPaymentMethodParams","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBancontactParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams","kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a Bancontact Payment Method"}],"title":"STPPaymentMethodBancontactParams","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbancontactparams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"bancontact","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"bancontact"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams","kind":"typeIdentifier","text":"STPPaymentMethodBancontactParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bancontact"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"bancontact","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1bancontact\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bancontact"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1bancontact\/fragments","op":"replace"},{"value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace"},{"value":"STPPaymentMethodBancontactParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}