{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/billie"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/billie"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/billie","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)billie","title":"billie","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billie"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillieParams","text":"STPPaymentMethodBillieParams"},{"kind":"text","text":"?"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"billie"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"If this is a Billie PaymentMethod, this contains additional details."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"billie","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillieParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillieParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/billie":{"navigatorTitle":[{"kind":"identifier","text":"billie"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/billie","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"billie"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillieParams","kind":"typeIdentifier","text":"STPPaymentMethodBillieParams"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"If this is a Billie PaymentMethod, this contains additional details."}],"title":"billie","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/billie","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillieParams":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillieparams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillieParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Billie Payment Method"}],"title":"STPPaymentMethodBillieParams","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillieParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"billie","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"billie","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillieParams","kind":"typeIdentifier","text":"STPPaymentMethodBillieParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillieParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"billie"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"billie","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1billie\/title"},{"op":"replace","value":[{"text":"billie","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1billie\/fragments"},{"op":"replace","value":"STPPaymentMethodBillieParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodBillieParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodBillieParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillieParams\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}