{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/blik"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/blik"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"blik","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"blik","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodBLIKParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBLIKParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"blik","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)blik","role":"symbol","symbolKind":"property"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/blik","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If this is a BLIK PaymentMethod, this contains additional details."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blik"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBLIKParams","text":"STPPaymentMethodBLIKParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBLIKParams","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBLIKParams":{"title":"STPPaymentMethodBLIKParams","url":"\/documentation\/stripepayments\/stppaymentmethodblikparams","navigatorTitle":[{"text":"STPPaymentMethodBLIKParams","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodBLIKParams","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a BLIK Payment Method"},{"text":" ","type":"text"},{"type":"text","text":"There are currently no parameters to pass."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBLIKParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/blik":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"blik"},{"kind":"text","text":": "},{"text":"STPPaymentMethodBLIKParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBLIKParams"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/blik","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/blik","navigatorTitle":[{"kind":"identifier","text":"blik"}],"abstract":[{"type":"text","text":"If this is a BLIK PaymentMethod, this contains additional details."}],"type":"topic","title":"blik","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"blik"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"blik"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBLIKParams","text":"STPPaymentMethodBLIKParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBLIKParams","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"blik"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBLIKParams\/title","value":"STPPaymentMethodBLIKParams"},{"value":[{"text":"STPPaymentMethodBLIKParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBLIKParams\/fragments"},{"value":[{"text":"STPPaymentMethodBLIKParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBLIKParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace","value":"STPPaymentMethodParams"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1blik\/title","value":"blik","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1blik\/fragments","value":[{"kind":"identifier","text":"blik"}]}]}]}