{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/clientAttributionMetadata","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/clientattributionmetadata"]}],"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)clientAttributionMetadata","role":"symbol","title":"clientAttributionMetadata","fragments":[{"kind":"identifier","text":"clientAttributionMetadata"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"clientAttributionMetadata"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripeCore@objc(cs)STPClientAttributionMetadata","text":"STPClientAttributionMetadata","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"clientAttributionMetadata","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/clientAttributionMetadata":{"role":"symbol","abstract":[{"text":"Contains metadata with identifiers for the session and information about the integration","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/clientAttributionMetadata","kind":"symbol","type":"topic","fragments":[{"text":"clientAttributionMetadata","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/clientattributionmetadata","title":"clientAttributionMetadata"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}