{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"crypto","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCryptoParams","text":"STPPaymentMethodCryptoParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCryptoParams"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"crypto","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)crypto","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"crypto","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCryptoParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCryptoParams","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"crypto","modules":[{"name":"StripePayments"}],"role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"text":"If this is a Crypto PaymentMethod, this contains additional details.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/crypto"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/crypto"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/crypto"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/crypto":{"navigatorTitle":[{"kind":"identifier","text":"crypto"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/crypto","abstract":[{"type":"text","text":"If this is a Crypto PaymentMethod, this contains additional details."}],"title":"crypto","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"crypto"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCryptoParams","text":"STPPaymentMethodCryptoParams"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/crypto"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCryptoParams":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodcryptoparams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a Crypto Payment Method"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCryptoParams"}],"title":"STPPaymentMethodCryptoParams","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodCryptoParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCryptoParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodparams","kind":"symbol","title":"STPPaymentMethodParams","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"crypto"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"crypto","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodCryptoParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCryptoParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCryptoParams"},{"text":" * ","kind":"text"},{"text":"crypto","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1crypto\/title","value":"crypto"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1crypto\/fragments","value":[{"kind":"identifier","text":"crypto"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCryptoParams\/title","value":"STPPaymentMethodCryptoParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCryptoParams\/fragments","value":[{"text":"STPPaymentMethodCryptoParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCryptoParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCryptoParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]}]}]}