{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(fpx:billingDetails:metadata:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"abstract":[{"type":"text","text":"Creates params for an FPX PaymentMethod."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"fpx","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodFPXParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"fpx","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s FPX bank details.","type":"text"}]}]},{"name":"billingDetails","content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}],"type":"paragraph"}],"name":"metadata"}],"kind":"parameters"}],"metadata":{"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fpx"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams","text":"STPPaymentMethodFPXParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFpx:billingDetails:metadata:"}],"role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"init","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithFpx:billingDetails:metadata:","title":"init(fpx:billingDetails:metadata:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(fpx:billingdetails:metadata:)"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(fpx:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(fpx:billingDetails:metadata:)":{"type":"topic","abstract":[{"type":"text","text":"Creates params for an FPX PaymentMethod."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fpx","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodFPXParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(fpx:billingdetails:metadata:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(fpx:billingDetails:metadata:)","navigatorTitle":[{"kind":"identifier","text":"initWithFpx:billingDetails:metadata:"}],"title":"init(fpx:billingDetails:metadata:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodParams"}],"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"role":"symbol","title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodFPXParams"}],"kind":"symbol","title":"STPPaymentMethodFPXParams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create an FPX Payment Method"}],"url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"title":"STPPaymentMethodBillingDetails","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"abstract":[{"text":"Billing information associated with a ","type":"text"},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithFpx:billingDetails:metadata:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFpx:billingDetails:metadata:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithFpx:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentMethodFPXParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams"},{"kind":"text","text":" *) "},{"text":"fpx","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"billingDetails:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"billingDetails"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"metadata"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s FPX bank details."}],"type":"paragraph"}],"name":"fpx"},{"name":"billingDetails","content":[{"inlineContent":[{"text":"An object containing the user’s billing details.","type":"text"}],"type":"paragraph"}]},{"name":"metadata","content":[{"inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(fpx:billingDetails:metadata:)\/title","value":"initWithFpx:billingDetails:metadata:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFpx:billingDetails:metadata:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(fpx:billingDetails:metadata:)\/fragments"},{"value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/title","op":"replace","value":"STPPaymentMethodFPXParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodFPXParams"}]},{"value":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","op":"replace","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}