{"metadata":{"modules":[{"name":"StripePayments"}],"title":"init(payByBank:billingDetails:metadata:)","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithPayByBank:billingDetails:metadata:","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithPayByBank:billingDetails:metadata:","kind":"identifier"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"payByBank"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodPayByBankParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBankParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}]},"abstract":[{"type":"text","text":"Creates params for a Pay by Bank PaymentMethod."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(paybybank:billingdetails:metadata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(paybybank:billingdetails:metadata:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"payByBank"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodPayByBankParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBankParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBankParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"payByBank","content":[{"inlineContent":[{"type":"text","text":"An object containing additional Pay by Bank details."}],"type":"paragraph"}]},{"name":"billingDetails","content":[{"inlineContent":[{"text":"An object containing the user’s billing details.","type":"text"}],"type":"paragraph"}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}]}],"kind":"parameters"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(payByBank:billingDetails:metadata:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(payByBank:billingDetails:metadata:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"payByBank","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodPayByBankParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBankParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"title":"init(payByBank:billingDetails:metadata:)","abstract":[{"type":"text","text":"Creates params for a Pay by Bank PaymentMethod."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithPayByBank:billingDetails:metadata:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(payByBank:billingDetails:metadata:)","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(paybybank:billingdetails:metadata:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPayByBankParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPayByBankParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Pay by Bank Payment Method"}],"navigatorTitle":[{"text":"STPPaymentMethodPayByBankParams","kind":"identifier"}],"title":"STPPaymentMethodPayByBankParams","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBankParams","url":"\/documentation\/stripepayments\/stppaymentmethodpaybybankparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"abstract":[{"type":"text","text":"Billing information associated with a "},{"code":"STPPaymentMethod","type":"codeVoice"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"symbol","title":"STPPaymentMethodBillingDetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","title":"STPPaymentMethodParams","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithPayByBank:billingDetails:metadata:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPayByBank:billingDetails:metadata:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPayByBank:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPayByBankParams","text":"STPPaymentMethodPayByBankParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPayByBankParams"},{"text":" *) ","kind":"text"},{"text":"payByBank","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"billingDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"payByBank","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing additional Pay by Bank details.","type":"text"}]}]},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details.","type":"text"}]}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(payByBank:billingDetails:metadata:)\/title","value":"initWithPayByBank:billingDetails:metadata:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(payByBank:billingDetails:metadata:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPayByBank:billingDetails:metadata:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBankParams\/title","value":"STPPaymentMethodPayByBankParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBankParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodPayByBankParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPayByBankParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodPayByBankParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}