{"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(sepadebit:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(sepadebit:billingdetails:metadata:)"]}],"abstract":[{"type":"text","text":"Creates params for a SEPA Debit PaymentMethod;"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"metadata":{"symbolKind":"init","title":"init(sepaDebit:billingDetails:metadata:)","navigatorTitle":[{"text":"initWithSepaDebit:billingDetails:metadata:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sepaDebit"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodSEPADebitParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSEPADebitParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithSepaDebit:billingDetails:metadata:","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Initializer"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(sepaDebit:billingDetails:metadata:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"sepaDebit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodSEPADebitParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSEPADebitParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSEPADebitParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"sepaDebit","content":[{"inlineContent":[{"type":"text","text":"An object containing the SEPA bank debit details."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details. Note that ","type":"text"},{"code":"billingDetails.name","type":"codeVoice"},{"text":" is required for SEPA Debit PaymentMethods.","type":"text"}]}],"name":"billingDetails"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}],"name":"metadata"}],"kind":"parameters"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"abstract":[{"type":"text","text":"Billing information associated with a "},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"kind":"symbol","title":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodparams","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(sepaDebit:billingDetails:metadata:)":{"type":"topic","title":"init(sepaDebit:billingDetails:metadata:)","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(sepadebit:billingdetails:metadata:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sepaDebit"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodSEPADebitParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSEPADebitParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSepaDebit:billingDetails:metadata:"}],"abstract":[{"text":"Creates params for a SEPA Debit PaymentMethod;","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(sepaDebit:billingDetails:metadata:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSEPADebitParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodsepadebitparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodSEPADebitParams","kind":"identifier"}],"type":"topic","title":"STPPaymentMethodSEPADebitParams","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodSEPADebitParams","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"An object representing parameters used to create a SEPA Debit Payment Method","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSEPADebitParams"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithSepaDebit:billingDetails:metadata:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSepaDebit:billingDetails:metadata:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithSepaDebit:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSEPADebitParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSEPADebitParams","text":"STPPaymentMethodSEPADebitParams"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sepaDebit"},{"text":" ","kind":"text"},{"text":"billingDetails:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" *) "},{"text":"metadata","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object containing the SEPA bank debit details."}],"type":"paragraph"}],"name":"sepaDebit"},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing the user’s billing details. Note that "},{"code":"billingDetails.name","type":"codeVoice"},{"text":" is required for SEPA Debit PaymentMethods.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}],"type":"paragraph"}],"name":"metadata"}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails"},{"value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments"},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle"},{"value":"STPPaymentMethodParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(sepaDebit:billingDetails:metadata:)\/title","op":"replace","value":"initWithSepaDebit:billingDetails:metadata:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(sepaDebit:billingDetails:metadata:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSepaDebit:billingDetails:metadata:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSEPADebitParams\/title","value":"STPPaymentMethodSEPADebitParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSEPADebitParams\/fragments","value":[{"text":"STPPaymentMethodSEPADebitParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSEPADebitParams\/navigatorTitle","value":[{"text":"STPPaymentMethodSEPADebitParams","kind":"identifier"}]}]}]}