{"metadata":{"role":"symbol","title":"init(affirm:metadata:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"affirm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirmParams","text":"STPPaymentMethodAffirmParams"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"text":"initWithAffirm:metadata:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithAffirm:metadata:","modules":[{"name":"StripePayments"}],"symbolKind":"init"},"abstract":[{"type":"text","text":"Creates params for an Affirm PaymentMethod. :nodoc:"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(affirm:metadata:)"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(affirm:metadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"affirm","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirmParams","text":"STPPaymentMethodAffirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirmParams"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"affirm","content":[{"inlineContent":[{"text":"An object containing additional Affirm details.","type":"text"}],"type":"paragraph"}]},{"name":"metadata","content":[{"inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}],"type":"paragraph"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(affirm:metadata:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAffirmParams":{"title":"STPPaymentMethodAffirmParams","url":"\/documentation\/stripepayments\/stppaymentmethodaffirmparams","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodAffirmParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create an Affirm Payment Method"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAffirmParams","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirmParams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams","role":"symbol","type":"topic","title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(affirm:metadata:)":{"role":"symbol","title":"init(affirm:metadata:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(affirm:metadata:)","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(affirm:metadata:)","abstract":[{"type":"text","text":"Creates params for an Affirm PaymentMethod. :nodoc:"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"affirm","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirmParams","text":"STPPaymentMethodAffirmParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?)","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAffirm:metadata:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithAffirm:metadata:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAffirm:metadata:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithAffirm:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodAffirmParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAffirmParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAffirmParams"},{"text":" *) ","kind":"text"},{"text":"affirm","kind":"internalParam"},{"kind":"text","text":" "},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing additional Affirm details.","type":"text"}]}],"name":"affirm"},{"content":[{"inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}],"type":"paragraph"}],"name":"metadata"}]},"op":"replace"},{"value":"STPPaymentMethodAffirmParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirmParams\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentMethodAffirmParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirmParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAffirmParams\/navigatorTitle","value":[{"text":"STPPaymentMethodAffirmParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(affirm:metadata:)\/title","op":"replace","value":"initWithAffirm:metadata:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(affirm:metadata:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAffirm:metadata:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}