{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(upi:billingdetails:metadata:)"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(upi:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(upi:billingDetails:metadata:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Creates params for a UPI PaymentMethod;","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"upi","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUPIParams","kind":"typeIdentifier","text":"STPPaymentMethodUPIParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUPIParams"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?)","kind":"text"}]}]},{"parameters":[{"name":"upi","content":[{"inlineContent":[{"type":"text","text":"An object containing additional UPI details."}],"type":"paragraph"}]},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}],"type":"paragraph"}],"name":"metadata"}],"kind":"parameters"}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithUpi:billingDetails:metadata:","navigatorTitle":[{"text":"initWithUpi:billingDetails:metadata:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(upi:billingDetails:metadata:)","modules":[{"name":"StripePayments"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"upi"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUPIParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUPIParams"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"symbolKind":"init","role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}],"kind":"symbol","title":"STPPaymentMethodParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","role":"symbol","abstract":[{"type":"text","text":"Billing information associated with a "},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","type":"topic","title":"STPPaymentMethodBillingDetails","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUPIParams":{"abstract":[{"text":"An object representing parameters used to create a UPI Payment Method","type":"text"}],"title":"STPPaymentMethodUPIParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUPIParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUPIParams"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUPIParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodupiparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(upi:billingDetails:metadata:)":{"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(upi:billingdetails:metadata:)","abstract":[{"text":"Creates params for a UPI PaymentMethod;","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithUpi:billingDetails:metadata:"}],"title":"init(upi:billingDetails:metadata:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"upi"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUPIParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUPIParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(upi:billingDetails:metadata:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithUpi:billingDetails:metadata:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithUpi:billingDetails:metadata:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithUpi:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUPIParams","text":"STPPaymentMethodUPIParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUPIParams"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"upi"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billingDetails:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"upi","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing additional UPI details.","type":"text"}]}]},{"name":"billingDetails","content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}],"type":"paragraph"}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"STPPaymentMethodParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUPIParams\/title","value":"STPPaymentMethodUPIParams"},{"value":[{"text":"STPPaymentMethodUPIParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUPIParams\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUPIParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodUPIParams"}]},{"value":"initWithUpi:billingDetails:metadata:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(upi:billingDetails:metadata:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(upi:billingDetails:metadata:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithUpi:billingDetails:metadata:"}],"op":"replace"}]}]}