{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(bacsdebit:billingdetails:metadata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(bacsdebit:billingdetails:metadata:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(bacsDebit:billingDetails:metadata:)"},"abstract":[{"type":"text","text":"Creates params for a Bacs Debit PaymentMethod;"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bacsDebit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBacsDebitParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object containing the Bacs bank debit details."}],"type":"paragraph"}],"name":"bacsDebit"},{"content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details. Note that name, email, and address are required for Bacs Debit PaymentMethods."}],"type":"paragraph"}],"name":"billingDetails"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}]}],"name":"metadata"}],"kind":"parameters"}],"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithBacsDebit:billingDetails:metadata:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bacsDebit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams","kind":"typeIdentifier","text":"STPPaymentMethodBacsDebitParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?)"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithBacsDebit:billingDetails:metadata:","role":"symbol","roleHeading":"Initializer","title":"init(bacsDebit:billingDetails:metadata:)"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBacsDebitParams":{"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbacsdebitparams","title":"STPPaymentMethodBacsDebitParams","navigatorTitle":[{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"abstract":[{"type":"text","text":"The user’s bank account details."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(bacsDebit:billingDetails:metadata:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bacsDebit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams","kind":"typeIdentifier","text":"STPPaymentMethodBacsDebitParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Creates params for a Bacs Debit PaymentMethod;"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(bacsdebit:billingdetails:metadata:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(bacsDebit:billingDetails:metadata:)","navigatorTitle":[{"kind":"identifier","text":"initWithBacsDebit:billingDetails:metadata:"}],"title":"init(bacsDebit:billingDetails:metadata:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","title":"STPPaymentMethodBillingDetails","abstract":[{"text":"Billing information associated with a ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithBacsDebit:billingDetails:metadata:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBacsDebit:billingDetails:metadata:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBacsDebit:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBacsDebitParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBacsDebitParams","text":"STPPaymentMethodBacsDebitParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bacsDebit"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingDetails:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"billingDetails"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object containing the Bacs bank debit details."}],"type":"paragraph"}],"name":"bacsDebit"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details. Note that name, email, and address are required for Bacs Debit PaymentMethods.","type":"text"}]}],"name":"billingDetails"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}]}],"name":"metadata"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/title","value":"STPPaymentMethodBacsDebitParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/fragments","value":[{"text":"STPPaymentMethodBacsDebitParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBacsDebitParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBacsDebitParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(bacsDebit:billingDetails:metadata:)\/title","value":"initWithBacsDebit:billingDetails:metadata:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(bacsDebit:billingDetails:metadata:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBacsDebit:billingDetails:metadata:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace"}]}]}