{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bancontact"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams","text":"STPPaymentMethodBancontactParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"bancontact","content":[{"inlineContent":[{"text":"An object containing additional Bancontact details.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details. Note that "},{"type":"codeVoice","code":"billingDetails.name"},{"type":"text","text":" is required for Bancontact PaymentMethods."}],"type":"paragraph"}],"name":"billingDetails"},{"name":"metadata","content":[{"inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}],"type":"paragraph"}]}]}],"sections":[],"abstract":[{"type":"text","text":"Creates params for a Bancontact PaymentMethod;"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(bancontact:billingDetails:metadata:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"init(bancontact:billingDetails:metadata:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithBancontact:billingDetails:metadata:","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithBancontact:billingDetails:metadata:","modules":[{"name":"StripePayments"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bancontact","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodBancontactParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"role":"symbol","symbolKind":"init"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(bancontact:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(bancontact:billingdetails:metadata:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","title":"STPPaymentMethodParams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodParams"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBancontactParams":{"title":"STPPaymentMethodBancontactParams","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBancontactParams","kind":"identifier"}],"role":"symbol","abstract":[{"text":"An object representing parameters used to create a Bancontact Payment Method","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodbancontactparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","title":"STPPaymentMethodBillingDetails","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"abstract":[{"text":"Billing information associated with a ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethod"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(bancontact:billingDetails:metadata:)":{"type":"topic","abstract":[{"type":"text","text":"Creates params for a Bancontact PaymentMethod;"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBancontact:billingDetails:metadata:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(bancontact:billingDetails:metadata:)","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(bancontact:billingdetails:metadata:)","title":"init(bancontact:billingDetails:metadata:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bancontact"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams","text":"STPPaymentMethodBancontactParams"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithBancontact:billingDetails:metadata:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBancontact:billingDetails:metadata:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithBancontact:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBancontactParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBancontactParams","text":"STPPaymentMethodBancontactParams","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"bancontact","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingDetails:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing additional Bancontact details."}]}],"name":"bancontact"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details. Note that ","type":"text"},{"type":"codeVoice","code":"billingDetails.name"},{"text":" is required for Bancontact PaymentMethods.","type":"text"}]}],"name":"billingDetails"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}]}],"name":"metadata"}]},"path":"\/primaryContentSections\/1"},{"value":"STPPaymentMethodParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/title","value":"STPPaymentMethodBancontactParams"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBancontactParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBancontactParams"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails","op":"replace"},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}]},{"value":"initWithBancontact:billingDetails:metadata:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(bancontact:billingDetails:metadata:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(bancontact:billingDetails:metadata:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithBancontact:billingDetails:metadata:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}