{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"usBankAccount"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams","kind":"typeIdentifier","text":"STPPaymentMethodUSBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountParams"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"kind":"externalParam","text":"allowRedisplay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay","text":"STPPaymentMethodAllowRedisplay","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay"},{"text":" = .unspecified, ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?)"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"usBankAccount","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing additional US bank account details","type":"text"}]}]},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing the user’s billing details. Name is required for US Bank Accounts"}]}]},{"name":"allowRedisplay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An enum defining consent options for redisplay"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod"}]}],"name":"metadata"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"initWithUsBankAccount:billingDetails:allowRedisplay:metadata:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"usBankAccount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountParams","text":"STPPaymentMethodUSBankAccountParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"allowRedisplay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay","text":"STPPaymentMethodAllowRedisplay"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?)","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(usBankAccount:billingDetails:allowRedisplay:metadata:)","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithUsBankAccount:billingDetails:allowRedisplay:metadata:","modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(usbankaccount:billingdetails:allowredisplay:metadata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(usbankaccount:billingdetails:allowredisplay:metadata:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Creates params for a US Bank Account Payment Method","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(usBankAccount:billingDetails:allowRedisplay:metadata:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountParams":{"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccountparams","abstract":[{"text":"An object representing parameters used to create a US Bank Account Payment Method","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams","title":"STPPaymentMethodUSBankAccountParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","abstract":[{"type":"text","text":"Billing information associated with a "},{"type":"codeVoice","code":"STPPaymentMethod"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"title":"STPPaymentMethodBillingDetails","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay":{"kind":"symbol","type":"topic","role":"symbol","title":"STPPaymentMethodAllowRedisplay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}],"abstract":[{"text":"Values for STPPaymentMethodAllowRedisplay","type":"text"}],"navigatorTitle":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(usBankAccount:billingDetails:allowRedisplay:metadata:)":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithUsBankAccount:billingDetails:allowRedisplay:metadata:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(usBankAccount:billingDetails:allowRedisplay:metadata:)","abstract":[{"type":"text","text":"Creates params for a US Bank Account Payment Method"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"usBankAccount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethodUSBankAccountParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"text":"allowRedisplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAllowRedisplay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"title":"init(usBankAccount:billingDetails:allowRedisplay:metadata:)","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(usbankaccount:billingdetails:allowredisplay:metadata:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithUsBankAccount:billingDetails:allowRedisplay:metadata:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUsBankAccount:billingDetails:allowRedisplay:metadata:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithUsBankAccount:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountParams","kind":"typeIdentifier","text":"STPPaymentMethodUSBankAccountParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodUSBankAccountParams"},{"kind":"text","text":" *) "},{"text":"usBankAccount","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billingDetails:"},{"text":"(","kind":"text"},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"text":"billingDetails","kind":"internalParam"},{"kind":"text","text":" "},{"text":"allowRedisplay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAllowRedisplay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"allowRedisplay","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"usBankAccount","content":[{"inlineContent":[{"text":"An object containing additional US bank account details","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details. Name is required for US Bank Accounts","type":"text"}]}],"name":"billingDetails"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An enum defining consent options for redisplay"}]}],"name":"allowRedisplay"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod"}]}],"name":"metadata"}]}},{"value":"STPPaymentMethodUSBankAccountParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodUSBankAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","op":"replace","value":"STPPaymentMethodBillingDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle"},{"value":"STPPaymentMethodAllowRedisplay","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/fragments"},{"value":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(usBankAccount:billingDetails:allowRedisplay:metadata:)\/title","op":"replace","value":"initWithUsBankAccount:billingDetails:allowRedisplay:metadata:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithUsBankAccount:billingDetails:allowRedisplay:metadata:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(usBankAccount:billingDetails:allowRedisplay:metadata:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace","value":"STPPaymentMethodParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]}]}]}