{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(singleUsePaymentMethod:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"init(singleUsePaymentMethod:)","modules":[{"name":"StripePayments"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"singleUsePaymentMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethod","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":")","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithSingleUsePaymentMethod:","navigatorTitle":[{"kind":"identifier","text":"initWithSingleUsePaymentMethod:"}]},"abstract":[{"text":"Creates params from a single-use PaymentMethod. This is useful for recreating a new payment method","type":"text"},{"type":"text","text":" "},{"type":"text","text":"with similar settings. It will return nil if used with a reusable PaymentMethod."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"singleUsePaymentMethod","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"paymentMethod"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"paymentMethod","content":[{"inlineContent":[{"type":"text","text":"An object containing the original single-use PaymentMethod."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(singleusepaymentmethod:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(singleusepaymentmethod:)"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(singleUsePaymentMethod:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"singleUsePaymentMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(singleUsePaymentMethod:)","navigatorTitle":[{"text":"initWithSingleUsePaymentMethod:","kind":"identifier"}],"abstract":[{"text":"Creates params from a single-use PaymentMethod. This is useful for recreating a new payment method","type":"text"},{"text":" ","type":"text"},{"text":"with similar settings. It will return nil if used with a reusable PaymentMethod.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(singleusepaymentmethod:)","title":"init(singleUsePaymentMethod:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethod":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","type":"topic","title":"STPPaymentMethod","navigatorTitle":[{"text":"STPPaymentMethod","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"PaymentMethod objects represent your customer’s payment instruments. They can be used with PaymentIntents to collect payments."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethod","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithSingleUsePaymentMethod:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithSingleUsePaymentMethod:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithSingleUsePaymentMethod:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethod","text":"STPPaymentMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"paymentMethod"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing the original single-use PaymentMethod."}]}],"name":"paymentMethod"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(singleUsePaymentMethod:)\/title","value":"initWithSingleUsePaymentMethod:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(singleUsePaymentMethod:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithSingleUsePaymentMethod:","kind":"identifier"}]},{"value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/title","value":"STPPaymentMethod","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/fragments","op":"replace","value":[{"text":"STPPaymentMethod","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethod\/navigatorTitle","value":[{"text":"STPPaymentMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}