{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(eps:billingDetails:metadata:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(eps:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(eps:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"eps","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodEPSParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPSParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodEPSParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"An object containing additional EPS details.","type":"text"}],"type":"paragraph"}],"name":"eps"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details. Note that ","type":"text"},{"code":"billingDetails.name","type":"codeVoice"},{"text":" is required for EPS PaymentMethods.","type":"text"}]}],"name":"billingDetails"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}],"name":"metadata"}],"kind":"parameters"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithEps:billingDetails:metadata:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"StripePayments"}],"roleHeading":"Initializer","title":"init(eps:billingDetails:metadata:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"eps","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodEPSParams","text":"STPPaymentMethodEPSParams","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithEps:billingDetails:metadata:"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"abstract":[{"type":"text","text":"Creates params for an EPS PaymentMethod;"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","type":"topic","title":"STPPaymentMethodParams","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"title":"STPPaymentMethodBillingDetails","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"abstract":[{"text":"Billing information associated with a ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethod"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodEPSParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a EPS Payment Method"}],"type":"topic","title":"STPPaymentMethodEPSParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPSParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodEPSParams"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodEPSParams"}],"url":"\/documentation\/stripepayments\/stppaymentmethodepsparams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(eps:billingDetails:metadata:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eps"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodEPSParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodEPSParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"text":"Creates params for an EPS PaymentMethod;","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEps:billingDetails:metadata:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(eps:billingDetails:metadata:)","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(eps:billingdetails:metadata:)","kind":"symbol","role":"symbol","title":"init(eps:billingDetails:metadata:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithEps:billingDetails:metadata:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEps:billingDetails:metadata:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithEps:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodEPSParams","text":"STPPaymentMethodEPSParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodEPSParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"eps","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"billingDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"eps","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing additional EPS details."}]}]},{"name":"billingDetails","content":[{"inlineContent":[{"text":"An object containing the user’s billing details. Note that ","type":"text"},{"code":"billingDetails.name","type":"codeVoice"},{"text":" is required for EPS PaymentMethods.","type":"text"}],"type":"paragraph"}]},{"name":"metadata","content":[{"inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPSParams\/title","value":"STPPaymentMethodEPSParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPSParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodEPSParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodEPSParams\/navigatorTitle","value":[{"text":"STPPaymentMethodEPSParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(eps:billingDetails:metadata:)\/title","value":"initWithEps:billingDetails:metadata:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(eps:billingDetails:metadata:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEps:billingDetails:metadata:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}