{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(card:billingDetails:allowRedisplay:metadata:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"card"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","text":"STPPaymentMethodCardParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"allowRedisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","text":"STPPaymentMethodAllowRedisplay"},{"kind":"text","text":" = .unspecified, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"card","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s card details.","type":"text"}]}]},{"name":"billingDetails","content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}],"type":"paragraph"}]},{"name":"allowRedisplay","content":[{"type":"paragraph","inlineContent":[{"text":"An enum defining consent options for redisplay","type":"text"}]}]},{"name":"metadata","content":[{"inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}],"type":"paragraph"}]}]}],"abstract":[{"text":"Creates params for a card PaymentMethod.","type":"text"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"card"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"allowRedisplay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodAllowRedisplay","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"roleHeading":"Initializer","modules":[{"name":"StripePayments"}],"role":"symbol","title":"init(card:billingDetails:allowRedisplay:metadata:)","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithCard:billingDetails:allowRedisplay:metadata:","navigatorTitle":[{"text":"initWithCard:billingDetails:allowRedisplay:metadata:","kind":"identifier"}],"symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(card:billingdetails:allowredisplay:metadata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(card:billingdetails:allowredisplay:metadata:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","abstract":[{"text":"Billing information associated with a ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethod"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}],"title":"STPPaymentMethodBillingDetails","navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAllowRedisplay":{"type":"topic","title":"STPPaymentMethodAllowRedisplay","abstract":[{"text":"Values for STPPaymentMethodAllowRedisplay","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","navigatorTitle":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodallowredisplay"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodcardparams","navigatorTitle":[{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"abstract":[{"type":"text","text":"The user’s card details."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodCardParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","kind":"symbol","title":"STPPaymentMethodCardParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","title":"STPPaymentMethodParams","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(card:billingDetails:allowRedisplay:metadata:)":{"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(card:billingdetails:allowredisplay:metadata:)","title":"init(card:billingDetails:allowRedisplay:metadata:)","abstract":[{"type":"text","text":"Creates params for a card PaymentMethod."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(card:billingDetails:allowRedisplay:metadata:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"card","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":"?, ","kind":"text"},{"text":"allowRedisplay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAllowRedisplay","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"text":"initWithCard:billingDetails:allowRedisplay:metadata:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCard:billingDetails:allowRedisplay:metadata:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCard:billingDetails:allowRedisplay:metadata:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCard:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentMethodCardParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardParams"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"card"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingDetails:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"allowRedisplay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentMethodAllowRedisplay","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAllowRedisplay","text":"STPPaymentMethodAllowRedisplay"},{"kind":"text","text":") "},{"kind":"internalParam","text":"allowRedisplay"},{"kind":"text","text":" "},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s card details."}],"type":"paragraph"}],"name":"card"},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details.","type":"text"}]}],"name":"billingDetails"},{"content":[{"inlineContent":[{"type":"text","text":"An enum defining consent options for redisplay"}],"type":"paragraph"}],"name":"allowRedisplay"},{"content":[{"inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}],"type":"paragraph"}],"name":"metadata"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/title","value":"STPPaymentMethodAllowRedisplay"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/fragments","value":[{"text":"STPPaymentMethodAllowRedisplay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAllowRedisplay\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodAllowRedisplay"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/title","value":"STPPaymentMethodCardParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodCardParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodCardParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(card:billingDetails:allowRedisplay:metadata:)\/title","value":"initWithCard:billingDetails:allowRedisplay:metadata:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(card:billingDetails:allowRedisplay:metadata:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCard:billingDetails:allowRedisplay:metadata:","kind":"identifier"}]}]}]}