{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"alipay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams","text":"STPPaymentMethodAlipayParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?)","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"alipay","content":[{"inlineContent":[{"type":"text","text":"An object containing additional Alipay details."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}],"type":"paragraph"}],"name":"billingDetails"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}]}],"name":"metadata"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(alipay:billingDetails:metadata:)","interfaceLanguage":"swift"},"metadata":{"title":"init(alipay:billingDetails:metadata:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"alipay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams","text":"STPPaymentMethodAlipayParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAlipay:billingDetails:metadata:"}],"symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithAlipay:billingDetails:metadata:","modules":[{"name":"StripePayments"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(alipay:billingdetails:metadata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(alipay:billingdetails:metadata:)"]}],"abstract":[{"type":"text","text":"Creates params for an Alipay PaymentMethod."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipayParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodalipayparams","kind":"symbol","title":"STPPaymentMethodAlipayParams","abstract":[{"text":"An object representing parameters used to create an Alipay Payment Method.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"There are currently no parameters to pass."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"title":"STPPaymentMethodBillingDetails","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","role":"symbol","abstract":[{"type":"text","text":"Billing information associated with a "},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" that may be used or required by particular types of payment methods."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(alipay:billingDetails:metadata:)":{"title":"init(alipay:billingDetails:metadata:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(alipay:billingDetails:metadata:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"alipay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodAlipayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"text":"initWithAlipay:billingDetails:metadata:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(alipay:billingdetails:metadata:)","abstract":[{"type":"text","text":"Creates params for an Alipay PaymentMethod."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithAlipay:billingDetails:metadata:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAlipay:billingDetails:metadata:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithAlipay:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams","text":"STPPaymentMethodAlipayParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"alipay","kind":"internalParam"},{"kind":"text","text":" "},{"text":"billingDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"kind":"text","text":" "},{"text":"metadata:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"metadata"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"alipay","content":[{"inlineContent":[{"type":"text","text":"An object containing additional Alipay details."}],"type":"paragraph"}]},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}]}]},{"content":[{"inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}],"type":"paragraph"}],"name":"metadata"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/title","op":"replace","value":"STPPaymentMethodAlipayParams"},{"value":[{"kind":"identifier","text":"STPPaymentMethodAlipayParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}]},{"op":"replace","value":"STPPaymentMethodBillingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title"},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle"},{"value":"initWithAlipay:billingDetails:metadata:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(alipay:billingDetails:metadata:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAlipay:billingDetails:metadata:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(alipay:billingDetails:metadata:)\/fragments","op":"replace"}]}]}