{"sections":[],"metadata":{"title":"initWithShopPay:billingDetails:metadata:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShopPay:billingDetails:metadata:"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithShopPay:billingDetails:metadata:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithShopPay:billingDetails:metadata:","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithShopPay:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams","text":"STPPaymentMethodShopPayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodShopPayParams","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"shopPay"},{"kind":"text","text":" "},{"kind":"identifier","text":"billingDetails:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"billingDetails"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},{"parameters":[{"name":"shopPay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing additional ShopPay details."}]}]},{"name":"billingDetails","content":[{"inlineContent":[{"text":"An object containing the user’s billing details.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}],"name":"metadata"}],"kind":"parameters"}],"abstract":[{"text":"Creates params for an ShopPay PaymentMethod.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/initWithShopPay:billingDetails:metadata:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/initwithshoppay:billingdetails:metadata:"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/initWithShopPay:billingDetails:metadata:":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/initWithShopPay:billingDetails:metadata:","abstract":[{"type":"text","text":"Creates params for an ShopPay PaymentMethod."}],"role":"symbol","navigatorTitle":[{"text":"initWithShopPay:billingDetails:metadata:","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/initwithshoppay:billingdetails:metadata:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithShopPay:billingDetails:metadata:"}],"title":"initWithShopPay:billingDetails:metadata:"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"abstract":[{"type":"text","text":"Billing information associated with a "},{"type":"codeVoice","code":"STPPaymentMethod"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}],"title":"STPPaymentMethodBillingDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPayParams":{"kind":"symbol","abstract":[{"text":"An object representing parameters used to create a ShopPay Payment Method","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodshoppayparams","title":"STPPaymentMethodShopPayParams","fragments":[{"text":"STPPaymentMethodShopPayParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"STPPaymentMethodBillingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title"},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}]},{"op":"replace","value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace"}]}]}