{"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(im)initWithOxxo:billingDetails:metadata:","symbolKind":"init","navigatorTitle":[{"text":"initWithOxxo:billingDetails:metadata:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"StripePayments"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"oxxo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","text":"STPPaymentMethodOXXOParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"title":"init(oxxo:billingDetails:metadata:)","role":"symbol"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(oxxo:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/init(oxxo:billingdetails:metadata:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Creates params for an OXXO PaymentMethod;"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(oxxo:billingDetails:metadata:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"oxxo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","text":"STPPaymentMethodOXXOParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object containing additional OXXO details."}],"type":"paragraph"}],"name":"oxxo"},{"name":"billingDetails","content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}],"type":"paragraph"}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"kind":"symbol","title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/init(oxxo:billingDetails:metadata:)":{"navigatorTitle":[{"text":"initWithOxxo:billingDetails:metadata:","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"oxxo","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","kind":"typeIdentifier","text":"STPPaymentMethodOXXOParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/init(oxxo:billingDetails:metadata:)","title":"init(oxxo:billingDetails:metadata:)","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/init(oxxo:billingdetails:metadata:)","role":"symbol","abstract":[{"text":"Creates params for an OXXO PaymentMethod;","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodOXXOParams":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodOXXOParams"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams","title":"STPPaymentMethodOXXOParams","url":"\/documentation\/stripepayments\/stppaymentmethodoxxoparams","role":"symbol","abstract":[{"text":"An object representing parameters used to create an OXXO Payment Method","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"abstract":[{"type":"text","text":"Billing information associated with a "},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"title":"STPPaymentMethodBillingDetails"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithOxxo:billingDetails:metadata:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithOxxo:billingDetails:metadata:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithOxxo:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","text":"STPPaymentMethodOXXOParams"},{"text":" *) ","kind":"text"},{"text":"oxxo","kind":"internalParam"},{"kind":"text","text":" "},{"text":"billingDetails:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"metadata","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"value":"initWithOxxo:billingDetails:metadata:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(oxxo:billingDetails:metadata:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1init(oxxo:billingDetails:metadata:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithOxxo:billingDetails:metadata:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/title","value":"STPPaymentMethodOXXOParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","op":"replace","value":"STPPaymentMethodBillingDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
