{"metadata":{"roleHeading":"Instance Property","title":"multibanco","modules":[{"name":"StripePayments"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multibanco","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodMultibancoParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibancoParams"},{"kind":"text","text":"?"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)multibanco","navigatorTitle":[{"text":"multibanco","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/multibanco"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/multibanco"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/multibanco","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"multibanco","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPPaymentMethodMultibancoParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibancoParams"},{"text":"?","kind":"text"}]}]}],"abstract":[{"type":"text","text":"If this is a Multibanco PaymentMethod, this contains additional details."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibancoParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodmultibancoparams","kind":"symbol","title":"STPPaymentMethodMultibancoParams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a Multibanco Payment Method"}],"navigatorTitle":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodMultibancoParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/multibanco":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/multibanco","title":"multibanco","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/multibanco","navigatorTitle":[{"kind":"identifier","text":"multibanco"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multibanco"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibancoParams","text":"STPPaymentMethodMultibancoParams"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"If this is a Multibanco PaymentMethod, this contains additional details."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"multibanco","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"multibanco","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"STPPaymentMethodMultibancoParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibancoParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibancoParams"},{"text":" * ","kind":"text"},{"text":"multibanco","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/title","value":"STPPaymentMethodMultibancoParams"},{"op":"replace","value":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibancoParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodMultibancoParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1multibanco\/title","op":"replace","value":"multibanco"},{"value":[{"text":"multibanco","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1multibanco\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}