{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/oxxo"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/oxxo"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/oxxo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If this is an OXXO PaymentMethod, this contains additional details."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"oxxo","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"oxxo"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodOXXOParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"oxxo","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)oxxo","modules":[{"name":"StripePayments"}],"symbolKind":"property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"oxxo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodOXXOParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/oxxo":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/oxxo","abstract":[{"type":"text","text":"If this is an OXXO PaymentMethod, this contains additional details."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"oxxo"}],"title":"oxxo","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/oxxo","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"oxxo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodOXXOParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodOXXOParams":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodOXXOParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create an OXXO Payment Method"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodoxxoparams","title":"STPPaymentMethodOXXOParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"oxxo"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"oxxo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodOXXOParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams"},{"kind":"text","text":" * "},{"text":"oxxo","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1oxxo\/title","value":"oxxo"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1oxxo\/fragments","value":[{"text":"oxxo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodOXXOParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}