{"metadata":{"roleHeading":"Type Method","title":"paramsWith(giropay:billingDetails:metadata:)","role":"symbol","modules":[{"name":"StripePayments"}],"extendedModule":"StripePayments","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"paramsWithGiropay:billingDetails:metadata:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paramsWith","kind":"identifier"},{"kind":"text","text":"("},{"text":"giropay","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGiropayParams","text":"STPPaymentMethodGiropayParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams"}],"externalID":"c:@CM@StripePayments@objc(cs)STPPaymentMethodParams(cm)paramsWithGiropay:billingDetails:metadata:"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(giropay:billingDetails:metadata:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(paramsWithGiropay:billingDetails:metadata:) "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramsWith"},{"kind":"text","text":"("},{"text":"giropay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodGiropayParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGiropayParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGiropayParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"typeIdentifier","text":"STPPaymentMethodParams"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"giropay","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing additional giropay details.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s billing details. Note that ","type":"text"},{"code":"billingDetails.name","type":"codeVoice"},{"type":"text","text":" is required for giropay PaymentMethods."}]}],"name":"billingDetails"},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(giropay:billingdetails:metadata:)"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(giropay:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Creates params for a giropay PaymentMethod;","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/paramsWith(giropay:billingDetails:metadata:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(giropay:billingDetails:metadata:)","title":"paramsWith(giropay:billingDetails:metadata:)","type":"topic","abstract":[{"text":"Creates params for a giropay PaymentMethod;","type":"text"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(giropay:billingdetails:metadata:)","navigatorTitle":[{"kind":"identifier","text":"paramsWithGiropay:billingDetails:metadata:"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paramsWith"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"giropay"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGiropayParams","text":"STPPaymentMethodGiropayParams"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodGiropayParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGiropayParams","title":"STPPaymentMethodGiropayParams","abstract":[{"type":"text","text":"An object representing parameters used to create a giropay Payment Method"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodgiropayparams","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodGiropayParams","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodGiropayParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Billing information associated with a "},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"title":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"paramsWithGiropay:billingDetails:metadata:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"paramsWithGiropay:billingDetails:metadata:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":" *) ","kind":"text"},{"text":"paramsWithGiropay:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGiropayParams","text":"STPPaymentMethodGiropayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodGiropayParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"giropay","kind":"internalParam"},{"kind":"text","text":" "},{"text":"billingDetails:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata:"},{"kind":"text","text":"("},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"giropay","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing additional giropay details."}]}]},{"name":"billingDetails","content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details. Note that "},{"code":"billingDetails.name","type":"codeVoice"},{"type":"text","text":" is required for giropay PaymentMethods."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}],"type":"paragraph"}],"name":"metadata"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(giropay:billingDetails:metadata:)\/title","value":"paramsWithGiropay:billingDetails:metadata:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(giropay:billingDetails:metadata:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"paramsWithGiropay:billingDetails:metadata:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"op":"replace","value":"STPPaymentMethodGiropayParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGiropayParams\/title"},{"value":[{"text":"STPPaymentMethodGiropayParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGiropayParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGiropayParams\/navigatorTitle","value":[{"text":"STPPaymentMethodGiropayParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","value":"STPPaymentMethodBillingDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]}]}]}