{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(fpx:billingDetails:metadata:)"},"sections":[],"metadata":{"navigatorTitle":[{"text":"paramsWithFPX:billingDetails:metadata:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paramsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fpx","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodFPXParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?) -> ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"}],"roleHeading":"Type Method","extendedModule":"StripePayments","modules":[{"name":"StripePayments"}],"role":"symbol","title":"paramsWith(fpx:billingDetails:metadata:)","externalID":"c:@CM@StripePayments@objc(cs)STPPaymentMethodParams(cm)paramsWithFPX:billingDetails:metadata:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Creates params for an FPX PaymentMethod."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(fpx:billingdetails:metadata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(fpx:billingdetails:metadata:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(paramsWithFPX:billingDetails:metadata:) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramsWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fpx"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams","text":"STPPaymentMethodFPXParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"fpx","content":[{"type":"paragraph","inlineContent":[{"text":"An object containing the user’s FPX bank details.","type":"text"}]}]},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}]}]},{"name":"metadata","content":[{"inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodFPXParams":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create an FPX Payment Method","type":"text"}],"type":"topic","title":"STPPaymentMethodFPXParams","url":"\/documentation\/stripepayments\/stppaymentmethodfpxparams","navigatorTitle":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"title":"STPPaymentMethodBillingDetails","role":"symbol","abstract":[{"text":"Billing information associated with a ","type":"text"},{"code":"STPPaymentMethod","type":"codeVoice"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodparams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"title":"STPPaymentMethodParams","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/paramsWith(fpx:billingDetails:metadata:)":{"role":"symbol","abstract":[{"type":"text","text":"Creates params for an FPX PaymentMethod."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramsWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fpx"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodFPXParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"}],"navigatorTitle":[{"kind":"identifier","text":"paramsWithFPX:billingDetails:metadata:"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(fpx:billingdetails:metadata:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(fpx:billingDetails:metadata:)","title":"paramsWith(fpx:billingDetails:metadata:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"paramsWithFPX:billingDetails:metadata:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paramsWithFPX:billingDetails:metadata:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"paramsWithFPX:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentMethodFPXParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodFPXParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodFPXParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fpx","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"billingDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"An object containing the user’s FPX bank details.","type":"text"}],"type":"paragraph"}],"name":"fpx"},{"content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}],"type":"paragraph"}],"name":"billingDetails"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}],"name":"metadata"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"STPPaymentMethodFPXParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodFPXParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodFPXParams\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodBillingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"op":"replace","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"op":"replace","value":"paramsWithFPX:billingDetails:metadata:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(fpx:billingDetails:metadata:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paramsWithFPX:billingDetails:metadata:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(fpx:billingDetails:metadata:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}