{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(sofort:billingDetails:metadata:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramsWith"},{"kind":"text","text":"("},{"text":"sofort","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodSofortParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSofortParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@CM@StripePayments@objc(cs)STPPaymentMethodParams(cm)paramsWithSofort:billingDetails:metadata:","roleHeading":"Type Method","title":"paramsWith(sofort:billingDetails:metadata:)","symbolKind":"method","navigatorTitle":[{"text":"paramsWithSofort:billingDetails:metadata:","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"abstract":[{"type":"text","text":"Creates params for a Sofort PaymentMethod;"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(paramsWithSofort:billingDetails:metadata:) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"paramsWith","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sofort"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodSofortParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSofortParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"parameters":[{"name":"sofort","content":[{"inlineContent":[{"type":"text","text":"An object containing additional Sofort details."}],"type":"paragraph"}]},{"name":"billingDetails","content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details. Note that "},{"code":"billingDetails.name","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"billingDetails.email","type":"codeVoice"},{"text":" are required to save bank details from a Sofort payment.","type":"text"}],"type":"paragraph"}]},{"name":"metadata","content":[{"inlineContent":[{"type":"text","text":"Additional information to attach to the PaymentMethod."}],"type":"paragraph"}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(sofort:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(sofort:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/paramsWith(sofort:billingDetails:metadata:)":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paramsWith"},{"text":"(","kind":"text"},{"text":"sofort","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodSofortParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSofortParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"metadata"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?) -> ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"}],"navigatorTitle":[{"text":"paramsWithSofort:billingDetails:metadata:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(sofort:billingDetails:metadata:)","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(sofort:billingdetails:metadata:)","title":"paramsWith(sofort:billingDetails:metadata:)","type":"topic","abstract":[{"text":"Creates params for a Sofort PaymentMethod;","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"abstract":[{"text":"Billing information associated with a ","type":"text"},{"code":"STPPaymentMethod","type":"codeVoice"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","type":"topic","navigatorTitle":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"title":"STPPaymentMethodBillingDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSofortParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodSofortParams","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodSofortParams"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams","url":"\/documentation\/stripepayments\/stppaymentmethodsofortparams","title":"STPPaymentMethodSofortParams","type":"topic","abstract":[{"text":"An object representing parameters used to create a Sofort Payment Method","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"title":"STPPaymentMethodParams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","kind":"symbol","abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"paramsWithSofort:billingDetails:metadata:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"paramsWithSofort:billingDetails:metadata:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"},{"kind":"text","text":" *) "},{"text":"paramsWithSofort:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodSofortParams","text":"STPPaymentMethodSofortParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofortParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sofort","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"billingDetails:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"text":" *) ","kind":"text"},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"metadata"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(sofort:billingDetails:metadata:)\/title","value":"paramsWithSofort:billingDetails:metadata:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"paramsWithSofort:billingDetails:metadata:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(sofort:billingDetails:metadata:)\/fragments"},{"value":"STPPaymentMethodBillingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams\/title","op":"replace","value":"STPPaymentMethodSofortParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofortParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodSofortParams"}],"op":"replace"},{"value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace"}]}]}
