{"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(oxxo:billingDetails:metadata:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(paramsWithOXXO:billingDetails:metadata:) ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paramsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"oxxo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethodOXXOParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?) -> "},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object containing additional OXXO details."}],"type":"paragraph"}],"name":"oxxo"},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing the user’s billing details. Note that "},{"type":"codeVoice","code":"billingDetails.name"},{"text":" is required for OXXO PaymentMethods.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}],"name":"metadata"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"metadata":{"modules":[{"name":"StripePayments"}],"symbolKind":"method","extendedModule":"StripePayments","externalID":"c:@CM@StripePayments@objc(cs)STPPaymentMethodParams(cm)paramsWithOXXO:billingDetails:metadata:","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paramsWith","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"oxxo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","text":"STPPaymentMethodOXXOParams"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?) -> "},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"}],"navigatorTitle":[{"text":"paramsWithOXXO:billingDetails:metadata:","kind":"identifier"}],"roleHeading":"Type Method","title":"paramsWith(oxxo:billingDetails:metadata:)","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(oxxo:billingdetails:metadata:)"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(oxxo:billingdetails:metadata:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Creates params for an OXXO PaymentMethod;","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","type":"topic","abstract":[{"text":"Billing information associated with a ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethod"},{"type":"text","text":" that may be used or required by particular types of payment methods."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"kind":"symbol","title":"STPPaymentMethodBillingDetails","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/paramsWith(oxxo:billingDetails:metadata:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paramsWith","kind":"identifier"},{"text":"(","kind":"text"},{"text":"oxxo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","kind":"typeIdentifier","text":"STPPaymentMethodOXXOParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":", "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(oxxo:billingdetails:metadata:)","abstract":[{"text":"Creates params for an OXXO PaymentMethod;","type":"text"}],"type":"topic","navigatorTitle":[{"text":"paramsWithOXXO:billingDetails:metadata:","kind":"identifier"}],"title":"paramsWith(oxxo:billingDetails:metadata:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(oxxo:billingDetails:metadata:)","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodOXXOParams":{"navigatorTitle":[{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams","url":"\/documentation\/stripepayments\/stppaymentmethodoxxoparams","title":"STPPaymentMethodOXXOParams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create an OXXO Payment Method"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"paramsWithOXXO:billingDetails:metadata:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"paramsWithOXXO:billingDetails:metadata:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"typeIdentifier","text":"STPPaymentMethodParams"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"paramsWithOXXO:"},{"text":"(","kind":"text"},{"text":"STPPaymentMethodOXXOParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodOXXOParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodOXXOParams","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"oxxo"},{"text":" ","kind":"text"},{"text":"billingDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentMethodBillingDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"text":"billingDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"metadata:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" *) "},{"text":"metadata","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"oxxo","content":[{"inlineContent":[{"text":"An object containing additional OXXO details.","type":"text"}],"type":"paragraph"}]},{"name":"billingDetails","content":[{"inlineContent":[{"type":"text","text":"An object containing the user’s billing details. Note that "},{"code":"billingDetails.name","type":"codeVoice"},{"type":"text","text":" is required for OXXO PaymentMethods."}],"type":"paragraph"}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"value":"STPPaymentMethodBillingDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]},{"op":"replace","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle"},{"value":"paramsWithOXXO:billingDetails:metadata:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(oxxo:billingDetails:metadata:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(oxxo:billingDetails:metadata:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"paramsWithOXXO:billingDetails:metadata:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/title","value":"STPPaymentMethodOXXOParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/fragments","op":"replace","value":[{"text":"STPPaymentMethodOXXOParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodOXXOParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodOXXOParams"}],"op":"replace"}]}]}