{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"abstract":[{"type":"text","text":"Creates params for an Alipay PaymentMethod."}],"sections":[],"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"StripePayments"}],"title":"paramsWith(alipay:billingDetails:metadata:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paramsWith"},{"kind":"text","text":"("},{"text":"alipay","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams","text":"STPPaymentMethodAlipayParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"billingDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?) -> "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier","text":"STPPaymentMethodParams"}],"navigatorTitle":[{"kind":"identifier","text":"paramsWithAlipay:billingDetails:metadata:"}],"roleHeading":"Type Method","externalID":"c:@CM@StripePayments@objc(cs)STPPaymentMethodParams(cm)paramsWithAlipay:billingDetails:metadata:","extendedModule":"StripePayments"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(alipay:billingdetails:metadata:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(alipay:billingdetails:metadata:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(alipay:billingDetails:metadata:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(paramsWithAlipay:billingDetails:metadata:) ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paramsWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"alipay"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams","text":"STPPaymentMethodAlipayParams"},{"text":", ","kind":"text"},{"text":"billingDetails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPPaymentMethodBillingDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?) -> ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","kind":"typeIdentifier","text":"STPPaymentMethodParams"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"An object containing additional Alipay details."}],"type":"paragraph"}],"name":"alipay"},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}]}]},{"name":"metadata","content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/paramsWith(alipay:billingDetails:metadata:)":{"type":"topic","abstract":[{"type":"text","text":"Creates params for an Alipay PaymentMethod."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/paramswith(alipay:billingdetails:metadata:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/paramsWith(alipay:billingDetails:metadata:)","navigatorTitle":[{"kind":"identifier","text":"paramsWithAlipay:billingDetails:metadata:"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paramsWith"},{"text":"(","kind":"text"},{"text":"alipay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodAlipayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"billingDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":"?, "},{"text":"metadata","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?) -> ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"}],"title":"paramsWith(alipay:billingDetails:metadata:)","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","title":"STPPaymentMethodParams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodParams"}],"role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAlipayParams":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodAlipayParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create an Alipay Payment Method."},{"type":"text","text":" "},{"type":"text","text":"There are currently no parameters to pass."}],"type":"topic","title":"STPPaymentMethodAlipayParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams","url":"\/documentation\/stripepayments\/stppaymentmethodalipayparams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodBillingDetails":{"url":"\/documentation\/stripepayments\/stppaymentmethodbillingdetails","title":"STPPaymentMethodBillingDetails","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}],"abstract":[{"text":"Billing information associated with a ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethod"},{"text":" that may be used or required by particular types of payment methods.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"paramsWithAlipay:billingDetails:metadata:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"paramsWithAlipay:billingDetails:metadata:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"paramsWithAlipay:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAlipayParams","text":"STPPaymentMethodAlipayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodAlipayParams","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"alipay"},{"text":" ","kind":"text"},{"text":"billingDetails:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodBillingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodBillingDetails","text":"STPPaymentMethodBillingDetails"},{"kind":"text","text":" *) "},{"text":"billingDetails","kind":"internalParam"},{"kind":"text","text":" "},{"text":"metadata:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"metadata","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":{"parameters":[{"name":"alipay","content":[{"inlineContent":[{"text":"An object containing additional Alipay details.","type":"text"}],"type":"paragraph"}]},{"name":"billingDetails","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An object containing the user’s billing details."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Additional information to attach to the PaymentMethod.","type":"text"}]}],"name":"metadata"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":"paramsWithAlipay:billingDetails:metadata:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(alipay:billingDetails:metadata:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1paramsWith(alipay:billingDetails:metadata:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"paramsWithAlipay:billingDetails:metadata:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/title","value":"STPPaymentMethodAlipayParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/fragments","value":[{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPPaymentMethodAlipayParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAlipayParams\/navigatorTitle"},{"op":"replace","value":"STPPaymentMethodBillingDetails","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/title"},{"op":"replace","value":[{"text":"STPPaymentMethodBillingDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodBillingDetails\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodBillingDetails"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}