{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/przelewy24","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"przelewy24"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodPrzelewy24Params","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24Params","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24Params"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/przelewy24"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/przelewy24"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"If this is a Przelewy24 PaymentMethod, this contains additional details.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"przelewy24","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24Params","kind":"typeIdentifier","text":"STPPaymentMethodPrzelewy24Params"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)przelewy24","title":"przelewy24","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"przelewy24"}],"role":"symbol"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/przelewy24":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"przelewy24","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24Params","kind":"typeIdentifier","text":"STPPaymentMethodPrzelewy24Params"},{"kind":"text","text":"?"}],"title":"przelewy24","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/przelewy24","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/przelewy24","navigatorTitle":[{"text":"przelewy24","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"If this is a Przelewy24 PaymentMethod, this contains additional details."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPrzelewy24Params":{"role":"symbol","title":"STPPaymentMethodPrzelewy24Params","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodPrzelewy24Params","kind":"identifier"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a Przelewy24 Payment Method"}],"url":"\/documentation\/stripepayments\/stppaymentmethodprzelewy24params","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24Params","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodPrzelewy24Params"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"przelewy24","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"przelewy24","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24Params","text":"STPPaymentMethodPrzelewy24Params","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24Params"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"przelewy24"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"text":"STPPaymentMethodParams","kind":"identifier"}]},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1przelewy24\/title","value":"przelewy24","op":"replace"},{"value":[{"text":"przelewy24","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1przelewy24\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24Params\/title","value":"STPPaymentMethodPrzelewy24Params"},{"value":[{"text":"STPPaymentMethodPrzelewy24Params","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24Params\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24Params\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodPrzelewy24Params"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}