{"metadata":{"title":"radarOptions","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)radarOptions","modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"text":"radarOptions","kind":"identifier"}],"fragments":[{"text":"radarOptions","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/radaroptions"]}],"abstract":[{"text":"Radar options that may contain HCaptcha token","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPRadarOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarOptions","text":"STPRadarOptions"},{"kind":"text","text":" * "},{"kind":"identifier","text":"radarOptions"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/radarOptions"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRadarOptions":{"fragments":[{"kind":"identifier","text":"STPRadarOptions"}],"abstract":[{"type":"text","text":"Values for STPRadarOptions"}],"title":"STPRadarOptions","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRadarOptions","url":"\/documentation\/stripepayments\/stpradaroptions","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"kind":"symbol","role":"symbol","type":"topic","title":"STPPaymentMethodParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"url":"\/documentation\/stripepayments\/stppaymentmethodparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/radarOptions":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/radarOptions","kind":"symbol","abstract":[{"type":"text","text":"Radar options that may contain HCaptcha token"}],"type":"topic","fragments":[{"text":"radarOptions","kind":"identifier"}],"title":"radarOptions","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/radaroptions"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentMethodParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace"}]}]}