{"metadata":{"title":"rawTypeString","navigatorTitle":[{"text":"rawTypeString","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawTypeString"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)rawTypeString","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Instance Property"},"sections":[],"abstract":[{"text":"The raw underlying type string sent to the server.","type":"text"},{"type":"text","text":" "},{"text":"Generally you should use ","type":"text"},{"code":"type","type":"codeVoice"},{"text":" instead unless you have a reason not to.","type":"text"},{"type":"text","text":" "},{"text":"You can use this if you want to create a param of a type not yet supported","type":"text"},{"type":"text","text":" "},{"type":"text","text":"by the current version of the SDK’s "},{"type":"codeVoice","code":"STPPaymentMethodType"},{"text":" enum.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Setting this to a value not known by the SDK causes "},{"code":"type","type":"codeVoice"},{"type":"text","text":" to"},{"type":"text","text":" "},{"type":"text","text":"return "},{"code":"STPPaymentMethodTypeUnknown","type":"codeVoice"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawTypeString"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/rawtypestring"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/rawtypestring"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/rawTypeString","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentMethodParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/rawTypeString":{"url":"\/documentation\/stripepayments\/stppaymentmethodparams\/rawtypestring","kind":"symbol","abstract":[{"text":"The raw underlying type string sent to the server.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Generally you should use "},{"code":"type","type":"codeVoice"},{"text":" instead unless you have a reason not to.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can use this if you want to create a param of a type not yet supported"},{"type":"text","text":" "},{"text":"by the current version of the SDK’s ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodType"},{"text":" enum.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Setting this to a value not known by the SDK causes "},{"code":"type","type":"codeVoice"},{"text":" to","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"return "},{"code":"STPPaymentMethodTypeUnknown","type":"codeVoice"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"rawTypeString","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"title":"rawTypeString","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/rawTypeString","navigatorTitle":[{"kind":"identifier","text":"rawTypeString"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"rawTypeString","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rawTypeString"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"rawTypeString","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"STPPaymentMethodParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title"},{"value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"},{"value":"rawTypeString","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1rawTypeString\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1rawTypeString\/fragments","op":"replace","value":[{"text":"rawTypeString","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}