{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"revolutPay","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodRevolutPayParams","text":"STPPaymentMethodRevolutPayParams"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)revolutPay","role":"symbol","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"revolutPay"}],"title":"revolutPay","roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/revolutpay"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/revolutpay"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"revolutPay"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodRevolutPayParams","text":"STPPaymentMethodRevolutPayParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPayParams"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/revolutPay"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"abstract":[{"type":"text","text":"If this is a RevolutPay PaymentMethod, this contains additional details."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/revolutPay":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/revolutPay","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/revolutpay","abstract":[{"type":"text","text":"If this is a RevolutPay PaymentMethod, this contains additional details."}],"type":"topic","title":"revolutPay","navigatorTitle":[{"kind":"identifier","text":"revolutPay"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"revolutPay"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodRevolutPayParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodRevolutPayParams","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodRevolutPayParams":{"abstract":[{"text":"An object representing parameters used to create a RevolutPay Payment Method","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodRevolutPayParams","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodrevolutpayparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPayParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodRevolutPayParams"}],"title":"STPPaymentMethodRevolutPayParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"url":"\/documentation\/stripepayments\/stppaymentmethodparams","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","abstract":[{"text":"An object representing parameters used to create a PaymentMethod object.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"revolutPay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"revolutPay","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodRevolutPayParams","text":"STPPaymentMethodRevolutPayParams","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodRevolutPayParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"revolutPay"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1revolutPay\/title","value":"revolutPay","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1revolutPay\/fragments","value":[{"text":"revolutPay","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPayParams\/title","value":"STPPaymentMethodRevolutPayParams"},{"value":[{"text":"STPPaymentMethodRevolutPayParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPayParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodRevolutPayParams\/navigatorTitle","value":[{"text":"STPPaymentMethodRevolutPayParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","op":"replace","value":"STPPaymentMethodParams"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]}]}]}