{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/rootObjectName()","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/rootobjectname()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/rootobjectname()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"code":"propertyNamesToFormFieldNamesMapping","type":"codeVoice"},{"text":" below.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(cm)rootObjectName","modules":[{"name":"StripePayments"}],"symbolKind":"method","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"rootObjectName()"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/rootObjectName()":{"type":"topic","title":"rootObjectName()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/rootObjectName()","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/rootobjectname()","kind":"symbol","abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"text":" below.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"rootObjectName","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"rootObjectName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"rootObjectName","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1rootObjectName()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams~1rootObjectName()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}]},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}