{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams"]]},"abstract":[{"type":"text","text":"If this is a ShopPay PaymentMethod, this contains additional details."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPPaymentMethodShopPayParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodShopPayParams"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shopPay"},{"text":";","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/shopPay","interfaceLanguage":"occ"},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodparams\/shoppay"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"shopPay","kind":"identifier"}],"symbolKind":"property","title":"shopPay","fragments":[{"kind":"identifier","text":"shopPay"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams(py)shopPay","modules":[{"name":"StripePayments"}]},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams/shopPay":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodparams\/shoppay","title":"shopPay","role":"symbol","fragments":[{"text":"shopPay","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams\/shopPay","abstract":[{"type":"text","text":"If this is a ShopPay PaymentMethod, this contains additional details."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodShopPayParams":{"kind":"symbol","abstract":[{"text":"An object representing parameters used to create a ShopPay Payment Method","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentmethodshoppayparams","title":"STPPaymentMethodShopPayParams","fragments":[{"text":"STPPaymentMethodShopPayParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodShopPayParams","type":"topic","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodParams":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodParams","kind":"identifier"}],"title":"STPPaymentMethodParams","url":"\/documentation\/stripepayments\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodParams","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"type":"topic","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/title","value":"STPPaymentMethodParams"},{"value":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}