{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/directorsProvided_objc"},"abstract":[{"type":"text","text":"Whether the company’s directors have been provided."},{"type":"text","text":" "},{"type":"text","text":"Set this Boolean to true after creating all the company’s directors with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.director requirement."},{"text":" ","type":"text"},{"type":"text","text":"This value is not automatically set to true after creating directors, so it needs to be updated to indicate all directors have been provided."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/directorsprovided_objc"]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/directorsprovided_objc"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"directorsProvided_objc"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":[],"role":"symbol","navigatorTitle":[{"text":"directorsProvided","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams(py)directorsProvided","symbolKind":"property","title":"directorsProvided_objc","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(directorsProvided) "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"directorsProvided_objc","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"title":"STPConnectAccountCompanyParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"abstract":[{"text":"Information about the company or business to use with ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/directorsProvided_objc":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"directorsProvided_objc","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"directorsProvided","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/directorsProvided_objc","title":"directorsProvided_objc","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/directorsprovided_objc","abstract":[{"type":"text","text":"Whether the company’s directors have been provided."},{"text":" ","type":"text"},{"type":"text","text":"Set this Boolean to true after creating all the company’s directors with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.director requirement."},{"type":"text","text":" "},{"type":"text","text":"This value is not automatically set to true after creating directors, so it needs to be updated to indicate all directors have been provided."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"directorsProvided","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"directorsProvided","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"directorsProvided"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"STPConnectAccountCompanyParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title"},{"value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments"},{"op":"replace","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle"},{"value":"directorsProvided","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1directorsProvided_objc\/title"},{"value":[{"kind":"identifier","text":"directorsProvided"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1directorsProvided_objc\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}