{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"directorsProvided","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"directorsProvided","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams(py)directorsProvided","symbolKind":"property","role":"symbol","title":"directorsProvided"},"abstract":[{"text":"Whether the company’s directors have been provided.","type":"text"},{"type":"text","text":" "},{"text":"Set this Boolean to true after creating all the company’s directors with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.director requirement.","type":"text"},{"text":" ","type":"text"},{"text":"This value is not automatically set to true after creating directors, so it needs to be updated to indicate all directors have been provided.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/directorsprovided"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/directorsprovided"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/directorsProvided"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"directorsProvided","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/directorsProvided":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"directorsProvided"},{"text":": ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"directorsProvided"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/directorsprovided","kind":"symbol","abstract":[{"text":"Whether the company’s directors have been provided.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Set this Boolean to true after creating all the company’s directors with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.director requirement."},{"text":" ","type":"text"},{"type":"text","text":"This value is not automatically set to true after creating directors, so it needs to be updated to indicate all directors have been provided."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/directorsProvided","title":"directorsProvided","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","title":"STPConnectAccountCompanyParams","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"abstract":[{"text":"Information about the company or business to use with ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"directorsProvided"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"directorsProvided"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"directorsProvided","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1directorsProvided\/title","value":"directorsProvided","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1directorsProvided\/fragments","value":[{"kind":"identifier","text":"directorsProvided"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title","op":"replace","value":"STPConnectAccountCompanyParams"},{"value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}