{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/directorsProvided-2djxd"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"directorsProvided","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"directorsProvided","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"externalID":"s:14StripePayments30STPConnectAccountCompanyParamsC17directorsProvidedSbSgvp","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"sections":[],"abstract":[{"type":"text","text":"Whether the company’s directors have been provided."},{"text":" ","type":"text"},{"type":"text","text":"Set this Boolean to true after creating all the company’s directors with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.director requirement."},{"text":" ","type":"text"},{"text":"This value is not automatically set to true after creating directors, so it needs to be updated to indicate all directors have been provided.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"directorsProvided"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"?"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/directorsprovided-2djxd"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/directorsProvided-2djxd":{"title":"directorsProvided","abstract":[{"text":"Whether the company’s directors have been provided.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Set this Boolean to true after creating all the company’s directors with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.director requirement."},{"type":"text","text":" "},{"type":"text","text":"This value is not automatically set to true after creating directors, so it needs to be updated to indicate all directors have been provided."}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/directorsprovided-2djxd","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/directorsProvided-2djxd","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"directorsProvided","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","abstract":[{"type":"text","text":"Information about the company or business to use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"role":"symbol","title":"STPConnectAccountCompanyParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title","value":"STPConnectAccountCompanyParams"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}]}]}]}