{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kanaAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","kind":"typeIdentifier","text":"STPConnectAccountAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"The Kana variation of the company’s primary address (Japan only).","type":"text"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/kanaAddress"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/kanaaddress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/kanaaddress"]}],"metadata":{"roleHeading":"Instance Property","title":"kanaAddress","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams(py)kanaAddress","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"kanaAddress"}],"role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kanaAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","kind":"typeIdentifier","text":"STPConnectAccountAddress"},{"kind":"text","text":"?"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","title":"STPConnectAccountCompanyParams","abstract":[{"text":"Information about the company or business to use with ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/kanaAddress":{"navigatorTitle":[{"text":"kanaAddress","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/kanaaddress","abstract":[{"text":"The Kana variation of the company’s primary address (Japan only).","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kanaAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPConnectAccountAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/kanaAddress","kind":"symbol","role":"symbol","title":"kanaAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountAddress","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountaddress","abstract":[{"type":"text","text":"An address to use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"STPConnectAccountAddress","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","role":"symbol","title":"STPConnectAccountAddress"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"kanaAddress"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"kanaAddress","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","text":"STPConnectAccountAddress","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"kanaAddress","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title","op":"replace","value":"STPConnectAccountCompanyParams"},{"op":"replace","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments"},{"op":"replace","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle"},{"op":"replace","value":"kanaAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1kanaAddress\/title"},{"op":"replace","value":[{"text":"kanaAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1kanaAddress\/fragments"},{"op":"replace","value":"STPConnectAccountAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/title"},{"op":"replace","value":[{"text":"STPConnectAccountAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountAddress"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/navigatorTitle"}]}]}