{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/kanjiAddress"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"kanjiAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","text":"STPConnectAccountAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/kanjiaddress"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/kanjiaddress"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams(py)kanjiAddress","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"kanjiAddress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPConnectAccountAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"kanjiAddress","navigatorTitle":[{"text":"kanjiAddress","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"abstract":[{"text":"The Kanji variation of the company’s primary address (Japan only).","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountAddress":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountAddress","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconnectaccountaddress","navigatorTitle":[{"text":"STPConnectAccountAddress","kind":"identifier"}],"title":"STPConnectAccountAddress","type":"topic","abstract":[{"type":"text","text":"An address to use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","title":"STPConnectAccountCompanyParams","abstract":[{"text":"Information about the company or business to use with ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/kanjiAddress":{"role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/kanjiaddress","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kanjiAddress"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress","text":"STPConnectAccountAddress"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/kanjiAddress","abstract":[{"type":"text","text":"The Kanji variation of the company’s primary address (Japan only)."}],"navigatorTitle":[{"text":"kanjiAddress","kind":"identifier"}],"title":"kanjiAddress","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"kanjiAddress","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"kanjiAddress","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountAddress","text":"STPConnectAccountAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountAddress"},{"kind":"text","text":" * "},{"text":"kanjiAddress","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"STPConnectAccountAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/fragments","value":[{"kind":"identifier","text":"STPConnectAccountAddress"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountAddress\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountAddress"}]},{"value":"STPConnectAccountCompanyParams","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1kanjiAddress\/title","value":"kanjiAddress","op":"replace"},{"value":[{"text":"kanjiAddress","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1kanjiAddress\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}