{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/ownersProvided-5q29o","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"abstract":[{"type":"text","text":"Whether the company’s owners have been provided."},{"type":"text","text":" "},{"type":"text","text":"Set this Boolean to true after creating all the company’s owners with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.owner requirement."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/ownersprovided-5q29o"]}],"metadata":{"role":"symbol","title":"ownersProvided","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"symbolKind":"property","externalID":"s:14StripePayments30STPConnectAccountCompanyParamsC14ownersProvidedSbSgvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ownersProvided","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ownersProvided","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","abstract":[{"type":"text","text":"Information about the company or business to use with "},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":".","type":"text"}],"title":"STPConnectAccountCompanyParams","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/ownersProvided-5q29o":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/ownersProvided-5q29o","role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/ownersprovided-5q29o","abstract":[{"type":"text","text":"Whether the company’s owners have been provided."},{"type":"text","text":" "},{"type":"text","text":"Set this Boolean to true after creating all the company’s owners with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.owner requirement."}],"title":"ownersProvided","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ownersProvided"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title","op":"replace","value":"STPConnectAccountCompanyParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments","op":"replace","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle","op":"replace","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}]}]}]}