{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/ownersProvided","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"StripePayments"}],"title":"ownersProvided","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams(py)ownersProvided","navigatorTitle":[{"text":"ownersProvided","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ownersProvided","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"symbolKind":"property"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ownersProvided"},{"kind":"text","text":": "},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/ownersprovided"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/ownersprovided"]}],"abstract":[{"text":"Whether the company’s owners have been provided.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Set this Boolean to true after creating all the company’s owners with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.owner requirement."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/ownersProvided":{"url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/ownersprovided","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ownersProvided","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"?","kind":"text"}],"abstract":[{"text":"Whether the company’s owners have been provided.","type":"text"},{"type":"text","text":" "},{"text":"Set this Boolean to true after creating all the company’s owners with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.owner requirement.","type":"text"}],"title":"ownersProvided","role":"symbol","navigatorTitle":[{"text":"ownersProvided","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/ownersProvided"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"title":"STPConnectAccountCompanyParams","abstract":[{"text":"Information about the company or business to use with ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountParams"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ownersProvided"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ownersProvided"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ownersProvided"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ownersProvided","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1ownersProvided\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1ownersProvided\/fragments","value":[{"text":"ownersProvided","kind":"identifier"}],"op":"replace"},{"value":"STPConnectAccountCompanyParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title"},{"value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}