{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/ownersprovided_objc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/ownersprovided_objc"]}],"abstract":[{"type":"text","text":"Whether the company’s owners have been provided."},{"type":"text","text":" "},{"type":"text","text":"Set this Boolean to true after creating all the company’s owners with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.owner requirement."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ownersProvided"}],"modules":[{"name":"StripePayments"}],"title":"ownersProvided_objc","platforms":[],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ownersProvided_objc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"?"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams(py)ownersProvided","role":"symbol","symbolKind":"property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ownersProvided) ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ownersProvided_objc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/ownersProvided_objc","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"abstract":[{"text":"Information about the company or business to use with ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","kind":"symbol","type":"topic","title":"STPConnectAccountCompanyParams","role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/ownersProvided_objc":{"navigatorTitle":[{"kind":"identifier","text":"ownersProvided"}],"type":"topic","title":"ownersProvided_objc","abstract":[{"type":"text","text":"Whether the company’s owners have been provided."},{"type":"text","text":" "},{"type":"text","text":"Set this Boolean to true after creating all the company’s owners with the Persons API (https:\/\/stripe.com\/docs\/api\/persons) for accounts with a relationship.owner requirement."}],"kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ownersProvided_objc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/ownersProvided_objc","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/ownersprovided_objc"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"ownersProvided","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ownersProvided","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":" * ","kind":"text"},{"text":"ownersProvided","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title","value":"STPConnectAccountCompanyParams","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1ownersProvided_objc\/title","value":"ownersProvided","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1ownersProvided_objc\/fragments","value":[{"text":"ownersProvided","kind":"identifier"}],"op":"replace"}]}]}