{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"collectionGroup","title":"STPFormEncodable Implementations","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/stpformencodable-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/stpformencodable-implementations"]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/rootObjectName()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/STPFormEncodable-Implementations","interfaceLanguage":"swift"},"kind":"article","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/propertyNamesToFormFieldNamesMapping()":{"title":"propertyNamesToFormFieldNamesMapping()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/propertyNamesToFormFieldNamesMapping()","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/propertynamestoformfieldnamesmapping()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"code":"expMonth","type":"codeVoice"},{"type":"text","text":", but the Stripe API expects a field called "},{"code":"exp_month","type":"codeVoice"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"kind":"symbol","role":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"title":"STPConnectAccountCompanyParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"abstract":[{"type":"text","text":"Information about the company or business to use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/rootObjectName()":{"kind":"symbol","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/rootobjectname()","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/rootObjectName()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"type":"text","text":" below."}],"title":"rootObjectName()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/rootObjectName()"],"generated":true}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1propertyNamesToFormFieldNamesMapping()\/title","op":"replace","value":"propertyNamesToFormFieldNamesMapping"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1propertyNamesToFormFieldNamesMapping()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title","op":"replace","value":"STPConnectAccountCompanyParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments","op":"replace","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1rootObjectName()\/title","op":"replace","value":"rootObjectName"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1rootObjectName()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}]}]}]}