{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/vatID","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/vatid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/vatid"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"vatID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams"]]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"The VAT number of the company.","type":"text"}],"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"vatID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol","title":"vatID","navigatorTitle":[{"kind":"identifier","text":"vatID"}],"externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams(py)vatID"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"type":"topic","url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","abstract":[{"type":"text","text":"Information about the company or business to use with "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":"."}],"role":"symbol","title":"STPConnectAccountCompanyParams","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams/vatID":{"url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams\/vatid","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams\/vatID","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"vatID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"vatID","kind":"identifier"}],"abstract":[{"type":"text","text":"The VAT number of the company."}],"title":"vatID","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"vatID","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"vatID"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"vatID"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"STPConnectAccountCompanyParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1vatID\/title","value":"vatID"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams~1vatID\/fragments","value":[{"text":"vatID","kind":"identifier"}]}]}]}