{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/errored"},"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountstatus\/errored"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpbankaccountstatus\/errored"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"STPBankAccountStatusErrored","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPBankAccountStatus@STPBankAccountStatusErrored","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errored","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"role":"symbol","title":"STPBankAccountStatus.errored"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"A transfer sent to this bank account has failed.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errored"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus":{"abstract":[{"type":"text","text":"Possible validation states for a bank account."}],"role":"symbol","navigatorTitle":[{"text":"STPBankAccountStatus","kind":"identifier"}],"title":"STPBankAccountStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","url":"\/documentation\/stripepayments\/stpbankaccountstatus","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPBankAccountStatus","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/errored":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/errored","navigatorTitle":[{"text":"STPBankAccountStatusErrored","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A transfer sent to this bank account has failed."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errored","kind":"identifier"}],"title":"STPBankAccountStatus.errored","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/errored"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPBankAccountStatusErrored","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"STPBankAccountStatusErrored","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPBankAccountStatusErrored"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPBankAccountStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPBankAccountStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/fragments","op":"replace"},{"value":[{"text":"STPBankAccountStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/navigatorTitle","op":"replace"},{"value":"STPBankAccountStatusErrored","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1errored\/title","op":"replace"},{"value":[{"text":"STPBankAccountStatusErrored","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1errored\/fragments","op":"replace"}]}]}