{"metadata":{"roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountStatusVerificationFailed"}],"title":"STPBankAccountStatus.verificationFailed","modules":[{"name":"StripePayments"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPBankAccountStatus@STPBankAccountStatusVerificationFailed","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"verificationFailed"}]},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verificationFailed","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verificationFailed","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpbankaccountstatus\/verificationfailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountstatus\/verificationfailed"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus"]]},"abstract":[{"type":"text","text":"Verification for this bank account has failed."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/verificationFailed":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verificationFailed","role":"symbol","url":"\/documentation\/stripepayments\/stpbankaccountstatus\/verificationfailed","type":"topic","abstract":[{"type":"text","text":"Verification for this bank account has failed."}],"title":"STPBankAccountStatus.verificationFailed","navigatorTitle":[{"kind":"identifier","text":"STPBankAccountStatusVerificationFailed"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verificationFailed"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus":{"navigatorTitle":[{"text":"STPBankAccountStatus","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Possible validation states for a bank account.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPBankAccountStatus"}],"title":"STPBankAccountStatus","type":"topic","url":"\/documentation\/stripepayments\/stpbankaccountstatus","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"STPBankAccountStatusVerificationFailed","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"STPBankAccountStatusVerificationFailed","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"STPBankAccountStatusVerificationFailed"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"STPBankAccountStatusVerificationFailed","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1verificationFailed\/title"},{"op":"replace","value":[{"text":"STPBankAccountStatusVerificationFailed","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1verificationFailed\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/title","value":"STPBankAccountStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/fragments","value":[{"text":"STPBankAccountStatus","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPBankAccountStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/navigatorTitle"}]}]}