{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/activityIndicatorViewStyle"},"abstract":[{"type":"text","text":"The style of "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"type":"text","text":"s displayed."},{"type":"text","text":" "},{"type":"text","text":"This should contrast with "},{"code":"backgroundColor","type":"codeVoice"},{"type":"text","text":".  Defaults to gray."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activityIndicatorViewStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"text":".","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIActivityIndicatorViewStyle"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicatorViewStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","text":"UIActivityIndicatorView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIActivityIndicatorViewStyle","text":"Style"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(py)activityIndicatorViewStyle","modules":[{"name":"StripePayments"}],"role":"symbol","title":"activityIndicatorViewStyle","navigatorTitle":[{"kind":"identifier","text":"activityIndicatorViewStyle"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/activityindicatorviewstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/activityindicatorviewstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/activityIndicatorViewStyle":{"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/activityindicatorviewstyle","navigatorTitle":[{"kind":"identifier","text":"activityIndicatorViewStyle"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/activityIndicatorViewStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"activityIndicatorViewStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"c:@E@UIActivityIndicatorViewStyle"}],"role":"symbol","abstract":[{"type":"text","text":"The style of "},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"type":"text","text":"s displayed."},{"type":"text","text":" "},{"type":"text","text":"This should contrast with "},{"type":"codeVoice","code":"backgroundColor"},{"type":"text","text":".  Defaults to gray."}],"title":"activityIndicatorViewStyle"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"type":"text","text":" "},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" APIs."},{"type":"text","text":" "},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"type":"text","text":" "},{"type":"text","text":"make to your "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" instance."}],"title":"STPThreeDSUICustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpthreedsuicustomization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSUICustomization"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"activityIndicatorViewStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"activityIndicatorViewStyle","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@E@UIActivityIndicatorViewStyle","text":"UIActivityIndicatorViewStyle","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"activityIndicatorViewStyle","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1activityIndicatorViewStyle\/title","value":"activityIndicatorViewStyle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1activityIndicatorViewStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"activityIndicatorViewStyle"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","op":"replace","value":"STPThreeDSUICustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","op":"replace","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle","op":"replace","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}