{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"blurStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIBlurEffect","kind":"typeIdentifier","text":"UIBlurEffect"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIBlurEffectStyle","text":"Style"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/blurstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/blurstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"blurStyle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBlurEffect","text":"UIBlurEffect"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@UIBlurEffectStyle","text":"Style","kind":"typeIdentifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(py)blurStyle","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"blurStyle"}],"title":"blurStyle"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/blurStyle"},"sections":[],"abstract":[{"text":"The style of the ","type":"text"},{"code":"UIBlurEffect","type":"codeVoice"},{"type":"text","text":" displayed underneath the "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"UIBlurEffectStyleLight"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/blurStyle":{"role":"symbol","navigatorTitle":[{"text":"blurStyle","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"blurStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBlurEffect","text":"UIBlurEffect"},{"kind":"text","text":"."},{"text":"Style","preciseIdentifier":"c:@E@UIBlurEffectStyle","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/blurstyle","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/blurStyle","abstract":[{"type":"text","text":"The style of the "},{"type":"codeVoice","code":"UIBlurEffect"},{"text":" displayed underneath the ","type":"text"},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to "},{"code":"UIBlurEffectStyleLight","type":"codeVoice"},{"text":".","type":"text"}],"title":"blurStyle"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPThreeDSUICustomization","kind":"identifier"}],"title":"STPThreeDSUICustomization","role":"symbol","navigatorTitle":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","url":"\/documentation\/stripepayments\/stpthreedsuicustomization","abstract":[{"text":"The ","type":"text"},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"text":" ","type":"text"},{"text":"Note: It’s important to configure this object appropriately before calling any ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" APIs.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"type":"text","text":" "},{"type":"text","text":"make to your "},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"type":"text","text":" instance."}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"blurStyle","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"blurStyle"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@E@UIBlurEffectStyle","text":"UIBlurEffectStyle","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"blurStyle","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"blurStyle","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1blurStyle\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1blurStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"blurStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","value":"STPThreeDSUICustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"op":"replace"},{"value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}