{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/buttonCustomization(for:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(buttonCustomizationForButtonType:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buttonCustomization","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"buttonType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","text":"STPThreeDSCustomizationButtonType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","text":"STPThreeDSButtonCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The button type to retrieve a customization object for.","type":"text"}],"type":"paragraph"}],"name":"buttonType"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A button customization object, or the default if none was set."}]}],"kind":"content"},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"name":"See Also","content":[{"type":"paragraph","inlineContent":[{"text":"STPThreeDSButtonCustomization","type":"text"}]}],"type":"aside","style":"note"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/buttoncustomization(for:)"]},{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/buttoncustomization(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Retrieves a button customization object for the given button type."}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"buttonCustomization","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"STPThreeDSCustomizationButtonType","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"STPThreeDSButtonCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","kind":"typeIdentifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(im)buttonCustomizationForButtonType:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"buttonCustomizationForButtonType:"}],"title":"buttonCustomization(for:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"navigatorTitle":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"title":"STPThreeDSCustomizationButtonType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An enum that defines the different types of buttons that are able to be customized."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"title":"STPThreeDSButtonCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","abstract":[{"type":"text","text":"A customization object to use to configure the UI of a button."}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"title":"STPThreeDSUICustomization","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSUICustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"text":" ","type":"text"},{"text":"Note: It’s important to configure this object appropriately before calling any ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" APIs.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"type":"text","text":" "},{"text":"make to your ","type":"text"},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"text":" instance.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/buttonCustomization(for:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/buttonCustomization(for:)","abstract":[{"text":"Retrieves a button customization object for the given button type.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"buttonCustomization"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPThreeDSCustomizationButtonType","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","text":"STPThreeDSButtonCustomization"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/buttoncustomization(for:)","role":"symbol","navigatorTitle":[{"text":"buttonCustomizationForButtonType:","kind":"identifier"}],"title":"buttonCustomization(for:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"buttonCustomizationForButtonType:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"buttonCustomizationForButtonType:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","kind":"typeIdentifier","text":"STPThreeDSButtonCustomization"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buttonCustomizationForButtonType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"STPThreeDSCustomizationButtonType","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"buttonType"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title","value":"STPThreeDSCustomizationButtonType"},{"value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments","op":"replace"},{"op":"replace","value":"STPThreeDSButtonCustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","value":"STPThreeDSUICustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}]},{"value":"buttonCustomizationForButtonType:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1buttonCustomization(for:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1buttonCustomization(for:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"buttonCustomizationForButtonType:","kind":"identifier"}]}]}]}
