{"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(cm)defaultSettings","symbolKind":"method","title":"defaultSettings()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"STPThreeDSUICustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"defaultSettings","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/defaultSettings()"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"STPThreeDSUICustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/defaultsettings()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/defaultsettings()"]}],"abstract":[{"type":"text","text":"The default settings.  See individual properties for their default values."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/defaultSettings()":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/defaultSettings()","title":"defaultSettings()","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultSettings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"STPThreeDSUICustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization","kind":"typeIdentifier"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/defaultsettings()","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"defaultSettings","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The default settings.  See individual properties for their default values.","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"title":"STPThreeDSUICustomization","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"type":"text","text":" "},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" APIs."},{"type":"text","text":" "},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"type":"text","text":" "},{"type":"text","text":"make to your "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" instance."}],"navigatorTitle":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSUICustomization","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"defaultSettings","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"defaultSettings","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization","text":"STPThreeDSUICustomization"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"defaultSettings"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"defaultSettings","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1defaultSettings()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"defaultSettings","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1defaultSettings()\/fragments"},{"value":"STPThreeDSUICustomization","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title"},{"value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments"},{"value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle"}]}]}