{"abstract":[{"type":"text","text":"Provides custom settings for the footer the challenge view can display containing additional details."},{"type":"text","text":" "},{"text":"The default is ","type":"text"},{"type":"codeVoice","code":"STPThreeDSFooterCustomization.defaultSettings()"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"footerCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPThreeDSFooterCustomization","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(py)footerCustomization","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"footerCustomization"}],"title":"footerCustomization","roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"footerCustomization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization","text":"STPThreeDSFooterCustomization"}],"symbolKind":"property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/footercustomization"]},{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/footercustomization"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/footerCustomization"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"url":"\/documentation\/stripepayments\/stpthreedsuicustomization","role":"symbol","navigatorTitle":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"text":" provides configuration for UI elements displayed during 3D Secure authentication.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" APIs.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"text":" ","type":"text"},{"text":"make to your ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"text":" instance.","type":"text"}],"title":"STPThreeDSUICustomization","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSUICustomization"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSFooterCustomization":{"abstract":[{"text":"The Challenge view displays a footer with additional details that","type":"text"},{"type":"text","text":" "},{"text":"expand when tapped. This object configures the appearance of that view.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}],"url":"\/documentation\/stripepayments\/stpthreedsfootercustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSFooterCustomization","kind":"identifier"}],"title":"STPThreeDSFooterCustomization","type":"topic","role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/footerCustomization":{"title":"footerCustomization","type":"topic","navigatorTitle":[{"text":"footerCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/footercustomization","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/footerCustomization","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"footerCustomization"},{"kind":"text","text":": "},{"text":"STPThreeDSFooterCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization"}],"abstract":[{"type":"text","text":"Provides custom settings for the footer the challenge view can display containing additional details."},{"text":" ","type":"text"},{"text":"The default is ","type":"text"},{"code":"STPThreeDSFooterCustomization.defaultSettings()","type":"codeVoice"},{"type":"text","text":"."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"footerCustomization","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"footerCustomization","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"STPThreeDSFooterCustomization","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSFooterCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSFooterCustomization"},{"kind":"text","text":" * "},{"text":"footerCustomization","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","value":"STPThreeDSUICustomization"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/title","value":"STPThreeDSFooterCustomization","op":"replace"},{"value":[{"kind":"identifier","text":"STPThreeDSFooterCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/fragments","op":"replace"},{"value":[{"text":"STPThreeDSFooterCustomization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSFooterCustomization\/navigatorTitle"},{"value":"footerCustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1footerCustomization\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1footerCustomization\/fragments","value":[{"kind":"identifier","text":"footerCustomization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}