{"metadata":{"roleHeading":"Initializer","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(im)init","modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/init()"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/init()"},"abstract":[{"text":":nodoc:","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","url":"\/documentation\/stripepayments","kind":"symbol","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/init()":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/init()","abstract":[{"text":":nodoc:","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"text":" ","type":"text"},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" APIs."},{"type":"text","text":" "},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"type":"text","text":" "},{"type":"text","text":"make to your "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" instance."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSUICustomization"}],"navigatorTitle":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"role":"symbol","title":"STPThreeDSUICustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","url":"\/documentation\/stripepayments\/stpthreedsuicustomization"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"init","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","value":"STPThreeDSUICustomization","op":"replace"},{"value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","op":"replace"},{"op":"replace","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}