{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/labelcustomization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/labelcustomization"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Provides custom settings for labels.","type":"text"},{"text":" ","type":"text"},{"text":"The default is ","type":"text"},{"type":"codeVoice","code":"STPThreeDSLabelCustomization.defaultSettings()"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/labelCustomization","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"labelCustomization","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labelCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization","text":"STPThreeDSLabelCustomization","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(py)labelCustomization","navigatorTitle":[{"text":"labelCustomization","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labelCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization","text":"STPThreeDSLabelCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/labelCustomization":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/labelCustomization","kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/labelcustomization","type":"topic","abstract":[{"text":"Provides custom settings for labels.","type":"text"},{"text":" ","type":"text"},{"text":"The default is ","type":"text"},{"code":"STPThreeDSLabelCustomization.defaultSettings()","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"labelCustomization","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"labelCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPThreeDSLabelCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"labelCustomization","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSLabelCustomization":{"type":"topic","url":"\/documentation\/stripepayments\/stpthreedslabelcustomization","title":"STPThreeDSLabelCustomization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSLabelCustomization","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization","abstract":[{"text":"A customization object to use to configure the UI of a text label.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"STPThreeDSLabelCustomization","kind":"identifier"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"text":" provides configuration for UI elements displayed during 3D Secure authentication.","type":"text"},{"text":" ","type":"text"},{"text":"Note: It’s important to configure this object appropriately before calling any ","type":"text"},{"type":"codeVoice","code":"STPPaymentHandler"},{"text":" APIs.","type":"text"},{"text":" ","type":"text"},{"text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you","type":"text"},{"text":" ","type":"text"},{"text":"make to your ","type":"text"},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"text":" instance.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSUICustomization"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"type":"topic","title":"STPThreeDSUICustomization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"labelCustomization"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"labelCustomization"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSLabelCustomization","text":"STPThreeDSLabelCustomization","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSLabelCustomization"},{"text":" * ","kind":"text"},{"text":"labelCustomization","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1labelCustomization\/title","op":"replace","value":"labelCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1labelCustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"labelCustomization"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/title","op":"replace","value":"STPThreeDSLabelCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSLabelCustomization"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSLabelCustomization\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSLabelCustomization"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","op":"replace","value":"STPThreeDSUICustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle","op":"replace","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}]}]}]}