{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigationBarCustomization","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPThreeDSNavigationBarCustomization","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(py)navigationBarCustomization","roleHeading":"Instance Property","title":"navigationBarCustomization","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"navigationBarCustomization","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization","text":"STPThreeDSNavigationBarCustomization","kind":"typeIdentifier"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"navigationBarCustomization","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/navigationbarcustomization"]},{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/navigationbarcustomization"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Provides custom settings for the UINavigationBar of all UIViewControllers displayed during 3D Secure authentication."},{"type":"text","text":" "},{"text":"The default is ","type":"text"},{"type":"codeVoice","code":"STPThreeDSNavigationBarCustomization.defaultSettings()"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/navigationBarCustomization"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/navigationBarCustomization":{"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/navigationbarcustomization","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Provides custom settings for the UINavigationBar of all UIViewControllers displayed during 3D Secure authentication."},{"type":"text","text":" "},{"text":"The default is ","type":"text"},{"type":"codeVoice","code":"STPThreeDSNavigationBarCustomization.defaultSettings()"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/navigationBarCustomization","type":"topic","title":"navigationBarCustomization","navigatorTitle":[{"kind":"identifier","text":"navigationBarCustomization"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigationBarCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization","text":"STPThreeDSNavigationBarCustomization"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"type":"text","text":" "},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" APIs."},{"text":" ","type":"text"},{"text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"make to your "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"text":" instance.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSUICustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsuicustomization","kind":"symbol","role":"symbol","title":"STPThreeDSUICustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSUICustomization"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSNavigationBarCustomization":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"navigatorTitle":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsnavigationbarcustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","title":"STPThreeDSNavigationBarCustomization","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A customization object to use to configure a UINavigationBar."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"navigationBarCustomization","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"navigationBarCustomization"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"STPThreeDSNavigationBarCustomization","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSNavigationBarCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSNavigationBarCustomization"},{"kind":"text","text":" * "},{"kind":"identifier","text":"navigationBarCustomization"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1navigationBarCustomization\/title","op":"replace","value":"navigationBarCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1navigationBarCustomization\/fragments","value":[{"kind":"identifier","text":"navigationBarCustomization"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","value":"STPThreeDSUICustomization","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/title","value":"STPThreeDSNavigationBarCustomization"},{"value":[{"text":"STPThreeDSNavigationBarCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPThreeDSNavigationBarCustomization"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSNavigationBarCustomization\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}