{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"selectionCustomization","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(py)selectionCustomization","symbolKind":"property","role":"symbol","title":"selectionCustomization","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPThreeDSSelectionCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization"}],"modules":[{"name":"StripePayments"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/selectionCustomization","interfaceLanguage":"swift"},"abstract":[{"text":"Provides custom settings for radio buttons and checkboxes.","type":"text"},{"text":" ","type":"text"},{"text":"The default is ","type":"text"},{"code":"STPThreeDSSelectionCustomization.defaultSettings()","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectionCustomization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization","text":"STPThreeDSSelectionCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/selectioncustomization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/selectioncustomization"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/selectionCustomization":{"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/selectioncustomization","abstract":[{"text":"Provides custom settings for radio buttons and checkboxes.","type":"text"},{"text":" ","type":"text"},{"text":"The default is ","type":"text"},{"code":"STPThreeDSSelectionCustomization.defaultSettings()","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectionCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPThreeDSSelectionCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization"}],"navigatorTitle":[{"text":"selectionCustomization","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/selectionCustomization","kind":"symbol","title":"selectionCustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"title":"STPThreeDSUICustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSUICustomization"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","abstract":[{"text":"The ","type":"text"},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"text":" provides configuration for UI elements displayed during 3D Secure authentication.","type":"text"},{"text":" ","type":"text"},{"text":"Note: It’s important to configure this object appropriately before calling any ","type":"text"},{"code":"STPPaymentHandler","type":"codeVoice"},{"text":" APIs.","type":"text"},{"text":" ","type":"text"},{"text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you","type":"text"},{"text":" ","type":"text"},{"text":"make to your ","type":"text"},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"text":" instance.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSSelectionCustomization":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"navigatorTitle":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpthreedsselectioncustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization","role":"symbol","title":"STPThreeDSSelectionCustomization","abstract":[{"text":"A customization object that configures the appearance of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"radio buttons and checkboxes."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"selectionCustomization"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"selectionCustomization"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSSelectionCustomization","text":"STPThreeDSSelectionCustomization","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSSelectionCustomization","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"selectionCustomization","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1selectionCustomization\/title","op":"replace","value":"selectionCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1selectionCustomization\/fragments","op":"replace","value":[{"text":"selectionCustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","op":"replace","value":"STPThreeDSUICustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments","op":"replace","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle","op":"replace","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/title","op":"replace","value":"STPThreeDSSelectionCustomization"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPThreeDSSelectionCustomization"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSSelectionCustomization\/navigatorTitle","op":"replace","value":[{"text":"STPThreeDSSelectionCustomization","kind":"identifier"}]}]}]}