{"metadata":{"symbolKind":"method","modules":[{"name":"StripePayments"}],"title":"setButtonCustomization(_:for:)","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(im)setButtonCustomization:forType:","navigatorTitle":[{"kind":"identifier","text":"setButtonCustomization:forType:"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setButtonCustomization"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","text":"STPThreeDSButtonCustomization"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","text":"STPThreeDSCustomizationButtonType"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/setbuttoncustomization(_:for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/setbuttoncustomization(_:for:)"]}],"abstract":[{"type":"text","text":"Sets a given button customization for the specified type."}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/setButtonCustomization(_:for:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(setButtonCustomization:forType:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setButtonCustomization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buttonCustomization"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","text":"STPThreeDSButtonCustomization"},{"kind":"text","text":", "},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"buttonType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","text":"STPThreeDSCustomizationButtonType"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"buttonCustomization","content":[{"inlineContent":[{"text":"The buttom customization to use.","type":"text"}],"type":"paragraph"}]},{"name":"buttonType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of button to use the customization for."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"type":"topic","url":"\/documentation\/stripepayments\/stpthreedsuicustomization","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"type":"text","text":" "},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"type":"codeVoice","code":"STPPaymentHandler"},{"type":"text","text":" APIs."},{"type":"text","text":" "},{"type":"text","text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you"},{"type":"text","text":" "},{"type":"text","text":"make to your "},{"type":"codeVoice","code":"STPThreeDSUICustomization"},{"type":"text","text":" instance."}],"title":"STPThreeDSUICustomization","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPThreeDSUICustomization"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSUICustomization"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSCustomizationButtonType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"navigatorTitle":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","type":"topic","abstract":[{"text":"An enum that defines the different types of buttons that are able to be customized.","type":"text"}],"title":"STPThreeDSCustomizationButtonType","url":"\/documentation\/stripepayments\/stpthreedscustomizationbuttontype","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSButtonCustomization":{"role":"symbol","navigatorTitle":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"abstract":[{"type":"text","text":"A customization object to use to configure the UI of a button."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","type":"topic","title":"STPThreeDSButtonCustomization","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpthreedsbuttoncustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/setButtonCustomization(_:for:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/setButtonCustomization(_:for:)","url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/setbuttoncustomization(_:for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setButtonCustomization","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization","text":"STPThreeDSButtonCustomization","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType","text":"STPThreeDSCustomizationButtonType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Sets a given button customization for the specified type."}],"type":"topic","role":"symbol","kind":"symbol","title":"setButtonCustomization(_:for:)","navigatorTitle":[{"text":"setButtonCustomization:forType:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setButtonCustomization:forType:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setButtonCustomization:forType:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"setButtonCustomization:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPThreeDSButtonCustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSButtonCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSButtonCustomization"},{"text":" *) ","kind":"text"},{"text":"buttonCustomization","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSCustomizationButtonType","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSCustomizationButtonType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPThreeDSCustomizationButtonType"},{"text":") ","kind":"text"},{"text":"buttonType","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"buttonCustomization","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The buttom customization to use."}]}]},{"name":"buttonType","content":[{"inlineContent":[{"text":"The type of button to use the customization for.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"STPThreeDSUICustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title"},{"op":"replace","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments"},{"op":"replace","value":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle"},{"op":"replace","value":"STPThreeDSCustomizationButtonType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSCustomizationButtonType"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/fragments"},{"op":"replace","value":[{"text":"STPThreeDSCustomizationButtonType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSCustomizationButtonType\/navigatorTitle"},{"op":"replace","value":"STPThreeDSButtonCustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSButtonCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/fragments"},{"op":"replace","value":[{"text":"STPThreeDSButtonCustomization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSButtonCustomization\/navigatorTitle"},{"op":"replace","value":"setButtonCustomization:forType:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1setButtonCustomization(_:for:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setButtonCustomization:forType:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1setButtonCustomization(_:for:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}