{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldCustomization"},{"text":": ","kind":"text"},{"text":"STPThreeDSTextFieldCustomization","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization"}],"navigatorTitle":[{"text":"textFieldCustomization","kind":"identifier"}],"title":"textFieldCustomization","externalID":"c:@M@StripePayments@objc(cs)STPThreeDSUICustomization(py)textFieldCustomization","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization"]]},"abstract":[{"type":"text","text":"Provides custom settings for text fields."},{"type":"text","text":" "},{"type":"text","text":"The default is "},{"code":"STPThreeDSTextFieldCustomization.defaultSettings()","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textFieldCustomization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization","text":"STPThreeDSTextFieldCustomization","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/textfieldcustomization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpthreedsuicustomization\/textfieldcustomization"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/textFieldCustomization"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSTextFieldCustomization":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization","title":"STPThreeDSTextFieldCustomization","navigatorTitle":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"url":"\/documentation\/stripepayments\/stpthreedstextfieldcustomization","abstract":[{"text":"A customization object to use to configure the UI of a text field.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization/textFieldCustomization":{"url":"\/documentation\/stripepayments\/stpthreedsuicustomization\/textfieldcustomization","abstract":[{"text":"Provides custom settings for text fields.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The default is "},{"code":"STPThreeDSTextFieldCustomization.defaultSettings()","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization\/textFieldCustomization","type":"topic","navigatorTitle":[{"text":"textFieldCustomization","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"textFieldCustomization","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization","kind":"typeIdentifier","text":"STPThreeDSTextFieldCustomization"}],"role":"symbol","title":"textFieldCustomization"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPThreeDSUICustomization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPThreeDSUICustomization","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"STPThreeDSUICustomization","kind":"identifier"}],"title":"STPThreeDSUICustomization","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stpthreedsuicustomization","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSUICustomization","abstract":[{"type":"text","text":"The "},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"type":"text","text":" provides configuration for UI elements displayed during 3D Secure authentication."},{"type":"text","text":" "},{"type":"text","text":"Note: It’s important to configure this object appropriately before calling any "},{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" APIs."},{"text":" ","type":"text"},{"text":"The API makes a copy of the customization settings you provide; it ignores any subsequent changes you","type":"text"},{"type":"text","text":" "},{"type":"text","text":"make to your "},{"code":"STPThreeDSUICustomization","type":"codeVoice"},{"type":"text","text":" instance."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"textFieldCustomization","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"textFieldCustomization","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPThreeDSTextFieldCustomization","text":"STPThreeDSTextFieldCustomization","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPThreeDSTextFieldCustomization"},{"text":" * ","kind":"text"},{"text":"textFieldCustomization","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"STPThreeDSTextFieldCustomization","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/title"},{"value":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPThreeDSTextFieldCustomization"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSTextFieldCustomization\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1textFieldCustomization\/title","value":"textFieldCustomization"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization~1textFieldCustomization\/fragments","value":[{"text":"textFieldCustomization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/title","value":"STPThreeDSUICustomization"},{"value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPThreeDSUICustomization"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPThreeDSUICustomization\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}