{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/accessibilityHint(_:isEnabled:)-2b2z6"},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityHint","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation23LocalizedStringResourceV","text":"LocalizedStringResource","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier","kind":"typeIdentifier"},{"text":">","kind":"text"}],"externalID":"s:7SwiftUI4ViewPAAE17accessibilityHint_9isEnabledAA15ModifiedContentVyxAA31AccessibilityAttachmentModifierVG10Foundation23LocalizedStringResourceV_SbtF::SYNTHESIZED::s:16StripePaymentsUI15STPCardFormViewC13RepresentableV","extendedModule":"SwiftUICore","modules":[{"name":"StripePaymentsUI","relatedModules":["SwiftUICore"]}],"platforms":[{"name":"iOS","deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false},{"name":"macOS","deprecated":false,"introducedAt":"15.0","unavailable":false,"beta":false},{"name":"tvOS","deprecated":false,"introducedAt":"18.0","unavailable":false,"beta":false},{"name":"visionOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"name":"watchOS","deprecated":false,"introducedAt":"11.0","unavailable":false,"beta":false}],"title":"accessibilityHint(_:isEnabled:)","symbolKind":"method","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityHint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hint","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation23LocalizedStringResourceV","text":"LocalizedStringResource","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","text":"ModifiedContent","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/representable\/accessibilityhint(_:isenabled:)-2b2z6"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.accessibilityHint(_:isEnabled:)"},{"type":"text","text":"."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable/accessibilityHint(_:isEnabled:)-2b2z6":{"url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable\/accessibilityhint(_:isenabled:)-2b2z6","title":"accessibilityHint(_:isEnabled:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/accessibilityHint(_:isEnabled:)-2b2z6","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessibilityHint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"LocalizedStringResource","preciseIdentifier":"s:10Foundation23LocalizedStringResourceV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"ModifiedContent","preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"AccessibilityAttachmentModifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable":{"role":"symbol","navigatorTitle":[{"text":"Representable","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Representable","kind":"identifier"}],"abstract":[{"type":"text","text":"A SwiftUI representation of STPCardFormView"}],"title":"STPCardFormView.Representable","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"type":"topic","abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"text":" provides a multiline interface for users to input their","type":"text"},{"text":" ","type":"text"},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"text":" ","type":"text"},{"text":"the created ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"STPCardFormView"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"text":" ","type":"text"},{"text":"is displayed when invalid input is detected.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCardFormView","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview","title":"STPCardFormView","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"url":"\/documentation\/stripepaymentsui","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"text":"STPCardFormView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"text":"STPCardFormView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}