{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/accessibilityActivationPoint(_:)-7logv"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"accessibilityActivationPoint","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"activationPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","kind":"typeIdentifier","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/representable\/accessibilityactivationpoint(_:)-7logv"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"accessibilityActivationPoint(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"accessibilityActivationPoint"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier","text":"ModifiedContent"},{"text":"<","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"AccessibilityAttachmentModifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV"},{"text":">","kind":"text"}],"modules":[{"name":"StripePaymentsUI","relatedModules":["SwiftUICore"]}],"roleHeading":"Instance Method","extendedModule":"SwiftUICore","role":"symbol","symbolKind":"method","externalID":"s:7SwiftUI4ViewPAAE28accessibilityActivationPointyAA15ModifiedContentVyxAA31AccessibilityAttachmentModifierVGSo7CGPointVF::SYNTHESIZED::s:16StripePaymentsUI15STPCardFormViewC13RepresentableV","platforms":[{"introducedAt":"14.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"14.0"},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","beta":false,"name":"Mac Catalyst"},{"beta":false,"name":"macOS","deprecated":false,"introducedAt":"11.0","unavailable":false},{"introducedAt":"14.0","unavailable":false,"name":"tvOS","beta":false,"deprecated":false},{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"7.0","name":"watchOS"}]},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"View.accessibilityActivationPoint(_:)"},{"text":".","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/View-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardFormView","kind":"identifier"}],"role":"symbol","abstract":[{"code":"STPCardFormView","type":"codeVoice"},{"text":" provides a multiline interface for users to input their","type":"text"},{"type":"text","text":" "},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the created "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"text":" ","type":"text"},{"type":"text","text":"is displayed when invalid input is detected."}],"title":"STPCardFormView","navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","url":"\/documentation\/stripepaymentsui\/stpcardformview"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","role":"collection","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Representable","kind":"identifier"}],"abstract":[{"text":"A SwiftUI representation of STPCardFormView","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Representable"}],"kind":"symbol","role":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable","type":"topic","title":"STPCardFormView.Representable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable/accessibilityActivationPoint(_:)-7logv":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessibilityActivationPoint"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI15ModifiedContentV","kind":"typeIdentifier","text":"ModifiedContent"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI31AccessibilityAttachmentModifierV","text":"AccessibilityAttachmentModifier"},{"kind":"text","text":">"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/accessibilityActivationPoint(_:)-7logv","title":"accessibilityActivationPoint(_:)","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable\/accessibilityactivationpoint(_:)-7logv","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable/View-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"title":"View Implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/View-Implementations","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable\/view-implementations"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView","op":"replace"},{"value":[{"text":"STPCardFormView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFormView"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}