{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable"]]},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/representable\/fileexporterfilenamelabel(_:)-91ep5"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"nonisolated"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileExporterFilenameLabel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"label"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI4TextV","kind":"typeIdentifier","text":"Text"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"},{"kind":"text","text":"\n"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.fileExporterFilenameLabel(_:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/fileExporterFilenameLabel(_:)-91ep5"},"metadata":{"platforms":[{"name":"iOS","unavailable":false,"introducedAt":"17.0","deprecated":false,"beta":false},{"name":"iPadOS","unavailable":false,"introducedAt":"17.0","deprecated":false,"beta":false},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"17.0","deprecated":false,"beta":false},{"name":"macOS","unavailable":false,"introducedAt":"14.0","deprecated":false,"beta":false}],"modules":[{"name":"StripePaymentsUI","relatedModules":["SwiftUICore"]}],"title":"fileExporterFilenameLabel(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileExporterFilenameLabel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4TextV","text":"Text"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"}],"roleHeading":"Instance Method","externalID":"s:7SwiftUI4ViewPAAE25fileExporterFilenameLabelyQrAA4TextVSgF::SYNTHESIZED::s:16StripePaymentsUI15STPCardFormViewC13RepresentableV","role":"symbol","extendedModule":"SwiftUICore"},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable/fileExporterFilenameLabel(_:)-91ep5":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileExporterFilenameLabel"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7SwiftUI4TextV","kind":"typeIdentifier","text":"Text"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/fileExporterFilenameLabel(_:)-91ep5","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable\/fileexporterfilenamelabel(_:)-91ep5","type":"topic","title":"fileExporterFilenameLabel(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"kind":"symbol","type":"topic","title":"STPCardFormView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview","navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" provides a multiline interface for users to input their"},{"text":" ","type":"text"},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"type":"text","text":" "},{"text":"the created ","type":"text"},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"type":"text","text":" "},{"type":"text","text":"is displayed when invalid input is detected."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Representable"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable","title":"STPCardFormView.Representable","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Representable","kind":"identifier"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable","role":"symbol","abstract":[{"text":"A SwiftUI representation of STPCardFormView","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"kind":"identifier","text":"STPCardFormView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFormView"}]}]}]}