{"metadata":{"externalID":"s:16StripePaymentsUI15STPCardFormViewC13RepresentableV_19paymentMethodParams10isCompleteAeA0deF5StyleO_05SwiftC07BindingVy0aB0010STPPaymentiJ0CGALySbGtcfc","symbolKind":"init","title":"init(_:paymentMethodParams:isComplete:)","role":"symbol","modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle","text":"STPCardFormViewStyle","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paymentMethodParams"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":">, ","kind":"text"},{"text":"isComplete","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":">)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/init(_:paymentMethodParams:isComplete:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/representable\/init(_:paymentmethodparams:iscomplete:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Initialize a SwiftUI representation of an STPCardFormView."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPCardFormViewStyle","preciseIdentifier":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle"},{"kind":"text","text":" = .standard, "},{"kind":"externalParam","text":"paymentMethodParams"},{"kind":"text","text":": "},{"text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodParams","text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"isComplete"},{"text":": ","kind":"text"},{"text":"Binding","preciseIdentifier":"s:7SwiftUI7BindingV","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":">)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The visual style to apply to the STPCardFormView. @see STPCardFormViewStyle","type":"text"}],"type":"paragraph"}],"name":"style"},{"name":"paymentMethodParams","content":[{"type":"paragraph","inlineContent":[{"text":"A binding to the payment card text field’s contents.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The STPPaymentMethodParams will be "},{"type":"codeVoice","code":"nil"},{"text":" if the card form view’s contents are invalid or incomplete.","type":"text"}]}]}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"title":"STPCardFormView","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCardFormView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"type":"topic","abstract":[{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" provides a multiline interface for users to input their"},{"type":"text","text":" "},{"text":"credit card details as well as billing postal code and provides an interface to access","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the created "},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"code":"STPCardFormView","type":"codeVoice"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is displayed when invalid input is detected."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormViewStyle":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormViewStyle","navigatorTitle":[{"text":"STPCardFormViewStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPCardFormViewStyle","kind":"identifier"}],"title":"STPCardFormViewStyle","kind":"symbol","abstract":[{"text":"Options for configuring the display of an ","type":"text"},{"code":"STPCardFormView","type":"codeVoice"},{"type":"text","text":" instance."}],"url":"\/documentation\/stripepaymentsui\/stpcardformviewstyle","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentMethodParams":{"type":"topic","abstract":[{"type":"text","text":"An object representing parameters used to create a PaymentMethod object."}],"title":"STPPaymentMethodParams","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodParams"}],"url":"\/documentation\/stripepaymentsui\/stppaymentmethodparams","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentMethodParams","navigatorTitle":[{"text":"STPPaymentMethodParams","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"url":"\/documentation\/stripepaymentsui","role":"collection","type":"topic","title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Representable"}],"navigatorTitle":[{"kind":"identifier","text":"Representable"}],"abstract":[{"text":"A SwiftUI representation of STPCardFormView","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable","title":"STPCardFormView.Representable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable/init(_:paymentMethodParams:isComplete:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPCardFormViewStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@E@STPCardFormViewStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"paymentMethodParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"text":"<","kind":"text"},{"text":"STPPaymentMethodParams","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodParams"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"isComplete"},{"text":": ","kind":"text"},{"text":"Binding","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV"},{"kind":"text","text":"<"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":">)","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/init(_:paymentMethodParams:isComplete:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initialize a SwiftUI representation of an STPCardFormView."}],"title":"init(_:paymentMethodParams:isComplete:)","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable\/init(_:paymentmethodparams:iscomplete:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","op":"replace","value":[{"text":"STPCardFormView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFormView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/title","value":"STPCardFormViewStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/fragments","value":[{"kind":"identifier","text":"STPCardFormViewStyle"}]},{"value":[{"kind":"identifier","text":"STPCardFormViewStyle"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormViewStyle\/navigatorTitle"}]}]}