{"metadata":{"extendedModule":"SwiftUICore","modules":[{"relatedModules":["SwiftUICore"],"name":"StripePaymentsUI"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"padding"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"externalID":"s:7SwiftUI4ViewPAAE7paddingyQr14CoreFoundation7CGFloatVF::SYNTHESIZED::s:16StripePaymentsUI15STPCardFormViewC13RepresentableV","symbolKind":"method","platforms":[{"introducedAt":"13.0","name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"13.0","name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"13.0","name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"10.15","name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"13.0","name":"tvOS","beta":false,"deprecated":false,"unavailable":false},{"introducedAt":"6.0","name":"watchOS","beta":false,"deprecated":false,"unavailable":false}],"role":"symbol","roleHeading":"Instance Method","title":"padding(_:)"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/padding(_:)-77omd","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.padding(_:)"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/representable\/padding(_:)-77omd"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"padding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"length","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"},{"kind":"text","text":"\n"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable/padding(_:)-77omd":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"padding"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"kind":"text","text":" "},{"preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier","text":"View"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable\/padding(_:)-77omd","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/padding(_:)-77omd","abstract":[],"title":"padding(_:)","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","title":"StripePaymentsUI","kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Representable"}],"navigatorTitle":[{"kind":"identifier","text":"Representable"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable","abstract":[{"type":"text","text":"A SwiftUI representation of STPCardFormView"}],"title":"STPCardFormView.Representable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"url":"\/documentation\/stripepaymentsui\/stpcardformview","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFormView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","abstract":[{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" provides a multiline interface for users to input their"},{"type":"text","text":" "},{"type":"text","text":"credit card details as well as billing postal code and provides an interface to access"},{"type":"text","text":" "},{"type":"text","text":"the created "},{"type":"codeVoice","code":"STPPaymentMethodParams"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"codeVoice","code":"STPCardFormView"},{"type":"text","text":" includes both the input fields as well as an error label that"},{"type":"text","text":" "},{"type":"text","text":"is displayed when invalid input is detected."}],"navigatorTitle":[{"text":"STPCardFormView","kind":"identifier"}],"title":"STPCardFormView","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments","value":[{"kind":"identifier","text":"STPCardFormView"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"text":"STPCardFormView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}