{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"safeAreaInset(edge:alignment:spacing:content:)","modules":[{"relatedModules":["SwiftUICore"],"name":"StripePaymentsUI"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"safeAreaInset","kind":"identifier"},{"kind":"text","text":"<"},{"text":"V","kind":"genericParameter"},{"text":">(","kind":"text"},{"text":"edge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI12VerticalEdgeO","text":"VerticalEdge","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"alignment"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI19HorizontalAlignmentV","text":"HorizontalAlignment","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"spacing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> "},{"text":"V","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"}],"platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"15.0","beta":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"15.0"},{"introducedAt":"15.0","unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false},{"introducedAt":"12.0","beta":false,"deprecated":false,"name":"macOS","unavailable":false},{"name":"tvOS","deprecated":false,"introducedAt":"15.0","unavailable":false,"beta":false},{"beta":false,"name":"watchOS","deprecated":false,"introducedAt":"8.0","unavailable":false}],"externalID":"s:7SwiftUI4ViewPAAE13safeAreaInset4edge9alignment7spacing7contentQrAA12VerticalEdgeO_AA19HorizontalAlignmentV14CoreFoundation7CGFloatVSgqd__yXEtAaBRd__lF::SYNTHESIZED::s:16StripePaymentsUI15STPCardFormViewC13RepresentableV","symbolKind":"method","extendedModule":"SwiftUICore","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"View.safeAreaInset(edge:alignment:spacing:content:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"nonisolated","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"safeAreaInset"},{"text":"<","kind":"text"},{"text":"V","kind":"genericParameter"},{"text":">(","kind":"text"},{"kind":"externalParam","text":"edge"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI12VerticalEdgeO","kind":"typeIdentifier","text":"VerticalEdge"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"alignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI19HorizontalAlignmentV","text":"HorizontalAlignment","kind":"typeIdentifier"},{"text":" = .center, ","kind":"text"},{"text":"spacing","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"ViewBuilder","kind":"attribute","preciseIdentifier":"s:7SwiftUI11ViewBuilderV"},{"text":" ","kind":"text"},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> "},{"text":"V","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"where","kind":"keyword"},{"kind":"text","text":" "},{"text":"V","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":"\n"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/View-Implementations"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpcardformview\/representable\/safeareainset(edge:alignment:spacing:content:)-i6hc"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/safeAreaInset(edge:alignment:spacing:content:)-i6hc"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView":{"kind":"symbol","role":"symbol","abstract":[{"code":"STPCardFormView","type":"codeVoice"},{"text":" provides a multiline interface for users to input their","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"credit card details as well as billing postal code and provides an interface to access"},{"type":"text","text":" "},{"text":"the created ","type":"text"},{"code":"STPPaymentMethodParams","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"code":"STPCardFormView","type":"codeVoice"},{"text":" includes both the input fields as well as an error label that","type":"text"},{"type":"text","text":" "},{"text":"is displayed when invalid input is detected.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPCardFormView"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardFormView"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView","title":"STPCardFormView","url":"\/documentation\/stripepaymentsui\/stpcardformview"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable":{"type":"topic","title":"STPCardFormView.Representable","kind":"symbol","abstract":[{"text":"A SwiftUI representation of STPCardFormView","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Representable","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable","role":"symbol","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable","navigatorTitle":[{"kind":"identifier","text":"Representable"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable/safeAreaInset(edge:alignment:spacing:content:)-i6hc":{"type":"topic","role":"symbol","kind":"symbol","title":"safeAreaInset(edge:alignment:spacing:content:)","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/safeAreaInset(edge:alignment:spacing:content:)-i6hc","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"safeAreaInset","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"V"},{"kind":"text","text":">("},{"kind":"externalParam","text":"edge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"VerticalEdge","preciseIdentifier":"s:7SwiftUI12VerticalEdgeO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"alignment"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI19HorizontalAlignmentV","text":"HorizontalAlignment","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"spacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": () -> "},{"text":"V","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"some"},{"text":" ","kind":"text"},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"}],"url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable\/safeareainset(edge:alignment:spacing:content:)-i6hc"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPCardFormView/Representable/View-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPCardFormView\/Representable\/View-Implementations","type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/stripepaymentsui\/stpcardformview\/representable\/view-implementations","abstract":[],"title":"View Implementations"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/title","value":"STPCardFormView"},{"op":"replace","value":[{"kind":"identifier","text":"STPCardFormView"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPCardFormView\/navigatorTitle","value":[{"text":"STPCardFormView","kind":"identifier"}]}]}]}