{"kind":"symbol","primaryContentSections":[{"content":[{"type":"heading","text":"Table of contents","level":2,"anchor":"Table-of-contents"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"#Stripe-Apple-Pay-iOS-SDK","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"#Table-of-contents","type":"reference"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#Requirements","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"#Getting-started","isActive":true}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#Integration","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"#Example","isActive":true,"type":"reference"}]}]}],"type":"unorderedList"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"#Manual-linking","isActive":true}],"type":"paragraph"}]}]}]}]},{"text":"Requirements","anchor":"Requirements","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The Stripe Apple Pay SDK is compatible with apps targeting iOS 13.0 or above."}]},{"type":"heading","level":2,"text":"Getting started","anchor":"Getting-started"},{"text":"Integration","anchor":"Integration","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"text":"Get started with our ","type":"text"},{"identifier":"https:\/\/stripe.com\/docs\/apple-pay?platform=ios","isActive":true,"type":"reference"},{"text":" and ","type":"text"},{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.16.0\/StripeApplePay\/..\/Example\/AppClipExample","isActive":true,"type":"reference"},{"text":", or ","type":"text"},{"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-applepay\/index.html","isActive":true,"type":"reference"},{"text":" for fine-grained documentation of all the classes and methods in the SDK.","type":"text"}]},{"text":"Example","anchor":"Example","type":"heading","level":3},{"type":"paragraph","inlineContent":[{"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.16.0\/StripeApplePay\/..\/Example\/AppClipExample","type":"reference","isActive":true,"overridingTitle":"AppClipExample","overridingTitleInlineContent":[{"text":"AppClipExample","type":"text"}]},{"type":"text","text":" – This example demonstrates how to offer Apple Pay in an App Clip."}]},{"text":"Manual linking","anchor":"Manual-linking","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"If you link this library manually, use a version from our ","type":"text"},{"type":"reference","identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases","isActive":true},{"type":"text","text":" page and make sure to embed "},{"type":"text","text":"all"},{"type":"text","text":" of the following frameworks:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"StripeCore.xcframework","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"StripeApplePay.xcframework","type":"codeVoice"}],"type":"paragraph"}]}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay"},"abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripeapplepay"]},{"paths":["\/documentation\/stripeapplepay"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"StripeApplePay","role":"collection","roleHeading":"Framework","title":"StripeApplePay","symbolKind":"module","modules":[{"name":"StripeApplePay"}]},"topicSections":[{"title":"Classes","generated":true,"anchor":"Classes","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]},{"title":"Protocols","generated":true,"anchor":"Protocols","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/ApplePayContextDelegate"]},{"title":"Type Aliases","generated":true,"anchor":"Type-Aliases","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPIntentClientSecretCompletionBlock","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock"]},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/StripeCore"],"anchor":"Extended-Modules","title":"Extended Modules"}],"sections":[],"hierarchy":{"paths":[[]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"#Stripe-Apple-Pay-iOS-SDK":{"titleInlineContent":[{"type":"text","text":"Stripe Apple Pay iOS SDK"}],"identifier":"#Stripe-Apple-Pay-iOS-SDK","url":"#Stripe-Apple-Pay-iOS-SDK","title":"Stripe Apple Pay iOS SDK","type":"link"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/StripeApplePayVersionString":{"type":"topic","role":"symbol","url":"\/documentation\/stripeapplepay\/stripeapplepayversionstring","fragments":[{"text":"StripeApplePayVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/StripeApplePayVersionString","abstract":[{"type":"text","text":"Project version string for StripeApplePay."}],"title":"StripeApplePayVersionString","kind":"symbol"},"https://github.com/stripe/stripe-ios/tree/25.16.0/StripeApplePay/../Example/AppClipExample":{"titleInlineContent":[{"type":"text","text":"example project"}],"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.16.0\/StripeApplePay\/..\/Example\/AppClipExample","url":"https:\/\/github.com\/stripe\/stripe-ios\/tree\/25.16.0\/StripeApplePay\/..\/Example\/AppClipExample","title":"example project","type":"link"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/StripeApplePayVersionNumber":{"kind":"symbol","abstract":[{"type":"text","text":"Project version number for StripeApplePay."}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/StripeApplePayVersionNumber","type":"topic","title":"StripeApplePayVersionNumber","url":"\/documentation\/stripeapplepay\/stripeapplepayversionnumber","role":"symbol","fragments":[{"text":"StripeApplePayVersionNumber","kind":"identifier"}]},"https://stripe.com/docs/apple-pay?platform=ios":{"titleInlineContent":[{"type":"text","text":"📚 Apple Pay integration guide"}],"identifier":"https:\/\/stripe.com\/docs\/apple-pay?platform=ios","url":"https:\/\/stripe.com\/docs\/apple-pay?platform=ios","title":"📚 Apple Pay integration guide","type":"link"},"https://stripe.dev/stripe-ios/stripe-applepay/index.html":{"titleInlineContent":[{"type":"text","text":"📘 browse the SDK reference"}],"identifier":"https:\/\/stripe.dev\/stripe-ios\/stripe-applepay\/index.html","url":"https:\/\/stripe.dev\/stripe-ios\/stripe-applepay\/index.html","title":"📘 browse the SDK reference","type":"link"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPIntentClientSecretCompletionBlock":{"kind":"symbol","abstract":[{"type":"text","text":"A block to be run with the client secret of a PaymentIntent or SetupIntent."}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPIntentClientSecretCompletionBlock","navigatorTitle":[{"text":"STPIntentClientSecretCompletionBlock","kind":"identifier"}],"type":"topic","title":"STPIntentClientSecretCompletionBlock","url":"\/documentation\/stripeapplepay\/stpintentclientsecretcompletionblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPIntentClientSecretCompletionBlock","kind":"identifier"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPVoidBlock":{"kind":"symbol","abstract":[{"text":"An empty block, called with no arguments, returning nothing.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock","navigatorTitle":[{"text":"STPVoidBlock","kind":"identifier"}],"type":"topic","title":"STPVoidBlock","url":"\/documentation\/stripeapplepay\/stpvoidblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPVoidBlock","kind":"identifier"}]},"#Manual-linking":{"url":"#Manual-linking","type":"link","title":"Manual linking","titleInlineContent":[{"text":"Manual linking","type":"text"}],"identifier":"#Manual-linking"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"title":"StripeApplePay","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","type":"topic","url":"\/documentation\/stripeapplepay","role":"collection","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}],"kind":"symbol"},"#Requirements":{"url":"#Requirements","type":"link","title":"Requirements","titleInlineContent":[{"text":"Requirements","type":"text"}],"identifier":"#Requirements"},"https://github.com/stripe/stripe-ios/releases":{"url":"https:\/\/github.com\/stripe\/stripe-ios\/releases","type":"link","title":"releases","titleInlineContent":[{"text":"releases","type":"text"}],"identifier":"https:\/\/github.com\/stripe\/stripe-ios\/releases"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/ApplePayContextDelegate":{"navigatorTitle":[{"text":"ApplePayContextDelegate","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/stripeapplepay\/applepaycontextdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApplePayContextDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/ApplePayContextDelegate","abstract":[{"type":"text","text":"Implement the required methods of this delegate to supply a PaymentIntent to ApplePayContext and be notified of the completion of the Apple Pay payment."},{"type":"text","text":" "},{"type":"text","text":"You may also implement the optional delegate methods to handle shipping methods and shipping address changes e.g. to verify you can ship to the address, or update the payment amount."}],"title":"ApplePayContextDelegate","kind":"symbol"},"#Example":{"url":"#Example","type":"link","title":"Example","titleInlineContent":[{"type":"text","text":"Example"}],"identifier":"#Example"},"#Getting-started":{"url":"#Getting-started","type":"link","title":"Getting started","titleInlineContent":[{"type":"text","text":"Getting started"}],"identifier":"#Getting-started"},"#Integration":{"url":"#Integration","type":"link","title":"Integration","titleInlineContent":[{"text":"Integration","type":"text"}],"identifier":"#Integration"},"#Table-of-contents":{"url":"#Table-of-contents","type":"link","title":"Table of contents","titleInlineContent":[{"text":"Table of contents","type":"text"}],"identifier":"#Table-of-contents"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","role":"symbol","type":"topic","navigatorTitle":[{"text":"STPApplePayContext","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPApplePayContext","kind":"identifier"}],"abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"type":"text","text":" "},{"type":"text","text":"Usage looks like this:"}],"title":"STPApplePayContext"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/StripeCore":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/StripeCore","type":"topic","title":"StripeCore","url":"\/documentation\/stripeapplepay\/stripecore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"anchor":"Classes","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"],"generated":true,"title":"Classes"},{"anchor":"Variables","identifiers":["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/StripeApplePayVersionNumber","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/StripeApplePayVersionString"],"generated":true,"title":"Variables"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"STPApplePayContext","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPApplePayContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"STPApplePayContext"}],"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}