{"abstract":[{"text":"Called when editing begins in the text field as a whole.","type":"text"},{"text":" ","type":"text"},{"text":"After receiving this callback, you will always also receive a callback for which","type":"text"},{"type":"text","text":" "},{"text":"specific subfield of the view began editing.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","modules":[{"name":"StripePaymentsUI"}],"title":"paymentCardTextFieldDidBeginEditing(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"paymentCardTextFieldDidBeginEditing","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":")","kind":"text"}],"externalID":"c:@M@StripePaymentsUI@objc(pl)STPPaymentCardTextFieldDelegate(im)paymentCardTextFieldDidBeginEditing:","symbolKind":"method","navigatorTitle":[{"text":"paymentCardTextFieldDidBeginEditing:","kind":"identifier"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbeginediting(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbeginediting(_:)"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditing(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditing"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"textField","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","kind":"symbol","title":"STPPaymentCardTextFieldDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"abstract":[{"type":"text","text":"This protocol allows a delegate to be notified when a payment text field’s"},{"type":"text","text":" "},{"type":"text","text":"contents change, which can in turn be used to take further actions depending"},{"type":"text","text":" "},{"text":"on the validity of its contents.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"text":"designed to fit on a single line, and from a design perspective can be used","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextField"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"title":"STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidBeginEditing(_:)":{"abstract":[{"type":"text","text":"Called when editing begins in the text field as a whole."},{"type":"text","text":" "},{"type":"text","text":"After receiving this callback, you will always also receive a callback for which"},{"type":"text","text":" "},{"type":"text","text":"specific subfield of the view began editing."}],"title":"paymentCardTextFieldDidBeginEditing(_:)","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbeginediting(_:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditing(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"paymentCardTextFieldDidBeginEditing:","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"url":"\/documentation\/stripepaymentsui","role":"collection","title":"StripePaymentsUI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"paymentCardTextFieldDidBeginEditing:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditing:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditing:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":" *) ","kind":"text"},{"text":"textField","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"STPPaymentCardTextFieldDelegate","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title","op":"replace"},{"value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"value":"paymentCardTextFieldDidBeginEditing:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditing(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditing(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditing:"}],"op":"replace"}]}]}