{"sections":[],"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(pl)STPPaymentCardTextFieldDelegate(im)paymentCardTextFieldDidEndEditing:","role":"symbol","symbolKind":"method","title":"paymentCardTextFieldDidEndEditing(_:)","modules":[{"name":"StripePaymentsUI"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditing"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paymentCardTextFieldDidEndEditing:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Called when editing ends in the text field as a whole."},{"text":" ","type":"text"},{"text":"This callback is always preceded by an callback for which","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"specific subfield of the view ended its editing."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"textField","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditing(_:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendediting(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendediting(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"]]},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidEndEditing(_:)":{"role":"symbol","navigatorTitle":[{"text":"paymentCardTextFieldDidEndEditing:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"paymentCardTextFieldDidEndEditing(_:)","required":true,"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendediting(_:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditing(_:)","abstract":[{"type":"text","text":"Called when editing ends in the text field as a whole."},{"text":" ","type":"text"},{"type":"text","text":"This callback is always preceded by an callback for which"},{"type":"text","text":" "},{"type":"text","text":"specific subfield of the view ended its editing."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"type":"text","text":" "},{"text":"designed to fit on a single line, and from a design perspective can be used","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextField"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"title":"STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","kind":"symbol","title":"STPPaymentCardTextFieldDelegate","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"abstract":[{"type":"text","text":"This protocol allows a delegate to be notified when a payment text field’s"},{"type":"text","text":" "},{"type":"text","text":"contents change, which can in turn be used to take further actions depending"},{"type":"text","text":" "},{"text":"on the validity of its contents.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","type":"topic","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"url":"\/documentation\/stripepaymentsui","role":"collection","title":"StripePaymentsUI"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"paymentCardTextFieldDidEndEditing:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"paymentCardTextFieldDidEndEditing:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"paymentCardTextFieldDidEndEditing:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textField"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"paymentCardTextFieldDidEndEditing:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditing(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditing:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditing(_:)\/fragments"},{"value":"STPPaymentCardTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title","op":"replace","value":"STPPaymentCardTextFieldDelegate"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments","value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}