{"sections":[],"metadata":{"modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingPostalCode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"paymentCardTextFieldDidBeginEditingPostalCode:","kind":"identifier"}],"externalID":"c:@M@StripePaymentsUI@objc(pl)STPPaymentCardTextFieldDelegate(im)paymentCardTextFieldDidBeginEditingPostalCode:","title":"paymentCardTextFieldDidBeginEditingPostalCode(_:)","symbolKind":"method"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingPostalCode(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingPostalCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"textField","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"typeIdentifier","text":"STPPaymentCardTextField"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Called when editing begins in the payment card field’s ZIP\/postal code field."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingpostalcode(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingpostalcode(_:)"]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"abstract":[{"text":"This protocol allows a delegate to be notified when a payment text field’s","type":"text"},{"type":"text","text":" "},{"text":"contents change, which can in turn be used to take further actions depending","type":"text"},{"type":"text","text":" "},{"text":"on the validity of its contents.","type":"text"}],"navigatorTitle":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","kind":"symbol","title":"STPPaymentCardTextFieldDelegate","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidBeginEditingPostalCode(_:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingPostalCode:"}],"title":"paymentCardTextFieldDidBeginEditingPostalCode(_:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingPostalCode(_:)","abstract":[{"type":"text","text":"Called when editing begins in the payment card field’s ZIP\/postal code field."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingPostalCode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingpostalcode(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","title":"StripePaymentsUI","kind":"symbol","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"kind":"symbol","title":"STPPaymentCardTextField","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentCardTextField"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"text":" ","type":"text"},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"text":" ","type":"text"},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"type":"text","text":"anywhere a UITextField would be appropriate."}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"paymentCardTextFieldDidBeginEditingPostalCode:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"paymentCardTextFieldDidBeginEditingPostalCode:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingPostalCode:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"typeIdentifier","text":"STPPaymentCardTextField"},{"text":" *) ","kind":"text"},{"text":"textField","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title","value":"STPPaymentCardTextFieldDelegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments"},{"value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingPostalCode(_:)\/title","value":"paymentCardTextFieldDidBeginEditingPostalCode:"},{"value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingPostalCode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingPostalCode(_:)\/fragments"},{"value":"STPPaymentCardTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]}]}]}