{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"]]},"abstract":[{"type":"text","text":"Called when editing ends in the payment card field’s ZIP\/postal code field."}],"sections":[],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendeditingpostalcode(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendeditingpostalcode(_:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingPostalCode(_:)","interfaceLanguage":"swift"},"metadata":{"title":"paymentCardTextFieldDidEndEditingPostalCode(_:)","modules":[{"name":"StripePaymentsUI"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidEndEditingPostalCode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@StripePaymentsUI@objc(pl)STPPaymentCardTextFieldDelegate(im)paymentCardTextFieldDidEndEditingPostalCode:","navigatorTitle":[{"text":"paymentCardTextFieldDidEndEditingPostalCode:","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldDidEndEditingPostalCode"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"textField","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"text":")","kind":"text"}]}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","role":"collection","type":"topic","kind":"symbol","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"type":"topic","role":"symbol","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","abstract":[{"type":"text","text":"This protocol allows a delegate to be notified when a payment text field’s"},{"type":"text","text":" "},{"text":"contents change, which can in turn be used to take further actions depending","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"on the validity of its contents."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"title":"STPPaymentCardTextFieldDelegate","kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","title":"STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","role":"symbol","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"identifier"}],"abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"type":"text","text":" "},{"text":"multiple UITextFields under the hood to collect this information. It’s","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"type":"text","text":" "},{"type":"text","text":"anywhere a UITextField would be appropriate."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidEndEditingPostalCode(_:)":{"kind":"symbol","type":"topic","title":"paymentCardTextFieldDidEndEditingPostalCode(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidEndEditingPostalCode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidendeditingpostalcode(_:)","role":"symbol","navigatorTitle":[{"text":"paymentCardTextFieldDidEndEditingPostalCode:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when editing ends in the payment card field’s ZIP\/postal code field."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidEndEditingPostalCode(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paymentCardTextFieldDidEndEditingPostalCode:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidEndEditingPostalCode:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"paymentCardTextFieldDidEndEditingPostalCode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"textField","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"STPPaymentCardTextFieldDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments","op":"replace","value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}]},{"value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle","op":"replace"},{"value":"STPPaymentCardTextField","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentCardTextField","kind":"identifier"}]},{"op":"replace","value":"paymentCardTextFieldDidEndEditingPostalCode:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingPostalCode(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidEndEditingPostalCode(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidEndEditingPostalCode:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
