{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"paymentCardTextFieldWillEndEditingForReturn:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method","externalID":"c:@M@StripePaymentsUI@objc(pl)STPPaymentCardTextFieldDelegate(im)paymentCardTextFieldWillEndEditingForReturn:","title":"paymentCardTextFieldWillEndEditing(forReturn:)","modules":[{"name":"StripePaymentsUI"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditing"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forReturn"},{"kind":"text","text":": "},{"text":"STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":")"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldWillEndEditing(forReturn:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"]]},"kind":"symbol","abstract":[{"text":"Notification that the user pressed the ","type":"text"},{"type":"codeVoice","code":"return"},{"text":" key after completely filling","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"out the STPPaymentCardTextField with data that passes validation."},{"text":" ","type":"text"},{"type":"text","text":"The Stripe SDK is going to "},{"type":"codeVoice","code":"resignFirstResponder"},{"type":"text","text":" on the "},{"code":"STPPaymentCardTextField","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"to dismiss the keyboard after this delegate method returns, however if your app wants"},{"type":"text","text":" "},{"type":"text","text":"to do something more (ex: move first responder to another field), this is a good"},{"type":"text","text":" "},{"type":"text","text":"opportunity to do that."},{"type":"text","text":" "},{"text":"This is delivered ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"before","type":"text"}]},{"type":"text","text":" the corresponding "},{"type":"codeVoice","code":"paymentCardTextFieldDidEndEditing:"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfieldwillendediting(forreturn:)"]},{"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfieldwillendediting(forreturn:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditing"},{"kind":"text","text":"("},{"text":"forReturn","kind":"externalParam"},{"kind":"text","text":" "},{"text":"textField","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPPaymentCardTextField","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"textField","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The STPPaymentCardTextField that was being edited when the user pressed return"}]}]}],"kind":"parameters"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"url":"\/documentation\/stripepaymentsui","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","abstract":[{"text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe.","type":"text"}],"kind":"symbol","type":"topic","title":"StripePaymentsUI","role":"collection"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldWillEndEditing(forReturn:)":{"title":"paymentCardTextFieldWillEndEditing(forReturn:)","abstract":[{"type":"text","text":"Notification that the user pressed the "},{"type":"codeVoice","code":"return"},{"type":"text","text":" key after completely filling"},{"type":"text","text":" "},{"text":"out the STPPaymentCardTextField with data that passes validation.","type":"text"},{"text":" ","type":"text"},{"text":"The Stripe SDK is going to ","type":"text"},{"code":"resignFirstResponder","type":"codeVoice"},{"text":" on the ","type":"text"},{"type":"codeVoice","code":"STPPaymentCardTextField"},{"type":"text","text":" "},{"text":"to dismiss the keyboard after this delegate method returns, however if your app wants","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"to do something more (ex: move first responder to another field), this is a good"},{"type":"text","text":" "},{"type":"text","text":"opportunity to do that."},{"type":"text","text":" "},{"type":"text","text":"This is delivered "},{"inlineContent":[{"text":"before","type":"text"}],"type":"emphasis"},{"text":" the corresponding ","type":"text"},{"type":"codeVoice","code":"paymentCardTextFieldDidEndEditing:"}],"kind":"symbol","role":"symbol","required":true,"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfieldwillendediting(forreturn:)","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldWillEndEditing(forReturn:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditing"},{"kind":"text","text":"("},{"text":"forReturn","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"paymentCardTextFieldWillEndEditingForReturn:"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"abstract":[{"text":"This protocol allows a delegate to be notified when a payment text field’s","type":"text"},{"type":"text","text":" "},{"text":"contents change, which can in turn be used to take further actions depending","type":"text"},{"type":"text","text":" "},{"text":"on the validity of its contents.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"title":"STPPaymentCardTextFieldDelegate","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"title":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","type":"topic","role":"symbol","abstract":[{"text":"STPPaymentCardTextField is a text field with similar properties to UITextField,","type":"text"},{"text":" ","type":"text"},{"text":"but specialized for credit\/debit card information. It manages","type":"text"},{"type":"text","text":" "},{"type":"text","text":"multiple UITextFields under the hood to collect this information. It’s"},{"text":" ","type":"text"},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"text":"anywhere a UITextField would be appropriate.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentCardTextField","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"paymentCardTextFieldWillEndEditingForReturn:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditingForReturn:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"paymentCardTextFieldWillEndEditingForReturn:","kind":"identifier"},{"kind":"text","text":"("},{"text":"STPPaymentCardTextField","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The STPPaymentCardTextField that was being edited when the user pressed return","type":"text"}],"type":"paragraph"}],"name":"textField"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"paymentCardTextFieldWillEndEditingForReturn:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldWillEndEditing(forReturn:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldWillEndEditingForReturn:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldWillEndEditing(forReturn:)\/fragments"},{"value":"STPPaymentCardTextFieldDelegate","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments","value":[{"text":"STPPaymentCardTextFieldDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}]}]}]}