{"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(pl)STPPaymentCardTextFieldDelegate(im)paymentCardTextFieldDidBeginEditingNumber:","modules":[{"name":"StripePaymentsUI"}],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingNumber:"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"paymentCardTextFieldDidBeginEditingNumber(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingNumber","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingNumber(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingNumber"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"kind":"text","text":")"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Called when editing begins in the payment card field’s number field."}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingnumber(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingnumber(_:)"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"title":"StripePaymentsUI","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate/paymentCardTextFieldDidBeginEditingNumber(_:)":{"kind":"symbol","abstract":[{"text":"Called when editing begins in the payment card field’s number field.","type":"text"}],"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingNumber:"}],"type":"topic","title":"paymentCardTextFieldDidBeginEditingNumber(_:)","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate\/paymentcardtextfielddidbegineditingnumber(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"paymentCardTextFieldDidBeginEditingNumber"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField","text":"STPPaymentCardTextField"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate\/paymentCardTextFieldDidBeginEditingNumber(_:)"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextField":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","navigatorTitle":[{"text":"STPPaymentCardTextField","kind":"identifier"}],"abstract":[{"type":"text","text":"STPPaymentCardTextField is a text field with similar properties to UITextField,"},{"type":"text","text":" "},{"type":"text","text":"but specialized for credit\/debit card information. It manages"},{"text":" ","type":"text"},{"text":"multiple UITextFields under the hood to collect this information. It’s","type":"text"},{"type":"text","text":" "},{"type":"text","text":"designed to fit on a single line, and from a design perspective can be used"},{"text":" ","type":"text"},{"text":"anywhere a UITextField would be appropriate.","type":"text"}],"title":"STPPaymentCardTextField","type":"topic","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfield","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentCardTextField","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPPaymentCardTextFieldDelegate":{"abstract":[{"type":"text","text":"This protocol allows a delegate to be notified when a payment text field’s"},{"type":"text","text":" "},{"type":"text","text":"contents change, which can in turn be used to take further actions depending"},{"type":"text","text":" "},{"type":"text","text":"on the validity of its contents."}],"kind":"symbol","title":"STPPaymentCardTextFieldDelegate","url":"\/documentation\/stripepaymentsui\/stppaymentcardtextfielddelegate","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextFieldDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"paymentCardTextFieldDidBeginEditingNumber:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingNumber:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPPaymentCardTextField","text":"STPPaymentCardTextField","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePaymentsUI@objc(cs)STPPaymentCardTextField"},{"text":" *) ","kind":"text"},{"text":"textField","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingNumber(_:)\/title","value":"paymentCardTextFieldDidBeginEditingNumber:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate~1paymentCardTextFieldDidBeginEditingNumber(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"paymentCardTextFieldDidBeginEditingNumber:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/title","value":"STPPaymentCardTextField","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/fragments","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentCardTextField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/title","value":"STPPaymentCardTextFieldDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPPaymentCardTextFieldDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentCardTextFieldDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}