{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTheme:"},{"text":"(","kind":"text"},{"text":"STPTheme","preciseIdentifier":"c:@M@Stripe@objc(cs)STPTheme","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"theme","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/stripe\/stpcoretableviewcontroller\/initwiththeme:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"Stripe"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithTheme:","kind":"identifier"}],"role":"symbol","title":"initWithTheme:","externalID":"c:@M@Stripe@objc(cs)STPCoreTableViewController(im)initWithTheme:","navigatorTitle":[{"text":"initWithTheme:","kind":"identifier"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/initWithTheme:","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPTheme":{"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPTheme","type":"topic","abstract":[{"type":"text","text":"STPTheme objects can be used to visually style Stripe-provided UI. See https:\/\/stripe.com\/docs\/mobile\/ios\/basic#theming for more information."}],"title":"STPTheme","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPTheme","kind":"identifier"}],"url":"\/documentation\/stripe\/stptheme","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPTheme"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController":{"kind":"symbol","abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It inherits from STPCoreScrollViewController and changes the type of the"},{"type":"text","text":" "},{"text":"created scroll view to UITableView, as well as other shared table view logic.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","role":"symbol","title":"STPCoreTableViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreTableViewController"}]},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/initWithTheme:":{"url":"\/documentation\/stripe\/stpcoretableviewcontroller\/initwiththeme:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithTheme:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithTheme:","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/initWithTheme:","abstract":[],"kind":"symbol","title":"initWithTheme:","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/title","op":"replace","value":"STPTheme"},{"op":"replace","value":[{"text":"STPTheme","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPTheme\/fragments"},{"value":"STPCoreTableViewController","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCoreTableViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
