{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":": "},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"title":"tableView","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":"?"}],"modules":[{"name":"Stripe"}],"externalID":"c:@M@Stripe@objc(cs)STPCoreTableViewController(py)tableView","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"tableView"}],"roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/stripe\/stpcoretableviewcontroller\/tableview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripe\/stpcoretableviewcontroller\/tableview"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"]]},"abstract":[{"text":"This points to the same object as ","type":"text"},{"code":"STPCoreScrollViewController","type":"codeVoice"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"scrollView"},{"type":"text","text":" "},{"type":"text","text":"property but with the type cast to "},{"type":"codeVoice","code":"UITableView"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView"},"references":{"doc://com.stripe.stripe-ios/documentation/Stripe":{"kind":"symbol","abstract":[],"title":"Stripe","url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","type":"topic"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/tableView":{"role":"symbol","title":"tableView","type":"topic","url":"\/documentation\/stripe\/stpcoretableviewcontroller\/tableview","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"tableView"}],"abstract":[{"type":"text","text":"This points to the same object as "},{"type":"codeVoice","code":"STPCoreScrollViewController"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"scrollView"},{"type":"text","text":" "},{"type":"text","text":"property but with the type cast to "},{"code":"UITableView","type":"codeVoice"}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController":{"role":"symbol","title":"STPCoreTableViewController","type":"topic","kind":"symbol","url":"\/documentation\/stripe\/stpcoretableviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCoreTableViewController","kind":"identifier"}],"navigatorTitle":[{"text":"STPCoreTableViewController","kind":"identifier"}],"abstract":[{"text":"This is the base class for all Stripe scroll view controllers. It is intended","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"text":"It inherits from STPCoreScrollViewController and changes the type of the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"created scroll view to UITableView, as well as other shared table view logic."}],"identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"tableView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"tableView"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" * ","kind":"text"},{"text":"tableView","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"tableView","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1tableView\/title"},{"value":[{"text":"tableView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1tableView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/title","value":"STPCoreTableViewController"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/fragments","value":[{"kind":"identifier","text":"STPCoreTableViewController"}],"op":"replace"}]}]}
