{"identifier":{"url":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView(_:heightForHeaderInSection:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"heightForHeaderInSection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"externalID":"c:@M@Stripe@objc(cs)STPCoreTableViewController(im)tableView:heightForHeaderInSection:","modules":[{"name":"Stripe"}],"role":"symbol","title":"tableView(_:heightForHeaderInSection:)","navigatorTitle":[{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}],"roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"heightForHeaderInSection"},{"text":" ","kind":"text"},{"text":"section","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":":nodoc:"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripe\/stpcoretableviewcontroller\/tableview(_:heightforheaderinsection:)"]},{"paths":["\/documentation\/stripe\/stpcoretableviewcontroller\/tableview(_:heightforheaderinsection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController/tableView(_:heightForHeaderInSection:)":{"kind":"symbol","abstract":[{"text":":nodoc:","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"heightForHeaderInSection"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller\/tableview(_:heightforheaderinsection:)","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController\/tableView(_:heightForHeaderInSection:)","role":"symbol","title":"tableView(_:heightForHeaderInSection:)","type":"topic","navigatorTitle":[{"text":"tableView:heightForHeaderInSection:","kind":"identifier"}]},"doc://com.stripe.stripe-ios/documentation/Stripe":{"url":"\/documentation\/stripe","role":"collection","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe","kind":"symbol","type":"topic","abstract":[],"title":"Stripe"},"doc://com.stripe.stripe-ios/documentation/Stripe/STPCoreTableViewController":{"kind":"symbol","abstract":[{"type":"text","text":"This is the base class for all Stripe scroll view controllers. It is intended"},{"type":"text","text":" "},{"type":"text","text":"for use only by Stripe classes, you should not subclass it yourself in your app."},{"type":"text","text":" "},{"type":"text","text":"It inherits from STPCoreScrollViewController and changes the type of the"},{"type":"text","text":" "},{"text":"created scroll view to UITableView, as well as other shared table view logic.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCoreTableViewController"}],"url":"\/documentation\/stripe\/stpcoretableviewcontroller","identifier":"doc:\/\/com.stripe.stripe-ios\/documentation\/Stripe\/STPCoreTableViewController","role":"symbol","title":"STPCoreTableViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPCoreTableViewController"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"tableView:heightForHeaderInSection:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:heightForHeaderInSection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"text":" ","kind":"text"},{"kind":"identifier","text":"heightForHeaderInSection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"section"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1tableView(_:heightForHeaderInSection:)\/title","value":"tableView:heightForHeaderInSection:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController~1tableView(_:heightForHeaderInSection:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"tableView:heightForHeaderInSection:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPCoreTableViewController","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/title"},{"value":[{"kind":"identifier","text":"STPCoreTableViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-ios~1documentation~1Stripe~1STPCoreTableViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
