//
// VerificationPageDataRequirements.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageDataRequirements: StripeDecodable, Equatable {

    typealias Missing = VerificationPageRequirements.Missing

    let errors: [VerificationPageDataRequirementError]
    let missing: [Missing]

    var _allResponseFieldsStorage: NonEncodableParameters?
}
