//
// VerificationPageDataRequirements.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore

extension StripeAPI { 

    struct VerificationPageDataRequirements: Decodable, Equatable {
        let errors: [VerificationPageDataRequirementError]
    }

}
