//
// VerificationPageDataRequirements.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageDataRequirements: StripeDecodable, Equatable {

    let errors: [VerificationPageDataRequirementError]

    var _allResponseFieldsStorage: NonEncodableParameters?
}
