//
// VerificationPageDataRequirementError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageDataRequirementError: StripeDecodable, Equatable {
    let backButtonText: String?
    let body: String
    let continueButtonText: String?
    let requirement: VerificationPageFieldType
    let title: String
    var _allResponseFieldsStorage: NonEncodableParameters?
}
