//
// VerificationPageDataRequirementError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
@_spi(STP) import StripeCore



struct VerificationPageDataRequirementError: StripeDecodable, Equatable {

    let body: String
    let buttonText: String?
    let requirement: VerificationPageFieldType
    let title: String?

    var _allResponseFieldsStorage: NonEncodableParameters?
}
