{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","kind":"typeIdentifier","text":"STPAddress"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress\/init(address:)","interfaceLanguage":"swift"},"metadata":{"title":"init(address:)","roleHeading":"Initializer","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress(im)initWithAddress:","navigatorTitle":[{"kind":"identifier","text":"initWithAddress:"}],"role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"address","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress"]]},"abstract":[{"text":"Convenience initializer for creating a STPPaymentMethodAddress from an STPAddress.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodaddress\/init(address:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodaddress\/init(address:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","title":"STPAddress","abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"role":"symbol","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPAddress","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpaddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAddress":{"title":"STPPaymentMethodAddress","type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodaddress","kind":"symbol","abstract":[{"type":"text","text":"The billing address, a property on "},{"type":"codeVoice","code":"STPPaymentMethodBillingDetails"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAddress","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodAddress","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAddress/init(address:)":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress\/init(address:)","title":"init(address:)","url":"\/documentation\/stripepayments\/stppaymentmethodaddress\/init(address:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"},{"kind":"text","text":")"}],"abstract":[{"text":"Convenience initializer for creating a STPPaymentMethodAddress from an STPAddress.","type":"text"}],"navigatorTitle":[{"text":"initWithAddress:","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithAddress:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAddress:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithAddress:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"address"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"STPAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","value":[{"kind":"identifier","text":"STPAddress"}],"op":"replace"},{"value":[{"text":"STPAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","op":"replace"},{"value":"STPPaymentMethodAddress","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/title","op":"replace"},{"op":"replace","value":[{"text":"STPPaymentMethodAddress","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodAddress"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress~1init(address:)\/title","op":"replace","value":"initWithAddress:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress~1init(address:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAddress:","kind":"identifier"}],"op":"replace"}]}]}