{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodAddress(cm)rootObjectName","title":"rootObjectName()"},"abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"type":"text","text":" below."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodaddress\/rootobjectname()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodaddress\/rootobjectname()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress\/rootObjectName()"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAddress/rootObjectName()":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentmethodaddress\/rootobjectname()","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress\/rootObjectName()","abstract":[{"type":"text","text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by "},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"type":"text","text":" below."}],"title":"rootObjectName()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","kind":"symbol","type":"topic","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodAddress":{"url":"\/documentation\/stripepayments\/stppaymentmethodaddress","title":"STPPaymentMethodAddress","abstract":[{"text":"The billing address, a property on ","type":"text"},{"code":"STPPaymentMethodBillingDetails","type":"codeVoice"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodAddress","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPPaymentMethodAddress","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodAddress"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"rootObjectName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress~1rootObjectName()\/title","value":"rootObjectName"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress~1rootObjectName()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/title","value":"STPPaymentMethodAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/fragments","value":[{"text":"STPPaymentMethodAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodAddress\/navigatorTitle","value":[{"text":"STPPaymentMethodAddress","kind":"identifier"}]}]}]}