pod 'Stripe', path: '../../../..'
pod 'Stripe/ApplePay', path: '../../../..'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = "YES"
  end
end
