{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appVersionKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"content":[{"inlineContent":[{"type":"text","text":"This is automatically populated by the SDK."}],"type":"paragraph"}],"type":"aside","name":"Note","style":"note"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmalipayoptions\/appversionkey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmalipayoptions\/appversionkey"]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/appVersionKey","interfaceLanguage":"swift"},"abstract":[{"text":"The app version.","type":"text"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"appVersionKey","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"appVersionKey","externalID":"c:@M@StripePayments@objc(cs)STPConfirmAlipayOptions(py)appVersionKey","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appVersionKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmAlipayOptions":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmAlipayOptions","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmAlipayOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpconfirmalipayoptions","abstract":[{"type":"text","text":"Alipay options to pass to `STPConfirmPaymentMethodOptions``"}],"title":"STPConfirmAlipayOptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmAlipayOptions/appVersionKey":{"type":"topic","abstract":[{"type":"text","text":"The app version."}],"navigatorTitle":[{"text":"appVersionKey","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/appVersionKey","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appVersionKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"appVersionKey","url":"\/documentation\/stripepayments\/stpconfirmalipayoptions\/appversionkey","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"appVersionKey","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"appVersionKey","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"appVersionKey"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPConfirmAlipayOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/fragments","op":"replace"},{"value":[{"text":"STPConfirmAlipayOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/navigatorTitle","op":"replace"},{"value":"appVersionKey","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions~1appVersionKey\/title","op":"replace"},{"value":[{"text":"appVersionKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions~1appVersionKey\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}