{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/init"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPConfirmAlipayOptions(im)init","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"title":"init"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmalipayoptions\/init"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmAlipayOptions/init":{"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmalipayoptions\/init","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","abstract":[],"title":"init"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmAlipayOptions":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPConfirmAlipayOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions","navigatorTitle":[{"text":"STPConfirmAlipayOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmalipayoptions","kind":"symbol","role":"symbol","title":"STPConfirmAlipayOptions","abstract":[{"type":"text","text":"Alipay options to pass to `STPConfirmPaymentMethodOptions``"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","title":"StripePayments"}},"variantOverrides":[{"patch":[{"value":"STPConfirmAlipayOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/title"},{"value":[{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/navigatorTitle","value":[{"kind":"identifier","text":"STPConfirmAlipayOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}