{"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmalipayoptions\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconfirmalipayoptions\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","metadata":{"title":"STPFormEncodable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"StripePayments"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/rootObjectName()"],"generated":true,"anchor":"Type-Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/STPFormEncodable-Implementations"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmAlipayOptions/propertyNamesToFormFieldNamesMapping()":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/propertyNamesToFormFieldNamesMapping()","title":"propertyNamesToFormFieldNamesMapping()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"url":"\/documentation\/stripepayments\/stpconfirmalipayoptions\/propertynamestoformfieldnamesmapping()"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmAlipayOptions":{"role":"symbol","abstract":[{"text":"Alipay options to pass to `STPConfirmPaymentMethodOptions``","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions","type":"topic","kind":"symbol","title":"STPConfirmAlipayOptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"url":"\/documentation\/stripepayments\/stpconfirmalipayoptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmAlipayOptions/rootObjectName()":{"url":"\/documentation\/stripepayments\/stpconfirmalipayoptions\/rootobjectname()","abstract":[],"kind":"symbol","title":"rootObjectName()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/rootObjectName()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmAlipayOptions\/rootObjectName()"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"propertyNamesToFormFieldNamesMapping","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions~1propertyNamesToFormFieldNamesMapping()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions~1propertyNamesToFormFieldNamesMapping()\/fragments"},{"value":"STPConfirmAlipayOptions","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/title"},{"value":[{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/fragments"},{"value":[{"kind":"identifier","text":"STPConfirmAlipayOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions\/navigatorTitle"},{"value":"rootObjectName","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions~1rootObjectName()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmAlipayOptions~1rootObjectName()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}