{"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSourceCardDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceCardDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPSource(py)cardDetails","navigatorTitle":[{"text":"cardDetails","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"symbolKind":"property","title":"cardDetails"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceCardDetails","text":"STPSourceCardDetails"},{"kind":"text","text":"? { get }"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/cardDetails","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"If this is a card source, this property provides typed access to the","type":"text"},{"text":" ","type":"text"},{"text":"contents of the ","type":"text"},{"type":"codeVoice","code":"details"},{"text":" dictionary.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpsource\/carddetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsource\/carddetails"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/cardDetails":{"url":"\/documentation\/stripepayments\/stpsource\/carddetails","navigatorTitle":[{"kind":"identifier","text":"cardDetails"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/cardDetails","kind":"symbol","title":"cardDetails","abstract":[{"type":"text","text":"If this is a card source, this property provides typed access to the"},{"text":" ","type":"text"},{"text":"contents of the ","type":"text"},{"type":"codeVoice","code":"details"},{"text":" dictionary.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceCardDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceCardDetails"},{"kind":"text","text":"?"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceCardDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceCardDetails"}],"navigatorTitle":[{"kind":"identifier","text":"STPSourceCardDetails"}],"type":"topic","url":"\/documentation\/stripepayments\/stpsourcecarddetails","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails","title":"STPSourceCardDetails","role":"symbol","abstract":[{"type":"text","text":"This class provides typed access to the contents of an STPSource "},{"type":"codeVoice","code":"details"},{"type":"text","text":" "},{"type":"text","text":"dictionary for card sources."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","navigatorTitle":[{"text":"STPSource","kind":"identifier"}],"title":"STPSource","abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"url":"\/documentation\/stripepayments\/stpsource","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cardDetails"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cardDetails","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceCardDetails","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceCardDetails","text":"STPSourceCardDetails"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cardDetails"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1cardDetails\/title","op":"replace","value":"cardDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1cardDetails\/fragments","op":"replace","value":[{"text":"cardDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/title","op":"replace","value":"STPSourceCardDetails"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/fragments","op":"replace","value":[{"text":"STPSourceCardDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceCardDetails\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSourceCardDetails"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","op":"replace","value":"STPSource"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSource"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSource"}]}]}]}