{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"flow","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceFlow","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPSource(py)flow","navigatorTitle":[{"text":"flow","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}],"title":"flow"},"abstract":[{"text":"The authentication flow of the source.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsource\/flow"]},{"paths":["\/documentation\/stripepayments\/stpsource\/flow"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"flow","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSourceFlow","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow"},{"text":" { get }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/flow","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceFlow":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSourceFlow"}],"role":"symbol","abstract":[{"text":"Authentication flows for a Source","type":"text"}],"navigatorTitle":[{"text":"STPSourceFlow","kind":"identifier"}],"title":"STPSourceFlow","url":"\/documentation\/stripepayments\/stpsourceflow"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/flow":{"url":"\/documentation\/stripepayments\/stpsource\/flow","title":"flow","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/flow","navigatorTitle":[{"kind":"identifier","text":"flow"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPSourceFlow","preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow"}],"abstract":[{"text":"The authentication flow of the source.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"role":"symbol","kind":"symbol","abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"title":"STPSource","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsource"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"flow","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"flow","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceFlow","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceFlow","kind":"typeIdentifier","text":"STPSourceFlow"},{"kind":"text","text":" "},{"kind":"identifier","text":"flow"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/title","value":"STPSourceFlow"},{"op":"replace","value":[{"kind":"identifier","text":"STPSourceFlow"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceFlow\/navigatorTitle","value":[{"text":"STPSourceFlow","kind":"identifier"}]},{"value":"flow","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1flow\/title","op":"replace"},{"value":[{"text":"flow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1flow\/fragments"},{"op":"replace","value":"STPSource","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","value":[{"kind":"identifier","text":"STPSource"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","value":[{"kind":"identifier","text":"STPSource"}],"op":"replace"}]}]}
