{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"modules":[{"name":"StripePayments"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@StripePayments@objc(cs)STPSource(im)isEqual:"},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/isEqual(_:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":":nodoc:"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpsource\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsource\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/isEqual(_:)":{"url":"\/documentation\/stripepayments\/stpsource\/isequal(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/isEqual(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","abstract":[{"text":":nodoc:","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"kind":"symbol","abstract":[{"type":"text","text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpsource","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPSource"}],"type":"topic","title":"STPSource","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","navigatorTitle":[{"kind":"identifier","text":"STPSource"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"value":"STPSource","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPSource"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","value":[{"kind":"identifier","text":"STPSource"}],"op":"replace"}]}]}