{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsource\/receiver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsource\/receiver"]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiver"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceReceiver","text":"STPSourceReceiver","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"receiver","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"receiver","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSource(py)receiver"},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/receiver","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"receiver","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSourceReceiver","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceReceiver","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Information related to the receiver flow. Present if the source’s flow","type":"text"},{"text":" ","type":"text"},{"text":"is receiver.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/receiver":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"receiver"},{"text":": ","kind":"text"},{"text":"STPSourceReceiver","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceReceiver"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/receiver","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"receiver"}],"url":"\/documentation\/stripepayments\/stpsource\/receiver","title":"receiver","abstract":[{"text":"Information related to the receiver flow. Present if the source’s flow","type":"text"},{"text":" ","type":"text"},{"text":"is receiver.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceReceiver":{"url":"\/documentation\/stripepayments\/stpsourcereceiver","title":"STPSourceReceiver","navigatorTitle":[{"text":"STPSourceReceiver","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceReceiver","kind":"identifier"}],"abstract":[{"type":"text","text":"Information related to a source’s receiver flow."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"title":"STPSource","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSource","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","url":"\/documentation\/stripepayments\/stpsource","navigatorTitle":[{"text":"STPSource","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"receiver"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"receiver","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceReceiver","text":"STPSourceReceiver","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceReceiver"},{"kind":"text","text":" * "},{"kind":"identifier","text":"receiver"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1receiver\/title","value":"receiver","op":"replace"},{"op":"replace","value":[{"text":"receiver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1receiver\/fragments"},{"op":"replace","value":"STPSourceReceiver","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver\/title"},{"value":[{"kind":"identifier","text":"STPSourceReceiver"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceReceiver\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","op":"replace","value":"STPSource"},{"value":[{"text":"STPSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
