{"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"sepaDebitDetails"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sepaDebitDetails","kind":"identifier"},{"kind":"text","text":": "},{"text":"STPSourceSEPADebitDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails"},{"text":"?","kind":"text"}],"externalID":"c:@M@StripePayments@objc(cs)STPSource(py)sepaDebitDetails","modules":[{"name":"StripePayments"}],"title":"sepaDebitDetails","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/sepaDebitDetails","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sepaDebitDetails","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","text":"STPSourceSEPADebitDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails"},{"text":"? { get }","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsource\/sepadebitdetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsource\/sepadebitdetails"]}],"abstract":[{"type":"text","text":"If this is a SEPA Debit source, this property provides typed access to the"},{"text":" ","type":"text"},{"text":"contents of the ","type":"text"},{"type":"codeVoice","code":"details"},{"type":"text","text":" dictionary."}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/sepaDebitDetails":{"role":"symbol","abstract":[{"type":"text","text":"If this is a SEPA Debit source, this property provides typed access to the"},{"type":"text","text":" "},{"text":"contents of the ","type":"text"},{"type":"codeVoice","code":"details"},{"type":"text","text":" dictionary."}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/sepaDebitDetails","url":"\/documentation\/stripepayments\/stpsource\/sepadebitdetails","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sepaDebitDetails"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceSEPADebitDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sepaDebitDetails","kind":"identifier"}],"title":"sepaDebitDetails","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceSEPADebitDetails":{"navigatorTitle":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceSEPADebitDetails"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","url":"\/documentation\/stripepayments\/stpsourcesepadebitdetails","abstract":[{"text":"This class provides typed access to the contents of an STPSource ","type":"text"},{"code":"details","type":"codeVoice"},{"type":"text","text":" "},{"text":"dictionary for SEPA Debit sources.","type":"text"}],"title":"STPSourceSEPADebitDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"title":"STPSource","url":"\/documentation\/stripepayments\/stpsource","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sepaDebitDetails","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"sepaDebitDetails","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceSEPADebitDetails","text":"STPSourceSEPADebitDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceSEPADebitDetails","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"sepaDebitDetails","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1sepaDebitDetails\/title","op":"replace","value":"sepaDebitDetails"},{"value":[{"text":"sepaDebitDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1sepaDebitDetails\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/title","op":"replace","value":"STPSourceSEPADebitDetails"},{"value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/fragments"},{"value":[{"text":"STPSourceSEPADebitDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceSEPADebitDetails\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","value":"STPSource","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPSource"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","op":"replace","value":[{"text":"STPSource","kind":"identifier"}]}]}]}