{"sections":[],"abstract":[{"type":"text","text":"The status of the source."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","text":"STPSourceStatus","preciseIdentifier":"c:@M@StripePayments@E@STPSourceStatus"},{"kind":"text","text":" { get }"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/status"},"variants":[{"paths":["\/documentation\/stripepayments\/stpsource\/status"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsource\/status"]}],"metadata":{"navigatorTitle":[{"text":"status","kind":"identifier"}],"title":"status","externalID":"c:@M@StripePayments@objc(cs)STPSource(py)status","role":"symbol","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceStatus","kind":"typeIdentifier","text":"STPSourceStatus"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"navigatorTitle":[{"text":"STPSource","kind":"identifier"}],"kind":"symbol","title":"STPSource","abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","url":"\/documentation\/stripepayments\/stpsource"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceStatus":{"url":"\/documentation\/stripepayments\/stpsourcestatus","abstract":[{"type":"text","text":"Status types for a Source"}],"title":"STPSourceStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPSourceStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus","kind":"symbol","navigatorTitle":[{"text":"STPSourceStatus","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/status":{"type":"topic","abstract":[{"text":"The status of the source.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"title":"status","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/status","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPSourceStatus","text":"STPSourceStatus","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/status"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"status"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"status"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceStatus","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceStatus"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"STPSource","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title"},{"op":"replace","value":[{"text":"STPSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments"},{"op":"replace","value":"STPSourceStatus","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/title"},{"op":"replace","value":[{"text":"STPSourceStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1status\/title","value":"status"},{"value":[{"kind":"identifier","text":"status"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1status\/fragments","op":"replace"}]}]}
