{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/usage"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"usage"},{"text":": ","kind":"text"},{"text":"STPSourceUsage","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage"},{"text":" { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceUsage","preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage"}],"navigatorTitle":[{"text":"usage","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"usage","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@objc(cs)STPSource(py)usage"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Whether this source should be reusable or not.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsource\/usage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsource\/usage"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/usage":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"usage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPSourceUsage","preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage"}],"kind":"symbol","navigatorTitle":[{"text":"usage","kind":"identifier"}],"abstract":[{"text":"Whether this source should be reusable or not.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsource\/usage","title":"usage","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/usage","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"title":"STPSource","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSource","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource","url":"\/documentation\/stripepayments\/stpsource","navigatorTitle":[{"text":"STPSource","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceUsage":{"abstract":[{"text":"Usage types for a Source","type":"text"}],"title":"STPSourceUsage","navigatorTitle":[{"kind":"identifier","text":"STPSourceUsage"}],"url":"\/documentation\/stripepayments\/stpsourceusage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceUsage"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"usage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"usage"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPSourceUsage","text":"STPSourceUsage","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceUsage"},{"kind":"text","text":" "},{"text":"usage","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1usage\/title","value":"usage","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1usage\/fragments","op":"replace","value":[{"kind":"identifier","text":"usage"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","value":"STPSource","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","value":[{"kind":"identifier","text":"STPSource"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/title","op":"replace","value":"STPSourceUsage"},{"op":"replace","value":[{"text":"STPSourceUsage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceUsage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
