{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/weChatPayDetails"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"abstract":[{"text":"If this is a WeChat Pay source, this property provides typed access to the","type":"text"},{"text":" ","type":"text"},{"text":"contents of the ","type":"text"},{"code":"details","type":"codeVoice"},{"text":" dictionary.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPSource(py)weChatPayDetails","title":"weChatPayDetails","modules":[{"name":"StripePayments"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"weChatPayDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceWeChatPayDetails","text":"STPSourceWeChatPayDetails","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"weChatPayDetails"}]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpsource\/wechatpaydetails"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpsource\/wechatpaydetails"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"weChatPayDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPSourceWeChatPayDetails","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceWeChatPayDetails","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceWeChatPayDetails":{"title":"STPSourceWeChatPayDetails","url":"\/documentation\/stripepayments\/stpsourcewechatpaydetails","abstract":[{"type":"text","text":"Details of a WeChat Pay Source."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceWeChatPayDetails"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceWeChatPayDetails"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","type":"topic","title":"StripePayments","url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/weChatPayDetails":{"navigatorTitle":[{"kind":"identifier","text":"weChatPayDetails"}],"abstract":[{"text":"If this is a WeChat Pay source, this property provides typed access to the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"contents of the "},{"type":"codeVoice","code":"details"},{"text":" dictionary.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsource\/wechatpaydetails","title":"weChatPayDetails","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"weChatPayDetails"},{"text":": ","kind":"text"},{"text":"STPSourceWeChatPayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceWeChatPayDetails","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/weChatPayDetails","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"title":"STPSource","url":"\/documentation\/stripepayments\/stpsource","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"weChatPayDetails","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"weChatPayDetails","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceWeChatPayDetails","kind":"typeIdentifier","text":"STPSourceWeChatPayDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceWeChatPayDetails"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"weChatPayDetails"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"STPSourceWeChatPayDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/fragments","value":[{"kind":"identifier","text":"STPSourceWeChatPayDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceWeChatPayDetails\/navigatorTitle","value":[{"text":"STPSourceWeChatPayDetails","kind":"identifier"}]},{"value":"weChatPayDetails","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1weChatPayDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1weChatPayDetails\/fragments","value":[{"text":"weChatPayDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","value":"STPSource","op":"replace"},{"value":[{"kind":"identifier","text":"STPSource"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments"},{"value":[{"kind":"identifier","text":"STPSource"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}