{"metadata":{"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType@STPPaymentMethodUSBankAccountTypeChecking","symbolKind":"case","title":"STPPaymentMethodUSBankAccountType.checking","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"checking"}],"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountTypeChecking","kind":"identifier"}],"role":"symbol","roleHeading":"Case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/checking"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"checking"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/checking"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/checking"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Bank account type is checking","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType","kind":"symbol","title":"STPPaymentMethodUSBankAccountType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Account type","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType/checking":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/checking","kind":"symbol","abstract":[{"text":"Bank account type is checking","type":"text"}],"title":"STPPaymentMethodUSBankAccountType.checking","type":"topic","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/checking","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountTypeChecking","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checking","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentMethodUSBankAccountTypeChecking","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountTypeChecking"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountTypeChecking"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/title","value":"STPPaymentMethodUSBankAccountType","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType~1checking\/title","value":"STPPaymentMethodUSBankAccountTypeChecking","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType~1checking\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountTypeChecking"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}