{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/CustomStringConvertible-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType"]]},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","modules":[{"name":"StripePayments"}],"roleHeading":"API Collection"},"kind":"article","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/description"],"title":"Instance Properties","generated":true}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType","kind":"symbol","title":"STPPaymentMethodUSBankAccountType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Account type","type":"text"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","kind":"symbol","type":"topic","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType/description":{"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"type":"topic","title":"description","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"STPPaymentMethodUSBankAccountType","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/title","op":"replace"},{"value":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/fragments","op":"replace"},{"value":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}