{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"savings","kind":"identifier"}]}]}],"sections":[],"abstract":[{"type":"text","text":"Bank account type is savings"}],"metadata":{"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountTypeSavings","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType@STPPaymentMethodUSBankAccountTypeSavings","symbolKind":"case","role":"symbol","title":"STPPaymentMethodUSBankAccountType.savings","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"savings","kind":"identifier"}],"roleHeading":"Case"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/savings"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/savings"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/savings","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"title":"STPPaymentMethodUSBankAccountType","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype","abstract":[{"type":"text","text":"Account type"}],"navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType/savings":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/savings","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountTypeSavings","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/savings","title":"STPPaymentMethodUSBankAccountType.savings","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"savings","kind":"identifier"}],"abstract":[{"type":"text","text":"Bank account type is savings"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPPaymentMethodUSBankAccountTypeSavings","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountTypeSavings"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPPaymentMethodUSBankAccountTypeSavings","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/title","op":"replace","value":"STPPaymentMethodUSBankAccountType"},{"value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/fragments"},{"value":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType~1savings\/title","value":"STPPaymentMethodUSBankAccountTypeSavings","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType~1savings\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountTypeSavings","kind":"identifier"}]}]}]}