{"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/unknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/unknown","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"text":"STPPaymentMethodUSBankAccountTypeUnknown","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"StripePayments"}],"title":"STPPaymentMethodUSBankAccountType.unknown","externalID":"c:@M@StripePayments@E@STPPaymentMethodUSBankAccountType@STPPaymentMethodUSBankAccountTypeUnknown","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType"]]},"abstract":[{"text":"This is an unknown type that’s been added since the SDK","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"was last updated."},{"text":" ","type":"text"},{"type":"text","text":"Update your SDK, or use the "},{"code":"allResponseFields","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"for custom handling."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType/unknown":{"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype\/unknown","type":"topic","abstract":[{"type":"text","text":"This is an unknown type that’s been added since the SDK"},{"type":"text","text":" "},{"text":"was last updated.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Update your SDK, or use the "},{"type":"codeVoice","code":"allResponseFields"},{"type":"text","text":" "},{"type":"text","text":"for custom handling."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType\/unknown","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountTypeUnknown"}],"kind":"symbol","role":"symbol","title":"STPPaymentMethodUSBankAccountType.unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodUSBankAccountType":{"abstract":[{"type":"text","text":"Account type"}],"title":"STPPaymentMethodUSBankAccountType","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodUSBankAccountType","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}],"url":"\/documentation\/stripepayments\/stppaymentmethodusbankaccounttype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"STPPaymentMethodUSBankAccountTypeUnknown","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountTypeUnknown"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPPaymentMethodUSBankAccountTypeUnknown","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"STPPaymentMethodUSBankAccountTypeUnknown","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType~1unknown\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType~1unknown\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountTypeUnknown"}],"op":"replace"},{"value":"STPPaymentMethodUSBankAccountType","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/fragments","value":[{"text":"STPPaymentMethodUSBankAccountType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodUSBankAccountType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodUSBankAccountType"}]}]}]}