{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterror\/code"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterror\/code"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentError\/code","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For some errors that could be handled programmatically, a short string indicating the error code reported."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"code","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentLastPaymentError(py)code","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"code"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentError"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentError":{"role":"symbol","title":"STPPaymentIntentLastPaymentError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentLastPaymentError"}],"abstract":[{"type":"text","text":"A value for "},{"type":"codeVoice","code":"code"},{"type":"text","text":" indicating the provided payment method failed authentication.\/\/\/ The payment error encountered in the previous PaymentIntent confirmation."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentError"}],"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterror"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentError/code":{"role":"symbol","title":"code","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"For some errors that could be handled programmatically, a short string indicating the error code reported."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentError\/code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"code"}],"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterror\/code"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"code"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"code"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"code"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError\/title","value":"STPPaymentIntentLastPaymentError"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError~1code\/title","value":"code"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError~1code\/fragments","value":[{"kind":"identifier","text":"code"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
