{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"docURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"aside","name":"See Also","style":"note","content":[{"inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Error-Codes","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentError\/docURL"},"kind":"symbol","metadata":{"modules":[{"name":"StripePayments"}],"title":"docURL","navigatorTitle":[{"kind":"identifier","text":"docURL"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"docURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntentLastPaymentError(py)docURL","role":"symbol","symbolKind":"property"},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterror\/docurl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentlastpaymenterror\/docurl"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentError"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"A URL to more information about the error code reported."}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentError/docURL":{"title":"docURL","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentError\/docURL","kind":"symbol","abstract":[{"text":"A URL to more information about the error code reported.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"docURL"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"docURL"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterror\/docurl","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentLastPaymentError":{"url":"\/documentation\/stripepayments\/stppaymentintentlastpaymenterror","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentLastPaymentError","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentIntentLastPaymentError","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentLastPaymentError","kind":"symbol","abstract":[{"text":"A value for ","type":"text"},{"type":"codeVoice","code":"code"},{"text":" indicating the provided payment method failed authentication.\/\/\/ The payment error encountered in the previous PaymentIntent confirmation.","type":"text"}],"title":"STPPaymentIntentLastPaymentError","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"docURL","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"docURL","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"docURL"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"docURL","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError~1docURL\/title","op":"replace"},{"value":[{"kind":"identifier","text":"docURL"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError~1docURL\/fragments","op":"replace"},{"value":"STPPaymentIntentLastPaymentError","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError\/title","op":"replace"},{"value":[{"text":"STPPaymentIntentLastPaymentError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPPaymentIntentLastPaymentError"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentLastPaymentError\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}