{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"The Stripe SDK will modally present additional view controllers on top"},{"type":"text","text":" "},{"type":"text","text":"of the "},{"code":"authenticationPresentingViewController","type":"codeVoice"},{"type":"text","text":" when required for user"},{"text":" ","type":"text"},{"type":"text","text":"authentication, like in the Challenge Flow for 3DS2 transactions."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationPresentingViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationPresentingViewController()"},"variants":[{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationpresentingviewcontroller()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationpresentingviewcontroller()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationPresentingViewController","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"title":"authenticationPresentingViewController()","navigatorTitle":[{"kind":"identifier","text":"authenticationPresentingViewController"}],"roleHeading":"Instance Method","required":true,"modules":[{"name":"StripePayments"}],"symbolKind":"method","externalID":"c:@M@StripePayments@objc(pl)STPAuthenticationContext(im)authenticationPresentingViewController","role":"symbol"},"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/authenticationPresentingViewController()":{"abstract":[{"type":"text","text":"The Stripe SDK will modally present additional view controllers on top"},{"text":" ","type":"text"},{"type":"text","text":"of the "},{"type":"codeVoice","code":"authenticationPresentingViewController"},{"type":"text","text":" when required for user"},{"text":" ","type":"text"},{"type":"text","text":"authentication, like in the Challenge Flow for 3DS2 transactions."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationPresentingViewController()","url":"\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationpresentingviewcontroller()","type":"topic","role":"symbol","title":"authenticationPresentingViewController()","required":true,"navigatorTitle":[{"text":"authenticationPresentingViewController","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticationPresentingViewController","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"url":"\/documentation\/stripepayments\/stpauthenticationcontext","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPAuthenticationContext","kind":"identifier"}],"title":"STPAuthenticationContext","kind":"symbol","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","type":"topic","navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"authenticationPresentingViewController","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"authenticationPresentingViewController"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"authenticationPresentingViewController","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1authenticationPresentingViewController()\/title","value":"authenticationPresentingViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1authenticationPresentingViewController()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"authenticationPresentingViewController"}]},{"value":"STPAuthenticationContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}