{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":"(authenticationContextWillDismissViewController:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationContextWillDismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Method","role":"symbol","title":"authenticationContextWillDismiss(_:)","externalID":"c:@M@StripePayments@objc(pl)STPAuthenticationContext(im)authenticationContextWillDismissViewController:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationContextWillDismiss"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"authenticationContextWillDismissViewController:"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationcontextwilldismiss(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationcontextwilldismiss(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextWillDismiss(_:)"},"abstract":[{"text":"This method is called when an authentication UIViewController is about to be dismissed.","type":"text"},{"text":" ","type":"text"},{"text":"Implement this method to prepare your UI for the authentication view controller to be dismissed. For example,","type":"text"},{"text":" ","type":"text"},{"text":"if you requested authentication while displaying an STPBankSelectionViewController, you may want to hide","type":"text"},{"text":" ","type":"text"},{"text":"it to return the user to your desired view controller.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/authenticationContextWillDismiss(_:)":{"title":"authenticationContextWillDismiss(_:)","abstract":[{"type":"text","text":"This method is called when an authentication UIViewController is about to be dismissed."},{"type":"text","text":" "},{"type":"text","text":"Implement this method to prepare your UI for the authentication view controller to be dismissed. For example,"},{"type":"text","text":" "},{"type":"text","text":"if you requested authentication while displaying an STPBankSelectionViewController, you may want to hide"},{"type":"text","text":" "},{"type":"text","text":"it to return the user to your desired view controller."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationContextWillDismiss"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"authenticationContextWillDismissViewController:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextWillDismiss(_:)","url":"\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationcontextwilldismiss(_:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"type":"topic","title":"STPAuthenticationContext","kind":"symbol","url":"\/documentation\/stripepayments\/stpauthenticationcontext","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAuthenticationContext","kind":"identifier"}],"abstract":[{"code":"STPAuthenticationContext","type":"codeVoice"},{"text":" provides information required to present authentication challenges","type":"text"},{"text":" ","type":"text"},{"text":"to a user.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"authenticationContextWillDismissViewController:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationContextWillDismissViewController:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"authenticationContextWillDismissViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"authenticationContextWillDismissViewController:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1authenticationContextWillDismiss(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"authenticationContextWillDismissViewController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1authenticationContextWillDismiss(_:)\/fragments"},{"value":"STPAuthenticationContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle"}]}]}