{"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextDidDismissViewController:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationcontextdiddismissviewcontroller:"]}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticationContextDidDismissViewController:"}],"navigatorTitle":[{"text":"authenticationContextDidDismissViewController:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"StripePayments"}],"role":"symbol","title":"authenticationContextDidDismissViewController:","symbolKind":"method","externalID":"c:@M@StripePayments@objc(pl)STPAuthenticationContext(im)authenticationContextDidDismissViewController:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"authenticationContextDidDismissViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"]]},"abstract":[{"type":"text","text":"This method is called when an authentication UIViewController has been dismissed."},{"type":"text","text":" "},{"type":"text","text":"Implement this method to have your UI respond to the authentication view controller to being dismissed. For example,"},{"type":"text","text":" "},{"text":"if you requested authentication while displaying an STPBankSelectionViewController, you may want to hide","type":"text"},{"text":" ","type":"text"},{"text":"it to return the user to your desired view controller.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"STPAuthenticationContext","kind":"identifier"}],"title":"STPAuthenticationContext","url":"\/documentation\/stripepayments\/stpauthenticationcontext","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","role":"symbol","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"text":" provides information required to present authentication challenges","type":"text"},{"type":"text","text":" "},{"text":"to a user.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/authenticationContextDidDismissViewController:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"authenticationContextDidDismissViewController:"}],"title":"authenticationContextDidDismissViewController:","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/authenticationContextDidDismissViewController:","type":"topic","url":"\/documentation\/stripepayments\/stpauthenticationcontext\/authenticationcontextdiddismissviewcontroller:","navigatorTitle":[{"text":"authenticationContextDidDismissViewController:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"This method is called when an authentication UIViewController has been dismissed.","type":"text"},{"type":"text","text":" "},{"text":"Implement this method to have your UI respond to the authentication view controller to being dismissed. For example,","type":"text"},{"type":"text","text":" "},{"text":"if you requested authentication while displaying an STPBankSelectionViewController, you may want to hide","type":"text"},{"text":" ","type":"text"},{"text":"it to return the user to your desired view controller.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPAuthenticationContext","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title"},{"value":[{"text":"STPAuthenticationContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPAuthenticationContext"}]}]}]}