{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/configuresafariviewcontroller(_:)"]},{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/configuresafariviewcontroller(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"]]},"metadata":{"title":"configureSafariViewController(_:)","navigatorTitle":[{"text":"configureSafariViewController:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"StripePayments"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configureSafariViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@StripePayments@objc(pl)STPAuthenticationContext(im)configureSafariViewController:"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/configureSafariViewController(_:)"},"abstract":[{"type":"text","text":"This method is called before presenting an SFSafariViewController for web-based authentication."},{"text":" ","type":"text"},{"text":"Implement this method to configure the ","type":"text"},{"code":"SFSafariViewController","type":"codeVoice"},{"type":"text","text":" instance, e.g. "},{"type":"codeVoice","code":"viewController.preferredBarTintColor = MyBarTintColor"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configureSafariViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SFSafariViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"text":")","kind":"text"}]}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"name":"Note","type":"aside","content":[{"inlineContent":[{"text":"Setting the ","type":"text"},{"type":"codeVoice","code":"delegate"},{"text":" property has no effect.","type":"text"}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPAuthenticationContext"}],"url":"\/documentation\/stripepayments\/stpauthenticationcontext","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","abstract":[{"type":"codeVoice","code":"STPAuthenticationContext"},{"text":" provides information required to present authentication challenges","type":"text"},{"type":"text","text":" "},{"text":"to a user.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPAuthenticationContext"}],"title":"STPAuthenticationContext"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/configureSafariViewController(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureSafariViewController"},{"text":"(","kind":"text"},{"text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/stripepayments\/stpauthenticationcontext\/configuresafariviewcontroller(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/configureSafariViewController(_:)","abstract":[{"type":"text","text":"This method is called before presenting an SFSafariViewController for web-based authentication."},{"type":"text","text":" "},{"type":"text","text":"Implement this method to configure the "},{"type":"codeVoice","code":"SFSafariViewController"},{"type":"text","text":" instance, e.g. "},{"code":"viewController.preferredBarTintColor = MyBarTintColor","type":"codeVoice"}],"navigatorTitle":[{"kind":"identifier","text":"configureSafariViewController:"}],"title":"configureSafariViewController(_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"configureSafariViewController:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"configureSafariViewController:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"configureSafariViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title","value":"STPAuthenticationContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPAuthenticationContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1configureSafariViewController(_:)\/title","value":"configureSafariViewController:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1configureSafariViewController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"configureSafariViewController:","kind":"identifier"}],"op":"replace"}]}]}