{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(pl)STPAuthenticationContext(im)prepareAuthenticationContextForPresentation:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresentation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripePayments12STPVoidBlocka","kind":"typeIdentifier","text":"STPVoidBlock"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"}],"title":"prepare(forPresentation:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"@preconcurrency","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":"(prepareAuthenticationContextForPresentation:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepare","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forPresentation","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ","kind":"text"},{"text":"STPVoidBlock","preciseIdentifier":"s:14StripePayments12STPVoidBlocka","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPVoidBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"code":"STPPaymentHandler","type":"codeVoice"},{"type":"text","text":" will not proceed until "},{"code":"completion","type":"codeVoice"},{"type":"text","text":" is called."}]}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/prepare(forPresentation:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/prepare(forpresentation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpauthenticationcontext\/prepare(forpresentation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext"]]},"abstract":[{"text":"This method is called before presenting a UIViewController for authentication.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext/prepare(forPresentation:)":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext\/prepare(forPresentation:)","abstract":[{"text":"This method is called before presenting a UIViewController for authentication.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forPresentation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripePayments12STPVoidBlocka"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"prepareAuthenticationContextForPresentation:"}],"url":"\/documentation\/stripepayments\/stpauthenticationcontext\/prepare(forpresentation:)","title":"prepare(forPresentation:)","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAuthenticationContext":{"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAuthenticationContext","kind":"identifier"}],"navigatorTitle":[{"text":"STPAuthenticationContext","kind":"identifier"}],"role":"symbol","title":"STPAuthenticationContext","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAuthenticationContext","url":"\/documentation\/stripepayments\/stpauthenticationcontext","abstract":[{"code":"STPAuthenticationContext","type":"codeVoice"},{"type":"text","text":" provides information required to present authentication challenges"},{"type":"text","text":" "},{"type":"text","text":"to a user."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPVoidBlock":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPVoidBlock","abstract":[{"text":"An empty block, called with no arguments, returning nothing.","type":"text"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPVoidBlock"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPVoidBlock"}],"url":"\/documentation\/stripepayments\/stpvoidblock","title":"STPVoidBlock","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"prepareAuthenticationContextForPresentation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"prepareAuthenticationContextForPresentation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)()) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1prepare(forPresentation:)\/title","value":"prepareAuthenticationContextForPresentation:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext~1prepare(forPresentation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareAuthenticationContextForPresentation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/title","value":"STPAuthenticationContext"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/fragments","value":[{"text":"STPAuthenticationContext","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAuthenticationContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPAuthenticationContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}