{"abstract":[{"type":"text","text":"An icon representing Diners Club."}],"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPImageLibrary(cm)dinersClubCardImage","title":"dinersClubCardImage()","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"dinersClubCardImage","kind":"identifier"}],"modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dinersClubCardImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/dinersClubCardImage()"},"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpimagelibrary\/dinersclubcardimage()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpimagelibrary\/dinersclubcardimage()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dinersClubCardImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"kind":"symbol","role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","title":"StripePaymentsUI","type":"topic","url":"\/documentation\/stripepaymentsui"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary":{"navigatorTitle":[{"kind":"identifier","text":"STPImageLibrary"}],"kind":"symbol","title":"STPImageLibrary","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary","abstract":[{"type":"text","text":"This class lets you access card icons used by the Stripe SDK. All icons are 32 x 20 points."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPImageLibrary","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepaymentsui\/stpimagelibrary"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/dinersClubCardImage()":{"abstract":[{"text":"An icon representing Diners Club.","type":"text"}],"url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/dinersclubcardimage()","role":"symbol","navigatorTitle":[{"text":"dinersClubCardImage","kind":"identifier"}],"type":"topic","title":"dinersClubCardImage()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"dinersClubCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/dinersClubCardImage()","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"dinersClubCardImage","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"dinersClubCardImage"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"dinersClubCardImage"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/title","op":"replace","value":"STPImageLibrary"},{"value":[{"text":"STPImageLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/navigatorTitle","value":[{"text":"STPImageLibrary","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1dinersClubCardImage()\/title","value":"dinersClubCardImage"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1dinersClubCardImage()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"dinersClubCardImage"}]}]}]}