{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/templatedBrandImage(for:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(templatedBrandImageForCardBrand:) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatedBrandImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"}]}]}],"abstract":[{"text":"This returns the appropriate icon for the specified card brand as a","type":"text"},{"text":" ","type":"text"},{"text":"single color template that can be tinted","type":"text"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpimagelibrary\/templatedbrandimage(for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpimagelibrary\/templatedbrandimage(for:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"templatedBrandImageForCardBrand:"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPImageLibrary(cm)templatedBrandImageForCardBrand:","modules":[{"name":"StripePaymentsUI"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatedBrandImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"title":"templatedBrandImage(for:)","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/templatedBrandImage(for:)":{"navigatorTitle":[{"kind":"identifier","text":"templatedBrandImageForCardBrand:"}],"url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/templatedbrandimage(for:)","abstract":[{"type":"text","text":"This returns the appropriate icon for the specified card brand as a"},{"text":" ","type":"text"},{"text":"single color template that can be tinted","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"templatedBrandImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier","text":"STPCardBrand"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/templatedBrandImage(for:)","type":"topic","title":"templatedBrandImage(for:)","kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"role":"collection","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","url":"\/documentation\/stripepaymentsui","title":"StripePaymentsUI","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/stripepaymentsui\/stpimagelibrary","abstract":[{"text":"This class lets you access card icons used by the Stripe SDK. All icons are 32 x 20 points.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPImageLibrary","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary","title":"STPImageLibrary","navigatorTitle":[{"text":"STPImageLibrary","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"templatedBrandImageForCardBrand:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"templatedBrandImageForCardBrand:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"templatedBrandImageForCardBrand:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"text":") ","kind":"text"},{"text":"brand","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"templatedBrandImageForCardBrand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1templatedBrandImage(for:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"templatedBrandImageForCardBrand:"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1templatedBrandImage(for:)\/fragments"},{"value":"STPImageLibrary","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/title"},{"value":[{"kind":"identifier","text":"STPImageLibrary"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/fragments"},{"value":[{"kind":"identifier","text":"STPImageLibrary"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/navigatorTitle"}]}]}