{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardparams\/address"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardparams\/address"]}],"kind":"symbol","abstract":[{"text":"The cardholder’s address.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCardParams(py)address","title":"address","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"address","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/address","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"Setting "},{"code":"address","type":"codeVoice"},{"type":"text","text":" to a new value will also change the "},{"code":"name","type":"codeVoice"},{"type":"text","text":" property to"},{"type":"text","text":" "},{"type":"text","text":"be the value of "},{"code":"address.name","type":"codeVoice"},{"type":"text","text":". However, changing "},{"code":"address.name","type":"codeVoice"},{"type":"text","text":" directly will"},{"text":" ","type":"text"},{"text":"not* change ","type":"text"},{"code":"name","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAddress":{"kind":"symbol","abstract":[{"type":"text","text":"STPAddress Contains an address as represented by the Stripe API."}],"type":"topic","title":"STPAddress","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAddress","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"STPAddress","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpaddress","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/address":{"title":"address","kind":"symbol","type":"topic","abstract":[{"text":"The cardholder’s address.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/address","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"address","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPAddress","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress"}],"navigatorTitle":[{"text":"address","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripepayments\/stpcardparams\/address"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"title":"STPCardParams","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","navigatorTitle":[{"kind":"identifier","text":"STPCardParams"}],"type":"topic","url":"\/documentation\/stripepayments\/stpcardparams","abstract":[{"text":"Representation of a user’s credit card details. You can assemble these with","type":"text"},{"text":" ","type":"text"},{"text":"information that your user enters and then create Stripe tokens with them using","type":"text"},{"text":" ","type":"text"},{"text":"an STPAPIClient.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"address"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"address"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAddress","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPAddress","text":"STPAddress"},{"kind":"text","text":" * "},{"kind":"identifier","text":"address"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/title","value":"STPAddress"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/fragments","value":[{"text":"STPAddress","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAddress\/navigatorTitle","value":[{"kind":"identifier","text":"STPAddress"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1address\/title","value":"address"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1address\/fragments","value":[{"text":"address","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title","value":"STPCardParams"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments","value":[{"text":"STPCardParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardParams"}]}]}]}