{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The country of the cardholder’s address"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressCountry"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressCountry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardparams\/addresscountry"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcardparams\/addresscountry"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@StripePayments@objc(cs)STPCardParams(py)addressCountry","title":"addressCountry","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"addressCountry"}],"role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/addressCountry":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/addressCountry","url":"\/documentation\/stripepayments\/stpcardparams\/addresscountry","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addressCountry"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"addressCountry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The country of the cardholder’s address"}],"kind":"symbol","title":"addressCountry","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"abstract":[{"type":"text","text":"Representation of a user’s credit card details. You can assemble these with"},{"type":"text","text":" "},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"type":"text","text":"an STPAPIClient."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPCardParams"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","title":"STPCardParams","kind":"symbol","url":"\/documentation\/stripepayments\/stpcardparams","navigatorTitle":[{"kind":"identifier","text":"STPCardParams"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","title":"StripePayments","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"addressCountry","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"addressCountry","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"addressCountry"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressCountry\/title","op":"replace","value":"addressCountry"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1addressCountry\/fragments","op":"replace","value":[{"kind":"identifier","text":"addressCountry"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title","op":"replace","value":"STPCardParams"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPCardParams"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle","op":"replace","value":[{"text":"STPCardParams","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}