{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams"]]},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPCardParams(py)currency","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}],"symbolKind":"property","title":"currency","modules":[{"name":"StripePayments"}],"role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/currency","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"currency","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcardparams\/currency"]},{"paths":["\/documentation\/stripepayments\/stpcardparams\/currency"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Three-letter ISO currency code representing the currency paid out to the bank","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"account. This is only applicable when tokenizing debit cards to issue payouts"},{"type":"text","text":" "},{"type":"text","text":"to managed accounts. You should not set it otherwise. The card can then be"},{"type":"text","text":" "},{"text":"used as a transfer destination for funds in this currency.","type":"text"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams/currency":{"title":"currency","role":"symbol","type":"topic","abstract":[{"text":"Three-letter ISO currency code representing the currency paid out to the bank","type":"text"},{"text":" ","type":"text"},{"text":"account. This is only applicable when tokenizing debit cards to issue payouts","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to managed accounts. You should not set it otherwise. The card can then be"},{"type":"text","text":" "},{"text":"used as a transfer destination for funds in this currency.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"currency"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams\/currency","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currency","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/stripepayments\/stpcardparams\/currency","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardParams","navigatorTitle":[{"text":"STPCardParams","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCardParams","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of a user’s credit card details. You can assemble these with"},{"text":" ","type":"text"},{"type":"text","text":"information that your user enters and then create Stripe tokens with them using"},{"type":"text","text":" "},{"text":"an STPAPIClient.","type":"text"}],"type":"topic","title":"STPCardParams","url":"\/documentation\/stripepayments\/stpcardparams","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","url":"\/documentation\/stripepayments"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"currency","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"currency"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"currency"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1currency\/title","value":"currency","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams~1currency\/fragments","value":[{"kind":"identifier","text":"currency"}]},{"value":"STPCardParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/fragments","value":[{"text":"STPCardParams","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardParams\/navigatorTitle","value":[{"text":"STPCardParams","kind":"identifier"}]}]}]}