{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"appId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPConfirmWeChatPayOptions(im)initWithAppId:","title":"init(appId:)","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"initWithAppId:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"text":"Your WeChat-provided application ID. WeChat Pay","type":"text"},{"text":" ","type":"text"},{"text":"uses this as the redirect URL scheme.","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/init(appId:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmwechatpayoptions\/init(appid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmwechatpayoptions\/init(appid:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions"]]},"abstract":[{"type":"text","text":"Initializes STPConfirmWeChatPayOptions"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmWeChatPayOptions":{"abstract":[{"type":"text","text":"WeChat Pay options to pass to `STPConfirmPaymentMethodOptions``"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmWeChatPayOptions","kind":"identifier"}],"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmwechatpayoptions","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions","navigatorTitle":[{"kind":"identifier","text":"STPConfirmWeChatPayOptions"}],"title":"STPConfirmWeChatPayOptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmWeChatPayOptions/init(appId:)":{"type":"topic","title":"init(appId:)","kind":"symbol","navigatorTitle":[{"text":"initWithAppId:","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmwechatpayoptions\/init(appid:)","role":"symbol","abstract":[{"type":"text","text":"Initializes STPConfirmWeChatPayOptions"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"appId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/init(appId:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithAppId:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithAppId:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithAppId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"appId","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"appId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Your WeChat-provided application ID. WeChat Pay"},{"text":" ","type":"text"},{"type":"text","text":"uses this as the redirect URL scheme."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/title","op":"replace","value":"STPConfirmWeChatPayOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/fragments","value":[{"kind":"identifier","text":"STPConfirmWeChatPayOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/navigatorTitle","value":[{"text":"STPConfirmWeChatPayOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions~1init(appId:)\/title","op":"replace","value":"initWithAppId:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAppId:"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions~1init(appId:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}