{"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/rootObjectName()"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmwechatpayoptions\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconfirmwechatpayoptions\/stpformencodable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/STPFormEncodable-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","title":"STPFormEncodable Implementations","role":"collectionGroup","modules":[{"name":"StripePayments"}]},"kind":"article","sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"kind":"symbol","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmWeChatPayOptions":{"abstract":[{"text":"WeChat Pay options to pass to `STPConfirmPaymentMethodOptions``","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPConfirmWeChatPayOptions"}],"role":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpconfirmwechatpayoptions","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConfirmWeChatPayOptions"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions","kind":"symbol","title":"STPConfirmWeChatPayOptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmWeChatPayOptions/propertyNamesToFormFieldNamesMapping()":{"type":"topic","url":"\/documentation\/stripepayments\/stpconfirmwechatpayoptions\/propertynamestoformfieldnamesmapping()","title":"propertyNamesToFormFieldNamesMapping()","kind":"symbol","abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"type":"codeVoice","code":"expMonth"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/propertyNamesToFormFieldNamesMapping()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmWeChatPayOptions/rootObjectName()":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmwechatpayoptions\/rootobjectname()","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/rootObjectName()","abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"text":" below.","type":"text"}],"title":"rootObjectName()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/propertyNamesToFormFieldNamesMapping()","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmWeChatPayOptions\/rootObjectName()"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/title","value":"STPConfirmWeChatPayOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/fragments","value":[{"text":"STPConfirmWeChatPayOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions\/navigatorTitle","value":[{"text":"STPConfirmWeChatPayOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions~1propertyNamesToFormFieldNamesMapping()\/title","value":"propertyNamesToFormFieldNamesMapping"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions~1rootObjectName()\/title","value":"rootObjectName"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmWeChatPayOptions~1rootObjectName()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"rootObjectName","kind":"identifier"}]}]}]}