{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"automatic","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/automatic"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/automatic"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/automatic"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automatic"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod@STPPaymentIntentConfirmationMethodAutomatic","navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethodAutomatic","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Case","title":"STPPaymentIntentConfirmationMethod.automatic"},"kind":"symbol","abstract":[{"text":"Confirmed via secret key","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod":{"title":"STPPaymentIntentConfirmationMethod","abstract":[{"text":"Confirmation methods for a STPPaymentIntent","type":"text"}],"navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","role":"collection","type":"topic","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/automatic":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"automatic"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/automatic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/automatic","role":"symbol","abstract":[{"type":"text","text":"Confirmed via secret key"}],"navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethodAutomatic","kind":"identifier"}],"type":"topic","title":"STPPaymentIntentConfirmationMethod.automatic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentConfirmationMethodAutomatic"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodAutomatic"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodAutomatic"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/title","value":"STPPaymentIntentConfirmationMethod"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/fragments","value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPPaymentIntentConfirmationMethodAutomatic","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1automatic\/title"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodAutomatic"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1automatic\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
