{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/CustomStringConvertible-Implementations"]]},"metadata":{"title":"description","role":"symbol","modules":[{"name":"StripePayments"}],"externalID":"s:14StripePayments34STPPaymentIntentConfirmationMethodO11descriptionSSvp","extendedModule":"StripePayments","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/description"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"text":".","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","title":"StripePayments","url":"\/documentation\/stripepayments","kind":"symbol","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/description":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/description","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/description","role":"symbol","title":"description","abstract":[]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/CustomStringConvertible-Implementations":{"abstract":[],"title":"CustomStringConvertible Implementations","role":"collectionGroup","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/CustomStringConvertible-Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/customstringconvertible-implementations"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"abstract":[{"type":"text","text":"Confirmation methods for a STPPaymentIntent"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod","title":"STPPaymentIntentConfirmationMethod"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/title","value":"STPPaymentIntentConfirmationMethod"},{"value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/navigatorTitle","value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}