{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/Equatable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/equatable-implementations"]}],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"StripePayments"}],"role":"collectionGroup"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Operators","anchor":"Operators","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/!=(_:_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod"]]},"kind":"article","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/!=(_:_:)":{"type":"topic","kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/!=(_:_:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/!=(_:_:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"!=(_:_:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Confirmation methods for a STPPaymentIntent"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","title":"STPPaymentIntentConfirmationMethod","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentIntentConfirmationMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/fragments","op":"replace","value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/navigatorTitle","value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"op":"replace"}]}]}