{"metadata":{"modules":[{"name":"StripePayments"}],"title":"STPPaymentIntentConfirmationMethod.manual","role":"symbol","externalID":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod@STPPaymentIntentConfirmationMethodManual","symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodManual"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"manual"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manual","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Confirmed via publishable key"}],"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/manual"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/manual"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/manual","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod":{"url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod","role":"symbol","abstract":[{"text":"Confirmation methods for a STPPaymentIntent","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","title":"STPPaymentIntentConfirmationMethod","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/manual":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/manual","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"manual","kind":"identifier"}],"abstract":[{"text":"Confirmed via publishable key","type":"text"}],"role":"symbol","title":"STPPaymentIntentConfirmationMethod.manual","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/manual","kind":"symbol","navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethodManual","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","type":"topic","title":"StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntentConfirmationMethodManual"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPPaymentIntentConfirmationMethodManual","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodManual"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"STPPaymentIntentConfirmationMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/title"},{"value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/fragments"},{"value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/navigatorTitle"},{"value":"STPPaymentIntentConfirmationMethodManual","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1manual\/title"},{"value":[{"text":"STPPaymentIntentConfirmationMethodManual","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1manual\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}