{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod"]]},"abstract":[{"text":"Unknown confirmation method","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/unknown"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/unknown"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethodUnknown","kind":"identifier"}],"role":"symbol","symbolKind":"case","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod@STPPaymentIntentConfirmationMethodUnknown","title":"STPPaymentIntentConfirmationMethod.unknown","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"roleHeading":"Case"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","type":"topic","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"title":"StripePayments","role":"collection"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod/unknown":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod\/unknown","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodUnknown"}],"type":"topic","title":"STPPaymentIntentConfirmationMethod.unknown","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"}],"role":"symbol","abstract":[{"type":"text","text":"Unknown confirmation method"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod\/unknown"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntentConfirmationMethod":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntentConfirmationMethod"}],"url":"\/documentation\/stripepayments\/stppaymentintentconfirmationmethod","abstract":[{"text":"Confirmation methods for a STPPaymentIntent","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntentConfirmationMethod","role":"symbol","navigatorTitle":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"title":"STPPaymentIntentConfirmationMethod"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPPaymentIntentConfirmationMethodUnknown","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntentConfirmationMethodUnknown"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPPaymentIntentConfirmationMethodUnknown","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentIntentConfirmationMethodUnknown","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1unknown\/title"},{"op":"replace","value":[{"text":"STPPaymentIntentConfirmationMethodUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod~1unknown\/fragments"},{"op":"replace","value":"STPPaymentIntentConfirmationMethod","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/title"},{"op":"replace","value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/fragments"},{"op":"replace","value":[{"text":"STPPaymentIntentConfirmationMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntentConfirmationMethod\/navigatorTitle"}]}]}