{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGiropayParams\/init"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Method","title":"init","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodGiropayParams(im)init","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodgiropayparams\/init"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGiropayParams"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodGiropayParams/init":{"kind":"symbol","abstract":[],"role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"url":"\/documentation\/stripepayments\/stppaymentmethodgiropayparams\/init","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGiropayParams\/init","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodGiropayParams":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodGiropayParams","title":"STPPaymentMethodGiropayParams","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodGiropayParams"}],"url":"\/documentation\/stripepayments\/stppaymentmethodgiropayparams","abstract":[{"type":"text","text":"An object representing parameters used to create a giropay Payment Method"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPPaymentMethodGiropayParams"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"STPPaymentMethodGiropayParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGiropayParams\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGiropayParams\/fragments","value":[{"text":"STPPaymentMethodGiropayParams","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodGiropayParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodGiropayParams\/navigatorTitle"}]}]}