{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions\/confirmationNumber","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmkonbinioptions\/confirmationnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmkonbinioptions\/confirmationnumber"]}],"abstract":[{"type":"text","text":"An optional 10 to 11 digit numeric-only string determining the confirmation code at applicable convenience stores."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}]}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"confirmationNumber"}],"modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPConfirmKonbiniOptions(py)confirmationNumber","title":"confirmationNumber"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmKonbiniOptions":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions","url":"\/documentation\/stripepayments\/stpconfirmkonbinioptions","type":"topic","title":"STPConfirmKonbiniOptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmKonbiniOptions","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmKonbiniOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Options for a Konbini Payment Methods during PaymentIntent confirmation","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmKonbiniOptions/confirmationNumber":{"navigatorTitle":[{"text":"confirmationNumber","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions\/confirmationNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmationNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"confirmationNumber","role":"symbol","abstract":[{"type":"text","text":"An optional 10 to 11 digit numeric-only string determining the confirmation code at applicable convenience stores."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmkonbinioptions\/confirmationnumber"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"confirmationNumber"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"confirmationNumber","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"confirmationNumber","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"STPConfirmKonbiniOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions\/fragments","value":[{"kind":"identifier","text":"STPConfirmKonbiniOptions"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions\/navigatorTitle","value":[{"kind":"identifier","text":"STPConfirmKonbiniOptions"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions~1confirmationNumber\/title","value":"confirmationNumber"},{"value":[{"text":"confirmationNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions~1confirmationNumber\/fragments","op":"replace"}]}]}