{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions\/STPFormEncodable-Implementations"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rootObjectName","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpconfirmkonbinioptions\/rootobjectname()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconfirmkonbinioptions\/rootobjectname()"]}],"metadata":{"roleHeading":"Type Method","extendedModule":"StripePayments","symbolKind":"method","modules":[{"name":"StripePayments"}],"role":"symbol","title":"rootObjectName()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rootObjectName"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"rootObjectName","kind":"identifier"}],"externalID":"c:@CM@StripePayments@objc(cs)STPConfirmKonbiniOptions(cm)rootObjectName"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"type":"text","text":" below."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions\/rootObjectName()"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","url":"\/documentation\/stripepayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"type":"topic","role":"collection","title":"StripePayments"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmKonbiniOptions/rootObjectName()":{"navigatorTitle":[{"kind":"identifier","text":"rootObjectName"}],"title":"rootObjectName()","kind":"symbol","url":"\/documentation\/stripepayments\/stpconfirmkonbinioptions\/rootobjectname()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rootObjectName","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions\/rootObjectName()","abstract":[{"text":"The root object name to be used when converting this object to a form-encoded string. For example, if this returns “card”, then the form-encoded output will resemble “card[foo]=bar” (where ‘foo’ and ‘bar’ are specified by ","type":"text"},{"type":"codeVoice","code":"propertyNamesToFormFieldNamesMapping"},{"text":" below.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmKonbiniOptions":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPConfirmKonbiniOptions"}],"url":"\/documentation\/stripepayments\/stpconfirmkonbinioptions","abstract":[{"type":"text","text":"Options for a Konbini Payment Methods during PaymentIntent confirmation"}],"title":"STPConfirmKonbiniOptions","navigatorTitle":[{"text":"STPConfirmKonbiniOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmKonbiniOptions/STPFormEncodable-Implementations":{"title":"STPFormEncodable Implementations","url":"\/documentation\/stripepayments\/stpconfirmkonbinioptions\/stpformencodable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmKonbiniOptions\/STPFormEncodable-Implementations","role":"collectionGroup","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"rootObjectName","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"rootObjectName"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"rootObjectName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions~1rootObjectName()\/title","op":"replace","value":"rootObjectName"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions~1rootObjectName()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"rootObjectName"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions\/title","value":"STPConfirmKonbiniOptions"},{"value":[{"kind":"identifier","text":"STPConfirmKonbiniOptions"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmKonbiniOptions\/navigatorTitle","value":[{"text":"STPConfirmKonbiniOptions","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}