{"abstract":[{"type":"text","text":":nodoc:"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodsofort\/description"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodsofort\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofort\/description"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofort"]]},"metadata":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"title":"description","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodSofort(py)description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSofort/description":{"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"text":":nodoc:","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofort\/description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodsofort\/description","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodSofort":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodSofort","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodSofort","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodSofort"}],"title":"STPPaymentMethodSofort","url":"\/documentation\/stripepayments\/stppaymentmethodsofort","abstract":[{"text":"A Sofort Payment Method.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"kind":"symbol","url":"\/documentation\/stripepayments","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"}],"languages":["occ"]}]}},{"value":"description","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofort~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofort~1description\/fragments"},{"op":"replace","value":"STPPaymentMethodSofort","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofort\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodSofort\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodSofort"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
