{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The raw JSON response used to create the object. This can be useful for accessing"},{"type":"text","text":" "},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"metadata":{"modules":[{"name":"StripePayments"}],"title":"allResponseFields","role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24(py)allResponseFields","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/stripepayments\/stppaymentmethodprzelewy24\/allresponsefields"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodprzelewy24\/allresponsefields"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24\/allResponseFields","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"] { get }"}]}],"kind":"declarations"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"role":"collection","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","title":"StripePayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPrzelewy24/allResponseFields":{"title":"allResponseFields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"allResponseFields","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentmethodprzelewy24\/allresponsefields","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24\/allResponseFields","abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"text":" ","type":"text"},{"text":"fields that haven’t yet been made into native properties in the SDK.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPrzelewy24":{"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodPrzelewy24"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentMethodPrzelewy24"}],"abstract":[{"type":"text","text":"A Przelewy24 Payment Method."}],"url":"\/documentation\/stripepayments\/stppaymentmethodprzelewy24","role":"symbol","type":"topic","title":"STPPaymentMethodPrzelewy24","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"allResponseFields","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"allResponseFields","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSDictionary","preciseIdentifier":"c:objc(cs)NSDictionary","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24~1allResponseFields\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/title","value":"STPPaymentMethodPrzelewy24"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodPrzelewy24"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentMethodPrzelewy24"}]}]}]}