{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}]}],"name":"response"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The object represented by the JSON dictionary, or nil if the object"},{"type":"text","text":" "},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24\/decodedObject(fromAPIResponse:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24"]]},"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"code":"NSDictionary","type":"codeVoice"},{"type":"text","text":") into an instance of the class."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodprzelewy24\/decodedobject(fromapiresponse:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodprzelewy24\/decodedobject(fromapiresponse:)"]}],"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodPrzelewy24(cm)decodedObjectFromAPIResponse:","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"modules":[{"name":"StripePayments"}],"role":"symbol","title":"decodedObject(fromAPIResponse:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> `Self`"},{"kind":"text","text":"?"}],"symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPrzelewy24/decodedObject(fromAPIResponse:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24\/decodedObject(fromAPIResponse:)","abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"type":"text","text":" "},{"type":"text","text":"an "},{"type":"codeVoice","code":"NSDictionary"},{"type":"text","text":") into an instance of the class."}],"navigatorTitle":[{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stppaymentmethodprzelewy24\/decodedobject(fromapiresponse:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodPrzelewy24":{"role":"symbol","title":"STPPaymentMethodPrzelewy24","url":"\/documentation\/stripepayments\/stppaymentmethodprzelewy24","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodPrzelewy24","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A Przelewy24 Payment Method."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodPrzelewy24","navigatorTitle":[{"text":"STPPaymentMethodPrzelewy24","kind":"identifier"}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","url":"\/documentation\/stripepayments","type":"topic","abstract":[{"type":"text","text":"The StripePayments module contains bindings for the Stripe Payments API."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The JSON dictionary that represents an object of this type","type":"text"}],"type":"paragraph"}],"name":"response"}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The object represented by the JSON dictionary, or nil if the object"},{"type":"text","text":" "},{"type":"text","text":"could not be decoded (i.e. if one of its "},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}]}]}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24~1decodedObject(fromAPIResponse:)\/title","op":"replace","value":"decodedObjectFromAPIResponse:"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24~1decodedObject(fromAPIResponse:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/title","op":"replace","value":"STPPaymentMethodPrzelewy24"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodPrzelewy24"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodPrzelewy24\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodPrzelewy24"}]}]}]}