{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The JSON dictionary that represents an object of this type"}],"type":"paragraph"}],"name":"response"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"The object represented by the JSON dictionary, or nil if the object","type":"text"},{"type":"text","text":" "},{"text":"could not be decoded (i.e. if one of its ","type":"text"},{"type":"codeVoice","code":"requiredFields"},{"type":"text","text":" is nil)."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/decodedObject(fromAPIResponse:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Type Method","modules":[{"name":"StripePayments"}],"role":"symbol","externalID":"c:@M@StripePayments@objc(cs)STPSourceRedirect(cm)decodedObjectFromAPIResponse:","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"title":"decodedObject(fromAPIResponse:)","navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},"abstract":[{"type":"text","text":"Parses an response from the Stripe API (in JSON format; represented as"},{"text":" ","type":"text"},{"text":"an ","type":"text"},{"code":"NSDictionary","type":"codeVoice"},{"type":"text","text":") into an instance of the class."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceredirect\/decodedobject(fromapiresponse:)"]},{"paths":["\/documentation\/stripepayments\/stpsourceredirect\/decodedobject(fromapiresponse:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect"]]},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect":{"role":"symbol","type":"topic","kind":"symbol","title":"STPSourceRedirect","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect","abstract":[{"text":"Information related to a source’s redirect flow.","type":"text"}],"navigatorTitle":[{"text":"STPSourceRedirect","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPSourceRedirect","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceredirect"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect/decodedObject(fromAPIResponse:)":{"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"url":"\/documentation\/stripepayments\/stpsourceredirect\/decodedobject(fromapiresponse:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodedObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromAPIResponse","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> `Self`","kind":"text"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect\/decodedObject(fromAPIResponse:)","title":"decodedObject(fromAPIResponse:)"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","url":"\/documentation\/stripepayments","title":"StripePayments","role":"collection","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"decodedObjectFromAPIResponse:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/title","value":"STPSourceRedirect"},{"value":[{"kind":"identifier","text":"STPSourceRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/navigatorTitle","value":[{"text":"STPSourceRedirect","kind":"identifier"}]},{"value":"decodedObjectFromAPIResponse:","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1decodedObject(fromAPIResponse:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect~1decodedObject(fromAPIResponse:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}]}]}]}