{"variants":[{"paths":["\/documentation\/stripepayments\/stpcard\/addressstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcard\/addressstate"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addressState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"addressState","kind":"identifier"}],"title":"addressState","externalID":"c:@M@StripePayments@objc(cs)STPCard(py)addressState","roleHeading":"Instance Property","role":"symbol","platforms":[],"modules":[{"name":"StripePayments"}]},"kind":"symbol","sections":[],"abstract":[{"text":"The state of the cardholder’s address","type":"text"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use address.state"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"addressState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressState"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/addressState":{"kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcard\/addressstate","abstract":[{"text":"The state of the cardholder’s address","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"addressState","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"addressState","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/addressState","title":"addressState"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}],"url":"\/documentation\/stripepayments","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard":{"title":"STPCard","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCard","kind":"identifier"}],"navigatorTitle":[{"text":"STPCard","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of a user’s credit card details that have been tokenized with"},{"text":" ","type":"text"},{"text":"the Stripe API","type":"text"}],"url":"\/documentation\/stripepayments\/stpcard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard","type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"addressState"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"addressState"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"addressState","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"addressState","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressState\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1addressState\/fragments","value":[{"kind":"identifier","text":"addressState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/title","value":"STPCard"},{"value":[{"text":"STPCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/navigatorTitle","value":[{"text":"STPCard","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}